using Dapper;
using Sigov.Application.Bloco6;
using Sigov.Infrastructure.Persistence.Dapper;

namespace Sigov.Infrastructure.Bloco6;

public abstract class Bloco6RepositoryBase
{
 protected readonly NpgsqlConnectionFactory Factory;
 protected Bloco6RepositoryBase(NpgsqlConnectionFactory factory)=>Factory=factory;
 public async Task<Bloco6DashboardDto> DashboardAsync(Bloco6Context c,string tabela,CancellationToken ct)
 {
  var sql=tabela switch { "compras_solicitacao"=>"select count(*)::int Total,count(*) filter(where status not in ('CONCLUIDA','CANCELADA'))::int Pendentes,coalesce(sum(valor_total),0) ValorTotal from sigov.bloco6_compras_solicitacao where tenant_id=@TenantId and not is_deleted", "contrato"=>"select count(*)::int Total,count(*) filter(where status in ('RASCUNHO','VIGENTE','SUSPENSO'))::int Pendentes,coalesce(sum(valor_atual),0) ValorTotal from sigov.contrato where tenant_id=@TenantId and not is_deleted", _=>throw new ArgumentOutOfRangeException(nameof(tabela)) };
  await using var db=Factory.CreateConnection();var row=await db.QuerySingleAsync<DashboardRow>(new CommandDefinition(sql,c,cancellationToken:ct));return new(row.Total,row.Pendentes,row.ValorTotal,Array.Empty<Bloco6RegistroDto>());
 }
 protected sealed class DashboardRow { public int Total { get; set; } public int Pendentes { get; set; } public decimal ValorTotal { get; set; } }
}
public sealed class ComprasRepository:NpgsqlRepositoryBase,IComprasRepository
{
 public ComprasRepository(NpgsqlConnectionFactory f):base(f){}
 public async Task<Guid>CriarSolicitacaoAsync(Bloco6Context c,ComprasCriarSolicitacaoRequest r,CancellationToken ct){await using var db=Factory.CreateConnection();await db.OpenAsync(ct);await using var tx=await db.BeginTransactionAsync(ct);var id=Guid.NewGuid();var total=r.Itens.Sum(x=>x.Quantidade*(x.ValorEstimado??0));const string h="insert into sigov.bloco6_compras_solicitacao(id,tenant_id,entidade_id,exercicio_id,objeto,status,valor_estimado,valor_total,correlation_id,created_by,updated_by) values(@id,@TenantId,@EntidadeId,@ExercicioId,@Objeto,'RASCUNHO',@total,@total,@CorrelationId,@UsuarioId,@UsuarioId)";await db.ExecuteAsync(new CommandDefinition(h,new{id,c.TenantId,c.EntidadeId,c.ExercicioId,r.Objeto,total,c.CorrelationId,c.UsuarioId},tx,cancellationToken:ct));foreach(var i in r.Itens)await db.ExecuteAsync(new CommandDefinition("insert into sigov.bloco6_compras_solicitacao_item(tenant_id,solicitacao_id,descricao,valor_unitario,valor_total,dados,correlation_id,created_by,updated_by) values(@TenantId,@id,@Descricao,@ValorEstimado,@valor,jsonb_build_object('unidade',@Unidade,'quantidade',@Quantidade),@CorrelationId,@UsuarioId,@UsuarioId)",new{c.TenantId,id,i.Descricao,i.ValorEstimado,valor=i.Quantidade*(i.ValorEstimado??0),i.Unidade,i.Quantidade,c.CorrelationId,c.UsuarioId},tx,cancellationToken:ct));await tx.CommitAsync(ct);return id;}
 public async Task<Guid>GerarOrdemAsync(Bloco6Context c,ComprasGerarOrdemCompraRequest r,CancellationToken ct){await using var db=Factory.CreateConnection();await db.OpenAsync(ct);await using var tx=await db.BeginTransactionAsync(ct);var status=await db.ExecuteScalarAsync<string?>(new CommandDefinition("select status from sigov.bloco6_compras_processo where tenant_id=@TenantId and id=@ProcessoId and not is_deleted",new{c.TenantId,r.ProcessoId},tx,cancellationToken:ct));if(status!="HOMOLOGADO")throw new InvalidOperationException("Somente processo homologado pode gerar ordem.");var id=Guid.NewGuid();var total=r.Itens.Sum(x=>x.Quantidade*(x.ValorEstimado??0));await db.ExecuteAsync(new CommandDefinition("insert into sigov.bloco6_compras_ordem_compra(id,tenant_id,processo_id,fornecedor_id,status,valor_total,correlation_id,created_by,updated_by) values(@id,@TenantId,@ProcessoId,@FornecedorId,'EMITIDA',@total,@CorrelationId,@UsuarioId,@UsuarioId)",new{id,c.TenantId,r.ProcessoId,r.FornecedorId,total,c.CorrelationId,c.UsuarioId},tx,cancellationToken:ct));if(r.IntegrarFinanceiro)await db.ExecuteAsync(new CommandDefinition("insert into sigov.bloco6_compras_integracao_financeira(tenant_id,processo_id,status,dados,correlation_id,created_by,updated_by) select @TenantId,@id,'PENDENTE',jsonb_build_object('ordemCompraId',@id,'tipo','SOLICITACAO_EMPENHO_PREPARATORIA'),@CorrelationId,@UsuarioId,@UsuarioId where not exists(select 1 from sigov.bloco6_compras_integracao_financeira where tenant_id=@TenantId and dados->>'ordemCompraId'=@id::text and not is_deleted)",new{id,c.TenantId,c.CorrelationId,c.UsuarioId},tx,cancellationToken:ct));await tx.CommitAsync(ct);return id;}
}
public abstract class NpgsqlRepositoryBase:Bloco6RepositoryBase { protected NpgsqlRepositoryBase(NpgsqlConnectionFactory f):base(f){} }
public sealed class ContratosRepository:NpgsqlRepositoryBase,IContratosRepository
{public ContratosRepository(NpgsqlConnectionFactory f):base(f){} public async Task<Guid>CriarContratoAsync(Bloco6Context c,ContratoCriarRequest r,CancellationToken ct){var id=Guid.NewGuid();await using var db=Factory.CreateConnection();const string q="insert into sigov.contrato(id,tenant_id,entidade_id,exercicio_id,fornecedor_id,objeto,status,valor_original,valor_atual,saldo,vigencia_inicio,vigencia_fim,correlation_id,created_by,updated_by) values(@id,@TenantId,@EntidadeId,@ExercicioId,@FornecedorId,@Objeto,'RASCUNHO',@Valor,@Valor,@Valor,@VigenciaInicio,@VigenciaFim,@CorrelationId,@UsuarioId,@UsuarioId)";await db.ExecuteAsync(new CommandDefinition(q,new{id,c.TenantId,c.EntidadeId,c.ExercicioId,r.FornecedorId,r.Objeto,r.Valor,VigenciaInicio=r.VigenciaInicio.ToDateTime(TimeOnly.MinValue),VigenciaFim=r.VigenciaFim.ToDateTime(TimeOnly.MinValue),c.CorrelationId,c.UsuarioId},cancellationToken:ct));return id;} public async Task<Guid>MedirAsync(Bloco6Context c,Guid contratoId,ContratoCriarMedicaoRequest r,CancellationToken ct){var id=Guid.NewGuid();await using var db=Factory.CreateConnection();const string q="insert into sigov.contrato_medicao(id,tenant_id,processo_id,descricao,status,valor_total,correlation_id,created_by,updated_by) select @id,@TenantId,@contratoId,@Descricao,'PENDENTE',@Valor,@CorrelationId,@UsuarioId,@UsuarioId from sigov.contrato where tenant_id=@TenantId and id=@contratoId and status='VIGENTE' and saldo>=@Valor and not is_deleted";var n=await db.ExecuteAsync(new CommandDefinition(q,new{id,c.TenantId,contratoId,r.Descricao,r.Valor,c.CorrelationId,c.UsuarioId},cancellationToken:ct));if(n!=1)throw new InvalidOperationException("Contrato não vigente ou saldo insuficiente.");return id;}}
public sealed class AlmoxarifadoRepository:NpgsqlRepositoryBase,IAlmoxarifadoRepository
{public AlmoxarifadoRepository(NpgsqlConnectionFactory f):base(f){} public async Task<Guid>MovimentarAsync(Bloco6Context c,AlmoxarifadoCriarMovimentoRequest r,CancellationToken ct){await using var db=Factory.CreateConnection();await db.OpenAsync(ct);await using var tx=await db.BeginTransactionAsync(ct);var id=Guid.NewGuid();var tipo=r.Tipo.ToUpperInvariant();var delta=tipo=="ENTRADA"?r.Quantidade:-r.Quantidade;try{var updated=await db.ExecuteAsync(new CommandDefinition("update sigov.almoxarifado_estoque set quantidade=quantidade+@delta,updated_at=now(),updated_by=@UsuarioId,correlation_id=@CorrelationId where tenant_id=@TenantId and almoxarifado_id=@AlmoxarifadoId and item_id=@ItemId and not is_deleted",new{c.TenantId,r.AlmoxarifadoId,r.ItemId,delta,c.CorrelationId,c.UsuarioId},tx,cancellationToken:ct));if(updated==0)await db.ExecuteAsync(new CommandDefinition("insert into sigov.almoxarifado_estoque(tenant_id,almoxarifado_id,item_id,quantidade,correlation_id,created_by,updated_by) values(@TenantId,@AlmoxarifadoId,@ItemId,@delta,@CorrelationId,@UsuarioId,@UsuarioId)",new{c.TenantId,r.AlmoxarifadoId,r.ItemId,delta,c.CorrelationId,c.UsuarioId},tx,cancellationToken:ct));}catch(Exception){await tx.RollbackAsync(ct);throw new InvalidOperationException("Saldo insuficiente para a saída.");}await db.ExecuteAsync(new CommandDefinition("insert into sigov.almoxarifado_movimento(id,tenant_id,tipo,origem_id,destino_id,quantidade,status,dados,correlation_id,created_by,updated_by) values(@id,@TenantId,@tipo,@AlmoxarifadoId,@DestinoId,@Quantidade,'CONCLUIDO',jsonb_build_object('itemId',@ItemId,'justificativa',@Justificativa),@CorrelationId,@UsuarioId,@UsuarioId)",new{id,c.TenantId,tipo,r.AlmoxarifadoId,r.DestinoId,r.Quantidade,r.ItemId,r.Justificativa,c.CorrelationId,c.UsuarioId},tx,cancellationToken:ct));await tx.CommitAsync(ct);return id;}}
public sealed class PatrimonioRepository:NpgsqlRepositoryBase,IPatrimonioRepository
{public PatrimonioRepository(NpgsqlConnectionFactory f):base(f){} public async Task<Guid>CriarBemAsync(Bloco6Context c,PatrimonioCriarBemRequest r,CancellationToken ct){var id=Guid.NewGuid();await using var db=Factory.CreateConnection();const string q="insert into sigov.patrimonio_bem(id,tenant_id,codigo,descricao,status,tombamento,localizacao_id,responsavel_id,contrato_id,dados,correlation_id,created_by,updated_by) values(@id,@TenantId,@Tombamento,@Descricao,'ATIVO',@Tombamento,@LocalizacaoId,@ResponsavelId,@ContratoId,jsonb_build_object('origem','TOMBAMENTO'),@CorrelationId,@UsuarioId,@UsuarioId)";await db.ExecuteAsync(new CommandDefinition(q,new{id,c.TenantId,r.Tombamento,r.Descricao,r.LocalizacaoId,r.ResponsavelId,r.ContratoId,c.CorrelationId,c.UsuarioId},cancellationToken:ct));return id;}}
