using Sigov.Application.Common; using Sigov.Domain.Common;
namespace Sigov.Application.Agro.FeirasMercados;
public sealed record AgroFeiraCreateRequest(string Codigo,string Nome,string Local,string? DiaSemana,string? Horario,decimal? Latitude,decimal? Longitude,string? GeoJson,string Situacao,string? Observacao);
public sealed record AgroFeiraResponse(long Id,long TenantId,long EntidadeId,string Codigo,string Nome,string Local,string Situacao,decimal? Latitude,decimal? Longitude,string? GeoJson,bool Ativo);
public sealed record AgroFeiranteCreateRequest(long FeiraId,long? ProdutorId,long? PessoaId,string NumeroCadastro,string TipoFeirante,string? ProdutosJson,bool Autorizado,DateOnly? ValidadeAutorizacao,string Situacao,string? Observacao);
public sealed record AgroFeiranteResponse(long Id,long TenantId,long EntidadeId,long FeiraId,string NumeroCadastro,string TipoFeirante,bool Autorizado,DateOnly? ValidadeAutorizacao,string Situacao,bool Ativo);
public sealed record AgroBancaFeiraCreateRequest(long FeiraId,long? FeiranteId,string NumeroBanca,string? LocalizacaoDescricao,string? TipoBanca,string Status);
public sealed record AgroBancaFeiraResponse(long Id,long TenantId,long EntidadeId,long FeiraId,long? FeiranteId,string NumeroBanca,string Status,bool Ativo);
public sealed record AgroAutorizacaoFeiraCreateRequest(long FeiraId,long FeiranteId,string Numero,DateOnly? Validade,string Status,string? Observacao);
public sealed record AgroAutorizacaoFeiraResponse(long Id,long TenantId,long EntidadeId,long FeiraId,long FeiranteId,string Numero,DateOnly DataEmissao,DateOnly? Validade,string Status,bool Ativo);
public interface IAgroFeirasRepository{Task<PagedResult<AgroFeiraResponse>> ListarFeirasAsync(long tenantId,long entidadeId,int page,int pageSize,CancellationToken ct);Task<AgroFeiraResponse?> ObterFeiraAsync(long tenantId,long entidadeId,long id,CancellationToken ct);Task<long> CriarFeiraAsync(long tenantId,long entidadeId,long? usuarioId,AgroFeiraCreateRequest r,CancellationToken ct);Task AtualizarFeiraAsync(long tenantId,long entidadeId,long id,long? usuarioId,AgroFeiraCreateRequest r,CancellationToken ct);Task ExcluirFeiraAsync(long tenantId,long entidadeId,long id,long? usuarioId,CancellationToken ct);Task<PagedResult<AgroFeiranteResponse>> ListarFeirantesAsync(long tenantId,long entidadeId,int page,int pageSize,CancellationToken ct);Task<long> CriarFeiranteAsync(long tenantId,long entidadeId,long feiraId,long? usuarioId,AgroFeiranteCreateRequest r,CancellationToken ct);Task AtualizarFeiranteStatusAsync(long tenantId,long entidadeId,long id,string status,bool autorizado,long? usuarioId,CancellationToken ct);Task<PagedResult<AgroBancaFeiraResponse>> ListarBancasAsync(long tenantId,long entidadeId,long feiraId,CancellationToken ct);Task<long> CriarBancaAsync(long tenantId,long entidadeId,long feiraId,long? usuarioId,AgroBancaFeiraCreateRequest r,CancellationToken ct);}
public interface IAgroFeiraService{Task<Result<PagedResult<AgroFeiraResponse>>> ListarAsync(int page,int pageSize,CancellationToken ct);Task<Result<AgroFeiraResponse>> ObterAsync(long id,CancellationToken ct);Task<Result<long>> CriarAsync(AgroFeiraCreateRequest r,CancellationToken ct);Task<Result> AtualizarAsync(long id,AgroFeiraCreateRequest r,CancellationToken ct);Task<Result> ExcluirAsync(long id,CancellationToken ct);} public interface IAgroFeiranteService{Task<Result<PagedResult<AgroFeiranteResponse>>> ListarAsync(int page,int pageSize,CancellationToken ct);Task<Result<long>> CriarAsync(long feiraId,AgroFeiranteCreateRequest r,CancellationToken ct);Task<Result> AtualizarAsync(long id,AgroFeiranteCreateRequest r,CancellationToken ct);Task<Result> AutorizarAsync(long id,CancellationToken ct);Task<Result> SuspenderAsync(long id,CancellationToken ct);Task<Result<PagedResult<AgroBancaFeiraResponse>>> ListarBancasAsync(long feiraId,CancellationToken ct);Task<Result<long>> CriarBancaAsync(long feiraId,AgroBancaFeiraCreateRequest r,CancellationToken ct);} 
