using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Sigov.Api.Contracts;using Sigov.Application.Abstractions;using Sigov.Application.Authorization;using Sigov.Application.Compras;
namespace Sigov.Api.Controllers;
[ApiController,Authorize,Route("api/compras")]
public sealed class ComprasController(IComprasService s,ICurrentTenant tenant,ICurrentUser user,IAuthorizationEvaluator auth):ControllerBase
{
 [HttpGet("dashboard")]public Task<IActionResult> Dashboard(CancellationToken c)=>Run(ComprasPermissoes.Dashboard,()=>s.DashboardAsync(T(),E(),c),c);
 [HttpGet("fornecedores")]public Task<IActionResult> Fornecedores([FromQuery]CompraFiltro f,CancellationToken c)=>Run(ComprasPermissoes.FornecedorVer,()=>s.FornecedoresAsync(T(),E(),f,c),c);[HttpPost("fornecedores")]public Task<IActionResult> Fornecedor(FornecedorInput i,CancellationToken c)=>Run(ComprasPermissoes.FornecedorCriar,()=>s.CriarFornecedorAsync(T(),U(),Trace(),i with{EntidadeId=E()},c),c);
 [HttpGet("solicitacoes")]public Task<IActionResult> Solicitacoes([FromQuery]CompraFiltro f,CancellationToken c)=>Run(ComprasPermissoes.SolicitacaoVer,()=>s.SolicitacoesAsync(T(),E(),f,c),c);[HttpPost("solicitacoes")]public Task<IActionResult> Solicitacao(SolicitacaoInput i,CancellationToken c)=>Run(ComprasPermissoes.SolicitacaoCriar,()=>s.CriarSolicitacaoAsync(T(),U(),Trace(),i with{EntidadeId=E()},c),c);[HttpPost("solicitacoes/{id:long}/{acao}")]public Task<IActionResult> SolStatus(long id,string acao,[FromBody]Motivo? m,CancellationToken c)=>Run(acao=="enviar"?ComprasPermissoes.SolicitacaoCriar:ComprasPermissoes.SolicitacaoAprovar,async()=>{await s.AlterarSolicitacaoAsync(T(),E(),U(),Trace(),id,acao,m?.Justificativa,c);return new{id,acao};},c);
 [HttpGet("processos")]public Task<IActionResult> Processos([FromQuery]CompraFiltro f,CancellationToken c)=>Run(ComprasPermissoes.ProcessoVer,()=>s.ProcessosAsync(T(),E(),f,c),c);[HttpPost("processos")]public Task<IActionResult> Processo(ProcessoInput i,CancellationToken c)=>Run(ComprasPermissoes.ProcessoCriar,()=>s.CriarProcessoAsync(T(),U(),Trace(),i with{EntidadeId=E()},c),c);[HttpPost("processos/{id:long}/avancar-fase")]public Task<IActionResult> Avancar(long id,[FromBody]Fase i,CancellationToken c)=>Run(ComprasPermissoes.ProcessoAvancar,async()=>{await s.AvancarAsync(T(),E(),U(),Trace(),id,i.Status,c);return new{id,i.Status};},c);[HttpPost("processos/{id:long}/cotacoes")]public Task<IActionResult> Cotar(long id,CotacaoInput i,CancellationToken c)=>Run(ComprasPermissoes.CotacaoCriar,()=>s.CotarAsync(T(),E(),U(),Trace(),id,i,c),c);[HttpPost("processos/{id:long}/julgar")]public Task<IActionResult> Julgar(long id,JulgmentoInputCompat i,CancellationToken c)=>Run(ComprasPermissoes.Julgar,async()=>{await s.JulgarAsync(T(),E(),U(),Trace(),id,i,c);return new{id};},c);[HttpPost("processos/{id:long}/homologar")]public Task<IActionResult> Homologar(long id,CancellationToken c)=>Run(ComprasPermissoes.Julgar,async()=>{await s.HomologarAsync(T(),E(),U(),Trace(),id,c);return new{id};},c);
 [HttpPost("contratos")]public Task<IActionResult> Contrato(ContratoInput i,CancellationToken c)=>Run(ComprasPermissoes.ContratoCriar,()=>s.CriarContratoAsync(T(),U(),Trace(),i with{EntidadeId=E()},c),c);[HttpPost("atas")]public Task<IActionResult> Ata(AtaInput i,CancellationToken c)=>Run(ComprasPermissoes.AtaCriar,()=>s.CriarAtaAsync(T(),U(),Trace(),i with{EntidadeId=E()},c),c);
 async Task<IActionResult> Run<T>(string p,Func<Task<T>> f,CancellationToken c){if(!await Allowed(p,c))return Forbid();try{return Ok(ApiResponse<T>.Ok(await f()));}catch(KeyNotFoundException x){return NotFound(ApiResponse<T>.Fail(x.Message));}catch(ArgumentException x){return BadRequest(ApiResponse<T>.Fail(x.Message));}catch(InvalidOperationException x){return Conflict(ApiResponse<T>.Fail(x.Message));}}
 async Task<bool> Allowed(string p,CancellationToken c){var i=p.LastIndexOf('.');return(await auth.EvaluateAsync(new(U(),"compras",p[..i],p[(i+1)..],T(),E(),tenant.ExercicioId,null,null,Trace(),"API_FUNC03"),c)).Permitido;}long T()=>tenant.TenantId??throw new InvalidOperationException("tenant_id obrigatório.");long E()=>tenant.EntidadeId??throw new InvalidOperationException("entidade_id obrigatório.");long U()=>user.UsuarioId??throw new InvalidOperationException("Usuário obrigatório.");string Trace()=>HttpContext.TraceIdentifier;public sealed record Motivo(string? Justificativa);public sealed record Fase(string Status);
}
