using Microsoft.AspNetCore.Mvc;using Sigov.Api.Contracts;using Sigov.Application.Abstractions;using Sigov.Application.Common;using Sigov.Application.Educacao.Avancada;
namespace Sigov.Api.Controllers;
[ApiController,Route("api/educacao/biblioteca")] public sealed class EducacaoBibliotecaController:EducacaoAvancadaControllerBase{readonly IEducacaoBibliotecaService _service;public EducacaoBibliotecaController(IEducacaoBibliotecaService service,ICurrentTenant tenant,ICurrentUser user):base(tenant,user)=>_service=service;
[HttpGet("dashboard")] public async Task<ActionResult<ApiResponse<object>>> Dashboard([FromQuery]EducacaoAvancadaFiltro filtro,CancellationToken ct) => OkResponse<object>(await _service.DashboardAsync(TenantId(),"educacao_biblioteca_acervo",ct));
[HttpGet("acervo")] public async Task<ActionResult<ApiResponse<object>>> Listar1([FromQuery]EducacaoAvancadaFiltro filtro,CancellationToken ct) => OkResponse<object>(await _service.ListarAsync(TenantId(),"educacao_biblioteca_acervo",filtro,ct));
[HttpPost("acervo")] public async Task<ActionResult<ApiResponse<long>>> Criar1(EducacaoAvancadaOperacaoRequest request,CancellationToken ct)=>OkResponse(await _service.CriarAsync(Contexto(),"educacao_biblioteca_acervo",request,ct));
[HttpGet("exemplares")] public async Task<ActionResult<ApiResponse<object>>> Listar2([FromQuery]EducacaoAvancadaFiltro filtro,CancellationToken ct) => OkResponse<object>(await _service.ListarAsync(TenantId(),"educacao_biblioteca_exemplar",filtro,ct));
[HttpPost("exemplares")] public async Task<ActionResult<ApiResponse<long>>> Criar2(EducacaoAvancadaOperacaoRequest request,CancellationToken ct)=>OkResponse(await _service.CriarAsync(Contexto(),"educacao_biblioteca_exemplar",request,ct));
[HttpGet("emprestimos")] public async Task<ActionResult<ApiResponse<object>>> Listar3([FromQuery]EducacaoAvancadaFiltro filtro,CancellationToken ct) => OkResponse<object>(await _service.ListarAsync(TenantId(),"educacao_biblioteca_emprestimo",filtro,ct));
[HttpPost("emprestimos")] public async Task<ActionResult<ApiResponse<long>>> Criar3(EducacaoAvancadaOperacaoRequest request,CancellationToken ct)=>OkResponse(await _service.CriarAsync(Contexto(),"educacao_biblioteca_emprestimo",request,ct));
[HttpGet("reservas")] public async Task<ActionResult<ApiResponse<object>>> Listar4([FromQuery]EducacaoAvancadaFiltro filtro,CancellationToken ct) => OkResponse<object>(await _service.ListarAsync(TenantId(),"educacao_biblioteca_reserva",filtro,ct));
[HttpPost("reservas")] public async Task<ActionResult<ApiResponse<long>>> Criar4(EducacaoAvancadaOperacaoRequest request,CancellationToken ct)=>OkResponse(await _service.CriarAsync(Contexto(),"educacao_biblioteca_reserva",request,ct));
[HttpGet("atrasos")] public async Task<ActionResult<ApiResponse<object>>> Listar5([FromQuery]EducacaoAvancadaFiltro filtro,CancellationToken ct) => OkResponse<object>(await _service.ListarAsync(TenantId(),"educacao_biblioteca_emprestimo",filtro,ct));
[HttpPost("operacoes/{recurso}/{id:long}/status")] public async Task<ActionResult<ApiResponse<bool>>> Status(string recurso,long id,[FromQuery]string status,[FromQuery]string? justificativa,CancellationToken ct)=>OkResponse(await _service.AlterarStatusAsync(Contexto(),recurso,id,status,justificativa,ct));
[HttpGet("relatorios/resumo")] public async Task<ActionResult<ApiResponse<EducacaoAvancadaDashboardDto>>> Resumo(CancellationToken ct)=>OkResponse(await _service.DashboardAsync(TenantId(),"educacao_biblioteca_acervo",ct));
[HttpGet("relatorios/exportar-csv")] public async Task<IActionResult> Csv(CancellationToken ct)=>File(await _service.ExportarCsvAsync(TenantId(),"educacao_biblioteca_acervo",ct),"text/csv","educacao-dados-agregados.csv");}