using Microsoft.AspNetCore.Mvc;using Sigov.Api.Contracts;using Sigov.Application.Abstractions;using Sigov.Application.Common;using Sigov.Application.Educacao.Avancada;
namespace Sigov.Api.Controllers;
[ApiController,Route("api/educacao/transporte")] public sealed class EducacaoTransporteEscolarController:EducacaoAvancadaControllerBase{readonly IEducacaoTransporteEscolarService _service;public EducacaoTransporteEscolarController(IEducacaoTransporteEscolarService service,ICurrentTenant tenant,ICurrentUser user):base(tenant,user)=>_service=service;
[HttpGet("dashboard")] public async Task<ActionResult<ApiResponse<object>>> Dashboard([FromQuery]EducacaoAvancadaFiltro filtro,CancellationToken ct) => OkResponse<object>(await _service.DashboardAsync(TenantId(),"educacao_transporte_rota",ct));
[HttpGet("rotas")] public async Task<ActionResult<ApiResponse<object>>> Listar1([FromQuery]EducacaoAvancadaFiltro filtro,CancellationToken ct) => OkResponse<object>(await _service.ListarAsync(TenantId(),"educacao_transporte_rota",filtro,ct));
[HttpPost("rotas")] public async Task<ActionResult<ApiResponse<long>>> Criar1(EducacaoAvancadaOperacaoRequest request,CancellationToken ct)=>OkResponse(await _service.CriarAsync(Contexto(),"educacao_transporte_rota",request,ct));
[HttpGet("veiculos")] public async Task<ActionResult<ApiResponse<object>>> Listar2([FromQuery]EducacaoAvancadaFiltro filtro,CancellationToken ct) => OkResponse<object>(await _service.ListarAsync(TenantId(),"educacao_transporte_veiculo",filtro,ct));
[HttpPost("veiculos")] public async Task<ActionResult<ApiResponse<long>>> Criar2(EducacaoAvancadaOperacaoRequest request,CancellationToken ct)=>OkResponse(await _service.CriarAsync(Contexto(),"educacao_transporte_veiculo",request,ct));
[HttpGet("motoristas")] public async Task<ActionResult<ApiResponse<object>>> Listar3([FromQuery]EducacaoAvancadaFiltro filtro,CancellationToken ct) => OkResponse<object>(await _service.ListarAsync(TenantId(),"educacao_transporte_motorista",filtro,ct));
[HttpPost("motoristas")] public async Task<ActionResult<ApiResponse<long>>> Criar3(EducacaoAvancadaOperacaoRequest request,CancellationToken ct)=>OkResponse(await _service.CriarAsync(Contexto(),"educacao_transporte_motorista",request,ct));
[HttpGet("viagens")] public async Task<ActionResult<ApiResponse<object>>> Listar4([FromQuery]EducacaoAvancadaFiltro filtro,CancellationToken ct) => OkResponse<object>(await _service.ListarAsync(TenantId(),"educacao_transporte_viagem",filtro,ct));
[HttpPost("viagens")] public async Task<ActionResult<ApiResponse<long>>> Criar4(EducacaoAvancadaOperacaoRequest request,CancellationToken ct)=>OkResponse(await _service.CriarAsync(Contexto(),"educacao_transporte_viagem",request,ct));
[HttpGet("ocorrencias")] public async Task<ActionResult<ApiResponse<object>>> Listar5([FromQuery]EducacaoAvancadaFiltro filtro,CancellationToken ct) => OkResponse<object>(await _service.ListarAsync(TenantId(),"educacao_transporte_ocorrencia",filtro,ct));
[HttpPost("ocorrencias")] public async Task<ActionResult<ApiResponse<long>>> Criar5(EducacaoAvancadaOperacaoRequest request,CancellationToken ct)=>OkResponse(await _service.CriarAsync(Contexto(),"educacao_transporte_ocorrencia",request,ct));
[HttpGet("custos")] public async Task<ActionResult<ApiResponse<object>>> Listar6([FromQuery]EducacaoAvancadaFiltro filtro,CancellationToken ct) => OkResponse<object>(await _service.ListarAsync(TenantId(),"educacao_transporte_custo",filtro,ct));
[HttpPost("custos")] public async Task<ActionResult<ApiResponse<long>>> Criar6(EducacaoAvancadaOperacaoRequest request,CancellationToken ct)=>OkResponse(await _service.CriarAsync(Contexto(),"educacao_transporte_custo",request,ct));
[HttpPost("operacoes/{recurso}/{id:long}/status")] public async Task<ActionResult<ApiResponse<bool>>> Status(string recurso,long id,[FromQuery]string status,[FromQuery]string? justificativa,CancellationToken ct)=>OkResponse(await _service.AlterarStatusAsync(Contexto(),recurso,id,status,justificativa,ct));
[HttpGet("relatorios/resumo")] public async Task<ActionResult<ApiResponse<EducacaoAvancadaDashboardDto>>> Resumo(CancellationToken ct)=>OkResponse(await _service.DashboardAsync(TenantId(),"educacao_transporte_rota",ct));
[HttpGet("relatorios/exportar-csv")] public async Task<IActionResult> Csv(CancellationToken ct)=>File(await _service.ExportarCsvAsync(TenantId(),"educacao_transporte_rota",ct),"text/csv","educacao-dados-agregados.csv");}