using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Sigov.Application.Empresarial;
namespace Sigov.Api.Controllers;
[ApiController,Authorize,Route("api/empresarial/industrial")] public sealed class EmpresarialIndustrialController:ControllerBase { private readonly IEmpresarialService _service; public EmpresarialIndustrialController(IEmpresarialIndustrialService service)=>_service=service;
[HttpGet("dashboard")] public async Task<IActionResult> Dashboard(CancellationToken ct)=>Ok(await _service.DashboardAsync("emp_industrial_ativo",ct));
[HttpGet("ativos")] public async Task<IActionResult> Listar_ativos([FromQuery]int pagina=1,[FromQuery]int tamanho=20,CancellationToken ct=default)=>Ok(await _service.ListarAsync("emp_industrial_ativo",pagina,tamanho,ct));
[HttpPost("ativos")] public async Task<IActionResult> Criar_ativos([FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.CriarAsync("emp_industrial_ativo",request,HttpContext.TraceIdentifier,ct));
[HttpGet("planos-manutencao")] public async Task<IActionResult> Listar_planos_manutencao([FromQuery]int pagina=1,[FromQuery]int tamanho=20,CancellationToken ct=default)=>Ok(await _service.ListarAsync("emp_industrial_plano_manutencao",pagina,tamanho,ct));
[HttpPost("planos-manutencao")] public async Task<IActionResult> Criar_planos_manutencao([FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.CriarAsync("emp_industrial_plano_manutencao",request,HttpContext.TraceIdentifier,ct));
[HttpGet("programadas")] public async Task<IActionResult> Listar_programadas([FromQuery]int pagina=1,[FromQuery]int tamanho=20,CancellationToken ct=default)=>Ok(await _service.ListarAsync("emp_industrial_manutencao_programada",pagina,tamanho,ct));
[HttpPost("programadas")] public async Task<IActionResult> Criar_programadas([FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.CriarAsync("emp_industrial_manutencao_programada",request,HttpContext.TraceIdentifier,ct));
[HttpGet("medidores")] public async Task<IActionResult> Listar_medidores([FromQuery]int pagina=1,[FromQuery]int tamanho=20,CancellationToken ct=default)=>Ok(await _service.ListarAsync("emp_industrial_medidor",pagina,tamanho,ct));
[HttpPost("medidores")] public async Task<IActionResult> Criar_medidores([FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.CriarAsync("emp_industrial_medidor",request,HttpContext.TraceIdentifier,ct));
[HttpGet("paradas")] public async Task<IActionResult> Listar_paradas([FromQuery]int pagina=1,[FromQuery]int tamanho=20,CancellationToken ct=default)=>Ok(await _service.ListarAsync("emp_industrial_parada",pagina,tamanho,ct));
[HttpPost("paradas")] public async Task<IActionResult> Criar_paradas([FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.CriarAsync("emp_industrial_parada",request,HttpContext.TraceIdentifier,ct));
[HttpGet("producao/ordens")] public async Task<IActionResult> Listar_producao_ordens([FromQuery]int pagina=1,[FromQuery]int tamanho=20,CancellationToken ct=default)=>Ok(await _service.ListarAsync("emp_industrial_ordem_producao",pagina,tamanho,ct));
[HttpPost("producao/ordens")] public async Task<IActionResult> Criar_producao_ordens([FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.CriarAsync("emp_industrial_ordem_producao",request,HttpContext.TraceIdentifier,ct));
[HttpGet("qualidade/ocorrencias")] public async Task<IActionResult> Listar_qualidade_ocorrencias([FromQuery]int pagina=1,[FromQuery]int tamanho=20,CancellationToken ct=default)=>Ok(await _service.ListarAsync("emp_industrial_qualidade_ocorrencia",pagina,tamanho,ct));
[HttpPost("qualidade/ocorrencias")] public async Task<IActionResult> Criar_qualidade_ocorrencias([FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.CriarAsync("emp_industrial_qualidade_ocorrencia",request,HttpContext.TraceIdentifier,ct));
[HttpPost("planos-manutencao/{id:long}/gerar-os")] public async Task<IActionResult> Acao0(long id,[FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.StatusAsync("emp_industrial_plano_manutencao",id,"OS_GERADA",request.Justificativa,HttpContext.TraceIdentifier,ct));
[HttpPost("programadas/{id:long}/executar")] public async Task<IActionResult> Acao1(long id,[FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.StatusAsync("emp_industrial_manutencao_programada",id,"EM_EXECUCAO",request.Justificativa,HttpContext.TraceIdentifier,ct));
[HttpPost("programadas/{id:long}/concluir")] public async Task<IActionResult> Acao2(long id,[FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.StatusAsync("emp_industrial_manutencao_programada",id,"CONCLUIDA",request.Justificativa,HttpContext.TraceIdentifier,ct));
[HttpPost("paradas/{id:long}/encerrar")] public async Task<IActionResult> Acao3(long id,[FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.StatusAsync("emp_industrial_parada",id,"ENCERRADA",request.Justificativa,HttpContext.TraceIdentifier,ct));
[HttpGet("relatorios/resumo")] public async Task<IActionResult> Resumo(CancellationToken ct)=>Ok(await _service.DashboardAsync("emp_industrial_ativo",ct));
[HttpGet("relatorios/exportar-csv")] public async Task<IActionResult> Csv(CancellationToken ct){var r=await _service.ListarAsync("emp_industrial_ativo",1,100,ct);var csv="id;codigo;status;titulo\n"+string.Join("\n",r.Value?.Items.Select(x=>$"{x.Id};{x.Codigo};{x.Status};{x.Titulo}")??Array.Empty<string>());return File(System.Text.Encoding.UTF8.GetBytes(csv),"text/csv","industrial.csv");}
}