using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Sigov.Application.Empresarial;
namespace Sigov.Api.Controllers;
[ApiController,Authorize,Route("api/empresarial/os")] public sealed class EmpresarialOrdemServicoController:ControllerBase { private readonly IEmpresarialService _service; public EmpresarialOrdemServicoController(IEmpresarialOrdemServicoService service)=>_service=service;
[HttpGet("dashboard")] public async Task<IActionResult> Dashboard(CancellationToken ct)=>Ok(await _service.DashboardAsync("emp_os_ordem",ct));
[HttpGet("ordens")] public async Task<IActionResult> Listar_ordens([FromQuery]int pagina=1,[FromQuery]int tamanho=20,CancellationToken ct=default)=>Ok(await _service.ListarAsync("emp_os_ordem",pagina,tamanho,ct));
[HttpPost("ordens")] public async Task<IActionResult> Criar_ordens([FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.CriarAsync("emp_os_ordem",request,HttpContext.TraceIdentifier,ct));
[HttpGet("agenda")] public async Task<IActionResult> Listar_agenda([FromQuery]int pagina=1,[FromQuery]int tamanho=20,CancellationToken ct=default)=>Ok(await _service.ListarAsync("emp_os_agendamento",pagina,tamanho,ct));
[HttpPost("agenda")] public async Task<IActionResult> Criar_agenda([FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.CriarAsync("emp_os_agendamento",request,HttpContext.TraceIdentifier,ct));
[HttpGet("sla-vencido")] public async Task<IActionResult> Listar_sla_vencido([FromQuery]int pagina=1,[FromQuery]int tamanho=20,CancellationToken ct=default)=>Ok(await _service.ListarAsync("emp_os_sla",pagina,tamanho,ct));
[HttpPost("sla-vencido")] public async Task<IActionResult> Criar_sla_vencido([FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.CriarAsync("emp_os_sla",request,HttpContext.TraceIdentifier,ct));
[HttpGet("apontamentos")] public async Task<IActionResult> Listar_apontamentos([FromQuery]int pagina=1,[FromQuery]int tamanho=20,CancellationToken ct=default)=>Ok(await _service.ListarAsync("emp_os_apontamento",pagina,tamanho,ct));
[HttpPost("apontamentos")] public async Task<IActionResult> Criar_apontamentos([FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.CriarAsync("emp_os_apontamento",request,HttpContext.TraceIdentifier,ct));
[HttpGet("checklist")] public async Task<IActionResult> Listar_checklist([FromQuery]int pagina=1,[FromQuery]int tamanho=20,CancellationToken ct=default)=>Ok(await _service.ListarAsync("emp_os_checklist",pagina,tamanho,ct));
[HttpPost("checklist")] public async Task<IActionResult> Criar_checklist([FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.CriarAsync("emp_os_checklist",request,HttpContext.TraceIdentifier,ct));
[HttpPost("ordens/{id:long}/agendar")] public async Task<IActionResult> Acao0(long id,[FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.StatusAsync("emp_os_ordem",id,"AGENDADA",request.Justificativa,HttpContext.TraceIdentifier,ct));
[HttpPost("ordens/{id:long}/iniciar")] public async Task<IActionResult> Acao1(long id,[FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.StatusAsync("emp_os_ordem",id,"EM_EXECUCAO",request.Justificativa,HttpContext.TraceIdentifier,ct));
[HttpPost("ordens/{id:long}/pausar")] public async Task<IActionResult> Acao2(long id,[FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.StatusAsync("emp_os_ordem",id,"PAUSADA",request.Justificativa,HttpContext.TraceIdentifier,ct));
[HttpPost("ordens/{id:long}/retomar")] public async Task<IActionResult> Acao3(long id,[FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.StatusAsync("emp_os_ordem",id,"EM_EXECUCAO",request.Justificativa,HttpContext.TraceIdentifier,ct));
[HttpPost("ordens/{id:long}/concluir")] public async Task<IActionResult> Acao4(long id,[FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.StatusAsync("emp_os_ordem",id,"CONCLUIDA",request.Justificativa,HttpContext.TraceIdentifier,ct));
[HttpPost("ordens/{id:long}/cancelar")] public async Task<IActionResult> Acao5(long id,[FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.StatusAsync("emp_os_ordem",id,"CANCELADA",request.Justificativa,HttpContext.TraceIdentifier,ct));
[HttpPost("ordens/{id:long}/consumir-peca")] public async Task<IActionResult> Acao6(long id,[FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.StatusAsync("emp_os_ordem",id,"EM_EXECUCAO",request.Justificativa,HttpContext.TraceIdentifier,ct));
[HttpGet("relatorios/resumo")] public async Task<IActionResult> Resumo(CancellationToken ct)=>Ok(await _service.DashboardAsync("emp_os_ordem",ct));
[HttpGet("relatorios/exportar-csv")] public async Task<IActionResult> Csv(CancellationToken ct){var r=await _service.ListarAsync("emp_os_ordem",1,100,ct);var csv="id;codigo;status;titulo\n"+string.Join("\n",r.Value?.Items.Select(x=>$"{x.Id};{x.Codigo};{x.Status};{x.Titulo}")??Array.Empty<string>());return File(System.Text.Encoding.UTF8.GetBytes(csv),"text/csv","ordemservico.csv");}
}