using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Sigov.Application.Empresarial;
namespace Sigov.Api.Controllers;
[ApiController,Authorize,Route("api/empresarial/estoque")] public sealed class EmpresarialEstoqueController:ControllerBase { private readonly IEmpresarialService _service; public EmpresarialEstoqueController(IEmpresarialEstoqueService service)=>_service=service;
[HttpGet("dashboard")] public async Task<IActionResult> Dashboard(CancellationToken ct)=>Ok(await _service.DashboardAsync("emp_estoque_produto",ct));
[HttpGet("produtos")] public async Task<IActionResult> Listar_produtos([FromQuery]int pagina=1,[FromQuery]int tamanho=20,CancellationToken ct=default)=>Ok(await _service.ListarAsync("emp_estoque_produto",pagina,tamanho,ct));
[HttpPost("produtos")] public async Task<IActionResult> Criar_produtos([FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.CriarAsync("emp_estoque_produto",request,HttpContext.TraceIdentifier,ct));
[HttpGet("almoxarifados")] public async Task<IActionResult> Listar_almoxarifados([FromQuery]int pagina=1,[FromQuery]int tamanho=20,CancellationToken ct=default)=>Ok(await _service.ListarAsync("emp_estoque_almoxarifado",pagina,tamanho,ct));
[HttpPost("almoxarifados")] public async Task<IActionResult> Criar_almoxarifados([FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.CriarAsync("emp_estoque_almoxarifado",request,HttpContext.TraceIdentifier,ct));
[HttpGet("saldos")] public async Task<IActionResult> Listar_saldos([FromQuery]int pagina=1,[FromQuery]int tamanho=20,CancellationToken ct=default)=>Ok(await _service.ListarAsync("emp_estoque_saldo",pagina,tamanho,ct));
[HttpPost("saldos")] public async Task<IActionResult> Criar_saldos([FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.CriarAsync("emp_estoque_saldo",request,HttpContext.TraceIdentifier,ct));
[HttpGet("movimentos")] public async Task<IActionResult> Listar_movimentos([FromQuery]int pagina=1,[FromQuery]int tamanho=20,CancellationToken ct=default)=>Ok(await _service.ListarAsync("emp_estoque_movimento",pagina,tamanho,ct));
[HttpPost("movimentos")] public async Task<IActionResult> Criar_movimentos([FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.CriarAsync("emp_estoque_movimento",request,HttpContext.TraceIdentifier,ct));
[HttpGet("requisicoes")] public async Task<IActionResult> Listar_requisicoes([FromQuery]int pagina=1,[FromQuery]int tamanho=20,CancellationToken ct=default)=>Ok(await _service.ListarAsync("emp_estoque_requisicao",pagina,tamanho,ct));
[HttpPost("requisicoes")] public async Task<IActionResult> Criar_requisicoes([FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.CriarAsync("emp_estoque_requisicao",request,HttpContext.TraceIdentifier,ct));
[HttpGet("inventarios")] public async Task<IActionResult> Listar_inventarios([FromQuery]int pagina=1,[FromQuery]int tamanho=20,CancellationToken ct=default)=>Ok(await _service.ListarAsync("emp_estoque_inventario",pagina,tamanho,ct));
[HttpPost("inventarios")] public async Task<IActionResult> Criar_inventarios([FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.CriarAsync("emp_estoque_inventario",request,HttpContext.TraceIdentifier,ct));
[HttpGet("fornecedores")] public async Task<IActionResult> Listar_fornecedores([FromQuery]int pagina=1,[FromQuery]int tamanho=20,CancellationToken ct=default)=>Ok(await _service.ListarAsync("emp_compras_fornecedor",pagina,tamanho,ct));
[HttpPost("fornecedores")] public async Task<IActionResult> Criar_fornecedores([FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.CriarAsync("emp_compras_fornecedor",request,HttpContext.TraceIdentifier,ct));
[HttpGet("compras")] public async Task<IActionResult> Listar_compras([FromQuery]int pagina=1,[FromQuery]int tamanho=20,CancellationToken ct=default)=>Ok(await _service.ListarAsync("emp_compras_pedido",pagina,tamanho,ct));
[HttpPost("compras")] public async Task<IActionResult> Criar_compras([FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.CriarAsync("emp_compras_pedido",request,HttpContext.TraceIdentifier,ct));
[HttpPost("requisicoes/{id:long}/aprovar")] public async Task<IActionResult> Acao0(long id,[FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.StatusAsync("emp_estoque_requisicao",id,"APROVADA",request.Justificativa,HttpContext.TraceIdentifier,ct));
[HttpPost("requisicoes/{id:long}/baixar")] public async Task<IActionResult> Acao1(long id,[FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.StatusAsync("emp_estoque_requisicao",id,"BAIXADA",request.Justificativa,HttpContext.TraceIdentifier,ct));
[HttpPost("compras/{id:long}/receber")] public async Task<IActionResult> Acao2(long id,[FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.StatusAsync("emp_compras_pedido",id,"RECEBIDO",request.Justificativa,HttpContext.TraceIdentifier,ct));
[HttpGet("relatorios/resumo")] public async Task<IActionResult> Resumo(CancellationToken ct)=>Ok(await _service.DashboardAsync("emp_estoque_produto",ct));
[HttpGet("relatorios/exportar-csv")] public async Task<IActionResult> Csv(CancellationToken ct){var r=await _service.ListarAsync("emp_estoque_produto",1,100,ct);var csv="id;codigo;status;titulo\n"+string.Join("\n",r.Value?.Items.Select(x=>$"{x.Id};{x.Codigo};{x.Status};{x.Titulo}")??Array.Empty<string>());return File(System.Text.Encoding.UTF8.GetBytes(csv),"text/csv","estoque.csv");}
}