using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Sigov.Application.Empresarial;
namespace Sigov.Api.Controllers;
[ApiController,Authorize,Route("api/empresarial/comercial")] public sealed class EmpresarialComercialController:ControllerBase { private readonly IEmpresarialService _service; public EmpresarialComercialController(IEmpresarialComercialService service)=>_service=service;
[HttpGet("dashboard")] public async Task<IActionResult> Dashboard(CancellationToken ct)=>Ok(await _service.DashboardAsync("emp_comercial_cliente",ct));
[HttpGet("clientes")] public async Task<IActionResult> Listar_clientes([FromQuery]int pagina=1,[FromQuery]int tamanho=20,CancellationToken ct=default)=>Ok(await _service.ListarAsync("emp_comercial_cliente",pagina,tamanho,ct));
[HttpPost("clientes")] public async Task<IActionResult> Criar_clientes([FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.CriarAsync("emp_comercial_cliente",request,HttpContext.TraceIdentifier,ct));
[HttpGet("leads")] public async Task<IActionResult> Listar_leads([FromQuery]int pagina=1,[FromQuery]int tamanho=20,CancellationToken ct=default)=>Ok(await _service.ListarAsync("emp_comercial_lead",pagina,tamanho,ct));
[HttpPost("leads")] public async Task<IActionResult> Criar_leads([FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.CriarAsync("emp_comercial_lead",request,HttpContext.TraceIdentifier,ct));
[HttpGet("oportunidades")] public async Task<IActionResult> Listar_oportunidades([FromQuery]int pagina=1,[FromQuery]int tamanho=20,CancellationToken ct=default)=>Ok(await _service.ListarAsync("emp_comercial_oportunidade",pagina,tamanho,ct));
[HttpPost("oportunidades")] public async Task<IActionResult> Criar_oportunidades([FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.CriarAsync("emp_comercial_oportunidade",request,HttpContext.TraceIdentifier,ct));
[HttpGet("propostas")] public async Task<IActionResult> Listar_propostas([FromQuery]int pagina=1,[FromQuery]int tamanho=20,CancellationToken ct=default)=>Ok(await _service.ListarAsync("emp_comercial_proposta",pagina,tamanho,ct));
[HttpPost("propostas")] public async Task<IActionResult> Criar_propostas([FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.CriarAsync("emp_comercial_proposta",request,HttpContext.TraceIdentifier,ct));
[HttpGet("pedidos")] public async Task<IActionResult> Listar_pedidos([FromQuery]int pagina=1,[FromQuery]int tamanho=20,CancellationToken ct=default)=>Ok(await _service.ListarAsync("emp_comercial_pedido",pagina,tamanho,ct));
[HttpPost("pedidos")] public async Task<IActionResult> Criar_pedidos([FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.CriarAsync("emp_comercial_pedido",request,HttpContext.TraceIdentifier,ct));
[HttpGet("tabelas-preco")] public async Task<IActionResult> Listar_tabelas_preco([FromQuery]int pagina=1,[FromQuery]int tamanho=20,CancellationToken ct=default)=>Ok(await _service.ListarAsync("emp_comercial_tabela_preco",pagina,tamanho,ct));
[HttpPost("tabelas-preco")] public async Task<IActionResult> Criar_tabelas_preco([FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.CriarAsync("emp_comercial_tabela_preco",request,HttpContext.TraceIdentifier,ct));
[HttpGet("atividades")] public async Task<IActionResult> Listar_atividades([FromQuery]int pagina=1,[FromQuery]int tamanho=20,CancellationToken ct=default)=>Ok(await _service.ListarAsync("emp_comercial_atividade",pagina,tamanho,ct));
[HttpPost("atividades")] public async Task<IActionResult> Criar_atividades([FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.CriarAsync("emp_comercial_atividade",request,HttpContext.TraceIdentifier,ct));
[HttpPost("leads/{id:long}/converter-oportunidade")] public async Task<IActionResult> Acao0(long id,[FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.StatusAsync("emp_comercial_lead",id,"QUALIFICADO",request.Justificativa,HttpContext.TraceIdentifier,ct));
[HttpPost("oportunidades/{id:long}/mover-etapa")] public async Task<IActionResult> Acao1(long id,[FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.StatusAsync("emp_comercial_oportunidade",id,"EM_NEGOCIACAO",request.Justificativa,HttpContext.TraceIdentifier,ct));
[HttpPost("propostas/{id:long}/aprovar")] public async Task<IActionResult> Acao2(long id,[FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.StatusAsync("emp_comercial_proposta",id,"APROVADA",request.Justificativa,HttpContext.TraceIdentifier,ct));
[HttpPost("propostas/{id:long}/reprovar")] public async Task<IActionResult> Acao3(long id,[FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.StatusAsync("emp_comercial_proposta",id,"REPROVADA",request.Justificativa,HttpContext.TraceIdentifier,ct));
[HttpPost("propostas/{id:long}/gerar-pedido")] public async Task<IActionResult> Acao4(long id,[FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.StatusAsync("emp_comercial_proposta",id,"PEDIDO_GERADO",request.Justificativa,HttpContext.TraceIdentifier,ct));
[HttpPost("pedidos/{id:long}/confirmar")] public async Task<IActionResult> Acao5(long id,[FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.StatusAsync("emp_comercial_pedido",id,"CONFIRMADO",request.Justificativa,HttpContext.TraceIdentifier,ct));
[HttpPost("pedidos/{id:long}/cancelar")] public async Task<IActionResult> Acao6(long id,[FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.StatusAsync("emp_comercial_pedido",id,"CANCELADO",request.Justificativa,HttpContext.TraceIdentifier,ct));
[HttpPost("pedidos/{id:long}/gerar-os")] public async Task<IActionResult> Acao7(long id,[FromBody]EmpresarialOperacaoRequest request,CancellationToken ct)=>Ok(await _service.StatusAsync("emp_comercial_pedido",id,"OS_GERADA",request.Justificativa,HttpContext.TraceIdentifier,ct));
[HttpGet("relatorios/resumo")] public async Task<IActionResult> Resumo(CancellationToken ct)=>Ok(await _service.DashboardAsync("emp_comercial_cliente",ct));
[HttpGet("relatorios/exportar-csv")] public async Task<IActionResult> Csv(CancellationToken ct){var r=await _service.ListarAsync("emp_comercial_cliente",1,100,ct);var csv="id;codigo;status;titulo\n"+string.Join("\n",r.Value?.Items.Select(x=>$"{x.Id};{x.Codigo};{x.Status};{x.Titulo}")??Array.Empty<string>());return File(System.Text.Encoding.UTF8.GetBytes(csv),"text/csv","comercial.csv");}
}