using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Sigov.Api.Contracts;using Sigov.Application.Abstractions;using Sigov.Application.Authorization;using Sigov.Application.Frotas;
namespace Sigov.Api.Controllers;
[ApiController,Authorize,Route("api/frotas")]
public sealed class FrotasController(IFrotasService s,ICurrentTenant tenant,ICurrentUser user,IAuthorizationEvaluator auth):ControllerBase
{
 [HttpGet("dashboard")]public Task<IActionResult> Dashboard(CancellationToken c)=>Run(FrotasPermissoes.Dashboard,()=>s.DashboardAsync(T(),E(),c),c);[HttpGet("veiculos")]public Task<IActionResult> Veiculos([FromQuery]FrotaFiltro f,CancellationToken c)=>Run(FrotasPermissoes.VeiculoVer,()=>s.VeiculosAsync(T(),E(),f,c),c);[HttpPost("veiculos")]public Task<IActionResult> Veiculo(VeiculoInput i,CancellationToken c)=>Run(FrotasPermissoes.VeiculoCriar,()=>s.CriarVeiculoAsync(T(),U(),Trace(),i with{EntidadeId=E()},c),c);
 [HttpGet("motoristas")]public Task<IActionResult> Motoristas([FromQuery]FrotaFiltro f,CancellationToken c)=>Run(FrotasPermissoes.MotoristaVer,()=>s.MotoristasAsync(T(),E(),f,c),c);[HttpPost("motoristas")]public Task<IActionResult> Motorista(MotoristaInput i,CancellationToken c)=>Run(FrotasPermissoes.MotoristaCriar,()=>s.CriarMotoristaAsync(T(),U(),Trace(),i with{EntidadeId=E()},c),c);
 [HttpPost("utilizacoes")]public Task<IActionResult> Utilizacao(UtilizacaoInput i,CancellationToken c)=>Run(FrotasPermissoes.UtilizacaoCriar,()=>s.CriarUtilizacaoAsync(T(),U(),Trace(),i with{EntidadeId=E()},c),c);[HttpPost("utilizacoes/{id:long}/finalizar")]public Task<IActionResult> Finalizar(long id,FinalizarInput i,CancellationToken c)=>Run(FrotasPermissoes.UtilizacaoFinalizar,async()=>{await s.FinalizarUtilizacaoAsync(T(),E(),U(),Trace(),id,i.KmRetorno,i.RetornoEm,c);return new{id};},c);
 [HttpPost("abastecimentos")]public Task<IActionResult> Abastecimento(AbastecimentoInput i,CancellationToken c)=>Run(FrotasPermissoes.AbastecimentoCriar,()=>s.CriarAbastecimentoAsync(T(),U(),Trace(),i with{EntidadeId=E()},c),c);[HttpPost("manutencoes")]public Task<IActionResult> Manutencao(ManutencaoInput i,CancellationToken c)=>Run(FrotasPermissoes.ManutencaoCriar,()=>s.CriarManutencaoAsync(T(),U(),Trace(),i with{EntidadeId=E()},c),c);
 [HttpPost("ordens-servico")]public Task<IActionResult> Ordem(OrdemServicoInput i,CancellationToken c)=>Run(FrotasPermissoes.OsCriar,()=>s.CriarOrdemAsync(T(),U(),Trace(),i with{EntidadeId=E()},c),c);[HttpPost("ordens-servico/{id:long}/{acao:regex(^aprovar|concluir|cancelar$)}")]public Task<IActionResult> OrdemStatus(long id,string acao,CancellationToken c)=>Run(acao=="aprovar"?FrotasPermissoes.OsAprovar:FrotasPermissoes.OsConcluir,async()=>{await s.AlterarOrdemAsync(T(),E(),U(),Trace(),id,acao,c);return new{id,acao};},c);
 async Task<IActionResult> Run<T>(string p,Func<Task<T>> f,CancellationToken c){if(!await Allowed(p,c))return Forbid();try{return Ok(ApiResponse<T>.Ok(await f(),correlationId:Trace()));}catch(KeyNotFoundException x){return NotFound(ApiResponse<T>.Fail(x.Message));}catch(ArgumentException x){return BadRequest(ApiResponse<T>.Fail(x.Message));}catch(InvalidOperationException x){return Conflict(ApiResponse<T>.Fail(x.Message));}}
 async Task<bool> Allowed(string p,CancellationToken c){var i=p.LastIndexOf('.');return(await auth.EvaluateAsync(new(U(),"frotas",p[..i],p[(i+1)..],T(),E(),tenant.ExercicioId,null,null,Trace(),"API_FUNC04"),c)).Permitido;}long T()=>tenant.TenantId??throw new InvalidOperationException("tenant_id obrigatório.");long E()=>tenant.EntidadeId??throw new InvalidOperationException("entidade_id obrigatório.");long U()=>user.UsuarioId??throw new InvalidOperationException("Usuário obrigatório.");string Trace()=>HttpContext.TraceIdentifier;public sealed record FinalizarInput(decimal KmRetorno,DateTimeOffset RetornoEm);
}
