using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Dapper;
using Microsoft.AspNetCore.Mvc;
using Sigov.Api.Contracts;
using Sigov.Application.Abstractions;
using Sigov.Infrastructure.Persistence.Dapper;

namespace Sigov.Api.Controllers;

[ApiController]
public sealed class MobileCampoController : ControllerBase
{
    private readonly DapperContext _context;
    private readonly ICurrentTenant _tenant;
    private readonly ICurrentUser _user;
    private readonly ILogger<MobileCampoController> _logger;

    public MobileCampoController(DapperContext context, ICurrentTenant tenant, ICurrentUser user, ILogger<MobileCampoController> logger)
    {
        _context = context;
        _tenant = tenant;
        _user = user;
        _logger = logger;
    }

    [HttpGet("api/mobile/dispositivos")] public Task<ActionResult<ApiResponse<object>>> Dispositivos(CancellationToken ct) => TenantQuery("select id,usuario_id,identificador,nome,plataforma,versao_app,ativo,ultimo_sync_at,politica_offline_aceita,bloquear_dados_sensiveis from sigov.mobile_dispositivo where tenant_id=@TenantId order by id desc", "DISPOSITIVOS_LISTADOS", ct);
    [HttpPost("api/mobile/dispositivos/registrar")] public Task<ActionResult<ApiResponse<object>>> RegistrarDispositivo([FromBody] Dictionary<string, object?> body, CancellationToken ct) => Safe("DISPOSITIVO_REGISTRADO", async (tenantId, userId, cid) => { using var c = _context.CreateConnection(); var id = await c.ExecuteScalarAsync<long>(new CommandDefinition(@"insert into sigov.mobile_dispositivo(tenant_id,usuario_id,identificador,nome,plataforma,versao_app,politica_offline_aceita,cache_sensivel_permitido,bloquear_dados_sensiveis)
values(@TenantId,@UsuarioId,@Identificador,@Nome,@Plataforma,@VersaoApp,@PoliticaOfflineAceita,@CacheSensivelPermitido,@BloquearDadosSensiveis)
on conflict(tenant_id,usuario_id,identificador) do update set nome=excluded.nome,plataforma=excluded.plataforma,versao_app=excluded.versao_app,ativo=true,politica_offline_aceita=excluded.politica_offline_aceita,cache_sensivel_permitido=excluded.cache_sensivel_permitido,bloquear_dados_sensiveis=excluded.bloquear_dados_sensiveis,updated_at=now() returning id", new { TenantId = tenantId, UsuarioId = userId, Identificador = Text(body, "identificador", "pwa-demo"), Nome = Text(body, "nome", "Dispositivo PWA"), Plataforma = Text(body, "plataforma", "PWA"), VersaoApp = Text(body, "versaoApp", "1.0"), PoliticaOfflineAceita = Bool(body, "politicaOfflineAceita", true), CacheSensivelPermitido = Bool(body, "cacheSensivelPermitido", false), BloquearDadosSensiveis = Bool(body, "bloquearDadosSensiveis", true) }, cancellationToken: ct)); await Audit(c, tenantId, "DISPOSITIVO_REGISTRADO", "mobile_dispositivo", id, body, cid, ct); return Ok(ApiResponse<object>.Ok(new { id, tenantId, usuarioId = userId, correlationId = cid }, "Dispositivo registrado com política offline e LGPD.", cid)); }, ct);
    [HttpPatch("api/mobile/dispositivos/{id:long}/status")] public Task<ActionResult<ApiResponse<object>>> StatusDispositivo(long id, [FromBody] Dictionary<string, object?> body, CancellationToken ct) => Safe("DISPOSITIVO_INATIVADO", async (tenantId, _, cid) => { using var c = _context.CreateConnection(); await c.ExecuteAsync(new CommandDefinition("update sigov.mobile_dispositivo set ativo=@Ativo,updated_at=now() where tenant_id=@TenantId and id=@Id", new { TenantId = tenantId, Id = id, Ativo = Bool(body, "ativo", false) }, cancellationToken: ct)); await Audit(c, tenantId, "DISPOSITIVO_INATIVADO", "mobile_dispositivo", id, body, cid, ct); return Ok(ApiResponse<object>.Ok(new { id, ativo = Bool(body, "ativo", false), correlationId = cid }, correlationId: cid)); }, ct);
    [HttpPost("api/mobile/sessao/iniciar")] public Task<ActionResult<ApiResponse<object>>> IniciarSessao([FromBody] Dictionary<string, object?> body, CancellationToken ct) => Safe("MOBILE_SESSAO_INICIADA", async (tenantId, userId, cid) => { using var c = _context.CreateConnection(); var id = await c.ExecuteScalarAsync<long>(new CommandDefinition("insert into sigov.mobile_sessao(tenant_id,usuario_id,dispositivo_id,token_hash,ip,user_agent) values(@TenantId,@UsuarioId,@DispositivoId,@TokenHash,@Ip,@UserAgent) returning id", new { TenantId = tenantId, UsuarioId = userId, DispositivoId = Long(body, "dispositivoId"), TokenHash = Hash(cid + userId), Ip = HttpContext.Connection.RemoteIpAddress?.ToString(), UserAgent = Request.Headers["User-Agent"].ToString() }, cancellationToken: ct)); return Ok(ApiResponse<object>.Ok(new { id, correlationId = cid }, correlationId: cid)); }, ct);
    [HttpPost("api/mobile/sessao/finalizar")] public Task<ActionResult<ApiResponse<object>>> FinalizarSessao([FromBody] Dictionary<string, object?> body, CancellationToken ct) => Safe("MOBILE_SESSAO_FINALIZADA", async (tenantId, userId, cid) => { using var c = _context.CreateConnection(); await c.ExecuteAsync(new CommandDefinition("update sigov.mobile_sessao set ativa=false,fim_at=now() where tenant_id=@TenantId and usuario_id=@UsuarioId and (@Id is null or id=@Id)", new { TenantId = tenantId, UsuarioId = userId, Id = Long(body, "id") }, cancellationToken: ct)); return Ok(ApiResponse<object>.Ok(new { finalizada = true, correlationId = cid }, correlationId: cid)); }, ct);

    [HttpGet("api/mobile/sync/config")] public Task<ActionResult<ApiResponse<object>>> SyncConfig(CancellationToken ct) => TenantQuery("select modulo_codigo,entidade,habilitado,max_registros,ttl_minutos,permite_offline,mascarar_dados_sensiveis from sigov.mobile_cache_config where tenant_id=@TenantId and habilitado=true order by modulo_codigo,entidade", "SYNC_CONFIG_LISTADA", ct);
    [HttpPost("api/mobile/sync/upload")] public Task<ActionResult<ApiResponse<object>>> SyncUpload([FromBody] SyncUploadRequest request, CancellationToken ct) => Safe("SYNC_LOTE_CRIADO", async (tenantId, userId, cid) => { using var c = _context.CreateConnection(); await EnsureDeviceActive(c, tenantId, request.DispositivoId, ct); var items = request.Itens ?? Array.Empty<SyncUploadItem>(); var loteId = await c.ExecuteScalarAsync<long>(new CommandDefinition("insert into sigov.mobile_sync_lote(tenant_id,usuario_id,dispositivo_id,direcao,status,total_itens,correlation_id) values(@TenantId,@UsuarioId,@DispositivoId,'UPLOAD','PROCESSANDO',@Total,cast(@CorrelationId as uuid)) returning id", new { TenantId = tenantId, UsuarioId = userId, request.DispositivoId, Total = items.Length, CorrelationId = cid }, cancellationToken: ct)); var processed = 0; foreach (var item in items) { var status = ValidSyncItem(item) ? "PROCESSADO" : "FALHOU"; var erro = status == "FALHOU" ? "Item inválido mantido no lote sem interromper processamento." : null; if (status == "PROCESSADO") processed++; await c.ExecuteAsync(new CommandDefinition("insert into sigov.mobile_sync_item(lote_id,entidade,entidade_id_local,entidade_id_servidor,operacao,payload,status,erro,processado_at) values(@LoteId,@Entidade,@Local,@Servidor,@Operacao,cast(@Payload as jsonb),@Status,@Erro,now())", new { LoteId = loteId, Entidade = item.Entidade ?? "desconhecida", Local = item.EntidadeIdLocal, Servidor = item.EntidadeIdServidor, Operacao = item.Operacao ?? "CREATE", Payload = JsonSerializer.Serialize(item.Payload ?? new { }), Status = status, Erro = erro }, cancellationToken: ct)); } var loteStatus = processed == items.Length ? "CONCLUIDO" : (processed == 0 ? "FALHOU" : "PARCIAL"); await c.ExecuteAsync(new CommandDefinition("update sigov.mobile_sync_lote set status=@Status,itens_processados=@Processados,concluido_at=now(),erro=@Erro where id=@LoteId and tenant_id=@TenantId", new { TenantId = tenantId, LoteId = loteId, Status = loteStatus, Processados = processed, Erro = loteStatus == "CONCLUIDO" ? null : "Um ou mais itens ficaram pendentes/falharam." }, cancellationToken: ct)); await IncrementBilling(c, tenantId, "sync", items.Length, 0, ct); await Audit(c, tenantId, loteStatus == "FALHOU" ? "SYNC_LOTE_FALHOU" : "SYNC_LOTE_CONCLUIDO", "mobile_sync_lote", loteId, request, cid, ct); return Ok(ApiResponse<object>.Ok(new { loteId, status = loteStatus, total = items.Length, processados = processed, correlationId = cid }, "Upload processado com tolerância a item inválido.", cid)); }, ct);
    [HttpGet("api/mobile/sync/download")] public Task<ActionResult<ApiResponse<object>>> SyncDownload(CancellationToken ct) => Safe("SYNC_DOWNLOAD_GERADO", async (tenantId, userId, cid) => { using var c = _context.CreateConnection(); var loteId = await c.ExecuteScalarAsync<long>(new CommandDefinition("insert into sigov.mobile_sync_lote(tenant_id,usuario_id,direcao,status,total_itens,itens_processados,correlation_id,concluido_at) values(@TenantId,@UsuarioId,'DOWNLOAD','CONCLUIDO',0,0,cast(@CorrelationId as uuid),now()) returning id", new { TenantId = tenantId, UsuarioId = userId, CorrelationId = cid }, cancellationToken: ct)); await IncrementBilling(c, tenantId, "sync", 0, 0, ct); return Ok(ApiResponse<object>.Ok(new { loteId, atividades = Array.Empty<object>(), cacheExpiraMinutos = 720, correlationId = cid }, correlationId: cid)); }, ct);
    [HttpGet("api/mobile/sync/lotes")] public Task<ActionResult<ApiResponse<object>>> SyncLotes(CancellationToken ct) => TenantQuery("select id,usuario_id,dispositivo_id,direcao,status,total_itens,itens_processados,erro,correlation_id,created_at,concluido_at from sigov.mobile_sync_lote where tenant_id=@TenantId order by id desc limit 100", "SYNC_LOTES_LISTADOS", ct);
    [HttpGet("api/mobile/sync/lotes/{id:long}")] public Task<ActionResult<ApiResponse<object>>> SyncLote(long id, CancellationToken ct) => TenantSingle("select * from sigov.mobile_sync_lote where tenant_id=@TenantId and id=@Id", new { Id = id }, "Lote não encontrado.", ct);
    [HttpPost("api/mobile/sync/lotes/{id:long}/reprocessar")] public Task<ActionResult<ApiResponse<object>>> Reprocessar(long id, CancellationToken ct) => Safe("SYNC_LOTE_REPROCESSADO", async (tenantId, _, cid) => { using var c = _context.CreateConnection(); await c.ExecuteAsync(new CommandDefinition("update sigov.mobile_sync_lote set status='PENDENTE',erro=null where tenant_id=@TenantId and id=@Id", new { TenantId = tenantId, Id = id }, cancellationToken: ct)); return Ok(ApiResponse<object>.Ok(new { id, status = "PENDENTE", correlationId = cid }, correlationId: cid)); }, ct);

    [HttpGet("api/campo/atividades")] public Task<ActionResult<ApiResponse<object>>> Atividades(CancellationToken ct) => TenantQuery("select * from sigov.campo_atividade where tenant_id=@TenantId order by coalesce(data_agendada,created_at) desc limit 200", "ATIVIDADES_CAMPO_LISTADAS", ct);
    [HttpGet("api/campo/atividades/{id:long}")] public Task<ActionResult<ApiResponse<object>>> Atividade(long id, CancellationToken ct) => TenantSingle("select * from sigov.campo_atividade where tenant_id=@TenantId and id=@Id", new { Id = id }, "Atividade não encontrada.", ct);
    [HttpPost("api/campo/atividades")] public Task<ActionResult<ApiResponse<object>>> CriarAtividade([FromBody] Dictionary<string, object?> body, CancellationToken ct) => Safe("ATIVIDADE_CAMPO_CRIADA", async (tenantId, userId, cid) => { using var c = _context.CreateConnection(); var id = await c.ExecuteScalarAsync<long>(new CommandDefinition("insert into sigov.campo_atividade(tenant_id,modulo_codigo,origem,origem_id,titulo,descricao,tipo,status,responsavel_id,prioridade,offline_critica,aprovacao_pendente) values(@TenantId,@Modulo,@Origem,@OrigemId,@Titulo,@Descricao,@Tipo,@Status,@ResponsavelId,@Prioridade,@OfflineCritica,@AprovacaoPendente) returning id", new { TenantId = tenantId, Modulo = Text(body, "moduloCodigo", "campo_operacional"), Origem = TextOrNull(body, "origem"), OrigemId = Long(body, "origemId"), Titulo = Text(body, "titulo", "Atividade de campo"), Descricao = TextOrNull(body, "descricao"), Tipo = Text(body, "tipo", "VISITA"), Status = Bool(body, "offlineCritica", false) ? "SINCRONIZACAO_PENDENTE" : "PENDENTE", ResponsavelId = Long(body, "responsavelId") ?? userId, Prioridade = Text(body, "prioridade", "MEDIA"), OfflineCritica = Bool(body, "offlineCritica", false), AprovacaoPendente = Bool(body, "offlineCritica", false) }, cancellationToken: ct)); await Audit(c, tenantId, "ATIVIDADE_CAMPO_CRIADA", "campo_atividade", id, body, cid, ct); return Ok(ApiResponse<object>.Ok(new { id, tenantId, correlationId = cid }, correlationId: cid)); }, ct);
    [HttpPut("api/campo/atividades/{id:long}")] public Task<ActionResult<ApiResponse<object>>> AtualizarAtividade(long id, [FromBody] Dictionary<string, object?> body, CancellationToken ct) => StatusAtividade(id, Text(body, "status", "PENDENTE"), "ATIVIDADE_CAMPO_ATUALIZADA", ct);
    [HttpPost("api/campo/atividades/{id:long}/iniciar")] public Task<ActionResult<ApiResponse<object>>> IniciarAtividade(long id, CancellationToken ct) => StatusAtividade(id, "EM_EXECUCAO", "ATIVIDADE_CAMPO_INICIADA", ct, "inicio_at=coalesce(inicio_at,now()),");
    [HttpPost("api/campo/atividades/{id:long}/pausar")] public Task<ActionResult<ApiResponse<object>>> PausarAtividade(long id, CancellationToken ct) => StatusAtividade(id, "PAUSADA", "ATIVIDADE_CAMPO_PAUSADA", ct);
    [HttpPost("api/campo/atividades/{id:long}/concluir")] public Task<ActionResult<ApiResponse<object>>> ConcluirAtividade(long id, CancellationToken ct) => StatusAtividade(id, "CONCLUIDA", "ATIVIDADE_CAMPO_CONCLUIDA", ct, "fim_at=now(),");
    [HttpPost("api/campo/atividades/{id:long}/cancelar")] public Task<ActionResult<ApiResponse<object>>> CancelarAtividade(long id, CancellationToken ct) => StatusAtividade(id, "CANCELADA", "ATIVIDADE_CAMPO_CANCELADA", ct);

    [HttpGet("api/campo/visitas")] public Task<ActionResult<ApiResponse<object>>> Visitas(CancellationToken ct) => TenantQuery("select * from sigov.campo_visita where tenant_id=@TenantId order by id desc limit 200", "VISITAS_CAMPO_LISTADAS", ct);
    [HttpGet("api/campo/visitas/{id:long}")] public Task<ActionResult<ApiResponse<object>>> Visita(long id, CancellationToken ct) => TenantSingle("select * from sigov.campo_visita where tenant_id=@TenantId and id=@Id", new { Id = id }, "Visita não encontrada.", ct);
    [HttpPost("api/campo/visitas")] public Task<ActionResult<ApiResponse<object>>> CriarVisita([FromBody] Dictionary<string, object?> body, CancellationToken ct) => InsertSimple("campo_visita", "VISITA_CAMPO_CRIADA", "insert into sigov.campo_visita(tenant_id,atividade_id,pessoa_id,cliente_id,local_nome,finalidade,observacao,status) values(@TenantId,@AtividadeId,@PessoaId,@ClienteId,@LocalNome,@Finalidade,@Observacao,'PENDENTE') returning id", body, ct);
    [HttpPost("api/campo/visitas/{id:long}/iniciar")] public Task<ActionResult<ApiResponse<object>>> IniciarVisita(long id, CancellationToken ct) => UpdateTenant("update sigov.campo_visita set status='EM_EXECUCAO',inicio_at=coalesce(inicio_at,now()) where tenant_id=@TenantId and id=@Id", id, "VISITA_CAMPO_INICIADA", ct);
    [HttpPost("api/campo/visitas/{id:long}/concluir")] public Task<ActionResult<ApiResponse<object>>> ConcluirVisita(long id, CancellationToken ct) => UpdateTenant("update sigov.campo_visita set status='CONCLUIDA',fim_at=now() where tenant_id=@TenantId and id=@Id", id, "VISITA_CAMPO_CONCLUIDA", ct);

    [HttpGet("api/campo/checklists")] public Task<ActionResult<ApiResponse<object>>> Checklists(CancellationToken ct) => TenantQuery("select * from sigov.campo_checklist where tenant_id=@TenantId order by nome", "CHECKLISTS_LISTADOS", ct);
    [HttpGet("api/campo/checklists/{id:long}")] public Task<ActionResult<ApiResponse<object>>> Checklist(long id, CancellationToken ct) => TenantSingle("select c.*, coalesce(json_agg(i.*) filter(where i.id is not null),'[]') as itens from sigov.campo_checklist c left join sigov.campo_checklist_item i on i.checklist_id=c.id where c.tenant_id=@TenantId and c.id=@Id group by c.id", new { Id = id }, "Checklist não encontrado.", ct);
    [HttpPost("api/campo/checklists")] public Task<ActionResult<ApiResponse<object>>> CriarChecklist([FromBody] Dictionary<string, object?> body, CancellationToken ct) => InsertSimple("campo_checklist", "CHECKLIST_CRIADO", "insert into sigov.campo_checklist(tenant_id,codigo,nome,modulo_codigo,tipo) values(@TenantId,@Codigo,@Nome,@Modulo,@Tipo) on conflict(tenant_id,codigo) do update set nome=excluded.nome returning id", body, ct);
    [HttpPut("api/campo/checklists/{id:long}")] public Task<ActionResult<ApiResponse<object>>> AtualizarChecklist(long id, [FromBody] Dictionary<string, object?> body, CancellationToken ct) => UpdateTenant("update sigov.campo_checklist set nome=@Nome where tenant_id=@TenantId and id=@Id", id, "CHECKLIST_ATUALIZADO", ct, body);
    [HttpPost("api/campo/atividades/{id:long}/checklist/responder")] public Task<ActionResult<ApiResponse<object>>> ResponderChecklist(long id, [FromBody] Dictionary<string, object?> body, CancellationToken ct) => Safe("CHECKLIST_RESPONDIDO", async (tenantId, userId, cid) => { using var c = _context.CreateConnection(); var formId = await EnsureChecklistResponseForm(c, tenantId, ct); var respId = await c.ExecuteScalarAsync<long>(new CommandDefinition("insert into sigov.campo_formulario_resposta(tenant_id,formulario_id,atividade_id,usuario_id,resposta_json,latitude,longitude,sincronizado_at) values(@TenantId,@FormularioId,@AtividadeId,@UsuarioId,cast(@Resposta as jsonb),@Latitude,@Longitude,now()) returning id", new { TenantId = tenantId, FormularioId = formId, AtividadeId = id, UsuarioId = userId, Resposta = JsonSerializer.Serialize(body), Latitude = Decimal(body, "latitude"), Longitude = Decimal(body, "longitude") }, cancellationToken: ct)); await Audit(c, tenantId, "CHECKLIST_RESPONDIDO", "campo_atividade", id, body, cid, ct); return Ok(ApiResponse<object>.Ok(new { id = respId, atividadeId = id, correlationId = cid }, correlationId: cid)); }, ct);

    [HttpPost("api/campo/atividades/{id:long}/evidencias")] public Task<ActionResult<ApiResponse<object>>> Evidencia(long id, [FromBody] Dictionary<string, object?> body, CancellationToken ct) => Safe("EVIDENCIA_ENVIADA", async (tenantId, userId, cid) => { using var c = _context.CreateConnection(); var evId = await c.ExecuteScalarAsync<long>(new CommandDefinition("insert into sigov.campo_evidencia(tenant_id,atividade_id,visita_id,origem,origem_id,tipo,titulo,arquivo_path,content_type,tamanho_bytes,latitude,longitude,capturado_por,lgpd_classificacao,mascarado_offline) values(@TenantId,@AtividadeId,@VisitaId,@Origem,@OrigemId,@Tipo,@Titulo,@ArquivoPath,@ContentType,@TamanhoBytes,@Latitude,@Longitude,@UsuarioId,@Lgpd,true) returning id", Params(tenantId, id, userId, body), cancellationToken: ct)); await IncrementBilling(c, tenantId, "foto", 0, Long(body, "tamanhoBytes") ?? 0, ct); await Audit(c, tenantId, "EVIDENCIA_ENVIADA", "campo_evidencia", evId, body, cid, ct); return Ok(ApiResponse<object>.Ok(new { id = evId, correlationId = cid }, "Evidência registrada com classificação LGPD e mascaramento offline.", cid)); }, ct);
    [HttpGet("api/campo/atividades/{id:long}/evidencias")] public Task<ActionResult<ApiResponse<object>>> Evidencias(long id, CancellationToken ct) => TenantQuery("select id,atividade_id,visita_id,origem,tipo,titulo,content_type,tamanho_bytes,latitude,longitude,capturado_por,capturado_at,lgpd_classificacao,mascarado_offline from sigov.campo_evidencia where tenant_id=@TenantId and atividade_id=" + id + " order by id desc", "EVIDENCIAS_LISTADAS", ct);
    [HttpGet("api/campo/evidencias/{id:long}/download")] public Task<ActionResult<ApiResponse<object>>> DownloadEvidencia(long id, CancellationToken ct) => TenantSingle("select id,titulo,arquivo_path,content_type,tamanho_bytes,lgpd_classificacao from sigov.campo_evidencia where tenant_id=@TenantId and id=@Id", new { Id = id }, "Evidência não encontrada.", ct);
    [HttpPost("api/campo/atividades/{id:long}/assinatura")] public Task<ActionResult<ApiResponse<object>>> Assinatura(long id, [FromBody] Dictionary<string, object?> body, CancellationToken ct) => Safe("ASSINATURA_CAMPO_COLETADA", async (tenantId, _, cid) => { using var c = _context.CreateConnection(); var assinatura = Text(body, "assinaturaBase64", cid); var hash = Hash(assinatura); var sigId = await c.ExecuteScalarAsync<long>(new CommandDefinition("insert into sigov.campo_assinatura(tenant_id,atividade_id,visita_id,nome_assinante,documento_assinante,assinatura_base64,assinatura_hash,latitude,longitude,ip,user_agent) values(@TenantId,@AtividadeId,@VisitaId,@Nome,@Documento,@Assinatura,@Hash,@Latitude,@Longitude,@Ip,@UserAgent) returning id", new { TenantId = tenantId, AtividadeId = id, VisitaId = Long(body, "visitaId"), Nome = Text(body, "nomeAssinante", "Assinante"), Documento = TextOrNull(body, "documentoAssinante"), Assinatura = assinatura, Hash = hash, Latitude = Decimal(body, "latitude"), Longitude = Decimal(body, "longitude"), Ip = HttpContext.Connection.RemoteIpAddress?.ToString(), UserAgent = Request.Headers["User-Agent"].ToString() }, cancellationToken: ct)); await IncrementBilling(c, tenantId, "assinatura", 0, 0, ct); await Audit(c, tenantId, "ASSINATURA_CAMPO_COLETADA", "campo_assinatura", sigId, new { hash }, cid, ct); return Ok(ApiResponse<object>.Ok(new { id = sigId, assinaturaHash = hash, correlationId = cid }, correlationId: cid)); }, ct);
    [HttpGet("api/campo/atividades/{id:long}/assinaturas")] public Task<ActionResult<ApiResponse<object>>> Assinaturas(long id, CancellationToken ct) => TenantQuery("select id,atividade_id,visita_id,nome_assinante,documento_assinante,assinatura_hash,latitude,longitude,assinado_at from sigov.campo_assinatura where tenant_id=@TenantId and atividade_id=" + id + " order by id desc", "ASSINATURAS_LISTADAS", ct);
    [HttpPost("api/campo/localizacao")] public Task<ActionResult<ApiResponse<object>>> Localizacao([FromBody] Dictionary<string, object?> body, CancellationToken ct) => Safe("LOCALIZACAO_REGISTRADA", async (tenantId, userId, cid) => { if (string.IsNullOrWhiteSpace(Text(body, "consentimento", "REGRA_OPERACIONAL"))) throw new InvalidOperationException("Localização exige consentimento ou regra operacional clara."); using var c = _context.CreateConnection(); var locId = await c.ExecuteScalarAsync<long>(new CommandDefinition("insert into sigov.campo_localizacao(tenant_id,usuario_id,dispositivo_id,atividade_id,latitude,longitude,precisao_metros,origem,consentimento,regra_operacional) values(@TenantId,@UsuarioId,@DispositivoId,@AtividadeId,@Latitude,@Longitude,@Precisao,@Origem,@Consentimento,@Regra) returning id", new { TenantId = tenantId, UsuarioId = userId, DispositivoId = Long(body, "dispositivoId"), AtividadeId = Long(body, "atividadeId"), Latitude = Decimal(body, "latitude") ?? 0, Longitude = Decimal(body, "longitude") ?? 0, Precisao = Decimal(body, "precisaoMetros"), Origem = Text(body, "origem", "GPS"), Consentimento = Text(body, "consentimento", "REGRA_OPERACIONAL"), Regra = Text(body, "regraOperacional", "Coleta opcional conforme permissão e finalidade operacional.") }, cancellationToken: ct)); await IncrementBilling(c, tenantId, "localizacao", 0, 0, ct); await Audit(c, tenantId, "LOCALIZACAO_REGISTRADA", "campo_localizacao", locId, body, cid, ct); return Ok(ApiResponse<object>.Ok(new { id = locId, correlationId = cid }, correlationId: cid)); }, ct);
    [HttpGet("api/campo/atividades/{id:long}/localizacoes")] public Task<ActionResult<ApiResponse<object>>> Localizacoes(long id, CancellationToken ct) => TenantQuery("select * from sigov.campo_localizacao where tenant_id=@TenantId and atividade_id=" + id + " order by capturado_at desc", "LOCALIZACOES_LISTADAS", ct);

    [HttpGet("api/campo/rotas")] public Task<ActionResult<ApiResponse<object>>> Rotas(CancellationToken ct) => TenantQuery("select * from sigov.campo_rota where tenant_id=@TenantId order by data_rota desc,id desc", "ROTAS_LISTADAS", ct);
    [HttpPost("api/campo/rotas")] public Task<ActionResult<ApiResponse<object>>> CriarRota([FromBody] Dictionary<string, object?> body, CancellationToken ct) => Safe("ROTA_CRIADA", async (tenantId, userId, cid) => { using var c = _context.CreateConnection(); var id = await c.ExecuteScalarAsync<long>(new CommandDefinition("insert into sigov.campo_rota(tenant_id,usuario_id,nome,data_rota,status) values(@TenantId,@UsuarioId,@Nome,current_date,'PLANEJADA') returning id", new { TenantId = tenantId, UsuarioId = Long(body, "usuarioId") ?? userId, Nome = Text(body, "nome", "Rota de campo") }, cancellationToken: ct)); await Audit(c, tenantId, "ROTA_CRIADA", "campo_rota", id, body, cid, ct); return Ok(ApiResponse<object>.Ok(new { id, correlationId = cid }, correlationId: cid)); }, ct);
    [HttpGet("api/campo/rotas/{id:long}")] public Task<ActionResult<ApiResponse<object>>> Rota(long id, CancellationToken ct) => TenantSingle("select r.*, coalesce(json_agg(p.*) filter(where p.id is not null),'[]') as pontos from sigov.campo_rota r left join sigov.campo_rota_ponto p on p.rota_id=r.id where r.tenant_id=@TenantId and r.id=@Id group by r.id", new { Id = id }, "Rota não encontrada.", ct);
    [HttpPost("api/campo/rotas/{id:long}/otimizar-simulado")] public Task<ActionResult<ApiResponse<object>>> OtimizarRota(long id, CancellationToken ct) => UpdateTenant("update sigov.campo_rota set status='OTIMIZADA' where tenant_id=@TenantId and id=@Id", id, "ROTA_OTIMIZADA_SIMULADA", ct);
    [HttpGet("api/campo/notificacoes")] public Task<ActionResult<ApiResponse<object>>> Notificacoes(CancellationToken ct) => TenantQuery("select * from sigov.campo_notificacao where tenant_id=@TenantId order by id desc limit 100", "NOTIFICACOES_CAMPO_LISTADAS", ct);
    [HttpPost("api/campo/notificacoes/{id:long}/marcar-lida")] public Task<ActionResult<ApiResponse<object>>> MarcarLida(long id, CancellationToken ct) => UpdateTenant("update sigov.campo_notificacao set lida=true,lida_at=now() where tenant_id=@TenantId and id=@Id", id, "NOTIFICACAO_CAMPO_LIDA", ct);
    [HttpGet("api/campo/formularios")] public Task<ActionResult<ApiResponse<object>>> Formularios(CancellationToken ct) => TenantQuery("select * from sigov.campo_formulario where tenant_id=@TenantId order by nome", "FORMULARIOS_LISTADOS", ct);
    [HttpPost("api/campo/formularios")] public Task<ActionResult<ApiResponse<object>>> CriarFormulario([FromBody] Dictionary<string, object?> body, CancellationToken ct) => InsertSimple("campo_formulario", "FORMULARIO_CRIADO", "insert into sigov.campo_formulario(tenant_id,codigo,nome,modulo_codigo,schema_json) values(@TenantId,@Codigo,@Nome,@Modulo,cast(@Schema as jsonb)) on conflict(tenant_id,codigo) do update set nome=excluded.nome,schema_json=excluded.schema_json returning id", body, ct);
    [HttpPut("api/campo/formularios/{id:long}")] public Task<ActionResult<ApiResponse<object>>> AtualizarFormulario(long id, [FromBody] Dictionary<string, object?> body, CancellationToken ct) => UpdateTenant("update sigov.campo_formulario set nome=@Nome,schema_json=cast(@Schema as jsonb) where tenant_id=@TenantId and id=@Id", id, "FORMULARIO_ATUALIZADO", ct, body);
    [HttpPost("api/campo/formularios/{id:long}/respostas")] public Task<ActionResult<ApiResponse<object>>> ResponderFormulario(long id, [FromBody] Dictionary<string, object?> body, CancellationToken ct) => Safe("FORMULARIO_RESPONDIDO", async (tenantId, userId, cid) => { using var c = _context.CreateConnection(); var respId = await c.ExecuteScalarAsync<long>(new CommandDefinition("insert into sigov.campo_formulario_resposta(tenant_id,formulario_id,atividade_id,usuario_id,resposta_json,latitude,longitude,sincronizado_at) values(@TenantId,@FormularioId,@AtividadeId,@UsuarioId,cast(@Resposta as jsonb),@Latitude,@Longitude,now()) returning id", new { TenantId = tenantId, FormularioId = id, AtividadeId = Long(body, "atividadeId"), UsuarioId = userId, Resposta = JsonSerializer.Serialize(body), Latitude = Decimal(body, "latitude"), Longitude = Decimal(body, "longitude") }, cancellationToken: ct)); await Audit(c, tenantId, "FORMULARIO_RESPONDIDO", "campo_formulario_resposta", respId, body, cid, ct); return Ok(ApiResponse<object>.Ok(new { id = respId, correlationId = cid }, correlationId: cid)); }, ct);
    [HttpGet("api/campo/dashboard")] public Task<ActionResult<ApiResponse<object>>> Dashboard(CancellationToken ct) => Safe("CAMPO_DASHBOARD_VISUALIZADO", async (tenantId, _, cid) => { using var c = _context.CreateConnection(); var data = await c.QuerySingleAsync<object>(new CommandDefinition(@"select
(select count(*) from sigov.campo_atividade where tenant_id=@TenantId and status='PENDENTE') as atividades_pendentes,
(select count(*) from sigov.campo_atividade where tenant_id=@TenantId and status='EM_EXECUCAO') as atividades_em_execucao,
(select count(*) from sigov.campo_atividade where tenant_id=@TenantId and status='CONCLUIDA' and fim_at::date=current_date) as atividades_concluidas_hoje,
(select count(*) from sigov.mobile_sync_lote where tenant_id=@TenantId and status in ('PENDENTE','PARCIAL','FALHOU')) as pendencias_sincronizacao,
(select count(*) from sigov.mobile_dispositivo where tenant_id=@TenantId and ativo=true) as dispositivos_ativos,
(select count(*) from sigov.campo_evidencia where tenant_id=@TenantId) as evidencias_coletadas,
(select count(*) from sigov.campo_visita where tenant_id=@TenantId and created_at::date=current_date) as visitas_do_dia,
(select count(*) from sigov.campo_rota where tenant_id=@TenantId and status='PLANEJADA') as rotas_planejadas", new { TenantId = tenantId }, cancellationToken: ct)); return Ok(ApiResponse<object>.Ok(data, correlationId: cid)); }, ct);

    private Task<ActionResult<ApiResponse<object>>> StatusAtividade(long id, string status, string audit, CancellationToken ct, string extraSet = "") => Safe(audit, async (tenantId, _, cid) => { using var c = _context.CreateConnection(); if (status == "CONCLUIDA") { var requiredOpen = await c.ExecuteScalarAsync<int>(new CommandDefinition("select case when exists(select 1 from sigov.campo_atividade where tenant_id=@TenantId and id=@Id and requer_checklist=true) and not exists(select 1 from sigov.campo_formulario_resposta where tenant_id=@TenantId and atividade_id=@Id) then 1 else 0 end", new { TenantId = tenantId, Id = id }, cancellationToken: ct)); if (requiredOpen == 1) throw new InvalidOperationException("Atividade só pode ser concluída com checklist obrigatório preenchido."); } await c.ExecuteAsync(new CommandDefinition($"update sigov.campo_atividade set {extraSet}status=@Status,updated_at=now() where tenant_id=@TenantId and id=@Id", new { TenantId = tenantId, Id = id, Status = status }, cancellationToken: ct)); await Audit(c, tenantId, audit, "campo_atividade", id, new { status }, cid, ct); return Ok(ApiResponse<object>.Ok(new { id, status, correlationId = cid }, correlationId: cid)); }, ct);
    private Task<ActionResult<ApiResponse<object>>> TenantQuery(string sql, string operation, CancellationToken ct) => Safe(operation, async (tenantId, _, cid) => { using var c = _context.CreateConnection(); var rows = await c.QueryAsync<object>(new CommandDefinition(sql, new { TenantId = tenantId }, cancellationToken: ct)); return Ok(ApiResponse<object>.Ok(rows, correlationId: cid)); }, ct);
    private Task<ActionResult<ApiResponse<object>>> TenantSingle(string sql, object extra, string notFound, CancellationToken ct) => Safe("REGISTRO_CAMPO_OBTIDO", async (tenantId, _, cid) => { using var c = _context.CreateConnection(); var p = new DynamicParameters(extra); p.Add("TenantId", tenantId); var row = await c.QuerySingleOrDefaultAsync<object>(new CommandDefinition(sql, p, cancellationToken: ct)); return row is null ? NotFound(ApiResponse<object>.Fail(notFound, cid)) : Ok(ApiResponse<object>.Ok(row, correlationId: cid)); }, ct);
    private Task<ActionResult<ApiResponse<object>>> UpdateTenant(string sql, long id, string operation, CancellationToken ct, Dictionary<string, object?>? body = null) => Safe(operation, async (tenantId, _, cid) => { using var c = _context.CreateConnection(); var p = body is null ? new DynamicParameters() : Params(tenantId, null, null, body); p.Add("TenantId", tenantId); p.Add("Id", id); await c.ExecuteAsync(new CommandDefinition(sql, p, cancellationToken: ct)); await Audit(c, tenantId, operation, null, id, body, cid, ct); return Ok(ApiResponse<object>.Ok(new { id, correlationId = cid }, correlationId: cid)); }, ct);
    private Task<ActionResult<ApiResponse<object>>> InsertSimple(string table, string operation, string sql, Dictionary<string, object?> body, CancellationToken ct) => Safe(operation, async (tenantId, _, cid) => { using var c = _context.CreateConnection(); var id = await c.ExecuteScalarAsync<long>(new CommandDefinition(sql, Params(tenantId, Long(body, "atividadeId"), null, body), cancellationToken: ct)); await Audit(c, tenantId, operation, table, id, body, cid, ct); return Ok(ApiResponse<object>.Ok(new { id, correlationId = cid }, correlationId: cid)); }, ct);

    private async Task<ActionResult<ApiResponse<object>>> Safe(string operation, Func<long, long, string, Task<ActionResult<ApiResponse<object>>>> action, CancellationToken ct)
    {
        var cid = CorrelationId();
        try
        {
            return await action(RequireTenant(), UserId(), cid);
        }
        catch (InvalidOperationException ex)
        {
            _logger.LogWarning(ex, "Operação mobile/campo bloqueada {Operation}. CorrelationId={CorrelationId}", operation, cid);
            return StatusCode(StatusCodes.Status403Forbidden, ApiResponse<object>.Fail(ex.Message, cid));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Erro na operação mobile/campo {Operation}. CorrelationId={CorrelationId}", operation, cid);
            return StatusCode(StatusCodes.Status500InternalServerError, ApiResponse<object>.Fail("Falha na operação mobile/campo. Informe o correlationId ao suporte.", cid));
        }
    }

    private long RequireTenant() => _tenant.TenantId ?? throw new InvalidOperationException("Tenant obrigatório para operação mobile/campo.");
    private long UserId() => _user.UsuarioId ?? (long.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier), out var id) ? id : 1L);
    private string CorrelationId() => HttpContext.Items.TryGetValue("CorrelationId", out var value) ? value?.ToString() ?? Guid.NewGuid().ToString() : Guid.NewGuid().ToString();
    private static bool ValidSyncItem(SyncUploadItem item) => !string.IsNullOrWhiteSpace(item.Entidade) && !string.IsNullOrWhiteSpace(item.Operacao) && item.Payload is not null;
    private static async Task EnsureDeviceActive(System.Data.IDbConnection c, long tenantId, long? dispositivoId, CancellationToken ct) { if (!dispositivoId.HasValue) return; var active = await c.ExecuteScalarAsync<bool>(new CommandDefinition("select coalesce((select ativo from sigov.mobile_dispositivo where tenant_id=@TenantId and id=@Id),false)", new { TenantId = tenantId, Id = dispositivoId.Value }, cancellationToken: ct)); if (!active) throw new InvalidOperationException("Dispositivo precisa estar ativo para sincronizar."); }
    private static async Task<long> EnsureChecklistResponseForm(System.Data.IDbConnection c, long tenantId, CancellationToken ct) => await c.ExecuteScalarAsync<long>(new CommandDefinition("insert into sigov.campo_formulario(tenant_id,codigo,nome,modulo_codigo,schema_json) values(@TenantId,'resposta_checklist_mobile','Resposta Checklist Mobile','campo_operacional','{}') on conflict(tenant_id,codigo) do update set nome=excluded.nome returning id", new { TenantId = tenantId }, cancellationToken: ct));
    private static async Task IncrementBilling(System.Data.IDbConnection c, long tenantId, string tipo, int itens, long bytes, CancellationToken ct) => await c.ExecuteAsync(new CommandDefinition(@"insert into sigov.mobile_consumo_billing(tenant_id,competencia,mobile_usuarios_ativos,sync_lotes,sync_itens,fotos_campo,storage_campo_mb,localizacoes_registradas,assinaturas_campo,updated_at) values(@TenantId,date_trunc('month',current_date)::date,1,@SyncLotes,@SyncItens,@Fotos,@StorageMb,@Locs,@Assinaturas,now())
on conflict(tenant_id,competencia) do update set mobile_usuarios_ativos=greatest(sigov.mobile_consumo_billing.mobile_usuarios_ativos,1),sync_lotes=sigov.mobile_consumo_billing.sync_lotes+excluded.sync_lotes,sync_itens=sigov.mobile_consumo_billing.sync_itens+excluded.sync_itens,fotos_campo=sigov.mobile_consumo_billing.fotos_campo+excluded.fotos_campo,storage_campo_mb=sigov.mobile_consumo_billing.storage_campo_mb+excluded.storage_campo_mb,localizacoes_registradas=sigov.mobile_consumo_billing.localizacoes_registradas+excluded.localizacoes_registradas,assinaturas_campo=sigov.mobile_consumo_billing.assinaturas_campo+excluded.assinaturas_campo,alerta_limite=(sigov.mobile_consumo_billing.storage_campo_mb+excluded.storage_campo_mb)>1024,updated_at=now()", new { TenantId = tenantId, SyncLotes = tipo == "sync" ? 1 : 0, SyncItens = tipo == "sync" ? itens : 0, Fotos = tipo == "foto" ? 1 : 0, StorageMb = bytes / 1024m / 1024m, Locs = tipo == "localizacao" ? 1 : 0, Assinaturas = tipo == "assinatura" ? 1 : 0 }, cancellationToken: ct));
    private static async Task Audit(System.Data.IDbConnection c, long tenantId, string evento, string? entidade, long? registroId, object? payload, string cid, CancellationToken ct) => await c.ExecuteAsync(new CommandDefinition("insert into sigov.auditoria_evento(tenant_id,acao,entidade,entidade_id,depois,correlation_id) values(@TenantId,@Evento,coalesce(@Entidade,'mobile_campo'),@RegistroId,cast(@Payload as jsonb),cast(@CorrelationId as uuid))", new { TenantId = tenantId, Evento = evento, Entidade = entidade, RegistroId = registroId?.ToString(), Payload = JsonSerializer.Serialize(payload ?? new { }), CorrelationId = cid }, cancellationToken: ct));
    private static string Hash(string value) => Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(value))).ToLowerInvariant();
    private static DynamicParameters Params(long tenantId, long? atividadeId, long? userId, Dictionary<string, object?> body) { var p = new DynamicParameters(); p.Add("TenantId", tenantId); p.Add("AtividadeId", atividadeId ?? Long(body, "atividadeId")); p.Add("PessoaId", Long(body, "pessoaId")); p.Add("ClienteId", Long(body, "clienteId")); p.Add("LocalNome", TextOrNull(body, "localNome")); p.Add("Finalidade", Text(body, "finalidade", "Visita de campo")); p.Add("Observacao", TextOrNull(body, "observacao")); p.Add("Codigo", Text(body, "codigo", "form_mobile")); p.Add("Nome", Text(body, "nome", "Formulário Mobile")); p.Add("Modulo", Text(body, "moduloCodigo", "campo_operacional")); p.Add("Tipo", Text(body, "tipo", "OUTRO")); p.Add("Schema", JsonValue(body, "schemaJson", "{}")); p.Add("VisitaId", Long(body, "visitaId")); p.Add("Origem", Text(body, "origem", "MOBILE")); p.Add("OrigemId", Long(body, "origemId")); p.Add("Titulo", Text(body, "titulo", "Evidência de campo")); p.Add("ArquivoPath", TextOrNull(body, "arquivoPath")); p.Add("ContentType", Text(body, "contentType", "application/octet-stream")); p.Add("TamanhoBytes", Long(body, "tamanhoBytes") ?? 0); p.Add("Latitude", Decimal(body, "latitude")); p.Add("Longitude", Decimal(body, "longitude")); p.Add("UsuarioId", userId); p.Add("Lgpd", Text(body, "lgpdClassificacao", "OPERACIONAL")); return p; }
    private static string Text(Dictionary<string, object?> body, string key, string fallback) => TextOrNull(body, key) ?? fallback;
    private static string? TextOrNull(Dictionary<string, object?> body, string key) => body.TryGetValue(key, out var value) ? ValueToString(value) : null;
    private static string JsonValue(Dictionary<string, object?> body, string key, string fallback) => body.TryGetValue(key, out var value) ? (value is JsonElement e ? e.GetRawText() : JsonSerializer.Serialize(value)) : fallback;
    private static bool Bool(Dictionary<string, object?> body, string key, bool fallback) => body.TryGetValue(key, out var value) && bool.TryParse(ValueToString(value), out var parsed) ? parsed : fallback;
    private static long? Long(Dictionary<string, object?> body, string key) => body.TryGetValue(key, out var value) && long.TryParse(ValueToString(value), out var parsed) ? parsed : null;
    private static decimal? Decimal(Dictionary<string, object?> body, string key) => body.TryGetValue(key, out var value) && decimal.TryParse(ValueToString(value), System.Globalization.NumberStyles.Any, System.Globalization.CultureInfo.InvariantCulture, out var parsed) ? parsed : null;
    private static string? ValueToString(object? value) => value switch { null => null, JsonElement e when e.ValueKind == JsonValueKind.String => e.GetString(), JsonElement e when e.ValueKind == JsonValueKind.Number => e.GetRawText(), JsonElement e when e.ValueKind is JsonValueKind.True or JsonValueKind.False => e.GetRawText(), _ => value.ToString() };
}

public sealed record SyncUploadRequest(long? DispositivoId, SyncUploadItem[]? Itens);
public sealed record SyncUploadItem(string? Entidade, string? EntidadeIdLocal, long? EntidadeIdServidor, string? Operacao, object? Payload);
