using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Sigov.Api.Contracts; using Sigov.Application.Abstractions; using Sigov.Application.Common; using Sigov.Application.Tributario.TributarioAvancado;
namespace Sigov.Api.Controllers;
[ApiController,Route("api/portal-contribuinte")]
public sealed class PortalContribuinteController:TributarioAvancadoControllerBase { readonly IPortalContribuinteService _s; public PortalContribuinteController(IPortalContribuinteService s,ICurrentTenant t,ICurrentUser u):base(t,u)=>_s=s;
[HttpGet("dashboard")]public async Task<ActionResult<ApiResponse<TributarioDashboardDto>>>Dashboard(CancellationToken ct)=>Resposta(await _s.DashboardAsync(TenantId(),"portal_contribuinte_protocolo",ct));
[HttpPost("consulta")]public async Task<ActionResult<ApiResponse<PagedResult<TributarioRegistroDto>>>>Consulta(CancellationToken ct)=>Resposta(await _s.ListarAsync(TenantId(),"portal_contribuinte_solicitacao",1,20,ct));
[HttpGet("contribuintes/{codigo}/debitos"),HttpGet("contribuintes/{codigo}/pagamentos")]public async Task<ActionResult<ApiResponse<PagedResult<TributarioRegistroDto>>>>Movimentos(string codigo,CancellationToken ct)=>Resposta(await _s.ListarAsync(TenantId(),"portal_contribuinte_guia_emitida",1,50,ct));
[HttpPost("guias/emitir")]public async Task<ActionResult<ApiResponse<long>>>Guia(TributarioOperacaoRequest r,CancellationToken ct)=>Resposta(await _s.CriarAsync(Contexto(),"portal_contribuinte_guia_emitida",r with{Status="PREPARATORIA"},ct));
[HttpGet("guias/{id:long}")]public async Task<ActionResult<ApiResponse<TributarioRegistroDto?>>>Guia(long id,CancellationToken ct)=>Resposta(await _s.ObterAsync(TenantId(),"portal_contribuinte_guia_emitida",id,ct));
[HttpPost("certidoes/emitir")]public async Task<ActionResult<ApiResponse<long>>>Certidao(TributarioOperacaoRequest r,CancellationToken ct)=>Resposta(await _s.CriarAsync(Contexto(),"portal_contribuinte_certidao",r with{Status="PREPARATORIA"},ct));
[AllowAnonymous,HttpGet("certidoes/validar/{codigo}")]public async Task<ActionResult<ApiResponse<TributarioRegistroDto?>>>Validar(string codigo,CancellationToken ct)=>Resposta(await _s.ObterAsync(TenantId(),"portal_contribuinte_certidao",long.TryParse(codigo,out var id)?id:0,ct));
[HttpPost("parcelamentos/solicitar")]public async Task<ActionResult<ApiResponse<long>>>Parcelar(TributarioOperacaoRequest r,CancellationToken ct)=>Resposta(await _s.CriarAsync(Contexto(),"portal_contribuinte_parcelamento_solicitacao",r,ct));
[HttpGet("protocolos/{codigo}")]public async Task<ActionResult<ApiResponse<TributarioRegistroDto?>>>Protocolo(string codigo,CancellationToken ct)=>Resposta(await _s.ObterAsync(TenantId(),"portal_contribuinte_protocolo",long.TryParse(codigo,out var id)?id:0,ct));
[HttpPost("solicitacoes/atualizacao-cadastral")]public async Task<ActionResult<ApiResponse<long>>>Atualizacao(TributarioOperacaoRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Justificativa))throw new ArgumentException("Justificativa é obrigatória.");return Resposta(await _s.CriarAsync(Contexto(),"portal_contribuinte_solicitacao",r,ct));}}
