using Microsoft.AspNetCore.Mvc;
using Sigov.Api.Middlewares;
using Sigov.Application.Common;
using Sigov.Application.Saneamento;
using Sigov.Domain.Common;

namespace Sigov.Api.Controllers;

[ApiController]
[RequireModule("saneamento")]
public abstract class SaneamentoApiControllerBase : ControllerBase
{
    protected ActionResult<ApiResponse<T>> FromResult<T>(Result<T> result)
    {
        if (result.IsSuccess) return Ok(ApiResponse<T>.Ok(result.Value!));
        var error = result.Error ?? "Falha na operação.";
        return error.Contains("permiss", StringComparison.OrdinalIgnoreCase) || error.Contains("módulo", StringComparison.OrdinalIgnoreCase) ? StatusCode(StatusCodes.Status403Forbidden, ApiResponse<T>.Fail(error)) : BadRequest(ApiResponse<T>.Fail(error));
    }
    protected ActionResult<ApiResponse<object>> FromResult(Result result)
    {
        if (result.IsSuccess) return Ok(ApiResponse<object>.Ok(new { }));
        var error = result.Error ?? "Falha na operação.";
        return error.Contains("permiss", StringComparison.OrdinalIgnoreCase) || error.Contains("módulo", StringComparison.OrdinalIgnoreCase) ? StatusCode(StatusCodes.Status403Forbidden, ApiResponse<object>.Fail(error)) : BadRequest(ApiResponse<object>.Fail(error));
    }
}

[Route("api/saneamento/consumidores")]
public sealed class SaneamentoConsumidoresController : SaneamentoApiControllerBase { private readonly ISaneamentoConsumidorService _s; public SaneamentoConsumidoresController(ISaneamentoConsumidorService s)=>_s=s; [HttpGet] public async Task<ActionResult<ApiResponse<PagedResult<SaneamentoConsumidorResponse>>>> Listar([FromQuery] SaneamentoConsumidorFiltro f,CancellationToken ct)=>FromResult(await _s.ListarAsync(f,ct)); [HttpGet("{id:long}")] public async Task<ActionResult<ApiResponse<SaneamentoConsumidorResponse>>> Obter(long id,[FromQuery] bool completo,CancellationToken ct)=>FromResult(await _s.ObterAsync(id,completo,ct)); [HttpPost] public async Task<ActionResult<ApiResponse<long>>> Criar([FromBody] SaneamentoConsumidorCreateRequest r,CancellationToken ct)=>FromResult(await _s.CriarAsync(r,ct)); [HttpPut("{id:long}")] public async Task<ActionResult<ApiResponse<object>>> Atualizar(long id,[FromBody] SaneamentoConsumidorUpdateRequest r,CancellationToken ct)=>FromResult(await _s.AtualizarAsync(id,r,ct)); [HttpDelete("{id:long}")] public async Task<ActionResult<ApiResponse<object>>> Excluir(long id,CancellationToken ct)=>FromResult(await _s.ExcluirAsync(id,ct)); }
[Route("api/saneamento/ligacoes")]
public sealed class SaneamentoLigacoesController : SaneamentoApiControllerBase { private readonly ILigacaoSaneamentoService _s; public SaneamentoLigacoesController(ILigacaoSaneamentoService s)=>_s=s; [HttpGet] public async Task<ActionResult<ApiResponse<PagedResult<LigacaoSaneamentoResponse>>>> Listar([FromQuery] SaneamentoFiltro f,CancellationToken ct)=>FromResult(await _s.ListarAsync(f,ct)); [HttpGet("{id:long}")] public async Task<ActionResult<ApiResponse<LigacaoSaneamentoResponse>>> Obter(long id,CancellationToken ct)=>FromResult(await _s.ObterAsync(id,ct)); [HttpPost] public async Task<ActionResult<ApiResponse<long>>> Criar([FromBody] LigacaoSaneamentoCreateRequest r,CancellationToken ct)=>FromResult(await _s.CriarAsync(r,ct)); [HttpPut("{id:long}")] public async Task<ActionResult<ApiResponse<object>>> Atualizar(long id,[FromBody] LigacaoSaneamentoUpdateRequest r,CancellationToken ct)=>FromResult(await _s.AtualizarAsync(id,r,ct)); [HttpDelete("{id:long}")] public async Task<ActionResult<ApiResponse<object>>> Excluir(long id,CancellationToken ct)=>FromResult(await _s.ExcluirAsync(id,ct)); }
[Route("api/saneamento/unidades-consumidoras")]
public sealed class SaneamentoUnidadesConsumidorasController : SaneamentoApiControllerBase { private readonly IUnidadeConsumidoraService _s; public SaneamentoUnidadesConsumidorasController(IUnidadeConsumidoraService s)=>_s=s; [HttpGet] public async Task<ActionResult<ApiResponse<PagedResult<UnidadeConsumidoraResponse>>>> Listar([FromQuery] UnidadeConsumidoraFiltro f,CancellationToken ct)=>FromResult(await _s.ListarAsync(f,ct)); [HttpGet("{id:long}")] public async Task<ActionResult<ApiResponse<UnidadeConsumidoraResponse>>> Obter(long id,CancellationToken ct)=>FromResult(await _s.ObterAsync(id,ct)); [HttpPost] public async Task<ActionResult<ApiResponse<long>>> Criar([FromBody] UnidadeConsumidoraCreateRequest r,CancellationToken ct)=>FromResult(await _s.CriarAsync(r,ct)); [HttpPut("{id:long}")] public async Task<ActionResult<ApiResponse<object>>> Atualizar(long id,[FromBody] UnidadeConsumidoraUpdateRequest r,CancellationToken ct)=>FromResult(await _s.AtualizarAsync(id,r,ct)); [HttpDelete("{id:long}")] public async Task<ActionResult<ApiResponse<object>>> Excluir(long id,CancellationToken ct)=>FromResult(await _s.ExcluirAsync(id,ct)); }
[Route("api/saneamento/hidrometros")]
public sealed class SaneamentoHidrometrosController : SaneamentoApiControllerBase { private readonly IHidrometroService _s; public SaneamentoHidrometrosController(IHidrometroService s)=>_s=s; [HttpGet] public async Task<ActionResult<ApiResponse<PagedResult<HidrometroResponse>>>> Listar([FromQuery] SaneamentoFiltro f,CancellationToken ct)=>FromResult(await _s.ListarAsync(f,ct)); [HttpPost] public async Task<ActionResult<ApiResponse<long>>> Criar([FromBody] HidrometroCreateRequest r,CancellationToken ct)=>FromResult(await _s.CriarAsync(r,ct)); [HttpPut("{id:long}")] public async Task<ActionResult<ApiResponse<object>>> Atualizar(long id,[FromBody] HidrometroUpdateRequest r,CancellationToken ct)=>FromResult(await _s.AtualizarAsync(id,r,ct)); [HttpDelete("{id:long}")] public async Task<ActionResult<ApiResponse<object>>> Excluir(long id,CancellationToken ct)=>FromResult(await _s.ExcluirAsync(id,ct)); }
[Route("api/saneamento/leituras")]
public sealed class SaneamentoLeiturasController : SaneamentoApiControllerBase { private readonly ILeituraConsumoService _s; public SaneamentoLeiturasController(ILeituraConsumoService s)=>_s=s; [HttpGet] public async Task<ActionResult<ApiResponse<PagedResult<LeituraConsumoResponse>>>> Listar([FromQuery] LeituraConsumoFiltro f,CancellationToken ct)=>FromResult(await _s.ListarAsync(f,ct)); [HttpPost] public async Task<ActionResult<ApiResponse<long>>> Criar([FromBody] LeituraConsumoCreateRequest r,CancellationToken ct)=>FromResult(await _s.CriarAsync(r,ct)); [HttpPost("{id:long}/gerar-fatura")] public async Task<ActionResult<ApiResponse<long>>> Gerar(long id,[FromBody] GerarFaturaPorLeituraRequest r,CancellationToken ct)=>FromResult(await _s.GerarFaturaAsync(id,r,ct)); }
[Route("api/saneamento/faturas")]
public sealed class SaneamentoFaturasController : SaneamentoApiControllerBase { private readonly IFaturaSaneamentoService _s; public SaneamentoFaturasController(IFaturaSaneamentoService s)=>_s=s; [HttpGet] public async Task<ActionResult<ApiResponse<PagedResult<FaturaSaneamentoResponse>>>> Listar([FromQuery] FaturaSaneamentoFiltro f,CancellationToken ct)=>FromResult(await _s.ListarAsync(f,ct)); [HttpGet("{id:long}")] public async Task<ActionResult<ApiResponse<FaturaSaneamentoResponse>>> Obter(long id,CancellationToken ct)=>FromResult(await _s.ObterAsync(id,ct)); [HttpPost] public async Task<ActionResult<ApiResponse<long>>> Criar([FromBody] FaturaSaneamentoCreateRequest r,CancellationToken ct)=>FromResult(await _s.CriarAsync(r,ct)); [HttpPost("{id:long}/cancelar")] public async Task<ActionResult<ApiResponse<object>>> Cancelar(long id,[FromBody] CancelarFaturaRequest r,CancellationToken ct)=>FromResult(await _s.CancelarAsync(id,r,ct)); [HttpPost("{id:long}/registrar-pagamento-dev")] public async Task<ActionResult<ApiResponse<ArrecadacaoSaneamentoResponse>>> PagarDev(long id,[FromBody] RegistrarPagamentoDevRequest r,CancellationToken ct)=>FromResult(await _s.RegistrarPagamentoDevAsync(id,r,ct)); }
[Route("api/saneamento/arrecadacoes")]
public sealed class SaneamentoArrecadacoesController : SaneamentoApiControllerBase { private readonly IArrecadacaoSaneamentoService _s; public SaneamentoArrecadacoesController(IArrecadacaoSaneamentoService s)=>_s=s; [HttpGet] public async Task<ActionResult<ApiResponse<PagedResult<ArrecadacaoSaneamentoResponse>>>> Listar([FromQuery] SaneamentoFiltro f,CancellationToken ct)=>FromResult(await _s.ListarAsync(f,ct)); [HttpPost] public async Task<ActionResult<ApiResponse<long>>> Criar([FromBody] ArrecadacaoSaneamentoCreateRequest r,CancellationToken ct)=>FromResult(await _s.CriarAsync(r,ct)); }
[Route("api/saneamento/parcelamentos")]
public sealed class SaneamentoParcelamentosController : SaneamentoApiControllerBase { private readonly IParcelamentoSaneamentoService _s; public SaneamentoParcelamentosController(IParcelamentoSaneamentoService s)=>_s=s; [HttpGet] public async Task<ActionResult<ApiResponse<PagedResult<ParcelamentoSaneamentoResponse>>>> Listar([FromQuery] SaneamentoFiltro f,CancellationToken ct)=>FromResult(await _s.ListarAsync(f,ct)); [HttpPost] public async Task<ActionResult<ApiResponse<long>>> Criar([FromBody] ParcelamentoSaneamentoCreateRequest r,CancellationToken ct)=>FromResult(await _s.CriarAsync(r,ct)); }
[Route("api/saneamento/ordens-servico")]
public sealed class SaneamentoOrdensServicoController : SaneamentoApiControllerBase { private readonly IOrdemServicoSaneamentoService _s; public SaneamentoOrdensServicoController(IOrdemServicoSaneamentoService s)=>_s=s; [HttpGet] public async Task<ActionResult<ApiResponse<PagedResult<OrdemServicoSaneamentoResponse>>>> Listar([FromQuery] OrdemServicoSaneamentoFiltro f,CancellationToken ct)=>FromResult(await _s.ListarAsync(f,ct)); [HttpGet("{id:long}")] public async Task<ActionResult<ApiResponse<OrdemServicoSaneamentoResponse>>> Obter(long id,CancellationToken ct)=>FromResult(await _s.ObterAsync(id,ct)); [HttpPost] public async Task<ActionResult<ApiResponse<long>>> Criar([FromBody] OrdemServicoSaneamentoCreateRequest r,CancellationToken ct)=>FromResult(await _s.CriarAsync(r,ct)); [HttpPut("{id:long}")] public async Task<ActionResult<ApiResponse<object>>> Atualizar(long id,[FromBody] OrdemServicoSaneamentoUpdateRequest r,CancellationToken ct)=>FromResult(await _s.AtualizarAsync(id,r,ct)); [HttpPost("{id:long}/executar")] public async Task<ActionResult<ApiResponse<object>>> Executar(long id,[FromBody] ExecutarOrdemServicoRequest r,CancellationToken ct)=>FromResult(await _s.ExecutarAsync(id,r,ct)); [HttpPost("{id:long}/cancelar")] public async Task<ActionResult<ApiResponse<object>>> Cancelar(long id,[FromBody] CancelarOrdemServicoRequest r,CancellationToken ct)=>FromResult(await _s.CancelarAsync(id,r,ct)); }
[Route("api/saneamento/equipes-campo")]
public sealed class SaneamentoEquipesCampoController : SaneamentoApiControllerBase { private readonly IEquipeCampoSaneamentoService _s; public SaneamentoEquipesCampoController(IEquipeCampoSaneamentoService s)=>_s=s; [HttpGet] public async Task<ActionResult<ApiResponse<PagedResult<EquipeCampoSaneamentoResponse>>>> Listar([FromQuery] SaneamentoFiltro f,CancellationToken ct)=>FromResult(await _s.ListarAsync(f,ct)); [HttpPost] public async Task<ActionResult<ApiResponse<long>>> Criar([FromBody] EquipeCampoSaneamentoCreateRequest r,CancellationToken ct)=>FromResult(await _s.CriarAsync(r,ct)); }
[Route("api/saneamento/laboratorio")]
public sealed class SaneamentoLaboratorioController : SaneamentoApiControllerBase { private readonly ILaboratorioSaneamentoService _s; public SaneamentoLaboratorioController(ILaboratorioSaneamentoService s)=>_s=s; [HttpGet("amostras")] public async Task<ActionResult<ApiResponse<PagedResult<LaboratorioAmostraResponse>>>> Listar([FromQuery] SaneamentoFiltro f,CancellationToken ct)=>FromResult(await _s.ListarAsync(f,ct)); [HttpPost("amostras")] public async Task<ActionResult<ApiResponse<long>>> Criar([FromBody] LaboratorioAmostraCreateRequest r,CancellationToken ct)=>FromResult(await _s.CriarAmostraAsync(r,ct)); [HttpPost("amostras/{id:long}/resultados")] public async Task<ActionResult<ApiResponse<long>>> Resultado(long id,[FromBody] LaboratorioResultadoCreateRequest r,CancellationToken ct)=>FromResult(await _s.CriarResultadoAsync(id,r,ct)); }
[Route("api/saneamento/rede")]
public sealed class SaneamentoRedeController : SaneamentoApiControllerBase { private readonly IRedeSaneamentoService _s; public SaneamentoRedeController(IRedeSaneamentoService s)=>_s=s; [HttpGet("trechos")] public async Task<ActionResult<ApiResponse<PagedResult<RedeSaneamentoTrechoResponse>>>> Listar([FromQuery] SaneamentoFiltro f,CancellationToken ct)=>FromResult(await _s.ListarAsync(f,ct)); [HttpPost("trechos")] public async Task<ActionResult<ApiResponse<long>>> Criar([FromBody] RedeSaneamentoTrechoCreateRequest r,CancellationToken ct)=>FromResult(await _s.CriarAsync(r,ct)); }
[Route("api/saneamento/dashboard")]
public sealed class SaneamentoDashboardController : SaneamentoApiControllerBase { private readonly ISaneamentoDashboardService _s; public SaneamentoDashboardController(ISaneamentoDashboardService s)=>_s=s; [HttpGet] public async Task<ActionResult<ApiResponse<SaneamentoDashboardResponse>>> Obter(CancellationToken ct)=>FromResult(await _s.ObterAsync(ct)); }
[Route("api/saneamento/export")]
public sealed class SaneamentoExportacaoController : SaneamentoApiControllerBase { private readonly ISaneamentoExportacaoService _s; public SaneamentoExportacaoController(ISaneamentoExportacaoService s)=>_s=s; [HttpGet("{recurso}.{formato}")] public async Task<IActionResult> Exportar(string recurso,string formato,CancellationToken ct){var r=await _s.ExportarAsync(recurso,formato,ct); if(r.IsFailure)return BadRequest(ApiResponse<object>.Fail(r.Error??"Falha na exportação.")); return File(r.Value??Array.Empty<byte>(),formato.Equals("json",StringComparison.OrdinalIgnoreCase)?"application/json":"text/csv",$"{recurso}.{formato}");} }
