using Microsoft.AspNetCore.Mvc;
using Sigov.Api.Middlewares;
using Sigov.Application.Common;
using Sigov.Application.Saude;
using Sigov.Domain.Common;

namespace Sigov.Api.Controllers;

[ApiController]
[RequireModule(SaudePermissoes.Modulo)]
[Produces("application/json")]
public abstract class SaudeApiControllerBase : ControllerBase
{
    protected ActionResult<ApiResponse<T>> FromResult<T>(Result<T> result)
    {
        if (result.IsSuccess) return Ok(ApiResponse<T>.Ok(result.Value!));
        var error = result.Error ?? "Falha na operação.";
        return error.Contains("permiss", StringComparison.OrdinalIgnoreCase) || error.Contains("403", StringComparison.OrdinalIgnoreCase) ? StatusCode(StatusCodes.Status403Forbidden, ApiResponse<T>.Fail(error)) : BadRequest(ApiResponse<T>.Fail(error));
    }
    protected ActionResult<ApiResponse<object>> FromResult(Result result)
    {
        if (result.IsSuccess) return Ok(ApiResponse<object>.Ok(new { }));
        var error = result.Error ?? "Falha na operação.";
        return error.Contains("permiss", StringComparison.OrdinalIgnoreCase) || error.Contains("403", StringComparison.OrdinalIgnoreCase) ? StatusCode(StatusCodes.Status403Forbidden, ApiResponse<object>.Fail(error)) : BadRequest(ApiResponse<object>.Fail(error));
    }
}

[Route("api/saude/unidades")]
public sealed class UnidadesSaudeController : SaudeApiControllerBase { private readonly IUnidadeSaudeService _s; public UnidadesSaudeController(IUnidadeSaudeService s)=>_s=s; [HttpGet] public async Task<ActionResult<ApiResponse<PagedResult<UnidadeSaudeResponse>>>> Listar([FromQuery] UnidadeSaudeFiltro f,CancellationToken ct)=>FromResult(await _s.ListarAsync(f,ct).ConfigureAwait(false)); [HttpGet("{id:long}")] public async Task<ActionResult<ApiResponse<UnidadeSaudeResponse>>> Obter(long id,CancellationToken ct)=>FromResult(await _s.ObterAsync(id,ct).ConfigureAwait(false)); [HttpPost] public async Task<ActionResult<ApiResponse<long>>> Criar([FromBody] UnidadeSaudeCreateRequest r,CancellationToken ct)=>FromResult(await _s.CriarAsync(r,ct).ConfigureAwait(false)); [HttpPut("{id:long}")] public async Task<ActionResult<ApiResponse<object>>> Atualizar(long id,[FromBody] UnidadeSaudeUpdateRequest r,CancellationToken ct)=>FromResult(await _s.AtualizarAsync(id,r,ct).ConfigureAwait(false)); [HttpDelete("{id:long}")] public async Task<ActionResult<ApiResponse<object>>> Excluir(long id,CancellationToken ct)=>FromResult(await _s.ExcluirAsync(id,ct).ConfigureAwait(false)); }
[Route("api/saude/profissionais")]
public sealed class ProfissionaisSaudeController : SaudeApiControllerBase { private readonly IProfissionalSaudeService _s; public ProfissionaisSaudeController(IProfissionalSaudeService s)=>_s=s; [HttpGet] public async Task<ActionResult<ApiResponse<PagedResult<ProfissionalSaudeResponse>>>> Listar([FromQuery] ProfissionalSaudeFiltro f,CancellationToken ct)=>FromResult(await _s.ListarAsync(f,ct).ConfigureAwait(false)); [HttpGet("{id:long}")] public async Task<ActionResult<ApiResponse<ProfissionalSaudeResponse>>> Obter(long id,CancellationToken ct)=>FromResult(await _s.ObterAsync(id,ct).ConfigureAwait(false)); [HttpPost] public async Task<ActionResult<ApiResponse<long>>> Criar([FromBody] ProfissionalSaudeCreateRequest r,CancellationToken ct)=>FromResult(await _s.CriarAsync(r,ct).ConfigureAwait(false)); [HttpPut("{id:long}")] public async Task<ActionResult<ApiResponse<object>>> Atualizar(long id,[FromBody] ProfissionalSaudeUpdateRequest r,CancellationToken ct)=>FromResult(await _s.AtualizarAsync(id,r,ct).ConfigureAwait(false)); [HttpDelete("{id:long}")] public async Task<ActionResult<ApiResponse<object>>> Excluir(long id,CancellationToken ct)=>FromResult(await _s.ExcluirAsync(id,ct).ConfigureAwait(false)); }
[Route("api/saude/pacientes")]
public sealed class PacientesController : SaudeApiControllerBase { private readonly IPacienteService _s; private readonly IProntuarioService _p; public PacientesController(IPacienteService s,IProntuarioService p){_s=s;_p=p;} [HttpGet] public async Task<ActionResult<ApiResponse<PagedResult<PacienteResumoResponse>>>> Listar([FromQuery] PacienteFiltro f,CancellationToken ct)=>FromResult(await _s.ListarAsync(f,ct).ConfigureAwait(false)); [HttpGet("{id:long}")] public async Task<ActionResult<ApiResponse<PacienteDetalheResponse>>> Obter(long id,CancellationToken ct)=>FromResult(await _s.ObterAsync(id,ct).ConfigureAwait(false)); [HttpPost] public async Task<ActionResult<ApiResponse<long>>> Criar([FromBody] PacienteCreateRequest r,CancellationToken ct)=>FromResult(await _s.CriarAsync(r,ct).ConfigureAwait(false)); [HttpPut("{id:long}")] public async Task<ActionResult<ApiResponse<object>>> Atualizar(long id,[FromBody] PacienteUpdateRequest r,CancellationToken ct)=>FromResult(await _s.AtualizarAsync(id,r,ct).ConfigureAwait(false)); [HttpDelete("{id:long}")] public async Task<ActionResult<ApiResponse<object>>> Excluir(long id,CancellationToken ct)=>FromResult(await _s.ExcluirAsync(id,ct).ConfigureAwait(false)); [HttpGet("{id:long}/prontuario")] public async Task<ActionResult<ApiResponse<ProntuarioResponse>>> Prontuario(long id,CancellationToken ct)=>FromResult(await _p.ObterPorPacienteAsync(id,ct).ConfigureAwait(false)); [HttpPut("{id:long}/prontuario")] public async Task<ActionResult<ApiResponse<object>>> AtualizarProntuario(long id,[FromBody] ProntuarioUpdateRequest r,CancellationToken ct)=>FromResult(await _p.AtualizarAsync(id,r,ct).ConfigureAwait(false)); }
[Route("api/saude/prontuarios")]
public sealed class ProntuariosController : SaudeApiControllerBase { private readonly IProntuarioService _s; public ProntuariosController(IProntuarioService s)=>_s=s; [HttpGet("paciente/{pacienteId:long}")] public async Task<ActionResult<ApiResponse<ProntuarioResponse>>> Obter(long pacienteId,CancellationToken ct)=>FromResult(await _s.ObterPorPacienteAsync(pacienteId,ct).ConfigureAwait(false)); [HttpPut("paciente/{pacienteId:long}")] public async Task<ActionResult<ApiResponse<object>>> Atualizar(long pacienteId,[FromBody] ProntuarioUpdateRequest r,CancellationToken ct)=>FromResult(await _s.AtualizarAsync(pacienteId,r,ct).ConfigureAwait(false)); }
[Route("api/saude/atendimentos")]
public sealed class AtendimentosSaudeController : SaudeApiControllerBase { private readonly IAtendimentoSaudeService _s; public AtendimentosSaudeController(IAtendimentoSaudeService s)=>_s=s; [HttpGet] public async Task<ActionResult<ApiResponse<PagedResult<AtendimentoSaudeResponse>>>> Listar([FromQuery] AtendimentoSaudeFiltro f,CancellationToken ct)=>FromResult(await _s.ListarAsync(f,ct).ConfigureAwait(false)); [HttpGet("{id:long}")] public async Task<ActionResult<ApiResponse<AtendimentoSaudeResponse>>> Obter(long id,CancellationToken ct)=>FromResult(await _s.ObterAsync(id,ct).ConfigureAwait(false)); [HttpPost] public async Task<ActionResult<ApiResponse<long>>> Criar([FromBody] AtendimentoSaudeCreateRequest r,CancellationToken ct)=>FromResult(await _s.CriarAsync(r,ct).ConfigureAwait(false)); [HttpPut("{id:long}")] public async Task<ActionResult<ApiResponse<object>>> Atualizar(long id,[FromBody] AtendimentoSaudeUpdateRequest r,CancellationToken ct)=>FromResult(await _s.AtualizarAsync(id,r,ct).ConfigureAwait(false)); [HttpPost("{id:long}/conduta")] public async Task<ActionResult<ApiResponse<object>>> Conduta(long id,[FromBody] RegistrarCondutaRequest r,CancellationToken ct)=>FromResult(await _s.RegistrarCondutaAsync(id,r,ct).ConfigureAwait(false)); [HttpPost("{id:long}/cancelar")] public async Task<ActionResult<ApiResponse<object>>> Cancelar(long id,CancellationToken ct)=>FromResult(await _s.CancelarAsync(id,ct).ConfigureAwait(false)); }
[Route("api/saude/agenda")]
public sealed class AgendasSaudeController : SaudeApiControllerBase { private readonly IAgendaSaudeService _s; public AgendasSaudeController(IAgendaSaudeService s)=>_s=s; [HttpGet] public async Task<ActionResult<ApiResponse<PagedResult<AgendaSaudeResponse>>>> Listar([FromQuery] AgendaSaudeFiltro f,CancellationToken ct)=>FromResult(await _s.ListarAsync(f,ct).ConfigureAwait(false)); [HttpPost] public async Task<ActionResult<ApiResponse<long>>> Criar([FromBody] AgendaSaudeCreateRequest r,CancellationToken ct)=>FromResult(await _s.CriarAsync(r,ct).ConfigureAwait(false)); [HttpPost("{id:long}/cancelar")] public async Task<ActionResult<ApiResponse<object>>> Cancelar(long id,CancellationToken ct)=>FromResult(await _s.CancelarAsync(id,ct).ConfigureAwait(false)); }
[Route("api/saude/farmacia")]
public sealed class FarmaciaController : SaudeApiControllerBase { private readonly IFarmaciaService _s; public FarmaciaController(IFarmaciaService s)=>_s=s; [HttpGet("produtos")] public async Task<ActionResult<ApiResponse<PagedResult<FarmaciaProdutoResponse>>>> Produtos([FromQuery] UnidadeSaudeFiltro f,CancellationToken ct)=>FromResult(await _s.ListarProdutosAsync(f,ct).ConfigureAwait(false)); [HttpPost("produtos")] public async Task<ActionResult<ApiResponse<long>>> CriarProduto([FromBody] FarmaciaProdutoCreateRequest r,CancellationToken ct)=>FromResult(await _s.CriarProdutoAsync(r,ct).ConfigureAwait(false)); [HttpGet("estoque")] public async Task<ActionResult<ApiResponse<PagedResult<FarmaciaEstoqueResponse>>>> Estoque([FromQuery] UnidadeSaudeFiltro f,CancellationToken ct)=>FromResult(await _s.ListarEstoqueAsync(f,ct).ConfigureAwait(false)); [HttpPost("dispensacoes")] public async Task<ActionResult<ApiResponse<long>>> Dispensar([FromBody] FarmaciaDispensacaoCreateRequest r,CancellationToken ct)=>FromResult(await _s.DispensarAsync(r,ct).ConfigureAwait(false)); }
[Route("api/saude/vacinacoes")]
public sealed class VacinacoesController : SaudeApiControllerBase { private readonly IVacinacaoService _s; public VacinacoesController(IVacinacaoService s)=>_s=s; [HttpGet] public async Task<ActionResult<ApiResponse<PagedResult<VacinacaoResponse>>>> Listar([FromQuery] PacienteFiltro f,CancellationToken ct)=>FromResult(await _s.ListarAsync(f,ct).ConfigureAwait(false)); [HttpPost] public async Task<ActionResult<ApiResponse<long>>> Criar([FromBody] VacinacaoCreateRequest r,CancellationToken ct)=>FromResult(await _s.CriarAsync(r,ct).ConfigureAwait(false)); }
[Route("api/saude/laboratorio")]
public sealed class LaboratorioController : SaudeApiControllerBase { private readonly ILaboratorioService _s; public LaboratorioController(ILaboratorioService s)=>_s=s; [HttpGet("exames")] public async Task<ActionResult<ApiResponse<PagedResult<LaboratorioExameResponse>>>> Listar([FromQuery] PacienteFiltro f,CancellationToken ct)=>FromResult(await _s.ListarAsync(f,ct).ConfigureAwait(false)); [HttpPost("exames")] public async Task<ActionResult<ApiResponse<long>>> Criar([FromBody] LaboratorioExameCreateRequest r,CancellationToken ct)=>FromResult(await _s.CriarAsync(r,ct).ConfigureAwait(false)); [HttpPost("exames/{id:long}/resultado")] public async Task<ActionResult<ApiResponse<object>>> Resultado(long id,[FromBody] LaboratorioResultadoRequest r,CancellationToken ct)=>FromResult(await _s.RegistrarResultadoAsync(id,r,ct).ConfigureAwait(false)); }
[Route("api/saude/regulacao")]
public sealed class RegulacaoController : SaudeApiControllerBase { private readonly IRegulacaoService _s; public RegulacaoController(IRegulacaoService s)=>_s=s; [HttpGet] public async Task<ActionResult<ApiResponse<PagedResult<RegulacaoSolicitacaoResponse>>>> Listar([FromQuery] PacienteFiltro f,CancellationToken ct)=>FromResult(await _s.ListarAsync(f,ct).ConfigureAwait(false)); [HttpPost] public async Task<ActionResult<ApiResponse<long>>> Criar([FromBody] RegulacaoSolicitacaoCreateRequest r,CancellationToken ct)=>FromResult(await _s.CriarAsync(r,ct).ConfigureAwait(false)); [HttpPost("{id:long}/alterar-status")] public async Task<ActionResult<ApiResponse<object>>> Status(long id,[FromBody] AlterarStatusRequest r,CancellationToken ct)=>FromResult(await _s.AlterarStatusAsync(id,r,ct).ConfigureAwait(false)); }
[Route("api/saude/acs")]
public sealed class AcsController : SaudeApiControllerBase { private readonly IAcsService _s; public AcsController(IAcsService s)=>_s=s; [HttpGet("microareas")] public async Task<ActionResult<ApiResponse<PagedResult<AcsMicroareaResponse>>>> Microareas([FromQuery] UnidadeSaudeFiltro f,CancellationToken ct)=>FromResult(await _s.ListarMicroareasAsync(f,ct).ConfigureAwait(false)); [HttpPost("microareas")] public async Task<ActionResult<ApiResponse<long>>> CriarMicroarea([FromBody] AcsMicroareaCreateRequest r,CancellationToken ct)=>FromResult(await _s.CriarMicroareaAsync(r,ct).ConfigureAwait(false)); [HttpGet("dispositivos")] public ActionResult<ApiResponse<object>> Dispositivos()=>Ok(ApiResponse<object>.Ok(new { items = Array.Empty<object>() })); [HttpPost("dispositivos")] public async Task<ActionResult<ApiResponse<long>>> CriarDispositivo([FromBody] AcsDispositivoCreateRequest r,CancellationToken ct)=>FromResult(await _s.CriarDispositivoAsync(r,ct).ConfigureAwait(false)); [HttpGet("domicilios")] public async Task<ActionResult<ApiResponse<PagedResult<AcsCadastroDomiciliarResponse>>>> Domicilios([FromQuery] UnidadeSaudeFiltro f,CancellationToken ct)=>FromResult(await _s.ListarDomiciliosAsync(f,ct).ConfigureAwait(false)); [HttpPost("domicilios")] public async Task<ActionResult<ApiResponse<long>>> CriarDomicilio([FromBody] AcsCadastroDomiciliarCreateRequest r,CancellationToken ct)=>FromResult(await _s.CriarDomicilioAsync(r,ct).ConfigureAwait(false)); [HttpGet("individuos")] public async Task<ActionResult<ApiResponse<PagedResult<AcsCadastroIndividualResponse>>>> Individuos([FromQuery] PacienteFiltro f,CancellationToken ct)=>FromResult(await _s.ListarIndividuosAsync(f,ct).ConfigureAwait(false)); [HttpPost("individuos")] public async Task<ActionResult<ApiResponse<long>>> CriarIndividuo([FromBody] AcsCadastroIndividualCreateRequest r,CancellationToken ct)=>FromResult(await _s.CriarIndividuoAsync(r,ct).ConfigureAwait(false)); [HttpGet("visitas")] public async Task<ActionResult<ApiResponse<PagedResult<AcsVisitaResponse>>>> Visitas([FromQuery] PacienteFiltro f,CancellationToken ct)=>FromResult(await _s.ListarVisitasAsync(f,ct).ConfigureAwait(false)); [HttpPost("visitas")] public async Task<ActionResult<ApiResponse<long>>> CriarVisita([FromBody] AcsVisitaCreateRequest r,CancellationToken ct)=>FromResult(await _s.RegistrarVisitaAsync(r,ct).ConfigureAwait(false)); }
[Route("api/saude/acs/sync")]
public sealed class AcsSyncController : SaudeApiControllerBase { private readonly IAcsSyncService _s; public AcsSyncController(IAcsSyncService s)=>_s=s; [HttpPost] public async Task<ActionResult<ApiResponse<AcsSyncLoteResponse>>> Processar([FromBody] AcsSyncLoteRequest r,CancellationToken ct)=>FromResult(await _s.ProcessarAsync(r,ct).ConfigureAwait(false)); [HttpGet("{loteId}")] public async Task<ActionResult<ApiResponse<AcsSyncLoteResponse>>> Obter(string loteId,CancellationToken ct)=>FromResult(await _s.ObterAsync(loteId,ct).ConfigureAwait(false)); }
[Route("api/saude/dashboard")]
public sealed class SaudeDashboardController : SaudeApiControllerBase { private readonly ISaudeDashboardService _s; public SaudeDashboardController(ISaudeDashboardService s)=>_s=s; [HttpGet] public async Task<ActionResult<ApiResponse<SaudeDashboardResponse>>> Obter(CancellationToken ct)=>FromResult(await _s.ObterAsync(ct).ConfigureAwait(false)); }
[Route("api/saude/export")]
public sealed class SaudeExportacaoController : SaudeApiControllerBase { private readonly ISaudeExportacaoService _s; public SaudeExportacaoController(ISaudeExportacaoService s)=>_s=s; [HttpGet("{recurso}.{formato}")] public async Task<IActionResult> Exportar(string recurso,string formato,CancellationToken ct){ var r=await _s.ExportarAsync(recurso,formato,ct).ConfigureAwait(false); if(r.IsFailure)return BadRequest(ApiResponse<object>.Fail(r.Error??"Falha na exportação.")); return File(r.Value??Array.Empty<byte>(), formato.Equals("json",StringComparison.OrdinalIgnoreCase)?"application/json":"text/csv", $"{recurso}.{formato}"); } }
