using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Sigov.Api.Middlewares;
using Sigov.Application.Common;
using Sigov.Application.Social;
using Sigov.Domain.Common;

namespace Sigov.Api.Controllers;

[ApiController]
[Authorize]
[RequireModule("social")]
public abstract class SocialApiControllerBase : ControllerBase
{
    protected ActionResult<ApiResponse<T>> FromResult<T>(Result<T> r)=>r.IsFailure?BadRequest(ApiResponse<T>.Fail(r.Error??"Falha.")):Ok(ApiResponse<T>.Ok(r.Value!));
    protected ActionResult<ApiResponse<object>> FromResult(Result r)=>r.IsFailure?BadRequest(ApiResponse<object>.Fail(r.Error??"Falha.")):Ok(ApiResponse<object>.Ok(new{}));
}
[Route("api/social/unidades")] public sealed class SocialUnidadesController:SocialApiControllerBase{private readonly ISocialUnidadeService _s; public SocialUnidadesController(ISocialUnidadeService s)=>_s=s; [HttpGet] public async Task<ActionResult<ApiResponse<PagedResult<SocialUnidadeResponse>>>> Listar([FromQuery]SocialUnidadeFiltro f,CancellationToken ct)=>FromResult(await _s.ListarAsync(f,ct)); [HttpGet("{id:long}")] public async Task<ActionResult<ApiResponse<SocialUnidadeResponse>>> Obter(long id,CancellationToken ct)=>FromResult(await _s.ObterAsync(id,ct)); [HttpPost] public async Task<ActionResult<ApiResponse<long>>> Criar(SocialUnidadeCreateRequest r,CancellationToken ct)=>FromResult(await _s.CriarAsync(r,ct)); [HttpPut("{id:long}")] public async Task<ActionResult<ApiResponse<object>>> Atualizar(long id,SocialUnidadeUpdateRequest r,CancellationToken ct)=>FromResult(await _s.AtualizarAsync(id,r,ct)); [HttpDelete("{id:long}")] public async Task<ActionResult<ApiResponse<object>>> Excluir(long id,CancellationToken ct)=>FromResult(await _s.ExcluirAsync(id,ct));}
[Route("api/social/familias")] public sealed class SocialFamiliasController:SocialApiControllerBase{private readonly ISocialFamiliaService _s; public SocialFamiliasController(ISocialFamiliaService s)=>_s=s; [HttpGet] public async Task<ActionResult<ApiResponse<PagedResult<SocialFamiliaResponse>>>> Listar([FromQuery]SocialFamiliaFiltro f,CancellationToken ct)=>FromResult(await _s.ListarAsync(f,ct)); [HttpGet("{id:long}")] public async Task<ActionResult<ApiResponse<SocialFamiliaResponse>>> Obter(long id,CancellationToken ct)=>FromResult(await _s.ObterAsync(id,ct)); [HttpPost] public async Task<ActionResult<ApiResponse<long>>> Criar(SocialFamiliaCreateRequest r,CancellationToken ct)=>FromResult(await _s.CriarAsync(r,ct)); [HttpPut("{id:long}")] public async Task<ActionResult<ApiResponse<object>>> Atualizar(long id,SocialFamiliaUpdateRequest r,CancellationToken ct)=>FromResult(await _s.AtualizarAsync(id,r,ct)); [HttpDelete("{id:long}")] public async Task<ActionResult<ApiResponse<object>>> Excluir(long id,CancellationToken ct)=>FromResult(await _s.ExcluirAsync(id,ct)); [HttpPost("{id:long}/composicao")] public async Task<ActionResult<ApiResponse<long>>> Composicao(long id,SocialComposicaoFamiliarRequest r,CancellationToken ct)=>FromResult(await _s.AdicionarComposicaoAsync(id,r,ct)); [HttpPost("{id:long}/vulnerabilidades")] public async Task<ActionResult<ApiResponse<long>>> Vulnerabilidade(long id,SocialVulnerabilidadeCreateRequest r,CancellationToken ct)=>FromResult(await _s.RegistrarVulnerabilidadeAsync(id,r,ct)); [HttpPost("{id:long}/cadastro")] public async Task<ActionResult<ApiResponse<long>>> Cadastro(long id,SocialCadastroCreateRequest r,CancellationToken ct)=>FromResult(await _s.CriarCadastroAsync(id,r,ct));}
[Route("api/social/pessoas")] public sealed class SocialPessoasController:SocialApiControllerBase{private readonly ISocialPessoaService _s; public SocialPessoasController(ISocialPessoaService s)=>_s=s; [HttpGet] public async Task<ActionResult<ApiResponse<PagedResult<SocialPessoaResponse>>>> Listar([FromQuery]SocialPessoaFiltro f,CancellationToken ct)=>FromResult(await _s.ListarAsync(f,ct)); [HttpGet("{id:long}")] public async Task<ActionResult<ApiResponse<SocialPessoaResponse>>> Obter(long id,CancellationToken ct)=>FromResult(await _s.ObterAsync(id,ct)); [HttpPost] public async Task<ActionResult<ApiResponse<long>>> Criar(SocialPessoaCreateRequest r,CancellationToken ct)=>FromResult(await _s.CriarAsync(r,ct)); [HttpPut("{id:long}")] public async Task<ActionResult<ApiResponse<object>>> Atualizar(long id,SocialPessoaUpdateRequest r,CancellationToken ct)=>FromResult(await _s.AtualizarAsync(id,r,ct)); [HttpDelete("{id:long}")] public async Task<ActionResult<ApiResponse<object>>> Excluir(long id,CancellationToken ct)=>FromResult(await _s.ExcluirAsync(id,ct));}
[Route("api/social/programas")] public sealed class SocialProgramasController:SocialApiControllerBase{private readonly ISocialProgramaService _s; public SocialProgramasController(ISocialProgramaService s)=>_s=s; [HttpGet] public async Task<ActionResult<ApiResponse<PagedResult<SocialProgramaResponse>>>> Listar([FromQuery]SocialFiltro f,CancellationToken ct)=>FromResult(await _s.ListarAsync(f,ct)); [HttpPost] public async Task<ActionResult<ApiResponse<long>>> Criar(SocialProgramaCreateRequest r,CancellationToken ct)=>FromResult(await _s.CriarAsync(r,ct)); [HttpPut("{id:long}")] public async Task<ActionResult<ApiResponse<object>>> Atualizar(long id,SocialProgramaCreateRequest r,CancellationToken ct)=>FromResult(await _s.AtualizarAsync(id,r,ct)); [HttpDelete("{id:long}")] public async Task<ActionResult<ApiResponse<object>>> Excluir(long id,CancellationToken ct)=>FromResult(await _s.ExcluirAsync(id,ct));}
[Route("api/social/beneficios")] public sealed class SocialBeneficiosController:SocialApiControllerBase{private readonly ISocialBeneficioService _s; public SocialBeneficiosController(ISocialBeneficioService s)=>_s=s; [HttpGet] public async Task<ActionResult<ApiResponse<PagedResult<SocialBeneficioResponse>>>> Listar([FromQuery]SocialFiltro f,CancellationToken ct)=>FromResult(await _s.ListarAsync(f,ct)); [HttpPost] public async Task<ActionResult<ApiResponse<long>>> Criar(SocialBeneficioCreateRequest r,CancellationToken ct)=>FromResult(await _s.CriarAsync(r,ct)); [HttpPut("{id:long}")] public async Task<ActionResult<ApiResponse<object>>> Atualizar(long id,SocialBeneficioCreateRequest r,CancellationToken ct)=>FromResult(await _s.AtualizarAsync(id,r,ct)); [HttpDelete("{id:long}")] public async Task<ActionResult<ApiResponse<object>>> Excluir(long id,CancellationToken ct)=>FromResult(await _s.ExcluirAsync(id,ct)); [HttpGet("concessoes")] public async Task<ActionResult<ApiResponse<PagedResult<SocialBeneficioConcessaoResponse>>>> Concessoes([FromQuery]SocialFiltro f,CancellationToken ct)=>FromResult(await _s.ListarConcessoesAsync(f,ct)); [HttpPost("concessoes")] public async Task<ActionResult<ApiResponse<long>>> Conceder(SocialBeneficioConcessaoCreateRequest r,CancellationToken ct)=>FromResult(await _s.ConcederAsync(r,ct)); [HttpPost("concessoes/{id:long}/autorizar")] public async Task<ActionResult<ApiResponse<object>>> Autorizar(long id,AutorizarBeneficioRequest r,CancellationToken ct)=>FromResult(await _s.AutorizarAsync(id,r,ct)); [HttpPost("concessoes/{id:long}/indeferir")] public async Task<ActionResult<ApiResponse<object>>> Indeferir(long id,IndeferirBeneficioRequest r,CancellationToken ct)=>FromResult(await _s.IndeferirAsync(id,r,ct)); [HttpPost("concessoes/{id:long}/entregar")] public async Task<ActionResult<ApiResponse<object>>> Entregar(long id,CancellationToken ct)=>FromResult(await _s.EntregarAsync(id,ct));}
[Route("api/social/atendimentos")] public sealed class SocialAtendimentosController:SocialApiControllerBase{private readonly ISocialAtendimentoService _s; public SocialAtendimentosController(ISocialAtendimentoService s)=>_s=s; [HttpGet] public async Task<ActionResult<ApiResponse<PagedResult<SocialAtendimentoResponse>>>> Listar([FromQuery]SocialAtendimentoFiltro f,CancellationToken ct)=>FromResult(await _s.ListarAsync(f,ct)); [HttpGet("{id:long}")] public async Task<ActionResult<ApiResponse<SocialAtendimentoResponse>>> Obter(long id,CancellationToken ct)=>FromResult(await _s.ObterAsync(id,ct)); [HttpPost] public async Task<ActionResult<ApiResponse<long>>> Criar(SocialAtendimentoCreateRequest r,CancellationToken ct)=>FromResult(await _s.CriarAsync(r,ct)); [HttpPost("{id:long}/encaminhamentos")] public async Task<ActionResult<ApiResponse<long>>> Encaminhar(long id,SocialEncaminhamentoCreateRequest r,CancellationToken ct)=>FromResult(await _s.EncaminharAsync(id,r,ct));}
[Route("api/social/visitas")] public sealed class SocialVisitasController:SocialApiControllerBase{private readonly ISocialVisitaService _s; public SocialVisitasController(ISocialVisitaService s)=>_s=s; [HttpGet] public async Task<ActionResult<ApiResponse<PagedResult<SocialVisitaResponse>>>> Listar([FromQuery]SocialVisitaFiltro f,CancellationToken ct)=>FromResult(await _s.ListarAsync(f,ct)); [HttpGet("{id:long}")] public async Task<ActionResult<ApiResponse<SocialVisitaResponse>>> Obter(long id,CancellationToken ct)=>FromResult(await _s.ObterAsync(id,ct)); [HttpPost] public async Task<ActionResult<ApiResponse<long>>> Criar(SocialVisitaCreateRequest r,CancellationToken ct)=>FromResult(await _s.CriarAsync(r,ct));}
[Route("api/social/pareceres")] public sealed class SocialPareceresController:SocialApiControllerBase{private readonly ISocialParecerService _s; public SocialPareceresController(ISocialParecerService s)=>_s=s; [HttpGet] public async Task<ActionResult<ApiResponse<PagedResult<SocialParecerResponse>>>> Listar([FromQuery]SocialFiltro f,CancellationToken ct)=>FromResult(await _s.ListarAsync(f,ct)); [HttpPost] public async Task<ActionResult<ApiResponse<long>>> Criar(SocialParecerCreateRequest r,CancellationToken ct)=>FromResult(await _s.CriarAsync(r,ct));}
[Route("api/social/acompanhamentos")] public sealed class SocialAcompanhamentosController:SocialApiControllerBase{private readonly ISocialAcompanhamentoService _s; public SocialAcompanhamentosController(ISocialAcompanhamentoService s)=>_s=s; [HttpGet] public async Task<ActionResult<ApiResponse<PagedResult<SocialAcompanhamentoResponse>>>> Listar([FromQuery]SocialFiltro f,CancellationToken ct)=>FromResult(await _s.ListarAsync(f,ct)); [HttpPost] public async Task<ActionResult<ApiResponse<long>>> Criar(SocialAcompanhamentoCreateRequest r,CancellationToken ct)=>FromResult(await _s.CriarAsync(r,ct)); [HttpPost("{id:long}/encerrar")] public async Task<ActionResult<ApiResponse<object>>> Encerrar(long id,CancellationToken ct)=>FromResult(await _s.EncerrarAsync(id,ct));}
[Route("api/social/vigilancia")] public sealed class SocialVigilanciaController:SocialApiControllerBase{private readonly ISocialVigilanciaService _s; public SocialVigilanciaController(ISocialVigilanciaService s)=>_s=s; [HttpGet("indicadores")] public async Task<ActionResult<ApiResponse<PagedResult<object>>>> Indicadores([FromQuery]SocialFiltro f,CancellationToken ct)=>FromResult(await _s.ListarIndicadoresAsync(f,ct)); [HttpPost("indicadores")] public async Task<ActionResult<ApiResponse<long>>> CriarIndicador(SocialVigilanciaIndicadorCreateRequest r,CancellationToken ct)=>FromResult(await _s.CriarIndicadorAsync(r,ct)); [HttpGet("ocorrencias")] public async Task<ActionResult<ApiResponse<PagedResult<object>>>> Ocorrencias([FromQuery]SocialFiltro f,CancellationToken ct)=>FromResult(await _s.ListarOcorrenciasAsync(f,ct)); [HttpPost("ocorrencias")] public async Task<ActionResult<ApiResponse<long>>> CriarOcorrencia(SocialVigilanciaOcorrenciaCreateRequest r,CancellationToken ct)=>FromResult(await _s.CriarOcorrenciaAsync(r,ct));}
[Route("api/social/dashboard")] public sealed class SocialDashboardController:SocialApiControllerBase{private readonly ISocialDashboardService _s; public SocialDashboardController(ISocialDashboardService s)=>_s=s; [HttpGet] public async Task<ActionResult<ApiResponse<SocialDashboardResponse>>> Obter(CancellationToken ct)=>FromResult(await _s.ObterAsync(ct));}
[Route("api/social/export")] public sealed class SocialExportacaoController:SocialApiControllerBase{private readonly ISocialExportacaoService _s; public SocialExportacaoController(ISocialExportacaoService s)=>_s=s; [HttpGet("{recurso}.{formato}")] public async Task<IActionResult> Exportar(string recurso,string formato,CancellationToken ct){var r=await _s.ExportarAsync(recurso,formato,ct); if(r.IsFailure)return BadRequest(ApiResponse<object>.Fail(r.Error??"Falha.")); return File(r.Value??Array.Empty<byte>(),formato.Equals("json",StringComparison.OrdinalIgnoreCase)?"application/json":"text/csv",$"{recurso}.{formato}");}}
