using Microsoft.AspNetCore.Mvc; using Sigov.Api.Contracts; using Sigov.Application.Abstractions; using Sigov.Application.Common; using Sigov.Application.Tributario.TributarioAvancado;
namespace Sigov.Api.Controllers;
[ApiController,Route("api/tributario/fiscalizacao")]
public sealed class TributarioFiscalizacaoController:TributarioAvancadoControllerBase { readonly ITributarioFiscalizacaoService _s; public TributarioFiscalizacaoController(ITributarioFiscalizacaoService s,ICurrentTenant t,ICurrentUser u):base(t,u)=>_s=s;
[HttpGet("dashboard")]public async Task<ActionResult<ApiResponse<TributarioDashboardDto>>>Dashboard(CancellationToken ct)=>Resposta(await _s.DashboardAsync(TenantId(),"tributario_fiscalizacao_ordem",ct));
[HttpGet("ordens")]public async Task<ActionResult<ApiResponse<PagedResult<TributarioRegistroDto>>>>Ordens([FromQuery]int pagina=1,CancellationToken ct=default)=>Resposta(await _s.ListarAsync(TenantId(),"tributario_fiscalizacao_ordem",pagina,30,ct));
[HttpPost("ordens")]public async Task<ActionResult<ApiResponse<long>>>Criar(TributarioOperacaoRequest r,CancellationToken ct)=>Resposta(await _s.CriarAsync(Contexto(),"tributario_fiscalizacao_ordem",r,ct));
[HttpGet("ordens/{id:long}")]public async Task<ActionResult<ApiResponse<TributarioRegistroDto?>>>Obter(long id,CancellationToken ct)=>Resposta(await _s.ObterAsync(TenantId(),"tributario_fiscalizacao_ordem",id,ct));
[HttpPost("ordens/{id:long}/iniciar")]public Task<ActionResult<ApiResponse<bool>>>Iniciar(long id,CancellationToken ct)=>Status(id,"tributario_fiscalizacao_ordem","ABERTA",null,ct);
[HttpPost("ordens/{id:long}/diligencia")]public Task<ActionResult<ApiResponse<long>>>Diligencia(long id,TributarioOperacaoRequest r,CancellationToken ct)=>CriarFilho(id,"tributario_fiscalizacao_diligencia",r,ct);
[HttpPost("ordens/{id:long}/notificar")]public Task<ActionResult<ApiResponse<long>>>Notificar(long id,TributarioOperacaoRequest r,CancellationToken ct)=>CriarFilho(id,"tributario_fiscalizacao_notificacao",r,ct);
[HttpPost("ordens/{id:long}/auto-infracao")]public Task<ActionResult<ApiResponse<long>>>Auto(long id,TributarioOperacaoRequest r,CancellationToken ct)=>CriarFilho(id,"tributario_fiscalizacao_auto_infracao",r,ct);
[HttpPost("autos/{id:long}/defesa")]public Task<ActionResult<ApiResponse<long>>>Defesa(long id,TributarioOperacaoRequest r,CancellationToken ct)=>CriarFilho(id,"tributario_fiscalizacao_defesa",r,ct);
[HttpPost("autos/{id:long}/julgar")]public Task<ActionResult<ApiResponse<long>>>Julgar(long id,TributarioOperacaoRequest r,CancellationToken ct)=>CriarFilho(id,"tributario_fiscalizacao_julgamento",r,ct);
[HttpPost("ordens/{id:long}/encerrar")]public Task<ActionResult<ApiResponse<bool>>>Encerrar(long id,CancellationToken ct)=>Status(id,"tributario_fiscalizacao_ordem","ENCERRADA",null,ct);
[HttpPost("ordens/{id:long}/cancelar")]public Task<ActionResult<ApiResponse<bool>>>Cancelar(long id,TributarioCarneAtualizarStatusRequest r,CancellationToken ct)=>Status(id,"tributario_fiscalizacao_ordem","CANCELADA",r.Justificativa,ct);
[HttpGet("simples-divergencias")]public Task<ActionResult<ApiResponse<PagedResult<TributarioRegistroDto>>>>Simples(CancellationToken ct)=>Lista("tributario_simples_divergencia",ct);
[HttpGet("iss-apuracoes")]public Task<ActionResult<ApiResponse<PagedResult<TributarioRegistroDto>>>>Iss(CancellationToken ct)=>Lista("tributario_iss_apuracao",ct);
[HttpGet("relatorios/produtividade")]public async Task<ActionResult<ApiResponse<TributarioDashboardDto>>>Produtividade(CancellationToken ct)=>Resposta(await _s.DashboardAsync(TenantId(),"tributario_fiscalizacao_ordem",ct));
async Task<ActionResult<ApiResponse<long>>>CriarFilho(long id,string tabela,TributarioOperacaoRequest r,CancellationToken ct)=>Resposta(await _s.CriarAsync(Contexto(),tabela,r with{ReferenciaId=id},ct)); async Task<ActionResult<ApiResponse<bool>>>Status(long id,string tabela,string status,string? j,CancellationToken ct)=>Resposta(await _s.AlterarStatusAsync(Contexto(),tabela,id,status,j,ct)); async Task<ActionResult<ApiResponse<PagedResult<TributarioRegistroDto>>>>Lista(string t,CancellationToken ct)=>Resposta(await _s.ListarAsync(TenantId(),t,1,100,ct));}
