using Microsoft.AspNetCore.Mvc; using Sigov.Api.Contracts; using Sigov.Application.Abstractions; using Sigov.Application.Common; using Sigov.Application.Tributario.TributarioAvancado;
namespace Sigov.Api.Controllers;
[ApiController,Route("api/tributario/carnes-boletos")]
public sealed class TributarioCarnesBoletosController:TributarioAvancadoControllerBase { readonly ITributarioCarnesBoletosService _s; readonly ITributarioCarneArquivoService _arquivo; public TributarioCarnesBoletosController(ITributarioCarnesBoletosService s,ITributarioCarneArquivoService arquivo,ICurrentTenant t,ICurrentUser u):base(t,u){_s=s;_arquivo=arquivo;}
[HttpGet("dashboard")]public async Task<ActionResult<ApiResponse<TributarioDashboardDto>>>Dashboard(CancellationToken ct)=>Resposta(await _s.DashboardAsync(TenantId(),"tributario_carne_emissao",ct));
[HttpGet("emissoes")]public async Task<ActionResult<ApiResponse<PagedResult<TributarioRegistroDto>>>>Emissoes([FromQuery]int pagina=1,[FromQuery]int tamanho=20,CancellationToken ct=default)=>Resposta(await _s.ListarAsync(TenantId(),"tributario_carne_emissao",pagina,tamanho,ct));
[HttpPost("emissoes")]public async Task<ActionResult<ApiResponse<long>>>Criar(TributarioOperacaoRequest r,CancellationToken ct)=>Resposta(await _s.CriarAsync(Contexto(),"tributario_carne_emissao",r,ct));
[HttpGet("emissoes/{id:long}")]public async Task<ActionResult<ApiResponse<TributarioRegistroDto?>>>Obter(long id,CancellationToken ct)=>Resposta(await _s.ObterAsync(TenantId(),"tributario_carne_emissao",id,ct));
[HttpPost("emissoes/{id:long}/gerar-itens")]public async Task<ActionResult<ApiResponse<long>>>GerarItens(long id,TributarioOperacaoRequest r,CancellationToken ct)=>Resposta(await _s.CriarAsync(Contexto(),"tributario_carne_emissao",r with{ReferenciaId=id,Status="GERADO"},ct));
[HttpPost("emissoes/{id:long}/gerar-arquivo")]public async Task<ActionResult<ApiResponse<object>>>GerarArquivo(long id,CancellationToken ct){var b=await _arquivo.GerarCsvAsync(TenantId(),id,ct);return Resposta<object>(new{id,bytes=b.Length,status="ARQUIVO_GERADO"});}
[HttpGet("emissoes/{id:long}/arquivo-csv")]public async Task<IActionResult>Csv(long id,CancellationToken ct)=>File(await _arquivo.GerarCsvAsync(TenantId(),id,ct),"text/csv",$"carne-{id}-dados-mascarados.csv");
[HttpPost("emissoes/{id:long}/enviar-producao")]public async Task<ActionResult<ApiResponse<bool>>>Producao(long id,CancellationToken ct)=>Resposta(await _s.AlterarStatusAsync(Contexto(),"tributario_carne_emissao",id,"ENVIADO_PRODUCAO",null,ct));
[HttpPost("producao/{id:long}/atualizar-status")]public async Task<ActionResult<ApiResponse<bool>>>Status(long id,TributarioCarneAtualizarStatusRequest r,CancellationToken ct)=>Resposta(await _s.AlterarStatusAsync(Contexto(),"tributario_carne_producao",id,r.Status,r.Justificativa,ct));
[HttpGet("entregas")]public async Task<ActionResult<ApiResponse<PagedResult<TributarioRegistroDto>>>>Entregas([FromQuery]int pagina=1,CancellationToken ct=default)=>Resposta(await _s.ListarAsync(TenantId(),"tributario_carne_entrega",pagina,50,ct));
[HttpPost("entregas/{id:long}/registrar")]public async Task<ActionResult<ApiResponse<bool>>>Entrega(long id,TributarioCarneRegistrarEntregaRequest r,CancellationToken ct)=>Resposta(await _s.AlterarStatusAsync(Contexto(),"tributario_carne_entrega",id,r.Status,r.Motivo,ct));
[HttpGet("relatorios/entrega")]public async Task<ActionResult<ApiResponse<TributarioDashboardDto>>>Relatorio(CancellationToken ct)=>Resposta(await _s.DashboardAsync(TenantId(),"tributario_carne_entrega",ct));
[HttpGet("relatorios/exportar-csv")]public async Task<IActionResult>RelatorioCsv([FromQuery]long emissaoId,CancellationToken ct)=>File(await _arquivo.GerarCsvAsync(TenantId(),emissaoId,ct),"text/csv","entregas-carne.csv");}
