using System.Text;
using Dapper;
using Npgsql;
using Sigov.Application.Convenios;
using Sigov.Infrastructure.Persistence.Dapper;

namespace Sigov.Infrastructure.Convenios;

public sealed class ConvenioRepository(DapperContext db):IConvenioRepository
{
    private sealed record Spec(string Table,string Code,string Description,string Status,string[] Fields);
    private static readonly Dictionary<string,Spec> Specs=new(StringComparer.OrdinalIgnoreCase)
    {
        ["Orgaos"]=new("convenio_orgao_concedente","nome","coalesce(sigla,nome)","status",["cnpj","esfera","sigla","contato_nome","contato_email","contato_telefone"]),
        ["Programas"]=new("convenio_programa","codigo","nome","status",["orgao_concedente_id","finalidade","area","data_inicio","data_fim"]),
        ["Emendas"]=new("convenio_emenda","numero_emenda","parlamentar_nome","status",["parlamentar_partido","esfera","ano","area","valor_previsto","valor_aprovado","observacao"]),
        ["Instrumentos"]=new("convenio_instrumento","numero_instrumento","objeto","status",["tipo","orgao_concedente_id","programa_id","emenda_id","valor_global","valor_repasse","valor_contrapartida","data_assinatura","vigencia_inicio","vigencia_fim","responsavel_nome","responsavel_cpf","observacao"]),
        ["Projetos"]=new("convenio_projeto","nome","objetivo","status",["instrumento_id","justificativa","publico_alvo","local_execucao","unidade_responsavel","data_inicio","data_fim_prevista","data_fim_real","percentual_execucao"]),
        ["Metas"]=new("convenio_meta","numero","descricao","status",["projeto_id","indicador","unidade_medida","quantidade_prevista","quantidade_executada"]),
        ["Etapas"]=new("convenio_etapa","numero","descricao","status",["meta_id","data_inicio","data_fim_prevista","data_fim_real","valor_previsto","valor_executado","observacao"]),
        ["ContasBancarias"]=new("convenio_conta_bancaria","conta","banco||' / '||agencia","status",["instrumento_id","banco","agencia","tipo_conta","saldo_inicial","saldo_atual","observacao"]),
        ["Repasses"]=new("convenio_repasse","numero_repasse","fonte_recurso","status",["instrumento_id","conta_bancaria_id","data_repasse","valor","observacao"]),
        ["Despesas"]=new("convenio_despesa","numero_documento","fornecedor_nome||' — '||descricao","status",["instrumento_id","projeto_id","etapa_id","conta_bancaria_id","fornecedor_nome","fornecedor_documento","descricao","data_despesa","data_pagamento","valor","natureza_despesa","observacao"]),
        ["Contrapartidas"]=new("convenio_contrapartida","tipo","descricao","status",["instrumento_id","valor_previsto","valor_realizado","data_realizacao"]),
        ["Acompanhamentos"]=new("convenio_acompanhamento","data_acompanhamento::text","resumo","status",["projeto_id","data_acompanhamento","responsavel_nome","percentual_fisico","percentual_financeiro","risco","providencias"]),
        ["PrestacoesContas"]=new("convenio_prestacao_contas","numero_prestacao","tipo","status",["instrumento_id","periodo_inicio","periodo_fim","data_envio","valor_prestado","valor_aprovado","parecer_resumo"]),
        ["Diligencias"]=new("convenio_diligencia","numero_diligencia","descricao","status",["prestacao_contas_id","data_recebimento","prazo_resposta","data_resposta","resposta"]),
        ["Documentos"]=new("convenio_documento_referencia","coalesce(numero_documento,titulo)","titulo","status",["instrumento_id","projeto_id","prestacao_contas_id","tipo_documento","data_documento","observacao"]),
        ["Auditoria"]=new("convenio_auditoria","id::text","tabela||' — '||acao","acao",[])
    };
    public async Task<ConvenioDashboard> DashboardAsync(ConvenioContexto c,CancellationToken ct){using var cn=db.CreateConnection();const string sql="""select
      (select count(*) from sigov.convenio_instrumento where tenant_id=@TenantId and entity_id=@EntityId and deleted_at is null and status='ATIVO' and vigencia_fim>=current_date) InstrumentosAtivos,
      (select count(*) from sigov.convenio_instrumento where tenant_id=@TenantId and entity_id=@EntityId and deleted_at is null and status='ATIVO' and vigencia_fim between current_date and current_date+60) InstrumentosVencendo,
      (select count(*) from sigov.convenio_instrumento where tenant_id=@TenantId and entity_id=@EntityId and deleted_at is null and vigencia_fim<current_date and status not in('ENCERRADO','CANCELADO')) InstrumentosVencidos,
      (select coalesce(sum(valor_global),0) from sigov.convenio_instrumento where tenant_id=@TenantId and entity_id=@EntityId and deleted_at is null and status='ATIVO') ValorGlobalExecucao,
      (select coalesce(sum(valor),0) from sigov.convenio_repasse where tenant_id=@TenantId and entity_id=@EntityId and deleted_at is null) ValorRepassado,
      (select coalesce(sum(valor),0) from sigov.convenio_despesa where tenant_id=@TenantId and entity_id=@EntityId and deleted_at is null and status='PAGA') ValorExecutado,
      (select count(*) from sigov.convenio_projeto where tenant_id=@TenantId and entity_id=@EntityId and deleted_at is null and data_fim_prevista<current_date and status<>'CONCLUIDO') ProjetosAtrasados,
      (select count(*) from sigov.convenio_meta where tenant_id=@TenantId and entity_id=@EntityId and deleted_at is null and status not in('CONCLUIDA','CANCELADA')) MetasPendentes,
      (select count(*) from sigov.convenio_prestacao_contas where tenant_id=@TenantId and entity_id=@EntityId and deleted_at is null and status not in('APROVADA','CANCELADA')) PrestacoesPendentes,
      (select count(*) from sigov.convenio_diligencia where tenant_id=@TenantId and entity_id=@EntityId and deleted_at is null and prazo_resposta<current_date and status<>'RESPONDIDA') DiligenciasVencidas,
      (select count(*) from sigov.convenio_emenda where tenant_id=@TenantId and entity_id=@EntityId and deleted_at is null and ano=extract(year from current_date)) EmendasAno,
      (select coalesce(sum(saldo_atual),0) from sigov.convenio_conta_bancaria where tenant_id=@TenantId and entity_id=@EntityId and deleted_at is null and status='ATIVA') SaldoContas""";return await cn.QuerySingleAsync<ConvenioDashboard>(new CommandDefinition(sql,c,cancellationToken:ct));}
    public async Task<ConvenioPagina> ListarAsync(ConvenioContexto c,string recurso,ConvenioFiltro f,CancellationToken ct){var s=Get(recurso);using var cn=db.CreateConnection();var deleted=recurso.Equals("Auditoria",StringComparison.OrdinalIgnoreCase)?"true":"deleted_at is null";var where=$"tenant_id=@TenantId and entity_id=@EntityId and {deleted} and (@Busca is null or cast({s.Code} as text) ilike '%'||@Busca||'%' or cast({s.Description} as text) ilike '%'||@Busca||'%') and (@Status is null or cast({s.Status} as text)=@Status) and (@Inicio is null or created_at::date>=@Inicio) and (@Fim is null or created_at::date<=@Fim)";var page=Math.Max(1,f.Pagina);var size=Math.Clamp(f.Tamanho,1,10000);var p=new{c.TenantId,c.EntityId,f.Busca,f.Status,f.Inicio,f.Fim,Limit=size,Offset=(page-1)*size};var total=await cn.ExecuteScalarAsync<long>($"select count(*) from sigov.{s.Table} where {where}",p);var rows=(await cn.QueryAsync<ConvenioRegistro>($"select id,cast({s.Code} as text) Codigo,cast({s.Description} as text) Descricao,cast({s.Status} as text) Status,created_at CriadoEm from sigov.{s.Table} where {where} order by created_at desc limit @Limit offset @Offset",p)).AsList();return new(rows,page,size,total);}
    public async Task<ConvenioRegistroRequest?> ObterAsync(ConvenioContexto c,string recurso,long id,CancellationToken ct){var s=Get(recurso);if(recurso.Equals("Auditoria",StringComparison.OrdinalIgnoreCase))return null;using var cn=db.CreateConnection();var fields=string.Join(',',s.Fields.Select(x=>$"cast({x} as text) as {x}"));var row=await cn.QuerySingleOrDefaultAsync($"select cast({s.Code} as text) Codigo,cast({s.Description} as text) Descricao,cast({s.Status} as text) Status{(fields.Length>0?","+fields:"")} from sigov.{s.Table} where id=@id and tenant_id=@TenantId and entity_id=@EntityId and deleted_at is null",new{id,c.TenantId,c.EntityId});if(row is null)return null;var d=(IDictionary<string,object>)row;string V(string n)=>d.FirstOrDefault(x=>x.Key.Equals(n,StringComparison.OrdinalIgnoreCase)).Value?.ToString()??"";var r=new ConvenioRegistroRequest{Codigo=V("Codigo"),Descricao=V("Descricao"),Status=V("Status")};foreach(var f in s.Fields)r.Campos[f]=V(f);return r;}
    public async Task<IReadOnlyList<ConvenioOpcao>> OpcoesAsync(ConvenioContexto c,string recurso,CancellationToken ct){var s=Get(recurso);using var cn=db.CreateConnection();return(await cn.QueryAsync<ConvenioOpcao>($"select id,cast({s.Code} as text)||' — '||cast({s.Description} as text) Rotulo from sigov.{s.Table} where tenant_id=@TenantId and entity_id=@EntityId and deleted_at is null order by 2 limit 500",c)).AsList();}
    public async Task<long> SalvarAsync(ConvenioContexto c,string recurso,ConvenioRegistroRequest r,long? id,CancellationToken ct){var s=Get(recurso);if(recurso.Equals("Auditoria",StringComparison.OrdinalIgnoreCase))throw new ArgumentException("Recurso somente para consulta.");var values=new Dictionary<string,object?>();var code=Simple(s.Code);var description=Simple(s.Description);if(code is not null)values[code]=r.Codigo.Trim();if(description is not null&&description!=code)values[description]=r.Descricao.Trim();values[s.Status]=r.Status;foreach(var pair in r.Campos){if(!s.Fields.Contains(pair.Key,StringComparer.Ordinal))throw new ArgumentException("Campo não permitido.");values[pair.Key]=string.IsNullOrWhiteSpace(pair.Value)?null:pair.Value.Trim();}using var cn=db.CreateConnection();cn.Open();using var tx=cn.BeginTransaction();foreach(var pair in values.Where(x=>x.Key.EndsWith("_id")&&x.Value is not null)){if(!long.TryParse(pair.Value?.ToString(),out var rid)||!await RelationExists(c,pair.Key,rid,cn,tx,ct))throw new ArgumentException("Relacionamento inválido ou fora do contexto atual.");}var dp=new DynamicParameters(new{c.TenantId,c.EntityId,id});var cols=new List<string>{"tenant_id","entity_id"};var expr=new List<string>{"@TenantId","@EntityId"};var sets=new List<string>();var i=0;foreach(var pair in values){var n=$"v{++i}";dp.Add(n,pair.Value);var e=Cast(pair.Key,n);cols.Add(pair.Key);expr.Add(e);sets.Add($"{pair.Key}={e}");}try{long saved;if(id.HasValue){saved=await cn.ExecuteScalarAsync<long?>(new CommandDefinition($"update sigov.{s.Table} set {string.Join(',',sets)},updated_at=now() where id=@id and tenant_id=@TenantId and entity_id=@EntityId and deleted_at is null returning id",dp,tx,cancellationToken:ct))??throw new KeyNotFoundException("Registro não encontrado.");}else saved=await cn.ExecuteScalarAsync<long>(new CommandDefinition($"insert into sigov.{s.Table}({string.Join(',',cols)}) values({string.Join(',',expr)}) returning id",dp,tx,cancellationToken:ct));await cn.ExecuteAsync(new CommandDefinition("insert into sigov.convenio_auditoria(tenant_id,entity_id,tabela,registro_id,acao,usuario,dados_novos) values(@TenantId,@EntityId,@table,@saved,@action,@Usuario,jsonb_build_object('codigo',@Codigo,'descricao',@Descricao))",new{c.TenantId,c.EntityId,table=s.Table,saved,action=id.HasValue?"ALTERAR":"CRIAR",c.Usuario,r.Codigo,r.Descricao},tx,cancellationToken:ct));tx.Commit();return saved;}catch(PostgresException ex){throw new ArgumentException("Os dados violam a regra "+ex.ConstraintName,ex);}}
    public async Task ExcluirAsync(ConvenioContexto c,string recurso,long id,CancellationToken ct){var s=Get(recurso);using var cn=db.CreateConnection();cn.Open();using var tx=cn.BeginTransaction();if(await cn.ExecuteAsync(new CommandDefinition($"update sigov.{s.Table} set deleted_at=now(),updated_at=now() where id=@id and tenant_id=@TenantId and entity_id=@EntityId and deleted_at is null",new{id,c.TenantId,c.EntityId},tx,cancellationToken:ct))==0)throw new KeyNotFoundException();await cn.ExecuteAsync(new CommandDefinition("insert into sigov.convenio_auditoria(tenant_id,entity_id,tabela,registro_id,acao,usuario) values(@TenantId,@EntityId,@table,@id,'EXCLUIR',@Usuario)",new{c.TenantId,c.EntityId,table=s.Table,id,c.Usuario},tx,cancellationToken:ct));tx.Commit();}
    public async Task<byte[]> CsvAsync(ConvenioContexto c,string recurso,ConvenioFiltro f,CancellationToken ct){var p=await ListarAsync(c,recurso,f with{Pagina=1,Tamanho=10000},ct);var b=new StringBuilder("Identificação;Descrição;Status;Criado em\r\n");foreach(var x in p.Itens)b.AppendLine($"{Csv(x.Codigo)};{Csv(x.Descricao)};{Csv(x.Status)};{x.CriadoEm:O}");return new UTF8Encoding(true).GetBytes(b.ToString());}
    private static Spec Get(string r)=>Specs.TryGetValue(r,out var s)?s:throw new ArgumentException("Recurso inválido.");private static string? Simple(string x)=>x.All(c=>char.IsLetterOrDigit(c)||c=='_')?x:null;
    private static string Cast(string key,string p)=>key.EndsWith("_id")?$"cast(@{p} as bigint)":key is "ano"?$"cast(@{p} as integer)":key.StartsWith("data_")||key.StartsWith("vigencia_")||key.StartsWith("periodo_")?$"cast(@{p} as date)":key.StartsWith("valor_")||key.StartsWith("saldo_")||key.StartsWith("percentual_")||key.StartsWith("quantidade_")?$"cast(@{p} as numeric)":$"@{p}";
    private static string Csv(string? v){v??="";if(v.Length>0&&"=+-@\t\r".Contains(v[0]))v="'"+v;return '"'+v.Replace("\"","\"\"")+'"';}
    private static async Task<bool> RelationExists(ConvenioContexto c,string key,long id,System.Data.IDbConnection cn,System.Data.IDbTransaction tx,CancellationToken ct){var table=key switch{"orgao_concedente_id"=>"convenio_orgao_concedente","programa_id"=>"convenio_programa","emenda_id"=>"convenio_emenda","instrumento_id"=>"convenio_instrumento","projeto_id"=>"convenio_projeto","meta_id"=>"convenio_meta","etapa_id"=>"convenio_etapa","conta_bancaria_id"=>"convenio_conta_bancaria","prestacao_contas_id"=>"convenio_prestacao_contas",_=>throw new ArgumentException("Relacionamento desconhecido.")};return await cn.ExecuteScalarAsync<bool>(new CommandDefinition($"select exists(select 1 from sigov.{table} where id=@id and tenant_id=@TenantId and entity_id=@EntityId and deleted_at is null)",new{id,c.TenantId,c.EntityId},tx,cancellationToken:ct));}
}
