using System.Text;
using System.Text.Json;
using Dapper;
using Sigov.Application.Common;
using Sigov.Application.Educacao.Avancada;
using Sigov.Application.Health;
using Sigov.Infrastructure.Persistence.Dapper;
namespace Sigov.Infrastructure.Educacao.Avancada;
public sealed class EducacaoAvancadaRepository:IEducacaoTransporteEscolarRepository,IEducacaoTransporteDashboardService,IEducacaoTransporteRelatorioService,IEducacaoMerendaRepository,IEducacaoMerendaEstoqueService,IEducacaoMerendaCardapioService,IEducacaoMerendaRelatorioService,IEducacaoBibliotecaRepository,IEducacaoBibliotecaEmprestimoService,IEducacaoBibliotecaRelatorioService,IEducacaoIndicadoresRepository,IEducacaoFundebService,IEducacaoCustosService,IEducacaoEducacensoService,IEducacaoAvaliacaoMagisterioService
{
 static readonly HashSet<string> Recursos=new(StringComparer.Ordinal){"educacao_transporte_rota","educacao_transporte_rota_ponto","educacao_transporte_veiculo","educacao_transporte_motorista","educacao_transporte_aluno","educacao_transporte_viagem","educacao_transporte_frequencia","educacao_transporte_ocorrencia","educacao_transporte_custo","educacao_merenda_produto","educacao_merenda_fornecedor","educacao_merenda_estoque","educacao_merenda_movimento","educacao_merenda_cardapio","educacao_merenda_distribuicao","educacao_merenda_requisicao","educacao_merenda_consumo","educacao_biblioteca_acervo","educacao_biblioteca_exemplar","educacao_biblioteca_emprestimo","educacao_biblioteca_reserva","educacao_biblioteca_ocorrencia","educacao_biblioteca_digital_referencia","educacao_fundeb_parametro","educacao_fundeb_receita","educacao_fundeb_aplicacao","educacao_custo_centro","educacao_custo_lancamento","educacao_custo_rateio","educacao_indicador","educacao_indicador_valor","educacao_projecao_matricula","educacao_educacenso_lote","educacao_educacenso_inconsistencia","educacao_avaliacao_magisterio","educacao_avaliacao_resultado"};
 readonly DapperContext _context; readonly IDatabaseObjectInspector _inspector; public EducacaoAvancadaRepository(DapperContext context,IDatabaseObjectInspector inspector){_context=context;_inspector=inspector;}
 public async Task<PagedResult<EducacaoAvancadaRegistroDto>> ListarAsync(long tenantId,string recurso,EducacaoAvancadaFiltro f,CancellationToken ct){recurso=Recurso(recurso);var p=Math.Max(1,f.Pagina);var t=Math.Clamp(f.Tamanho,1,100);if(!await _inspector.TableExistsAsync("sigov",recurso,ct).ConfigureAwait(false))return PagedResult<EducacaoAvancadaRegistroDto>.Empty(p,t);var sql=$"select id as Id,codigo as Codigo,nome as Nome,status as Status,tipo as Tipo,descricao as Descricao,quantidade as Quantidade,valor as Valor,created_at as CreatedAt from sigov.{recurso} where tenant_id=@TenantId and is_deleted=false and (@EscolaId is null or escola_id=@EscolaId) and (@AnoLetivo is null or ano_letivo=@AnoLetivo) and (@Status is null or status=@Status) order by id desc limit @Tamanho offset @Offset;select count(1) from sigov.{recurso} where tenant_id=@TenantId and is_deleted=false and (@EscolaId is null or escola_id=@EscolaId) and (@AnoLetivo is null or ano_letivo=@AnoLetivo) and (@Status is null or status=@Status)";using var c=_context.CreateConnection();using var m=await c.QueryMultipleAsync(new CommandDefinition(sql,new{TenantId=tenantId,f.EscolaId,f.AnoLetivo,f.Status,Tamanho=t,Offset=(p-1)*t},cancellationToken:ct));var rows=(await m.ReadAsync<EducacaoAvancadaRegistroDto>()).ToList();return new(rows,p,t,await m.ReadSingleAsync<long>());}
 public async Task<long> CriarAsync(EducacaoAvancadaContext x,string recurso,EducacaoAvancadaOperacaoRequest r,CancellationToken ct){recurso=Recurso(recurso);Validar(recurso,r);using var c=_context.CreateConnection();var sql=$"insert into sigov.{recurso}(tenant_id,entidade_id,exercicio_id,ano_letivo,escola_id,aluno_id,referencia_id,codigo,nome,tipo,status,descricao,justificativa,turno,quantidade,valor,dados,auditoria,correlation_id,created_by) values(@TenantId,@EntidadeId,@ExercicioId,@AnoLetivo,@EscolaId,@AlunoId,@ReferenciaId,@Codigo,@Nome,@Tipo,@Status,@Descricao,@Justificativa,@Turno,@Quantidade,@Valor,@Dados::jsonb,jsonb_build_object('acao','CRIAR','em',now()),@CorrelationId,@UsuarioId) returning id";return await c.ExecuteScalarAsync<long>(new CommandDefinition(sql,new{x.TenantId,x.EntidadeId,x.ExercicioId,r.AnoLetivo,r.EscolaId,r.AlunoId,r.ReferenciaId,r.Codigo,r.Nome,r.Tipo,r.Status,r.Descricao,r.Justificativa,r.Turno,r.Quantidade,r.Valor,Dados=JsonSerializer.Serialize(r.Dados??new Dictionary<string,object?>()),CorrelationId=Guid.TryParse(x.CorrelationId,out var g)?g:Guid.NewGuid(),x.UsuarioId},cancellationToken:ct));}
 public async Task<bool> AlterarStatusAsync(EducacaoAvancadaContext x,string recurso,long id,string status,string? justificativa,CancellationToken ct){recurso=Recurso(recurso);if ((status is "CANCELADA" or "CANCELADO") && string.IsNullOrWhiteSpace(justificativa))throw new ArgumentException("Cancelamento exige justificativa.");using var c=_context.CreateConnection();return await c.ExecuteAsync(new CommandDefinition($"update sigov.{recurso} set status=@Status,justificativa=coalesce(@Justificativa,justificativa),updated_at=now(),updated_by=@UsuarioId,correlation_id=@CorrelationId,auditoria=auditoria||jsonb_build_object('acao','STATUS','status',@Status,'em',now()) where tenant_id=@TenantId and id=@Id and is_deleted=false",new{x.TenantId,Id=id,Status=status,Justificativa=justificativa,x.UsuarioId,CorrelationId=Guid.TryParse(x.CorrelationId,out var g)?g:Guid.NewGuid()},cancellationToken:ct))>0;}
 public async Task<EducacaoAvancadaDashboardDto> DashboardAsync(long tenantId,string recurso,CancellationToken ct){var page=await ListarAsync(tenantId,recurso,new EducacaoAvancadaFiltro(Tamanho:6),ct);var active=page.Items.LongCount(x=>x.Status is "ATIVA" or "ATIVO" or "PUBLICADO" or "DISPONIVEL" or "ABERTO");var pending=page.Items.LongCount(x=>x.Status is "RASCUNHO" or "PROGRAMADA" or "SOLICITADA");var alerts=page.Items.LongCount(x=>x.Status is "ATRASADO" or "SUSPENSA" or "COM_INCONSISTENCIA");return new(page.TotalItems,active,pending,alerts,page.Items);}
 public async Task<byte[]> ExportarCsvAsync(long tenantId,string recurso,CancellationToken ct){var r=await ListarAsync(tenantId,recurso,new EducacaoAvancadaFiltro(Tamanho:100),ct);var b=new StringBuilder("id;codigo;nome;tipo;status;valor\n");foreach(var x in r.Items)b.Append(x.Id).Append(';').Append(Limpar(x.Codigo)).Append(';').Append(Limpar(x.Nome)).Append(';').Append(Limpar(x.Tipo)).Append(';').Append(x.Status).Append(';').Append(x.Valor).Append('\n');return Encoding.UTF8.GetBytes(b.ToString());}
 static void Validar(string recurso,EducacaoAvancadaOperacaoRequest r){if(string.IsNullOrWhiteSpace(r.Status))throw new ArgumentException("Status é obrigatório.");if(recurso=="educacao_transporte_rota"&&(string.IsNullOrWhiteSpace(r.Nome)||string.IsNullOrWhiteSpace(r.Turno)||(!r.EscolaId.HasValue&&!(r.Dados?.ContainsKey("regiao")??false))))throw new ArgumentException("Rota exige escola ou região, nome e turno.");if(recurso=="educacao_merenda_produto"&&(string.IsNullOrWhiteSpace(r.Nome)||string.IsNullOrWhiteSpace(r.Tipo)))throw new ArgumentException("Produto exige nome, unidade e categoria.");if(recurso=="educacao_biblioteca_acervo"&&(string.IsNullOrWhiteSpace(r.Nome)||string.IsNullOrWhiteSpace(r.Tipo)))throw new ArgumentException("Acervo exige título e tipo.");if(recurso=="educacao_merenda_movimento"&&r.Quantidade<=0)throw new ArgumentException("Movimento exige quantidade positiva.");if(recurso=="educacao_custo_rateio"&&string.IsNullOrWhiteSpace(r.Tipo))throw new ArgumentException("Rateio exige critério.");}
 static string Recurso(string r)=>Recursos.Contains(r)?r:throw new ArgumentException("Recurso de educação avançada inválido.");static string Limpar(string? s)=>(s??string.Empty).Replace(";",string.Empty,StringComparison.Ordinal).Replace("\n"," ",StringComparison.Ordinal);
}
