namespace Sigov.Web.Models.Editais;

public sealed record EditalResumoViewModel(long Id, string Nome, string Orgao, string Municipio, string Uf, string Status, string Objeto, DateTime? DataSessao, decimal? ValorEstimado, bool Persistido);
public sealed record RequisitoEditalViewModel(long Id, long EditalId, string Codigo, string Item, string Descricao, string Modulo, string Categoria, string Criticidade, bool Obrigatorio, bool Eliminatorio, decimal Percentual, string StatusAderencia, string ObservacaoTecnica, int Evidencias, string Responsavel);
public sealed record EvidenciaEditalViewModel(long Id, long EditalId, long RequisitoId, string Tipo, string Titulo, string Descricao, string Url, string RotaSistema, string Modulo, string Status, string Responsavel, DateTime Data);
public sealed record ModuloAderenciaViewModel(string Nome, string RotaPrincipal, string Status, string Evidencias, string Documentacao, string Limitacoes, string ProximaEvolucao);
public sealed record MatrizResumoViewModel(int Total, int Atende, int NaoAtende, int Parcial, int EmImplantacao, int Criticos, int CriticosNaoAtendidos, decimal PercentualAderencia);
public sealed record EditalDetalheViewModel(EditalResumoViewModel Edital, IReadOnlyList<RequisitoEditalViewModel> Requisitos, IReadOnlyList<EvidenciaEditalViewModel> Evidencias, IReadOnlyList<ModuloAderenciaViewModel> Modulos, MatrizResumoViewModel Resumo, bool SchemaDisponivel, string MensagemFallback);
public sealed class EditalFormViewModel { public string Nome { get; set; } = string.Empty; public string Orgao { get; set; } = string.Empty; public string Municipio { get; set; } = string.Empty; public string Uf { get; set; } = string.Empty; public string Modalidade { get; set; } = string.Empty; public string Numero { get; set; } = string.Empty; public int Ano { get; set; } = DateTime.UtcNow.Year; public string Objeto { get; set; } = string.Empty; public DateTime? DataPublicacao { get; set; } public DateTime? DataSessao { get; set; } public string Status { get; set; } = "Rascunho"; public string Observacoes { get; set; } = string.Empty; public string LinkOrigem { get; set; } = string.Empty; public decimal? ValorEstimado { get; set; } public string ResponsavelInterno { get; set; } = string.Empty; public long? TenantId { get; set; } }
public sealed class RequisitoFormViewModel { public string Codigo { get; set; } = string.Empty; public string Item { get; set; } = string.Empty; public string Descricao { get; set; } = string.Empty; public string ModuloRelacionado { get; set; } = string.Empty; public string Categoria { get; set; } = "Geral"; public string Criticidade { get; set; } = "Média"; public bool Obrigatorio { get; set; } public bool Eliminatorio { get; set; } public decimal Percentual { get; set; } public string StatusAderencia { get; set; } = "Não avaliado"; public string ObservacaoTecnica { get; set; } = string.Empty; public int Ordem { get; set; } }
public sealed class EvidenciaFormViewModel { public string Tipo { get; set; } = "Documento"; public string Titulo { get; set; } = string.Empty; public string Descricao { get; set; } = string.Empty; public string Url { get; set; } = string.Empty; public string RotaSistema { get; set; } = string.Empty; public string Modulo { get; set; } = string.Empty; public string Responsavel { get; set; } = string.Empty; }
