using System.Text;
using Dapper;
using Npgsql;
using Sigov.Application.Defesa;
using Sigov.Infrastructure.Persistence.Dapper;

namespace Sigov.Infrastructure.Defesa;

public sealed class DefesaRepository(DapperContext db):IDefesaRepository
{
 private sealed record Spec(string Table,string Code,string Description,string Status);
 private static readonly IReadOnlyDictionary<string,Spec> Specs=new Dictionary<string,Spec>(StringComparer.OrdinalIgnoreCase){
  ["Agentes"]=new("defesa_agente","matricula","nome","status"),["Equipes"]=new("defesa_civil_equipe","codigo","nome","status"),["Recursos"]=new("defesa_civil_recurso","codigo","descricao","status"),["AreasRisco"]=new("defesa_civil_area_risco","codigo","nome","status"),["Ocorrencias"]=new("defesa_civil_ocorrencia","codigo","descricao","status"),["Acionamentos"]=new("defesa_acionamento","id::text","observacao","status"),["Vistorias"]=new("defesa_vistoria","numero_vistoria","situacao_encontrada","status"),["Abrigos"]=new("defesa_civil_abrigo","codigo","nome","status"),["Atendimentos"]=new("defesa_atendimento_emergencial","id::text","nome_responsavel_familiar","status"),["Rondas"]=new("defesa_ronda","numero_ronda","area_atuacao","status"),["OrdensServico"]=new("defesa_ordem_servico","numero_os","descricao","status"),["Notificacoes"]=new("defesa_notificacao_preventiva","numero_notificacao","destinatario_nome","status"),["PlanosContingencia"]=new("defesa_civil_plano_contingencia","codigo","titulo","status"),["Auditoria"]=new("defesa_auditoria","id::text","tabela||' — '||acao","acao"),["CenariosRisco"]=new("defesa_civil_cenario_risco","codigo","descricao","status"),["RotasEvacuacao"]=new("defesa_civil_rota_evacuacao","codigo","descricao","status"),["Resposta"]=new("defesa_civil_ocorrencia_resposta","id::text","descricao","status"),["Estoques"]=new("defesa_civil_estoque","codigo","item","status"),["Doacoes"]=new("defesa_civil_doacao","codigo","descricao","status"),["Alertas"]=new("defesa_civil_alerta","codigo","mensagem","status"),["FontesMonitoramento"]=new("defesa_civil_fonte_monitoramento","codigo","nome","status"),["Comunicacoes"]=new("defesa_civil_comunicacao","codigo","mensagem","status"),["Evidencias"]=new("defesa_civil_evidencia_vinculo","id::text","descricao","status"),["Ocupacao"]=new("defesa_civil_abrigo_ocupacao","id::text","pessoa_id::text","status")};
 private static readonly IReadOnlyDictionary<string,HashSet<string>> Allowed=new Dictionary<string,HashSet<string>>(StringComparer.OrdinalIgnoreCase){
  ["Agentes"]=["cpf","telefone","email","tipo_agente","cargo_funcao","data_inicio","data_fim","observacao","active"],
  ["Equipes"]=["tipo","responsavel_usuario_id","unidade_id"],
  ["Recursos"]=["tipo","patrimonio_id","frota_veiculo_id","quantidade","quantidade_mobilizada","unidade_id"],
  ["AreasRisco"]=["tipo","nivel_risco","bairro","localidade","unidade_id","populacao_estimada","latitude","longitude","vulnerabilidades"],
  ["Ocorrencias"]=["tipo","severidade","nivel_resposta","local","inicio_em","encerrada_em","area_risco_id","equipe_id","fiscalizacao_ordem_id"],
  ["Acionamentos"]=["ocorrencia_id","equipe_id","agente_responsavel_id","data_hora_acionamento","data_hora_chegada","data_hora_encerramento"],
  ["Vistorias"]=["tipo_vistoria","area_risco_id","ocorrencia_id","agente_responsavel_id","data_vistoria","endereco","bairro","recomendacoes","prazo_regularizacao"],
  ["Abrigos"]=["endereco","bairro","responsavel_usuario_id","capacidade","vagas_reservadas","estrutura","unidade_id"],
  ["Atendimentos"]=["ocorrencia_id","abrigo_id","documento_responsavel","telefone","quantidade_pessoas","quantidade_criancas","quantidade_idosos","necessidade_especial","tipo_apoio","descricao_apoio","data_atendimento","observacao"],
  ["Rondas"]=["equipe_id","agente_responsavel_id","data_hora_inicio","data_hora_fim","tipo_ronda","resumo"],
  ["OrdensServico"]=["tipo_servico","solicitante","equipe_id","agente_responsavel_id","data_abertura","data_previsao","data_conclusao","prioridade","resultado"],
  ["Notificacoes"]=["vistoria_id","area_risco_id","destinatario_documento","endereco","data_emissao","prazo_atendimento","motivo","recomendacao"],
  ["PlanosContingencia"]=["cenario_risco_id","responsavel_usuario_id","versao","vigencia_inicio","vigencia_fim","aprovado_por","aprovado_em"],["CenariosRisco"]=["area_risco_id","tipo","severidade","probabilidade","populacao_exposta","impactos","gatilhos"],["RotasEvacuacao"]=["plano_id","origem","destino","restricoes","recursos_necessarios"],["Resposta"]=["ocorrencia_id","equipe_id","recurso_id","acao","inicio_em","fim_em"],["Estoques"]=["abrigo_id","saldo","nivel_critico","unidade_medida"],["Doacoes"]=["origem","tipo","quantidade","destino_abrigo_id","prestacao"],["Alertas"]=["area_risco_id","severidade","mensagem","valido_de","valido_ate","canal","aprovado_por","publicado_em"],["FontesMonitoramento"]=["tipo","identificacao","periodicidade_minutos","ultima_atualizacao","erro_sanitizado"],["Comunicacoes"]=["alerta_id","canal","mensagem","publicada_em","outbox_id","erro_sanitizado"],["Evidencias"]=["evidencia_id","contexto_tipo","contexto_id"],["Ocupacao"]=["abrigo_id","pessoa_id","entrada_em","saida_em","justificativa_excedente"],["Auditoria"]=[]};

 public async Task<DefesaDashboard> DashboardAsync(DefesaContexto c,CancellationToken ct){using var cn=db.CreateConnection();const string sql= """
select
 (select count(*) from sigov.defesa_civil_ocorrencia where tenant_id=@TenantId and entity_id=@EntityId and deleted_at is null and status='ABERTA') OcorrenciasAbertas,
 (select count(*) from sigov.defesa_civil_ocorrencia where tenant_id=@TenantId and entity_id=@EntityId and deleted_at is null and status='ABERTA' and severidade='CRITICA') OcorrenciasCriticas,
 (select count(*) from sigov.defesa_civil_ocorrencia where tenant_id=@TenantId and entity_id=@EntityId and deleted_at is null and status='ENCERRADA' and encerrada_em>=date_trunc('month',now())) OcorrenciasFechadasMes,
 (select count(*) from sigov.defesa_civil_ocorrencia_resposta where tenant_id=@TenantId and entity_id=@EntityId and deleted_at is null and status='EM_ANDAMENTO') AcionamentosAndamento,
 0::bigint VistoriasPendentes,
 (select count(*) from sigov.defesa_civil_area_risco where tenant_id=@TenantId and entity_id=@EntityId and deleted_at is null and nivel_risco='CRITICO') AreasCriticas,
 (select count(*) from sigov.defesa_civil_abrigo where tenant_id=@TenantId and entity_id=@EntityId and deleted_at is null and status='ATIVO') AbrigosAtivos,
 (select coalesce(sum(capacidade),0) from sigov.defesa_civil_abrigo where tenant_id=@TenantId and entity_id=@EntityId and deleted_at is null and status='ATIVO') CapacidadeAbrigos,
 (select count(*) from sigov.defesa_civil_abrigo_ocupacao where tenant_id=@TenantId and entity_id=@EntityId and deleted_at is null and status='ABRIGADA' and saida_em is null) OcupacaoAbrigos,
 0::bigint RondasAndamento,0::bigint OrdensAbertas,0::bigint NotificacoesPendentes
""";return await cn.QuerySingleAsync<DefesaDashboard>(new CommandDefinition(sql,c,cancellationToken:ct));}
 public async Task<DefesaPagina> ListarAsync(DefesaContexto c,string recurso,DefesaFiltro f,CancellationToken ct){var s=SpecFor(recurso);using var cn=db.CreateConnection();var page=Math.Max(1,f.Pagina);var size=Math.Clamp(f.Tamanho,1,10000);var deleted=s.Table=="defesa_auditoria"?"true":"deleted_at is null";var where=$"tenant_id=@TenantId and entity_id=@EntityId and {deleted} and (@Busca is null or cast({s.Code} as text) ilike '%'||@Busca||'%' or cast({s.Description} as text) ilike '%'||@Busca||'%') and (@Status is null or cast({s.Status} as text)=@Status) and (@Inicio is null or created_at::date>=@Inicio) and (@Fim is null or created_at::date<=@Fim)";var p=new{c.TenantId,c.EntityId,f.Busca,f.Status,f.Inicio,f.Fim,Limit=size,Offset=(page-1)*size};var total=await cn.ExecuteScalarAsync<long>($"select count(*) from sigov.{s.Table} where {where}",p);var items=(await cn.QueryAsync<DefesaRegistro>($"select id,cast({s.Code} as text) Codigo,coalesce(cast({s.Description} as text),'') Descricao,cast({s.Status} as text) Status,created_at CriadoEm from sigov.{s.Table} where {where} order by created_at desc limit @Limit offset @Offset",p)).AsList();return new(items,page,size,total);}
 public async Task<DefesaRegistroRequest?> ObterAsync(DefesaContexto c,string recurso,long id,CancellationToken ct)
 {
  var s=SpecFor(recurso);if(recurso.Equals("Auditoria",StringComparison.OrdinalIgnoreCase))return null;
  var columns=Allowed[recurso].OrderBy(x=>x,StringComparer.Ordinal).ToArray();
  var code=!s.Code.Contains("::",StringComparison.Ordinal)&&!s.Code.Contains('(')?s.Code:"id::text";
  var description=s.Description.Split("||",StringSplitOptions.None)[0];
  using var cn=db.CreateConnection();
  var row=await cn.QuerySingleOrDefaultAsync($"select cast({code} as text) Codigo,coalesce(cast({description} as text),'') Descricao,cast({s.Status} as text) Status,{string.Join(',',columns.Select(x=>$"cast({x} as text) as {x}"))} from sigov.{s.Table} where id=@id and tenant_id=@TenantId and entity_id=@EntityId and deleted_at is null",new{id,c.TenantId,c.EntityId});
  if(row is null)return null;var values=(IDictionary<string,object>)row;
  string Value(string name)=>values.FirstOrDefault(x=>x.Key.Equals(name,StringComparison.OrdinalIgnoreCase)).Value?.ToString()??"";
  var request=new DefesaRegistroRequest{Codigo=Value("Codigo"),Descricao=Value("Descricao"),Status=Value("Status")};
  foreach(var column in columns)request.Campos[column]=Value(column);
  return request;
 }
 public async Task<IReadOnlyList<DefesaOpcao>> OpcoesAsync(DefesaContexto c,string tipo,bool somenteAtivos,CancellationToken ct)
 {
  using var cn=db.CreateConnection();
  if(tipo.Equals("Usuarios",StringComparison.OrdinalIgnoreCase))return(await cn.QueryAsync<DefesaOpcao>("select u.id,coalesce(p.nome_social,p.nome,u.login) Rotulo from sigov.usuario u left join sigov.pessoa p on p.id=u.pessoa_id where u.entidade_id=@EntityId and u.ativo and not u.is_deleted order by 2 limit 500",c)).AsList();
  if(tipo.Equals("Unidades",StringComparison.OrdinalIgnoreCase))return(await cn.QueryAsync<DefesaOpcao>("select id,coalesce(sigla||' — ','')||nome Rotulo from sigov.unidade_organizacional where entidade_id=@EntityId and ativo and not is_deleted order by 2 limit 500",c)).AsList();
  if(tipo.Equals("Pessoas",StringComparison.OrdinalIgnoreCase))return(await cn.QueryAsync<DefesaOpcao>("select id,left(coalesce(nome_social,nome),3)||'***' Rotulo from sigov.pessoa where entidade_id=@EntityId and ativo and not is_deleted order by 2 limit 500",c)).AsList();
  if(tipo.Equals("EvidenciasCanonicas",StringComparison.OrdinalIgnoreCase))return(await cn.QueryAsync<DefesaOpcao>("select id,tipo||' — '||left(descricao,80)||' — '||to_char(registrada_at,'DD/MM/YYYY HH24:MI') Rotulo from sigov.evidencia_transversal where tenant_id=@TenantId and entidade_id=@EntityId and not is_deleted order by registrada_at desc limit 500",c)).AsList();
  var s=SpecFor(tipo);var active=tipo.ToUpperInvariant() switch{"AGENTES"=>"and active=true and status='ATIVO'","EQUIPES"=>"and status='ATIVA'","ABRIGOS"=>"and status='ATIVO'",_=>""};
  var label=tipo.ToUpperInvariant() switch{"AGENTES"=>"matricula||' — '||nome","EQUIPES"=>"codigo||' — '||nome","AREASRISCO"=>"codigo||' — '||nome||' — '||bairro||' — '||nivel_risco","OCORRENCIAS"=>"codigo||' — '||left(descricao,80)","ABRIGOS"=>"codigo||' — '||nome||' — '||bairro","CENARIOSRISCO"=>"codigo||' — '||left(descricao,80)","PLANOSCONTINGENCIA"=>"codigo||' — '||titulo","RECURSOS"=>"codigo||' — '||left(descricao,80)","ALERTAS"=>"codigo||' — '||left(mensagem,80)","VISTORIAS"=>"numero_vistoria||' — '||left(situacao_encontrada,80)",_=>$"cast({s.Code} as text)||' — '||cast({s.Description} as text)"};
  return(await cn.QueryAsync<DefesaOpcao>($"select id,{label} Rotulo from sigov.{s.Table} where tenant_id=@TenantId and entity_id=@EntityId and deleted_at is null {(somenteAtivos?active:"")} order by 2 limit 500",c)).AsList();
 }
 public async Task<long> SalvarAsync(DefesaContexto c,string recurso,DefesaRegistroRequest r,long? id,CancellationToken ct)
 {
  var s=SpecFor(recurso);if(recurso.Equals("Auditoria",StringComparison.OrdinalIgnoreCase))throw new ArgumentException("Recurso somente para consulta.");

  var values=new Dictionary<string,object?>();
  if(!s.Code.Contains("::",StringComparison.Ordinal)&&!s.Code.Contains('('))values[s.Code]=r.Codigo.Trim();
  values[s.Description.Split("||",StringSplitOptions.None)[0]]=r.Descricao.Trim();
  values[s.Status]=r.Status;
  foreach(var (key,value) in r.Campos){if(!Allowed[recurso].Contains(key))throw new ArgumentException($"Campo não permitido: {key}.");values[key]=string.IsNullOrWhiteSpace(value)?null:value.Trim();}
  using var cn=db.CreateConnection();cn.Open();using var tx=cn.BeginTransaction();
  foreach(var (key,value) in r.Campos.Where(x=>x.Key.EndsWith("_id",StringComparison.Ordinal)&&!string.IsNullOrWhiteSpace(x.Value))){if(!long.TryParse(value,out var relationId))throw new ArgumentException("Seleção de relacionamento inválida.");var table=RelationTable(key);var relationSql=table=="usuario"?"select exists(select 1 from sigov.usuario where id=@relationId and entidade_id=@EntityId and ativo and not is_deleted)":table=="pessoa"?"select exists(select 1 from sigov.pessoa where id=@relationId and entidade_id=@EntityId and ativo and not is_deleted)":table=="evidencia_transversal"?"select exists(select 1 from sigov.evidencia_transversal where id=@relationId and tenant_id=@TenantId and entidade_id=@EntityId and not is_deleted)":table=="unidade_organizacional"?"select exists(select 1 from sigov.unidade_organizacional where id=@relationId and entidade_id=@EntityId and ativo and not is_deleted)":$"select exists(select 1 from sigov.{table} where id=@relationId and tenant_id=@TenantId and entity_id=@EntityId and deleted_at is null)";var valid=await cn.ExecuteScalarAsync<bool>(new CommandDefinition(relationSql,new{relationId,c.TenantId,c.EntityId},tx,cancellationToken:ct));if(!valid)throw new ArgumentException("A seleção não pertence ao contexto atual ou não está ativa.");}
  await ValidateOperationalRules(c,recurso,r,cn,tx,ct);
  if(recurso.Equals("Recursos",StringComparison.OrdinalIgnoreCase)&&!string.IsNullOrWhiteSpace(r.Campos.GetValueOrDefault("patrimonio_codigo"))){var duplicate=await cn.ExecuteScalarAsync<bool>(new CommandDefinition("select exists(select 1 from sigov.defesa_recurso_operacional where tenant_id=@TenantId and entity_id=@EntityId and deleted_at is null and patrimonio_codigo=@codigo and (@id is null or id<>@id))",new{c.TenantId,c.EntityId,codigo=r.Campos["patrimonio_codigo"],id},tx,cancellationToken:ct));if(duplicate)throw new ArgumentException("O código patrimonial já está em uso neste contexto.");}
  var parameters=new DynamicParameters(new{c.TenantId,c.EntityId,id});var assignments=new List<string>();var columns=new List<string>{"tenant_id","entity_id"};var expressions=new List<string>{"@TenantId","@EntityId"};var i=0;
  foreach(var pair in values){var name=$"v{++i}";parameters.Add(name,pair.Value);var expression=SqlValue(pair.Key,name);columns.Add(pair.Key);expressions.Add(expression);assignments.Add($"{pair.Key}={expression}");}
  try{
   long savedId;
   if(id.HasValue){var updated=await cn.ExecuteScalarAsync<long?>(new CommandDefinition($"update sigov.{s.Table} set {string.Join(',',assignments)},updated_at=now() where id=@id and tenant_id=@TenantId and entity_id=@EntityId and deleted_at is null returning id",parameters,tx,cancellationToken:ct));if(!updated.HasValue)throw new KeyNotFoundException("Registro não encontrado neste contexto.");savedId=updated.Value;}
   else savedId=await cn.ExecuteScalarAsync<long>(new CommandDefinition($"insert into sigov.{s.Table}({string.Join(',',columns)}) values({string.Join(',',expressions)}) returning id",parameters,tx,cancellationToken:ct));
   await cn.ExecuteAsync(new CommandDefinition("insert into sigov.defesa_auditoria(tenant_id,entity_id,tabela,registro_id,acao,usuario,dados_novos) values(@TenantId,@EntityId,@Tabela,@savedId,@Acao,@Usuario,jsonb_build_object('identificacao',@Codigo,'descricao',@Descricao))",new{c.TenantId,c.EntityId,Tabela=s.Table,savedId,Acao=id.HasValue?"ALTERAR":"CRIAR",c.Usuario,r.Codigo,r.Descricao},tx,cancellationToken:ct));tx.Commit();return savedId;
  }catch(PostgresException ex){throw new ArgumentException("Os dados violam uma regra operacional: "+ex.ConstraintName,ex);}
 }
 public async Task ExcluirAsync(DefesaContexto c,string recurso,long id,CancellationToken ct){var s=SpecFor(recurso);using var cn=db.CreateConnection();cn.Open();using var tx=cn.BeginTransaction();var n=await cn.ExecuteAsync(new CommandDefinition($"update sigov.{s.Table} set deleted_at=now(),updated_at=now() where id=@id and tenant_id=@TenantId and entity_id=@EntityId and deleted_at is null",new{id,c.TenantId,c.EntityId},tx,cancellationToken:ct));if(n==0)throw new KeyNotFoundException("Registro não encontrado neste contexto.");await cn.ExecuteAsync(new CommandDefinition("insert into sigov.defesa_auditoria(tenant_id,entity_id,tabela,registro_id,acao,usuario) values(@TenantId,@EntityId,@Tabela,@id,'EXCLUIR',@Usuario)",new{c.TenantId,c.EntityId,Tabela=s.Table,id,c.Usuario},tx,cancellationToken:ct));tx.Commit();}
 public async Task<byte[]> CsvAsync(DefesaContexto c,string recurso,DefesaFiltro f,CancellationToken ct){string[] allowed=["Ocorrencias","Acionamentos","Vistorias","AreasRisco","Abrigos","Atendimentos","Rondas","OrdensServico","Notificacoes","CenariosRisco","PlanosContingencia","RotasEvacuacao","Resposta","Recursos","Estoques","Doacoes","Alertas","FontesMonitoramento","Auditoria"];if(!allowed.Contains(recurso,StringComparer.OrdinalIgnoreCase))throw new ArgumentException("Relatório não permitido.");var page=await ListarAsync(c,recurso,f with{Pagina=1,Tamanho=10000},ct);var b=new StringBuilder("Identificação;Descrição;Status;Criado em\r\n");foreach(var x in page.Itens)b.AppendLine($"{Csv(x.Codigo)};{Csv(x.Descricao)};{Csv(x.Status)};{x.CriadoEm:O}");return new UTF8Encoding(true).GetBytes(b.ToString());}
 private static async Task ValidateOperationalRules(DefesaContexto c,string recurso,DefesaRegistroRequest r,System.Data.IDbConnection cn,System.Data.IDbTransaction tx,CancellationToken ct){if(recurso.Equals("Acionamentos",StringComparison.OrdinalIgnoreCase)&&long.TryParse(r.Campos.GetValueOrDefault("ocorrencia_id"),out var ocorrencia)){var aberta=await cn.ExecuteScalarAsync<bool>(new CommandDefinition("select exists(select 1 from sigov.defesa_ocorrencia where id=@ocorrencia and tenant_id=@TenantId and entity_id=@EntityId and deleted_at is null and status<>'FECHADA')",new{ocorrencia,c.TenantId,c.EntityId},tx,cancellationToken:ct));if(!aberta)throw new ArgumentException("Não é permitido acionar uma ocorrência fechada.");}if(recurso.Equals("Atendimentos",StringComparison.OrdinalIgnoreCase)&&long.TryParse(r.Campos.GetValueOrDefault("abrigo_id"),out var abrigo)){var ativo=await cn.ExecuteScalarAsync<bool>(new CommandDefinition("select exists(select 1 from sigov.defesa_abrigo where id=@abrigo and tenant_id=@TenantId and entity_id=@EntityId and deleted_at is null and status='ATIVO' and capacidade_ocupada<capacidade_total)",new{abrigo,c.TenantId,c.EntityId},tx,cancellationToken:ct));if(!ativo)throw new ArgumentException("O abrigo selecionado está inativo ou lotado.");}}
 private static Spec SpecFor(string r)=>Specs.TryGetValue(r,out var s)?s:throw new ArgumentException("Recurso de Defesa inválido.");
 private static string RelationTable(string key)=>key switch{"responsavel_agente_id" or "agente_responsavel_id"=>"defesa_agente","responsavel_usuario_id" or "aprovado_por"=>"usuario","unidade_id"=>"unidade_organizacional","pessoa_id"=>"pessoa","evidencia_id"=>"evidencia_transversal","contexto_id"=>"defesa_civil_area_risco","equipe_id" or "equipe_responsavel_id"=>"defesa_civil_equipe","area_risco_id"=>"defesa_civil_area_risco","cenario_risco_id"=>"defesa_civil_cenario_risco","ocorrencia_id"=>"defesa_civil_ocorrencia","abrigo_id" or "destino_abrigo_id"=>"defesa_civil_abrigo","recurso_id"=>"defesa_civil_recurso","plano_id"=>"defesa_civil_plano_contingencia","alerta_id"=>"defesa_civil_alerta","vistoria_id"=>"defesa_vistoria",_=>throw new ArgumentException("Relacionamento não permitido.")};
 private static string SqlValue(string column,string parameter)
 {
  if(column.EndsWith("_id",StringComparison.Ordinal))return $"nullif(@{parameter},'')::bigint";
  if(column is "active")return $"coalesce(nullif(@{parameter},'')::boolean,false)";
  if(column.StartsWith("data_hora_",StringComparison.Ordinal)||column.EndsWith("_em",StringComparison.Ordinal)||column.StartsWith("valido_",StringComparison.Ordinal)||column is "data_atendimento" or "data_abertura" or "data_previsao" or "data_conclusao")return $"nullif(@{parameter},'')::timestamptz";
  if(column.StartsWith("data_",StringComparison.Ordinal)||column.StartsWith("vigencia_",StringComparison.Ordinal)||column.StartsWith("prazo_",StringComparison.Ordinal))return $"nullif(@{parameter},'')::date";
  if(column.StartsWith("quantidade",StringComparison.Ordinal)||column is "saldo" or "nivel_critico")return $"nullif(@{parameter},'')::numeric";
  if(column.StartsWith("capacidade",StringComparison.Ordinal)||column is "populacao_estimada" or "populacao_exposta" or "periodicidade_minutos" or "versao" or "vagas_reservadas")return $"nullif(@{parameter},'')::integer";
  if(column is "latitude" or "longitude")return $"nullif(@{parameter},'')::numeric";
  return $"@{parameter}";
 }
 private static string Csv(string? value){var s=value??"";if(s.Length>0&&"=+-@".Contains(s[0]))s="'"+s;return '"'+s.Replace("\"","\"\"")+'"';}
}
