using Dapper;
using Sigov.Application.Agro.Propriedades;
using Sigov.Application.Common;
using Sigov.Infrastructure.Persistence.Dapper;

namespace Sigov.Infrastructure.Agro.Repositories;

public sealed class AgroPropriedadeRepository : IAgroPropriedadeRepository
{
    private readonly DapperContext _context; public AgroPropriedadeRepository(DapperContext context) => _context = context;
    public async Task<PagedResult<AgroPropriedadeResponse>> ListarAsync(long tenantId, long entidadeId, AgroPropriedadeFiltro f, CancellationToken ct) { const string csql="select count(*) from sigov.agro_propriedade where tenant_id=@TenantId and entidade_id=@EntidadeId and is_deleted=false and (@ProdutorId is null or produtor_id=@ProdutorId) and (@Busca is null or codigo_propriedade ilike @Busca or nome ilike @Busca);"; const string sql="select id as Id, tenant_id as TenantId, entidade_id as EntidadeId, produtor_id as ProdutorId, codigo_propriedade as CodigoPropriedade, nome as Nome, localidade as Localidade, comunidade as Comunidade, area_total_ha as AreaTotalHa, area_produtiva_ha as AreaProdutivaHa, situacao as Situacao, ativo as Ativo from sigov.agro_propriedade where tenant_id=@TenantId and entidade_id=@EntidadeId and is_deleted=false and (@ProdutorId is null or produtor_id=@ProdutorId) and (@Busca is null or codigo_propriedade ilike @Busca or nome ilike @Busca) order by created_at desc,id desc limit @Limit offset @Offset;"; var a=Args(tenantId,entidadeId,f); using var cn=_context.CreateConnection(); var total=await cn.ExecuteScalarAsync<long>(new CommandDefinition(csql,a,cancellationToken:ct)); var rows=await cn.QueryAsync<AgroPropriedadeResponse>(new CommandDefinition(sql,a,cancellationToken:ct)); return new PagedResult<AgroPropriedadeResponse>(rows.AsList(),f.Page,f.PageSize,total); }
    public async Task<AgroPropriedadeDetalheResponse?> ObterAsync(long tenantId, long entidadeId, long id, CancellationToken ct) { const string sql="select id as Id, tenant_id as TenantId, entidade_id as EntidadeId, produtor_id as ProdutorId, codigo_propriedade as CodigoPropriedade, nome as Nome, localidade as Localidade, comunidade as Comunidade, endereco_json::text as EnderecoJson, area_total_ha as AreaTotalHa, area_produtiva_ha as AreaProdutivaHa, area_preservacao_ha as AreaPreservacaoHa, latitude as Latitude, longitude as Longitude, geojson::text as GeoJson, situacao as Situacao, observacao as Observacao, ativo as Ativo from sigov.agro_propriedade where tenant_id=@TenantId and entidade_id=@EntidadeId and id=@Id and is_deleted=false;"; using var cn=_context.CreateConnection(); return await cn.QuerySingleOrDefaultAsync<AgroPropriedadeDetalheResponse>(new CommandDefinition(sql,new{TenantId=tenantId,EntidadeId=entidadeId,Id=id},cancellationToken:ct)); }
    public async Task<long> CriarAsync(long tenantId, long entidadeId, long? usuarioId, AgroPropriedadeCreateRequest r, string codigo, CancellationToken ct) { const string sql="insert into sigov.agro_propriedade(tenant_id,entidade_id,produtor_id,codigo_propriedade,nome,localidade,comunidade,endereco_json,area_total_ha,area_produtiva_ha,area_preservacao_ha,latitude,longitude,geojson,situacao,observacao,created_by) values(@TenantId,@EntidadeId,@ProdutorId,@Codigo,@Nome,@Localidade,@Comunidade,cast(@EnderecoJson as jsonb),@AreaTotalHa,@AreaProdutivaHa,@AreaPreservacaoHa,@Latitude,@Longitude,cast(@GeoJson as jsonb),@Situacao,@Observacao,@UsuarioId) returning id;"; using var cn=_context.CreateConnection(); return await cn.ExecuteScalarAsync<long>(new CommandDefinition(sql,new{TenantId=tenantId,EntidadeId=entidadeId,r.ProdutorId,Codigo=codigo,r.Nome,r.Localidade,r.Comunidade,EnderecoJson=r.EnderecoJson??"{}",r.AreaTotalHa,r.AreaProdutivaHa,r.AreaPreservacaoHa,r.Latitude,r.Longitude,GeoJson=r.GeoJson,r.Situacao,r.Observacao,UsuarioId=usuarioId},cancellationToken:ct)); }
    public async Task AtualizarAsync(long tenantId, long entidadeId, long id, long? usuarioId, AgroPropriedadeUpdateRequest r, CancellationToken ct) { const string sql="update sigov.agro_propriedade set produtor_id=@ProdutorId,codigo_propriedade=@CodigoPropriedade,nome=@Nome,localidade=@Localidade,comunidade=@Comunidade,endereco_json=cast(@EnderecoJson as jsonb),area_total_ha=@AreaTotalHa,area_produtiva_ha=@AreaProdutivaHa,area_preservacao_ha=@AreaPreservacaoHa,latitude=@Latitude,longitude=@Longitude,geojson=cast(@GeoJson as jsonb),situacao=@Situacao,observacao=@Observacao,ativo=@Ativo,updated_at=now(),updated_by=@UsuarioId where tenant_id=@TenantId and entidade_id=@EntidadeId and id=@Id and is_deleted=false;"; using var cn=_context.CreateConnection(); await cn.ExecuteAsync(new CommandDefinition(sql,new{TenantId=tenantId,EntidadeId=entidadeId,Id=id,r.ProdutorId,r.CodigoPropriedade,r.Nome,r.Localidade,r.Comunidade,EnderecoJson=r.EnderecoJson??"{}",r.AreaTotalHa,r.AreaProdutivaHa,r.AreaPreservacaoHa,r.Latitude,r.Longitude,GeoJson=r.GeoJson,r.Situacao,r.Observacao,r.Ativo,UsuarioId=usuarioId},cancellationToken:ct)); }
    public async Task ExcluirAsync(long tenantId,long entidadeId,long id,long? usuarioId,CancellationToken ct){const string sql="update sigov.agro_propriedade set is_deleted=true,ativo=false,deleted_at=now(),deleted_by=@UsuarioId where tenant_id=@TenantId and entidade_id=@EntidadeId and id=@Id and is_deleted=false;"; using var cn=_context.CreateConnection(); await cn.ExecuteAsync(new CommandDefinition(sql,new{TenantId=tenantId,EntidadeId=entidadeId,Id=id,UsuarioId=usuarioId},cancellationToken:ct));}
    public async Task<PagedResult<AgroTalhaoResponse>> ListarTalhoesAsync(long tenantId,long entidadeId,int page,int pageSize,long? propriedadeId,CancellationToken ct){const string csql="select count(*) from sigov.agro_talhao where tenant_id=@TenantId and entidade_id=@EntidadeId and is_deleted=false and (@PropriedadeId is null or propriedade_id=@PropriedadeId);"; const string sql="select id as Id, tenant_id as TenantId, entidade_id as EntidadeId, propriedade_id as PropriedadeId, codigo as Codigo, nome as Nome, area_ha as AreaHa, tipo_solo as TipoSolo, irrigado as Irrigado, latitude as Latitude, longitude as Longitude, geojson::text as GeoJson, situacao as Situacao, ativo as Ativo from sigov.agro_talhao where tenant_id=@TenantId and entidade_id=@EntidadeId and is_deleted=false and (@PropriedadeId is null or propriedade_id=@PropriedadeId) order by nome limit @Limit offset @Offset;"; var a=new{TenantId=tenantId,EntidadeId=entidadeId,PropriedadeId=propriedadeId,Limit=pageSize,Offset=(page-1)*pageSize}; using var cn=_context.CreateConnection(); var total=await cn.ExecuteScalarAsync<long>(new CommandDefinition(csql,a,cancellationToken:ct)); var rows=await cn.QueryAsync<AgroTalhaoResponse>(new CommandDefinition(sql,a,cancellationToken:ct)); return new PagedResult<AgroTalhaoResponse>(rows.AsList(),page,pageSize,total);}
    public async Task<long> CriarTalhaoAsync(long tenantId,long entidadeId,long? usuarioId,AgroTalhaoCreateRequest r,CancellationToken ct){const string sql="insert into sigov.agro_talhao(tenant_id,entidade_id,propriedade_id,codigo,nome,area_ha,tipo_solo,irrigado,latitude,longitude,geojson,situacao,created_by) values(@TenantId,@EntidadeId,@PropriedadeId,@Codigo,@Nome,@AreaHa,@TipoSolo,@Irrigado,@Latitude,@Longitude,cast(@GeoJson as jsonb),@Situacao,@UsuarioId) returning id;"; using var cn=_context.CreateConnection(); return await cn.ExecuteScalarAsync<long>(new CommandDefinition(sql,new{TenantId=tenantId,EntidadeId=entidadeId,r.PropriedadeId,r.Codigo,r.Nome,r.AreaHa,r.TipoSolo,r.Irrigado,r.Latitude,r.Longitude,GeoJson=r.GeoJson,r.Situacao,UsuarioId=usuarioId},cancellationToken:ct));}
    public async Task<PagedResult<AgroCulturaResponse>> ListarCulturasAsync(long tenantId,long entidadeId,int page,int pageSize,CancellationToken ct){const string csql="select count(*) from sigov.agro_cultura where tenant_id=@TenantId and entidade_id=@EntidadeId and is_deleted=false;"; const string sql="select id as Id, tenant_id as TenantId, entidade_id as EntidadeId, codigo as Codigo, nome as Nome, tipo_cultura as TipoCultura, ciclo_dias as CicloDias, unidade_medida as UnidadeMedida, ativo as Ativo from sigov.agro_cultura where tenant_id=@TenantId and entidade_id=@EntidadeId and is_deleted=false order by nome limit @Limit offset @Offset;"; var a=new{TenantId=tenantId,EntidadeId=entidadeId,Limit=pageSize,Offset=(page-1)*pageSize}; using var cn=_context.CreateConnection(); var total=await cn.ExecuteScalarAsync<long>(new CommandDefinition(csql,a,cancellationToken:ct)); var rows=await cn.QueryAsync<AgroCulturaResponse>(new CommandDefinition(sql,a,cancellationToken:ct)); return new PagedResult<AgroCulturaResponse>(rows.AsList(),page,pageSize,total);}
    public async Task<long> CriarCulturaAsync(long tenantId,long entidadeId,long? usuarioId,AgroCulturaCreateRequest r,CancellationToken ct){const string sql="insert into sigov.agro_cultura(tenant_id,entidade_id,codigo,nome,tipo_cultura,ciclo_dias,unidade_medida,created_by) values(@TenantId,@EntidadeId,@Codigo,@Nome,@TipoCultura,@CicloDias,@UnidadeMedida,@UsuarioId) returning id;"; using var cn=_context.CreateConnection(); return await cn.ExecuteScalarAsync<long>(new CommandDefinition(sql,new{TenantId=tenantId,EntidadeId=entidadeId,r.Codigo,r.Nome,r.TipoCultura,r.CicloDias,r.UnidadeMedida,UsuarioId=usuarioId},cancellationToken:ct));}
    public async Task<PagedResult<AgroSafraResponse>> ListarSafrasAsync(long tenantId,long entidadeId,long? exercicioId,int page,int pageSize,CancellationToken ct){const string csql="select count(*) from sigov.agro_safra where tenant_id=@TenantId and entidade_id=@EntidadeId and is_deleted=false and (@ExercicioId is null or exercicio_id=@ExercicioId);"; const string sql="select id as Id, tenant_id as TenantId, entidade_id as EntidadeId, exercicio_id as ExercicioId, codigo as Codigo, nome as Nome, ano_inicio as AnoInicio, ano_fim as AnoFim, data_inicio as DataInicio, data_fim as DataFim, status as Status, ativo as Ativo from sigov.agro_safra where tenant_id=@TenantId and entidade_id=@EntidadeId and is_deleted=false and (@ExercicioId is null or exercicio_id=@ExercicioId) order by ano_inicio desc,nome limit @Limit offset @Offset;"; var a=new{TenantId=tenantId,EntidadeId=entidadeId,ExercicioId=exercicioId,Limit=pageSize,Offset=(page-1)*pageSize}; using var cn=_context.CreateConnection(); var total=await cn.ExecuteScalarAsync<long>(new CommandDefinition(csql,a,cancellationToken:ct)); var rows=await cn.QueryAsync<AgroSafraResponse>(new CommandDefinition(sql,a,cancellationToken:ct)); return new PagedResult<AgroSafraResponse>(rows.AsList(),page,pageSize,total);}
    public async Task<long> CriarSafraAsync(long tenantId,long entidadeId,long? exercicioId,long? usuarioId,AgroSafraCreateRequest r,CancellationToken ct){const string sql="insert into sigov.agro_safra(tenant_id,entidade_id,exercicio_id,codigo,nome,ano_inicio,ano_fim,data_inicio,data_fim,status,created_by) values(@TenantId,@EntidadeId,@ExercicioId,@Codigo,@Nome,@AnoInicio,@AnoFim,@DataInicio,@DataFim,@Status,@UsuarioId) returning id;"; using var cn=_context.CreateConnection(); return await cn.ExecuteScalarAsync<long>(new CommandDefinition(sql,new{TenantId=tenantId,EntidadeId=entidadeId,ExercicioId=exercicioId,r.Codigo,r.Nome,r.AnoInicio,r.AnoFim,r.DataInicio,r.DataFim,r.Status,UsuarioId=usuarioId},cancellationToken:ct));}
    private static object Args(long tenantId,long entidadeId,AgroPropriedadeFiltro f)=>new{TenantId=tenantId,EntidadeId=entidadeId,f.ProdutorId,Busca=string.IsNullOrWhiteSpace(f.Busca)?null:$"%{f.Busca}%",Limit=f.PageSize,Offset=(f.Page-1)*f.PageSize};
}
