using Dapper;
using Sigov.Application.Agro.Producao;
using Sigov.Application.Common;
using Sigov.Infrastructure.Persistence.Dapper;

namespace Sigov.Infrastructure.Agro.Repositories;

public sealed class AgroProducaoRepository : IAgroProducaoRepository
{
    private readonly DapperContext _context; public AgroProducaoRepository(DapperContext context) => _context = context;
    public async Task<PagedResult<AgroProducaoAgricolaResponse>> ListarAsync(long tenantId,long entidadeId,long? exercicioId,AgroProducaoAgricolaFiltro f,CancellationToken ct){const string csql="select count(*) from sigov.agro_producao_agricola where tenant_id=@TenantId and entidade_id=@EntidadeId and is_deleted=false and (@ExercicioId is null or exercicio_id=@ExercicioId) and (@ProdutorId is null or produtor_id=@ProdutorId) and (@CulturaId is null or cultura_id=@CulturaId) and (@SafraId is null or safra_id=@SafraId);"; const string sql="select id as Id, tenant_id as TenantId, entidade_id as EntidadeId, exercicio_id as ExercicioId, produtor_id as ProdutorId, propriedade_id as PropriedadeId, talhao_id as TalhaoId, cultura_id as CulturaId, safra_id as SafraId, area_plantada_ha as AreaPlantadaHa, data_plantio as DataPlantio, data_colheita_prevista as DataColheitaPrevista, data_colheita_real as DataColheitaReal, producao_estimada as ProducaoEstimada, producao_realizada as ProducaoRealizada, unidade_medida as UnidadeMedida, produtividade as Produtividade, status as Status, observacao as Observacao, ativo as Ativo from sigov.agro_producao_agricola where tenant_id=@TenantId and entidade_id=@EntidadeId and is_deleted=false and (@ExercicioId is null or exercicio_id=@ExercicioId) and (@ProdutorId is null or produtor_id=@ProdutorId) and (@CulturaId is null or cultura_id=@CulturaId) and (@SafraId is null or safra_id=@SafraId) order by created_at desc,id desc limit @Limit offset @Offset;"; var a=new{TenantId=tenantId,EntidadeId=entidadeId,ExercicioId=exercicioId,f.ProdutorId,f.CulturaId,f.SafraId,Limit=f.PageSize,Offset=(f.Page-1)*f.PageSize}; using var cn=_context.CreateConnection(); var total=await cn.ExecuteScalarAsync<long>(new CommandDefinition(csql,a,cancellationToken:ct)); var rows=await cn.QueryAsync<AgroProducaoAgricolaResponse>(new CommandDefinition(sql,a,cancellationToken:ct)); return new PagedResult<AgroProducaoAgricolaResponse>(rows.AsList(),f.Page,f.PageSize,total);}
    public async Task<AgroProducaoAgricolaResponse?> ObterAsync(long tenantId,long entidadeId,long id,CancellationToken ct){const string sql="select id as Id, tenant_id as TenantId, entidade_id as EntidadeId, exercicio_id as ExercicioId, produtor_id as ProdutorId, propriedade_id as PropriedadeId, talhao_id as TalhaoId, cultura_id as CulturaId, safra_id as SafraId, area_plantada_ha as AreaPlantadaHa, data_plantio as DataPlantio, data_colheita_prevista as DataColheitaPrevista, data_colheita_real as DataColheitaReal, producao_estimada as ProducaoEstimada, producao_realizada as ProducaoRealizada, unidade_medida as UnidadeMedida, produtividade as Produtividade, status as Status, observacao as Observacao, ativo as Ativo from sigov.agro_producao_agricola where tenant_id=@TenantId and entidade_id=@EntidadeId and id=@Id and is_deleted=false;"; using var cn=_context.CreateConnection(); return await cn.QuerySingleOrDefaultAsync<AgroProducaoAgricolaResponse>(new CommandDefinition(sql,new{TenantId=tenantId,EntidadeId=entidadeId,Id=id},cancellationToken:ct));}
    public async Task<long> CriarAsync(long tenantId,long entidadeId,long? exercicioId,long? usuarioId,AgroProducaoAgricolaCreateRequest r,decimal? produtividade,CancellationToken ct){const string sql="insert into sigov.agro_producao_agricola(tenant_id,entidade_id,exercicio_id,produtor_id,propriedade_id,talhao_id,cultura_id,safra_id,area_plantada_ha,data_plantio,data_colheita_prevista,data_colheita_real,producao_estimada,producao_realizada,unidade_medida,produtividade,status,observacao,created_by) values(@TenantId,@EntidadeId,@ExercicioId,@ProdutorId,@PropriedadeId,@TalhaoId,@CulturaId,@SafraId,@AreaPlantadaHa,@DataPlantio,@DataColheitaPrevista,@DataColheitaReal,@ProducaoEstimada,@ProducaoRealizada,@UnidadeMedida,@Produtividade,@Status,@Observacao,@UsuarioId) returning id;"; using var cn=_context.CreateConnection(); return await cn.ExecuteScalarAsync<long>(new CommandDefinition(sql,Params(tenantId,entidadeId,exercicioId,usuarioId,r,produtividade,null),cancellationToken:ct));}
    public async Task AtualizarAsync(long tenantId,long entidadeId,long id,long? exercicioId,long? usuarioId,AgroProducaoAgricolaCreateRequest r,decimal? produtividade,CancellationToken ct){const string sql="update sigov.agro_producao_agricola set produtor_id=@ProdutorId,propriedade_id=@PropriedadeId,talhao_id=@TalhaoId,cultura_id=@CulturaId,safra_id=@SafraId,area_plantada_ha=@AreaPlantadaHa,data_plantio=@DataPlantio,data_colheita_prevista=@DataColheitaPrevista,data_colheita_real=@DataColheitaReal,producao_estimada=@ProducaoEstimada,producao_realizada=@ProducaoRealizada,unidade_medida=@UnidadeMedida,produtividade=@Produtividade,status=@Status,observacao=@Observacao,updated_at=now(),updated_by=@UsuarioId where tenant_id=@TenantId and entidade_id=@EntidadeId and id=@Id and is_deleted=false and (@ExercicioId is null or exercicio_id=@ExercicioId);"; using var cn=_context.CreateConnection(); await cn.ExecuteAsync(new CommandDefinition(sql,Params(tenantId,entidadeId,exercicioId,usuarioId,r,produtividade,id),cancellationToken:ct));}
    public async Task ExcluirAsync(long tenantId,long entidadeId,long id,long? usuarioId,CancellationToken ct){const string sql="update sigov.agro_producao_agricola set is_deleted=true,ativo=false,deleted_at=now(),deleted_by=@UsuarioId where tenant_id=@TenantId and entidade_id=@EntidadeId and id=@Id and is_deleted=false;"; using var cn=_context.CreateConnection(); await cn.ExecuteAsync(new CommandDefinition(sql,new{TenantId=tenantId,EntidadeId=entidadeId,Id=id,UsuarioId=usuarioId},cancellationToken:ct));}
    private static object Params(long tenantId,long entidadeId,long? exercicioId,long? usuarioId,AgroProducaoAgricolaCreateRequest r,decimal? produtividade,long? id)=>new{TenantId=tenantId,EntidadeId=entidadeId,ExercicioId=exercicioId,UsuarioId=usuarioId,Id=id,r.ProdutorId,r.PropriedadeId,r.TalhaoId,r.CulturaId,r.SafraId,r.AreaPlantadaHa,r.DataPlantio,r.DataColheitaPrevista,r.DataColheitaReal,r.ProducaoEstimada,r.ProducaoRealizada,r.UnidadeMedida,Produtividade=produtividade,r.Status,r.Observacao};
}
