using Dapper;
using Sigov.Application.Agro.Produtores;
using Sigov.Application.Common;
using Sigov.Infrastructure.Persistence.Dapper;

namespace Sigov.Infrastructure.Agro.Repositories;

public sealed class AgroProdutorRepository : IAgroProdutorRepository
{
    private readonly DapperContext _context; public AgroProdutorRepository(DapperContext context) => _context = context;
    public async Task<PagedResult<AgroProdutorResponse>> ListarAsync(long tenantId, long entidadeId, AgroProdutorFiltro filtro, CancellationToken ct)
    {
        const string countSql = "select count(*) from sigov.agro_produtor ap join sigov.pessoa p on p.id=ap.pessoa_id where ap.tenant_id=@TenantId and ap.entidade_id=@EntidadeId and ap.is_deleted=false and (@Situacao is null or ap.situacao=@Situacao) and (@Busca is null or ap.codigo_produtor ilike @Busca or p.nome ilike @Busca);";
        const string sql = "select ap.id as Id, ap.tenant_id as TenantId, ap.entidade_id as EntidadeId, ap.pessoa_id as PessoaId, ap.codigo_produtor as CodigoProdutor, ap.tipo_produtor as TipoProdutor, p.nome as NomePessoa, case when p.documento is null then null else concat(repeat('*', greatest(length(p.documento)-4,0)), right(p.documento,4)) end as DocumentoMascarado, ap.situacao as Situacao, ap.data_cadastro as DataCadastro, ap.ativo as Ativo from sigov.agro_produtor ap join sigov.pessoa p on p.id=ap.pessoa_id where ap.tenant_id=@TenantId and ap.entidade_id=@EntidadeId and ap.is_deleted=false and (@Situacao is null or ap.situacao=@Situacao) and (@Busca is null or ap.codigo_produtor ilike @Busca or p.nome ilike @Busca) order by ap.created_at desc, ap.id desc limit @Limit offset @Offset;";
        var args = Args(tenantId, entidadeId, filtro); using var cn = _context.CreateConnection(); var total = await cn.ExecuteScalarAsync<long>(new CommandDefinition(countSql, args, cancellationToken: ct)); var rows = await cn.QueryAsync<AgroProdutorResponse>(new CommandDefinition(sql, args, cancellationToken: ct)); return new PagedResult<AgroProdutorResponse>(rows.AsList(), filtro.Page, filtro.PageSize, total);
    }
    public async Task<AgroProdutorDetalheResponse?> ObterAsync(long tenantId, long entidadeId, long id, bool dadosCompletos, CancellationToken ct)
    {
        const string sql = "select ap.id as Id, ap.tenant_id as TenantId, ap.entidade_id as EntidadeId, ap.pessoa_id as PessoaId, ap.codigo_produtor as CodigoProdutor, ap.tipo_produtor as TipoProdutor, p.nome as NomePessoa, case when p.documento is null then null else concat(repeat('*', greatest(length(p.documento)-4,0)), right(p.documento,4)) end as DocumentoMascarado, case when @DadosCompletos then p.documento else null end as DocumentoCompleto, ap.inscricao_estadual as InscricaoEstadual, ap.inscricao_municipal as InscricaoMunicipal, ap.numero_produtor_rural as NumeroProdutorRural, ap.associacao_cooperativa as AssociacaoCooperativa, ap.principal_atividade as PrincipalAtividade, ap.situacao as Situacao, ap.data_cadastro as DataCadastro, ap.observacao as Observacao, ap.ativo as Ativo from sigov.agro_produtor ap join sigov.pessoa p on p.id=ap.pessoa_id where ap.tenant_id=@TenantId and ap.entidade_id=@EntidadeId and ap.id=@Id and ap.is_deleted=false;";
        using var cn = _context.CreateConnection(); return await cn.QuerySingleOrDefaultAsync<AgroProdutorDetalheResponse>(new CommandDefinition(sql, new { TenantId = tenantId, EntidadeId = entidadeId, Id = id, DadosCompletos = dadosCompletos }, cancellationToken: ct));
    }
    public async Task<long> CriarAsync(long tenantId, long entidadeId, long? usuarioId, AgroProdutorCreateRequest r, string codigo, CancellationToken ct)
    {
        const string sql = "insert into sigov.agro_produtor(tenant_id,entidade_id,pessoa_id,codigo_produtor,tipo_produtor,inscricao_estadual,inscricao_municipal,numero_produtor_rural,associacao_cooperativa,principal_atividade,situacao,observacao,created_by) values(@TenantId,@EntidadeId,@PessoaId,@Codigo,@TipoProdutor,@InscricaoEstadual,@InscricaoMunicipal,@NumeroProdutorRural,@AssociacaoCooperativa,@PrincipalAtividade,@Situacao,@Observacao,@UsuarioId) returning id;";
        using var cn = _context.CreateConnection(); return await cn.ExecuteScalarAsync<long>(new CommandDefinition(sql, new { TenantId = tenantId, EntidadeId = entidadeId, r.PessoaId, Codigo = codigo, r.TipoProdutor, r.InscricaoEstadual, r.InscricaoMunicipal, r.NumeroProdutorRural, r.AssociacaoCooperativa, r.PrincipalAtividade, r.Situacao, r.Observacao, UsuarioId = usuarioId }, cancellationToken: ct));
    }
    public async Task AtualizarAsync(long tenantId, long entidadeId, long id, long? usuarioId, AgroProdutorUpdateRequest r, CancellationToken ct) { const string sql = "update sigov.agro_produtor set codigo_produtor=@CodigoProdutor,tipo_produtor=@TipoProdutor,inscricao_estadual=@InscricaoEstadual,inscricao_municipal=@InscricaoMunicipal,numero_produtor_rural=@NumeroProdutorRural,associacao_cooperativa=@AssociacaoCooperativa,principal_atividade=@PrincipalAtividade,situacao=@Situacao,observacao=@Observacao,ativo=@Ativo,updated_at=now(),updated_by=@UsuarioId where tenant_id=@TenantId and entidade_id=@EntidadeId and id=@Id and is_deleted=false;"; using var cn = _context.CreateConnection(); await cn.ExecuteAsync(new CommandDefinition(sql, new { TenantId = tenantId, EntidadeId = entidadeId, Id = id, r.CodigoProdutor, r.TipoProdutor, r.InscricaoEstadual, r.InscricaoMunicipal, r.NumeroProdutorRural, r.AssociacaoCooperativa, r.PrincipalAtividade, r.Situacao, r.Observacao, r.Ativo, UsuarioId = usuarioId }, cancellationToken: ct)); }
    public async Task ExcluirAsync(long tenantId, long entidadeId, long id, long? usuarioId, CancellationToken ct) { const string sql = "update sigov.agro_produtor set is_deleted=true,ativo=false,deleted_at=now(),deleted_by=@UsuarioId where tenant_id=@TenantId and entidade_id=@EntidadeId and id=@Id and is_deleted=false;"; using var cn = _context.CreateConnection(); await cn.ExecuteAsync(new CommandDefinition(sql, new { TenantId = tenantId, EntidadeId = entidadeId, Id = id, UsuarioId = usuarioId }, cancellationToken: ct)); }
    public async Task RegistrarAcessoDadoPessoalAsync(long tenantId, long entidadeId, long pessoaId, long? usuarioId, string finalidade, CancellationToken ct) { const string sql = "insert into sigov.acesso_dado_pessoal(tenant_id,entidade_id,pessoa_id,usuario_id,finalidade,campos_acessados,created_by) values(@TenantId,@EntidadeId,@PessoaId,@UsuarioId,@Finalidade,'[\"documento\",\"produtor\"]'::jsonb,@UsuarioId);"; using var cn = _context.CreateConnection(); await cn.ExecuteAsync(new CommandDefinition(sql, new { TenantId = tenantId, EntidadeId = entidadeId, PessoaId = pessoaId, UsuarioId = usuarioId, Finalidade = finalidade }, cancellationToken: ct)); }
    private static object Args(long tenantId, long entidadeId, AgroProdutorFiltro f) => new { TenantId = tenantId, EntidadeId = entidadeId, Situacao = string.IsNullOrWhiteSpace(f.Situacao) ? null : f.Situacao, Busca = string.IsNullOrWhiteSpace(f.Busca) ? null : $"%{f.Busca}%", Limit = f.PageSize, Offset = (f.Page - 1) * f.PageSize };
}
