using System.Text;
using System.Text.Json;
using Dapper;
using Sigov.Application.Agro.Relatorios;
using Sigov.Infrastructure.Agro.Sql;
using Sigov.Infrastructure.Persistence.Dapper;

namespace Sigov.Infrastructure.Agro.Repositories;

public sealed class AgroRelatoriosRepository : IAgroIndicadorRepository, IAgroRelatoriosRepository
{
    private readonly DapperContext _context;
    private static readonly ISet<string> Datasets = new HashSet<string>(StringComparer.OrdinalIgnoreCase) { "produtores", "propriedades", "producao", "pecuaria", "programas", "maquinas", "estradas", "feiras", "agroindustrias", "geojson" };
    public AgroRelatoriosRepository(DapperContext context) => _context = context;
    public async Task<IReadOnlyCollection<AgroIndicadorResponse>> ListarIndicadoresAsync(long tenantId, long? entidadeId, int page, int pageSize, CancellationToken cancellationToken) { using var cn = _context.CreateConnection(); var items = await cn.QueryAsync<AgroIndicadorResponse>(new CommandDefinition(AgroRelatoriosSql.ListarIndicadores, new { TenantId = tenantId, EntidadeId = entidadeId, PageSize = pageSize, Offset = (page - 1) * pageSize }, cancellationToken: cancellationToken)).ConfigureAwait(false); return items.ToArray(); }
    public async Task<AgroIndicadorResponse> CriarIndicadorAsync(long tenantId, long? entidadeId, long usuarioId, AgroIndicadorCreateRequest request, CancellationToken cancellationToken)
    {
        const string sql = @"insert into sigov.agro_indicador(tenant_id,entidade_id,codigo,nome,descricao,categoria,unidade_medida,publico,created_by)
values(@TenantId,@EntidadeId,@Codigo,@Nome,@Descricao,@Categoria,@UnidadeMedida,@Publico,@UsuarioId)
on conflict (tenant_id, entidade_id, codigo) do update set nome=excluded.nome, descricao=excluded.descricao, categoria=excluded.categoria, unidade_medida=excluded.unidade_medida, publico=excluded.publico, updated_at=now(), updated_by=@UsuarioId
returning id as Id, tenant_id as TenantId, entidade_id as EntidadeId, codigo as Codigo, nome as Nome, categoria as Categoria, descricao as Descricao, unidade_medida as UnidadeMedida, publico as Publico, ativo as Ativo;
";
        using var cn = _context.CreateConnection(); var result = await cn.QuerySingleAsync<AgroIndicadorResponse>(new CommandDefinition(sql, new { TenantId = tenantId, EntidadeId = entidadeId, request.Codigo, request.Nome, request.Descricao, request.Categoria, request.UnidadeMedida, request.Publico, UsuarioId = usuarioId }, cancellationToken: cancellationToken)).ConfigureAwait(false); await EventoAsync(cn, tenantId, entidadeId, null, "AgroIndicadorCriado", "agro_indicador", result.Id, usuarioId, new { request.Codigo }, cancellationToken).ConfigureAwait(false); return result;
    }
    public async Task<IReadOnlyCollection<AgroIndicadorValorResponse>> ListarValoresAsync(long tenantId, long? entidadeId, long indicadorId, int page, int pageSize, CancellationToken cancellationToken) { using var cn = _context.CreateConnection(); var items = await cn.QueryAsync<AgroIndicadorValorResponse>(new CommandDefinition(AgroRelatoriosSql.ListarValores, new { TenantId = tenantId, EntidadeId = entidadeId, IndicadorId = indicadorId, PageSize = pageSize, Offset = (page - 1) * pageSize }, cancellationToken: cancellationToken)).ConfigureAwait(false); return items.ToArray(); }
    public async Task<IReadOnlyCollection<AgroRelatorioModeloResponse>> ListarModelosAsync(long tenantId, long? entidadeId, int page, int pageSize, CancellationToken cancellationToken) { using var cn = _context.CreateConnection(); var items = await cn.QueryAsync<AgroRelatorioModeloResponse>(new CommandDefinition(AgroRelatoriosSql.ListarModelos, new { TenantId = tenantId, EntidadeId = entidadeId, PageSize = pageSize, Offset = (page - 1) * pageSize }, cancellationToken: cancellationToken)).ConfigureAwait(false); return items.ToArray(); }
    public async Task<AgroRelatorioModeloResponse> CriarModeloAsync(long tenantId, long? entidadeId, long usuarioId, AgroRelatorioModeloCreateRequest request, CancellationToken cancellationToken)
    {
        const string sql = @"insert into sigov.agro_relatorio_modelo(tenant_id,entidade_id,codigo,nome,descricao,tipo_relatorio,formato_padrao,publico_no_tenant,contem_dados_pessoais,contem_dados_sensiveis,created_by)
values(@TenantId,@EntidadeId,@Codigo,@Nome,@Descricao,@TipoRelatorio,@FormatoPadrao,@PublicoNoTenant,@ContemDadosPessoais,@ContemDadosSensiveis,@UsuarioId)
on conflict (tenant_id, entidade_id, codigo) do update set nome=excluded.nome, descricao=excluded.descricao, tipo_relatorio=excluded.tipo_relatorio, formato_padrao=excluded.formato_padrao, publico_no_tenant=excluded.publico_no_tenant, updated_at=now(), updated_by=@UsuarioId
returning id as Id, tenant_id as TenantId, entidade_id as EntidadeId, codigo as Codigo, nome as Nome, tipo_relatorio as TipoRelatorio, formato_padrao as FormatoPadrao, publico_no_tenant as PublicoNoTenant, contem_dados_pessoais as ContemDadosPessoais, ativo as Ativo;
";
        using var cn = _context.CreateConnection(); return await cn.QuerySingleAsync<AgroRelatorioModeloResponse>(new CommandDefinition(sql, new { TenantId = tenantId, EntidadeId = entidadeId, request.Codigo, request.Nome, request.Descricao, request.TipoRelatorio, request.FormatoPadrao, PublicoNoTenant = request.ContemDadosPessoais ? false : request.PublicoNoTenant, request.ContemDadosPessoais, request.ContemDadosSensiveis, UsuarioId = usuarioId }, cancellationToken: cancellationToken)).ConfigureAwait(false);
    }
    public async Task<AgroRelatorioExecucaoResponse> ExecutarAsync(long tenantId, long? entidadeId, long? exercicioId, long usuarioId, long modeloId, ExecutarAgroRelatorioRequest request, CancellationToken cancellationToken)
    {
        const string sql = @"insert into sigov.agro_relatorio_execucao(tenant_id,entidade_id,exercicio_id,modelo_id,usuario_id,formato,parametros_json,status,total_linhas,finalizou_at,conteudo_resumo)
values(@TenantId,@EntidadeId,@ExercicioId,@ModeloId,@UsuarioId,@Formato,cast(@ParametrosJson as jsonb),'CONCLUIDO',0,now(),'{}'::jsonb)
returning id as Id, tenant_id as TenantId, entidade_id as EntidadeId, exercicio_id as ExercicioId, modelo_id as ModeloId, usuario_id as UsuarioId, formato as Formato, status as Status, total_linhas as TotalLinhas, iniciou_at as IniciouAt, finalizou_at as FinalizouAt, erro as Erro;
";
        using var cn = _context.CreateConnection(); var result = await cn.QuerySingleAsync<AgroRelatorioExecucaoResponse>(new CommandDefinition(sql, new { TenantId = tenantId, EntidadeId = entidadeId, ExercicioId = exercicioId, ModeloId = modeloId, UsuarioId = usuarioId, request.Formato, ParametrosJson = string.IsNullOrWhiteSpace(request.ParametrosJson) ? "{}" : request.ParametrosJson }, cancellationToken: cancellationToken)).ConfigureAwait(false); await EventoAsync(cn, tenantId, entidadeId, exercicioId, "AgroRelatorioExecutado", "agro_relatorio_modelo", modeloId, usuarioId, new { request.Formato }, cancellationToken).ConfigureAwait(false); return result;
    }
    public async Task<IReadOnlyCollection<AgroRelatorioExecucaoResponse>> ListarExecucoesAsync(long tenantId, long? entidadeId, int page, int pageSize, CancellationToken cancellationToken) { using var cn = _context.CreateConnection(); var items = await cn.QueryAsync<AgroRelatorioExecucaoResponse>(new CommandDefinition(AgroRelatoriosSql.ListarExecucoes, new { TenantId = tenantId, EntidadeId = entidadeId, PageSize = pageSize, Offset = (page - 1) * pageSize }, cancellationToken: cancellationToken)).ConfigureAwait(false); return items.ToArray(); }
    public async Task<AgroRelatorioExecucaoResponse?> ObterExecucaoAsync(long tenantId, long id, CancellationToken cancellationToken) { using var cn = _context.CreateConnection(); return await cn.QuerySingleOrDefaultAsync<AgroRelatorioExecucaoResponse>(new CommandDefinition(AgroRelatoriosSql.ListarExecucoes.Replace("order by iniciou_at desc limit @PageSize offset @Offset", "and id = @Id limit 1"), new { TenantId = tenantId, EntidadeId = (long?)null, Id = id, PageSize = 1, Offset = 0 }, cancellationToken: cancellationToken)).ConfigureAwait(false); }
    public async Task<AgroExportResponse> ExportarAsync(long tenantId, long? entidadeId, long? exercicioId, long usuarioId, AgroExportRequest request, CancellationToken cancellationToken)
    {
        if (!Datasets.Contains(request.Dataset)) throw new ArgumentException("Dataset de exportação inválido.", nameof(request));
        using var cn = _context.CreateConnection(); var rows = await ObterLinhasExportacaoAsync(cn, tenantId, entidadeId, request.Dataset, cancellationToken).ConfigureAwait(false); var formato = request.Formato.ToUpperInvariant(); var content = formato switch { "JSON" => JsonSerializer.Serialize(rows), "GEOJSON" => BuildGeoJson(rows), _ => BuildCsv(rows) }; await AuditExportAsync(cn, tenantId, entidadeId, exercicioId, usuarioId, request, rows.Count, cancellationToken).ConfigureAwait(false); await EventoAsync(cn, tenantId, entidadeId, exercicioId, "AgroRelatorioExportado", "agro_export", null, usuarioId, new { request.Dataset, Formato = formato, Total = rows.Count }, cancellationToken).ConfigureAwait(false); var ext = formato.Equals("GEOJSON", StringComparison.Ordinal) ? "geojson" : formato.ToLowerInvariant(); var contentType = formato == "JSON" ? "application/json" : formato == "GEOJSON" ? "application/geo+json" : "text/csv"; return new AgroExportResponse($"agro-{request.Dataset}.{ext}", contentType, content, rows.Count, request.MascararDadosPessoais, false);
    }
    private static async Task<List<IDictionary<string, object?>>> ObterLinhasExportacaoAsync(System.Data.IDbConnection cn, long tenantId, long? entidadeId, string dataset, CancellationToken ct)
    {
        var sql = dataset.ToLowerInvariant() switch
        {
            "propriedades" => "select codigo_propriedade as codigo, nome, localidade, comunidade, area_total_ha, area_produtiva_ha, situacao from sigov.agro_propriedade where tenant_id=@TenantId and is_deleted=false and ((@EntidadeId is null) or entidade_id=@EntidadeId) order by nome limit 5000",
            "producao" => "select cultura_id, safra_id, area_plantada_ha, producao_estimada, producao_realizada, unidade_medida from sigov.agro_producao_agricola where tenant_id=@TenantId and is_deleted=false and ((@EntidadeId is null) or entidade_id=@EntidadeId) order by id limit 5000",
            "programas" => "select codigo, nome, tipo_programa, status from sigov.agro_programa_rural where tenant_id=@TenantId and is_deleted=false and ((@EntidadeId is null) or entidade_id=@EntidadeId) order by nome limit 5000",
            "maquinas" => "select numero_patrimonio, descricao, tipo_maquina, status from sigov.agro_maquina where tenant_id=@TenantId and is_deleted=false and ((@EntidadeId is null) or entidade_id=@EntidadeId) order by descricao limit 5000",
            "estradas" => "select codigo, nome, situacao, extensao_km from sigov.agro_estrada_vicinal where tenant_id=@TenantId and is_deleted=false and ((@EntidadeId is null) or entidade_id=@EntidadeId) order by nome limit 5000",
            "feiras" => "select codigo, nome, localidade, status from sigov.agro_feira where tenant_id=@TenantId and is_deleted=false and ((@EntidadeId is null) or entidade_id=@EntidadeId) order by nome limit 5000",
            "agroindustrias" => "select codigo, nome, tipo_atividade, situacao from sigov.agro_agroindustria where tenant_id=@TenantId and is_deleted=false and ((@EntidadeId is null) or entidade_id=@EntidadeId) order by nome limit 5000",
            "geojson" => "select nome, tipo_geometria, geojson from sigov.agro_geo_feicao where tenant_id=@TenantId and is_deleted=false and ((@EntidadeId is null) or entidade_id=@EntidadeId) order by nome limit 5000",
            _ => "select codigo_produtor as codigo, tipo_produtor, principal_atividade, situacao from sigov.agro_produtor where tenant_id=@TenantId and is_deleted=false and ((@EntidadeId is null) or entidade_id=@EntidadeId) order by codigo_produtor limit 5000"
        };
        var items = await cn.QueryAsync(new CommandDefinition(sql, new { TenantId = tenantId, EntidadeId = entidadeId }, cancellationToken: ct)).ConfigureAwait(false); return items.Select(x => (IDictionary<string, object?>)x).ToList();
    }
    private static string BuildCsv(IReadOnlyCollection<IDictionary<string, object?>> rows) { if (rows.Count == 0) return string.Empty; var sb = new StringBuilder(); var headers = rows.First().Keys.ToArray(); sb.AppendLine(string.Join(';', headers)); foreach (var row in rows) sb.AppendLine(string.Join(';', headers.Select(h => Escape(row.TryGetValue(h, out var v) ? v : null)))); return sb.ToString(); }
    private static string Escape(object? value) => Convert.ToString(value)?.Replace(";", ",", StringComparison.Ordinal).Replace("\n", " ", StringComparison.Ordinal) ?? string.Empty;
    private static string BuildGeoJson(IReadOnlyCollection<IDictionary<string, object?>> rows) => JsonSerializer.Serialize(new { type = "FeatureCollection", features = rows.Select(r => new { type = "Feature", properties = r.Where(k => !string.Equals(k.Key, "geojson", StringComparison.OrdinalIgnoreCase)).ToDictionary(k => k.Key, k => k.Value), geometry = r.TryGetValue("geojson", out var g) ? g : null }) });
    private static Task AuditExportAsync(System.Data.IDbConnection cn, long tenantId, long? entidadeId, long? exercicioId, long usuarioId, AgroExportRequest request, long total, CancellationToken ct) => cn.ExecuteAsync(new CommandDefinition("insert into sigov.agro_relatorio_execucao(tenant_id,entidade_id,exercicio_id,usuario_id,formato,parametros_json,status,total_linhas,finalizou_at,conteudo_resumo) values(@TenantId,@EntidadeId,@ExercicioId,@UsuarioId,@Formato,cast(@Parametros as jsonb),'CONCLUIDO',@Total,now(),cast(@Resumo as jsonb))", new { TenantId = tenantId, EntidadeId = entidadeId, ExercicioId = exercicioId, UsuarioId = usuarioId, Formato = request.Formato.ToUpperInvariant(), Parametros = JsonSerializer.Serialize(request), Total = total, Resumo = JsonSerializer.Serialize(new { exportacao = request.Dataset, mascarado = request.MascararDadosPessoais }) }, cancellationToken: ct));
    private static Task EventoAsync(System.Data.IDbConnection cn, long tenantId, long? entidadeId, long? exercicioId, string tipo, string origem, long? origemId, long usuarioId, object payload, CancellationToken ct) => cn.ExecuteAsync(new CommandDefinition("insert into sigov.agro_evento(tenant_id,entidade_id,exercicio_id,tipo_evento,origem,origem_id,payload_json,created_by,correlation_id) values(@TenantId,@EntidadeId,@ExercicioId,@Tipo,@Origem,@OrigemId,cast(@Payload as jsonb),@UsuarioId,@CorrelationId)", new { TenantId = tenantId, EntidadeId = entidadeId, ExercicioId = exercicioId, Tipo = tipo, Origem = origem, OrigemId = origemId, Payload = JsonSerializer.Serialize(payload), UsuarioId = usuarioId, CorrelationId = Guid.NewGuid() }, cancellationToken: ct));
}
