using Sigov.Application.Common;
using Sigov.Domain.Common;

namespace Sigov.Application.Saneamento;

public static class SaneamentoPermissoes
{
    public const string Modulo = "saneamento";
}

public sealed record SaneamentoFiltro(int Page = 1, int PageSize = 20, string? Termo = null, string? Status = null, long? UnidadeConsumidoraId = null, long? ConsumidorId = null);
public sealed record SaneamentoConsumidorCreateRequest(long PessoaId, string? CodigoConsumidor = null, string TipoConsumidor = "PESSOA_FISICA", string Situacao = "ATIVO", string? Observacao = null);
public sealed record SaneamentoConsumidorUpdateRequest(string CodigoConsumidor, string TipoConsumidor = "PESSOA_FISICA", string Situacao = "ATIVO", string? Observacao = null);
public sealed record SaneamentoConsumidorFiltro(int Page = 1, int PageSize = 20, string? Termo = null, string? Situacao = null);
public sealed record SaneamentoConsumidorResponse(long Id, long PessoaId, string CodigoConsumidor, string TipoConsumidor, string Situacao, string? NomePessoa);

public sealed record LigacaoSaneamentoCreateRequest(long ConsumidorId, string? NumeroLigacao = null, string TipoLigacao = "AGUA", string Situacao = "ATIVA", string Categoria = "RESIDENCIAL", int Economia = 1, DateOnly? DataLigacao = null, string? Observacao = null);
public sealed record LigacaoSaneamentoUpdateRequest(string NumeroLigacao, string TipoLigacao = "AGUA", string Situacao = "ATIVA", string Categoria = "RESIDENCIAL", int Economia = 1, DateOnly? DataLigacao = null, DateOnly? DataCorte = null, string? Observacao = null);
public sealed record LigacaoSaneamentoResponse(long Id, long ConsumidorId, string NumeroLigacao, string TipoLigacao, string Situacao, string Categoria, int Economia);

public sealed record UnidadeConsumidoraCreateRequest(long ConsumidorId, long? LigacaoId = null, string? CodigoUnidade = null, string EnderecoJson = "{}", string? Bairro = null, string? Setor = null, string? Rota = null, int? SequenciaRota = null, decimal? Latitude = null, decimal? Longitude = null, string Situacao = "ATIVA");
public sealed record UnidadeConsumidoraUpdateRequest(long? LigacaoId = null, string CodigoUnidade = "", string EnderecoJson = "{}", string? Bairro = null, string? Setor = null, string? Rota = null, int? SequenciaRota = null, decimal? Latitude = null, decimal? Longitude = null, string Situacao = "ATIVA");
public sealed record UnidadeConsumidoraFiltro(int Page = 1, int PageSize = 20, string? Termo = null, string? Rota = null, string? Situacao = null);
public sealed record UnidadeConsumidoraResponse(long Id, long ConsumidorId, long? LigacaoId, string CodigoUnidade, string? Bairro, string? Rota, int? SequenciaRota, decimal? Latitude, decimal? Longitude, string Situacao);

public sealed record HidrometroCreateRequest(long UnidadeConsumidoraId, string NumeroSerie, string? Marca = null, string? Modelo = null, string? Diametro = null, DateOnly? DataInstalacao = null, decimal LeituraInstalacao = 0, string Situacao = "INSTALADO");
public sealed record HidrometroUpdateRequest(string NumeroSerie, string? Marca = null, string? Modelo = null, string? Diametro = null, DateOnly? DataInstalacao = null, DateOnly? DataRetirada = null, decimal LeituraInstalacao = 0, string Situacao = "INSTALADO");
public sealed record HidrometroResponse(long Id, long UnidadeConsumidoraId, string NumeroSerie, string? Marca, string? Modelo, string Situacao);

public sealed record LeituraConsumoCreateRequest(long UnidadeConsumidoraId, long? HidrometroId, string Competencia, DateOnly DataLeitura, decimal LeituraAnterior, decimal LeituraAtual, decimal? ConsumoFaturado = null, string TipoLeitura = "NORMAL", string? Ocorrencia = null, decimal? Latitude = null, decimal? Longitude = null, string? Observacao = null);
public sealed record LeituraConsumoFiltro(int Page = 1, int PageSize = 20, long? UnidadeConsumidoraId = null, string? Competencia = null);
public sealed record LeituraConsumoResponse(long Id, long UnidadeConsumidoraId, long? HidrometroId, string Competencia, DateOnly DataLeitura, decimal LeituraAnterior, decimal LeituraAtual, decimal ConsumoMedido, decimal ConsumoFaturado, string TipoLeitura);

public sealed record FaturaSaneamentoCreateRequest(long UnidadeConsumidoraId, long? LeituraId, string? Numero, string Competencia, DateOnly DataVencimento, decimal ValorAgua = 0, decimal ValorEsgoto = 0, decimal ValorServicos = 0, decimal ValorMulta = 0, decimal ValorJuros = 0, decimal ValorDesconto = 0);
public sealed record FaturaSaneamentoFiltro(int Page = 1, int PageSize = 20, long? UnidadeConsumidoraId = null, string? Status = null, string? Competencia = null);
public sealed record FaturaSaneamentoItemResponse(long Id, string TipoItem, string Descricao, decimal Quantidade, decimal ValorUnitario, decimal ValorTotal);
public sealed record FaturaSaneamentoResponse(long Id, long UnidadeConsumidoraId, long? LeituraId, string Numero, string Competencia, DateOnly DataVencimento, decimal ValorTotal, decimal ValorPago, string Status, IReadOnlyCollection<FaturaSaneamentoItemResponse>? Itens = null);
public sealed record GerarFaturaPorLeituraRequest(DateOnly DataVencimento, decimal TarifaAgua = 0, decimal TarifaEsgoto = 0, decimal ValorServicos = 0);
public sealed record CancelarFaturaRequest(string Motivo);

public sealed record ArrecadacaoSaneamentoCreateRequest(long FaturaId, string? Numero = null, DateOnly? DataPagamento = null, string FormaPagamento = "MANUAL_DEV", decimal ValorPago = 0, string? Origem = null, string MetadadosJson = "{}");
public sealed record ArrecadacaoSaneamentoResponse(long Id, long FaturaId, string Numero, DateOnly DataPagamento, string FormaPagamento, decimal ValorPago);
public sealed record RegistrarPagamentoDevRequest(decimal ValorPago, DateOnly? DataPagamento = null, string? Origem = "DEV");

public sealed record ParcelamentoSaneamentoCreateRequest(long ConsumidorId, string? Numero = null, int QuantidadeParcelas = 1, decimal ValorTotal = 0, string? Observacao = null);
public sealed record ParcelamentoSaneamentoResponse(long Id, long ConsumidorId, string Numero, int QuantidadeParcelas, decimal ValorTotal, string Status);

public sealed record OrdemServicoSaneamentoCreateRequest(long? UnidadeConsumidoraId, long? ConsumidorId, string? Numero, string TipoServico, string Prioridade = "MEDIA", string Descricao = "", long? EquipeCampoId = null, DateTimeOffset? DataAgendamento = null, decimal? Latitude = null, decimal? Longitude = null);
public sealed record OrdemServicoSaneamentoUpdateRequest(string TipoServico, string Prioridade = "MEDIA", string Status = "ABERTA", string Descricao = "", long? EquipeCampoId = null, DateTimeOffset? DataAgendamento = null, decimal? Latitude = null, decimal? Longitude = null);
public sealed record OrdemServicoSaneamentoFiltro(int Page = 1, int PageSize = 20, string? Status = null, long? UnidadeConsumidoraId = null);
public sealed record OrdemServicoSaneamentoResponse(long Id, string Numero, long? UnidadeConsumidoraId, long? ConsumidorId, string TipoServico, string Prioridade, string Status, DateTimeOffset DataAbertura);
public sealed record ExecutarOrdemServicoRequest(string Solucao, long? EquipeCampoId = null, string? MateriaisJson = "[]", string? EvidenciasJson = "[]");
public sealed record CancelarOrdemServicoRequest(string Motivo);

public sealed record EquipeCampoSaneamentoCreateRequest(string? Codigo = null, string Nome = "", long? ResponsavelUsuarioId = null, string MembrosJson = "[]");
public sealed record EquipeCampoSaneamentoResponse(long Id, string Codigo, string Nome, long? ResponsavelUsuarioId, bool Ativo);

public sealed record LaboratorioAmostraCreateRequest(string? Numero, string PontoColeta, DateTimeOffset DataColeta, long? ColetadoPorUsuarioId = null, decimal? Latitude = null, decimal? Longitude = null, string Status = "COLETADA", string? Observacao = null);
public sealed record LaboratorioResultadoCreateRequest(string Parametro, string Valor, string? Unidade = null, string? LimiteReferencia = null, bool? Conforme = null, DateOnly? DataResultado = null, string? Observacao = null);
public sealed record LaboratorioAmostraResponse(long Id, string Numero, string PontoColeta, DateTimeOffset DataColeta, string Status);
public sealed record LaboratorioResultadoResponse(long Id, long AmostraId, string Parametro, string Valor, bool? Conforme);

public sealed record RedeSaneamentoTrechoCreateRequest(string? Codigo, string TipoRede, string? Material = null, string? Diametro = null, decimal? ExtensaoMetros = null, string? GeometriaGeoJson = null, string Situacao = "ATIVA");
public sealed record RedeSaneamentoTrechoResponse(long Id, string Codigo, string TipoRede, string? Material, string? Diametro, decimal? ExtensaoMetros, string Situacao);

public sealed record SaneamentoDashboardResponse(long TotalConsumidores, long TotalUnidadesConsumidoras, long LigacoesAtivas, long HidrometrosAtivos, long LeiturasPendentes, long FaturasAbertas, long FaturasVencidas, decimal ValorFaturadoMes, decimal ValorArrecadadoMes, decimal InadimplenciaMes, long OrdensAbertas, long OrdensEmCampo, long OrdensExecutadasMes, long AmostrasPendentes, long ResultadosNaoConformes, long TrechosRedeCadastrados, IReadOnlyCollection<object> UltimasLeituras, IReadOnlyCollection<object> UltimasFaturas, IReadOnlyCollection<object> UltimasOrdensServico, IReadOnlyCollection<string> Alertas);

public interface ISaneamentoConsumidorRepository { Task<PagedResult<SaneamentoConsumidorResponse>> ListarAsync(long tenantId,long entidadeId,SaneamentoConsumidorFiltro filtro,CancellationToken ct); Task<SaneamentoConsumidorResponse?> ObterAsync(long tenantId,long entidadeId,long id,bool completo,CancellationToken ct); Task<long> CriarAsync(long tenantId,long entidadeId,long? usuarioId,SaneamentoConsumidorCreateRequest request,string codigo,CancellationToken ct); Task AtualizarAsync(long tenantId,long entidadeId,long id,long? usuarioId,SaneamentoConsumidorUpdateRequest request,CancellationToken ct); Task ExcluirAsync(long tenantId,long entidadeId,long id,long? usuarioId,CancellationToken ct); }
public interface ILigacaoSaneamentoRepository { Task<PagedResult<LigacaoSaneamentoResponse>> ListarAsync(long tenantId,long entidadeId,SaneamentoFiltro filtro,CancellationToken ct); Task<LigacaoSaneamentoResponse?> ObterAsync(long tenantId,long entidadeId,long id,CancellationToken ct); Task<long> CriarAsync(long tenantId,long entidadeId,long? usuarioId,LigacaoSaneamentoCreateRequest request,string numero,CancellationToken ct); Task AtualizarAsync(long tenantId,long entidadeId,long id,long? usuarioId,LigacaoSaneamentoUpdateRequest request,CancellationToken ct); Task ExcluirAsync(long tenantId,long entidadeId,long id,long? usuarioId,CancellationToken ct); }
public interface IUnidadeConsumidoraRepository { Task<PagedResult<UnidadeConsumidoraResponse>> ListarAsync(long tenantId,long entidadeId,UnidadeConsumidoraFiltro filtro,CancellationToken ct); Task<UnidadeConsumidoraResponse?> ObterAsync(long tenantId,long entidadeId,long id,CancellationToken ct); Task<long> CriarAsync(long tenantId,long entidadeId,long? usuarioId,UnidadeConsumidoraCreateRequest request,string codigo,CancellationToken ct); Task AtualizarAsync(long tenantId,long entidadeId,long id,long? usuarioId,UnidadeConsumidoraUpdateRequest request,CancellationToken ct); Task ExcluirAsync(long tenantId,long entidadeId,long id,long? usuarioId,CancellationToken ct); }
public interface IHidrometroRepository { Task<PagedResult<HidrometroResponse>> ListarAsync(long tenantId,long entidadeId,SaneamentoFiltro filtro,CancellationToken ct); Task<long> CriarAsync(long tenantId,long entidadeId,long? usuarioId,HidrometroCreateRequest request,CancellationToken ct); Task AtualizarAsync(long tenantId,long entidadeId,long id,long? usuarioId,HidrometroUpdateRequest request,CancellationToken ct); Task ExcluirAsync(long tenantId,long entidadeId,long id,long? usuarioId,CancellationToken ct); }
public interface ILeituraConsumoRepository { Task<PagedResult<LeituraConsumoResponse>> ListarAsync(long tenantId,long entidadeId,LeituraConsumoFiltro filtro,CancellationToken ct); Task<LeituraConsumoResponse?> ObterAsync(long tenantId,long entidadeId,long id,CancellationToken ct); Task<long> CriarAsync(long tenantId,long entidadeId,long? exercicioId,long? usuarioId,LeituraConsumoCreateRequest request,decimal consumoMedido,decimal consumoFaturado,CancellationToken ct); }
public interface IFaturaSaneamentoRepository { Task<PagedResult<FaturaSaneamentoResponse>> ListarAsync(long tenantId,long entidadeId,FaturaSaneamentoFiltro filtro,CancellationToken ct); Task<FaturaSaneamentoResponse?> ObterAsync(long tenantId,long entidadeId,long id,CancellationToken ct); Task<long> CriarAsync(long tenantId,long entidadeId,long? exercicioId,long? usuarioId,FaturaSaneamentoCreateRequest request,string numero,decimal total,string ambiente,CancellationToken ct); Task<long> GerarPorLeituraAsync(long tenantId,long entidadeId,long? exercicioId,long leituraId,long? usuarioId,GerarFaturaPorLeituraRequest request,string numero,string ambiente,CancellationToken ct); Task CancelarAsync(long tenantId,long entidadeId,long id,long? usuarioId,string motivo,CancellationToken ct); Task<ArrecadacaoSaneamentoResponse> RegistrarPagamentoDevAsync(long tenantId,long entidadeId,long? exercicioId,long id,long? usuarioId,RegistrarPagamentoDevRequest request,string numero,CancellationToken ct); }
public interface IArrecadacaoSaneamentoRepository { Task<PagedResult<ArrecadacaoSaneamentoResponse>> ListarAsync(long tenantId,long entidadeId,SaneamentoFiltro filtro,CancellationToken ct); Task<long> CriarAsync(long tenantId,long entidadeId,long? exercicioId,long? usuarioId,ArrecadacaoSaneamentoCreateRequest request,string numero,CancellationToken ct); }
public interface IParcelamentoSaneamentoRepository { Task<PagedResult<ParcelamentoSaneamentoResponse>> ListarAsync(long tenantId,long entidadeId,SaneamentoFiltro filtro,CancellationToken ct); Task<long> CriarAsync(long tenantId,long entidadeId,long? exercicioId,long? usuarioId,ParcelamentoSaneamentoCreateRequest request,string numero,CancellationToken ct); }
public interface IOrdemServicoSaneamentoRepository { Task<PagedResult<OrdemServicoSaneamentoResponse>> ListarAsync(long tenantId,long entidadeId,OrdemServicoSaneamentoFiltro filtro,CancellationToken ct); Task<OrdemServicoSaneamentoResponse?> ObterAsync(long tenantId,long entidadeId,long id,CancellationToken ct); Task<long> CriarAsync(long tenantId,long entidadeId,long? exercicioId,long? usuarioId,OrdemServicoSaneamentoCreateRequest request,string numero,CancellationToken ct); Task AtualizarAsync(long tenantId,long entidadeId,long id,long? usuarioId,OrdemServicoSaneamentoUpdateRequest request,CancellationToken ct); Task ExecutarAsync(long tenantId,long entidadeId,long? exercicioId,long id,long? usuarioId,ExecutarOrdemServicoRequest request,CancellationToken ct); Task CancelarAsync(long tenantId,long entidadeId,long id,long? usuarioId,string motivo,CancellationToken ct); }
public interface IEquipeCampoSaneamentoRepository { Task<PagedResult<EquipeCampoSaneamentoResponse>> ListarAsync(long tenantId,long entidadeId,SaneamentoFiltro filtro,CancellationToken ct); Task<long> CriarAsync(long tenantId,long entidadeId,long? usuarioId,EquipeCampoSaneamentoCreateRequest request,string codigo,CancellationToken ct); }
public interface ILaboratorioSaneamentoRepository { Task<PagedResult<LaboratorioAmostraResponse>> ListarAsync(long tenantId,long entidadeId,SaneamentoFiltro filtro,CancellationToken ct); Task<long> CriarAmostraAsync(long tenantId,long entidadeId,long? exercicioId,long? usuarioId,LaboratorioAmostraCreateRequest request,string numero,CancellationToken ct); Task<long> CriarResultadoAsync(long tenantId,long entidadeId,long amostraId,long? usuarioId,LaboratorioResultadoCreateRequest request,CancellationToken ct); }
public interface IRedeSaneamentoRepository { Task<PagedResult<RedeSaneamentoTrechoResponse>> ListarAsync(long tenantId,long entidadeId,SaneamentoFiltro filtro,CancellationToken ct); Task<long> CriarAsync(long tenantId,long entidadeId,long? usuarioId,RedeSaneamentoTrechoCreateRequest request,string codigo,CancellationToken ct); }
public interface ISaneamentoDashboardRepository { Task<SaneamentoDashboardResponse> ObterAsync(long tenantId,long entidadeId,CancellationToken ct); }
public interface ISaneamentoExportacaoRepository { Task<byte[]> ExportarAsync(long tenantId,long entidadeId,string recurso,string formato,CancellationToken ct); }
public interface ISaneamentoSequencialService { Task<string> ProximoAsync(long tenantId,long entidadeId,string prefixo,CancellationToken ct); }

public interface ISaneamentoConsumidorService { Task<Result<PagedResult<SaneamentoConsumidorResponse>>> ListarAsync(SaneamentoConsumidorFiltro filtro,CancellationToken ct); Task<Result<SaneamentoConsumidorResponse>> ObterAsync(long id,bool completo,CancellationToken ct); Task<Result<long>> CriarAsync(SaneamentoConsumidorCreateRequest request,CancellationToken ct); Task<Result> AtualizarAsync(long id,SaneamentoConsumidorUpdateRequest request,CancellationToken ct); Task<Result> ExcluirAsync(long id,CancellationToken ct); }
public interface ILigacaoSaneamentoService { Task<Result<PagedResult<LigacaoSaneamentoResponse>>> ListarAsync(SaneamentoFiltro filtro,CancellationToken ct); Task<Result<LigacaoSaneamentoResponse>> ObterAsync(long id,CancellationToken ct); Task<Result<long>> CriarAsync(LigacaoSaneamentoCreateRequest request,CancellationToken ct); Task<Result> AtualizarAsync(long id,LigacaoSaneamentoUpdateRequest request,CancellationToken ct); Task<Result> ExcluirAsync(long id,CancellationToken ct); }
public interface IUnidadeConsumidoraService { Task<Result<PagedResult<UnidadeConsumidoraResponse>>> ListarAsync(UnidadeConsumidoraFiltro filtro,CancellationToken ct); Task<Result<UnidadeConsumidoraResponse>> ObterAsync(long id,CancellationToken ct); Task<Result<long>> CriarAsync(UnidadeConsumidoraCreateRequest request,CancellationToken ct); Task<Result> AtualizarAsync(long id,UnidadeConsumidoraUpdateRequest request,CancellationToken ct); Task<Result> ExcluirAsync(long id,CancellationToken ct); }
public interface IHidrometroService { Task<Result<PagedResult<HidrometroResponse>>> ListarAsync(SaneamentoFiltro filtro,CancellationToken ct); Task<Result<long>> CriarAsync(HidrometroCreateRequest request,CancellationToken ct); Task<Result> AtualizarAsync(long id,HidrometroUpdateRequest request,CancellationToken ct); Task<Result> ExcluirAsync(long id,CancellationToken ct); }
public interface ILeituraConsumoService { Task<Result<PagedResult<LeituraConsumoResponse>>> ListarAsync(LeituraConsumoFiltro filtro,CancellationToken ct); Task<Result<long>> CriarAsync(LeituraConsumoCreateRequest request,CancellationToken ct); Task<Result<long>> GerarFaturaAsync(long id,GerarFaturaPorLeituraRequest request,CancellationToken ct); }
public interface IFaturaSaneamentoService { Task<Result<PagedResult<FaturaSaneamentoResponse>>> ListarAsync(FaturaSaneamentoFiltro filtro,CancellationToken ct); Task<Result<FaturaSaneamentoResponse>> ObterAsync(long id,CancellationToken ct); Task<Result<long>> CriarAsync(FaturaSaneamentoCreateRequest request,CancellationToken ct); Task<Result> CancelarAsync(long id,CancelarFaturaRequest request,CancellationToken ct); Task<Result<ArrecadacaoSaneamentoResponse>> RegistrarPagamentoDevAsync(long id,RegistrarPagamentoDevRequest request,CancellationToken ct); }
public interface IArrecadacaoSaneamentoService { Task<Result<PagedResult<ArrecadacaoSaneamentoResponse>>> ListarAsync(SaneamentoFiltro filtro,CancellationToken ct); Task<Result<long>> CriarAsync(ArrecadacaoSaneamentoCreateRequest request,CancellationToken ct); }
public interface IParcelamentoSaneamentoService { Task<Result<PagedResult<ParcelamentoSaneamentoResponse>>> ListarAsync(SaneamentoFiltro filtro,CancellationToken ct); Task<Result<long>> CriarAsync(ParcelamentoSaneamentoCreateRequest request,CancellationToken ct); }
public interface IOrdemServicoSaneamentoService { Task<Result<PagedResult<OrdemServicoSaneamentoResponse>>> ListarAsync(OrdemServicoSaneamentoFiltro filtro,CancellationToken ct); Task<Result<OrdemServicoSaneamentoResponse>> ObterAsync(long id,CancellationToken ct); Task<Result<long>> CriarAsync(OrdemServicoSaneamentoCreateRequest request,CancellationToken ct); Task<Result> AtualizarAsync(long id,OrdemServicoSaneamentoUpdateRequest request,CancellationToken ct); Task<Result> ExecutarAsync(long id,ExecutarOrdemServicoRequest request,CancellationToken ct); Task<Result> CancelarAsync(long id,CancelarOrdemServicoRequest request,CancellationToken ct); }
public interface IEquipeCampoSaneamentoService { Task<Result<PagedResult<EquipeCampoSaneamentoResponse>>> ListarAsync(SaneamentoFiltro filtro,CancellationToken ct); Task<Result<long>> CriarAsync(EquipeCampoSaneamentoCreateRequest request,CancellationToken ct); }
public interface ILaboratorioSaneamentoService { Task<Result<PagedResult<LaboratorioAmostraResponse>>> ListarAsync(SaneamentoFiltro filtro,CancellationToken ct); Task<Result<long>> CriarAmostraAsync(LaboratorioAmostraCreateRequest request,CancellationToken ct); Task<Result<long>> CriarResultadoAsync(long amostraId,LaboratorioResultadoCreateRequest request,CancellationToken ct); }
public interface IRedeSaneamentoService { Task<Result<PagedResult<RedeSaneamentoTrechoResponse>>> ListarAsync(SaneamentoFiltro filtro,CancellationToken ct); Task<Result<long>> CriarAsync(RedeSaneamentoTrechoCreateRequest request,CancellationToken ct); }
public interface ISaneamentoDashboardService { Task<Result<SaneamentoDashboardResponse>> ObterAsync(CancellationToken ct); }
public interface ISaneamentoExportacaoService { Task<Result<byte[]>> ExportarAsync(string recurso,string formato,CancellationToken ct); }
