using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Sigov.Application.Abstractions;
using Sigov.Application.Common;
using Sigov.Application.Saas;
using Sigov.Domain.Common;
using Sigov.Domain.Saneamento;

namespace Sigov.Application.Saneamento;

public sealed class SaneamentoService : ISaneamentoConsumidorService, ILigacaoSaneamentoService, IUnidadeConsumidoraService, IHidrometroService, ILeituraConsumoService, IFaturaSaneamentoService, IArrecadacaoSaneamentoService, IParcelamentoSaneamentoService, IOrdemServicoSaneamentoService, IEquipeCampoSaneamentoService, ILaboratorioSaneamentoService, IRedeSaneamentoService, ISaneamentoDashboardService, ISaneamentoExportacaoService
{
    private readonly ICurrentTenant _tenant; private readonly ICurrentUser _user; private readonly IModuloLicenciamentoService _modulos; private readonly IPermissionService _permissoes; private readonly IAuditService _audit; private readonly ISaneamentoSequencialService _seq; private readonly IHostEnvironment _env; private readonly ILogger<SaneamentoService> _logger;
    private readonly ISaneamentoConsumidorRepository _consumidores; private readonly ILigacaoSaneamentoRepository _ligacoes; private readonly IUnidadeConsumidoraRepository _unidades; private readonly IHidrometroRepository _hidrometros; private readonly ILeituraConsumoRepository _leituras; private readonly IFaturaSaneamentoRepository _faturas; private readonly IArrecadacaoSaneamentoRepository _arrecadacoes; private readonly IParcelamentoSaneamentoRepository _parcelamentos; private readonly IOrdemServicoSaneamentoRepository _ordens; private readonly IEquipeCampoSaneamentoRepository _equipes; private readonly ILaboratorioSaneamentoRepository _laboratorio; private readonly IRedeSaneamentoRepository _rede; private readonly ISaneamentoDashboardRepository _dashboard; private readonly ISaneamentoExportacaoRepository _exportacao;
    public SaneamentoService(ICurrentTenant tenant, ICurrentUser user, IModuloLicenciamentoService modulos, IPermissionService permissoes, IAuditService audit, ISaneamentoSequencialService seq, IHostEnvironment env, ILogger<SaneamentoService> logger, ISaneamentoConsumidorRepository consumidores, ILigacaoSaneamentoRepository ligacoes, IUnidadeConsumidoraRepository unidades, IHidrometroRepository hidrometros, ILeituraConsumoRepository leituras, IFaturaSaneamentoRepository faturas, IArrecadacaoSaneamentoRepository arrecadacoes, IParcelamentoSaneamentoRepository parcelamentos, IOrdemServicoSaneamentoRepository ordens, IEquipeCampoSaneamentoRepository equipes, ILaboratorioSaneamentoRepository laboratorio, IRedeSaneamentoRepository rede, ISaneamentoDashboardRepository dashboard, ISaneamentoExportacaoRepository exportacao)
    { _tenant=tenant; _user=user; _modulos=modulos; _permissoes=permissoes; _audit=audit; _seq=seq; _env=env; _logger=logger; _consumidores=consumidores; _ligacoes=ligacoes; _unidades=unidades; _hidrometros=hidrometros; _leituras=leituras; _faturas=faturas; _arrecadacoes=arrecadacoes; _parcelamentos=parcelamentos; _ordens=ordens; _equipes=equipes; _laboratorio=laboratorio; _rede=rede; _dashboard=dashboard; _exportacao=exportacao; }
    private async Task<Result<(long TenantId,long EntidadeId,long? ExercicioId,long? UsuarioId)>> Ctx(string recurso,string acao,CancellationToken ct){ if(!_tenant.TenantId.HasValue||!_tenant.EntidadeId.HasValue)return Result<(long,long,long?,long?)>.Failure("Tenant e entidade são obrigatórios."); if(!await _modulos.IsModuleEnabledAsync(_tenant.TenantId.Value,SaneamentoPermissoes.Modulo,ct).ConfigureAwait(false))return Result<(long,long,long?,long?)>.Failure("Módulo saneamento não contratado ou desabilitado para o tenant."); if(_user.UsuarioId.HasValue&&!await _permissoes.HasPermissionAsync(_user.UsuarioId.Value,"saneamento",recurso,acao,ct).ConfigureAwait(false))return Result<(long,long,long?,long?)>.Failure("Usuário sem permissão para saneamento."); return Result<(long,long,long?,long?)>.Success((_tenant.TenantId.Value,_tenant.EntidadeId.Value,_tenant.ExercicioId,_user.UsuarioId)); }
    private static int Page(int p)=>p<=0?1:p; private static int Size(int s)=>s is <=0 or >100?20:s;

    async Task<Result<PagedResult<SaneamentoConsumidorResponse>>> ISaneamentoConsumidorService.ListarAsync(SaneamentoConsumidorFiltro f,CancellationToken ct){var c=await Ctx("consumidor","visualizar",ct); if(c.IsFailure)return Result<PagedResult<SaneamentoConsumidorResponse>>.Failure(c.Error!); var v=c.Value!; return Result<PagedResult<SaneamentoConsumidorResponse>>.Success(await _consumidores.ListarAsync(v.TenantId,v.EntidadeId,f with{Page=Page(f.Page),PageSize=Size(f.PageSize)},ct));}
    async Task<Result<SaneamentoConsumidorResponse>> ISaneamentoConsumidorService.ObterAsync(long id,bool completo,CancellationToken ct){var c=await Ctx("consumidor",completo?"visualizar_dados_completos":"visualizar",ct); if(c.IsFailure)return Result<SaneamentoConsumidorResponse>.Failure(c.Error!); var v=c.Value!; var item=await _consumidores.ObterAsync(v.TenantId,v.EntidadeId,id,completo,ct); await _audit.RegistrarAsync("saneamento","ACESSO_DADO_PESSOAL","sigov.saneamento_consumidor",id.ToString(),null,new{id,completo},ct); return item is null?Result<SaneamentoConsumidorResponse>.Failure("Consumidor não encontrado."):Result<SaneamentoConsumidorResponse>.Success(item);}
    async Task<Result<long>> ISaneamentoConsumidorService.CriarAsync(SaneamentoConsumidorCreateRequest r,CancellationToken ct){var c=await Ctx("consumidor","criar",ct); if(c.IsFailure)return Result<long>.Failure(c.Error!); var v=c.Value!; try{ _=new SaneamentoConsumidor(v.TenantId,v.EntidadeId,r.PessoaId,r.CodigoConsumidor??"CON"); var codigo=r.CodigoConsumidor??await _seq.ProximoAsync(v.TenantId,v.EntidadeId,"CON",ct); var id=await _consumidores.CriarAsync(v.TenantId,v.EntidadeId,v.UsuarioId,r,codigo,ct); await _audit.RegistrarAsync("saneamento","CRIAR","sigov.saneamento_consumidor",id.ToString(),null,r,ct); return Result<long>.Success(id);}catch(Exception ex){_logger.LogWarning(ex,"Falha ao criar consumidor de saneamento"); return Result<long>.Failure(ex.Message);}}
    async Task<Result> ISaneamentoConsumidorService.AtualizarAsync(long id,SaneamentoConsumidorUpdateRequest r,CancellationToken ct){var c=await Ctx("consumidor","editar",ct); if(c.IsFailure)return Result.Failure(c.Error!); var v=c.Value!; await _consumidores.AtualizarAsync(v.TenantId,v.EntidadeId,id,v.UsuarioId,r,ct); await _audit.RegistrarAsync("saneamento","ALTERAR","sigov.saneamento_consumidor",id.ToString(),null,r,ct); return Result.Success();}
    async Task<Result> ISaneamentoConsumidorService.ExcluirAsync(long id,CancellationToken ct){var c=await Ctx("consumidor","excluir",ct); if(c.IsFailure)return Result.Failure(c.Error!); var v=c.Value!; await _consumidores.ExcluirAsync(v.TenantId,v.EntidadeId,id,v.UsuarioId,ct); await _audit.RegistrarAsync("saneamento","EXCLUIR","sigov.saneamento_consumidor",id.ToString(),null,new{id},ct); return Result.Success();}

    async Task<Result<PagedResult<LigacaoSaneamentoResponse>>> ILigacaoSaneamentoService.ListarAsync(SaneamentoFiltro f,CancellationToken ct){var c=await Ctx("ligacao","visualizar",ct); if(c.IsFailure)return Result<PagedResult<LigacaoSaneamentoResponse>>.Failure(c.Error!); var v=c.Value!; return Result<PagedResult<LigacaoSaneamentoResponse>>.Success(await _ligacoes.ListarAsync(v.TenantId,v.EntidadeId,f with{Page=Page(f.Page),PageSize=Size(f.PageSize)},ct));}
    async Task<Result<LigacaoSaneamentoResponse>> ILigacaoSaneamentoService.ObterAsync(long id,CancellationToken ct){var c=await Ctx("ligacao","visualizar",ct); if(c.IsFailure)return Result<LigacaoSaneamentoResponse>.Failure(c.Error!); var v=c.Value!; var item=await _ligacoes.ObterAsync(v.TenantId,v.EntidadeId,id,ct); return item is null?Result<LigacaoSaneamentoResponse>.Failure("Ligação não encontrada."):Result<LigacaoSaneamentoResponse>.Success(item);}
    async Task<Result<long>> ILigacaoSaneamentoService.CriarAsync(LigacaoSaneamentoCreateRequest r,CancellationToken ct){var c=await Ctx("ligacao","criar",ct); if(c.IsFailure)return Result<long>.Failure(c.Error!); var v=c.Value!; var numero=r.NumeroLigacao??await _seq.ProximoAsync(v.TenantId,v.EntidadeId,"LIG",ct); var id=await _ligacoes.CriarAsync(v.TenantId,v.EntidadeId,v.UsuarioId,r,numero,ct); await _audit.RegistrarAsync("saneamento","CRIAR","sigov.saneamento_ligacao",id.ToString(),null,r,ct); return Result<long>.Success(id);}
    async Task<Result> ILigacaoSaneamentoService.AtualizarAsync(long id,LigacaoSaneamentoUpdateRequest r,CancellationToken ct){var c=await Ctx("ligacao","editar",ct); if(c.IsFailure)return Result.Failure(c.Error!); var v=c.Value!; await _ligacoes.AtualizarAsync(v.TenantId,v.EntidadeId,id,v.UsuarioId,r,ct); return Result.Success();}
    async Task<Result> ILigacaoSaneamentoService.ExcluirAsync(long id,CancellationToken ct){var c=await Ctx("ligacao","excluir",ct); if(c.IsFailure)return Result.Failure(c.Error!); var v=c.Value!; await _ligacoes.ExcluirAsync(v.TenantId,v.EntidadeId,id,v.UsuarioId,ct); return Result.Success();}

    async Task<Result<PagedResult<UnidadeConsumidoraResponse>>> IUnidadeConsumidoraService.ListarAsync(UnidadeConsumidoraFiltro f,CancellationToken ct){var c=await Ctx("unidade_consumidora","visualizar",ct); if(c.IsFailure)return Result<PagedResult<UnidadeConsumidoraResponse>>.Failure(c.Error!); var v=c.Value!; var r=await _unidades.ListarAsync(v.TenantId,v.EntidadeId,f with{Page=Page(f.Page),PageSize=Size(f.PageSize)},ct); await _audit.RegistrarAsync("saneamento","ACESSO_DADO_PESSOAL","sigov.saneamento_unidade_consumidora","lista",null,new{f.Page,f.PageSize},ct); return Result<PagedResult<UnidadeConsumidoraResponse>>.Success(r);}
    async Task<Result<UnidadeConsumidoraResponse>> IUnidadeConsumidoraService.ObterAsync(long id,CancellationToken ct){var c=await Ctx("unidade_consumidora","visualizar",ct); if(c.IsFailure)return Result<UnidadeConsumidoraResponse>.Failure(c.Error!); var v=c.Value!; var item=await _unidades.ObterAsync(v.TenantId,v.EntidadeId,id,ct); return item is null?Result<UnidadeConsumidoraResponse>.Failure("Unidade não encontrada."):Result<UnidadeConsumidoraResponse>.Success(item);}
    async Task<Result<long>> IUnidadeConsumidoraService.CriarAsync(UnidadeConsumidoraCreateRequest r,CancellationToken ct){var c=await Ctx("unidade_consumidora","criar",ct); if(c.IsFailure)return Result<long>.Failure(c.Error!); var v=c.Value!; _=new UnidadeConsumidora(v.TenantId,v.EntidadeId,r.ConsumidorId,r.CodigoUnidade??"UC",r.Latitude,r.Longitude); var codigo=r.CodigoUnidade??await _seq.ProximoAsync(v.TenantId,v.EntidadeId,"UC",ct); var id=await _unidades.CriarAsync(v.TenantId,v.EntidadeId,v.UsuarioId,r,codigo,ct); await _audit.RegistrarAsync("saneamento","CRIAR","sigov.saneamento_unidade_consumidora",id.ToString(),null,r,ct); return Result<long>.Success(id);}
    async Task<Result> IUnidadeConsumidoraService.AtualizarAsync(long id,UnidadeConsumidoraUpdateRequest r,CancellationToken ct){var c=await Ctx("unidade_consumidora","editar",ct); if(c.IsFailure)return Result.Failure(c.Error!); var v=c.Value!; await _unidades.AtualizarAsync(v.TenantId,v.EntidadeId,id,v.UsuarioId,r,ct); return Result.Success();}
    async Task<Result> IUnidadeConsumidoraService.ExcluirAsync(long id,CancellationToken ct){var c=await Ctx("unidade_consumidora","excluir",ct); if(c.IsFailure)return Result.Failure(c.Error!); var v=c.Value!; await _unidades.ExcluirAsync(v.TenantId,v.EntidadeId,id,v.UsuarioId,ct); return Result.Success();}

    async Task<Result<PagedResult<HidrometroResponse>>> IHidrometroService.ListarAsync(SaneamentoFiltro f,CancellationToken ct){var c=await Ctx("hidrometro","visualizar",ct); if(c.IsFailure)return Result<PagedResult<HidrometroResponse>>.Failure(c.Error!); var v=c.Value!; return Result<PagedResult<HidrometroResponse>>.Success(await _hidrometros.ListarAsync(v.TenantId,v.EntidadeId,f with{Page=Page(f.Page),PageSize=Size(f.PageSize)},ct));}
    async Task<Result<long>> IHidrometroService.CriarAsync(HidrometroCreateRequest r,CancellationToken ct){var c=await Ctx("hidrometro","criar",ct); if(c.IsFailure)return Result<long>.Failure(c.Error!); var v=c.Value!; _=new Hidrometro(v.TenantId,v.EntidadeId,r.UnidadeConsumidoraId,r.NumeroSerie); var id=await _hidrometros.CriarAsync(v.TenantId,v.EntidadeId,v.UsuarioId,r,ct); await _audit.RegistrarAsync("saneamento","CRIAR","sigov.saneamento_hidrometro",id.ToString(),null,r,ct); return Result<long>.Success(id);}
    async Task<Result> IHidrometroService.AtualizarAsync(long id,HidrometroUpdateRequest r,CancellationToken ct){var c=await Ctx("hidrometro","editar",ct); if(c.IsFailure)return Result.Failure(c.Error!); var v=c.Value!; await _hidrometros.AtualizarAsync(v.TenantId,v.EntidadeId,id,v.UsuarioId,r,ct); return Result.Success();}
    async Task<Result> IHidrometroService.ExcluirAsync(long id,CancellationToken ct){var c=await Ctx("hidrometro","excluir",ct); if(c.IsFailure)return Result.Failure(c.Error!); var v=c.Value!; await _hidrometros.ExcluirAsync(v.TenantId,v.EntidadeId,id,v.UsuarioId,ct); return Result.Success();}

    async Task<Result<PagedResult<LeituraConsumoResponse>>> ILeituraConsumoService.ListarAsync(LeituraConsumoFiltro f,CancellationToken ct){var c=await Ctx("leitura","visualizar",ct); if(c.IsFailure)return Result<PagedResult<LeituraConsumoResponse>>.Failure(c.Error!); var v=c.Value!; return Result<PagedResult<LeituraConsumoResponse>>.Success(await _leituras.ListarAsync(v.TenantId,v.EntidadeId,f with{Page=Page(f.Page),PageSize=Size(f.PageSize)},ct));}
    async Task<Result<long>> ILeituraConsumoService.CriarAsync(LeituraConsumoCreateRequest r,CancellationToken ct){var c=await Ctx("leitura","criar",ct); if(c.IsFailure)return Result<long>.Failure(c.Error!); var v=c.Value!; var tipo=Enum.TryParse<TipoLeitura>(r.TipoLeitura,true,out var parsed)?parsed:TipoLeitura.Normal; var consumo=r.LeituraAtual-r.LeituraAnterior; _=new LeituraConsumo(v.TenantId,v.EntidadeId,r.UnidadeConsumidoraId,r.LeituraAnterior,r.LeituraAtual,r.ConsumoFaturado??consumo,tipo,r.Observacao,r.Latitude,r.Longitude); var id=await _leituras.CriarAsync(v.TenantId,v.EntidadeId,v.ExercicioId,v.UsuarioId,r,consumo,r.ConsumoFaturado??consumo,ct); await _audit.RegistrarAsync("saneamento","CRIAR","sigov.saneamento_leitura",id.ToString(),null,r,ct); return Result<long>.Success(id);}
    async Task<Result<long>> ILeituraConsumoService.GerarFaturaAsync(long id,GerarFaturaPorLeituraRequest r,CancellationToken ct){var c=await Ctx("leitura","gerar_fatura",ct); if(c.IsFailure)return Result<long>.Failure(c.Error!); var v=c.Value!; var numero=await _seq.ProximoAsync(v.TenantId,v.EntidadeId,"FAT",ct); var fid=await _faturas.GerarPorLeituraAsync(v.TenantId,v.EntidadeId,v.ExercicioId,id,v.UsuarioId,r,numero,_env.EnvironmentName,ct); await _audit.RegistrarAsync("saneamento","GERAR_FATURA","sigov.saneamento_fatura",fid.ToString(),null,r,ct); return Result<long>.Success(fid);}

    async Task<Result<PagedResult<FaturaSaneamentoResponse>>> IFaturaSaneamentoService.ListarAsync(FaturaSaneamentoFiltro f,CancellationToken ct){var c=await Ctx("fatura","visualizar",ct); if(c.IsFailure)return Result<PagedResult<FaturaSaneamentoResponse>>.Failure(c.Error!); var v=c.Value!; await _audit.RegistrarAsync("saneamento","ACESSO_DADO_PESSOAL","sigov.saneamento_fatura","lista",null,new{f.Page,f.PageSize},ct); return Result<PagedResult<FaturaSaneamentoResponse>>.Success(await _faturas.ListarAsync(v.TenantId,v.EntidadeId,f with{Page=Page(f.Page),PageSize=Size(f.PageSize)},ct));}
    async Task<Result<FaturaSaneamentoResponse>> IFaturaSaneamentoService.ObterAsync(long id,CancellationToken ct){var c=await Ctx("fatura","visualizar",ct); if(c.IsFailure)return Result<FaturaSaneamentoResponse>.Failure(c.Error!); var v=c.Value!; var item=await _faturas.ObterAsync(v.TenantId,v.EntidadeId,id,ct); return item is null?Result<FaturaSaneamentoResponse>.Failure("Fatura não encontrada."):Result<FaturaSaneamentoResponse>.Success(item);}
    async Task<Result<long>> IFaturaSaneamentoService.CriarAsync(FaturaSaneamentoCreateRequest r,CancellationToken ct){var c=await Ctx("fatura","criar",ct); if(c.IsFailure)return Result<long>.Failure(c.Error!); var v=c.Value!; var total=r.ValorAgua+r.ValorEsgoto+r.ValorServicos+r.ValorMulta+r.ValorJuros-r.ValorDesconto; _=new FaturaSaneamento(v.TenantId,v.EntidadeId,r.UnidadeConsumidoraId,r.Numero??"FAT",total); var numero=r.Numero??await _seq.ProximoAsync(v.TenantId,v.EntidadeId,"FAT",ct); var id=await _faturas.CriarAsync(v.TenantId,v.EntidadeId,v.ExercicioId,v.UsuarioId,r,numero,total,_env.EnvironmentName,ct); await _audit.RegistrarAsync("saneamento","CRIAR","sigov.saneamento_fatura",id.ToString(),null,r,ct); return Result<long>.Success(id);}
    async Task<Result> IFaturaSaneamentoService.CancelarAsync(long id,CancelarFaturaRequest r,CancellationToken ct){var c=await Ctx("fatura","cancelar",ct); if(c.IsFailure)return Result.Failure(c.Error!); var v=c.Value!; await _faturas.CancelarAsync(v.TenantId,v.EntidadeId,id,v.UsuarioId,r.Motivo,ct); await _audit.RegistrarAsync("saneamento","CANCELAR","sigov.saneamento_fatura",id.ToString(),null,r,ct); return Result.Success();}
    async Task<Result<ArrecadacaoSaneamentoResponse>> IFaturaSaneamentoService.RegistrarPagamentoDevAsync(long id,RegistrarPagamentoDevRequest r,CancellationToken ct){ if(!_env.IsDevelopment())return Result<ArrecadacaoSaneamentoResponse>.Failure("Pagamento manual/dev bloqueado fora de Development."); var c=await Ctx("fatura","registrar_pagamento_dev",ct); if(c.IsFailure)return Result<ArrecadacaoSaneamentoResponse>.Failure(c.Error!); var v=c.Value!; var numero=await _seq.ProximoAsync(v.TenantId,v.EntidadeId,"ARR-SAN",ct); var res=await _faturas.RegistrarPagamentoDevAsync(v.TenantId,v.EntidadeId,v.ExercicioId,id,v.UsuarioId,r,numero,ct); await _audit.RegistrarAsync("saneamento","ARRECADAR_DEV","sigov.saneamento_arrecadacao",res.Id.ToString(),null,r,ct); return Result<ArrecadacaoSaneamentoResponse>.Success(res);}

    async Task<Result<PagedResult<ArrecadacaoSaneamentoResponse>>> IArrecadacaoSaneamentoService.ListarAsync(SaneamentoFiltro f,CancellationToken ct){var c=await Ctx("arrecadacao","visualizar",ct); if(c.IsFailure)return Result<PagedResult<ArrecadacaoSaneamentoResponse>>.Failure(c.Error!); var v=c.Value!; return Result<PagedResult<ArrecadacaoSaneamentoResponse>>.Success(await _arrecadacoes.ListarAsync(v.TenantId,v.EntidadeId,f with{Page=Page(f.Page),PageSize=Size(f.PageSize)},ct));}
    async Task<Result<long>> IArrecadacaoSaneamentoService.CriarAsync(ArrecadacaoSaneamentoCreateRequest r,CancellationToken ct){var c=await Ctx("arrecadacao","criar",ct); if(c.IsFailure)return Result<long>.Failure(c.Error!); var v=c.Value!; var numero=r.Numero??await _seq.ProximoAsync(v.TenantId,v.EntidadeId,"ARR-SAN",ct); return Result<long>.Success(await _arrecadacoes.CriarAsync(v.TenantId,v.EntidadeId,v.ExercicioId,v.UsuarioId,r,numero,ct));}
    async Task<Result<PagedResult<ParcelamentoSaneamentoResponse>>> IParcelamentoSaneamentoService.ListarAsync(SaneamentoFiltro f,CancellationToken ct){var c=await Ctx("parcelamento","visualizar",ct); if(c.IsFailure)return Result<PagedResult<ParcelamentoSaneamentoResponse>>.Failure(c.Error!); var v=c.Value!; return Result<PagedResult<ParcelamentoSaneamentoResponse>>.Success(await _parcelamentos.ListarAsync(v.TenantId,v.EntidadeId,f with{Page=Page(f.Page),PageSize=Size(f.PageSize)},ct));}
    async Task<Result<long>> IParcelamentoSaneamentoService.CriarAsync(ParcelamentoSaneamentoCreateRequest r,CancellationToken ct){var c=await Ctx("parcelamento","criar",ct); if(c.IsFailure)return Result<long>.Failure(c.Error!); var v=c.Value!; _=new ParcelamentoSaneamento(r.ConsumidorId,r.QuantidadeParcelas,r.ValorTotal); var numero=r.Numero??await _seq.ProximoAsync(v.TenantId,v.EntidadeId,"PARC-SAN",ct); return Result<long>.Success(await _parcelamentos.CriarAsync(v.TenantId,v.EntidadeId,v.ExercicioId,v.UsuarioId,r,numero,ct));}

    async Task<Result<PagedResult<OrdemServicoSaneamentoResponse>>> IOrdemServicoSaneamentoService.ListarAsync(OrdemServicoSaneamentoFiltro f,CancellationToken ct){var c=await Ctx("ordem_servico","visualizar",ct); if(c.IsFailure)return Result<PagedResult<OrdemServicoSaneamentoResponse>>.Failure(c.Error!); var v=c.Value!; return Result<PagedResult<OrdemServicoSaneamentoResponse>>.Success(await _ordens.ListarAsync(v.TenantId,v.EntidadeId,f with{Page=Page(f.Page),PageSize=Size(f.PageSize)},ct));}
    async Task<Result<OrdemServicoSaneamentoResponse>> IOrdemServicoSaneamentoService.ObterAsync(long id,CancellationToken ct){var c=await Ctx("ordem_servico","visualizar",ct); if(c.IsFailure)return Result<OrdemServicoSaneamentoResponse>.Failure(c.Error!); var v=c.Value!; var item=await _ordens.ObterAsync(v.TenantId,v.EntidadeId,id,ct); return item is null?Result<OrdemServicoSaneamentoResponse>.Failure("Ordem não encontrada."):Result<OrdemServicoSaneamentoResponse>.Success(item);}
    async Task<Result<long>> IOrdemServicoSaneamentoService.CriarAsync(OrdemServicoSaneamentoCreateRequest r,CancellationToken ct){var c=await Ctx("ordem_servico","criar",ct); if(c.IsFailure)return Result<long>.Failure(c.Error!); var v=c.Value!; var numero=r.Numero??await _seq.ProximoAsync(v.TenantId,v.EntidadeId,"OS-SAN",ct); _=new OrdemServicoSaneamento(v.TenantId,v.EntidadeId,numero,r.TipoServico,r.Descricao,r.Latitude,r.Longitude); return Result<long>.Success(await _ordens.CriarAsync(v.TenantId,v.EntidadeId,v.ExercicioId,v.UsuarioId,r,numero,ct));}
    async Task<Result> IOrdemServicoSaneamentoService.AtualizarAsync(long id,OrdemServicoSaneamentoUpdateRequest r,CancellationToken ct){var c=await Ctx("ordem_servico","editar",ct); if(c.IsFailure)return Result.Failure(c.Error!); var v=c.Value!; await _ordens.AtualizarAsync(v.TenantId,v.EntidadeId,id,v.UsuarioId,r,ct); return Result.Success();}
    async Task<Result> IOrdemServicoSaneamentoService.ExecutarAsync(long id,ExecutarOrdemServicoRequest r,CancellationToken ct){var c=await Ctx("ordem_servico","executar",ct); if(c.IsFailure)return Result.Failure(c.Error!); var v=c.Value!; await _ordens.ExecutarAsync(v.TenantId,v.EntidadeId,v.ExercicioId,id,v.UsuarioId,r,ct); return Result.Success();}
    async Task<Result> IOrdemServicoSaneamentoService.CancelarAsync(long id,CancelarOrdemServicoRequest r,CancellationToken ct){var c=await Ctx("ordem_servico","cancelar",ct); if(c.IsFailure)return Result.Failure(c.Error!); var v=c.Value!; await _ordens.CancelarAsync(v.TenantId,v.EntidadeId,id,v.UsuarioId,r.Motivo,ct); return Result.Success();}
    async Task<Result<PagedResult<EquipeCampoSaneamentoResponse>>> IEquipeCampoSaneamentoService.ListarAsync(SaneamentoFiltro f,CancellationToken ct){var c=await Ctx("ordem_servico","visualizar",ct); if(c.IsFailure)return Result<PagedResult<EquipeCampoSaneamentoResponse>>.Failure(c.Error!); var v=c.Value!; return Result<PagedResult<EquipeCampoSaneamentoResponse>>.Success(await _equipes.ListarAsync(v.TenantId,v.EntidadeId,f with{Page=Page(f.Page),PageSize=Size(f.PageSize)},ct));}
    async Task<Result<long>> IEquipeCampoSaneamentoService.CriarAsync(EquipeCampoSaneamentoCreateRequest r,CancellationToken ct){var c=await Ctx("ordem_servico","criar",ct); if(c.IsFailure)return Result<long>.Failure(c.Error!); var v=c.Value!; var codigo=r.Codigo??await _seq.ProximoAsync(v.TenantId,v.EntidadeId,"EQ-SAN",ct); return Result<long>.Success(await _equipes.CriarAsync(v.TenantId,v.EntidadeId,v.UsuarioId,r,codigo,ct));}
    async Task<Result<PagedResult<LaboratorioAmostraResponse>>> ILaboratorioSaneamentoService.ListarAsync(SaneamentoFiltro f,CancellationToken ct){var c=await Ctx("laboratorio","visualizar",ct); if(c.IsFailure)return Result<PagedResult<LaboratorioAmostraResponse>>.Failure(c.Error!); var v=c.Value!; return Result<PagedResult<LaboratorioAmostraResponse>>.Success(await _laboratorio.ListarAsync(v.TenantId,v.EntidadeId,f with{Page=Page(f.Page),PageSize=Size(f.PageSize)},ct));}
    async Task<Result<long>> ILaboratorioSaneamentoService.CriarAmostraAsync(LaboratorioAmostraCreateRequest r,CancellationToken ct){var c=await Ctx("laboratorio","criar",ct); if(c.IsFailure)return Result<long>.Failure(c.Error!); var v=c.Value!; var numero=r.Numero??await _seq.ProximoAsync(v.TenantId,v.EntidadeId,"AMO",ct); _=new LaboratorioAmostra(numero,r.PontoColeta,r.DataColeta,r.Latitude,r.Longitude); return Result<long>.Success(await _laboratorio.CriarAmostraAsync(v.TenantId,v.EntidadeId,v.ExercicioId,v.UsuarioId,r,numero,ct));}
    async Task<Result<long>> ILaboratorioSaneamentoService.CriarResultadoAsync(long amostraId,LaboratorioResultadoCreateRequest r,CancellationToken ct){var c=await Ctx("laboratorio","resultado",ct); if(c.IsFailure)return Result<long>.Failure(c.Error!); var v=c.Value!; _=new LaboratorioResultado(amostraId,r.Parametro,r.Valor); return Result<long>.Success(await _laboratorio.CriarResultadoAsync(v.TenantId,v.EntidadeId,amostraId,v.UsuarioId,r,ct));}
    async Task<Result<PagedResult<RedeSaneamentoTrechoResponse>>> IRedeSaneamentoService.ListarAsync(SaneamentoFiltro f,CancellationToken ct){var c=await Ctx("rede","visualizar",ct); if(c.IsFailure)return Result<PagedResult<RedeSaneamentoTrechoResponse>>.Failure(c.Error!); var v=c.Value!; return Result<PagedResult<RedeSaneamentoTrechoResponse>>.Success(await _rede.ListarAsync(v.TenantId,v.EntidadeId,f with{Page=Page(f.Page),PageSize=Size(f.PageSize)},ct));}
    async Task<Result<long>> IRedeSaneamentoService.CriarAsync(RedeSaneamentoTrechoCreateRequest r,CancellationToken ct){var c=await Ctx("rede","criar",ct); if(c.IsFailure)return Result<long>.Failure(c.Error!); var v=c.Value!; var codigo=r.Codigo??await _seq.ProximoAsync(v.TenantId,v.EntidadeId,"RED",ct); return Result<long>.Success(await _rede.CriarAsync(v.TenantId,v.EntidadeId,v.UsuarioId,r,codigo,ct));}
    async Task<Result<SaneamentoDashboardResponse>> ISaneamentoDashboardService.ObterAsync(CancellationToken ct){var c=await Ctx("dashboard","visualizar",ct); if(c.IsFailure)return Result<SaneamentoDashboardResponse>.Failure(c.Error!); var v=c.Value!; return Result<SaneamentoDashboardResponse>.Success(await _dashboard.ObterAsync(v.TenantId,v.EntidadeId,ct));}
    async Task<Result<byte[]>> ISaneamentoExportacaoService.ExportarAsync(string recurso,string formato,CancellationToken ct){var c=await Ctx("exportar","executar",ct); if(c.IsFailure)return Result<byte[]>.Failure(c.Error!); var v=c.Value!; await _audit.RegistrarAsync("saneamento","EXPORTAR","sigov.saneamento_export",recurso,null,new{recurso,formato},ct); return Result<byte[]>.Success(await _exportacao.ExportarAsync(v.TenantId,v.EntidadeId,recurso,formato,ct));}
}
