using System.Globalization;
using System.Text;
using Dapper;
using Sigov.Application.Royalties;
using Sigov.Infrastructure.Persistence.Dapper;

namespace Sigov.Infrastructure.Royalties;
public sealed class RoyaltiesRepository(DapperContext db):IRoyaltiesRepository
{
 private static readonly IReadOnlyDictionary<string,string> Tables=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase){["parametros"]="royalties_parametro_normativo",["fontesdados"]="royalties_fonte_dado",["areas"]="royalties_area_exploracao",["campos"]="royalties_campo_origem",["origemreceita"]="royalties_campo_origem",["previsoes"]="royalties_receita_previsao",["cenarios"]="royalties_receita_previsao",["repasses"]="royalties_repasse",["conciliacao"]="royalties_conciliacao",["planosaplicacao"]="royalties_plano_aplicacao",["projetos"]="royalties_projeto",["acompanhamento"]="royalties_projeto_acompanhamento",["execucaofinanceira"]="royalties_execucao_financeira_vinculo",["saldos"]="royalties_execucao_financeira_vinculo",["transparencia"]="royalties_transparencia_publicacao",["alertas"]="royalties_alerta",["governanca"]="royalties_auditoria_operacional"};
 public async Task<RoyaltiesDashboard> DashboardAsync(RoyaltiesContexto c,RoyaltiesFiltro f,CancellationToken ct){using var cn=db.CreateConnection();const string sql="""select coalesce((select sum(valor) from sigov.royalties_receita_previsao where tenant_id=@TenantId and entidade_id=@EntidadeId),0) prevista,coalesce((select sum(valor) from sigov.royalties_receita_realizada where tenant_id=@TenantId and entidade_id=@EntidadeId),0) realizada,coalesce((select sum(valor_liquido) from sigov.royalties_repasse where tenant_id=@TenantId and entidade_id=@EntidadeId and status<>'CANCELADO'),0) repasses,coalesce((select sum(valor) from sigov.royalties_plano_aplicacao where tenant_id=@TenantId and entidade_id=@EntidadeId and status in('APROVADO','EM_EXECUCAO','CONCLUIDO')),0) aplicacoes,(select count(*) from sigov.royalties_repasse where tenant_id=@TenantId and entidade_id=@EntidadeId and status in('LANCADO','DIVERGENTE')) repasses_pendentes,(select count(*) from sigov.royalties_projeto where tenant_id=@TenantId and entidade_id=@EntidadeId) projetos,(select count(*) from sigov.royalties_projeto where tenant_id=@TenantId and entidade_id=@EntidadeId and data_fim_prevista<current_date and status not in('CONCLUIDO','CANCELADO')) projetos_atrasados,(select count(*) from sigov.royalties_projeto where tenant_id=@TenantId and entidade_id=@EntidadeId and contrato_id is not null) obras,(select count(*) from sigov.royalties_projeto where tenant_id=@TenantId and entidade_id=@EntidadeId and upper(coalesce(descricao,'')) ~ 'ENERGIA|CARBONO|SUSTENT') sustentabilidade,(select count(*) from sigov.royalties_alerta where tenant_id=@TenantId and entidade_id=@EntidadeId and status='ABERTO') alertas""";var x=await cn.QuerySingleAsync(sql,c);var recentes=await ListarAsync(c,"repasses",f,ct);decimal prevista=x.prevista,realizada=x.realizada,repasses=x.repasses,aplicacoes=x.aplicacoes;return new(prevista,realizada,repasses,aplicacoes,realizada-aplicacoes,(long)x.repasses_pendentes,(long)x.projetos,(long)x.projetos_atrasados,(long)x.obras,(long)x.sustentabilidade,(long)x.alertas,recentes.Take(5).ToList());}
 public async Task<IReadOnlyList<RoyaltiesRegistro>> ListarAsync(RoyaltiesContexto c,string recurso,RoyaltiesFiltro f,CancellationToken ct){using var cn=db.CreateConnection();var publicacao=recurso.Equals("transparencia",StringComparison.OrdinalIgnoreCase)?" and publicavel and visibilidade='PUBLICA'":"";var sql=$"select id,codigo,nome,status,tipo_receita TipoReceita,valor,competencia,data_referencia DataReferencia,fonte_recurso_id FonteRecursoId,descricao from sigov.{Table(recurso)} where tenant_id=@TenantId and entidade_id=@EntidadeId and (@Busca is null or codigo ilike '%'||@Busca||'%' or nome ilike '%'||@Busca||'%') and (@Status is null or status=@Status) and (@TipoReceita is null or tipo_receita=@TipoReceita) and (@Inicio is null or data_referencia>=@Inicio) and (@Fim is null or data_referencia<=@Fim){publicacao} order by id desc limit 300";return (await cn.QueryAsync<RoyaltiesRegistro>(new CommandDefinition(sql,new{c.TenantId,c.EntidadeId,f.Busca,f.Status,f.TipoReceita,f.Inicio,f.Fim},cancellationToken:ct))).AsList();}
 public async Task<RoyaltiesRegistro?> ObterAsync(RoyaltiesContexto c,string recurso,long id,CancellationToken ct){using var cn=db.CreateConnection();return await cn.QuerySingleOrDefaultAsync<RoyaltiesRegistro>(new CommandDefinition($"select id,codigo,nome,status,tipo_receita TipoReceita,valor,competencia,data_referencia DataReferencia,fonte_recurso_id FonteRecursoId,descricao from sigov.{Table(recurso)} where id=@id and tenant_id=@TenantId and entidade_id=@EntidadeId",new{id,c.TenantId,c.EntidadeId},cancellationToken:ct));}
 public async Task<long> SalvarAsync(RoyaltiesContexto c,string recurso,RoyaltiesRequest r,long? id,CancellationToken ct){Validar(recurso,r,id);using var cn=db.CreateConnection();var p=new DynamicParameters(r);p.Add("Id",id);p.Add("TenantId",c.TenantId);p.Add("EntidadeId",c.EntidadeId);p.Add("UsuarioId",c.UsuarioId);var cols="codigo,nome,descricao,status,tipo_receita,valor,valor_bruto,deducoes,valor_liquido,percentual,competencia,data_referencia,vigencia_inicio,vigencia_fim,data_fim_prevista,exercicio_id,fonte_recurso_id,parametro_id,projeto_id,unidade_id,pessoa_juridica_id,programa_id,acao_id,contrato_id,cenario,fonte_normativa,formula_textual,premissas,justificativa,visibilidade,publicavel";var vals="@Codigo,@Nome,@Descricao,@Status,@TipoReceita,@Valor,@ValorBruto,@Deducoes,@ValorLiquido,@Percentual,@Competencia,@DataReferencia,@VigenciaInicio,@VigenciaFim,@DataFimPrevista,@ExercicioId,@FonteRecursoId,@ParametroId,@ProjetoId,@UnidadeId,@PessoaJuridicaId,@ProgramaId,@AcaoId,@ContratoId,@Cenario,@FonteNormativa,@FormulaTextual,@Premissas,@Justificativa,@Visibilidade,@Publicavel";string sql;if(id is null)sql=$"insert into sigov.{Table(recurso)}({cols},tenant_id,entidade_id,created_by) values({vals},@TenantId,@EntidadeId,@UsuarioId) returning id";else{if(recurso=="parametros"&&await cn.ExecuteScalarAsync<bool>(new CommandDefinition("select exists(select 1 from sigov.royalties_parametro_normativo where id=@Id and tenant_id=@TenantId and entidade_id=@EntidadeId and status='VIGENTE')",p,cancellationToken:ct)))throw new InvalidOperationException("Regra vigente não pode ser editada; crie uma nova versão.");sql=$"update sigov.{Table(recurso)} set (codigo,nome,descricao,status,tipo_receita,valor,valor_bruto,deducoes,valor_liquido,percentual,competencia,data_referencia,vigencia_inicio,vigencia_fim,data_fim_prevista,exercicio_id,fonte_recurso_id,parametro_id,projeto_id,unidade_id,pessoa_juridica_id,programa_id,acao_id,contrato_id,cenario,fonte_normativa,formula_textual,premissas,justificativa,visibilidade,publicavel)=({vals}),updated_at=now(),updated_by=@UsuarioId where id=@Id and tenant_id=@TenantId and entidade_id=@EntidadeId returning id";}return await cn.ExecuteScalarAsync<long?>(new CommandDefinition(sql,p,cancellationToken:ct))??throw new KeyNotFoundException("Registro não encontrado no contexto atual.");}
 public async Task<IReadOnlyList<RoyaltiesOpcao>> OpcoesAsync(RoyaltiesContexto c,string tipo,CancellationToken ct){using var cn=db.CreateConnection();var sql=tipo switch{"exercicio"=>"select id,ano::text texto from sigov.exercicio where entidade_id=@EntidadeId and ativo and not is_deleted order by ano desc","fonte"=>"select id,coalesce(codigo,'')||' — '||coalesce(descricao,nome,'') texto from sigov.fonte_recurso where tenant_id=@TenantId and entidade_id=@EntidadeId order by 2","unidade"=>"select id,nome texto from sigov.unidade_organizacional where tenant_id=@TenantId and entidade_id=@EntidadeId order by nome","pessoa"=>"select pj.id,pj.razao_social texto from sigov.pessoa_juridica pj join sigov.pessoa p on p.id=pj.pessoa_id where p.tenant_id=@TenantId and p.entidade_id=@EntidadeId order by 2","projeto"=>"select id,codigo||' — '||nome texto from sigov.royalties_projeto where tenant_id=@TenantId and entidade_id=@EntidadeId order by nome","parametro"=>"select id,codigo||' — '||nome texto from sigov.royalties_parametro_normativo where tenant_id=@TenantId and entidade_id=@EntidadeId and status='VIGENTE' order by nome","contrato"=>"select id,numero||' — '||objeto texto from sigov.contrato where tenant_id=@TenantId and entidade_id=@EntidadeId order by id desc",_=>throw new ArgumentException("Catálogo inválido.")};return (await cn.QueryAsync<RoyaltiesOpcao>(new CommandDefinition(sql,c,cancellationToken:ct))).AsList();}
 public async Task<byte[]> ExportarCsvAsync(RoyaltiesContexto c,string recurso,RoyaltiesFiltro f,CancellationToken ct){var rows=await ListarAsync(c,recurso,f,ct);var b=new StringBuilder("codigo;nome;status;tipo;valor;competencia\r\n");foreach(var x in rows)b.AppendLine($"{Csv(x.Codigo)};{Csv(x.Nome)};{Csv(x.Status)};{Csv(x.TipoReceita??"")};{x.Valor.ToString(CultureInfo.InvariantCulture)};{x.Competencia:yyyy-MM-dd}");return new UTF8Encoding(true).GetBytes(b.ToString());}
 private static string Table(string r)=>Tables.TryGetValue(r,out var t)?t:throw new ArgumentException("Recurso Royalties360 inválido.");
 private static void Validar(string recurso,RoyaltiesRequest r,long? id){if(r.Valor<0||r.ValorBruto<0||r.Deducoes<0||r.ValorLiquido<0)throw new ArgumentException("Valores não podem ser negativos.");if(r.ValorLiquido>r.ValorBruto&&string.IsNullOrWhiteSpace(r.Justificativa))throw new ArgumentException("Valor líquido superior ao bruto exige justificativa.");if(r.VigenciaFim<r.VigenciaInicio)throw new ArgumentException("A vigência final deve ser posterior à inicial.");if(recurso=="parametros"&&(string.IsNullOrWhiteSpace(r.FonteNormativa)||r.VigenciaInicio is null))throw new ArgumentException("Fonte normativa e vigência são obrigatórias.");if((r.Status is "REVOGADO" or "CANCELADO" or "DESCARTADO")&&string.IsNullOrWhiteSpace(r.Justificativa))throw new ArgumentException("Revogação, cancelamento ou descarte exige justificativa.");if(recurso=="previsoes"&&(r.ExercicioId is null||r.Competencia is null))throw new ArgumentException("Exercício e competência são obrigatórios.");}
 private static string Csv(string s){if(s.Length>0&&"=+-@\t\r".Contains(s[0]))s="'"+s;return '"'+s.Replace("\"","\"\"")+'"';}
}
