using System.Text;
using Dapper;
using Sigov.Application.Fiscalizacao;
using Sigov.Infrastructure.Persistence.Dapper;

namespace Sigov.Infrastructure.Fiscalizacao;

public sealed class FiscalizacaoRepository(DapperContext db):IFiscalizacaoRepository
{
 public async Task<FiscalizacaoDashboard> DashboardAsync(FiscalizacaoContexto c,FiscalizacaoFiltro f,CancellationToken ct){using var cn=db.CreateConnection();const string q= """
select
 (select count(*) from sigov.fiscalizacao_ordem where tenant_id=@TenantId and entidade_id=@EntidadeId and exercicio_id=@ExercicioId and status in('ABERTA','AGENDADA','EM_VISTORIA')) OrdensAbertas,
 (select count(*) from sigov.fiscalizacao_vistoria where tenant_id=@TenantId and entidade_id=@EntidadeId and exercicio_id=@ExercicioId and status='AGENDADA') VistoriasAgendadas,
 (select count(*) from sigov.fiscalizacao_vistoria where tenant_id=@TenantId and entidade_id=@EntidadeId and exercicio_id=@ExercicioId and status='CONCLUIDA') VistoriasConcluidas,
 (select count(*) from sigov.fiscalizacao_auto_notificacao where tenant_id=@TenantId and entidade_id=@EntidadeId and exercicio_id=@ExercicioId and status='EMITIDO') AutosEmitidos,
 (select count(*) from sigov.fiscalizacao_sincronizacao_item where tenant_id=@TenantId and entidade_id=@EntidadeId and status in('PENDENTE','FALHA')) SincronizacoesPendentes,
 (select count(*) from sigov.evidencia_transversal where tenant_id=@TenantId and entidade_id=@EntidadeId and origem='FISCALIZA360' and not is_deleted) Evidencias
""";return await cn.QuerySingleAsync<FiscalizacaoDashboard>(new CommandDefinition(q,c,cancellationToken:ct));}
 public async Task<IReadOnlyList<FiscalizacaoLinha>> ListarAsync(FiscalizacaoContexto c,string recurso,FiscalizacaoFiltro f,CancellationToken ct){var spec=Spec(recurso);using var cn=db.CreateConnection();var sql=$"select id,{spec.Code} Codigo,{spec.Desc} Descricao,{spec.Status} Status,{spec.Date} Data from sigov.{spec.Table} where tenant_id=@TenantId and entidade_id=@EntidadeId and (@Modulo is null or {spec.Module}=@Modulo) and (@Status is null or {spec.Status}=@Status) and (@Inicio is null or {spec.Date}::date>=@Inicio) and (@Fim is null or {spec.Date}::date<=@Fim) and (@Busca is null or cast({spec.Desc} as text) ilike '%'||@Busca||'%') order by {spec.Date} desc limit 1000";return(await cn.QueryAsync<FiscalizacaoLinha>(new CommandDefinition(sql,new{c.TenantId,c.EntidadeId,f.Modulo,f.Status,f.Inicio,f.Fim,f.Busca},cancellationToken:ct))).AsList();}
 public async Task<OrdemFiscalizacaoRequest?> ObterOrdemAsync(FiscalizacaoContexto c,long id,CancellationToken ct){using var cn=db.CreateConnection();return await cn.QuerySingleOrDefaultAsync<OrdemFiscalizacaoRequest>(new CommandDefinition("select origem_modulo OrigemModulo,tipo,prioridade,status,registro_fiscalizado_id RegistroFiscalizadoId,registro_fiscalizado_tipo RegistroFiscalizadoTipo,registro_fiscalizado_rotulo RegistroFiscalizadoRotulo,equipe_id EquipeId,responsavel_usuario_id ResponsavelUsuarioId,agendada_em AgendadaEm,motivo,observacoes from sigov.fiscalizacao_ordem where id=@id and tenant_id=@TenantId and entidade_id=@EntidadeId and exercicio_id=@ExercicioId",new{id,c.TenantId,c.EntidadeId,c.ExercicioId},cancellationToken:ct));}
 public async Task<IReadOnlyList<FiscalizacaoOpcao>> OpcoesAsync(FiscalizacaoContexto c,string tipo,string? origem,CancellationToken ct){using var cn=db.CreateConnection();var q=tipo switch{"Equipe"=>"select id,nome Rotulo from sigov.fiscalizacao_equipe where tenant_id=@TenantId and entidade_id=@EntidadeId and exercicio_id=@ExercicioId and status='ATIVA' and not is_deleted order by nome","Registro"=>origem switch{"OBRAS"=>"select id,codigo||' — '||nome Rotulo from sigov.obras_obra where tenant_id=@TenantId and entidade_id=@EntidadeId and deleted_at is null order by 2","MEIO_AMBIENTE"=>"select id,coalesce(codigo,id::text)||' — '||nome Rotulo from sigov.ambiental_empreendimento where tenant_id=@TenantId and entidade_id=@EntidadeId and deleted_at is null order by 2","TRANSITO"=>"select id,tipo||' — '||local Rotulo from sigov.transito_ocorrencia where tenant_id=@TenantId and entity_id=@EntidadeId and deleted_at is null order by 2","DEFESA_CIVIL"=>"select id,numero_ocorrencia||' — '||endereco Rotulo from sigov.defesa_ocorrencia where tenant_id=@TenantId and entity_id=@EntidadeId and deleted_at is null order by 2",_=>throw new ArgumentException("Origem inválida.")},_=>throw new ArgumentException("Opção inválida.")};return(await cn.QueryAsync<FiscalizacaoOpcao>(new CommandDefinition(q,c,cancellationToken:ct))).AsList();}
 public async Task<long> SalvarOrdemAsync(FiscalizacaoContexto c,OrdemFiscalizacaoRequest r,long? id,CancellationToken ct){if(!new[]{"OBRAS","MEIO_AMBIENTE","TRANSITO","DEFESA_CIVIL"}.Contains(r.OrigemModulo)||!new[]{"BAIXA","NORMAL","ALTA","URGENTE"}.Contains(r.Prioridade))throw new ArgumentException("Origem ou prioridade inválida.");var options=await OpcoesAsync(c,"Registro",r.OrigemModulo,ct);var selected=options.SingleOrDefault(x=>x.Id==r.RegistroFiscalizadoId)??throw new ArgumentException("Registro fiscalizado inválido ou fora do contexto.");var teams=await OpcoesAsync(c,"Equipe",null,ct);if(!teams.Any(x=>x.Id==r.EquipeId))throw new ArgumentException("Equipe inválida ou fora do contexto.");using var cn=db.CreateConnection();cn.Open();using var tx=cn.BeginTransaction();var p=new{c.TenantId,c.EntidadeId,c.ExercicioId,c.UsuarioId,id,r.OrigemModulo,r.Tipo,r.Prioridade,r.Status,RegistroFiscalizadoId=selected.Id,r.RegistroFiscalizadoTipo,RegistroFiscalizadoRotulo=selected.Rotulo,r.EquipeId,r.ResponsavelUsuarioId,r.AgendadaEm,r.Motivo,r.Observacoes};var sql=id.HasValue?"update sigov.fiscalizacao_ordem set origem_modulo=@OrigemModulo,tipo=@Tipo,prioridade=@Prioridade,equipe_id=@EquipeId,responsavel_usuario_id=@ResponsavelUsuarioId,registro_fiscalizado_tipo=@RegistroFiscalizadoTipo,registro_fiscalizado_id=@RegistroFiscalizadoId,registro_fiscalizado_rotulo=@RegistroFiscalizadoRotulo,agendada_em=@AgendadaEm,motivo=@Motivo,observacoes=@Observacoes,atualizado_por=@UsuarioId,updated_at=now() where id=@id and tenant_id=@TenantId and entidade_id=@EntidadeId and exercicio_id=@ExercicioId and status in('ABERTA','AGENDADA') returning id":"insert into sigov.fiscalizacao_ordem(tenant_id,entidade_id,exercicio_id,origem_modulo,tipo,prioridade,status,equipe_id,responsavel_usuario_id,registro_fiscalizado_tipo,registro_fiscalizado_id,registro_fiscalizado_rotulo,agendada_em,motivo,observacoes,criado_por) values(@TenantId,@EntidadeId,@ExercicioId,@OrigemModulo,@Tipo,@Prioridade,case when @AgendadaEm is null then 'ABERTA' else 'AGENDADA' end,@EquipeId,@ResponsavelUsuarioId,@RegistroFiscalizadoTipo,@RegistroFiscalizadoId,@RegistroFiscalizadoRotulo,@AgendadaEm,@Motivo,@Observacoes,@UsuarioId) returning id";var saved=await cn.ExecuteScalarAsync<long?>(new CommandDefinition(sql,p,tx,cancellationToken:ct))??throw new ArgumentException("Ordem não encontrada ou não editável.");await Audit(c,cn,tx,saved,id.HasValue?"EDITAR":"CRIAR",p,ct);tx.Commit();return saved;}
 public async Task TransicionarOrdemAsync(FiscalizacaoContexto c,long id,string destino,string? justificativa,CancellationToken ct){var allowed=destino switch{"CANCELADA"=>new[]{"ABERTA","AGENDADA"},"CONCLUIDA"=>new[]{"EM_VISTORIA"},_=>[]};if(allowed.Length==0)throw new ArgumentException("Transição inválida.");using var cn=db.CreateConnection();cn.Open();using var tx=cn.BeginTransaction();var n=await cn.ExecuteAsync(new CommandDefinition("update sigov.fiscalizacao_ordem set status=@destino,cancelada_em=case when @destino='CANCELADA' then now() end,concluida_em=case when @destino='CONCLUIDA' then now() end,observacoes=concat_ws(E'\\n',observacoes,@justificativa),atualizado_por=@UsuarioId,updated_at=now() where id=@id and tenant_id=@TenantId and entidade_id=@EntidadeId and exercicio_id=@ExercicioId and status=any(@allowed)",new{id,destino,justificativa,allowed,c.TenantId,c.EntidadeId,c.ExercicioId,c.UsuarioId},tx,cancellationToken:ct));if(n!=1)throw new ArgumentException("A transição não é permitida no estado atual.");await Audit(c,cn,tx,id,destino,new{justificativa},ct);tx.Commit();}
 public async Task<byte[]> CsvAsync(FiscalizacaoContexto c,string recurso,FiscalizacaoFiltro f,CancellationToken ct){var rows=await ListarAsync(c,recurso,f,ct);var b=new StringBuilder("Código;Descrição;Status;Data\r\n");foreach(var x in rows)b.AppendLine($"{Csv(x.Codigo)};{Csv(x.Descricao)};{Csv(x.Status)};{x.Data:O}");return new UTF8Encoding(true).GetBytes(b.ToString());}
 private static (string Table,string Code,string Desc,string Status,string Date,string Module) Spec(string r)=>r switch{"Ordens"=>("fiscalizacao_ordem","id::text","registro_fiscalizado_rotulo","status","aberta_em","origem_modulo"),"Vistorias"=>("fiscalizacao_vistoria","id::text","local_descricao","status","agendada_em","(select origem_modulo from sigov.fiscalizacao_ordem o where o.id=ordem_id)"),"Autos"=>("fiscalizacao_auto_notificacao","id::text","descricao","status","emitido_em","(select origem_modulo from sigov.fiscalizacao_ordem o where o.id=ordem_id)"),"Evidencias"=>("evidencia_transversal","id::text","descricao","tipo","registrada_at","origem"),"Sincronizacao"=>("fiscalizacao_sincronizacao_item","id::text","coalesce(erro_sanitizado,chave_idempotencia)","status","created_at","'FISCALIZA360'"),"Auditoria"=>("fiscalizacao_auditoria","id::text","acao||' — '||tabela","acao","created_at","'FISCALIZA360'"),_=>throw new ArgumentException("Relatório inválido.")};
 private static async Task Audit(FiscalizacaoContexto c,System.Data.IDbConnection cn,System.Data.IDbTransaction tx,long id,string action,object data,CancellationToken ct)=>await cn.ExecuteAsync(new CommandDefinition("insert into sigov.fiscalizacao_auditoria(tenant_id,entidade_id,exercicio_id,tabela,registro_id,acao,usuario_id,dados_novos) values(@TenantId,@EntidadeId,@ExercicioId,'fiscalizacao_ordem',@id,@action,@UsuarioId,cast(@json as jsonb))",new{c.TenantId,c.EntidadeId,c.ExercicioId,c.UsuarioId,id,action,json=System.Text.Json.JsonSerializer.Serialize(data)},tx,cancellationToken:ct));
 private static string Csv(string? v){v??="";if(v.Length>0&&"=+-@\t\r".Contains(v[0]))v="'"+v;return '"'+v.Replace("\"","\"\"")+'"';}
}
