<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>Sigov.Web</AssemblyName>
    <RootNamespace>Sigov.Web</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Sigov.Application\Sigov.Application.csproj" />
    <ProjectReference Include="..\Sigov.Infrastructure\Sigov.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Settings.Configuration" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.File" />
  </ItemGroup>
</Project>
