using System.Globalization;
using System.Text;
using System.Text.Json;
using Dapper;
using Sigov.Application.Atendimento;
using Sigov.Infrastructure.Persistence.Dapper;
namespace Sigov.Infrastructure.Atendimento;

public sealed class AtendimentoRepository(DapperContext db) : IAtendimentoRepository
{
    private static readonly IReadOnlyDictionary<string,string> Tables = new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase) {
        ["cidadaos"]="atendimento_cidadao",["carta-servicos"]="atendimento_servico",["demandas"]="atendimento_demanda",["ouvidoria"]="atendimento_ouvidoria_manifestacao",["esic"]="atendimento_esic_pedido",["encaminhamentos"]="atendimento_encaminhamento",["agendas"]="atendimento_agenda",["agendamentos"]="atendimento_agendamento",["sla"]="atendimento_sla_parametro",["satisfacao"]="atendimento_satisfacao",["base-conhecimento"]="atendimento_base_conhecimento",["auditoria"]="atendimento_auditoria" };
    public async Task<AtendimentoDashboard> DashboardAsync(AtendimentoContexto c, AtendimentoFiltro f, CancellationToken ct) { using var cn=db.CreateConnection(); const string sql="""select
+ (select count(*) from sigov.atendimento_demanda where tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted and status not in('CONCLUIDO','CANCELADO','ARQUIVADO')) DemandasAbertas,
+ (select count(*) from sigov.atendimento_demanda where tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted and prazo<now() and status not in('CONCLUIDO','CANCELADO','ARQUIVADO')) DemandasAtrasadas,
+ (select count(*) from sigov.atendimento_ouvidoria_manifestacao where tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted and status not in('ENCERRADO','ARQUIVADO')) OuvidoriaPendentes,
+ (select count(*) from sigov.atendimento_esic_pedido where tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted and status not in('RESPONDIDO','NEGADO','CANCELADO')) EsicPendentes,
+ (select count(*) from sigov.atendimento_agendamento where tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted and inicio::date=current_date) AgendamentosHoje,
+ (select count(*) from sigov.atendimento_encaminhamento where tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted and status='PENDENTE') EncaminhamentosPendentes,
+ (select avg(nota) from sigov.atendimento_satisfacao where tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted) SatisfacaoMedia""".Replace("+ ",""); var d=await cn.QuerySingleAsync<AtendimentoDashboard>(new CommandDefinition(sql,c,cancellationToken:ct)); const string top="""select s.id,coalesce(s.codigo,'') codigo,s.nome descricao,s.status,s.created_at CriadoEm from sigov.atendimento_servico s join sigov.atendimento_demanda d on d.servico_id=s.id and d.tenant_id=s.tenant_id and d.entidade_id=s.entidade_id and not d.is_deleted where s.tenant_id=@TenantId and s.entidade_id=@EntidadeId and not s.is_deleted group by s.id order by count(d.id) desc limit 5"""; var rows=(await cn.QueryAsync<AtendimentoRegistro>(new CommandDefinition(top,c,cancellationToken:ct))).AsList(); return d with { ServicosMaisSolicitados=rows }; }
    public async Task<AtendimentoPagina> ListarAsync(AtendimentoContexto c,string recurso,AtendimentoFiltro f,bool podeVerSigilo,CancellationToken ct) { var t=Table(recurso); using var cn=db.CreateConnection(); var page=Math.Max(1,f.Pagina);var size=Math.Clamp(f.Tamanho,1,100); var where="tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted and ativo and (@Busca is null or coalesce(codigo,'') ilike '%'||@Busca||'%' or descricao ilike '%'||@Busca||'%') and (@Status is null or status=@Status)";var a=new{c.TenantId,c.EntidadeId,f.Busca,f.Status,Limit=size,Offset=(page-1)*size};var total=await cn.ExecuteScalarAsync<long>(new CommandDefinition($"select count(*) from sigov.{t} where {where}",a,cancellationToken:ct));var description=recurso=="ouvidoria"&&!podeVerSigilo?"case when sigilosa then '[CONTEÚDO SIGILOSO]' else descricao end":"descricao";var rows=(await cn.QueryAsync<AtendimentoRegistro>(new CommandDefinition($"select id,coalesce(codigo,'') Codigo,{description} Descricao,status,created_at CriadoEm from sigov.{t} where {where} order by updated_at desc limit @Limit offset @Offset",a,cancellationToken:ct))).AsList();return new(rows,page,size,total); }
    public async Task<long> SalvarAsync(AtendimentoContexto c,string recurso,AtendimentoRegistroRequest r,long? id,CancellationToken ct) { r=r with { DadosJson=string.IsNullOrWhiteSpace(r.DadosJson)?"{}":r.DadosJson };Validate(r);var t=Table(recurso);using var cn=db.CreateConnection();cn.Open();using var tx=cn.BeginTransaction();var p=new DynamicParameters(r);p.Add("TenantId",c.TenantId);p.Add("EntidadeId",c.EntidadeId);p.Add("UsuarioId",c.UsuarioId);p.Add("Id",id);var sql=id is null?$"insert into sigov.{t}(codigo,descricao,status,dados,tenant_id,entidade_id,created_by{ExtraColumns(recurso)}) values(@Codigo,@Descricao,@Status,cast(@DadosJson as jsonb),@TenantId,@EntidadeId,@UsuarioId{ExtraValues(recurso)}) returning id":$"update sigov.{t} set codigo=@Codigo,descricao=@Descricao,status=@Status,dados=cast(@DadosJson as jsonb),updated_at=now(),updated_by=@UsuarioId where id=@Id and tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted returning id";var saved=await cn.ExecuteScalarAsync<long?>(new CommandDefinition(sql,p,tx,cancellationToken:ct))??throw new KeyNotFoundException("Registro não encontrado no contexto atual.");await Audit(c,cn,id is null?"CRIAR":"ALTERAR",recurso,saved,JsonSerializer.Serialize(new{r.Codigo,r.Status}),tx,ct);tx.Commit();return saved; }
    public async Task ExcluirAsync(AtendimentoContexto c,string recurso,long id,string justificativa,CancellationToken ct) { if(string.IsNullOrWhiteSpace(justificativa))throw new ArgumentException("Justificativa obrigatória.");using var cn=db.CreateConnection();cn.Open();using var tx=cn.BeginTransaction();var n=await cn.ExecuteAsync(new CommandDefinition($"update sigov.{Table(recurso)} set ativo=false,is_deleted=true,deleted_at=now(),deleted_by=@UsuarioId,updated_at=now() where id=@id and tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted",new{id,c.UsuarioId,c.TenantId,c.EntidadeId},tx,cancellationToken:ct));if(n==0)throw new KeyNotFoundException("Registro não encontrado.");await Audit(c,cn,"EXCLUIR",recurso,id,JsonSerializer.Serialize(new{justificativa}),tx,ct);tx.Commit(); }
    public async Task<byte[]> ExportarCsvAsync(AtendimentoContexto c,string relatorio,AtendimentoFiltro f,CancellationToken ct) { using var cn=db.CreateConnection();var rows=await cn.QueryAsync<dynamic>(new CommandDefinition($"select id,coalesce(codigo,'') codigo,descricao,status,created_at from sigov.{Table(relatorio)} where tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted order by id",c,cancellationToken:ct));var b=new StringBuilder("id;codigo;descricao;status;criado_em\r\n");foreach(var x in rows)b.AppendLine($"{x.id};{Csv(x.codigo)};{Csv(x.descricao)};{Csv(x.status)};{x.created_at:O}");await Audit(c,cn,"EXPORTAR",relatorio,null,null,null,ct);return new UTF8Encoding(true).GetBytes(b.ToString()); }
    private static string Table(string r)=>Tables.TryGetValue(r,out var t)?t:throw new ArgumentException("Recurso inválido.");
    private static void Validate(AtendimentoRegistroRequest r){if(string.IsNullOrWhiteSpace(r.Descricao))throw new ArgumentException("Descrição é obrigatória.");if((r.Status is "CONCLUIDO" or "CANCELADO" or "ARQUIVADO" or "NEGADO" or "PRORROGADO" or "ENCERRADO") && string.IsNullOrWhiteSpace(r.Justificativa))throw new ArgumentException("Este estado exige justificativa.");try{JsonDocument.Parse(r.DadosJson);}catch(JsonException){throw new ArgumentException("Dados complementares devem ser JSON válido.");}}
    private static string ExtraColumns(string r)=>r switch{"cidadaos"=>",nome,consentimento_lgpd,consentimento_em","carta-servicos"=>",nome,setor_responsavel","demandas"=>",assunto,justificativa","ouvidoria"=>",tipo,anonima,sigilosa","esic"=>",setor_destino,prazo,justificativa","encaminhamentos"=>",origem,destino","agendas"=>",setor,inicio_vigencia,slot_minutos","sla"=>",tipo,prazo_dias","base-conhecimento"=>",pergunta,resposta",_=>""};
    private static string ExtraValues(string r)=>r switch{"cidadaos"=>",@Descricao,coalesce((cast(@DadosJson as jsonb)->>'consentimento_lgpd')::boolean,false),case when coalesce((cast(@DadosJson as jsonb)->>'consentimento_lgpd')::boolean,false) then now() end","carta-servicos"=>",@Descricao,cast(@DadosJson as jsonb)->>'setor_responsavel'","demandas"=>",@Descricao,@Justificativa","ouvidoria"=>",cast(@DadosJson as jsonb)->>'tipo',coalesce((cast(@DadosJson as jsonb)->>'anonima')::boolean,false),coalesce((cast(@DadosJson as jsonb)->>'sigilosa')::boolean,false)","esic"=>",cast(@DadosJson as jsonb)->>'setor_destino',(select now()+make_interval(days=>prazo_dias) from sigov.atendimento_sla_parametro where tenant_id=@TenantId and entidade_id=@EntidadeId and tipo='ESIC' and ativo and not is_deleted order by id limit 1),@Justificativa","encaminhamentos"=>",cast(@DadosJson as jsonb)->>'origem',cast(@DadosJson as jsonb)->>'destino'","agendas"=>",cast(@DadosJson as jsonb)->>'setor',coalesce((cast(@DadosJson as jsonb)->>'inicio_vigencia')::date,current_date),(cast(@DadosJson as jsonb)->>'slot_minutos')::integer","sla"=>",cast(@DadosJson as jsonb)->>'tipo',(cast(@DadosJson as jsonb)->>'prazo_dias')::integer","base-conhecimento"=>",@Descricao,cast(@DadosJson as jsonb)->>'resposta'",_=>""};
    private static string Csv(object? v){var s=Convert.ToString(v,CultureInfo.InvariantCulture)??"";if(s.Length>0&&"=+-@\t\r".Contains(s[0]))s="'"+s;return '"'+s.Replace("\"","\"\"")+'"';}
    private static Task Audit(AtendimentoContexto c,System.Data.IDbConnection cn,string acao,string recurso,long? id,string? depois,System.Data.IDbTransaction? tx,CancellationToken ct)=>cn.ExecuteAsync(new CommandDefinition("insert into sigov.atendimento_auditoria(acao,recurso,registro_id,usuario_id,depois,correlation_id,ip,tenant_id,entidade_id,created_by,descricao,status,dados) values(@acao,@recurso,@id,@UsuarioId,cast(@depois as jsonb),@CorrelationId,cast(@Ip as inet),@TenantId,@EntidadeId,@UsuarioId,@recurso,'REGISTRADA','{}')",new{acao,recurso,id,c.UsuarioId,depois,c.CorrelationId,c.Ip,c.TenantId,c.EntidadeId},tx,cancellationToken:ct));
}
