using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Sigov.Application.Commercial;
namespace Sigov.Api.Controllers.Commercial;
[ApiController,Authorize]
public abstract class CommercialControllerBase(ICommercialRepository repository):ControllerBase
{
 protected ICommercialRepository Repository {get;}=repository;
 protected Guid Tenant()=>Guid.TryParse(User.FindFirst("tenant_id")?.Value,out var id)&&id!=Guid.Empty?id:throw new UnauthorizedAccessException("Tenant não resolvido.");
 protected Guid UserId()=>Guid.TryParse(User.FindFirst("sub")?.Value,out var id)?id:Guid.Empty;
 protected string Correlation()=>HttpContext.TraceIdentifier;
}
[Route("api/comercial/dashboard")]
public sealed class CommercialDashboardController(ICommercialRepository r):CommercialControllerBase(r){[HttpGet]public async Task<ActionResult<ApiResponse<ComercialDashboardDto>>> Get([FromQuery]DateOnly? inicio,[FromQuery]DateOnly? fim,CancellationToken ct){var end=fim??DateOnly.FromDateTime(DateTime.UtcNow);var data=await Repository.ObterDashboardAsync(Tenant(),inicio??end.AddDays(-30),end,ct);return Ok(ApiResponse<ComercialDashboardDto>.Ok(data,correlationId:Correlation()));}}
[Route("api/comercial/clientes")]
public sealed class CommercialClientsController(ICommercialRepository r):CommercialControllerBase(r){[HttpGet]public async Task<IActionResult> List([FromQuery]ClienteFiltro filtro,CancellationToken ct)=>Ok(ApiResponse<object>.Ok(await Repository.ListarClientesAsync(Tenant(),filtro,ct),correlationId:Correlation()));[HttpGet("{id:guid}")]public async Task<IActionResult> Get(Guid id,CancellationToken ct){var x=await Repository.ObterClienteAsync(Tenant(),id,User.HasClaim("permission","comercial.clientes.dados_pessoais.visualizar"),ct);return x is null?NotFound(ApiResponse<object>.Fail("Cliente não encontrado.",Correlation())):Ok(ApiResponse<ClienteDetalheDto>.Ok(x,correlationId:Correlation()));}[HttpPost]public async Task<IActionResult>Create(CriarClienteRequest request,CancellationToken ct){var id=await Repository.CriarClienteAsync(Tenant(),UserId(),request,Correlation(),ct);return CreatedAtAction(nameof(Get),new{id},ApiResponse<Guid>.Ok(id,correlationId:Correlation()));}}
[Route("api/comercial/leads")]
public sealed class CommercialLeadsController(ICommercialRepository r):CommercialControllerBase(r){[HttpGet]public async Task<IActionResult>List(int pagina=1,int tamanho=20,string? busca=null,CancellationToken ct=default)=>Ok(ApiResponse<object>.Ok(await Repository.ListarLeadsAsync(Tenant(),pagina,tamanho,busca,ct),correlationId:Correlation()));[HttpPost]public async Task<IActionResult>Create(CriarLeadRequest request,CancellationToken ct){var id=await Repository.CriarLeadAsync(Tenant(),UserId(),request,Correlation(),ct);return Created($"/api/comercial/leads/{id}",ApiResponse<Guid>.Ok(id,correlationId:Correlation()));}[HttpPost("{id:guid}/converter")]public async Task<IActionResult>Convert(Guid id,ConverterLeadRequest request,CancellationToken ct)=>Ok(ApiResponse<ConversaoLeadDto>.Ok(await Repository.ConverterLeadAsync(Tenant(),UserId(),id,request,Correlation(),ct),correlationId:Correlation()));}
[Route("api/comercial/oportunidades")]
public sealed class CommercialOpportunitiesController(ICommercialRepository r):CommercialControllerBase(r){[HttpGet]public async Task<IActionResult>List(int pagina=1,int tamanho=100,string? fase=null,string? busca=null,CancellationToken ct=default)=>Ok(ApiResponse<object>.Ok(await Repository.ListarOportunidadesAsync(Tenant(),pagina,tamanho,fase,busca,ct),correlationId:Correlation()));[HttpPost("{id:guid}/mover-fase")]public async Task<IActionResult>Move(Guid id,MoverOportunidadeRequest request,CancellationToken ct){await Repository.MoverOportunidadeAsync(Tenant(),UserId(),id,request,Correlation(),ct);return Ok(ApiResponse<object>.Ok(new{id},correlationId:Correlation()));}}
[Route("api/comercial/propostas")]
public sealed class CommercialProposalsController(ICommercialRepository r):CommercialControllerBase(r){[HttpGet]public async Task<IActionResult>List(int pagina=1,int tamanho=20,CancellationToken ct=default)=>Ok(ApiResponse<object>.Ok(await Repository.ListarPropostasAsync(Tenant(),pagina,tamanho,ct),correlationId:Correlation()));[HttpGet("{id:guid}")]public async Task<IActionResult>Get(Guid id,CancellationToken ct){var x=await Repository.ObterPropostaAsync(Tenant(),id,ct);return x is null?NotFound():Ok(ApiResponse<PropostaDetalheDto>.Ok(x,correlationId:Correlation()));}[HttpPost]public async Task<IActionResult>Create(CriarPropostaRequest request,CancellationToken ct){var id=await Repository.CriarPropostaAsync(Tenant(),UserId(),request,Correlation(),ct);return CreatedAtAction(nameof(Get),new{id},ApiResponse<Guid>.Ok(id,correlationId:Correlation()));}[HttpPost("{id:guid}/emitir")]public async Task<IActionResult>Issue(Guid id,EmitirPropostaRequest request,CancellationToken ct){await Repository.EmitirPropostaAsync(Tenant(),UserId(),id,request.Version,Correlation(),ct);return Ok();}[HttpPost("{id:guid}/aprovar")]public async Task<IActionResult>Approve(Guid id,DecidirPropostaRequest request,CancellationToken ct){await Repository.AprovarPropostaAsync(Tenant(),UserId(),id,request.Version,Correlation(),ct);return Ok();}[HttpPost("{id:guid}/gerar-pedido")]public async Task<IActionResult>Order(Guid id,CancellationToken ct){var key=Request.Headers["Idempotency-Key"].ToString();return Ok(ApiResponse<PedidoDetalheDto>.Ok(await Repository.GerarPedidoAsync(Tenant(),UserId(),id,key,Correlation(),ct),correlationId:Correlation()));}}
[Route("api/comercial/pedidos")]
public sealed class CommercialOrdersController(ICommercialRepository r):CommercialControllerBase(r){[HttpGet]public async Task<IActionResult>List(int pagina=1,int tamanho=20,CancellationToken ct=default)=>Ok(ApiResponse<object>.Ok(await Repository.ListarPedidosAsync(Tenant(),pagina,tamanho,ct),correlationId:Correlation()));[HttpPost("{id:guid}/confirmar")]public async Task<IActionResult>Confirm(Guid id,ConfirmarPedidoRequest request,CancellationToken ct){await Repository.ConfirmarPedidoAsync(Tenant(),UserId(),id,request.Version,Correlation(),ct);return Ok();}}
