using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Sigov.Application.Atendimento;
using Sigov.Web.Models.Atendimento;
namespace Sigov.Web.Controllers;

[Authorize, Route("AtendimentoCidadao")]
public sealed class AtendimentoCidadaoController(IAtendimentoRepository repository, IAuthorizationService authorization, ILogger<AtendimentoCidadaoController> logger) : Controller
{
    private static readonly IReadOnlyDictionary<string,(string Titulo,string View,string Manage)> Recursos=new Dictionary<string,(string,string,string)>(StringComparer.OrdinalIgnoreCase) {
        ["cidadaos"]=("Cidadãos","ATENDIMENTO_CIDADAO_VIEW","ATENDIMENTO_CIDADAO_MANAGE"),["carta-servicos"]=("Carta de Serviços","ATENDIMENTO_SERVICO_VIEW","ATENDIMENTO_SERVICO_MANAGE"),["demandas"]=("Demandas","ATENDIMENTO_DEMANDA_VIEW","ATENDIMENTO_DEMANDA_MANAGE"),["ouvidoria"]=("Ouvidoria","OUVIDORIA_MANIFESTACAO_VIEW","OUVIDORIA_MANIFESTACAO_MANAGE"),["esic"]=("e-SIC / LAI","ESIC_PEDIDO_VIEW","ESIC_PEDIDO_MANAGE"),["encaminhamentos"]=("Encaminhamentos","ATENDIMENTO_ENCAMINHAMENTO_VIEW","ATENDIMENTO_ENCAMINHAMENTO_MANAGE"),["agendas"]=("Agendas","ATENDIMENTO_AGENDA_VIEW","ATENDIMENTO_AGENDA_MANAGE"),["agendamentos"]=("Agendamentos","ATENDIMENTO_AGENDAMENTO_VIEW","ATENDIMENTO_AGENDAMENTO_MANAGE"),["sla"]=("SLA e alertas","ATENDIMENTO_SLA_VIEW","ATENDIMENTO_SLA_MANAGE"),["satisfacao"]=("Satisfação","ATENDIMENTO_SATISFACAO_VIEW","ATENDIMENTO_SATISFACAO_VIEW"),["base-conhecimento"]=("Base de conhecimento","ATENDIMENTO_BASE_CONHECIMENTO_VIEW","ATENDIMENTO_BASE_CONHECIMENTO_MANAGE"),["auditoria"]=("Auditoria","ATENDIMENTO_AUDITORIA_VIEW","ATENDIMENTO_AUDITORIA_VIEW")};
    [HttpGet(""),HttpGet("Dashboard"),Authorize(Policy="ATENDIMENTO_DASHBOARD_VIEW")] public async Task<IActionResult> Index(string? status,DateOnly? inicio,DateOnly? fim,CancellationToken ct)=>View("Dashboard",await repository.DashboardAsync(Contexto(),new(null,status,inicio,fim),ct));
    [AllowAnonymous,HttpGet("CartaServicos")] public async Task<IActionResult> CartaServicos(string? busca,CancellationToken ct)=>View("Lista",new AtendimentoListaViewModel("Carta de Serviços","carta-servicos",await repository.ListarAsync(ContextoPublico(),"carta-servicos",new(busca,"ATIVO"),false,ct),new(busca,"ATIVO")));
    [HttpGet("{recurso:regex(^Cidadaos|Demandas|Ouvidoria|Esic|Encaminhamentos|Agendas|Agendamentos|Sla|Satisfacao|BaseConhecimento|Auditoria$)}")] public async Task<IActionResult> Lista(string recurso,string? busca,string? status,int pagina,CancellationToken ct){recurso=Slug(recurso);var m=Meta(recurso);if(!await Permitido(m.View))return Forbid();var f=new AtendimentoFiltro(busca,status,Pagina:Math.Max(1,pagina));var sigilo=await Permitido("OUVIDORIA_SIGILO_VIEW");return View("Lista",new AtendimentoListaViewModel(m.Titulo,recurso,await repository.ListarAsync(Contexto(),recurso,f,sigilo,ct),f));}
    [HttpGet("{recurso}/Novo")] public async Task<IActionResult> Novo(string recurso){recurso=Slug(recurso);var m=Meta(recurso);if(!await Permitido(m.Manage))return Forbid();ViewData["Recurso"]=recurso;ViewData["Titulo"]=m.Titulo;return View("Form",new AtendimentoRegistroRequest("","","ABERTO",null));}
    [HttpPost("{recurso}/Salvar"),ValidateAntiForgeryToken] public async Task<IActionResult> Salvar(string recurso,AtendimentoRegistroRequest model,long? id,CancellationToken ct){recurso=Slug(recurso);var m=Meta(recurso);if(!await Permitido(m.Manage))return Forbid();try{await repository.SalvarAsync(Contexto(),recurso,model,id,ct);TempData["Success"]="Registro salvo com histórico e auditoria.";return Redirect($"/AtendimentoCidadao/{RouteName(recurso)}");}catch(Exception ex) when(ex is ArgumentException or InvalidOperationException or KeyNotFoundException){logger.LogWarning(ex,"Validação no atendimento {Recurso} ({CorrelationId})",recurso,HttpContext.TraceIdentifier);ModelState.AddModelError("",ex.Message);}catch(Exception ex){logger.LogError(ex,"Falha no atendimento ({CorrelationId})",HttpContext.TraceIdentifier);ModelState.AddModelError("",$"Não foi possível salvar. Referência: {HttpContext.TraceIdentifier}");}ViewData["Recurso"]=recurso;ViewData["Titulo"]=m.Titulo;return View("Form",model);}
    [HttpPost("{recurso}/{id:long}/Excluir"),ValidateAntiForgeryToken] public async Task<IActionResult> Excluir(string recurso,long id,string justificativa,CancellationToken ct){recurso=Slug(recurso);var m=Meta(recurso);if(!await Permitido(m.Manage))return Forbid();try{await repository.ExcluirAsync(Contexto(),recurso,id,justificativa,ct);TempData["Success"]="Registro excluído logicamente e auditado.";}catch(Exception ex){logger.LogError(ex,"Falha ao excluir {Recurso} ({CorrelationId})",recurso,HttpContext.TraceIdentifier);TempData["Error"]=$"Não foi possível excluir: {ex.Message}";}return Redirect($"/AtendimentoCidadao/{RouteName(recurso)}");}
    [HttpGet("Relatorios"),Authorize(Policy="ATENDIMENTO_RELATORIO_EXPORT")] public IActionResult Relatorios()=>View("Relatorios");
    [HttpGet("Relatorios/{relatorio}.csv"),Authorize(Policy="ATENDIMENTO_RELATORIO_EXPORT")] public async Task<IActionResult> Csv(string relatorio,CancellationToken ct)=>File(await repository.ExportarCsvAsync(Contexto(),Slug(relatorio),new(null,null),ct),"text/csv; charset=utf-8",$"atendimento-{relatorio}-{DateTime.UtcNow:yyyyMMdd}.csv");
    private async Task<bool> Permitido(string p)=>(await authorization.AuthorizeAsync(User,p)).Succeeded;
    private static string Slug(string r)=>r.Replace("BaseConhecimento","base-conhecimento",StringComparison.OrdinalIgnoreCase).Replace("CartaServicos","carta-servicos",StringComparison.OrdinalIgnoreCase).ToLowerInvariant();
    private static string RouteName(string r)=>r switch{"base-conhecimento"=>"BaseConhecimento","carta-servicos"=>"CartaServicos",_=>char.ToUpperInvariant(r[0])+r[1..]};
    private static (string Titulo,string View,string Manage) Meta(string r)=>Recursos.TryGetValue(r,out var m)?m:throw new ArgumentException("Recurso inválido.");
    private AtendimentoContexto Contexto(){if(!long.TryParse(User.FindFirst("tenant_id")?.Value,out var t)||t<=0||!long.TryParse(User.FindFirst("entidade_id")?.Value,out var e)||e<=0)throw new UnauthorizedAccessException("Tenant/entidade não resolvidos.");long.TryParse(User.FindFirst("sub")?.Value??User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value,out var u);return new(t,e,u>0?u:null,HttpContext.TraceIdentifier,HttpContext.Connection.RemoteIpAddress?.ToString());}
    private AtendimentoContexto ContextoPublico()=>Contexto();
}
