using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Sigov.Application.Convenios;
using Sigov.Web.Models.Convenios;
namespace Sigov.Web.Controllers;

[Authorize,Route("Convenios")]
public sealed class ConveniosController(IConvenioRepository repository,IAuthorizationService authorization):Controller
{
 private static readonly Dictionary<string,(string Title,string View,string Manage)> Resources=new(StringComparer.OrdinalIgnoreCase){["Orgaos"]=("Órgãos concedentes","CONVENIO_ORGAO_VIEW","CONVENIO_ORGAO_MANAGE"),["Programas"]=("Programas de repasse","CONVENIO_PROGRAMA_VIEW","CONVENIO_PROGRAMA_MANAGE"),["Emendas"]=("Emendas parlamentares","CONVENIO_EMENDA_VIEW","CONVENIO_EMENDA_MANAGE"),["Instrumentos"]=("Convênios e instrumentos","CONVENIO_INSTRUMENTO_VIEW","CONVENIO_INSTRUMENTO_MANAGE"),["Projetos"]=("Projetos e planos de trabalho","CONVENIO_PROJETO_VIEW","CONVENIO_PROJETO_MANAGE"),["Metas"]=("Metas","CONVENIO_META_VIEW","CONVENIO_META_MANAGE"),["Etapas"]=("Etapas e cronograma","CONVENIO_ETAPA_VIEW","CONVENIO_ETAPA_MANAGE"),["ContasBancarias"]=("Contas bancárias vinculadas","CONVENIO_FINANCEIRO_VIEW","CONVENIO_FINANCEIRO_MANAGE"),["Repasses"]=("Liberações e repasses","CONVENIO_FINANCEIRO_VIEW","CONVENIO_FINANCEIRO_MANAGE"),["Despesas"]=("Despesas vinculadas","CONVENIO_FINANCEIRO_VIEW","CONVENIO_FINANCEIRO_MANAGE"),["Contrapartidas"]=("Contrapartidas","CONVENIO_FINANCEIRO_VIEW","CONVENIO_FINANCEIRO_MANAGE"),["Acompanhamentos"]=("Acompanhamento da execução","CONVENIO_PROJETO_VIEW","CONVENIO_PROJETO_MANAGE"),["PrestacoesContas"]=("Prestações de contas","CONVENIO_PRESTACAO_VIEW","CONVENIO_PRESTACAO_MANAGE"),["Diligencias"]=("Diligências e pendências","CONVENIO_DILIGENCIA_VIEW","CONVENIO_DILIGENCIA_MANAGE"),["Documentos"]=("Documentos de referência","CONVENIO_INSTRUMENTO_VIEW","CONVENIO_INSTRUMENTO_MANAGE"),["Auditoria"]=("Auditoria","CONVENIO_AUDITORIA_VIEW","CONVENIO_AUDITORIA_VIEW")};
 [HttpGet(""),HttpGet("Dashboard"),Authorize(Policy="CONVENIO_DASHBOARD_VIEW")]public async Task<IActionResult> Dashboard(CancellationToken ct)=>View(await repository.DashboardAsync(Context(),ct));
 [HttpGet("{recurso}")]public async Task<IActionResult> Lista(string recurso,string? busca,string? status,DateOnly? inicio,DateOnly? fim,int pagina,CancellationToken ct){var m=Meta(recurso);if(!await Allowed(m.View))return Forbid();var f=new ConvenioFiltro(busca,status,inicio,fim,Math.Max(1,pagina));return View("Lista",new ConvenioListaViewModel(m.Title,recurso,await repository.ListarAsync(Context(),recurso,f,ct),f));}
 [HttpGet("{recurso}/Novo")]public async Task<IActionResult> Novo(string recurso,CancellationToken ct){var m=Meta(recurso);if(!await Allowed(m.Manage)||recurso.Equals("Auditoria",StringComparison.OrdinalIgnoreCase))return Forbid();return View("Form",await Form(m.Title,recurso,new(),null,ct));}
 [HttpGet("{recurso}/{id:long}")]public async Task<IActionResult> Detalhes(string recurso,long id,CancellationToken ct){var m=Meta(recurso);if(!await Allowed(m.View))return Forbid();var row=await repository.ObterAsync(Context(),recurso,id,ct);return row is null?NotFound():View("Detalhes",new ConvenioDetalhesViewModel(m.Title,recurso,id,row));}
 [HttpGet("{recurso}/{id:long}/Editar")]public async Task<IActionResult> Editar(string recurso,long id,CancellationToken ct){var m=Meta(recurso);if(!await Allowed(m.Manage))return Forbid();var row=await repository.ObterAsync(Context(),recurso,id,ct);return row is null?NotFound():View("Form",await Form(m.Title,recurso,row,id,ct));}
 [HttpPost("{recurso}/Salvar"),ValidateAntiForgeryToken]public async Task<IActionResult> Salvar(string recurso,long? id,ConvenioRegistroRequest registro,CancellationToken ct){var m=Meta(recurso);if(!await Allowed(m.Manage))return Forbid();Validate(recurso,registro);if(!ModelState.IsValid)return View("Form",await Form(m.Title,recurso,registro,id,ct));try{await repository.SalvarAsync(Context(),recurso,registro,id,ct);TempData["Success"]="Registro salvo e auditado.";return RedirectToAction(nameof(Lista),new{recurso});}catch(ArgumentException ex){ModelState.AddModelError("",ex.Message);return View("Form",await Form(m.Title,recurso,registro,id,ct));}}
 [HttpPost("{recurso}/{id:long}/Excluir"),ValidateAntiForgeryToken]public async Task<IActionResult> Excluir(string recurso,long id,CancellationToken ct){var m=Meta(recurso);if(!await Allowed(m.Manage))return Forbid();await repository.ExcluirAsync(Context(),recurso,id,ct);return RedirectToAction(nameof(Lista),new{recurso});}
 [HttpGet("Relatorios"),Authorize(Policy="CONVENIO_RELATORIO_EXPORT")]public IActionResult Relatorios()=>View();
 [HttpGet("Relatorios/{recurso}.csv"),Authorize(Policy="CONVENIO_RELATORIO_EXPORT")]public async Task<IActionResult> Csv(string recurso,string? busca,string? status,DateOnly? inicio,DateOnly? fim,CancellationToken ct)=>File(await repository.CsvAsync(Context(),recurso,new(busca,status,inicio,fim),ct),"text/csv; charset=utf-8",$"convenios-{recurso}-{DateTime.UtcNow:yyyyMMdd}.csv");
 private async Task<ConvenioFormViewModel> Form(string title,string recurso,ConvenioRegistroRequest r,long? id,CancellationToken ct){var d=new Dictionary<string,IReadOnlyList<ConvenioOpcao>>();foreach(var relation in Relations(recurso))d[relation.Key]=await repository.OpcoesAsync(Context(),relation.Value,ct);return new(title,recurso,id,r,d);}
 private static Dictionary<string,string> Relations(string r)=>r switch{"Programas"=>new(){{"orgao_concedente_id","Orgaos"}},"Instrumentos"=>new(){{"orgao_concedente_id","Orgaos"},{"programa_id","Programas"},{"emenda_id","Emendas"}},"Projetos"=>new(){{"instrumento_id","Instrumentos"}},"Metas"=>new(){{"projeto_id","Projetos"}},"Etapas"=>new(){{"meta_id","Metas"}},"ContasBancarias" or "Contrapartidas"=>new(){{"instrumento_id","Instrumentos"}},"Repasses"=>new(){{"instrumento_id","Instrumentos"},{"conta_bancaria_id","ContasBancarias"}},"Despesas"=>new(){{"instrumento_id","Instrumentos"},{"projeto_id","Projetos"},{"etapa_id","Etapas"},{"conta_bancaria_id","ContasBancarias"}},"Acompanhamentos"=>new(){{"projeto_id","Projetos"}},"PrestacoesContas"=>new(){{"instrumento_id","Instrumentos"}},"Diligencias"=>new(){{"prestacao_contas_id","PrestacoesContas"}},"Documentos"=>new(){{"instrumento_id","Instrumentos"},{"projeto_id","Projetos"},{"prestacao_contas_id","PrestacoesContas"}},_=>[]};
 private void Validate(string recurso,ConvenioRegistroRequest r)
 {
  string? F(string name)=>r.Campos.GetValueOrDefault(name);
  void Req(params string[] fields){foreach(var field in fields)if(string.IsNullOrWhiteSpace(F(field)))ModelState.AddModelError($"Registro.Campos[{field}]","Campo obrigatório.");}
  void Dates(string start,string end){if(DateOnly.TryParse(F(start),out var x)&&DateOnly.TryParse(F(end),out var y)&&y<x)ModelState.AddModelError($"Registro.Campos[{end}]","A data final não pode anteceder a data inicial.");}
  decimal? Number(string field){if(string.IsNullOrWhiteSpace(F(field)))return null;if(decimal.TryParse(F(field),out var value))return value;ModelState.AddModelError($"Registro.Campos[{field}]","Informe um número válido.");return null;}
  void NonNegative(params string[] fields){foreach(var field in fields)if(Number(field) is < 0)ModelState.AddModelError($"Registro.Campos[{field}]","O valor não pode ser negativo.");}
  void Percent(params string[] fields){foreach(var field in fields)if(Number(field) is decimal value&&(value<0||value>100))ModelState.AddModelError($"Registro.Campos[{field}]","O percentual deve estar entre 0 e 100.");}
  var statuses=recurso switch{
   "Orgaos"=>new[]{"ATIVO","INATIVO"},"Programas"=>new[]{"ATIVO","INATIVO","ENCERRADO","CANCELADO"},"Emendas"=>new[]{"CADASTRADA","APROVADA","EMPENHADA","PAGA","CANCELADA"},"Instrumentos"=>new[]{"RASCUNHO","ATIVO","SUSPENSO","ENCERRADO","CANCELADO"},"Projetos"=>new[]{"PLANEJADO","EM_EXECUCAO","CONCLUIDO","SUSPENSO","CANCELADO"},"Metas" or "Etapas"=>new[]{"PENDENTE","EM_EXECUCAO","CONCLUIDA","CANCELADA"},"ContasBancarias"=>new[]{"ATIVA","INATIVA","ENCERRADA","AJUSTE"},"Repasses"=>new[]{"PREVISTO","RECEBIDO","ESTORNADO","CANCELADO"},"Despesas"=>new[]{"PENDENTE","LIQUIDADA","PAGA","ESTORNADA","CANCELADA"},"Contrapartidas"=>new[]{"PREVISTA","REALIZADA","PARCIAL","CANCELADA"},"Acompanhamentos"=>new[]{"REGULAR","ATENCAO","CRITICO","ENCERRADO"},"PrestacoesContas"=>new[]{"RASCUNHO","ENVIADA","EM_ANALISE","DILIGENCIA","APROVADA","REJEITADA","CANCELADA"},"Diligencias"=>new[]{"ABERTA","EM_RESPOSTA","RESPONDIDA","ENCERRADA","CANCELADA"},"Documentos"=>new[]{"ATIVO","INATIVO","CANCELADO"},_=>Array.Empty<string>()};
  if(!statuses.Contains(r.Status,StringComparer.Ordinal))ModelState.AddModelError("Registro.Status","Selecione um status válido para este cadastro.");
  switch(recurso){
   case "Orgaos":Req("esfera");break;
   case "Programas":Req("orgao_concedente_id","finalidade","area","data_inicio");Dates("data_inicio","data_fim");break;
   case "Emendas":Req("esfera","ano","area","valor_previsto","valor_aprovado");NonNegative("valor_previsto","valor_aprovado");break;
   case "Instrumentos":Req("tipo","orgao_concedente_id","valor_global","valor_repasse","valor_contrapartida","data_assinatura","vigencia_inicio","vigencia_fim","responsavel_nome");Dates("vigencia_inicio","vigencia_fim");NonNegative("valor_global","valor_repasse","valor_contrapartida");if(Number("valor_global") is decimal g&&Number("valor_repasse") is decimal rp&&Number("valor_contrapartida") is decimal cp&&Math.Abs(g-rp-cp)>.01m)ModelState.AddModelError("Registro.Campos[valor_global]","Valor global deve ser igual a repasse mais contrapartida (tolerância de R$ 0,01).");break;
   case "Projetos":Req("instrumento_id","justificativa","publico_alvo","local_execucao","unidade_responsavel","data_inicio","data_fim_prevista","percentual_execucao");Dates("data_inicio","data_fim_prevista");Dates("data_inicio","data_fim_real");Percent("percentual_execucao");if(r.Status=="CONCLUIDO")Req("data_fim_real");break;
   case "Metas":Req("projeto_id","indicador","unidade_medida","quantidade_prevista","quantidade_executada");NonNegative("quantidade_prevista","quantidade_executada");if(r.Status=="CONCLUIDA"&&Number("quantidade_executada")<Number("quantidade_prevista"))ModelState.AddModelError("Registro.Campos[quantidade_executada]","Meta concluída deve alcançar a quantidade prevista.");break;
   case "Etapas":Req("meta_id","data_inicio","data_fim_prevista","valor_previsto","valor_executado");Dates("data_inicio","data_fim_prevista");Dates("data_inicio","data_fim_real");NonNegative("valor_previsto","valor_executado");if(r.Status=="CONCLUIDA")Req("data_fim_real");if(Number("valor_executado")>Number("valor_previsto")&&string.IsNullOrWhiteSpace(F("observacao")))ModelState.AddModelError("Registro.Campos[observacao]","Justifique a execução acima do valor previsto.");break;
   case "ContasBancarias":Req("instrumento_id","banco","agencia","tipo_conta","saldo_inicial","saldo_atual");break;
   case "Repasses":Req("instrumento_id","data_repasse","valor","fonte_recurso");if(Number("valor") is <=0)ModelState.AddModelError("Registro.Campos[valor]","O repasse deve ter valor positivo.");break;
   case "Despesas":Req("instrumento_id","fornecedor_nome","fornecedor_documento","data_despesa","valor","natureza_despesa");if(Number("valor") is <=0)ModelState.AddModelError("Registro.Campos[valor]","A despesa deve ter valor positivo.");if(r.Status=="PAGA")Req("data_pagamento");Dates("data_despesa","data_pagamento");break;
   case "Contrapartidas":Req("instrumento_id","valor_previsto","valor_realizado");NonNegative("valor_previsto","valor_realizado");if(r.Status is "REALIZADA" or "PARCIAL")Req("data_realizacao");break;
   case "Acompanhamentos":Req("projeto_id","data_acompanhamento","responsavel_nome","percentual_fisico","percentual_financeiro");Percent("percentual_fisico","percentual_financeiro");break;
   case "PrestacoesContas":Req("instrumento_id","periodo_inicio","periodo_fim","valor_prestado");Dates("periodo_inicio","periodo_fim");NonNegative("valor_prestado","valor_aprovado");if(r.Status is "ENVIADA" or "EM_ANALISE" or "DILIGENCIA" or "APROVADA" or "REJEITADA")Req("data_envio");if(r.Status=="APROVADA")Req("valor_aprovado","parecer_resumo");break;
   case "Diligencias":Req("prestacao_contas_id","data_recebimento","prazo_resposta");Dates("data_recebimento","prazo_resposta");Dates("data_recebimento","data_resposta");if(r.Status is "RESPONDIDA" or "ENCERRADA")Req("data_resposta","resposta");break;
   case "Documentos":Req("tipo_documento","data_documento");if(new[]{F("instrumento_id"),F("projeto_id"),F("prestacao_contas_id")}.Count(x=>!string.IsNullOrWhiteSpace(x))!=1)ModelState.AddModelError("","Selecione exatamente um vínculo: instrumento, projeto ou prestação de contas.");break;
  }
 }
 private ConvenioContexto Context(){if(!long.TryParse(User.FindFirst("tenant_id")?.Value,out var t)||!long.TryParse(User.FindFirst("entidade_id")?.Value??User.FindFirst("entity_id")?.Value,out var e)||t<=0||e<=0)throw new UnauthorizedAccessException("Contexto tenant/entidade não resolvido.");return new(t,e,User.Identity?.Name??"sistema");}private async Task<bool> Allowed(string p)=>(await authorization.AuthorizeAsync(User,p)).Succeeded;private static(string Title,string View,string Manage)Meta(string r)=>Resources.TryGetValue(r,out var m)?m:throw new ArgumentException("Recurso inválido.");
}
