using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Sigov.Application.Convenios;
using Sigov.Web.Models.Convenios;
namespace Sigov.Web.Controllers;

[Authorize,Route("Convenios")]
public sealed class ConveniosController(IConvenioRepository repository,IAuthorizationService authorization):Controller
{
 private static readonly Dictionary<string,(string Title,string View,string Manage)> Resources=new(StringComparer.OrdinalIgnoreCase){["Orgaos"]=("Órgãos concedentes","CONVENIO_ORGAO_VIEW","CONVENIO_ORGAO_MANAGE"),["Programas"]=("Programas de repasse","CONVENIO_PROGRAMA_VIEW","CONVENIO_PROGRAMA_MANAGE"),["Emendas"]=("Emendas parlamentares","CONVENIO_EMENDA_VIEW","CONVENIO_EMENDA_MANAGE"),["Instrumentos"]=("Convênios e instrumentos","CONVENIO_INSTRUMENTO_VIEW","CONVENIO_INSTRUMENTO_MANAGE"),["Projetos"]=("Projetos e planos de trabalho","CONVENIO_PROJETO_VIEW","CONVENIO_PROJETO_MANAGE"),["Metas"]=("Metas","CONVENIO_META_VIEW","CONVENIO_META_MANAGE"),["Etapas"]=("Etapas e cronograma","CONVENIO_ETAPA_VIEW","CONVENIO_ETAPA_MANAGE"),["ContasBancarias"]=("Contas bancárias vinculadas","CONVENIO_FINANCEIRO_VIEW","CONVENIO_FINANCEIRO_MANAGE"),["Repasses"]=("Liberações e repasses","CONVENIO_FINANCEIRO_VIEW","CONVENIO_FINANCEIRO_MANAGE"),["Despesas"]=("Despesas vinculadas","CONVENIO_FINANCEIRO_VIEW","CONVENIO_FINANCEIRO_MANAGE"),["Contrapartidas"]=("Contrapartidas","CONVENIO_FINANCEIRO_VIEW","CONVENIO_FINANCEIRO_MANAGE"),["Acompanhamentos"]=("Acompanhamento da execução","CONVENIO_PROJETO_VIEW","CONVENIO_PROJETO_MANAGE"),["PrestacoesContas"]=("Prestações de contas","CONVENIO_PRESTACAO_VIEW","CONVENIO_PRESTACAO_MANAGE"),["Diligencias"]=("Diligências e pendências","CONVENIO_DILIGENCIA_VIEW","CONVENIO_DILIGENCIA_MANAGE"),["Documentos"]=("Documentos de referência","CONVENIO_INSTRUMENTO_VIEW","CONVENIO_INSTRUMENTO_MANAGE"),["Auditoria"]=("Auditoria","CONVENIO_AUDITORIA_VIEW","CONVENIO_AUDITORIA_VIEW")};
 [HttpGet(""),HttpGet("Dashboard"),Authorize(Policy="CONVENIO_DASHBOARD_VIEW")]public async Task<IActionResult> Dashboard(CancellationToken ct)=>View(await repository.DashboardAsync(Context(),ct));
 [HttpGet("{recurso}")]public async Task<IActionResult> Lista(string recurso,string? busca,string? status,DateOnly? inicio,DateOnly? fim,int pagina,CancellationToken ct){var m=Meta(recurso);if(!await Allowed(m.View))return Forbid();var f=new ConvenioFiltro(busca,status,inicio,fim,Math.Max(1,pagina));return View("Lista",new ConvenioListaViewModel(m.Title,recurso,await repository.ListarAsync(Context(),recurso,f,ct),f));}
 [HttpGet("{recurso}/Novo")]public async Task<IActionResult> Novo(string recurso,CancellationToken ct){var m=Meta(recurso);if(!await Allowed(m.Manage)||recurso.Equals("Auditoria",StringComparison.OrdinalIgnoreCase))return Forbid();return View("Form",await Form(m.Title,recurso,new(),null,ct));}
 [HttpGet("{recurso}/{id:long}")]public async Task<IActionResult> Detalhes(string recurso,long id,CancellationToken ct){var m=Meta(recurso);if(!await Allowed(m.View))return Forbid();var row=await repository.ObterAsync(Context(),recurso,id,ct);return row is null?NotFound():View("Detalhes",new ConvenioDetalhesViewModel(m.Title,recurso,id,row));}
 [HttpGet("{recurso}/{id:long}/Editar")]public async Task<IActionResult> Editar(string recurso,long id,CancellationToken ct){var m=Meta(recurso);if(!await Allowed(m.Manage))return Forbid();var row=await repository.ObterAsync(Context(),recurso,id,ct);return row is null?NotFound():View("Form",await Form(m.Title,recurso,row,id,ct));}
 [HttpPost("{recurso}/Salvar"),ValidateAntiForgeryToken]public async Task<IActionResult> Salvar(string recurso,long? id,ConvenioRegistroRequest registro,CancellationToken ct){var m=Meta(recurso);if(!await Allowed(m.Manage))return Forbid();Validate(recurso,registro);if(!ModelState.IsValid)return View("Form",await Form(m.Title,recurso,registro,id,ct));try{await repository.SalvarAsync(Context(),recurso,registro,id,ct);TempData["Success"]="Registro salvo e auditado.";return RedirectToAction(nameof(Lista),new{recurso});}catch(ArgumentException ex){ModelState.AddModelError("",ex.Message);return View("Form",await Form(m.Title,recurso,registro,id,ct));}}
 [HttpPost("{recurso}/{id:long}/Excluir"),ValidateAntiForgeryToken]public async Task<IActionResult> Excluir(string recurso,long id,CancellationToken ct){var m=Meta(recurso);if(!await Allowed(m.Manage))return Forbid();await repository.ExcluirAsync(Context(),recurso,id,ct);return RedirectToAction(nameof(Lista),new{recurso});}
 [HttpGet("Relatorios"),Authorize(Policy="CONVENIO_RELATORIO_EXPORT")]public IActionResult Relatorios()=>View();
 [HttpGet("Relatorios/{recurso}.csv"),Authorize(Policy="CONVENIO_RELATORIO_EXPORT")]public async Task<IActionResult> Csv(string recurso,string? busca,string? status,DateOnly? inicio,DateOnly? fim,CancellationToken ct)=>File(await repository.CsvAsync(Context(),recurso,new(busca,status,inicio,fim),ct),"text/csv; charset=utf-8",$"convenios-{recurso}-{DateTime.UtcNow:yyyyMMdd}.csv");
 private async Task<ConvenioFormViewModel> Form(string title,string recurso,ConvenioRegistroRequest r,long? id,CancellationToken ct){var d=new Dictionary<string,IReadOnlyList<ConvenioOpcao>>();foreach(var relation in Relations(recurso))d[relation.Key]=await repository.OpcoesAsync(Context(),relation.Value,ct);return new(title,recurso,id,r,d);}
 private static Dictionary<string,string> Relations(string r)=>r switch{"Programas"=>new(){{"orgao_concedente_id","Orgaos"}},"Instrumentos"=>new(){{"orgao_concedente_id","Orgaos"},{"programa_id","Programas"},{"emenda_id","Emendas"}},"Projetos"=>new(){{"instrumento_id","Instrumentos"}},"Metas"=>new(){{"projeto_id","Projetos"}},"Etapas"=>new(){{"meta_id","Metas"}},"ContasBancarias" or "Contrapartidas"=>new(){{"instrumento_id","Instrumentos"}},"Repasses"=>new(){{"instrumento_id","Instrumentos"},{"conta_bancaria_id","ContasBancarias"}},"Despesas"=>new(){{"instrumento_id","Instrumentos"},{"projeto_id","Projetos"},{"etapa_id","Etapas"},{"conta_bancaria_id","ContasBancarias"}},"Acompanhamentos"=>new(){{"projeto_id","Projetos"}},"PrestacoesContas"=>new(){{"instrumento_id","Instrumentos"}},"Diligencias"=>new(){{"prestacao_contas_id","PrestacoesContas"}},"Documentos"=>new(){{"instrumento_id","Instrumentos"},{"projeto_id","Projetos"},{"prestacao_contas_id","PrestacoesContas"}},_=>[]};
 private void Validate(string recurso,ConvenioRegistroRequest r){string? F(string n)=>r.Campos.GetValueOrDefault(n);void Req(params string[] fs){foreach(var f in fs)if(string.IsNullOrWhiteSpace(F(f)))ModelState.AddModelError($"Registro.Campos[{f}]","Campo obrigatório.");}void Dates(string a,string b){if(DateOnly.TryParse(F(a),out var x)&&DateOnly.TryParse(F(b),out var y)&&y<x)ModelState.AddModelError("",$"{b} não pode anteceder {a}.");}switch(recurso){case"Programas":Req("orgao_concedente_id","finalidade","area","data_inicio");Dates("data_inicio","data_fim");break;case"Instrumentos":Req("tipo","orgao_concedente_id","valor_global","valor_repasse","valor_contrapartida","vigencia_inicio","vigencia_fim","responsavel_nome");Dates("vigencia_inicio","vigencia_fim");if(decimal.TryParse(F("valor_global"),out var g)&&decimal.TryParse(F("valor_repasse"),out var rp)&&decimal.TryParse(F("valor_contrapartida"),out var cp)&&Math.Abs(g-rp-cp)>.01m)ModelState.AddModelError("","Valor global deve ser igual a repasse mais contrapartida.");break;case"Projetos":Req("instrumento_id","data_inicio","data_fim_prevista");Dates("data_inicio","data_fim_prevista");Dates("data_inicio","data_fim_real");if(r.Status=="CONCLUIDO")Req("data_fim_real");break;case"Metas":Req("projeto_id","quantidade_prevista");break;case"Etapas":Req("meta_id","data_inicio","data_fim_prevista","valor_previsto","valor_executado");Dates("data_inicio","data_fim_prevista");if(r.Status=="CONCLUIDA")Req("data_fim_real");break;case"Repasses":Req("instrumento_id","data_repasse","valor");break;case"Despesas":Req("instrumento_id","fornecedor_documento","data_despesa","valor","natureza_despesa");if(r.Status=="PAGA")Req("data_pagamento");break;case"PrestacoesContas":Req("instrumento_id","periodo_inicio","periodo_fim","valor_prestado");Dates("periodo_inicio","periodo_fim");if(r.Status is "ENVIADA" or "APROVADA")Req("data_envio");if(r.Status=="APROVADA")Req("valor_aprovado","parecer_resumo");break;case"Diligencias":Req("prestacao_contas_id","data_recebimento","prazo_resposta");Dates("data_recebimento","prazo_resposta");Dates("data_recebimento","data_resposta");if(r.Status=="RESPONDIDA")Req("data_resposta","resposta");break;}}
 private ConvenioContexto Context(){if(!long.TryParse(User.FindFirst("tenant_id")?.Value,out var t)||!long.TryParse(User.FindFirst("entidade_id")?.Value??User.FindFirst("entity_id")?.Value,out var e)||t<=0||e<=0)throw new UnauthorizedAccessException("Contexto tenant/entidade não resolvido.");return new(t,e,User.Identity?.Name??"sistema");}private async Task<bool> Allowed(string p)=>(await authorization.AuthorizeAsync(User,p)).Succeeded;private static(string Title,string View,string Manage)Meta(string r)=>Resources.TryGetValue(r,out var m)?m:throw new ArgumentException("Recurso inválido.");
}
