using System.Text;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Sigov.Web.Models.Editais;
using Sigov.Web.Services.Editais;

namespace Sigov.Web.Controllers;

[Authorize]
public sealed class EditaisController : Controller
{
    private readonly EditalPocService _service; public EditaisController(EditalPocService service)=>_service=service;
    [HttpGet("/Editais")] public async Task<IActionResult> Index(CancellationToken ct)=>View(await _service.ListarEditaisAsync(ct));
    [HttpGet("/Editais/Novo")] public IActionResult Novo()=>View(new EditalFormViewModel());
    [HttpPost("/Editais/Novo")] public async Task<IActionResult> Novo(EditalFormViewModel form,CancellationToken ct){ var id=await _service.CriarEditalAsync(form,HttpContext.TraceIdentifier,ct); TempData[id.HasValue?"Success":"Warning"] = id.HasValue?"Edital salvo com auditoria.":"Schema sigov.edital ausente: edital não foi simulado como salvo."; return RedirectToAction("Index"); }
    [HttpGet("/Editais/{id:long}")] public async Task<IActionResult> Detalhe(long id,CancellationToken ct)=>View(await _service.ObterDetalheAsync(id,ct));
    [HttpGet("/Editais/{id:long}/Editar")] public async Task<IActionResult> Editar(long id,CancellationToken ct)=>View("Novo", new EditalFormViewModel{Nome=(await _service.ObterDetalheAsync(id,ct)).Edital.Nome});
    [HttpPost("/Editais/{id:long}/Editar")] public async Task<IActionResult> Editar(long id, EditalFormViewModel form,CancellationToken ct){ await _service.RegistrarAcaoAsync("EDITAL_EDITAR_SOLICITADO","edital",id.ToString(),form,HttpContext.TraceIdentifier,ct); TempData["Warning"]="Edição real depende do schema detectado; sem simulação falsa."; return Redirect($"/Editais/{id}"); }
    [HttpPost("/Editais/{id:long}/Arquivar")] public async Task<IActionResult> Arquivar(long id,CancellationToken ct){ await _service.RegistrarAcaoAsync("EDITAL_ARQUIVAR_SOLICITADO","edital",id.ToString(),new{id},HttpContext.TraceIdentifier,ct); TempData["Warning"]="Arquivamento auditado; persistência depende de sigov.edital."; return RedirectToAction("Index"); }
    [HttpGet("/Editais/{id:long}/Documentos")] public async Task<IActionResult> Documentos(long id,CancellationToken ct)=>View(await _service.ObterDetalheAsync(id,ct));
    [HttpPost("/Editais/{id:long}/Documentos")] public async Task<IActionResult> Documentos(long id,string titulo,string url,CancellationToken ct){ await _service.RegistrarAcaoAsync("EDITAL_DOCUMENTO_REGISTRAR","edital_documento",id.ToString(),new{titulo,url},HttpContext.TraceIdentifier,ct); TempData["Warning"]="Documento registrado apenas se storage/tabela estiver disponível; URL/texto aceito como fallback honesto."; return Redirect($"/Editais/{id}/Documentos"); }
}

[Authorize]
public sealed class RequisitosEditalController : Controller
{ private readonly EditalPocService _service; public RequisitosEditalController(EditalPocService service)=>_service=service;
    [HttpGet("/Editais/{editalId:long}/Requisitos")] public async Task<IActionResult> Index(long editalId,CancellationToken ct)=>View("~/Views/Editais/Requisitos/Index.cshtml", await _service.ObterDetalheAsync(editalId,ct));
    [HttpGet("/Editais/{editalId:long}/Requisitos/Novo")] public IActionResult Novo(long editalId)=>View("~/Views/Editais/Requisitos/Novo.cshtml", new RequisitoFormViewModel());
    [HttpPost("/Editais/{editalId:long}/Requisitos/Novo")] public async Task<IActionResult> Novo(long editalId,RequisitoFormViewModel form,CancellationToken ct){ if(form.StatusAderencia=="Atende"){form.StatusAderencia="Não avaliado"; TempData["Warning"]="Status Atende bloqueado sem evidência validada.";} await _service.RegistrarAcaoAsync("REQUISITO_CRIAR_SOLICITADO","edital_requisito",null,new{editalId,form},HttpContext.TraceIdentifier,ct); return Redirect($"/Editais/{editalId}/Requisitos"); }
    [HttpGet("/Editais/{editalId:long}/Requisitos/{id:long}")] public async Task<IActionResult> Detalhe(long editalId,long id,CancellationToken ct)=>View("~/Views/Editais/Requisitos/Index.cshtml",await _service.ObterDetalheAsync(editalId,ct));
    [HttpGet("/Editais/{editalId:long}/Requisitos/{id:long}/Editar")] public IActionResult Editar(long editalId,long id)=>View("~/Views/Editais/Requisitos/Novo.cshtml",new RequisitoFormViewModel());
    [HttpPost("/Editais/{editalId:long}/Requisitos/{id:long}/Editar")] public async Task<IActionResult> Editar(long editalId,long id,RequisitoFormViewModel form,CancellationToken ct){ await _service.RegistrarAcaoAsync("REQUISITO_EDITAR_SOLICITADO","edital_requisito",id.ToString(),form,HttpContext.TraceIdentifier,ct); return Redirect($"/Editais/{editalId}/Requisitos"); }
    [HttpPost("/Editais/{editalId:long}/Requisitos/{id:long}/Arquivar")] public async Task<IActionResult> Arquivar(long editalId,long id,CancellationToken ct){ await _service.RegistrarAcaoAsync("REQUISITO_ARQUIVAR_SOLICITADO","edital_requisito",id.ToString(),new{editalId,id},HttpContext.TraceIdentifier,ct); return Redirect($"/Editais/{editalId}/Requisitos"); }
    [HttpPost("/Editais/{editalId:long}/Requisitos/Importar")] public async Task<IActionResult> Importar(long editalId,string csv,CancellationToken ct){ await _service.RegistrarAcaoAsync("REQUISITO_IMPORTAR_CSV_SOLICITADO","edital_requisito",editalId.ToString(),new{linhas=csv?.Split('\n').Length??0},HttpContext.TraceIdentifier,ct); TempData["Warning"]="CSV recebido para validação; persistência depende do schema real."; return Redirect($"/Editais/{editalId}/Requisitos"); }}

[Authorize] public sealed class MatrizAderenciaController:Controller { private readonly EditalPocService _service; public MatrizAderenciaController(EditalPocService service)=>_service=service; [HttpGet("/MatrizAderencia")] public async Task<IActionResult> Index(CancellationToken ct)=>View(await _service.ObterDetalheAsync(1,ct)); [HttpGet("/MatrizAderencia/Edital/{editalId:long}")] public async Task<IActionResult> Edital(long editalId,CancellationToken ct)=>View("Index",await _service.ObterDetalheAsync(editalId,ct)); [HttpGet("/MatrizAderencia/Edital/{editalId:long}/Resumo")] public async Task<IActionResult> Resumo(long editalId,CancellationToken ct)=>Json((await _service.ObterDetalheAsync(editalId,ct)).Resumo); [HttpPost("/MatrizAderencia/Requisito/{id:long}/AtualizarStatus")] public async Task<IActionResult> AtualizarStatus(long id,string status,CancellationToken ct){ if(status=="Atende"){TempData["Warning"]="Atende exige evidência validada; atualização bloqueada em fallback.";} await _service.RegistrarAcaoAsync("MATRIZ_STATUS_SOLICITADO","edital_matriz_aderencia",id.ToString(),new{status},HttpContext.TraceIdentifier,ct); return Redirect("/MatrizAderencia");} [HttpPost("/MatrizAderencia/Requisito/{id:long}/VincularModulo")] public async Task<IActionResult> VincularModulo(long id,string modulo,CancellationToken ct){await _service.RegistrarAcaoAsync("MATRIZ_MODULO_VINCULADO","edital_requisito_modulo",id.ToString(),new{modulo},HttpContext.TraceIdentifier,ct);return Redirect("/MatrizAderencia");} [HttpPost("/MatrizAderencia/Requisito/{id:long}/AdicionarObservacao")] public async Task<IActionResult> AdicionarObservacao(long id,string observacao,CancellationToken ct){await _service.RegistrarAcaoAsync("MATRIZ_OBSERVACAO","edital_matriz_aderencia",id.ToString(),new{observacao},HttpContext.TraceIdentifier,ct);return Redirect("/MatrizAderencia");}}

[Authorize] public sealed class EvidenciasController:Controller { private readonly EditalPocService _service; public EvidenciasController(EditalPocService service)=>_service=service; [HttpGet("/Editais/{editalId:long}/Evidencias")] public async Task<IActionResult> Index(long editalId,CancellationToken ct)=>View("~/Views/Editais/Evidencias/Index.cshtml", await _service.ObterDetalheAsync(editalId,ct)); [HttpGet("/Editais/{editalId:long}/Requisitos/{requisitoId:long}/Evidencias")] public async Task<IActionResult> PorRequisito(long editalId,long requisitoId,CancellationToken ct)=>View("~/Views/Editais/Evidencias/Index.cshtml",await _service.ObterDetalheAsync(editalId,ct)); [HttpPost("/Editais/{editalId:long}/Requisitos/{requisitoId:long}/Evidencias/Nova")] public async Task<IActionResult> Nova(long editalId,long requisitoId,EvidenciaFormViewModel form,CancellationToken ct){await _service.RegistrarAcaoAsync("EVIDENCIA_NOVA_SOLICITADA","edital_evidencia",null,new{editalId,requisitoId,form},HttpContext.TraceIdentifier,ct);TempData["Success"]="Evidência textual/URL auditada; upload não é obrigatório.";return Redirect($"/Editais/{editalId}/Evidencias");} [HttpGet("/Editais/Evidencias/{id:long}")] public IActionResult Detalhe(long id)=>Redirect("/Editais/1/Evidencias"); [HttpPost("/Editais/Evidencias/{id:long}/Aprovar")] public async Task<IActionResult> Aprovar(long id,CancellationToken ct){await _service.RegistrarAcaoAsync("EVIDENCIA_APROVAR_SOLICITADA","edital_evidencia",id.ToString(),new{id},HttpContext.TraceIdentifier,ct);TempData["Warning"]="Aprovação exige permissão e persistência real; operação auditada.";return Redirect("/Editais/1/Evidencias");} [HttpPost("/Editais/Evidencias/{id:long}/Reprovar")] public async Task<IActionResult> Reprovar(long id,CancellationToken ct){await _service.RegistrarAcaoAsync("EVIDENCIA_REPROVAR_SOLICITADA","edital_evidencia",id.ToString(),new{id},HttpContext.TraceIdentifier,ct);return Redirect("/Editais/1/Evidencias");}}

[Authorize] public sealed class PocEditalController:Controller { private readonly EditalPocService _service; public PocEditalController(EditalPocService service)=>_service=service; [HttpGet("/Poc/Editais")] public async Task<IActionResult> Index(CancellationToken ct)=>View(await _service.ObterDetalheAsync(1,ct)); [HttpGet("/Poc/Editais/{editalId:long}")] public async Task<IActionResult> Detalhe(long editalId,CancellationToken ct)=>View("Index",await _service.ObterDetalheAsync(editalId,ct)); [HttpGet("/Poc/Editais/{editalId:long}/Roteiro")] public async Task<IActionResult> Roteiro(long editalId,CancellationToken ct)=>View("Roteiro",await _service.ObterDetalheAsync(editalId,ct)); [HttpPost("/Poc/Editais/{editalId:long}/GerarRoteiro")] public async Task<IActionResult> GerarRoteiro(long editalId,CancellationToken ct){await _service.RegistrarAcaoAsync("POC_ROTEIRO_GERAR","edital_poc_roteiro",editalId.ToString(),new{editalId},HttpContext.TraceIdentifier,ct);return Redirect($"/Poc/Editais/{editalId}/Roteiro");} [HttpGet("/Poc/Editais/{editalId:long}/Execucao")] public async Task<IActionResult> Execucao(long editalId,CancellationToken ct)=>View("Execucao",await _service.ObterDetalheAsync(editalId,ct)); [HttpPost("/Poc/Editais/{editalId:long}/Execucao/Iniciar")] public async Task<IActionResult> Iniciar(long editalId,CancellationToken ct){await _service.RegistrarAcaoAsync("POC_EXECUCAO_INICIAR","edital_poc_execucao",editalId.ToString(),new{editalId},HttpContext.TraceIdentifier,ct);return Redirect($"/Poc/Editais/{editalId}/Execucao");} [HttpPost("/Poc/Editais/{editalId:long}/Execucao/Item/{itemId:long}/Atende")] public async Task<IActionResult> Atende(long editalId,long itemId,CancellationToken ct){await _service.RegistrarAcaoAsync("POC_ITEM_ATENDE_SOLICITADO","edital_poc_item",itemId.ToString(),new{editalId,itemId},HttpContext.TraceIdentifier,ct);TempData["Warning"]="POC não será aprovada se houver crítico não atendido ou sem evidência.";return Redirect($"/Poc/Editais/{editalId}/Execucao");} [HttpPost("/Poc/Editais/{editalId:long}/Execucao/Item/{itemId:long}/NaoAtende")] public async Task<IActionResult> NaoAtende(long editalId,long itemId,CancellationToken ct){await _service.RegistrarAcaoAsync("POC_ITEM_NAO_ATENDE","edital_poc_item",itemId.ToString(),new{editalId,itemId},HttpContext.TraceIdentifier,ct);return Redirect($"/Poc/Editais/{editalId}/Execucao");} [HttpPost("/Poc/Editais/{editalId:long}/Execucao/Finalizar")] public async Task<IActionResult> Finalizar(long editalId,CancellationToken ct){await _service.RegistrarAcaoAsync("POC_FINALIZAR_SOLICITADO","edital_poc_execucao",editalId.ToString(),new{editalId},HttpContext.TraceIdentifier,ct);TempData["Warning"]="Finalização não aprova POC automaticamente.";return Redirect($"/Poc/Editais/{editalId}");}}

[Authorize] public sealed class RelatorioAderenciaController:Controller { private readonly EditalPocService _service; public RelatorioAderenciaController(EditalPocService service)=>_service=service; [HttpGet("/Editais/{editalId:long}/RelatorioAderencia")] public async Task<IActionResult> Index(long editalId,CancellationToken ct)=>View(await _service.ObterDetalheAsync(editalId,ct)); [HttpGet("/Editais/{editalId:long}/RelatorioAderencia/Html")] public async Task<IActionResult> Html(long editalId,CancellationToken ct)=>View("Index",await _service.ObterDetalheAsync(editalId,ct)); [HttpGet("/Editais/{editalId:long}/RelatorioAderencia/Csv")] public async Task<IActionResult> Csv(long editalId,CancellationToken ct){var d=await _service.ObterDetalheAsync(editalId,ct); await _service.RegistrarAcaoAsync("RELATORIO_ADERENCIA_CSV","edital_relatorio_tecnico",editalId.ToString(),new{editalId},HttpContext.TraceIdentifier,ct); var csv="codigo;descricao;status;evidencias\n"+string.Join('\n',d.Requisitos.Select(r=>$"{r.Codigo};{r.Descricao.Replace(';',',')};{r.StatusAderencia};{r.Evidencias}"))+"\n"; return File(new UTF8Encoding(true).GetBytes(csv),"text/csv; charset=utf-8","relatorio-aderencia.csv");} [HttpGet("/Editais/{editalId:long}/RelatorioAderencia/Json")] public async Task<IActionResult> JsonReport(long editalId,CancellationToken ct)=>Json(await _service.ObterDetalheAsync(editalId,ct)); [HttpGet("/Editais/{editalId:long}/RelatorioAderencia/Pdf")] public IActionResult Pdf(long editalId)=>Content("Exportação PDF em implantação; use HTML/CSV/JSON reais.");}

[Authorize] public sealed class PropostaTecnicaController:Controller { private readonly EditalPocService _service; public PropostaTecnicaController(EditalPocService service)=>_service=service; [HttpGet("/Editais/{editalId:long}/PropostaTecnica")] public async Task<IActionResult> Index(long editalId,CancellationToken ct)=>View(await _service.ObterDetalheAsync(editalId,ct)); [HttpPost("/Editais/{editalId:long}/PropostaTecnica/Gerar")] public async Task<IActionResult> Gerar(long editalId,CancellationToken ct){await _service.RegistrarAcaoAsync("PROPOSTA_TECNICA_GERAR","proposta_tecnica",editalId.ToString(),new{editalId},HttpContext.TraceIdentifier,ct);return Redirect($"/Editais/{editalId}/PropostaTecnica/Html");} [HttpGet("/Editais/{editalId:long}/PropostaTecnica/Html")] public async Task<IActionResult> Html(long editalId,CancellationToken ct)=>View("Index",await _service.ObterDetalheAsync(editalId,ct)); [HttpGet("/Editais/{editalId:long}/PropostaTecnica/Docx")] public IActionResult Docx(long editalId)=>Content("Exportação avançada DOCX em implantação; HTML/Markdown real disponível."); [HttpGet("/Editais/{editalId:long}/PropostaTecnica/Pdf")] public IActionResult Pdf(long editalId)=>Content("Exportação avançada PDF em implantação; HTML/Markdown real disponível.");}
