using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Sigov.Application.Empresarial;
namespace Sigov.Web.Controllers; [Authorize] public sealed class EmpresarialEstoqueController:Controller { private readonly IEmpresarialService _service; public EmpresarialEstoqueController(IEmpresarialEstoqueService service)=>_service=service;
[Route("/Empresarial/Estoque/Dashboard")] public async Task<IActionResult> Dashboard(CancellationToken ct){var r=await _service.DashboardAsync("emp_estoque_produto",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Estoque — Dashboard";return View("~/Views/Empresarial/Module.cshtml",r.Value);}
[Route("/Empresarial/Estoque/Produtos")] public async Task<IActionResult> Produtos(CancellationToken ct){var r=await _service.DashboardAsync("emp_estoque_produto",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Estoque — Produtos";return View("~/Views/Empresarial/Module.cshtml",r.Value);}
[Route("/Empresarial/Estoque/ProdutoDetalhe")] public async Task<IActionResult> ProdutoDetalhe(CancellationToken ct){var r=await _service.DashboardAsync("emp_estoque_produto",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Estoque — ProdutoDetalhe";return View("~/Views/Empresarial/Module.cshtml",r.Value);}
[Route("/Empresarial/Estoque/Almoxarifados")] public async Task<IActionResult> Almoxarifados(CancellationToken ct){var r=await _service.DashboardAsync("emp_estoque_produto",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Estoque — Almoxarifados";return View("~/Views/Empresarial/Module.cshtml",r.Value);}
[Route("/Empresarial/Estoque/Saldos")] public async Task<IActionResult> Saldos(CancellationToken ct){var r=await _service.DashboardAsync("emp_estoque_produto",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Estoque — Saldos";return View("~/Views/Empresarial/Module.cshtml",r.Value);}
[Route("/Empresarial/Estoque/Movimentos")] public async Task<IActionResult> Movimentos(CancellationToken ct){var r=await _service.DashboardAsync("emp_estoque_produto",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Estoque — Movimentos";return View("~/Views/Empresarial/Module.cshtml",r.Value);}
[Route("/Empresarial/Estoque/Requisicoes")] public async Task<IActionResult> Requisicoes(CancellationToken ct){var r=await _service.DashboardAsync("emp_estoque_produto",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Estoque — Requisicoes";return View("~/Views/Empresarial/Module.cshtml",r.Value);}
[Route("/Empresarial/Estoque/Inventarios")] public async Task<IActionResult> Inventarios(CancellationToken ct){var r=await _service.DashboardAsync("emp_estoque_produto",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Estoque — Inventarios";return View("~/Views/Empresarial/Module.cshtml",r.Value);}
[Route("/Empresarial/Estoque/Fornecedores")] public async Task<IActionResult> Fornecedores(CancellationToken ct){var r=await _service.DashboardAsync("emp_estoque_produto",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Estoque — Fornecedores";return View("~/Views/Empresarial/Module.cshtml",r.Value);}
[Route("/Empresarial/Estoque/Compras")] public async Task<IActionResult> Compras(CancellationToken ct){var r=await _service.DashboardAsync("emp_estoque_produto",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Estoque — Compras";return View("~/Views/Empresarial/Module.cshtml",r.Value);}
[Route("/Empresarial/Estoque/Relatorios")] public async Task<IActionResult> Relatorios(CancellationToken ct){var r=await _service.DashboardAsync("emp_estoque_produto",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Estoque — Relatorios";return View("~/Views/Empresarial/Module.cshtml",r.Value);}
}