using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Sigov.Application.Empresarial;
namespace Sigov.Web.Controllers; [Authorize] public sealed class EmpresarialComercialController:Controller { private readonly IEmpresarialService _service; public EmpresarialComercialController(IEmpresarialComercialService service)=>_service=service;
[Route("/Empresarial/Comercial/Dashboard")] public async Task<IActionResult> Dashboard(CancellationToken ct){var r=await _service.DashboardAsync("emp_comercial_cliente",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Comercial — Dashboard";return View("~/Views/Empresarial/Module.cshtml",r.Value);}
[Route("/Empresarial/Comercial/Clientes")] public async Task<IActionResult> Clientes(CancellationToken ct){var r=await _service.DashboardAsync("emp_comercial_cliente",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Comercial — Clientes";return View("~/Views/Empresarial/Module.cshtml",r.Value);}
[Route("/Empresarial/Comercial/ClienteDetalhe")] public async Task<IActionResult> ClienteDetalhe(CancellationToken ct){var r=await _service.DashboardAsync("emp_comercial_cliente",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Comercial — ClienteDetalhe";return View("~/Views/Empresarial/Module.cshtml",r.Value);}
[Route("/Empresarial/Comercial/Leads")] public async Task<IActionResult> Leads(CancellationToken ct){var r=await _service.DashboardAsync("emp_comercial_cliente",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Comercial — Leads";return View("~/Views/Empresarial/Module.cshtml",r.Value);}
[Route("/Empresarial/Comercial/Oportunidades")] public async Task<IActionResult> Oportunidades(CancellationToken ct){var r=await _service.DashboardAsync("emp_comercial_cliente",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Comercial — Oportunidades";return View("~/Views/Empresarial/Module.cshtml",r.Value);}
[Route("/Empresarial/Comercial/Funil")] public async Task<IActionResult> Funil(CancellationToken ct){var r=await _service.DashboardAsync("emp_comercial_oportunidade",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Comercial — Funil";return View("~/Views/Empresarial/Module.cshtml",r.Value);}
[Route("/Empresarial/Comercial/Propostas")] public async Task<IActionResult> Propostas(CancellationToken ct){var r=await _service.DashboardAsync("emp_comercial_cliente",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Comercial — Propostas";return View("~/Views/Empresarial/Module.cshtml",r.Value);}
[Route("/Empresarial/Comercial/Pedidos")] public async Task<IActionResult> Pedidos(CancellationToken ct){var r=await _service.DashboardAsync("emp_comercial_cliente",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Comercial — Pedidos";return View("~/Views/Empresarial/Module.cshtml",r.Value);}
[Route("/Empresarial/Comercial/TabelasPreco")] public async Task<IActionResult> TabelasPreco(CancellationToken ct){var r=await _service.DashboardAsync("emp_comercial_cliente",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Comercial — TabelasPreco";return View("~/Views/Empresarial/Module.cshtml",r.Value);}
[Route("/Empresarial/Comercial/Relatorios")] public async Task<IActionResult> Relatorios(CancellationToken ct){var r=await _service.DashboardAsync("emp_comercial_cliente",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Comercial — Relatorios";return View("~/Views/Empresarial/Module.cshtml",r.Value);}
}
