using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Sigov.Application.Empresarial;
namespace Sigov.Web.Controllers; [Authorize] public sealed class EmpresarialOrdemServicoController:Controller { private readonly IEmpresarialService _service; public EmpresarialOrdemServicoController(IEmpresarialOrdemServicoService service)=>_service=service;
[Route("/Empresarial/OrdemServico/Dashboard")] public async Task<IActionResult> Dashboard(CancellationToken ct){var r=await _service.DashboardAsync("emp_os_ordem",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="OrdemServico — Dashboard";return View("~/Views/Empresarial/Module.cshtml",r.Value);}
[Route("/Empresarial/OrdemServico/Ordens")] public async Task<IActionResult> Ordens(CancellationToken ct){var r=await _service.DashboardAsync("emp_os_ordem",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="OrdemServico — Ordens";return View("~/Views/Empresarial/Module.cshtml",r.Value);}
[Route("/Empresarial/OrdemServico/OrdemDetalhe")] public async Task<IActionResult> OrdemDetalhe(CancellationToken ct){var r=await _service.DashboardAsync("emp_os_ordem",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="OrdemServico — OrdemDetalhe";return View("~/Views/Empresarial/Module.cshtml",r.Value);}
[Route("/Empresarial/OrdemServico/Agenda")] public async Task<IActionResult> Agenda(CancellationToken ct){var r=await _service.DashboardAsync("emp_os_ordem",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="OrdemServico — Agenda";return View("~/Views/Empresarial/Module.cshtml",r.Value);}
[Route("/Empresarial/OrdemServico/Checklist")] public async Task<IActionResult> Checklist(CancellationToken ct){var r=await _service.DashboardAsync("emp_os_ordem",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="OrdemServico — Checklist";return View("~/Views/Empresarial/Module.cshtml",r.Value);}
[Route("/Empresarial/OrdemServico/Apontamentos")] public async Task<IActionResult> Apontamentos(CancellationToken ct){var r=await _service.DashboardAsync("emp_os_ordem",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="OrdemServico — Apontamentos";return View("~/Views/Empresarial/Module.cshtml",r.Value);}
[Route("/Empresarial/OrdemServico/Sla")] public async Task<IActionResult> Sla(CancellationToken ct){var r=await _service.DashboardAsync("emp_os_ordem",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="OrdemServico — Sla";return View("~/Views/Empresarial/Module.cshtml",r.Value);}
[Route("/Empresarial/OrdemServico/Relatorios")] public async Task<IActionResult> Relatorios(CancellationToken ct){var r=await _service.DashboardAsync("emp_os_ordem",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="OrdemServico — Relatorios";return View("~/Views/Empresarial/Module.cshtml",r.Value);}
}