using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Sigov.Application.Empresarial;
namespace Sigov.Web.Controllers; [Authorize] public sealed class EmpresarialIndustrialController:Controller { private readonly IEmpresarialService _service; public EmpresarialIndustrialController(IEmpresarialIndustrialService service)=>_service=service;
[Route("/Empresarial/Industrial/Dashboard")] public async Task<IActionResult> Dashboard(CancellationToken ct){var r=await _service.DashboardAsync("emp_industrial_ativo",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Industrial — Dashboard";return View("~/Views/Empresarial/Module.cshtml",r.Value);}
[Route("/Empresarial/Industrial/Ativos")] public async Task<IActionResult> Ativos(CancellationToken ct){var r=await _service.DashboardAsync("emp_industrial_ativo",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Industrial — Ativos";return View("~/Views/Empresarial/Module.cshtml",r.Value);}
[Route("/Empresarial/Industrial/AtivoDetalhe")] public async Task<IActionResult> AtivoDetalhe(CancellationToken ct){var r=await _service.DashboardAsync("emp_industrial_ativo",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Industrial — AtivoDetalhe";return View("~/Views/Empresarial/Module.cshtml",r.Value);}
[Route("/Empresarial/Industrial/PlanosManutencao")] public async Task<IActionResult> PlanosManutencao(CancellationToken ct){var r=await _service.DashboardAsync("emp_industrial_ativo",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Industrial — PlanosManutencao";return View("~/Views/Empresarial/Module.cshtml",r.Value);}
[Route("/Empresarial/Industrial/Programadas")] public async Task<IActionResult> Programadas(CancellationToken ct){var r=await _service.DashboardAsync("emp_industrial_ativo",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Industrial — Programadas";return View("~/Views/Empresarial/Module.cshtml",r.Value);}
[Route("/Empresarial/Industrial/Medidores")] public async Task<IActionResult> Medidores(CancellationToken ct){var r=await _service.DashboardAsync("emp_industrial_ativo",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Industrial — Medidores";return View("~/Views/Empresarial/Module.cshtml",r.Value);}
[Route("/Empresarial/Industrial/Paradas")] public async Task<IActionResult> Paradas(CancellationToken ct){var r=await _service.DashboardAsync("emp_industrial_ativo",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Industrial — Paradas";return View("~/Views/Empresarial/Module.cshtml",r.Value);}
[Route("/Empresarial/Industrial/Producao")] public async Task<IActionResult> Producao(CancellationToken ct){var r=await _service.DashboardAsync("emp_industrial_ativo",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Industrial — Producao";return View("~/Views/Empresarial/Module.cshtml",r.Value);}
[Route("/Empresarial/Industrial/Qualidade")] public async Task<IActionResult> Qualidade(CancellationToken ct){var r=await _service.DashboardAsync("emp_industrial_ativo",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Industrial — Qualidade";return View("~/Views/Empresarial/Module.cshtml",r.Value);}
[Route("/Empresarial/Industrial/Relatorios")] public async Task<IActionResult> Relatorios(CancellationToken ct){var r=await _service.DashboardAsync("emp_industrial_ativo",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Industrial — Relatorios";return View("~/Views/Empresarial/Module.cshtml",r.Value);}
}