using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Sigov.Application.Energia;

namespace Sigov.Web.Controllers;

[Authorize,Route("Energia")]
public sealed class EnergiaController(IEnergiaRepository repository,IAuthorizationService authorization,ILogger<EnergiaController> logger):Controller
{
 private static readonly IReadOnlyDictionary<string,(string Title,string View,string Manage)> Resources=new Dictionary<string,(string,string,string)>(StringComparer.OrdinalIgnoreCase){
  ["unidades-consumidoras"]=("Unidades consumidoras","ENERGIA_UNIDADE_VIEW","ENERGIA_UNIDADE_MANAGE"),["medidores"]=("Medidores","ENERGIA_UNIDADE_VIEW","ENERGIA_MEDIDOR_MANAGE"),["leituras"]=("Leituras e consumo","ENERGIA_UNIDADE_VIEW","ENERGIA_LEITURA_MANAGE"),["faturas"]=("Faturas de energia","ENERGIA_FATURA_VIEW","ENERGIA_FATURA_MANAGE"),["contratos"]=("Contratos de fornecimento","ENERGIA_CONTRATO_VIEW","ENERGIA_CONTRATO_MANAGE"),["demanda"]=("Demanda contratada x medida","ENERGIA_DEMANDA_VIEW","ENERGIA_CONTRATO_MANAGE"),["pontos"]=("Pontos de iluminação","ENERGIA_ILUMINACAO_VIEW","ENERGIA_ILUMINACAO_MANAGE"),["chamados"]=("Chamados de iluminação","ENERGIA_ILUMINACAO_VIEW","ENERGIA_ILUMINACAO_MANAGE"),["ordens-servico"]=("Ordens de serviço","ENERGIA_ILUMINACAO_VIEW","ENERGIA_ILUMINACAO_MANAGE"),["manutencoes"]=("Manutenções","ENERGIA_ILUMINACAO_VIEW","ENERGIA_ILUMINACAO_MANAGE"),["geracao-distribuida"]=("Geração distribuída","ENERGIA_GERACAO_VIEW","ENERGIA_GERACAO_MANAGE"),["creditos"]=("Créditos e compensações","ENERGIA_GERACAO_VIEW","ENERGIA_CREDITO_MANAGE"),["eficiencia"]=("Eficiência energética","ENERGIA_DASHBOARD_VIEW","ENERGIA_EFICIENCIA_MANAGE"),["alertas"]=("Alertas e anomalias","ENERGIA_ALERTA_VIEW","ENERGIA_ALERTA_MANAGE")};
 [HttpGet(""),HttpGet("Dashboard"),Authorize(Policy="ENERGIA_DASHBOARD_VIEW")]
 public async Task<IActionResult> Dashboard(string? status,DateOnly? inicio,DateOnly? fim,CancellationToken ct)=>View(await repository.DashboardAsync(Contexto(),new(null,status,inicio,fim),ct));
 [HttpGet("UnidadesConsumidoras"),HttpGet("Medidores"),HttpGet("Leituras"),HttpGet("Faturas"),HttpGet("Contratos"),HttpGet("Demanda"),HttpGet("Iluminacao"),HttpGet("Iluminacao/Pontos"),HttpGet("Iluminacao/Chamados"),HttpGet("Iluminacao/OrdensServico"),HttpGet("Iluminacao/Manutencoes"),HttpGet("GeracaoDistribuida"),HttpGet("Creditos"),HttpGet("Eficiencia"),HttpGet("Alertas")]
 public async Task<IActionResult> Lista(string? busca,string? status,CancellationToken ct){var recurso=RecursoRota();var m=Meta(recurso);if(!await Permitido(m.View))return Forbid();ViewData["Recurso"]=recurso;ViewData["Titulo"]=m.Title;return View("Lista",await repository.ListarAsync(Contexto(),recurso,new(busca,status),ct));}
 [HttpGet("{area:regex(^UnidadesConsumidoras|Medidores|Faturas|GeracaoDistribuida|Eficiencia$)}/Create")]
 public async Task<IActionResult> Create(string area,CancellationToken ct){var recurso=Normalizar(area);if(!await Permitido(Meta(recurso).Manage))return Forbid();await Preparar(recurso,ct);return View("Form",new EnergiaRegistroRequest());}
 [HttpGet("{area:regex(^UnidadesConsumidoras|Medidores|Faturas|GeracaoDistribuida|Eficiencia$)}/Edit/{id:long}")]
 public async Task<IActionResult> Edit(string area,long id,CancellationToken ct){var recurso=Normalizar(area);if(!await Permitido(Meta(recurso).Manage))return Forbid();var x=await repository.ObterAsync(Contexto(),recurso,id,ct);if(x is null)return NotFound();await Preparar(recurso,ct);ViewData["Id"]=id;return View("Form",new EnergiaRegistroRequest{Codigo=x.Codigo,Descricao=x.Descricao,Status=x.Status,Valor=x.Valor,Data=x.Data,UnidadeConsumidoraId=x.UnidadeConsumidoraId});}
 [HttpGet("{area:regex(^UnidadesConsumidoras|Medidores|Faturas|GeracaoDistribuida|Eficiencia|Alertas$)}/Details/{id:long}")]
 public async Task<IActionResult> Details(string area,long id,CancellationToken ct){var recurso=Normalizar(area);if(!await Permitido(Meta(recurso).View))return Forbid();var x=await repository.ObterAsync(Contexto(),recurso,id,ct);return x is null?NotFound():View("Details",x);}
 [HttpPost("{area:regex(^UnidadesConsumidoras|Medidores|Faturas|GeracaoDistribuida|Eficiencia$)}/Save"),ValidateAntiForgeryToken]
 public async Task<IActionResult> Save(string area,EnergiaRegistroRequest model,long? id,CancellationToken ct){var recurso=Normalizar(area);if(!await Permitido(Meta(recurso).Manage))return Forbid();if(ModelState.IsValid)try{var saved=await repository.SalvarAsync(Contexto(),recurso,model,id,ct);TempData["Success"]="Registro salvo com rastreabilidade.";return RedirectToAction(nameof(Details),new{area,id=saved});}catch(Exception ex) when(ex is ArgumentException or InvalidOperationException or Npgsql.PostgresException){logger.LogWarning(ex,"Validação Energia360 {CorrelationId}",HttpContext.TraceIdentifier);ModelState.AddModelError("",ex.Message);}await Preparar(recurso,ct);ViewData["Id"]=id;return View("Form",model);}
 [HttpPost("Faturas/Conferir/{id:long}"),ValidateAntiForgeryToken,Authorize(Policy="ENERGIA_FATURA_CONFERIR")]public Task<IActionResult> Conferir(long id,CancellationToken ct)=>MudarFatura(id,"CONFERIDA",null,ct);
 [HttpPost("Faturas/Contestar/{id:long}"),ValidateAntiForgeryToken,Authorize(Policy="ENERGIA_FATURA_MANAGE")]public Task<IActionResult> Contestar(long id,string justificativa,CancellationToken ct)=>MudarFatura(id,"CONTESTADA",justificativa,ct);
 [HttpGet("Relatorios/{recurso}.csv"),Authorize(Policy="ENERGIA_RELATORIO_EXPORT")]public async Task<IActionResult> Csv(string recurso,string? busca,string? status,CancellationToken ct)=>File(await repository.ExportarCsvAsync(Contexto(),recurso,new(busca,status),ct),"text/csv; charset=utf-8",$"energia-{recurso}-{DateTime.UtcNow:yyyyMMdd}.csv");
 private async Task<IActionResult> MudarFatura(long id,string status,string? justificativa,CancellationToken ct){var x=await repository.ObterAsync(Contexto(),"faturas",id,ct)??throw new KeyNotFoundException();await repository.SalvarAsync(Contexto(),"faturas",new(){Codigo=x.Codigo,Descricao=x.Descricao,Status=status,Valor=x.Valor,Data=x.Data,UnidadeConsumidoraId=x.UnidadeConsumidoraId,Justificativa=justificativa},id,ct);return RedirectToAction(nameof(Details),new{area="Faturas",id});}
 private async Task Preparar(string recurso,CancellationToken ct){ViewData["Recurso"]=recurso;ViewData["Titulo"]=Meta(recurso).Title;ViewBag.Unidades=new SelectList(await repository.OpcoesAsync(Contexto(),"uc",ct),"Id","Texto");if(recurso=="unidades-consumidoras"){ViewBag.Concessionarias=new SelectList(await repository.OpcoesAsync(Contexto(),"concessionaria",ct),"Id","Texto");ViewBag.UnidadesOrganizacionais=new SelectList(await repository.OpcoesAsync(Contexto(),"unidade",ct),"Id","Texto");ViewBag.Contratos=new SelectList(await repository.OpcoesAsync(Contexto(),"contrato",ct),"Id","Texto");}}
 private static string Normalizar(string area)=>area.ToLowerInvariant() switch{"unidadesconsumidoras"=>"unidades-consumidoras","geracaodistribuida"=>"geracao-distribuida",_=>area.ToLowerInvariant()};
 private string RecursoRota(){var p=Request.Path.Value?.ToLowerInvariant()??"";if(p.EndsWith("/iluminacao"))return "pontos";return p.Split('/',StringSplitOptions.RemoveEmptyEntries).Last() switch{"unidadesconsumidoras"=>"unidades-consumidoras","ordensservico"=>"ordens-servico","geracaodistribuida"=>"geracao-distribuida",var x=>x};}
 private static (string Title,string View,string Manage) Meta(string r)=>Resources.TryGetValue(r,out var m)?m:throw new ArgumentException("Recurso inválido.");
 private async Task<bool> Permitido(string p)=>(await authorization.AuthorizeAsync(User,p)).Succeeded;
 private EnergiaContexto Contexto(){if(!long.TryParse(User.FindFirst("tenant_id")?.Value,out var t)||!long.TryParse(User.FindFirst("entidade_id")?.Value,out var e)||t<=0||e<=0)throw new UnauthorizedAccessException("Tenant e entidade são obrigatórios.");long.TryParse(User.FindFirst("sub")?.Value,out var u);return new(t,e,u>0?u:null,HttpContext.TraceIdentifier,HttpContext.Connection.RemoteIpAddress?.ToString());}
}
