using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Sigov.Application.Habitacao;
using Sigov.Web.Models.Habitacao;
namespace Sigov.Web.Controllers;
[Authorize,Route("Habitacao")]
public sealed class HabitacaoController(IHabitacaoRepository repository,IAuthorizationService authorization,ILogger<HabitacaoController> logger):Controller
{
 private static readonly IReadOnlyDictionary<string,(string Title,string View,string Manage)> Resources=new Dictionary<string,(string,string,string)>(StringComparer.OrdinalIgnoreCase){["familias"]=("Famílias","HABITACAO_FAMILIA_VIEW","HABITACAO_FAMILIA_MANAGE"),["membros"]=("Membros familiares","HABITACAO_FAMILIA_VIEW","HABITACAO_FAMILIA_MANAGE"),["domicilios"]=("Domicílios","HABITACAO_DOMICILIO_VIEW","HABITACAO_DOMICILIO_MANAGE"),["programas"]=("Programas habitacionais","HABITACAO_PROGRAMA_VIEW","HABITACAO_PROGRAMA_MANAGE"),["inscricoes"]=("Inscrições","HABITACAO_INSCRICAO_VIEW","HABITACAO_INSCRICAO_MANAGE"),["classificacao"]=("Classificação","HABITACAO_CLASSIFICACAO_VIEW","HABITACAO_CLASSIFICACAO_MANAGE"),["visitas"]=("Visitas sociais e técnicas","HABITACAO_VISITA_VIEW","HABITACAO_VISITA_MANAGE"),["regularizacao"]=("Regularização fundiária","HABITACAO_REGULARIZACAO_VIEW","HABITACAO_REGULARIZACAO_MANAGE"),["nucleos"]=("Núcleos urbanos","HABITACAO_REGULARIZACAO_VIEW","HABITACAO_REGULARIZACAO_MANAGE"),["lotes"]=("Lotes","HABITACAO_LOTE_VIEW","HABITACAO_LOTE_MANAGE"),["unidades"]=("Unidades habitacionais","HABITACAO_UNIDADE_VIEW","HABITACAO_UNIDADE_MANAGE"),["beneficiarios"]=("Beneficiários e termos","HABITACAO_BENEFICIARIO_VIEW","HABITACAO_BENEFICIARIO_MANAGE"),["auditoria"]=("Auditoria","HABITACAO_AUDITORIA_VIEW","HABITACAO_AUDITORIA_VIEW")};
 [HttpGet(""),HttpGet("Dashboard"),Authorize(Policy="HABITACAO_DASHBOARD_VIEW")]public async Task<IActionResult> Index(CancellationToken ct)=>View("Dashboard",await repository.DashboardAsync(Context(),ct));
 [HttpGet("{recurso:regex(^Familias|Membros|Domicilios|Programas|Inscricoes|Classificacao|Visitas|Regularizacao|Nucleos|Lotes|Unidades|Beneficiarios|Auditoria$)}")]public async Task<IActionResult> Lista(string recurso,string? busca,string? status,int pagina,CancellationToken ct){recurso=recurso.ToLowerInvariant();var m=Meta(recurso);if(!await Allowed(m.View))return Forbid();var f=new HabitacaoFiltro(busca,status,Math.Max(1,pagina));return View("Lista",new HabitacaoListaViewModel(m.Title,recurso,await repository.ListarAsync(Context(),recurso,f,ct),f));}
 [HttpGet("{recurso}/Novo")]public async Task<IActionResult> Novo(string recurso){recurso=recurso.ToLowerInvariant();var m=Meta(recurso);if(!await Allowed(m.Manage))return Forbid();ViewData["Recurso"]=recurso;ViewData["Titulo"]=m.Title;return View("Form",new HabitacaoRegistroRequest("","","ATIVO",null));}
 [HttpPost("{recurso}/Salvar"),ValidateAntiForgeryToken]public async Task<IActionResult> Salvar(string recurso,HabitacaoRegistroRequest model,long? id,CancellationToken ct){recurso=recurso.ToLowerInvariant();var m=Meta(recurso);if(!await Allowed(m.Manage))return Forbid();try{await repository.SalvarAsync(Context(),recurso,model,id,ct);TempData["Success"]="Registro salvo com histórico e auditoria.";return Redirect($"/Habitacao/{Route(recurso)}");}catch(Exception ex)when(ex is ArgumentException or InvalidOperationException or KeyNotFoundException){logger.LogWarning(ex,"Validação de habitação {Recurso} {CorrelationId}",recurso,HttpContext.TraceIdentifier);ModelState.AddModelError("",ex.Message);}catch(Exception ex){logger.LogError(ex,"Falha crítica em habitação {CorrelationId}",HttpContext.TraceIdentifier);ModelState.AddModelError("",$"Não foi possível salvar. Referência: {HttpContext.TraceIdentifier}");}ViewData["Recurso"]=recurso;ViewData["Titulo"]=m.Title;return View("Form",model);}
 [HttpPost("{recurso}/{id:long}/Excluir"),ValidateAntiForgeryToken]public async Task<IActionResult> Excluir(string recurso,long id,string justificativa,CancellationToken ct){recurso=recurso.ToLowerInvariant();var m=Meta(recurso);if(!await Allowed(m.Manage))return Forbid();try{await repository.ExcluirAsync(Context(),recurso,id,justificativa,ct);TempData["Success"]="Exclusão lógica auditada.";}catch(Exception ex){logger.LogError(ex,"Falha ao excluir em habitação {CorrelationId}",HttpContext.TraceIdentifier);TempData["Error"]=ex.Message;}return Redirect($"/Habitacao/{Route(recurso)}");}
 [HttpGet("Relatorios"),Authorize(Policy="HABITACAO_RELATORIO_EXPORT")]public IActionResult Relatorios()=>View();
 [HttpGet("Relatorios/{recurso}.csv"),Authorize(Policy="HABITACAO_RELATORIO_EXPORT")]public async Task<IActionResult> Csv(string recurso,CancellationToken ct){recurso=recurso.ToLowerInvariant();Meta(recurso);return File(await repository.ExportarCsvAsync(Context(),recurso,ct),"text/csv; charset=utf-8",$"habitacao-{recurso}-{DateTime.UtcNow:yyyyMMdd}.csv");}
 private async Task<bool> Allowed(string p)=>(await authorization.AuthorizeAsync(User,p)).Succeeded;
 private static (string Title,string View,string Manage) Meta(string r)=>Resources.TryGetValue(r,out var m)?m:throw new ArgumentException("Recurso inválido.");
 private static string Route(string r)=>char.ToUpperInvariant(r[0])+r[1..];
 private HabitacaoContexto Context(){if(!long.TryParse(User.FindFirst("tenant_id")?.Value,out var t)||t<=0||!long.TryParse(User.FindFirst("entidade_id")?.Value,out var e)||e<=0)throw new UnauthorizedAccessException("Tenant/entidade não resolvidos.");long.TryParse(User.FindFirst("sub")?.Value??User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value,out var u);return new(t,e,u>0?u:null,HttpContext.TraceIdentifier,HttpContext.Connection.RemoteIpAddress?.ToString());}
}
