using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Sigov.Application.Bloco8;
namespace Sigov.Web.Controllers;
[Authorize] public sealed class LegislativoController:Controller { private readonly ILegislativoService _service; public LegislativoController(ILegislativoService service)=>_service=service;
 [Route("/Legislativo")] public async Task<IActionResult> Index(CancellationToken ct){var r=await _service.DashboardAsync("legislativo_proposicao",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Legislativo — Index";return View("~/Views/Bloco8/Module.cshtml",r.Value);}
 [Route("/Legislativo/Dashboard")] public async Task<IActionResult> Dashboard(CancellationToken ct){var r=await _service.DashboardAsync("legislativo_proposicao",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Legislativo — Dashboard";return View("~/Views/Bloco8/Module.cshtml",r.Value);}
 [Route("/Legislativo/Parlamentares")] public async Task<IActionResult> Parlamentares(CancellationToken ct){var r=await _service.DashboardAsync("legislativo_proposicao",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Legislativo — Parlamentares";return View("~/Views/Bloco8/Module.cshtml",r.Value);}
 [Route("/Legislativo/Proposicoes")] public async Task<IActionResult> Proposicoes(CancellationToken ct){var r=await _service.DashboardAsync("legislativo_proposicao",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Legislativo — Proposicoes";return View("~/Views/Bloco8/Module.cshtml",r.Value);}
 [Route("/Legislativo/ProposicaoDetalhe")] public async Task<IActionResult> ProposicaoDetalhe(CancellationToken ct){var r=await _service.DashboardAsync("legislativo_proposicao",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Legislativo — ProposicaoDetalhe";return View("~/Views/Bloco8/Module.cshtml",r.Value);}
 [Route("/Legislativo/Comissoes")] public async Task<IActionResult> Comissoes(CancellationToken ct){var r=await _service.DashboardAsync("legislativo_proposicao",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Legislativo — Comissoes";return View("~/Views/Bloco8/Module.cshtml",r.Value);}
 [Route("/Legislativo/Sessoes")] public async Task<IActionResult> Sessoes(CancellationToken ct){var r=await _service.DashboardAsync("legislativo_proposicao",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Legislativo — Sessoes";return View("~/Views/Bloco8/Module.cshtml",r.Value);}
 [Route("/Legislativo/SessaoDetalhe")] public async Task<IActionResult> SessaoDetalhe(CancellationToken ct){var r=await _service.DashboardAsync("legislativo_proposicao",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Legislativo — SessaoDetalhe";return View("~/Views/Bloco8/Module.cshtml",r.Value);}
 [Route("/Legislativo/Pautas")] public async Task<IActionResult> Pautas(CancellationToken ct){var r=await _service.DashboardAsync("legislativo_proposicao",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Legislativo — Pautas";return View("~/Views/Bloco8/Module.cshtml",r.Value);}
 [Route("/Legislativo/Votacoes")] public async Task<IActionResult> Votacoes(CancellationToken ct){var r=await _service.DashboardAsync("legislativo_proposicao",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Legislativo — Votacoes";return View("~/Views/Bloco8/Module.cshtml",r.Value);}
 [Route("/Legislativo/Atas")] public async Task<IActionResult> Atas(CancellationToken ct){var r=await _service.DashboardAsync("legislativo_proposicao",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Legislativo — Atas";return View("~/Views/Bloco8/Module.cshtml",r.Value);}
 [Route("/Legislativo/Normas")] public async Task<IActionResult> Normas(CancellationToken ct){var r=await _service.DashboardAsync("legislativo_proposicao",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Legislativo — Normas";return View("~/Views/Bloco8/Module.cshtml",r.Value);}
 [Route("/Legislativo/Relatorios")] public async Task<IActionResult> Relatorios(CancellationToken ct){var r=await _service.DashboardAsync("legislativo_proposicao",ct);if(r.IsFailure)return Problem(r.Error);ViewData["Module"]="Legislativo — Relatorios";return View("~/Views/Bloco8/Module.cshtml",r.Value);}
}
