using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Sigov.Application.Ambiental;
using Sigov.Web.Models.Ambiental;
namespace Sigov.Web.Controllers;
[Authorize,Route("MeioAmbiente")]
public sealed class MeioAmbienteController(IAmbientalRepository repository,ILogger<MeioAmbienteController> logger):Controller
{
 private static readonly IReadOnlyDictionary<string,(string Title,string ViewPolicy,string ManagePolicy)> Resources=new Dictionary<string,(string,string,string)>(StringComparer.OrdinalIgnoreCase){["empreendedores"]=("Empreendedores e responsáveis","AMBIENTAL_EMPREENDEDOR_VIEW","AMBIENTAL_EMPREENDEDOR_MANAGE"),["empreendimentos"]=("Empreendimentos e atividades","AMBIENTAL_EMPREENDIMENTO_VIEW","AMBIENTAL_EMPREENDIMENTO_MANAGE"),["parametros"]=("Tipos de licença e parâmetros","AMBIENTAL_PARAMETRO_VIEW","AMBIENTAL_PARAMETRO_MANAGE"),["requerimentos"]=("Requerimentos ambientais","AMBIENTAL_REQUERIMENTO_VIEW","AMBIENTAL_REQUERIMENTO_MANAGE"),["documentos"]=("Documentos e checklist","AMBIENTAL_DOCUMENTO_VIEW","AMBIENTAL_DOCUMENTO_MANAGE"),["analises"]=("Análises técnicas e pareceres","AMBIENTAL_ANALISE_VIEW","AMBIENTAL_ANALISE_MANAGE"),["licencas"]=("Licenças emitidas","AMBIENTAL_LICENCA_VIEW","AMBIENTAL_LICENCA_MANAGE"),["condicionantes"]=("Condicionantes ambientais","AMBIENTAL_CONDICIONANTE_VIEW","AMBIENTAL_CONDICIONANTE_MANAGE"),["vistorias"]=("Vistorias e fiscalização","AMBIENTAL_VISTORIA_VIEW","AMBIENTAL_VISTORIA_MANAGE"),["denuncias"]=("Denúncias e ocorrências","AMBIENTAL_DENUNCIA_VIEW","AMBIENTAL_DENUNCIA_MANAGE"),["autos"]=("Autos, notificações e penalidades","AMBIENTAL_AUTO_VIEW","AMBIENTAL_AUTO_MANAGE"),["taxas"]=("Taxas ambientais","AMBIENTAL_TAXA_VIEW","AMBIENTAL_TAXA_MANAGE"),["auditoria"]=("Auditoria ambiental","AMBIENTAL_AUDITORIA_VIEW","AMBIENTAL_AUDITORIA_VIEW"),["pareceres"]=("Pareceres ambientais","AMBIENTAL_ANALISE_VIEW","AMBIENTAL_ANALISE_MANAGE"),["fiscalizacao"]=("Fiscalização ambiental","AMBIENTAL_VISTORIA_VIEW","AMBIENTAL_VISTORIA_MANAGE"),["autosinfracao"]=("Autos de infração","AMBIENTAL_AUTO_VIEW","AMBIENTAL_AUTO_MANAGE"),["notificacoes"]=("Notificações ambientais","AMBIENTAL_AUTO_VIEW","AMBIENTAL_AUTO_MANAGE"),["embargos"]=("Embargos e interdições","AMBIENTAL_AUTO_VIEW","AMBIENTAL_AUTO_MANAGE"),["recursos"]=("Defesas e recursos","AMBIENTAL_AUTO_VIEW","AMBIENTAL_AUTO_MANAGE")};
 [HttpGet(""),HttpGet("Dashboard"),Authorize(Policy="AMBIENTAL_DASHBOARD_VIEW")]public async Task<IActionResult> Index(string? status,DateOnly? inicio,DateOnly? fim,CancellationToken ct)=>View("Dashboard",await repository.DashboardAsync(Contexto(),new(null,status,inicio,fim),ct));
 [HttpGet("{recurso:regex(^empreendedores|empreendimentos|parametros|requerimentos|documentos|analises|pareceres|licencas|condicionantes|fiscalizacao|vistorias|denuncias|autos|autosinfracao|notificacoes|embargos|recursos|taxas|auditoria$)}")]
 public async Task<IActionResult> Lista(string recurso,string? busca,string? status,int pagina,CancellationToken ct){var meta=Meta(recurso);if(!await Autorizado(meta.ViewPolicy))return Forbid();var f=new AmbientalFiltro(busca,status,Pagina:Math.Max(1,pagina),Tamanho:20);return View("Lista",new AmbientalListaViewModel(meta.Title,recurso,await repository.ListarAsync(Contexto(),recurso,f,ct),f));}
 [HttpGet("Licencas/Create")] public Task<IActionResult> LicencaCreate()=>Novo("licencas");
 [HttpGet("Licencas/Edit")] public Task<IActionResult> LicencaEdit(long id)=>Novo("licencas");
 [HttpGet("Licencas/Details")] public Task<IActionResult> LicencaDetails(long id,CancellationToken ct)=>Lista("licencas",id.ToString(),null,1,ct);
 [HttpGet("{recurso}/Novo")]public async Task<IActionResult> Novo(string recurso){var meta=Meta(recurso);if(!await Autorizado(meta.ManagePolicy))return Forbid();ViewData["Recurso"]=recurso;ViewData["Titulo"]=meta.Title;return View("Form",new AmbientalRegistroRequest("","","ATIVO",null,DateOnly.FromDateTime(DateTime.Today),null));}
 [HttpPost("{recurso}/Salvar"),ValidateAntiForgeryToken]public async Task<IActionResult> Salvar(string recurso,AmbientalRegistroRequest model,long? id,CancellationToken ct){var meta=Meta(recurso);if(!await Autorizado(meta.ManagePolicy))return Forbid();try{await repository.SalvarAsync(Contexto(),recurso,model,id,ct);TempData["Success"]="Registro ambiental salvo e auditado.";return Redirect($"/MeioAmbiente/{recurso}");}catch(Exception ex) when(ex is ArgumentException or InvalidOperationException or KeyNotFoundException){logger.LogWarning(ex,"Validação ambiental em {Recurso} ({CorrelationId})",recurso,HttpContext.TraceIdentifier);ModelState.AddModelError("",ex.Message);ViewData["Recurso"]=recurso;ViewData["Titulo"]=meta.Title;return View("Form",model);}catch(Exception ex){logger.LogError(ex,"Falha ambiental crítica ({CorrelationId})",HttpContext.TraceIdentifier);ModelState.AddModelError("",$"Falha ao persistir. Referência: {HttpContext.TraceIdentifier}");ViewData["Recurso"]=recurso;ViewData["Titulo"]=meta.Title;return View("Form",model);}}
 [HttpPost("{recurso}/{id:long}/Excluir"),ValidateAntiForgeryToken]public async Task<IActionResult> Excluir(string recurso,long id,string justificativa,CancellationToken ct){var meta=Meta(recurso);if(!await Autorizado(meta.ManagePolicy))return Forbid();await repository.ExcluirAsync(Contexto(),recurso,id,justificativa,ct);return Redirect($"/MeioAmbiente/{recurso}");}
 [HttpGet("Relatorios"),Authorize(Policy="AMBIENTAL_RELATORIO_EXPORT")]public IActionResult Relatorios()=>View("Relatorios");
 [HttpGet("Relatorios/{relatorio}.csv"),Authorize(Policy="AMBIENTAL_RELATORIO_EXPORT")]public async Task<IActionResult> Csv(string relatorio,CancellationToken ct)=>File(await repository.ExportarCsvAsync(Contexto(),relatorio,new(null,null),ct),"text/csv; charset=utf-8",$"ambiental-{relatorio}-{DateTime.UtcNow:yyyyMMdd}.csv");
 private (string Title,string ViewPolicy,string ManagePolicy) Meta(string r)=>Resources.TryGetValue(r,out var m)?m:throw new ArgumentException("Recurso inválido.");
 private async Task<bool> Autorizado(string policy)=>(await HttpContext.RequestServices.GetRequiredService<IAuthorizationService>().AuthorizeAsync(User,policy)).Succeeded;
 private AmbientalContexto Contexto(){if(!long.TryParse(User.FindFirst("tenant_id")?.Value,out var t)||t<=0||!long.TryParse(User.FindFirst("entidade_id")?.Value,out var e)||e<=0)throw new UnauthorizedAccessException("Tenant/entidade não resolvidos.");long.TryParse(User.FindFirst("sub")?.Value??User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value,out var u);return new(t,e,u>0?u:null,HttpContext.TraceIdentifier,HttpContext.Connection.RemoteIpAddress?.ToString());}
}
