using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Sigov.Application.Obras.Engenharia;
using Sigov.Web.Models.Obras;
namespace Sigov.Web.Controllers;
[Authorize,Route("Obras")]
public sealed class ObrasController(IObrasEngenhariaRepository repository,IAuthorizationService authorization,ILogger<ObrasController> logger):Controller
{
 [HttpGet(""),HttpGet("Dashboard"),Authorize(Policy="OBRAS_DASHBOARD_VIEW")]
 public async Task<IActionResult> Index([FromQuery]ObrasFiltro? filtro,CancellationToken ct)=>View("Dashboard",await repository.DashboardAsync(Contexto(),filtro??Filtro(),ct));
 [HttpGet("Cadastro"),Authorize(Policy="OBRAS_OBRA_VIEW")]
 public async Task<IActionResult> Cadastro(string? busca,string? status,int pagina,CancellationToken ct)=>View("Cadastro",await repository.ListarObrasAsync(Contexto(),Filtro(busca,status,pagina),ct));
 [HttpGet("Cadastro/Nova"),Authorize(Policy="OBRAS_OBRA_MANAGE")]public IActionResult Nova()=>View("ObraForm",new ObraRequest("","",null,"",null,"",null,null,null,0,0,DateOnly.FromDateTime(DateTime.Today),DateOnly.FromDateTime(DateTime.Today),null,null,"PLANEJADA",null,null,null,null,null));
 [HttpPost("Cadastro/Salvar"),ValidateAntiForgeryToken,Authorize(Policy="OBRAS_OBRA_MANAGE")]
 public async Task<IActionResult> SalvarObra(ObraRequest model,long? id,CancellationToken ct){if(!ModelState.IsValid)return View("ObraForm",model);try{await repository.SalvarObraAsync(Contexto(),model,id,ct);TempData["Success"]="Obra salva com sucesso.";return RedirectToAction(nameof(Cadastro));}catch(ArgumentException ex){ModelState.AddModelError("",ex.Message);}catch(Exception ex){logger.LogError(ex,"Falha ao salvar obra {CorrelationId}",HttpContext.TraceIdentifier);ModelState.AddModelError("",$"Falha ao salvar. Referência: {HttpContext.TraceIdentifier}");}return View("ObraForm",model);}
 [HttpPost("Cadastro/{id:long}/Excluir"),ValidateAntiForgeryToken,Authorize(Policy="OBRAS_OBRA_MANAGE")]public async Task<IActionResult> Excluir(long id,string justificativa,CancellationToken ct){await repository.ExcluirObraAsync(Contexto(),id,justificativa,ct);return RedirectToAction(nameof(Cadastro));}
 [HttpGet("Projetos"),Authorize(Policy="OBRAS_PROJETO_VIEW")]public Task<IActionResult> Projetos(string? busca,string? status,int pagina,CancellationToken ct)=>Lista("Projetos de engenharia","projetos",busca,status,pagina,ct);
 [HttpGet("Orcamentos"),Authorize(Policy="OBRAS_ORCAMENTO_VIEW")]public Task<IActionResult> Orcamentos(string? busca,string? status,int pagina,CancellationToken ct)=>Lista("Orçamentos e itens","orcamentos",busca,status,pagina,ct);
 [HttpGet("Cronogramas"),Authorize(Policy="OBRAS_CRONOGRAMA_VIEW")]public Task<IActionResult> Cronogramas(string? busca,string? status,int pagina,CancellationToken ct)=>Lista("Cronograma físico-financeiro","cronogramas",busca,status,pagina,ct);
 [HttpGet("Medicoes"),Authorize(Policy="OBRAS_MEDICAO_VIEW")]public Task<IActionResult> Medicoes(string? busca,string? status,int pagina,CancellationToken ct)=>Lista("Medições","medicoes",busca,status,pagina,ct);
 [HttpGet("DiarioObra"),HttpGet("Diario"),HttpGet("Diarios"),Authorize(Policy="OBRAS_DIARIO_VIEW")]public Task<IActionResult> Diario(string? busca,string? status,int pagina,CancellationToken ct)=>Lista("Diário de obra","diarios",busca,status,pagina,ct);
 [HttpGet("Fiscalizacao"),Authorize(Policy="OBRAS_FISCALIZACAO_VIEW")]public Task<IActionResult> Fiscalizacao(string? busca,string? status,int pagina,CancellationToken ct)=>Lista("Fiscalizações e vistorias","fiscalizacoes",busca,status,pagina,ct);
 [HttpGet("Ocorrencias"),Authorize(Policy="OBRAS_OCORRENCIA_MANAGE")]public Task<IActionResult> Ocorrencias(string? busca,string? status,int pagina,CancellationToken ct)=>Lista("Ocorrências","ocorrencias",busca,status,pagina,ct);
 [HttpGet("OrdensServico"),Authorize(Policy="OBRAS_ORDEM_SERVICO_VIEW")]public Task<IActionResult> Ordens(string? busca,string? status,int pagina,CancellationToken ct)=>Lista("Ordens de serviço","ordens-servico",busca,status,pagina,ct);
 [HttpGet("NaoConformidades"),Authorize(Policy="OBRAS_NAO_CONFORMIDADE_MANAGE")]public Task<IActionResult> NaoConformidades(string? busca,string? status,int pagina,CancellationToken ct)=>Lista("Não conformidades","nao-conformidades",busca,status,pagina,ct);
 [HttpGet("Aditivos"),Authorize(Policy="OBRAS_ADITIVO_MANAGE")]public Task<IActionResult> Aditivos(string? busca,string? status,int pagina,CancellationToken ct)=>Lista("Aditivos contratuais","aditivos",busca,status,pagina,ct);
 [HttpGet("Reajustes"),Authorize(Policy="OBRAS_ADITIVO_MANAGE")]public Task<IActionResult> Reajustes(string? busca,string? status,int pagina,CancellationToken ct)=>Lista("Reajustes","reajustes",busca,status,pagina,ct);
 [HttpGet("Reequilibrios"),Authorize(Policy="OBRAS_ADITIVO_MANAGE")]public Task<IActionResult> Reequilibrios(string? busca,string? status,int pagina,CancellationToken ct)=>Lista("Reequilíbrios econômico-financeiros","reequilibrios",busca,status,pagina,ct);
 [HttpGet("Evidencias"),Authorize(Policy="OBRAS_OCORRENCIA_MANAGE")]public Task<IActionResult> Evidencias(string? busca,string? status,int pagina,CancellationToken ct)=>Lista("Geoevidências transversais","evidencias",busca,status,pagina,ct);
 [HttpGet("Transparencia"),Authorize(Policy="OBRAS_TRANSPARENCIA_VIEW")]public Task<IActionResult> Transparencia(string? busca,string? status,int pagina,CancellationToken ct)=>Lista("Publicações de transparência","transparencia",busca,status,pagina,ct);
 [HttpGet("Convenios"),Authorize(Policy="OBRAS_CONVENIO_VIEW")]public Task<IActionResult> Convenios(string? busca,string? status,int pagina,CancellationToken ct)=>Lista("Convênios, fontes e repasses","convenios",busca,status,pagina,ct);
 [HttpGet("Documentos"),Authorize(Policy="OBRAS_DOCUMENTO_VIEW")]public Task<IActionResult> Documentos(string? busca,string? status,int pagina,CancellationToken ct)=>Lista("Documentos técnicos (metadados)","documentos",busca,status,pagina,ct);
 [HttpGet("IntegracaoFinanceira"),Authorize(Policy="OBRAS_INTEGRACAO_FINANCEIRA_VIEW")]public Task<IActionResult> Integracao(string? busca,string? status,int pagina,CancellationToken ct)=>Lista("Integração financeira preparada","integracao-financeira",busca,status,pagina,ct);
 [HttpGet("Auditoria"),Authorize(Policy="OBRAS_AUDITORIA_VIEW")]public Task<IActionResult> Auditoria(string? busca,string? status,int pagina,CancellationToken ct)=>Lista("Auditoria do módulo","auditoria",busca,status,pagina,ct);
 [HttpGet("{recurso}/Novo"),HttpGet("{recurso}/Create")]public async Task<IActionResult> NovoRegistro(string recurso,CancellationToken ct){if(!await Permitido(recurso,true))return Forbid();return View("RegistroForm",await Form(recurso,null,ct));}
 [HttpGet("{recurso}/{id:long}/Edit")]public async Task<IActionResult> EditarRegistro(string recurso,long id,CancellationToken ct){if(!await Permitido(recurso,true))return Forbid();var item=(await repository.ListarAsync(Contexto(),recurso,Filtro(),ct)).FirstOrDefault(x=>x.Id==id);if(item is null)return NotFound();return View("RegistroForm",await Form(recurso,item,ct));}
 [HttpGet("{recurso}/{id:long}/Details")]public async Task<IActionResult> DetalhesRegistro(string recurso,long id,CancellationToken ct){if(!await Permitido(recurso,false))return Forbid();var item=(await repository.ListarAsync(Contexto(),recurso,Filtro(),ct)).FirstOrDefault(x=>x.Id==id);return item is null?NotFound():View("RegistroDetails",item);}
 [HttpGet("Medicoes/{id:long}/Aprovar"),Authorize(Policy="OBRAS_MEDICAO_APPROVE")]public async Task<IActionResult> Aprovar(long id,CancellationToken ct){var item=(await repository.ListarAsync(Contexto(),"medicoes",Filtro(),ct)).FirstOrDefault(x=>x.Id==id);return item is null?NotFound():View("Aprovar",item);}
 [HttpPost("{recurso}/Salvar"),ValidateAntiForgeryToken]public async Task<IActionResult> SalvarRegistro(string recurso,ObrasRegistroFormViewModel model,CancellationToken ct){if(!await Permitido(recurso,true))return Forbid();if(ModelState.IsValid)try{await repository.SalvarAsync(Contexto(),recurso,model.ToRequest(),model.Id,ct);TempData["Success"]="Registro salvo e auditado.";return Redirect(Action(recurso));}catch(Exception ex) when(ex is ArgumentException or InvalidOperationException){ModelState.AddModelError("",ex.Message);}model.Obras=await repository.ListarOpcoesObraAsync(Contexto(),ct);model.Recurso=recurso;model.StatusPermitidos=Statuses(recurso);return View("RegistroForm",model);}
 [HttpPost("Medicoes/{id:long}/Homologar"),ValidateAntiForgeryToken,Authorize(Policy="OBRAS_MEDICAO_HOMOLOGAR")]public async Task<IActionResult> Homologar(long id,CancellationToken ct){await repository.HomologarMedicaoAsync(Contexto(),id,ct);TempData["Success"]="Medição homologada e disponibilizada para integração.";return RedirectToAction(nameof(Medicoes));}
 [HttpGet("Relatorios"),Authorize(Policy="OBRAS_RELATORIO_EXPORT")]public IActionResult Relatorios()=>View("Relatorios");
 [HttpGet("Relatorios/{relatorio}.csv"),Authorize(Policy="OBRAS_RELATORIO_EXPORT")]public async Task<IActionResult> Csv(string relatorio,CancellationToken ct)=>File(await repository.ExportarCsvAsync(Contexto(),relatorio,Filtro(),ct),"text/csv; charset=utf-8",$"obras-{relatorio}-{DateTime.UtcNow:yyyyMMdd}.csv");
 [HttpGet("ObrasCsv"),Authorize(Policy="OBRAS_RELATORIO_EXPORT")]public Task<IActionResult> ObrasCsv(CancellationToken ct)=>Csv("obras-status-localidade",ct);
 private async Task<IActionResult> Lista(string titulo,string recurso,string? busca,string? status,int pagina,CancellationToken ct)=>View("Lista",new ObrasListaViewModel(titulo,recurso,await repository.ListarAsync(Contexto(),recurso,Filtro(busca,status,pagina),ct),Filtro(busca,status,pagina)));
 private ObrasContexto Contexto(){if(!long.TryParse(User.FindFirst("tenant_id")?.Value,out var t)||t<=0||!long.TryParse(User.FindFirst("entidade_id")?.Value,out var e)||e<=0)throw new UnauthorizedAccessException("Tenant/entidade não resolvidos.");long.TryParse(User.FindFirst("exercicio_id")?.Value,out var x);long.TryParse(User.FindFirst("sub")?.Value??User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value,out var u);return new(t,e,x>0?x:null,u>0?u:null,HttpContext.TraceIdentifier,HttpContext.Connection.RemoteIpAddress?.ToString());}
 private async Task<ObrasRegistroFormViewModel> Form(string recurso,ObrasRegistro? item,CancellationToken ct)=>new(){Id=item?.Id,ObraId=item?.ObraId??0,Codigo=item?.Codigo??"",Descricao=item?.Descricao??"",Status=item?.Status??Statuses(recurso)[0],Valor=item?.Valor,Data=item?.Data,DadosJson=item?.DadosJson??"{}",Recurso=recurso,StatusPermitidos=Statuses(recurso),Obras=await repository.ListarOpcoesObraAsync(Contexto(),ct)};
 private async Task<bool> Permitido(string recurso,bool escrita)=>!(escrita&&(recurso is "evidencias" or "transparencia"))&&(await authorization.AuthorizeAsync(User,Policy(recurso,escrita))).Succeeded;
 private static string Policy(string r,bool escrita)=>r switch{
  "cronogramas"=>escrita?"OBRAS_CRONOGRAMA_MANAGE":"OBRAS_CRONOGRAMA_VIEW","diarios"=>escrita?"OBRAS_DIARIO_MANAGE":"OBRAS_DIARIO_VIEW","medicoes"=>escrita?"OBRAS_MEDICAO_MANAGE":"OBRAS_MEDICAO_VIEW",
  "aditivos" or "reajustes" or "reequilibrios"=>"OBRAS_ADITIVO_MANAGE","ocorrencias" or "evidencias"=>"OBRAS_OCORRENCIA_MANAGE","nao-conformidades"=>"OBRAS_NAO_CONFORMIDADE_MANAGE",
  "transparencia"=>"OBRAS_TRANSPARENCIA_VIEW","ordens-servico"=>escrita?"OBRAS_ORDEM_SERVICO_MANAGE":"OBRAS_ORDEM_SERVICO_VIEW","projetos"=>escrita?"OBRAS_PROJETO_MANAGE":"OBRAS_PROJETO_VIEW","orcamentos"=>escrita?"OBRAS_ORCAMENTO_MANAGE":"OBRAS_ORCAMENTO_VIEW","fiscalizacoes"=>escrita?"OBRAS_FISCALIZACAO_MANAGE":"OBRAS_FISCALIZACAO_VIEW",_=>"OBRAS_OBRA_MANAGE"};
 private static IReadOnlyList<string> Statuses(string r)=>r switch{
  "medicoes"=>["RASCUNHO","ENVIADA","EM_ANALISE","APROVADA","REJEITADA","CANCELADA"],"diarios"=>["RASCUNHO","ENVIADO","APROVADO","REJEITADO"],
  "ordens-servico"=>["ABERTA","ATRIBUIDA","EM_EXECUCAO","CONCLUIDA","CANCELADA"],"ocorrencias"=>["ABERTA","EM_TRATAMENTO","RESOLVIDA","CANCELADA"],
  "nao-conformidades"=>["ABERTA","EM_CORRECAO","CORRIGIDA","CANCELADA"],"transparencia"=>["PENDENTE","PUBLICADA","SUSPENSA","CANCELADA"],
  "cronogramas"=>["RASCUNHO","ATIVO","CONCLUIDO","CANCELADO"],_=>["RASCUNHO","EM_ANALISE","APROVADA","REJEITADA","CANCELADA"]};
 private static ObrasFiltro Filtro(string? busca=null,string? status=null,int pagina=1)=>new(busca,status,null,null,null,null,null,null,null,Math.Max(1,pagina),20);
 private static string Action(string r)=>r switch{"projetos"=>"/Obras/Projetos","orcamentos"=>"/Obras/Orcamentos","cronogramas"=>"/Obras/Cronogramas","medicoes"=>"/Obras/Medicoes","diarios"=>"/Obras/DiarioObra","fiscalizacoes"=>"/Obras/Fiscalizacao","ocorrencias"=>"/Obras/Ocorrencias","ordens-servico"=>"/Obras/OrdensServico","nao-conformidades"=>"/Obras/NaoConformidades","aditivos"=>"/Obras/Aditivos","reajustes"=>"/Obras/Reajustes","reequilibrios"=>"/Obras/Reequilibrios","evidencias"=>"/Obras/Evidencias","transparencia"=>"/Obras/Transparencia","convenios"=>"/Obras/Convenios","documentos"=>"/Obras/Documentos",_=>"/Obras"};
}
