using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Sigov.Application.Abstractions;
using Sigov.Application.Authorization;
using IAuthorizationEvaluator = Sigov.Application.Authorization.IAuthorizationEvaluator;
using Sigov.Application.Patrimonio;

namespace Sigov.Web.Controllers;

[Authorize]
public sealed class PatrimonioController(IPatrimonioService service,ICurrentTenant tenant,ICurrentUser user,IAuthorizationEvaluator authorization) : Controller
{
    [HttpGet("/Patrimonio"),HttpGet("/Patrimonio/Dashboard")]
    public async Task<IActionResult> Dashboard(CancellationToken ct){if(!await Permitido(PatrimonioPermissoes.DashboardVisualizar,ct))return Forbid();return View(await service.ObterDashboardAsync(Tenant(),ct));}
    [HttpGet("/Patrimonio/Bens")]
    public async Task<IActionResult> Bens([FromQuery]PatrimonioBemFiltro filtro,CancellationToken ct){if(!await Permitido(PatrimonioPermissoes.BemVisualizar,ct))return Forbid();ViewBag.PodeCriar=await Permitido(PatrimonioPermissoes.BemCriar,ct);ViewBag.PodeMovimentar=await Permitido(PatrimonioPermissoes.BemMovimentar,ct);ViewBag.PodeBaixar=await Permitido(PatrimonioPermissoes.BemBaixar,ct);ViewBag.PodeExportar=await Permitido(PatrimonioPermissoes.Exportar,ct);ViewBag.Opcoes=await service.ObterOpcoesAsync(Tenant(),Entidade(),ct);ViewBag.Filtro=filtro;return View(await service.ListarBensAsync(Tenant(),filtro,ct));}
    [HttpGet("/Patrimonio/Bens/Novo"),HttpGet("/Patrimonio/Bens/Create")]
    public async Task<IActionResult> Novo(CancellationToken ct){if(!await Permitido(PatrimonioPermissoes.BemCriar,ct))return Forbid();ViewBag.Opcoes=await service.ObterOpcoesAsync(Tenant(),Entidade(),ct);return View("Formulario",new PatrimonioBemInput("", "", null, "", null, null, null, null, null, null, null, "", null, null, null, null, null));}
    [HttpPost("/Patrimonio/Bens/Novo"),ValidateAntiForgeryToken]
    public async Task<IActionResult> Novo(PatrimonioBemInput input,CancellationToken ct){if(!await Permitido(PatrimonioPermissoes.BemCriar,ct))return Forbid();try{var id=await service.CriarBemAsync(Tenant(),Usuario(),HttpContext.TraceIdentifier,input,ct);TempData["Success"]="Bem tombado com sucesso.";return Redirect($"/Patrimonio/Bens/{id}");}catch(Exception e) when(e is ArgumentException or InvalidOperationException){ModelState.AddModelError("",e.Message);ViewBag.Opcoes=await service.ObterOpcoesAsync(Tenant(),Entidade(),ct);return View("Formulario",input);}}
    [HttpGet("/Patrimonio/Bens/{id:long}"),HttpGet("/Patrimonio/Bens/Details/{id:long}")]
    public async Task<IActionResult> Detalhe(long id,CancellationToken ct){if(!await Permitido(PatrimonioPermissoes.BemVisualizar,ct))return Forbid();var detalhe=await service.ObterBemDetalheAsync(Tenant(),id,ct);if(detalhe is null)return NotFound();ViewBag.Opcoes=await service.ObterOpcoesAsync(Tenant(),Entidade(),ct);ViewBag.PodeResponsabilidade=await Permitido(PatrimonioPermissoes.ResponsabilidadePropor,ct);ViewBag.PodeDecidir=await Permitido(PatrimonioPermissoes.ResponsabilidadeAceitar,ct);ViewBag.PodeOperar=await Permitido(PatrimonioPermissoes.MovimentacaoOperar,ct);ViewBag.PodeEditar=await Permitido(PatrimonioPermissoes.BemEditar,ct);ViewBag.PodeBaixar=await Permitido(PatrimonioPermissoes.BemBaixar,ct);return View(detalhe);}
    [HttpGet("/Patrimonio/Bens/{id:long}/TermoResponsabilidade")]
    public async Task<IActionResult> TermoResponsabilidade(long id,CancellationToken ct){if(!await Permitido(PatrimonioPermissoes.BemVisualizar,ct))return Forbid();var bem=await service.ObterBemAsync(Tenant(),id,ct);return bem is null?NotFound():View("TermoResponsabilidade",bem);}
    [HttpGet("/Patrimonio/Bens/{id:long}/Editar"),HttpGet("/Patrimonio/Bens/Edit/{id:long}")]
    public async Task<IActionResult> Editar(long id,CancellationToken ct){if(!await Permitido(PatrimonioPermissoes.BemEditar,ct))return Forbid();var b=await service.ObterBemAsync(Tenant(),id,ct);if(b is null)return NotFound();ViewBag.Id=id;ViewBag.Opcoes=await service.ObterOpcoesAsync(Tenant(),Entidade(),ct);return View("Formulario",new PatrimonioBemInput(b.CodigoTombo,b.Descricao,b.CategoriaId,b.TipoBem,null,b.Marca,b.Modelo,b.NumeroSerie,b.DataAquisicao,b.ValorAquisicao,b.ValorAtual,b.EstadoConservacao,b.UnidadeId,b.SetorId,b.ResponsavelUsuarioId,b.Localizacao,b.Observacao));}
    [HttpPost("/Patrimonio/Bens/{id:long}/Editar"),ValidateAntiForgeryToken]
    public async Task<IActionResult> Editar(long id,PatrimonioBemInput input,CancellationToken ct){if(!await Permitido(PatrimonioPermissoes.BemEditar,ct))return Forbid();try{await service.EditarBemAsync(Tenant(),Usuario(),HttpContext.TraceIdentifier,id,input,ct);TempData["Success"]="Bem atualizado.";return Redirect($"/Patrimonio/Bens/{id}");}catch(Exception e)when(e is ArgumentException or InvalidOperationException){ModelState.AddModelError("",e.Message);ViewBag.Id=id;ViewBag.Opcoes=await service.ObterOpcoesAsync(Tenant(),Entidade(),ct);return View("Formulario",input);}}

    [HttpGet("/Patrimonio/Incorporacoes")]
    public async Task<IActionResult> Incorporacoes(CancellationToken ct){if(!await Permitido(PatrimonioPermissoes.IncorporacaoVisualizar,ct))return Forbid();ViewBag.PodeIncorporar=await Permitido(PatrimonioPermissoes.IncorporacaoExecutar,ct);return View(new PatrimonioIncorporacoesPagina(await service.ListarRecebimentosElegiveisAsync(Tenant(),Entidade(),ct),await service.ObterOpcoesAsync(Tenant(),Entidade(),ct)));}
    [HttpPost("/Patrimonio/Incorporacoes"),ValidateAntiForgeryToken]
    public async Task<IActionResult> Incorporar(PatrimonioIncorporacaoInput input,CancellationToken ct){if(!await Permitido(PatrimonioPermissoes.IncorporacaoExecutar,ct))return Forbid();try{var ids=await service.IncorporarAsync(Tenant(),Entidade(),Usuario(),input,ct);TempData["Success"]=$"{ids.Count} bem(ns) incorporado(s) com rastreabilidade.";return ids.Count==1?Redirect($"/Patrimonio/Bens/{ids[0]}"):Redirect("/Patrimonio/Bens");}catch(Exception e)when(e is ArgumentException or InvalidOperationException){TempData["Error"]=e.Message;return Redirect("/Patrimonio/Incorporacoes");}}
    [HttpPost("/Patrimonio/Bens/{id:long}/Responsabilidade"),ValidateAntiForgeryToken]
    public async Task<IActionResult> ProporResponsabilidade(long id,PatrimonioTermoInput input,CancellationToken ct){if(!await Permitido(PatrimonioPermissoes.ResponsabilidadePropor,ct))return Forbid();return await ExecutarEscrita(async()=>{await service.ProporResponsabilidadeAsync(Tenant(),Entidade(),Usuario(),id,input,ct);TempData["Success"]="Termo emitido para aceite; a responsabilidade vigente não foi alterada.";return Redirect($"/Patrimonio/Bens/{id}");},$"/Patrimonio/Bens/{id}");}
    [HttpPost("/Patrimonio/Responsabilidade/{termoId:long}/Decidir"),ValidateAntiForgeryToken]
    public async Task<IActionResult> DecidirResponsabilidade(long termoId,long bemId,PatrimonioTermoDecisaoInput input,CancellationToken ct){if(!await Permitido(PatrimonioPermissoes.ResponsabilidadeAceitar,ct))return Forbid();return await ExecutarEscrita(async()=>{await service.DecidirResponsabilidadeAsync(Tenant(),Entidade(),Usuario(),termoId,input,ct);TempData["Success"]=input.Aceitar?"Responsabilidade aceita e vigente.":"Proposta recusada; a responsabilidade anterior foi preservada.";return Redirect($"/Patrimonio/Bens/{bemId}");},$"/Patrimonio/Bens/{bemId}");}
    [HttpGet("/Patrimonio/Responsabilidade/{termoId:long}/Imprimir")]
    public async Task<IActionResult> ImprimirTermo(long termoId,CancellationToken ct){if(!await Permitido(PatrimonioPermissoes.BemVisualizar,ct))return Forbid();var termo=await service.ObterTermoAsync(Tenant(),Entidade(),termoId,ct);return termo is null?NotFound():View("ImprimirTermo",termo);}
    [HttpPost("/Patrimonio/Bens/{id:long}/Transferencias"),ValidateAntiForgeryToken]
    public async Task<IActionResult> SolicitarTransferencia(long id,PatrimonioTransferenciaInput input,CancellationToken ct){if(!await Permitido(PatrimonioPermissoes.MovimentacaoOperar,ct))return Forbid();return await ExecutarEscrita(async()=>{await service.SolicitarTransferenciaAsync(Tenant(),Entidade(),Usuario(),id,input,ct);TempData["Success"]="Movimentação solicitada; a localização vigente foi preservada.";return Redirect($"/Patrimonio/Bens/{id}");},$"/Patrimonio/Bens/{id}");}
    [HttpPost("/Patrimonio/Transferencias/{transferenciaId:long}/Operar"),ValidateAntiForgeryToken]
    public async Task<IActionResult> OperarTransferencia(long transferenciaId,long bemId,PatrimonioTransferenciaAcaoInput input,CancellationToken ct){if(!await Permitido(PatrimonioPermissoes.MovimentacaoOperar,ct))return Forbid();return await ExecutarEscrita(async()=>{await service.OperarTransferenciaAsync(Tenant(),Entidade(),Usuario(),transferenciaId,input,ct);TempData["Success"]="Etapa da movimentação registrada.";return Redirect($"/Patrimonio/Bens/{bemId}");},$"/Patrimonio/Bens/{bemId}");}
    [HttpPost("/Patrimonio/Bens/{id:long}/Movimentar"),ValidateAntiForgeryToken]
    public async Task<IActionResult> Movimentar(long id,string idempotencyKey,PatrimonioMovimentacaoInput input,CancellationToken ct){if(!await Permitido(PatrimonioPermissoes.BemMovimentar,ct))return Forbid();return await ExecutarEscrita(async()=>{await service.MovimentarBemAsync(Tenant(),Usuario(),idempotencyKey,id,input,ct);TempData["Success"]="Movimentação registrada e auditada.";return Redirect($"/Patrimonio/Bens/{id}");},$"/Patrimonio/Bens/{id}");}
    [HttpPost("/Patrimonio/Bens/{id:long}/Baixar"),ValidateAntiForgeryToken]
    public async Task<IActionResult> Baixar(long id,PatrimonioBaixaInput input,CancellationToken ct){if(!await Permitido(PatrimonioPermissoes.BemBaixar,ct))return Forbid();return await ExecutarEscrita(async()=>{await service.BaixarBemAsync(Tenant(),Usuario(),HttpContext.TraceIdentifier,id,input,ct);TempData["Success"]="Baixa patrimonial registrada.";return Redirect($"/Patrimonio/Bens/{id}");},$"/Patrimonio/Bens/{id}");}
    [HttpGet("/Patrimonio/Inventarios")]
    public async Task<IActionResult> Inventarios(int pagina=1,CancellationToken ct=default){if(!await Permitido(PatrimonioPermissoes.InventarioVisualizar,ct))return Forbid();ViewBag.PodeCriar=await Permitido(PatrimonioPermissoes.InventarioCriar,ct);ViewBag.Opcoes=await service.ObterOpcoesAsync(Tenant(),Entidade(),ct);return View(await service.ListarInventariosAsync(Tenant(),pagina,25,ct));}
    [HttpPost("/Patrimonio/Inventarios"),ValidateAntiForgeryToken]
    public async Task<IActionResult> AbrirInventario(PatrimonioInventarioInput input,CancellationToken ct){if(!await Permitido(PatrimonioPermissoes.InventarioCriar,ct))return Forbid();return await ExecutarEscrita(async()=>{var id=await service.AbrirInventarioAsync(Tenant(),Usuario(),HttpContext.TraceIdentifier,input,ct);TempData["Success"]="Inventário aberto e itens do escopo carregados.";return Redirect($"/Patrimonio/Inventarios/{id}");},"/Patrimonio/Inventarios");}
    [HttpGet("/Patrimonio/Inventarios/{id:long}")]
    public async Task<IActionResult> Inventario(long id,CancellationToken ct){if(!await Permitido(PatrimonioPermissoes.InventarioVisualizar,ct))return Forbid();ViewBag.PodeConferir=await Permitido(PatrimonioPermissoes.InventarioConferir,ct);ViewBag.PodeFechar=await Permitido(PatrimonioPermissoes.InventarioCriar,ct);var x=await service.ObterInventarioAsync(Tenant(),id,ct);return x is null?NotFound():View(x);}
    [HttpPost("/Patrimonio/Inventarios/{id:long}/Itens/{itemId:long}/Conferir"),ValidateAntiForgeryToken]
    public async Task<IActionResult> Conferir(long id,long itemId,PatrimonioConferenciaInput input,CancellationToken ct){if(!await Permitido(PatrimonioPermissoes.InventarioConferir,ct))return Forbid();return await ExecutarEscrita(async()=>{await service.ConferirItemAsync(Tenant(),Usuario(),HttpContext.TraceIdentifier,id,itemId,input,ct);TempData["Success"]="Conferência registrada.";return Redirect($"/Patrimonio/Inventarios/{id}");},$"/Patrimonio/Inventarios/{id}");}
    [HttpPost("/Patrimonio/Inventarios/{id:long}/Fechar"),ValidateAntiForgeryToken]
    public async Task<IActionResult> Fechar(long id,CancellationToken ct){if(!await Permitido(PatrimonioPermissoes.InventarioCriar,ct))return Forbid();return await ExecutarEscrita(async()=>{await service.FecharInventarioAsync(Tenant(),Usuario(),HttpContext.TraceIdentifier,id,ct);TempData["Success"]="Inventário fechado.";return Redirect($"/Patrimonio/Inventarios/{id}");},$"/Patrimonio/Inventarios/{id}");}
    [HttpGet("/Patrimonio/Bens/Exportar")]
    public async Task<IActionResult> Exportar([FromQuery]PatrimonioBemFiltro filtro,CancellationToken ct){if(!await Permitido(PatrimonioPermissoes.Exportar,ct))return Forbid();return File(await service.ExportarCsvAsync(Tenant(),filtro,ct),"text/csv; charset=utf-8","patrimonio-bens.csv");}
    [HttpGet("/Patrimonio/Movimentacoes")] public IActionResult Movimentacoes()=>Redirect("/Patrimonio/Bens");
    [HttpGet("/Patrimonio/Baixas")] public IActionResult Baixas()=>Redirect("/Patrimonio/Bens?Situacao=BAIXADO");
    [HttpGet("/Patrimonio/Depreciacao")] public IActionResult Depreciacao()=>Redirect("/Ativos/Patrimonio/Depreciacao");
    [HttpGet("/Patrimonio/Relatorios")] public IActionResult Relatorios()=>Redirect("/Ativos/Relatorios");
    [HttpGet("/Patrimonio/Imoveis"),HttpGet("/Patrimonio/Imoveis/Create"),HttpGet("/Patrimonio/Imoveis/Edit/{id:long?}"),HttpGet("/Patrimonio/Imoveis/Details/{id:long?}"),HttpGet("/Patrimonio/Imoveis/Ocupacao"),HttpGet("/Patrimonio/Imoveis/Documentos")]
    public IActionResult Imoveis()=>Redirect("/Ativos/Patrimonio");
    private async Task<IActionResult> ExecutarEscrita(Func<Task<IActionResult>> action,string fallback)
    {try{return await action();}catch(Exception e)when(e is ArgumentException or InvalidOperationException or KeyNotFoundException){TempData["Error"]=e.Message;return Redirect(fallback);}}
    private async Task<bool> Permitido(string chave,CancellationToken ct){var i=chave.LastIndexOf('.');var d=await authorization.EvaluateAsync(new(Usuario(),"patrimonio",chave[..i],chave[(i+1)..],Tenant(),tenant.EntidadeId,tenant.ExercicioId,null,null,HttpContext.TraceIdentifier,"WEB_FUNC01"),ct);return d.Permitido;}
    private long Tenant()=>tenant.TenantId??throw new InvalidOperationException("tenant_id obrigatório.");private long Entidade()=>tenant.EntidadeId??throw new InvalidOperationException("entidade_id obrigatório.");private long Usuario()=>user.UsuarioId??throw new InvalidOperationException("Usuário obrigatório.");
}
