using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Sigov.Application.Royalties;

namespace Sigov.Web.Controllers;
[Authorize,Route("Royalties")]
public sealed class RoyaltiesController(IRoyaltiesRepository repository,IAuthorizationService authorization,ILogger<RoyaltiesController> logger):Controller
{
 private static readonly IReadOnlyDictionary<string,(string Title,string View,string Manage)> Meta=new Dictionary<string,(string,string,string)>(StringComparer.OrdinalIgnoreCase){
 ["parametros"]=("Parâmetros normativos","ROYALTIES_DASHBOARD_VIEW","ROYALTIES_PARAMETRO_MANAGE"),["fontesdados"]=("Fontes de dados","ROYALTIES_DASHBOARD_VIEW","ROYALTIES_FONTE_DADO_MANAGE"),["areas"]=("Áreas de exploração","ROYALTIES_DASHBOARD_VIEW","ROYALTIES_ORIGEM_RECEITA_MANAGE"),["campos"]=("Campos, blocos e origens","ROYALTIES_DASHBOARD_VIEW","ROYALTIES_ORIGEM_RECEITA_MANAGE"),["origemreceita"]=("Origem da receita","ROYALTIES_DASHBOARD_VIEW","ROYALTIES_ORIGEM_RECEITA_MANAGE"),["previsoes"]=("Previsões de receita","ROYALTIES_PREVISAO_VIEW","ROYALTIES_PREVISAO_MANAGE"),["cenarios"]=("Cenários de arrecadação","ROYALTIES_PREVISAO_VIEW","ROYALTIES_PREVISAO_MANAGE"),["repasses"]=("Repasses recebidos","ROYALTIES_REPASSE_VIEW","ROYALTIES_REPASSE_MANAGE"),["conciliacao"]=("Conciliação financeira","ROYALTIES_REPASSE_VIEW","ROYALTIES_CONCILIACAO_MANAGE"),["planosaplicacao"]=("Planos de aplicação","ROYALTIES_PLANO_VIEW","ROYALTIES_PLANO_MANAGE"),["projetos"]=("Projetos financiados","ROYALTIES_PROJETO_VIEW","ROYALTIES_PROJETO_MANAGE"),["acompanhamento"]=("Acompanhamento de projetos","ROYALTIES_PROJETO_VIEW","ROYALTIES_PROJETO_MANAGE"),["execucaofinanceira"]=("Execução financeira vinculada","ROYALTIES_EXECUCAO_VIEW","ROYALTIES_EXECUCAO_VIEW"),["saldos"]=("Saldos por fonte","ROYALTIES_EXECUCAO_VIEW","ROYALTIES_EXECUCAO_VIEW"),["transparencia"]=("Transparência de royalties","ROYALTIES_TRANSPARENCIA_VIEW","ROYALTIES_TRANSPARENCIA_PUBLISH"),["alertas"]=("Alertas","ROYALTIES_DASHBOARD_VIEW","ROYALTIES_ALERTA_MANAGE"),["governanca"]=("Governança e auditoria","ROYALTIES_DASHBOARD_VIEW","ROYALTIES_ALERTA_MANAGE")};
 [HttpGet(""),HttpGet("Dashboard"),Authorize(Policy="ROYALTIES_DASHBOARD_VIEW")]
 public async Task<IActionResult> Dashboard(string? status,string? tipoReceita,DateOnly? inicio,DateOnly? fim,CancellationToken ct)=>View(await repository.DashboardAsync(Contexto(),new(null,status,null,null,tipoReceita,inicio,fim),ct));
 [HttpGet("{recurso:regex(^Parametros|FontesDados|Areas|Campos|OrigemReceita|Previsoes|Cenarios|Repasses|Conciliacao|PlanosAplicacao|Projetos|ExecucaoFinanceira|Saldos|Transparencia|Alertas|Governanca$)}")]
 public async Task<IActionResult> Lista(string recurso,string? busca,string? status,string? tipoReceita,CancellationToken ct)=>await ListaInterna(Normalizar(recurso),busca,status,tipoReceita,ct);
 [HttpGet("Projetos/Acompanhamento")] public Task<IActionResult> Acompanhamento(string? busca,string? status,CancellationToken ct)=>ListaInterna("acompanhamento",busca,status,null,ct);
 [HttpGet("Relatorios")] public IActionResult Relatorios()=>View();
 [HttpGet("{recurso:regex(^Parametros|FontesDados|Areas|Campos|OrigemReceita|Previsoes|Repasses|PlanosAplicacao|Projetos$)}/Create")]
 public async Task<IActionResult> Create(string recurso,CancellationToken ct){var r=Normalizar(recurso);if(!await Permitido(Meta[r].Manage))return Forbid();await Preparar(r,ct);return View("Form",new RoyaltiesRequest());}
 [HttpGet("{recurso:regex(^Parametros|FontesDados|Areas|Campos|OrigemReceita|Previsoes|Repasses|PlanosAplicacao|Projetos$)}/Edit/{id:long}")]
 public async Task<IActionResult> Edit(string recurso,long id,CancellationToken ct){var r=Normalizar(recurso);if(!await Permitido(Meta[r].Manage))return Forbid();var x=await repository.ObterAsync(Contexto(),r,id,ct);if(x is null)return NotFound();await Preparar(r,ct);ViewData["Id"]=id;return View("Form",new RoyaltiesRequest{Codigo=x.Codigo,Nome=x.Nome,Descricao=x.Descricao,Status=x.Status,TipoReceita=x.TipoReceita??"ROYALTIES",Valor=x.Valor,Competencia=x.Competencia,DataReferencia=x.DataReferencia,FonteRecursoId=x.FonteRecursoId});}
 [HttpGet("{recurso:regex(^Parametros|FontesDados|Areas|Campos|OrigemReceita|Previsoes|Repasses|PlanosAplicacao|Projetos$)}/Details/{id:long}")]
 public async Task<IActionResult> Details(string recurso,long id,CancellationToken ct){var r=Normalizar(recurso);if(!await Permitido(Meta[r].View))return Forbid();var x=await repository.ObterAsync(Contexto(),r,id,ct);ViewData["Titulo"]=Meta[r].Title;return x is null?NotFound():View(x);}
 [HttpPost("{recurso:regex(^Parametros|FontesDados|Areas|Campos|OrigemReceita|Previsoes|Repasses|PlanosAplicacao|Projetos$)}/Save"),ValidateAntiForgeryToken]
 public async Task<IActionResult> Save(string recurso,RoyaltiesRequest model,long? id,CancellationToken ct){var r=Normalizar(recurso);if(!await Permitido(Meta[r].Manage))return Forbid();if(ModelState.IsValid)try{var saved=await repository.SalvarAsync(Contexto(),r,model,id,ct);TempData["Success"]="Registro salvo com rastreabilidade e contexto institucional.";return RedirectToAction(nameof(Details),new{recurso,id=saved});}catch(Exception ex) when(ex is ArgumentException or InvalidOperationException or Npgsql.PostgresException){logger.LogWarning(ex,"Validação Royalties360 {CorrelationId}",HttpContext.TraceIdentifier);ModelState.AddModelError("",ex.Message);}await Preparar(r,ct);ViewData["Id"]=id;return View("Form",model);}
 [HttpGet("Relatorios/{recurso}.csv"),Authorize(Policy="ROYALTIES_RELATORIO_EXPORT")] public async Task<IActionResult> Csv(string recurso,string? busca,string? status,CancellationToken ct)=>File(await repository.ExportarCsvAsync(Contexto(),Normalizar(recurso),new(busca,status),ct),"text/csv; charset=utf-8",$"royalties-{recurso}-{DateTime.UtcNow:yyyyMMdd}.csv");
 private async Task<IActionResult> ListaInterna(string r,string? busca,string? status,string? tipo,CancellationToken ct){if(!Meta.TryGetValue(r,out var m))return NotFound();if(!await Permitido(m.View))return Forbid();ViewData["Recurso"]=r;ViewData["Titulo"]=m.Title;ViewData["PodeGerenciar"]=await Permitido(m.Manage);return View("Lista",await repository.ListarAsync(Contexto(),r,new(busca,status,null,null,tipo),ct));}
 private async Task Preparar(string r,CancellationToken ct){ViewData["Recurso"]=r;ViewData["Titulo"]=Meta[r].Title;ViewBag.Exercicios=new SelectList(await repository.OpcoesAsync(Contexto(),"exercicio",ct),"Id","Texto");ViewBag.Fontes=new SelectList(await repository.OpcoesAsync(Contexto(),"fonte",ct),"Id","Texto");ViewBag.Unidades=new SelectList(await repository.OpcoesAsync(Contexto(),"unidade",ct),"Id","Texto");ViewBag.Pessoas=new SelectList(await repository.OpcoesAsync(Contexto(),"pessoa",ct),"Id","Texto");ViewBag.Projetos=new SelectList(await repository.OpcoesAsync(Contexto(),"projeto",ct),"Id","Texto");ViewBag.Parametros=new SelectList(await repository.OpcoesAsync(Contexto(),"parametro",ct),"Id","Texto");ViewBag.Contratos=new SelectList(await repository.OpcoesAsync(Contexto(),"contrato",ct),"Id","Texto");}
 private static string Normalizar(string r)=>r.Replace("-","").ToLowerInvariant();
 private async Task<bool> Permitido(string p)=>(await authorization.AuthorizeAsync(User,p)).Succeeded;
 private RoyaltiesContexto Contexto(){if(!long.TryParse(User.FindFirst("tenant_id")?.Value,out var t)||!long.TryParse(User.FindFirst("entidade_id")?.Value,out var e)||t<=0||e<=0)throw new UnauthorizedAccessException("Tenant e entidade são obrigatórios.");long.TryParse(User.FindFirst("sub")?.Value,out var u);return new(t,e,u>0?u:null,HttpContext.TraceIdentifier);}
}
