using Microsoft.AspNetCore.Mvc;
using Sigov.Web.Models.Social;
using Sigov.Web.Services;
namespace Sigov.Web.Controllers;
public sealed class SocialController : Controller
{
    private readonly SectorModuleService? _sector;
    public SocialController(SectorModuleService sector) => _sector = sector;
    [Route("/Social")] public async Task<IActionResult> Index(string? q, CancellationToken cancellationToken) => _sector is null ? View(new SocialDashboardViewModel()) : View("~/Views/Sectors/Module.cshtml", await _sector.BuildAsync("Social", "Assistência Social", "Famílias, pessoas, atendimentos, benefícios, visitas e relatórios com LGPD reforçada.", new[]{"Famílias","Pessoas","Atendimentos","Benefícios"}, new[]{"/Social/Familias","/Social/Pessoas","/Social/Atendimentos","/Social/Beneficios","/Social/Visitas","/Social/Relatorios"}, true, q, cancellationToken));
    [Route("/Social/Dashboard"), Route("/AssistenciaSocial/Dashboard")] public IActionResult Dashboard()=>View(new SocialDashboardViewModel()); [Route("/Social/Unidades"), Route("/AssistenciaSocial/Unidades")] public IActionResult Unidades()=>View(new SocialUnidadeFormViewModel()); [Route("/Social/Familias"), Route("/AssistenciaSocial/Familias")] public IActionResult Familias()=>View(new SocialFamiliaFormViewModel());
    [Route("/Social/Familias/Nova")] public IActionResult FamiliaNova()=>View(new SocialFamiliaFormViewModel());
    [HttpPost("/Social/Familias/Nova")][ValidateAntiForgeryToken] public IActionResult FamiliaNovaPost(SocialFamiliaFormViewModel model){ if(!ModelState.IsValid)return View(model); TempData["Warning"]="Use a operação autenticada do formulário, persistida pela API Social."; return RedirectToAction(nameof(Familias)); }
    [Route("/Social/Familias/{id:long}")] public IActionResult FamiliaDetalhe(long id)=>View(new SocialFamiliaFormViewModel()); [Route("/Social/Pessoas"), Route("/AssistenciaSocial/Pessoas")] public IActionResult Pessoas()=>View(new SocialPessoaFormViewModel()); public IActionResult Cadastros()=>View(new SocialFamiliaFormViewModel()); public IActionResult Programas()=>View(new SocialProgramaFormViewModel()); [Route("/Social/Beneficios"), Route("/AssistenciaSocial/Beneficios")] public IActionResult Beneficios()=>View(new SocialBeneficioFormViewModel()); public IActionResult Concessoes()=>View(new SocialBeneficioConcessaoFormViewModel()); [Route("/Social/Atendimentos"), Route("/AssistenciaSocial/Atendimentos")] public IActionResult Atendimentos()=>View(new SocialAtendimentoFormViewModel()); public IActionResult AtendimentoDetalhe(long id)=>View(new SocialAtendimentoFormViewModel()); [Route("/Social/Visitas"), Route("/AssistenciaSocial/Visitas")] public IActionResult Visitas()=>View(new SocialVisitaFormViewModel()); public IActionResult Pareceres()=>View(new SocialParecerFormViewModel()); [Route("/Social/Acompanhamentos"), Route("/AssistenciaSocial/Acompanhamentos")] public IActionResult Acompanhamentos()=>View(new SocialAcompanhamentoFormViewModel()); public IActionResult Vigilancia()=>View(new SocialVigilanciaFormViewModel()); [Route("/Social/Relatorios"), Route("/AssistenciaSocial/Relatorios")] public IActionResult Relatorios()=>View(new SocialDashboardViewModel()); [Route("/AssistenciaSocial/Domicilios")] public IActionResult Domicilios()=>View("Familias",new SocialFamiliaFormViewModel()); [Route("/AssistenciaSocial/Tecnicos")] public IActionResult Tecnicos()=>View("Unidades",new SocialUnidadeFormViewModel()); [Route("/AssistenciaSocial/Prontuarios")] public IActionResult Prontuarios()=>View("Pareceres",new SocialParecerFormViewModel()); [Route("/AssistenciaSocial/Encaminhamentos")] public IActionResult Encaminhamentos()=>View("Atendimentos",new SocialAtendimentoFormViewModel()); [Route("/AssistenciaSocial/Scfv")] public IActionResult Scfv()=>View("Acompanhamentos",new SocialAcompanhamentoFormViewModel());
}
