using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Sigov.Application.Transito;
using Sigov.Web.Models.Transito;
namespace Sigov.Web.Controllers;

[Authorize,Route("Transito")]
public sealed class TransitoController(ITransitoRepository repository,IAuthorizationService authorization):Controller
{
 private static readonly IReadOnlyDictionary<string,(string Title,string View,string Manage)> Resources=new Dictionary<string,(string,string,string)>(StringComparer.OrdinalIgnoreCase){["Agentes"]=("Agentes de trânsito","TRANSITO_AGENTE_VIEW","TRANSITO_AGENTE_MANAGE"),["Condutores"]=("Condutores","TRANSITO_CONDUTOR_VIEW","TRANSITO_CONDUTOR_MANAGE"),["Veiculos"]=("Veículos fiscalizados","TRANSITO_VEICULO_VIEW","TRANSITO_VEICULO_MANAGE"),["Infracoes"]=("Tipos de infração","TRANSITO_INFRACAO_VIEW","TRANSITO_INFRACAO_MANAGE"),["Autos"]=("Autos de infração","TRANSITO_AUTO_VIEW","TRANSITO_AUTO_MANAGE"),["Notificacoes"]=("Notificações","TRANSITO_NOTIFICACAO_VIEW","TRANSITO_NOTIFICACAO_MANAGE"),["Recursos"]=("Recursos","TRANSITO_RECURSO_VIEW","TRANSITO_RECURSO_MANAGE"),["Julgamentos"]=("Julgamentos","TRANSITO_RECURSO_VIEW","TRANSITO_RECURSO_MANAGE"),["Ocorrencias"]=("Ocorrências","TRANSITO_OCORRENCIA_VIEW","TRANSITO_OCORRENCIA_MANAGE"),["Sinalizacao"]=("Sinalização viária","TRANSITO_SINALIZACAO_VIEW","TRANSITO_SINALIZACAO_MANAGE"),["Intervencoes"]=("Intervenções viárias","TRANSITO_INTERVENCAO_VIEW","TRANSITO_INTERVENCAO_MANAGE"),["Linhas"]=("Linhas de transporte","TRANSITO_TRANSPORTE_VIEW","TRANSITO_TRANSPORTE_MANAGE"),["Rotas"]=("Rotas de transporte","TRANSITO_TRANSPORTE_VIEW","TRANSITO_TRANSPORTE_MANAGE"),["Pontos"]=("Pontos de transporte","TRANSITO_TRANSPORTE_VIEW","TRANSITO_TRANSPORTE_MANAGE"),["Autorizacoes"]=("Autorizações de transporte","TRANSITO_TRANSPORTE_VIEW","TRANSITO_TRANSPORTE_MANAGE"),["Vistorias"]=("Vistorias","TRANSITO_VISTORIA_VIEW","TRANSITO_VISTORIA_MANAGE"),["Credenciais"]=("Credenciais especiais","TRANSITO_CREDENCIAL_VIEW","TRANSITO_CREDENCIAL_MANAGE"),["Auditoria"]=("Auditoria","TRANSITO_AUDITORIA_VIEW","TRANSITO_AUDITORIA_VIEW")};
 [HttpGet(""),HttpGet("Dashboard"),Authorize(Policy="TRANSITO_DASHBOARD_VIEW")]public async Task<IActionResult> Dashboard(CancellationToken ct)=>View(await repository.DashboardAsync(Context(),ct));
 [HttpGet("{recurso}")]public async Task<IActionResult> Lista(string recurso,string? busca,string? status,DateOnly? inicio,DateOnly? fim,int pagina,CancellationToken ct){var m=Meta(recurso);if(!await Allowed(m.View))return Forbid();var f=new TransitoFiltro(busca,status,inicio,fim,Math.Max(1,pagina));return View("Lista",new TransitoListaViewModel(m.Title,recurso,await repository.ListarAsync(Context(),recurso,f,ct),f));}
 [HttpGet("{recurso}/Novo")]public async Task<IActionResult> Novo(string recurso,CancellationToken ct){var m=Meta(recurso);if(!await Allowed(m.Manage))return Forbid();return View("Form",await Form(m.Title,recurso,new(),ct));}
 [HttpPost("{recurso}/Salvar"),ValidateAntiForgeryToken]public async Task<IActionResult> Salvar(string recurso,TransitoRegistroRequest registro,CancellationToken ct){var m=Meta(recurso);if(!await Allowed(m.Manage))return Forbid();ValidateRules(recurso,registro);if(!ModelState.IsValid)return View("Form",await Form(m.Title,recurso,registro,ct));try{await repository.SalvarAsync(Context(),recurso,registro,ct);TempData["Success"]="Registro salvo e auditado.";return RedirectToAction(nameof(Lista),new{recurso});}catch(ArgumentException ex){ModelState.AddModelError("",ex.Message);return View("Form",await Form(m.Title,recurso,registro,ct));}}
 [HttpPost("{recurso}/{id:long}/Excluir"),ValidateAntiForgeryToken]public async Task<IActionResult> Excluir(string recurso,long id,CancellationToken ct){var m=Meta(recurso);if(!await Allowed(m.Manage))return Forbid();await repository.ExcluirAsync(Context(),recurso,id,ct);TempData["Success"]="Registro excluído com rastreabilidade.";return RedirectToAction(nameof(Lista),new{recurso});}
 [HttpGet("Relatorios"),Authorize(Policy="TRANSITO_RELATORIO_EXPORT")]public IActionResult Relatorios()=>View();
 [HttpGet("Relatorios/{recurso}.csv"),Authorize(Policy="TRANSITO_RELATORIO_EXPORT")]public async Task<IActionResult> Csv(string recurso,string? busca,string? status,DateOnly? inicio,DateOnly? fim,CancellationToken ct)=>File(await repository.CsvAsync(Context(),recurso,new(busca,status,inicio,fim),ct),"text/csv; charset=utf-8",$"transito-{recurso}-{DateTime.UtcNow:yyyyMMdd}.csv");
 private async Task<TransitoFormViewModel> Form(string title,string recurso,TransitoRegistroRequest r,CancellationToken ct){var types=new[]{"Agentes","Condutores","Veiculos","Infracoes","Autos","Notificacoes","Recursos","Linhas","Pontos","Autorizacoes"};var d=new Dictionary<string,IReadOnlyList<TransitoOpcao>>();foreach(var type in types)if(!type.Equals(recurso,StringComparison.OrdinalIgnoreCase))d[type]=await repository.OpcoesAsync(Context(),type,ct);return new(title,recurso,r,d);}
 private void ValidateRules(string recurso,TransitoRegistroRequest r)
 {
  string? F(string name)=>r.Campos.GetValueOrDefault(name);
  void Required(params string[] fields){foreach(var field in fields)if(string.IsNullOrWhiteSpace(F(field)))ModelState.AddModelError($"Registro.Campos[{field}]",$"Informe {field.Replace('_',' ')}.");}
  void Ordered(string first,string last){if(DateTime.TryParse(F(first),out var a)&&DateTime.TryParse(F(last),out var b)&&b<a)ModelState.AddModelError($"Registro.Campos[{last}]","A data final não pode anteceder a data inicial.");}
  void Coordinates(){if(decimal.TryParse(F("latitude"),out var lat)&&(lat < -90 || lat > 90))ModelState.AddModelError("Registro.Campos[latitude]","Latitude deve estar entre -90 e 90.");if(decimal.TryParse(F("longitude"),out var lon)&&(lon < -180 || lon > 180))ModelState.AddModelError("Registro.Campos[longitude]","Longitude deve estar entre -180 e 180.");}
  switch(recurso.ToUpperInvariant())
  {
   case "AUTOS": Required("agente_id","infracao_tipo_id","data_hora_infracao","local_infracao","valor_multa");if(string.IsNullOrWhiteSpace(F("veiculo_id"))&&string.IsNullOrWhiteSpace(F("justificativa_sem_veiculo")))ModelState.AddModelError("","Selecione o veículo ou informe a justificativa sem veículo.");var identificado=bool.TryParse(F("condutor_identificado"),out var ci)&&ci;if(identificado&&string.IsNullOrWhiteSpace(F("condutor_id")))ModelState.AddModelError("","Selecione o condutor identificado.");if(!identificado&&string.IsNullOrWhiteSpace(F("justificativa_sem_condutor")))ModelState.AddModelError("","Informe a justificativa para condutor não identificado.");if(decimal.TryParse(F("valor_multa"),out var multa)&&multa<0)ModelState.AddModelError("","O valor da multa não pode ser negativo.");break;
   case "NOTIFICACOES": Required("auto_infracao_id","data_emissao","data_vencimento","meio_envio","destinatario_documento","endereco_envio");Ordered("data_emissao","data_vencimento");break;
   case "RECURSOS": Required("auto_infracao_id","requerente_documento","data_recurso","fundamento");break;
   case "JULGAMENTOS": Required("recurso_id","data_julgamento","fundamentacao");break;
   case "OCORRENCIAS": Required("tipo","data_hora","local","gravidade");Coordinates();break;
   case "SINALIZACAO": Required("tipo","local","estado_conservacao");Coordinates();Ordered("data_instalacao","data_ultima_vistoria");break;
   case "INTERVENCOES": Required("tipo","local","data_inicio","data_fim_prevista","responsavel","impacto");Ordered("data_inicio","data_fim_prevista");Ordered("data_inicio","data_fim_real");break;
   case "ROTAS": Required("linha_id","sentido","distancia_km","tempo_estimado_min");if(decimal.TryParse(F("distancia_km"),out var km)&&km<0)ModelState.AddModelError("","A distância não pode ser negativa.");if(int.TryParse(F("tempo_estimado_min"),out var min)&&min<0)ModelState.AddModelError("","O tempo estimado não pode ser negativo.");break;
   case "AUTORIZACOES": Required("tipo","titular_documento","data_emissao","data_validade");Ordered("data_emissao","data_validade");break;
   case "VISTORIAS": Required("veiculo_id","data_vistoria","resultado");if(F("resultado")?.Equals("REPROVADA",StringComparison.OrdinalIgnoreCase)==true)Required("irregularidades");Ordered("data_vistoria","prazo_regularizacao");break;
   case "CREDENCIAIS": Required("tipo","beneficiario_documento","data_emissao","data_validade");Ordered("data_emissao","data_validade");break;
  }
  if((r.Status.Equals("CANCELADA",StringComparison.OrdinalIgnoreCase)||r.Status.Equals("CANCELADO",StringComparison.OrdinalIgnoreCase)||r.Status.Equals("ANULADO",StringComparison.OrdinalIgnoreCase)) && recurso is ("Autos" or "Credenciais" or "Autorizacoes") && string.IsNullOrWhiteSpace(F("justificativa_cancelamento")))ModelState.AddModelError("","Cancelamento ou anulação exige justificativa.");
 }
 private TransitoContexto Context(){if(!long.TryParse(User.FindFirst("tenant_id")?.Value,out var t)||!long.TryParse(User.FindFirst("entidade_id")?.Value??User.FindFirst("entity_id")?.Value,out var e)||t<=0||e<=0)throw new UnauthorizedAccessException("Contexto tenant/entidade não resolvido.");return new(t,e,User.Identity?.Name??"sistema");}private async Task<bool> Allowed(string p)=>(await authorization.AuthorizeAsync(User,p)).Succeeded;private static (string Title,string View,string Manage) Meta(string r)=>Resources.TryGetValue(r,out var m)?m:throw new ArgumentException("Recurso inválido.");
}
