using System.ComponentModel.DataAnnotations;

namespace Sigov.Web.Models.Financeiro;

public sealed class PlanoContasFormViewModel { public long? Id { get; set; } [Required] public string Codigo { get; set; } = string.Empty; [Required] public string Nome { get; set; } = string.Empty; public string TipoConta { get; set; } = "DESPESA"; public int Nivel { get; set; } = 1; public bool AceitaLancamento { get; set; } = true; }
public sealed class FonteRecursoFormViewModel { public long? Id { get; set; } [Required] public string Codigo { get; set; } = string.Empty; [Required] public string Nome { get; set; } = string.Empty; public string? Descricao { get; set; } }
public sealed class ProgramaFormViewModel { public long? Id { get; set; } [Required] public string Codigo { get; set; } = string.Empty; [Required] public string Nome { get; set; } = string.Empty; public string? Objetivo { get; set; } }
public sealed class AcaoFormViewModel { public long? Id { get; set; } public long ProgramaId { get; set; } [Required] public string Codigo { get; set; } = string.Empty; [Required] public string Nome { get; set; } = string.Empty; public string TipoAcao { get; set; } = "ATIVIDADE"; }
public sealed class NaturezaDespesaFormViewModel { public long? Id { get; set; } [Required] public string Codigo { get; set; } = string.Empty; [Required] public string Nome { get; set; } = string.Empty; public string? Categoria { get; set; } public string? Grupo { get; set; } public string? Modalidade { get; set; } public string? Elemento { get; set; } }
public sealed class NaturezaReceitaFormViewModel { public long? Id { get; set; } [Required] public string Codigo { get; set; } = string.Empty; [Required] public string Nome { get; set; } = string.Empty; public string? Categoria { get; set; } public string? Origem { get; set; } public string? Especie { get; set; } }
public sealed class OrcamentoDespesaFormViewModel { public long? Id { get; set; } public long ProgramaId { get; set; } public long AcaoId { get; set; } public long NaturezaDespesaId { get; set; } public long FonteRecursoId { get; set; } [Range(typeof(decimal), "0", "79228162514264337593543950335")] public decimal DotacaoInicial { get; set; } }
public sealed class OrcamentoReceitaFormViewModel { public long? Id { get; set; } public long NaturezaReceitaId { get; set; } public long FonteRecursoId { get; set; } [Range(typeof(decimal), "0", "79228162514264337593543950335")] public decimal PrevisaoInicial { get; set; } }
public sealed class EmpenhoFormViewModel { public long? Id { get; set; } public DateOnly DataEmpenho { get; set; } = DateOnly.FromDateTime(DateTime.Today); public long FornecedorPessoaId { get; set; } public long OrcamentoDespesaId { get; set; } public string TipoEmpenho { get; set; } = "ORDINARIO"; [Required] public string Historico { get; set; } = string.Empty; public string? Observacoes { get; set; } public List<EmpenhoItemFormViewModel> Itens { get; set; } = new() { new EmpenhoItemFormViewModel() }; }
public sealed class EmpenhoItemFormViewModel { [Required] public string Descricao { get; set; } = string.Empty; [Range(typeof(decimal), "0.0001", "79228162514264337593543950335")] public decimal Quantidade { get; set; } = 1m; [Range(typeof(decimal), "0.01", "79228162514264337593543950335")] public decimal ValorUnitario { get; set; } }
public sealed class LiquidacaoFormViewModel { public long EmpenhoId { get; set; } public DateOnly DataLiquidacao { get; set; } = DateOnly.FromDateTime(DateTime.Today); public string? DocumentoFiscal { get; set; } public string Historico { get; set; } = string.Empty; public decimal Valor { get; set; } }
public sealed class PagamentoFormViewModel { public long LiquidacaoId { get; set; } public DateOnly DataPagamento { get; set; } = DateOnly.FromDateTime(DateTime.Today); public string FormaPagamento { get; set; } = "TRANSFERENCIA"; public string? ContaBancaria { get; set; } public string Historico { get; set; } = string.Empty; public decimal Valor { get; set; } }
public sealed class ReceitaLancamentoFormViewModel { public long OrcamentoReceitaId { get; set; } public DateOnly DataLancamento { get; set; } = DateOnly.FromDateTime(DateTime.Today); public long? ContribuintePessoaId { get; set; } public string Historico { get; set; } = string.Empty; public decimal Valor { get; set; } }
public sealed class ReceitaArrecadacaoFormViewModel { public long ReceitaLancamentoId { get; set; } public DateOnly DataArrecadacao { get; set; } = DateOnly.FromDateTime(DateTime.Today); public string FormaArrecadacao { get; set; } = "PIX"; public decimal Valor { get; set; } public string Historico { get; set; } = string.Empty; }
public sealed class FinanceiroDashboardViewModel { public decimal OrcamentoAutorizado { get; set; } public decimal Empenhado { get; set; } public decimal Liquidado { get; set; } public decimal Pago { get; set; } public decimal SaldoDisponivel { get; set; } public decimal ReceitaPrevista { get; set; } public decimal ReceitaLancada { get; set; } public decimal ReceitaArrecadada { get; set; } }
