using System.Globalization;
using System.Text;
using System.Text.Json;
using Dapper;
using Sigov.Application.Juridico;
using Sigov.Infrastructure.Persistence.Dapper;
namespace Sigov.Infrastructure.Juridico;
public sealed class JuridicoRepository(DapperContext db):IJuridicoRepository
{
 private static readonly IReadOnlyDictionary<string,string> Tables=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase){["advogados"]="juridico_advogado",["partes"]="juridico_parte",["processos"]="juridico_processo",["movimentacoes"]="juridico_movimentacao",["prazos"]="juridico_prazo",["intimacoes"]="juridico_intimacao",["audiencias"]="juridico_audiencia",["pareceres"]="juridico_parecer",["consultas"]="juridico_consulta",["acordos"]="juridico_acordo",["dividaativa"]="juridico_divida_ativa_judicial",["custas"]="juridico_custas",["auditoria"]="juridico_auditoria"};
 private static readonly IReadOnlyDictionary<string,(string Columns,string Values)> Extras=new Dictionary<string,(string,string)>(StringComparer.OrdinalIgnoreCase){
 ["advogados"]=(",nome,oab,uf_oab,email,telefone,area",",@Descricao,j->>'oab',j->>'ufOab',j->>'email',j->>'telefone',j->>'area'"),["partes"]=(",tipo_pessoa,nome_razao_social,cpf_cnpj,contato,endereco,tipo",",j->>'tipoPessoa',@Descricao,j->>'cpfCnpj',j->>'contato',j->>'endereco',j->>'tipo'"),
 ["processos"]=(",numero_interno,numero_judicial_cnj,area,natureza,assunto,objeto,valor_causa,vara_orgao,comarca,instancia,advogado_id,referencia_externa",",@Codigo,j->>'numeroCnj',j->>'area',j->>'natureza',@Descricao,j->>'objeto',coalesce((j->>'valorCausa')::numeric,0),j->>'varaOrgao',j->>'comarca',j->>'instancia',nullif(j->>'advogadoId','')::bigint,j->>'referenciaExterna'"),
 ["movimentacoes"]=(",processo_id,data_movimentacao,tipo,responsavel,resultado",",(j->>'processoId')::bigint,coalesce((j->>'data')::timestamptz,now()),j->>'tipo',j->>'responsavel',j->>'resultado'"),["prazos"]=(",processo_id,origem,data_inicio,data_limite,advogado_id",",(j->>'processoId')::bigint,j->>'origem',(j->>'dataInicio')::date,(j->>'dataLimite')::date,nullif(j->>'advogadoId','')::bigint"),
 ["intimacoes"]=(",processo_id,data_recebimento,meio,resumo,prazo_id",",(j->>'processoId')::bigint,(j->>'dataRecebimento')::date,j->>'meio',@Descricao,nullif(j->>'prazoId','')::bigint"),["audiencias"]=(",processo_id,data_hora,local_link,tipo,advogado_id,resultado",",(j->>'processoId')::bigint,(j->>'dataHora')::timestamptz,j->>'localLink',j->>'tipo',nullif(j->>'advogadoId','')::bigint,j->>'resultado'"),
 ["consultas"]=(",secretaria_setor,solicitante,assunto,data_solicitacao",",j->>'secretariaSetor',j->>'solicitante',@Descricao,(j->>'dataSolicitacao')::date"),["pareceres"]=(",consulta_id,processo_id,ementa,fundamentacao,conclusao,advogado_id",",nullif(j->>'consultaId','')::bigint,nullif(j->>'processoId','')::bigint,j->>'ementa',j->>'fundamentacao',j->>'conclusao',nullif(j->>'advogadoId','')::bigint"),
 ["acordos"]=(",processo_id,parte_id,valor,condicoes,data_assinatura,vigencia_inicio,vigencia_fim",",(j->>'processoId')::bigint,nullif(j->>'parteId','')::bigint,coalesce((j->>'valor')::numeric,0),j->>'condicoes',nullif(j->>'dataAssinatura','')::date,nullif(j->>'vigenciaInicio','')::date,nullif(j->>'vigenciaFim','')::date"),["dividaativa"]=(",processo_id,inscricao_certidao,parte_id,valor_principal,multa,juros,correcao,valor_atualizado,referencia_tributaria",",(j->>'processoId')::bigint,@Codigo,nullif(j->>'parteId','')::bigint,coalesce((j->>'valorPrincipal')::numeric,0),coalesce((j->>'multa')::numeric,0),coalesce((j->>'juros')::numeric,0),coalesce((j->>'correcao')::numeric,0),coalesce((j->>'valorAtualizado')::numeric,0),j->>'referenciaTributaria'"),["custas"]=(",processo_id,tipo,valor,vencimento,pagamento",",(j->>'processoId')::bigint,j->>'tipo',(j->>'valor')::numeric,nullif(j->>'vencimento','')::date,nullif(j->>'pagamento','')::date"),
 ["auditoria"]=(",acao,recurso,usuario_id,correlation_id",",'CONSULTA','auditoria',@UsuarioId,@CorrelationId")};
 public async Task<JuridicoDashboard> DashboardAsync(JuridicoContexto c,CancellationToken ct){using var cn=db.CreateConnection();const string sql="""select (select count(*) from sigov.juridico_processo where tenant_id=@TenantId and entidade_id=@EntidadeId and ativo and not is_deleted and status in ('ATIVO','EM_RECURSO','EM_ACORDO')) ProcessosAtivos,(select count(*) from sigov.juridico_prazo where tenant_id=@TenantId and entidade_id=@EntidadeId and ativo and not is_deleted and status='ABERTO' and data_limite<current_date) PrazosVencidos,(select count(*) from sigov.juridico_prazo where tenant_id=@TenantId and entidade_id=@EntidadeId and ativo and not is_deleted and status='ABERTO' and data_limite between current_date and current_date+7) PrazosSeteDias,(select count(*) from sigov.juridico_intimacao where tenant_id=@TenantId and entidade_id=@EntidadeId and ativo and not is_deleted and status in ('RECEBIDA','EM_ANALISE')) IntimacoesPendentes,(select count(*) from sigov.juridico_audiencia where tenant_id=@TenantId and entidade_id=@EntidadeId and ativo and not is_deleted and status='AGENDADA') AudienciasAgendadas,(select count(*) from sigov.juridico_parecer where tenant_id=@TenantId and entidade_id=@EntidadeId and ativo and not is_deleted and status in ('RASCUNHO','EM_ANALISE','REVISAO')) PareceresPendentes,(select count(*) from sigov.juridico_acordo where tenant_id=@TenantId and entidade_id=@EntidadeId and ativo and not is_deleted and status='ATIVO') AcordosAtivos,(select count(*) from sigov.juridico_obrigacao_acordo where tenant_id=@TenantId and entidade_id=@EntidadeId and ativo and not is_deleted and status in ('PENDENTE','VENCIDA') and vencimento<current_date) ObrigacoesVencidas,(select count(*) from sigov.juridico_divida_ativa_judicial where tenant_id=@TenantId and entidade_id=@EntidadeId and ativo and not is_deleted and status not in ('QUITADA','CANCELADA')) DividasEmAberto,(select coalesce(sum(valor),0) from sigov.juridico_custas where tenant_id=@TenantId and entidade_id=@EntidadeId and ativo and not is_deleted and created_at>=date_trunc('month',current_date)) CustasPeriodo""";return await cn.QuerySingleAsync<JuridicoDashboard>(new CommandDefinition(sql,c,cancellationToken:ct));}
 public async Task<JuridicoPagina> ListarAsync(JuridicoContexto c,string recurso,JuridicoFiltro f,CancellationToken ct){var t=Table(recurso);using var cn=db.CreateConnection();var p=Math.Max(1,f.Pagina);var s=Math.Clamp(f.Tamanho,1,100);var a=new{c.TenantId,c.EntidadeId,f.Busca,f.Status,Limit=s,Offset=(p-1)*s};var w="tenant_id=@TenantId and entidade_id=@EntidadeId and ativo and not is_deleted and (@Busca is null or coalesce(codigo,'') ilike '%'||@Busca||'%' or descricao ilike '%'||@Busca||'%') and (@Status is null or status=@Status)";var total=await cn.ExecuteScalarAsync<long>($"select count(*) from sigov.{t} where {w}",a);var rows=(await cn.QueryAsync<JuridicoRegistro>($"select id,coalesce(codigo,'') codigo,descricao,status,created_at CriadoEm from sigov.{t} where {w} order by updated_at desc limit @Limit offset @Offset",a)).AsList();return new(rows,p,s,total);}
 public async Task<long> SalvarAsync(JuridicoContexto c,string recurso,JuridicoRegistroRequest r,long? id,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Descricao))throw new ArgumentException("Descrição é obrigatória.");var json=Validate(r,recurso);using var cn=db.CreateConnection();cn.Open();using var tx=cn.BeginTransaction();var t=Table(recurso);var e=Extras[recurso];var a=new{r.Codigo,r.Descricao,r.Status,r.Justificativa,DadosJson=json,c.TenantId,c.EntidadeId,c.UsuarioId,c.CorrelationId,id};var sql=id is null?$"with x as(select cast(@DadosJson as jsonb) j) insert into sigov.{t}(codigo,descricao,status,justificativa,dados,tenant_id,entidade_id,created_by{e.Columns}) select @Codigo,@Descricao,@Status,@Justificativa,j,@TenantId,@EntidadeId,@UsuarioId{e.Values} from x returning id":$"update sigov.{t} set codigo=@Codigo,descricao=@Descricao,status=@Status,justificativa=@Justificativa,dados=cast(@DadosJson as jsonb),updated_at=now(),updated_by=@UsuarioId where id=@id and tenant_id=@TenantId and entidade_id=@EntidadeId and ativo and not is_deleted returning id";var saved=await cn.ExecuteScalarAsync<long?>(new CommandDefinition(sql,a,tx,cancellationToken:ct))??throw new KeyNotFoundException("Registro não encontrado.");await Trace(c,cn,id is null?"CRIAR":"ALTERAR",recurso,saved,json,tx,ct);tx.Commit();return saved;}
 public async Task ExcluirAsync(JuridicoContexto c,string recurso,long id,string justificativa,CancellationToken ct){if(string.IsNullOrWhiteSpace(justificativa))throw new ArgumentException("Justificativa é obrigatória.");using var cn=db.CreateConnection();cn.Open();using var tx=cn.BeginTransaction();var n=await cn.ExecuteAsync(new CommandDefinition($"update sigov.{Table(recurso)} set ativo=false,is_deleted=true,deleted_at=now(),deleted_by=@UsuarioId,justificativa=@justificativa where id=@id and tenant_id=@TenantId and entidade_id=@EntidadeId and ativo and not is_deleted",new{id,justificativa,c.UsuarioId,c.TenantId,c.EntidadeId},tx,cancellationToken:ct));if(n==0)throw new KeyNotFoundException("Registro não encontrado.");await Trace(c,cn,"EXCLUIR",recurso,id,"{}",tx,ct);tx.Commit();}
 public async Task<byte[]> ExportarCsvAsync(JuridicoContexto c,string recurso,CancellationToken ct){using var cn=db.CreateConnection();cn.Open();using var tx=cn.BeginTransaction();var rows=await cn.QueryAsync<dynamic>(new CommandDefinition($"select id,coalesce(codigo,'') codigo,descricao,status,created_at from sigov.{Table(recurso)} where tenant_id=@TenantId and entidade_id=@EntidadeId and ativo and not is_deleted order by id",c,tx,cancellationToken:ct));var b=new StringBuilder("id;codigo;descricao;status;criado_em\r\n");foreach(var x in rows)b.AppendLine($"{x.id};{Csv(x.codigo)};{Csv(x.descricao)};{Csv(x.status)};{x.created_at:O}");await Trace(c,cn,"EXPORTAR",recurso,null,"{}",tx,ct);tx.Commit();return new UTF8Encoding(true).GetBytes(b.ToString());}
 private static string Validate(JuridicoRegistroRequest r,string recurso){var json=string.IsNullOrWhiteSpace(r.DadosJson)?"{}":r.DadosJson;JsonElement d;try{using var doc=JsonDocument.Parse(json);if(doc.RootElement.ValueKind!=JsonValueKind.Object)throw new ArgumentException("Dados devem ser objeto JSON.");d=doc.RootElement.Clone();}catch(JsonException){throw new ArgumentException("Dados complementares devem ser JSON válido.");}if((r.Status is "INATIVO" or "SUSPENSO" or "ARQUIVADO" or "ENCERRADO" or "CANCELADO" or "CANCELADA" or "REMARCADA" or "DESCUMPRIDO" or "QUITADA" or "CUMPRIDO")&&string.IsNullOrWhiteSpace(r.Justificativa))throw new ArgumentException("Este estado exige justificativa.");if(recurso=="pareceres"&&r.Status=="EMITIDO"&&(!d.TryGetProperty("conclusao",out var x)||string.IsNullOrWhiteSpace(x.GetString())))throw new ArgumentException("Emitir parecer exige conclusão.");return json;}
 private static string Table(string r)=>Tables.TryGetValue(r,out var t)?t:throw new ArgumentException("Recurso jurídico inválido.");private static string Csv(object? v){var s=Convert.ToString(v,CultureInfo.InvariantCulture)??"";if(s.Length>0&&"=+-@".Contains(s[0]))s="'"+s;return '"'+s.Replace("\"","\"\"")+'"';}
 private static async Task Trace(JuridicoContexto c,System.Data.IDbConnection cn,string acao,string recurso,long? id,string depois,System.Data.IDbTransaction tx,CancellationToken ct){var p=new{c.TenantId,c.EntidadeId,c.UsuarioId,c.CorrelationId,c.Ip,acao,recurso,id,depois};await cn.ExecuteAsync(new CommandDefinition("insert into sigov.juridico_historico(tenant_id,entidade_id,codigo,descricao,status,recurso,registro_id,acao,estado_novo,usuario_id,created_by) values(@TenantId,@EntidadeId,'',@recurso,'REGISTRADO',@recurso,coalesce(@id,0),@acao,cast(@depois as jsonb),@UsuarioId,@UsuarioId)",p,tx,cancellationToken:ct));await cn.ExecuteAsync(new CommandDefinition("insert into sigov.juridico_auditoria(tenant_id,entidade_id,codigo,descricao,status,acao,recurso,registro_id,usuario_id,depois,correlation_id,ip,created_by) values(@TenantId,@EntidadeId,'',@recurso,'REGISTRADA',@acao,@recurso,@id,@UsuarioId,'{}'::jsonb,@CorrelationId,cast(@Ip as inet),@UsuarioId)",p,tx,cancellationToken:ct));}
}
