using Microsoft.Extensions.Logging;
using Sigov.Application.Agro.Permissions;
using Sigov.Application.Auditoria;
using Sigov.Application.Common;
using Sigov.Domain.Common;

namespace Sigov.Application.Agro.Produtores;

public sealed class AgroProdutorService : IAgroProdutorService
{
    private readonly AgroProdutorPermissionChecker _permission; private readonly AgroProdutorValidator _validator; private readonly AgroProdutorAuditWriter _audit; private readonly IAgroProdutorRepository _repository; private readonly AcessoDadoPessoalService _lgpd; private readonly ILogger<AgroProdutorService> _logger;
    public AgroProdutorService(AgroProdutorPermissionChecker permission, AgroProdutorValidator validator, AgroProdutorAuditWriter audit, IAgroProdutorRepository repository, AcessoDadoPessoalService lgpd, ILogger<AgroProdutorService> logger) { _permission = permission; _validator = validator; _audit = audit; _repository = repository; _lgpd = lgpd; _logger = logger; }
    public async Task<Result<PagedResult<AgroProdutorResponse>>> ListarAsync(AgroProdutorFiltro filtro, CancellationToken cancellationToken)
    { var c = await Ctx(AgroPermissions.ProdutorVisualizar, cancellationToken).ConfigureAwait(false); if (c.IsFailure) return Result<PagedResult<AgroProdutorResponse>>.Failure(c.Error!); var e = Ent(c.Value!); if (e.IsFailure) return Result<PagedResult<AgroProdutorResponse>>.Failure(e.Error!); return Result<PagedResult<AgroProdutorResponse>>.Success(await _repository.ListarAsync(c.Value!.TenantId, c.Value!.EntidadeId!.Value, Page(filtro), cancellationToken).ConfigureAwait(false)); }
    public async Task<Result<AgroProdutorDetalheResponse>> ObterAsync(long id, bool dadosCompletos, CancellationToken cancellationToken)
    { var c = await Ctx(dadosCompletos ? AgroPermissions.ProdutorVisualizarDadosCompletos : AgroPermissions.ProdutorVisualizar, cancellationToken).ConfigureAwait(false); if (c.IsFailure) return Result<AgroProdutorDetalheResponse>.Failure(c.Error!); var e = Ent(c.Value!); if (e.IsFailure) return Result<AgroProdutorDetalheResponse>.Failure(e.Error!); var row = await _repository.ObterAsync(c.Value!.TenantId, c.Value!.EntidadeId!.Value, id, dadosCompletos, cancellationToken).ConfigureAwait(false); if (row is null) return Result<AgroProdutorDetalheResponse>.Failure("Produtor não encontrado."); await _repository.RegistrarAcessoDadoPessoalAsync(c.Value.TenantId, c.Value.EntidadeId.Value, row.PessoaId, c.Value.UsuarioId, _lgpd.BuildFinalidade("produtor rural"), cancellationToken).ConfigureAwait(false); return Result<AgroProdutorDetalheResponse>.Success(row); }
    public async Task<Result<long>> CriarAsync(AgroProdutorCreateRequest request, CancellationToken cancellationToken)
    { var c = await Ctx(AgroPermissions.ProdutorCriar, cancellationToken).ConfigureAwait(false); if (c.IsFailure) return Result<long>.Failure(c.Error!); var e = Ent(c.Value!); if (e.IsFailure) return Result<long>.Failure(e.Error!); var v = _validator.ValidarCriacao(request); if (v.IsFailure) return Result<long>.Failure(v.Error!); var codigo = string.IsNullOrWhiteSpace(request.CodigoProdutor) ? $"AGR-PROD-{DateTime.UtcNow.Year:D4}-{DateTime.UtcNow.Ticks % 1000000:D6}" : request.CodigoProdutor!; var id = await _repository.CriarAsync(c.Value!.TenantId, c.Value.EntidadeId!.Value, c.Value.UsuarioId, request, codigo, cancellationToken).ConfigureAwait(false); await _audit.WriteAsync("CRIAR", id.ToString(System.Globalization.CultureInfo.InvariantCulture), null, request with { CodigoProdutor = codigo }, cancellationToken).ConfigureAwait(false); _logger.LogInformation("Produtor Agro {Id} criado.", id); return Result<long>.Success(id); }
    public async Task<Result> AtualizarAsync(long id, AgroProdutorUpdateRequest request, CancellationToken cancellationToken)
    { var c = await Ctx(AgroPermissions.ProdutorEditar, cancellationToken).ConfigureAwait(false); if (c.IsFailure) return Result.Failure(c.Error!); var e = Ent(c.Value!); if (e.IsFailure) return e; var v = _validator.ValidarAtualizacao(request); if (v.IsFailure) return v; await _repository.AtualizarAsync(c.Value!.TenantId, c.Value.EntidadeId!.Value, id, c.Value.UsuarioId, request, cancellationToken).ConfigureAwait(false); await _audit.WriteAsync("EDITAR", id.ToString(System.Globalization.CultureInfo.InvariantCulture), null, request, cancellationToken).ConfigureAwait(false); return Result.Success(); }
    public async Task<Result> ExcluirAsync(long id, CancellationToken cancellationToken)
    { var c = await Ctx(AgroPermissions.ProdutorExcluir, cancellationToken).ConfigureAwait(false); if (c.IsFailure) return Result.Failure(c.Error!); var e = Ent(c.Value!); if (e.IsFailure) return e; await _repository.ExcluirAsync(c.Value!.TenantId, c.Value.EntidadeId!.Value, id, c.Value.UsuarioId, cancellationToken).ConfigureAwait(false); await _audit.WriteAsync("EXCLUIR", id.ToString(System.Globalization.CultureInfo.InvariantCulture), null, new { isDeleted = true }, cancellationToken).ConfigureAwait(false); return Result.Success(); }
    private Task<Result<AgroAccessContext>> Ctx(string p, CancellationToken ct) => _permission.CheckAsync(p, ct);
    private static Result Ent(AgroAccessContext c) => c.EntidadeId.HasValue ? Result.Success() : Result.Failure("Entidade atual obrigatória para Agro.");
    private static AgroProdutorFiltro Page(AgroProdutorFiltro f) => f with { Page = Math.Max(1, f.Page), PageSize = Math.Clamp(f.PageSize, 1, 100) };
}
