using Microsoft.Extensions.Logging;
using Sigov.Application.Agro.Permissions;
using Sigov.Application.Common;
using Sigov.Domain.Agro;
using Sigov.Domain.Agro.Enums;
using Sigov.Domain.Common;

namespace Sigov.Application.Agro.PatrulhaMecanizada;

public sealed class AgroMaquinaValidator { public Result Validar(AgroMaquinaCreateRequest r)=>Validar(r.Codigo,r.Nome,r.TipoMaquina,r.Situacao,r.HorimetroAtual,r.OdometroAtual); public Result Validar(AgroMaquinaUpdateRequest r)=>Validar(r.Codigo,r.Nome,r.TipoMaquina,r.Situacao,r.HorimetroAtual,r.OdometroAtual); private static Result Validar(string c,string n,string t,string s,decimal? h,decimal? o){ if(!Enum.TryParse<AgroMaquinaTipo>(t,true,out var tipo)) return Result.Failure("Tipo de máquina inválido."); if(!Enum.TryParse<AgroMaquinaSituacao>(s,true,out var sit)) return Result.Failure("Situação da máquina inválida."); try{ _=new MaquinaRural(1,1,c,n,tipo,sit,h,o); return Result.Success(); }catch(Exception ex){ return Result.Failure(ex.Message);} } }
public sealed class AgroImplementoValidator { public Result Validar(AgroImplementoCreateRequest r){ try{ _=new ImplementoRural(1,1,r.Codigo,r.Nome,r.TipoImplemento,r.Situacao); return Result.Success(); }catch(Exception ex){ return Result.Failure(ex.Message);} } }
public sealed class AgroAgendaMaquinaValidator { public async Task<Result> ValidarAsync(AgroAgendaMaquinaCreateRequest r,IAgroPatrulhaMecanizadaRepository repo,long tenantId,long entidadeId,CancellationToken ct){ if(!Enum.TryParse<AgroAgendaMaquinaStatus>(r.Status,true,out var status)) return Result.Failure("Status da agenda inválido."); try{ _=new AgendaMaquinaRural(tenantId,entidadeId,null,r.MaquinaId,r.DataInicio,r.DataFim,status); }catch(Exception ex){ return Result.Failure(ex.Message);} if(await repo.ExisteConflitoAgendaAsync(tenantId,entidadeId,r.MaquinaId,r.DataInicio,r.DataFim,null,ct)) return Result.Failure("Não pode haver sobreposição de agenda para a mesma máquina."); return Result.Success(); } }
public sealed class AgroServicoMaquinaValidator { public Result Validar(AgroServicoMaquinaCreateRequest r){ if(!Enum.TryParse<AgroServicoMaquinaTipo>(r.TipoServico,true,out var tipo)) return Result.Failure("Tipo de serviço é obrigatório."); try{ _=new ServicoMaquinaRural(1,1,1,r.ProdutorId,"TMP",tipo,AgroServicoMaquinaStatus.SOLICITADO); return Result.Success(); }catch(Exception ex){ return Result.Failure(ex.Message);} } public Result ValidarExecucao(ExecutarServicoMaquinaRequest r){ try{ _=new ServicoMaquinaRural(1,1,1,1,"TMP",AgroServicoMaquinaTipo.OUTROS,AgroServicoMaquinaStatus.EXECUTADO,r.DataExecucao,r.HorasTrabalhadas,r.AreaAtendidaHa,r.HorimetroInicial,r.HorimetroFinal,r.OdometroInicial,r.OdometroFinal,r.ValorCobrado); return Result.Success(); }catch(Exception ex){ return Result.Failure(ex.Message);} } }
public sealed class AgroMaquinaPermissionChecker { private readonly IAgroAccessChecker _access; public AgroMaquinaPermissionChecker(IAgroAccessChecker access)=>_access=access; public Task<Result<AgroAccessContext>> CheckAsync(string p,string f,CancellationToken ct)=>_access.CheckAsync(new AgroAccessRequest(p,f),ct); }
public sealed class AgroServicoMaquinaPermissionChecker { private readonly IAgroAccessChecker _access; public AgroServicoMaquinaPermissionChecker(IAgroAccessChecker access)=>_access=access; public Task<Result<AgroAccessContext>> CheckAsync(string p,string f,CancellationToken ct)=>_access.CheckAsync(new AgroAccessRequest(p,f),ct); }
public sealed class AgroMaquinaAuditWriter { private readonly ILogger<AgroMaquinaAuditWriter> _logger; public AgroMaquinaAuditWriter(ILogger<AgroMaquinaAuditWriter> logger)=>_logger=logger; public Task WriteAsync(string t,string a,long id,object d,CancellationToken ct){_logger.LogInformation("Auditoria Agro {Acao} em {Tabela} #{Id}.",a,t,id); return Task.CompletedTask;} }
public sealed class AgroServicoMaquinaAuditWriter { private readonly ILogger<AgroServicoMaquinaAuditWriter> _logger; public AgroServicoMaquinaAuditWriter(ILogger<AgroServicoMaquinaAuditWriter> logger)=>_logger=logger; public Task WriteAsync(string t,string a,long id,object d,CancellationToken ct){_logger.LogInformation("Auditoria Agro {Acao} em {Tabela} #{Id}.",a,t,id); return Task.CompletedTask;} }
public sealed class AgroServicoMaquinaMapper { public string Numero(AgroServicoMaquinaCreateRequest r)=>string.IsNullOrWhiteSpace(r.Numero)?$"AGR-MAQ-{DateTime.UtcNow.Year:D4}-{DateTime.UtcNow.Ticks%1000000:D6}":r.Numero!; }

public sealed class AgroMaquinaService : IAgroMaquinaService
{
    private readonly AgroMaquinaPermissionChecker _permission; private readonly AgroMaquinaValidator _validator; private readonly AgroMaquinaAuditWriter _audit; private readonly IAgroPatrulhaMecanizadaRepository _repo; public AgroMaquinaService(AgroMaquinaPermissionChecker permission,AgroMaquinaValidator validator,AgroMaquinaAuditWriter audit,IAgroPatrulhaMecanizadaRepository repo){_permission=permission;_validator=validator;_audit=audit;_repo=repo;}
    public async Task<Result<PagedResult<AgroMaquinaResponse>>> ListarAsync(AgroMaquinaFiltro filtro,CancellationToken ct){var c=await Ctx(AgroPermissions.MaquinaVisualizar,"agro.maquinas",ct); if(c.IsFailure)return Result<PagedResult<AgroMaquinaResponse>>.Failure(c.Error!); return Result<PagedResult<AgroMaquinaResponse>>.Success(await _repo.ListarMaquinasAsync(c.Value!.TenantId,c.Value.EntidadeId!.Value,Page(filtro),ct));}
    public async Task<Result<AgroMaquinaResponse>> ObterAsync(long id,CancellationToken ct){var c=await Ctx(AgroPermissions.MaquinaVisualizar,"agro.maquinas",ct); if(c.IsFailure)return Result<AgroMaquinaResponse>.Failure(c.Error!); var row=await _repo.ObterMaquinaAsync(c.Value!.TenantId,c.Value.EntidadeId!.Value,id,ct); return row is null?Result<AgroMaquinaResponse>.Failure("Máquina não encontrada."):Result<AgroMaquinaResponse>.Success(row);}
    public async Task<Result<long>> CriarAsync(AgroMaquinaCreateRequest request,CancellationToken ct){var c=await Ctx(AgroPermissions.MaquinaCriar,"agro.maquinas",ct); if(c.IsFailure)return Result<long>.Failure(c.Error!); var v=_validator.Validar(request); if(v.IsFailure)return Result<long>.Failure(v.Error!); var id=await _repo.CriarMaquinaAsync(c.Value!.TenantId,c.Value.EntidadeId!.Value,c.Value.UsuarioId,request,ct); await _audit.WriteAsync("sigov.agro_maquina","CRIAR",id,request,ct); return Result<long>.Success(id);}
    public async Task<Result> AtualizarAsync(long id,AgroMaquinaUpdateRequest request,CancellationToken ct){var c=await Ctx(AgroPermissions.MaquinaEditar,"agro.maquinas",ct); if(c.IsFailure)return Result.Failure(c.Error!); var v=_validator.Validar(request); if(v.IsFailure)return v; await _repo.AtualizarMaquinaAsync(c.Value!.TenantId,c.Value.EntidadeId!.Value,id,c.Value.UsuarioId,request,ct); return Result.Success();}
    public async Task<Result> ExcluirAsync(long id,CancellationToken ct){var c=await Ctx(AgroPermissions.MaquinaExcluir,"agro.maquinas",ct); if(c.IsFailure)return Result.Failure(c.Error!); await _repo.ExcluirMaquinaAsync(c.Value!.TenantId,c.Value.EntidadeId!.Value,id,c.Value.UsuarioId,ct); return Result.Success();}
    public async Task<Result<AgroPatrulhaResumoResponse>> ResumoAsync(CancellationToken ct){var c=await Ctx(AgroPermissions.MaquinaVisualizar,"agro.patrulha_mecanizada",ct); if(c.IsFailure)return Result<AgroPatrulhaResumoResponse>.Failure(c.Error!); return Result<AgroPatrulhaResumoResponse>.Success(await _repo.ObterResumoAsync(c.Value!.TenantId,c.Value.EntidadeId!.Value,ct));}
    private async Task<Result<AgroAccessContext>> Ctx(string p,string f,CancellationToken ct){var c=await _permission.CheckAsync(p,f,ct); if(c.IsFailure)return c; return c.Value!.EntidadeId.HasValue?c:Result<AgroAccessContext>.Failure("Entidade atual é obrigatória para Agro.");} private static AgroMaquinaFiltro Page(AgroMaquinaFiltro f)=>f with{Page=Math.Max(1,f.Page),PageSize=Math.Clamp(f.PageSize,1,100)};
}

public sealed class AgroImplementoService : IAgroImplementoService
{
    private readonly IAgroAccessChecker _access; private readonly AgroImplementoValidator _validator; private readonly IAgroPatrulhaMecanizadaRepository _repo; public AgroImplementoService(IAgroAccessChecker access,AgroImplementoValidator validator,IAgroPatrulhaMecanizadaRepository repo){_access=access;_validator=validator;_repo=repo;}
    public async Task<Result<PagedResult<AgroImplementoResponse>>> ListarAsync(AgroMaquinaFiltro filtro,CancellationToken ct){var c=await Ctx(AgroPermissions.ImplementoVisualizar,ct); if(c.IsFailure)return Result<PagedResult<AgroImplementoResponse>>.Failure(c.Error!); return Result<PagedResult<AgroImplementoResponse>>.Success(await _repo.ListarImplementosAsync(c.Value!.TenantId,c.Value.EntidadeId!.Value,filtro,ct));}
    public async Task<Result<long>> CriarAsync(AgroImplementoCreateRequest request,CancellationToken ct){var c=await Ctx(AgroPermissions.ImplementoCriar,ct); if(c.IsFailure)return Result<long>.Failure(c.Error!); var v=_validator.Validar(request); if(v.IsFailure)return Result<long>.Failure(v.Error!); return Result<long>.Success(await _repo.CriarImplementoAsync(c.Value!.TenantId,c.Value.EntidadeId!.Value,c.Value.UsuarioId,request,ct));}
    private async Task<Result<AgroAccessContext>> Ctx(string p,CancellationToken ct){var c=await _access.CheckAsync(new AgroAccessRequest(p,"agro.patrulha_mecanizada"),ct); if(c.IsFailure)return c; return c.Value!.EntidadeId.HasValue?c:Result<AgroAccessContext>.Failure("Entidade atual é obrigatória para Agro.");}
}
public sealed class AgroAgendaMaquinaService : IAgroAgendaMaquinaService
{
    private readonly IAgroAccessChecker _access; private readonly AgroAgendaMaquinaValidator _validator; private readonly IAgroPatrulhaMecanizadaRepository _repo; public AgroAgendaMaquinaService(IAgroAccessChecker access,AgroAgendaMaquinaValidator validator,IAgroPatrulhaMecanizadaRepository repo){_access=access;_validator=validator;_repo=repo;}
    public async Task<Result<PagedResult<AgroAgendaMaquinaResponse>>> ListarAsync(AgroMaquinaFiltro filtro,CancellationToken ct){var c=await Ctx(AgroPermissions.ServicoMaquinaAgendar,ct); if(c.IsFailure)return Result<PagedResult<AgroAgendaMaquinaResponse>>.Failure(c.Error!); return Result<PagedResult<AgroAgendaMaquinaResponse>>.Success(await _repo.ListarAgendaAsync(c.Value!.TenantId,c.Value.EntidadeId!.Value,filtro,ct));}
    public async Task<Result<long>> CriarAsync(AgroAgendaMaquinaCreateRequest request,CancellationToken ct){var c=await Ctx(AgroPermissions.ServicoMaquinaAgendar,ct); if(c.IsFailure)return Result<long>.Failure(c.Error!); var v=await _validator.ValidarAsync(request,_repo,c.Value!.TenantId,c.Value.EntidadeId!.Value,ct); if(v.IsFailure)return Result<long>.Failure(v.Error!); return Result<long>.Success(await _repo.CriarAgendaAsync(c.Value.TenantId,c.Value.EntidadeId.Value,c.Value.ExercicioId,c.Value.UsuarioId,request,ct));}
    private async Task<Result<AgroAccessContext>> Ctx(string p,CancellationToken ct){var c=await _access.CheckAsync(new AgroAccessRequest(p,"agro.patrulha_mecanizada"),ct); if(c.IsFailure)return c; return c.Value!.EntidadeId.HasValue?c:Result<AgroAccessContext>.Failure("Entidade atual é obrigatória para Agro.");}
}
public sealed class AgroServicoMaquinaService : IAgroServicoMaquinaService
{
    private readonly AgroServicoMaquinaPermissionChecker _permission; private readonly AgroServicoMaquinaValidator _validator; private readonly AgroServicoMaquinaAuditWriter _audit; private readonly AgroServicoMaquinaMapper _mapper; private readonly IAgroPatrulhaMecanizadaRepository _repo; public AgroServicoMaquinaService(AgroServicoMaquinaPermissionChecker permission,AgroServicoMaquinaValidator validator,AgroServicoMaquinaAuditWriter audit,AgroServicoMaquinaMapper mapper,IAgroPatrulhaMecanizadaRepository repo){_permission=permission;_validator=validator;_audit=audit;_mapper=mapper;_repo=repo;}
    public async Task<Result<PagedResult<AgroServicoMaquinaResponse>>> ListarAsync(AgroServicoMaquinaFiltro filtro,CancellationToken ct){var c=await Ctx(AgroPermissions.ServicoMaquinaVisualizar,ct); if(c.IsFailure)return Result<PagedResult<AgroServicoMaquinaResponse>>.Failure(c.Error!); return Result<PagedResult<AgroServicoMaquinaResponse>>.Success(await _repo.ListarServicosAsync(c.Value!.TenantId,c.Value.EntidadeId!.Value,Page(filtro),ct));}
    public async Task<Result<AgroServicoMaquinaResponse>> ObterAsync(long id,CancellationToken ct){var c=await Ctx(AgroPermissions.ServicoMaquinaVisualizar,ct); if(c.IsFailure)return Result<AgroServicoMaquinaResponse>.Failure(c.Error!); var row=await _repo.ObterServicoAsync(c.Value!.TenantId,c.Value.EntidadeId!.Value,id,ct); return row is null?Result<AgroServicoMaquinaResponse>.Failure("Serviço de máquina não encontrado."):Result<AgroServicoMaquinaResponse>.Success(row);}
    public async Task<Result<long>> CriarAsync(AgroServicoMaquinaCreateRequest request,CancellationToken ct){var c=await Ctx(AgroPermissions.ServicoMaquinaCriar,ct); if(c.IsFailure)return Result<long>.Failure(c.Error!); var v=_validator.Validar(request); if(v.IsFailure)return Result<long>.Failure(v.Error!); var id=await _repo.CriarServicoAsync(c.Value!.TenantId,c.Value.EntidadeId!.Value,c.Value.ExercicioId,c.Value.UsuarioId,request,_mapper.Numero(request),ct); await _audit.WriteAsync("sigov.agro_servico_maquina","CRIAR",id,request,ct); return Result<long>.Success(id);}
    public async Task<Result> AtualizarAsync(long id,AgroServicoMaquinaUpdateRequest request,CancellationToken ct){var c=await Ctx(AgroPermissions.ServicoMaquinaEditar,ct); if(c.IsFailure)return Result.Failure(c.Error!); await _repo.AtualizarServicoAsync(c.Value!.TenantId,c.Value.EntidadeId!.Value,id,c.Value.UsuarioId,request,ct); return Result.Success();}
    public async Task<Result> AgendarAsync(long id,AgendarServicoMaquinaRequest request,CancellationToken ct){var c=await Ctx(AgroPermissions.ServicoMaquinaAgendar,ct); if(c.IsFailure)return Result.Failure(c.Error!); if(request.DataInicio.HasValue&&request.DataFim.HasValue&&await _repo.ExisteConflitoAgendaAsync(c.Value!.TenantId,c.Value.EntidadeId!.Value,request.MaquinaId,request.DataInicio.Value,request.DataFim.Value,null,ct)) return Result.Failure("Não pode haver sobreposição de agenda para a mesma máquina."); await _repo.AgendarServicoAsync(c.Value!.TenantId,c.Value.EntidadeId!.Value,id,c.Value.ExercicioId,c.Value.UsuarioId,request,ct); return Result.Success();}
    public async Task<Result> ExecutarAsync(long id,ExecutarServicoMaquinaRequest request,CancellationToken ct){var c=await Ctx(AgroPermissions.ServicoMaquinaExecutar,ct); if(c.IsFailure)return Result.Failure(c.Error!); var v=_validator.ValidarExecucao(request); if(v.IsFailure)return v; await _repo.ExecutarServicoAsync(c.Value!.TenantId,c.Value.EntidadeId!.Value,id,c.Value.UsuarioId,request,ct); await _audit.WriteAsync("sigov.agro_servico_maquina","EXECUTAR",id,request,ct); return Result.Success();}
    public async Task<Result> CancelarAsync(long id,CancelarServicoMaquinaRequest request,CancellationToken ct){var c=await Ctx(AgroPermissions.ServicoMaquinaCancelar,ct); if(c.IsFailure)return Result.Failure(c.Error!); await _repo.CancelarServicoAsync(c.Value!.TenantId,c.Value.EntidadeId!.Value,id,c.Value.UsuarioId,request.Motivo,ct); return Result.Success();}
    public async Task<Result> ExcluirAsync(long id,CancellationToken ct){var c=await Ctx(AgroPermissions.ServicoMaquinaExcluir,ct); if(c.IsFailure)return Result.Failure(c.Error!); await _repo.ExcluirServicoAsync(c.Value!.TenantId,c.Value.EntidadeId!.Value,id,c.Value.UsuarioId,ct); return Result.Success();}
    private async Task<Result<AgroAccessContext>> Ctx(string p,CancellationToken ct){var c=await _permission.CheckAsync(p,"agro.servicos_maquina",ct); if(c.IsFailure)return c; return c.Value!.EntidadeId.HasValue?c:Result<AgroAccessContext>.Failure("Entidade atual é obrigatória para Agro.");} private static AgroServicoMaquinaFiltro Page(AgroServicoMaquinaFiltro f)=>f with{Page=Math.Max(1,f.Page),PageSize=Math.Clamp(f.PageSize,1,100)};
}
