using Sigov.Application.Common;
using Sigov.Domain.Common;

namespace Sigov.Application.Agro.PatrulhaMecanizada;

public sealed record AgroMaquinaFiltro(int Page = 1, int PageSize = 20, string? Busca = null, string? Situacao = null);
public sealed record AgroMaquinaCreateRequest(string Codigo, string Nome, string TipoMaquina, string? Placa, decimal? HorimetroAtual, decimal? OdometroAtual, string Situacao, long? PatrimonioBemId, long? FrotaVeiculoId, string? Observacao, bool Ativo = true);
public sealed record AgroMaquinaUpdateRequest(string Codigo, string Nome, string TipoMaquina, string? Placa, decimal? HorimetroAtual, decimal? OdometroAtual, string Situacao, long? PatrimonioBemId, long? FrotaVeiculoId, string? Observacao, bool Ativo = true);
public sealed record AgroMaquinaResponse(long Id, long TenantId, long EntidadeId, string Codigo, string Nome, string TipoMaquina, string? Placa, decimal? HorimetroAtual, decimal? OdometroAtual, string Situacao, bool Ativo);
public sealed record AgroImplementoCreateRequest(long? MaquinaId, string Codigo, string Nome, string TipoImplemento, string Situacao, string? Observacao, bool Ativo = true);
public sealed record AgroImplementoResponse(long Id, long TenantId, long EntidadeId, long? MaquinaId, string Codigo, string Nome, string TipoImplemento, string Situacao, bool Ativo);
public sealed record AgroAgendaMaquinaCreateRequest(long MaquinaId, long? ServicoMaquinaId, DateTimeOffset DataInicio, DateTimeOffset DataFim, string Status, string? Observacao);
public sealed record AgroAgendaMaquinaResponse(long Id, long TenantId, long EntidadeId, long? ExercicioId, long MaquinaId, long? ServicoMaquinaId, DateTimeOffset DataInicio, DateTimeOffset DataFim, string Status, string? Observacao);
public sealed record AgroServicoMaquinaFiltro(int Page = 1, int PageSize = 20, long? ProdutorId = null, string? Status = null);
public sealed record AgroServicoMaquinaCreateRequest(long ProdutorId, long? PropriedadeId, long? MaquinaId, long? ImplementoId, string? Numero, string TipoServico, DateOnly? DataAgendada, decimal? ValorEstimado, string? Observacao);
public sealed record AgroServicoMaquinaUpdateRequest(long? PropriedadeId, long? MaquinaId, long? ImplementoId, string TipoServico, DateOnly? DataAgendada, decimal? ValorEstimado, decimal? ValorCobrado, string Status, string? Observacao);
public sealed record AgroServicoMaquinaResponse(long Id, long TenantId, long EntidadeId, long? ExercicioId, long ProdutorId, long? PropriedadeId, long? MaquinaId, long? ImplementoId, string Numero, string TipoServico, DateOnly DataSolicitacao, DateOnly? DataAgendada, DateOnly? DataExecucao, decimal? HorasTrabalhadas, decimal? AreaAtendidaHa, decimal? ValorEstimado, decimal? ValorCobrado, string Status, string ProdutorNomeMascarado);
public sealed record AgendarServicoMaquinaRequest(long MaquinaId, DateOnly DataAgendada, DateTimeOffset? DataInicio, DateTimeOffset? DataFim, string? Observacao);
public sealed record ExecutarServicoMaquinaRequest(DateOnly DataExecucao, decimal? HorasTrabalhadas, decimal? AreaAtendidaHa, decimal? HorimetroInicial, decimal? HorimetroFinal, decimal? OdometroInicial, decimal? OdometroFinal, decimal? ValorCobrado, long? OperadorUsuarioId, string? Observacao);
public sealed record CancelarServicoMaquinaRequest(string? Motivo);
public sealed record AgroPatrulhaResumoResponse(long MaquinasAtivas, long ServicosPendentes, long ServicosAgendados, long ServicosExecutadosMes, decimal HorasTrabalhadasMes, decimal AreaAtendidaMes);

public interface IAgroPatrulhaMecanizadaRepository
{
    Task<PagedResult<AgroMaquinaResponse>> ListarMaquinasAsync(long tenantId,long entidadeId,AgroMaquinaFiltro filtro,CancellationToken ct); Task<AgroMaquinaResponse?> ObterMaquinaAsync(long tenantId,long entidadeId,long id,CancellationToken ct); Task<long> CriarMaquinaAsync(long tenantId,long entidadeId,long? usuarioId,AgroMaquinaCreateRequest request,CancellationToken ct); Task AtualizarMaquinaAsync(long tenantId,long entidadeId,long id,long? usuarioId,AgroMaquinaUpdateRequest request,CancellationToken ct); Task ExcluirMaquinaAsync(long tenantId,long entidadeId,long id,long? usuarioId,CancellationToken ct);
    Task<PagedResult<AgroImplementoResponse>> ListarImplementosAsync(long tenantId,long entidadeId,AgroMaquinaFiltro filtro,CancellationToken ct); Task<long> CriarImplementoAsync(long tenantId,long entidadeId,long? usuarioId,AgroImplementoCreateRequest request,CancellationToken ct);
    Task<PagedResult<AgroAgendaMaquinaResponse>> ListarAgendaAsync(long tenantId,long entidadeId,AgroMaquinaFiltro filtro,CancellationToken ct); Task<long> CriarAgendaAsync(long tenantId,long entidadeId,long? exercicioId,long? usuarioId,AgroAgendaMaquinaCreateRequest request,CancellationToken ct); Task<bool> ExisteConflitoAgendaAsync(long tenantId,long entidadeId,long maquinaId,DateTimeOffset inicio,DateTimeOffset fim,long? ignorarId,CancellationToken ct);
    Task<PagedResult<AgroServicoMaquinaResponse>> ListarServicosAsync(long tenantId,long entidadeId,AgroServicoMaquinaFiltro filtro,CancellationToken ct); Task<AgroServicoMaquinaResponse?> ObterServicoAsync(long tenantId,long entidadeId,long id,CancellationToken ct); Task<long> CriarServicoAsync(long tenantId,long entidadeId,long? exercicioId,long? usuarioId,AgroServicoMaquinaCreateRequest request,string numero,CancellationToken ct); Task AtualizarServicoAsync(long tenantId,long entidadeId,long id,long? usuarioId,AgroServicoMaquinaUpdateRequest request,CancellationToken ct); Task AgendarServicoAsync(long tenantId,long entidadeId,long id,long? exercicioId,long? usuarioId,AgendarServicoMaquinaRequest request,CancellationToken ct); Task ExecutarServicoAsync(long tenantId,long entidadeId,long id,long? usuarioId,ExecutarServicoMaquinaRequest request,CancellationToken ct); Task CancelarServicoAsync(long tenantId,long entidadeId,long id,long? usuarioId,string? motivo,CancellationToken ct); Task ExcluirServicoAsync(long tenantId,long entidadeId,long id,long? usuarioId,CancellationToken ct); Task<AgroPatrulhaResumoResponse> ObterResumoAsync(long tenantId,long entidadeId,CancellationToken ct);
}
public interface IAgroMaquinaService { Task<Result<PagedResult<AgroMaquinaResponse>>> ListarAsync(AgroMaquinaFiltro filtro,CancellationToken ct); Task<Result<AgroMaquinaResponse>> ObterAsync(long id,CancellationToken ct); Task<Result<long>> CriarAsync(AgroMaquinaCreateRequest request,CancellationToken ct); Task<Result> AtualizarAsync(long id,AgroMaquinaUpdateRequest request,CancellationToken ct); Task<Result> ExcluirAsync(long id,CancellationToken ct); Task<Result<AgroPatrulhaResumoResponse>> ResumoAsync(CancellationToken ct); }
public interface IAgroImplementoService { Task<Result<PagedResult<AgroImplementoResponse>>> ListarAsync(AgroMaquinaFiltro filtro,CancellationToken ct); Task<Result<long>> CriarAsync(AgroImplementoCreateRequest request,CancellationToken ct); }
public interface IAgroAgendaMaquinaService { Task<Result<PagedResult<AgroAgendaMaquinaResponse>>> ListarAsync(AgroMaquinaFiltro filtro,CancellationToken ct); Task<Result<long>> CriarAsync(AgroAgendaMaquinaCreateRequest request,CancellationToken ct); }
public interface IAgroServicoMaquinaService { Task<Result<PagedResult<AgroServicoMaquinaResponse>>> ListarAsync(AgroServicoMaquinaFiltro filtro,CancellationToken ct); Task<Result<AgroServicoMaquinaResponse>> ObterAsync(long id,CancellationToken ct); Task<Result<long>> CriarAsync(AgroServicoMaquinaCreateRequest request,CancellationToken ct); Task<Result> AtualizarAsync(long id,AgroServicoMaquinaUpdateRequest request,CancellationToken ct); Task<Result> AgendarAsync(long id,AgendarServicoMaquinaRequest request,CancellationToken ct); Task<Result> ExecutarAsync(long id,ExecutarServicoMaquinaRequest request,CancellationToken ct); Task<Result> CancelarAsync(long id,CancelarServicoMaquinaRequest request,CancellationToken ct); Task<Result> ExcluirAsync(long id,CancellationToken ct); }
