using Microsoft.Extensions.Logging;
using Sigov.Application.Agro.Permissions;
using Sigov.Application.Common;
using Sigov.Domain.Common;

namespace Sigov.Application.Agro.Propriedades;

public sealed class AgroPropriedadeService : IAgroPropriedadeService, IAgroTalhaoService, IAgroCulturaService, IAgroSafraService
{
    private readonly AgroPropriedadePermissionChecker _permission; private readonly AgroPropriedadeValidator _propValidator; private readonly AgroTalhaoValidator _talhaoValidator; private readonly AgroCulturaValidator _culturaValidator; private readonly AgroSafraValidator _safraValidator; private readonly AgroPropriedadeAuditWriter _audit; private readonly IAgroPropriedadeRepository _repository; private readonly ILogger<AgroPropriedadeService> _logger;
    public AgroPropriedadeService(AgroPropriedadePermissionChecker permission, AgroPropriedadeValidator propValidator, AgroTalhaoValidator talhaoValidator, AgroCulturaValidator culturaValidator, AgroSafraValidator safraValidator, AgroPropriedadeAuditWriter audit, IAgroPropriedadeRepository repository, ILogger<AgroPropriedadeService> logger) { _permission = permission; _propValidator = propValidator; _talhaoValidator = talhaoValidator; _culturaValidator = culturaValidator; _safraValidator = safraValidator; _audit = audit; _repository = repository; _logger = logger; }
    public async Task<Result<PagedResult<AgroPropriedadeResponse>>> ListarAsync(AgroPropriedadeFiltro filtro, CancellationToken ct) { var c = await Ctx(AgroPermissions.PropriedadeVisualizar, ct); if (c.IsFailure) return Result<PagedResult<AgroPropriedadeResponse>>.Failure(c.Error!); var e = Ent(c.Value!); if (e.IsFailure) return Result<PagedResult<AgroPropriedadeResponse>>.Failure(e.Error!); return Result<PagedResult<AgroPropriedadeResponse>>.Success(await _repository.ListarAsync(c.Value!.TenantId, c.Value.EntidadeId!.Value, Fix(filtro), ct)); }
    public async Task<Result<AgroPropriedadeDetalheResponse>> ObterAsync(long id, CancellationToken ct) { var c = await Ctx(AgroPermissions.PropriedadeVisualizar, ct); if (c.IsFailure) return Result<AgroPropriedadeDetalheResponse>.Failure(c.Error!); var e = Ent(c.Value!); if (e.IsFailure) return Result<AgroPropriedadeDetalheResponse>.Failure(e.Error!); var row = await _repository.ObterAsync(c.Value!.TenantId, c.Value.EntidadeId!.Value, id, ct); return row is null ? Result<AgroPropriedadeDetalheResponse>.Failure("Propriedade não encontrada.") : Result<AgroPropriedadeDetalheResponse>.Success(row); }
    public async Task<Result<long>> CriarAsync(AgroPropriedadeCreateRequest r, CancellationToken ct) { var c = await Ctx(AgroPermissions.PropriedadeCriar, ct); if (c.IsFailure) return Result<long>.Failure(c.Error!); var e = Ent(c.Value!); if (e.IsFailure) return Result<long>.Failure(e.Error!); var v = _propValidator.Validar(r); if (v.IsFailure) return Result<long>.Failure(v.Error!); var codigo = string.IsNullOrWhiteSpace(r.CodigoPropriedade) ? $"AGR-PROP-{DateTime.UtcNow.Year:D4}-{DateTime.UtcNow.Ticks % 1000000:D6}" : r.CodigoPropriedade!; var id = await _repository.CriarAsync(c.Value!.TenantId, c.Value.EntidadeId!.Value, c.Value.UsuarioId, r, codigo, ct); await _audit.WriteAsync("sigov.agro_propriedade", "CRIAR", id.ToString(System.Globalization.CultureInfo.InvariantCulture), r with { CodigoPropriedade = codigo }, ct); _logger.LogInformation("Propriedade Agro {Id} criada.", id); return Result<long>.Success(id); }
    public async Task<Result> AtualizarAsync(long id, AgroPropriedadeUpdateRequest r, CancellationToken ct) { var c = await Ctx(AgroPermissions.PropriedadeEditar, ct); if (c.IsFailure) return Result.Failure(c.Error!); var e = Ent(c.Value!); if (e.IsFailure) return e; var v = _propValidator.Validar(r); if (v.IsFailure) return v; await _repository.AtualizarAsync(c.Value!.TenantId, c.Value.EntidadeId!.Value, id, c.Value.UsuarioId, r, ct); await _audit.WriteAsync("sigov.agro_propriedade", "EDITAR", id.ToString(System.Globalization.CultureInfo.InvariantCulture), r, ct); return Result.Success(); }
    public async Task<Result> ExcluirAsync(long id, CancellationToken ct) { var c = await Ctx(AgroPermissions.PropriedadeExcluir, ct); if (c.IsFailure) return Result.Failure(c.Error!); var e = Ent(c.Value!); if (e.IsFailure) return e; await _repository.ExcluirAsync(c.Value!.TenantId, c.Value.EntidadeId!.Value, id, c.Value.UsuarioId, ct); await _audit.WriteAsync("sigov.agro_propriedade", "EXCLUIR", id.ToString(System.Globalization.CultureInfo.InvariantCulture), new { isDeleted = true }, ct); return Result.Success(); }
    async Task<Result<PagedResult<AgroTalhaoResponse>>> IAgroTalhaoService.ListarAsync(int page, int pageSize, long? propriedadeId, CancellationToken ct) { var c = await Ctx(AgroPermissions.TalhaoVisualizar, ct); if (c.IsFailure) return Result<PagedResult<AgroTalhaoResponse>>.Failure(c.Error!); var e = Ent(c.Value!); if (e.IsFailure) return Result<PagedResult<AgroTalhaoResponse>>.Failure(e.Error!); return Result<PagedResult<AgroTalhaoResponse>>.Success(await _repository.ListarTalhoesAsync(c.Value!.TenantId, c.Value.EntidadeId!.Value, Math.Max(1, page), Math.Clamp(pageSize, 1, 100), propriedadeId, ct)); }
    async Task<Result<long>> IAgroTalhaoService.CriarAsync(long propriedadeId, AgroTalhaoCreateRequest r, CancellationToken ct) { var c = await Ctx(AgroPermissions.TalhaoCriar, ct); if (c.IsFailure) return Result<long>.Failure(c.Error!); var req = r with { PropriedadeId = propriedadeId }; var e = Ent(c.Value!); if (e.IsFailure) return Result<long>.Failure(e.Error!); var v = _talhaoValidator.Validar(req); if (v.IsFailure) return Result<long>.Failure(v.Error!); var id = await _repository.CriarTalhaoAsync(c.Value!.TenantId, c.Value.EntidadeId!.Value, c.Value.UsuarioId, req, ct); await _audit.WriteAsync("sigov.agro_talhao", "CRIAR", id.ToString(System.Globalization.CultureInfo.InvariantCulture), req, ct); return Result<long>.Success(id); }
    async Task<Result<PagedResult<AgroCulturaResponse>>> IAgroCulturaService.ListarAsync(int page, int pageSize, CancellationToken ct) { var c = await Ctx(AgroPermissions.CulturaVisualizar, ct); if (c.IsFailure) return Result<PagedResult<AgroCulturaResponse>>.Failure(c.Error!); var e = Ent(c.Value!); if (e.IsFailure) return Result<PagedResult<AgroCulturaResponse>>.Failure(e.Error!); return Result<PagedResult<AgroCulturaResponse>>.Success(await _repository.ListarCulturasAsync(c.Value!.TenantId, c.Value.EntidadeId!.Value, Math.Max(1, page), Math.Clamp(pageSize, 1, 100), ct)); }
    async Task<Result<long>> IAgroCulturaService.CriarAsync(AgroCulturaCreateRequest r, CancellationToken ct) { var c = await Ctx(AgroPermissions.CulturaCriar, ct); if (c.IsFailure) return Result<long>.Failure(c.Error!); var e = Ent(c.Value!); if (e.IsFailure) return Result<long>.Failure(e.Error!); var v = _culturaValidator.Validar(r); if (v.IsFailure) return Result<long>.Failure(v.Error!); var id = await _repository.CriarCulturaAsync(c.Value!.TenantId, c.Value.EntidadeId!.Value, c.Value.UsuarioId, r, ct); await _audit.WriteAsync("sigov.agro_cultura", "CRIAR", id.ToString(System.Globalization.CultureInfo.InvariantCulture), r, ct); return Result<long>.Success(id); }
    async Task<Result<PagedResult<AgroSafraResponse>>> IAgroSafraService.ListarAsync(int page, int pageSize, CancellationToken ct) { var c = await Ctx(AgroPermissions.SafraVisualizar, ct); if (c.IsFailure) return Result<PagedResult<AgroSafraResponse>>.Failure(c.Error!); var e = Ent(c.Value!); if (e.IsFailure) return Result<PagedResult<AgroSafraResponse>>.Failure(e.Error!); return Result<PagedResult<AgroSafraResponse>>.Success(await _repository.ListarSafrasAsync(c.Value!.TenantId, c.Value.EntidadeId!.Value, c.Value.ExercicioId, Math.Max(1, page), Math.Clamp(pageSize, 1, 100), ct)); }
    async Task<Result<long>> IAgroSafraService.CriarAsync(AgroSafraCreateRequest r, CancellationToken ct) { var c = await Ctx(AgroPermissions.SafraCriar, ct); if (c.IsFailure) return Result<long>.Failure(c.Error!); var e = Ent(c.Value!); if (e.IsFailure) return Result<long>.Failure(e.Error!); var v = _safraValidator.Validar(r); if (v.IsFailure) return Result<long>.Failure(v.Error!); var id = await _repository.CriarSafraAsync(c.Value!.TenantId, c.Value.EntidadeId!.Value, r.ExercicioId ?? c.Value.ExercicioId, c.Value.UsuarioId, r, ct); await _audit.WriteAsync("sigov.agro_safra", "CRIAR", id.ToString(System.Globalization.CultureInfo.InvariantCulture), r, ct); return Result<long>.Success(id); }
    private Task<Result<AgroAccessContext>> Ctx(string p, CancellationToken ct) => _permission.CheckAsync(p, ct);
    private static Result Ent(AgroAccessContext c) => c.EntidadeId.HasValue ? Result.Success() : Result.Failure("Entidade atual obrigatória para Agro.");
    private static AgroPropriedadeFiltro Fix(AgroPropriedadeFiltro f) => f with { Page = Math.Max(1, f.Page), PageSize = Math.Clamp(f.PageSize, 1, 100) };
}
