namespace Sigov.Application.Bloco6;

public sealed class FornecedorService:IFornecedorService { public string Normalizar(string d)=>new(d.Where(char.IsDigit).ToArray()); public string Mascarar(string d){var n=Normalizar(d);return n.Length<4?"***":"***"+n.Substring(n.Length-4);} }
public sealed class ComprasService:IComprasService,IComprasSolicitacaoService,IComprasOrdemCompraService { private readonly IComprasRepository _r; public ComprasService(IComprasRepository r)=>_r=r; public Task<Guid> CriarSolicitacaoAsync(Bloco6Context c,ComprasCriarSolicitacaoRequest x,CancellationToken ct){if(x.Itens.Count==0)throw new ArgumentException("A solicitação precisa ter itens.");return _r.CriarSolicitacaoAsync(c,x,ct);} public Task<Guid> GerarOrdemAsync(Bloco6Context c,ComprasGerarOrdemCompraRequest x,CancellationToken ct)=>_r.GerarOrdemAsync(c,x,ct); }
public sealed class ComprasDashboardService:IComprasDashboardService { readonly IComprasRepository _r; public ComprasDashboardService(IComprasRepository r)=>_r=r; public Task<Bloco6DashboardDto> ObterAsync(Bloco6Context c,CancellationToken ct)=>_r.DashboardAsync(c,"compras_solicitacao",ct); }
public sealed class ContratosService:IContratosService,IContratoMedicaoService { readonly IContratosRepository _r; public ContratosService(IContratosRepository r)=>_r=r; public Task<Guid>CriarAsync(Bloco6Context c,ContratoCriarRequest x,CancellationToken ct){if(x.VigenciaFim<=x.VigenciaInicio)throw new ArgumentException("Vigência final deve ser posterior à inicial.");return _r.CriarContratoAsync(c,x,ct);} public Task<Guid>MedirAsync(Bloco6Context c,Guid id,ContratoCriarMedicaoRequest x,CancellationToken ct)=>_r.MedirAsync(c,id,x,ct); }
public sealed class ContratosDashboardService:IContratosDashboardService { readonly IContratosRepository _r; public ContratosDashboardService(IContratosRepository r)=>_r=r; public Task<Bloco6DashboardDto>ObterAsync(Bloco6Context c,CancellationToken ct)=>_r.DashboardAsync(c,"contrato",ct); }
public sealed class AlmoxarifadoService:IAlmoxarifadoService,IAlmoxarifadoEstoqueService,IAlmoxarifadoMovimentoService { readonly IAlmoxarifadoRepository _r; public AlmoxarifadoService(IAlmoxarifadoRepository r)=>_r=r; public Task<Guid>MovimentarAsync(Bloco6Context c,AlmoxarifadoCriarMovimentoRequest x,CancellationToken ct){if(x.Tipo.Equals("TRANSFERENCIA",StringComparison.OrdinalIgnoreCase)&&x.DestinoId is null)throw new ArgumentException("Destino obrigatório.");return _r.MovimentarAsync(c,x,ct);} }
public sealed class PatrimonioService:IPatrimonioService,IPatrimonioMovimentoService { readonly IPatrimonioRepository _r; public PatrimonioService(IPatrimonioRepository r)=>_r=r; public Task<Guid>CriarBemAsync(Bloco6Context c,PatrimonioCriarBemRequest x,CancellationToken ct)=>x.LocalizacaoId==Guid.Empty?throw new ArgumentException("Localização obrigatória."):_r.CriarBemAsync(c,x,ct); }
