using Microsoft.Extensions.Logging;
using Sigov.Application.Agro.Permissions;
using Sigov.Domain.Common;

namespace Sigov.Application.Agro.Transparencia;

public sealed class AgroTransparenciaService : IAgroTransparenciaService
{
    private readonly IAgroAccessChecker _accessChecker; private readonly IAgroTransparenciaRepository _repository; private readonly AgroDatasetValidator _validator; private readonly AgroDatasetAnonymizer _anonymizer; private readonly ILogger<AgroTransparenciaService> _logger;
    public AgroTransparenciaService(IAgroAccessChecker accessChecker, IAgroTransparenciaRepository repository, AgroDatasetValidator validator, AgroDatasetAnonymizer anonymizer, ILogger<AgroTransparenciaService> logger) { _accessChecker = accessChecker; _repository = repository; _validator = validator; _anonymizer = anonymizer; _logger = logger; }
    public async Task<Result<IReadOnlyCollection<AgroDatasetPublicoResponse>>> ListarDatasetsAsync(int page, int pageSize, CancellationToken cancellationToken) { var c = await _accessChecker.CheckAsync(new AgroAccessRequest(AgroPermissions.TransparenciaVisualizar, "agro.transparencia"), cancellationToken).ConfigureAwait(false); if (c.IsFailure) return Result<IReadOnlyCollection<AgroDatasetPublicoResponse>>.Failure(c.Error!); var v = c.Value!; return Result<IReadOnlyCollection<AgroDatasetPublicoResponse>>.Success(await _repository.ListarDatasetsAsync(v.TenantId, v.EntidadeId, false, Math.Max(1, page), Math.Clamp(pageSize, 1, 200), cancellationToken).ConfigureAwait(false)); }
    public async Task<Result<AgroDatasetPublicoResponse>> CriarDatasetAsync(AgroDatasetPublicoCreateRequest request, CancellationToken cancellationToken) { var c = await _accessChecker.CheckAsync(new AgroAccessRequest(AgroPermissions.TransparenciaGerenciar, "agro.transparencia", request.EntidadeId), cancellationToken).ConfigureAwait(false); if (c.IsFailure) return Result<AgroDatasetPublicoResponse>.Failure(c.Error!); try { var v = c.Value!; _validator.Validate(request, v.TenantId, request.EntidadeId ?? v.EntidadeId); return Result<AgroDatasetPublicoResponse>.Success(await _repository.CriarDatasetAsync(v.TenantId, request.EntidadeId ?? v.EntidadeId, v.UsuarioId, request, cancellationToken).ConfigureAwait(false)); } catch (Exception ex) when (ex is ArgumentException or InvalidOperationException) { return Result<AgroDatasetPublicoResponse>.Failure(ex.Message); } }
    public async Task<Result<AgroDatasetPublicacaoResponse>> PublicarAsync(long datasetId, PublicarAgroDatasetRequest request, CancellationToken cancellationToken) { var c = await _accessChecker.CheckAsync(new AgroAccessRequest(AgroPermissions.TransparenciaPublicar, "agro.dados_abertos"), cancellationToken).ConfigureAwait(false); if (c.IsFailure) return Result<AgroDatasetPublicacaoResponse>.Failure(c.Error!); var v = c.Value!; _logger.LogInformation("Publicando dataset Agro {DatasetId}.", datasetId); return Result<AgroDatasetPublicacaoResponse>.Success(await _repository.PublicarAsync(v.TenantId, datasetId, v.UsuarioId, request, cancellationToken).ConfigureAwait(false)); }
    public async Task<Result<AgroDatasetPublicacaoResponse>> SuspenderAsync(long datasetId, CancellationToken cancellationToken) { var c = await _accessChecker.CheckAsync(new AgroAccessRequest(AgroPermissions.TransparenciaPublicar, "agro.dados_abertos"), cancellationToken).ConfigureAwait(false); if (c.IsFailure) return Result<AgroDatasetPublicacaoResponse>.Failure(c.Error!); var v = c.Value!; return Result<AgroDatasetPublicacaoResponse>.Success(await _repository.SuspenderAsync(v.TenantId, datasetId, v.UsuarioId, cancellationToken).ConfigureAwait(false)); }
    public async Task<Result<IReadOnlyCollection<AgroDatasetPublicoResponse>>> ListarPublicosAsync(string tenantSlug, CancellationToken cancellationToken) { var tenantId = await _repository.ResolverTenantPorSlugAsync(tenantSlug, cancellationToken).ConfigureAwait(false); if (!tenantId.HasValue) return Result<IReadOnlyCollection<AgroDatasetPublicoResponse>>.Failure("Tenant não encontrado."); return Result<IReadOnlyCollection<AgroDatasetPublicoResponse>>.Success(await _repository.ListarDatasetsAsync(tenantId.Value, null, true, 1, 200, cancellationToken).ConfigureAwait(false)); }
    public async Task<Result<AgroDatasetPublicacaoResponse>> DownloadPublicoAsync(string tenantSlug, string codigo, string formato, string? ip, string? userAgent, CancellationToken cancellationToken) { var tenantId = await _repository.ResolverTenantPorSlugAsync(tenantSlug, cancellationToken).ConfigureAwait(false); if (!tenantId.HasValue) return Result<AgroDatasetPublicacaoResponse>.Failure("Tenant não encontrado."); var publicacao = await _repository.ObterPublicacaoAsync(tenantId.Value, codigo, formato, cancellationToken).ConfigureAwait(false); if (publicacao is null || !string.Equals(publicacao.Status, "PUBLICADO", StringComparison.OrdinalIgnoreCase)) return Result<AgroDatasetPublicacaoResponse>.Failure("Dataset publicado não encontrado."); var safe = publicacao with { ConteudoTexto = _anonymizer.Anonymize(publicacao.ConteudoTexto ?? string.Empty) }; await _repository.RegistrarDownloadAsync(tenantId.Value, safe.DatasetId, safe.Id, formato.ToUpperInvariant(), ip, userAgent, cancellationToken).ConfigureAwait(false); return Result<AgroDatasetPublicacaoResponse>.Success(safe); }
}
