using Microsoft.Extensions.Logging;
using Sigov.Application.Agro.Permissions;
using Sigov.Domain.Common;

namespace Sigov.Application.Agro.Relatorios;

public sealed class AgroRelatorioService : IAgroRelatorioService, IAgroExportService
{
    private readonly IAgroAccessChecker _accessChecker; private readonly IAgroRelatoriosRepository _repository; private readonly AgroRelatorioValidator _validator; private readonly ILogger<AgroRelatorioService> _logger;
    public AgroRelatorioService(IAgroAccessChecker accessChecker, IAgroRelatoriosRepository repository, AgroRelatorioValidator validator, ILogger<AgroRelatorioService> logger) { _accessChecker = accessChecker; _repository = repository; _validator = validator; _logger = logger; }
    public async Task<Result<IReadOnlyCollection<AgroRelatorioModeloResponse>>> ListarModelosAsync(int page, int pageSize, CancellationToken cancellationToken) { var c = await _accessChecker.CheckAsync(new AgroAccessRequest(AgroPermissions.RelatorioVisualizar, "agro.relatorios"), cancellationToken).ConfigureAwait(false); if (c.IsFailure) return Result<IReadOnlyCollection<AgroRelatorioModeloResponse>>.Failure(c.Error!); var v = c.Value!; return Result<IReadOnlyCollection<AgroRelatorioModeloResponse>>.Success(await _repository.ListarModelosAsync(v.TenantId, v.EntidadeId, Math.Max(1, page), Math.Clamp(pageSize, 1, 200), cancellationToken).ConfigureAwait(false)); }
    public async Task<Result<AgroRelatorioModeloResponse>> CriarModeloAsync(AgroRelatorioModeloCreateRequest request, CancellationToken cancellationToken) { var c = await _accessChecker.CheckAsync(new AgroAccessRequest(AgroPermissions.RelatorioGerenciar, "agro.relatorios", request.EntidadeId), cancellationToken).ConfigureAwait(false); if (c.IsFailure) return Result<AgroRelatorioModeloResponse>.Failure(c.Error!); try { var v = c.Value!; _validator.ValidateModelo(request, v.TenantId, request.EntidadeId ?? v.EntidadeId); return Result<AgroRelatorioModeloResponse>.Success(await _repository.CriarModeloAsync(v.TenantId, request.EntidadeId ?? v.EntidadeId, v.UsuarioId, request, cancellationToken).ConfigureAwait(false)); } catch (Exception ex) when (ex is ArgumentException or InvalidOperationException) { return Result<AgroRelatorioModeloResponse>.Failure(ex.Message); } }
    public async Task<Result<AgroRelatorioExecucaoResponse>> ExecutarAsync(long modeloId, ExecutarAgroRelatorioRequest request, CancellationToken cancellationToken) { var c = await _accessChecker.CheckAsync(new AgroAccessRequest(AgroPermissions.RelatorioExecutar, "agro.relatorios", request.EntidadeId, request.ExercicioId), cancellationToken).ConfigureAwait(false); if (c.IsFailure) return Result<AgroRelatorioExecucaoResponse>.Failure(c.Error!); try { var v = c.Value!; _validator.ValidateExecucao(request, v.TenantId, request.EntidadeId ?? v.EntidadeId, request.ExercicioId ?? v.ExercicioId, modeloId, v.UsuarioId); _logger.LogInformation("Executando relatório Agro {ModeloId}.", modeloId); return Result<AgroRelatorioExecucaoResponse>.Success(await _repository.ExecutarAsync(v.TenantId, request.EntidadeId ?? v.EntidadeId, request.ExercicioId ?? v.ExercicioId, v.UsuarioId, modeloId, request, cancellationToken).ConfigureAwait(false)); } catch (Exception ex) when (ex is ArgumentException or InvalidOperationException) { return Result<AgroRelatorioExecucaoResponse>.Failure(ex.Message); } }
    public async Task<Result<IReadOnlyCollection<AgroRelatorioExecucaoResponse>>> ListarExecucoesAsync(int page, int pageSize, CancellationToken cancellationToken) { var c = await _accessChecker.CheckAsync(new AgroAccessRequest(AgroPermissions.RelatorioVisualizar, "agro.relatorios"), cancellationToken).ConfigureAwait(false); if (c.IsFailure) return Result<IReadOnlyCollection<AgroRelatorioExecucaoResponse>>.Failure(c.Error!); var v = c.Value!; return Result<IReadOnlyCollection<AgroRelatorioExecucaoResponse>>.Success(await _repository.ListarExecucoesAsync(v.TenantId, v.EntidadeId, Math.Max(1, page), Math.Clamp(pageSize, 1, 200), cancellationToken).ConfigureAwait(false)); }
    public async Task<Result<AgroRelatorioExecucaoResponse>> ObterExecucaoAsync(long id, CancellationToken cancellationToken) { var c = await _accessChecker.CheckAsync(new AgroAccessRequest(AgroPermissions.RelatorioVisualizar, "agro.relatorios"), cancellationToken).ConfigureAwait(false); if (c.IsFailure) return Result<AgroRelatorioExecucaoResponse>.Failure(c.Error!); var item = await _repository.ObterExecucaoAsync(c.Value!.TenantId, id, cancellationToken).ConfigureAwait(false); return item is null ? Result<AgroRelatorioExecucaoResponse>.Failure("Execução não encontrada.") : Result<AgroRelatorioExecucaoResponse>.Success(item); }
    public async Task<Result<AgroExportResponse>> ExportarAsync(AgroExportRequest request, CancellationToken cancellationToken) { var c = await _accessChecker.CheckAsync(new AgroAccessRequest(AgroPermissions.Exportar, request.Formato.Equals("GEOJSON", StringComparison.OrdinalIgnoreCase) ? "agro.exportacao_geojson" : "agro.relatorios", request.EntidadeId, request.ExercicioId), cancellationToken).ConfigureAwait(false); if (c.IsFailure) return Result<AgroExportResponse>.Failure(c.Error!); var v = c.Value!; return Result<AgroExportResponse>.Success(await _repository.ExportarAsync(v.TenantId, request.EntidadeId ?? v.EntidadeId, request.ExercicioId ?? v.ExercicioId, v.UsuarioId, request, cancellationToken).ConfigureAwait(false)); }
}
