using System.Globalization;
using System.Text;
using System.Text.Json;
using Dapper;
using Npgsql;
using Sigov.Application.Patrimonio;
using Sigov.Infrastructure.Persistence.Dapper;

namespace Sigov.Infrastructure.Patrimonio;

public sealed partial class PatrimonioService
{
    public async Task<PatrimonioPagina<PatrimonioInventarioDto>> ListarInventariosAsync(long tenantId,int pagina,int tamanho,CancellationToken ct)
    { pagina=Math.Max(1,pagina);tamanho=Math.Clamp(tamanho,1,100);await using var c=factory.CreateConnection();var total=await c.ExecuteScalarAsync<long>(new CommandDefinition("select count(*) from sigov.patrimonio_inventario where tenant_id=@Tenant",new{Tenant=tenantId},cancellationToken:ct));var items=(await c.QueryAsync<PatrimonioInventarioDto>(new CommandDefinition("select i.id,i.codigo,i.descricao,i.data_abertura DataAbertura,i.data_fechamento DataFechamento,i.situacao,i.unidade_id UnidadeId,i.responsavel_usuario_id ResponsavelUsuarioId,count(ii.id)::int TotalItens,count(ii.conferido_em)::int Conferidos,count(ii.id) filter(where ii.divergencia)::int Divergencias,uo.nome UnidadeNome,coalesce(p.nome,u.login) ResponsavelNome from sigov.patrimonio_inventario i left join sigov.patrimonio_inventario_item ii on ii.inventario_id=i.id and ii.tenant_id=i.tenant_id left join sigov.unidade_organizacional uo on uo.id=i.unidade_id left join sigov.usuario u on u.id=i.responsavel_usuario_id left join sigov.pessoa p on p.id=u.pessoa_id where i.tenant_id=@Tenant group by i.id,uo.nome,p.nome,u.login order by i.data_abertura desc,i.id desc limit @Limit offset @Offset",new{Tenant=tenantId,Limit=tamanho,Offset=(pagina-1)*tamanho},cancellationToken:ct))).AsList();return new(items,pagina,tamanho,total); }

    public async Task<PatrimonioInventarioDetalhe?> ObterInventarioAsync(long tenantId,long id,CancellationToken ct)
    { await using var c=factory.CreateConnection();var inv=await c.QuerySingleOrDefaultAsync<PatrimonioInventarioDto>(new CommandDefinition("select i.id,i.codigo,i.descricao,i.data_abertura DataAbertura,i.data_fechamento DataFechamento,i.situacao,i.unidade_id UnidadeId,i.responsavel_usuario_id ResponsavelUsuarioId,count(ii.id)::int TotalItens,count(ii.conferido_em)::int Conferidos,count(ii.id) filter(where ii.divergencia)::int Divergencias,uo.nome UnidadeNome,coalesce(p.nome,u.login) ResponsavelNome from sigov.patrimonio_inventario i left join sigov.patrimonio_inventario_item ii on ii.inventario_id=i.id and ii.tenant_id=i.tenant_id left join sigov.unidade_organizacional uo on uo.id=i.unidade_id left join sigov.usuario u on u.id=i.responsavel_usuario_id left join sigov.pessoa p on p.id=u.pessoa_id where i.tenant_id=@Tenant and i.id=@Id group by i.id,uo.nome,p.nome,u.login",new{Tenant=tenantId,Id=id},cancellationToken:ct));if(inv is null)return null;var itens=(await c.QueryAsync<PatrimonioInventarioItemDto>(new CommandDefinition("select ii.id,ii.bem_id BemId,b.codigo_tombo CodigoTombo,b.descricao,ii.localizado,b.estado_conservacao EstadoCadastro,ii.estado_informado EstadoInformado,b.localizacao LocalizacaoCadastro,ii.localizacao_informada LocalizacaoInformada,ii.divergencia,ii.descricao_divergencia DescricaoDivergencia,ii.conferido_em ConferidoEm from sigov.patrimonio_inventario_item ii join sigov.patrimonio_bem b on b.id=ii.bem_id and b.tenant_id=ii.tenant_id where ii.tenant_id=@Tenant and ii.inventario_id=@Id order by b.codigo_tombo",new{Tenant=tenantId,Id=id},cancellationToken:ct))).AsList();return new(inv,itens); }

    public async Task<long> AbrirInventarioAsync(long tenantId,long usuarioId,string correlationId,PatrimonioInventarioInput input,CancellationToken ct)
    { if(string.IsNullOrWhiteSpace(input.Codigo)||string.IsNullOrWhiteSpace(input.Descricao))throw new ArgumentException("Código e descrição são obrigatórios.");await using var c=factory.CreateConnection();await c.OpenAsync(ct);await using var tx=await c.BeginTransactionAsync(ct);var id=await c.ExecuteScalarAsync<long>(new CommandDefinition("insert into sigov.patrimonio_inventario(tenant_id,codigo,descricao,data_abertura,situacao,unidade_id,responsavel_usuario_id,created_by,updated_by) values(@Tenant,@Codigo,@Descricao,current_date,'ABERTO',@Unidade,@Responsavel,@Usuario,@Usuario) returning id",new{Tenant=tenantId,Codigo=input.Codigo.Trim(),Descricao=input.Descricao.Trim(),Unidade=input.UnidadeId,Responsavel=input.ResponsavelUsuarioId,Usuario=usuarioId},tx,cancellationToken:ct));await c.ExecuteAsync(new CommandDefinition("insert into sigov.patrimonio_inventario_item(tenant_id,inventario_id,bem_id) select @Tenant,@Inventario,id from sigov.patrimonio_bem where tenant_id=@Tenant and not is_deleted and situacao<>'BAIXADO' and (@Unidade is null or unidade_id=@Unidade) and (@Responsavel is null or responsavel_usuario_id=@Responsavel) on conflict(inventario_id,bem_id) do nothing",new{Tenant=tenantId,Inventario=id,Unidade=input.UnidadeId,Responsavel=input.ResponsavelUsuarioId},tx,cancellationToken:ct));await Auditar(c,tx,tenantId,"patrimonio_inventario",id,"ABRIR",null,input,usuarioId,correlationId,ct);await tx.CommitAsync(ct);return id; }

    public async Task ConferirItemAsync(long tenantId,long usuarioId,string correlationId,long inventarioId,long itemId,PatrimonioConferenciaInput input,CancellationToken ct)
    { await using var c=factory.CreateConnection();await c.OpenAsync(ct);await using var tx=await c.BeginTransactionAsync(ct);var row=await c.QuerySingleOrDefaultAsync<ItemEstado>(new CommandDefinition("select i.situacao,b.estado_conservacao Estado,b.localizacao from sigov.patrimonio_inventario_item ii join sigov.patrimonio_inventario i on i.id=ii.inventario_id and i.tenant_id=ii.tenant_id join sigov.patrimonio_bem b on b.id=ii.bem_id and b.tenant_id=ii.tenant_id where ii.tenant_id=@Tenant and ii.inventario_id=@Inventario and ii.id=@Item for update",new{Tenant=tenantId,Inventario=inventarioId,Item=itemId},tx,cancellationToken:ct))??throw new KeyNotFoundException("Item de inventário não encontrado.");if(row.Situacao!="ABERTO")throw new InvalidOperationException("Inventário fechado não aceita conferência.");var divergencia=!input.Localizado||!Igual(row.Estado,input.EstadoInformado)||!Igual(row.Localizacao,input.LocalizacaoInformada);if(!input.Localizado&&string.IsNullOrWhiteSpace(input.DescricaoDivergencia))throw new ArgumentException("Descreva a divergência quando o bem não for localizado.");await c.ExecuteAsync(new CommandDefinition("update sigov.patrimonio_inventario_item set localizado=@Localizado,estado_informado=@Estado,localizacao_informada=@Localizacao,divergencia=@Divergencia,descricao_divergencia=@Descricao,conferido_por_usuario_id=@Usuario,conferido_em=now(),observacao=@Observacao where tenant_id=@Tenant and inventario_id=@Inventario and id=@Item",new{input.Localizado,Estado=VazioNulo(input.EstadoInformado),Localizacao=VazioNulo(input.LocalizacaoInformada),Divergencia=divergencia,Descricao=VazioNulo(input.DescricaoDivergencia),Usuario=usuarioId,input.Observacao,Tenant=tenantId,Inventario=inventarioId,Item=itemId},tx,cancellationToken:ct));await Auditar(c,tx,tenantId,"patrimonio_inventario_item",itemId,"CONFERIR",row,input with { DescricaoDivergencia=divergencia?input.DescricaoDivergencia:null },usuarioId,correlationId,ct);await tx.CommitAsync(ct); }

    public async Task FecharInventarioAsync(long tenantId,long usuarioId,string correlationId,long id,CancellationToken ct)
    { await using var c=factory.CreateConnection();await c.OpenAsync(ct);await using var tx=await c.BeginTransactionAsync(ct);var pendentes=await c.ExecuteScalarAsync<int>(new CommandDefinition("select count(*) from sigov.patrimonio_inventario_item ii join sigov.patrimonio_inventario i on i.id=ii.inventario_id and i.tenant_id=ii.tenant_id where ii.tenant_id=@Tenant and i.id=@Id and i.situacao='ABERTO' and ii.conferido_em is null",new{Tenant=tenantId,Id=id},tx,cancellationToken:ct));if(pendentes>0)throw new InvalidOperationException($"Existem {pendentes} itens sem conferência.");var n=await c.ExecuteAsync(new CommandDefinition("update sigov.patrimonio_inventario set situacao='FECHADO',data_fechamento=current_date,updated_at=now(),updated_by=@Usuario where tenant_id=@Tenant and id=@Id and situacao='ABERTO'",new{Usuario=usuarioId,Tenant=tenantId,Id=id},tx,cancellationToken:ct));if(n==0)throw new InvalidOperationException("Inventário não está aberto.");await Auditar(c,tx,tenantId,"patrimonio_inventario",id,"FECHAR",null,new{id},usuarioId,correlationId,ct);await tx.CommitAsync(ct); }

    public async Task<PatrimonioDashboard> ObterDashboardAsync(long tenantId,CancellationToken ct)
    { await using var c=factory.CreateConnection();var total=await c.ExecuteScalarAsync<long>(new CommandDefinition("select count(*) from sigov.patrimonio_bem where tenant_id=@Tenant and not is_deleted",new{Tenant=tenantId},cancellationToken:ct));var situacao=(await c.QueryAsync<PatrimonioAgrupamento>(new CommandDefinition("select situacao Nome,count(*) Total from sigov.patrimonio_bem where tenant_id=@Tenant and not is_deleted group by situacao",new{Tenant=tenantId},cancellationToken:ct))).ToDictionary(x=>x.Nome,x=>x.Total);var estado=(await c.QueryAsync<PatrimonioAgrupamento>(new CommandDefinition("select estado_conservacao Nome,count(*) Total from sigov.patrimonio_bem where tenant_id=@Tenant and not is_deleted group by estado_conservacao",new{Tenant=tenantId},cancellationToken:ct))).ToDictionary(x=>x.Nome,x=>x.Total);var unidades=(await c.QueryAsync<PatrimonioAgrupamento>(new CommandDefinition("select coalesce(uo.nome,'Sem unidade') Nome,count(*) Total from sigov.patrimonio_bem b left join sigov.unidade_organizacional uo on uo.id=b.unidade_id where b.tenant_id=@Tenant and not b.is_deleted group by uo.nome order by count(*) desc limit 10",new{Tenant=tenantId},cancellationToken:ct))).AsList();var resumo=await c.QuerySingleAsync<Resumo>(new CommandDefinition("select (select count(*) from sigov.patrimonio_inventario where tenant_id=@Tenant and situacao='ABERTO') Inventarios,(select count(*) from sigov.patrimonio_inventario_item ii join sigov.patrimonio_inventario i on i.id=ii.inventario_id and i.tenant_id=ii.tenant_id where ii.tenant_id=@Tenant and ii.divergencia and i.situacao='ABERTO') Divergencias,(select count(*) from sigov.patrimonio_baixa where tenant_id=@Tenant and data_baixa>=date_trunc('month',current_date)) Baixas",new{Tenant=tenantId},cancellationToken:ct));return new(total,situacao,estado,unidades,resumo.Inventarios,resumo.Divergencias,resumo.Baixas); }

    public async Task<byte[]> ExportarCsvAsync(long tenantId,PatrimonioBemFiltro filtro,CancellationToken ct)
    { var pagina=await ListarBensAsync(tenantId,filtro with{Pagina=1,TamanhoPagina=100},ct);var sb=new StringBuilder("Tombo;Descrição;Categoria;Tipo;Estado;Situação;Unidade;Localização;Valor atual\r\n");foreach(var b in pagina.Itens)sb.AppendJoin(';',Csv(b.CodigoTombo),Csv(b.Descricao),Csv(b.Categoria),Csv(b.TipoBem),Csv(b.EstadoConservacao),Csv(b.Situacao),Csv(b.UnidadeNome),Csv(b.Localizacao),Csv(b.ValorAtual?.ToString("0.00",CultureInfo.InvariantCulture))).Append("\r\n");return Encoding.UTF8.GetPreamble().Concat(Encoding.UTF8.GetBytes(sb.ToString())).ToArray(); }

}
