using System.Globalization;
using System.Text;
using System.Text.Json;
using Dapper;
using Npgsql;
using Sigov.Application.Patrimonio;
using Sigov.Infrastructure.Persistence.Dapper;

namespace Sigov.Infrastructure.Patrimonio;

public sealed class PatrimonioService(NpgsqlConnectionFactory factory) : IPatrimonioService
{
    public async Task<PatrimonioPagina<PatrimonioBemDto>> ListarBensAsync(long tenantId, PatrimonioBemFiltro filtro, CancellationToken ct)
    {
        var pagina = Math.Max(1, filtro.Pagina); var tamanho = Math.Clamp(filtro.TamanhoPagina, 1, 100);
        const string where = "b.tenant_id=@TenantId and not b.is_deleted and (@Busca is null or b.codigo_tombo ilike '%'||@Busca||'%' or b.descricao ilike '%'||@Busca||'%') and (@CategoriaId is null or b.categoria_id=@CategoriaId) and (@Situacao is null or b.situacao=@Situacao) and (@UnidadeId is null or b.unidade_id=@UnidadeId) and (@ResponsavelUsuarioId is null or b.responsavel_usuario_id=@ResponsavelUsuarioId)";
        var args = new { TenantId=tenantId, Busca=VazioNulo(filtro.Busca), filtro.CategoriaId, Situacao=VazioNulo(filtro.Situacao), filtro.UnidadeId, filtro.ResponsavelUsuarioId, Limit=tamanho, Offset=(pagina-1)*tamanho };
        await using var c = factory.CreateConnection();
        var total = await c.ExecuteScalarAsync<long>(new CommandDefinition($"select count(*) from sigov.patrimonio_bem b where {where}", args, cancellationToken:ct));
        var items = (await c.QueryAsync<PatrimonioBemDto>(new CommandDefinition($"""select b.id,b.codigo_tombo CodigoTombo,b.descricao,b.categoria_id CategoriaId,c.nome Categoria,b.tipo_bem TipoBem,b.marca,b.modelo,b.numero_serie NumeroSerie,b.data_aquisicao DataAquisicao,b.valor_aquisicao ValorAquisicao,b.valor_atual ValorAtual,b.estado_conservacao EstadoConservacao,b.situacao,b.unidade_id UnidadeId,b.setor_id SetorId,b.responsavel_usuario_id ResponsavelUsuarioId,b.localizacao,b.observacao,b.created_at CreatedAt,b.updated_at UpdatedAt from sigov.patrimonio_bem b left join sigov.patrimonio_categoria c on c.id=b.categoria_id and c.tenant_id=b.tenant_id where {where} order by b.codigo_tombo,b.id limit @Limit offset @Offset""",args,cancellationToken:ct))).AsList();
        return new(items,pagina,tamanho,total);
    }

    public async Task<PatrimonioBemDto?> ObterBemAsync(long tenantId,long id,CancellationToken ct)
    { await using var c=factory.CreateConnection(); return await c.QuerySingleOrDefaultAsync<PatrimonioBemDto>(new CommandDefinition("select b.id,b.codigo_tombo CodigoTombo,b.descricao,b.categoria_id CategoriaId,c.nome Categoria,b.tipo_bem TipoBem,b.marca,b.modelo,b.numero_serie NumeroSerie,b.data_aquisicao DataAquisicao,b.valor_aquisicao ValorAquisicao,b.valor_atual ValorAtual,b.estado_conservacao EstadoConservacao,b.situacao,b.unidade_id UnidadeId,b.setor_id SetorId,b.responsavel_usuario_id ResponsavelUsuarioId,b.localizacao,b.observacao,b.created_at CreatedAt,b.updated_at UpdatedAt from sigov.patrimonio_bem b left join sigov.patrimonio_categoria c on c.id=b.categoria_id and c.tenant_id=b.tenant_id where b.tenant_id=@TenantId and b.id=@Id and not b.is_deleted",new{TenantId=tenantId,Id=id},cancellationToken:ct)); }

    public async Task<long> CriarBemAsync(long tenantId,long usuarioId,string correlationId,PatrimonioBemInput input,CancellationToken ct)
    {
        ValidarBem(input); await using var c=factory.CreateConnection(); await c.OpenAsync(ct); await using var tx=await c.BeginTransactionAsync(ct);
        try { const string sql="""insert into sigov.patrimonio_bem(tenant_id,codigo_tombo,codigo_anterior,descricao,categoria_id,tipo_bem,marca,modelo,numero_serie,data_aquisicao,valor_aquisicao,valor_atual,estado_conservacao,situacao,unidade_id,setor_id,responsavel_usuario_id,localizacao,observacao,created_by,updated_by) values(@TenantId,@CodigoTombo,@CodigoAnterior,@Descricao,@CategoriaId,@TipoBem,@Marca,@Modelo,@NumeroSerie,@DataAquisicao,@ValorAquisicao,@ValorAtual,@EstadoConservacao,'ATIVO',@UnidadeId,@SetorId,@ResponsavelUsuarioId,@Localizacao,@Observacao,@UsuarioId,@UsuarioId) returning id""";
            var id=await c.ExecuteScalarAsync<long>(new CommandDefinition(sql,Args(input,tenantId,usuarioId),tx,cancellationToken:ct)); await Auditar(c,tx,tenantId,"patrimonio_bem",id,"CRIAR",null,input,usuarioId,correlationId,ct); await tx.CommitAsync(ct); return id; }
        catch(PostgresException e) when(e.SqlState==PostgresErrorCodes.UniqueViolation){await tx.RollbackAsync(ct);throw new InvalidOperationException("O código de tombo já existe neste tenant.",e);} catch{await tx.RollbackAsync(ct);throw;}
    }

    public async Task EditarBemAsync(long tenantId,long usuarioId,string correlationId,long id,PatrimonioBemInput input,CancellationToken ct)
    {
        ValidarBem(input); await using var c=factory.CreateConnection(); await c.OpenAsync(ct); await using var tx=await c.BeginTransactionAsync(ct);
        try { var antes=await ObterJson(c,tx,"patrimonio_bem",tenantId,id,ct); if(antes is null) throw new KeyNotFoundException("Bem não encontrado.");
            const string sql="""update sigov.patrimonio_bem set codigo_tombo=@CodigoTombo,codigo_anterior=@CodigoAnterior,descricao=@Descricao,categoria_id=@CategoriaId,tipo_bem=@TipoBem,marca=@Marca,modelo=@Modelo,numero_serie=@NumeroSerie,data_aquisicao=@DataAquisicao,valor_aquisicao=@ValorAquisicao,valor_atual=@ValorAtual,estado_conservacao=@EstadoConservacao,unidade_id=@UnidadeId,setor_id=@SetorId,responsavel_usuario_id=@ResponsavelUsuarioId,localizacao=@Localizacao,observacao=@Observacao,updated_at=now(),updated_by=@UsuarioId where tenant_id=@TenantId and id=@Id and not is_deleted""";
            var parameters=new DynamicParameters(Args(input,tenantId,usuarioId)); parameters.Add("Id",id); await c.ExecuteAsync(new CommandDefinition(sql,parameters,tx,cancellationToken:ct)); await Auditar(c,tx,tenantId,"patrimonio_bem",id,"EDITAR",antes,input,usuarioId,correlationId,ct); await tx.CommitAsync(ct); }
        catch(PostgresException e) when(e.SqlState==PostgresErrorCodes.UniqueViolation){await tx.RollbackAsync(ct);throw new InvalidOperationException("O código de tombo já existe neste tenant.",e);} catch{await tx.RollbackAsync(ct);throw;}
    }

    public async Task MovimentarBemAsync(long tenantId,long usuarioId,string correlationId,long id,PatrimonioMovimentacaoInput input,CancellationToken ct)
    {
        if(string.IsNullOrWhiteSpace(input.Justificativa)) throw new ArgumentException("A justificativa é obrigatória.");
        await using var c=factory.CreateConnection(); await c.OpenAsync(ct); await using var tx=await c.BeginTransactionAsync(ct);
        var bem=await c.QuerySingleOrDefaultAsync<BemEstado>(new CommandDefinition("select unidade_id UnidadeId,responsavel_usuario_id ResponsavelId,localizacao,situacao from sigov.patrimonio_bem where tenant_id=@TenantId and id=@Id and not is_deleted for update",new{TenantId=tenantId,Id=id},tx,cancellationToken:ct))??throw new KeyNotFoundException("Bem não encontrado.");
        if(bem.Situacao=="BAIXADO") throw new InvalidOperationException("Bem baixado não pode ser movimentado.");
        await c.ExecuteAsync(new CommandDefinition("insert into sigov.patrimonio_movimentacao(tenant_id,bem_id,unidade_origem_id,unidade_destino_id,responsavel_origem_id,responsavel_destino_id,localizacao_origem,localizacao_destino,tipo_movimentacao,justificativa,data_movimentacao,usuario_id,correlation_id) values(@TenantId,@Id,@UnidadeOrigem,@UnidadeDestino,@ResponsavelOrigem,@ResponsavelDestino,@LocalizacaoOrigem,@LocalizacaoDestino,@Tipo,@Justificativa,@Data,@UsuarioId,@CorrelationId)",new{TenantId=tenantId,Id=id,UnidadeOrigem=bem.UnidadeId,UnidadeDestino=input.UnidadeDestinoId,ResponsavelOrigem=bem.ResponsavelId,ResponsavelDestino=input.ResponsavelDestinoId,LocalizacaoOrigem=bem.Localizacao,LocalizacaoDestino=input.LocalizacaoDestino,Tipo=input.TipoMovimentacao,Justificativa=input.Justificativa.Trim(),Data=input.DataMovimentacao??DateTimeOffset.UtcNow,UsuarioId=usuarioId,CorrelationId=correlationId},tx,cancellationToken:ct));
        await c.ExecuteAsync(new CommandDefinition("update sigov.patrimonio_bem set unidade_id=@Unidade,responsavel_usuario_id=@Responsavel,localizacao=@Localizacao,updated_at=now(),updated_by=@Usuario where tenant_id=@Tenant and id=@Id",new{Unidade=input.UnidadeDestinoId,Responsavel=input.ResponsavelDestinoId,Localizacao=VazioNulo(input.LocalizacaoDestino),Usuario=usuarioId,Tenant=tenantId,Id=id},tx,cancellationToken:ct)); await Auditar(c,tx,tenantId,"patrimonio_bem",id,"MOVIMENTAR",bem,input,usuarioId,correlationId,ct); await tx.CommitAsync(ct);
    }

    public async Task BaixarBemAsync(long tenantId,long usuarioId,string correlationId,long id,PatrimonioBaixaInput input,CancellationToken ct)
    {
        if(string.IsNullOrWhiteSpace(input.Justificativa)) throw new ArgumentException("A justificativa é obrigatória."); await using var c=factory.CreateConnection(); await c.OpenAsync(ct); await using var tx=await c.BeginTransactionAsync(ct);
        var antes=await ObterJson(c,tx,"patrimonio_bem",tenantId,id,ct)??throw new KeyNotFoundException("Bem não encontrado."); var changed=await c.ExecuteAsync(new CommandDefinition("update sigov.patrimonio_bem set situacao='BAIXADO',ativo=false,updated_at=now(),updated_by=@Usuario where tenant_id=@Tenant and id=@Id and situacao<>'BAIXADO' and not is_deleted",new{Usuario=usuarioId,Tenant=tenantId,Id=id},tx,cancellationToken:ct)); if(changed==0) throw new InvalidOperationException("Bem já baixado ou indisponível.");
        await c.ExecuteAsync(new CommandDefinition("insert into sigov.patrimonio_baixa(tenant_id,bem_id,tipo_baixa,justificativa,data_baixa,valor_baixa,autorizado_por_usuario_id) values(@Tenant,@Id,@Tipo,@Justificativa,@Data,@Valor,@Usuario)",new{Tenant=tenantId,Id=id,Tipo=input.TipoBaixa,Justificativa=input.Justificativa.Trim(),Data=input.DataBaixa,Valor=input.ValorBaixa,Usuario=usuarioId},tx,cancellationToken:ct)); await Auditar(c,tx,tenantId,"patrimonio_bem",id,"BAIXAR",antes,input,usuarioId,correlationId,ct); await tx.CommitAsync(ct);
    }

    public async Task<PatrimonioPagina<PatrimonioInventarioDto>> ListarInventariosAsync(long tenantId,int pagina,int tamanho,CancellationToken ct)
    { pagina=Math.Max(1,pagina);tamanho=Math.Clamp(tamanho,1,100);await using var c=factory.CreateConnection();var total=await c.ExecuteScalarAsync<long>(new CommandDefinition("select count(*) from sigov.patrimonio_inventario where tenant_id=@Tenant",new{Tenant=tenantId},cancellationToken:ct));var items=(await c.QueryAsync<PatrimonioInventarioDto>(new CommandDefinition("select i.id,i.codigo,i.descricao,i.data_abertura DataAbertura,i.data_fechamento DataFechamento,i.situacao,i.unidade_id UnidadeId,i.responsavel_usuario_id ResponsavelUsuarioId,count(ii.id)::int TotalItens,count(ii.conferido_em)::int Conferidos,count(ii.id) filter(where ii.divergencia)::int Divergencias from sigov.patrimonio_inventario i left join sigov.patrimonio_inventario_item ii on ii.inventario_id=i.id and ii.tenant_id=i.tenant_id where i.tenant_id=@Tenant group by i.id order by i.data_abertura desc,i.id desc limit @Limit offset @Offset",new{Tenant=tenantId,Limit=tamanho,Offset=(pagina-1)*tamanho},cancellationToken:ct))).AsList();return new(items,pagina,tamanho,total); }

    public async Task<PatrimonioInventarioDetalhe?> ObterInventarioAsync(long tenantId,long id,CancellationToken ct)
    { await using var c=factory.CreateConnection();var inv=await c.QuerySingleOrDefaultAsync<PatrimonioInventarioDto>(new CommandDefinition("select i.id,i.codigo,i.descricao,i.data_abertura DataAbertura,i.data_fechamento DataFechamento,i.situacao,i.unidade_id UnidadeId,i.responsavel_usuario_id ResponsavelUsuarioId,count(ii.id)::int TotalItens,count(ii.conferido_em)::int Conferidos,count(ii.id) filter(where ii.divergencia)::int Divergencias from sigov.patrimonio_inventario i left join sigov.patrimonio_inventario_item ii on ii.inventario_id=i.id and ii.tenant_id=i.tenant_id where i.tenant_id=@Tenant and i.id=@Id group by i.id",new{Tenant=tenantId,Id=id},cancellationToken:ct));if(inv is null)return null;var itens=(await c.QueryAsync<PatrimonioInventarioItemDto>(new CommandDefinition("select ii.id,ii.bem_id BemId,b.codigo_tombo CodigoTombo,b.descricao,ii.localizado,b.estado_conservacao EstadoCadastro,ii.estado_informado EstadoInformado,b.localizacao LocalizacaoCadastro,ii.localizacao_informada LocalizacaoInformada,ii.divergencia,ii.descricao_divergencia DescricaoDivergencia,ii.conferido_em ConferidoEm from sigov.patrimonio_inventario_item ii join sigov.patrimonio_bem b on b.id=ii.bem_id and b.tenant_id=ii.tenant_id where ii.tenant_id=@Tenant and ii.inventario_id=@Id order by b.codigo_tombo",new{Tenant=tenantId,Id=id},cancellationToken:ct))).AsList();return new(inv,itens); }

    public async Task<long> AbrirInventarioAsync(long tenantId,long usuarioId,string correlationId,PatrimonioInventarioInput input,CancellationToken ct)
    { if(string.IsNullOrWhiteSpace(input.Codigo)||string.IsNullOrWhiteSpace(input.Descricao))throw new ArgumentException("Código e descrição são obrigatórios.");await using var c=factory.CreateConnection();await c.OpenAsync(ct);await using var tx=await c.BeginTransactionAsync(ct);var id=await c.ExecuteScalarAsync<long>(new CommandDefinition("insert into sigov.patrimonio_inventario(tenant_id,codigo,descricao,data_abertura,situacao,unidade_id,responsavel_usuario_id,created_by,updated_by) values(@Tenant,@Codigo,@Descricao,current_date,'ABERTO',@Unidade,@Responsavel,@Usuario,@Usuario) returning id",new{Tenant=tenantId,Codigo=input.Codigo.Trim(),Descricao=input.Descricao.Trim(),Unidade=input.UnidadeId,Responsavel=input.ResponsavelUsuarioId,Usuario=usuarioId},tx,cancellationToken:ct));await c.ExecuteAsync(new CommandDefinition("insert into sigov.patrimonio_inventario_item(tenant_id,inventario_id,bem_id) select @Tenant,@Inventario,id from sigov.patrimonio_bem where tenant_id=@Tenant and not is_deleted and situacao<>'BAIXADO' and (@Unidade is null or unidade_id=@Unidade) and (@Responsavel is null or responsavel_usuario_id=@Responsavel) on conflict(inventario_id,bem_id) do nothing",new{Tenant=tenantId,Inventario=id,Unidade=input.UnidadeId,Responsavel=input.ResponsavelUsuarioId},tx,cancellationToken:ct));await Auditar(c,tx,tenantId,"patrimonio_inventario",id,"ABRIR",null,input,usuarioId,correlationId,ct);await tx.CommitAsync(ct);return id; }

    public async Task ConferirItemAsync(long tenantId,long usuarioId,string correlationId,long inventarioId,long itemId,PatrimonioConferenciaInput input,CancellationToken ct)
    { await using var c=factory.CreateConnection();await c.OpenAsync(ct);await using var tx=await c.BeginTransactionAsync(ct);var row=await c.QuerySingleOrDefaultAsync<ItemEstado>(new CommandDefinition("select i.situacao,b.estado_conservacao Estado,b.localizacao from sigov.patrimonio_inventario_item ii join sigov.patrimonio_inventario i on i.id=ii.inventario_id and i.tenant_id=ii.tenant_id join sigov.patrimonio_bem b on b.id=ii.bem_id and b.tenant_id=ii.tenant_id where ii.tenant_id=@Tenant and ii.inventario_id=@Inventario and ii.id=@Item for update",new{Tenant=tenantId,Inventario=inventarioId,Item=itemId},tx,cancellationToken:ct))??throw new KeyNotFoundException("Item de inventário não encontrado.");if(row.Situacao!="ABERTO")throw new InvalidOperationException("Inventário fechado não aceita conferência.");var divergencia=!input.Localizado||!Igual(row.Estado,input.EstadoInformado)||!Igual(row.Localizacao,input.LocalizacaoInformada);await c.ExecuteAsync(new CommandDefinition("update sigov.patrimonio_inventario_item set localizado=@Localizado,estado_informado=@Estado,localizacao_informada=@Localizacao,divergencia=@Divergencia,descricao_divergencia=@Descricao,conferido_por_usuario_id=@Usuario,conferido_em=now(),observacao=@Observacao where tenant_id=@Tenant and inventario_id=@Inventario and id=@Item",new{input.Localizado,Estado=VazioNulo(input.EstadoInformado),Localizacao=VazioNulo(input.LocalizacaoInformada),Divergencia=divergencia,Descricao=VazioNulo(input.DescricaoDivergencia),Usuario=usuarioId,input.Observacao,Tenant=tenantId,Inventario=inventarioId,Item=itemId},tx,cancellationToken:ct));await Auditar(c,tx,tenantId,"patrimonio_inventario_item",itemId,"CONFERIR",row,input with { DescricaoDivergencia=divergencia?input.DescricaoDivergencia:null },usuarioId,correlationId,ct);await tx.CommitAsync(ct); }

    public async Task FecharInventarioAsync(long tenantId,long usuarioId,string correlationId,long id,CancellationToken ct)
    { await using var c=factory.CreateConnection();await c.OpenAsync(ct);await using var tx=await c.BeginTransactionAsync(ct);var pendentes=await c.ExecuteScalarAsync<int>(new CommandDefinition("select count(*) from sigov.patrimonio_inventario_item ii join sigov.patrimonio_inventario i on i.id=ii.inventario_id and i.tenant_id=ii.tenant_id where ii.tenant_id=@Tenant and i.id=@Id and i.situacao='ABERTO' and ii.conferido_em is null",new{Tenant=tenantId,Id=id},tx,cancellationToken:ct));if(pendentes>0)throw new InvalidOperationException($"Existem {pendentes} itens sem conferência.");var n=await c.ExecuteAsync(new CommandDefinition("update sigov.patrimonio_inventario set situacao='FECHADO',data_fechamento=current_date,updated_at=now(),updated_by=@Usuario where tenant_id=@Tenant and id=@Id and situacao='ABERTO'",new{Usuario=usuarioId,Tenant=tenantId,Id=id},tx,cancellationToken:ct));if(n==0)throw new InvalidOperationException("Inventário não está aberto.");await Auditar(c,tx,tenantId,"patrimonio_inventario",id,"FECHAR",null,new{id},usuarioId,correlationId,ct);await tx.CommitAsync(ct); }

    public async Task<PatrimonioDashboard> ObterDashboardAsync(long tenantId,CancellationToken ct)
    { await using var c=factory.CreateConnection();var total=await c.ExecuteScalarAsync<long>(new CommandDefinition("select count(*) from sigov.patrimonio_bem where tenant_id=@Tenant and not is_deleted",new{Tenant=tenantId},cancellationToken:ct));var situacao=(await c.QueryAsync<PatrimonioAgrupamento>(new CommandDefinition("select situacao Nome,count(*) Total from sigov.patrimonio_bem where tenant_id=@Tenant and not is_deleted group by situacao",new{Tenant=tenantId},cancellationToken:ct))).ToDictionary(x=>x.Nome,x=>x.Total);var estado=(await c.QueryAsync<PatrimonioAgrupamento>(new CommandDefinition("select estado_conservacao Nome,count(*) Total from sigov.patrimonio_bem where tenant_id=@Tenant and not is_deleted group by estado_conservacao",new{Tenant=tenantId},cancellationToken:ct))).ToDictionary(x=>x.Nome,x=>x.Total);var unidades=(await c.QueryAsync<PatrimonioAgrupamento>(new CommandDefinition("select coalesce(unidade_id::text,'Sem unidade') Nome,count(*) Total from sigov.patrimonio_bem where tenant_id=@Tenant and not is_deleted group by unidade_id order by count(*) desc limit 10",new{Tenant=tenantId},cancellationToken:ct))).AsList();var resumo=await c.QuerySingleAsync<Resumo>(new CommandDefinition("select (select count(*) from sigov.patrimonio_inventario where tenant_id=@Tenant and situacao='ABERTO') Inventarios,(select count(*) from sigov.patrimonio_inventario_item ii join sigov.patrimonio_inventario i on i.id=ii.inventario_id and i.tenant_id=ii.tenant_id where ii.tenant_id=@Tenant and ii.divergencia and i.situacao='ABERTO') Divergencias,(select count(*) from sigov.patrimonio_baixa where tenant_id=@Tenant and data_baixa>=date_trunc('month',current_date)) Baixas",new{Tenant=tenantId},cancellationToken:ct));return new(total,situacao,estado,unidades,resumo.Inventarios,resumo.Divergencias,resumo.Baixas); }

    public async Task<byte[]> ExportarCsvAsync(long tenantId,PatrimonioBemFiltro filtro,CancellationToken ct)
    { var pagina=await ListarBensAsync(tenantId,filtro with{Pagina=1,TamanhoPagina=100},ct);var sb=new StringBuilder("Tombo;Descrição;Categoria;Tipo;Estado;Situação;Unidade;Localização;Valor atual\r\n");foreach(var b in pagina.Itens)sb.AppendJoin(';',Csv(b.CodigoTombo),Csv(b.Descricao),Csv(b.Categoria),Csv(b.TipoBem),Csv(b.EstadoConservacao),Csv(b.Situacao),Csv(b.UnidadeId?.ToString()),Csv(b.Localizacao),Csv(b.ValorAtual?.ToString("0.00",CultureInfo.InvariantCulture))).Append("\r\n");return Encoding.UTF8.GetPreamble().Concat(Encoding.UTF8.GetBytes(sb.ToString())).ToArray(); }

    private static object Args(PatrimonioBemInput i,long tenant,long user)=>new{TenantId=tenant,UsuarioId=user,CodigoTombo=i.CodigoTombo.Trim(),i.CodigoAnterior,Descricao=i.Descricao.Trim(),i.CategoriaId,TipoBem=i.TipoBem.Trim(),i.Marca,i.Modelo,i.NumeroSerie,i.DataAquisicao,i.ValorAquisicao,i.ValorAtual,EstadoConservacao=i.EstadoConservacao.Trim().ToUpperInvariant(),i.UnidadeId,i.SetorId,i.ResponsavelUsuarioId,Localizacao=VazioNulo(i.Localizacao),Observacao=VazioNulo(i.Observacao)};
    private static void ValidarBem(PatrimonioBemInput i){if(string.IsNullOrWhiteSpace(i.CodigoTombo))throw new ArgumentException("Tombo obrigatório.");if(string.IsNullOrWhiteSpace(i.Descricao))throw new ArgumentException("Descrição obrigatória.");if(string.IsNullOrWhiteSpace(i.TipoBem)||string.IsNullOrWhiteSpace(i.EstadoConservacao))throw new ArgumentException("Tipo e estado de conservação são obrigatórios.");if(i.CodigoTombo.Length>80||i.Descricao.Length>500)throw new ArgumentException("Tombo ou descrição excede o tamanho permitido.");}
    private static async Task<string?> ObterJson(NpgsqlConnection c,NpgsqlTransaction tx,string tabela,long tenant,long id,CancellationToken ct)=>await c.ExecuteScalarAsync<string?>(new CommandDefinition($"select to_jsonb(x)::text from (select * from sigov.{tabela} where tenant_id=@Tenant and id=@Id and not is_deleted) x",new{Tenant=tenant,Id=id},tx,cancellationToken:ct));
    private static Task Auditar(NpgsqlConnection c,NpgsqlTransaction tx,long tenant,string entidade,long id,string operacao,object? antes,object? depois,long usuario,string correlation,CancellationToken ct)=>c.ExecuteAsync(new CommandDefinition("insert into sigov.patrimonio_auditoria(tenant_id,entidade,entidade_id,operacao,antes,depois,usuario_id,correlation_id) values(@Tenant,@Entidade,@Id,@Operacao,cast(@Antes as jsonb),cast(@Depois as jsonb),@Usuario,@Correlation)",new{Tenant=tenant,Entidade=entidade,Id=id,Operacao=operacao,Antes=antes is string s?s:antes is null?null:JsonSerializer.Serialize(antes),Depois=depois is null?null:JsonSerializer.Serialize(depois),Usuario=usuario,Correlation=correlation},tx,cancellationToken:ct));
    private static string? VazioNulo(string? value)=>string.IsNullOrWhiteSpace(value)?null:value.Trim(); private static bool Igual(string? a,string? b)=>string.Equals(VazioNulo(a),VazioNulo(b),StringComparison.OrdinalIgnoreCase);
    private static string Csv(string? value){value??="";if(value.Length>0&&"=+-@\t\r".Contains(value[0]))value="'"+value;return '"'+value.Replace("\"","\"\"")+'"';}
    private sealed record BemEstado(long? UnidadeId,long? ResponsavelId,string? Localizacao,string Situacao); private sealed record ItemEstado(string Situacao,string Estado,string? Localizacao); private sealed record Resumo(long Inventarios,long Divergencias,long Baixas);
}
