namespace Sigov.Domain.Agro.Enums;

public enum AgroServicoMaquinaTipo { ARACAO, GRADAGEM, TERRAPLANAGEM, TRANSPORTE, ROCAGEM, PERFURACAO, LIMPEZA_ACUDE, ABERTURA_ESTRADA, MANUTENCAO_ESTRADA, OUTROS }
