namespace Sigov.Domain.Agro.Enums;

public enum AgroProgramaTipo { CORTE_TERRA, DISTRIBUICAO_SEMENTES, DISTRIBUICAO_MUDAS, CALCARIO_ADUBO, AGRICULTURA_FAMILIAR, PATRULHA_MECANIZADA, APOIO_PECUARIA, FEIRAS, AGROINDUSTRIA, OUTROS }
