using Microsoft.Extensions.Logging;
using Sigov.Application.Abstractions;
using Sigov.Application.Agro.Permissions;
using Sigov.Application.Common;
using Sigov.Domain.Common;

namespace Sigov.Application.Agro.Producao;

public sealed class AgroProducaoAgricolaService : IAgroProducaoAgricolaService
{
    private readonly IAgroAccessChecker _access; private readonly AgroProducaoAgricolaValidator _validator; private readonly AgroProducaoAgricolaMapper _mapper; private readonly IAgroProducaoRepository _repository; private readonly IAuditService _audit; private readonly ILogger<AgroProducaoAgricolaService> _logger;
    public AgroProducaoAgricolaService(IAgroAccessChecker access, AgroProducaoAgricolaValidator validator, AgroProducaoAgricolaMapper mapper, IAgroProducaoRepository repository, IAuditService audit, ILogger<AgroProducaoAgricolaService> logger) { _access = access; _validator = validator; _mapper = mapper; _repository = repository; _audit = audit; _logger = logger; }
    public async Task<Result<PagedResult<AgroProducaoAgricolaResponse>>> ListarAsync(AgroProducaoAgricolaFiltro filtro, CancellationToken ct) { var c = await Ctx(AgroPermissions.ProducaoVisualizar, ct); if (c.IsFailure) return Result<PagedResult<AgroProducaoAgricolaResponse>>.Failure(c.Error!); var e = Ent(c.Value!); if (e.IsFailure) return Result<PagedResult<AgroProducaoAgricolaResponse>>.Failure(e.Error!); var f = filtro with { Page = Math.Max(1, filtro.Page), PageSize = Math.Clamp(filtro.PageSize, 1, 100) }; return Result<PagedResult<AgroProducaoAgricolaResponse>>.Success(await _repository.ListarAsync(c.Value!.TenantId, c.Value.EntidadeId!.Value, c.Value.ExercicioId, f, ct)); }
    public async Task<Result<AgroProducaoAgricolaResponse>> ObterAsync(long id, CancellationToken ct) { var c = await Ctx(AgroPermissions.ProducaoVisualizar, ct); if (c.IsFailure) return Result<AgroProducaoAgricolaResponse>.Failure(c.Error!); var e = Ent(c.Value!); if (e.IsFailure) return Result<AgroProducaoAgricolaResponse>.Failure(e.Error!); var row = await _repository.ObterAsync(c.Value!.TenantId, c.Value.EntidadeId!.Value, id, ct); return row is null ? Result<AgroProducaoAgricolaResponse>.Failure("Produção agrícola não encontrada.") : Result<AgroProducaoAgricolaResponse>.Success(row); }
    public async Task<Result<long>> CriarAsync(AgroProducaoAgricolaCreateRequest r, CancellationToken ct) { var c = await Ctx(AgroPermissions.ProducaoCriar, ct); if (c.IsFailure) return Result<long>.Failure(c.Error!); var e = Ent(c.Value!); if (e.IsFailure) return Result<long>.Failure(e.Error!); var v = _validator.Validar(r, c.Value!.ExercicioId); if (v.IsFailure) return Result<long>.Failure(v.Error!); var prod = _mapper.CalcularProdutividade(r); var id = await _repository.CriarAsync(c.Value.TenantId, c.Value.EntidadeId!.Value, c.Value.ExercicioId, c.Value.UsuarioId, r, prod, ct); await Audit("CRIAR", id, r, ct); _logger.LogInformation("Produção agrícola Agro {Id} criada.", id); return Result<long>.Success(id); }
    public async Task<Result> AtualizarAsync(long id, AgroProducaoAgricolaCreateRequest r, CancellationToken ct) { var c = await Ctx(AgroPermissions.ProducaoEditar, ct); if (c.IsFailure) return Result.Failure(c.Error!); var e = Ent(c.Value!); if (e.IsFailure) return e; var v = _validator.Validar(r, c.Value!.ExercicioId); if (v.IsFailure) return v; await _repository.AtualizarAsync(c.Value.TenantId, c.Value.EntidadeId!.Value, id, c.Value.ExercicioId, c.Value.UsuarioId, r, _mapper.CalcularProdutividade(r), ct); await Audit("EDITAR", id, r, ct); return Result.Success(); }
    public async Task<Result> ExcluirAsync(long id, CancellationToken ct) { var c = await Ctx(AgroPermissions.ProducaoExcluir, ct); if (c.IsFailure) return Result.Failure(c.Error!); var e = Ent(c.Value!); if (e.IsFailure) return e; await _repository.ExcluirAsync(c.Value!.TenantId, c.Value.EntidadeId!.Value, id, c.Value.UsuarioId, ct); await Audit("EXCLUIR", id, new { isDeleted = true }, ct); return Result.Success(); }
    private Task<Result<AgroAccessContext>> Ctx(string p, CancellationToken ct) => _access.CheckAsync(new AgroAccessRequest(p, "agro.producao"), ct);
    private static Result Ent(AgroAccessContext c) => c.EntidadeId.HasValue ? Result.Success() : Result.Failure("Entidade atual obrigatória para Agro.");
    private async Task Audit(string acao, long id, object novo, CancellationToken ct) { try { await _audit.RegistrarAsync("agro", acao, "sigov.agro_producao_agricola", id.ToString(System.Globalization.CultureInfo.InvariantCulture), null, novo, ct); } catch (Exception ex) { _logger.LogWarning(ex, "Falha ao auditar produção Agro."); } }
}
