using System.Globalization;
using System.Text;
using System.Text.Json;
using Dapper;
using Sigov.Application.Obras.Engenharia;
using Sigov.Infrastructure.Persistence.Dapper;
namespace Sigov.Infrastructure.Obras;

public sealed class ObrasEngenhariaRepository(DapperContext db) : IObrasEngenhariaRepository
{
 private static readonly IReadOnlyDictionary<string,string> Tables=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase){
  ["projetos"]="obras_projeto",["orcamentos"]="obras_orcamento",["cronogramas"]="obras_cronograma",["medicoes"]="obras_medicao",["diarios"]="obras_diario",["fiscalizacoes"]="obras_fiscalizacao",["ocorrencias"]="obras_ocorrencia",["ordens-servico"]="obras_ordem_servico",["convenios"]="obras_convenio",["documentos"]="obras_documento_tecnico",["integracao-financeira"]="obras_integracao_financeira",["auditoria"]="obras_auditoria"};
 public async Task<ObrasDashboard> DashboardAsync(ObrasContexto c,ObrasFiltro f,CancellationToken ct){using var cn=db.CreateConnection();const string sql="""
 select count(*) filter(where status='PLANEJADA') Planejadas,count(*) filter(where status in ('LICITADA','CONTRATADA')) Contratadas,count(*) filter(where status='EM_EXECUCAO') EmExecucao,count(*) filter(where status='PARALISADA') Paralisadas,count(*) filter(where status='CONCLUIDA') Concluidas,coalesce(sum(valor_contratado),0) ValorContratado,
 coalesce((select sum(m.valor_medido) from sigov.obras_medicao m where m.tenant_id=@TenantId and m.entidade_id=@EntidadeId and m.status in('APROVADA','HOMOLOGADA') and not m.is_deleted),0) ValorMedido,
 greatest(coalesce(sum(valor_contratado),0)-coalesce((select sum(m.valor_medido) from sigov.obras_medicao m where m.tenant_id=@TenantId and m.entidade_id=@EntidadeId and m.status in('APROVADA','HOMOLOGADA') and not m.is_deleted),0),0) SaldoMedir,
 (select count(*) from sigov.obras_medicao m where m.tenant_id=@TenantId and m.entidade_id=@EntidadeId and m.status in('RASCUNHO','EM_ANALISE') and not m.is_deleted) MedicoesPendentes,
 (select count(*) from sigov.obras_fiscalizacao x where x.tenant_id=@TenantId and x.entidade_id=@EntidadeId and x.status in('AGENDADA','PENDENTE_CORRECAO') and not x.is_deleted) FiscalizacoesPendentes,
 (select count(*) from sigov.obras_ordem_servico x where x.tenant_id=@TenantId and x.entidade_id=@EntidadeId and x.status in('ABERTA','ATRIBUIDA','EM_EXECUCAO') and not x.is_deleted) OrdensAbertas
 from sigov.obras_obra where tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted;
 """;return await cn.QuerySingleAsync<ObrasDashboard>(new CommandDefinition(sql,c,cancellationToken:ct));}
 public async Task<ObrasPagina> ListarObrasAsync(ObrasContexto c,ObrasFiltro f,CancellationToken ct){var p=Math.Max(1,f.Pagina);var n=Math.Clamp(f.Tamanho,1,100);using var cn=db.CreateConnection();const string where="tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted and (@Busca is null or codigo ilike '%'||@Busca||'%' or nome ilike '%'||@Busca||'%') and (@Status is null or status=@Status) and (@Unidade is null or unidade ilike '%'||@Unidade||'%') and (@Localidade is null or localidade ilike '%'||@Localidade||'%') and (@Fiscal is null or fiscal ilike '%'||@Fiscal||'%') and (@Fonte is null or fonte_recurso ilike '%'||@Fonte||'%') and (@Inicio is null or fim_previsto>=@Inicio) and (@Fim is null or inicio_previsto<=@Fim)";var a=new{c.TenantId,c.EntidadeId,f.Busca,f.Status,f.Unidade,f.Localidade,f.Fiscal,f.Fonte,f.Inicio,f.Fim,Limit=n,Offset=(p-1)*n};var total=await cn.ExecuteScalarAsync<long>(new CommandDefinition($"select count(*) from sigov.obras_obra where {where}",a,cancellationToken:ct));var rows=(await cn.QueryAsync<ObraResumo>(new CommandDefinition($"select id,codigo,nome,tipo_obra Tipo,unidade,localidade,valor_contratado ValorContratado,status,inicio_previsto InicioPrevisto,fim_previsto FimPrevisto from sigov.obras_obra where {where} order by updated_at desc limit @Limit offset @Offset",a,cancellationToken:ct))).AsList();return new(rows,p,n,total);}
 public async Task<long> SalvarObraAsync(ObrasContexto c,ObraRequest r,long? id,CancellationToken ct){ValidarObra(r);using var cn=db.CreateConnection();var antes=id is null?null:await cn.QuerySingleOrDefaultAsync<string>(new CommandDefinition("select row_to_json(o)::text from sigov.obras_obra o where id=@id and tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted",new{id,c.TenantId,c.EntidadeId},cancellationToken:ct));const string insert="""insert into sigov.obras_obra(codigo,nome,descricao,tipo_obra,unidade,localidade,endereco,latitude,longitude,valor_estimado,valor_contratado,inicio_previsto,fim_previsto,inicio_real,fim_real,status,fiscal,observacoes,justificativa,contrato_referencia,fonte_recurso,tenant_id,entidade_id,created_by) values(@Codigo,@Nome,@Descricao,@TipoObra,@Unidade,@Localidade,@Endereco,@Latitude,@Longitude,@ValorEstimado,@ValorContratado,@InicioPrevisto,@FimPrevisto,@InicioReal,@FimReal,@Status,@Fiscal,@Observacoes,@Justificativa,@ContratoReferencia,@FonteRecurso,@TenantId,@EntidadeId,@UsuarioId) returning id""";const string update="""update sigov.obras_obra set codigo=@Codigo,nome=@Nome,descricao=@Descricao,tipo_obra=@TipoObra,unidade=@Unidade,localidade=@Localidade,endereco=@Endereco,latitude=@Latitude,longitude=@Longitude,valor_estimado=@ValorEstimado,valor_contratado=@ValorContratado,inicio_previsto=@InicioPrevisto,fim_previsto=@FimPrevisto,inicio_real=@InicioReal,fim_real=@FimReal,status=@Status,fiscal=@Fiscal,observacoes=@Observacoes,justificativa=@Justificativa,contrato_referencia=@ContratoReferencia,fonte_recurso=@FonteRecurso,updated_by=@UsuarioId,updated_at=now() where id=@Id and tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted returning id""";var args=new DynamicParameters(r);args.Add("TenantId",c.TenantId);args.Add("EntidadeId",c.EntidadeId);args.Add("UsuarioId",c.UsuarioId);args.Add("Id",id);var saved=await cn.ExecuteScalarAsync<long?>(new CommandDefinition(id is null?insert:update,args,cancellationToken:ct))??throw new KeyNotFoundException("Obra não encontrada.");await Audit(c,cn,id is null?"CRIAR":"ALTERAR","obra",saved,antes,JsonSerializer.Serialize(r),ct);return saved;}
 public async Task ExcluirObraAsync(ObrasContexto c,long id,string justificativa,CancellationToken ct){if(string.IsNullOrWhiteSpace(justificativa))throw new ArgumentException("Justificativa é obrigatória.");using var cn=db.CreateConnection();var n=await cn.ExecuteAsync(new CommandDefinition("update sigov.obras_obra set ativo=false,is_deleted=true,deleted_at=now(),deleted_by=@UsuarioId,justificativa=@justificativa where id=@id and tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted",new{id,justificativa,c.UsuarioId,c.TenantId,c.EntidadeId},cancellationToken:ct));if(n==0)throw new KeyNotFoundException();await Audit(c,cn,"EXCLUIR","obra",id,null,null,ct);}
 public async Task<IReadOnlyList<ObrasRegistro>> ListarAsync(ObrasContexto c,string recurso,ObrasFiltro f,CancellationToken ct){var t=Table(recurso);using var cn=db.CreateConnection();var sql=$"select id,obra_id ObraId,codigo,descricao,status,valor,data,dados::text DadosJson,created_at CriadoEm from sigov.{t} where tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted and (@Busca is null or codigo ilike '%'||@Busca||'%' or descricao ilike '%'||@Busca||'%') and (@Status is null or status=@Status) order by id desc limit @Limit offset @Offset";return (await cn.QueryAsync<ObrasRegistro>(new CommandDefinition(sql,new{c.TenantId,c.EntidadeId,f.Busca,f.Status,Limit=Math.Clamp(f.Tamanho,1,100),Offset=(Math.Max(f.Pagina,1)-1)*f.Tamanho},cancellationToken:ct))).AsList();}
 public async Task<long> SalvarAsync(ObrasContexto c,string recurso,ObrasRegistroRequest r,long? id,CancellationToken ct){Validar(recurso,r);var t=Table(recurso);using var cn=db.CreateConnection();var sql=id is null?$"insert into sigov.{t}(obra_id,codigo,descricao,status,valor,data,justificativa,dados,tenant_id,entidade_id,created_by) values(@ObraId,@Codigo,@Descricao,@Status,@Valor,@Data,@Justificativa,cast(@DadosJson as jsonb),@TenantId,@EntidadeId,@UsuarioId) returning id":$"update sigov.{t} set obra_id=@ObraId,codigo=@Codigo,descricao=@Descricao,status=@Status,valor=@Valor,data=@Data,justificativa=@Justificativa,dados=cast(@DadosJson as jsonb),updated_at=now(),updated_by=@UsuarioId where id=@Id and tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted {(recurso.Equals("medicoes",StringComparison.OrdinalIgnoreCase)?"and status not in ('APROVADA','HOMOLOGADA')":"")} returning id";var a=new DynamicParameters(r);a.Add("TenantId",c.TenantId);a.Add("EntidadeId",c.EntidadeId);a.Add("UsuarioId",c.UsuarioId);a.Add("Id",id);var saved=await cn.ExecuteScalarAsync<long?>(new CommandDefinition(sql,a,cancellationToken:ct))??throw new InvalidOperationException("Registro bloqueado, inexistente ou fora do contexto.");await Audit(c,cn,id is null?"CRIAR":"ALTERAR",recurso,saved,null,JsonSerializer.Serialize(r),ct);return saved;}
 public async Task HomologarMedicaoAsync(ObrasContexto c,long id,CancellationToken ct){using var cn=db.CreateConnection();cn.Open();using var tx=cn.BeginTransaction();var n=await cn.ExecuteAsync(new CommandDefinition("update sigov.obras_medicao m set status='HOMOLOGADA',homologada_at=now(),updated_by=@UsuarioId,updated_at=now() where m.id=@id and m.tenant_id=@TenantId and m.entidade_id=@EntidadeId and m.status='APROVADA' and not m.is_deleted and m.valor <= (select least(o.valor_contratado,coalesce(sum(oi.valor_total),o.valor_contratado)) from sigov.obras_obra o left join sigov.obras_orcamento_item oi on oi.obra_id=o.id and oi.ativo and not oi.is_deleted where o.id=m.obra_id group by o.id)",new{id,c.TenantId,c.EntidadeId,c.UsuarioId},tx,cancellationToken:ct));if(n==0)throw new InvalidOperationException("Medição deve estar aprovada e respeitar o saldo contratado/orçado.");await cn.ExecuteAsync(new CommandDefinition("insert into sigov.obras_integracao_financeira(obra_id,medicao_id,codigo,descricao,status,valor,data,dados,tenant_id,entidade_id,created_by) select obra_id,id,codigo,'Medição homologada para integração futura','PENDENTE',valor,current_date,'{}',tenant_id,entidade_id,@UsuarioId from sigov.obras_medicao where id=@id on conflict(medicao_id) do nothing",new{id,c.UsuarioId},tx,cancellationToken:ct));await Audit(c,cn,"HOMOLOGAR","medicoes",id,null,null,ct,tx);tx.Commit();}
 public async Task<byte[]> ExportarCsvAsync(ObrasContexto c,string relatorio,ObrasFiltro f,CancellationToken ct){if(relatorio is not("obras-status-localidade" or "obras-unidade" or "orcamento" or "cronograma" or "medicoes-periodo" or "medicoes-homologadas" or "diario" or "fiscalizacoes" or "ocorrencias-ordens" or "convenios-repasses" or "integracao-financeira" or "auditoria"))throw new ArgumentException("Relatório inválido.");using var cn=db.CreateConnection();var table=relatorio switch{"obras-status-localidade" or "obras-unidade"=>"obras_obra","orcamento"=>"obras_orcamento_item","cronograma"=>"obras_cronograma","medicoes-periodo" or "medicoes-homologadas"=>"obras_medicao","diario"=>"obras_diario","fiscalizacoes"=>"obras_fiscalizacao","ocorrencias-ordens"=>"obras_ordem_servico","convenios-repasses"=>"obras_convenio","integracao-financeira"=>"obras_integracao_financeira",_=>"obras_auditoria"};var projection=table=="obras_obra"?"id,codigo,nome descricao,status,valor_contratado valor,created_at":table=="obras_orcamento_item"?"id,codigo,descricao,status,valor_total valor,created_at":"id,coalesce(codigo,'') codigo,coalesce(descricao,'') descricao,coalesce(status,'') status,coalesce(valor,0) valor,created_at";var rows=await cn.QueryAsync<dynamic>(new CommandDefinition($"select {projection} from sigov.{table} where tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted {(relatorio=="medicoes-homologadas"?"and status='HOMOLOGADA'":"")} order by id",c,cancellationToken:ct));var b=new StringBuilder("id;codigo;descricao;status;valor;data\r\n");foreach(var x in rows)b.AppendLine($"{x.id};{Csv(x.codigo)};{Csv(x.descricao)};{Csv(x.status)};{x.valor.ToString(CultureInfo.InvariantCulture)};{x.created_at:O}");await Audit(c,cn,"EXPORTAR",relatorio,null,null,null,ct);return new UTF8Encoding(true).GetBytes(b.ToString());}
 private static string Table(string r)=>Tables.TryGetValue(r,out var t)?t:throw new ArgumentException("Recurso inválido.");
 private static void ValidarObra(ObraRequest r){if(string.IsNullOrWhiteSpace(r.Codigo)||string.IsNullOrWhiteSpace(r.Nome))throw new ArgumentException("Código e nome são obrigatórios.");if(r.ValorEstimado<0||r.ValorContratado<0||r.FimPrevisto<r.InicioPrevisto)throw new ArgumentException("Valores e datas inválidos.");if((r.Status is "PARALISADA" or "CANCELADA" or "RESCINDIDA")&&string.IsNullOrWhiteSpace(r.Justificativa))throw new ArgumentException("O status exige justificativa.");}
 private static void Validar(string recurso,ObrasRegistroRequest r){if(r.ObraId<=0||string.IsNullOrWhiteSpace(r.Descricao))throw new ArgumentException("Obra e descrição são obrigatórias.");if(r.Valor<0)throw new ArgumentException("Valor não pode ser negativo.");if(r.Status=="CANCELADA"&&string.IsNullOrWhiteSpace(r.Justificativa))throw new ArgumentException("Cancelamento exige justificativa.");if(recurso=="projetos"&&r.Status=="SUBSTITUIDO"&&string.IsNullOrWhiteSpace(r.Justificativa))throw new ArgumentException("Substituição exige justificativa.");}
 private static string Csv(object? v){var s=Convert.ToString(v,CultureInfo.InvariantCulture)??"";if(s.Length>0&&"=+-@\t\r".Contains(s[0]))s="'"+s;return '"'+s.Replace("\"","\"\"")+'"';}
 private static async Task Audit(ObrasContexto c,System.Data.IDbConnection cn,string acao,string recurso,long? id,string? antes,string? depois,CancellationToken ct,System.Data.IDbTransaction? tx=null)=>await cn.ExecuteAsync(new CommandDefinition("insert into sigov.obras_auditoria(acao,recurso,registro_id,usuario_id,antes,depois,correlation_id,ip,tenant_id,entidade_id,created_by,codigo,descricao,status,dados) values(@acao,@recurso,@id,@UsuarioId,cast(@antes as jsonb),cast(@depois as jsonb),@CorrelationId,cast(@Ip as inet),@TenantId,@EntidadeId,@UsuarioId,@acao,@recurso,'REGISTRADA','{}')",new{acao,recurso,id,c.UsuarioId,antes,depois,c.CorrelationId,c.Ip,c.TenantId,c.EntidadeId},tx,cancellationToken:ct));
}
