using Sigov.Application.Abstractions; using Sigov.Application.Common; using Sigov.Domain.Common;
namespace Sigov.Application.Empresarial;
public sealed class EmpresarialService:IEmpresarialComercialService,IEmpresarialComercialDashboardService,IEmpresarialClienteService,IEmpresarialLeadService,IEmpresarialPropostaService,IEmpresarialPedidoService,IEmpresarialOrdemServicoService,IEmpresarialOrdemServicoDashboardService,IEmpresarialOrdemServicoSlaService,IEmpresarialOrdemServicoChecklistService,IEmpresarialEstoqueService,IEmpresarialEstoqueDashboardService,IEmpresarialProdutoService,IEmpresarialMovimentoEstoqueService,IEmpresarialCompraService,IEmpresarialIndustrialService,IEmpresarialIndustrialDashboardService,IEmpresarialAtivoIndustrialService,IEmpresarialPlanoManutencaoService,IEmpresarialProducaoService {
 private static readonly IReadOnlyDictionary<string,string> StatusInicial=new Dictionary<string,string>(StringComparer.Ordinal){["emp_comercial_lead"]="NOVO",["emp_comercial_oportunidade"]="ABERTA",["emp_comercial_proposta"]="RASCUNHO",["emp_comercial_pedido"]="RASCUNHO",["emp_os_ordem"]="ABERTA",["emp_estoque_requisicao"]="RASCUNHO",["emp_compras_pedido"]="RASCUNHO",["emp_industrial_manutencao_programada"]="PROGRAMADA",["emp_industrial_ordem_producao"]="ABERTA"};
 private readonly ICurrentTenant _tenant; private readonly ICurrentUser _user; private readonly IEmpresarialRepository _repo; private readonly IAuditService _audit; public EmpresarialService(ICurrentTenant tenant,ICurrentUser user,IEmpresarialRepository repo,IAuditService audit){_tenant=tenant;_user=user;_repo=repo;_audit=audit;}
 public async Task<Result<PagedResult<EmpresarialRegistroDto>>> ListarAsync(string r,int p,int t,CancellationToken ct)=>!_tenant.TenantId.HasValue?Result<PagedResult<EmpresarialRegistroDto>>.Failure("Tenant obrigatório."):Result<PagedResult<EmpresarialRegistroDto>>.Success(await _repo.ListarAsync(_tenant.TenantId.Value,r,Math.Max(1,p),Math.Clamp(t,1,100),ct));
 public async Task<Result<long>> CriarAsync(string r,EmpresarialOperacaoRequest x,string cid,CancellationToken ct){if(!_tenant.TenantId.HasValue)return Result<long>.Failure("Tenant obrigatório.");if(string.IsNullOrWhiteSpace(x.Titulo)&&string.IsNullOrWhiteSpace(x.Descricao))return Result<long>.Failure("Nome, título ou descrição é obrigatório.");if((r.Contains("proposta",StringComparison.Ordinal)||r.Contains("pedido",StringComparison.Ordinal))&&x.Valor<0)return Result<long>.Failure("Valor não pode ser negativo.");if(r=="emp_estoque_movimento"&&x.Quantidade<=0)return Result<long>.Failure("Quantidade deve ser positiva.");if(x.Status=="ATIVO"&&StatusInicial.TryGetValue(r,out var inicial))x=x with{Status=inicial};var id=await _repo.CriarAsync(_tenant.TenantId.Value,_tenant.EntidadeId,_user.UsuarioId,r,x,cid,ct);await _audit.RegistrarAsync("empresarial","CRIAR",r,id.ToString(),null,new{id,status=x.Status},ct);return Result<long>.Success(id);}
 public async Task<Result> StatusAsync(string r,long id,string status,string? just,string cid,CancellationToken ct){if(!_tenant.TenantId.HasValue)return Result.Failure("Tenant obrigatório.");if(status is "CANCELADA" or "CANCELADO" or "REPROVADA" or "PAUSADA" && string.IsNullOrWhiteSpace(just))return Result.Failure("Justificativa obrigatória.");var ok=await _repo.StatusAsync(_tenant.TenantId.Value,r,id,status,just,_user.UsuarioId,cid,ct);if(!ok)return Result.Failure("Registro não encontrado ou transição inválida.");await _audit.RegistrarAsync("empresarial","STATUS",r,id.ToString(),null,new{status},ct);return Result.Success();}
 public async Task<Result<EmpresarialDashboardDto>> DashboardAsync(string r,CancellationToken ct)=>!_tenant.TenantId.HasValue?Result<EmpresarialDashboardDto>.Failure("Tenant obrigatório."):Result<EmpresarialDashboardDto>.Success(await _repo.DashboardAsync(_tenant.TenantId.Value,r,ct)); }
