using Sigov.Application.Common;
using Sigov.Domain.Common;
namespace Sigov.Application.Empresarial;
public sealed record EmpresarialRegistroDto(long Id,string? Codigo,string Status,string? Titulo,string? Descricao,DateTimeOffset CreatedAt,Dictionary<string,object?> Dados);
public sealed record EmpresarialOperacaoRequest(string? Codigo,string? Titulo,string? Descricao,string? Tipo=null,string Status="ATIVO",long? ReferenciaId=null,decimal? Quantidade=null,decimal? Valor=null,string? Justificativa=null,Dictionary<string,object?>? Dados=null);
public sealed record EmpresarialDashboardDto(long Total,long Abertos,long Alertas,long Concluidos,IReadOnlyCollection<EmpresarialRegistroDto> Recentes);
public sealed record EmpresarialComercialClienteDto(long Id,string Nome,string? DocumentoMascarado,string? EmailMascarado,string? TelefoneMascarado,string Status);
public sealed record EmpresarialComercialCriarClienteRequest(string Nome,string? Documento=null,string? Email=null,string? Telefone=null);
public sealed record EmpresarialComercialLeadDto(long Id,string Nome,string Status); public sealed record EmpresarialComercialCriarLeadRequest(string Nome,string? Email=null,string? Telefone=null);
public sealed record EmpresarialComercialOportunidadeDto(long Id,string Titulo,string Etapa,string Status); public sealed record EmpresarialComercialCriarOportunidadeRequest(string Titulo,long? ClienteId,long EtapaId,decimal Valor);
public sealed record EmpresarialComercialPropostaItemDto(string Descricao,decimal Quantidade,decimal ValorUnitario); public sealed record EmpresarialComercialPropostaDto(long Id,string Numero,string Status,decimal Valor);
public sealed record EmpresarialComercialCriarPropostaRequest(long? ClienteId,long? OportunidadeId,IReadOnlyCollection<EmpresarialComercialPropostaItemDto> Itens);
public sealed record EmpresarialComercialPedidoDto(long Id,string Numero,string Status,decimal Valor); public sealed record EmpresarialComercialGerarPedidoRequest(long PropostaId);
public sealed record EmpresarialComercialTabelaPrecoDto(long Id,string Nome,DateTimeOffset Inicio,DateTimeOffset? Fim); public sealed record EmpresarialComercialAtividadeDto(long Id,string Tipo,string Descricao,DateTimeOffset Data);
public sealed record EmpresarialOrdemServicoDto(long Id,string Numero,string Status,string Prioridade,string Titulo); public sealed record EmpresarialOrdemServicoCriarRequest(long ClienteId,string Titulo,string Tipo,string Prioridade);
public sealed record EmpresarialOrdemServicoAgendarRequest(DateTimeOffset DataPrevista,long ResponsavelId); public sealed record EmpresarialOrdemServicoIniciarRequest(string? Observacao=null); public sealed record EmpresarialOrdemServicoPausarRequest(string Motivo); public sealed record EmpresarialOrdemServicoConcluirRequest(string Resolucao); public sealed record EmpresarialOrdemServicoCancelarRequest(string Justificativa); public sealed record EmpresarialOrdemServicoConsumirPecaRequest(long ProdutoId,long AlmoxarifadoId,decimal Quantidade); public sealed record EmpresarialOrdemServicoApontamentoDto(long TecnicoId,decimal Horas,string Descricao,decimal Custo); public sealed record EmpresarialOrdemServicoChecklistDto(long Id,string Titulo,bool Concluido); public sealed record EmpresarialOrdemServicoSlaDto(long OrdemId,DateTimeOffset Prazo,bool Vencido);
public sealed record EmpresarialEstoqueProdutoDto(long Id,string Codigo,string Nome,string Unidade,decimal Saldo); public sealed record EmpresarialEstoqueCriarProdutoRequest(string Codigo,string Nome,string Unidade,decimal? EstoqueMinimo=null,decimal? EstoqueMaximo=null); public sealed record EmpresarialEstoqueSaldoDto(long ProdutoId,long AlmoxarifadoId,decimal Quantidade); public sealed record EmpresarialEstoqueMovimentoDto(long Id,string Tipo,decimal Quantidade,DateTimeOffset Data); public sealed record EmpresarialEstoqueCriarMovimentoRequest(long ProdutoId,long AlmoxarifadoId,decimal Quantidade,string? Justificativa=null,long? DestinoId=null); public sealed record EmpresarialEstoqueRequisicaoDto(long Id,string Status); public sealed record EmpresarialEstoqueInventarioDto(long Id,string Status); public sealed record EmpresarialCompraFornecedorDto(long Id,string Nome,string? DocumentoMascarado); public sealed record EmpresarialCompraPedidoDto(long Id,string Numero,string Status,decimal Valor); public sealed record EmpresarialCompraCriarPedidoRequest(long FornecedorId,IReadOnlyCollection<EmpresarialComercialPropostaItemDto> Itens);
public sealed record EmpresarialIndustrialAtivoDto(long Id,string Codigo,string Nome,string Criticidade,string Status); public sealed record EmpresarialIndustrialCriarAtivoRequest(string Codigo,string Nome,string Criticidade); public sealed record EmpresarialIndustrialPlanoManutencaoDto(long Id,long AtivoId,string Tipo,int FrequenciaDias); public sealed record EmpresarialIndustrialCriarPlanoRequest(long AtivoId,string Tipo,int FrequenciaDias); public sealed record EmpresarialIndustrialManutencaoProgramadaDto(long Id,DateTimeOffset Prevista,string Status); public sealed record EmpresarialIndustrialMedidorDto(long Id,long AtivoId,string Unidade,decimal UltimaLeitura); public sealed record EmpresarialIndustrialLeituraMedidorRequest(decimal Valor,DateTimeOffset Data); public sealed record EmpresarialIndustrialParadaDto(long Id,long AtivoId,DateTimeOffset Inicio,DateTimeOffset? Fim); public sealed record EmpresarialIndustrialCriarParadaRequest(long AtivoId,DateTimeOffset Inicio,string Motivo,string Causa); public sealed record EmpresarialIndustrialOrdemProducaoDto(long Id,string Numero,string Status); public sealed record EmpresarialIndustrialApontamentoProducaoDto(long OrdemId,long LinhaId,DateTimeOffset Data,decimal Quantidade); public sealed record EmpresarialIndustrialQualidadeOcorrenciaDto(long Id,string Descricao,string Severidade);
public interface IEmpresarialRepository { Task<PagedResult<EmpresarialRegistroDto>> ListarAsync(long tenantId,string tabela,int pagina,int tamanho,CancellationToken ct); Task<long> CriarAsync(long tenantId,long? entidadeId,long? usuarioId,string tabela,EmpresarialOperacaoRequest request,string correlationId,CancellationToken ct); Task<bool> StatusAsync(long tenantId,string tabela,long id,string status,string? justificativa,long? usuarioId,string correlationId,CancellationToken ct); Task<EmpresarialDashboardDto> DashboardAsync(long tenantId,string tabela,CancellationToken ct); }
public interface IEmpresarialService { Task<Result<PagedResult<EmpresarialRegistroDto>>> ListarAsync(string recurso,int pagina,int tamanho,CancellationToken ct); Task<Result<long>> CriarAsync(string recurso,EmpresarialOperacaoRequest request,string correlationId,CancellationToken ct); Task<Result> StatusAsync(string recurso,long id,string status,string? justificativa,string correlationId,CancellationToken ct); Task<Result<EmpresarialDashboardDto>> DashboardAsync(string recurso,CancellationToken ct); }
public interface IEmpresarialComercialRepository:IEmpresarialRepository{} public interface IEmpresarialOrdemServicoRepository:IEmpresarialRepository{} public interface IEmpresarialEstoqueRepository:IEmpresarialRepository{} public interface IEmpresarialIndustrialRepository:IEmpresarialRepository{}
public interface IEmpresarialComercialService:IEmpresarialService{} public interface IEmpresarialComercialDashboardService:IEmpresarialService{} public interface IEmpresarialClienteService:IEmpresarialService{} public interface IEmpresarialLeadService:IEmpresarialService{} public interface IEmpresarialPropostaService:IEmpresarialService{} public interface IEmpresarialPedidoService:IEmpresarialService{}
public interface IEmpresarialOrdemServicoService:IEmpresarialService{} public interface IEmpresarialOrdemServicoDashboardService:IEmpresarialService{} public interface IEmpresarialOrdemServicoSlaService:IEmpresarialService{} public interface IEmpresarialOrdemServicoChecklistService:IEmpresarialService{}
public interface IEmpresarialEstoqueService:IEmpresarialService{} public interface IEmpresarialEstoqueDashboardService:IEmpresarialService{} public interface IEmpresarialProdutoService:IEmpresarialService{} public interface IEmpresarialMovimentoEstoqueService:IEmpresarialService{} public interface IEmpresarialCompraService:IEmpresarialService{}
public interface IEmpresarialIndustrialService:IEmpresarialService{} public interface IEmpresarialIndustrialDashboardService:IEmpresarialService{} public interface IEmpresarialAtivoIndustrialService:IEmpresarialService{} public interface IEmpresarialPlanoManutencaoService:IEmpresarialService{} public interface IEmpresarialProducaoService:IEmpresarialService{}
