using System.Security.Claims;

namespace Sigov.Application.Security;

/// <summary>
/// Canonical definition of permissions exposed by SIGOV applications.
/// API and Web must register authorization policies exclusively from this catalog.
/// </summary>
public sealed record PermissionDefinition(
    string Code,
    string Module,
    string Resource,
    string Action,
    string Description,
    string MenuGroup,
    bool IsAdministrative = false,
    params string[] Aliases);

public static class PermissionCatalog
{
    private const string PurchasingModule = "compras_empresariais";

    public static IReadOnlyList<PermissionDefinition> All { get; } =
    [
        Permission("AMBIENTAL_DASHBOARD_VIEW", "ambiental", "dashboard_view", "visualizar"),
        Permission("AMBIENTAL_EMPREENDEDOR_VIEW", "ambiental", "empreendedor_view", "visualizar"),
        Permission("AMBIENTAL_EMPREENDEDOR_MANAGE", "ambiental", "empreendedor_manage", "gerenciar"),
        Permission("AMBIENTAL_EMPREENDIMENTO_VIEW", "ambiental", "empreendimento_view", "visualizar"),
        Permission("AMBIENTAL_EMPREENDIMENTO_MANAGE", "ambiental", "empreendimento_manage", "gerenciar"),
        Permission("AMBIENTAL_PARAMETRO_VIEW", "ambiental", "parametro_view", "visualizar"),
        Permission("AMBIENTAL_PARAMETRO_MANAGE", "ambiental", "parametro_manage", "gerenciar"),
        Permission("AMBIENTAL_REQUERIMENTO_VIEW", "ambiental", "requerimento_view", "visualizar"),
        Permission("AMBIENTAL_REQUERIMENTO_MANAGE", "ambiental", "requerimento_manage", "gerenciar"),
        Permission("AMBIENTAL_DOCUMENTO_VIEW", "ambiental", "documento_view", "visualizar"),
        Permission("AMBIENTAL_DOCUMENTO_MANAGE", "ambiental", "documento_manage", "gerenciar"),
        Permission("AMBIENTAL_ANALISE_VIEW", "ambiental", "analise_view", "visualizar"),
        Permission("AMBIENTAL_ANALISE_MANAGE", "ambiental", "analise_manage", "gerenciar"),
        Permission("AMBIENTAL_LICENCA_VIEW", "ambiental", "licenca_view", "visualizar"),
        Permission("AMBIENTAL_LICENCA_MANAGE", "ambiental", "licenca_manage", "gerenciar"),
        Permission("AMBIENTAL_CONDICIONANTE_VIEW", "ambiental", "condicionante_view", "visualizar"),
        Permission("AMBIENTAL_CONDICIONANTE_MANAGE", "ambiental", "condicionante_manage", "gerenciar"),
        Permission("AMBIENTAL_VISTORIA_VIEW", "ambiental", "vistoria_view", "visualizar"),
        Permission("AMBIENTAL_VISTORIA_MANAGE", "ambiental", "vistoria_manage", "gerenciar"),
        Permission("AMBIENTAL_DENUNCIA_VIEW", "ambiental", "denuncia_view", "visualizar"),
        Permission("AMBIENTAL_DENUNCIA_MANAGE", "ambiental", "denuncia_manage", "gerenciar"),
        Permission("AMBIENTAL_AUTO_VIEW", "ambiental", "auto_view", "visualizar"),
        Permission("AMBIENTAL_AUTO_MANAGE", "ambiental", "auto_manage", "gerenciar"),
        Permission("AMBIENTAL_TAXA_VIEW", "ambiental", "taxa_view", "visualizar"),
        Permission("AMBIENTAL_TAXA_MANAGE", "ambiental", "taxa_manage", "gerenciar"),
        Permission("AMBIENTAL_RELATORIO_EXPORT", "ambiental", "relatorio_export", "exportar"),
        Permission("AMBIENTAL_AUDITORIA_VIEW", "ambiental", "auditoria_view", "visualizar"),
        Permission("OBRAS_DASHBOARD_VIEW", "obras", "dashboard_view", "visualizar"),
        Permission("OBRAS_OBRA_VIEW", "obras", "obra_view", "visualizar"),
        Permission("OBRAS_OBRA_MANAGE", "obras", "obra_manage", "gerenciar"),
        Permission("OBRAS_PROJETO_VIEW", "obras", "projeto_view", "visualizar"),
        Permission("OBRAS_PROJETO_MANAGE", "obras", "projeto_manage", "gerenciar"),
        Permission("OBRAS_ORCAMENTO_VIEW", "obras", "orcamento_view", "visualizar"),
        Permission("OBRAS_ORCAMENTO_MANAGE", "obras", "orcamento_manage", "gerenciar"),
        Permission("OBRAS_CRONOGRAMA_VIEW", "obras", "cronograma_view", "visualizar"),
        Permission("OBRAS_CRONOGRAMA_MANAGE", "obras", "cronograma_manage", "gerenciar"),
        Permission("OBRAS_MEDICAO_VIEW", "obras", "medicao_view", "visualizar"),
        Permission("OBRAS_MEDICAO_MANAGE", "obras", "medicao_manage", "gerenciar"),
        Permission("OBRAS_MEDICAO_HOMOLOGAR", "obras", "medicao_homologar", "homologar"),
        Permission("OBRAS_DIARIO_VIEW", "obras", "diario_view", "visualizar"),
        Permission("OBRAS_DIARIO_MANAGE", "obras", "diario_manage", "gerenciar"),
        Permission("OBRAS_FISCALIZACAO_VIEW", "obras", "fiscalizacao_view", "visualizar"),
        Permission("OBRAS_FISCALIZACAO_MANAGE", "obras", "fiscalizacao_manage", "gerenciar"),
        Permission("OBRAS_ORDEM_SERVICO_VIEW", "obras", "ordem_servico_view", "visualizar"),
        Permission("OBRAS_ORDEM_SERVICO_MANAGE", "obras", "ordem_servico_manage", "gerenciar"),
        Permission("OBRAS_CONVENIO_VIEW", "obras", "convenio_view", "visualizar"),
        Permission("OBRAS_CONVENIO_MANAGE", "obras", "convenio_manage", "gerenciar"),
        Permission("OBRAS_DOCUMENTO_VIEW", "obras", "documento_view", "visualizar"),
        Permission("OBRAS_DOCUMENTO_MANAGE", "obras", "documento_manage", "gerenciar"),
        Permission("OBRAS_INTEGRACAO_FINANCEIRA_VIEW", "obras", "integracao_financeira_view", "visualizar"),
        Permission("OBRAS_INTEGRACAO_FINANCEIRA_MANAGE", "obras", "integracao_financeira_manage", "gerenciar"),
        Permission("OBRAS_RELATORIO_EXPORT", "obras", "relatorio_export", "exportar"),
        Permission("OBRAS_AUDITORIA_VIEW", "obras", "auditoria_view", "visualizar"),
        Permission("AGRO_DASHBOARD_VIEW", "agro", "dashboard_view", "visualizar"),
        Permission("AGRO_PRODUTOR_VIEW", "agro", "produtor_view", "visualizar"),
        Permission("AGRO_PRODUTOR_MANAGE", "agro", "produtor_manage", "gerenciar"),
        Permission("AGRO_PROPRIEDADE_VIEW", "agro", "propriedade_view", "visualizar"),
        Permission("AGRO_PROPRIEDADE_MANAGE", "agro", "propriedade_manage", "gerenciar"),
        Permission("AGRO_ATIVIDADE_VIEW", "agro", "atividade_view", "visualizar"),
        Permission("AGRO_ATIVIDADE_MANAGE", "agro", "atividade_manage", "gerenciar"),
        Permission("AGRO_ASSISTENCIA_VIEW", "agro", "assistencia_view", "visualizar"),
        Permission("AGRO_ASSISTENCIA_MANAGE", "agro", "assistencia_manage", "gerenciar"),
        Permission("AGRO_PROGRAMA_VIEW", "agro", "programa_view", "visualizar"),
        Permission("AGRO_PROGRAMA_MANAGE", "agro", "programa_manage", "gerenciar"),
        Permission("AGRO_INSUMO_VIEW", "agro", "insumo_view", "visualizar"),
        Permission("AGRO_INSUMO_MANAGE", "agro", "insumo_manage", "gerenciar"),
        Permission("AGRO_PATRULHA_VIEW", "agro", "patrulha_view", "visualizar"),
        Permission("AGRO_PATRULHA_MANAGE", "agro", "patrulha_manage", "gerenciar"),
        Permission("AGRO_FEIRA_VIEW", "agro", "feira_view", "visualizar"),
        Permission("AGRO_FEIRA_MANAGE", "agro", "feira_manage", "gerenciar"),
        Permission("AGRO_AGROINDUSTRIA_VIEW", "agro", "agroindustria_view", "visualizar"),
        Permission("AGRO_AGROINDUSTRIA_MANAGE", "agro", "agroindustria_manage", "gerenciar"),
        Permission("AGRO_SOLICITACAO_VIEW", "agro", "solicitacao_view", "visualizar"),
        Permission("AGRO_SOLICITACAO_MANAGE", "agro", "solicitacao_manage", "gerenciar"),
        Permission("AGRO_RELATORIO_EXPORT", "agro", "relatorio_export", "exportar"),
        Permission("AGRO_AUDITORIA_VIEW", "agro", "auditoria_view", "visualizar"),
        Permission("TRIBUTARIO_DASHBOARD_VIEW", "tributario", "dashboard", "visualizar"),
        Permission("TRIBUTARIO_CONTRIBUINTE_VIEW", "tributario", "contribuinte", "visualizar"),
        Permission("TRIBUTARIO_CONTRIBUINTE_MANAGE", "tributario", "contribuinte", "gerenciar"),
        Permission("TRIBUTARIO_IMOVEL_VIEW", "tributario", "imovel", "visualizar"),
        Permission("TRIBUTARIO_IMOVEL_MANAGE", "tributario", "imovel", "gerenciar"),
        Permission("TRIBUTARIO_MOBILIARIO_VIEW", "tributario", "mobiliario", "visualizar"),
        Permission("TRIBUTARIO_MOBILIARIO_MANAGE", "tributario", "mobiliario", "gerenciar"),
        Permission("TRIBUTARIO_PARAMETRO_VIEW", "tributario", "parametro", "visualizar"),
        Permission("TRIBUTARIO_PARAMETRO_MANAGE", "tributario", "parametro", "gerenciar"),
        Permission("TRIBUTARIO_LANCAMENTO_VIEW", "tributario", "lancamento", "visualizar"),
        Permission("TRIBUTARIO_LANCAMENTO_MANAGE", "tributario", "lancamento", "gerenciar"),
        Permission("TRIBUTARIO_GUIA_VIEW", "tributario", "guia", "visualizar"),
        Permission("TRIBUTARIO_GUIA_MANAGE", "tributario", "guia", "gerenciar"),
        Permission("TRIBUTARIO_ARRECADACAO_VIEW", "tributario", "arrecadacao", "visualizar"),
        Permission("TRIBUTARIO_ARRECADACAO_MANAGE", "tributario", "arrecadacao", "gerenciar"),
        Permission("TRIBUTARIO_DIVIDA_ATIVA_VIEW", "tributario", "divida_ativa", "visualizar"),
        Permission("TRIBUTARIO_DIVIDA_ATIVA_MANAGE", "tributario", "divida_ativa", "gerenciar"),
        Permission("TRIBUTARIO_PARCELAMENTO_VIEW", "tributario", "parcelamento", "visualizar"),
        Permission("TRIBUTARIO_PARCELAMENTO_MANAGE", "tributario", "parcelamento", "gerenciar"),
        Permission("TRIBUTARIO_FISCALIZACAO_VIEW", "tributario", "fiscalizacao", "visualizar"),
        Permission("TRIBUTARIO_FISCALIZACAO_MANAGE", "tributario", "fiscalizacao", "gerenciar"),
        Permission("TRIBUTARIO_CERTIDAO_VIEW", "tributario", "certidao", "visualizar"),
        Permission("TRIBUTARIO_CERTIDAO_MANAGE", "tributario", "certidao", "gerenciar"),
        Permission("TRIBUTARIO_RELATORIO_EXPORT", "tributario", "relatorio", "exportar"),
        Permission("TRIBUTARIO_AUDITORIA_VIEW", "tributario", "auditoria", "visualizar"),
        Permission("tributario.contribuinte.visualizar", "tributario", "contribuinte", "visualizar"),
        Permission("tributario.contribuinte.criar", "tributario", "contribuinte", "criar"),
        Permission("tributario.contribuinte.alterar", "tributario", "contribuinte", "alterar"),
        Permission("tributario.lancamento.visualizar", "tributario", "lancamento", "visualizar"),
        Permission("tributario.lancamento.criar", "tributario", "lancamento", "criar"),
        Permission("tributario.lancamento.cancelar", "tributario", "lancamento", "cancelar"),
        Permission("tributario.dam.emitir", "tributario", "dam", "emitir"),
        Permission("tributario.dam.cancelar", "tributario", "dam", "cancelar"),
        Permission("tributario.divida_ativa.inscrever", "tributario", "divida_ativa", "inscrever"),
        Permission("tributario.fiscalizacao.abrir", "tributario", "fiscalizacao", "abrir"),
        Permission("tributario.relatorio.exportar", "tributario", "relatorio", "exportar"),

        Permission("financeiro.dashboard.visualizar", "financeiro", "dashboard", "visualizar"),
        Permission("financeiro.arrecadacao.visualizar", "financeiro", "arrecadacao", "visualizar"),
        Permission("financeiro.arrecadacao.baixar", "financeiro", "arrecadacao", "baixar"),
        Permission("financeiro.arrecadacao.estornar", "financeiro", "arrecadacao", "estornar"),
        Permission("financeiro.pagamento.registrar", "financeiro", "pagamento", "registrar"),
        Permission("financeiro.relatorio.exportar", "financeiro", "relatorio", "exportar"),
        Permission("financeiro.configurar", "financeiro", "configuracao", "configurar", isAdministrative: true),

        Permission("saneamento.consumidor.visualizar", "saneamento", "consumidor", "visualizar"),
        Permission("saneamento.consumidor.criar", "saneamento", "consumidor", "criar"),
        Permission("saneamento.consumidor.alterar", "saneamento", "consumidor", "alterar"),
        Permission("saneamento.ligacao.criar", "saneamento", "ligacao", "criar"),
        Permission("saneamento.hidrometro.instalar", "saneamento", "hidrometro", "instalar"),
        Permission("saneamento.hidrometro.substituir", "saneamento", "hidrometro", "substituir"),
        Permission("saneamento.leitura.registrar", "saneamento", "leitura", "registrar"),
        Permission("saneamento.fatura.gerar", "saneamento", "fatura", "gerar"),
        Permission("saneamento.fatura.cancelar", "saneamento", "fatura", "cancelar"),
        Permission("saneamento.pagamento.registrar", "saneamento", "pagamento", "registrar"),
        Permission("saneamento.corte.executar", "saneamento", "corte", "executar"),
        Permission("saneamento.religacao.executar", "saneamento", "religacao", "executar"),
        Permission("saneamento.relatorio.exportar", "saneamento", "relatorio", "exportar"),

        Permission("comercial.dashboard.visualizar", "comercial", "dashboard", "visualizar"),
        Permission("comercial.clientes.visualizar", "comercial", "clientes", "visualizar"),
        Permission("comercial.clientes.criar", "comercial", "clientes", "criar"),
        Permission("comercial.leads.visualizar", "comercial", "leads", "visualizar"),
        Permission("comercial.leads.criar", "comercial", "leads", "criar"),
        Permission("comercial.leads.converter", "comercial", "leads", "converter"),
        Permission("comercial.oportunidades.visualizar", "comercial", "oportunidades", "visualizar"),
        Permission("comercial.oportunidades.editar", "comercial", "oportunidades", "editar"),
        Permission("comercial.propostas.visualizar", "comercial", "propostas", "visualizar"),
        Permission("comercial.propostas.criar", "comercial", "propostas", "criar"),
        Permission("comercial.propostas.emitir", "comercial", "propostas", "emitir"),
        Permission("comercial.propostas.aprovar", "comercial", "propostas", "aprovar"),
        Permission("comercial.pedidos.visualizar", "comercial", "pedidos", "visualizar"),
        Permission("comercial.pedidos.criar", "comercial", "pedidos", "criar"),
        Permission("comercial.pedidos.confirmar", "comercial", "pedidos", "confirmar"),

        Permission("os.dashboard.visualizar", "os", "dashboard", "visualizar"),
        Permission("os.ordens.visualizar", "os", "ordens", "visualizar"),
        Permission("os.ordens.criar", "os", "ordens", "criar"),
        Permission("os.ordens.agendar", "os", "ordens", "agendar"),
        Permission("os.ordens.atribuir", "os", "ordens", "atribuir"),
        Permission("os.ordens.iniciar", "os", "ordens", "iniciar"),
        Permission("os.ordens.pausar", "os", "ordens", "pausar"),
        Permission("os.ordens.concluir", "os", "ordens", "concluir"),
        Permission("os.ordens.cancelar", "os", "ordens", "cancelar"),
        Permission("os.checklist.visualizar", "os", "checklist", "visualizar"),
        Permission("os.checklist.responder", "os", "checklist", "responder"),
        Permission("os.apontamentos.visualizar", "os", "apontamentos", "visualizar"),
        Permission("os.apontamentos.criar", "os", "apontamentos", "criar"),
        Permission("os.pecas.visualizar", "os", "pecas", "visualizar"),
        Permission("os.pecas.consumir", "os", "pecas", "consumir"),
        Permission("os.pecas.devolver", "os", "pecas", "devolver"),

        Purchasing("dashboard", "visualizar"),
        Purchasing("fornecedores", "visualizar", "com.meuerp.compras.fornecedor.visualizar"),
        Purchasing("fornecedores", "criar", "com.meuerp.compras.fornecedor.criar"),
        Purchasing("fornecedores", "editar", "com.meuerp.compras.fornecedor.editar"),
        Purchasing("fornecedores", "inativar", "com.meuerp.compras.fornecedor.inativar"),
        Purchasing("fornecedores", "homologar", "com.meuerp.compras.fornecedor.homologar"),
        Purchasing("fornecedores", "bloquear"),
        Purchasing("requisicoes", "visualizar"),
        Purchasing("requisicoes", "criar"),
        Purchasing("requisicoes", "editar"),
        Purchasing("requisicoes", "enviar"),
        Purchasing("requisicoes", "aprovar"),
        Purchasing("requisicoes", "rejeitar"),
        Purchasing("requisicoes", "cancelar"),
        Purchasing("aprovacoes", "visualizar"),
        Purchasing("aprovacoes", "aprovar"),
        Purchasing("cotacoes", "visualizar"),
        Purchasing("cotacoes", "criar"),
        Purchasing("cotacoes", "enviar"),
        Purchasing("cotacoes", "responder"),
        Purchasing("cotacoes", "julgar"),
        Purchasing("cotacoes", "cancelar"),
        Purchasing("pedidos", "visualizar"),
        Purchasing("pedidos", "gerar"),
        Purchasing("pedidos", "emitir"),
        Purchasing("pedidos", "cancelar"),
        Purchasing("pedidos", "receber"),
        Purchasing("recebimentos", "visualizar"),
        Purchasing("recebimentos", "registrar"),
        Purchasing("recebimentos", "aceitar"),
        Purchasing("recebimentos", "rejeitar"),
        Purchasing("recebimentos", "estornar"),
        Purchasing("faturas", "visualizar"),
        Purchasing("devolucoes", "visualizar"),
        Purchasing("avaliacoes", "gerenciar"),
        Purchasing("relatorios", "visualizar"),
        Purchasing("configuracao", "gerenciar", isAdministrative: true),
        Permission("WORKFLOW_CONSULTA", "workflow", "workflow", "consultar"),
        Permission("WORKFLOW_GERENCIAR", "workflow", "workflow", "gerenciar", isAdministrative: true),
        Permission("FORMULARIO_CONSULTA", "formularios", "formulario", "consultar"),
        Permission("FORMULARIO_GERENCIAR", "formularios", "formulario", "gerenciar", isAdministrative: true),
        Permission("PORTAL_CONFIGURAR", "portal", "configuracao", "gerenciar", isAdministrative: true),
        Permission("PORTAL_CONSULTAR_SOLICITACOES", "portal", "solicitacoes", "consultar"),
        Permission("SLA_CONSULTA", "sla", "regras", "consultar"),
        Permission("SLA_GERENCIAR", "sla", "regras", "gerenciar", isAdministrative: true),
        Permission("APROVACAO_CONSULTA", "aprovacoes", "aprovacao", "consultar"),
        Permission("APROVACAO_DECIDIR", "aprovacoes", "aprovacao", "decidir"),
        Permission("TEMPLATE_CONSULTA", "templates", "template", "consultar"),
        Permission("TEMPLATE_GERENCIAR", "templates", "template", "gerenciar", isAdministrative: true),
        Permission("ONBOARDING_CONSULTA", "onboarding", "checklist", "consultar"),
        Permission("SHOWCASE_ACESSAR", "showcase", "showcase", "acessar", isAdministrative: true),
        Permission("RELATORIO_EXECUTIVO", "relatorios", "executivo", "consultar", isAdministrative: true),
        Permission("arrei.visualizar", "arrei", "solicitacoes", "visualizar"),
        Permission("arrei.criar", "arrei", "solicitacoes", "criar"),
        Permission("arrei.editar", "arrei", "solicitacoes", "editar"),
        Permission("arrei.analisar", "arrei", "solicitacoes", "analisar"),
        Permission("arrei.atribuir", "arrei", "solicitacoes", "atribuir"),
        Permission("arrei.deferir", "arrei", "solicitacoes", "deferir"),
        Permission("arrei.indeferir", "arrei", "solicitacoes", "indeferir"),
        Permission("arrei.configurar", "arrei", "configuracao", "gerenciar", isAdministrative: true),
        Permission("arrei.exportar", "arrei", "relatorios", "exportar"),
        Permission("arrei.portal", "arrei", "portal", "acessar")
    ];

    public static IEnumerable<(string Policy, PermissionDefinition Permission)> Policies =>
        All.SelectMany(permission => permission.Aliases.Prepend(permission.Code)
            .Select(policy => (policy, permission)));

    public static bool UserHasPermission(ClaimsPrincipal user, PermissionDefinition permission)
    {
        if (user.IsInRole("ADMIN_GERAL") || user.IsInRole("ADMIN_TENANT"))
            return true;

        var accepted = permission.Aliases.Prepend(permission.Code).ToHashSet(StringComparer.OrdinalIgnoreCase);
        return user.Claims
            .Where(claim => claim.Type is "permission" or "permissions" or "scope")
            .SelectMany(claim => claim.Value.Split([' ', ',', ';'], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
            .Any(accepted.Contains);
    }

    private static PermissionDefinition Purchasing(string resource, string action, string? alias = null, bool isAdministrative = false) =>
        Permission($"{PurchasingModule}.{resource}.{action}", PurchasingModule, resource, action, alias, isAdministrative);

    private static PermissionDefinition Permission(string code, string module, string resource, string action, string? alias = null, bool isAdministrative = false) =>
        new(code, module, resource, action, $"Permite {action} {resource}.", module, isAdministrative,
            string.IsNullOrWhiteSpace(alias) ? [] : [alias]);
}
