namespace Sigov.Domain.Agro.Transparencia;

public enum AgroDatasetTipo { PRODUCAO_AGREGADA, AREA_PRODUTIVA_LOCALIDADE, ESTRADAS_SITUACAO, PONTOS_CRITICOS_AGREGADOS, FEIRAS_ATIVAS, AGROINDUSTRIAS_ATIVAS, COMPRAS_AF_AGREGADAS, GEO }
public enum AgroDatasetStatus { RASCUNHO, PUBLICADO, SUSPENSO, ERRO }
