using Microsoft.Extensions.DependencyInjection;
using Sigov.Application.Abstractions;
using Sigov.Infrastructure.Common;
using Sigov.Infrastructure.Persistence.Dapper;
using Sigov.Infrastructure.Persistence.Migrations;
using Sigov.Infrastructure.Persistence.Repositories;
using Sigov.Infrastructure.Persistence.UnitOfWork;
using Sigov.Infrastructure.Security;
using Sigov.Application.Saas;
using Sigov.Infrastructure.Saas;
using Sigov.Application.Storage;
using Sigov.Infrastructure.Storage;
using Sigov.Application.Processos;
using Sigov.Infrastructure.Processos;
using Sigov.Application.Financeiro;
using Sigov.Application.Core;
using Sigov.Infrastructure.Financeiro;
using Sigov.Application.Rh;
using Sigov.Infrastructure.Rh;
using Sigov.Application.Educacao;
using Sigov.Infrastructure.Educacao;
using Sigov.Application.Saude;
using Sigov.Infrastructure.Saude;
using Sigov.Application.Saneamento;
using Sigov.Infrastructure.Saneamento;
using Sigov.Application.Social;
using Sigov.Infrastructure.Social;
using Sigov.Infrastructure.Integracoes;
using Sigov.Application.Integracoes;
using Sigov.Application.Health;
using Sigov.Infrastructure.Health;
using Sigov.Application.Lgpd;
using Sigov.Infrastructure.Lgpd;
using Sigov.Application.Release;
using Sigov.Application.Homologacao;
using Sigov.Infrastructure.Homologacao;
using Sigov.Infrastructure.Release;

namespace Sigov.Infrastructure;

public static class DependencyInjection
{
    public static IServiceCollection AddInfrastructure(this IServiceCollection services)
    {
        services.AddSingleton<NpgsqlConnectionFactory>();
        services.AddScoped<DapperContext>();
        services.AddScoped<IUnitOfWork, UnitOfWork>();
        services.AddScoped<MigrationRunner>();
        services.AddSingleton<IVersionInfoProvider, VersionInfoProvider>();
        services.AddSingleton<IReleaseInfoProvider, ReleaseInfoProvider>();
        services.AddSingleton<ReleaseMetadataReader>();
        services.AddSingleton<BuildInfoProvider>();
        services.AddSingleton<IGoLiveChecklistService, GoLiveChecklistService>();
        services.AddSingleton<ISmokeTestPlanService, SmokeTestPlanService>();
        services.AddSingleton<IHomologacaoValidator, HomologacaoValidator>();
        services.AddScoped<IHomologacaoSeedService, HomologacaoSeedService>();
        services.AddScoped<HomologacaoRepository>();
        services.AddScoped<IHealthCheckService, HealthCheckService>();
        services.AddScoped<IHealthCheck, DatabaseHealthCheck>();
        services.AddScoped<IHealthCheck, OutboxHealthCheck>();
        services.AddScoped<IHealthCheck, StorageHealthCheck>();

        services.AddScoped<IApiCredentialRepository, ApiCredentialRepository>();
        services.AddScoped<IIntegracaoSistemaRepository, IntegracaoSistemaRepository>();
        services.AddScoped<IWebhookRepository, WebhookRepository>();
        services.AddScoped<IOutboxRepository, OutboxRepository>();
        services.AddScoped<IIntegracaoLogRepository, IntegracaoLogRepository>();
        services.AddScoped<IRemessaOficialRepository, RemessaOficialRepository>();
        services.AddScoped<ICertificadoDigitalRepository, CertificadoDigitalRepository>();
        services.AddScoped<IIntegracaoDashboardRepository, IntegracaoDashboardRepository>();
        services.AddScoped<IIntegracaoExportacaoRepository, IntegracaoExportacaoRepository>();
        services.AddScoped<IApiKeyHasher, ApiKeyHasher>();
        services.AddScoped<IWebhookSignatureService, WebhookSignatureService>();
        services.AddScoped<IApiCredentialService, ApiCredentialService>();
        services.AddScoped<IIntegracaoSistemaService, IntegracaoSistemaService>();
        services.AddScoped<IWebhookService, WebhookService>();
        services.AddScoped<IIdempotencyService, IdempotencyService>();
        services.AddScoped<IOutboxService, OutboxService>();
        services.AddScoped<IIntegracaoLogService, IntegracaoLogService>();
        services.AddScoped<IRemessaOficialService, RemessaOficialService>();
        services.AddScoped<ICertificadoDigitalService, CertificadoDigitalService>();
        services.AddScoped<IGovBrAdapter, GovBrEstruturalService>();
        services.AddScoped<IAssinadorDigitalService, AssinadorDigitalEstruturalService>();
        services.AddScoped<IIntegracaoDashboardService, IntegracaoDashboardService>();
        services.AddScoped<IIntegracaoExportacaoService, IntegracaoExportacaoService>();
        services.AddScoped<PessoaRepository>();
        services.AddScoped<IPessoaCadastroRepository, PessoaRepository>();
        services.AddScoped<UsuarioRepository>();
        services.AddScoped<AuditRepository>();
        services.AddScoped<IAuditService, ProcessosAuditService>();
        services.AddScoped<ILgpdMaskingService, LgpdMaskingService>();
        services.AddScoped<ILgpdClassificationService, LgpdClassificationService>();
        services.AddScoped<ILgpdMaskingPolicy, LgpdMaskingPolicy>();
        services.AddScoped<ILgpdAccessLogger, LgpdAccessLogger>();
        services.AddScoped<IDateTimeProvider, DateTimeProvider>();
        services.AddScoped<ICorrelationIdProvider, CorrelationIdProvider>();
        services.AddScoped<ICurrentUser, CurrentUser>();
        services.AddScoped<ICurrentTenant, CurrentTenant>();
        services.AddScoped<ICurrentExercicio, CurrentExercicio>();
        services.AddScoped<IPasswordHashService, PasswordHashService>();
        services.AddScoped<IPermissionService, PermissionService>();
        services.AddScoped<ITenantContext, TenantContext>();
        services.AddScoped<ITenantResolver, TenantResolver>();
        services.AddScoped<ITenantProvisioningService, TenantProvisioningService>();
        services.AddScoped<IFeatureFlagService, FeatureFlagService>();
        services.AddScoped<IModuloLicenciamentoService, ModuloLicenciamentoService>();
        services.AddScoped<ITenantUsageMeter, TenantUsageMeter>();
        services.AddScoped<ITenantConfigurationProvider, TenantConfigurationProvider>();
        services.AddScoped<Func<long, CancellationToken, Task<string?>>>(provider => async (tenantId, cancellationToken) =>
        {
            var context = provider.GetRequiredService<DapperContext>();
            using var connection = context.CreateConnection();
            return await Dapper.SqlMapper.ExecuteScalarAsync<string?>(connection, new Dapper.CommandDefinition("select status from sigov.tenant where id = @TenantId and ativo = true and is_deleted = false;", new { TenantId = tenantId }, cancellationToken: cancellationToken)).ConfigureAwait(false);
        });
        services.AddScoped<ITenantAccessGuard, TenantAccessGuard>();
        services.AddScoped<IFileHashService, FileHashService>();
        services.AddScoped<IStorageKeyGenerator, StorageKeyGenerator>();
        services.AddScoped<IFileTypeValidator, FileTypeValidator>();
        services.AddScoped<IAntivirusScanner, NoOpAntivirusScanner>();
        services.AddScoped<IFileStorageService, LocalFileStorageService>();
        services.AddScoped<ITipoProcessoRepository, TipoProcessoRepository>();
        services.AddScoped<IProcessoDigitalRepository, ProcessoDigitalRepository>();
        services.AddScoped<IProcessoMovimentacaoRepository, ProcessoMovimentacaoRepository>();
        services.AddScoped<IProcessoParecerRepository, ProcessoParecerRepository>();
        services.AddScoped<IProtocoloAtendimentoRepository, ProtocoloAtendimentoRepository>();
        services.AddScoped<IOuvidoriaRepository, OuvidoriaRepository>();
        services.AddScoped<IDiarioOficialRepository, DiarioOficialRepository>();
        services.AddScoped<IProcessoSequencialService, ProcessoSequencialRepository>();
        services.AddScoped<ITipoProcessoService, TipoProcessoService>();
        services.AddScoped<IProcessoDigitalService, ProcessoDigitalService>();
        services.AddScoped<IProtocoloAtendimentoService, ProtocoloAtendimentoService>();
        services.AddScoped<IOuvidoriaService, OuvidoriaService>();
        services.AddScoped<IDiarioOficialService, DiarioOficialService>();
        services.AddScoped<IPlanoContasRepository, PlanoContasRepository>();
        services.AddScoped<IFonteRecursoRepository, FonteRecursoRepository>();
        services.AddScoped<IProgramaRepository, ProgramaRepository>();
        services.AddScoped<IAcaoRepository, AcaoRepository>();
        services.AddScoped<INaturezaReceitaRepository, NaturezaReceitaRepository>();
        services.AddScoped<INaturezaDespesaRepository, NaturezaDespesaRepository>();
        services.AddScoped<IOrcamentoRepository, OrcamentoRepository>();
        services.AddScoped<IEmpenhoRepository, EmpenhoRepository>();
        services.AddScoped<ILiquidacaoRepository, LiquidacaoRepository>();
        services.AddScoped<IPagamentoRepository, PagamentoRepository>();
        services.AddScoped<IReceitaRepository, ReceitaRepository>();
        services.AddScoped<IFinanceiroSequencialService, FinanceiroSequencialRepository>();
        services.AddScoped<IFinanceiroDashboardRepository, FinanceiroDashboardRepository>();
        services.AddScoped<IPlanoContasService, PlanoContasService>();
        services.AddScoped<IFonteRecursoService, FonteRecursoService>();
        services.AddScoped<IProgramaService, ProgramaService>();
        services.AddScoped<IAcaoService, AcaoService>();
        services.AddScoped<INaturezaReceitaService, NaturezaReceitaService>();
        services.AddScoped<INaturezaDespesaService, NaturezaDespesaService>();
        services.AddScoped<IOrcamentoService, OrcamentoService>();
        services.AddScoped<IEmpenhoService, EmpenhoService>();
        services.AddScoped<ILiquidacaoService, LiquidacaoService>();
        services.AddScoped<IPagamentoService, PagamentoService>();
        services.AddScoped<IReceitaService, ReceitaService>();
        services.AddScoped<IFinanceiroDashboardService, FinanceiroDashboardService>();
        services.AddScoped<IFinanceiroExportacaoService, FinanceiroExportacaoService>();
        services.AddScoped<IRhRepository, RhRepository>();
        services.AddScoped<IRhService, RhService>();
        services.AddScoped<IRhTypedService, RhTypedService>();
        services.AddScoped<IPessoaCadastroService, PessoaCadastroService>();
        services.AddScoped<EducacaoRepository>();
        services.AddScoped<IEducacaoRepository, EducacaoRepository>();
        services.AddScoped<IEscolaRepository, EducacaoRepository>();
        services.AddScoped<IAnoLetivoRepository, EducacaoRepository>();
        services.AddScoped<ICursoRepository, EducacaoRepository>();
        services.AddScoped<ITurmaRepository, EducacaoRepository>();
        services.AddScoped<IAlunoRepository, EducacaoRepository>();
        services.AddScoped<IMatriculaRepository, EducacaoRepository>();
        services.AddScoped<IProfessorRepository, EducacaoRepository>();
        services.AddScoped<IFrequenciaRepository, EducacaoRepository>();
        services.AddScoped<IAvaliacaoRepository, EducacaoRepository>();
        services.AddScoped<IPreMatriculaRepository, EducacaoRepository>();
        services.AddScoped<IEducacensoRepository, EducacaoRepository>();
        services.AddScoped<IEducacaoDashboardRepository, EducacaoRepository>();
        services.AddScoped<IEducacaoExportacaoRepository, EducacaoRepository>();
        services.AddScoped<IEducacaoSequencialService, EducacaoRepository>();
        services.AddScoped<EducacaoService>();
        services.AddScoped<IEscolaService, EducacaoService>();
        services.AddScoped<IAnoLetivoService, EducacaoService>();
        services.AddScoped<ICursoService, EducacaoService>();
        services.AddScoped<ITurmaService, EducacaoService>();
        services.AddScoped<IAlunoService, EducacaoService>();
        services.AddScoped<IMatriculaService, EducacaoService>();
        services.AddScoped<IProfessorService, EducacaoService>();
        services.AddScoped<IFrequenciaService, EducacaoService>();
        services.AddScoped<IAvaliacaoService, EducacaoService>();
        services.AddScoped<IPreMatriculaService, EducacaoService>();
        services.AddScoped<IEducacensoService, EducacaoService>();
        services.AddScoped<IEducacaoDashboardService, EducacaoService>();
        services.AddScoped<IEducacaoExportacaoService, EducacaoService>();
        services.AddScoped<SaudeRepository>();
        services.AddScoped<ISaudeCrudRepository, SaudeRepository>();
        services.AddScoped<IUnidadeSaudeRepository, SaudeRepository>();
        services.AddScoped<IProfissionalSaudeRepository, SaudeRepository>();
        services.AddScoped<IPacienteRepository, SaudeRepository>();
        services.AddScoped<IProntuarioRepository, SaudeRepository>();
        services.AddScoped<IAtendimentoSaudeRepository, SaudeRepository>();
        services.AddScoped<IAgendaSaudeRepository, SaudeRepository>();
        services.AddScoped<IFarmaciaRepository, SaudeRepository>();
        services.AddScoped<IVacinacaoRepository, SaudeRepository>();
        services.AddScoped<ILaboratorioRepository, SaudeRepository>();
        services.AddScoped<IRegulacaoRepository, SaudeRepository>();
        services.AddScoped<IAcsRepository, SaudeRepository>();
        services.AddScoped<IAcsSyncRepository, SaudeRepository>();
        services.AddScoped<ISaudeDashboardRepository, SaudeRepository>();
        services.AddScoped<ISaudeExportacaoRepository, SaudeRepository>();
        services.AddScoped<ISaudeSequencialService, SaudeRepository>();
        services.AddScoped<SaudeService>();
        services.AddScoped<IUnidadeSaudeService, SaudeService>();
        services.AddScoped<IProfissionalSaudeService, SaudeService>();
        services.AddScoped<IPacienteService, SaudeService>();
        services.AddScoped<IProntuarioService, SaudeService>();
        services.AddScoped<IAtendimentoSaudeService, SaudeService>();
        services.AddScoped<IAgendaSaudeService, SaudeService>();
        services.AddScoped<IFarmaciaService, SaudeService>();
        services.AddScoped<IVacinacaoService, SaudeService>();
        services.AddScoped<ILaboratorioService, SaudeService>();
        services.AddScoped<IRegulacaoService, SaudeService>();
        services.AddScoped<IAcsService, SaudeService>();
        services.AddScoped<IAcsSyncService, SaudeService>();
        services.AddScoped<ISaudeDashboardService, SaudeService>();
        services.AddScoped<ISaudeExportacaoService, SaudeService>();

        services.AddScoped<SaneamentoRepository>();
        services.AddScoped<ISaneamentoConsumidorRepository, SaneamentoRepository>();
        services.AddScoped<ILigacaoSaneamentoRepository, SaneamentoRepository>();
        services.AddScoped<IUnidadeConsumidoraRepository, SaneamentoRepository>();
        services.AddScoped<IHidrometroRepository, SaneamentoRepository>();
        services.AddScoped<ILeituraConsumoRepository, SaneamentoRepository>();
        services.AddScoped<IFaturaSaneamentoRepository, SaneamentoRepository>();
        services.AddScoped<IArrecadacaoSaneamentoRepository, SaneamentoRepository>();
        services.AddScoped<IParcelamentoSaneamentoRepository, SaneamentoRepository>();
        services.AddScoped<IOrdemServicoSaneamentoRepository, SaneamentoRepository>();
        services.AddScoped<IEquipeCampoSaneamentoRepository, SaneamentoRepository>();
        services.AddScoped<ILaboratorioSaneamentoRepository, SaneamentoRepository>();
        services.AddScoped<IRedeSaneamentoRepository, SaneamentoRepository>();
        services.AddScoped<ISaneamentoDashboardRepository, SaneamentoRepository>();
        services.AddScoped<ISaneamentoExportacaoRepository, SaneamentoRepository>();
        services.AddScoped<ISaneamentoSequencialService, SaneamentoRepository>();
        services.AddScoped<SaneamentoService>();
        services.AddScoped<ISaneamentoConsumidorService, SaneamentoService>();
        services.AddScoped<ILigacaoSaneamentoService, SaneamentoService>();
        services.AddScoped<IUnidadeConsumidoraService, SaneamentoService>();
        services.AddScoped<IHidrometroService, SaneamentoService>();
        services.AddScoped<ILeituraConsumoService, SaneamentoService>();
        services.AddScoped<IFaturaSaneamentoService, SaneamentoService>();
        services.AddScoped<IArrecadacaoSaneamentoService, SaneamentoService>();
        services.AddScoped<IParcelamentoSaneamentoService, SaneamentoService>();
        services.AddScoped<IOrdemServicoSaneamentoService, SaneamentoService>();
        services.AddScoped<IEquipeCampoSaneamentoService, SaneamentoService>();
        services.AddScoped<ILaboratorioSaneamentoService, SaneamentoService>();
        services.AddScoped<IRedeSaneamentoService, SaneamentoService>();
        services.AddScoped<ISaneamentoDashboardService, SaneamentoService>();
        services.AddScoped<ISaneamentoExportacaoService, SaneamentoService>();
        services.AddScoped<SocialRepository>();
        services.AddScoped<ISocialUnidadeRepository, SocialRepository>();
        services.AddScoped<ISocialFamiliaRepository, SocialRepository>();
        services.AddScoped<ISocialPessoaRepository, SocialRepository>();
        services.AddScoped<ISocialCadastroRepository, SocialRepository>();
        services.AddScoped<ISocialProgramaRepository, SocialRepository>();
        services.AddScoped<ISocialBeneficioRepository, SocialRepository>();
        services.AddScoped<ISocialAtendimentoRepository, SocialRepository>();
        services.AddScoped<ISocialVisitaRepository, SocialRepository>();
        services.AddScoped<ISocialParecerRepository, SocialRepository>();
        services.AddScoped<ISocialAcompanhamentoRepository, SocialRepository>();
        services.AddScoped<ISocialVigilanciaRepository, SocialRepository>();
        services.AddScoped<ISocialDashboardRepository, SocialRepository>();
        services.AddScoped<ISocialExportacaoRepository, SocialRepository>();
        services.AddScoped<ISocialSequencialService, SocialRepository>();
        services.AddScoped<SocialService>();
        services.AddScoped<ISocialUnidadeService, SocialService>();
        services.AddScoped<ISocialFamiliaService, SocialService>();
        services.AddScoped<ISocialPessoaService, SocialService>();
        services.AddScoped<ISocialCadastroService, SocialService>();
        services.AddScoped<ISocialProgramaService, SocialService>();
        services.AddScoped<ISocialBeneficioService, SocialService>();
        services.AddScoped<ISocialAtendimentoService, SocialService>();
        services.AddScoped<ISocialVisitaService, SocialService>();
        services.AddScoped<ISocialParecerService, SocialService>();
        services.AddScoped<ISocialAcompanhamentoService, SocialService>();
        services.AddScoped<ISocialVigilanciaService, SocialService>();
        services.AddScoped<ISocialDashboardService, SocialService>();
        services.AddScoped<ISocialExportacaoService, SocialService>();
        return services;
    }
}
