using Sigov.Application.Ia;
using Sigov.Infrastructure.Ia;
using Microsoft.Extensions.DependencyInjection;
using Sigov.Application.Abstractions;
using Sigov.Application.Common;
using Sigov.Application.Security;
using Sigov.Infrastructure.Common;
using Sigov.Infrastructure.Persistence.Dapper;
using Sigov.Infrastructure.Persistence.Migrations;
using Sigov.Infrastructure.Persistence.Repositories;
using Sigov.Infrastructure.Persistence.UnitOfWork;
using Sigov.Infrastructure.Security;
using Sigov.Application.Saas;
using Sigov.Application.Saas.B2B;
using Sigov.Infrastructure.Saas;
using Sigov.Infrastructure.Saas.B2B;
using Sigov.Application.Storage;
using Sigov.Infrastructure.Storage;
using Sigov.Application.Processos;
using Sigov.Infrastructure.Processos;
using Sigov.Application.Financeiro;
using Sigov.Application.Core;
using Sigov.Application.Frotas;
using Sigov.Application.Obras;
using Sigov.Infrastructure.Frotas;
using Sigov.Infrastructure.Financeiro;
using Sigov.Application.FinanceiroEmpresarial;
using Sigov.Infrastructure.FinanceiroEmpresarial;
using Sigov.Application.Rh;
using Sigov.Infrastructure.Rh;
using Sigov.Application.Educacao;
using Sigov.Infrastructure.Educacao;
using Sigov.Application.Educacao.Bloco3;
using Sigov.Infrastructure.Educacao.Bloco3;
using Sigov.Application.Educacao.Avancada;
using Sigov.Infrastructure.Educacao.Avancada;
using Sigov.Application.Relatorios;
using Sigov.Infrastructure.Relatorios;
using Sigov.Application.Parameters;
using Sigov.Infrastructure.Parameters;
using Sigov.Application.Workflows;
using Sigov.Infrastructure.Workflows;
using Sigov.Application.Saude;
using Sigov.Infrastructure.Saude;
using Sigov.Application.Saude.Avancada;
using Sigov.Infrastructure.Saude.Avancada;
using Sigov.Application.Saneamento;
using Sigov.Infrastructure.Saneamento;
using Sigov.Application.Saneamento.Avancado;
using Sigov.Infrastructure.Saneamento.Avancado;
using Sigov.Application.Social;
using Sigov.Application.Agro.Catalogo;
using Sigov.Application.Agro.Dashboard;
using Sigov.Application.Agro.Geo;
using Sigov.Application.Agro.Permissions;
using Sigov.Application.Agro.Produtores;
using Sigov.Application.Agro.Propriedades;
using Sigov.Application.Agro.Producao;
using Sigov.Application.Agro.Programas;
using Sigov.Application.Agro.PatrulhaMecanizada;
using Sigov.Application.Agro.ComprasAgriculturaFamiliar;
using Sigov.Application.Agro.Agroindustrias;
using Sigov.Application.Agro.FeirasMercados;
using Sigov.Application.Agro.InfraestruturaRural;
using Sigov.Application.Agro.Comercial;
using Sigov.Application.Agro.Dicionario;
using Sigov.Application.Agro.Transparencia;
using Sigov.Application.Agro.Bi;
using Sigov.Application.Agro.Relatorios;
using Sigov.Infrastructure.Agro;
using Sigov.Infrastructure.Agro.Repositories;
using Sigov.Infrastructure.Social;
using Sigov.Infrastructure.Integracoes;
using Sigov.Application.Integracoes;
using Sigov.Application.Health;
using Sigov.Application.Auditoria;
using Sigov.Infrastructure.Health;
using Sigov.Application.Lgpd;
using Sigov.Infrastructure.Lgpd;
using Sigov.Application.Release;
using Sigov.Application.Homologacao;
using Sigov.Application.Governanca;
using Sigov.Infrastructure.Governanca;
using Sigov.Infrastructure.Homologacao;
using Sigov.Infrastructure.Release;
using Sigov.Infrastructure.Ui;
using Sigov.Infrastructure.Onboarding;
using Sigov.Infrastructure.Saas.Perfis;
using Sigov.Infrastructure.Saas.WhiteLabel;
using Sigov.Infrastructure.Saas.Comercial;
using Sigov.Application.Saas.Perfis;
using Sigov.Application.Saas.WhiteLabel;
using Sigov.Application.Saas.Comercial;
using Sigov.Application.Comercio;
using Sigov.Application.Commercial;
using Sigov.Application.Enterprise;
using Sigov.Application.Operational;
using Sigov.Infrastructure.Comercio;
using Sigov.Infrastructure.Operational;
using Sigov.Infrastructure.Enterprise;
using Sigov.Infrastructure.Commercial;
using Sigov.Application.OrdemServico;
using Sigov.Infrastructure.OrdemServico;
using Sigov.Application.ComprasEmpresariais;
using Sigov.Infrastructure.ComprasEmpresariais;
using Sigov.Application.ExecutiveOperations;
using Sigov.Application.Bloco8;
using Sigov.Infrastructure.Bloco8;
using Sigov.Application.Empresarial;
using Sigov.Infrastructure.Empresarial;
using Sigov.Infrastructure.ExecutiveOperations;

using Sigov.Application.Industria;
using Sigov.Infrastructure.Industria;
using Sigov.Application.Ui;
using Sigov.Application.Bloco6;
using Sigov.Infrastructure.Bloco6;
using Sigov.Application.Tributario.TributarioAvancado;
using Sigov.Infrastructure.Tributario;
namespace Sigov.Infrastructure;

public static class DependencyInjection
{
    public static IServiceCollection AddInfrastructure(this IServiceCollection services)
    {
        services.AddScoped<TributarioAvancadoRepository>();
        services.AddScoped<ITributarioCarnesBoletosRepository>(p => p.GetRequiredService<TributarioAvancadoRepository>());
        services.AddScoped<IPortalContribuinteRepository>(p => p.GetRequiredService<TributarioAvancadoRepository>());
        services.AddScoped<ITributarioFiscalizacaoRepository>(p => p.GetRequiredService<TributarioAvancadoRepository>());
        services.AddScoped<ITributarioNfseRepository>(p => p.GetRequiredService<TributarioAvancadoRepository>());
        services.AddScoped<ITributarioCarnesBoletosService>(p => p.GetRequiredService<TributarioAvancadoRepository>());
        services.AddScoped<ITributarioCarneArquivoService>(p => p.GetRequiredService<TributarioAvancadoRepository>());
        services.AddScoped<IPortalContribuinteService>(p => p.GetRequiredService<TributarioAvancadoRepository>());
        services.AddScoped<ITributarioFiscalizacaoService>(p => p.GetRequiredService<TributarioAvancadoRepository>());
        services.AddScoped<ITributarioNfseService>(p => p.GetRequiredService<TributarioAvancadoRepository>());
        services.AddSingleton<NpgsqlConnectionFactory>();
        services.AddScoped<ITransversalGovernancaService, TransversalGovernancaService>();
        services.AddScoped<IComprasRepository, ComprasRepository>();
        services.AddScoped<IContratosRepository, ContratosRepository>();
        services.AddScoped<IAlmoxarifadoRepository, AlmoxarifadoRepository>();
        services.AddScoped<IPatrimonioRepository, PatrimonioRepository>();
        services.AddScoped<ComprasService>();
        services.AddScoped<IComprasService>(p => p.GetRequiredService<ComprasService>());
        services.AddScoped<IComprasSolicitacaoService>(p => p.GetRequiredService<ComprasService>());
        services.AddScoped<IComprasOrdemCompraService>(p => p.GetRequiredService<ComprasService>());
        services.AddScoped<IComprasDashboardService, ComprasDashboardService>();
        services.AddSingleton<IFornecedorService, FornecedorService>();
        services.AddScoped<ContratosService>();
        services.AddScoped<IContratosService>(p => p.GetRequiredService<ContratosService>());
        services.AddScoped<IContratoMedicaoService>(p => p.GetRequiredService<ContratosService>());
        services.AddScoped<IContratosDashboardService, ContratosDashboardService>();
        services.AddScoped<AlmoxarifadoService>();
        services.AddScoped<IAlmoxarifadoService>(p => p.GetRequiredService<AlmoxarifadoService>());
        services.AddScoped<IAlmoxarifadoEstoqueService>(p => p.GetRequiredService<AlmoxarifadoService>());
        services.AddScoped<IAlmoxarifadoMovimentoService>(p => p.GetRequiredService<AlmoxarifadoService>());
        services.AddScoped<PatrimonioService>();
        services.AddScoped<IPatrimonioService>(p => p.GetRequiredService<PatrimonioService>());
        services.AddScoped<IPatrimonioMovimentoService>(p => p.GetRequiredService<PatrimonioService>());
        services.AddScoped<DapperContext>();
        services.AddScoped<IWhiteLabelB2BLaunchService, WhiteLabelB2BLaunchService>();
        services.AddScoped<IUnitOfWork, UnitOfWork>();
        services.AddScoped<MigrationRunner>();
        services.AddScoped<IComercioEstoqueService, ComercioEstoqueService>();
        services.AddSingleton<ICommercialPersonalDataProtector, CommercialPersonalDataProtector>();
        services.AddScoped<ICommercialRepository, CommercialRepository>();
        services.AddScoped<ICommercialApplicationService, CommercialApplicationService>();
        services.AddScoped<IOrdemServicoRepository, OrdemServicoRepository>();
        services.AddScoped<IOrdemServicoApplicationService, OrdemServicoApplicationService>();
        services.AddScoped<IFornecedorRepository, FornecedorRepository>();
        services.AddScoped<IRequisicaoCompraRepository, RequisicaoCompraRepository>();
        services.AddScoped<IComprasDashboardRepository, ComprasDashboardRepository>();
        services.AddScoped<IFornecedorApplicationService, FornecedorApplicationService>();
        services.AddScoped<IRequisicaoCompraApplicationService, RequisicaoCompraApplicationService>();
        services.AddScoped<IComprasDashboardApplicationService, ComprasDashboardApplicationService>();
        services.AddScoped<IExecutiveOperationsRepository, ExecutiveOperationsRepository>();
        services.AddScoped<IGovernancaOperacionalService, GovernancaOperacionalService>();
        services.AddSingleton<IDocumentTemplateRenderer, SafeDocumentTemplateRenderer>();
        services.AddScoped<ITarefaRepository, TarefaRepository>();
        services.AddScoped<ITarefaHistoricoRepository, TarefaHistoricoRepository>();
        services.AddScoped<ITarefaService, Sigov.Application.Operational.TarefaService>();
        services.AddScoped<IAgendaRepository, AgendaRepository>();
        services.AddScoped<IAgendaService, Sigov.Application.Operational.AgendaService>();
        services.AddScoped<IPrazoOperacionalRepository, PrazoOperacionalRepository>();
        services.AddScoped<IPrazoOperacionalService, Sigov.Application.Operational.PrazoOperacionalService>();
        services.AddScoped<INotificacaoRepository, NotificacaoRepository>();
        services.AddScoped<INotificacaoService, Sigov.Application.Operational.NotificacaoService>();
        services.AddScoped<INotificacaoPreferenceService, NotificacaoPreferenceRepository>();
        services.AddScoped<IKanbanRepository, KanbanRepository>();
        services.AddScoped<IKanbanService, Sigov.Application.Operational.KanbanService>();
        services.AddScoped<ITarefaNotificationService, NotificacaoRepository>();
        services.AddScoped<IOperationalEventPublisher, OutboxOperationalEventPublisher>();
        services.AddScoped<IEnterpriseTenantMappingService, EnterpriseTenantMappingService>();
        services.AddScoped<EnterpriseDapperCrudService>();
        services.AddScoped<IEnterpriseModuleService>(provider => provider.GetRequiredService<EnterpriseDapperCrudService>());
        services.AddScoped<IEnterpriseCrudService>(provider => provider.GetRequiredService<EnterpriseDapperCrudService>());
        services.AddScoped<IUserPreferenceRepository, UserPreferenceRepository>();
        services.AddScoped<IAuthenticationRepository, AuthenticationRepository>();
        services.AddScoped<IPasswordRecoveryService, PasswordRecoveryService>();
        services.AddOptions<PasswordRecoveryEmailOptions>().BindConfiguration(PasswordRecoveryEmailOptions.SectionName);
        services.AddScoped<IPasswordRecoveryEmailSender, SmtpPasswordRecoveryEmailSender>();
        services.AddSingleton<IPasswordPolicyService, PasswordPolicyService>();
        services.AddScoped<OnboardingRepository>();
        services.AddSingleton<IVersionInfoProvider, VersionInfoProvider>();
        services.AddSingleton<IReleaseInfoProvider, ReleaseInfoProvider>();
        services.AddSingleton<ReleaseMetadataReader>();
        services.AddSingleton<BuildInfoProvider>();
        services.AddSingleton<IGoLiveChecklistService, GoLiveChecklistService>();
        services.AddSingleton<ISmokeTestPlanService, SmokeTestPlanService>();
        services.AddSingleton<IHomologacaoValidator, HomologacaoValidator>();
        services.AddScoped<IHomologacaoSeedService, HomologacaoSeedService>();
        services.AddScoped<HomologacaoRepository>();
        services.AddScoped<IHealthCheckService, HealthCheckService>();
        services.AddScoped<IHealthCheck, DatabaseHealthCheck>();
        services.AddScoped<IHealthCheck, OutboxHealthCheck>();
        services.AddScoped<IHealthCheck, StorageHealthCheck>();
        services.AddScoped<IDatabaseObjectInspector, DatabaseObjectInspector>();
        services.AddScoped<ProjectStatusProvider>();

        services.AddScoped<IApiCredentialRepository, ApiCredentialRepository>();
        services.AddScoped<IIntegracaoSistemaRepository, IntegracaoSistemaRepository>();
        services.AddScoped<IWebhookRepository, WebhookRepository>();
        services.AddScoped<IOutboxRepository, OutboxRepository>();
        services.AddScoped<IIntegracaoLogRepository, IntegracaoLogRepository>();
        services.AddScoped<IRemessaOficialRepository, RemessaOficialRepository>();
        services.AddScoped<ICertificadoDigitalRepository, CertificadoDigitalRepository>();
        services.AddScoped<IIntegracaoDashboardRepository, IntegracaoDashboardRepository>();
        services.AddScoped<IIntegracaoExportacaoRepository, IntegracaoExportacaoRepository>();
        services.AddScoped<IApiKeyHasher, ApiKeyHasher>();
        services.AddScoped<IWebhookSignatureService, WebhookSignatureService>();
        services.AddScoped<IApiCredentialService, ApiCredentialService>();
        services.AddScoped<IIntegracaoSistemaService, IntegracaoSistemaService>();
        services.AddScoped<IWebhookService, WebhookService>();
        services.AddScoped<IIdempotencyService, IdempotencyService>();
        services.AddScoped<IOutboxService, OutboxService>();
        services.AddScoped<IIntegracaoLogService, IntegracaoLogService>();
        services.AddScoped<IRemessaOficialService, RemessaOficialService>();
        services.AddScoped<ICertificadoDigitalService, CertificadoDigitalService>();
        services.AddScoped<IGovBrAdapter, GovBrEstruturalService>();
        services.AddScoped<IAssinadorDigitalService, AssinadorDigitalEstruturalService>();
        services.AddScoped<IIntegracaoDashboardService, IntegracaoDashboardService>();
        services.AddScoped<IIntegracaoExportacaoService, IntegracaoExportacaoService>();
        services.AddScoped<PessoaRepository>();
        services.AddScoped<IPessoaCadastroRepository, PessoaRepository>();
        services.AddScoped<UsuarioRepository>();
        services.AddScoped<AuditRepository>();
        services.AddScoped<IAuditService, ProcessosAuditService>();
        services.AddScoped<ILgpdMaskingService, LgpdMaskingService>();
        services.AddScoped<ILgpdClassificationService, LgpdClassificationService>();
        services.AddScoped<ILgpdMaskingPolicy, LgpdMaskingPolicy>();
        services.AddScoped<ILgpdAccessLogger, LgpdAccessLogger>();
        services.AddScoped<IDateTimeProvider, DateTimeProvider>();
        services.AddScoped<ICorrelationIdProvider, CorrelationIdProvider>();
        services.AddScoped<ICurrentUser, CurrentUser>();
        services.AddScoped<ICurrentTenant, CurrentTenant>();
        services.AddScoped<ICurrentExercicio, CurrentExercicio>();
        services.AddScoped<IPasswordHashService, PasswordHashService>();
        services.AddScoped<Sigov.Application.Authorization.IAuthorizationEvaluator, PersistentAuthorizationEvaluator>();
        services.AddScoped<IPermissionService, PermissionService>();
        services.AddScoped<ITenantContext, TenantContext>();
        services.AddScoped<ITenantResolver, TenantResolver>();
        services.AddScoped<ITenantProvisioningService, TenantProvisioningService>();
        services.AddScoped<IFeatureFlagService, FeatureFlagService>();
        services.AddScoped<IModuloLicenciamentoService, ModuloLicenciamentoService>();
        services.AddScoped<ITenantUsageMeter, TenantUsageMeter>();
        services.AddScoped<ITenantConfigurationProvider, TenantConfigurationProvider>();
        services.AddScoped<Func<long, CancellationToken, Task<string?>>>(provider => async (tenantId, cancellationToken) =>
        {
            var context = provider.GetRequiredService<DapperContext>();
            using var connection = context.CreateConnection();
            return await Dapper.SqlMapper.ExecuteScalarAsync<string?>(connection, new Dapper.CommandDefinition("select status from sigov.tenant where id = @TenantId and ativo = true and is_deleted = false;", new { TenantId = tenantId }, cancellationToken: cancellationToken)).ConfigureAwait(false);
        });
        services.AddScoped<ITenantAccessGuard, TenantAccessGuard>();
        services.AddScoped<IIaMaskingService, IaMaskingService>();
        services.AddScoped<IIaProviderClient, InternalIaProviderClient>();
        services.AddScoped<IIaConsumptionService, IaConsumptionService>();
        services.AddScoped<IIaExecutionService, IaExecutionService>();
        services.AddScoped<IIaSuggestionService, IaSuggestionService>();
        services.AddScoped<IIaAutomationService, IaAutomationService>();
        services.AddSingleton<Sigov.Application.Saas.Modules.IModuleCatalogService, Sigov.Application.Saas.Modules.ModuleCatalogService>();
        services.AddScoped<Sigov.Application.Saas.Modules.IModuleAccessRepository, ModuleAccessRepository>();
        services.AddScoped<Sigov.Application.Saas.Modules.IModuleAccessChecker, Sigov.Application.Saas.Modules.ModuleAccessChecker>();
        services.AddScoped<Sigov.Application.Saas.Profiles.IProfileLevelRepository, ProfileLevelRepository>();
        services.AddScoped<Sigov.Application.Saas.Profiles.IProfileLevelService, Sigov.Application.Saas.Profiles.ProfileLevelService>();
        services.AddScoped<Sigov.Application.Saas.Profiles.IEffectivePermissionService, Sigov.Application.Saas.Profiles.EffectivePermissionService>();
        services.AddScoped<Sigov.Application.Saas.Parameters.ITenantParameterRepository, TenantParameterRepository>();
        services.AddScoped<Sigov.Application.Saas.Parameters.ITenantParameterService, Sigov.Application.Saas.Parameters.TenantParameterService>();
        services.AddScoped<Sigov.Application.Saas.Parameters.ITenantParameterResolver, Sigov.Application.Saas.Parameters.TenantParameterResolver>();
        services.AddScoped<Sigov.Application.Saas.Context.ITenantContextSwitchRepository, TenantContextSwitchRepository>();
        services.AddScoped<Sigov.Application.Saas.Context.IGlobalAdminChecker, Sigov.Application.Saas.Context.GlobalAdminChecker>();
        services.AddScoped<Sigov.Application.Saas.Context.ITenantContextSwitcher, Sigov.Application.Saas.Context.TenantContextSwitcher>();
        services.AddScoped<Sigov.Application.Saas.Context.IOperationalContextService, Sigov.Application.Saas.Context.OperationalContextService>();
        services.AddScoped<ISaasPlanoRepository, SaasPlanoRepository>();
        services.AddScoped<ISaasPlanoService, SaasPlanoService>();
        services.AddScoped<SaasPlanoValidator>();
        services.AddScoped<SaasPlanoMapper>();
        services.AddScoped<ISaasAssinaturaRepository, SaasAssinaturaRepository>();
        services.AddScoped<ISaasLimitValidator, SaasLimitValidator>();
        services.AddScoped<ISaasAssinaturaService, SaasAssinaturaService>();
        services.AddScoped<SaasAssinaturaValidator>();
        services.AddScoped<SaasAssinaturaMapper>();
        services.AddScoped<ISaasSolicitacaoClienteRepository, SaasSolicitacaoClienteRepository>();
        services.AddScoped<ISaasSolicitacaoClienteService, SaasSolicitacaoClienteService>();
        services.AddScoped<SaasSolicitacaoClienteValidator>();
        services.AddScoped<SaasSolicitacaoClienteMapper>();
        services.AddScoped<ISaasTenantProvisioningRepository, SaasTenantProvisioningRepository>();
        services.AddScoped<ISaasTenantProvisioningService, SaasTenantProvisioningService>();
        services.AddScoped<ITenantBrandingRepository, TenantBrandingRepository>();
        services.AddScoped<ITenantBrandingService, TenantBrandingService>();
        services.AddScoped<TenantBrandingValidator>();
        services.AddScoped<ITenantDominioRepository, TenantDominioRepository>();
        services.AddScoped<ITenantDominioService, TenantDominioService>();
        services.AddScoped<TenantDominioValidator>();
        services.AddScoped<ISaasPerfilTemplateRepository, SaasPerfilTemplateRepository>();
        services.AddScoped<ISaasPerfilTemplateService, SaasPerfilTemplateService>();
        services.AddScoped<SaasPerfilTemplateValidator>();
        services.AddScoped<SaasPerfilTemplateMapper>();
        services.AddScoped<ModuleCatalogRepository>();
        services.AddScoped<IFileHashService, FileHashService>();
        services.AddScoped<IStorageKeyGenerator, StorageKeyGenerator>();
        services.AddScoped<IFileTypeValidator, FileTypeValidator>();
        services.AddScoped<IAntivirusScanner, NoOpAntivirusScanner>();
        services.AddScoped<IFileStorageService, LocalFileStorageService>();
        services.AddScoped<ITipoProcessoRepository, TipoProcessoRepository>();
        services.AddScoped<IProcessoDigitalRepository, ProcessoDigitalRepository>();
        services.AddScoped<IProcessoMovimentacaoRepository, ProcessoMovimentacaoRepository>();
        services.AddScoped<IProcessoParecerRepository, ProcessoParecerRepository>();
        services.AddScoped<IProtocoloAtendimentoRepository, ProtocoloAtendimentoRepository>();
        services.AddScoped<IOuvidoriaRepository, OuvidoriaRepository>();
        services.AddScoped<Sigov.Application.Processos.IDiarioOficialRepository, DiarioOficialRepository>();
        services.AddScoped<IProcessoSequencialService, ProcessoSequencialRepository>();
        services.AddScoped<ITipoProcessoService, TipoProcessoService>();
        services.AddScoped<IProcessoDigitalService, ProcessoDigitalService>();
        services.AddScoped<IProtocoloAtendimentoService, ProtocoloAtendimentoService>();
        services.AddScoped<Sigov.Application.Processos.IOuvidoriaService, OuvidoriaService>();
        services.AddScoped<Sigov.Application.Processos.IDiarioOficialService, DiarioOficialService>();
        services.AddScoped<IPlanoContasRepository, PlanoContasRepository>();
        services.AddScoped<IFonteRecursoRepository, FonteRecursoRepository>();
        services.AddScoped<IProgramaRepository, ProgramaRepository>();
        services.AddScoped<IAcaoRepository, AcaoRepository>();
        services.AddScoped<INaturezaReceitaRepository, NaturezaReceitaRepository>();
        services.AddScoped<INaturezaDespesaRepository, NaturezaDespesaRepository>();
        services.AddScoped<IOrcamentoRepository, OrcamentoRepository>();
        services.AddScoped<IEmpenhoRepository, EmpenhoRepository>();
        services.AddScoped<ILiquidacaoRepository, LiquidacaoRepository>();
        services.AddScoped<IPagamentoRepository, PagamentoRepository>();
        services.AddScoped<IReceitaRepository, ReceitaRepository>();
        services.AddScoped<IFinanceiroSequencialService, FinanceiroSequencialRepository>();
        services.AddScoped<IFinanceiroDashboardRepository, FinanceiroDashboardRepository>();
        services.AddScoped<IFinanceiroEmpresarialRepository, FinanceiroEmpresarialRepository>();
        services.AddScoped<IPlanoContasService, PlanoContasService>();
        services.AddScoped<IFonteRecursoService, FonteRecursoService>();
        services.AddScoped<IProgramaService, ProgramaService>();
        services.AddScoped<IAcaoService, AcaoService>();
        services.AddScoped<INaturezaReceitaService, NaturezaReceitaService>();
        services.AddScoped<INaturezaDespesaService, NaturezaDespesaService>();
        services.AddScoped<IOrcamentoService, OrcamentoService>();
        services.AddScoped<IEmpenhoService, EmpenhoService>();
        services.AddScoped<ILiquidacaoService, LiquidacaoService>();
        services.AddScoped<IPagamentoService, PagamentoService>();
        services.AddScoped<IReceitaService, ReceitaService>();
        services.AddScoped<IFinanceiroDashboardService, FinanceiroDashboardService>();
        services.AddScoped<IFinanceiroExportacaoService, FinanceiroExportacaoService>();
        services.AddScoped<IRelatorioExecutivoRepository, RelatorioExecutivoRepository>();
        services.AddScoped<IRelatorioExecutivoService, RelatorioExecutivoService>();
        services.AddScoped<IRelatorioExecutivoWidgetService, RelatorioExecutivoWidgetService>();
        services.AddScoped<IRelatorioExecutivoExportService, RelatorioExecutivoExportService>();
        services.AddScoped<IRhRepository, RhRepository>();
        services.AddScoped<IOperationalImportStore, OperationalImportStore>();
        services.AddScoped<IRhService, RhService>();
        services.AddScoped<IRhTypedService, RhTypedService>();
        services.AddScoped<IPessoaCadastroService, PessoaCadastroService>();
        services.AddScoped<IModuleParameterRepository, ModuleParameterRepository>();
        services.AddScoped<IModuleParameterService, ModuleParameterService>();
        services.AddScoped<EducacaoRepository>();
        services.AddScoped<EducacaoBloco3Repository>();
        services.AddScoped<IEducacaoBloco3Repository, EducacaoBloco3Repository>();
        services.AddScoped<IEducacaoSecretariaRepository, EducacaoBloco3Repository>();
        services.AddScoped<IEducacaoDiarioClasseRepository, EducacaoBloco3Repository>();
        services.AddScoped<IEducacaoPortalRepository, EducacaoBloco3Repository>();
        services.AddScoped<EducacaoBloco3Service>();
        services.AddScoped<IEducacaoSecretariaService, EducacaoBloco3Service>();
        services.AddScoped<IEducacaoDocumentoEscolarService, EducacaoBloco3Service>();
        services.AddScoped<IEducacaoTransferenciaService, EducacaoBloco3Service>();
        services.AddScoped<IEducacaoSolicitacaoEscolarService, EducacaoBloco3Service>();
        services.AddScoped<IEducacaoDiarioClasseService, EducacaoBloco3Service>();
        services.AddScoped<IEducacaoDiarioFrequenciaService, EducacaoBloco3Service>();
        services.AddScoped<IEducacaoDiarioFechamentoService, EducacaoBloco3Service>();
        services.AddScoped<IEducacaoPortalService, EducacaoBloco3Service>();
        services.AddScoped<IEducacaoPortalSolicitacaoService, EducacaoBloco3Service>();
        services.AddScoped<IEducacaoComunicadoService, EducacaoBloco3Service>();
        services.AddScoped<IEducacaoRepository, EducacaoRepository>();
        services.AddScoped<IEscolaRepository, EducacaoRepository>();
        services.AddScoped<IAnoLetivoRepository, EducacaoRepository>();
        services.AddScoped<ICursoRepository, EducacaoRepository>();
        services.AddScoped<ITurmaRepository, EducacaoRepository>();
        services.AddScoped<IAlunoRepository, EducacaoRepository>();
        services.AddScoped<IMatriculaRepository, EducacaoRepository>();
        services.AddScoped<IProfessorRepository, EducacaoRepository>();
        services.AddScoped<IFrequenciaRepository, EducacaoRepository>();
        services.AddScoped<IAvaliacaoRepository, EducacaoRepository>();
        services.AddScoped<IPreMatriculaRepository, EducacaoRepository>();
        services.AddScoped<IEducacensoRepository, EducacaoRepository>();
        services.AddScoped<IEducacaoDashboardRepository, EducacaoRepository>();
        services.AddScoped<IEducacaoExportacaoRepository, EducacaoRepository>();
        services.AddScoped<IEducacaoSequencialService, EducacaoRepository>();
        services.AddScoped<EducacaoService>();
        services.AddScoped<IEscolaService, EducacaoService>();
        services.AddScoped<IAnoLetivoService, EducacaoService>();
        services.AddScoped<ICursoService, EducacaoService>();
        services.AddScoped<ITurmaService, EducacaoService>();
        services.AddScoped<IAlunoService, EducacaoService>();
        services.AddScoped<IMatriculaService, EducacaoService>();
        services.AddScoped<IProfessorService, EducacaoService>();
        services.AddScoped<IFrequenciaService, EducacaoService>();
        services.AddScoped<IAvaliacaoService, EducacaoService>();
        services.AddScoped<IBoletimService, EducacaoService>();
        services.AddScoped<IPreMatriculaService, EducacaoService>();
        services.AddScoped<IEducacensoService, EducacaoService>();
        services.AddScoped<IEducacaoDashboardService, EducacaoService>();
        services.AddScoped<IEducacaoExportacaoService, EducacaoService>();
        services.AddScoped<IWorkflowRepository, WorkflowRepository>();
        services.AddScoped<IWorkflowOperacionalService, WorkflowOperacionalService>();
        services.AddScoped<SaudeRepository>();
        services.AddScoped<ISaudeCrudRepository, SaudeRepository>();
        services.AddScoped<IUnidadeSaudeRepository, SaudeRepository>();
        services.AddScoped<IProfissionalSaudeRepository, SaudeRepository>();
        services.AddScoped<IPacienteRepository, SaudeRepository>();
        services.AddScoped<IProntuarioRepository, SaudeRepository>();
        services.AddScoped<IAtendimentoSaudeRepository, SaudeRepository>();
        services.AddScoped<IAgendaSaudeRepository, SaudeRepository>();
        services.AddScoped<IFarmaciaRepository, SaudeRepository>();
        services.AddScoped<IVacinacaoRepository, SaudeRepository>();
        services.AddScoped<ILaboratorioRepository, SaudeRepository>();
        services.AddScoped<IRegulacaoRepository, SaudeRepository>();
        services.AddScoped<IAcsRepository, SaudeRepository>();
        services.AddScoped<IAcsSyncRepository, SaudeRepository>();
        services.AddScoped<ISaudeDashboardRepository, SaudeRepository>();
        services.AddScoped<ISaudeExportacaoRepository, SaudeRepository>();
        services.AddScoped<ISaudeSequencialService, SaudeRepository>();
        services.AddScoped<SaudeService>();
        services.AddScoped<IUnidadeSaudeService, SaudeService>();
        services.AddScoped<IProfissionalSaudeService, SaudeService>();
        services.AddScoped<IPacienteService, SaudeService>();
        services.AddScoped<IProntuarioService, SaudeService>();
        services.AddScoped<IAtendimentoSaudeService, SaudeService>();
        services.AddScoped<IAgendaSaudeService, SaudeService>();
        services.AddScoped<IFarmaciaService, SaudeService>();
        services.AddScoped<IVacinacaoService, SaudeService>();
        services.AddScoped<ILaboratorioService, SaudeService>();
        services.AddScoped<IRegulacaoService, SaudeService>();
        services.AddScoped<IAcsService, SaudeService>();
        services.AddScoped<IAcsSyncService, SaudeService>();
        services.AddScoped<ISaudeDashboardService, SaudeService>();
        services.AddScoped<ISaudeExportacaoService, SaudeService>();

        services.AddScoped<SaneamentoRepository>();
        services.AddScoped<ISaneamentoConsumidorRepository, SaneamentoRepository>();
        services.AddScoped<ILigacaoSaneamentoRepository, SaneamentoRepository>();
        services.AddScoped<IUnidadeConsumidoraRepository, SaneamentoRepository>();
        services.AddScoped<IHidrometroRepository, SaneamentoRepository>();
        services.AddScoped<ILeituraConsumoRepository, SaneamentoRepository>();
        services.AddScoped<IFaturaSaneamentoRepository, SaneamentoRepository>();
        services.AddScoped<IArrecadacaoSaneamentoRepository, SaneamentoRepository>();
        services.AddScoped<IParcelamentoSaneamentoRepository, SaneamentoRepository>();
        services.AddScoped<IOrdemServicoSaneamentoRepository, SaneamentoRepository>();
        services.AddScoped<IEquipeCampoSaneamentoRepository, SaneamentoRepository>();
        services.AddScoped<ILaboratorioSaneamentoRepository, SaneamentoRepository>();
        services.AddScoped<IRedeSaneamentoRepository, SaneamentoRepository>();
        services.AddScoped<ISaneamentoDashboardRepository, SaneamentoRepository>();
        services.AddScoped<ISaneamentoExportacaoRepository, SaneamentoRepository>();
        services.AddScoped<ISaneamentoSequencialService, SaneamentoRepository>();
        services.AddScoped<SaneamentoService>();
        services.AddScoped<ISaneamentoConsumidorService, SaneamentoService>();
        services.AddScoped<ILigacaoSaneamentoService, SaneamentoService>();
        services.AddScoped<IUnidadeConsumidoraService, SaneamentoService>();
        services.AddScoped<IHidrometroService, SaneamentoService>();
        services.AddScoped<ILeituraConsumoService, SaneamentoService>();
        services.AddScoped<IFaturaSaneamentoService, SaneamentoService>();
        services.AddScoped<IArrecadacaoSaneamentoService, SaneamentoService>();
        services.AddScoped<IParcelamentoSaneamentoService, SaneamentoService>();
        services.AddScoped<IOrdemServicoSaneamentoService, SaneamentoService>();
        services.AddScoped<IEquipeCampoSaneamentoService, SaneamentoService>();
        services.AddScoped<ILaboratorioSaneamentoService, SaneamentoService>();
        services.AddScoped<IRedeSaneamentoService, SaneamentoService>();
        services.AddScoped<ISaneamentoDashboardService, SaneamentoService>();
        services.AddScoped<ISaneamentoExportacaoService, SaneamentoService>();
        services.AddScoped<SocialRepository>();
        services.AddScoped<IAgroModuloCatalogService, AgroModuloCatalogService>();
        services.AddScoped<ICoordenadaValidator, CoordenadaValidator>();
        services.AddScoped<IGeoJsonValidator, GeoJsonValidator>();
        services.AddScoped<IAgroAccessChecker, AgroAccessChecker>();
        services.AddScoped<IAgroDashboardRepository, AgroDashboardRepository>();
        services.AddScoped<AgroModuleRepository>();
        services.AddScoped<IAgroGeoRepository, AgroGeoRepository>();
        services.AddScoped<IAgroDashboardService, AgroDashboardService>();
        services.AddScoped<IAgroGeoService, AgroGeoService>();
        services.AddScoped<AcessoDadoPessoalService>();
        services.AddScoped<AgroProdutorValidator>();
        services.AddScoped<AgroProdutorPermissionChecker>();
        services.AddScoped<AgroProdutorAuditWriter>();
        services.AddScoped<AgroProdutorMapper>();
        services.AddScoped<AgroProdutorExportService>();
        services.AddScoped<IAgroProdutorRepository, AgroProdutorRepository>();
        services.AddScoped<IAgroProdutorService, AgroProdutorService>();
        services.AddScoped<AgroPropriedadeValidator>();
        services.AddScoped<AgroPropriedadePermissionChecker>();
        services.AddScoped<AgroPropriedadeAuditWriter>();
        services.AddScoped<AgroPropriedadeMapper>();
        services.AddScoped<AgroTalhaoValidator>();
        services.AddScoped<AgroCulturaValidator>();
        services.AddScoped<AgroSafraValidator>();
        services.AddScoped<IAgroPropriedadeRepository, AgroPropriedadeRepository>();
        services.AddScoped<AgroPropriedadeService>();
        services.AddScoped<IAgroPropriedadeService, AgroPropriedadeService>();
        services.AddScoped<IAgroTalhaoService, AgroPropriedadeService>();
        services.AddScoped<IAgroCulturaService, AgroPropriedadeService>();
        services.AddScoped<IAgroSafraService, AgroPropriedadeService>();
        services.AddScoped<AgroProducaoAgricolaValidator>();
        services.AddScoped<AgroProducaoAgricolaMapper>();
        services.AddScoped<IAgroProducaoRepository, AgroProducaoRepository>();
        services.AddScoped<IAgroProducaoAgricolaService, AgroProducaoAgricolaService>();
        services.AddScoped<AgroProgramaRuralValidator>();
        services.AddScoped<AgroProgramaRuralPermissionChecker>();
        services.AddScoped<AgroProgramaRuralAuditWriter>();
        services.AddScoped<AgroProgramaRuralMapper>();
        services.AddScoped<AgroBeneficioRuralValidator>();
        services.AddScoped<AgroBeneficioRuralPermissionChecker>();
        services.AddScoped<AgroBeneficioRuralAuditWriter>();
        services.AddScoped<AgroBeneficioRuralMapper>();
        services.AddScoped<AgroInsumoValidator>();
        services.AddScoped<AgroDistribuicaoInsumoValidator>();
        services.AddScoped<IAgroProgramasRepository, AgroProgramasRepository>();
        services.AddScoped<IAgroProgramaRuralService, AgroProgramaRuralService>();
        services.AddScoped<IAgroBeneficioRuralService, AgroBeneficioRuralService>();
        services.AddScoped<IAgroInsumoService, AgroInsumoService>();
        services.AddScoped<IAgroDistribuicaoInsumoService, AgroDistribuicaoInsumoService>();
        services.AddScoped<AgroMaquinaValidator>();
        services.AddScoped<AgroMaquinaPermissionChecker>();
        services.AddScoped<AgroMaquinaAuditWriter>();
        services.AddScoped<AgroImplementoValidator>();
        services.AddScoped<AgroAgendaMaquinaValidator>();
        services.AddScoped<AgroServicoMaquinaValidator>();
        services.AddScoped<AgroServicoMaquinaPermissionChecker>();
        services.AddScoped<AgroServicoMaquinaAuditWriter>();
        services.AddScoped<AgroServicoMaquinaMapper>();
        services.AddScoped<IAgroPatrulhaMecanizadaRepository, AgroPatrulhaMecanizadaRepository>();
        services.AddScoped<IAgroMaquinaService, AgroMaquinaService>();
        services.AddScoped<IAgroImplementoService, AgroImplementoService>();
        services.AddScoped<IAgroAgendaMaquinaService, AgroAgendaMaquinaService>();
        services.AddScoped<IAgroServicoMaquinaService, AgroServicoMaquinaService>();
        services.AddScoped<AgroEstradaVicinalValidator>();
        services.AddScoped<AgroEstradaVicinalPermissionChecker>();
        services.AddScoped<AgroEstradaVicinalAuditWriter>();
        services.AddScoped<AgroPontoCriticoValidator>();
        services.AddScoped<AgroOcorrenciaRuralValidator>();
        services.AddScoped<AgroManutencaoRuralValidator>();
        services.AddScoped<IAgroInfraestruturaRuralRepository, AgroInfraestruturaRuralRepository>();
        services.AddScoped<IAgroEstradaVicinalService, AgroEstradaVicinalService>();
        services.AddScoped<IAgroPontoCriticoService, AgroPontoCriticoService>();
        services.AddScoped<IAgroOcorrenciaRuralService, AgroOcorrenciaRuralService>();
        services.AddScoped<IAgroManutencaoRuralService, AgroManutencaoRuralService>();
        services.AddScoped<AgroFeiraValidator>();
        services.AddScoped<AgroFeiranteValidator>();
        services.AddScoped<IAgroFeirasRepository, AgroFeirasRepository>();
        services.AddScoped<IAgroFeiraService, AgroFeiraService>();
        services.AddScoped<IAgroFeiranteService, AgroFeiranteService>();
        services.AddScoped<AgroAgroindustriaValidator>();
        services.AddScoped<AgroInspecaoMunicipalValidator>();
        services.AddScoped<IAgroAgroindustriaRepository, AgroAgroindustriaRepository>();
        services.AddScoped<IAgroAgroindustriaService, AgroAgroindustriaService>();
        services.AddScoped<IAgroInspecaoMunicipalService, AgroInspecaoMunicipalService>();
        services.AddScoped<AgroCompraAgriculturaFamiliarValidator>();
        services.AddScoped<IAgroCompraAgriculturaFamiliarRepository, AgroCompraAgriculturaFamiliarRepository>();
        services.AddScoped<IAgroCompraAgriculturaFamiliarService, AgroCompraAgriculturaFamiliarService>();
        services.AddScoped<AgroIndicadorValidator>();
        services.AddScoped<AgroRelatorioValidator>();
        services.AddScoped<AgroDatasetValidator>();
        services.AddScoped<AgroDatasetAnonymizer>();
        services.AddScoped<IAgroBiRepository, AgroBiRepository>();
        services.AddScoped<IAgroBiService, AgroBiService>();
        services.AddScoped<IAgroIndicadorRepository, AgroRelatoriosRepository>();
        services.AddScoped<IAgroRelatoriosRepository, AgroRelatoriosRepository>();
        services.AddScoped<IAgroIndicadorService, AgroIndicadorService>();
        services.AddScoped<IAgroRelatorioService, AgroRelatorioService>();
        services.AddScoped<IAgroExportService, AgroRelatorioService>();
        services.AddScoped<AgroRelatorioExportService>();
        services.AddScoped<AgroExportService>();
        services.AddScoped<IAgroTransparenciaRepository, AgroTransparenciaRepository>();
        services.AddScoped<IAgroTransparenciaService, AgroTransparenciaService>();
        services.AddScoped<IIndustriaEstoqueService, IndustriaEstoqueService>();
        services.AddScoped<IIndustriaComercialService, IndustriaComercialService>();
        services.AddScoped<IAgroDicionarioDadosRepository, AgroDicionarioDadosRepository>();
        services.AddScoped<IAgroDicionarioDadosService, AgroDicionarioDadosService>();
        services.AddScoped<IAgroPainelComercialRepository, AgroPainelComercialRepository>();
        services.AddScoped<IAgroPainelComercialService, AgroPainelComercialService>();
        services.AddScoped<ISocialUnidadeRepository, SocialRepository>();
        services.AddScoped<ISocialFamiliaRepository, SocialRepository>();
        services.AddScoped<ISocialPessoaRepository, SocialRepository>();
        services.AddScoped<ISocialCadastroRepository, SocialRepository>();
        services.AddScoped<ISocialProgramaRepository, SocialRepository>();
        services.AddScoped<ISocialBeneficioRepository, SocialRepository>();
        services.AddScoped<ISocialAtendimentoRepository, SocialRepository>();
        services.AddScoped<ISocialVisitaRepository, SocialRepository>();
        services.AddScoped<ISocialParecerRepository, SocialRepository>();
        services.AddScoped<ISocialAcompanhamentoRepository, SocialRepository>();
        services.AddScoped<ISocialVigilanciaRepository, SocialRepository>();
        services.AddScoped<ISocialDashboardRepository, SocialRepository>();
        services.AddScoped<ISocialExportacaoRepository, SocialRepository>();
        services.AddScoped<ISocialSequencialService, SocialRepository>();
        services.AddScoped<SocialService>();
        services.AddScoped<ISocialUnidadeService, SocialService>();
        services.AddScoped<ISocialFamiliaService, SocialService>();
        services.AddScoped<ISocialPessoaService, SocialService>();
        services.AddScoped<ISocialCadastroService, SocialService>();
        services.AddScoped<ISocialProgramaService, SocialService>();
        services.AddScoped<ISocialBeneficioService, SocialService>();
        services.AddScoped<ISocialAtendimentoService, SocialService>();
        services.AddScoped<ISocialVisitaService, SocialService>();
        services.AddScoped<ISocialParecerService, SocialService>();
        services.AddScoped<ISocialAcompanhamentoService, SocialService>();
        services.AddScoped<ISocialVigilanciaService, SocialService>();
        services.AddScoped<ISocialDashboardService, SocialService>();
        services.AddScoped<ISocialExportacaoService, SocialService>();
        services.AddScoped<FrotasObrasRepository>();
        services.AddScoped<IFrotasRepository, FrotasObrasRepository>();
        services.AddScoped<IObrasRepository, FrotasObrasRepository>();
        services.AddScoped<IFrotasService, FrotasService>();
        services.AddScoped<IObrasService, ObrasService>();
                services.AddScoped<Bloco8Repository>();
        services.AddScoped<IBloco8Repository, Bloco8Repository>();
        services.AddScoped<IProcessosDigitaisRepository, Bloco8Repository>();
        services.AddScoped<IGedRepository, Bloco8Repository>();
        services.AddScoped<IAssinaturaRepository, Bloco8Repository>();
        services.AddScoped<ILegislativoRepository, Bloco8Repository>();
        services.AddScoped<ITransparenciaRepository, Bloco8Repository>();
        services.AddScoped<Sigov.Application.Bloco8.IDiarioOficialRepository, Bloco8Repository>();
        services.AddScoped<Bloco8Service>();
        services.AddScoped<IProcessosDigitaisService>(sp => sp.GetRequiredService<Bloco8Service>());
        services.AddScoped<IProtocoloDigitalService>(sp => sp.GetRequiredService<Bloco8Service>());
        services.AddScoped<IProcessoNumeroService>(sp => sp.GetRequiredService<Bloco8Service>());
        services.AddScoped<IProcessoMovimentacaoService>(sp => sp.GetRequiredService<Bloco8Service>());
        services.AddScoped<IProcessoRelatorioService>(sp => sp.GetRequiredService<Bloco8Service>());
        services.AddScoped<IGedService>(sp => sp.GetRequiredService<Bloco8Service>());
        services.AddScoped<IGedDocumentoService>(sp => sp.GetRequiredService<Bloco8Service>());
        services.AddScoped<IGedArquivoFisicoService>(sp => sp.GetRequiredService<Bloco8Service>());
        services.AddScoped<IGedValidacaoPublicaService>(sp => sp.GetRequiredService<Bloco8Service>());
        services.AddScoped<IAssinaturaService>(sp => sp.GetRequiredService<Bloco8Service>());
        services.AddScoped<ILegislativoService>(sp => sp.GetRequiredService<Bloco8Service>());
        services.AddScoped<ILegislativoProposicaoService>(sp => sp.GetRequiredService<Bloco8Service>());
        services.AddScoped<ILegislativoSessaoService>(sp => sp.GetRequiredService<Bloco8Service>());
        services.AddScoped<ILegislativoVotacaoService>(sp => sp.GetRequiredService<Bloco8Service>());
        services.AddScoped<ILegislativoNormaService>(sp => sp.GetRequiredService<Bloco8Service>());
        services.AddScoped<ILegislativoRelatorioService>(sp => sp.GetRequiredService<Bloco8Service>());
        services.AddScoped<ITransparenciaService>(sp => sp.GetRequiredService<Bloco8Service>());
        services.AddScoped<Sigov.Application.Bloco8.IDiarioOficialService>(sp => sp.GetRequiredService<Bloco8Service>());
        services.AddScoped<IEsicService>(sp => sp.GetRequiredService<Bloco8Service>());
        services.AddScoped<Sigov.Application.Bloco8.IOuvidoriaService>(sp => sp.GetRequiredService<Bloco8Service>());
        services.AddScoped<IAtendimentoDigitalService>(sp => sp.GetRequiredService<Bloco8Service>());
        services.AddScoped<EmpresarialRepository>();
        services.AddScoped<IEmpresarialRepository>(sp => sp.GetRequiredService<EmpresarialRepository>());
        services.AddScoped<IEmpresarialComercialRepository>(sp => sp.GetRequiredService<EmpresarialRepository>());
        services.AddScoped<IEmpresarialOrdemServicoRepository>(sp => sp.GetRequiredService<EmpresarialRepository>());
        services.AddScoped<IEmpresarialEstoqueRepository>(sp => sp.GetRequiredService<EmpresarialRepository>());
        services.AddScoped<IEmpresarialIndustrialRepository>(sp => sp.GetRequiredService<EmpresarialRepository>());
        services.AddScoped<EmpresarialService>();
        services.AddScoped<IEmpresarialComercialService>(sp => sp.GetRequiredService<EmpresarialService>());
        services.AddScoped<IEmpresarialComercialDashboardService>(sp => sp.GetRequiredService<EmpresarialService>());
        services.AddScoped<IEmpresarialClienteService>(sp => sp.GetRequiredService<EmpresarialService>()); services.AddScoped<IEmpresarialLeadService>(sp => sp.GetRequiredService<EmpresarialService>()); services.AddScoped<IEmpresarialPropostaService>(sp => sp.GetRequiredService<EmpresarialService>()); services.AddScoped<IEmpresarialPedidoService>(sp => sp.GetRequiredService<EmpresarialService>());
        services.AddScoped<IEmpresarialOrdemServicoService>(sp => sp.GetRequiredService<EmpresarialService>()); services.AddScoped<IEmpresarialOrdemServicoDashboardService>(sp => sp.GetRequiredService<EmpresarialService>()); services.AddScoped<IEmpresarialOrdemServicoSlaService>(sp => sp.GetRequiredService<EmpresarialService>()); services.AddScoped<IEmpresarialOrdemServicoChecklistService>(sp => sp.GetRequiredService<EmpresarialService>());
        services.AddScoped<IEmpresarialEstoqueService>(sp => sp.GetRequiredService<EmpresarialService>()); services.AddScoped<IEmpresarialEstoqueDashboardService>(sp => sp.GetRequiredService<EmpresarialService>()); services.AddScoped<IEmpresarialProdutoService>(sp => sp.GetRequiredService<EmpresarialService>()); services.AddScoped<IEmpresarialMovimentoEstoqueService>(sp => sp.GetRequiredService<EmpresarialService>()); services.AddScoped<IEmpresarialCompraService>(sp => sp.GetRequiredService<EmpresarialService>());
        services.AddScoped<IEmpresarialIndustrialService>(sp => sp.GetRequiredService<EmpresarialService>()); services.AddScoped<IEmpresarialIndustrialDashboardService>(sp => sp.GetRequiredService<EmpresarialService>()); services.AddScoped<IEmpresarialAtivoIndustrialService>(sp => sp.GetRequiredService<EmpresarialService>()); services.AddScoped<IEmpresarialPlanoManutencaoService>(sp => sp.GetRequiredService<EmpresarialService>()); services.AddScoped<IEmpresarialProducaoService>(sp => sp.GetRequiredService<EmpresarialService>());
        services.AddScoped<SaudeAvancadaRepository>();
        services.AddScoped<ISaudeAcsOfflineRepository>(sp => sp.GetRequiredService<SaudeAvancadaRepository>()); services.AddScoped<ISaudeAcsOfflineService>(sp => sp.GetRequiredService<SaudeAvancadaRepository>()); services.AddScoped<ISaudeAcsSincronizacaoService>(sp => sp.GetRequiredService<SaudeAvancadaRepository>()); services.AddScoped<ISaudeAcsGeorreferenciaService>(sp => sp.GetRequiredService<SaudeAvancadaRepository>()); services.AddScoped<ISaudeAcsRelatorioService>(sp => sp.GetRequiredService<SaudeAvancadaRepository>());
        services.AddScoped<ISaudeAcsCampoRepository>(sp => sp.GetRequiredService<SaudeAvancadaRepository>()); services.AddScoped<ISaudeAcsCampoService>(sp => sp.GetRequiredService<SaudeAvancadaRepository>()); services.AddScoped<ISaudeDomicilioService>(sp => sp.GetRequiredService<SaudeAvancadaRepository>()); services.AddScoped<ISaudeVisitaDomiciliarService>(sp => sp.GetRequiredService<SaudeAvancadaRepository>()); services.AddScoped<ISaudeAtividadeColetivaService>(sp => sp.GetRequiredService<SaudeAvancadaRepository>()); services.AddScoped<ISaudeOcorrenciaCampoService>(sp => sp.GetRequiredService<SaudeAvancadaRepository>());
        services.AddScoped<ISaudeOperacaoRepository>(sp => sp.GetRequiredService<SaudeAvancadaRepository>()); services.AddScoped<ISaudeVacinacaoAvancadaService>(sp => sp.GetRequiredService<SaudeAvancadaRepository>()); services.AddScoped<ISaudeFarmaciaAvancadaService>(sp => sp.GetRequiredService<SaudeAvancadaRepository>()); services.AddScoped<ISaudeRegulacaoAvancadaService>(sp => sp.GetRequiredService<SaudeAvancadaRepository>()); services.AddScoped<ISaudeOperacaoDashboardService>(sp => sp.GetRequiredService<SaudeAvancadaRepository>());
        services.AddScoped<ISaudeRetaguardaRepository>(sp => sp.GetRequiredService<SaudeAvancadaRepository>()); services.AddScoped<ISaudeRetaguardaService>(sp => sp.GetRequiredService<SaudeAvancadaRepository>()); services.AddScoped<ISaudeEsusPreparatorioService>(sp => sp.GetRequiredService<SaudeAvancadaRepository>()); services.AddScoped<ISaudeSlaService>(sp => sp.GetRequiredService<SaudeAvancadaRepository>()); services.AddScoped<ISaudeSuporteService>(sp => sp.GetRequiredService<SaudeAvancadaRepository>()); services.AddScoped<ISaudeIndicadoresService>(sp => sp.GetRequiredService<SaudeAvancadaRepository>());
        services.AddScoped<SaneamentoAvancadoRepository>();
        services.AddScoped<ISaneamentoComercialRepository>(sp => sp.GetRequiredService<SaneamentoAvancadoRepository>()); services.AddScoped<ISaneamentoComercialService>(sp => sp.GetRequiredService<SaneamentoAvancadoRepository>()); services.AddScoped<ISaneamentoLigacaoService>(sp => sp.GetRequiredService<SaneamentoAvancadoRepository>()); services.AddScoped<ISaneamentoHidrometroService>(sp => sp.GetRequiredService<SaneamentoAvancadoRepository>()); services.AddScoped<ISaneamentoAtendimentoService>(sp => sp.GetRequiredService<SaneamentoAvancadoRepository>());
        services.AddScoped<ISaneamentoFaturamentoRepository>(sp => sp.GetRequiredService<SaneamentoAvancadoRepository>()); services.AddScoped<ISaneamentoFaturamentoService>(sp => sp.GetRequiredService<SaneamentoAvancadoRepository>()); services.AddScoped<ISaneamentoLeituraService>(sp => sp.GetRequiredService<SaneamentoAvancadoRepository>()); services.AddScoped<ISaneamentoFaturaService>(sp => sp.GetRequiredService<SaneamentoAvancadoRepository>()); services.AddScoped<ISaneamentoArrecadacaoService>(sp => sp.GetRequiredService<SaneamentoAvancadoRepository>()); services.AddScoped<ISaneamentoInadimplenciaService>(sp => sp.GetRequiredService<SaneamentoAvancadoRepository>());
        services.AddScoped<ISaneamentoOperacaoRepository>(sp => sp.GetRequiredService<SaneamentoAvancadoRepository>()); services.AddScoped<ISaneamentoOperacaoService>(sp => sp.GetRequiredService<SaneamentoAvancadoRepository>()); services.AddScoped<ISaneamentoOrdemServicoService>(sp => sp.GetRequiredService<SaneamentoAvancadoRepository>()); services.AddScoped<ISaneamentoCorteReligacaoService>(sp => sp.GetRequiredService<SaneamentoAvancadoRepository>()); services.AddScoped<ISaneamentoVazamentoService>(sp => sp.GetRequiredService<SaneamentoAvancadoRepository>()); services.AddScoped<ISaneamentoEquipeService>(sp => sp.GetRequiredService<SaneamentoAvancadoRepository>());
        services.AddScoped<ISaneamentoGisQualidadeRepository>(sp => sp.GetRequiredService<SaneamentoAvancadoRepository>()); services.AddScoped<ISaneamentoGisQualidadeService>(sp => sp.GetRequiredService<SaneamentoAvancadoRepository>()); services.AddScoped<ISaneamentoGisService>(sp => sp.GetRequiredService<SaneamentoAvancadoRepository>()); services.AddScoped<ISaneamentoLaboratorioService>(sp => sp.GetRequiredService<SaneamentoAvancadoRepository>()); services.AddScoped<ISaneamentoQualidadeService>(sp => sp.GetRequiredService<SaneamentoAvancadoRepository>());
        services.AddScoped<EducacaoAvancadaRepository>();
        services.AddScoped<IEducacaoTransporteEscolarRepository>(sp => sp.GetRequiredService<EducacaoAvancadaRepository>()); services.AddScoped<IEducacaoTransporteEscolarService>(sp => sp.GetRequiredService<EducacaoAvancadaRepository>()); services.AddScoped<IEducacaoTransporteDashboardService>(sp => sp.GetRequiredService<EducacaoAvancadaRepository>()); services.AddScoped<IEducacaoTransporteRelatorioService>(sp => sp.GetRequiredService<EducacaoAvancadaRepository>());
        services.AddScoped<IEducacaoMerendaRepository>(sp => sp.GetRequiredService<EducacaoAvancadaRepository>()); services.AddScoped<IEducacaoMerendaService>(sp => sp.GetRequiredService<EducacaoAvancadaRepository>()); services.AddScoped<IEducacaoMerendaEstoqueService>(sp => sp.GetRequiredService<EducacaoAvancadaRepository>()); services.AddScoped<IEducacaoMerendaCardapioService>(sp => sp.GetRequiredService<EducacaoAvancadaRepository>()); services.AddScoped<IEducacaoMerendaRelatorioService>(sp => sp.GetRequiredService<EducacaoAvancadaRepository>());
        services.AddScoped<IEducacaoBibliotecaRepository>(sp => sp.GetRequiredService<EducacaoAvancadaRepository>()); services.AddScoped<IEducacaoBibliotecaService>(sp => sp.GetRequiredService<EducacaoAvancadaRepository>()); services.AddScoped<IEducacaoBibliotecaEmprestimoService>(sp => sp.GetRequiredService<EducacaoAvancadaRepository>()); services.AddScoped<IEducacaoBibliotecaRelatorioService>(sp => sp.GetRequiredService<EducacaoAvancadaRepository>());
        services.AddScoped<IEducacaoIndicadoresRepository>(sp => sp.GetRequiredService<EducacaoAvancadaRepository>()); services.AddScoped<IEducacaoIndicadoresService>(sp => sp.GetRequiredService<EducacaoAvancadaRepository>()); services.AddScoped<IEducacaoFundebService>(sp => sp.GetRequiredService<EducacaoAvancadaRepository>()); services.AddScoped<IEducacaoCustosService>(sp => sp.GetRequiredService<EducacaoAvancadaRepository>()); services.AddScoped<IEducacaoEducacensoService>(sp => sp.GetRequiredService<EducacaoAvancadaRepository>()); services.AddScoped<IEducacaoAvaliacaoMagisterioService>(sp => sp.GetRequiredService<EducacaoAvancadaRepository>());
return services;
    }
}
