<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Sigov.Infrastructure</AssemblyName>
    <RootNamespace>Sigov.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Sigov.Application\Sigov.Application.csproj" />
    <ProjectReference Include="..\Sigov.Domain\Sigov.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>
</Project>
