create table if not exists sigov.entidade (
    id bigint generated always as identity primary key,
    nome varchar(250) not null,
    cnpj varchar(20) not null,
    codigo_ibge varchar(20) null,
    codigo_externo varchar(100) null,
    observacao text null,
    ativo boolean not null default true,
    is_deleted boolean not null default false,
    created_at timestamptz not null default now(),
    created_by bigint null,
    updated_at timestamptz null,
    updated_by bigint null,
    deleted_at timestamptz null,
    deleted_by bigint null,
    correlation_id uuid null
);

create table if not exists sigov.exercicio (
    id bigint generated always as identity primary key,
    entidade_id bigint not null references sigov.entidade(id),
    ano integer not null check (ano >= 1900),
    data_inicio date not null,
    data_fim date not null,
    codigo_externo varchar(100) null,
    observacao text null,
    ativo boolean not null default true,
    is_deleted boolean not null default false,
    created_at timestamptz not null default now(),
    created_by bigint null,
    updated_at timestamptz null,
    updated_by bigint null,
    deleted_at timestamptz null,
    deleted_by bigint null,
    correlation_id uuid null,
    unique (entidade_id, ano)
);

create table if not exists sigov.unidade_organizacional (
    id bigint generated always as identity primary key,
    entidade_id bigint null references sigov.entidade(id),
    exercicio_id bigint null references sigov.exercicio(id),
    unidade_pai_id bigint null references sigov.unidade_organizacional(id),
    nome varchar(250) not null,
    sigla varchar(30) null,
    codigo_externo varchar(100) null,
    observacao text null,
    ativo boolean not null default true,
    is_deleted boolean not null default false,
    created_at timestamptz not null default now(),
    created_by bigint null,
    updated_at timestamptz null,
    updated_by bigint null,
    deleted_at timestamptz null,
    deleted_by bigint null,
    correlation_id uuid null
);

create table if not exists sigov.pessoa (
    id bigint generated always as identity primary key,
    entidade_id bigint null references sigov.entidade(id),
    exercicio_id bigint null references sigov.exercicio(id),
    tipo_pessoa varchar(1) not null check (tipo_pessoa in ('F', 'J')),
    nome varchar(250) not null,
    nome_social varchar(250) null,
    documento varchar(20) null,
    classificacao_lgpd varchar(50) not null default 'DADO_PESSOAL',
    codigo_externo varchar(100) null,
    observacao text null,
    ativo boolean not null default true,
    is_deleted boolean not null default false,
    created_at timestamptz not null default now(),
    created_by bigint null,
    updated_at timestamptz null,
    updated_by bigint null,
    deleted_at timestamptz null,
    deleted_by bigint null,
    correlation_id uuid null
);

create table if not exists sigov.pessoa_fisica (
    id bigint generated always as identity primary key,
    entidade_id bigint null references sigov.entidade(id),
    exercicio_id bigint null references sigov.exercicio(id),
    pessoa_id bigint not null unique references sigov.pessoa(id),
    cpf varchar(20) not null,
    data_nascimento date null,
    nome_mae varchar(250) null,
    codigo_externo varchar(100) null,
    observacao text null,
    ativo boolean not null default true,
    is_deleted boolean not null default false,
    created_at timestamptz not null default now(),
    created_by bigint null,
    updated_at timestamptz null,
    updated_by bigint null,
    deleted_at timestamptz null,
    deleted_by bigint null,
    correlation_id uuid null
);

create table if not exists sigov.pessoa_juridica (
    id bigint generated always as identity primary key,
    entidade_id bigint null references sigov.entidade(id),
    exercicio_id bigint null references sigov.exercicio(id),
    pessoa_id bigint not null unique references sigov.pessoa(id),
    cnpj varchar(20) not null,
    razao_social varchar(250) not null,
    nome_fantasia varchar(250) null,
    codigo_externo varchar(100) null,
    observacao text null,
    ativo boolean not null default true,
    is_deleted boolean not null default false,
    created_at timestamptz not null default now(),
    created_by bigint null,
    updated_at timestamptz null,
    updated_by bigint null,
    deleted_at timestamptz null,
    deleted_by bigint null,
    correlation_id uuid null
);

create table if not exists sigov.endereco (
    id bigint generated always as identity primary key,
    entidade_id bigint null references sigov.entidade(id),
    exercicio_id bigint null references sigov.exercicio(id),
    pessoa_id bigint null references sigov.pessoa(id),
    logradouro varchar(250) not null,
    numero varchar(30) null,
    complemento varchar(100) null,
    bairro varchar(120) null,
    municipio varchar(120) not null,
    uf varchar(2) not null,
    cep varchar(12) null,
    codigo_externo varchar(100) null,
    observacao text null,
    ativo boolean not null default true,
    is_deleted boolean not null default false,
    created_at timestamptz not null default now(),
    created_by bigint null,
    updated_at timestamptz null,
    updated_by bigint null,
    deleted_at timestamptz null,
    deleted_by bigint null,
    correlation_id uuid null
);

create table if not exists sigov.contato (
    id bigint generated always as identity primary key,
    entidade_id bigint null references sigov.entidade(id),
    exercicio_id bigint null references sigov.exercicio(id),
    pessoa_id bigint null references sigov.pessoa(id),
    tipo varchar(30) not null,
    valor varchar(250) not null,
    principal boolean not null default false,
    codigo_externo varchar(100) null,
    observacao text null,
    ativo boolean not null default true,
    is_deleted boolean not null default false,
    created_at timestamptz not null default now(),
    created_by bigint null,
    updated_at timestamptz null,
    updated_by bigint null,
    deleted_at timestamptz null,
    deleted_by bigint null,
    correlation_id uuid null
);

create table if not exists sigov.campo_personalizado_def (
    id bigint generated always as identity primary key,
    entidade_id bigint null references sigov.entidade(id),
    exercicio_id bigint null references sigov.exercicio(id),
    contexto varchar(100) not null,
    nome varchar(120) not null,
    tipo varchar(50) not null,
    obrigatorio boolean not null default false,
    codigo_externo varchar(100) null,
    observacao text null,
    ativo boolean not null default true,
    is_deleted boolean not null default false,
    created_at timestamptz not null default now(),
    created_by bigint null,
    updated_at timestamptz null,
    updated_by bigint null,
    deleted_at timestamptz null,
    deleted_by bigint null,
    correlation_id uuid null
);

create table if not exists sigov.campo_personalizado_valor (
    id bigint generated always as identity primary key,
    entidade_id bigint null references sigov.entidade(id),
    exercicio_id bigint null references sigov.exercicio(id),
    campo_id bigint not null references sigov.campo_personalizado_def(id),
    registro_id bigint not null,
    valor text null,
    codigo_externo varchar(100) null,
    observacao text null,
    ativo boolean not null default true,
    is_deleted boolean not null default false,
    created_at timestamptz not null default now(),
    created_by bigint null,
    updated_at timestamptz null,
    updated_by bigint null,
    deleted_at timestamptz null,
    deleted_by bigint null,
    correlation_id uuid null
);

create table if not exists sigov.notificacao (
    id bigint generated always as identity primary key,
    entidade_id bigint null references sigov.entidade(id),
    exercicio_id bigint null references sigov.exercicio(id),
    destinatario_usuario_id bigint null,
    titulo varchar(150) not null,
    mensagem text not null,
    lida boolean not null default false,
    codigo_externo varchar(100) null,
    observacao text null,
    ativo boolean not null default true,
    is_deleted boolean not null default false,
    created_at timestamptz not null default now(),
    created_by bigint null,
    updated_at timestamptz null,
    updated_by bigint null,
    deleted_at timestamptz null,
    deleted_by bigint null,
    correlation_id uuid null
);

create table if not exists sigov.tarefa (
    id bigint generated always as identity primary key,
    entidade_id bigint null references sigov.entidade(id),
    exercicio_id bigint null references sigov.exercicio(id),
    titulo varchar(150) not null,
    descricao text null,
    status varchar(30) not null default 'PENDENTE',
    data_limite timestamptz null,
    codigo_externo varchar(100) null,
    observacao text null,
    ativo boolean not null default true,
    is_deleted boolean not null default false,
    created_at timestamptz not null default now(),
    created_by bigint null,
    updated_at timestamptz null,
    updated_by bigint null,
    deleted_at timestamptz null,
    deleted_by bigint null,
    correlation_id uuid null
);

create table if not exists sigov.agenda_obrigacao (
    id bigint generated always as identity primary key,
    entidade_id bigint null references sigov.entidade(id),
    exercicio_id bigint null references sigov.exercicio(id),
    titulo varchar(150) not null,
    data_vencimento date not null,
    modulo varchar(60) not null,
    codigo_externo varchar(100) null,
    observacao text null,
    ativo boolean not null default true,
    is_deleted boolean not null default false,
    created_at timestamptz not null default now(),
    created_by bigint null,
    updated_at timestamptz null,
    updated_by bigint null,
    deleted_at timestamptz null,
    deleted_by bigint null,
    correlation_id uuid null
);
