-- RC50.32 - Ponto, Ferias/Afastamentos e Portal do Servidor (idempotente)
create schema if not exists sigov;

create or replace function sigov.rc50_32_create_rh_table(p_table text) returns void language plpgsql as $$
begin
 execute format('create table if not exists sigov.%I (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null, entidade_id bigint null, exercicio_id bigint null, servidor_id bigint null,
  usuario_id bigint null, competencia date null, periodo_inicio date null, periodo_fim date null,
  data_referencia date null, tipo varchar(60) null, status varchar(40) not null default ''RASCUNHO'',
  motivo text null, justificativa text null, descricao text null, resposta text null,
  ativo boolean not null default true, is_deleted boolean not null default false,
  created_at timestamptz not null default now(), updated_at timestamptz null, deleted_at timestamptz null,
  created_by bigint null, updated_by bigint null, deleted_by bigint null,
  auditoria jsonb not null default ''{}''::jsonb, dados jsonb not null default ''{}''::jsonb,
  correlation_id uuid null,
  constraint %I check (periodo_fim is null or periodo_inicio is null or periodo_fim >= periodo_inicio)
 )', p_table, 'ck_' || p_table || '_periodo');
 execute format('create index if not exists %I on sigov.%I (tenant_id)', 'ix_'||p_table||'_tenant', p_table);
 execute format('create index if not exists %I on sigov.%I (tenant_id,is_deleted)', 'ix_'||p_table||'_tenant_deleted', p_table);
 execute format('create index if not exists %I on sigov.%I (servidor_id)', 'ix_'||p_table||'_servidor', p_table);
 execute format('create index if not exists %I on sigov.%I (status)', 'ix_'||p_table||'_status', p_table);
end $$;

select sigov.rc50_32_create_rh_table(t) from unnest(array[
 'rh_jornada','rh_escala','rh_escala_servidor','rh_ponto_registro','rh_ponto_justificativa',
 'rh_ponto_apuracao','rh_ponto_apuracao_item','rh_ponto_homologacao','rh_ponto_integracao_folha','rh_ponto_evento',
 'rh_ferias_periodo_aquisitivo','rh_ferias_programacao','rh_ferias_solicitacao','rh_ferias_historico',
 'rh_afastamento_tipo','rh_afastamento','rh_afastamento_historico','rh_afastamento_impacto_folha','rh_afastamento_impacto_ponto',
 'rh_portal_usuario','rh_portal_acesso','rh_portal_solicitacao','rh_portal_solicitacao_historico',
 'rh_portal_atualizacao_cadastral','rh_portal_comprovante','rh_portal_mensagem','rh_evento_integracao_folha'
]) t;

drop function sigov.rc50_32_create_rh_table(text);

create unique index if not exists ux_rh_ponto_registro_batida on sigov.rh_ponto_registro(tenant_id,servidor_id,(dados->>'dataHora'),(dados->>'tipo')) where is_deleted=false;
create unique index if not exists ux_rh_ponto_integracao_origem on sigov.rh_ponto_integracao_folha(tenant_id,(dados->>'apuracaoId'),(dados->>'evento')) where is_deleted=false;
create unique index if not exists ux_rh_evento_integracao_origem on sigov.rh_evento_integracao_folha(tenant_id,(dados->>'origemModulo'),(dados->>'origemTipo'),(dados->>'origemId'),(dados->>'eventoId')) where is_deleted=false;
create index if not exists ix_rh_ponto_registro_data on sigov.rh_ponto_registro(data_referencia);
create index if not exists ix_rh_ponto_apuracao_competencia on sigov.rh_ponto_apuracao(competencia);

-- compatibilidade: tabelas legadas permanecem intactas; as novas origens mantêm o id legado no JSON dados.
comment on table sigov.rh_ponto_registro is 'RC50.32: batidas reais, isoladas por tenant; compatível com sigov.ponto via dados.legacyId';
comment on table sigov.rh_ferias_programacao is 'RC50.32: workflow de férias; compatível com sigov.ferias via dados.legacyId';
comment on table sigov.rh_afastamento is 'RC50.32: afastamentos com dados médicos somente em detalhe autorizado';
