with seed(modulo, recurso, acao, chave, descricao, ativo) as (
  values
  ('agro','produtor','visualizar','agro.produtor.visualizar','Visualizar produtores rurais.',true),('agro','produtor','criar','agro.produtor.criar','Criar produtores rurais.',true),('agro','produtor','editar','agro.produtor.editar','Editar produtores rurais.',true),('agro','produtor','excluir','agro.produtor.excluir','Excluir produtores rurais.',true),('agro','produtor','visualizar_dados_completos','agro.produtor.visualizar_dados_completos','Visualizar dados pessoais completos de produtores rurais.',true),
('agro','propriedade','visualizar','agro.propriedade.visualizar','Visualizar propriedades rurais.',true),('agro','propriedade','criar','agro.propriedade.criar','Criar propriedades rurais.',true),('agro','propriedade','editar','agro.propriedade.editar','Editar propriedades rurais.',true),('agro','propriedade','excluir','agro.propriedade.excluir','Excluir propriedades rurais.',true),
('agro','talhao','visualizar','agro.talhao.visualizar','Visualizar talhões.',true),('agro','talhao','criar','agro.talhao.criar','Criar talhões.',true),('agro','talhao','editar','agro.talhao.editar','Editar talhões.',true),
('agro','cultura','visualizar','agro.cultura.visualizar','Visualizar culturas.',true),('agro','cultura','criar','agro.cultura.criar','Criar culturas.',true),('agro','cultura','editar','agro.cultura.editar','Editar culturas.',true),
('agro','safra','visualizar','agro.safra.visualizar','Visualizar safras.',true),('agro','safra','criar','agro.safra.criar','Criar safras.',true),('agro','safra','editar','agro.safra.editar','Editar safras.',true),
('agro','producao','visualizar','agro.producao.visualizar','Visualizar produção agrícola.',true),('agro','producao','criar','agro.producao.criar','Criar produção agrícola.',true),('agro','producao','editar','agro.producao.editar','Editar produção agrícola.',true),('agro','producao','excluir','agro.producao.excluir','Excluir produção agrícola.',true)
), atualizadas as (
  update sigov.permissao p
     set descricao = s.descricao,
         ativo = true,
         is_deleted = false,
         updated_at = now()
    from seed s
   where p.chave = s.chave
   returning p.chave
)
insert into sigov.permissao (modulo, recurso, acao, chave, descricao, ativo)
select s.modulo, s.recurso, s.acao, s.chave, s.descricao, s.ativo
  from seed s
 where not exists (select 1 from sigov.permissao p where p.chave = s.chave);

insert into sigov.perfil_permissao (tenant_id, perfil_acesso_id, permissao_id)
select coalesce(pa.tenant_id, t.id), pa.id, p.id from sigov.perfil_acesso pa
cross join lateral (select id from sigov.tenant where slug = 'plataforma' order by id limit 1) t join sigov.permissao p on p.modulo='agro' and p.ativo=true and p.is_deleted=false where pa.ativo=true and pa.is_deleted=false and (coalesce(pa.codigo_externo, upper(replace(pa.nome,' ','_'))) in ('ADMINISTRADOR_GERAL','ADMINISTRADOR_TENANT','ADMINISTRADOR_ENTIDADE','COORDENADOR','DIRETOR','OPERADOR','AUDITOR','SUPORTE') or upper(pa.nome) like '%ADMINISTRADOR%') and not exists (select 1 from sigov.perfil_permissao pp where pp.tenant_id = coalesce(pa.tenant_id, t.id) and pp.perfil_acesso_id = pa.id and pp.permissao_id = p.id);

create table if not exists sigov.agro_produtor (id bigint generated always as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), pessoa_id bigint not null references sigov.pessoa(id), codigo_produtor varchar(80) not null, tipo_produtor varchar(80) not null, inscricao_estadual varchar(80) null, inscricao_municipal varchar(80) null, numero_produtor_rural varchar(80) null, associacao_cooperativa varchar(250) null, principal_atividade varchar(150) null, situacao varchar(40) not null, data_cadastro date not null default current_date, observacao text null, ativo boolean not null default true, is_deleted boolean not null default false, created_at timestamptz not null default now(), created_by bigint null, updated_at timestamptz null, updated_by bigint null, deleted_at timestamptz null, deleted_by bigint null, correlation_id uuid null, constraint uk_agro_produtor_tenant_entidade_codigo unique(tenant_id,entidade_id,codigo_produtor), constraint uk_agro_produtor_tenant_entidade_pessoa unique(tenant_id,entidade_id,pessoa_id));
create table if not exists sigov.agro_propriedade (id bigint generated always as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), produtor_id bigint not null references sigov.agro_produtor(id), codigo_propriedade varchar(80) not null, nome varchar(250) not null, localidade varchar(250) null, comunidade varchar(250) null, endereco_json jsonb not null default '{}'::jsonb, area_total_ha numeric(18,4) null, area_produtiva_ha numeric(18,4) null, area_preservacao_ha numeric(18,4) null, latitude numeric(12,8) null, longitude numeric(12,8) null, geojson jsonb null, situacao varchar(40) not null, observacao text null, ativo boolean not null default true, is_deleted boolean not null default false, created_at timestamptz not null default now(), created_by bigint null, updated_at timestamptz null, updated_by bigint null, deleted_at timestamptz null, deleted_by bigint null, correlation_id uuid null, constraint uk_agro_propriedade_tenant_entidade_codigo unique(tenant_id,entidade_id,codigo_propriedade), constraint ck_agro_propriedade_areas check ((area_total_ha is null or area_total_ha >= 0) and (area_produtiva_ha is null or area_produtiva_ha >= 0) and (area_total_ha is null or area_produtiva_ha is null or area_produtiva_ha <= area_total_ha)), constraint ck_agro_propriedade_coords check ((latitude is null and longitude is null) or (latitude between -90 and 90 and longitude between -180 and 180)));
create table if not exists sigov.agro_imovel_rural (id bigint generated always as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), propriedade_id bigint not null references sigov.agro_propriedade(id), car varchar(120) null, ccir varchar(120) null, incra varchar(120) null, itr_nirf varchar(120) null, matricula_imovel varchar(120) null, cartorio varchar(250) null, area_registrada_ha numeric(18,4) null, situacao_ambiental varchar(80) null, status_regularizacao varchar(80) null, dados_json jsonb not null default '{}'::jsonb, ativo boolean not null default true, is_deleted boolean not null default false, created_at timestamptz not null default now(), created_by bigint null, updated_at timestamptz null, updated_by bigint null, deleted_at timestamptz null, deleted_by bigint null, correlation_id uuid null);
create table if not exists sigov.agro_documento_rural (id bigint generated always as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), produtor_id bigint null references sigov.agro_produtor(id), propriedade_id bigint null references sigov.agro_propriedade(id), tipo_documento varchar(80) not null, numero varchar(150) null, validade date null, arquivo_id bigint null, metadados jsonb not null default '{}'::jsonb, ativo boolean not null default true, is_deleted boolean not null default false, created_at timestamptz not null default now(), created_by bigint null, updated_at timestamptz null, updated_by bigint null, deleted_at timestamptz null, deleted_by bigint null, correlation_id uuid null);
create table if not exists sigov.agro_talhao (id bigint generated always as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), propriedade_id bigint not null references sigov.agro_propriedade(id), codigo varchar(80) not null, nome varchar(150) not null, area_ha numeric(18,4) not null, tipo_solo varchar(120) null, irrigado boolean not null default false, latitude numeric(12,8) null, longitude numeric(12,8) null, geojson jsonb null, situacao varchar(40) not null, ativo boolean not null default true, is_deleted boolean not null default false, created_at timestamptz not null default now(), created_by bigint null, updated_at timestamptz null, updated_by bigint null, deleted_at timestamptz null, deleted_by bigint null, correlation_id uuid null, constraint ck_agro_talhao_area check (area_ha > 0), constraint ck_agro_talhao_coords check ((latitude is null and longitude is null) or (latitude between -90 and 90 and longitude between -180 and 180)));
create table if not exists sigov.agro_cultura (id bigint generated always as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), codigo varchar(80) not null, nome varchar(150) not null, tipo_cultura varchar(80) not null, ciclo_dias int null, unidade_medida varchar(40) not null, ativo boolean not null default true, is_deleted boolean not null default false, created_at timestamptz not null default now(), created_by bigint null, updated_at timestamptz null, updated_by bigint null, deleted_at timestamptz null, deleted_by bigint null, correlation_id uuid null, constraint uk_agro_cultura_tenant_entidade_codigo unique(tenant_id,entidade_id,codigo), constraint ck_agro_cultura_ciclo check (ciclo_dias is null or ciclo_dias >= 0));
create table if not exists sigov.agro_safra (id bigint generated always as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), exercicio_id bigint null references sigov.exercicio(id), codigo varchar(80) not null, nome varchar(150) not null, ano_inicio int not null, ano_fim int not null, data_inicio date null, data_fim date null, status varchar(40) not null, ativo boolean not null default true, is_deleted boolean not null default false, created_at timestamptz not null default now(), created_by bigint null, updated_at timestamptz null, updated_by bigint null, deleted_at timestamptz null, deleted_by bigint null, correlation_id uuid null, constraint uk_agro_safra_tenant_entidade_codigo unique(tenant_id,entidade_id,codigo), constraint ck_agro_safra_periodo check (ano_fim >= ano_inicio and (data_inicio is null or data_fim is null or data_fim >= data_inicio)));
create table if not exists sigov.agro_producao_agricola (id bigint generated always as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), exercicio_id bigint null references sigov.exercicio(id), produtor_id bigint not null references sigov.agro_produtor(id), propriedade_id bigint null references sigov.agro_propriedade(id), talhao_id bigint null references sigov.agro_talhao(id), cultura_id bigint not null references sigov.agro_cultura(id), safra_id bigint null references sigov.agro_safra(id), area_plantada_ha numeric(18,4) not null default 0, data_plantio date null, data_colheita_prevista date null, data_colheita_real date null, producao_estimada numeric(18,4) null, producao_realizada numeric(18,4) null, unidade_medida varchar(40) not null, produtividade numeric(18,4) null, status varchar(40) not null, observacao text null, ativo boolean not null default true, is_deleted boolean not null default false, created_at timestamptz not null default now(), created_by bigint null, updated_at timestamptz null, updated_by bigint null, deleted_at timestamptz null, deleted_by bigint null, correlation_id uuid null, constraint ck_agro_producao_valores check (area_plantada_ha >= 0 and (producao_estimada is null or producao_estimada >= 0) and (producao_realizada is null or producao_realizada >= 0)), constraint ck_agro_producao_datas check (data_plantio is null or data_colheita_real is null or data_colheita_real >= data_plantio));

create index if not exists idx_agro_produtor_tenant_codigo on sigov.agro_produtor(tenant_id,entidade_id,codigo_produtor) where is_deleted=false;
create index if not exists idx_agro_produtor_tenant_pessoa on sigov.agro_produtor(tenant_id,entidade_id,pessoa_id) where is_deleted=false;
create index if not exists idx_agro_propriedade_tenant_codigo on sigov.agro_propriedade(tenant_id,entidade_id,codigo_propriedade) where is_deleted=false;
create index if not exists idx_agro_propriedade_tenant_produtor on sigov.agro_propriedade(tenant_id,entidade_id,produtor_id) where is_deleted=false;
create index if not exists idx_agro_talhao_tenant_propriedade on sigov.agro_talhao(tenant_id,entidade_id,propriedade_id) where is_deleted=false;
create index if not exists idx_agro_cultura_tenant_codigo on sigov.agro_cultura(tenant_id,entidade_id,codigo) where is_deleted=false;
create index if not exists idx_agro_safra_tenant_codigo on sigov.agro_safra(tenant_id,entidade_id,codigo) where is_deleted=false;
create index if not exists idx_agro_producao_tenant_produtor on sigov.agro_producao_agricola(tenant_id,entidade_id,produtor_id) where is_deleted=false;
create index if not exists idx_agro_producao_tenant_cultura on sigov.agro_producao_agricola(tenant_id,entidade_id,cultura_id) where is_deleted=false;

insert into sigov.agro_cultura (tenant_id, entidade_id, codigo, nome, tipo_cultura, unidade_medida, created_by)
select t.id, e.id, x.codigo, x.nome, x.tipo, x.unidade, null from sigov.tenant t join sigov.entidade e on e.tenant_id=t.id cross join (values ('MILHO','Milho','GRAOS','kg'),('FEIJAO','Feijão','GRAOS','kg'),('MANDIOCA','Mandioca','RAIZES_TUBERCULOS','kg'),('ARROZ','Arroz','GRAOS','kg'),('HORTALICAS','Hortaliças','HORTALICAS','kg'),('FRUTAS','Frutas','FRUTAS','kg'),('PASTAGEM','Pastagem','PASTAGEM','ha')) as x(codigo,nome,tipo,unidade) where t.ambiente='Development' and not exists (select 1 from sigov.agro_cultura c where c.tenant_id=t.id and c.entidade_id=e.id and c.codigo=x.codigo and c.is_deleted=false);

create or replace view sigov.vw_agro_dashboard as
with chaves as (select tenant_id, entidade_id from sigov.agro_geo_camada where is_deleted=false union select tenant_id, entidade_id from sigov.agro_geo_feicao where is_deleted=false union select tenant_id, entidade_id from sigov.agro_evento union select tenant_id, entidade_id from sigov.agro_produtor where is_deleted=false union select tenant_id, entidade_id from sigov.agro_propriedade where is_deleted=false union select tenant_id, entidade_id from sigov.agro_talhao where is_deleted=false union select tenant_id, entidade_id from sigov.agro_cultura where is_deleted=false union select tenant_id, entidade_id from sigov.agro_safra where is_deleted=false union select tenant_id, entidade_id from sigov.agro_producao_agricola where is_deleted=false),
camadas as (select tenant_id, entidade_id, count(*)::bigint total_camadas from sigov.agro_geo_camada where is_deleted=false group by tenant_id, entidade_id), feicoes as (select tenant_id, entidade_id, count(*)::bigint total_feicoes from sigov.agro_geo_feicao where is_deleted=false group by tenant_id, entidade_id), eventos as (select tenant_id, entidade_id, count(*)::bigint total_eventos from sigov.agro_evento group by tenant_id, entidade_id), produtores as (select tenant_id, entidade_id, count(*)::bigint total_produtores, count(*) filter (where ativo)::bigint produtores_ativos from sigov.agro_produtor where is_deleted=false group by tenant_id, entidade_id), propriedades as (select tenant_id, entidade_id, count(*)::bigint total_propriedades, coalesce(sum(area_total_ha),0)::numeric(18,4) area_total_mapeada, coalesce(sum(area_produtiva_ha),0)::numeric(18,4) area_produtiva from sigov.agro_propriedade where is_deleted=false group by tenant_id, entidade_id), talhoes as (select tenant_id, entidade_id, count(*)::bigint total_talhoes from sigov.agro_talhao where is_deleted=false group by tenant_id, entidade_id), culturas as (select tenant_id, entidade_id, count(*)::bigint culturas_cadastradas from sigov.agro_cultura where is_deleted=false group by tenant_id, entidade_id), safras as (select tenant_id, entidade_id, count(*) filter (where status='ATIVA' or status='Ativa')::bigint safras_ativas from sigov.agro_safra where is_deleted=false group by tenant_id, entidade_id), producao as (select tenant_id, entidade_id, coalesce(sum(producao_estimada),0)::numeric(18,4) producao_estimada, coalesce(sum(producao_realizada),0)::numeric(18,4) producao_realizada from sigov.agro_producao_agricola where is_deleted=false group by tenant_id, entidade_id)
select k.tenant_id,k.entidade_id,coalesce(c.total_camadas,0)::bigint total_camadas,coalesce(f.total_feicoes,0)::bigint total_feicoes,coalesce(e.total_eventos,0)::bigint total_eventos,coalesce(p.total_produtores,0)::bigint total_produtores,coalesce(pr.total_propriedades,0)::bigint total_propriedades,0::bigint total_visitas,0::bigint total_servicos_maquina,0::bigint total_pontos_criticos,coalesce(p.produtores_ativos,0)::bigint produtores_ativos,coalesce(pr.area_total_mapeada,0)::numeric(18,4) area_total_mapeada,coalesce(pr.area_produtiva,0)::numeric(18,4) area_produtiva,coalesce(t.total_talhoes,0)::bigint total_talhoes,coalesce(cu.culturas_cadastradas,0)::bigint culturas_cadastradas,coalesce(s.safras_ativas,0)::bigint safras_ativas,coalesce(pa.producao_estimada,0)::numeric(18,4) producao_estimada,coalesce(pa.producao_realizada,0)::numeric(18,4) producao_realizada
from chaves k left join camadas c on c.tenant_id=k.tenant_id and c.entidade_id is not distinct from k.entidade_id left join feicoes f on f.tenant_id=k.tenant_id and f.entidade_id is not distinct from k.entidade_id left join eventos e on e.tenant_id=k.tenant_id and e.entidade_id is not distinct from k.entidade_id left join produtores p on p.tenant_id=k.tenant_id and p.entidade_id is not distinct from k.entidade_id left join propriedades pr on pr.tenant_id=k.tenant_id and pr.entidade_id is not distinct from k.entidade_id left join talhoes t on t.tenant_id=k.tenant_id and t.entidade_id is not distinct from k.entidade_id left join culturas cu on cu.tenant_id=k.tenant_id and cu.entidade_id is not distinct from k.entidade_id left join safras s on s.tenant_id=k.tenant_id and s.entidade_id is not distinct from k.entidade_id left join producao pa on pa.tenant_id=k.tenant_id and pa.entidade_id is not distinct from k.entidade_id;
