-- Agro Parte 4: programas, benefícios, insumos e patrulha mecanizada.
-- Schema único sigov; migration idempotente; sem schemas agro/rural/geo.

insert into sigov.feature_flag_def (codigo, nome, descricao, modulo, ativo)
values
('agro.programas_rurais','Programas rurais','Habilita programas rurais do Agro.','agro',true),
('agro.beneficios_rurais','Benefícios rurais','Habilita benefícios e concessões rurais.','agro',true),
('agro.insumos','Insumos Agro','Habilita insumos e distribuições rurais.','agro',true),
('agro.patrulha_mecanizada','Patrulha mecanizada','Habilita patrulha mecanizada rural.','agro',true),
('agro.maquinas','Máquinas rurais','Habilita máquinas e implementos rurais.','agro',true),
('agro.servicos_maquina','Serviços de máquinas','Habilita serviços de máquinas rurais.','agro',true)
on conflict (codigo) do update set nome=excluded.nome, descricao=excluded.descricao, modulo=excluded.modulo, ativo=true;

insert into sigov.permissao (modulo, recurso, acao, chave, descricao, ativo)
values
('agro','programa','visualizar','agro.programa.visualizar','Visualizar programas rurais.',true),('agro','programa','criar','agro.programa.criar','Criar programas rurais.',true),('agro','programa','editar','agro.programa.editar','Editar programas rurais.',true),('agro','programa','excluir','agro.programa.excluir','Excluir programas rurais.',true),
('agro','beneficio','visualizar','agro.beneficio.visualizar','Visualizar benefícios rurais.',true),('agro','beneficio','criar','agro.beneficio.criar','Criar benefícios rurais.',true),('agro','beneficio','editar','agro.beneficio.editar','Editar benefícios rurais.',true),('agro','beneficio','excluir','agro.beneficio.excluir','Excluir benefícios rurais.',true),('agro','beneficio','conceder','agro.beneficio.conceder','Solicitar concessões de benefício rural.',true),('agro','beneficio','autorizar','agro.beneficio.autorizar','Autorizar concessões de benefício rural.',true),('agro','beneficio','entregar','agro.beneficio.entregar','Entregar concessões de benefício rural.',true),('agro','beneficio','indeferir','agro.beneficio.indeferir','Indeferir concessões de benefício rural.',true),('agro','beneficio','cancelar','agro.beneficio.cancelar','Cancelar concessões de benefício rural.',true),
('agro','insumo','visualizar','agro.insumo.visualizar','Visualizar insumos Agro.',true),('agro','insumo','criar','agro.insumo.criar','Criar insumos Agro.',true),('agro','insumo','distribuir','agro.insumo.distribuir','Distribuir insumos Agro.',true),
('agro','maquina','visualizar','agro.maquina.visualizar','Visualizar máquinas rurais.',true),('agro','maquina','criar','agro.maquina.criar','Criar máquinas rurais.',true),('agro','maquina','editar','agro.maquina.editar','Editar máquinas rurais.',true),('agro','maquina','excluir','agro.maquina.excluir','Excluir máquinas rurais.',true),
('agro','implemento','visualizar','agro.implemento.visualizar','Visualizar implementos rurais.',true),('agro','implemento','criar','agro.implemento.criar','Criar implementos rurais.',true),
('agro','servico_maquina','visualizar','agro.servico_maquina.visualizar','Visualizar serviços de máquinas.',true),('agro','servico_maquina','criar','agro.servico_maquina.criar','Criar serviços de máquinas.',true),('agro','servico_maquina','editar','agro.servico_maquina.editar','Editar serviços de máquinas.',true),('agro','servico_maquina','agendar','agro.servico_maquina.agendar','Agendar serviços de máquinas.',true),('agro','servico_maquina','executar','agro.servico_maquina.executar','Executar serviços de máquinas.',true),('agro','servico_maquina','cancelar','agro.servico_maquina.cancelar','Cancelar serviços de máquinas.',true),('agro','servico_maquina','excluir','agro.servico_maquina.excluir','Excluir serviços de máquinas.',true)
on conflict (modulo, recurso, acao) do update set chave=excluded.chave, descricao=excluded.descricao, ativo=true;

insert into sigov.perfil_permissao (tenant_id, perfil_acesso_id, permissao_id)
select coalesce(pa.tenant_id, t.id), pa.id, p.id from sigov.perfil_acesso pa
cross join lateral (select id from sigov.tenant where slug = 'plataforma' order by id limit 1) t join sigov.permissao p on p.modulo='agro' and p.ativo=true and p.is_deleted=false
where pa.ativo=true and pa.is_deleted=false and coalesce(pa.codigo_externo, upper(replace(pa.nome,' ','_'))) in ('ADMINISTRADOR_GERAL','ADMINISTRADOR_TENANT','ADMINISTRADOR_ENTIDADE','COORDENADOR','DIRETOR','OPERADOR','AUDITOR','SUPORTE') and not exists (select 1 from sigov.perfil_permissao pp where pp.tenant_id = coalesce(pa.tenant_id, t.id) and pp.perfil_acesso_id = pa.id and pp.permissao_id = p.id);

insert into sigov.tenant_feature_flag (tenant_id, feature_flag_def_id, habilitado, ativo)
select t.id, f.id, true, true from sigov.tenant t join sigov.feature_flag_def f on f.modulo='agro' and f.codigo like 'agro.%' where t.ativo=true and t.is_deleted=false on conflict (tenant_id, feature_flag_def_id) do nothing;

create table if not exists sigov.agro_programa_rural (
 id bigint generated always as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), codigo varchar(80) not null, nome varchar(250) not null, tipo_programa varchar(100) not null, descricao text null, criterios_json jsonb not null default '{}'::jsonb, vigencia_inicio date null, vigencia_fim date null, ativo boolean not null default true, is_deleted boolean not null default false, created_at timestamptz not null default now(), created_by bigint null, updated_at timestamptz null, updated_by bigint null, deleted_at timestamptz null, deleted_by bigint null, correlation_id uuid null);
create table if not exists sigov.agro_beneficio_rural (
 id bigint generated always as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), programa_id bigint null references sigov.agro_programa_rural(id), codigo varchar(80) not null, nome varchar(250) not null, tipo_beneficio varchar(100) not null, unidade_medida varchar(40) null, valor_referencia numeric(18,2) null, quantidade_limite numeric(18,4) null, criterios_json jsonb not null default '{}'::jsonb, ativo boolean not null default true, is_deleted boolean not null default false, created_at timestamptz not null default now(), created_by bigint null, updated_at timestamptz null, updated_by bigint null, deleted_at timestamptz null, deleted_by bigint null, correlation_id uuid null);
create table if not exists sigov.agro_beneficio_concessao (
 id bigint generated always as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), exercicio_id bigint null references sigov.exercicio(id), beneficio_id bigint not null references sigov.agro_beneficio_rural(id), produtor_id bigint not null references sigov.agro_produtor(id), propriedade_id bigint null references sigov.agro_propriedade(id), numero varchar(80) not null, data_solicitacao date not null default current_date, data_concessao date null, quantidade numeric(18,4) null, valor numeric(18,2) null, status varchar(40) not null, autorizado_by bigint null references sigov.usuario(id), autorizado_at timestamptz null, entregue_by bigint null references sigov.usuario(id), entregue_at timestamptz null, observacao text null, ativo boolean not null default true, is_deleted boolean not null default false, created_at timestamptz not null default now(), created_by bigint null, updated_at timestamptz null, updated_by bigint null, deleted_at timestamptz null, deleted_by bigint null, correlation_id uuid null);
create table if not exists sigov.agro_insumo (
 id bigint generated always as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), codigo varchar(80) not null, nome varchar(250) not null, tipo_insumo varchar(100) not null, unidade_medida varchar(40) not null, controla_estoque boolean not null default false, produto_id bigint null, ativo boolean not null default true, is_deleted boolean not null default false, created_at timestamptz not null default now(), created_by bigint null, updated_at timestamptz null, updated_by bigint null, deleted_at timestamptz null, deleted_by bigint null, correlation_id uuid null);
create table if not exists sigov.agro_distribuicao_insumo (
 id bigint generated always as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), exercicio_id bigint null references sigov.exercicio(id), insumo_id bigint not null references sigov.agro_insumo(id), produtor_id bigint not null references sigov.agro_produtor(id), propriedade_id bigint null references sigov.agro_propriedade(id), programa_id bigint null references sigov.agro_programa_rural(id), beneficio_concessao_id bigint null references sigov.agro_beneficio_concessao(id), numero varchar(80) not null, data_distribuicao date not null default current_date, quantidade numeric(18,4) not null, valor_estimado numeric(18,2) null, status varchar(40) not null, entregue_by bigint null references sigov.usuario(id), observacao text null, ativo boolean not null default true, is_deleted boolean not null default false, created_at timestamptz not null default now(), created_by bigint null, updated_at timestamptz null, updated_by bigint null, deleted_at timestamptz null, deleted_by bigint null, correlation_id uuid null);
create table if not exists sigov.agro_maquina (
 id bigint generated always as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), patrimonio_bem_id bigint null, frota_veiculo_id bigint null, codigo varchar(80) not null, nome varchar(150) not null, tipo_maquina varchar(100) not null, placa varchar(20) null, horimetro_atual numeric(18,2) null, odometro_atual numeric(18,2) null, situacao varchar(40) not null, observacao text null, ativo boolean not null default true, is_deleted boolean not null default false, created_at timestamptz not null default now(), created_by bigint null, updated_at timestamptz null, updated_by bigint null, deleted_at timestamptz null, deleted_by bigint null, correlation_id uuid null);
create table if not exists sigov.agro_implemento (
 id bigint generated always as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), maquina_id bigint null references sigov.agro_maquina(id), codigo varchar(80) not null, nome varchar(150) not null, tipo_implemento varchar(100) not null, situacao varchar(40) not null, observacao text null, ativo boolean not null default true, is_deleted boolean not null default false, created_at timestamptz not null default now(), created_by bigint null, updated_at timestamptz null, updated_by bigint null, deleted_at timestamptz null, deleted_by bigint null, correlation_id uuid null);
create table if not exists sigov.agro_agenda_maquina (
 id bigint generated always as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), exercicio_id bigint null references sigov.exercicio(id), maquina_id bigint not null references sigov.agro_maquina(id), servico_maquina_id bigint null, data_inicio timestamptz not null, data_fim timestamptz not null, status varchar(40) not null, observacao text null, ativo boolean not null default true, is_deleted boolean not null default false, created_at timestamptz not null default now(), created_by bigint null, updated_at timestamptz null, updated_by bigint null, deleted_at timestamptz null, deleted_by bigint null, correlation_id uuid null);
create table if not exists sigov.agro_servico_maquina (
 id bigint generated always as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), exercicio_id bigint null references sigov.exercicio(id), produtor_id bigint not null references sigov.agro_produtor(id), propriedade_id bigint null references sigov.agro_propriedade(id), maquina_id bigint null references sigov.agro_maquina(id), implemento_id bigint null references sigov.agro_implemento(id), numero varchar(80) not null, tipo_servico varchar(100) not null, data_solicitacao date not null default current_date, data_agendada date null, data_execucao date null, horas_trabalhadas numeric(18,4) null, area_atendida_ha numeric(18,4) null, horimetro_inicial numeric(18,2) null, horimetro_final numeric(18,2) null, odometro_inicial numeric(18,2) null, odometro_final numeric(18,2) null, valor_estimado numeric(18,2) null, valor_cobrado numeric(18,2) null, status varchar(40) not null, operador_usuario_id bigint null references sigov.usuario(id), observacao text null, ativo boolean not null default true, is_deleted boolean not null default false, created_at timestamptz not null default now(), created_by bigint null, updated_at timestamptz null, updated_by bigint null, deleted_at timestamptz null, deleted_by bigint null, correlation_id uuid null);

do $$ begin if not exists (select 1 from pg_constraint where conname='fk_agro_agenda_servico_maquina') then alter table sigov.agro_agenda_maquina add constraint fk_agro_agenda_servico_maquina foreign key (servico_maquina_id) references sigov.agro_servico_maquina(id) not valid; end if; end $$;

create index if not exists idx_agro_programa_tenant_codigo on sigov.agro_programa_rural(tenant_id,entidade_id,codigo) where is_deleted=false;
create index if not exists idx_agro_beneficio_tenant_codigo on sigov.agro_beneficio_rural(tenant_id,entidade_id,codigo) where is_deleted=false;
create index if not exists idx_agro_concessao_tenant_produtor on sigov.agro_beneficio_concessao(tenant_id,entidade_id,produtor_id) where is_deleted=false;
create index if not exists idx_agro_concessao_tenant_status on sigov.agro_beneficio_concessao(tenant_id,entidade_id,status) where is_deleted=false;
create index if not exists idx_agro_insumo_tenant_codigo on sigov.agro_insumo(tenant_id,entidade_id,codigo) where is_deleted=false;
create index if not exists idx_agro_distribuicao_tenant_produtor on sigov.agro_distribuicao_insumo(tenant_id,entidade_id,produtor_id) where is_deleted=false;
create index if not exists idx_agro_maquina_tenant_codigo on sigov.agro_maquina(tenant_id,entidade_id,codigo) where is_deleted=false;
create index if not exists idx_agro_implemento_tenant_codigo on sigov.agro_implemento(tenant_id,entidade_id,codigo) where is_deleted=false;
create index if not exists idx_agro_agenda_maquina_tenant_maquina on sigov.agro_agenda_maquina(tenant_id,entidade_id,maquina_id,data_inicio,data_fim) where is_deleted=false;
create index if not exists idx_agro_servico_maquina_tenant_numero on sigov.agro_servico_maquina(tenant_id,entidade_id,numero) where is_deleted=false;
create index if not exists idx_agro_servico_maquina_tenant_produtor on sigov.agro_servico_maquina(tenant_id,entidade_id,produtor_id) where is_deleted=false;
create index if not exists idx_agro_servico_maquina_tenant_status on sigov.agro_servico_maquina(tenant_id,entidade_id,status) where is_deleted=false;

insert into sigov.agro_programa_rural (tenant_id, entidade_id, codigo, nome, tipo_programa, descricao, created_by)
select t.id, e.id, x.codigo, x.nome, x.tipo, 'Seed Development Agro Parte 4', null from sigov.tenant t join sigov.entidade e on e.tenant_id=t.id cross join (values ('CORTE_TERRA','Corte de Terra','CORTE_TERRA'),('DIST_SEMENTES','Distribuição de Sementes','DISTRIBUICAO_SEMENTES'),('DIST_MUDAS','Distribuição de Mudas','DISTRIBUICAO_MUDAS'),('PATRULHA_MEC','Patrulha Mecanizada','PATRULHA_MECANIZADA')) as x(codigo,nome,tipo)
where t.ambiente='Development' and not exists (select 1 from sigov.agro_programa_rural p where p.tenant_id=t.id and p.entidade_id=e.id and p.codigo=x.codigo and p.is_deleted=false);

insert into sigov.agro_insumo (tenant_id, entidade_id, codigo, nome, tipo_insumo, unidade_medida, controla_estoque, created_by)
select t.id, e.id, x.codigo, x.nome, x.tipo, x.unidade, false, null from sigov.tenant t join sigov.entidade e on e.tenant_id=t.id cross join (values ('SEMENTE','Semente','SEMENTE','kg'),('MUDA','Muda','MUDA','un'),('CALCARIO','Calcário','CALCARIO','kg'),('ADUBO','Adubo','ADUBO','kg')) as x(codigo,nome,tipo,unidade)
where t.ambiente='Development' and not exists (select 1 from sigov.agro_insumo i where i.tenant_id=t.id and i.entidade_id=e.id and i.codigo=x.codigo and i.is_deleted=false);

create or replace view sigov.vw_agro_dashboard as
with chaves as (
 select tenant_id, entidade_id from sigov.agro_geo_camada where is_deleted=false union select tenant_id, entidade_id from sigov.agro_geo_feicao where is_deleted=false union select tenant_id, entidade_id from sigov.agro_evento union select tenant_id, entidade_id from sigov.agro_produtor where is_deleted=false union select tenant_id, entidade_id from sigov.agro_propriedade where is_deleted=false union select tenant_id, entidade_id from sigov.agro_talhao where is_deleted=false union select tenant_id, entidade_id from sigov.agro_cultura where is_deleted=false union select tenant_id, entidade_id from sigov.agro_safra where is_deleted=false union select tenant_id, entidade_id from sigov.agro_producao_agricola where is_deleted=false union select tenant_id, entidade_id from sigov.agro_programa_rural where is_deleted=false union select tenant_id, entidade_id from sigov.agro_beneficio_rural where is_deleted=false union select tenant_id, entidade_id from sigov.agro_maquina where is_deleted=false union select tenant_id, entidade_id from sigov.agro_servico_maquina where is_deleted=false
),
camadas as (select tenant_id, entidade_id, count(*)::bigint total_camadas from sigov.agro_geo_camada where is_deleted=false group by tenant_id, entidade_id),
feicoes as (select tenant_id, entidade_id, count(*)::bigint total_feicoes from sigov.agro_geo_feicao where is_deleted=false group by tenant_id, entidade_id),
eventos as (select tenant_id, entidade_id, count(*)::bigint total_eventos from sigov.agro_evento group by tenant_id, entidade_id),
produtores as (select tenant_id, entidade_id, count(*)::bigint total_produtores, count(*) filter (where ativo)::bigint produtores_ativos from sigov.agro_produtor where is_deleted=false group by tenant_id, entidade_id),
propriedades as (select tenant_id, entidade_id, count(*)::bigint total_propriedades, coalesce(sum(area_total_ha),0)::numeric(18,4) area_total_mapeada, coalesce(sum(area_produtiva_ha),0)::numeric(18,4) area_produtiva from sigov.agro_propriedade where is_deleted=false group by tenant_id, entidade_id),
talhoes as (select tenant_id, entidade_id, count(*)::bigint total_talhoes from sigov.agro_talhao where is_deleted=false group by tenant_id, entidade_id),
culturas as (select tenant_id, entidade_id, count(*)::bigint culturas_cadastradas from sigov.agro_cultura where is_deleted=false group by tenant_id, entidade_id),
safras as (select tenant_id, entidade_id, count(*) filter (where status='ATIVA' or status='Ativa')::bigint safras_ativas from sigov.agro_safra where is_deleted=false group by tenant_id, entidade_id),
producao as (select tenant_id, entidade_id, coalesce(sum(producao_estimada),0)::numeric(18,4) producao_estimada, coalesce(sum(producao_realizada),0)::numeric(18,4) producao_realizada from sigov.agro_producao_agricola where is_deleted=false group by tenant_id, entidade_id),
programas as (select tenant_id, entidade_id, count(*) filter (where ativo)::bigint total_programas from sigov.agro_programa_rural where is_deleted=false group by tenant_id, entidade_id),
beneficios as (select tenant_id, entidade_id, count(*)::bigint total_beneficios from sigov.agro_beneficio_rural where is_deleted=false group by tenant_id, entidade_id),
concessoes as (select tenant_id, entidade_id, count(*) filter (where status='CONCEDIDO')::bigint beneficios_concedidos_mes, count(*) filter (where status='SOLICITADO')::bigint concessoes_solicitadas, count(*) filter (where status='AUTORIZADO')::bigint concessoes_autorizadas, count(*) filter (where status='ENTREGUE' and date_trunc('month',entregue_at)=date_trunc('month',now()))::bigint concessoes_entregues_mes from sigov.agro_beneficio_concessao where is_deleted=false group by tenant_id, entidade_id),
insumos_mes as (select tenant_id, entidade_id, count(*)::bigint insumos_distribuidos_mes from sigov.agro_distribuicao_insumo where is_deleted=false and date_trunc('month',data_distribuicao::timestamp)=date_trunc('month',current_date::timestamp) group by tenant_id, entidade_id),
maquinas as (select tenant_id, entidade_id, count(*) filter (where ativo and situacao='ATIVA')::bigint total_maquinas from sigov.agro_maquina where is_deleted=false group by tenant_id, entidade_id),
servicos as (select tenant_id, entidade_id, count(*)::bigint total_servicos_maquina, count(*) filter (where status in ('SOLICITADO','EM_ANALISE'))::bigint servicos_maquina_pendentes, count(*) filter (where status='AGENDADO')::bigint servicos_maquina_agendados, count(*) filter (where status='EXECUTADO' and date_trunc('month',data_execucao::timestamp)=date_trunc('month',current_date::timestamp))::bigint servicos_maquina_executados_mes, coalesce(sum(horas_trabalhadas) filter (where status='EXECUTADO' and date_trunc('month',data_execucao::timestamp)=date_trunc('month',current_date::timestamp)),0)::numeric(18,4) horas_trabalhadas_mes, coalesce(sum(area_atendida_ha) filter (where status='EXECUTADO' and date_trunc('month',data_execucao::timestamp)=date_trunc('month',current_date::timestamp)),0)::numeric(18,4) area_atendida_mes from sigov.agro_servico_maquina where is_deleted=false group by tenant_id, entidade_id),
conflitos as (select a.tenant_id, a.entidade_id, count(*)::bigint alertas_conflito_agenda from sigov.agro_agenda_maquina a join sigov.agro_agenda_maquina b on b.tenant_id=a.tenant_id and b.entidade_id=a.entidade_id and b.maquina_id=a.maquina_id and b.id<>a.id and b.is_deleted=false and b.status not in ('CANCELADA') and a.data_inicio < b.data_fim and a.data_fim > b.data_inicio where a.is_deleted=false and a.status not in ('CANCELADA') group by a.tenant_id,a.entidade_id)
select k.tenant_id,k.entidade_id,coalesce(c.total_camadas,0)::bigint total_camadas,coalesce(f.total_feicoes,0)::bigint total_feicoes,coalesce(e.total_eventos,0)::bigint total_eventos,coalesce(p.total_produtores,0)::bigint total_produtores,coalesce(pr.total_propriedades,0)::bigint total_propriedades,0::bigint total_visitas,coalesce(sv.total_servicos_maquina,0)::bigint total_servicos_maquina,0::bigint total_pontos_criticos,coalesce(p.produtores_ativos,0)::bigint produtores_ativos,coalesce(pr.area_total_mapeada,0)::numeric(18,4) area_total_mapeada,coalesce(pr.area_produtiva,0)::numeric(18,4) area_produtiva,coalesce(t.total_talhoes,0)::bigint total_talhoes,coalesce(cu.culturas_cadastradas,0)::bigint culturas_cadastradas,coalesce(sf.safras_ativas,0)::bigint safras_ativas,coalesce(pa.producao_estimada,0)::numeric(18,4) producao_estimada,coalesce(pa.producao_realizada,0)::numeric(18,4) producao_realizada,coalesce(pg.total_programas,0)::bigint total_programas,coalesce(bn.total_beneficios,0)::bigint total_beneficios,coalesce(co.beneficios_concedidos_mes,0)::bigint beneficios_concedidos_mes,coalesce(m.total_maquinas,0)::bigint total_maquinas,coalesce(sv.servicos_maquina_pendentes,0)::bigint servicos_maquina_pendentes,coalesce(sv.servicos_maquina_executados_mes,0)::bigint servicos_maquina_executados_mes,coalesce(co.concessoes_solicitadas,0)::bigint concessoes_solicitadas,coalesce(co.concessoes_autorizadas,0)::bigint concessoes_autorizadas,coalesce(co.concessoes_entregues_mes,0)::bigint concessoes_entregues_mes,coalesce(im.insumos_distribuidos_mes,0)::bigint insumos_distribuidos_mes,coalesce(sv.servicos_maquina_agendados,0)::bigint servicos_maquina_agendados,coalesce(sv.horas_trabalhadas_mes,0)::numeric(18,4) horas_trabalhadas_mes,coalesce(sv.area_atendida_mes,0)::numeric(18,4) area_atendida_mes,coalesce(cf.alertas_conflito_agenda,0)::bigint alertas_conflito_agenda
from chaves k left join camadas c on c.tenant_id=k.tenant_id and c.entidade_id is not distinct from k.entidade_id left join feicoes f on f.tenant_id=k.tenant_id and f.entidade_id is not distinct from k.entidade_id left join eventos e on e.tenant_id=k.tenant_id and e.entidade_id is not distinct from k.entidade_id left join produtores p on p.tenant_id=k.tenant_id and p.entidade_id is not distinct from k.entidade_id left join propriedades pr on pr.tenant_id=k.tenant_id and pr.entidade_id is not distinct from k.entidade_id left join talhoes t on t.tenant_id=k.tenant_id and t.entidade_id is not distinct from k.entidade_id left join culturas cu on cu.tenant_id=k.tenant_id and cu.entidade_id is not distinct from k.entidade_id left join safras sf on sf.tenant_id=k.tenant_id and sf.entidade_id is not distinct from k.entidade_id left join producao pa on pa.tenant_id=k.tenant_id and pa.entidade_id is not distinct from k.entidade_id left join programas pg on pg.tenant_id=k.tenant_id and pg.entidade_id is not distinct from k.entidade_id left join beneficios bn on bn.tenant_id=k.tenant_id and bn.entidade_id is not distinct from k.entidade_id left join concessoes co on co.tenant_id=k.tenant_id and co.entidade_id is not distinct from k.entidade_id left join insumos_mes im on im.tenant_id=k.tenant_id and im.entidade_id is not distinct from k.entidade_id left join maquinas m on m.tenant_id=k.tenant_id and m.entidade_id is not distinct from k.entidade_id left join servicos sv on sv.tenant_id=k.tenant_id and sv.entidade_id is not distinct from k.entidade_id left join conflitos cf on cf.tenant_id=k.tenant_id and cf.entidade_id is not distinct from k.entidade_id;
