-- FUNC07 - Saneamento comercial e operacional. Corretiva, aditiva e idempotente.
create schema if not exists sigov;

-- Cadastro comercial complementar, preservando as estruturas RC50.50 publicadas.
create table if not exists sigov.saneamento_cliente (
 id bigint generated by default as identity primary key, tenant_id bigint not null, entidade_id bigint not null,
 codigo varchar(40) not null, nome varchar(250) not null, tipo_pessoa varchar(20) not null,
 documento varchar(20), email varchar(254), telefone varchar(30), finalidade_tratamento varchar(250) not null default 'prestacao_servico_saneamento',
 situacao varchar(20) not null default 'ATIVO', is_deleted boolean not null default false,
 created_at timestamptz not null default now(), updated_at timestamptz, created_by bigint, updated_by bigint,
 constraint ck_san_cliente_tipo check(tipo_pessoa in('FISICA','JURIDICA','ORGAO_PUBLICO')),
 constraint ck_san_cliente_situacao check(situacao in('ATIVO','INATIVO','BLOQUEADO')),
 constraint ux_san_cliente_codigo unique(tenant_id,entidade_id,codigo)
);
create table if not exists sigov.saneamento_unidade_consumidora (
 id bigint generated by default as identity primary key, tenant_id bigint not null, entidade_id bigint not null,
 matricula varchar(40) not null, proprietario_id bigint not null, inquilino_id bigint, responsavel_financeiro_id bigint, orgao_pagador_id bigint,
 logradouro varchar(250) not null, numero varchar(30) not null, complemento varchar(120), bairro varchar(120) not null, cep varchar(8), cidade varchar(120) not null, uf char(2) not null,
 categoria varchar(30) not null, subcategoria varchar(60), moradores integer not null default 0, economias integer not null default 1,
 area_edificada numeric(12,2), inscricao_imobiliaria varchar(60), reservatorio boolean not null default false, cisterna boolean not null default false,
 fonte_propria boolean not null default false, fossa boolean not null default false, situacao varchar(20) not null default 'ATIVA',
 is_deleted boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz, created_by bigint, updated_by bigint,
 constraint fk_san_uc_proprietario foreign key(proprietario_id) references sigov.saneamento_cliente(id),
 constraint ck_san_uc_quantidades check(moradores>=0 and economias>0 and (area_edificada is null or area_edificada>=0)),
 constraint ck_san_uc_situacao check(situacao in('ATIVA','INATIVA','SUSPENSA','CANCELADA')),
 constraint ux_san_uc_matricula unique(tenant_id,entidade_id,matricula)
);
create table if not exists sigov.saneamento_economia (
 id bigint generated by default as identity primary key, tenant_id bigint not null, entidade_id bigint not null, unidade_consumidora_id bigint not null,
 categoria varchar(30) not null, subcategoria varchar(60), quantidade integer not null default 1, ativo boolean not null default true,
 created_at timestamptz not null default now(), created_by bigint,
 constraint fk_san_economia_uc foreign key(unidade_consumidora_id) references sigov.saneamento_unidade_consumidora(id), constraint ck_san_economia_qtd check(quantidade>0)
);
create table if not exists sigov.saneamento_hidrometro_movimento (
 id bigint generated by default as identity primary key, tenant_id bigint not null, entidade_id bigint not null, hidrometro_id bigint not null,
 ligacao_id bigint, tipo varchar(20) not null, data_movimento timestamptz not null default now(), leitura numeric(14,3), observacao text,
 created_at timestamptz not null default now(), created_by bigint,
 constraint fk_san_hm_hidrometro foreign key(hidrometro_id) references sigov.saneamento_hidrometro(id),
 constraint ck_san_hm_tipo check(tipo in('ENTRADA','INSTALACAO','RETIRADA','TROCA','AFERICAO','MANUTENCAO','BAIXA'))
);
create table if not exists sigov.saneamento_competencia (
 id bigint generated by default as identity primary key, tenant_id bigint not null, entidade_id bigint not null, competencia date not null,
 status varchar(20) not null default 'ABERTA', gerada_at timestamptz, fechada_at timestamptz, created_at timestamptz not null default now(), created_by bigint,
 constraint ck_san_comp_mes check(extract(day from competencia)=1), constraint ck_san_comp_status check(status in('ABERTA','GERADA','FATURADA','FECHADA')),
 constraint ux_san_comp unique(tenant_id,entidade_id,competencia)
);
create table if not exists sigov.saneamento_rota_unidade (
 id bigint generated by default as identity primary key, tenant_id bigint not null, entidade_id bigint not null, rota_id bigint not null,
 unidade_consumidora_id bigint not null, sequencia integer not null, ativo boolean not null default true, created_at timestamptz not null default now(), created_by bigint,
 constraint fk_san_ru_rota foreign key(rota_id) references sigov.saneamento_rota_leitura(id),
 constraint fk_san_ru_uc foreign key(unidade_consumidora_id) references sigov.saneamento_unidade_consumidora(id), constraint ck_san_ru_seq check(sequencia>0),
 constraint ux_san_ru_uc unique(tenant_id,entidade_id,unidade_consumidora_id), constraint ux_san_ru_seq unique(tenant_id,entidade_id,rota_id,sequencia)
);
create table if not exists sigov.saneamento_ordem_servico_item (
 id bigint generated by default as identity primary key, tenant_id bigint not null, entidade_id bigint not null, ordem_servico_id bigint not null,
 material_id bigint, descricao varchar(250) not null, quantidade numeric(16,3) not null, unidade varchar(20) not null,
 created_at timestamptz not null default now(), created_by bigint, constraint fk_san_osi_os foreign key(ordem_servico_id) references sigov.saneamento_ordem_servico(id),
 constraint ck_san_osi_qtd check(quantidade>0)
);
create table if not exists sigov.saneamento_parametro_tarifa (
 id bigint generated by default as identity primary key, tenant_id bigint not null, entidade_id bigint not null, categoria varchar(30) not null,
 faixa_inicio numeric(14,3) not null, faixa_fim numeric(14,3), valor_m3 numeric(18,6) not null, percentual_esgoto numeric(7,4) not null default 0,
 vigencia_inicio date not null, vigencia_fim date, ativo boolean not null default true, created_at timestamptz not null default now(), created_by bigint,
 constraint ck_san_tarifa_valores check(faixa_inicio>=0 and (faixa_fim is null or faixa_fim>=faixa_inicio) and valor_m3>=0 and percentual_esgoto between 0 and 100),
 constraint ck_san_tarifa_vigencia check(vigencia_fim is null or vigencia_fim>=vigencia_inicio)
);
create table if not exists sigov.saneamento_parametro_servico (
 id bigint generated by default as identity primary key, tenant_id bigint not null, entidade_id bigint not null, codigo varchar(40) not null,
 descricao varchar(250) not null, valor numeric(18,2) not null, gera_os_automatica boolean not null default false, tipo_os varchar(40),
 ativo boolean not null default true, created_at timestamptz not null default now(), created_by bigint,
 constraint ck_san_servico_valor check(valor>=0), constraint ux_san_servico_codigo unique(tenant_id,entidade_id,codigo)
);
create table if not exists sigov.saneamento_historico_cadastral (
 id bigint generated by default as identity primary key, tenant_id bigint not null, entidade_id bigint not null, recurso varchar(40) not null,
 recurso_id bigint not null, acao varchar(30) not null, dados_anteriores jsonb, dados_novos jsonb, justificativa text,
 correlation_id uuid not null default gen_random_uuid(), created_at timestamptz not null default now(), created_by bigint
);

-- Colunas funcionais sobre estruturas legadas. Nenhuma coluna publicada e removida.
alter table sigov.saneamento_hidrometro add column if not exists ligacao_ativa_id bigint, add column if not exists data_fabricacao date, add column if not exists capacidade numeric(14,3), add column if not exists fabricante varchar(120), add column if not exists modelo varchar(120);
alter table sigov.saneamento_leitura add column if not exists competencia_id bigint, add column if not exists leitura_anterior numeric(14,3), add column if not exists leitura_atual numeric(14,3), add column if not exists consumo_calculado numeric(14,3), add column if not exists critica varchar(40), add column if not exists revisada_por bigint;
alter table sigov.saneamento_fatura add column if not exists data_vencimento date, add column if not exists valor_total numeric(18,2), add column if not exists justificativa_revisao text, add column if not exists justificativa_cancelamento text, add column if not exists linha_digitavel varchar(80);
alter table sigov.saneamento_parcelamento add column if not exists justificativa_cancelamento text;
alter table sigov.saneamento_ordem_servico add column if not exists prazo_at timestamptz, add column if not exists veiculo_id bigint, add column if not exists laudo text;
alter table sigov.saneamento_atendimento add column if not exists unidade_consumidora_id bigint, add column if not exists ordem_servico_gerada_id bigint, add column if not exists prioridade varchar(20);

create unique index if not exists ux_san_hidrometro_ligacao_instalado on sigov.saneamento_hidrometro(tenant_id,entidade_id,ligacao_ativa_id) where ligacao_ativa_id is not null and status='INSTALADO' and not is_deleted;
create index if not exists ix_san_uc_situacao_categoria on sigov.saneamento_unidade_consumidora(tenant_id,entidade_id,situacao,categoria) where not is_deleted;
create index if not exists ix_san_rota_unidade_rota on sigov.saneamento_rota_unidade(tenant_id,entidade_id,rota_id,sequencia) where ativo;
create index if not exists ix_san_competencia_status on sigov.saneamento_competencia(tenant_id,entidade_id,competencia,status);
create index if not exists ix_san_fatura_vencimento on sigov.saneamento_fatura(tenant_id,entidade_id,status,data_vencimento) where not is_deleted;
create index if not exists ix_san_os_prazo on sigov.saneamento_ordem_servico(tenant_id,entidade_id,status,prazo_at) where not is_deleted;
create index if not exists ix_san_hist_recurso on sigov.saneamento_historico_cadastral(tenant_id,entidade_id,recurso,recurso_id,created_at);

-- RBAC persistido e fail-closed: nenhuma concessão é feita exceto ao perfil sistêmico SUPERADMIN.
insert into sigov.permissao(modulo,chave,recurso,acao,descricao,ativo,is_deleted)
select 'saneamento',v.chave,v.recurso,v.acao,'Permissão FUNC07 Saneamento',true,false from(values
('SANEAMENTO_DASHBOARD_VIEW','saneamento.dashboard','visualizar'),('SANEAMENTO_CLIENTE_VIEW','saneamento.cliente','visualizar'),('SANEAMENTO_CLIENTE_MANAGE','saneamento.cliente','gerenciar'),
('SANEAMENTO_UNIDADE_VIEW','saneamento.unidade','visualizar'),('SANEAMENTO_UNIDADE_MANAGE','saneamento.unidade','gerenciar'),('SANEAMENTO_LIGACAO_VIEW','saneamento.ligacao','visualizar'),('SANEAMENTO_LIGACAO_MANAGE','saneamento.ligacao','gerenciar'),
('SANEAMENTO_HIDROMETRO_VIEW','saneamento.hidrometro','visualizar'),('SANEAMENTO_HIDROMETRO_MANAGE','saneamento.hidrometro','gerenciar'),('SANEAMENTO_LEITURA_VIEW','saneamento.leitura','visualizar'),('SANEAMENTO_LEITURA_MANAGE','saneamento.leitura','gerenciar'),
('SANEAMENTO_FATURAMENTO_VIEW','saneamento.faturamento','visualizar'),('SANEAMENTO_FATURAMENTO_MANAGE','saneamento.faturamento','gerenciar'),('SANEAMENTO_ARRECADACAO_VIEW','saneamento.arrecadacao','visualizar'),('SANEAMENTO_ARRECADACAO_MANAGE','saneamento.arrecadacao','gerenciar'),
('SANEAMENTO_OS_VIEW','saneamento.os','visualizar'),('SANEAMENTO_OS_MANAGE','saneamento.os','gerenciar'),('SANEAMENTO_ATENDIMENTO_VIEW','saneamento.atendimento','visualizar'),('SANEAMENTO_ATENDIMENTO_MANAGE','saneamento.atendimento','gerenciar'),('SANEAMENTO_RELATORIO_EXPORT','saneamento.relatorio','exportar')
)v(chave,recurso,acao) where not exists(select 1 from sigov.permissao p where p.chave=v.chave);
insert into sigov.perfil_permissao(perfil_acesso_id,permissao_id,efeito,ativo,is_deleted)
select pa.id,p.id,'PERMITIR',true,false from sigov.perfil_acesso pa cross join sigov.permissao p
where pa.codigo_externo='SUPERADMIN' and pa.sistemico and pa.ativo and not pa.is_deleted and p.modulo='saneamento' and p.chave like 'SANEAMENTO_%' and p.ativo and not p.is_deleted
on conflict(perfil_acesso_id,permissao_id) do update set efeito='PERMITIR',ativo=true,is_deleted=false;
