-- SIGOV Pós-Build 04: base comercial, ordem de serviço, manutenção industrial, estoque/compras e comércio.
create schema if not exists sigov;

create table if not exists sigov.enterprise_audit_event (
    id uuid primary key default gen_random_uuid(), tenant_id uuid not null, entity_name text not null, entity_id uuid not null,
    action text not null, correlation_id text, payload jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);

create table if not exists sigov.comercial_cliente (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, nome text not null, documento text, email text, telefone text, status text not null default 'ATIVO', lgpd_classificacao text not null default 'DADO_PESSOAL', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists sigov.comercial_lead (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, nome text not null, origem text, email text, telefone text, status text not null default 'NOVO', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists sigov.comercial_oportunidade (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, cliente_id uuid references sigov.comercial_cliente(id), titulo text not null, valor_estimado numeric(14,2) not null default 0, status text not null default 'ABERTA', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists sigov.comercial_proposta (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, cliente_id uuid references sigov.comercial_cliente(id), oportunidade_id uuid references sigov.comercial_oportunidade(id), numero text not null, status text not null default 'RASCUNHO', valor_total numeric(14,2) not null default 0, aprovada_em timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(tenant_id, numero));
create table if not exists sigov.comercial_proposta_item (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, proposta_id uuid not null references sigov.comercial_proposta(id) on delete cascade, descricao text not null, quantidade numeric(14,4) not null default 1, valor_unitario numeric(14,2) not null default 0, created_at timestamptz not null default now());
create table if not exists sigov.comercial_pedido (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, cliente_id uuid references sigov.comercial_cliente(id), proposta_id uuid references sigov.comercial_proposta(id), numero text not null, status text not null default 'ABERTO', valor_total numeric(14,2) not null default 0, confirmado_em timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(tenant_id, numero));
create table if not exists sigov.comercial_pedido_item (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, pedido_id uuid not null references sigov.comercial_pedido(id) on delete cascade, produto_id uuid, descricao text not null, quantidade numeric(14,4) not null default 1, valor_unitario numeric(14,2) not null default 0, gera_os boolean not null default false, created_at timestamptz not null default now());
create table if not exists sigov.comercial_tabela_preco (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, nome text not null, status text not null default 'ATIVA', vigencia_inicio date, vigencia_fim date, created_at timestamptz not null default now());
create table if not exists sigov.comercial_tabela_preco_item (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, tabela_preco_id uuid not null references sigov.comercial_tabela_preco(id) on delete cascade, produto_id uuid not null, preco numeric(14,2) not null, created_at timestamptz not null default now());

create table if not exists sigov.os_tipo (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, nome text not null, ativo boolean not null default true);
create table if not exists sigov.os_ordem_servico (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, cliente_id uuid, pedido_id uuid, ativo_id uuid, tipo_id uuid references sigov.os_tipo(id), numero text not null, status text not null default 'ABERTA' check (status in ('ABERTA','TRIAGEM','AGENDADA','EM_EXECUCAO','AGUARDANDO_PECA','AGUARDANDO_CLIENTE','CONCLUIDA','CANCELADA')), descricao text, agendada_para timestamptz, concluida_em timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(tenant_id, numero));
create table if not exists sigov.os_item (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, ordem_servico_id uuid not null references sigov.os_ordem_servico(id) on delete cascade, produto_id uuid, descricao text not null, quantidade numeric(14,4) not null default 1, consumo_estoque boolean not null default false);
create table if not exists sigov.os_apontamento (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, ordem_servico_id uuid not null references sigov.os_ordem_servico(id) on delete cascade, tecnico_id uuid, inicio timestamptz not null default now(), fim timestamptz, horas numeric(10,2) not null default 0, observacao text);
create table if not exists sigov.os_checklist (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, ordem_servico_id uuid not null references sigov.os_ordem_servico(id) on delete cascade, item text not null, concluido boolean not null default false);
create table if not exists sigov.os_anexo (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, ordem_servico_id uuid not null references sigov.os_ordem_servico(id) on delete cascade, nome_arquivo text not null, storage_key text not null, content_type text, created_at timestamptz not null default now());
create table if not exists sigov.os_status_historico (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, ordem_servico_id uuid not null references sigov.os_ordem_servico(id) on delete cascade, status_anterior text, status_novo text not null, created_at timestamptz not null default now(), correlation_id text);

create table if not exists sigov.industrial_localizacao (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, nome text not null, hierarquia text);
create table if not exists sigov.industrial_ativo (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, localizacao_id uuid references sigov.industrial_localizacao(id), codigo text not null, nome text not null, criticidade text not null default 'MEDIA', status text not null default 'OPERACIONAL', unique(tenant_id, codigo));
create table if not exists sigov.industrial_plano_manutencao (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, ativo_id uuid references sigov.industrial_ativo(id), nome text not null, tipo text not null check (tipo in ('PREVENTIVA','CORRETIVA','PREDITIVA','INSPECAO','LUBRIFICACAO','CALIBRACAO')), frequencia_dias int not null default 30, ativo boolean not null default true);
create table if not exists sigov.industrial_plano_item (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, plano_id uuid not null references sigov.industrial_plano_manutencao(id) on delete cascade, descricao text not null, ordem int not null default 1);
create table if not exists sigov.industrial_manutencao_programada (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, plano_id uuid not null references sigov.industrial_plano_manutencao(id), ordem_servico_id uuid, prevista_para date not null, status text not null default 'PROGRAMADA');
create table if not exists sigov.industrial_medidor (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, ativo_id uuid references sigov.industrial_ativo(id), nome text not null, unidade text not null);
create table if not exists sigov.industrial_leitura_medidor (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, medidor_id uuid not null references sigov.industrial_medidor(id) on delete cascade, leitura numeric(14,4) not null, lida_em timestamptz not null default now());
create table if not exists sigov.industrial_causa_falha (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, codigo text not null, descricao text not null, unique(tenant_id, codigo));
create table if not exists sigov.industrial_parada (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, ativo_id uuid references sigov.industrial_ativo(id), causa_falha_id uuid references sigov.industrial_causa_falha(id), inicio timestamptz not null, fim timestamptz, impacto text);

create table if not exists sigov.estoque_produto (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, sku text not null, nome text not null, unidade text not null default 'UN', estoque_minimo numeric(14,4) not null default 0, permite_saldo_negativo boolean not null default false, ativo boolean not null default true, unique(tenant_id, sku));
create table if not exists sigov.estoque_almoxarifado (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, nome text not null, ativo boolean not null default true);
create table if not exists sigov.estoque_movimento (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, produto_id uuid not null references sigov.estoque_produto(id), almoxarifado_id uuid references sigov.estoque_almoxarifado(id), tipo text not null check (tipo in ('ENTRADA','SAIDA','AJUSTE','TRANSFERENCIA','CONSUMO_OS','VENDA','DEVOLUCAO')), quantidade numeric(14,4) not null, origem text, origem_id uuid, created_at timestamptz not null default now());
create table if not exists sigov.estoque_saldo (tenant_id uuid not null, produto_id uuid not null references sigov.estoque_produto(id), almoxarifado_id uuid not null references sigov.estoque_almoxarifado(id), quantidade numeric(14,4) not null default 0, updated_at timestamptz not null default now(), primary key (tenant_id, produto_id, almoxarifado_id));
create table if not exists sigov.estoque_requisicao (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, status text not null default 'ABERTA', solicitante_id uuid, created_at timestamptz not null default now());
create table if not exists sigov.estoque_requisicao_item (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, requisicao_id uuid not null references sigov.estoque_requisicao(id) on delete cascade, produto_id uuid not null references sigov.estoque_produto(id), quantidade numeric(14,4) not null);
create table if not exists sigov.compras_fornecedor (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, nome text not null, documento text, email text, telefone text, ativo boolean not null default true);
create table if not exists sigov.compras_pedido (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, fornecedor_id uuid references sigov.compras_fornecedor(id), numero text not null, status text not null default 'ABERTO', valor_total numeric(14,2) not null default 0, unique(tenant_id, numero));
create table if not exists sigov.compras_pedido_item (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, pedido_id uuid not null references sigov.compras_pedido(id) on delete cascade, produto_id uuid references sigov.estoque_produto(id), quantidade numeric(14,4) not null, valor_unitario numeric(14,2) not null default 0);

create index if not exists ix_comercial_cliente_tenant on sigov.comercial_cliente(tenant_id);
create index if not exists ix_os_ordem_servico_tenant_status on sigov.os_ordem_servico(tenant_id, status);
create index if not exists ix_industrial_ativo_tenant on sigov.industrial_ativo(tenant_id);
create index if not exists ix_estoque_produto_tenant on sigov.estoque_produto(tenant_id);
create index if not exists ix_compras_fornecedor_tenant on sigov.compras_fornecedor(tenant_id);

insert into sigov.permissao (modulo,recurso,acao,chave,descricao,ativo)
values
('comercial','*','gerenciar','comercial.*','Gerenciar módulo Comercial/CRM',true),
('os','*','gerenciar','os.*','Gerenciar módulo de Ordem de Serviço',true),
('industrial','*','gerenciar','industrial.*','Gerenciar módulo de Manutenção Industrial',true),
('estoque','*','gerenciar','estoque.*','Gerenciar módulo de Estoque',true),
('compras','*','gerenciar','compras.*','Gerenciar módulo de Compras',true),
('comercio','*','gerenciar','comercio.*','Gerenciar módulo de Comércio',true)
on conflict (modulo,recurso,acao) do update set chave=excluded.chave, descricao=excluded.descricao, ativo=true;
