-- SIGOV+ RC50.45 - integridade, validação pública e evidências GED.

create table if not exists sigov.assinatura_documento (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    status varchar(40) not null default 'PENDENTE',
    ativo boolean not null default true,
    is_deleted boolean not null default false
);
alter table sigov.ged_documento add column if not exists ativo boolean not null default true;
alter table sigov.ged_documento add column if not exists is_deleted boolean not null default false;
alter table sigov.ged_documento add column if not exists status varchar(40) not null default 'ATIVO';
alter table sigov.assinatura_documento add column if not exists ativo boolean not null default true;
alter table sigov.assinatura_documento add column if not exists is_deleted boolean not null default false;
alter table sigov.assinatura_documento add column if not exists status varchar(40) not null default 'PENDENTE';

create unique index if not exists ux_ged_validacao_codigo_publico
    on sigov.ged_validacao_publica (tenant_id, codigo_validacao)
    where codigo_validacao is not null and is_deleted = false and sigiloso = false;
create index if not exists ix_ged_documento_hash
    on sigov.ged_documento (tenant_id, hash_sha256)
    where hash_sha256 is not null and is_deleted = false and ativo = true;
create index if not exists ix_assinatura_prazo_pendente
    on sigov.assinatura_documento (tenant_id, prazo_at)
    where is_deleted = false and ativo = true and status = 'PENDENTE';
