-- EXP11 Saúde360 + ACS360 — território, campo, sincronização, e-SUS e vigilâncias.
-- PostgreSQL 16+, aditiva, idempotente e sem dados fictícios.
create schema if not exists sigov;

create table if not exists sigov.acs_area (
 id bigint generated by default as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), exercicio_id bigint, unidade_id bigint not null references sigov.unidade_saude(id),
 codigo varchar(40) not null, nome varchar(160) not null, equipe_id bigint, status varchar(20) not null default 'ATIVA' check(status in ('ATIVA','INATIVA')),
 created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz not null default now(), updated_by bigint,
 unique(tenant_id,entidade_id,codigo)
);
alter table sigov.acs_microarea add column if not exists area_id bigint references sigov.acs_area(id);
alter table sigov.acs_microarea add column if not exists exercicio_id bigint;
alter table sigov.acs_microarea add column if not exists equipe_id bigint;
create index if not exists ix_acs_area_contexto on sigov.acs_area(tenant_id,entidade_id,unidade_id,status);
create index if not exists ix_acs_microarea_area on sigov.acs_microarea(tenant_id,entidade_id,area_id,unidade_saude_id);

create table if not exists sigov.acs_agente_vinculo (
 id bigint generated by default as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), exercicio_id bigint, unidade_id bigint not null references sigov.unidade_saude(id),
 microarea_id bigint not null references sigov.acs_microarea(id), profissional_acs_id bigint not null references sigov.profissional_saude(id), inicio date not null, fim date,
 status varchar(20) not null default 'ATIVO' check(status in ('ATIVO','ENCERRADO','INATIVO')), permite_sobreposicao boolean not null default false,
 created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz not null default now(), updated_by bigint, check(fim is null or fim>=inicio)
);
create unique index if not exists ux_acs_vinculo_microarea_ativo on sigov.acs_agente_vinculo(tenant_id,entidade_id,microarea_id) where status='ATIVO' and fim is null and not permite_sobreposicao;
create index if not exists ix_acs_vinculo_agente on sigov.acs_agente_vinculo(tenant_id,entidade_id,profissional_acs_id,inicio,fim);

create table if not exists sigov.acs_rota_trabalho (
 id bigint generated by default as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), exercicio_id bigint, unidade_id bigint not null references sigov.unidade_saude(id),
 profissional_acs_id bigint not null references sigov.profissional_saude(id), microarea_id bigint not null references sigov.acs_microarea(id), data_rota date not null, turno varchar(10) not null check(turno in ('MANHA','TARDE','NOITE','INTEGRAL')),
 trajeto_geojson jsonb, status varchar(20) not null default 'PLANEJADA' check(status in ('PLANEJADA','INICIADA','CONCLUIDA','CANCELADA')), created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz not null default now(), updated_by bigint
);
create index if not exists ix_acs_rota_contexto on sigov.acs_rota_trabalho(tenant_id,entidade_id,unidade_id,profissional_acs_id,data_rota,status);

alter table sigov.acs_sync_item add column if not exists idempotency_key varchar(160);
create unique index if not exists ux_acs_sync_item_idempotencia on sigov.acs_sync_item(tenant_id,entidade_id,idempotency_key) where idempotency_key is not null;
create table if not exists sigov.acs_sync_conflito (
 id bigint generated by default as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), exercicio_id bigint, unidade_id bigint,
 sync_item_id bigint not null references sigov.acs_sync_item(id), tipo varchar(40) not null, dados_servidor jsonb not null default '{}'::jsonb, dados_dispositivo jsonb not null default '{}'::jsonb,
 status varchar(20) not null default 'PENDENTE' check(status in ('PENDENTE','RESOLVIDO_SERVIDOR','RESOLVIDO_DISPOSITIVO','MESCLADO')), resolvido_at timestamptz, resolvido_by bigint,
 created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz not null default now(), updated_by bigint
);
create table if not exists sigov.acs_sync_erro (
 id bigint generated by default as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), exercicio_id bigint, unidade_id bigint,
 sync_lote_id bigint not null references sigov.acs_sync_lote(id), sync_item_id bigint references sigov.acs_sync_item(id), codigo varchar(50) not null, mensagem_sanitizada text not null,
 created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz not null default now(), updated_by bigint
);
create index if not exists ix_acs_sync_conflito_status on sigov.acs_sync_conflito(tenant_id,entidade_id,status,sync_item_id);
create index if not exists ix_acs_sync_erro_lote on sigov.acs_sync_erro(tenant_id,entidade_id,sync_lote_id,created_at);

alter table sigov.acs_cadastro_domiciliar add column if not exists exercicio_id bigint;
alter table sigov.acs_cadastro_domiciliar add column if not exists unidade_id bigint references sigov.unidade_saude(id);
alter table sigov.acs_cadastro_domiciliar add column if not exists endereco_descricao text;
alter table sigov.acs_cadastro_domiciliar add column if not exists recusa_justificativa text;
create table if not exists sigov.acs_familia (
 id bigint generated by default as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), exercicio_id bigint, unidade_id bigint not null references sigov.unidade_saude(id),
 domicilio_id bigint not null references sigov.acs_cadastro_domiciliar(id), responsavel_pessoa_id bigint references sigov.pessoa(id), codigo varchar(80) not null, renda_familiar numeric(14,2) check(renda_familiar is null or renda_familiar>=0),
 status varchar(20) not null default 'ATIVA' check(status in ('ATIVA','INATIVA','RECUSA')), created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz not null default now(), updated_by bigint,
 unique(tenant_id,entidade_id,codigo)
);
create table if not exists sigov.acs_morador_vinculo (
 id bigint generated by default as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), exercicio_id bigint, unidade_id bigint,
 familia_id bigint not null references sigov.acs_familia(id), pessoa_id bigint not null references sigov.pessoa(id), parentesco varchar(40), inicio date not null, fim date,
 created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz not null default now(), updated_by bigint, check(fim is null or fim>=inicio), unique(tenant_id,entidade_id,familia_id,pessoa_id,inicio)
);
create table if not exists sigov.acs_condicao_moradia (
 id bigint generated by default as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), exercicio_id bigint, unidade_id bigint,
 domicilio_id bigint not null references sigov.acs_cadastro_domiciliar(id), abastecimento_agua varchar(40), destino_lixo varchar(40), esgotamento varchar(40), energia_eletrica boolean,
 quantidade_comodos integer check(quantidade_comodos is null or quantidade_comodos>=0), created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz not null default now(), updated_by bigint
);
create index if not exists ix_acs_familia_domicilio on sigov.acs_familia(tenant_id,entidade_id,unidade_id,domicilio_id,status);

create table if not exists sigov.acs_condicao_saude (
 id bigint generated by default as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), exercicio_id bigint, unidade_id bigint,
 cadastro_individual_id bigint not null references sigov.acs_cadastro_individual(id), tipo varchar(50) not null, ativa boolean not null default true, observacao text,
 created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz not null default now(), updated_by bigint, unique(tenant_id,entidade_id,cadastro_individual_id,tipo)
);
create table if not exists sigov.acs_vulnerabilidade (
 id bigint generated by default as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), exercicio_id bigint, unidade_id bigint,
 cadastro_individual_id bigint not null references sigov.acs_cadastro_individual(id), tipo varchar(50) not null, severidade varchar(15) not null check(severidade in ('BAIXA','MEDIA','ALTA','CRITICA')),
 created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz not null default now(), updated_by bigint
);
create table if not exists sigov.acs_deficiencia (
 id bigint generated by default as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), exercicio_id bigint, unidade_id bigint,
 cadastro_individual_id bigint not null references sigov.acs_cadastro_individual(id), tipo varchar(50) not null, grau varchar(30), created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz not null default now(), updated_by bigint
);
create table if not exists sigov.acs_situacao_rua (
 id bigint generated by default as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), exercicio_id bigint, unidade_id bigint,
 cadastro_individual_id bigint not null references sigov.acs_cadastro_individual(id), tempo_situacao varchar(30), recebe_beneficio boolean, referencia_local text,
 created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz not null default now(), updated_by bigint
);
create index if not exists ix_acs_condicao_individuo on sigov.acs_condicao_saude(tenant_id,entidade_id,cadastro_individual_id,tipo,ativa);

alter table sigov.acs_visita add column if not exists microarea_id bigint references sigov.acs_microarea(id);
alter table sigov.acs_visita add column if not exists unidade_id bigint references sigov.unidade_saude(id);
alter table sigov.acs_visita add column if not exists turno varchar(10);
alter table sigov.acs_visita add column if not exists justificativa_data_futura text;
alter table sigov.acs_visita add column if not exists fora_microarea boolean not null default false;
alter table sigov.acs_visita add column if not exists justificativa_excecao text;
alter table sigov.acs_visita add column if not exists coletado_at timestamptz;
create table if not exists sigov.acs_visita_motivo (
 id bigint generated by default as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), exercicio_id bigint, unidade_id bigint,
 visita_id bigint not null references sigov.acs_visita(id), motivo varchar(60) not null, created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz not null default now(), updated_by bigint, unique(tenant_id,entidade_id,visita_id,motivo)
);
create table if not exists sigov.acs_visita_acompanhamento (
 id bigint generated by default as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), exercicio_id bigint, unidade_id bigint,
 visita_id bigint not null references sigov.acs_visita(id), tipo varchar(60) not null, peso numeric(6,2) check(peso is null or peso>0), altura numeric(5,2) check(altura is null or altura>0), vacinacao_em_dia boolean,
 created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz not null default now(), updated_by bigint
);
create table if not exists sigov.acs_visita_desfecho (
 id bigint generated by default as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), exercicio_id bigint, unidade_id bigint,
 visita_id bigint not null references sigov.acs_visita(id), desfecho varchar(20) not null check(desfecho in ('REALIZADA','RECUSADA','AUSENTE')), orientacoes text,
 created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz not null default now(), updated_by bigint
);
create table if not exists sigov.acs_produtividade_dia (
 id bigint generated by default as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), exercicio_id bigint, unidade_id bigint not null references sigov.unidade_saude(id),
 profissional_acs_id bigint not null references sigov.profissional_saude(id), equipe_id bigint, data date not null, visitas_realizadas integer not null default 0 check(visitas_realizadas>=0), recusas integer not null default 0 check(recusas>=0), ausencias integer not null default 0 check(ausencias>=0),
 created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz not null default now(), updated_by bigint, unique(tenant_id,entidade_id,profissional_acs_id,data)
);
create index if not exists ix_acs_visita_contexto360 on sigov.acs_visita(tenant_id,entidade_id,unidade_id,microarea_id,profissional_acs_id,data_visita,desfecho);

create table if not exists sigov.acs_atividade_participante (
 id bigint generated by default as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), exercicio_id bigint, unidade_id bigint,
 atividade_id bigint not null references sigov.acs_atividade_coletiva(id), pessoa_id bigint not null references sigov.pessoa(id), created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz not null default now(), updated_by bigint,
 unique(tenant_id,entidade_id,atividade_id,pessoa_id)
);
create table if not exists sigov.acs_marcador_consumo_alimentar (
 id bigint generated by default as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), exercicio_id bigint, unidade_id bigint not null references sigov.unidade_saude(id),
 cadastro_individual_id bigint not null references sigov.acs_cadastro_individual(id), data_marcador date not null, respostas jsonb not null, profissional_acs_id bigint references sigov.profissional_saude(id),
 created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz not null default now(), updated_by bigint, unique(tenant_id,entidade_id,cadastro_individual_id,data_marcador)
);

create table if not exists sigov.acs_ocorrencia_campo (
 id bigint generated by default as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), exercicio_id bigint, unidade_id bigint not null references sigov.unidade_saude(id),
 domicilio_id bigint references sigov.acs_cadastro_domiciliar(id), cadastro_individual_id bigint references sigov.acs_cadastro_individual(id), microarea_id bigint references sigov.acs_microarea(id), visita_id bigint references sigov.acs_visita(id),
 tipo varchar(50) not null, origem varchar(30) not null, severidade varchar(15) not null check(severidade in ('BAIXA','MEDIA','ALTA','CRITICA')), status varchar(25) not null default 'ABERTA' check(status in ('ABERTA','EM_TRATAMENTO','ENCERRADA','CANCELADA')),
 descricao text not null, responsavel_pessoa_id bigint references sigov.pessoa(id), created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz not null default now(), updated_by bigint
);
create table if not exists sigov.acs_foco_risco (
 id bigint generated by default as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), exercicio_id bigint, unidade_id bigint not null references sigov.unidade_saude(id),
 ocorrencia_id bigint references sigov.acs_ocorrencia_campo(id), tipo varchar(50) not null, severidade varchar(15) not null check(severidade in ('BAIXA','MEDIA','ALTA','CRITICA')), status varchar(20) not null default 'ABERTO' check(status in ('ABERTO','TRATADO','ENCERRADO')),
 latitude numeric(12,8) not null check(latitude between -90 and 90), longitude numeric(12,8) not null check(longitude between -180 and 180), precisao_metros numeric(10,2) check(precisao_metros is null or precisao_metros>=0),
 created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz not null default now(), updated_by bigint
);
create table if not exists sigov.acs_evidencia_campo (
 id bigint generated by default as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), exercicio_id bigint, unidade_id bigint,
 ocorrencia_id bigint references sigov.acs_ocorrencia_campo(id), foco_risco_id bigint references sigov.acs_foco_risco(id), ged_documento_id bigint, hash_sha256 varchar(64), origem varchar(30) not null, coletado_at timestamptz not null,
 latitude numeric(12,8) check(latitude between -90 and 90), longitude numeric(12,8) check(longitude between -180 and 180), metadados jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz not null default now(), updated_by bigint, check(ocorrencia_id is not null or foco_risco_id is not null)
);
create index if not exists ix_acs_ocorrencia_contexto on sigov.acs_ocorrencia_campo(tenant_id,entidade_id,unidade_id,microarea_id,status,severidade,created_at);

create table if not exists sigov.acs_exportacao_esus (
 id bigint generated by default as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), exercicio_id bigint, unidade_id bigint not null references sigov.unidade_saude(id),
 lote varchar(100) not null, competencia char(6) not null check(competencia ~ '^[0-9]{6}$'), status varchar(25) not null default 'EM_VALIDACAO' check(status in ('EM_VALIDACAO','VALIDADO','COM_INCONSISTENCIA','GERADO','CANCELADO','BLOQUEADO_LAYOUT')),
 quantidade_registros integer not null default 0 check(quantidade_registros>=0), responsavel_pessoa_id bigint not null references sigov.pessoa(id), arquivo_hash varchar(64),
 created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz not null default now(), updated_by bigint, unique(tenant_id,entidade_id,lote)
);
create table if not exists sigov.acs_exportacao_esus_item (
 id bigint generated by default as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), exercicio_id bigint, unidade_id bigint,
 exportacao_id bigint not null references sigov.acs_exportacao_esus(id), origem_tipo varchar(40) not null, origem_id bigint not null, status varchar(20) not null check(status in ('PENDENTE','VALIDO','INVALIDO','EXPORTADO')),
 created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz not null default now(), updated_by bigint, unique(tenant_id,entidade_id,exportacao_id,origem_tipo,origem_id)
);
create table if not exists sigov.acs_inconsistencia_esus (
 id bigint generated by default as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), exercicio_id bigint, unidade_id bigint,
 exportacao_id bigint not null references sigov.acs_exportacao_esus(id), item_id bigint references sigov.acs_exportacao_esus_item(id), campo varchar(100) not null, codigo varchar(40) not null, mensagem text not null,
 status varchar(20) not null default 'ABERTA' check(status in ('ABERTA','CORRIGIDA','IGNORADA')), created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz not null default now(), updated_by bigint
);
create index if not exists ix_acs_esus_contexto on sigov.acs_exportacao_esus(tenant_id,entidade_id,unidade_id,competencia,status);

create table if not exists sigov.saude_vigilancia_evento (
 id bigint generated by default as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), exercicio_id bigint, unidade_id bigint,
 ocorrencia_acs_id bigint references sigov.acs_ocorrencia_campo(id), tipo_vigilancia varchar(20) not null check(tipo_vigilancia in ('EPIDEMIOLOGICA','SANITARIA','AMBIENTAL','TRABALHADOR')), tipo_evento varchar(80) not null,
 severidade varchar(15) not null check(severidade in ('BAIXA','MEDIA','ALTA','CRITICA')), status varchar(25) not null default 'ABERTO' check(status in ('ABERTO','INVESTIGACAO','EM_ACAO','ENCERRADO','CANCELADO')),
 descricao text not null, prazo date, responsavel_pessoa_id bigint references sigov.pessoa(id), encerrado_at timestamptz, created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz not null default now(), updated_by bigint
);
create table if not exists sigov.saude_vigilancia_alerta (
 id bigint generated by default as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), exercicio_id bigint, unidade_id bigint,
 evento_id bigint not null references sigov.saude_vigilancia_evento(id), severidade varchar(15) not null check(severidade in ('BAIXA','MEDIA','ALTA','CRITICA')), prazo timestamptz,
 status varchar(20) not null default 'ABERTO' check(status in ('ABERTO','CIENTE','TRATADO','VENCIDO')), mensagem text not null, created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz not null default now(), updated_by bigint
);
create table if not exists sigov.saude_vigilancia_notificacao (
 id bigint generated by default as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), exercicio_id bigint, unidade_id bigint,
 evento_id bigint not null references sigov.saude_vigilancia_evento(id), canal varchar(30) not null, destinatario_pessoa_id bigint references sigov.pessoa(id), status varchar(20) not null check(status in ('PENDENTE','ENVIADA','ERRO','CANCELADA')),
 enviada_at timestamptz, created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz not null default now(), updated_by bigint
);
create table if not exists sigov.saude_vigilancia_acao (
 id bigint generated by default as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id), exercicio_id bigint, unidade_id bigint,
 evento_id bigint not null references sigov.saude_vigilancia_evento(id), descricao text not null, responsavel_pessoa_id bigint references sigov.pessoa(id), prazo date, concluida_at timestamptz,
 status varchar(20) not null default 'PLANEJADA' check(status in ('PLANEJADA','EM_EXECUCAO','CONCLUIDA','CANCELADA')), created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz not null default now(), updated_by bigint
);
create index if not exists ix_vigilancia_evento_contexto on sigov.saude_vigilancia_evento(tenant_id,entidade_id,unidade_id,tipo_vigilancia,status,prazo);
create index if not exists ix_vigilancia_alerta_aberto on sigov.saude_vigilancia_alerta(tenant_id,entidade_id,status,prazo,severidade);

insert into sigov.permissao(modulo,recurso,acao,chave,descricao,ativo)
select 'saude', split_part(v.chave,'_',1), case when v.chave like '%_VIEW' then 'visualizar' when v.chave like '%_EXPORT' then 'exportar' else 'gerenciar' end, v.chave, v.descricao, true
from (values
 ('SAUDE_DASHBOARD_VIEW','Consultar Saúde360'),('SAUDE_UNIDADE_VIEW','Consultar unidades de saúde'),('SAUDE_PROFISSIONAL_VIEW','Consultar profissionais'),('ACS_DASHBOARD_VIEW','Consultar ACS360'),
 ('ACS_TERRITORIO_VIEW','Consultar territórios ACS'),('ACS_TERRITORIO_MANAGE','Gerir territórios ACS'),('ACS_DOMICILIO_VIEW','Consultar domicílios'),('ACS_DOMICILIO_MANAGE','Gerir domicílios'),
 ('ACS_INDIVIDUO_VIEW','Consultar indivíduos'),('ACS_INDIVIDUO_MANAGE','Gerir indivíduos'),('ACS_VISITA_VIEW','Consultar visitas'),('ACS_VISITA_MANAGE','Gerir visitas'),
 ('ACS_ATIVIDADE_MANAGE','Gerir atividades coletivas'),('ACS_OCORRENCIA_MANAGE','Gerir ocorrências de campo'),('ACS_SYNC_VIEW','Consultar sincronização'),('ACS_SYNC_MANAGE','Gerir sincronização'),
 ('ACS_ESUS_EXPORT','Exportar staging e-SUS'),('ACS_DADO_SENSIVEL_VIEW','Consultar dado sensível ACS'),('ACS_DADO_SENSIVEL_EXPORT','Exportar dado sensível ACS'),
 ('VIGILANCIA_EVENTO_VIEW','Consultar eventos de vigilância'),('VIGILANCIA_EVENTO_MANAGE','Gerir eventos de vigilância'),('VIGILANCIA_ALERTA_MANAGE','Gerir alertas de vigilância'),('SAUDE_RELATORIO_EXPORT','Exportar relatórios de saúde')
) v(chave,descricao) where not exists(select 1 from sigov.permissao p where p.chave=v.chave);
