-- RC50.86: financeiro, orçamento, contabilidade e tesouraria multi-esfera.
-- Migration aditiva, idempotente e sem integração externa simulada.
CREATE SCHEMA IF NOT EXISTS sigov;

CREATE TABLE IF NOT EXISTS sigov.financeiro_unidade_orcamentaria (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, exercicio_id bigint NOT NULL,
 esfera_governo varchar(10) NOT NULL, orgao_id bigint, unidade_gestora_id bigint, unidade_executora_id bigint,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ck_financeiro_unidade_orcamentaria_esfera CHECK (esfera_governo IN ('municipal','estadual','federal')),
 codigo varchar(30) NOT NULL, nome varchar(180) NOT NULL, tipo_entidade varchar(80) NOT NULL, orgao_superior_id bigint, abrangencia_territorial varchar(120), jurisdicao varchar(160), uf char(2), municipio varchar(160), regiao varchar(120), ativo boolean NOT NULL DEFAULT true
);

CREATE INDEX IF NOT EXISTS ix_financeiro_unidade_orcamentaria_contexto ON sigov.financeiro_unidade_orcamentaria (tenant_id, entidade_id, esfera_governo, exercicio_id);

CREATE TABLE IF NOT EXISTS sigov.financeiro_unidade_gestora (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, exercicio_id bigint NOT NULL,
 esfera_governo varchar(10) NOT NULL, orgao_id bigint, unidade_gestora_id bigint, unidade_executora_id bigint,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ck_financeiro_unidade_gestora_esfera CHECK (esfera_governo IN ('municipal','estadual','federal')),
 codigo varchar(30) NOT NULL, nome varchar(180) NOT NULL, tipo_entidade varchar(80) NOT NULL, orgao_superior_id bigint, abrangencia_territorial varchar(120), jurisdicao varchar(160), ativo boolean NOT NULL DEFAULT true
);

CREATE INDEX IF NOT EXISTS ix_financeiro_unidade_gestora_contexto ON sigov.financeiro_unidade_gestora (tenant_id, entidade_id, esfera_governo, exercicio_id);

CREATE TABLE IF NOT EXISTS sigov.financeiro_unidade_executora (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, exercicio_id bigint NOT NULL,
 esfera_governo varchar(10) NOT NULL, orgao_id bigint, unidade_gestora_id bigint, unidade_executora_id bigint,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ck_financeiro_unidade_executora_esfera CHECK (esfera_governo IN ('municipal','estadual','federal')),
 codigo varchar(30) NOT NULL, nome varchar(180) NOT NULL, tipo_entidade varchar(80) NOT NULL, ativo boolean NOT NULL DEFAULT true
);

CREATE INDEX IF NOT EXISTS ix_financeiro_unidade_executora_contexto ON sigov.financeiro_unidade_executora (tenant_id, entidade_id, esfera_governo, exercicio_id);

CREATE TABLE IF NOT EXISTS sigov.financeiro_programa (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, exercicio_id bigint NOT NULL,
 esfera_governo varchar(10) NOT NULL, orgao_id bigint, unidade_gestora_id bigint, unidade_executora_id bigint,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ck_financeiro_programa_esfera CHECK (esfera_governo IN ('municipal','estadual','federal')),
 codigo varchar(30) NOT NULL, nome varchar(200) NOT NULL, objetivo text NOT NULL, status varchar(20) NOT NULL DEFAULT 'ativo', CHECK (status IN ('ativo','inativo','encerrado'))
);

CREATE INDEX IF NOT EXISTS ix_financeiro_programa_contexto ON sigov.financeiro_programa (tenant_id, entidade_id, esfera_governo, exercicio_id);

CREATE TABLE IF NOT EXISTS sigov.financeiro_acao (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, exercicio_id bigint NOT NULL,
 esfera_governo varchar(10) NOT NULL, orgao_id bigint, unidade_gestora_id bigint, unidade_executora_id bigint,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ck_financeiro_acao_esfera CHECK (esfera_governo IN ('municipal','estadual','federal')),
 programa_id bigint REFERENCES sigov.financeiro_programa(id), codigo varchar(30) NOT NULL, nome varchar(200) NOT NULL, tipo varchar(20) NOT NULL, CHECK (tipo IN ('projeto','atividade','operacao_especial'))
);

CREATE INDEX IF NOT EXISTS ix_financeiro_acao_contexto ON sigov.financeiro_acao (tenant_id, entidade_id, esfera_governo, exercicio_id);

CREATE TABLE IF NOT EXISTS sigov.financeiro_fonte_recurso (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, exercicio_id bigint NOT NULL,
 esfera_governo varchar(10) NOT NULL, orgao_id bigint, unidade_gestora_id bigint, unidade_executora_id bigint,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ck_financeiro_fonte_recurso_esfera CHECK (esfera_governo IN ('municipal','estadual','federal')),
 codigo varchar(30) NOT NULL, nome varchar(200) NOT NULL, vinculada boolean NOT NULL DEFAULT false
);

CREATE INDEX IF NOT EXISTS ix_financeiro_fonte_recurso_contexto ON sigov.financeiro_fonte_recurso (tenant_id, entidade_id, esfera_governo, exercicio_id);

CREATE TABLE IF NOT EXISTS sigov.financeiro_natureza_receita (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, exercicio_id bigint NOT NULL,
 esfera_governo varchar(10) NOT NULL, orgao_id bigint, unidade_gestora_id bigint, unidade_executora_id bigint,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ck_financeiro_natureza_receita_esfera CHECK (esfera_governo IN ('municipal','estadual','federal')),
 codigo varchar(30) NOT NULL, nome varchar(200) NOT NULL, categoria varchar(30) NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_financeiro_natureza_receita_contexto ON sigov.financeiro_natureza_receita (tenant_id, entidade_id, esfera_governo, exercicio_id);

CREATE TABLE IF NOT EXISTS sigov.financeiro_natureza_despesa (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, exercicio_id bigint NOT NULL,
 esfera_governo varchar(10) NOT NULL, orgao_id bigint, unidade_gestora_id bigint, unidade_executora_id bigint,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ck_financeiro_natureza_despesa_esfera CHECK (esfera_governo IN ('municipal','estadual','federal')),
 codigo varchar(30) NOT NULL, nome varchar(200) NOT NULL, categoria varchar(30) NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_financeiro_natureza_despesa_contexto ON sigov.financeiro_natureza_despesa (tenant_id, entidade_id, esfera_governo, exercicio_id);

CREATE TABLE IF NOT EXISTS sigov.financeiro_ppa (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, exercicio_id bigint NOT NULL,
 esfera_governo varchar(10) NOT NULL, orgao_id bigint, unidade_gestora_id bigint, unidade_executora_id bigint,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ck_financeiro_ppa_esfera CHECK (esfera_governo IN ('municipal','estadual','federal')),
 ano_inicio integer NOT NULL, ano_fim integer NOT NULL, status varchar(20) NOT NULL DEFAULT 'elaboracao', CHECK (ano_fim >= ano_inicio), CHECK (status IN ('elaboracao','aprovado','vigente','encerrado'))
);

CREATE INDEX IF NOT EXISTS ix_financeiro_ppa_contexto ON sigov.financeiro_ppa (tenant_id, entidade_id, esfera_governo, exercicio_id);

CREATE TABLE IF NOT EXISTS sigov.financeiro_ppa_programa (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, exercicio_id bigint NOT NULL,
 esfera_governo varchar(10) NOT NULL, orgao_id bigint, unidade_gestora_id bigint, unidade_executora_id bigint,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ck_financeiro_ppa_programa_esfera CHECK (esfera_governo IN ('municipal','estadual','federal')),
 ppa_id bigint NOT NULL REFERENCES sigov.financeiro_ppa(id), programa_id bigint NOT NULL REFERENCES sigov.financeiro_programa(id), valor_previsto numeric(18,2) NOT NULL DEFAULT 0, CHECK (valor_previsto >= 0)
);

CREATE INDEX IF NOT EXISTS ix_financeiro_ppa_programa_contexto ON sigov.financeiro_ppa_programa (tenant_id, entidade_id, esfera_governo, exercicio_id);

CREATE TABLE IF NOT EXISTS sigov.financeiro_ldo (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, exercicio_id bigint NOT NULL,
 esfera_governo varchar(10) NOT NULL, orgao_id bigint, unidade_gestora_id bigint, unidade_executora_id bigint,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ck_financeiro_ldo_esfera CHECK (esfera_governo IN ('municipal','estadual','federal')),
 ano integer NOT NULL, status varchar(20) NOT NULL DEFAULT 'elaboracao', metas text, CHECK (status IN ('elaboracao','aprovada','vigente','encerrada'))
);

CREATE INDEX IF NOT EXISTS ix_financeiro_ldo_contexto ON sigov.financeiro_ldo (tenant_id, entidade_id, esfera_governo, exercicio_id);

CREATE TABLE IF NOT EXISTS sigov.financeiro_loa (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, exercicio_id bigint NOT NULL,
 esfera_governo varchar(10) NOT NULL, orgao_id bigint, unidade_gestora_id bigint, unidade_executora_id bigint,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ck_financeiro_loa_esfera CHECK (esfera_governo IN ('municipal','estadual','federal')),
 ano integer NOT NULL, status varchar(20) NOT NULL DEFAULT 'elaboracao', valor_total numeric(18,2) NOT NULL DEFAULT 0, CHECK (valor_total >= 0), CHECK (status IN ('elaboracao','aprovada','vigente','encerrada'))
);

CREATE INDEX IF NOT EXISTS ix_financeiro_loa_contexto ON sigov.financeiro_loa (tenant_id, entidade_id, esfera_governo, exercicio_id);

CREATE TABLE IF NOT EXISTS sigov.financeiro_dotacao (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, exercicio_id bigint NOT NULL,
 esfera_governo varchar(10) NOT NULL, orgao_id bigint, unidade_gestora_id bigint, unidade_executora_id bigint,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ck_financeiro_dotacao_esfera CHECK (esfera_governo IN ('municipal','estadual','federal')),
 loa_id bigint REFERENCES sigov.financeiro_loa(id), programa_id bigint NOT NULL REFERENCES sigov.financeiro_programa(id), acao_id bigint NOT NULL REFERENCES sigov.financeiro_acao(id), fonte_recurso_id bigint NOT NULL REFERENCES sigov.financeiro_fonte_recurso(id), natureza_despesa_id bigint NOT NULL REFERENCES sigov.financeiro_natureza_despesa(id), valor_inicial numeric(18,2) NOT NULL, valor_atualizado numeric(18,2) NOT NULL, valor_bloqueado numeric(18,2) NOT NULL DEFAULT 0, valor_empenhado numeric(18,2) NOT NULL DEFAULT 0, CHECK (valor_inicial >= 0 AND valor_atualizado >= 0 AND valor_bloqueado >= 0 AND valor_empenhado >= 0)
);

CREATE INDEX IF NOT EXISTS ix_financeiro_dotacao_contexto ON sigov.financeiro_dotacao (tenant_id, entidade_id, esfera_governo, exercicio_id);

CREATE TABLE IF NOT EXISTS sigov.financeiro_credito_adicional (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, exercicio_id bigint NOT NULL,
 esfera_governo varchar(10) NOT NULL, orgao_id bigint, unidade_gestora_id bigint, unidade_executora_id bigint,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ck_financeiro_credito_adicional_esfera CHECK (esfera_governo IN ('municipal','estadual','federal')),
 dotacao_id bigint NOT NULL REFERENCES sigov.financeiro_dotacao(id), tipo varchar(20) NOT NULL, valor numeric(18,2) NOT NULL, justificativa text NOT NULL, status varchar(20) NOT NULL DEFAULT 'proposto', CHECK (valor > 0), CHECK (tipo IN ('suplementar','especial','extraordinario')), CHECK (status IN ('proposto','autorizado','cancelado'))
);

CREATE INDEX IF NOT EXISTS ix_financeiro_credito_adicional_contexto ON sigov.financeiro_credito_adicional (tenant_id, entidade_id, esfera_governo, exercicio_id);

CREATE TABLE IF NOT EXISTS sigov.financeiro_bloqueio_orcamentario (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, exercicio_id bigint NOT NULL,
 esfera_governo varchar(10) NOT NULL, orgao_id bigint, unidade_gestora_id bigint, unidade_executora_id bigint,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ck_financeiro_bloqueio_orcamentario_esfera CHECK (esfera_governo IN ('municipal','estadual','federal')),
 dotacao_id bigint NOT NULL REFERENCES sigov.financeiro_dotacao(id), tipo varchar(20) NOT NULL, valor numeric(18,2) NOT NULL, justificativa text NOT NULL, status varchar(20) NOT NULL DEFAULT 'ativo', CHECK (valor > 0), CHECK (tipo IN ('bloqueio','desbloqueio')), CHECK (status IN ('ativo','efetivado','cancelado'))
);

CREATE INDEX IF NOT EXISTS ix_financeiro_bloqueio_orcamentario_contexto ON sigov.financeiro_bloqueio_orcamentario (tenant_id, entidade_id, esfera_governo, exercicio_id);

CREATE TABLE IF NOT EXISTS sigov.financeiro_receita_prevista (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, exercicio_id bigint NOT NULL,
 esfera_governo varchar(10) NOT NULL, orgao_id bigint, unidade_gestora_id bigint, unidade_executora_id bigint,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ck_financeiro_receita_prevista_esfera CHECK (esfera_governo IN ('municipal','estadual','federal')),
 fonte_recurso_id bigint NOT NULL REFERENCES sigov.financeiro_fonte_recurso(id), natureza_receita_id bigint NOT NULL REFERENCES sigov.financeiro_natureza_receita(id), valor numeric(18,2) NOT NULL, CHECK (valor >= 0)
);

CREATE INDEX IF NOT EXISTS ix_financeiro_receita_prevista_contexto ON sigov.financeiro_receita_prevista (tenant_id, entidade_id, esfera_governo, exercicio_id);

CREATE TABLE IF NOT EXISTS sigov.financeiro_receita_arrecadada (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, exercicio_id bigint NOT NULL,
 esfera_governo varchar(10) NOT NULL, orgao_id bigint, unidade_gestora_id bigint, unidade_executora_id bigint,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ck_financeiro_receita_arrecadada_esfera CHECK (esfera_governo IN ('municipal','estadual','federal')),
 receita_prevista_id bigint REFERENCES sigov.financeiro_receita_prevista(id), fonte_recurso_id bigint NOT NULL REFERENCES sigov.financeiro_fonte_recurso(id), natureza_receita_id bigint NOT NULL REFERENCES sigov.financeiro_natureza_receita(id), data_arrecadacao date NOT NULL, valor numeric(18,2) NOT NULL, origem_integracao varchar(30), referencia_externa varchar(120), CHECK (valor > 0)
);

CREATE INDEX IF NOT EXISTS ix_financeiro_receita_arrecadada_contexto ON sigov.financeiro_receita_arrecadada (tenant_id, entidade_id, esfera_governo, exercicio_id);

CREATE TABLE IF NOT EXISTS sigov.financeiro_empenho (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, exercicio_id bigint NOT NULL,
 esfera_governo varchar(10) NOT NULL, orgao_id bigint, unidade_gestora_id bigint, unidade_executora_id bigint,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ck_financeiro_empenho_esfera CHECK (esfera_governo IN ('municipal','estadual','federal')),
 dotacao_id bigint NOT NULL REFERENCES sigov.financeiro_dotacao(id), fornecedor_id bigint, contrato_id bigint, numero varchar(40) NOT NULL, data_empenho date NOT NULL, valor numeric(18,2) NOT NULL, valor_anulado numeric(18,2) NOT NULL DEFAULT 0, status varchar(20) NOT NULL DEFAULT 'emitido', CHECK (valor > 0 AND valor_anulado >= 0 AND valor_anulado <= valor), CHECK (status IN ('emitido','parcial','liquidado','pago','anulado'))
);

CREATE INDEX IF NOT EXISTS ix_financeiro_empenho_contexto ON sigov.financeiro_empenho (tenant_id, entidade_id, esfera_governo, exercicio_id);

CREATE TABLE IF NOT EXISTS sigov.financeiro_empenho_item (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, exercicio_id bigint NOT NULL,
 esfera_governo varchar(10) NOT NULL, orgao_id bigint, unidade_gestora_id bigint, unidade_executora_id bigint,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ck_financeiro_empenho_item_esfera CHECK (esfera_governo IN ('municipal','estadual','federal')),
 empenho_id bigint NOT NULL REFERENCES sigov.financeiro_empenho(id), descricao text NOT NULL, quantidade numeric(18,4) NOT NULL, valor_unitario numeric(18,4) NOT NULL, CHECK (quantidade > 0 AND valor_unitario >= 0)
);

CREATE INDEX IF NOT EXISTS ix_financeiro_empenho_item_contexto ON sigov.financeiro_empenho_item (tenant_id, entidade_id, esfera_governo, exercicio_id);

CREATE TABLE IF NOT EXISTS sigov.financeiro_empenho_movimento (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, exercicio_id bigint NOT NULL,
 esfera_governo varchar(10) NOT NULL, orgao_id bigint, unidade_gestora_id bigint, unidade_executora_id bigint,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ck_financeiro_empenho_movimento_esfera CHECK (esfera_governo IN ('municipal','estadual','federal')),
 empenho_id bigint NOT NULL REFERENCES sigov.financeiro_empenho(id), tipo varchar(20) NOT NULL, valor numeric(18,2) NOT NULL, justificativa text NOT NULL, data_movimento date NOT NULL, CHECK (tipo IN ('emissao','reforco','anulacao')), CHECK (valor > 0)
);

CREATE INDEX IF NOT EXISTS ix_financeiro_empenho_movimento_contexto ON sigov.financeiro_empenho_movimento (tenant_id, entidade_id, esfera_governo, exercicio_id);

CREATE TABLE IF NOT EXISTS sigov.financeiro_liquidacao (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, exercicio_id bigint NOT NULL,
 esfera_governo varchar(10) NOT NULL, orgao_id bigint, unidade_gestora_id bigint, unidade_executora_id bigint,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ck_financeiro_liquidacao_esfera CHECK (esfera_governo IN ('municipal','estadual','federal')),
 empenho_id bigint NOT NULL REFERENCES sigov.financeiro_empenho(id), numero varchar(40) NOT NULL, data_liquidacao date NOT NULL, valor numeric(18,2) NOT NULL, status varchar(20) NOT NULL DEFAULT 'liquidada', CHECK (valor > 0), CHECK (status IN ('liquidada','parcial','paga','anulada'))
);

CREATE INDEX IF NOT EXISTS ix_financeiro_liquidacao_contexto ON sigov.financeiro_liquidacao (tenant_id, entidade_id, esfera_governo, exercicio_id);

CREATE TABLE IF NOT EXISTS sigov.financeiro_liquidacao_item (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, exercicio_id bigint NOT NULL,
 esfera_governo varchar(10) NOT NULL, orgao_id bigint, unidade_gestora_id bigint, unidade_executora_id bigint,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ck_financeiro_liquidacao_item_esfera CHECK (esfera_governo IN ('municipal','estadual','federal')),
 liquidacao_id bigint NOT NULL REFERENCES sigov.financeiro_liquidacao(id), descricao text NOT NULL, valor numeric(18,2) NOT NULL, CHECK (valor > 0)
);

CREATE INDEX IF NOT EXISTS ix_financeiro_liquidacao_item_contexto ON sigov.financeiro_liquidacao_item (tenant_id, entidade_id, esfera_governo, exercicio_id);

CREATE TABLE IF NOT EXISTS sigov.financeiro_conta_bancaria (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, exercicio_id bigint NOT NULL,
 esfera_governo varchar(10) NOT NULL, orgao_id bigint, unidade_gestora_id bigint, unidade_executora_id bigint,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ck_financeiro_conta_bancaria_esfera CHECK (esfera_governo IN ('municipal','estadual','federal')),
 codigo varchar(30) NOT NULL, banco varchar(120) NOT NULL, agencia_mascarada varchar(30) NOT NULL, conta_mascarada varchar(30) NOT NULL, status varchar(20) NOT NULL DEFAULT 'ativa', CHECK (status IN ('ativa','inativa','bloqueada'))
);

CREATE INDEX IF NOT EXISTS ix_financeiro_conta_bancaria_contexto ON sigov.financeiro_conta_bancaria (tenant_id, entidade_id, esfera_governo, exercicio_id);

CREATE TABLE IF NOT EXISTS sigov.financeiro_pagamento (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, exercicio_id bigint NOT NULL,
 esfera_governo varchar(10) NOT NULL, orgao_id bigint, unidade_gestora_id bigint, unidade_executora_id bigint,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ck_financeiro_pagamento_esfera CHECK (esfera_governo IN ('municipal','estadual','federal')),
 liquidacao_id bigint NOT NULL REFERENCES sigov.financeiro_liquidacao(id), conta_bancaria_id bigint REFERENCES sigov.financeiro_conta_bancaria(id), numero varchar(40) NOT NULL, data_pagamento date NOT NULL, valor numeric(18,2) NOT NULL, status varchar(20) NOT NULL DEFAULT 'pendente', CHECK (valor > 0), CHECK (status IN ('pendente','pago','cancelado'))
);

CREATE INDEX IF NOT EXISTS ix_financeiro_pagamento_contexto ON sigov.financeiro_pagamento (tenant_id, entidade_id, esfera_governo, exercicio_id);

CREATE TABLE IF NOT EXISTS sigov.financeiro_pagamento_retencao (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, exercicio_id bigint NOT NULL,
 esfera_governo varchar(10) NOT NULL, orgao_id bigint, unidade_gestora_id bigint, unidade_executora_id bigint,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ck_financeiro_pagamento_retencao_esfera CHECK (esfera_governo IN ('municipal','estadual','federal')),
 pagamento_id bigint NOT NULL REFERENCES sigov.financeiro_pagamento(id), tipo varchar(40) NOT NULL, percentual numeric(7,4), valor numeric(18,2) NOT NULL, CHECK (percentual IS NULL OR percentual BETWEEN 0 AND 100), CHECK (valor >= 0)
);

CREATE INDEX IF NOT EXISTS ix_financeiro_pagamento_retencao_contexto ON sigov.financeiro_pagamento_retencao (tenant_id, entidade_id, esfera_governo, exercicio_id);

CREATE TABLE IF NOT EXISTS sigov.financeiro_ordem_bancaria (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, exercicio_id bigint NOT NULL,
 esfera_governo varchar(10) NOT NULL, orgao_id bigint, unidade_gestora_id bigint, unidade_executora_id bigint,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ck_financeiro_ordem_bancaria_esfera CHECK (esfera_governo IN ('municipal','estadual','federal')),
 pagamento_id bigint REFERENCES sigov.financeiro_pagamento(id), conta_bancaria_id bigint NOT NULL REFERENCES sigov.financeiro_conta_bancaria(id), numero varchar(40) NOT NULL, data_ordem date NOT NULL, valor numeric(18,2) NOT NULL, status varchar(20) NOT NULL DEFAULT 'pendente', CHECK (valor > 0), CHECK (status IN ('pendente','emitida','efetivada','cancelada'))
);

CREATE INDEX IF NOT EXISTS ix_financeiro_ordem_bancaria_contexto ON sigov.financeiro_ordem_bancaria (tenant_id, entidade_id, esfera_governo, exercicio_id);

CREATE TABLE IF NOT EXISTS sigov.financeiro_conciliacao_bancaria (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, exercicio_id bigint NOT NULL,
 esfera_governo varchar(10) NOT NULL, orgao_id bigint, unidade_gestora_id bigint, unidade_executora_id bigint,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ck_financeiro_conciliacao_bancaria_esfera CHECK (esfera_governo IN ('municipal','estadual','federal')),
 conta_bancaria_id bigint NOT NULL REFERENCES sigov.financeiro_conta_bancaria(id), competencia date NOT NULL, status varchar(20) NOT NULL DEFAULT 'pendente', justificativa_manual text, CHECK (status IN ('pendente','conciliado','divergente','cancelado')), CHECK (status <> 'conciliado' OR justificativa_manual IS NULL OR nullif(btrim(justificativa_manual),'') IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS ix_financeiro_conciliacao_bancaria_contexto ON sigov.financeiro_conciliacao_bancaria (tenant_id, entidade_id, esfera_governo, exercicio_id);

CREATE TABLE IF NOT EXISTS sigov.financeiro_conciliacao_item (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, exercicio_id bigint NOT NULL,
 esfera_governo varchar(10) NOT NULL, orgao_id bigint, unidade_gestora_id bigint, unidade_executora_id bigint,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ck_financeiro_conciliacao_item_esfera CHECK (esfera_governo IN ('municipal','estadual','federal')),
 conciliacao_id bigint NOT NULL REFERENCES sigov.financeiro_conciliacao_bancaria(id), pagamento_id bigint REFERENCES sigov.financeiro_pagamento(id), receita_arrecadada_id bigint REFERENCES sigov.financeiro_receita_arrecadada(id), valor_extrato numeric(18,2) NOT NULL, valor_sistema numeric(18,2) NOT NULL, status varchar(20) NOT NULL, CHECK (valor_extrato >= 0 AND valor_sistema >= 0), CHECK (status IN ('pendente','conciliado','divergente','cancelado'))
);

CREATE INDEX IF NOT EXISTS ix_financeiro_conciliacao_item_contexto ON sigov.financeiro_conciliacao_item (tenant_id, entidade_id, esfera_governo, exercicio_id);

CREATE TABLE IF NOT EXISTS sigov.financeiro_restos_pagar (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, exercicio_id bigint NOT NULL,
 esfera_governo varchar(10) NOT NULL, orgao_id bigint, unidade_gestora_id bigint, unidade_executora_id bigint,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ck_financeiro_restos_pagar_esfera CHECK (esfera_governo IN ('municipal','estadual','federal')),
 empenho_id bigint NOT NULL REFERENCES sigov.financeiro_empenho(id), exercicio_origem_id bigint NOT NULL, fornecedor_id bigint, valor_inscrito numeric(18,2) NOT NULL, valor_pago numeric(18,2) NOT NULL DEFAULT 0, status varchar(20) NOT NULL DEFAULT 'inscrito', justificativa_cancelamento text, CHECK (valor_inscrito > 0 AND valor_pago >= 0 AND valor_pago <= valor_inscrito), CHECK (status IN ('inscrito','processado','pago','cancelado')), CHECK (status <> 'cancelado' OR nullif(btrim(justificativa_cancelamento),'') IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS ix_financeiro_restos_pagar_contexto ON sigov.financeiro_restos_pagar (tenant_id, entidade_id, esfera_governo, exercicio_id);

CREATE TABLE IF NOT EXISTS sigov.financeiro_repasse (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, exercicio_id bigint NOT NULL,
 esfera_governo varchar(10) NOT NULL, orgao_id bigint, unidade_gestora_id bigint, unidade_executora_id bigint,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ck_financeiro_repasse_esfera CHECK (esfera_governo IN ('municipal','estadual','federal')),
 fonte_recurso_id bigint NOT NULL REFERENCES sigov.financeiro_fonte_recurso(id), data_repasse date NOT NULL, valor numeric(18,2) NOT NULL, status varchar(20) NOT NULL DEFAULT 'previsto', CHECK (valor > 0), CHECK (status IN ('previsto','recebido','devolvido','cancelado'))
);

CREATE INDEX IF NOT EXISTS ix_financeiro_repasse_contexto ON sigov.financeiro_repasse (tenant_id, entidade_id, esfera_governo, exercicio_id);

CREATE TABLE IF NOT EXISTS sigov.financeiro_transferencia (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, exercicio_id bigint NOT NULL,
 esfera_governo varchar(10) NOT NULL, orgao_id bigint, unidade_gestora_id bigint, unidade_executora_id bigint,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ck_financeiro_transferencia_esfera CHECK (esfera_governo IN ('municipal','estadual','federal')),
 conta_origem_id bigint REFERENCES sigov.financeiro_conta_bancaria(id), conta_destino_id bigint REFERENCES sigov.financeiro_conta_bancaria(id), data_transferencia date NOT NULL, valor numeric(18,2) NOT NULL, status varchar(20) NOT NULL DEFAULT 'pendente', CHECK (valor > 0), CHECK (status IN ('pendente','efetivada','cancelada'))
);

CREATE INDEX IF NOT EXISTS ix_financeiro_transferencia_contexto ON sigov.financeiro_transferencia (tenant_id, entidade_id, esfera_governo, exercicio_id);

CREATE TABLE IF NOT EXISTS sigov.contabilidade_plano_contas (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, exercicio_id bigint NOT NULL,
 esfera_governo varchar(10) NOT NULL, orgao_id bigint, unidade_gestora_id bigint, unidade_executora_id bigint,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ck_contabilidade_plano_contas_esfera CHECK (esfera_governo IN ('municipal','estadual','federal')),
 codigo varchar(40) NOT NULL, nome varchar(200) NOT NULL, natureza varchar(10) NOT NULL, aceita_lancamento boolean NOT NULL DEFAULT true, CHECK (natureza IN ('devedora','credora','mista'))
);

CREATE INDEX IF NOT EXISTS ix_contabilidade_plano_contas_contexto ON sigov.contabilidade_plano_contas (tenant_id, entidade_id, esfera_governo, exercicio_id);

CREATE TABLE IF NOT EXISTS sigov.contabilidade_evento (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, exercicio_id bigint NOT NULL,
 esfera_governo varchar(10) NOT NULL, orgao_id bigint, unidade_gestora_id bigint, unidade_executora_id bigint,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ck_contabilidade_evento_esfera CHECK (esfera_governo IN ('municipal','estadual','federal')),
 codigo varchar(30) NOT NULL, nome varchar(200) NOT NULL, ativo boolean NOT NULL DEFAULT true
);

CREATE INDEX IF NOT EXISTS ix_contabilidade_evento_contexto ON sigov.contabilidade_evento (tenant_id, entidade_id, esfera_governo, exercicio_id);

CREATE TABLE IF NOT EXISTS sigov.contabilidade_lancamento (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, exercicio_id bigint NOT NULL,
 esfera_governo varchar(10) NOT NULL, orgao_id bigint, unidade_gestora_id bigint, unidade_executora_id bigint,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ck_contabilidade_lancamento_esfera CHECK (esfera_governo IN ('municipal','estadual','federal')),
 evento_id bigint REFERENCES sigov.contabilidade_evento(id), numero varchar(40) NOT NULL, data_lancamento date NOT NULL, historico text NOT NULL, status varchar(20) NOT NULL DEFAULT 'rascunho', CHECK (status IN ('rascunho','validado','efetivado','estornado'))
);

CREATE INDEX IF NOT EXISTS ix_contabilidade_lancamento_contexto ON sigov.contabilidade_lancamento (tenant_id, entidade_id, esfera_governo, exercicio_id);

CREATE TABLE IF NOT EXISTS sigov.contabilidade_lancamento_item (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, exercicio_id bigint NOT NULL,
 esfera_governo varchar(10) NOT NULL, orgao_id bigint, unidade_gestora_id bigint, unidade_executora_id bigint,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ck_contabilidade_lancamento_item_esfera CHECK (esfera_governo IN ('municipal','estadual','federal')),
 lancamento_id bigint NOT NULL REFERENCES sigov.contabilidade_lancamento(id), conta_id bigint NOT NULL REFERENCES sigov.contabilidade_plano_contas(id), natureza varchar(7) NOT NULL, valor numeric(18,2) NOT NULL, CHECK (natureza IN ('debito','credito')), CHECK (valor > 0)
);

CREATE INDEX IF NOT EXISTS ix_contabilidade_lancamento_item_contexto ON sigov.contabilidade_lancamento_item (tenant_id, entidade_id, esfera_governo, exercicio_id);

CREATE TABLE IF NOT EXISTS sigov.contabilidade_balancete (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, exercicio_id bigint NOT NULL,
 esfera_governo varchar(10) NOT NULL, orgao_id bigint, unidade_gestora_id bigint, unidade_executora_id bigint,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ck_contabilidade_balancete_esfera CHECK (esfera_governo IN ('municipal','estadual','federal')),
 competencia date NOT NULL, total_debitos numeric(18,2) NOT NULL DEFAULT 0, total_creditos numeric(18,2) NOT NULL DEFAULT 0, status varchar(20) NOT NULL DEFAULT 'aberto', CHECK (total_debitos >= 0 AND total_creditos >= 0), CHECK (status IN ('aberto','apurado','fechado'))
);

CREATE INDEX IF NOT EXISTS ix_contabilidade_balancete_contexto ON sigov.contabilidade_balancete (tenant_id, entidade_id, esfera_governo, exercicio_id);

CREATE TABLE IF NOT EXISTS sigov.contabilidade_encerramento_exercicio (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, exercicio_id bigint NOT NULL,
 esfera_governo varchar(10) NOT NULL, orgao_id bigint, unidade_gestora_id bigint, unidade_executora_id bigint,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ck_contabilidade_encerramento_exercicio_esfera CHECK (esfera_governo IN ('municipal','estadual','federal')),
 data_encerramento date, status varchar(20) NOT NULL DEFAULT 'pendente', pendencias_criticas integer NOT NULL DEFAULT 0, justificativa text, CHECK (pendencias_criticas >= 0), CHECK (status IN ('pendente','em_processamento','encerrado','reaberto')), CHECK (status <> 'encerrado' OR pendencias_criticas = 0)
);

CREATE INDEX IF NOT EXISTS ix_contabilidade_encerramento_exercicio_contexto ON sigov.contabilidade_encerramento_exercicio (tenant_id, entidade_id, esfera_governo, exercicio_id);

CREATE TABLE IF NOT EXISTS sigov.contabilidade_prestacao_contas_lote (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, exercicio_id bigint NOT NULL,
 esfera_governo varchar(10) NOT NULL, orgao_id bigint, unidade_gestora_id bigint, unidade_executora_id bigint,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ck_contabilidade_prestacao_contas_lote_esfera CHECK (esfera_governo IN ('municipal','estadual','federal')),
 codigo varchar(40) NOT NULL, competencia date NOT NULL, destino varchar(120) NOT NULL, status varchar(20) NOT NULL DEFAULT 'rascunho', CHECK (status IN ('rascunho','validado','enviado','aceito','rejeitado','cancelado'))
);

CREATE INDEX IF NOT EXISTS ix_contabilidade_prestacao_contas_lote_contexto ON sigov.contabilidade_prestacao_contas_lote (tenant_id, entidade_id, esfera_governo, exercicio_id);

INSERT INTO sigov.permissao(modulo,chave,recurso,acao,descricao,ativo,is_deleted)
SELECT CASE WHEN v.chave LIKE 'CONTABILIDADE%' THEN 'contabilidade' WHEN v.chave LIKE 'ORCAMENTO%' THEN 'orcamento' ELSE 'financeiro' END,
 v.chave,'financeiro',CASE WHEN v.chave LIKE '%VIEW' THEN 'visualizar' WHEN v.chave LIKE '%EXPORT' THEN 'exportar' ELSE 'gerenciar' END,v.descricao,true,false
FROM (VALUES
 ('FINANCEIRO_DASHBOARD_VIEW','Financeiro Dashboard View'),
 ('FINANCEIRO_UNIDADE_MANAGE','Financeiro Unidade Manage'),
 ('ORCAMENTO_PPA_VIEW','Orcamento Ppa View'),
 ('ORCAMENTO_PPA_MANAGE','Orcamento Ppa Manage'),
 ('ORCAMENTO_LDO_MANAGE','Orcamento Ldo Manage'),
 ('ORCAMENTO_LOA_MANAGE','Orcamento Loa Manage'),
 ('ORCAMENTO_DOTACAO_VIEW','Orcamento Dotacao View'),
 ('ORCAMENTO_DOTACAO_MANAGE','Orcamento Dotacao Manage'),
 ('ORCAMENTO_CREDITO_MANAGE','Orcamento Credito Manage'),
 ('ORCAMENTO_BLOQUEIO_MANAGE','Orcamento Bloqueio Manage'),
 ('FINANCEIRO_RECEITA_VIEW','Financeiro Receita View'),
 ('FINANCEIRO_RECEITA_MANAGE','Financeiro Receita Manage'),
 ('FINANCEIRO_EMPENHO_VIEW','Financeiro Empenho View'),
 ('FINANCEIRO_EMPENHO_MANAGE','Financeiro Empenho Manage'),
 ('FINANCEIRO_LIQUIDACAO_VIEW','Financeiro Liquidacao View'),
 ('FINANCEIRO_LIQUIDACAO_MANAGE','Financeiro Liquidacao Manage'),
 ('FINANCEIRO_PAGAMENTO_VIEW','Financeiro Pagamento View'),
 ('FINANCEIRO_PAGAMENTO_MANAGE','Financeiro Pagamento Manage'),
 ('FINANCEIRO_CONCILIACAO_VIEW','Financeiro Conciliacao View'),
 ('FINANCEIRO_CONCILIACAO_MANAGE','Financeiro Conciliacao Manage'),
 ('FINANCEIRO_RESTOS_PAGAR_MANAGE','Financeiro Restos Pagar Manage'),
 ('CONTABILIDADE_VIEW','Contabilidade View'),
 ('CONTABILIDADE_LANCAMENTO_MANAGE','Contabilidade Lancamento Manage'),
 ('CONTABILIDADE_ENCERRAMENTO_MANAGE','Contabilidade Encerramento Manage'),
 ('CONTABILIDADE_PRESTACAO_CONTAS_MANAGE','Contabilidade Prestacao Contas Manage'),
 ('FINANCEIRO_RELATORIO_EXPORT','Financeiro Relatorio Export')) v(chave,descricao)
WHERE NOT EXISTS (SELECT 1 FROM sigov.permissao p WHERE p.chave=v.chave);
