-- SIGOV+ RC50.45 - prazos legais, publicação segura e atendimento digital.

create table if not exists sigov.esic_pedido (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    status varchar(40) not null default 'ABERTO',
    ativo boolean not null default true,
    is_deleted boolean not null default false
);
alter table sigov.diario_oficial_publicacao add column if not exists ativo boolean not null default true;
alter table sigov.diario_oficial_publicacao add column if not exists is_deleted boolean not null default false;
alter table sigov.diario_oficial_publicacao add column if not exists status varchar(40) not null default 'PENDENTE';
alter table sigov.esic_pedido add column if not exists ativo boolean not null default true;
alter table sigov.esic_pedido add column if not exists is_deleted boolean not null default false;
alter table sigov.esic_pedido add column if not exists status varchar(40) not null default 'ABERTO';

create unique index if not exists ux_diario_validacao_publica
    on sigov.diario_oficial_publicacao (tenant_id, codigo_validacao)
    where codigo_validacao is not null and is_deleted = false and sigiloso = false;
create index if not exists ix_esic_prazo_operacional
    on sigov.esic_pedido (tenant_id, prazo_at, status)
    where is_deleted = false and ativo = true;
create index if not exists ix_ouvidoria_prazo_operacional
    on sigov.ouvidoria_manifestacao (tenant_id, prazo_at, status)
    where is_deleted = false and ativo = true;
create unique index if not exists ux_atendimento_codigo
    on sigov.atendimento_digital_chamado (tenant_id, codigo)
    where codigo is not null and is_deleted = false;
