-- FUNC04: gestão integrada de frotas. Reaplicável e sem dados demonstrativos.
create table if not exists sigov.frotas_veiculo(
 id bigint generated always as identity primary key,tenant_id bigint not null,entidade_id bigint not null,placa varchar(12) not null,renavam varchar(20),chassi varchar(40),marca varchar(100) not null,modelo varchar(120) not null,ano_fabricacao integer,ano_modelo integer,tipo varchar(20) not null,combustivel_principal varchar(30) not null,quilometragem_atual numeric(18,2) not null default 0,horimetro_atual numeric(18,2),status varchar(20) not null default 'ATIVO',unidade_responsavel varchar(200) not null,bem_patrimonial_id bigint references sigov.patrimonio_bem(id),observacoes text,created_at timestamptz not null default now(),created_by bigint,updated_at timestamptz not null default now(),updated_by bigint,
 constraint ck_frotas_veiculo_tipo check(tipo in('PASSEIO','CAMINHONETE','CAMINHAO','ONIBUS','MOTOCICLETA','MAQUINA','OUTRO')),constraint ck_frotas_veiculo_status check(status in('ATIVO','EM_MANUTENCAO','INATIVO','BAIXADO')),constraint ck_frotas_veiculo_medidores check(quilometragem_atual>=0 and (horimetro_atual is null or horimetro_atual>=0)),constraint ck_frotas_veiculo_anos check((ano_fabricacao is null or ano_fabricacao between 1900 and 2200) and (ano_modelo is null or ano_modelo between 1900 and 2200)));
create unique index if not exists ux_frotas_veiculo_placa on sigov.frotas_veiculo(tenant_id,entidade_id,upper(placa));
create table if not exists sigov.frotas_motorista(
 id bigint generated always as identity primary key,tenant_id bigint not null,entidade_id bigint not null,nome varchar(250) not null,cpf varchar(11) not null,cnh varchar(30) not null,categoria_cnh varchar(10) not null,validade_cnh date not null,telefone varchar(40),email varchar(250),vinculo_lotacao varchar(200),status varchar(12) not null default 'ATIVO',observacoes text,created_at timestamptz not null default now(),created_by bigint,updated_at timestamptz not null default now(),updated_by bigint,constraint ck_frotas_motorista_status check(status in('ATIVO','SUSPENSO','INATIVO')));
create unique index if not exists ux_frotas_motorista_cpf on sigov.frotas_motorista(tenant_id,entidade_id,cpf);
create table if not exists sigov.frotas_utilizacao(
 id bigint generated always as identity primary key,tenant_id bigint not null,entidade_id bigint not null,veiculo_id bigint not null references sigov.frotas_veiculo(id),motorista_id bigint not null references sigov.frotas_motorista(id),unidade_solicitante varchar(200) not null,saida_em timestamptz not null,retorno_em timestamptz,km_saida numeric(18,2) not null,km_retorno numeric(18,2),destino varchar(300) not null,finalidade text not null,status varchar(12) not null default 'ABERTO',observacao text,created_at timestamptz not null default now(),created_by bigint,updated_at timestamptz not null default now(),updated_by bigint,constraint ck_frotas_util_status check(status in('ABERTO','FINALIZADO','CANCELADO')),constraint ck_frotas_util_km check(km_saida>=0 and (km_retorno is null or km_retorno>=km_saida)),constraint ck_frotas_util_datas check(retorno_em is null or retorno_em>=saida_em));
create unique index if not exists ux_frotas_util_aberta on sigov.frotas_utilizacao(tenant_id,entidade_id,veiculo_id) where status='ABERTO';
create table if not exists sigov.frotas_abastecimento(
 id bigint generated always as identity primary key,tenant_id bigint not null,entidade_id bigint not null,veiculo_id bigint not null references sigov.frotas_veiculo(id),motorista_id bigint references sigov.frotas_motorista(id),fornecedor_id bigint references sigov.compras_fornecedor(id),contrato_id bigint references sigov.compras_contrato(id),data_abastecimento timestamptz not null,km_atual numeric(18,2) not null,tipo_combustivel varchar(30) not null,litros numeric(18,4) not null,valor_unitario numeric(18,4) not null,valor_total numeric(18,2) generated always as (round(litros*valor_unitario,2)) stored,documento_fiscal varchar(100),observacao text,created_at timestamptz not null default now(),created_by bigint,constraint ck_frotas_abast_valores check(km_atual>=0 and litros>0 and valor_unitario>=0));
create table if not exists sigov.frotas_manutencao(
 id bigint generated always as identity primary key,tenant_id bigint not null,entidade_id bigint not null,veiculo_id bigint not null references sigov.frotas_veiculo(id),tipo varchar(15) not null,data_abertura timestamptz not null,data_conclusao timestamptz,km_abertura numeric(18,2) not null,fornecedor_id bigint references sigov.compras_fornecedor(id),contrato_id bigint references sigov.compras_contrato(id),descricao text not null,valor_estimado numeric(18,2) not null default 0,valor_final numeric(18,2),status varchar(15) not null default 'ABERTA',observacao text,created_at timestamptz not null default now(),created_by bigint,updated_at timestamptz not null default now(),updated_by bigint,constraint ck_frotas_manut_tipo check(tipo in('PREVENTIVA','CORRETIVA','REVISAO','PNEU','LAVAGEM','OUTRA')),constraint ck_frotas_manut_status check(status in('ABERTA','EM_EXECUCAO','CONCLUIDA','CANCELADA')),constraint ck_frotas_manut_valores check(km_abertura>=0 and valor_estimado>=0 and (valor_final is null or valor_final>=0)),constraint ck_frotas_manut_datas check(data_conclusao is null or data_conclusao>=data_abertura));
create table if not exists sigov.frotas_manutencao_historico(id bigint generated always as identity primary key,tenant_id bigint not null,entidade_id bigint not null,manutencao_id bigint not null references sigov.frotas_manutencao(id),status_anterior varchar(15),status_novo varchar(15) not null,justificativa text,usuario_id bigint,correlation_id varchar(100) not null,ocorrido_em timestamptz not null default now());
create table if not exists sigov.frotas_ordem_servico(
 id bigint generated always as identity primary key,tenant_id bigint not null,entidade_id bigint not null,exercicio integer not null,numero varchar(80) not null,veiculo_id bigint not null references sigov.frotas_veiculo(id),manutencao_id bigint references sigov.frotas_manutencao(id),fornecedor_id bigint references sigov.compras_fornecedor(id),data_abertura timestamptz not null,previsao_conclusao date,descricao text not null,status varchar(15) not null default 'ABERTA',created_at timestamptz not null default now(),created_by bigint,updated_at timestamptz not null default now(),updated_by bigint,constraint ck_frotas_os_status check(status in('ABERTA','APROVADA','EM_EXECUCAO','CONCLUIDA','CANCELADA')),constraint ck_frotas_os_previsao check(previsao_conclusao is null or previsao_conclusao>=data_abertura::date));
create unique index if not exists ux_frotas_os_numero on sigov.frotas_ordem_servico(tenant_id,entidade_id,exercicio,numero);
create table if not exists sigov.frotas_ordem_servico_item(
 id bigint generated always as identity primary key,tenant_id bigint not null,entidade_id bigint not null,ordem_servico_id bigint not null references sigov.frotas_ordem_servico(id) on delete cascade,descricao varchar(500) not null,tipo varchar(10) not null,quantidade numeric(18,4) not null,valor_unitario numeric(18,4) not null,material_id bigint references sigov.almoxarifado_material(id),almoxarifado_id bigint references sigov.almoxarifado_local(id),contrato_id bigint references sigov.compras_contrato(id),movimentacao_almoxarifado_id bigint references sigov.almoxarifado_movimentacao(id),constraint ck_frotas_os_item_tipo check(tipo in('SERVICO','PECA','MATERIAL')),constraint ck_frotas_os_item_valores check(quantidade>0 and valor_unitario>=0),constraint ck_frotas_os_item_material check(tipo='SERVICO' or material_id is not null));
create table if not exists sigov.frotas_ordem_servico_historico(id bigint generated always as identity primary key,tenant_id bigint not null,entidade_id bigint not null,ordem_servico_id bigint not null references sigov.frotas_ordem_servico(id),status_anterior varchar(15),status_novo varchar(15) not null,justificativa text,usuario_id bigint,correlation_id varchar(100) not null,ocorrido_em timestamptz not null default now());
create table if not exists sigov.frotas_documento(
 id bigint generated always as identity primary key,tenant_id bigint not null,entidade_id bigint not null,veiculo_id bigint not null references sigov.frotas_veiculo(id),tipo varchar(15) not null,numero varchar(100) not null,data_emissao date,data_vencimento date not null,status varchar(12) not null default 'VIGENTE',observacao text,created_at timestamptz not null default now(),created_by bigint,updated_at timestamptz not null default now(),updated_by bigint,constraint ck_frotas_doc_tipo check(tipo in('LICENCIAMENTO','SEGURO','TACOGRAFO','IPVA','OUTRO')),constraint ck_frotas_doc_status check(status in('VIGENTE','VENCIDO','RENOVADO','CANCELADO')),constraint ck_frotas_doc_datas check(data_emissao is null or data_vencimento>=data_emissao));
create table if not exists sigov.frotas_auditoria(id bigint generated always as identity primary key,tenant_id bigint not null,entidade_id bigint not null,entidade varchar(80) not null,registro_id bigint not null,operacao varchar(40) not null,antes jsonb,depois jsonb,usuario_id bigint,correlation_id varchar(100) not null,ocorrido_em timestamptz not null default now());
create index if not exists ix_frotas_veiculo_status on sigov.frotas_veiculo(tenant_id,entidade_id,status,unidade_responsavel);
create index if not exists ix_frotas_motorista_status on sigov.frotas_motorista(tenant_id,entidade_id,status,validade_cnh);
create index if not exists ix_frotas_utilizacao on sigov.frotas_utilizacao(tenant_id,entidade_id,veiculo_id,motorista_id,status,saida_em desc);
create index if not exists ix_frotas_abastecimento on sigov.frotas_abastecimento(tenant_id,entidade_id,veiculo_id,data_abastecimento desc);
create index if not exists ix_frotas_manutencao on sigov.frotas_manutencao(tenant_id,entidade_id,veiculo_id,status,data_abertura desc);
create index if not exists ix_frotas_os on sigov.frotas_ordem_servico(tenant_id,entidade_id,veiculo_id,status,data_abertura desc);
create index if not exists ix_frotas_documento on sigov.frotas_documento(tenant_id,entidade_id,veiculo_id,status,data_vencimento);
create index if not exists ix_frotas_auditoria on sigov.frotas_auditoria(tenant_id,entidade_id,ocorrido_em desc);
do $$ begin
 if not exists(select 1 from pg_constraint where conname='ux_frotas_documento_numero') then
  alter table sigov.frotas_documento add constraint ux_frotas_documento_numero unique(tenant_id,entidade_id,veiculo_id,tipo,numero);
 end if;
end $$;
insert into sigov.permissao(modulo,chave,recurso,acao,descricao,ativo,is_deleted) select 'frotas',v.chave,v.recurso,v.acao,v.descricao,true,false from(values
('frotas.dashboard.visualizar','frotas.dashboard','visualizar','Visualizar dashboard'),('frotas.veiculo.visualizar','frotas.veiculo','visualizar','Visualizar veículos'),('frotas.veiculo.criar','frotas.veiculo','criar','Criar veículos'),('frotas.veiculo.editar','frotas.veiculo','editar','Editar veículos'),('frotas.motorista.visualizar','frotas.motorista','visualizar','Visualizar motoristas'),('frotas.motorista.criar','frotas.motorista','criar','Criar motoristas'),('frotas.motorista.editar','frotas.motorista','editar','Editar motoristas'),('frotas.utilizacao.visualizar','frotas.utilizacao','visualizar','Visualizar utilizações'),('frotas.utilizacao.criar','frotas.utilizacao','criar','Abrir utilização'),('frotas.utilizacao.finalizar','frotas.utilizacao','finalizar','Finalizar utilização'),('frotas.abastecimento.visualizar','frotas.abastecimento','visualizar','Visualizar abastecimentos'),('frotas.abastecimento.criar','frotas.abastecimento','criar','Registrar abastecimento'),('frotas.manutencao.visualizar','frotas.manutencao','visualizar','Visualizar manutenções'),('frotas.manutencao.criar','frotas.manutencao','criar','Abrir manutenção'),('frotas.manutencao.concluir','frotas.manutencao','concluir','Concluir manutenção'),('frotas.os.visualizar','frotas.os','visualizar','Visualizar ordens de serviço'),('frotas.os.criar','frotas.os','criar','Criar ordem de serviço'),('frotas.os.aprovar','frotas.os','aprovar','Aprovar ordem de serviço'),('frotas.os.concluir','frotas.os','concluir','Concluir ordem de serviço'),('frotas.documento.visualizar','frotas.documento','visualizar','Visualizar documentos'),('frotas.documento.criar','frotas.documento','criar','Criar documentos'),('frotas.exportar','frotas','exportar','Exportar dados'))v(chave,recurso,acao,descricao) where not exists(select 1 from sigov.permissao p where p.chave=v.chave);
insert into sigov.perfil_permissao(perfil_acesso_id,permissao_id,efeito,ativo,is_deleted) select pa.id,p.id,'PERMITIR',true,false from sigov.perfil_acesso pa cross join sigov.permissao p where pa.codigo_externo='SUPERADMIN' and pa.sistemico and pa.ativo and not pa.is_deleted and p.modulo='frotas' and p.ativo and not p.is_deleted on conflict(perfil_acesso_id,permissao_id) do update set efeito='PERMITIR',ativo=true,is_deleted=false;
