-- SIGOV+ RC50.50 — Saneamento Avançado. Idempotente; Database=postgres, schema=sigov.
create schema if not exists sigov;

create table if not exists sigov.saneamento_unidade_operacional (
 id bigint generated by default as identity primary key,
 tenant_id bigint not null, entidade_id bigint, exercicio_id bigint,
 consumidor_id bigint, ligacao_id bigint, hidrometro_id bigint,
 unidade_operacional_id bigint, ordem_servico_id bigint, referencia_id bigint,
 codigo varchar(80), numero varchar(80), ano integer, tipo varchar(80),
 status varchar(40) not null default 'ATIVO', descricao text,
 data_referencia date, competencia date, latitude numeric(10,7), longitude numeric(10,7),
 quantidade numeric(16,3), valor numeric(18,2), dados jsonb not null default '{}'::jsonb,
 auditoria jsonb not null default '{}'::jsonb, correlation_id uuid not null default gen_random_uuid(),
 ativo boolean not null default true, is_deleted boolean not null default false,
 created_at timestamptz not null default now(), updated_at timestamptz, deleted_at timestamptz,
 created_by bigint, updated_by bigint, deleted_by bigint
);
alter table sigov.saneamento_unidade_operacional
 add column if not exists tenant_id bigint,
 add column if not exists entidade_id bigint,
 add column if not exists consumidor_id bigint,
 add column if not exists ligacao_id bigint,
 add column if not exists hidrometro_id bigint,
 add column if not exists unidade_operacional_id bigint,
 add column if not exists ordem_servico_id bigint,
 add column if not exists codigo varchar(80),
 add column if not exists numero varchar(80),
 add column if not exists tipo varchar(80),
 add column if not exists descricao text,
 add column if not exists valor numeric(18,2),
 add column if not exists auditoria jsonb not null default '{}'::jsonb,
 add column if not exists correlation_id uuid not null default gen_random_uuid(),
 add column if not exists created_at timestamptz not null default now(),
 add column if not exists status varchar(40) not null default 'ATIVO',
 add column if not exists data_referencia date,
 add column if not exists ativo boolean not null default true,
 add column if not exists is_deleted boolean not null default false;
create index if not exists ix_saneamento_unidade_operacional_tenant_status on sigov.saneamento_unidade_operacional(tenant_id,status,data_referencia) where is_deleted=false;

create table if not exists sigov.saneamento_ponto_gis (
 id bigint generated by default as identity primary key,
 tenant_id bigint not null, entidade_id bigint, exercicio_id bigint,
 consumidor_id bigint, ligacao_id bigint, hidrometro_id bigint,
 unidade_operacional_id bigint, ordem_servico_id bigint, referencia_id bigint,
 codigo varchar(80), numero varchar(80), ano integer, tipo varchar(80),
 status varchar(40) not null default 'ATIVO', descricao text,
 data_referencia date, competencia date, latitude numeric(10,7), longitude numeric(10,7),
 quantidade numeric(16,3), valor numeric(18,2), dados jsonb not null default '{}'::jsonb,
 auditoria jsonb not null default '{}'::jsonb, correlation_id uuid not null default gen_random_uuid(),
 ativo boolean not null default true, is_deleted boolean not null default false,
 created_at timestamptz not null default now(), updated_at timestamptz, deleted_at timestamptz,
 created_by bigint, updated_by bigint, deleted_by bigint
);
alter table sigov.saneamento_ponto_gis
 add column if not exists tenant_id bigint,
 add column if not exists entidade_id bigint,
 add column if not exists consumidor_id bigint,
 add column if not exists ligacao_id bigint,
 add column if not exists hidrometro_id bigint,
 add column if not exists unidade_operacional_id bigint,
 add column if not exists ordem_servico_id bigint,
 add column if not exists codigo varchar(80),
 add column if not exists numero varchar(80),
 add column if not exists tipo varchar(80),
 add column if not exists descricao text,
 add column if not exists valor numeric(18,2),
 add column if not exists auditoria jsonb not null default '{}'::jsonb,
 add column if not exists correlation_id uuid not null default gen_random_uuid(),
 add column if not exists created_at timestamptz not null default now(),
 add column if not exists status varchar(40) not null default 'ATIVO',
 add column if not exists data_referencia date,
 add column if not exists ativo boolean not null default true,
 add column if not exists is_deleted boolean not null default false;
create index if not exists ix_saneamento_ponto_gis_tenant_status on sigov.saneamento_ponto_gis(tenant_id,status,data_referencia) where is_deleted=false;

create table if not exists sigov.saneamento_rede (
 id bigint generated by default as identity primary key,
 tenant_id bigint not null, entidade_id bigint, exercicio_id bigint,
 consumidor_id bigint, ligacao_id bigint, hidrometro_id bigint,
 unidade_operacional_id bigint, ordem_servico_id bigint, referencia_id bigint,
 codigo varchar(80), numero varchar(80), ano integer, tipo varchar(80),
 status varchar(40) not null default 'ATIVO', descricao text,
 data_referencia date, competencia date, latitude numeric(10,7), longitude numeric(10,7),
 quantidade numeric(16,3), valor numeric(18,2), dados jsonb not null default '{}'::jsonb,
 auditoria jsonb not null default '{}'::jsonb, correlation_id uuid not null default gen_random_uuid(),
 ativo boolean not null default true, is_deleted boolean not null default false,
 created_at timestamptz not null default now(), updated_at timestamptz, deleted_at timestamptz,
 created_by bigint, updated_by bigint, deleted_by bigint
);
alter table sigov.saneamento_rede
 add column if not exists tenant_id bigint,
 add column if not exists entidade_id bigint,
 add column if not exists consumidor_id bigint,
 add column if not exists ligacao_id bigint,
 add column if not exists hidrometro_id bigint,
 add column if not exists unidade_operacional_id bigint,
 add column if not exists ordem_servico_id bigint,
 add column if not exists codigo varchar(80),
 add column if not exists numero varchar(80),
 add column if not exists tipo varchar(80),
 add column if not exists descricao text,
 add column if not exists valor numeric(18,2),
 add column if not exists auditoria jsonb not null default '{}'::jsonb,
 add column if not exists correlation_id uuid not null default gen_random_uuid(),
 add column if not exists created_at timestamptz not null default now(),
 add column if not exists status varchar(40) not null default 'ATIVO',
 add column if not exists data_referencia date,
 add column if not exists ativo boolean not null default true,
 add column if not exists is_deleted boolean not null default false;
create index if not exists ix_saneamento_rede_tenant_status on sigov.saneamento_rede(tenant_id,status,data_referencia) where is_deleted=false;

create table if not exists sigov.saneamento_trecho_rede (
 id bigint generated by default as identity primary key,
 tenant_id bigint not null, entidade_id bigint, exercicio_id bigint,
 consumidor_id bigint, ligacao_id bigint, hidrometro_id bigint,
 unidade_operacional_id bigint, ordem_servico_id bigint, referencia_id bigint,
 codigo varchar(80), numero varchar(80), ano integer, tipo varchar(80),
 status varchar(40) not null default 'ATIVO', descricao text,
 data_referencia date, competencia date, latitude numeric(10,7), longitude numeric(10,7),
 quantidade numeric(16,3), valor numeric(18,2), dados jsonb not null default '{}'::jsonb,
 auditoria jsonb not null default '{}'::jsonb, correlation_id uuid not null default gen_random_uuid(),
 ativo boolean not null default true, is_deleted boolean not null default false,
 created_at timestamptz not null default now(), updated_at timestamptz, deleted_at timestamptz,
 created_by bigint, updated_by bigint, deleted_by bigint
);
alter table sigov.saneamento_trecho_rede
 add column if not exists tenant_id bigint,
 add column if not exists entidade_id bigint,
 add column if not exists consumidor_id bigint,
 add column if not exists ligacao_id bigint,
 add column if not exists hidrometro_id bigint,
 add column if not exists unidade_operacional_id bigint,
 add column if not exists ordem_servico_id bigint,
 add column if not exists codigo varchar(80),
 add column if not exists numero varchar(80),
 add column if not exists tipo varchar(80),
 add column if not exists descricao text,
 add column if not exists valor numeric(18,2),
 add column if not exists auditoria jsonb not null default '{}'::jsonb,
 add column if not exists correlation_id uuid not null default gen_random_uuid(),
 add column if not exists created_at timestamptz not null default now(),
 add column if not exists status varchar(40) not null default 'ATIVO',
 add column if not exists data_referencia date,
 add column if not exists ativo boolean not null default true,
 add column if not exists is_deleted boolean not null default false;
create index if not exists ix_saneamento_trecho_rede_tenant_status on sigov.saneamento_trecho_rede(tenant_id,status,data_referencia) where is_deleted=false;

create table if not exists sigov.saneamento_equipamento_operacional (
 id bigint generated by default as identity primary key,
 tenant_id bigint not null, entidade_id bigint, exercicio_id bigint,
 consumidor_id bigint, ligacao_id bigint, hidrometro_id bigint,
 unidade_operacional_id bigint, ordem_servico_id bigint, referencia_id bigint,
 codigo varchar(80), numero varchar(80), ano integer, tipo varchar(80),
 status varchar(40) not null default 'ATIVO', descricao text,
 data_referencia date, competencia date, latitude numeric(10,7), longitude numeric(10,7),
 quantidade numeric(16,3), valor numeric(18,2), dados jsonb not null default '{}'::jsonb,
 auditoria jsonb not null default '{}'::jsonb, correlation_id uuid not null default gen_random_uuid(),
 ativo boolean not null default true, is_deleted boolean not null default false,
 created_at timestamptz not null default now(), updated_at timestamptz, deleted_at timestamptz,
 created_by bigint, updated_by bigint, deleted_by bigint
);
alter table sigov.saneamento_equipamento_operacional
 add column if not exists tenant_id bigint,
 add column if not exists entidade_id bigint,
 add column if not exists consumidor_id bigint,
 add column if not exists ligacao_id bigint,
 add column if not exists hidrometro_id bigint,
 add column if not exists unidade_operacional_id bigint,
 add column if not exists ordem_servico_id bigint,
 add column if not exists codigo varchar(80),
 add column if not exists numero varchar(80),
 add column if not exists tipo varchar(80),
 add column if not exists descricao text,
 add column if not exists valor numeric(18,2),
 add column if not exists auditoria jsonb not null default '{}'::jsonb,
 add column if not exists correlation_id uuid not null default gen_random_uuid(),
 add column if not exists created_at timestamptz not null default now(),
 add column if not exists status varchar(40) not null default 'ATIVO',
 add column if not exists data_referencia date,
 add column if not exists ativo boolean not null default true,
 add column if not exists is_deleted boolean not null default false;
create index if not exists ix_saneamento_equipamento_operacional_tenant_status on sigov.saneamento_equipamento_operacional(tenant_id,status,data_referencia) where is_deleted=false;

create table if not exists sigov.saneamento_laboratorio_parametro (
 id bigint generated by default as identity primary key,
 tenant_id bigint not null, entidade_id bigint, exercicio_id bigint,
 consumidor_id bigint, ligacao_id bigint, hidrometro_id bigint,
 unidade_operacional_id bigint, ordem_servico_id bigint, referencia_id bigint,
 codigo varchar(80), numero varchar(80), ano integer, tipo varchar(80),
 status varchar(40) not null default 'ATIVO', descricao text,
 data_referencia date, competencia date, latitude numeric(10,7), longitude numeric(10,7),
 quantidade numeric(16,3), valor numeric(18,2), dados jsonb not null default '{}'::jsonb,
 auditoria jsonb not null default '{}'::jsonb, correlation_id uuid not null default gen_random_uuid(),
 ativo boolean not null default true, is_deleted boolean not null default false,
 created_at timestamptz not null default now(), updated_at timestamptz, deleted_at timestamptz,
 created_by bigint, updated_by bigint, deleted_by bigint
);
alter table sigov.saneamento_laboratorio_parametro
 add column if not exists tenant_id bigint,
 add column if not exists entidade_id bigint,
 add column if not exists consumidor_id bigint,
 add column if not exists ligacao_id bigint,
 add column if not exists hidrometro_id bigint,
 add column if not exists unidade_operacional_id bigint,
 add column if not exists ordem_servico_id bigint,
 add column if not exists codigo varchar(80),
 add column if not exists numero varchar(80),
 add column if not exists tipo varchar(80),
 add column if not exists descricao text,
 add column if not exists valor numeric(18,2),
 add column if not exists auditoria jsonb not null default '{}'::jsonb,
 add column if not exists correlation_id uuid not null default gen_random_uuid(),
 add column if not exists created_at timestamptz not null default now(),
 add column if not exists status varchar(40) not null default 'ATIVO',
 add column if not exists data_referencia date,
 add column if not exists ativo boolean not null default true,
 add column if not exists is_deleted boolean not null default false;
create index if not exists ix_saneamento_laboratorio_parametro_tenant_status on sigov.saneamento_laboratorio_parametro(tenant_id,status,data_referencia) where is_deleted=false;

create table if not exists sigov.saneamento_laboratorio_ponto_coleta (
 id bigint generated by default as identity primary key,
 tenant_id bigint not null, entidade_id bigint, exercicio_id bigint,
 consumidor_id bigint, ligacao_id bigint, hidrometro_id bigint,
 unidade_operacional_id bigint, ordem_servico_id bigint, referencia_id bigint,
 codigo varchar(80), numero varchar(80), ano integer, tipo varchar(80),
 status varchar(40) not null default 'ATIVO', descricao text,
 data_referencia date, competencia date, latitude numeric(10,7), longitude numeric(10,7),
 quantidade numeric(16,3), valor numeric(18,2), dados jsonb not null default '{}'::jsonb,
 auditoria jsonb not null default '{}'::jsonb, correlation_id uuid not null default gen_random_uuid(),
 ativo boolean not null default true, is_deleted boolean not null default false,
 created_at timestamptz not null default now(), updated_at timestamptz, deleted_at timestamptz,
 created_by bigint, updated_by bigint, deleted_by bigint
);
alter table sigov.saneamento_laboratorio_ponto_coleta
 add column if not exists tenant_id bigint,
 add column if not exists entidade_id bigint,
 add column if not exists consumidor_id bigint,
 add column if not exists ligacao_id bigint,
 add column if not exists hidrometro_id bigint,
 add column if not exists unidade_operacional_id bigint,
 add column if not exists ordem_servico_id bigint,
 add column if not exists codigo varchar(80),
 add column if not exists numero varchar(80),
 add column if not exists tipo varchar(80),
 add column if not exists descricao text,
 add column if not exists valor numeric(18,2),
 add column if not exists auditoria jsonb not null default '{}'::jsonb,
 add column if not exists correlation_id uuid not null default gen_random_uuid(),
 add column if not exists created_at timestamptz not null default now(),
 add column if not exists status varchar(40) not null default 'ATIVO',
 add column if not exists data_referencia date,
 add column if not exists ativo boolean not null default true,
 add column if not exists is_deleted boolean not null default false;
create index if not exists ix_saneamento_laboratorio_ponto_coleta_tenant_status on sigov.saneamento_laboratorio_ponto_coleta(tenant_id,status,data_referencia) where is_deleted=false;

create table if not exists sigov.saneamento_laboratorio_amostra (
 id bigint generated by default as identity primary key,
 tenant_id bigint not null, entidade_id bigint, exercicio_id bigint,
 consumidor_id bigint, ligacao_id bigint, hidrometro_id bigint,
 unidade_operacional_id bigint, ordem_servico_id bigint, referencia_id bigint,
 codigo varchar(80), numero varchar(80), ano integer, tipo varchar(80),
 status varchar(40) not null default 'ATIVO', descricao text,
 data_referencia date, competencia date, latitude numeric(10,7), longitude numeric(10,7),
 quantidade numeric(16,3), valor numeric(18,2), dados jsonb not null default '{}'::jsonb,
 auditoria jsonb not null default '{}'::jsonb, correlation_id uuid not null default gen_random_uuid(),
 ativo boolean not null default true, is_deleted boolean not null default false,
 created_at timestamptz not null default now(), updated_at timestamptz, deleted_at timestamptz,
 created_by bigint, updated_by bigint, deleted_by bigint
);
alter table sigov.saneamento_laboratorio_amostra
 add column if not exists tenant_id bigint,
 add column if not exists entidade_id bigint,
 add column if not exists consumidor_id bigint,
 add column if not exists ligacao_id bigint,
 add column if not exists hidrometro_id bigint,
 add column if not exists unidade_operacional_id bigint,
 add column if not exists ordem_servico_id bigint,
 add column if not exists codigo varchar(80),
 add column if not exists numero varchar(80),
 add column if not exists tipo varchar(80),
 add column if not exists descricao text,
 add column if not exists valor numeric(18,2),
 add column if not exists auditoria jsonb not null default '{}'::jsonb,
 add column if not exists correlation_id uuid not null default gen_random_uuid(),
 add column if not exists created_at timestamptz not null default now(),
 add column if not exists status varchar(40) not null default 'ATIVO',
 add column if not exists data_referencia date,
 add column if not exists ativo boolean not null default true,
 add column if not exists is_deleted boolean not null default false;
create index if not exists ix_saneamento_laboratorio_amostra_tenant_status on sigov.saneamento_laboratorio_amostra(tenant_id,status,data_referencia) where is_deleted=false;

create table if not exists sigov.saneamento_laboratorio_ensaio (
 id bigint generated by default as identity primary key,
 tenant_id bigint not null, entidade_id bigint, exercicio_id bigint,
 consumidor_id bigint, ligacao_id bigint, hidrometro_id bigint,
 unidade_operacional_id bigint, ordem_servico_id bigint, referencia_id bigint,
 codigo varchar(80), numero varchar(80), ano integer, tipo varchar(80),
 status varchar(40) not null default 'ATIVO', descricao text,
 data_referencia date, competencia date, latitude numeric(10,7), longitude numeric(10,7),
 quantidade numeric(16,3), valor numeric(18,2), dados jsonb not null default '{}'::jsonb,
 auditoria jsonb not null default '{}'::jsonb, correlation_id uuid not null default gen_random_uuid(),
 ativo boolean not null default true, is_deleted boolean not null default false,
 created_at timestamptz not null default now(), updated_at timestamptz, deleted_at timestamptz,
 created_by bigint, updated_by bigint, deleted_by bigint
);
alter table sigov.saneamento_laboratorio_ensaio
 add column if not exists tenant_id bigint,
 add column if not exists entidade_id bigint,
 add column if not exists consumidor_id bigint,
 add column if not exists ligacao_id bigint,
 add column if not exists hidrometro_id bigint,
 add column if not exists unidade_operacional_id bigint,
 add column if not exists ordem_servico_id bigint,
 add column if not exists codigo varchar(80),
 add column if not exists numero varchar(80),
 add column if not exists tipo varchar(80),
 add column if not exists descricao text,
 add column if not exists valor numeric(18,2),
 add column if not exists auditoria jsonb not null default '{}'::jsonb,
 add column if not exists correlation_id uuid not null default gen_random_uuid(),
 add column if not exists created_at timestamptz not null default now(),
 add column if not exists status varchar(40) not null default 'ATIVO',
 add column if not exists data_referencia date,
 add column if not exists ativo boolean not null default true,
 add column if not exists is_deleted boolean not null default false;
create index if not exists ix_saneamento_laboratorio_ensaio_tenant_status on sigov.saneamento_laboratorio_ensaio(tenant_id,status,data_referencia) where is_deleted=false;

create table if not exists sigov.saneamento_qualidade_alerta (
 id bigint generated by default as identity primary key,
 tenant_id bigint not null, entidade_id bigint, exercicio_id bigint,
 consumidor_id bigint, ligacao_id bigint, hidrometro_id bigint,
 unidade_operacional_id bigint, ordem_servico_id bigint, referencia_id bigint,
 codigo varchar(80), numero varchar(80), ano integer, tipo varchar(80),
 status varchar(40) not null default 'ATIVO', descricao text,
 data_referencia date, competencia date, latitude numeric(10,7), longitude numeric(10,7),
 quantidade numeric(16,3), valor numeric(18,2), dados jsonb not null default '{}'::jsonb,
 auditoria jsonb not null default '{}'::jsonb, correlation_id uuid not null default gen_random_uuid(),
 ativo boolean not null default true, is_deleted boolean not null default false,
 created_at timestamptz not null default now(), updated_at timestamptz, deleted_at timestamptz,
 created_by bigint, updated_by bigint, deleted_by bigint
);
alter table sigov.saneamento_qualidade_alerta
 add column if not exists tenant_id bigint,
 add column if not exists entidade_id bigint,
 add column if not exists consumidor_id bigint,
 add column if not exists ligacao_id bigint,
 add column if not exists hidrometro_id bigint,
 add column if not exists unidade_operacional_id bigint,
 add column if not exists ordem_servico_id bigint,
 add column if not exists codigo varchar(80),
 add column if not exists numero varchar(80),
 add column if not exists tipo varchar(80),
 add column if not exists descricao text,
 add column if not exists valor numeric(18,2),
 add column if not exists auditoria jsonb not null default '{}'::jsonb,
 add column if not exists correlation_id uuid not null default gen_random_uuid(),
 add column if not exists created_at timestamptz not null default now(),
 add column if not exists status varchar(40) not null default 'ATIVO',
 add column if not exists data_referencia date,
 add column if not exists ativo boolean not null default true,
 add column if not exists is_deleted boolean not null default false;
create index if not exists ix_saneamento_qualidade_alerta_tenant_status on sigov.saneamento_qualidade_alerta(tenant_id,status,data_referencia) where is_deleted=false;

create table if not exists sigov.saneamento_gis_qualidade_evento (
 id bigint generated by default as identity primary key,
 tenant_id bigint not null, entidade_id bigint, exercicio_id bigint,
 consumidor_id bigint, ligacao_id bigint, hidrometro_id bigint,
 unidade_operacional_id bigint, ordem_servico_id bigint, referencia_id bigint,
 codigo varchar(80), numero varchar(80), ano integer, tipo varchar(80),
 status varchar(40) not null default 'ATIVO', descricao text,
 data_referencia date, competencia date, latitude numeric(10,7), longitude numeric(10,7),
 quantidade numeric(16,3), valor numeric(18,2), dados jsonb not null default '{}'::jsonb,
 auditoria jsonb not null default '{}'::jsonb, correlation_id uuid not null default gen_random_uuid(),
 ativo boolean not null default true, is_deleted boolean not null default false,
 created_at timestamptz not null default now(), updated_at timestamptz, deleted_at timestamptz,
 created_by bigint, updated_by bigint, deleted_by bigint
);
alter table sigov.saneamento_gis_qualidade_evento
 add column if not exists tenant_id bigint,
 add column if not exists entidade_id bigint,
 add column if not exists consumidor_id bigint,
 add column if not exists ligacao_id bigint,
 add column if not exists hidrometro_id bigint,
 add column if not exists unidade_operacional_id bigint,
 add column if not exists ordem_servico_id bigint,
 add column if not exists codigo varchar(80),
 add column if not exists numero varchar(80),
 add column if not exists tipo varchar(80),
 add column if not exists descricao text,
 add column if not exists valor numeric(18,2),
 add column if not exists auditoria jsonb not null default '{}'::jsonb,
 add column if not exists correlation_id uuid not null default gen_random_uuid(),
 add column if not exists created_at timestamptz not null default now(),
 add column if not exists status varchar(40) not null default 'ATIVO',
 add column if not exists data_referencia date,
 add column if not exists ativo boolean not null default true,
 add column if not exists is_deleted boolean not null default false;
create index if not exists ix_saneamento_gis_qualidade_evento_tenant_status on sigov.saneamento_gis_qualidade_evento(tenant_id,status,data_referencia) where is_deleted=false;

do $$ begin
 alter table sigov.saneamento_ponto_gis add constraint ck_saneamento_ponto_gis_coordenadas check ((latitude is null and longitude is null) or (latitude between -90 and 90 and longitude between -180 and 180));
exception when duplicate_object then null; end $$;
