CREATE SCHEMA IF NOT EXISTS sigov;

CREATE TABLE IF NOT EXISTS sigov.identidade_sessao (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint NOT NULL,
    entidade_id bigint NOT NULL,
    exercicio_id bigint NULL,
    usuario_id bigint NOT NULL,
    token_hash char(64) NOT NULL UNIQUE,
    auth_version bigint NOT NULL DEFAULT 1,
    criada_at timestamptz NOT NULL DEFAULT now(),
    ultimo_acesso_at timestamptz NULL,
    expira_at timestamptz NOT NULL,
    encerrada_at timestamptz NULL,
    revogada_at timestamptz NULL,
    motivo_encerramento varchar(80) NULL,
    ip_hash char(64) NULL,
    user_agent_sanitizado varchar(200) NULL,
    correlation_id uuid NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by bigint NULL,
    updated_at timestamptz NULL,
    updated_by bigint NULL,
    deleted_at timestamptz NULL,
    deleted_by bigint NULL,
    is_deleted boolean NOT NULL DEFAULT false
);

ALTER TABLE IF EXISTS sigov.identidade_sessao ADD COLUMN IF NOT EXISTS exercicio_id bigint NULL;
ALTER TABLE IF EXISTS sigov.identidade_sessao ADD COLUMN IF NOT EXISTS auth_version bigint NOT NULL DEFAULT 1;
ALTER TABLE IF EXISTS sigov.identidade_sessao ADD COLUMN IF NOT EXISTS ultimo_acesso_at timestamptz NULL;
ALTER TABLE IF EXISTS sigov.identidade_sessao ADD COLUMN IF NOT EXISTS revogada_at timestamptz NULL;
ALTER TABLE IF EXISTS sigov.identidade_sessao ADD COLUMN IF NOT EXISTS ip_hash char(64) NULL;
ALTER TABLE IF EXISTS sigov.identidade_sessao ADD COLUMN IF NOT EXISTS user_agent_sanitizado varchar(200) NULL;
ALTER TABLE IF EXISTS sigov.identidade_sessao ADD COLUMN IF NOT EXISTS correlation_id uuid NULL;
ALTER TABLE IF EXISTS sigov.identidade_sessao ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE IF EXISTS sigov.identidade_sessao ADD COLUMN IF NOT EXISTS created_by bigint NULL;
ALTER TABLE IF EXISTS sigov.identidade_sessao ADD COLUMN IF NOT EXISTS updated_at timestamptz NULL;
ALTER TABLE IF EXISTS sigov.identidade_sessao ADD COLUMN IF NOT EXISTS updated_by bigint NULL;
ALTER TABLE IF EXISTS sigov.identidade_sessao ADD COLUMN IF NOT EXISTS deleted_at timestamptz NULL;
ALTER TABLE IF EXISTS sigov.identidade_sessao ADD COLUMN IF NOT EXISTS deleted_by bigint NULL;
ALTER TABLE IF EXISTS sigov.identidade_sessao ADD COLUMN IF NOT EXISTS is_deleted boolean NOT NULL DEFAULT false;

DO $$
BEGIN
    IF to_regclass('sigov.identidade_sessao') IS NOT NULL THEN
        UPDATE sigov.identidade_sessao
           SET auth_version = 1
         WHERE auth_version IS NULL;

        UPDATE sigov.identidade_sessao
           SET created_at = coalesce(created_at, criada_at, now())
         WHERE created_at IS NULL;

        UPDATE sigov.identidade_sessao
           SET is_deleted = false
         WHERE is_deleted IS NULL;
    END IF;
END $$;

ALTER TABLE IF EXISTS sigov.identidade_sessao ALTER COLUMN auth_version SET DEFAULT 1;
ALTER TABLE IF EXISTS sigov.identidade_sessao ALTER COLUMN auth_version SET NOT NULL;
ALTER TABLE IF EXISTS sigov.identidade_sessao ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE IF EXISTS sigov.identidade_sessao ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE IF EXISTS sigov.identidade_sessao ALTER COLUMN is_deleted SET DEFAULT false;
ALTER TABLE IF EXISTS sigov.identidade_sessao ALTER COLUMN is_deleted SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
          FROM pg_constraint
         WHERE conrelid = 'sigov.identidade_sessao'::regclass
           AND conname = 'ck_identidade_sessao_expira_at'
    ) THEN
        ALTER TABLE sigov.identidade_sessao
            ADD CONSTRAINT ck_identidade_sessao_expira_at CHECK (expira_at > criada_at) NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1
          FROM pg_constraint
         WHERE conrelid = 'sigov.identidade_sessao'::regclass
           AND conname = 'ck_identidade_sessao_auth_version'
    ) THEN
        ALTER TABLE sigov.identidade_sessao
            ADD CONSTRAINT ck_identidade_sessao_auth_version CHECK (auth_version >= 1) NOT VALID;
    END IF;

    IF to_regclass('sigov.tenant') IS NOT NULL AND NOT EXISTS (
        SELECT 1
          FROM pg_constraint
         WHERE conrelid = 'sigov.identidade_sessao'::regclass
           AND conname = 'fk_identidade_sessao_tenant'
    ) THEN
        ALTER TABLE sigov.identidade_sessao
            ADD CONSTRAINT fk_identidade_sessao_tenant FOREIGN KEY (tenant_id) REFERENCES sigov.tenant(id) NOT VALID;
    END IF;

    IF to_regclass('sigov.entidade') IS NOT NULL AND NOT EXISTS (
        SELECT 1
          FROM pg_constraint
         WHERE conrelid = 'sigov.identidade_sessao'::regclass
           AND conname = 'fk_identidade_sessao_entidade'
    ) THEN
        ALTER TABLE sigov.identidade_sessao
            ADD CONSTRAINT fk_identidade_sessao_entidade FOREIGN KEY (entidade_id) REFERENCES sigov.entidade(id) NOT VALID;
    END IF;

    IF to_regclass('sigov.exercicio') IS NOT NULL AND NOT EXISTS (
        SELECT 1
          FROM pg_constraint
         WHERE conrelid = 'sigov.identidade_sessao'::regclass
           AND conname = 'fk_identidade_sessao_exercicio'
    ) THEN
        ALTER TABLE sigov.identidade_sessao
            ADD CONSTRAINT fk_identidade_sessao_exercicio FOREIGN KEY (exercicio_id) REFERENCES sigov.exercicio(id) NOT VALID;
    END IF;

    IF to_regclass('sigov.usuario') IS NOT NULL AND NOT EXISTS (
        SELECT 1
          FROM pg_constraint
         WHERE conrelid = 'sigov.identidade_sessao'::regclass
           AND conname = 'fk_identidade_sessao_usuario'
    ) THEN
        ALTER TABLE sigov.identidade_sessao
            ADD CONSTRAINT fk_identidade_sessao_usuario FOREIGN KEY (usuario_id) REFERENCES sigov.usuario(id) NOT VALID;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS ix_identidade_sessao_usuario_ativa
    ON sigov.identidade_sessao (usuario_id, tenant_id, expira_at)
    WHERE encerrada_at IS NULL AND coalesce(is_deleted, false) = false;

CREATE INDEX IF NOT EXISTS ix_identidade_sessao_tenant_entidade
    ON sigov.identidade_sessao (tenant_id, entidade_id, usuario_id);

CREATE INDEX IF NOT EXISTS ix_identidade_sessao_token_hash_ativa
    ON sigov.identidade_sessao (token_hash)
    WHERE encerrada_at IS NULL AND coalesce(is_deleted, false) = false;
