create schema if not exists sigov;

create table if not exists sigov.agro_indicador (id bigint generated always as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint null references sigov.entidade(id), codigo varchar(100) not null, nome varchar(250) not null, descricao text null, categoria varchar(100) not null, unidade_medida varchar(40) null, formula_json jsonb not null default '{}'::jsonb, publico boolean not null default false, ativo boolean not null default true, is_deleted boolean not null default false, created_at timestamptz not null default now(), created_by bigint null, updated_at timestamptz null, updated_by bigint null, deleted_at timestamptz null, deleted_by bigint null, correlation_id uuid null, constraint uk_agro_indicador_tenant_entidade_codigo unique(tenant_id, entidade_id, codigo));
create table if not exists sigov.agro_indicador_valor (id bigint generated always as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint null references sigov.entidade(id), exercicio_id bigint null references sigov.exercicio(id), indicador_id bigint not null references sigov.agro_indicador(id), competencia varchar(20) null, valor numeric(18,4) not null default 0, metadados jsonb not null default '{}'::jsonb, calculado_at timestamptz not null default now());
create table if not exists sigov.agro_relatorio_modelo (id bigint generated always as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint null references sigov.entidade(id), codigo varchar(100) not null, nome varchar(250) not null, descricao text null, tipo_relatorio varchar(100) not null, formato_padrao varchar(20) not null default 'HTML', filtros_json jsonb not null default '[]'::jsonb, colunas_json jsonb not null default '[]'::jsonb, publico_no_tenant boolean not null default false, contem_dados_pessoais boolean not null default false, contem_dados_sensiveis boolean not null default false, ativo boolean not null default true, is_deleted boolean not null default false, created_at timestamptz not null default now(), created_by bigint null, updated_at timestamptz null, updated_by bigint null, deleted_at timestamptz null, deleted_by bigint null, correlation_id uuid null, constraint uk_agro_relatorio_modelo_tenant_entidade_codigo unique(tenant_id, entidade_id, codigo));
create table if not exists sigov.agro_relatorio_execucao (id bigint generated always as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint null references sigov.entidade(id), exercicio_id bigint null references sigov.exercicio(id), modelo_id bigint null references sigov.agro_relatorio_modelo(id), usuario_id bigint null references sigov.usuario(id), formato varchar(20) not null, parametros_json jsonb not null default '{}'::jsonb, status varchar(40) not null, total_linhas bigint null, iniciou_at timestamptz not null default now(), finalizou_at timestamptz null, erro text null, conteudo_resumo jsonb null, correlation_id uuid null);
create table if not exists sigov.agro_dataset_publico (id bigint generated always as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint null references sigov.entidade(id), codigo varchar(100) not null, nome varchar(250) not null, descricao text null, tipo_dataset varchar(100) not null, formato_padrao varchar(20) not null default 'CSV', anonimizado boolean not null default true, publico boolean not null default false, periodicidade_atualizacao varchar(80) null, ultima_publicacao_at timestamptz null, ativo boolean not null default true, is_deleted boolean not null default false, created_at timestamptz not null default now(), created_by bigint null, updated_at timestamptz null, updated_by bigint null, deleted_at timestamptz null, deleted_by bigint null, correlation_id uuid null, constraint uk_agro_dataset_publico_tenant_entidade_codigo unique(tenant_id, entidade_id, codigo), constraint ck_agro_dataset_publico_lgpd check (publico = false or anonimizado = true));
create table if not exists sigov.agro_dataset_publicacao (id bigint generated always as identity primary key, tenant_id bigint not null references sigov.tenant(id), dataset_id bigint not null references sigov.agro_dataset_publico(id), status varchar(40) not null, formato varchar(20) not null, conteudo_texto text null, storage_key varchar(500) null, hash_sha256 varchar(128) null, total_registros bigint null, publicado_at timestamptz null, publicado_by bigint null references sigov.usuario(id), erro text null, created_at timestamptz not null default now());
create table if not exists sigov.agro_dataset_download_log (id bigint generated always as identity primary key, tenant_id bigint not null references sigov.tenant(id), dataset_id bigint null references sigov.agro_dataset_publico(id), publicacao_id bigint null references sigov.agro_dataset_publicacao(id), formato varchar(20) null, ip varchar(80) null, user_agent text null, baixado_at timestamptz not null default now(), metadados jsonb not null default '{}'::jsonb);
create table if not exists sigov.agro_dicionario_dados (id bigint generated always as identity primary key, tenant_id bigint null references sigov.tenant(id), tabela_nome varchar(150) not null, campo_nome varchar(150) null, nome_amigavel varchar(250) null, descricao text null, categoria varchar(100) null, dado_pessoal boolean not null default false, dado_sensivel boolean not null default false, publico boolean not null default false, mascara_padrao varchar(80) null, created_at timestamptz not null default now(), constraint ck_agro_dicionario_mascara check ((dado_pessoal = false and dado_sensivel = false) or mascara_padrao is not null));
create table if not exists sigov.agro_painel_comercial_config (id bigint generated always as identity primary key, tenant_id bigint not null references sigov.tenant(id), entidade_id bigint null references sigov.entidade(id), titulo varchar(250) not null, subtitulo text null, mostrar_produtores boolean not null default true, mostrar_producao boolean not null default true, mostrar_pecuaria boolean not null default true, mostrar_mapa boolean not null default true, mostrar_programas boolean not null default true, mostrar_estradas boolean not null default true, mostrar_feiras boolean not null default true, mostrar_agroindustrias boolean not null default true, configuracao_json jsonb not null default '{}'::jsonb, ativo boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz null, constraint uk_agro_painel_comercial_tenant_entidade unique(tenant_id, entidade_id));

create index if not exists idx_agro_indicador_tenant_codigo on sigov.agro_indicador(tenant_id,codigo) where is_deleted=false;
create index if not exists idx_agro_indicador_valor_tenant_indicador on sigov.agro_indicador_valor(tenant_id,indicador_id);
create index if not exists idx_agro_relatorio_modelo_tenant_codigo on sigov.agro_relatorio_modelo(tenant_id,codigo) where is_deleted=false;
create index if not exists idx_agro_relatorio_execucao_tenant on sigov.agro_relatorio_execucao(tenant_id,entidade_id,exercicio_id,iniciou_at desc);
create index if not exists idx_agro_dataset_publico_tenant_codigo on sigov.agro_dataset_publico(tenant_id,codigo) where is_deleted=false;
create index if not exists idx_agro_dataset_publicacao_tenant_status on sigov.agro_dataset_publicacao(tenant_id,status,formato);
create index if not exists idx_agro_dataset_download_tenant on sigov.agro_dataset_download_log(tenant_id,baixado_at desc);
create index if not exists idx_agro_dicionario_tabela on sigov.agro_dicionario_dados(tabela_nome,campo_nome);
create index if not exists idx_agro_painel_comercial_tenant on sigov.agro_painel_comercial_config(tenant_id,entidade_id) where ativo=true;

create or replace view sigov.vw_agro_bi_resumo as
with escopos as (
    select id as tenant_id, null::bigint as entidade_id from sigov.tenant where ativo=true and is_deleted=false
    union select tenant_id, entidade_id from sigov.agro_produtor where is_deleted=false
    union select tenant_id, entidade_id from sigov.agro_propriedade where is_deleted=false
)
select e.tenant_id, e.entidade_id,
       (select count(*) from sigov.agro_produtor p where p.tenant_id=e.tenant_id and p.is_deleted=false and (e.entidade_id is null or p.entidade_id=e.entidade_id)) as total_produtores,
       (select count(*) from sigov.agro_produtor p where p.tenant_id=e.tenant_id and p.ativo=true and p.is_deleted=false and (e.entidade_id is null or p.entidade_id=e.entidade_id)) as produtores_ativos,
       (select count(*) from sigov.agro_propriedade p where p.tenant_id=e.tenant_id and p.is_deleted=false and (e.entidade_id is null or p.entidade_id=e.entidade_id)) as total_propriedades,
       coalesce((select sum(p.area_total_ha) from sigov.agro_propriedade p where p.tenant_id=e.tenant_id and p.is_deleted=false and (e.entidade_id is null or p.entidade_id=e.entidade_id)),0) as area_total_mapeada,
       coalesce((select sum(p.area_produtiva_ha) from sigov.agro_propriedade p where p.tenant_id=e.tenant_id and p.is_deleted=false and (e.entidade_id is null or p.entidade_id=e.entidade_id)),0) as area_produtiva,
       (select count(*) from sigov.agro_cultura c where c.tenant_id=e.tenant_id and c.is_deleted=false and (e.entidade_id is null or c.entidade_id=e.entidade_id)) as culturas_cadastradas,
       coalesce((select sum(p.producao_estimada) from sigov.agro_producao_agricola p where p.tenant_id=e.tenant_id and p.is_deleted=false and (e.entidade_id is null or p.entidade_id=e.entidade_id)),0) as producao_estimada,
       coalesce((select sum(p.producao_realizada) from sigov.agro_producao_agricola p where p.tenant_id=e.tenant_id and p.is_deleted=false and (e.entidade_id is null or p.entidade_id=e.entidade_id)),0) as producao_realizada,
       0::bigint as total_rebanhos, 0::bigint as total_animais, 0::bigint as visitas_tecnicas_mes,
       (select count(*) from sigov.agro_beneficio_concessao b where b.tenant_id=e.tenant_id and b.is_deleted=false and b.status in ('ENTREGUE','CONCEDIDO') and b.created_at >= date_trunc('month', now()) and (e.entidade_id is null or b.entidade_id=e.entidade_id)) as beneficios_entregues_mes,
       (select count(*) from sigov.agro_servico_maquina s where s.tenant_id=e.tenant_id and s.is_deleted=false and s.status='EXECUTADO' and coalesce(s.data_execucao,s.created_at::date) >= date_trunc('month', now())::date and (e.entidade_id is null or s.entidade_id=e.entidade_id)) as servicos_maquina_executados_mes,
       coalesce((select sum(s.horas_trabalhadas) from sigov.agro_servico_maquina s where s.tenant_id=e.tenant_id and s.is_deleted=false and s.status='EXECUTADO' and coalesce(s.data_execucao,s.created_at::date) >= date_trunc('month', now())::date and (e.entidade_id is null or s.entidade_id=e.entidade_id)),0) as horas_maquinas_mes,
       coalesce((select sum(s.area_atendida_ha) from sigov.agro_servico_maquina s where s.tenant_id=e.tenant_id and s.is_deleted=false and s.status='EXECUTADO' and coalesce(s.data_execucao,s.created_at::date) >= date_trunc('month', now())::date and (e.entidade_id is null or s.entidade_id=e.entidade_id)),0) as area_atendida_maquinas_mes,
       coalesce((select sum(v.extensao_km) from sigov.agro_estrada_vicinal v where v.tenant_id=e.tenant_id and v.is_deleted=false and (e.entidade_id is null or v.entidade_id=e.entidade_id)),0) as estradas_vicinais_km,
       (select count(*) from sigov.agro_ponto_critico_rural pc where pc.tenant_id=e.tenant_id and pc.is_deleted=false and pc.status <> 'RESOLVIDO' and (e.entidade_id is null or pc.entidade_id=e.entidade_id)) as pontos_criticos_abertos,
       (select count(*) from sigov.agro_feira f where f.tenant_id=e.tenant_id and f.ativo=true and f.is_deleted=false and (e.entidade_id is null or f.entidade_id=e.entidade_id)) as feiras_ativas,
       (select count(*) from sigov.agro_agroindustria a where a.tenant_id=e.tenant_id and a.ativo=true and a.is_deleted=false and (e.entidade_id is null or a.entidade_id=e.entidade_id)) as agroindustrias_ativas,
       (select count(*) from sigov.agro_compra_agricultura_familiar c where c.tenant_id=e.tenant_id and c.is_deleted=false and c.data_compra >= date_trunc('month', now())::date and (e.entidade_id is null or c.entidade_id=e.entidade_id)) as compras_af_mes
from escopos e;

create or replace view sigov.vw_agro_bi_producao as select tenant_id, entidade_id, culturas_cadastradas, producao_estimada, producao_realizada, area_produtiva from sigov.vw_agro_bi_resumo;
create or replace view sigov.vw_agro_bi_pecuaria as select tenant_id, entidade_id, total_rebanhos, total_animais from sigov.vw_agro_bi_resumo;
create or replace view sigov.vw_agro_bi_programas as select tenant_id, entidade_id, beneficios_entregues_mes from sigov.vw_agro_bi_resumo;
create or replace view sigov.vw_agro_bi_patrulha as select tenant_id, entidade_id, servicos_maquina_executados_mes, horas_maquinas_mes, area_atendida_maquinas_mes from sigov.vw_agro_bi_resumo;
create or replace view sigov.vw_agro_bi_estradas as select tenant_id, entidade_id, estradas_vicinais_km, pontos_criticos_abertos from sigov.vw_agro_bi_resumo;
create or replace view sigov.vw_agro_bi_feiras as select tenant_id, entidade_id, feiras_ativas from sigov.vw_agro_bi_resumo;
create or replace view sigov.vw_agro_bi_agroindustrias as select tenant_id, entidade_id, agroindustrias_ativas from sigov.vw_agro_bi_resumo;

insert into sigov.agro_indicador(tenant_id, entidade_id, codigo, nome, categoria, unidade_medida, publico)
select t.id, null, v.codigo, v.nome, v.categoria, v.unidade, true
from sigov.tenant t
cross join (values
('total_produtores','Total de produtores','PRODUTORES',null),('total_propriedades','Total de propriedades','PROPRIEDADES',null),('area_produtiva_ha','Área produtiva','PROPRIEDADES','ha'),('total_culturas','Total de culturas','PRODUCAO',null),('producao_estimada','Produção estimada','PRODUCAO',null),('producao_realizada','Produção realizada','PRODUCAO',null),('total_rebanhos','Total de rebanhos','PECUARIA',null),('total_animais','Total de animais','PECUARIA',null),('visitas_tecnicas_mes','Visitas técnicas no mês','ASSISTENCIA_TECNICA',null),('beneficios_entregues_mes','Benefícios entregues no mês','PROGRAMAS',null),('servicos_maquina_executados_mes','Serviços de máquina executados no mês','PATRULHA_MECANIZADA',null),('estradas_vicinais_km','Estradas vicinais em km','ESTRADAS','km'),('pontos_criticos_abertos','Pontos críticos abertos','ESTRADAS',null),('feiras_ativas','Feiras ativas','FEIRAS',null),('agroindustrias_ativas','Agroindústrias ativas','AGROINDUSTRIA',null),('compras_af_mes','Compras da agricultura familiar no mês','COMPRAS_AF',null)
) as v(codigo,nome,categoria,unidade)
where t.ambiente = 'Development' or t.slug in ('dev','demo','municipio-demo')
on conflict (tenant_id, entidade_id, codigo) do nothing;

insert into sigov.agro_dicionario_dados(tabela_nome,campo_nome,nome_amigavel,descricao,categoria,dado_pessoal,dado_sensivel,publico,mascara_padrao) values
('agro_produtor','pessoa_id','Pessoa do produtor','Referência interna ao cadastro de pessoa; nunca expor em dados abertos.','PRODUTORES',true,false,false,'ID_INTERNO'),
('agro_propriedade','endereco_json','Endereço da propriedade','Endereço completo deve ser mascarado em exportações públicas.','PROPRIEDADES',true,false,false,'ENDERECO_MASCARADO'),
('agro_agroindustria','endereco_json','Endereço da agroindústria','Endereço completo deve ser mascarado em exportações públicas.','AGROINDUSTRIA',true,false,false,'ENDERECO_MASCARADO'),
('agro_compra_agricultura_familiar','produto','Produto adquirido','Campo publicável apenas agregado por produto.','COMPRAS_AF',false,false,true,null)
on conflict do nothing;
