using System.Globalization;
using System.Text;
using Dapper;
using Sigov.Application.Energia;
using Sigov.Infrastructure.Persistence.Dapper;

namespace Sigov.Infrastructure.Energia;

public sealed class EnergiaRepository(DapperContext db):IEnergiaRepository
{
 private static readonly IReadOnlyDictionary<string,string> Tables=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase){
  ["unidades-consumidoras"]="energia_unidade_consumidora",["medidores"]="energia_medidor",["leituras"]="energia_leitura",["faturas"]="energia_fatura",["contratos"]="energia_contrato_vinculo",["demanda"]="energia_demanda_historico",["pontos"]="energia_iluminacao_ponto",["chamados"]="energia_iluminacao_chamado",["ordens-servico"]="energia_iluminacao_ordem_servico",["manutencoes"]="energia_iluminacao_manutencao",["geracao-distribuida"]="energia_geracao_unidade",["creditos"]="energia_credito_compensacao",["eficiencia"]="energia_projeto_eficiencia",["alertas"]="energia_alerta"};
 public async Task<EnergiaDashboard> DashboardAsync(EnergiaContexto c,EnergiaFiltro f,CancellationToken ct){using var cn=db.CreateConnection();const string sql="""
 select coalesce((select sum(consumo_kwh) from sigov.energia_fatura where tenant_id=@TenantId and entidade_id=@EntidadeId and competencia=date_trunc('month',current_date)::date),0) ConsumoMes,
 coalesce((select sum(valor_total) from sigov.energia_fatura where tenant_id=@TenantId and entidade_id=@EntidadeId and competencia=date_trunc('month',current_date)::date),0) CustoMes,
 (select count(*) from sigov.energia_unidade_consumidora where tenant_id=@TenantId and entidade_id=@EntidadeId and status='ATIVA') UnidadesAtivas,
 (select count(*) from sigov.energia_fatura where tenant_id=@TenantId and entidade_id=@EntidadeId and status in('LANCADA','VENCIDA','EM_LIQUIDACAO')) FaturasPendentes,
 coalesce((select sum(demanda_contratada) from sigov.energia_contrato_vinculo where tenant_id=@TenantId and entidade_id=@EntidadeId and status='ATIVO'),0) DemandaContratada,
 coalesce((select sum(demanda_medida) from sigov.energia_demanda_historico where tenant_id=@TenantId and entidade_id=@EntidadeId and competencia=date_trunc('month',current_date)::date),0) DemandaMedida,
 (select count(*) from sigov.energia_alerta where tenant_id=@TenantId and entidade_id=@EntidadeId and tipo='DEMANDA_ULTRAPASSADA' and status='ABERTO') AlertasDemanda,
 (select count(*) from sigov.energia_iluminacao_chamado where tenant_id=@TenantId and entidade_id=@EntidadeId and status not in('RESOLVIDO','CANCELADO')) ChamadosAbertos,
 (select count(*) from sigov.energia_iluminacao_ponto where tenant_id=@TenantId and entidade_id=@EntidadeId and status<>'ATIVO') PontosInativos,
 coalesce((select sum(geracao_kwh) from sigov.energia_geracao_leitura where tenant_id=@TenantId and entidade_id=@EntidadeId and competencia=date_trunc('month',current_date)::date),0) GeracaoMes,
 coalesce((select sum(saldo_kwh) from sigov.energia_credito_compensacao where tenant_id=@TenantId and entidade_id=@EntidadeId and status='DISPONIVEL'),0) CreditosDisponiveis,
 coalesce((select sum(economia_realizada) from sigov.energia_projeto_eficiencia where tenant_id=@TenantId and entidade_id=@EntidadeId),0) EconomiaRealizada,
 coalesce((select sum(emissoes_evitadas_tco2e) from sigov.energia_integracao_carbono where tenant_id=@TenantId and entidade_id=@EntidadeId),0) EmissoesEvitadas
 """;var d=await cn.QuerySingleAsync<EnergiaDashboard>(new CommandDefinition(sql,c,cancellationToken:ct));var top=(await cn.QueryAsync<EnergiaRegistro>(new CommandDefinition("select u.id,u.numero_instalacao codigo,u.descricao,u.status,coalesce(sum(f.consumo_kwh),0) valor,null::date data,u.id unidade_consumidora_id from sigov.energia_unidade_consumidora u left join sigov.energia_fatura f on f.unidade_consumidora_id=u.id and f.competencia=date_trunc('month',current_date)::date where u.tenant_id=@TenantId and u.entidade_id=@EntidadeId group by u.id order by valor desc limit 5",c,cancellationToken:ct))).AsList();return d with{MaioresConsumidores=top};}
 public async Task<IReadOnlyList<EnergiaRegistro>> ListarAsync(EnergiaContexto c,string recurso,EnergiaFiltro f,CancellationToken ct){using var cn=db.CreateConnection();var t=Table(recurso);var sql=$"select id,coalesce(codigo,'') codigo,coalesce(descricao,'') descricao,status,coalesce(valor,0) valor,data,unidade_consumidora_id UnidadeConsumidoraId from sigov.{t} where tenant_id=@TenantId and entidade_id=@EntidadeId and (@Busca is null or codigo ilike '%'||@Busca||'%' or descricao ilike '%'||@Busca||'%') and (@Status is null or status=@Status) and (@Inicio is null or data>=@Inicio) and (@Fim is null or data<=@Fim) order by id desc limit 200";return (await cn.QueryAsync<EnergiaRegistro>(new CommandDefinition(sql,new{c.TenantId,c.EntidadeId,f.Busca,f.Status,f.Inicio,f.Fim},cancellationToken:ct))).AsList();}
 public async Task<EnergiaRegistro?> ObterAsync(EnergiaContexto c,string recurso,long id,CancellationToken ct){using var cn=db.CreateConnection();return await cn.QuerySingleOrDefaultAsync<EnergiaRegistro>(new CommandDefinition($"select id,coalesce(codigo,'') codigo,coalesce(descricao,'') descricao,status,coalesce(valor,0) valor,data,unidade_consumidora_id UnidadeConsumidoraId from sigov.{Table(recurso)} where id=@id and tenant_id=@TenantId and entidade_id=@EntidadeId",new{id,c.TenantId,c.EntidadeId},cancellationToken:ct));}
 public async Task<long> SalvarAsync(EnergiaContexto c,string recurso,EnergiaRegistroRequest r,long? id,CancellationToken ct){Validar(recurso,r);using var cn=db.CreateConnection();var t=Table(recurso);var p=new DynamicParameters(r);p.Add("Id",id);p.Add("TenantId",c.TenantId);p.Add("EntidadeId",c.EntidadeId);p.Add("UsuarioId",c.UsuarioId);var isUc=recurso.Equals("unidades-consumidoras",StringComparison.OrdinalIgnoreCase);var sql=id is null?(isUc?"insert into sigov.energia_unidade_consumidora(numero_instalacao,codigo,descricao,status,valor,data,pessoa_juridica_id,unidade_organizacional_id,contrato_id,latitude,longitude,justificativa,tenant_id,entidade_id,created_by) values(@Codigo,@Codigo,@Descricao,@Status,@Valor,@Data,@PessoaJuridicaId,@UnidadeOrganizacionalId,@ContratoId,@Latitude,@Longitude,@Justificativa,@TenantId,@EntidadeId,@UsuarioId) returning id":$"insert into sigov.{t}(codigo,descricao,status,valor,data,unidade_consumidora_id,pessoa_juridica_id,unidade_organizacional_id,contrato_id,latitude,longitude,justificativa,tenant_id,entidade_id,created_by) values(@Codigo,@Descricao,@Status,@Valor,@Data,@UnidadeConsumidoraId,@PessoaJuridicaId,@UnidadeOrganizacionalId,@ContratoId,@Latitude,@Longitude,@Justificativa,@TenantId,@EntidadeId,@UsuarioId) returning id"):$"update sigov.{t} set codigo=@Codigo,descricao=@Descricao,status=@Status,valor=@Valor,data=@Data,unidade_consumidora_id=@UnidadeConsumidoraId,pessoa_juridica_id=@PessoaJuridicaId,unidade_organizacional_id=@UnidadeOrganizacionalId,contrato_id=@ContratoId,latitude=@Latitude,longitude=@Longitude,justificativa=@Justificativa,updated_at=now(),updated_by=@UsuarioId where id=@Id and tenant_id=@TenantId and entidade_id=@EntidadeId returning id";return await cn.ExecuteScalarAsync<long?>(new CommandDefinition(sql,p,cancellationToken:ct))??throw new KeyNotFoundException("Registro não encontrado no contexto atual.");}
 public async Task<IReadOnlyList<EnergiaOpcao>> OpcoesAsync(EnergiaContexto c,string tipo,CancellationToken ct){using var cn=db.CreateConnection();var sql=tipo switch{"uc"=>"select id,numero_instalacao||' — '||descricao texto from sigov.energia_unidade_consumidora where tenant_id=@TenantId and entidade_id=@EntidadeId and status='ATIVA' order by descricao","concessionaria"=>"select p.id,p.razao_social texto from sigov.pessoa_juridica p join sigov.pessoa x on x.id=p.pessoa_id where x.tenant_id=@TenantId and x.entidade_id=@EntidadeId order by p.razao_social","unidade"=>"select id,nome texto from sigov.unidade_organizacional where tenant_id=@TenantId and entidade_id=@EntidadeId order by nome","contrato"=>"select id,numero||' — '||objeto texto from sigov.contrato where tenant_id=@TenantId and entidade_id=@EntidadeId order by id desc",_=>throw new ArgumentException("Catálogo inválido.")};return (await cn.QueryAsync<EnergiaOpcao>(new CommandDefinition(sql,c,cancellationToken:ct))).AsList();}
 public async Task<byte[]> ExportarCsvAsync(EnergiaContexto c,string recurso,EnergiaFiltro f,CancellationToken ct){var rows=await ListarAsync(c,recurso,f,ct);var b=new StringBuilder("id;codigo;descricao;status;valor;data\r\n");foreach(var x in rows)b.AppendLine($"{x.Id};{Csv(x.Codigo)};{Csv(x.Descricao)};{Csv(x.Status)};{x.Valor.ToString(CultureInfo.InvariantCulture)};{x.Data:yyyy-MM-dd}");return new UTF8Encoding(true).GetBytes(b.ToString());}
 private static string Table(string r)=>Tables.TryGetValue(r,out var t)?t:throw new ArgumentException("Recurso de energia inválido.");
 private static void Validar(string recurso,EnergiaRegistroRequest r){if(string.IsNullOrWhiteSpace(r.Codigo)||string.IsNullOrWhiteSpace(r.Descricao))throw new ArgumentException("Código e descrição são obrigatórios.");if(r.Valor<0)throw new ArgumentException("Valores, consumo, demanda, potência e créditos não podem ser negativos.");if(r.Latitude is < -90 or > 90||r.Longitude is < -180 or > 180)throw new ArgumentException("Coordenadas inválidas.");if(recurso is not "unidades-consumidoras"&&r.UnidadeConsumidoraId is null)throw new ArgumentException("Selecione uma unidade consumidora.");if((r.Status is "CONTESTADA" or "CANCELADA" or "DESCARTADO")&&string.IsNullOrWhiteSpace(r.Justificativa))throw new ArgumentException("O status selecionado exige justificativa auditável.");}
 private static string Csv(string s){if(s.Length>0&&"=+-@\t\r".Contains(s[0]))s="'"+s;return '"'+s.Replace("\"","\"\"")+'"';}
}
