namespace Sigov.Domain.Agro.Comercial;

public enum AgroPainelComercialSecao { PRODUTORES, PROPRIEDADES, PRODUCAO, PECUARIA, ASSISTENCIA_TECNICA, PROGRAMAS, PATRULHA_MECANIZADA, ESTRADAS, FEIRAS, AGROINDUSTRIAS, DADOS_ABERTOS }
