using Microsoft.Extensions.Logging;
using Sigov.Application.Abstractions;
using Sigov.Application.Common;
using Sigov.Domain.Common;
using Sigov.Domain.Processos;

namespace Sigov.Application.Processos;

public abstract class ProcessosServiceBase
{
    protected ProcessosServiceBase(ICurrentTenant tenant, ICurrentUser user, IPermissionService permissions, IAuditService audit)
    { Tenant = tenant; User = user; Permissions = permissions; Audit = audit; }
    protected ICurrentTenant Tenant { get; }
    protected ICurrentUser User { get; }
    protected IPermissionService Permissions { get; }
    protected IAuditService Audit { get; }
    protected long? UsuarioId => User.UsuarioId;
    protected Result<long> TenantFailureLong() => Result<long>.Failure("Tenant obrigatório.");
    protected Result<T> TenantFailure<T>() => Result<T>.Failure("Tenant obrigatório.");
    protected Result TenantFailure() => Result.Failure("Tenant obrigatório.");
    protected Result<long> AuthFailureLong() => Result<long>.Failure("Usuário autenticado obrigatório.");
    protected Result AuthFailure() => Result.Failure("Usuário autenticado obrigatório.");
    protected async Task<bool> CanAsync(string chave, CancellationToken ct)
    {
        if (!User.UsuarioId.HasValue) return false;
        var partes = chave.Split('.');
        var recurso = partes.Length >= 3 ? $"{partes[0]}.{partes[1]}" : chave;
        var acao = partes.Length >= 3 ? partes[2] : "visualizar";
        return await Permissions.HasPermissionAsync(User.UsuarioId.Value, ProcessosPermissoes.Modulo, recurso, acao, ct).ConfigureAwait(false);
    }
}

public sealed class TipoProcessoService : ProcessosServiceBase, ITipoProcessoService
{
    private readonly ITipoProcessoRepository _repo; private readonly ILogger<TipoProcessoService> _logger;
    public TipoProcessoService(ITipoProcessoRepository repo, ICurrentTenant tenant, ICurrentUser user, IPermissionService permissions, IAuditService audit, ILogger<TipoProcessoService> logger) : base(tenant, user, permissions, audit) { _repo = repo; _logger = logger; }
    public async Task<Result<PagedResult<TipoProcessoResponse>>> ListarAsync(int page, int pageSize, CancellationToken ct) { if (!Tenant.TenantId.HasValue) return TenantFailure<PagedResult<TipoProcessoResponse>>(); if (!await CanAsync(ProcessosPermissoes.TipoVisualizar, ct).ConfigureAwait(false)) return Result<PagedResult<TipoProcessoResponse>>.Failure("403"); try { return Result<PagedResult<TipoProcessoResponse>>.Success(await _repo.ListarAsync(Tenant.TenantId.Value, Tenant.EntidadeId, page, pageSize, ct).ConfigureAwait(false)); } catch (Exception ex) { _logger.LogError(ex, "Erro ao listar tipos de processo."); return Result<PagedResult<TipoProcessoResponse>>.Failure("Erro ao listar tipos de processo."); } }
    public async Task<Result<TipoProcessoResponse>> ObterAsync(long id, CancellationToken ct) { if (!Tenant.TenantId.HasValue) return TenantFailure<TipoProcessoResponse>(); if (!await CanAsync(ProcessosPermissoes.TipoVisualizar, ct).ConfigureAwait(false)) return Result<TipoProcessoResponse>.Failure("403"); var item = await _repo.ObterAsync(Tenant.TenantId.Value, id, ct).ConfigureAwait(false); return item is null ? Result<TipoProcessoResponse>.Failure("Tipo não encontrado.") : Result<TipoProcessoResponse>.Success(item); }
    public async Task<Result<long>> CriarAsync(CriarTipoProcessoRequest request, CancellationToken ct) { if (!Tenant.TenantId.HasValue) return TenantFailureLong(); if (!await CanAsync(ProcessosPermissoes.TipoCriar, ct).ConfigureAwait(false)) return Result<long>.Failure("403"); if (string.IsNullOrWhiteSpace(request.Nome)) return Result<long>.Failure("Nome obrigatório."); try { var id = await _repo.CriarAsync(Tenant.TenantId.Value, Tenant.EntidadeId, request, UsuarioId, Guid.NewGuid(), ct).ConfigureAwait(false); await Audit.RegistrarAsync("processos", "CRIAR_TIPO", "sigov.tipo_processo", id.ToString(System.Globalization.CultureInfo.InvariantCulture), null, request, ct).ConfigureAwait(false); return Result<long>.Success(id); } catch (Exception ex) { _logger.LogError(ex, "Erro ao criar tipo de processo."); return Result<long>.Failure("Erro ao criar tipo de processo."); } }
    public async Task<Result> AtualizarAsync(long id, AtualizarTipoProcessoRequest request, CancellationToken ct) { if (!Tenant.TenantId.HasValue) return TenantFailure(); if (!await CanAsync(ProcessosPermissoes.TipoEditar, ct).ConfigureAwait(false)) return Result.Failure("403"); await _repo.AtualizarAsync(Tenant.TenantId.Value, id, request, UsuarioId, ct).ConfigureAwait(false); await Audit.RegistrarAsync("processos", "EDITAR_TIPO", "sigov.tipo_processo", id.ToString(System.Globalization.CultureInfo.InvariantCulture), null, request, ct).ConfigureAwait(false); return Result.Success(); }
    public async Task<Result> ExcluirAsync(long id, CancellationToken ct) { if (!Tenant.TenantId.HasValue) return TenantFailure(); if (!await CanAsync(ProcessosPermissoes.TipoExcluir, ct).ConfigureAwait(false)) return Result.Failure("403"); await _repo.ExcluirAsync(Tenant.TenantId.Value, id, UsuarioId, ct).ConfigureAwait(false); await Audit.RegistrarAsync("processos", "EXCLUIR_TIPO", "sigov.tipo_processo", id.ToString(System.Globalization.CultureInfo.InvariantCulture), null, null, ct).ConfigureAwait(false); return Result.Success(); }
}

public sealed class ProcessoDigitalService : ProcessosServiceBase, IProcessoDigitalService
{
    private readonly IProcessoDigitalRepository _repo; private readonly IProcessoMovimentacaoRepository _mov; private readonly IProcessoParecerRepository _parecer; private readonly IProcessoSequencialService _seq; private readonly ILogger<ProcessoDigitalService> _logger;
    public ProcessoDigitalService(IProcessoDigitalRepository repo, IProcessoMovimentacaoRepository mov, IProcessoParecerRepository parecer, IProcessoSequencialService seq, ICurrentTenant tenant, ICurrentUser user, IPermissionService permissions, IAuditService audit, ILogger<ProcessoDigitalService> logger) : base(tenant, user, permissions, audit) { _repo = repo; _mov = mov; _parecer = parecer; _seq = seq; _logger = logger; }
    public async Task<Result<PagedResult<ProcessoResumoResponse>>> ListarAsync(ProcessoFiltro f, CancellationToken ct) { if (!Tenant.TenantId.HasValue) return TenantFailure<PagedResult<ProcessoResumoResponse>>(); if (!await CanAsync(ProcessosPermissoes.ProcessoVisualizar, ct).ConfigureAwait(false)) return Result<PagedResult<ProcessoResumoResponse>>.Failure("403"); return Result<PagedResult<ProcessoResumoResponse>>.Success(await _repo.ListarAsync(Tenant.TenantId.Value, Tenant.EntidadeId, Tenant.ExercicioId, f, ct).ConfigureAwait(false)); }
    public async Task<Result<ProcessoDetalheResponse>> ObterAsync(long id, CancellationToken ct) { if (!Tenant.TenantId.HasValue) return TenantFailure<ProcessoDetalheResponse>(); if (!await CanAsync(ProcessosPermissoes.ProcessoVisualizar, ct).ConfigureAwait(false)) return Result<ProcessoDetalheResponse>.Failure("403"); var item = await _repo.ObterAsync(Tenant.TenantId.Value, id, ct).ConfigureAwait(false); if (item is null) return Result<ProcessoDetalheResponse>.Failure("Processo não encontrado."); await Audit.RegistrarAsync("processos", "ACESSO_DADO_PESSOAL", "sigov.processo_digital", id.ToString(System.Globalization.CultureInfo.InvariantCulture), null, new { item.Interessado }, ct).ConfigureAwait(false); return Result<ProcessoDetalheResponse>.Success(item); }
    public async Task<Result<long>> CriarAsync(CriarProcessoRequest r, CancellationToken ct) { if (!Tenant.TenantId.HasValue) return TenantFailureLong(); if (!UsuarioId.HasValue) return AuthFailureLong(); if (!await CanAsync(ProcessosPermissoes.ProcessoCriar, ct).ConfigureAwait(false)) return Result<long>.Failure("403"); if (string.IsNullOrWhiteSpace(r.Assunto)) return Result<long>.Failure("Assunto obrigatório."); try { var ano = DateTimeOffset.UtcNow.Year; var numero = await _seq.ProximoAsync(Tenant.TenantId.Value, Tenant.EntidadeId, Tenant.ExercicioId, ano, "processo_digital", "PROC", ct).ConfigureAwait(false); var id = await _repo.CriarAsync(Tenant.TenantId.Value, Tenant.EntidadeId, Tenant.ExercicioId, numero, ano, r, UsuarioId.Value, Guid.NewGuid(), ct).ConfigureAwait(false); await Audit.RegistrarAsync("processos", "CRIAR_PROCESSO", "sigov.processo_digital", id.ToString(System.Globalization.CultureInfo.InvariantCulture), null, r, ct).ConfigureAwait(false); return Result<long>.Success(id); } catch (Exception ex) { _logger.LogError(ex, "Erro ao criar processo."); return Result<long>.Failure("Erro ao criar processo."); } }
    public async Task<Result> AtualizarAsync(long id, AtualizarProcessoRequest r, CancellationToken ct) { if (!Tenant.TenantId.HasValue) return TenantFailure(); if (!await CanAsync(ProcessosPermissoes.ProcessoEditar, ct).ConfigureAwait(false)) return Result.Failure("403"); await _repo.AtualizarAsync(Tenant.TenantId.Value, id, r, UsuarioId, ct).ConfigureAwait(false); await Audit.RegistrarAsync("processos", "EDITAR_PROCESSO", "sigov.processo_digital", id.ToString(System.Globalization.CultureInfo.InvariantCulture), null, r, ct).ConfigureAwait(false); return Result.Success(); }
    public async Task<Result> ExcluirAsync(long id, CancellationToken ct) { if (!Tenant.TenantId.HasValue) return TenantFailure(); if (!await CanAsync(ProcessosPermissoes.ProcessoExcluir, ct).ConfigureAwait(false)) return Result.Failure("403"); await _repo.ExcluirAsync(Tenant.TenantId.Value, id, UsuarioId, ct).ConfigureAwait(false); await Audit.RegistrarAsync("processos", "EXCLUIR_PROCESSO", "sigov.processo_digital", id.ToString(System.Globalization.CultureInfo.InvariantCulture), null, null, ct).ConfigureAwait(false); return Result.Success(); }
    public async Task<Result<long>> MovimentarAsync(long id, MovimentarProcessoRequest r, CancellationToken ct) { if (!Tenant.TenantId.HasValue) return TenantFailureLong(); if (!UsuarioId.HasValue) return AuthFailureLong(); if (!await CanAsync(ProcessosPermissoes.ProcessoMovimentar, ct).ConfigureAwait(false)) return Result<long>.Failure("403"); _ = new ProcessoMovimentacao(r.Despacho); var mid = await _mov.CriarAsync(Tenant.TenantId.Value, id, r, UsuarioId.Value, ct).ConfigureAwait(false); await Audit.RegistrarAsync("processos", "MOVIMENTAR_PROCESSO", "sigov.processo_movimentacao", mid.ToString(System.Globalization.CultureInfo.InvariantCulture), null, r, ct).ConfigureAwait(false); return Result<long>.Success(mid); }
    public async Task<Result<long>> EmitirParecerAsync(long id, EmitirParecerRequest r, CancellationToken ct) { if (!Tenant.TenantId.HasValue) return TenantFailureLong(); if (!UsuarioId.HasValue) return AuthFailureLong(); if (!await CanAsync(ProcessosPermissoes.ProcessoParecer, ct).ConfigureAwait(false)) return Result<long>.Failure("403"); _ = new ProcessoParecer(r.Titulo, r.Texto); var pid = await _parecer.CriarAsync(Tenant.TenantId.Value, id, r, UsuarioId.Value, ct).ConfigureAwait(false); await Audit.RegistrarAsync("processos", "EMITIR_PARECER", "sigov.processo_parecer", pid.ToString(System.Globalization.CultureInfo.InvariantCulture), null, r, ct).ConfigureAwait(false); return Result<long>.Success(pid); }
    public async Task<Result> EncerrarAsync(long id, CancellationToken ct) { if (!Tenant.TenantId.HasValue) return TenantFailure(); if (!await CanAsync(ProcessosPermissoes.ProcessoEncerrar, ct).ConfigureAwait(false)) return Result.Failure("403"); await _repo.AlterarStatusAsync(Tenant.TenantId.Value, id, "ENCERRADO", UsuarioId, ct).ConfigureAwait(false); await Audit.RegistrarAsync("processos", "ENCERRAR_PROCESSO", "sigov.processo_digital", id.ToString(System.Globalization.CultureInfo.InvariantCulture), null, new { Status = "ENCERRADO" }, ct).ConfigureAwait(false); return Result.Success(); }
    public async Task<Result> CancelarAsync(long id, CancellationToken ct) { if (!Tenant.TenantId.HasValue) return TenantFailure(); if (!await CanAsync(ProcessosPermissoes.ProcessoCancelar, ct).ConfigureAwait(false)) return Result.Failure("403"); await _repo.AlterarStatusAsync(Tenant.TenantId.Value, id, "CANCELADO", UsuarioId, ct).ConfigureAwait(false); await Audit.RegistrarAsync("processos", "CANCELAR_PROCESSO", "sigov.processo_digital", id.ToString(System.Globalization.CultureInfo.InvariantCulture), null, new { Status = "CANCELADO" }, ct).ConfigureAwait(false); return Result.Success(); }
}

public sealed class ProtocoloAtendimentoService : ProcessosServiceBase, IProtocoloAtendimentoService
{
    private readonly IProtocoloAtendimentoRepository _repo; private readonly IProcessoDigitalRepository _processos; private readonly IProcessoSequencialService _seq;
    public ProtocoloAtendimentoService(IProtocoloAtendimentoRepository repo, IProcessoDigitalRepository processos, IProcessoSequencialService seq, ICurrentTenant tenant, ICurrentUser user, IPermissionService permissions, IAuditService audit) : base(tenant, user, permissions, audit) { _repo = repo; _processos = processos; _seq = seq; }
    public async Task<Result<PagedResult<ProtocoloResumoResponse>>> ListarAsync(ProtocoloFiltro f, CancellationToken ct) { if (!Tenant.TenantId.HasValue) return TenantFailure<PagedResult<ProtocoloResumoResponse>>(); if (!await CanAsync(ProcessosPermissoes.ProtocoloVisualizar, ct).ConfigureAwait(false)) return Result<PagedResult<ProtocoloResumoResponse>>.Failure("403"); return Result<PagedResult<ProtocoloResumoResponse>>.Success(await _repo.ListarAsync(Tenant.TenantId.Value, f, ct).ConfigureAwait(false)); }
    public async Task<Result<ProtocoloDetalheResponse>> ObterAsync(long id, CancellationToken ct) { if (!Tenant.TenantId.HasValue) return TenantFailure<ProtocoloDetalheResponse>(); if (!await CanAsync(ProcessosPermissoes.ProtocoloVisualizar, ct).ConfigureAwait(false)) return Result<ProtocoloDetalheResponse>.Failure("403"); var item = await _repo.ObterAsync(Tenant.TenantId.Value, id, ct).ConfigureAwait(false); if (item is null) return Result<ProtocoloDetalheResponse>.Failure("Protocolo não encontrado."); await Audit.RegistrarAsync("processos", "ACESSO_DADO_PESSOAL", "sigov.protocolo_atendimento", id.ToString(System.Globalization.CultureInfo.InvariantCulture), null, new { item.Pessoa }, ct).ConfigureAwait(false); return Result<ProtocoloDetalheResponse>.Success(item); }
    public async Task<Result<long>> CriarAsync(CriarProtocoloRequest r, CancellationToken ct) { if (!Tenant.TenantId.HasValue) return TenantFailureLong(); if (!await CanAsync(ProcessosPermissoes.ProtocoloCriar, ct).ConfigureAwait(false)) return Result<long>.Failure("403"); var ano = DateTimeOffset.UtcNow.Year; var numero = await _seq.ProximoAsync(Tenant.TenantId.Value, Tenant.EntidadeId, Tenant.ExercicioId, ano, "protocolo_atendimento", "PROT", ct).ConfigureAwait(false); var id = await _repo.CriarAsync(Tenant.TenantId.Value, Tenant.EntidadeId, Tenant.ExercicioId, numero, r, UsuarioId, ct).ConfigureAwait(false); await Audit.RegistrarAsync("processos", "CRIAR_PROTOCOLO", "sigov.protocolo_atendimento", id.ToString(System.Globalization.CultureInfo.InvariantCulture), null, r, ct).ConfigureAwait(false); return Result<long>.Success(id); }
    public async Task<Result> AtualizarAsync(long id, CriarProtocoloRequest r, CancellationToken ct) { if (!Tenant.TenantId.HasValue) return TenantFailure(); if (!await CanAsync(ProcessosPermissoes.ProtocoloEditar, ct).ConfigureAwait(false)) return Result.Failure("403"); await _repo.AtualizarAsync(Tenant.TenantId.Value, id, r, UsuarioId, ct).ConfigureAwait(false); return Result.Success(); }
    public async Task<Result<long>> ConverterEmProcessoAsync(long id, ConverterProtocoloEmProcessoRequest r, CancellationToken ct) { if (!Tenant.TenantId.HasValue) return TenantFailureLong(); if (!UsuarioId.HasValue) return AuthFailureLong(); if (!await CanAsync(ProcessosPermissoes.ProtocoloConverter, ct).ConfigureAwait(false)) return Result<long>.Failure("403"); var detalhe = await _repo.ObterAsync(Tenant.TenantId.Value, id, ct).ConfigureAwait(false); if (detalhe is null) return Result<long>.Failure("Protocolo não encontrado."); if (detalhe.ProcessoDigitalId.HasValue) return Result<long>.Failure("Protocolo já convertido."); var ano = DateTimeOffset.UtcNow.Year; var numero = await _seq.ProximoAsync(Tenant.TenantId.Value, Tenant.EntidadeId, Tenant.ExercicioId, ano, "processo_digital", "PROC", ct).ConfigureAwait(false); var processoId = await _processos.CriarAsync(Tenant.TenantId.Value, Tenant.EntidadeId, Tenant.ExercicioId, numero, ano, new CriarProcessoRequest(r.TipoProcessoId, detalhe.Assunto, detalhe.Descricao, null, r.UnidadeOrigemId, r.Prioridade, false, null, "Convertido do protocolo"), UsuarioId.Value, Guid.NewGuid(), ct).ConfigureAwait(false); await _repo.VincularProcessoAsync(Tenant.TenantId.Value, id, processoId, UsuarioId, ct).ConfigureAwait(false); await Audit.RegistrarAsync("processos", "CONVERTER_PROTOCOLO", "sigov.protocolo_atendimento", id.ToString(System.Globalization.CultureInfo.InvariantCulture), null, new { ProcessoDigitalId = processoId }, ct).ConfigureAwait(false); return Result<long>.Success(processoId); }
    public async Task<Result> EncerrarAsync(long id, CancellationToken ct) { if (!Tenant.TenantId.HasValue) return TenantFailure(); if (!await CanAsync(ProcessosPermissoes.ProtocoloEncerrar, ct).ConfigureAwait(false)) return Result.Failure("403"); await _repo.EncerrarAsync(Tenant.TenantId.Value, id, UsuarioId, ct).ConfigureAwait(false); return Result.Success(); }
}

public sealed class OuvidoriaService : ProcessosServiceBase, IOuvidoriaService
{
    private readonly IOuvidoriaRepository _repo; private readonly IProcessoDigitalRepository _processos; private readonly IProcessoSequencialService _seq;
    public OuvidoriaService(IOuvidoriaRepository repo, IProcessoDigitalRepository processos, IProcessoSequencialService seq, ICurrentTenant tenant, ICurrentUser user, IPermissionService permissions, IAuditService audit) : base(tenant, user, permissions, audit) { _repo = repo; _processos = processos; _seq = seq; }
    public async Task<Result<PagedResult<OuvidoriaResumoResponse>>> ListarAsync(OuvidoriaFiltro f, CancellationToken ct) { if (!Tenant.TenantId.HasValue) return TenantFailure<PagedResult<OuvidoriaResumoResponse>>(); if (!await CanAsync(ProcessosPermissoes.OuvidoriaVisualizar, ct).ConfigureAwait(false)) return Result<PagedResult<OuvidoriaResumoResponse>>.Failure("403"); return Result<PagedResult<OuvidoriaResumoResponse>>.Success(await _repo.ListarAsync(Tenant.TenantId.Value, f, ct).ConfigureAwait(false)); }
    public async Task<Result<OuvidoriaDetalheResponse>> ObterAsync(long id, CancellationToken ct) { if (!Tenant.TenantId.HasValue) return TenantFailure<OuvidoriaDetalheResponse>(); if (!await CanAsync(ProcessosPermissoes.OuvidoriaVisualizar, ct).ConfigureAwait(false)) return Result<OuvidoriaDetalheResponse>.Failure("403"); var item = await _repo.ObterAsync(Tenant.TenantId.Value, id, true, ct).ConfigureAwait(false); if (item is null) return Result<OuvidoriaDetalheResponse>.Failure("Manifestação não encontrada."); await Audit.RegistrarAsync("processos", "ACESSO_DADO_PESSOAL", "sigov.ouvidoria_manifestacao", id.ToString(System.Globalization.CultureInfo.InvariantCulture), null, new { item.Pessoa }, ct).ConfigureAwait(false); return Result<OuvidoriaDetalheResponse>.Success(item); }
    public async Task<Result<long>> CriarAsync(CriarOuvidoriaRequest r, CancellationToken ct) { if (!Tenant.TenantId.HasValue) return TenantFailureLong(); if (!await CanAsync(ProcessosPermissoes.OuvidoriaCriar, ct).ConfigureAwait(false)) return Result<long>.Failure("403"); _ = new OuvidoriaManifestacao(r.Anonima, r.PessoaId); var ano = DateTimeOffset.UtcNow.Year; var numero = await _seq.ProximoAsync(Tenant.TenantId.Value, Tenant.EntidadeId, Tenant.ExercicioId, ano, "ouvidoria_manifestacao", "OUV", ct).ConfigureAwait(false); var id = await _repo.CriarAsync(Tenant.TenantId.Value, Tenant.EntidadeId, Tenant.ExercicioId, numero, r, UsuarioId, ct).ConfigureAwait(false); await Audit.RegistrarAsync("processos", "CRIAR_OUVIDORIA", "sigov.ouvidoria_manifestacao", id.ToString(System.Globalization.CultureInfo.InvariantCulture), null, r, ct).ConfigureAwait(false); return Result<long>.Success(id); }
    public async Task<Result> ResponderAsync(long id, ResponderOuvidoriaRequest r, CancellationToken ct) { if (!Tenant.TenantId.HasValue) return TenantFailure(); if (!UsuarioId.HasValue) return AuthFailure(); if (!await CanAsync(ProcessosPermissoes.OuvidoriaResponder, ct).ConfigureAwait(false)) return Result.Failure("403"); await _repo.ResponderAsync(Tenant.TenantId.Value, id, r, UsuarioId.Value, ct).ConfigureAwait(false); await Audit.RegistrarAsync("processos", "RESPONDER_OUVIDORIA", "sigov.ouvidoria_manifestacao", id.ToString(System.Globalization.CultureInfo.InvariantCulture), null, r, ct).ConfigureAwait(false); return Result.Success(); }
    public async Task<Result<long>> ConverterEmProcessoAsync(long id, ConverterProtocoloEmProcessoRequest r, CancellationToken ct) { if (!Tenant.TenantId.HasValue) return TenantFailureLong(); if (!UsuarioId.HasValue) return AuthFailureLong(); if (!await CanAsync(ProcessosPermissoes.OuvidoriaConverter, ct).ConfigureAwait(false)) return Result<long>.Failure("403"); var detalhe = await _repo.ObterAsync(Tenant.TenantId.Value, id, true, ct).ConfigureAwait(false); if (detalhe is null) return Result<long>.Failure("Manifestação não encontrada."); if (detalhe.ProcessoDigitalId.HasValue) return Result<long>.Failure("Manifestação já convertida."); var ano = DateTimeOffset.UtcNow.Year; var numero = await _seq.ProximoAsync(Tenant.TenantId.Value, Tenant.EntidadeId, Tenant.ExercicioId, ano, "processo_digital", "PROC", ct).ConfigureAwait(false); var processoId = await _processos.CriarAsync(Tenant.TenantId.Value, Tenant.EntidadeId, Tenant.ExercicioId, numero, ano, new CriarProcessoRequest(r.TipoProcessoId, detalhe.Assunto, detalhe.Descricao, null, r.UnidadeOrigemId, r.Prioridade, detalhe.Sigilosa, null, "Convertido da ouvidoria"), UsuarioId.Value, Guid.NewGuid(), ct).ConfigureAwait(false); await _repo.VincularProcessoAsync(Tenant.TenantId.Value, id, processoId, UsuarioId, ct).ConfigureAwait(false); return Result<long>.Success(processoId); }
    public async Task<Result> ArquivarAsync(long id, CancellationToken ct) { if (!Tenant.TenantId.HasValue) return TenantFailure(); if (!await CanAsync(ProcessosPermissoes.OuvidoriaArquivar, ct).ConfigureAwait(false)) return Result.Failure("403"); await _repo.ArquivarAsync(Tenant.TenantId.Value, id, UsuarioId, ct).ConfigureAwait(false); return Result.Success(); }
}

public sealed class DiarioOficialService : ProcessosServiceBase, IDiarioOficialService
{
    private readonly IDiarioOficialRepository _repo;
    public DiarioOficialService(IDiarioOficialRepository repo, ICurrentTenant tenant, ICurrentUser user, IPermissionService permissions, IAuditService audit) : base(tenant, user, permissions, audit) { _repo = repo; }
    public async Task<Result<PagedResult<DiarioPublicacaoResponse>>> ListarAsync(DiarioFiltro f, CancellationToken ct) { if (!Tenant.TenantId.HasValue) return TenantFailure<PagedResult<DiarioPublicacaoResponse>>(); if (!await CanAsync(ProcessosPermissoes.DiarioVisualizar, ct).ConfigureAwait(false)) return Result<PagedResult<DiarioPublicacaoResponse>>.Failure("403"); return Result<PagedResult<DiarioPublicacaoResponse>>.Success(await _repo.ListarAsync(Tenant.TenantId.Value, f, ct).ConfigureAwait(false)); }
    public async Task<Result<DiarioPublicacaoResponse>> ObterAsync(long id, CancellationToken ct) { if (!Tenant.TenantId.HasValue) return TenantFailure<DiarioPublicacaoResponse>(); if (!await CanAsync(ProcessosPermissoes.DiarioVisualizar, ct).ConfigureAwait(false)) return Result<DiarioPublicacaoResponse>.Failure("403"); var item = await _repo.ObterAsync(Tenant.TenantId.Value, id, ct).ConfigureAwait(false); return item is null ? Result<DiarioPublicacaoResponse>.Failure("Publicação não encontrada.") : Result<DiarioPublicacaoResponse>.Success(item); }
    public async Task<Result<long>> CriarAsync(CriarDiarioPublicacaoRequest r, CancellationToken ct) { if (!Tenant.TenantId.HasValue) return TenantFailureLong(); if (!await CanAsync(ProcessosPermissoes.DiarioCriar, ct).ConfigureAwait(false)) return Result<long>.Failure("403"); var id = await _repo.CriarAsync(Tenant.TenantId.Value, Tenant.EntidadeId, Tenant.ExercicioId, r, UsuarioId, ct).ConfigureAwait(false); await Audit.RegistrarAsync("processos", "CRIAR_DIARIO", "sigov.diario_oficial_publicacao", id.ToString(System.Globalization.CultureInfo.InvariantCulture), null, r, ct).ConfigureAwait(false); return Result<long>.Success(id); }
    public async Task<Result> AtualizarAsync(long id, CriarDiarioPublicacaoRequest r, CancellationToken ct) { if (!Tenant.TenantId.HasValue) return TenantFailure(); if (!await CanAsync(ProcessosPermissoes.DiarioEditar, ct).ConfigureAwait(false)) return Result.Failure("403"); await _repo.AtualizarAsync(Tenant.TenantId.Value, id, r, UsuarioId, ct).ConfigureAwait(false); return Result.Success(); }
    public async Task<Result> PublicarAsync(long id, PublicarDiarioRequest r, CancellationToken ct) { if (!Tenant.TenantId.HasValue) return TenantFailure(); if (!UsuarioId.HasValue) return AuthFailure(); if (!await CanAsync(ProcessosPermissoes.DiarioPublicar, ct).ConfigureAwait(false)) return Result.Failure("403"); await _repo.PublicarAsync(Tenant.TenantId.Value, id, UsuarioId.Value, ct).ConfigureAwait(false); await Audit.RegistrarAsync("processos", "PUBLICAR_DIARIO", "sigov.diario_oficial_publicacao", id.ToString(System.Globalization.CultureInfo.InvariantCulture), null, r, ct).ConfigureAwait(false); return Result.Success(); }
    public async Task<Result<long>> CriarAtoAsync(long id, CriarAtoOficialRequest r, CancellationToken ct) { if (!Tenant.TenantId.HasValue) return TenantFailureLong(); if (!await CanAsync(ProcessosPermissoes.DiarioCriar, ct).ConfigureAwait(false)) return Result<long>.Failure("403"); _ = new AtoOficial(id); var atoId = await _repo.CriarAtoAsync(Tenant.TenantId.Value, id, r, UsuarioId, ct).ConfigureAwait(false); await Audit.RegistrarAsync("processos", "CRIAR_ATO", "sigov.ato_oficial", atoId.ToString(System.Globalization.CultureInfo.InvariantCulture), null, r, ct).ConfigureAwait(false); return Result<long>.Success(atoId); }
    public async Task<Result<IReadOnlyCollection<AtoOficialResponse>>> ListarAtosAsync(long id, CancellationToken ct) { if (!Tenant.TenantId.HasValue) return TenantFailure<IReadOnlyCollection<AtoOficialResponse>>(); if (!await CanAsync(ProcessosPermissoes.DiarioVisualizar, ct).ConfigureAwait(false)) return Result<IReadOnlyCollection<AtoOficialResponse>>.Failure("403"); return Result<IReadOnlyCollection<AtoOficialResponse>>.Success(await _repo.ListarAtosAsync(Tenant.TenantId.Value, id, ct).ConfigureAwait(false)); }
}
