using Microsoft.Extensions.Logging;
using Sigov.Application.Agro.Permissions;
using Sigov.Application.Common;
using Sigov.Domain.Common;

namespace Sigov.Application.Agro.Programas;

public sealed class AgroBeneficioRuralService : IAgroBeneficioRuralService
{
    private readonly AgroBeneficioRuralPermissionChecker _permission; private readonly AgroBeneficioRuralValidator _validator; private readonly AgroBeneficioRuralAuditWriter _audit; private readonly AgroBeneficioRuralMapper _mapper; private readonly IAgroProgramasRepository _repository; private readonly ILogger<AgroBeneficioRuralService> _logger;
    public AgroBeneficioRuralService(AgroBeneficioRuralPermissionChecker permission, AgroBeneficioRuralValidator validator, AgroBeneficioRuralAuditWriter audit, AgroBeneficioRuralMapper mapper, IAgroProgramasRepository repository, ILogger<AgroBeneficioRuralService> logger){_permission=permission;_validator=validator;_audit=audit;_mapper=mapper;_repository=repository;_logger=logger;}
    public async Task<Result<PagedResult<AgroBeneficioRuralResponse>>> ListarAsync(AgroProgramaRuralFiltro filtro,CancellationToken ct){var c=await Ctx(AgroPermissions.BeneficioVisualizar,"agro.beneficios_rurais",ct); if(c.IsFailure)return Result<PagedResult<AgroBeneficioRuralResponse>>.Failure(c.Error!); return Result<PagedResult<AgroBeneficioRuralResponse>>.Success(await _repository.ListarBeneficiosAsync(c.Value!.TenantId,c.Value.EntidadeId!.Value,Page(filtro),ct));}
    public async Task<Result<AgroBeneficioRuralResponse>> ObterAsync(long id,CancellationToken ct){var c=await Ctx(AgroPermissions.BeneficioVisualizar,"agro.beneficios_rurais",ct); if(c.IsFailure)return Result<AgroBeneficioRuralResponse>.Failure(c.Error!); var row=await _repository.ObterBeneficioAsync(c.Value!.TenantId,c.Value.EntidadeId!.Value,id,ct); return row is null?Result<AgroBeneficioRuralResponse>.Failure("Benefício não encontrado."):Result<AgroBeneficioRuralResponse>.Success(row);}
    public async Task<Result<long>> CriarAsync(AgroBeneficioRuralCreateRequest request,CancellationToken ct){var c=await Ctx(AgroPermissions.BeneficioCriar,"agro.beneficios_rurais",ct); if(c.IsFailure)return Result<long>.Failure(c.Error!); var req=_mapper.Normalize(request); var v=_validator.Validar(req); if(v.IsFailure)return Result<long>.Failure(v.Error!); var id=await _repository.CriarBeneficioAsync(c.Value!.TenantId,c.Value.EntidadeId!.Value,c.Value.UsuarioId,req,ct); await _audit.WriteAsync("sigov.agro_beneficio_rural","CRIAR",id,req,ct); _logger.LogInformation("Benefício rural {Id} criado.",id); return Result<long>.Success(id);}
    public async Task<Result> AtualizarAsync(long id,AgroBeneficioRuralUpdateRequest request,CancellationToken ct){var c=await Ctx(AgroPermissions.BeneficioEditar,"agro.beneficios_rurais",ct); if(c.IsFailure)return Result.Failure(c.Error!); var v=_validator.Validar(request); if(v.IsFailure)return v; await _repository.AtualizarBeneficioAsync(c.Value!.TenantId,c.Value.EntidadeId!.Value,id,c.Value.UsuarioId,request,ct); await _audit.WriteAsync("sigov.agro_beneficio_rural","EDITAR",id,request,ct); return Result.Success();}
    public async Task<Result> ExcluirAsync(long id,CancellationToken ct){var c=await Ctx(AgroPermissions.BeneficioExcluir,"agro.beneficios_rurais",ct); if(c.IsFailure)return Result.Failure(c.Error!); await _repository.ExcluirBeneficioAsync(c.Value!.TenantId,c.Value.EntidadeId!.Value,id,c.Value.UsuarioId,ct); return Result.Success();}
    public async Task<Result<PagedResult<AgroBeneficioConcessaoResponse>>> ListarConcessoesAsync(AgroBeneficioConcessaoFiltro filtro,CancellationToken ct){var c=await Ctx(AgroPermissions.BeneficioVisualizar,"agro.beneficios_rurais",ct); if(c.IsFailure)return Result<PagedResult<AgroBeneficioConcessaoResponse>>.Failure(c.Error!); return Result<PagedResult<AgroBeneficioConcessaoResponse>>.Success(await _repository.ListarConcessoesAsync(c.Value!.TenantId,c.Value.EntidadeId!.Value,Page(filtro),ct));}
    public async Task<Result<AgroBeneficioConcessaoResponse>> ObterConcessaoAsync(long id,CancellationToken ct){var c=await Ctx(AgroPermissions.BeneficioVisualizar,"agro.beneficios_rurais",ct); if(c.IsFailure)return Result<AgroBeneficioConcessaoResponse>.Failure(c.Error!); var row=await _repository.ObterConcessaoAsync(c.Value!.TenantId,c.Value.EntidadeId!.Value,id,ct); return row is null?Result<AgroBeneficioConcessaoResponse>.Failure("Concessão não encontrada."):Result<AgroBeneficioConcessaoResponse>.Success(row);}
    public async Task<Result<long>> SolicitarConcessaoAsync(AgroBeneficioConcessaoCreateRequest request,CancellationToken ct){var c=await Ctx(AgroPermissions.BeneficioConceder,"agro.beneficios_rurais",ct); if(c.IsFailure)return Result<long>.Failure(c.Error!); var v=_validator.Validar(request); if(v.IsFailure)return Result<long>.Failure(v.Error!); var numero=string.IsNullOrWhiteSpace(request.Numero)?$"AGR-BEN-{DateTime.UtcNow.Year:D4}-{DateTime.UtcNow.Ticks%1000000:D6}":request.Numero!; var id=await _repository.CriarConcessaoAsync(c.Value!.TenantId,c.Value.EntidadeId!.Value,c.Value.ExercicioId,c.Value.UsuarioId,request,numero,ct); await _audit.WriteAsync("sigov.agro_beneficio_concessao","SOLICITAR",id,request,ct); return Result<long>.Success(id);}
    public Task<Result> AutorizarAsync(long id,AutorizarBeneficioRuralRequest request,CancellationToken ct)=>Status(id,AgroPermissions.BeneficioAutorizar,"AUTORIZADO",request.Observacao,ct);
    public Task<Result> EntregarAsync(long id,EntregarBeneficioRuralRequest request,CancellationToken ct)=>Status(id,AgroPermissions.BeneficioEntregar,"ENTREGUE",request.Observacao,ct);
    public Task<Result> IndeferirAsync(long id,IndeferirBeneficioRuralRequest request,CancellationToken ct)=>Status(id,AgroPermissions.BeneficioIndeferir,"INDEFERIDO",request.Motivo,ct);
    public Task<Result> CancelarAsync(long id,CancelarBeneficioRuralRequest request,CancellationToken ct)=>Status(id,AgroPermissions.BeneficioCancelar,"CANCELADO",request.Motivo,ct);
    private async Task<Result> Status(long id,string permissao,string status,string? obs,CancellationToken ct){var c=await Ctx(permissao,"agro.beneficios_rurais",ct); if(c.IsFailure)return Result.Failure(c.Error!); await _repository.AtualizarStatusConcessaoAsync(c.Value!.TenantId,c.Value.EntidadeId!.Value,id,c.Value.UsuarioId,status,obs,ct); await _audit.WriteAsync("sigov.agro_beneficio_concessao",status,id,new{status,obs},ct); return Result.Success();}
    private async Task<Result<AgroAccessContext>> Ctx(string p,string f,CancellationToken ct){var c=await _permission.CheckAsync(p,f,ct); if(c.IsFailure)return c; return c.Value!.EntidadeId.HasValue?c:Result<AgroAccessContext>.Failure("Entidade atual é obrigatória para Agro.");}
    private static AgroProgramaRuralFiltro Page(AgroProgramaRuralFiltro f)=>f with{Page=Math.Max(1,f.Page),PageSize=Math.Clamp(f.PageSize,1,100)}; private static AgroBeneficioConcessaoFiltro Page(AgroBeneficioConcessaoFiltro f)=>f with{Page=Math.Max(1,f.Page),PageSize=Math.Clamp(f.PageSize,1,100)};
}

public sealed class AgroInsumoService : IAgroInsumoService
{
    private readonly IAgroAccessChecker _access; private readonly AgroInsumoValidator _validator; private readonly IAgroProgramasRepository _repository; public AgroInsumoService(IAgroAccessChecker access,AgroInsumoValidator validator,IAgroProgramasRepository repository){_access=access;_validator=validator;_repository=repository;}
    public async Task<Result<PagedResult<AgroInsumoResponse>>> ListarAsync(AgroProgramaRuralFiltro filtro,CancellationToken ct){var c=await Ctx(AgroPermissions.InsumoVisualizar,ct); if(c.IsFailure)return Result<PagedResult<AgroInsumoResponse>>.Failure(c.Error!); return Result<PagedResult<AgroInsumoResponse>>.Success(await _repository.ListarInsumosAsync(c.Value!.TenantId,c.Value.EntidadeId!.Value,filtro,ct));}
    public async Task<Result<long>> CriarAsync(AgroInsumoCreateRequest request,CancellationToken ct){var c=await Ctx(AgroPermissions.InsumoCriar,ct); if(c.IsFailure)return Result<long>.Failure(c.Error!); var v=_validator.Validar(request); if(v.IsFailure)return Result<long>.Failure(v.Error!); return Result<long>.Success(await _repository.CriarInsumoAsync(c.Value!.TenantId,c.Value.EntidadeId!.Value,c.Value.UsuarioId,request,ct));}
    private async Task<Result<AgroAccessContext>> Ctx(string p,CancellationToken ct){var c=await _access.CheckAsync(new AgroAccessRequest(p,"agro.insumos"),ct); if(c.IsFailure)return c; return c.Value!.EntidadeId.HasValue?c:Result<AgroAccessContext>.Failure("Entidade atual é obrigatória para Agro.");}
}
public sealed class AgroDistribuicaoInsumoService : IAgroDistribuicaoInsumoService
{
    private readonly IAgroAccessChecker _access; private readonly AgroDistribuicaoInsumoValidator _validator; private readonly IAgroProgramasRepository _repository; public AgroDistribuicaoInsumoService(IAgroAccessChecker access,AgroDistribuicaoInsumoValidator validator,IAgroProgramasRepository repository){_access=access;_validator=validator;_repository=repository;}
    public async Task<Result<PagedResult<AgroDistribuicaoInsumoResponse>>> ListarAsync(AgroBeneficioConcessaoFiltro filtro,CancellationToken ct){var c=await Ctx(AgroPermissions.InsumoVisualizar,ct); if(c.IsFailure)return Result<PagedResult<AgroDistribuicaoInsumoResponse>>.Failure(c.Error!); return Result<PagedResult<AgroDistribuicaoInsumoResponse>>.Success(await _repository.ListarDistribuicoesAsync(c.Value!.TenantId,c.Value.EntidadeId!.Value,filtro,ct));}
    public async Task<Result<long>> CriarAsync(AgroDistribuicaoInsumoCreateRequest request,CancellationToken ct){var c=await Ctx(AgroPermissions.InsumoDistribuir,ct); if(c.IsFailure)return Result<long>.Failure(c.Error!); var v=_validator.Validar(request); if(v.IsFailure)return Result<long>.Failure(v.Error!); var numero=string.IsNullOrWhiteSpace(request.Numero)?$"AGR-INS-{DateTime.UtcNow.Year:D4}-{DateTime.UtcNow.Ticks%1000000:D6}":request.Numero!; return Result<long>.Success(await _repository.CriarDistribuicaoAsync(c.Value!.TenantId,c.Value.EntidadeId!.Value,c.Value.ExercicioId,c.Value.UsuarioId,request,numero,ct));}
    private async Task<Result<AgroAccessContext>> Ctx(string p,CancellationToken ct){var c=await _access.CheckAsync(new AgroAccessRequest(p,"agro.insumos"),ct); if(c.IsFailure)return c; return c.Value!.EntidadeId.HasValue?c:Result<AgroAccessContext>.Failure("Entidade atual é obrigatória para Agro.");}
}
