using Microsoft.Extensions.Logging;
using Sigov.Application.Agro.Permissions;
using Sigov.Application.Common;
using Sigov.Domain.Agro;
using Sigov.Domain.Agro.Enums;
using Sigov.Domain.Common;

namespace Sigov.Application.Agro.Programas;

public sealed class AgroProgramaRuralValidator { public Result Validar(AgroProgramaRuralCreateRequest r) => Validar(r.Codigo, r.Nome, r.TipoPrograma, r.VigenciaInicio, r.VigenciaFim); public Result Validar(AgroProgramaRuralUpdateRequest r) => Validar(r.Codigo, r.Nome, r.TipoPrograma, r.VigenciaInicio, r.VigenciaFim); private static Result Validar(string c,string n,string t,DateOnly? i,DateOnly? f){ if(!Enum.TryParse<AgroProgramaTipo>(t,true,out var tipo)) return Result.Failure("Tipo de programa inválido."); try{ _ = new ProgramaRural(1,1,c,n,tipo,i,f); return Result.Success(); }catch(Exception ex){ return Result.Failure(ex.Message);} } }
public sealed class AgroBeneficioRuralValidator { public Result Validar(AgroBeneficioRuralCreateRequest r) => Validar(r.Codigo,r.Nome,r.TipoBeneficio,r.ValorReferencia,r.QuantidadeLimite); public Result Validar(AgroBeneficioRuralUpdateRequest r) => Validar(r.Codigo,r.Nome,r.TipoBeneficio,r.ValorReferencia,r.QuantidadeLimite); public Result Validar(AgroBeneficioConcessaoCreateRequest r){ try{ _=new BeneficioRuralConcessao(1,1,1,r.BeneficioId,r.ProdutorId,"TMP",r.Quantidade,r.Valor,AgroBeneficioStatus.SOLICITADO); return Result.Success(); }catch(Exception ex){ return Result.Failure(ex.Message);} } private static Result Validar(string c,string n,string t,decimal? v,decimal? q){ if(!Enum.TryParse<AgroBeneficioTipo>(t,true,out var tipo)) return Result.Failure("Tipo de benefício inválido."); try{ _=new BeneficioRural(1,1,c,n,tipo,v,q); return Result.Success(); }catch(Exception ex){ return Result.Failure(ex.Message);} } }
public sealed class AgroInsumoValidator { public Result Validar(AgroInsumoCreateRequest r){ if(!Enum.TryParse<AgroInsumoTipo>(r.TipoInsumo,true,out var tipo)) return Result.Failure("Tipo de insumo inválido."); try{ _=new Insumo(1,1,r.Codigo,r.Nome,tipo,r.UnidadeMedida); return Result.Success(); }catch(Exception ex){ return Result.Failure(ex.Message);} } }
public sealed class AgroDistribuicaoInsumoValidator { public Result Validar(AgroDistribuicaoInsumoCreateRequest r){ try{ _=new DistribuicaoInsumo(1,1,1,r.InsumoId,r.ProdutorId,"TMP",r.Quantidade,r.ValorEstimado); return Result.Success(); }catch(Exception ex){ return Result.Failure(ex.Message);} } }
public sealed class AgroProgramaRuralPermissionChecker { private readonly IAgroAccessChecker _access; public AgroProgramaRuralPermissionChecker(IAgroAccessChecker access)=>_access=access; public Task<Result<AgroAccessContext>> CheckAsync(string permissao,string feature,CancellationToken ct)=>_access.CheckAsync(new AgroAccessRequest(permissao,feature),ct); }
public sealed class AgroBeneficioRuralPermissionChecker { private readonly IAgroAccessChecker _access; public AgroBeneficioRuralPermissionChecker(IAgroAccessChecker access)=>_access=access; public Task<Result<AgroAccessContext>> CheckAsync(string permissao,string feature,CancellationToken ct)=>_access.CheckAsync(new AgroAccessRequest(permissao,feature),ct); }
public sealed class AgroProgramaRuralAuditWriter { private readonly ILogger<AgroProgramaRuralAuditWriter> _logger; public AgroProgramaRuralAuditWriter(ILogger<AgroProgramaRuralAuditWriter> logger)=>_logger=logger; public Task WriteAsync(string tabela,string acao,long id,object dados,CancellationToken ct){ _logger.LogInformation("Auditoria Agro {Acao} em {Tabela} #{Id}.",acao,tabela,id); return Task.CompletedTask; } }
public sealed class AgroBeneficioRuralAuditWriter { private readonly ILogger<AgroBeneficioRuralAuditWriter> _logger; public AgroBeneficioRuralAuditWriter(ILogger<AgroBeneficioRuralAuditWriter> logger)=>_logger=logger; public Task WriteAsync(string tabela,string acao,long id,object dados,CancellationToken ct){ _logger.LogInformation("Auditoria Agro {Acao} em {Tabela} #{Id}.",acao,tabela,id); return Task.CompletedTask; } }
public sealed class AgroProgramaRuralMapper { public AgroProgramaRuralCreateRequest Normalize(AgroProgramaRuralCreateRequest r)=>r with { Codigo=r.Codigo.Trim().ToUpperInvariant(), Nome=r.Nome.Trim(), TipoPrograma=r.TipoPrograma.Trim().ToUpperInvariant() }; }
public sealed class AgroBeneficioRuralMapper { public AgroBeneficioRuralCreateRequest Normalize(AgroBeneficioRuralCreateRequest r)=>r with { Codigo=r.Codigo.Trim().ToUpperInvariant(), Nome=r.Nome.Trim(), TipoBeneficio=r.TipoBeneficio.Trim().ToUpperInvariant() }; }

public sealed class AgroProgramaRuralService : IAgroProgramaRuralService
{
    private readonly AgroProgramaRuralPermissionChecker _permission; private readonly AgroProgramaRuralValidator _validator; private readonly AgroProgramaRuralAuditWriter _audit; private readonly AgroProgramaRuralMapper _mapper; private readonly IAgroProgramasRepository _repository; private readonly ILogger<AgroProgramaRuralService> _logger;
    public AgroProgramaRuralService(AgroProgramaRuralPermissionChecker permission, AgroProgramaRuralValidator validator, AgroProgramaRuralAuditWriter audit, AgroProgramaRuralMapper mapper, IAgroProgramasRepository repository, ILogger<AgroProgramaRuralService> logger){_permission=permission;_validator=validator;_audit=audit;_mapper=mapper;_repository=repository;_logger=logger;}
    public async Task<Result<PagedResult<AgroProgramaRuralResponse>>> ListarAsync(AgroProgramaRuralFiltro filtro,CancellationToken ct){var c=await Ctx(AgroPermissions.ProgramaVisualizar,"agro.programas_rurais",ct); if(c.IsFailure) return Result<PagedResult<AgroProgramaRuralResponse>>.Failure(c.Error!); return Result<PagedResult<AgroProgramaRuralResponse>>.Success(await _repository.ListarProgramasAsync(c.Value!.TenantId,c.Value.EntidadeId!.Value,Page(filtro),ct));}
    public async Task<Result<AgroProgramaRuralResponse>> ObterAsync(long id,CancellationToken ct){var c=await Ctx(AgroPermissions.ProgramaVisualizar,"agro.programas_rurais",ct); if(c.IsFailure) return Result<AgroProgramaRuralResponse>.Failure(c.Error!); var row=await _repository.ObterProgramaAsync(c.Value!.TenantId,c.Value.EntidadeId!.Value,id,ct); return row is null?Result<AgroProgramaRuralResponse>.Failure("Programa não encontrado."):Result<AgroProgramaRuralResponse>.Success(row);}
    public async Task<Result<long>> CriarAsync(AgroProgramaRuralCreateRequest request,CancellationToken ct){var c=await Ctx(AgroPermissions.ProgramaCriar,"agro.programas_rurais",ct); if(c.IsFailure) return Result<long>.Failure(c.Error!); var req=_mapper.Normalize(request); var v=_validator.Validar(req); if(v.IsFailure) return Result<long>.Failure(v.Error!); var id=await _repository.CriarProgramaAsync(c.Value!.TenantId,c.Value.EntidadeId!.Value,c.Value.UsuarioId,req,ct); await _audit.WriteAsync("sigov.agro_programa_rural","CRIAR",id,req,ct); _logger.LogInformation("Programa rural {Id} criado.",id); return Result<long>.Success(id);}
    public async Task<Result> AtualizarAsync(long id,AgroProgramaRuralUpdateRequest request,CancellationToken ct){var c=await Ctx(AgroPermissions.ProgramaEditar,"agro.programas_rurais",ct); if(c.IsFailure) return Result.Failure(c.Error!); var v=_validator.Validar(request); if(v.IsFailure) return v; await _repository.AtualizarProgramaAsync(c.Value!.TenantId,c.Value.EntidadeId!.Value,id,c.Value.UsuarioId,request,ct); await _audit.WriteAsync("sigov.agro_programa_rural","EDITAR",id,request,ct); return Result.Success();}
    public async Task<Result> ExcluirAsync(long id,CancellationToken ct){var c=await Ctx(AgroPermissions.ProgramaExcluir,"agro.programas_rurais",ct); if(c.IsFailure) return Result.Failure(c.Error!); await _repository.ExcluirProgramaAsync(c.Value!.TenantId,c.Value.EntidadeId!.Value,id,c.Value.UsuarioId,ct); await _audit.WriteAsync("sigov.agro_programa_rural","EXCLUIR",id,new{isDeleted=true},ct); return Result.Success();}
    private async Task<Result<AgroAccessContext>> Ctx(string p,string f,CancellationToken ct){var c=await _permission.CheckAsync(p,f,ct); if(c.IsFailure) return c; return c.Value!.EntidadeId.HasValue?c:Result<AgroAccessContext>.Failure("Entidade atual é obrigatória para Agro.");}
    private static AgroProgramaRuralFiltro Page(AgroProgramaRuralFiltro f)=>f with{Page=Math.Max(1,f.Page),PageSize=Math.Clamp(f.PageSize,1,100)};
}
