using System.Text;
using System.Text.Json;
using Dapper;
using Sigov.Application.Tributario.ReceitaMunicipal;
using Sigov.Infrastructure.Persistence.Dapper;
namespace Sigov.Infrastructure.Tributario.ReceitaMunicipal;
public sealed class TributarioReceitaRepository(DapperContext context) : ITributarioReceitaRepository
{
 private static readonly IReadOnlyDictionary<string,(string Table,string Code,string Description,string Status,string? Value)> Resources = new Dictionary<string,(string,string,string,string,string?)>(StringComparer.OrdinalIgnoreCase){
  ["contribuintes"]=("tributario_contribuinte","coalesce(inscricao_municipal,documento)","nome_razao_social","situacao",null),["imoveis"]=("tributario_imovel","inscricao_imobiliaria","logradouro||coalesce(', '||numero,'')","situacao","valor_venal_total"),["mobiliario"]=("tributario_mobiliario","inscricao_municipal","cnae_principal||' - '||regime_tributario","situacao",null),["exercicios"]=("tributario_exercicio","ano::text","inicio::text||' a '||fim::text","status",null),["tributos"]=("tributario_tributo","codigo","nome","tipo",null),["parametros"]=("tributario_parametro_tributario","versao::text","vigencia_inicio::text","case when ativo then 'ATIVO' else 'INATIVO' end","aliquota"),["lancamentos"]=("tributario_lancamento","numero","competencia","status","valor_total"),["guias"]=("tributario_guia","numero","'Vencimento '||vencimento::text","status","valor"),["pagamentos"]=("tributario_pagamento","id::text","pago_at::text","status","valor_pago"),["divida-ativa"]=("tributario_divida_ativa","numero_inscricao","coalesce(livro,'')||'/'||coalesce(folha,'')","status","valor_atualizado"),["parcelamentos"]=("tributario_parcelamento","numero","quantidade_parcelas||' parcelas'","status","valor_parcela"),["fiscalizacoes"]=("tributario_fiscalizacao","numero_ordem","tipo","status",null),["notificacoes"]=("tributario_notificacao","numero","tipo","status",null),["autos-infracao"]=("tributario_auto_infracao","numero","descricao","status","valor_multa"),["certidoes"]=("tributario_certidao","codigo_validacao","tipo","case when revogada_at is null then 'VALIDA' else 'REVOGADA' end",null)};
 private static CommandDefinition Cmd(string sql,object? args,CancellationToken ct)=>new(sql,args,cancellationToken:ct);
 public async Task<TributarioDashboard> DashboardAsync(long t,long e,CancellationToken ct){const string sql=@"select
 (select count(*) from sigov.tributario_contribuinte where tenant_id=@t and entidade_id=@e and situacao='ATIVO' and not is_deleted) Contribuintes,
 (select count(*) from sigov.tributario_imovel where tenant_id=@t and entidade_id=@e and not is_deleted) Imoveis,
 (select count(*) from sigov.tributario_mobiliario where tenant_id=@t and entidade_id=@e and not is_deleted) Mobiliarios,
 (select count(*) from sigov.tributario_lancamento l join sigov.tributario_exercicio x on x.id=l.exercicio_id where l.tenant_id=@t and l.entidade_id=@e and x.ano=extract(year from current_date) and not l.is_deleted) Lancamentos,
 (select count(*) from sigov.tributario_guia where tenant_id=@t and entidade_id=@e and not is_deleted) Guias,
 (select coalesce(sum(valor_total),0) from sigov.tributario_lancamento where tenant_id=@t and entidade_id=@e and status<>'CANCELADO' and not is_deleted) Lancado,
 (select coalesce(sum(valor_pago),0) from sigov.tributario_pagamento where tenant_id=@t and entidade_id=@e and status='CONFIRMADO' and not is_deleted) Arrecadado,
 (select coalesce(sum(valor_total),0) from sigov.tributario_lancamento where tenant_id=@t and entidade_id=@e and vencimento<current_date and status in('ABERTO','VENCIDO') and not is_deleted) Inadimplencia,
 (select coalesce(sum(valor_atualizado),0) from sigov.tributario_divida_ativa where tenant_id=@t and entidade_id=@e and status not in('QUITADA','CANCELADA') and not is_deleted) Divida,
 (select count(*) from sigov.tributario_parcelamento where tenant_id=@t and entidade_id=@e and status in('ATIVO','APROVADO') and not is_deleted) Parcelamentos,
 (select count(*) from sigov.tributario_fiscalizacao where tenant_id=@t and entidade_id=@e and status='ABERTA' and not is_deleted) Fiscalizacoes,
 (select count(*) from sigov.tributario_certidao where tenant_id=@t and entidade_id=@e and not is_deleted) Certidoes,
 (select count(*) from sigov.tributario_guia where tenant_id=@t and entidade_id=@e and status='EMITIDA' and vencimento between current_date and current_date+7 and not is_deleted) Vencimentos,
 (select count(*) from sigov.tributario_contribuinte where tenant_id=@t and entidade_id=@e and (email is null or endereco='{}'::jsonb) and not is_deleted) Inconsistencias"; using var db=context.CreateConnection();var x=await db.QuerySingleAsync<Row>(Cmd(sql,new{t,e},ct));var alerts=new List<string>();if(x.Vencimentos>0)alerts.Add($"{x.Vencimentos} guia(s) vencem nos próximos 7 dias.");if(x.Inconsistencias>0)alerts.Add($"{x.Inconsistencias} contribuinte(s) com cadastro incompleto.");return new(x.Contribuintes,x.Imoveis,x.Mobiliarios,x.Lancamentos,x.Guias,x.Lancado,x.Arrecadado,x.Inadimplencia,x.Divida,x.Parcelamentos,x.Fiscalizacoes,x.Certidoes,alerts);}
 public async Task<TributarioPagina> ListarAsync(long t,long e,string recurso,string? busca,string? status,int pagina,int tamanho,CancellationToken ct){var r=Resolve(recurso);pagina=Math.Max(1,pagina);tamanho=Math.Clamp(tamanho,1,100);var where=$"tenant_id=@t and entidade_id=@e and not is_deleted and (@status is null or {r.Status}=@status) and (@busca is null or ({r.Code}) ilike '%'||@busca||'%' or ({r.Description}) ilike '%'||@busca||'%')";var sql=$"select id,{r.Code} Codigo,{r.Description} Descricao,{r.Status} Status,{(r.Value??"null::numeric")} Valor,created_at CriadoEm from sigov.{r.Table} where {where} order by id desc limit @size offset @off;select count(*) from sigov.{r.Table} where {where}";using var db=context.CreateConnection();using var multi=await db.QueryMultipleAsync(Cmd(sql,new{t,e,busca=Null(busca),status=Null(status),size=tamanho,off=(pagina-1)*tamanho},ct));return new((await multi.ReadAsync<TributarioLinha>()).AsList(),pagina,tamanho,await multi.ReadSingleAsync<long>(),recurso);}
 public async Task<long> CriarContribuinteAsync(TributarioContexto c,ContribuinteRequest r,CancellationToken ct){if(r.TipoPessoa is not("F" or "J"))throw new ArgumentException("Tipo de pessoa inválido.");var doc=new string(r.Documento.Where(char.IsDigit).ToArray());if((r.TipoPessoa=="F"&&doc.Length!=11)||(r.TipoPessoa=="J"&&doc.Length!=14))throw new ArgumentException("CPF/CNPJ inválido para o tipo informado.");const string sql="insert into sigov.tributario_contribuinte(tenant_id,entidade_id,tipo_pessoa,documento,nome_razao_social,nome_fantasia,inscricao_municipal,email,telefone,endereco,situacao,created_by) values(@TenantId,@EntidadeId,@TipoPessoa,@doc,@NomeRazaoSocial,@NomeFantasia,@InscricaoMunicipal,@Email,@Telefone,jsonb_build_object('logradouro',@Logradouro,'numero',@Numero,'bairro',@Bairro),@Situacao,@UsuarioId) returning id";using var db=context.CreateConnection();return await db.ExecuteScalarAsync<long>(Cmd(sql,new{c.TenantId,c.EntidadeId,c.UsuarioId,r.TipoPessoa,doc,r.NomeRazaoSocial,r.NomeFantasia,r.InscricaoMunicipal,r.Email,r.Telefone,r.Logradouro,r.Numero,r.Bairro,r.Situacao},ct));}
 public async Task<byte[]> ExportarCsvAsync(long t,long e,string recurso,CancellationToken ct){var page=await ListarAsync(t,e,recurso,null,null,1,10000,ct);var csv=new StringBuilder("id;codigo;descricao;status;valor;criado_em\n");foreach(var x in page.Items)csv.Append(x.Id).Append(';').Append(Clean(x.Codigo)).Append(';').Append(Clean(x.Descricao)).Append(';').Append(Clean(x.Status)).Append(';').Append(x.Valor?.ToString(System.Globalization.CultureInfo.InvariantCulture)).Append(';').Append(x.CriadoEm.ToString("O")).Append('\n');return Encoding.UTF8.GetPreamble().Concat(Encoding.UTF8.GetBytes(csv.ToString())).ToArray();}
 public async Task RegistrarAuditoriaAsync(TributarioContexto c,string acao,string recurso,long? id,string finalidade,CancellationToken ct){using var db=context.CreateConnection();await db.ExecuteAsync(Cmd("insert into sigov.tributario_auditoria(tenant_id,entidade_id,usuario_id,acao,recurso,recurso_id,finalidade,correlation_id,dados_minimizados) values(@TenantId,@EntidadeId,@UsuarioId,@acao,@recurso,@id,@finalidade,@CorrelationId,'{}')",new{c.TenantId,c.EntidadeId,c.UsuarioId,acao,recurso,id,finalidade,c.CorrelationId},ct));}
 private static (string Table,string Code,string Description,string Status,string? Value) Resolve(string r)=>Resources.TryGetValue(r,out var v)?v:throw new ArgumentException("Relatório tributário inválido.");private static string? Null(string? s)=>string.IsNullOrWhiteSpace(s)?null:s.Trim();private static string Clean(string? s)=>(s??"").Replace(';',',').Replace('\n',' ');private sealed record Row(long Contribuintes,long Imoveis,long Mobiliarios,long Lancamentos,long Guias,decimal Lancado,decimal Arrecadado,decimal Inadimplencia,decimal Divida,long Parcelamentos,long Fiscalizacoes,long Certidoes,long Vencimentos,long Inconsistencias);
}
