using Sigov.Application.Common;
using Sigov.Domain.Common;
namespace Sigov.Application.Agro.InfraestruturaRural;
public sealed record AgroEstradaVicinalFiltro(int Page=1,int PageSize=20,string? Busca=null,string? Status=null);
public sealed record AgroEstradaVicinalCreateRequest(string Codigo,string Nome,string? LocalidadeInicio,string? LocalidadeFim,string? ComunidadesAtendidasJson,decimal? ExtensaoKm,string? TipoRevestimento,string Situacao,decimal? LatitudeInicio,decimal? LongitudeInicio,decimal? LatitudeFim,decimal? LongitudeFim,string? GeoJson,string? Observacao);
public sealed record AgroEstradaVicinalUpdateRequest(string Codigo,string Nome,string? LocalidadeInicio,string? LocalidadeFim,string? ComunidadesAtendidasJson,decimal? ExtensaoKm,string? TipoRevestimento,string Situacao,decimal? LatitudeInicio,decimal? LongitudeInicio,decimal? LatitudeFim,decimal? LongitudeFim,string? GeoJson,string? Observacao);
public sealed record AgroEstradaVicinalResponse(long Id,long TenantId,long EntidadeId,string Codigo,string Nome,decimal? ExtensaoKm,string? TipoRevestimento,string Situacao,decimal? LatitudeInicio,decimal? LongitudeInicio,decimal? LatitudeFim,decimal? LongitudeFim,string? GeoJson,string? Observacao,bool Ativo);
public sealed record AgroPontoCriticoCreateRequest(long? EstradaVicinalId,string TipoPonto,string Descricao,string Severidade,string Status,decimal? Latitude,decimal? Longitude,string? GeoJson,string? EvidenciasJson,string? Observacao);
public sealed record AgroPontoCriticoResponse(long Id,long TenantId,long EntidadeId,long? EstradaVicinalId,string TipoPonto,string Descricao,string Severidade,string Status,decimal? Latitude,decimal? Longitude,string? GeoJson,bool Ativo);
public sealed record AgroOcorrenciaRuralCreateRequest(long? ProdutorId,long? PropriedadeId,long? EstradaVicinalId,long? PontoCriticoId,string Numero,string TipoOcorrencia,string Descricao,DateTime? DataOcorrencia,string Severidade,string Status,decimal? Latitude,decimal? Longitude,string? EvidenciasJson);
public sealed record AgroOcorrenciaRuralResponse(long Id,long TenantId,long EntidadeId,long? ExercicioId,string Numero,string TipoOcorrencia,string Descricao,string Severidade,string Status,decimal? Latitude,decimal? Longitude,bool Ativo);
public sealed record AgroManutencaoRuralCreateRequest(long? EstradaVicinalId,long? PontoCriticoId,long? OcorrenciaId,string Numero,string TipoManutencao,string Descricao,DateOnly? DataProgramada,DateOnly? DataExecucao,string Status,string? EquipeResponsavel,long? MaquinaId,decimal? CustoEstimado,decimal? CustoRealizado,string? Observacao);
public sealed record AgroManutencaoRuralResponse(long Id,long TenantId,long EntidadeId,long? ExercicioId,string Numero,string TipoManutencao,string Descricao,DateOnly? DataProgramada,DateOnly? DataExecucao,string Status,decimal? CustoEstimado,decimal? CustoRealizado,bool Ativo);
public interface IAgroInfraestruturaRuralRepository{Task<PagedResult<AgroEstradaVicinalResponse>> ListarEstradasAsync(long tenantId,long entidadeId,AgroEstradaVicinalFiltro filtro,CancellationToken ct);Task<AgroEstradaVicinalResponse?> ObterEstradaAsync(long tenantId,long entidadeId,long id,CancellationToken ct);Task<long> CriarEstradaAsync(long tenantId,long entidadeId,long? usuarioId,AgroEstradaVicinalCreateRequest r,CancellationToken ct);Task AtualizarEstradaAsync(long tenantId,long entidadeId,long id,long? usuarioId,AgroEstradaVicinalUpdateRequest r,CancellationToken ct);Task ExcluirEstradaAsync(long tenantId,long entidadeId,long id,long? usuarioId,CancellationToken ct);Task<PagedResult<AgroPontoCriticoResponse>> ListarPontosAsync(long tenantId,long entidadeId,AgroEstradaVicinalFiltro filtro,CancellationToken ct);Task<long> CriarPontoAsync(long tenantId,long entidadeId,long? usuarioId,AgroPontoCriticoCreateRequest r,CancellationToken ct);Task AtualizarPontoStatusAsync(long tenantId,long entidadeId,long id,string status,long? usuarioId,CancellationToken ct);Task<PagedResult<AgroOcorrenciaRuralResponse>> ListarOcorrenciasAsync(long tenantId,long entidadeId,long? exercicioId,AgroEstradaVicinalFiltro filtro,CancellationToken ct);Task<AgroOcorrenciaRuralResponse?> ObterOcorrenciaAsync(long tenantId,long entidadeId,long id,CancellationToken ct);Task<long> CriarOcorrenciaAsync(long tenantId,long entidadeId,long? exercicioId,long? usuarioId,AgroOcorrenciaRuralCreateRequest r,CancellationToken ct);Task AtualizarOcorrenciaStatusAsync(long tenantId,long entidadeId,long id,string status,long? usuarioId,CancellationToken ct);Task<PagedResult<AgroManutencaoRuralResponse>> ListarManutencoesAsync(long tenantId,long entidadeId,long? exercicioId,AgroEstradaVicinalFiltro filtro,CancellationToken ct);Task<long> CriarManutencaoAsync(long tenantId,long entidadeId,long? exercicioId,long? usuarioId,AgroManutencaoRuralCreateRequest r,CancellationToken ct);Task AtualizarManutencaoStatusAsync(long tenantId,long entidadeId,long id,string status,DateOnly? dataExecucao,long? usuarioId,CancellationToken ct);}
public interface IAgroEstradaVicinalService{Task<Result<PagedResult<AgroEstradaVicinalResponse>>> ListarAsync(AgroEstradaVicinalFiltro f,CancellationToken ct);Task<Result<AgroEstradaVicinalResponse>> ObterAsync(long id,CancellationToken ct);Task<Result<long>> CriarAsync(AgroEstradaVicinalCreateRequest r,CancellationToken ct);Task<Result> AtualizarAsync(long id,AgroEstradaVicinalUpdateRequest r,CancellationToken ct);Task<Result> ExcluirAsync(long id,CancellationToken ct);} 
public interface IAgroPontoCriticoService{Task<Result<PagedResult<AgroPontoCriticoResponse>>> ListarAsync(AgroEstradaVicinalFiltro f,CancellationToken ct);Task<Result<long>> CriarAsync(long? estradaId,AgroPontoCriticoCreateRequest r,CancellationToken ct);Task<Result> AtualizarAsync(long id,AgroPontoCriticoCreateRequest r,CancellationToken ct);Task<Result> ResolverAsync(long id,CancellationToken ct);} 
public interface IAgroOcorrenciaRuralService{Task<Result<PagedResult<AgroOcorrenciaRuralResponse>>> ListarAsync(AgroEstradaVicinalFiltro f,CancellationToken ct);Task<Result<AgroOcorrenciaRuralResponse>> ObterAsync(long id,CancellationToken ct);Task<Result<long>> CriarAsync(AgroOcorrenciaRuralCreateRequest r,CancellationToken ct);Task<Result> AtualizarAsync(long id,AgroOcorrenciaRuralCreateRequest r,CancellationToken ct);Task<Result> ResolverAsync(long id,CancellationToken ct);Task<Result> CancelarAsync(long id,CancellationToken ct);} 
public interface IAgroManutencaoRuralService{Task<Result<PagedResult<AgroManutencaoRuralResponse>>> ListarAsync(AgroEstradaVicinalFiltro f,CancellationToken ct);Task<Result<long>> CriarAsync(AgroManutencaoRuralCreateRequest r,CancellationToken ct);Task<Result> ExecutarAsync(long id,CancellationToken ct);Task<Result> CancelarAsync(long id,CancellationToken ct);} 
