using System.ComponentModel.DataAnnotations;

namespace Sigov.Web.Models.Processos;

public sealed class ProcessoDigitalFormViewModel { public long? Id { get; set; } [Required] [Display(Name="Tipo de processo")] public long TipoProcessoId { get; set; } [Required, StringLength(250)] public string Assunto { get; set; } = string.Empty; public string? Descricao { get; set; } [Display(Name="Interessado")] public long? InteressadoPessoaId { get; set; } [Display(Name="Unidade origem")] public long? UnidadeOrigemId { get; set; } [Display(Name="Unidade atual")] public long? UnidadeAtualId { get; set; } [Required] public string Prioridade { get; set; } = "NORMAL"; public bool Sigiloso { get; set; } [Display(Name="Prazo")] public DateTimeOffset? PrazoRespostaAt { get; set; } public string? Observacao { get; set; } }
public sealed class ProcessoDigitalFiltroViewModel { public string? Numero { get; set; } public string? Assunto { get; set; } public long? TipoProcessoId { get; set; } public string? Status { get; set; } public string? Prioridade { get; set; } public long? InteressadoPessoaId { get; set; } public long? UnidadeAtualId { get; set; } public DateTimeOffset? Inicio { get; set; } public DateTimeOffset? Fim { get; set; } public bool? Sigiloso { get; set; } public int Page { get; set; } = 1; public int PageSize { get; set; } = 20; }
public sealed class ProcessoMovimentacaoFormViewModel { public long ProcessoId { get; set; } public long? UnidadeDestinoId { get; set; } public long? UsuarioDestinoId { get; set; } [Required] public string Despacho { get; set; } = string.Empty; public string? StatusNovo { get; set; } }
public sealed class ProcessoParecerFormViewModel { public long ProcessoId { get; set; } [Required, StringLength(150)] public string Titulo { get; set; } = string.Empty; [Required] public string Texto { get; set; } = string.Empty; [Required] public string TipoParecer { get; set; } = "TECNICO"; public bool Sigiloso { get; set; } }
public sealed class ProtocoloFormViewModel { public long? Id { get; set; } public long? PessoaId { get; set; } [Required, StringLength(250)] public string Assunto { get; set; } = string.Empty; public string? Descricao { get; set; } [Required] public string Canal { get; set; } = "PRESENCIAL"; public long? UsuarioResponsavelId { get; set; } }
public sealed class ProtocoloFiltroViewModel { public string? Numero { get; set; } public string? Status { get; set; } public long? PessoaId { get; set; } public int Page { get; set; } = 1; public int PageSize { get; set; } = 20; }
public sealed class OuvidoriaFormViewModel { public long? Id { get; set; } public long? PessoaId { get; set; } [Required] public string TipoManifestacao { get; set; } = "SOLICITACAO"; [Required, StringLength(250)] public string Assunto { get; set; } = string.Empty; [Required] public string Descricao { get; set; } = string.Empty; public bool Anonima { get; set; } public bool Sigilosa { get; set; } = true; }
public sealed class OuvidoriaFiltroViewModel { public string? Numero { get; set; } public string? Status { get; set; } public string? TipoManifestacao { get; set; } public int Page { get; set; } = 1; public int PageSize { get; set; } = 20; }
public sealed class DiarioPublicacaoFormViewModel { public long? Id { get; set; } [Required] public string NumeroEdicao { get; set; } = string.Empty; [Required] public DateTime DataPublicacao { get; set; } = DateTime.Today; [Required, StringLength(250)] public string Titulo { get; set; } = string.Empty; public string? Descricao { get; set; } }
public sealed class AtoOficialFormViewModel { public long DiarioOficialPublicacaoId { get; set; } [Required] public string TipoAto { get; set; } = string.Empty; public string? Numero { get; set; } [Required, StringLength(250)] public string Titulo { get; set; } = string.Empty; [Required] public string Texto { get; set; } = string.Empty; public DateTime? DataAto { get; set; } public string? Origem { get; set; } }
