using System.Text.Json;
using Dapper;
using Sigov.Application.Bloco8;
using Sigov.Application.Common;
using Sigov.Infrastructure.Persistence.Dapper;
using Sigov.Infrastructure.Persistence.Repositories;

namespace Sigov.Infrastructure.Bloco8;

public sealed class Bloco8Repository : BaseRepository,IBloco8Repository,IProcessosDigitaisRepository,IGedRepository,IAssinaturaRepository,ILegislativoRepository,ITransparenciaRepository,IDiarioOficialRepository
{
 private static readonly HashSet<string> Tabelas=new(StringComparer.Ordinal){"processo_digital","processo_movimentacao","processo_despacho","processo_parecer","processo_prazo","processo_anexo_referencia","protocolo_externo","ged_documento","ged_documento_versao","ged_metadado","ged_validacao_publica","arquivo_fisico_caixa","arquivo_fisico_movimento","assinatura_documento","assinatura_participante","assinatura_evidencia","legislativo_parlamentar","legislativo_proposicao","legislativo_tramitacao","legislativo_parecer","legislativo_sessao","legislativo_sessao_pauta","legislativo_votacao","legislativo_voto","legislativo_norma","diario_oficial_edicao","diario_oficial_materia","diario_oficial_publicacao","transparencia_item_pntp","transparencia_evidencia","transparencia_pncp_evento","esic_pedido","esic_recurso","ouvidoria_manifestacao","atendimento_digital_chamado","atendimento_digital_mensagem","atendimento_digital_satisfacao"};
 private readonly DapperContext _context; public Bloco8Repository(DapperContext context)=>_context=context;
 public async Task<PagedResult<Bloco8RegistroDto>> ListarAsync(long tenantId,string tabela,int pagina,int tamanho,CancellationToken ct){tabela=Tabela(tabela);var offset=(pagina-1)*tamanho;var sql=$"select id as Id,codigo as Codigo,numero as Numero,ano as Ano,tipo as Tipo,status as Status,titulo as Titulo,descricao as Descricao,created_at as CreatedAt,sigiloso as Sigiloso from sigov.{tabela} where tenant_id=@TenantId and is_deleted=false order by id desc limit @Tamanho offset @Offset; select count(1) from sigov.{tabela} where tenant_id=@TenantId and is_deleted=false";using var c=_context.CreateConnection();using var multi=await c.QueryMultipleAsync(new CommandDefinition(sql,new{TenantId=tenantId,Tamanho=tamanho,Offset=offset},cancellationToken:ct));var items=(await multi.ReadAsync<Bloco8RegistroDto>()).AsList();var total=await multi.ReadSingleAsync<long>();return new(items,pagina,tamanho,total);}
 public async Task<Bloco8RegistroDto?> ObterAsync(long tenantId,string tabela,long id,CancellationToken ct){tabela=Tabela(tabela);var sql=$"select id as Id,codigo as Codigo,numero as Numero,ano as Ano,tipo as Tipo,status as Status,titulo as Titulo,descricao as Descricao,created_at as CreatedAt,sigiloso as Sigiloso from sigov.{tabela} where tenant_id=@TenantId and id=@Id and is_deleted=false";using var c=_context.CreateConnection();return await c.QuerySingleOrDefaultAsync<Bloco8RegistroDto>(new CommandDefinition(sql,new{TenantId=tenantId,Id=id},cancellationToken:ct));}
 public async Task<long> CriarAsync(long tenantId,long? entidadeId,long? exercicioId,long? usuarioId,string tabela,Bloco8RegistroRequest request,string correlationId,CancellationToken ct){tabela=Tabela(tabela);var sql=$"insert into sigov.{tabela}(tenant_id,entidade_id,exercicio_id,codigo,ano,tipo,status,titulo,descricao,referencia_id,responsavel_id,prazo_at,justificativa,sigiloso,dados,auditoria,correlation_id,created_by) values(@TenantId,@EntidadeId,@ExercicioId,@Codigo,@Ano,@Tipo,@Status,@Titulo,@Descricao,@ReferenciaId,@ResponsavelId,@PrazoAt,@Justificativa,@Sigiloso,@Dados::jsonb,jsonb_build_object('acao','CRIAR','em',now()),@CorrelationId::uuid,@UsuarioId) returning id";var ano=DateTime.UtcNow.Year;using var c=_context.CreateConnection();return await c.ExecuteScalarAsync<long>(new CommandDefinition(sql,new{TenantId=tenantId,EntidadeId=entidadeId??0,ExercicioId=exercicioId,request.Codigo,Ano=ano,request.Tipo,request.Status,request.Titulo,request.Descricao,request.ReferenciaId,request.ResponsavelId,request.PrazoAt,request.Justificativa,request.Sigiloso,Dados=JsonSerializer.Serialize(request.Dados??new()),CorrelationId=Guid.TryParse(correlationId,out var id)?id:Guid.NewGuid(),UsuarioId=usuarioId},cancellationToken:ct));}
 public async Task<bool> AlterarStatusAsync(long tenantId,string tabela,long id,string status,string? justificativa,long? usuarioId,string correlationId,CancellationToken ct){tabela=Tabela(tabela);var sql=$"update sigov.{tabela} set status=@Status,justificativa=coalesce(@Justificativa,justificativa),updated_at=now(),updated_by=@UsuarioId,correlation_id=@CorrelationId::uuid,auditoria=auditoria||jsonb_build_object('ultima_acao','STATUS','status',@Status,'em',now()) where tenant_id=@TenantId and id=@Id and is_deleted=false and not (status='ENCERRADO' and @Status not in ('REABERTO'))";using var c=_context.CreateConnection();return await c.ExecuteAsync(new CommandDefinition(sql,new{TenantId=tenantId,Id=id,Status=status,Justificativa=justificativa,UsuarioId=usuarioId,CorrelationId=Guid.TryParse(correlationId,out var cid)?cid:Guid.NewGuid()},cancellationToken:ct))>0;}
 public async Task<Bloco8DashboardDto> DashboardAsync(long tenantId,string tabela,CancellationToken ct){tabela=Tabela(tabela);var sql=$"select count(1) as Total,count(1) filter(where status in ('PENDENTE','ABERTO','EM_TRAMITACAO')) as Pendentes,count(1) filter(where prazo_at<now() and status not in ('ENCERRADO','CONCLUIDO','PUBLICADO')) as Vencidos,count(1) filter(where status in ('ENCERRADO','CONCLUIDO','PUBLICADO','ASSINADO')) as Concluidos from sigov.{tabela} where tenant_id=@TenantId and is_deleted=false";using var c=_context.CreateConnection();var k=await c.QuerySingleAsync<(long Total,long Pendentes,long Vencidos,long Concluidos)>(new CommandDefinition(sql,new{TenantId=tenantId},cancellationToken:ct));var recentes=await ListarAsync(tenantId,tabela,1,5,ct);return new(k.Total,k.Pendentes,k.Vencidos,k.Concluidos,recentes.Items);}
 private static string Tabela(string value)=>Tabelas.Contains(value)?value:throw new ArgumentException("Recurso do Bloco 8 inválido.");
}
