using System.Globalization;
using System.Text;
using System.Text.Json;
using Dapper;
using Sigov.Application.Habitacao;
using Sigov.Infrastructure.Persistence.Dapper;
namespace Sigov.Infrastructure.Habitacao;

public sealed class HabitacaoRepository(DapperContext db):IHabitacaoRepository
{
 private static readonly IReadOnlyDictionary<string,string> Tables=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase){["familias"]="habitacao_familia",["membros"]="habitacao_membro_familiar",["domicilios"]="habitacao_domicilio",["programas"]="habitacao_programa",["inscricoes"]="habitacao_inscricao",["classificacao"]="habitacao_classificacao",["visitas"]="habitacao_visita_social",["regularizacao"]="habitacao_regularizacao_fundiaria",["nucleos"]="habitacao_nucleo_urbano",["lotes"]="habitacao_lote",["unidades"]="habitacao_unidade_habitacional",["beneficiarios"]="habitacao_beneficiario",["auditoria"]="habitacao_auditoria"};
 public async Task<HabitacaoDashboard> DashboardAsync(HabitacaoContexto c,CancellationToken ct){using var cn=db.CreateConnection();const string sql="""select
(select count(*) from sigov.habitacao_familia where tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted) Familias,
(select count(*) from sigov.habitacao_inscricao where tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted and status not in ('CANCELADA','INABILITADA')) InscricoesAtivas,
(select count(*) from sigov.habitacao_familia where tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted and vulnerabilidade='ALTA') VulnerabilidadeAlta,
(select count(*) from sigov.habitacao_programa where tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted and status='ATIVO') ProgramasAtivos,
(select count(*) from sigov.habitacao_visita_social where tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted and status in ('AGENDADA','REMARCADA'))+(select count(*) from sigov.habitacao_visita_tecnica where tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted and status in ('AGENDADA','REMARCADA')) VisitasPendentes,
(select count(*) from sigov.habitacao_lote where tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted and status='DISPONIVEL')+(select count(*) from sigov.habitacao_unidade_habitacional where tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted and status='DISPONIVEL') Disponiveis,
(select count(*) from sigov.habitacao_regularizacao_fundiaria where tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted and etapa not in ('CONCLUIDA','SUSPENSA')) Regularizacoes,
(select count(*) from sigov.habitacao_beneficiario where tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted and status='SELECIONADO') Beneficiarios,
(select count(*) from sigov.habitacao_termo_entrega where tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted and status='PENDENTE') TermosPendentes""".Replace("+","");return await cn.QuerySingleAsync<HabitacaoDashboard>(new CommandDefinition(sql,c,cancellationToken:ct));}
 public async Task<HabitacaoPagina> ListarAsync(HabitacaoContexto c,string recurso,HabitacaoFiltro f,CancellationToken ct){var t=Table(recurso);using var cn=db.CreateConnection();var p=Math.Max(1,f.Pagina);var s=Math.Clamp(f.Tamanho,1,100);var a=new{c.TenantId,c.EntidadeId,f.Busca,f.Status,Limit=s,Offset=(p-1)*s};var w="tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted and (@Busca is null or coalesce(codigo,'') ilike '%'||@Busca||'%' or descricao ilike '%'||@Busca||'%') and (@Status is null or status=@Status)";var total=await cn.ExecuteScalarAsync<long>(new CommandDefinition($"select count(*) from sigov.{t} where {w}",a,cancellationToken:ct));var rows=(await cn.QueryAsync<HabitacaoRegistro>(new CommandDefinition($"select id,coalesce(codigo,'') codigo,descricao,status,created_at CriadoEm from sigov.{t} where {w} order by updated_at desc limit @Limit offset @Offset",a,cancellationToken:ct))).AsList();return new(rows,p,s,total);}
 public async Task<long> SalvarAsync(HabitacaoContexto c,string recurso,HabitacaoRegistroRequest r,long? id,CancellationToken ct){Validate(recurso,r);using var cn=db.CreateConnection();cn.Open();using var tx=cn.BeginTransaction();var t=Table(recurso);var a=new{r.Codigo,r.Descricao,r.Status,DadosJson=string.IsNullOrWhiteSpace(r.DadosJson)?"{}":r.DadosJson,r.Justificativa,c.TenantId,c.EntidadeId,c.UsuarioId,id};var sql=id is null?$"insert into sigov.{t}(codigo,descricao,status,dados,justificativa,tenant_id,entidade_id,created_by) values(@Codigo,@Descricao,@Status,cast(@DadosJson as jsonb),@Justificativa,@TenantId,@EntidadeId,@UsuarioId) returning id":$"update sigov.{t} set codigo=@Codigo,descricao=@Descricao,status=@Status,dados=cast(@DadosJson as jsonb),justificativa=@Justificativa,updated_at=now(),updated_by=@UsuarioId where id=@id and tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted returning id";var saved=await cn.ExecuteScalarAsync<long?>(new CommandDefinition(sql,a,tx,cancellationToken:ct))??throw new KeyNotFoundException("Registro não encontrado no contexto atual.");await Audit(c,cn,id is null?"CRIAR":"ALTERAR",recurso,saved,JsonSerializer.Serialize(r),tx,ct);tx.Commit();return saved;}
 public async Task ExcluirAsync(HabitacaoContexto c,string recurso,long id,string justificativa,CancellationToken ct){if(string.IsNullOrWhiteSpace(justificativa))throw new ArgumentException("Justificativa é obrigatória.");using var cn=db.CreateConnection();cn.Open();using var tx=cn.BeginTransaction();var n=await cn.ExecuteAsync(new CommandDefinition($"update sigov.{Table(recurso)} set ativo=false,is_deleted=true,deleted_at=now(),deleted_by=@UsuarioId where id=@id and tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted",new{id,c.UsuarioId,c.TenantId,c.EntidadeId},tx,cancellationToken:ct));if(n==0)throw new KeyNotFoundException("Registro não encontrado.");await Audit(c,cn,"EXCLUIR",recurso,id,JsonSerializer.Serialize(new{justificativa}),tx,ct);tx.Commit();}
 public async Task<byte[]> ExportarCsvAsync(HabitacaoContexto c,string recurso,CancellationToken ct){using var cn=db.CreateConnection();var rows=await cn.QueryAsync<dynamic>(new CommandDefinition($"select id,coalesce(codigo,'') codigo,descricao,status,created_at from sigov.{Table(recurso)} where tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted order by id",c,cancellationToken:ct));var b=new StringBuilder("id;codigo;descricao;status;criado_em\r\n");foreach(var x in rows)b.AppendLine($"{x.id};{Csv(x.codigo)};{Csv(x.descricao)};{Csv(x.status)};{x.created_at:O}");await Audit(c,cn,"EXPORTAR",recurso,null,null,null,ct);return new UTF8Encoding(true).GetBytes(b.ToString());}
 private static string Table(string r)=>Tables.TryGetValue(r,out var t)?t:throw new ArgumentException("Recurso habitacional inválido.");
 private static void Validate(string recurso,HabitacaoRegistroRequest r){if(string.IsNullOrWhiteSpace(r.Descricao))throw new ArgumentException("Descrição é obrigatória.");try{JsonDocument.Parse(r.DadosJson);}catch(JsonException){throw new ArgumentException("Dados complementares devem ser JSON válido.");}if((r.Status is "CANCELADA" or "INABILITADA" or "SUSPENSA" or "CONCLUIDA" or "REMARCADA" or "CANCELADO" or "ENTREGUE" or "SELECIONADO")&&string.IsNullOrWhiteSpace(r.Justificativa))throw new ArgumentException("Este estado exige justificativa.");if(recurso=="classificacao"&&JsonDocument.Parse(r.DadosJson).RootElement.TryGetProperty("pontuacao",out var p)&&p.GetDecimal()<0)throw new ArgumentException("Pontuação não pode ser negativa.");}
 private static string Csv(object? value){var s=Convert.ToString(value,CultureInfo.InvariantCulture)??"";if(s.Length>0&&"=+-@".Contains(s[0]))s="'"+s;return '"'+s.Replace("\"","\"\"")+'"';}
 private static Task Audit(HabitacaoContexto c,System.Data.IDbConnection cn,string acao,string recurso,long? id,string? depois,System.Data.IDbTransaction? tx,CancellationToken ct)=>cn.ExecuteAsync(new CommandDefinition("insert into sigov.habitacao_auditoria(tenant_id,entidade_id,acao,recurso,registro_id,usuario_id,depois,correlation_id,ip,descricao,status,dados,created_by) values(@TenantId,@EntidadeId,@acao,@recurso,@id,@UsuarioId,cast(@depois as jsonb),@CorrelationId,cast(@Ip as inet),@recurso,'REGISTRADA','{}',@UsuarioId)",new{c.TenantId,c.EntidadeId,acao,recurso,id,c.UsuarioId,depois,c.CorrelationId,c.Ip},tx,cancellationToken:ct));
}
