using System.Globalization;
using System.Text;
using System.Text.Json;
using Dapper;
using Sigov.Application.Habitacao;
using Sigov.Infrastructure.Persistence.Dapper;
namespace Sigov.Infrastructure.Habitacao;

public sealed class HabitacaoRepository(DapperContext db):IHabitacaoRepository
{
 private static readonly IReadOnlyDictionary<string,string> Tables=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase){["familias"]="habitacao_familia",["membros"]="habitacao_membro_familiar",["domicilios"]="habitacao_domicilio",["programas"]="habitacao_programa",["inscricoes"]="habitacao_inscricao",["classificacao"]="habitacao_classificacao",["visitas"]="habitacao_visita_social",["regularizacao"]="habitacao_regularizacao_fundiaria",["nucleos"]="habitacao_nucleo_urbano",["lotes"]="habitacao_lote",["unidades"]="habitacao_unidade_habitacional",["beneficiarios"]="habitacao_beneficiario",["auditoria"]="habitacao_auditoria"};
 private static readonly IReadOnlyDictionary<string,(string Columns,string Values)> InsertExtras=new Dictionary<string,(string,string)>(StringComparer.OrdinalIgnoreCase)
 {
  ["familias"]=(",responsavel_nome",",@Descricao"),
  ["membros"]=(",familia_id,nome,parentesco",",(cast(@DadosJson as jsonb)->>'familiaId')::bigint,@Descricao,coalesce(cast(@DadosJson as jsonb)->>'parentesco','NÃO INFORMADO')"),
  ["domicilios"]=(",familia_id",",(cast(@DadosJson as jsonb)->>'familiaId')::bigint"),
  ["programas"]=(",nome,modalidade,vigencia_inicio,vigencia_fim",",@Descricao,coalesce(cast(@DadosJson as jsonb)->>'modalidade','OUTRO'),(cast(@DadosJson as jsonb)->>'vigenciaInicio')::date,(cast(@DadosJson as jsonb)->>'vigenciaFim')::date"),
  ["inscricoes"]=(",familia_id,programa_id",",(cast(@DadosJson as jsonb)->>'familiaId')::bigint,(cast(@DadosJson as jsonb)->>'programaId')::bigint"),
  ["classificacao"]=(",programa_id,inscricao_id,familia_id,posicao,pontuacao",",(cast(@DadosJson as jsonb)->>'programaId')::bigint,(cast(@DadosJson as jsonb)->>'inscricaoId')::bigint,(cast(@DadosJson as jsonb)->>'familiaId')::bigint,(cast(@DadosJson as jsonb)->>'posicao')::integer,coalesce((cast(@DadosJson as jsonb)->>'pontuacao')::numeric,0)"),
  ["visitas"]=(",familia_id,agendada_em,responsavel",",(cast(@DadosJson as jsonb)->>'familiaId')::bigint,(cast(@DadosJson as jsonb)->>'agendadaEm')::timestamptz,coalesce(cast(@DadosJson as jsonb)->>'responsavel',@Descricao)"),
  ["regularizacao"]=(",nucleo_id,etapa",",(cast(@DadosJson as jsonb)->>'nucleoId')::bigint,@Status"),
  ["nucleos"]=(",nome",",@Descricao"),
  ["lotes"]=(",nucleo_id,lote,inscricao_id,beneficiario_id",",(cast(@DadosJson as jsonb)->>'nucleoId')::bigint,coalesce(cast(@DadosJson as jsonb)->>'lote',@Codigo),nullif(cast(@DadosJson as jsonb)->>'inscricaoId','')::bigint,nullif(cast(@DadosJson as jsonb)->>'beneficiarioId','')::bigint"),
  ["unidades"]=(",inscricao_id,beneficiario_id",",nullif(cast(@DadosJson as jsonb)->>'inscricaoId','')::bigint,nullif(cast(@DadosJson as jsonb)->>'beneficiarioId','')::bigint"),
  ["beneficiarios"]=(",familia_id,programa_id,inscricao_id,selecionado_por",",(cast(@DadosJson as jsonb)->>'familiaId')::bigint,(cast(@DadosJson as jsonb)->>'programaId')::bigint,(cast(@DadosJson as jsonb)->>'inscricaoId')::bigint,@UsuarioId")
 };
 public async Task<HabitacaoDashboard> DashboardAsync(HabitacaoContexto c,CancellationToken ct){using var cn=db.CreateConnection();const string sql="""select
(select count(*) from sigov.habitacao_familia where tenant_id=@TenantId and entidade_id=@EntidadeId and ativo and not is_deleted) Familias,
(select count(*) from sigov.habitacao_inscricao where tenant_id=@TenantId and entidade_id=@EntidadeId and ativo and not is_deleted and status not in ('CANCELADA','INABILITADA')) InscricoesAtivas,
(select count(*) from sigov.habitacao_familia where tenant_id=@TenantId and entidade_id=@EntidadeId and ativo and not is_deleted and vulnerabilidade='ALTA') VulnerabilidadeAlta,
(select count(*) from sigov.habitacao_programa where tenant_id=@TenantId and entidade_id=@EntidadeId and ativo and not is_deleted and status='ATIVO') ProgramasAtivos,
(select count(*) from sigov.habitacao_visita_social where tenant_id=@TenantId and entidade_id=@EntidadeId and ativo and not is_deleted and status in ('AGENDADA','REMARCADA'))+(select count(*) from sigov.habitacao_visita_tecnica where tenant_id=@TenantId and entidade_id=@EntidadeId and ativo and not is_deleted and status in ('AGENDADA','REMARCADA')) VisitasPendentes,
(select count(*) from sigov.habitacao_lote where tenant_id=@TenantId and entidade_id=@EntidadeId and ativo and not is_deleted and status='DISPONIVEL')+(select count(*) from sigov.habitacao_unidade_habitacional where tenant_id=@TenantId and entidade_id=@EntidadeId and ativo and not is_deleted and status='DISPONIVEL') Disponiveis,
(select count(*) from sigov.habitacao_regularizacao_fundiaria where tenant_id=@TenantId and entidade_id=@EntidadeId and ativo and not is_deleted and etapa not in ('CONCLUIDA','SUSPENSA')) Regularizacoes,
(select count(*) from sigov.habitacao_beneficiario where tenant_id=@TenantId and entidade_id=@EntidadeId and ativo and not is_deleted and status='SELECIONADO') Beneficiarios,
(select count(*) from sigov.habitacao_termo_entrega where tenant_id=@TenantId and entidade_id=@EntidadeId and ativo and not is_deleted and status='PENDENTE') TermosPendentes""";return await cn.QuerySingleAsync<HabitacaoDashboard>(new CommandDefinition(sql,c,cancellationToken:ct));}
 public async Task<HabitacaoPagina> ListarAsync(HabitacaoContexto c,string recurso,HabitacaoFiltro f,CancellationToken ct){var t=Table(recurso);using var cn=db.CreateConnection();var p=Math.Max(1,f.Pagina);var s=Math.Clamp(f.Tamanho,1,100);var a=new{c.TenantId,c.EntidadeId,f.Busca,f.Status,Limit=s,Offset=(p-1)*s};var w="tenant_id=@TenantId and entidade_id=@EntidadeId and ativo and not is_deleted and (@Busca is null or coalesce(codigo,'') ilike '%'||@Busca||'%' or descricao ilike '%'||@Busca||'%') and (@Status is null or status=@Status)";var total=await cn.ExecuteScalarAsync<long>(new CommandDefinition($"select count(*) from sigov.{t} where {w}",a,cancellationToken:ct));var rows=(await cn.QueryAsync<HabitacaoRegistro>(new CommandDefinition($"select id,coalesce(codigo,'') codigo,descricao,status,created_at CriadoEm from sigov.{t} where {w} order by updated_at desc limit @Limit offset @Offset",a,cancellationToken:ct))).AsList();return new(rows,p,s,total);}
 public async Task<long> SalvarAsync(HabitacaoContexto c,string recurso,HabitacaoRegistroRequest r,long? id,CancellationToken ct){var dadosJson=NormalizeAndValidate(recurso,r);using var cn=db.CreateConnection();cn.Open();using var tx=cn.BeginTransaction();var t=Table(recurso);var a=new{r.Codigo,r.Descricao,r.Status,DadosJson=dadosJson,r.Justificativa,c.TenantId,c.EntidadeId,c.UsuarioId,id};var extra=InsertExtras[recurso];var sql=id is null?$"insert into sigov.{t}(codigo,descricao,status,dados,justificativa,tenant_id,entidade_id,created_by{extra.Columns}) values(@Codigo,@Descricao,@Status,cast(@DadosJson as jsonb),@Justificativa,@TenantId,@EntidadeId,@UsuarioId{extra.Values}) returning id":$"update sigov.{t} set codigo=@Codigo,descricao=@Descricao,status=@Status,dados=cast(@DadosJson as jsonb),justificativa=@Justificativa,updated_at=now(),updated_by=@UsuarioId where id=@id and tenant_id=@TenantId and entidade_id=@EntidadeId and ativo and not is_deleted returning id";var saved=await cn.ExecuteScalarAsync<long?>(new CommandDefinition(sql,a,tx,cancellationToken:ct))??throw new KeyNotFoundException("Registro não encontrado no contexto atual.");await Audit(c,cn,id is null?"CRIAR":"ALTERAR",recurso,saved,JsonSerializer.Serialize(new{r.Codigo,r.Status,JustificativaInformada=!string.IsNullOrWhiteSpace(r.Justificativa)}),tx,ct);tx.Commit();return saved;}
 public async Task ExcluirAsync(HabitacaoContexto c,string recurso,long id,string justificativa,CancellationToken ct){if(string.IsNullOrWhiteSpace(justificativa))throw new ArgumentException("Justificativa é obrigatória.");using var cn=db.CreateConnection();cn.Open();using var tx=cn.BeginTransaction();var n=await cn.ExecuteAsync(new CommandDefinition($"update sigov.{Table(recurso)} set ativo=false,is_deleted=true,deleted_at=now(),deleted_by=@UsuarioId where id=@id and tenant_id=@TenantId and entidade_id=@EntidadeId and ativo and not is_deleted",new{id,c.UsuarioId,c.TenantId,c.EntidadeId},tx,cancellationToken:ct));if(n==0)throw new KeyNotFoundException("Registro não encontrado.");await Audit(c,cn,"EXCLUIR",recurso,id,JsonSerializer.Serialize(new{justificativa}),tx,ct);tx.Commit();}
 public async Task<byte[]> ExportarCsvAsync(HabitacaoContexto c,string recurso,CancellationToken ct){using var cn=db.CreateConnection();cn.Open();using var tx=cn.BeginTransaction();var rows=await cn.QueryAsync<dynamic>(new CommandDefinition($"select id,coalesce(codigo,'') codigo,descricao,status,created_at from sigov.{Table(recurso)} where tenant_id=@TenantId and entidade_id=@EntidadeId and ativo and not is_deleted order by id",c,tx,cancellationToken:ct));var b=new StringBuilder("id;codigo;descricao;status;criado_em\r\n");foreach(var x in rows)b.AppendLine($"{x.id};{Csv(x.codigo)};{Csv(x.descricao)};{Csv(x.status)};{x.created_at:O}");await Audit(c,cn,"EXPORTAR",recurso,null,null,tx,ct);tx.Commit();return new UTF8Encoding(true).GetBytes(b.ToString());}
 private static string Table(string r)=>Tables.TryGetValue(r,out var t)?t:throw new ArgumentException("Recurso habitacional inválido.");
 private static string NormalizeAndValidate(string recurso,HabitacaoRegistroRequest r)
 {
  if(string.IsNullOrWhiteSpace(r.Descricao))throw new ArgumentException("Descrição é obrigatória.");
  var json=string.IsNullOrWhiteSpace(r.DadosJson)?"{}":r.DadosJson;
  JsonElement data;
  try{using var document=JsonDocument.Parse(json);if(document.RootElement.ValueKind!=JsonValueKind.Object)throw new ArgumentException("Dados complementares devem ser um objeto JSON.");data=document.RootElement.Clone();}
  catch(JsonException){throw new ArgumentException("Dados complementares devem ser JSON válido.");}
  if((r.Status is "CANCELADA" or "INABILITADA" or "SUSPENSA" or "CONCLUIDA" or "REMARCADA" or "CANCELADO" or "ENTREGUE")&&string.IsNullOrWhiteSpace(r.Justificativa))throw new ArgumentException("Este estado exige justificativa.");
  if(recurso=="classificacao"&&data.TryGetProperty("pontuacao",out var points)&&points.TryGetDecimal(out var score)&&score<0)throw new ArgumentException("Pontuação não pode ser negativa.");
  var requiredIds=recurso switch{"membros" or "domicilios" or "visitas"=>new[]{"familiaId"},"inscricoes"=>new[]{"familiaId","programaId"},"beneficiarios"=>new[]{"familiaId","programaId","inscricaoId"},"classificacao"=>new[]{"programaId","inscricaoId","familiaId"},"regularizacao" or "lotes"=>new[]{"nucleoId"},_=>Array.Empty<string>()};
  foreach(var required in requiredIds)if(!HasPositiveId(data,required))throw new ArgumentException($"O vínculo {required} é obrigatório.");
  if(recurso=="programas"&&(!data.TryGetProperty("vigenciaInicio",out _)||!data.TryGetProperty("vigenciaFim",out _)))throw new ArgumentException("Vigência inicial e final são obrigatórias.");
  if(recurso=="classificacao"&&(!data.TryGetProperty("posicao",out var position)||!position.TryGetInt32(out var rank)||rank<=0))throw new ArgumentException("Posição deve ser positiva.");
  if(recurso=="visitas"&&!data.TryGetProperty("agendadaEm",out _))throw new ArgumentException("Data de agendamento é obrigatória.");
  if(recurso=="lotes"&&string.IsNullOrWhiteSpace(r.Codigo)&&!data.TryGetProperty("lote",out _))throw new ArgumentException("Identificação do lote é obrigatória.");
  if(recurso=="beneficiarios"&&r.Status=="ENTREGUE"&&string.IsNullOrWhiteSpace(r.Justificativa))throw new ArgumentException("Entrega de benefício exige justificativa.");
  ValidateRange(data,"latitude",-90,90,"Latitude");ValidateRange(data,"longitude",-180,180,"Longitude");
  ValidateDates(data,"dataInicio","dataFim");ValidateDates(data,"vigenciaInicio","vigenciaFim");ValidateDates(data,"agendadaEm","realizadaEm");
  if((recurso is "lotes" or "unidades")&&r.Status=="ENTREGUE"&&!HasPositiveId(data,"inscricaoId")&&!HasPositiveId(data,"beneficiarioId"))throw new ArgumentException("Entrega exige vínculo com inscrição ou beneficiário.");
  if(recurso=="classificacao"&&data.TryGetProperty("manual",out var manual)&&manual.ValueKind==JsonValueKind.True&&string.IsNullOrWhiteSpace(r.Justificativa))throw new ArgumentException("Pontuação manual exige justificativa.");
  return json;
 }
 private static bool HasPositiveId(JsonElement data,string name)=>data.TryGetProperty(name,out var value)&&value.TryGetInt64(out var id)&&id>0;
 private static void ValidateRange(JsonElement data,string name,decimal min,decimal max,string label){if(data.TryGetProperty(name,out var value)&&value.ValueKind!=JsonValueKind.Null&&(!value.TryGetDecimal(out var number)||number<min||number>max))throw new ArgumentException($"{label} fora dos limites válidos.");}
 private static void ValidateDates(JsonElement data,string start,string end){if(data.TryGetProperty(start,out var a)&&data.TryGetProperty(end,out var b)&&a.ValueKind==JsonValueKind.String&&b.ValueKind==JsonValueKind.String&&DateTimeOffset.TryParse(a.GetString(),CultureInfo.InvariantCulture,DateTimeStyles.AssumeUniversal,out var begin)&&DateTimeOffset.TryParse(b.GetString(),CultureInfo.InvariantCulture,DateTimeStyles.AssumeUniversal,out var finish)&&finish<begin)throw new ArgumentException("A data final não pode ser anterior à data inicial.");}
 private static string Csv(object? value){var s=Convert.ToString(value,CultureInfo.InvariantCulture)??"";if(s.Length>0&&"=+-@".Contains(s[0]))s="'"+s;return '"'+s.Replace("\"","\"\"")+'"';}
 private static Task Audit(HabitacaoContexto c,System.Data.IDbConnection cn,string acao,string recurso,long? id,string? depois,System.Data.IDbTransaction? tx,CancellationToken ct)=>cn.ExecuteAsync(new CommandDefinition("insert into sigov.habitacao_auditoria(tenant_id,entidade_id,acao,recurso,registro_id,usuario_id,depois,correlation_id,ip,descricao,status,dados,created_by) values(@TenantId,@EntidadeId,@acao,@recurso,@id,@UsuarioId,cast(@depois as jsonb),@CorrelationId,cast(@Ip as inet),@recurso,'REGISTRADA','{}',@UsuarioId)",new{c.TenantId,c.EntidadeId,acao,recurso,id,c.UsuarioId,depois,c.CorrelationId,c.Ip},tx,cancellationToken:ct));
}
