using Dapper;
using Sigov.Application.Common;
using Sigov.Application.Financeiro;
using Sigov.Infrastructure.Persistence.Dapper;
using Sigov.Infrastructure.Persistence.Repositories;

namespace Sigov.Infrastructure.Financeiro;

public abstract class CrudFinanceiroRepository<TCreate, TUpdate, TFiltro, TResponse> : BaseRepository
{
    private readonly DapperContext _context;
    private readonly string _table;
    private readonly string _select;
    protected CrudFinanceiroRepository(DapperContext context, string table, string select) { _context = context; _table = table; _select = select; }
    public async Task<PagedResult<TResponse>> ListarAsync(long tenantId, long entidadeId, long exercicioId, TFiltro filtro, CancellationToken ct)
    {
        var (page, pageSize) = Page(filtro);
        var safePage = Math.Max(1, page); var safeSize = Math.Clamp(pageSize, 1, 100); var offset = (safePage - 1) * safeSize;
        var sql = $"select {_select} from {_table} where tenant_id=@TenantId and entidade_id=@EntidadeId and exercicio_id=@ExercicioId and is_deleted=false order by id desc limit @Limit offset @Offset; select count(1) from {_table} where tenant_id=@TenantId and entidade_id=@EntidadeId and exercicio_id=@ExercicioId and is_deleted=false;";
        using var cn = _context.CreateConnection();
        using var grid = await cn.QueryMultipleAsync(Command(sql, new { TenantId = tenantId, EntidadeId = entidadeId, ExercicioId = exercicioId, Limit = safeSize, Offset = offset }, ct)).ConfigureAwait(false);
        var rows = (await grid.ReadAsync<TResponse>().ConfigureAwait(false)).AsList();
        var total = await grid.ReadSingleAsync<long>().ConfigureAwait(false);
        return new PagedResult<TResponse>(rows, safePage, safeSize, total);
    }
    public async Task<TResponse?> ObterAsync(long tenantId, long entidadeId, long exercicioId, long id, CancellationToken ct)
    {
        var sql = $"select {_select} from {_table} where tenant_id=@TenantId and entidade_id=@EntidadeId and exercicio_id=@ExercicioId and id=@Id and is_deleted=false;";
        using var cn = _context.CreateConnection(); return await cn.QuerySingleOrDefaultAsync<TResponse>(Command(sql, new { TenantId = tenantId, EntidadeId = entidadeId, ExercicioId = exercicioId, Id = id }, ct)).ConfigureAwait(false);
    }
    public abstract Task<long> CriarAsync(long tenantId, long entidadeId, long exercicioId, TCreate request, long? usuarioId, CancellationToken ct);
    public abstract Task AtualizarAsync(long tenantId, long entidadeId, long exercicioId, long id, TUpdate request, long? usuarioId, CancellationToken ct);
    public async Task ExcluirAsync(long tenantId, long entidadeId, long exercicioId, long id, long? usuarioId, CancellationToken ct)
    { using var cn = _context.CreateConnection(); await cn.ExecuteAsync(Command($"update {_table} set is_deleted=true, ativo=false, deleted_at=now(), deleted_by=@UsuarioId where tenant_id=@TenantId and entidade_id=@EntidadeId and exercicio_id=@ExercicioId and id=@Id and is_deleted=false;", new { TenantId = tenantId, EntidadeId = entidadeId, ExercicioId = exercicioId, Id = id, UsuarioId = usuarioId }, ct)).ConfigureAwait(false); }
    protected DapperContext Context => _context;
    private static (int Page, int PageSize) Page(TFiltro filtro)
    { var type = typeof(TFiltro); return ((int?)type.GetProperty("Page")?.GetValue(filtro) ?? 1, (int?)type.GetProperty("PageSize")?.GetValue(filtro) ?? 20); }
}

public sealed class PlanoContasRepository : CrudFinanceiroRepository<PlanoContasCreateRequest, PlanoContasUpdateRequest, PlanoContasFiltro, PlanoContasResponse>, IPlanoContasRepository
{
    public PlanoContasRepository(DapperContext c) : base(c, "sigov.plano_contas", "id, codigo, nome, tipo_conta as TipoConta, nivel, conta_pai_id as ContaPaiId, natureza_saldo as NaturezaSaldo, aceita_lancamento as AceitaLancamento, ativo") { }
    public override async Task<long> CriarAsync(long t, long e, long x, PlanoContasCreateRequest r, long? u, CancellationToken ct) { const string sql = "insert into sigov.plano_contas (tenant_id,entidade_id,exercicio_id,codigo,nome,tipo_conta,nivel,conta_pai_id,natureza_saldo,aceita_lancamento,created_by) values (@t,@e,@x,@Codigo,@Nome,@TipoConta,@Nivel,@ContaPaiId,@NaturezaSaldo,@AceitaLancamento,@u) returning id;"; using var cn = Context.CreateConnection(); return await cn.ExecuteScalarAsync<long>(Command(sql, new { t, e, x, r.Codigo, r.Nome, r.TipoConta, r.Nivel, r.ContaPaiId, r.NaturezaSaldo, r.AceitaLancamento, u }, ct)).ConfigureAwait(false); }
    public override async Task AtualizarAsync(long t, long e, long x, long id, PlanoContasUpdateRequest r, long? u, CancellationToken ct) { const string sql = "update sigov.plano_contas set codigo=@Codigo,nome=@Nome,tipo_conta=@TipoConta,nivel=@Nivel,conta_pai_id=@ContaPaiId,natureza_saldo=@NaturezaSaldo,aceita_lancamento=@AceitaLancamento,ativo=@Ativo,updated_at=now(),updated_by=@u where tenant_id=@t and entidade_id=@e and exercicio_id=@x and id=@id and is_deleted=false;"; using var cn = Context.CreateConnection(); await cn.ExecuteAsync(Command(sql, new { t, e, x, id, r.Codigo, r.Nome, r.TipoConta, r.Nivel, r.ContaPaiId, r.NaturezaSaldo, r.AceitaLancamento, r.Ativo, u }, ct)).ConfigureAwait(false); }
}
public sealed class FonteRecursoRepository : CrudFinanceiroRepository<FonteRecursoCreateRequest, FonteRecursoUpdateRequest, FonteRecursoFiltro, FonteRecursoResponse>, IFonteRecursoRepository { public FonteRecursoRepository(DapperContext c) : base(c, "sigov.fonte_recurso", "id,codigo,nome,descricao,ativo") { } public override async Task<long> CriarAsync(long t, long e, long x, FonteRecursoCreateRequest r, long? u, CancellationToken ct) { const string sql="insert into sigov.fonte_recurso (tenant_id,entidade_id,exercicio_id,codigo,nome,descricao,created_by) values (@t,@e,@x,@Codigo,@Nome,@Descricao,@u) returning id;"; using var cn=Context.CreateConnection(); return await cn.ExecuteScalarAsync<long>(Command(sql,new{t,e,x,r.Codigo,r.Nome,r.Descricao,u},ct)).ConfigureAwait(false);} public override async Task AtualizarAsync(long t,long e,long x,long id,FonteRecursoUpdateRequest r,long? u,CancellationToken ct){const string sql="update sigov.fonte_recurso set codigo=@Codigo,nome=@Nome,descricao=@Descricao,ativo=@Ativo,updated_at=now(),updated_by=@u where tenant_id=@t and entidade_id=@e and exercicio_id=@x and id=@id and is_deleted=false;"; using var cn=Context.CreateConnection(); await cn.ExecuteAsync(Command(sql,new{t,e,x,id,r.Codigo,r.Nome,r.Descricao,r.Ativo,u},ct)).ConfigureAwait(false);} }
public sealed class ProgramaRepository : CrudFinanceiroRepository<ProgramaCreateRequest, ProgramaUpdateRequest, ProgramaFiltro, ProgramaResponse>, IProgramaRepository { public ProgramaRepository(DapperContext c) : base(c, "sigov.programa", "id,codigo,nome,objetivo,ativo") { } public override async Task<long> CriarAsync(long t,long e,long x,ProgramaCreateRequest r,long? u,CancellationToken ct){const string sql="insert into sigov.programa (tenant_id,entidade_id,exercicio_id,codigo,nome,objetivo,created_by) values (@t,@e,@x,@Codigo,@Nome,@Objetivo,@u) returning id;"; using var cn=Context.CreateConnection(); return await cn.ExecuteScalarAsync<long>(Command(sql,new{t,e,x,r.Codigo,r.Nome,r.Objetivo,u},ct)).ConfigureAwait(false);} public override async Task AtualizarAsync(long t,long e,long x,long id,ProgramaUpdateRequest r,long? u,CancellationToken ct){const string sql="update sigov.programa set codigo=@Codigo,nome=@Nome,objetivo=@Objetivo,ativo=@Ativo,updated_at=now(),updated_by=@u where tenant_id=@t and entidade_id=@e and exercicio_id=@x and id=@id and is_deleted=false;"; using var cn=Context.CreateConnection(); await cn.ExecuteAsync(Command(sql,new{t,e,x,id,r.Codigo,r.Nome,r.Objetivo,r.Ativo,u},ct)).ConfigureAwait(false);} }
public sealed class AcaoRepository : CrudFinanceiroRepository<AcaoCreateRequest, AcaoUpdateRequest, AcaoFiltro, AcaoResponse>, IAcaoRepository { public AcaoRepository(DapperContext c) : base(c, "sigov.acao", "id,programa_id as ProgramaId,codigo,nome,tipo_acao as TipoAcao,ativo") { } public override async Task<long> CriarAsync(long t,long e,long x,AcaoCreateRequest r,long? u,CancellationToken ct){const string sql="insert into sigov.acao (tenant_id,entidade_id,exercicio_id,programa_id,codigo,nome,tipo_acao,created_by) values (@t,@e,@x,@ProgramaId,@Codigo,@Nome,@TipoAcao,@u) returning id;"; using var cn=Context.CreateConnection(); return await cn.ExecuteScalarAsync<long>(Command(sql,new{t,e,x,r.ProgramaId,r.Codigo,r.Nome,r.TipoAcao,u},ct)).ConfigureAwait(false);} public override async Task AtualizarAsync(long t,long e,long x,long id,AcaoUpdateRequest r,long? u,CancellationToken ct){const string sql="update sigov.acao set programa_id=@ProgramaId,codigo=@Codigo,nome=@Nome,tipo_acao=@TipoAcao,ativo=@Ativo,updated_at=now(),updated_by=@u where tenant_id=@t and entidade_id=@e and exercicio_id=@x and id=@id and is_deleted=false;"; using var cn=Context.CreateConnection(); await cn.ExecuteAsync(Command(sql,new{t,e,x,id,r.ProgramaId,r.Codigo,r.Nome,r.TipoAcao,r.Ativo,u},ct)).ConfigureAwait(false);} }
public sealed class NaturezaReceitaRepository : CrudFinanceiroRepository<NaturezaReceitaCreateRequest, NaturezaReceitaUpdateRequest, NaturezaReceitaFiltro, NaturezaReceitaResponse>, INaturezaReceitaRepository { public NaturezaReceitaRepository(DapperContext c) : base(c, "sigov.natureza_receita", "id,codigo,nome,categoria,origem,especie,ativo") { } public override async Task<long> CriarAsync(long t,long e,long x,NaturezaReceitaCreateRequest r,long? u,CancellationToken ct){const string sql="insert into sigov.natureza_receita (tenant_id,entidade_id,exercicio_id,codigo,nome,categoria,origem,especie,created_by) values (@t,@e,@x,@Codigo,@Nome,@Categoria,@Origem,@Especie,@u) returning id;"; using var cn=Context.CreateConnection(); return await cn.ExecuteScalarAsync<long>(Command(sql,new{t,e,x,r.Codigo,r.Nome,r.Categoria,r.Origem,r.Especie,u},ct)).ConfigureAwait(false);} public override async Task AtualizarAsync(long t,long e,long x,long id,NaturezaReceitaUpdateRequest r,long? u,CancellationToken ct){const string sql="update sigov.natureza_receita set codigo=@Codigo,nome=@Nome,categoria=@Categoria,origem=@Origem,especie=@Especie,ativo=@Ativo,updated_at=now(),updated_by=@u where tenant_id=@t and entidade_id=@e and exercicio_id=@x and id=@id and is_deleted=false;"; using var cn=Context.CreateConnection(); await cn.ExecuteAsync(Command(sql,new{t,e,x,id,r.Codigo,r.Nome,r.Categoria,r.Origem,r.Especie,r.Ativo,u},ct)).ConfigureAwait(false);} }
public sealed class NaturezaDespesaRepository : CrudFinanceiroRepository<NaturezaDespesaCreateRequest, NaturezaDespesaUpdateRequest, NaturezaDespesaFiltro, NaturezaDespesaResponse>, INaturezaDespesaRepository { public NaturezaDespesaRepository(DapperContext c) : base(c, "sigov.natureza_despesa", "id,codigo,nome,categoria,grupo,modalidade,elemento,ativo") { } public override async Task<long> CriarAsync(long t,long e,long x,NaturezaDespesaCreateRequest r,long? u,CancellationToken ct){const string sql="insert into sigov.natureza_despesa (tenant_id,entidade_id,exercicio_id,codigo,nome,categoria,grupo,modalidade,elemento,created_by) values (@t,@e,@x,@Codigo,@Nome,@Categoria,@Grupo,@Modalidade,@Elemento,@u) returning id;"; using var cn=Context.CreateConnection(); return await cn.ExecuteScalarAsync<long>(Command(sql,new{t,e,x,r.Codigo,r.Nome,r.Categoria,r.Grupo,r.Modalidade,r.Elemento,u},ct)).ConfigureAwait(false);} public override async Task AtualizarAsync(long t,long e,long x,long id,NaturezaDespesaUpdateRequest r,long? u,CancellationToken ct){const string sql="update sigov.natureza_despesa set codigo=@Codigo,nome=@Nome,categoria=@Categoria,grupo=@Grupo,modalidade=@Modalidade,elemento=@Elemento,ativo=@Ativo,updated_at=now(),updated_by=@u where tenant_id=@t and entidade_id=@e and exercicio_id=@x and id=@id and is_deleted=false;"; using var cn=Context.CreateConnection(); await cn.ExecuteAsync(Command(sql,new{t,e,x,id,r.Codigo,r.Nome,r.Categoria,r.Grupo,r.Modalidade,r.Elemento,r.Ativo,u},ct)).ConfigureAwait(false);} }

public sealed class FinanceiroSequencialRepository : BaseRepository, IFinanceiroSequencialService
{
    private readonly DapperContext _context; public FinanceiroSequencialRepository(DapperContext context) => _context = context;
    public async Task<string> ProximoAsync(long tenantId, long entidadeId, long exercicioId, int ano, string escopo, string prefixo, CancellationToken ct)
    { const string sql = "insert into sigov.financeiro_sequencial (tenant_id,entidade_id,exercicio_id,ano,escopo,ultimo_numero) values (@TenantId,@EntidadeId,@ExercicioId,@Ano,@Escopo,1) on conflict (tenant_id,entidade_id,exercicio_id,ano,escopo) do update set ultimo_numero=sigov.financeiro_sequencial.ultimo_numero+1, updated_at=now() returning ultimo_numero;"; using var cn = _context.CreateConnection(); var n = await cn.ExecuteScalarAsync<int>(Command(sql, new { TenantId = tenantId, EntidadeId = entidadeId, ExercicioId = exercicioId, Ano = ano, Escopo = escopo }, ct)).ConfigureAwait(false); return $"{prefixo}-{ano}-{n:000000}"; }
}

public sealed class OrcamentoRepository : BaseRepository, IOrcamentoRepository
{
    private readonly DapperContext _context; public OrcamentoRepository(DapperContext c) => _context = c;
    public async Task<PagedResult<OrcamentoDespesaResponse>> ListarDespesasAsync(long t,long e,long x,OrcamentoDespesaFiltro f,CancellationToken ct){var page=Math.Max(1,f.Page);var size=Math.Clamp(f.PageSize,1,100);const string select="id,orgao_unidade_orcamentaria_id as OrgaoUnidadeOrcamentariaId,programa_id as ProgramaId,acao_id as AcaoId,natureza_despesa_id as NaturezaDespesaId,fonte_recurso_id as FonteRecursoId,dotacao_inicial as DotacaoInicial,suplementacoes,reducoes,reservado,empenhado,liquidado,pago,(dotacao_inicial+suplementacoes-reducoes-reservado-empenhado) as SaldoDisponivel,ativo";var sql=$"select {select} from sigov.orcamento_despesa where tenant_id=@t and entidade_id=@e and exercicio_id=@x and is_deleted=false order by id desc limit @size offset @offset; select count(1) from sigov.orcamento_despesa where tenant_id=@t and entidade_id=@e and exercicio_id=@x and is_deleted=false;"; using var cn=_context.CreateConnection(); using var g=await cn.QueryMultipleAsync(Command(sql,new{t,e,x,size,offset=(page-1)*size},ct)).ConfigureAwait(false); return new PagedResult<OrcamentoDespesaResponse>((await g.ReadAsync<OrcamentoDespesaResponse>().ConfigureAwait(false)).AsList(),page,size,await g.ReadSingleAsync<long>().ConfigureAwait(false));}
    public async Task<OrcamentoDespesaResponse?> ObterDespesaAsync(long t,long e,long x,long id,CancellationToken ct){const string sql="select id,orgao_unidade_orcamentaria_id as OrgaoUnidadeOrcamentariaId,programa_id as ProgramaId,acao_id as AcaoId,natureza_despesa_id as NaturezaDespesaId,fonte_recurso_id as FonteRecursoId,dotacao_inicial as DotacaoInicial,suplementacoes,reducoes,reservado,empenhado,liquidado,pago,(dotacao_inicial+suplementacoes-reducoes-reservado-empenhado) as SaldoDisponivel,ativo from sigov.orcamento_despesa where tenant_id=@t and entidade_id=@e and exercicio_id=@x and id=@id and is_deleted=false;"; using var cn=_context.CreateConnection(); return await cn.QuerySingleOrDefaultAsync<OrcamentoDespesaResponse>(Command(sql,new{t,e,x,id},ct)).ConfigureAwait(false);}
    public async Task<long> CriarDespesaAsync(long t,long e,long x,OrcamentoDespesaCreateRequest r,long? u,CancellationToken ct){const string sql="insert into sigov.orcamento_despesa (tenant_id,entidade_id,exercicio_id,orgao_unidade_orcamentaria_id,programa_id,acao_id,natureza_despesa_id,fonte_recurso_id,dotacao_inicial,created_by) values (@t,@e,@x,@OrgaoUnidadeOrcamentariaId,@ProgramaId,@AcaoId,@NaturezaDespesaId,@FonteRecursoId,@DotacaoInicial,@u) returning id;"; using var cn=_context.CreateConnection(); return await cn.ExecuteScalarAsync<long>(Command(sql,new{t,e,x,r.OrgaoUnidadeOrcamentariaId,r.ProgramaId,r.AcaoId,r.NaturezaDespesaId,r.FonteRecursoId,r.DotacaoInicial,u},ct)).ConfigureAwait(false);}
    public async Task AtualizarDespesaAsync(long t,long e,long x,long id,OrcamentoDespesaUpdateRequest r,long? u,CancellationToken ct){const string sql="update sigov.orcamento_despesa set orgao_unidade_orcamentaria_id=@OrgaoUnidadeOrcamentariaId,programa_id=@ProgramaId,acao_id=@AcaoId,natureza_despesa_id=@NaturezaDespesaId,fonte_recurso_id=@FonteRecursoId,dotacao_inicial=@DotacaoInicial,ativo=@Ativo,updated_at=now(),updated_by=@u where tenant_id=@t and entidade_id=@e and exercicio_id=@x and id=@id and is_deleted=false;"; using var cn=_context.CreateConnection(); await cn.ExecuteAsync(Command(sql,new{t,e,x,id,r.OrgaoUnidadeOrcamentariaId,r.ProgramaId,r.AcaoId,r.NaturezaDespesaId,r.FonteRecursoId,r.DotacaoInicial,r.Ativo,u},ct)).ConfigureAwait(false);}
    public async Task MovimentarDespesaAsync(long t,long e,long x,long id,MovimentacaoOrcamentariaRequest r,long? u,CancellationToken ct){var col=r.TipoMovimentacao.Equals("REDUCAO",StringComparison.OrdinalIgnoreCase)?"reducoes":"suplementacoes";var sql=$"update sigov.orcamento_despesa set {col}={col}+@Valor,updated_at=now(),updated_by=@u where tenant_id=@t and entidade_id=@e and exercicio_id=@x and id=@id and is_deleted=false; insert into sigov.orcamento_movimentacao (tenant_id,entidade_id,exercicio_id,orcamento_despesa_id,tipo_movimentacao,valor,historico,created_by) values (@t,@e,@x,@id,@TipoMovimentacao,@Valor,@Historico,@u);"; using var cn=_context.CreateConnection(); await cn.ExecuteAsync(Command(sql,new{t,e,x,id,r.TipoMovimentacao,r.Valor,r.Historico,u},ct)).ConfigureAwait(false);}
    public async Task<PagedResult<OrcamentoReceitaResponse>> ListarReceitasAsync(long t,long e,long x,OrcamentoReceitaFiltro f,CancellationToken ct){var page=Math.Max(1,f.Page);var size=Math.Clamp(f.PageSize,1,100);const string sql="select id,natureza_receita_id as NaturezaReceitaId,fonte_recurso_id as FonteRecursoId,previsao_inicial as PrevisaoInicial,previsao_atualizada as PrevisaoAtualizada,lancado,arrecadado,ativo from sigov.orcamento_receita where tenant_id=@t and entidade_id=@e and exercicio_id=@x and is_deleted=false order by id desc limit @size offset @offset; select count(1) from sigov.orcamento_receita where tenant_id=@t and entidade_id=@e and exercicio_id=@x and is_deleted=false;"; using var cn=_context.CreateConnection(); using var g=await cn.QueryMultipleAsync(Command(sql,new{t,e,x,size,offset=(page-1)*size},ct)).ConfigureAwait(false); return new PagedResult<OrcamentoReceitaResponse>((await g.ReadAsync<OrcamentoReceitaResponse>().ConfigureAwait(false)).AsList(),page,size,await g.ReadSingleAsync<long>().ConfigureAwait(false));}
    public async Task<OrcamentoReceitaResponse?> ObterReceitaAsync(long t,long e,long x,long id,CancellationToken ct){const string sql="select id,natureza_receita_id as NaturezaReceitaId,fonte_recurso_id as FonteRecursoId,previsao_inicial as PrevisaoInicial,previsao_atualizada as PrevisaoAtualizada,lancado,arrecadado,ativo from sigov.orcamento_receita where tenant_id=@t and entidade_id=@e and exercicio_id=@x and id=@id and is_deleted=false;"; using var cn=_context.CreateConnection(); return await cn.QuerySingleOrDefaultAsync<OrcamentoReceitaResponse>(Command(sql,new{t,e,x,id},ct)).ConfigureAwait(false);}
    public async Task<long> CriarReceitaAsync(long t,long e,long x,OrcamentoReceitaCreateRequest r,long? u,CancellationToken ct){const string sql="insert into sigov.orcamento_receita (tenant_id,entidade_id,exercicio_id,natureza_receita_id,fonte_recurso_id,previsao_inicial,previsao_atualizada,created_by) values (@t,@e,@x,@NaturezaReceitaId,@FonteRecursoId,@PrevisaoInicial,@PrevisaoInicial,@u) returning id;"; using var cn=_context.CreateConnection(); return await cn.ExecuteScalarAsync<long>(Command(sql,new{t,e,x,r.NaturezaReceitaId,r.FonteRecursoId,r.PrevisaoInicial,u},ct)).ConfigureAwait(false);}
    public async Task AtualizarReceitaAsync(long t,long e,long x,long id,OrcamentoReceitaUpdateRequest r,long? u,CancellationToken ct){const string sql="update sigov.orcamento_receita set natureza_receita_id=@NaturezaReceitaId,fonte_recurso_id=@FonteRecursoId,previsao_inicial=@PrevisaoInicial,previsao_atualizada=@PrevisaoAtualizada,ativo=@Ativo,updated_at=now(),updated_by=@u where tenant_id=@t and entidade_id=@e and exercicio_id=@x and id=@id and is_deleted=false;"; using var cn=_context.CreateConnection(); await cn.ExecuteAsync(Command(sql,new{t,e,x,id,r.NaturezaReceitaId,r.FonteRecursoId,r.PrevisaoInicial,r.PrevisaoAtualizada,r.Ativo,u},ct)).ConfigureAwait(false);}
}

public sealed class EmpenhoRepository : BaseRepository, IEmpenhoRepository
{
    private readonly DapperContext _context; public EmpenhoRepository(DapperContext c) => _context = c;
    public async Task<PagedResult<EmpenhoResumoResponse>> ListarAsync(long t,long e,long x,EmpenhoFiltro f,CancellationToken ct){var page=Math.Max(1,f.Page);var size=Math.Clamp(f.PageSize,1,100);const string sql="select emp.id, emp.numero, emp.data_empenho as DataEmpenho, coalesce(p.nome,'Fornecedor protegido') as Fornecedor, coalesce(nd.nome,'') as Natureza, coalesce(fr.nome,'') as Fonte, emp.valor_total as ValorTotal, emp.valor_liquidado as ValorLiquidado, emp.valor_pago as ValorPago, (emp.valor_total-emp.valor_anulado-emp.valor_pago) as Saldo, emp.status from sigov.empenho emp join sigov.orcamento_despesa od on od.id=emp.orcamento_despesa_id and od.tenant_id=@t left join sigov.pessoa p on p.id=emp.fornecedor_pessoa_id left join sigov.natureza_despesa nd on nd.id=od.natureza_despesa_id left join sigov.fonte_recurso fr on fr.id=od.fonte_recurso_id where emp.tenant_id=@t and emp.entidade_id=@e and emp.exercicio_id=@x and emp.is_deleted=false order by emp.id desc limit @size offset @offset; select count(1) from sigov.empenho emp where emp.tenant_id=@t and emp.entidade_id=@e and emp.exercicio_id=@x and emp.is_deleted=false;"; using var cn=_context.CreateConnection(); using var g=await cn.QueryMultipleAsync(Command(sql,new{t,e,x,size,offset=(page-1)*size},ct)).ConfigureAwait(false); return new PagedResult<EmpenhoResumoResponse>((await g.ReadAsync<EmpenhoResumoResponse>().ConfigureAwait(false)).AsList(),page,size,await g.ReadSingleAsync<long>().ConfigureAwait(false));}
    public async Task<EmpenhoDetalheResponse?> ObterAsync(long t,long e,long x,long id,CancellationToken ct){const string sql="select emp.id, emp.numero, emp.data_empenho as DataEmpenho, emp.orcamento_despesa_id as OrcamentoDespesaId, emp.fornecedor_pessoa_id as FornecedorPessoaId, coalesce(p.nome,'Fornecedor protegido') as Fornecedor, emp.historico, emp.tipo_empenho as TipoEmpenho, emp.valor_total as ValorTotal, emp.valor_anulado as ValorAnulado, emp.valor_liquidado as ValorLiquidado, emp.valor_pago as ValorPago, emp.status from sigov.empenho emp left join sigov.pessoa p on p.id=emp.fornecedor_pessoa_id where emp.tenant_id=@t and emp.entidade_id=@e and emp.exercicio_id=@x and emp.id=@id and emp.is_deleted=false; select id,descricao,quantidade,valor_unitario as ValorUnitario,valor_total as ValorTotal from sigov.empenho_item where tenant_id=@t and entidade_id=@e and exercicio_id=@x and empenho_id=@id and is_deleted=false order by id;"; using var cn=_context.CreateConnection(); using var g=await cn.QueryMultipleAsync(Command(sql,new{t,e,x,id},ct)).ConfigureAwait(false); var emp=await g.ReadSingleOrDefaultAsync<EmpenhoDetalheRow>().ConfigureAwait(false); if(emp is null)return null; var itens=(await g.ReadAsync<EmpenhoItemResponse>().ConfigureAwait(false)).AsList(); return new EmpenhoDetalheResponse(emp.Id,emp.Numero,emp.DataEmpenho,emp.OrcamentoDespesaId,emp.FornecedorPessoaId,emp.Fornecedor,emp.Historico,emp.TipoEmpenho,emp.ValorTotal,emp.ValorAnulado,emp.ValorLiquidado,emp.ValorPago,emp.Status,itens);}
    public async Task<long> CriarAsync(long t,long e,long x,string numero,int ano,EmpenhoCreateRequest r,long? u,CancellationToken ct){var valor=r.Itens.Sum(i=>decimal.Round(i.Quantidade*i.ValorUnitario,2)); const string sql="with saldo as (update sigov.orcamento_despesa set empenhado=empenhado+@valor,updated_at=now(),updated_by=@u where tenant_id=@t and entidade_id=@e and exercicio_id=@x and id=@OrcamentoDespesaId and is_deleted=false and (dotacao_inicial+suplementacoes-reducoes-reservado-empenhado)>=@valor returning id) insert into sigov.empenho (tenant_id,entidade_id,exercicio_id,orcamento_despesa_id,numero,ano,data_empenho,fornecedor_pessoa_id,historico,tipo_empenho,valor_total,status,metadados,created_by) select @t,@e,@x,@OrcamentoDespesaId,@numero,@ano,@DataEmpenho,@FornecedorPessoaId,@Historico,@TipoEmpenho,@valor,'EMITIDO',jsonb_build_object('observacoes',@Observacoes),@u from saldo returning id;"; using var cn=_context.CreateConnection(); var id=await cn.ExecuteScalarAsync<long>(Command(sql,new{t,e,x,numero,ano,r.OrcamentoDespesaId,r.DataEmpenho,r.FornecedorPessoaId,r.Historico,r.TipoEmpenho,Observacoes=r.Observacoes,valor,u},ct)).ConfigureAwait(false); foreach(var item in r.Itens){const string itemSql="insert into sigov.empenho_item (tenant_id,entidade_id,exercicio_id,empenho_id,descricao,quantidade,valor_unitario,valor_total,created_by) values (@t,@e,@x,@id,@Descricao,@Quantidade,@ValorUnitario,@ValorTotal,@u);"; await cn.ExecuteAsync(Command(itemSql,new{t,e,x,id,item.Descricao,item.Quantidade,item.ValorUnitario,ValorTotal=decimal.Round(item.Quantidade*item.ValorUnitario,2),u},ct)).ConfigureAwait(false);} await RegistrarEvento(cn,t,e,x,"EmpenhoEmitido",new{id,numero,valor},u,ct).ConfigureAwait(false); return id;}
    public async Task AtualizarAsync(long t,long e,long x,long id,EmpenhoUpdateRequest r,long? u,CancellationToken ct){const string sql="update sigov.empenho set data_empenho=@DataEmpenho,historico=@Historico,tipo_empenho=@TipoEmpenho,metadados=jsonb_build_object('observacoes',@Observacoes),updated_at=now(),updated_by=@u where tenant_id=@t and entidade_id=@e and exercicio_id=@x and id=@id and is_deleted=false and status <> 'ANULADO';"; using var cn=_context.CreateConnection(); await cn.ExecuteAsync(Command(sql,new{t,e,x,id,r.DataEmpenho,r.Historico,r.TipoEmpenho,r.Observacoes,u},ct)).ConfigureAwait(false);}
    public async Task AnularAsync(long t,long e,long x,long id,AnularEmpenhoRequest r,long? u,CancellationToken ct){const string sql="update sigov.empenho set valor_anulado=valor_anulado+@Valor,status='ANULADO',updated_at=now(),updated_by=@u where tenant_id=@t and entidade_id=@e and exercicio_id=@x and id=@id and is_deleted=false and status <> 'ANULADO' and @Valor <= (valor_total-valor_anulado-valor_liquidado); update sigov.orcamento_despesa od set empenhado=greatest(0,empenhado-@Valor),updated_at=now(),updated_by=@u from sigov.empenho emp where emp.orcamento_despesa_id=od.id and emp.id=@id and emp.tenant_id=@t and od.tenant_id=@t;"; using var cn=_context.CreateConnection(); await cn.ExecuteAsync(Command(sql,new{t,e,x,id,r.Valor,u},ct)).ConfigureAwait(false); await RegistrarEvento(cn,t,e,x,"EmpenhoAnulado",new{id,r.Valor,r.Motivo},u,ct).ConfigureAwait(false);}
    private static async Task RegistrarEvento(System.Data.IDbConnection cn,long t,long e,long x,string tipo,object payload,long? u,CancellationToken ct){const string sql="insert into sigov.fila_evento (tenant_id,entidade_id,exercicio_id,tipo_evento,payload,created_by) values (@t,@e,@x,@tipo,@payload::jsonb,@u);"; await cn.ExecuteAsync(Command(sql,new{t,e,x,tipo,payload=System.Text.Json.JsonSerializer.Serialize(payload),u},ct)).ConfigureAwait(false);}
    private sealed record EmpenhoDetalheRow(long Id,string Numero,DateOnly DataEmpenho,long OrcamentoDespesaId,long FornecedorPessoaId,string Fornecedor,string Historico,string TipoEmpenho,decimal ValorTotal,decimal ValorAnulado,decimal ValorLiquidado,decimal ValorPago,string Status);
}

public sealed class LiquidacaoRepository : BaseRepository, ILiquidacaoRepository
{
    private readonly DapperContext _context; public LiquidacaoRepository(DapperContext c)=>_context=c;
    public async Task<PagedResult<LiquidacaoResponse>> ListarAsync(long t,long e,long x,LiquidacaoFiltro f,CancellationToken ct){var page=Math.Max(1,f.Page);var size=Math.Clamp(f.PageSize,1,100);const string sql="select id,empenho_id as EmpenhoId,numero,data_liquidacao as DataLiquidacao,documento_fiscal as DocumentoFiscal,historico,valor,status from sigov.liquidacao where tenant_id=@t and entidade_id=@e and exercicio_id=@x and is_deleted=false order by id desc limit @size offset @offset; select count(1) from sigov.liquidacao where tenant_id=@t and entidade_id=@e and exercicio_id=@x and is_deleted=false;"; using var cn=_context.CreateConnection(); using var g=await cn.QueryMultipleAsync(Command(sql,new{t,e,x,size,offset=(page-1)*size},ct)).ConfigureAwait(false); return new PagedResult<LiquidacaoResponse>((await g.ReadAsync<LiquidacaoResponse>().ConfigureAwait(false)).AsList(),page,size,await g.ReadSingleAsync<long>().ConfigureAwait(false));}
    public async Task<LiquidacaoResponse?> ObterAsync(long t,long e,long x,long id,CancellationToken ct){const string sql="select id,empenho_id as EmpenhoId,numero,data_liquidacao as DataLiquidacao,documento_fiscal as DocumentoFiscal,historico,valor,status from sigov.liquidacao where tenant_id=@t and entidade_id=@e and exercicio_id=@x and id=@id and is_deleted=false;"; using var cn=_context.CreateConnection(); return await cn.QuerySingleOrDefaultAsync<LiquidacaoResponse>(Command(sql,new{t,e,x,id},ct)).ConfigureAwait(false);}
    public async Task<long> CriarAsync(long t,long e,long x,long empenhoId,string numero,LiquidacaoCreateRequest r,long? u,CancellationToken ct){const string sql="with saldo as (update sigov.empenho set valor_liquidado=valor_liquidado+@Valor,status=case when valor_total-valor_anulado-valor_liquidado-@Valor <= 0 then 'LIQUIDADO_TOTAL' else 'LIQUIDADO_PARCIAL' end,updated_at=now(),updated_by=@u where tenant_id=@t and entidade_id=@e and exercicio_id=@x and id=@empenhoId and status <> 'ANULADO' and @Valor <= (valor_total-valor_anulado-valor_liquidado) returning id) insert into sigov.liquidacao (tenant_id,entidade_id,exercicio_id,empenho_id,numero,data_liquidacao,documento_fiscal,historico,valor,status,created_by) select @t,@e,@x,@empenhoId,@numero,@DataLiquidacao,@DocumentoFiscal,@Historico,@Valor,'LIQUIDADA',@u from saldo returning id;"; using var cn=_context.CreateConnection(); var id=await cn.ExecuteScalarAsync<long>(Command(sql,new{t,e,x,empenhoId,numero,r.DataLiquidacao,r.DocumentoFiscal,r.Historico,r.Valor,u},ct)).ConfigureAwait(false); await cn.ExecuteAsync(Command("insert into sigov.fila_evento (entidade_id,exercicio_id,tipo_evento,payload,created_by) values (@e,@x,'EmpenhoLiquidado',jsonb_build_object('liquidacaoId',@id,'empenhoId',@empenhoId,'valor',@Valor),@u);",new{e,x,id,empenhoId,r.Valor,u},ct)).ConfigureAwait(false); return id;}
    public async Task AnularAsync(long t,long e,long x,long id,AnularLiquidacaoRequest r,long? u,CancellationToken ct){const string sql="update sigov.liquidacao set status='ANULADA',updated_at=now(),updated_by=@u where tenant_id=@t and entidade_id=@e and exercicio_id=@x and id=@id and status <> 'ANULADA';"; using var cn=_context.CreateConnection(); await cn.ExecuteAsync(Command(sql,new{t,e,x,id,u},ct)).ConfigureAwait(false); _=r;}
}
public sealed class PagamentoRepository : BaseRepository, IPagamentoRepository
{
    private readonly DapperContext _context; public PagamentoRepository(DapperContext c)=>_context=c;
    public async Task<PagedResult<PagamentoResponse>> ListarAsync(long t,long e,long x,PagamentoFiltro f,CancellationToken ct){var page=Math.Max(1,f.Page);var size=Math.Clamp(f.PageSize,1,100);const string sql="select id,liquidacao_id as LiquidacaoId,numero,data_pagamento as DataPagamento,forma_pagamento as FormaPagamento,conta_bancaria as ContaBancaria,historico,valor,status from sigov.pagamento where tenant_id=@t and entidade_id=@e and exercicio_id=@x and is_deleted=false order by id desc limit @size offset @offset; select count(1) from sigov.pagamento where tenant_id=@t and entidade_id=@e and exercicio_id=@x and is_deleted=false;"; using var cn=_context.CreateConnection(); using var g=await cn.QueryMultipleAsync(Command(sql,new{t,e,x,size,offset=(page-1)*size},ct)).ConfigureAwait(false); return new PagedResult<PagamentoResponse>((await g.ReadAsync<PagamentoResponse>().ConfigureAwait(false)).AsList(),page,size,await g.ReadSingleAsync<long>().ConfigureAwait(false));}
    public async Task<PagamentoResponse?> ObterAsync(long t,long e,long x,long id,CancellationToken ct){const string sql="select id,liquidacao_id as LiquidacaoId,numero,data_pagamento as DataPagamento,forma_pagamento as FormaPagamento,conta_bancaria as ContaBancaria,historico,valor,status from sigov.pagamento where tenant_id=@t and entidade_id=@e and exercicio_id=@x and id=@id and is_deleted=false;"; using var cn=_context.CreateConnection(); return await cn.QuerySingleOrDefaultAsync<PagamentoResponse>(Command(sql,new{t,e,x,id},ct)).ConfigureAwait(false);}
    public async Task<long> CriarAsync(long t,long e,long x,long liquidacaoId,string numero,PagamentoCreateRequest r,long? u,CancellationToken ct){const string sql="with liq as (select * from sigov.liquidacao where tenant_id=@t and entidade_id=@e and exercicio_id=@x and id=@liquidacaoId and status <> 'ANULADA' and @Valor <= valor), ins as (insert into sigov.pagamento (tenant_id,entidade_id,exercicio_id,liquidacao_id,numero,data_pagamento,forma_pagamento,conta_bancaria,historico,valor,status,created_by) select @t,@e,@x,@liquidacaoId,@numero,@DataPagamento,@FormaPagamento,@ContaBancaria,@Historico,@Valor,'EFETUADO',@u from liq returning id) update sigov.empenho emp set valor_pago=valor_pago+@Valor,status='PAGO_PARCIAL' from sigov.liquidacao liq where liq.empenho_id=emp.id and liq.id=@liquidacaoId and emp.tenant_id=@t returning (select id from ins);"; using var cn=_context.CreateConnection(); var id=await cn.ExecuteScalarAsync<long>(Command(sql,new{t,e,x,liquidacaoId,numero,r.DataPagamento,r.FormaPagamento,r.ContaBancaria,r.Historico,r.Valor,u},ct)).ConfigureAwait(false); await cn.ExecuteAsync(Command("insert into sigov.fila_evento (entidade_id,exercicio_id,tipo_evento,payload,created_by) values (@e,@x,'PagamentoRealizado',jsonb_build_object('pagamentoId',@id,'valor',@Valor),@u);",new{e,x,id,r.Valor,u},ct)).ConfigureAwait(false); return id;}
    public async Task CancelarAsync(long t,long e,long x,long id,CancelarPagamentoRequest r,long? u,CancellationToken ct){const string sql="update sigov.pagamento set status='CANCELADO',updated_at=now(),updated_by=@u where tenant_id=@t and entidade_id=@e and exercicio_id=@x and id=@id and status <> 'CANCELADO';"; using var cn=_context.CreateConnection(); await cn.ExecuteAsync(Command(sql,new{t,e,x,id,u},ct)).ConfigureAwait(false); _=r;}
}
public sealed class ReceitaRepository : BaseRepository, IReceitaRepository
{
    private readonly DapperContext _context; public ReceitaRepository(DapperContext c)=>_context=c;
    public async Task<PagedResult<ReceitaLancamentoResponse>> ListarLancamentosAsync(long t,long e,long x,ReceitaLancamentoFiltro f,CancellationToken ct){var page=Math.Max(1,f.Page);var size=Math.Clamp(f.PageSize,1,100);const string sql="select rl.id,rl.orcamento_receita_id as OrcamentoReceitaId,rl.numero,rl.data_lancamento as DataLancamento,rl.contribuinte_pessoa_id as ContribuintePessoaId,p.nome as Contribuinte,rl.historico,rl.valor,coalesce((select sum(ra.valor) from sigov.receita_arrecadacao ra where ra.receita_lancamento_id=rl.id and ra.status='ARRECADADA'),0) as Arrecadado,rl.status from sigov.receita_lancamento rl left join sigov.pessoa p on p.id=rl.contribuinte_pessoa_id where rl.tenant_id=@t and rl.entidade_id=@e and rl.exercicio_id=@x and rl.is_deleted=false order by rl.id desc limit @size offset @offset; select count(1) from sigov.receita_lancamento where tenant_id=@t and entidade_id=@e and exercicio_id=@x and is_deleted=false;"; using var cn=_context.CreateConnection(); using var g=await cn.QueryMultipleAsync(Command(sql,new{t,e,x,size,offset=(page-1)*size},ct)).ConfigureAwait(false); return new PagedResult<ReceitaLancamentoResponse>((await g.ReadAsync<ReceitaLancamentoResponse>().ConfigureAwait(false)).AsList(),page,size,await g.ReadSingleAsync<long>().ConfigureAwait(false));}
    public async Task<ReceitaLancamentoResponse?> ObterLancamentoAsync(long t,long e,long x,long id,CancellationToken ct){const string sql="select rl.id,rl.orcamento_receita_id as OrcamentoReceitaId,rl.numero,rl.data_lancamento as DataLancamento,rl.contribuinte_pessoa_id as ContribuintePessoaId,p.nome as Contribuinte,rl.historico,rl.valor,0::numeric as Arrecadado,rl.status from sigov.receita_lancamento rl left join sigov.pessoa p on p.id=rl.contribuinte_pessoa_id where rl.tenant_id=@t and rl.entidade_id=@e and rl.exercicio_id=@x and rl.id=@id and rl.is_deleted=false;"; using var cn=_context.CreateConnection(); return await cn.QuerySingleOrDefaultAsync<ReceitaLancamentoResponse>(Command(sql,new{t,e,x,id},ct)).ConfigureAwait(false);}
    public async Task<long> CriarLancamentoAsync(long t,long e,long x,string numero,ReceitaLancamentoCreateRequest r,long? u,CancellationToken ct){const string sql="insert into sigov.receita_lancamento (tenant_id,entidade_id,exercicio_id,orcamento_receita_id,numero,data_lancamento,contribuinte_pessoa_id,historico,valor,status,created_by) values (@t,@e,@x,@OrcamentoReceitaId,@numero,@DataLancamento,@ContribuintePessoaId,@Historico,@Valor,'LANCADA',@u) returning id; update sigov.orcamento_receita set lancado=lancado+@Valor,updated_at=now(),updated_by=@u where tenant_id=@t and entidade_id=@e and exercicio_id=@x and id=@OrcamentoReceitaId;"; using var cn=_context.CreateConnection(); var id=await cn.ExecuteScalarAsync<long>(Command(sql,new{t,e,x,numero,r.OrcamentoReceitaId,r.DataLancamento,r.ContribuintePessoaId,r.Historico,r.Valor,u},ct)).ConfigureAwait(false); return id;}
    public async Task<long> ArrecadarAsync(long t,long e,long x,long lancamentoId,string numero,ReceitaArrecadacaoCreateRequest r,long? u,CancellationToken ct){const string sql="insert into sigov.receita_arrecadacao (tenant_id,entidade_id,exercicio_id,receita_lancamento_id,numero,data_arrecadacao,forma_arrecadacao,valor,historico,status,created_by) select @t,@e,@x,@lancamentoId,@numero,@DataArrecadacao,@FormaArrecadacao,@Valor,@Historico,'ARRECADADA',@u from sigov.receita_lancamento where tenant_id=@t and entidade_id=@e and exercicio_id=@x and id=@lancamentoId and @Valor <= valor returning id;"; using var cn=_context.CreateConnection(); return await cn.ExecuteScalarAsync<long>(Command(sql,new{t,e,x,lancamentoId,numero,r.DataArrecadacao,r.FormaArrecadacao,r.Valor,r.Historico,u},ct)).ConfigureAwait(false);}
}
public sealed class FinanceiroDashboardRepository : BaseRepository, IFinanceiroDashboardRepository
{
    private readonly DapperContext _context; public FinanceiroDashboardRepository(DapperContext c)=>_context=c;
    public async Task<FinanceiroDashboardResponse> ObterAsync(long t,long e,long x,CancellationToken ct){const string sql="select coalesce(sum(dotacao_inicial+suplementacoes-reducoes),0) as OrcamentoAutorizado,coalesce(sum(empenhado),0) as Empenhado,coalesce(sum(liquidado),0) as Liquidado,coalesce(sum(pago),0) as Pago,coalesce(sum(dotacao_inicial+suplementacoes-reducoes-reservado-empenhado),0) as SaldoDisponivel from sigov.orcamento_despesa where tenant_id=@t and entidade_id=@e and exercicio_id=@x and is_deleted=false; select coalesce(sum(previsao_atualizada),0) as ReceitaPrevista,coalesce(sum(lancado),0) as ReceitaLancada,coalesce(sum(arrecadado),0) as ReceitaArrecadada from sigov.orcamento_receita where tenant_id=@t and entidade_id=@e and exercicio_id=@x and is_deleted=false;"; using var cn=_context.CreateConnection(); using var g=await cn.QueryMultipleAsync(Command(sql,new{t,e,x},ct)).ConfigureAwait(false); var d=await g.ReadSingleAsync<FinanceiroResumoDespesaResponse>().ConfigureAwait(false); var r=await g.ReadSingleAsync<FinanceiroResumoReceitaResponse>().ConfigureAwait(false); return new FinanceiroDashboardResponse(d,r,DateTimeOffset.UtcNow);}
}
public sealed class FinanceiroExportacaoRepository { }
