using System.Text;
using Microsoft.Extensions.Logging;
using Sigov.Application.Abstractions;
using Sigov.Application.Common;
using Sigov.Domain.Common;

namespace Sigov.Application.Financeiro;

public abstract class FinanceiroServiceBase
{
    protected FinanceiroServiceBase(ICurrentTenant tenant, ICurrentUser user, IPermissionService permissions, IAuditService audit) { Tenant = tenant; User = user; Permissions = permissions; Audit = audit; }
    protected ICurrentTenant Tenant { get; }
    protected ICurrentUser User { get; }
    protected IPermissionService Permissions { get; }
    protected IAuditService Audit { get; }
    protected long TenantId => Tenant.TenantId ?? 0;
    protected long EntidadeId => Tenant.EntidadeId ?? 0;
    protected long ExercicioId => Tenant.ExercicioId ?? 0;
    protected long? UsuarioId => User.UsuarioId;
    protected bool EscopoValido => TenantId > 0 && EntidadeId > 0 && ExercicioId > 0;
    protected Result<T> EscopoFailure<T>() => Result<T>.Failure("Tenant, entidade e exercício são obrigatórios para operações financeiras.");
    protected Result EscopoFailure() => Result.Failure("Tenant, entidade e exercício são obrigatórios para operações financeiras.");
    protected async Task<bool> CanAsync(string chave, CancellationToken ct)
    {
        if (!User.UsuarioId.HasValue) return false;
        var partes = chave.Split('.');
        var recurso = partes.Length >= 3 ? $"{partes[0]}.{partes[1]}" : chave;
        var acao = partes.Length >= 3 ? partes[2] : "visualizar";
        return await Permissions.HasPermissionAsync(User.UsuarioId.Value, FinanceiroPermissoes.Modulo, recurso, acao, ct).ConfigureAwait(false);
    }
}

public abstract class CrudFinanceiroService<TCreate, TUpdate, TFiltro, TResponse> : FinanceiroServiceBase
{
    private readonly ICrudFinanceiroRepository<TCreate, TUpdate, TFiltro, TResponse> _repo;
    private readonly ILogger _logger;
    private readonly string _tabela;
    private readonly string _visualizar;
    private readonly string _criar;
    private readonly string _editar;
    private readonly string _excluir;
    protected CrudFinanceiroService(ICrudFinanceiroRepository<TCreate, TUpdate, TFiltro, TResponse> repo, ICurrentTenant tenant, ICurrentUser user, IPermissionService permissions, IAuditService audit, ILogger logger, string tabela, string visualizar, string criar, string editar, string excluir) : base(tenant, user, permissions, audit)
    { _repo = repo; _logger = logger; _tabela = tabela; _visualizar = visualizar; _criar = criar; _editar = editar; _excluir = excluir; }
    public async Task<Result<PagedResult<TResponse>>> ListarAsync(TFiltro filtro, CancellationToken ct) { if (!EscopoValido) return EscopoFailure<PagedResult<TResponse>>(); if (!await CanAsync(_visualizar, ct).ConfigureAwait(false)) return Result<PagedResult<TResponse>>.Failure("403"); try { return Result<PagedResult<TResponse>>.Success(await _repo.ListarAsync(TenantId, EntidadeId, ExercicioId, filtro, ct).ConfigureAwait(false)); } catch (Exception ex) { _logger.LogError(ex, "Erro ao listar {Tabela}.", _tabela); return Result<PagedResult<TResponse>>.Failure("Erro ao listar registros financeiros."); } }
    public async Task<Result<TResponse>> ObterAsync(long id, CancellationToken ct) { if (!EscopoValido) return EscopoFailure<TResponse>(); if (!await CanAsync(_visualizar, ct).ConfigureAwait(false)) return Result<TResponse>.Failure("403"); var item = await _repo.ObterAsync(TenantId, EntidadeId, ExercicioId, id, ct).ConfigureAwait(false); return item is null ? Result<TResponse>.Failure("Registro não encontrado.") : Result<TResponse>.Success(item); }
    public async Task<Result<long>> CriarAsync(TCreate request, CancellationToken ct) { if (!EscopoValido) return EscopoFailure<long>(); if (!await CanAsync(_criar, ct).ConfigureAwait(false)) return Result<long>.Failure("403"); try { var id = await _repo.CriarAsync(TenantId, EntidadeId, ExercicioId, request, UsuarioId, ct).ConfigureAwait(false); await Audit.RegistrarAsync("financeiro", "CRIAR", _tabela, id.ToString(System.Globalization.CultureInfo.InvariantCulture), null, request, ct).ConfigureAwait(false); return Result<long>.Success(id); } catch (Exception ex) { _logger.LogError(ex, "Erro ao criar {Tabela}.", _tabela); return Result<long>.Failure("Erro ao criar registro financeiro."); } }
    public async Task<Result> AtualizarAsync(long id, TUpdate request, CancellationToken ct) { if (!EscopoValido) return EscopoFailure(); if (!await CanAsync(_editar, ct).ConfigureAwait(false)) return Result.Failure("403"); try { var anterior = await _repo.ObterAsync(TenantId, EntidadeId, ExercicioId, id, ct).ConfigureAwait(false); await _repo.AtualizarAsync(TenantId, EntidadeId, ExercicioId, id, request, UsuarioId, ct).ConfigureAwait(false); await Audit.RegistrarAsync("financeiro", "EDITAR", _tabela, id.ToString(System.Globalization.CultureInfo.InvariantCulture), anterior, request, ct).ConfigureAwait(false); return Result.Success(); } catch (Exception ex) { _logger.LogError(ex, "Erro ao atualizar {Tabela}.", _tabela); return Result.Failure("Erro ao atualizar registro financeiro."); } }
    public async Task<Result> ExcluirAsync(long id, CancellationToken ct) { if (!EscopoValido) return EscopoFailure(); if (!await CanAsync(_excluir, ct).ConfigureAwait(false)) return Result.Failure("403"); await _repo.ExcluirAsync(TenantId, EntidadeId, ExercicioId, id, UsuarioId, ct).ConfigureAwait(false); await Audit.RegistrarAsync("financeiro", "EXCLUIR", _tabela, id.ToString(System.Globalization.CultureInfo.InvariantCulture), null, null, ct).ConfigureAwait(false); return Result.Success(); }
}

public sealed class PlanoContasService : CrudFinanceiroService<PlanoContasCreateRequest, PlanoContasUpdateRequest, PlanoContasFiltro, PlanoContasResponse>, IPlanoContasService { public PlanoContasService(IPlanoContasRepository r, ICurrentTenant t, ICurrentUser u, IPermissionService p, IAuditService a, ILogger<PlanoContasService> l) : base(r, t, u, p, a, l, "sigov.plano_contas", FinanceiroPermissoes.PlanoContasVisualizar, FinanceiroPermissoes.PlanoContasCriar, FinanceiroPermissoes.PlanoContasEditar, FinanceiroPermissoes.PlanoContasExcluir) { } }
public sealed class FonteRecursoService : CrudFinanceiroService<FonteRecursoCreateRequest, FonteRecursoUpdateRequest, FonteRecursoFiltro, FonteRecursoResponse>, IFonteRecursoService { public FonteRecursoService(IFonteRecursoRepository r, ICurrentTenant t, ICurrentUser u, IPermissionService p, IAuditService a, ILogger<FonteRecursoService> l) : base(r, t, u, p, a, l, "sigov.fonte_recurso", FinanceiroPermissoes.OrcamentoVisualizar, FinanceiroPermissoes.OrcamentoCriar, FinanceiroPermissoes.OrcamentoEditar, FinanceiroPermissoes.OrcamentoEditar) { } }
public sealed class ProgramaService : CrudFinanceiroService<ProgramaCreateRequest, ProgramaUpdateRequest, ProgramaFiltro, ProgramaResponse>, IProgramaService { public ProgramaService(IProgramaRepository r, ICurrentTenant t, ICurrentUser u, IPermissionService p, IAuditService a, ILogger<ProgramaService> l) : base(r, t, u, p, a, l, "sigov.programa", FinanceiroPermissoes.OrcamentoVisualizar, FinanceiroPermissoes.OrcamentoCriar, FinanceiroPermissoes.OrcamentoEditar, FinanceiroPermissoes.OrcamentoEditar) { } }
public sealed class AcaoService : CrudFinanceiroService<AcaoCreateRequest, AcaoUpdateRequest, AcaoFiltro, AcaoResponse>, IAcaoService { public AcaoService(IAcaoRepository r, ICurrentTenant t, ICurrentUser u, IPermissionService p, IAuditService a, ILogger<AcaoService> l) : base(r, t, u, p, a, l, "sigov.acao", FinanceiroPermissoes.OrcamentoVisualizar, FinanceiroPermissoes.OrcamentoCriar, FinanceiroPermissoes.OrcamentoEditar, FinanceiroPermissoes.OrcamentoEditar) { } }
public sealed class NaturezaReceitaService : CrudFinanceiroService<NaturezaReceitaCreateRequest, NaturezaReceitaUpdateRequest, NaturezaReceitaFiltro, NaturezaReceitaResponse>, INaturezaReceitaService { public NaturezaReceitaService(INaturezaReceitaRepository r, ICurrentTenant t, ICurrentUser u, IPermissionService p, IAuditService a, ILogger<NaturezaReceitaService> l) : base(r, t, u, p, a, l, "sigov.natureza_receita", FinanceiroPermissoes.ReceitaVisualizar, FinanceiroPermissoes.ReceitaCriar, FinanceiroPermissoes.OrcamentoEditar, FinanceiroPermissoes.OrcamentoEditar) { } }
public sealed class NaturezaDespesaService : CrudFinanceiroService<NaturezaDespesaCreateRequest, NaturezaDespesaUpdateRequest, NaturezaDespesaFiltro, NaturezaDespesaResponse>, INaturezaDespesaService { public NaturezaDespesaService(INaturezaDespesaRepository r, ICurrentTenant t, ICurrentUser u, IPermissionService p, IAuditService a, ILogger<NaturezaDespesaService> l) : base(r, t, u, p, a, l, "sigov.natureza_despesa", FinanceiroPermissoes.OrcamentoVisualizar, FinanceiroPermissoes.OrcamentoCriar, FinanceiroPermissoes.OrcamentoEditar, FinanceiroPermissoes.OrcamentoEditar) { } }

public sealed class OrcamentoService : FinanceiroServiceBase, IOrcamentoService
{
    private readonly IOrcamentoRepository _repo; private readonly ILogger<OrcamentoService> _logger;
    public OrcamentoService(IOrcamentoRepository repo, ICurrentTenant tenant, ICurrentUser user, IPermissionService permissions, IAuditService audit, ILogger<OrcamentoService> logger) : base(tenant, user, permissions, audit) { _repo = repo; _logger = logger; }
    public async Task<Result<PagedResult<OrcamentoDespesaResponse>>> ListarDespesasAsync(OrcamentoDespesaFiltro f, CancellationToken ct) { if (!EscopoValido) return EscopoFailure<PagedResult<OrcamentoDespesaResponse>>(); if (!await CanAsync(FinanceiroPermissoes.OrcamentoVisualizar, ct).ConfigureAwait(false)) return Result<PagedResult<OrcamentoDespesaResponse>>.Failure("403"); return Result<PagedResult<OrcamentoDespesaResponse>>.Success(await _repo.ListarDespesasAsync(TenantId, EntidadeId, ExercicioId, f, ct).ConfigureAwait(false)); }
    public async Task<Result<OrcamentoDespesaResponse>> ObterDespesaAsync(long id, CancellationToken ct) { if (!EscopoValido) return EscopoFailure<OrcamentoDespesaResponse>(); if (!await CanAsync(FinanceiroPermissoes.OrcamentoVisualizar, ct).ConfigureAwait(false)) return Result<OrcamentoDespesaResponse>.Failure("403"); var item = await _repo.ObterDespesaAsync(TenantId, EntidadeId, ExercicioId, id, ct).ConfigureAwait(false); return item is null ? Result<OrcamentoDespesaResponse>.Failure("Orçamento não encontrado.") : Result<OrcamentoDespesaResponse>.Success(item); }
    public async Task<Result<long>> CriarDespesaAsync(OrcamentoDespesaCreateRequest r, CancellationToken ct) { if (!EscopoValido) return EscopoFailure<long>(); if (!await CanAsync(FinanceiroPermissoes.OrcamentoCriar, ct).ConfigureAwait(false)) return Result<long>.Failure("403"); if (r.DotacaoInicial < 0m) return Result<long>.Failure("Dotação inicial não pode ser negativa."); try { var id = await _repo.CriarDespesaAsync(TenantId, EntidadeId, ExercicioId, r, UsuarioId, ct).ConfigureAwait(false); await Audit.RegistrarAsync("financeiro", "CRIAR_ORCAMENTO_DESPESA", "sigov.orcamento_despesa", id.ToString(System.Globalization.CultureInfo.InvariantCulture), null, r, ct).ConfigureAwait(false); return Result<long>.Success(id); } catch (Exception ex) { _logger.LogError(ex, "Erro ao criar orçamento da despesa."); return Result<long>.Failure("Erro ao criar orçamento da despesa."); } }
    public async Task<Result> AtualizarDespesaAsync(long id, OrcamentoDespesaUpdateRequest r, CancellationToken ct) { if (!EscopoValido) return EscopoFailure(); if (!await CanAsync(FinanceiroPermissoes.OrcamentoEditar, ct).ConfigureAwait(false)) return Result.Failure("403"); await _repo.AtualizarDespesaAsync(TenantId, EntidadeId, ExercicioId, id, r, UsuarioId, ct).ConfigureAwait(false); return Result.Success(); }
    public async Task<Result> MovimentarDespesaAsync(long id, MovimentacaoOrcamentariaRequest r, CancellationToken ct) { if (!EscopoValido) return EscopoFailure(); if (!await CanAsync(FinanceiroPermissoes.OrcamentoMovimentar, ct).ConfigureAwait(false)) return Result.Failure("403"); try { await _repo.MovimentarDespesaAsync(TenantId, EntidadeId, ExercicioId, id, r, UsuarioId, ct).ConfigureAwait(false); await Audit.RegistrarAsync("financeiro", "ORCAMENTO_MOVIMENTADO", "sigov.orcamento_movimentacao", id.ToString(System.Globalization.CultureInfo.InvariantCulture), null, r, ct).ConfigureAwait(false); return Result.Success(); } catch (Exception ex) { _logger.LogError(ex, "Erro ao movimentar orçamento."); return Result.Failure(ex.Message.StartsWith("409:") || ex.Message.StartsWith("Não") ? ex.Message : "Erro ao movimentar orçamento."); } }
    public async Task<Result<PagedResult<OrcamentoReceitaResponse>>> ListarReceitasAsync(OrcamentoReceitaFiltro f, CancellationToken ct) { if (!EscopoValido) return EscopoFailure<PagedResult<OrcamentoReceitaResponse>>(); if (!await CanAsync(FinanceiroPermissoes.OrcamentoVisualizar, ct).ConfigureAwait(false)) return Result<PagedResult<OrcamentoReceitaResponse>>.Failure("403"); return Result<PagedResult<OrcamentoReceitaResponse>>.Success(await _repo.ListarReceitasAsync(TenantId, EntidadeId, ExercicioId, f, ct).ConfigureAwait(false)); }
    public async Task<Result<OrcamentoReceitaResponse>> ObterReceitaAsync(long id, CancellationToken ct) { if (!EscopoValido) return EscopoFailure<OrcamentoReceitaResponse>(); if (!await CanAsync(FinanceiroPermissoes.OrcamentoVisualizar, ct).ConfigureAwait(false)) return Result<OrcamentoReceitaResponse>.Failure("403"); var item = await _repo.ObterReceitaAsync(TenantId, EntidadeId, ExercicioId, id, ct).ConfigureAwait(false); return item is null ? Result<OrcamentoReceitaResponse>.Failure("Orçamento não encontrado.") : Result<OrcamentoReceitaResponse>.Success(item); }
    public async Task<Result<long>> CriarReceitaAsync(OrcamentoReceitaCreateRequest r, CancellationToken ct) { if (!EscopoValido) return EscopoFailure<long>(); if (!await CanAsync(FinanceiroPermissoes.OrcamentoCriar, ct).ConfigureAwait(false)) return Result<long>.Failure("403"); var id = await _repo.CriarReceitaAsync(TenantId, EntidadeId, ExercicioId, r, UsuarioId, ct).ConfigureAwait(false); return Result<long>.Success(id); }
    public async Task<Result> AtualizarReceitaAsync(long id, OrcamentoReceitaUpdateRequest r, CancellationToken ct) { if (!EscopoValido) return EscopoFailure(); if (!await CanAsync(FinanceiroPermissoes.OrcamentoEditar, ct).ConfigureAwait(false)) return Result.Failure("403"); await _repo.AtualizarReceitaAsync(TenantId, EntidadeId, ExercicioId, id, r, UsuarioId, ct).ConfigureAwait(false); return Result.Success(); }
}

public sealed class EmpenhoService : FinanceiroServiceBase, IEmpenhoService
{
    private readonly IEmpenhoRepository _repo; private readonly IFinanceiroSequencialService _seq; private readonly ILogger<EmpenhoService> _logger;
    public EmpenhoService(IEmpenhoRepository repo, IFinanceiroSequencialService seq, ICurrentTenant tenant, ICurrentUser user, IPermissionService permissions, IAuditService audit, ILogger<EmpenhoService> logger) : base(tenant, user, permissions, audit) { _repo = repo; _seq = seq; _logger = logger; }
    public async Task<Result<PagedResult<EmpenhoResumoResponse>>> ListarAsync(EmpenhoFiltro f, CancellationToken ct) { if (!EscopoValido) return EscopoFailure<PagedResult<EmpenhoResumoResponse>>(); if (!await CanAsync(FinanceiroPermissoes.EmpenhoVisualizar, ct).ConfigureAwait(false)) return Result<PagedResult<EmpenhoResumoResponse>>.Failure("403"); return Result<PagedResult<EmpenhoResumoResponse>>.Success(await _repo.ListarAsync(TenantId, EntidadeId, ExercicioId, f, ct).ConfigureAwait(false)); }
    public async Task<Result<EmpenhoDetalheResponse>> ObterAsync(long id, CancellationToken ct) { if (!EscopoValido) return EscopoFailure<EmpenhoDetalheResponse>(); if (!await CanAsync(FinanceiroPermissoes.EmpenhoVisualizar, ct).ConfigureAwait(false)) return Result<EmpenhoDetalheResponse>.Failure("403"); var item = await _repo.ObterAsync(TenantId, EntidadeId, ExercicioId, id, ct).ConfigureAwait(false); return item is null ? Result<EmpenhoDetalheResponse>.Failure("Empenho não encontrado.") : Result<EmpenhoDetalheResponse>.Success(item); }
    public async Task<Result<long>> CriarAsync(EmpenhoCreateRequest r, string? IdempotencyKey, CancellationToken ct) { if (!EscopoValido) return EscopoFailure<long>(); if (!await CanAsync(FinanceiroPermissoes.EmpenhoCriar, ct).ConfigureAwait(false)) return Result<long>.Failure("403"); if (r.FornecedorPessoaId <= 0 || r.Itens.Count == 0 || r.Itens.Sum(i => i.Quantidade * i.ValorUnitario) <= 0m) return Result<long>.Failure("Empenho exige fornecedor, itens e valor maior que zero."); try { var ano = r.DataEmpenho.Year; var numero = await _seq.ProximoAsync(TenantId, EntidadeId, ExercicioId, ano, "empenho", "EMP", ct).ConfigureAwait(false); var op = await _repo.CriarAsync(TenantId, EntidadeId, ExercicioId, numero, ano, r, UsuarioId, IdempotencyKey, ct).ConfigureAwait(false); if (!op.Replay) await Audit.RegistrarAsync("financeiro", "EMPENHO_EMITIDO", "sigov.empenho", op.DocumentoId.ToString(System.Globalization.CultureInfo.InvariantCulture), null, r, ct).ConfigureAwait(false); return Result<long>.Success(op.DocumentoId); } catch (FinanceiroIdempotenciaConflitoException ex) { return Result<long>.Failure(ex.Message); } catch (ArgumentException ex) { return Result<long>.Failure(ex.Message); } catch (Exception ex) { _logger.LogError(ex, "Erro ao emitir empenho."); return Result<long>.Failure(ex.Message.StartsWith("Saldo disponível insuficiente") || ex.Message.StartsWith("Dotação orçamentária") ? ex.Message : "Erro ao emitir empenho. Verifique saldo disponível e exercício."); } }
    public async Task<Result> AtualizarAsync(long id, EmpenhoUpdateRequest r, CancellationToken ct) { if (!EscopoValido) return EscopoFailure(); if (!await CanAsync(FinanceiroPermissoes.EmpenhoEditar, ct).ConfigureAwait(false)) return Result.Failure("403"); try { await _repo.AtualizarAsync(TenantId, EntidadeId, ExercicioId, id, r, UsuarioId, ct).ConfigureAwait(false); return Result.Success(); } catch (Exception ex) { return Result.Failure(ex.Message.StartsWith("Empenho não encontrado") || ex.Message.StartsWith("já anulado") ? ex.Message : "Erro ao atualizar empenho."); } }
    public async Task<Result> AnularAsync(long id, AnularEmpenhoRequest r, string? IdempotencyKey, CancellationToken ct) { if (!EscopoValido) return EscopoFailure(); if (!await CanAsync(FinanceiroPermissoes.EmpenhoAnular, ct).ConfigureAwait(false)) return Result.Failure("403"); if (string.IsNullOrWhiteSpace(r.Motivo)) return Result.Failure("Motivo é obrigatório para anulação de empenho."); try { var replay = await _repo.AnularAsync(TenantId, EntidadeId, ExercicioId, id, r, UsuarioId, IdempotencyKey, ct).ConfigureAwait(false); if (!replay) await Audit.RegistrarAsync("financeiro", "EMPENHO_ANULADO", "sigov.empenho", id.ToString(System.Globalization.CultureInfo.InvariantCulture), null, r, ct).ConfigureAwait(false); return Result.Success(); } catch (FinanceiroIdempotenciaConflitoException ex) { return Result.Failure(ex.Message); } catch (ArgumentException ex) { return Result.Failure(ex.Message); } catch (Exception ex) { _logger.LogError(ex, "Erro ao anular empenho {Id}.", id); return Result.Failure(ex.Message.StartsWith("409:") || ex.Message.StartsWith("Valor excede") || ex.Message.StartsWith("Empenho não") ? ex.Message : "Erro ao anular empenho."); } }
}

public sealed class LiquidacaoService : FinanceiroServiceBase, ILiquidacaoService
{
    private readonly ILiquidacaoRepository _repo; private readonly IFinanceiroSequencialService _seq; private readonly ILogger<LiquidacaoService> _logger;
    public LiquidacaoService(ILiquidacaoRepository repo, IFinanceiroSequencialService seq, ICurrentTenant tenant, ICurrentUser user, IPermissionService permissions, IAuditService audit, ILogger<LiquidacaoService> logger) : base(tenant, user, permissions, audit) { _repo = repo; _seq = seq; _logger = logger; }
    public async Task<Result<PagedResult<LiquidacaoResponse>>> ListarAsync(LiquidacaoFiltro f, CancellationToken ct) { if (!EscopoValido) return EscopoFailure<PagedResult<LiquidacaoResponse>>(); if (!await CanAsync(FinanceiroPermissoes.LiquidacaoVisualizar, ct).ConfigureAwait(false)) return Result<PagedResult<LiquidacaoResponse>>.Failure("403"); return Result<PagedResult<LiquidacaoResponse>>.Success(await _repo.ListarAsync(TenantId, EntidadeId, ExercicioId, f, ct).ConfigureAwait(false)); }
    public async Task<Result<LiquidacaoResponse>> ObterAsync(long id, CancellationToken ct) { if (!EscopoValido) return EscopoFailure<LiquidacaoResponse>(); if (!await CanAsync(FinanceiroPermissoes.LiquidacaoVisualizar, ct).ConfigureAwait(false)) return Result<LiquidacaoResponse>.Failure("403"); var item = await _repo.ObterAsync(TenantId, EntidadeId, ExercicioId, id, ct).ConfigureAwait(false); return item is null ? Result<LiquidacaoResponse>.Failure("Liquidação não encontrada.") : Result<LiquidacaoResponse>.Success(item); }
    public async Task<Result<long>> CriarAsync(long empenhoId, LiquidacaoCreateRequest r, string? IdempotencyKey, CancellationToken ct) { if (!EscopoValido) return EscopoFailure<long>(); if (!await CanAsync(FinanceiroPermissoes.LiquidacaoCriar, ct).ConfigureAwait(false)) return Result<long>.Failure("403"); if (r.Valor <= 0m) return Result<long>.Failure("O valor da liquidação deve ser maior que zero."); try { var numero = await _seq.ProximoAsync(TenantId, EntidadeId, ExercicioId, r.DataLiquidacao.Year, "liquidacao", "LIQ", ct).ConfigureAwait(false); var op = await _repo.CriarAsync(TenantId, EntidadeId, ExercicioId, empenhoId, numero, r, UsuarioId, IdempotencyKey, ct).ConfigureAwait(false); if (!op.Replay) await Audit.RegistrarAsync("financeiro", "LIQUIDACAO_CRIADA", "sigov.liquidacao", op.DocumentoId.ToString(System.Globalization.CultureInfo.InvariantCulture), null, r, ct).ConfigureAwait(false); return Result<long>.Success(op.DocumentoId); } catch (FinanceiroIdempotenciaConflitoException ex) { return Result<long>.Failure(ex.Message); } catch (ArgumentException ex) { return Result<long>.Failure(ex.Message); } catch (Exception ex) { _logger.LogError(ex, "Erro ao criar liquidação para empenho {EmpenhoId}.", empenhoId); return Result<long>.Failure(ex.Message.StartsWith("Valor excede") || ex.Message.StartsWith("Empenho não") || ex.Message.StartsWith("Não é possível") ? ex.Message : "Erro ao registrar liquidação."); } }
    public async Task<Result> AnularAsync(long id, AnularLiquidacaoRequest r, string? IdempotencyKey, CancellationToken ct) { if (!EscopoValido) return EscopoFailure(); if (!await CanAsync(FinanceiroPermissoes.LiquidacaoAnular, ct).ConfigureAwait(false)) return Result.Failure("403"); if (string.IsNullOrWhiteSpace(r.Motivo)) return Result.Failure("Motivo é obrigatório para anulação de liquidação."); try { var replay = await _repo.AnularAsync(TenantId, EntidadeId, ExercicioId, id, r, UsuarioId, IdempotencyKey, ct).ConfigureAwait(false); if (!replay) await Audit.RegistrarAsync("financeiro", "LIQUIDACAO_ANULADA", "sigov.liquidacao", id.ToString(System.Globalization.CultureInfo.InvariantCulture), null, r, ct).ConfigureAwait(false); return Result.Success(); } catch (FinanceiroIdempotenciaConflitoException ex) { return Result.Failure(ex.Message); } catch (ArgumentException ex) { return Result.Failure(ex.Message); } catch (Exception ex) { _logger.LogError(ex, "Erro ao anular liquidação {Id}.", id); return Result.Failure(ex.Message.StartsWith("409:") || ex.Message.StartsWith("Não é possível") || ex.Message.StartsWith("Liquidação não") ? ex.Message : "Erro ao anular liquidação."); } }
}

public sealed class PagamentoService : FinanceiroServiceBase, IPagamentoService
{
    private readonly IPagamentoRepository _repo; private readonly IFinanceiroSequencialService _seq; private readonly ILogger<PagamentoService> _logger;
    public PagamentoService(IPagamentoRepository repo, IFinanceiroSequencialService seq, ICurrentTenant tenant, ICurrentUser user, IPermissionService permissions, IAuditService audit, ILogger<PagamentoService> logger) : base(tenant, user, permissions, audit) { _repo = repo; _seq = seq; _logger = logger; }
    public async Task<Result<PagedResult<PagamentoResponse>>> ListarAsync(PagamentoFiltro f, CancellationToken ct) { if (!EscopoValido) return EscopoFailure<PagedResult<PagamentoResponse>>(); if (!await CanAsync(FinanceiroPermissoes.PagamentoVisualizar, ct).ConfigureAwait(false)) return Result<PagedResult<PagamentoResponse>>.Failure("403"); return Result<PagedResult<PagamentoResponse>>.Success(await _repo.ListarAsync(TenantId, EntidadeId, ExercicioId, f, ct).ConfigureAwait(false)); }
    public async Task<Result<PagamentoResponse>> ObterAsync(long id, CancellationToken ct) { if (!EscopoValido) return EscopoFailure<PagamentoResponse>(); if (!await CanAsync(FinanceiroPermissoes.PagamentoVisualizar, ct).ConfigureAwait(false)) return Result<PagamentoResponse>.Failure("403"); var item = await _repo.ObterAsync(TenantId, EntidadeId, ExercicioId, id, ct).ConfigureAwait(false); return item is null ? Result<PagamentoResponse>.Failure("Pagamento não encontrado.") : Result<PagamentoResponse>.Success(item); }
    public async Task<Result<long>> CriarAsync(long liquidacaoId, PagamentoCreateRequest r, string? IdempotencyKey, CancellationToken ct) { if (!EscopoValido) return EscopoFailure<long>(); if (!await CanAsync(FinanceiroPermissoes.PagamentoCriar, ct).ConfigureAwait(false)) return Result<long>.Failure("403"); if (r.Valor <= 0m) return Result<long>.Failure("O valor do pagamento deve ser maior que zero."); if (string.IsNullOrWhiteSpace(r.FormaPagamento)) return Result<long>.Failure("A forma de pagamento é obrigatória."); try { var numero = await _seq.ProximoAsync(TenantId, EntidadeId, ExercicioId, r.DataPagamento.Year, "pagamento", "PGT", ct).ConfigureAwait(false); var op = await _repo.CriarAsync(TenantId, EntidadeId, ExercicioId, liquidacaoId, numero, r, UsuarioId, IdempotencyKey, ct).ConfigureAwait(false); if (!op.Replay) await Audit.RegistrarAsync("financeiro", "PAGAMENTO_CRIADO", "sigov.pagamento", op.DocumentoId.ToString(System.Globalization.CultureInfo.InvariantCulture), null, r, ct).ConfigureAwait(false); return Result<long>.Success(op.DocumentoId); } catch (FinanceiroIdempotenciaConflitoException ex) { return Result<long>.Failure(ex.Message); } catch (ArgumentException ex) { return Result<long>.Failure(ex.Message); } catch (Exception ex) { _logger.LogError(ex, "Erro ao criar pagamento para liquidação {LiquidacaoId}.", liquidacaoId); return Result<long>.Failure(ex.Message.StartsWith("Valor excede") || ex.Message.StartsWith("Liquidação não") ? ex.Message : "Erro ao registrar pagamento."); } }
    public async Task<Result> CancelarAsync(long id, CancelarPagamentoRequest r, string? IdempotencyKey, CancellationToken ct) { if (!EscopoValido) return EscopoFailure(); if (!await CanAsync(FinanceiroPermissoes.PagamentoCancelar, ct).ConfigureAwait(false)) return Result.Failure("403"); if (string.IsNullOrWhiteSpace(r.Motivo)) return Result.Failure("Motivo é obrigatório para cancelamento de pagamento."); try { var replay = await _repo.CancelarAsync(TenantId, EntidadeId, ExercicioId, id, r, UsuarioId, IdempotencyKey, ct).ConfigureAwait(false); if (!replay) await Audit.RegistrarAsync("financeiro", "PAGAMENTO_CANCELADO", "sigov.pagamento", id.ToString(System.Globalization.CultureInfo.InvariantCulture), null, r, ct).ConfigureAwait(false); return Result.Success(); } catch (FinanceiroIdempotenciaConflitoException ex) { return Result.Failure(ex.Message); } catch (ArgumentException ex) { return Result.Failure(ex.Message); } catch (Exception ex) { _logger.LogError(ex, "Erro ao cancelar pagamento {Id}.", id); return Result.Failure(ex.Message.StartsWith("409:") || ex.Message.StartsWith("Pagamento não") ? ex.Message : "Erro ao cancelar pagamento."); } }
}

public sealed class ReceitaService : FinanceiroServiceBase, IReceitaService
{
    private readonly IReceitaRepository _repo; private readonly IFinanceiroSequencialService _seq; private readonly ILogger<ReceitaService> _logger;
    public ReceitaService(IReceitaRepository repo, IFinanceiroSequencialService seq, ICurrentTenant tenant, ICurrentUser user, IPermissionService permissions, IAuditService audit, ILogger<ReceitaService> logger) : base(tenant, user, permissions, audit) { _repo = repo; _seq = seq; _logger = logger; }
    public async Task<Result<PagedResult<ReceitaLancamentoResponse>>> ListarLancamentosAsync(ReceitaLancamentoFiltro f, CancellationToken ct) { if (!EscopoValido) return EscopoFailure<PagedResult<ReceitaLancamentoResponse>>(); if (!await CanAsync(FinanceiroPermissoes.ReceitaVisualizar, ct).ConfigureAwait(false)) return Result<PagedResult<ReceitaLancamentoResponse>>.Failure("403"); return Result<PagedResult<ReceitaLancamentoResponse>>.Success(await _repo.ListarLancamentosAsync(TenantId, EntidadeId, ExercicioId, f, ct).ConfigureAwait(false)); }
    public async Task<Result<ReceitaLancamentoResponse>> ObterLancamentoAsync(long id, CancellationToken ct) { if (!EscopoValido) return EscopoFailure<ReceitaLancamentoResponse>(); if (!await CanAsync(FinanceiroPermissoes.ReceitaVisualizar, ct).ConfigureAwait(false)) return Result<ReceitaLancamentoResponse>.Failure("403"); var item = await _repo.ObterLancamentoAsync(TenantId, EntidadeId, ExercicioId, id, ct).ConfigureAwait(false); return item is null ? Result<ReceitaLancamentoResponse>.Failure("Receita não encontrada.") : Result<ReceitaLancamentoResponse>.Success(item); }
    public async Task<Result<IReadOnlyList<ReceitaArrecadacaoResponse>>> ListarArrecadacoesAsync(long lancamentoId, CancellationToken ct) { if (!EscopoValido) return EscopoFailure<IReadOnlyList<ReceitaArrecadacaoResponse>>(); if (!await CanAsync(FinanceiroPermissoes.ReceitaVisualizar, ct).ConfigureAwait(false)) return Result<IReadOnlyList<ReceitaArrecadacaoResponse>>.Failure("403"); return Result<IReadOnlyList<ReceitaArrecadacaoResponse>>.Success(await _repo.ListarArrecadacoesAsync(TenantId, EntidadeId, ExercicioId, lancamentoId, ct).ConfigureAwait(false)); }
    public async Task<Result<long>> CriarLancamentoAsync(ReceitaLancamentoCreateRequest r, string? IdempotencyKey, CancellationToken ct) { if (!EscopoValido) return EscopoFailure<long>(); if (!await CanAsync(FinanceiroPermissoes.ReceitaCriar, ct).ConfigureAwait(false)) return Result<long>.Failure("403"); if (r.Valor <= 0m) return Result<long>.Failure("O valor do lançamento deve ser maior que zero."); try { var numero = await _seq.ProximoAsync(TenantId, EntidadeId, ExercicioId, r.DataLancamento.Year, "receita_lancamento", "REC", ct).ConfigureAwait(false); var op = await _repo.CriarLancamentoAsync(TenantId, EntidadeId, ExercicioId, numero, r, UsuarioId, IdempotencyKey, ct).ConfigureAwait(false); if (!op.Replay) await Audit.RegistrarAsync("financeiro", "RECEITA_LANCADA", "sigov.receita_lancamento", op.DocumentoId.ToString(System.Globalization.CultureInfo.InvariantCulture), null, r, ct).ConfigureAwait(false); return Result<long>.Success(op.DocumentoId); } catch (FinanceiroIdempotenciaConflitoException ex) { return Result<long>.Failure(ex.Message); } catch (ArgumentException ex) { return Result<long>.Failure(ex.Message); } catch (Exception ex) { _logger.LogError(ex, "Erro ao criar lançamento de receita."); return Result<long>.Failure("Erro ao registrar lançamento de receita."); } }
    public async Task<Result<long>> ArrecadarAsync(long lancamentoId, ReceitaArrecadacaoCreateRequest r, string? IdempotencyKey, CancellationToken ct) { if (!EscopoValido) return EscopoFailure<long>(); if (!await CanAsync(FinanceiroPermissoes.ReceitaArrecadar, ct).ConfigureAwait(false)) return Result<long>.Failure("403"); if (r.Valor <= 0m) return Result<long>.Failure("O valor da arrecadação deve ser maior que zero."); try { var numero = await _seq.ProximoAsync(TenantId, EntidadeId, ExercicioId, r.DataArrecadacao.Year, "receita_arrecadacao", "ARQ", ct).ConfigureAwait(false); var op = await _repo.ArrecadarAsync(TenantId, EntidadeId, ExercicioId, lancamentoId, numero, r, UsuarioId, IdempotencyKey, ct).ConfigureAwait(false); if (!op.Replay) await Audit.RegistrarAsync("financeiro", "RECEITA_ARRECADADA", "sigov.receita_arrecadacao", op.DocumentoId.ToString(System.Globalization.CultureInfo.InvariantCulture), null, r, ct).ConfigureAwait(false); return Result<long>.Success(op.DocumentoId); } catch (FinanceiroIdempotenciaConflitoException ex) { return Result<long>.Failure(ex.Message); } catch (ArgumentException ex) { return Result<long>.Failure(ex.Message); } catch (Exception ex) { _logger.LogError(ex, "Erro ao arrecadar lançamento {Id}.", lancamentoId); return Result<long>.Failure(ex.Message.StartsWith("Valor excede") || ex.Message.StartsWith("Lançamento não") || ex.Message.StartsWith("Lançamento já") ? ex.Message : "Erro ao registrar arrecadação."); } }
    public async Task<Result> CancelarLancamentoAsync(long id, CancelarLancamentoRequest r, string? IdempotencyKey, CancellationToken ct) { if (!EscopoValido) return EscopoFailure(); if (!await CanAsync(FinanceiroPermissoes.ArrecadacaoCancelar, ct).ConfigureAwait(false)) return Result.Failure("403"); if (string.IsNullOrWhiteSpace(r.Motivo)) return Result.Failure("Motivo é obrigatório para cancelamento de lançamento."); try { var replay = await _repo.CancelarLancamentoAsync(TenantId, EntidadeId, ExercicioId, id, r, UsuarioId, IdempotencyKey, ct).ConfigureAwait(false); if (!replay) await Audit.RegistrarAsync("financeiro", "LANCAMENTO_CANCELADO", "sigov.receita_lancamento", id.ToString(System.Globalization.CultureInfo.InvariantCulture), null, r, ct).ConfigureAwait(false); return Result.Success(); } catch (FinanceiroIdempotenciaConflitoException ex) { return Result.Failure(ex.Message); } catch (ArgumentException ex) { return Result.Failure(ex.Message); } catch (Exception ex) { _logger.LogError(ex, "Erro ao cancelar lançamento {Id}.", id); return Result.Failure(ex.Message.StartsWith("409:") || ex.Message.StartsWith("Lançamento não") ? ex.Message : "Erro ao cancelar lançamento."); } }
    public async Task<Result> CancelarArrecadacaoAsync(long id, CancelarArrecadacaoRequest r, string? IdempotencyKey, CancellationToken ct) { if (!EscopoValido) return EscopoFailure(); if (!await CanAsync(FinanceiroPermissoes.ArrecadacaoCancelar, ct).ConfigureAwait(false)) return Result.Failure("403"); if (string.IsNullOrWhiteSpace(r.Motivo)) return Result.Failure("Motivo é obrigatório para cancelamento de arrecadação."); try { var replay = await _repo.CancelarArrecadacaoAsync(TenantId, EntidadeId, ExercicioId, id, r, UsuarioId, IdempotencyKey, ct).ConfigureAwait(false); if (!replay) await Audit.RegistrarAsync("financeiro", "ARRECADACAO_CANCELADA", "sigov.receita_arrecadacao", id.ToString(System.Globalization.CultureInfo.InvariantCulture), null, r, ct).ConfigureAwait(false); return Result.Success(); } catch (FinanceiroIdempotenciaConflitoException ex) { return Result.Failure(ex.Message); } catch (ArgumentException ex) { return Result.Failure(ex.Message); } catch (Exception ex) { _logger.LogError(ex, "Erro ao cancelar arrecadação {Id}.", id); return Result.Failure(ex.Message.StartsWith("409:") || ex.Message.StartsWith("Arrecadação não") ? ex.Message : "Erro ao cancelar arrecadação."); } }
}

public sealed class FinanceiroDashboardService : FinanceiroServiceBase, IFinanceiroDashboardService
{
    private readonly IFinanceiroDashboardRepository _repo;
    public FinanceiroDashboardService(IFinanceiroDashboardRepository repo, ICurrentTenant tenant, ICurrentUser user, IPermissionService permissions, IAuditService audit) : base(tenant, user, permissions, audit) { _repo = repo; }
    public async Task<Result<FinanceiroDashboardResponse>> ObterAsync(CancellationToken ct) { if (!EscopoValido) return EscopoFailure<FinanceiroDashboardResponse>(); if (!await CanAsync(FinanceiroPermissoes.DashboardVisualizar, ct).ConfigureAwait(false)) return Result<FinanceiroDashboardResponse>.Failure("403"); return Result<FinanceiroDashboardResponse>.Success(await _repo.ObterAsync(TenantId, EntidadeId, ExercicioId, ct).ConfigureAwait(false)); }
}

public sealed class FinanceiroExportacaoService : FinanceiroServiceBase, IFinanceiroExportacaoService
{
    private readonly IFinanceiroExportacaoRepository _repo;
    public FinanceiroExportacaoService(IFinanceiroExportacaoRepository repo, ICurrentTenant tenant, ICurrentUser user, IPermissionService permissions, IAuditService audit) : base(tenant, user, permissions, audit) { _repo = repo; }
    public async Task<Result<byte[]>> ExportarAsync(string recurso, string formato, CancellationToken ct)
    {
        if (!EscopoValido) return EscopoFailure<byte[]>();
        if (!await CanAsync(FinanceiroPermissoes.Exportar, ct).ConfigureAwait(false)) return Result<byte[]>.Failure("403");
        await Audit.RegistrarAsync("financeiro", "EXPORTAR", $"financeiro.{recurso}", formato, null, new { recurso, formato }, ct).ConfigureAwait(false);
        var data = await _repo.ExportarAsync(TenantId, EntidadeId, ExercicioId, recurso, formato, ct).ConfigureAwait(false);
        return Result<byte[]>.Success(data);
    }
}

public sealed class FinanceiroConferenciaService : FinanceiroServiceBase, IFinanceiroConferenciaService
{
    private readonly IFinanceiroConferenciaRepository _repo; private readonly ILogger<FinanceiroConferenciaService> _logger;
    public FinanceiroConferenciaService(IFinanceiroConferenciaRepository repo, ICurrentTenant tenant, ICurrentUser user, IPermissionService permissions, IAuditService audit, ILogger<FinanceiroConferenciaService> logger) : base(tenant, user, permissions, audit) { _repo = repo; _logger = logger; }
    public async Task<Result<ConferenciaResponse>> ConferirAsync(ConferenciaFiltro filtro, CancellationToken ct)
    {
        if (!EscopoValido) return EscopoFailure<ConferenciaResponse>();
        if (!await CanAsync(FinanceiroPermissoes.ConferenciaVisualizar, ct).ConfigureAwait(false)) return Result<ConferenciaResponse>.Failure("403");
        try { return Result<ConferenciaResponse>.Success(await _repo.ConferirAsync(TenantId, EntidadeId, ExercicioId, filtro, ct).ConfigureAwait(false)); }
        catch (Exception ex) { _logger.LogError(ex, "Erro na conferência financeira."); return Result<ConferenciaResponse>.Failure("Erro na conferência financeira."); }
    }
    public async Task<Result> AjustarAsync(ConferenciaAjustarRequest request, string? IdempotencyKey, CancellationToken ct)
    {
        if (!EscopoValido) return EscopoFailure();
        if (!await CanAsync(FinanceiroPermissoes.ConferenciaAjustar, ct).ConfigureAwait(false)) return Result.Failure("403");
        if (string.IsNullOrWhiteSpace(request.Justificativa)) return Result.Failure("Justificativa é obrigatória para ajuste de conferência.");
        if (string.IsNullOrWhiteSpace(request.TipoDocumento)) return Result.Failure("Tipo de documento é obrigatório para ajuste de conferência.");
        try
        {
            // Recalcula a diferença no servidor: valores vindos da tela não são autoridade.
            var conferencia = await _repo.ConferirAsync(TenantId, EntidadeId, ExercicioId, new ConferenciaFiltro { Page = 1, PageSize = 1000 }, ct).ConfigureAwait(false);
            var item = conferencia.Itens.FirstOrDefault(i => i.DocumentoId == request.DocumentoId && string.Equals(i.TipoDocumento, request.TipoDocumento.Trim(), StringComparison.OrdinalIgnoreCase));
            if (item is null) return Result.Failure("Documento não localizado na conferência. Recarregue a tela e tente novamente.");
            decimal ajuste = item.ValorCalculado - item.ValorRegistrado;
            if (ajuste == 0m) return Result.Failure("A diferença deste documento já está zerada; não há ajuste pendente.");
            var replay = await _repo.AjustarAsync(TenantId, EntidadeId, ExercicioId, request.DocumentoId, request.TipoDocumento, ajuste, request.Justificativa, UsuarioId, IdempotencyKey, ct).ConfigureAwait(false);
            if (!replay) await Audit.RegistrarAsync("financeiro", "AJUSTE_CONFERENCIA", $"financeiro_conferencia.{request.TipoDocumento}", request.DocumentoId.ToString(System.Globalization.CultureInfo.InvariantCulture), null, new { request.DocumentoId, request.TipoDocumento, ajuste, justificativa = request.Justificativa }, ct).ConfigureAwait(false);
            return Result.Success();
        }
        catch (FinanceiroIdempotenciaConflitoException ex) { return Result.Failure(ex.Message); }
        catch (ArgumentException ex) { return Result.Failure(ex.Message); }
        catch (Exception ex) { _logger.LogError(ex, "Erro no ajuste de conferência {Id}.", request.DocumentoId); return Result.Failure("Erro no ajuste de conferência."); }
    }
}
