using Sigov.Application.Common;
using Sigov.Domain.Common;

namespace Sigov.Application.Saude;

public static class SaudePermissoes { public const string Modulo = "saude"; public const string AcsOfflineFeature = "saude.acs_offline"; }

public sealed record UnidadeSaudeCreateRequest(string Codigo, string Nome, string TipoUnidade = "BASICA", string Situacao = "ATIVA", string? Cnes = null, string? Observacao = null, decimal? Latitude = null, decimal? Longitude = null);
public sealed record UnidadeSaudeUpdateRequest(string Codigo, string Nome, string TipoUnidade = "BASICA", string Situacao = "ATIVA", string? Cnes = null, string? Observacao = null, decimal? Latitude = null, decimal? Longitude = null);
public sealed record UnidadeSaudeFiltro(int Page = 1, int PageSize = 20, string? Termo = null, bool? Ativo = null);
public sealed record UnidadeSaudeResponse(long Id, string Codigo, string Nome, string TipoUnidade, string Situacao, string? Cnes, bool Ativo);

public sealed record ProfissionalSaudeCreateRequest(long PessoaId, string CodigoProfissional, string TipoProfissional = "OUTRO", string Situacao = "ATIVO", long? ServidorId = null, long? UnidadeSaudeId = null, string? Cbo = null, string? ConselhoClasse = null, string? NumeroConselho = null, string? UfConselho = null);
public sealed record ProfissionalSaudeUpdateRequest(string CodigoProfissional, string TipoProfissional = "OUTRO", string Situacao = "ATIVO", long? ServidorId = null, long? UnidadeSaudeId = null, string? Cbo = null, string? ConselhoClasse = null, string? NumeroConselho = null, string? UfConselho = null);
public sealed record ProfissionalSaudeFiltro(int Page = 1, int PageSize = 20, string? Termo = null, string? Situacao = null);
public sealed record ProfissionalSaudeResponse(long Id, long PessoaId, string CodigoProfissional, string TipoProfissional, string Situacao, long? UnidadeSaudeId);

public sealed record PacienteCreateRequest(long PessoaId, string CodigoPaciente, string? CartaoSus = null, string? ProntuarioNumero = null, string? GrupoSanguineo = null, string? Alergias = null, Dictionary<string, object?>? DadosSensiveis = null, string Situacao = "ATIVO");
public sealed record PacienteUpdateRequest(string CodigoPaciente, string? CartaoSus = null, string? ProntuarioNumero = null, string? GrupoSanguineo = null, string? Alergias = null, Dictionary<string, object?>? DadosSensiveis = null, string Situacao = "ATIVO");
public sealed record PacienteFiltro(int Page = 1, int PageSize = 20, string? Termo = null, string? Situacao = null);
public sealed record PacienteResumoResponse(long Id, long PessoaId, string CodigoPaciente, string? CartaoSus, string? ProntuarioNumero, string Situacao);
public sealed record PacienteDetalheResponse(long Id, long PessoaId, string CodigoPaciente, string? CartaoSus, string? ProntuarioNumero, string? GrupoSanguineo, string? Alergias, string Situacao);

public sealed record ProntuarioResponse(long Id, long PacienteId, string Numero, string? ResumoClinico, string? Alergias, DateTimeOffset? UltimoAtendimentoAt);
public sealed record ProntuarioUpdateRequest(string? ResumoClinico = null, string? Alergias = null, string? ObservacoesSensiveis = null);

public sealed record AtendimentoSaudeCreateRequest(long UnidadeSaudeId, long PacienteId, string TipoAtendimento = "CONSULTA", long? ProfissionalSaudeId = null, string? ClassificacaoRisco = null, string? QueixaPrincipal = null);
public sealed record AtendimentoSaudeUpdateRequest(string TipoAtendimento = "CONSULTA", string Status = "AGENDADO", long? ProfissionalSaudeId = null, string? ClassificacaoRisco = null, string? QueixaPrincipal = null, string? Conduta = null, string? Cid10 = null);
public sealed record AtendimentoSaudeFiltro(int Page = 1, int PageSize = 20, long? PacienteId = null, long? UnidadeSaudeId = null, string? Status = null);
public sealed record AtendimentoSaudeResponse(long Id, string Numero, long UnidadeSaudeId, long PacienteId, DateTimeOffset DataAtendimento, string TipoAtendimento, string Status);
public sealed record RegistrarCondutaRequest(string Conduta, string? Cid10 = null);

public sealed record AgendaSaudeCreateRequest(long UnidadeSaudeId, DateTimeOffset DataInicio, DateTimeOffset DataFim, string TipoAgendamento = "CONSULTA", long? ProfissionalSaudeId = null, long? PacienteId = null, string Status = "AGENDADA", string? Observacao = null);
public sealed record AgendaSaudeFiltro(int Page = 1, int PageSize = 20, long? UnidadeSaudeId = null, DateTimeOffset? Inicio = null, DateTimeOffset? Fim = null);
public sealed record AgendaSaudeResponse(long Id, long UnidadeSaudeId, DateTimeOffset DataInicio, DateTimeOffset DataFim, string TipoAgendamento, string Status);

public sealed record FarmaciaProdutoCreateRequest(string Codigo, string Nome, string UnidadeMedida = "UN", string? PrincipioAtivo = null, string? Concentracao = null, string? FormaFarmaceutica = null, bool ControlaLote = true, bool MedicamentoControlado = false);
public sealed record FarmaciaProdutoResponse(long Id, string Codigo, string Nome, string UnidadeMedida, bool Ativo);
public sealed record FarmaciaEstoqueResponse(long Id, long UnidadeSaudeId, long FarmaciaProdutoId, string? Lote, DateOnly? Validade, decimal Quantidade);
public sealed record FarmaciaDispensacaoCreateRequest(long UnidadeSaudeId, long PacienteId, long FarmaciaProdutoId, decimal Quantidade, long? ProfissionalSaudeId = null, string? Lote = null, string? Observacao = null);
public sealed record FarmaciaDispensacaoResponse(long Id, long PacienteId, long FarmaciaProdutoId, decimal Quantidade, DateTimeOffset DataDispensacao);

public sealed record VacinacaoCreateRequest(long UnidadeSaudeId, long PacienteId, string Vacina, string Dose, DateOnly DataAplicacao, long? ProfissionalSaudeId = null, string? Lote = null, string? Fabricante = null, string? Observacao = null);
public sealed record VacinacaoResponse(long Id, long PacienteId, string Vacina, string Dose, DateOnly DataAplicacao);
public sealed record LaboratorioExameCreateRequest(long PacienteId, string TipoExame, long? UnidadeSaudeId = null, long? ProfissionalSolicitanteId = null, string? Observacao = null);
public sealed record LaboratorioResultadoRequest(Dictionary<string, object?> Resultado, DateOnly? DataResultado = null, string? Observacao = null);
public sealed record LaboratorioExameResponse(long Id, long PacienteId, string TipoExame, string Status, DateOnly DataSolicitacao, DateOnly? DataResultado);
public sealed record RegulacaoSolicitacaoCreateRequest(long PacienteId, string TipoSolicitacao, string Prioridade, string Justificativa, long? UnidadeOrigemId = null, string? Especialidade = null);
public sealed record RegulacaoSolicitacaoResponse(long Id, long PacienteId, string TipoSolicitacao, string Prioridade, string Status, DateOnly DataSolicitacao);
public sealed record AlterarStatusRequest(string Status);

public sealed record AcsMicroareaCreateRequest(long UnidadeSaudeId, string Codigo, string Nome, long? ProfissionalAcsId = null, Dictionary<string, object?>? PoligonoGeoJson = null);
public sealed record AcsMicroareaResponse(long Id, string Codigo, string Nome, bool Ativo);
public sealed record AcsDispositivoCreateRequest(long ProfissionalAcsId, string Identificador, string? Modelo = null, string? Plataforma = null, string Status = "ATIVO");
public sealed record AcsCadastroDomiciliarCreateRequest(string CodigoDomicilio, Dictionary<string, object?>? Endereco = null, Dictionary<string, object?>? CondicoesMoradia = null, long? AcsMicroareaId = null, decimal? Latitude = null, decimal? Longitude = null, decimal? PrecisaoMetros = null, string Status = "ATIVO");
public sealed record AcsCadastroDomiciliarResponse(long Id, string CodigoDomicilio, decimal? Latitude, decimal? Longitude, string Status);
public sealed record AcsCadastroIndividualCreateRequest(long PessoaId, long? AcsCadastroDomiciliarId = null, long? PacienteId = null, Dictionary<string, object?>? CondicoesSaude = null, Dictionary<string, object?>? Vulnerabilidades = null, string Status = "ATIVO");
public sealed record AcsCadastroIndividualResponse(long Id, long PessoaId, long? PacienteId, string Status);
public sealed record AcsVisitaCreateRequest(long ProfissionalAcsId, string TipoVisita, string Desfecho, long? AcsCadastroDomiciliarId = null, long? AcsCadastroIndividualId = null, long? PacienteId = null, DateTimeOffset? DataVisita = null, string? Observacao = null, decimal? Latitude = null, decimal? Longitude = null, decimal? PrecisaoMetros = null, string? OfflineId = null);
public sealed record AcsVisitaResponse(long Id, long ProfissionalAcsId, DateTimeOffset DataVisita, string TipoVisita, string Desfecho);
public sealed record AcsSyncLoteRequest(string LoteId, long? DispositivoId, long? ProfissionalAcsId, IReadOnlyCollection<AcsSyncItemRequest> Itens);
public sealed record AcsSyncItemRequest(string TipoItem, string OfflineId, Dictionary<string, object?> Payload);
public sealed record AcsSyncLoteResponse(string LoteId, string Status, int TotalItens, int TotalProcessados, int TotalErros, IReadOnlyCollection<AcsSyncItemResponse> Itens);
public sealed record AcsSyncItemResponse(string TipoItem, string OfflineId, string Status, string? Erro = null);
public sealed record SaudeDashboardResponse(long TotalUnidades, long TotalProfissionais, long TotalPacientesAtivos, long AtendimentosHoje, long AtendimentosMes, long AgendaHoje, long DispensacoesMes, long EstoqueBaixo, long VacinacoesMes, long ExamesPendentes, long RegulacoesPendentes, long MicroareasAtivas, long DomiciliosCadastrados, long IndividuosCadastrados, long VisitasAcsMes, long SyncsPendentes, IReadOnlyCollection<object> UltimosAtendimentos, IReadOnlyCollection<object> UltimasVisitasAcs, IReadOnlyCollection<string> Alertas);

public interface ISaudeCrudRepository { Task<PagedResult<T>> ListarAsync<T>(long tenantId, long entidadeId, long? exercicioId, string recurso, object filtro, CancellationToken ct); Task<T?> ObterAsync<T>(long tenantId, long entidadeId, long? exercicioId, string recurso, long id, CancellationToken ct); Task<long> CriarAsync(long tenantId, long entidadeId, long? exercicioId, string recurso, object request, long? usuarioId, CancellationToken ct); Task AtualizarAsync(long tenantId, long entidadeId, long? exercicioId, string recurso, long id, object request, long? usuarioId, CancellationToken ct); Task ExcluirAsync(long tenantId, long entidadeId, string recurso, long id, long? usuarioId, CancellationToken ct); Task<SaudeDashboardResponse> DashboardAsync(long tenantId, long entidadeId, CancellationToken ct); Task<byte[]> ExportarAsync(long tenantId, long entidadeId, string recurso, string formato, CancellationToken ct); Task<AcsSyncLoteResponse?> ObterSyncAsync(long tenantId, long entidadeId, string loteId, CancellationToken ct); }
public interface IUnidadeSaudeRepository : ISaudeCrudRepository { } public interface IProfissionalSaudeRepository : ISaudeCrudRepository { } public interface IPacienteRepository : ISaudeCrudRepository { } public interface IProntuarioRepository : ISaudeCrudRepository { } public interface IAtendimentoSaudeRepository : ISaudeCrudRepository { } public interface IAgendaSaudeRepository : ISaudeCrudRepository { } public interface IFarmaciaRepository : ISaudeCrudRepository { } public interface IVacinacaoRepository : ISaudeCrudRepository { } public interface ILaboratorioRepository : ISaudeCrudRepository { } public interface IRegulacaoRepository : ISaudeCrudRepository { } public interface IAcsRepository : ISaudeCrudRepository { } public interface IAcsSyncRepository : ISaudeCrudRepository { } public interface ISaudeDashboardRepository : ISaudeCrudRepository { } public interface ISaudeExportacaoRepository : ISaudeCrudRepository { } public interface ISaudeSequencialService { Task<string> ProximoAsync(string prefixo, int ano, CancellationToken ct); }

public interface IUnidadeSaudeService { Task<Result<PagedResult<UnidadeSaudeResponse>>> ListarAsync(UnidadeSaudeFiltro filtro, CancellationToken ct); Task<Result<UnidadeSaudeResponse>> ObterAsync(long id, CancellationToken ct); Task<Result<long>> CriarAsync(UnidadeSaudeCreateRequest request, CancellationToken ct); Task<Result> AtualizarAsync(long id, UnidadeSaudeUpdateRequest request, CancellationToken ct); Task<Result> ExcluirAsync(long id, CancellationToken ct); }
public interface IProfissionalSaudeService { Task<Result<PagedResult<ProfissionalSaudeResponse>>> ListarAsync(ProfissionalSaudeFiltro filtro, CancellationToken ct); Task<Result<ProfissionalSaudeResponse>> ObterAsync(long id, CancellationToken ct); Task<Result<long>> CriarAsync(ProfissionalSaudeCreateRequest request, CancellationToken ct); Task<Result> AtualizarAsync(long id, ProfissionalSaudeUpdateRequest request, CancellationToken ct); Task<Result> ExcluirAsync(long id, CancellationToken ct); }
public interface IPacienteService { Task<Result<PagedResult<PacienteResumoResponse>>> ListarAsync(PacienteFiltro filtro, CancellationToken ct); Task<Result<PacienteDetalheResponse>> ObterAsync(long id, CancellationToken ct); Task<Result<long>> CriarAsync(PacienteCreateRequest request, CancellationToken ct); Task<Result> AtualizarAsync(long id, PacienteUpdateRequest request, CancellationToken ct); Task<Result> ExcluirAsync(long id, CancellationToken ct); }
public interface IProntuarioService { Task<Result<ProntuarioResponse>> ObterPorPacienteAsync(long pacienteId, CancellationToken ct); Task<Result> AtualizarAsync(long pacienteId, ProntuarioUpdateRequest request, CancellationToken ct); }
public interface IAtendimentoSaudeService { Task<Result<PagedResult<AtendimentoSaudeResponse>>> ListarAsync(AtendimentoSaudeFiltro filtro, CancellationToken ct); Task<Result<AtendimentoSaudeResponse>> ObterAsync(long id, CancellationToken ct); Task<Result<long>> CriarAsync(AtendimentoSaudeCreateRequest request, CancellationToken ct); Task<Result> AtualizarAsync(long id, AtendimentoSaudeUpdateRequest request, CancellationToken ct); Task<Result> RegistrarCondutaAsync(long id, RegistrarCondutaRequest request, CancellationToken ct); Task<Result> CancelarAsync(long id, CancellationToken ct); }
public interface IAgendaSaudeService { Task<Result<PagedResult<AgendaSaudeResponse>>> ListarAsync(AgendaSaudeFiltro filtro, CancellationToken ct); Task<Result<long>> CriarAsync(AgendaSaudeCreateRequest request, CancellationToken ct); Task<Result> CancelarAsync(long id, CancellationToken ct); }
public interface IFarmaciaService { Task<Result<PagedResult<FarmaciaProdutoResponse>>> ListarProdutosAsync(UnidadeSaudeFiltro filtro, CancellationToken ct); Task<Result<long>> CriarProdutoAsync(FarmaciaProdutoCreateRequest request, CancellationToken ct); Task<Result<PagedResult<FarmaciaEstoqueResponse>>> ListarEstoqueAsync(UnidadeSaudeFiltro filtro, CancellationToken ct); Task<Result<long>> DispensarAsync(FarmaciaDispensacaoCreateRequest request, CancellationToken ct); }
public interface IVacinacaoService { Task<Result<PagedResult<VacinacaoResponse>>> ListarAsync(PacienteFiltro filtro, CancellationToken ct); Task<Result<long>> CriarAsync(VacinacaoCreateRequest request, CancellationToken ct); }
public interface ILaboratorioService { Task<Result<PagedResult<LaboratorioExameResponse>>> ListarAsync(PacienteFiltro filtro, CancellationToken ct); Task<Result<long>> CriarAsync(LaboratorioExameCreateRequest request, CancellationToken ct); Task<Result> RegistrarResultadoAsync(long id, LaboratorioResultadoRequest request, CancellationToken ct); }
public interface IRegulacaoService { Task<Result<PagedResult<RegulacaoSolicitacaoResponse>>> ListarAsync(PacienteFiltro filtro, CancellationToken ct); Task<Result<long>> CriarAsync(RegulacaoSolicitacaoCreateRequest request, CancellationToken ct); Task<Result> AlterarStatusAsync(long id, AlterarStatusRequest request, CancellationToken ct); }
public interface IAcsService { Task<Result<PagedResult<AcsMicroareaResponse>>> ListarMicroareasAsync(UnidadeSaudeFiltro filtro, CancellationToken ct); Task<Result<long>> CriarMicroareaAsync(AcsMicroareaCreateRequest request, CancellationToken ct); Task<Result<long>> CriarDispositivoAsync(AcsDispositivoCreateRequest request, CancellationToken ct); Task<Result<PagedResult<AcsCadastroDomiciliarResponse>>> ListarDomiciliosAsync(UnidadeSaudeFiltro filtro, CancellationToken ct); Task<Result<long>> CriarDomicilioAsync(AcsCadastroDomiciliarCreateRequest request, CancellationToken ct); Task<Result<PagedResult<AcsCadastroIndividualResponse>>> ListarIndividuosAsync(PacienteFiltro filtro, CancellationToken ct); Task<Result<long>> CriarIndividuoAsync(AcsCadastroIndividualCreateRequest request, CancellationToken ct); Task<Result<PagedResult<AcsVisitaResponse>>> ListarVisitasAsync(PacienteFiltro filtro, CancellationToken ct); Task<Result<long>> RegistrarVisitaAsync(AcsVisitaCreateRequest request, CancellationToken ct); }
public interface IAcsSyncService { Task<Result<AcsSyncLoteResponse>> ProcessarAsync(AcsSyncLoteRequest request, CancellationToken ct); Task<Result<AcsSyncLoteResponse>> ObterAsync(string loteId, CancellationToken ct); }
public interface ISaudeDashboardService { Task<Result<SaudeDashboardResponse>> ObterAsync(CancellationToken ct); }
public interface ISaudeExportacaoService { Task<Result<byte[]>> ExportarAsync(string recurso, string formato, CancellationToken ct); }
