using System.ComponentModel.DataAnnotations;

namespace Sigov.Web.Models.Educacao;

public sealed class EscolaFormViewModel { [Required] public string Codigo { get; set; } = string.Empty; [Required] public string Nome { get; set; } = string.Empty; public string TipoEscola { get; set; } = "MUNICIPAL"; public string Situacao { get; set; } = "ATIVA"; public string? InepCodigo { get; set; } public string? Observacao { get; set; } }
public sealed class AnoLetivoFormViewModel { public long? EscolaId { get; set; } public int Ano { get; set; } = DateTime.Today.Year; public DateOnly Inicio { get; set; } = DateOnly.FromDateTime(DateTime.Today); public DateOnly Fim { get; set; } = DateOnly.FromDateTime(DateTime.Today.AddMonths(10)); public string Status { get; set; } = "ABERTO"; }
public sealed class CursoFormViewModel { [Required] public string Codigo { get; set; } = string.Empty; [Required] public string Nome { get; set; } = string.Empty; public string? Observacao { get; set; } public bool Ativo { get; set; } = true; }
public sealed class SerieAnoFormViewModel { public long CursoId { get; set; } [Required] public string Nome { get; set; } = string.Empty; public int Ordem { get; set; } = 1; public bool Ativo { get; set; } = true; }
public sealed class TurmaFormViewModel { public long EscolaId { get; set; } public long AnoLetivoId { get; set; } public long CursoId { get; set; } public long SerieAnoId { get; set; } [Required] public string Codigo { get; set; } = string.Empty; [Required] public string Nome { get; set; } = string.Empty; public string Turno { get; set; } = "MATUTINO"; public int Capacidade { get; set; } = 30; public string Status { get; set; } = "ABERTA"; }
public sealed class AlunoFormViewModel { public long PessoaId { get; set; } [Required] public string CodigoAluno { get; set; } = string.Empty; public string? Nis { get; set; } public string? CartaoSus { get; set; } public bool NecessidadeEspecial { get; set; } public string Situacao { get; set; } = "ATIVO"; }
public sealed class ResponsavelAlunoViewModel { public long PessoaId { get; set; } public string Parentesco { get; set; } = string.Empty; public bool ResponsavelLegal { get; set; } public bool Financeiro { get; set; } public bool AutorizadoBuscar { get; set; } public bool ContatoEmergencia { get; set; } }
public sealed class MatriculaFormViewModel { public long AlunoId { get; set; } public long EscolaId { get; set; } public long AnoLetivoId { get; set; } public long TurmaId { get; set; } public string? NumeroMatricula { get; set; } public string Status { get; set; } = "ATIVA"; }
public sealed class ProfessorFormViewModel { public long PessoaId { get; set; } public string CodigoProfessor { get; set; } = string.Empty; public long? ServidorId { get; set; } public string? Formacao { get; set; } public string Situacao { get; set; } = "ATIVO"; }
public sealed class FrequenciaFormViewModel { public long TurmaId { get; set; } public long AlunoId { get; set; } public long? ProfessorId { get; set; } public DateOnly DataAula { get; set; } public string? ComponenteCurricular { get; set; } public bool Presente { get; set; } public string Status { get; set; } = "NAO_LANCADO"; public string? Justificativa { get; set; } }
public sealed class AvaliacaoFormViewModel { public long TurmaId { get; set; } public long? ProfessorId { get; set; } public string ComponenteCurricular { get; set; } = string.Empty; public string Titulo { get; set; } = string.Empty; public DateOnly DataAvaliacao { get; set; } public decimal ValorMaximo { get; set; } public decimal Peso { get; set; } public string Status { get; set; } = "ABERTA"; }
public sealed class NotaFormViewModel { public long AlunoId { get; set; } public decimal Valor { get; set; } public string? Observacao { get; set; } }
public sealed class PreMatriculaFormViewModel { [Range(1, long.MaxValue)] public long AlunoPessoaId { get; set; } public long? ResponsavelPessoaId { get; set; } public long? EscolaPreferencialId { get; set; } [Range(2000, 2200)] public int AnoLetivo { get; set; } = DateTime.Today.Year; [Required] public string EtapaEnsino { get; set; } = string.Empty; public string? Turno { get; set; } public string? Protocolo { get; set; } public string Status { get; set; } = "RASCUNHO"; public decimal? Pontuacao { get; set; } public string? Observacao { get; set; } }
public sealed class EducacaoDashboardViewModel { public string Titulo { get; set; } = "Dashboard Educação"; }
public sealed record EducacaoRecursoViewModel(string Titulo, string Descricao, string Endpoint);
