using System.Text;
using System.Text.Json;
using Dapper;
using Sigov.Application.Compras;
using Sigov.Infrastructure.Persistence.Dapper;

namespace Sigov.Infrastructure.Compras;

public sealed class LicitaProService(NpgsqlConnectionFactory factory) : ILicitaProService
{
    public async Task<LicitaProDashboard> DashboardAsync(long t,long e,CancellationToken ct)
    {
        const string sql = """
select count(*) filter(where status='ABERTA' and (data_limite is null or data_limite>=current_date)) Abertas,count(*) filter(where status='ABERTA' and data_limite between current_date and current_date+7) Vencendo,count(*) filter(where status='VENCIDA' or data_limite<current_date) Vencidas,count(*) filter(where processo_id is not null) Vinculadas,(select count(distinct fornecedor_id) from sigov.compras_licitapro_documento where tenant_id=@t and entidade_id=@e and validade<current_date) FornecedoresDocumentoVencido,(select count(*) from sigov.compras_licitapro_checklist where tenant_id=@t and entidade_id=@e and status in('PENDENTE','EM_ANALISE')) ChecklistsPendentes,(select count(*) from sigov.compras_licitapro_agenda where tenant_id=@t and entidade_id=@e and status='PREPARACAO') PropostasPreparacao,(select count(*) from sigov.compras_licitapro_agenda where tenant_id=@t and entidade_id=@e and status='CONQUISTADA' and contrato_id is not null) ContratosConquistados,coalesce((select avg(aderencia_percentual) from sigov.compras_licitapro_criterio where tenant_id=@t and entidade_id=@e),0) AderenciaMedia from sigov.compras_licitapro_oportunidade where tenant_id=@t and entidade_id=@e
""";
        await using var c=factory.CreateConnection(); return await c.QuerySingleAsync<LicitaProDashboard>(new CommandDefinition(sql,new{t,e},cancellationToken:ct));
    }
    public async Task<IReadOnlyList<LicitaProFonte>> FontesAsync(long t,long e,CancellationToken ct) { await using var c=factory.CreateConnection(); return (await c.QueryAsync<LicitaProFonte>(new CommandDefinition("select id,nome,tipo,configurada,ativa,ultima_sincronizacao_at UltimaSincronizacaoAt,case when not configurada then 'Fonte não configurada' when not ativa then 'Indisponível' else 'Disponível' end Estado from sigov.compras_licitapro_fonte where tenant_id=@t and entidade_id=@e order by nome",new{t,e},cancellationToken:ct))).AsList(); }
    public async Task<IReadOnlyList<LicitaProOportunidade>> OportunidadesAsync(long t,long e,LicitaProFiltro f,CancellationToken ct) { const string q="select o.id,o.numero,o.objeto,o.modalidade,x.nome Fonte,o.data_publicacao DataPublicacao,o.data_limite DataLimite,o.status,o.processo_id ProcessoId from sigov.compras_licitapro_oportunidade o join sigov.compras_licitapro_fonte x on x.id=o.fonte_id where o.tenant_id=@t and o.entidade_id=@e and (@s is null or o.status=@s) and (@b is null or o.objeto ilike '%'||@b||'%' or o.numero ilike '%'||@b||'%') and (@f is null or o.fonte_id=@f) and (@de is null or o.data_publicacao>=@de) and (@ate is null or o.data_publicacao<=@ate) order by o.data_limite nulls last,o.data_publicacao desc"; await using var c=factory.CreateConnection(); return (await c.QueryAsync<LicitaProOportunidade>(new CommandDefinition(q,new{t,e,s=N(f.Status),b=N(f.Busca),f=f.FonteId,de=f.De,ate=f.Ate},cancellationToken:ct))).AsList(); }
    public async Task<LicitaProOportunidade?> OportunidadeAsync(long t,long e,long id,CancellationToken ct)=> (await OportunidadesAsync(t,e,new(),ct)).SingleOrDefault(x=>x.Id==id);
    public async Task<LicitaProWorkspace> WorkspaceAsync(long t,long e,string area,LicitaProFiltro f,CancellationToken ct)
    {
        var config = area switch {"Importacoes"=>("Importações versionadas","Histórico real de coleta das fontes oficiais","compras_licitapro_importacao","coalesce(erro_sanitizado,'Versão '||versao)"),"Portal"=>("Portal do fornecedor","Situação documental e participação por fornecedor","compras_licitapro_documento","titulo"),"Documentos"=>("Certidões e documentos","Validades, análise e referências documentais","compras_licitapro_documento","titulo"),"Checklists"=>("Checklist de habilitação","Requisitos persistidos por fornecedor e processo","compras_licitapro_checklist","'Checklist do processo '||processo_id"),"Analises"=>("Análise assistida do edital","Sugestões explicáveis que não automatizam decisões","compras_licitapro_analise","coalesce(observacoes,'Análise em elaboração')"),"Agenda"=>("Agenda de proposta","Prazos e preparação de propostas","compras_licitapro_agenda","titulo"),"Alertas"=>("Alertas","Vencimentos documentais e prazos operacionais","compras_licitapro_alerta","mensagem"),"Auditoria"=>("Auditoria LicitaPro","Ações do LicitaPro no FUNC03","compras_licitapro_auditoria","acao||' · '||entidade"),_=>("LicitaPro","Dados persistidos do FUNC03","compras_licitapro_alerta","mensagem")};
        await using var c=factory.CreateConnection();
        var dateColumn=area switch { "Agenda"=>"prazo_at", "Importacoes"=>"iniciada_at", "Auditoria"=>"ocorrido_at", _=>"created_at" };
        var statusColumn=area=="Auditoria" ? "'REGISTRADO'" : "status";
        // Table and expression come exclusively from the closed switch above. User input is never interpolated.
        var sql= $"""
select id,{config.Item4} Titulo,'' Contexto,{statusColumn} Status,{dateColumn} Prazo
            from sigov.{config.Item3}
            where tenant_id=@t and entidade_id=@e
              and (@status is null or {statusColumn}=@status)
              and (@busca is null or ({config.Item4}) ilike '%'||@busca||'%')
              and (@de is null or {dateColumn}::date>=@de)
              and (@ate is null or {dateColumn}::date<=@ate)
            order by id desc limit 200
""";
        var rows=(await c.QueryAsync<LicitaProLinha>(new CommandDefinition(sql,new{t,e,status=N(f.Status),busca=N(f.Busca),de=f.De,ate=f.Ate},cancellationToken:ct))).AsList();
        var fornecedores=(await c.QueryAsync<LicitaProOpcao>(new CommandDefinition("select id,nome Texto from sigov.compras_fornecedor where tenant_id=@t and entidade_id=@e and status='ATIVO' order by nome",new{t,e},cancellationToken:ct))).AsList();
        var processos=(await c.QueryAsync<LicitaProOpcao>(new CommandDefinition("select id,numero||'/'||exercicio||' — '||objeto Texto from sigov.compras_processo where tenant_id=@t and entidade_id=@e order by exercicio desc,numero",new{t,e},cancellationToken:ct))).AsList();
        var oportunidades=(await c.QueryAsync<LicitaProOpcao>(new CommandDefinition("select id,numero||' — '||objeto Texto from sigov.compras_licitapro_oportunidade where tenant_id=@t and entidade_id=@e and status in('ABERTA','VINCULADA') and (data_limite is null or data_limite>=current_date) order by data_limite nulls last",new{t,e},cancellationToken:ct))).AsList();
        var contratos=(await c.QueryAsync<LicitaProOpcao>(new CommandDefinition("select id,numero||' — '||objeto Texto from sigov.compras_contrato where tenant_id=@t and entidade_id=@e order by id desc",new{t,e},cancellationToken:ct))).AsList();
        return new(area,config.Item1,config.Item2,f,rows,fornecedores,processos,oportunidades,contratos,new(),new());
    }
    public async Task<long> CriarOportunidadeAsync(long t,long e,long u,string corr,OportunidadeInput i,CancellationToken ct) { if(i.FonteId is null||i.DataPublicacao is null)throw new ArgumentException("Fonte e publicação são obrigatórias."); await using var c=factory.CreateConnection(); var id=await c.ExecuteScalarAsync<long>(new CommandDefinition("insert into sigov.compras_licitapro_oportunidade(tenant_id,entidade_id,fonte_id,identificador_externo,numero,objeto,modalidade,data_publicacao,data_limite,created_by) select @t,@e,@FonteId,@IdentificadorExterno,@Numero,@Objeto,@Modalidade,@DataPublicacao,@DataLimite,@u where exists(select 1 from sigov.compras_licitapro_fonte where id=@FonteId and tenant_id=@t and entidade_id=@e) on conflict(tenant_id,entidade_id,fonte_id,identificador_externo) do update set numero=excluded.numero,objeto=excluded.objeto,modalidade=excluded.modalidade,data_publicacao=excluded.data_publicacao,data_limite=excluded.data_limite,versao_fonte=sigov.compras_licitapro_oportunidade.versao_fonte+1,updated_at=now(),updated_by=@u returning id",new{t,e,u,i.FonteId,i.IdentificadorExterno,i.Numero,i.Objeto,i.Modalidade,i.DataPublicacao,i.DataLimite},cancellationToken:ct)); if(id==0)throw new ArgumentException("Fonte inválida."); await Audit(c,t,e,"OPORTUNIDADE",id,"SALVAR",u,corr,null,ct); return id; }
    public async Task VincularAsync(long t,long e,long u,string corr,long id,long processoId,CancellationToken ct) { await using var c=factory.CreateConnection(); var n=await c.ExecuteAsync(new CommandDefinition("update sigov.compras_licitapro_oportunidade o set processo_id=@p,status='VINCULADA',updated_at=now(),updated_by=@u where o.id=@id and o.tenant_id=@t and o.entidade_id=@e and exists(select 1 from sigov.compras_processo where id=@p and tenant_id=@t and entidade_id=@e)",new{t,e,u,id,p=processoId},cancellationToken:ct)); if(n!=1)throw new ArgumentException("Oportunidade ou processo não disponível."); await Audit(c,t,e,"OPORTUNIDADE",id,"VINCULAR_PROCESSO",u,corr,new{processoId},ct); }
    public async Task<long> CriarDocumentoAsync(long t,long e,long u,string corr,DocumentoFornecedorInput i,CancellationToken ct) { await using var c=factory.CreateConnection(); var id=await c.ExecuteScalarAsync<long>(new CommandDefinition("insert into sigov.compras_licitapro_documento(tenant_id,entidade_id,fornecedor_id,tipo,titulo,validade,referencia_documental,status,aprovado_por,aprovado_at,created_by) select @t,@e,@FornecedorId,@Tipo,@Titulo,@Validade,@ReferenciaDocumental,@Status,case when @Status='APROVADO' then @u end,case when @Status='APROVADO' then now() end,@u where exists(select 1 from sigov.compras_fornecedor where id=@FornecedorId and tenant_id=@t and entidade_id=@e) returning id",new{t,e,u,i.FornecedorId,i.Tipo,i.Titulo,i.Validade,i.ReferenciaDocumental,i.Status},cancellationToken:ct)); if(id==0)throw new ArgumentException("Fornecedor inválido."); await Audit(c,t,e,"DOCUMENTO",id,i.Status=="APROVADO"?"APROVAR":"CRIAR",u,corr,null,ct); return id; }
    public async Task<long> CriarAgendaAsync(long t,long e,long u,string corr,AgendaPropostaInput i,CancellationToken ct) { await using var c=factory.CreateConnection(); var id=await c.ExecuteScalarAsync<long?>(new CommandDefinition("insert into sigov.compras_licitapro_agenda(tenant_id,entidade_id,oportunidade_id,processo_id,fornecedor_id,contrato_id,titulo,prazo_at,responsavel_id,created_by) select @t,@e,@OportunidadeId,@ProcessoId,@FornecedorId,@ContratoId,@Titulo,@PrazoAt,@u,@u from sigov.compras_licitapro_oportunidade o where o.id=@OportunidadeId and o.tenant_id=@t and o.entidade_id=@e and o.status in('ABERTA','VINCULADA') and (o.data_limite is null or o.data_limite>=current_date) and exists(select 1 from sigov.compras_processo where id=@ProcessoId and tenant_id=@t and entidade_id=@e) and exists(select 1 from sigov.compras_fornecedor where id=@FornecedorId and tenant_id=@t and entidade_id=@e and status='ATIVO') and (@ContratoId is null or exists(select 1 from sigov.compras_contrato where id=@ContratoId and tenant_id=@t and entidade_id=@e)) returning id",new{t,e,u,i.OportunidadeId,i.ProcessoId,i.FornecedorId,i.ContratoId,i.Titulo,i.PrazoAt},cancellationToken:ct)); if(id is null)throw new InvalidOperationException("Oportunidade indisponível, vencida ou relacionamentos inválidos."); await Audit(c,t,e,"AGENDA",id.Value,"CRIAR",u,corr,null,ct); return id.Value; }
    public async Task<byte[]> ExportarAsync(long t,long e,long u,string corr,string area,LicitaProFiltro f,CancellationToken ct) {
        string[] headers;
        IEnumerable<string[]> rows;
        if(area=="oportunidades") { headers=["Número","Objeto","Modalidade","Fonte","Status","Data limite"]; rows=(await OportunidadesAsync(t,e,f,ct)).Select(x=>new[]{x.Numero,x.Objeto,x.Modalidade,x.Fonte,x.Status,x.DataLimite?.ToString("yyyy-MM-dd")??""}); }
        else { headers=["Registro","Contexto","Status","Prazo"]; var workspaceArea = area switch{"documentos"=>"Documentos","checklists"=>"Checklists","agenda"=>"Agenda","auditoria"=>"Auditoria",_=>"Alertas"}; rows=(await WorkspaceAsync(t,e,workspaceArea,f,ct)).Linhas.Select(x=>new[]{x.Titulo,x.Contexto,x.Status,x.Prazo?.ToString("O")??""}); }
        var sb=new StringBuilder().AppendLine(string.Join(';',headers.Select(Csv))); foreach(var row in rows)sb.AppendLine(string.Join(';',row.Select(Csv))); await using var c=factory.CreateConnection(); await Audit(c,t,e,"RELATORIO",null,"EXPORTAR_CSV",u,corr,new{area},ct); return Encoding.UTF8.GetPreamble().Concat(Encoding.UTF8.GetBytes(sb.ToString())).ToArray(); }
    static string Csv(string? value) { var s=value??""; if(s.Length>0&&"=+-@".Contains(s[0]))s="'"+s; return '"'+s.Replace("\"","\"\"")+'"'; }
    static string? N(string? x)=>string.IsNullOrWhiteSpace(x)?null:x.Trim();
    static Task Audit(System.Data.IDbConnection c,long t,long e,string entity,long? id,string action,long u,string corr,object? details,CancellationToken ct)=>c.ExecuteAsync(new CommandDefinition("insert into sigov.compras_licitapro_auditoria(tenant_id,entidade_id,entidade,registro_id,acao,detalhes,usuario_id,correlation_id) values(@t,@e,@entity,@id,@action,cast(@json as jsonb),@u,@corr)",new{t,e,entity,id,action,json=details is null?null:JsonSerializer.Serialize(details),u,corr},cancellationToken:ct));
}
