using Sigov.Application.Common;
namespace Sigov.Application.Saude.Avancada;
public sealed record SaudeAvancadaContext(long TenantId,long? EntidadeId,long? ExercicioId,long? UsuarioId,string CorrelationId);
public sealed record SaudeAvancadaFiltro(string? Status=null,string? Tipo=null,long? UnidadeSaudeId=null,long? PacienteId=null,int Pagina=1,int Tamanho=30);
public sealed record SaudeAvancadaRegistroDto(long Id,string? Codigo,string? Tipo,string Status,string? Descricao,string? Gravidade,decimal? Latitude,decimal? Longitude,decimal? Quantidade,DateTimeOffset CreatedAt);
public sealed record SaudeAvancadaOperacaoRequest(long? UnidadeSaudeId,long? PacienteId,long? ProfissionalId,long? AcsId,long? DomicilioId,long? ReferenciaId,long? LoteId,long? DispositivoId,string? Codigo,string? ChaveOffline,string Origem,string? Tipo,string Status,string? Gravidade,string? Descricao,string? Justificativa,decimal? Latitude,decimal? Longitude,decimal? Quantidade,decimal? SaldoMinimo,DateTimeOffset? DataReferencia,DateOnly? Validade,IReadOnlyDictionary<string,object?>? Dados);
public sealed record SaudeAvancadaDashboardDto(long Total,long Pendentes,long Alertas,long Georreferenciados,IReadOnlyCollection<SaudeAvancadaRegistroDto> Recentes);
public sealed record SaudeAcsOfflineDashboardDto(long LotesPendentes,long Sincronizados,long Inconsistencias,long DispositivosAtivos);
public sealed record SaudeAcsSincronizacaoResultadoDto(long LoteId,string Status,int TotalItens,int Inconsistencias,string CorrelationId);
public sealed record SaudeAcsCampoDashboardDto(long Domicilios,long Individuos,long Visitas,long OcorrenciasCriticas);
public sealed record SaudeOperacaoDashboardDto(long VacinasAplicadas,long PendenciasVacinais,long EstoqueBaixo,long RegulacoesCriticas);
public sealed record SaudeRetaguardaDashboardDto(long ProducaoAcs,long PontosMapa,long LotesEsusPreparatorios,long ChamadosSla);
public interface ISaudeAvancadaRepository { Task<PagedResult<SaudeAvancadaRegistroDto>> ListarAsync(long tenantId,string recurso,SaudeAvancadaFiltro filtro,CancellationToken ct); Task<SaudeAvancadaRegistroDto?> ObterAsync(long tenantId,string recurso,long id,CancellationToken ct); Task<long> CriarAsync(SaudeAvancadaContext contexto,string recurso,SaudeAvancadaOperacaoRequest request,CancellationToken ct); Task<bool> AlterarStatusAsync(SaudeAvancadaContext contexto,string recurso,long id,string status,string? justificativa,CancellationToken ct); Task<SaudeAvancadaDashboardDto> DashboardAsync(long tenantId,string recurso,CancellationToken ct); Task<byte[]> ExportarCsvAsync(long tenantId,string recurso,CancellationToken ct); }
public interface ISaudeAcsOfflineRepository:ISaudeAvancadaRepository{} public interface ISaudeAcsOfflineService:ISaudeAvancadaRepository{} public interface ISaudeAcsSincronizacaoService:ISaudeAcsOfflineService{} public interface ISaudeAcsGeorreferenciaService:ISaudeAcsOfflineService{} public interface ISaudeAcsRelatorioService:ISaudeAcsOfflineService{}
public interface ISaudeAcsCampoRepository:ISaudeAvancadaRepository{} public interface ISaudeAcsCampoService:ISaudeAvancadaRepository{} public interface ISaudeDomicilioService:ISaudeAcsCampoService{} public interface ISaudeVisitaDomiciliarService:ISaudeAcsCampoService{} public interface ISaudeAtividadeColetivaService:ISaudeAcsCampoService{} public interface ISaudeOcorrenciaCampoService:ISaudeAcsCampoService{}
public interface ISaudeOperacaoRepository:ISaudeAvancadaRepository{} public interface ISaudeVacinacaoAvancadaService:ISaudeAvancadaRepository{} public interface ISaudeFarmaciaAvancadaService:ISaudeAvancadaRepository{} public interface ISaudeRegulacaoAvancadaService:ISaudeAvancadaRepository{} public interface ISaudeOperacaoDashboardService:ISaudeAvancadaRepository{}
public interface ISaudeRetaguardaRepository:ISaudeAvancadaRepository{} public interface ISaudeRetaguardaService:ISaudeAvancadaRepository{} public interface ISaudeEsusPreparatorioService:ISaudeAvancadaRepository{} public interface ISaudeSlaService:ISaudeAvancadaRepository{} public interface ISaudeSuporteService:ISaudeAvancadaRepository{} public interface ISaudeIndicadoresService:ISaudeAvancadaRepository{}
