using System.Globalization;
using System.Text;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Sigov.Application.ComprasEmpresariais;

namespace Sigov.Api.Controllers.ComprasEmpresariais;

[ApiController,Authorize,Route("api/compras-empresariais")]
public sealed class ComprasEmpresariaisController(IFornecedorApplicationService fornecedores,IRequisicaoCompraApplicationService requisicoes,IComprasDashboardApplicationService dashboard,IRecebimentoCompraApplicationService recebimentos,IDivergenciaRecebimentoApplicationService divergencias,IDevolucaoCompraApplicationService devolucoes,IAprovacaoRequisicaoApplicationService aprovacoes,ICotacaoCompraApplicationService cotacoes,ILogger<ComprasEmpresariaisController> log):ControllerBase
{
 private ComprasContext Contexto(){if(!Guid.TryParse(User.FindFirst("enterprise_tenant_id")?.Value??User.FindFirst("tenant_id")?.Value,out var t)||t==Guid.Empty)throw new UnauthorizedAccessException("Tenant não resolvido.");if(!Guid.TryParse(User.FindFirst("sub")?.Value,out var u)||u==Guid.Empty)throw new UnauthorizedAccessException("Usuário não resolvido.");return new(t,u,HttpContext.TraceIdentifier);}
 private string Key()=>Request.Headers["Idempotency-Key"].ToString();
 [HttpGet("dashboard"),Authorize(Policy="compras_empresariais.dashboard.visualizar")]public async Task<IActionResult> Dashboard(CancellationToken ct){try{return Ok(await dashboard.ObterAsync(Contexto(),ct));}catch(Exception ex){return Falha(ex);}}
 [HttpGet("fornecedores"),Authorize(Policy="compras_empresariais.fornecedores.visualizar")]public async Task<IActionResult> Fornecedores([FromQuery]FornecedorFiltro filtro,CancellationToken ct){try{return Ok(await fornecedores.ListarAsync(Contexto(),filtro,ct));}catch(Exception ex){return Falha(ex);}}
 [HttpGet("fornecedores/{id:guid}"),Authorize(Policy="compras_empresariais.fornecedores.visualizar")]public async Task<IActionResult> Fornecedor(Guid id,CancellationToken ct){try{var item=await fornecedores.ObterAsync(Contexto(),id,ct);return item is null?NotFound():Ok(item);}catch(Exception ex){return Falha(ex);}}
 [HttpPost("fornecedores"),Authorize(Policy="compras_empresariais.fornecedores.criar")]public async Task<IActionResult> CriarFornecedor(CriarFornecedorRequest request,CancellationToken ct){try{var id=await fornecedores.CriarAsync(Contexto(),request,Key(),ct);return CreatedAtAction(nameof(Fornecedor),new{id},new{id});}catch(Exception ex){return Falha(ex);}}
 [HttpPost("fornecedores/{id:guid}/status"),Authorize(Policy="compras_empresariais.fornecedores.editar")]public async Task<IActionResult> Status(Guid id,AlterarStatusRequest request,CancellationToken ct){try{await fornecedores.AlterarStatusAsync(Contexto(),id,request,ct);return NoContent();}catch(Exception ex){return Falha(ex);}}
 [HttpPost("fornecedores/{id:guid}/contatos"),Authorize(Policy="compras_empresariais.fornecedores.editar")]public async Task<IActionResult> Contato(Guid id,AdicionarContatoRequest request,CancellationToken ct){try{await fornecedores.AdicionarContatoAsync(Contexto(),id,request,Key(),ct);return NoContent();}catch(Exception ex){return Falha(ex);}}
 [HttpPost("fornecedores/{id:guid}/enderecos"),Authorize(Policy="compras_empresariais.fornecedores.editar")]public async Task<IActionResult> Endereco(Guid id,AdicionarEnderecoRequest request,CancellationToken ct){try{await fornecedores.AdicionarEnderecoAsync(Contexto(),id,request,Key(),ct);return NoContent();}catch(Exception ex){return Falha(ex);}}
 [HttpPost("fornecedores/{id:guid}/documentos"),Authorize(Policy="compras_empresariais.fornecedores.editar")]public async Task<IActionResult> Documento(Guid id,AdicionarDocumentoRequest request,CancellationToken ct){try{await fornecedores.AdicionarDocumentoAsync(Contexto(),id,request,Key(),ct);return NoContent();}catch(Exception ex){return Falha(ex);}}
 [HttpGet("requisicoes"),Authorize(Policy="compras_empresariais.requisicoes.visualizar")]public async Task<IActionResult> Requisicoes([FromQuery]RequisicaoFiltro filtro,CancellationToken ct=default){try{return Ok(await requisicoes.ListarAsync(Contexto(),filtro,ct));}catch(Exception ex){return Falha(ex);}}
 [HttpGet("requisicoes/{id:guid}"),Authorize(Policy="compras_empresariais.requisicoes.visualizar")]public async Task<IActionResult> Requisicao(Guid id,CancellationToken ct){try{var item=await requisicoes.ObterAsync(Contexto(),id,ct);return item is null?NotFound():Ok(item);}catch(Exception ex){return Falha(ex);}}
 [HttpPost("requisicoes"),Authorize(Policy="compras_empresariais.requisicoes.criar")]public async Task<IActionResult> CriarRequisicao(CriarRequisicaoRequest request,CancellationToken ct){try{var id=await requisicoes.CriarAsync(Contexto(),request,Key(),ct);return Created($"/api/compras-empresariais/requisicoes/{id}",new{id});}catch(Exception ex){return Falha(ex);}}
 [HttpPut("requisicoes/{id:guid}"),Authorize(Policy="compras_empresariais.requisicoes.editar")]public async Task<IActionResult> AtualizarRequisicao(Guid id,AtualizarRequisicaoRequest request,CancellationToken ct){try{await requisicoes.AtualizarAsync(Contexto(),id,request,ct);return NoContent();}catch(Exception ex){return Falha(ex);}}
 [HttpPost("requisicoes/{id:guid}/enviar"),Authorize(Policy="compras_empresariais.requisicoes.enviar")]public async Task<IActionResult> Enviar(Guid id,[FromQuery]long version,CancellationToken ct){try{return Ok(await requisicoes.EnviarAsync(Contexto(),id,version,Key(),ct));}catch(Exception ex){return Falha(ex);}}
 [HttpGet("aprovacoes"),Authorize(Policy="compras_empresariais.aprovacoes.visualizar")]public async Task<IActionResult> FilaAprovacoes([FromQuery]int pagina=1,[FromQuery]int tamanho=20,[FromQuery]string? busca=null,[FromQuery]string? urgencia=null,CancellationToken ct=default){try{return Ok(await aprovacoes.ListarFilaAsync(Contexto(),pagina,tamanho,busca,urgencia,ct));}catch(Exception ex){return Falha(ex);}}
 [HttpPost("aprovacoes/{etapaId:guid}/decidir"),Authorize(Policy="compras_empresariais.aprovacoes.aprovar")]public async Task<IActionResult> DecidirAprovacao(Guid etapaId,[FromBody]AprovacaoDecisaoRequest? request,CancellationToken ct){var r=request??new AprovacaoDecisaoRequest(null,null,0,null);var chave=string.IsNullOrWhiteSpace(r.IdempotencyKey)?Key():r.IdempotencyKey;try{return Ok(await aprovacoes.DecidirAsync(Contexto(),etapaId,r with{IdempotencyKey=chave},ct));}catch(Exception ex){return Falha(ex);}}
 [HttpPost("requisicoes/{id:guid}/reavaliar-encaminhamento"),Authorize(Policy="compras_empresariais.aprovacoes.aprovar")]public async Task<IActionResult> ReavaliarEncaminhamento(Guid id,[FromBody]ReavaliarEncaminhamentoRequest? request,CancellationToken ct){var r=request??new ReavaliarEncaminhamentoRequest(null,null);var chave=string.IsNullOrWhiteSpace(r.IdempotencyKey)?Key():r.IdempotencyKey;try{return Ok(await aprovacoes.ReavaliarEncaminhamentoAsync(Contexto(),id,r with{IdempotencyKey=chave},ct));}catch(Exception ex){return Falha(ex);}}
  [HttpGet("configuracao/politica"),Authorize(Policy="compras_empresariais.configuracao.gerenciar")]public async Task<IActionResult> ObterPolitica(CancellationToken ct){try{var item=await aprovacoes.ObterPoliticaAsync(Contexto(),ct);return item is null?NotFound():Ok(item);}catch(Exception ex){return Falha(ex);}}
 [HttpPut("configuracao/politica"),Authorize(Policy="compras_empresariais.configuracao.gerenciar")]public async Task<IActionResult> SalvarPolitica([FromBody]SalvarPoliticaRequest? request,CancellationToken ct){var r=request??new SalvarPoliticaRequest(null,Array.Empty<NivelPoliticaRequest>());try{return Ok(await aprovacoes.SalvarPoliticaAsync(Contexto(),r,Key(),ct));}catch(Exception ex){return Falha(ex);}}
 [HttpGet("relatorios/aprovacoes.csv"),Authorize(Policy="compras_empresariais.relatorios.visualizar")]public async Task<IActionResult> RelatorioAprovacoesCsv(CancellationToken ct){try{var linhas=new List<string>{"Numero;Ciclo;Etapa;Alcada;SituacaoEtapa;Aprovador;StatusRequisicao;Total;CriadaEm;DecididaEm;Motivo"};foreach(var row in await ColetarRelatorioAprovacoesAsync(ct))linhas.Add(string.Join(";",Csv(row.Numero),Csv(row.Ciclo.ToString(CultureInfo.InvariantCulture)),Csv(row.Etapa.ToString(CultureInfo.InvariantCulture)),Csv(row.Alcada.ToString("0.00",CultureInfo.InvariantCulture)),Csv(row.SituacaoEtapa),Csv(row.AprovadorSub),Csv(row.StatusRequisicao),Csv(row.Total.ToString("0.00",CultureInfo.InvariantCulture)),row.CriadaEm.ToString("O"),row.DecididaEm?.ToString("O")??"",Csv(row.Motivo)));return File(Encoding.UTF8.GetBytes(string.Join("\r\n",linhas)),"text/csv; charset=utf-8",$"aprovacoes-{DateTime.Now:yyyyMMddHHmmss}.csv");}catch(Exception ex){return Falha(ex);}}
 private async Task<IReadOnlyList<AprovacaoRelatorioLinha>> ColetarRelatorioAprovacoesAsync(CancellationToken ct){var rows=new List<AprovacaoRelatorioLinha>();for(var page=1;;page++){var data=await aprovacoes.ListarRelatorioAsync(Contexto(),page,100,ct);rows.AddRange(data.Items);if(rows.Count>50000)throw new InvalidOperationException("A exportação excede o limite explícito de 50.000 registros; refine os filtros.");if(!data.HasNextPage)break;}return rows;}
 private static string Csv(string? v){v=v?.Replace("\r"," ").Replace("\n"," ").Replace(";","/");return string.IsNullOrEmpty(v)?string.Empty:v;}
 private ObjectResult Falha(Exception ex){if(ex is ComprasConcurrencyException)return StatusCode(409,new{status=409,title="Conflito",detail=ex.Message});if(ex is KeyNotFoundException)return NotFound(new{status=404,title="Não encontrado",detail=ex.Message});if(ex is UnauthorizedAccessException)return Unauthorized(new{status=401,title="Não autorizado",detail=ex.Message});if(ex is ArgumentException)return BadRequest(new{status=400,title="Requisição inválida",detail=ex.Message});if(ex is InvalidOperationException)return StatusCode(422,new{status=422,title="Situação inválida",detail=ex.Message});log.LogError(ex,"Falha inesperada em {Metodo} {Rota}.",HttpContext.Request.Method,HttpContext.Request.Path);return StatusCode(500,new{status=500,title="Falha inesperada no servidor"});}
 [HttpGet("recebimentos"),Authorize(Policy="compras_empresariais.recebimentos.visualizar")]public async Task<IActionResult> Recebimentos([FromQuery]RecebimentoFiltro filtro,CancellationToken ct){try{return Ok(await recebimentos.ListarAsync(Contexto(),filtro,ct));}catch(Exception ex){return Falha(ex);}}
 [HttpGet("recebimentos/{id:guid}"),Authorize(Policy="compras_empresariais.recebimentos.visualizar")]public async Task<IActionResult> Recebimento(Guid id,CancellationToken ct){try{var item=await recebimentos.ObterAsync(Contexto(),id,ct);return item is null?NotFound():Ok(item);}catch(Exception ex){return Falha(ex);}}
 [HttpPost("recebimentos/{id:guid}/inspecao"),Authorize(Policy="compras_empresariais.recebimentos.inspecionar")]public async Task<IActionResult> Inspecionar(Guid id,ConcluirInspecaoRequest request,CancellationToken ct){try{return Ok(await recebimentos.ConcluirInspecaoAsync(Contexto(),id,request,ct));}catch(Exception ex){return Falha(ex);}}
 [HttpGet("divergencias"),Authorize(Policy="compras_empresariais.divergencias.visualizar")]public async Task<IActionResult> Divergencias([FromQuery]DivergenciaFiltro filtro,CancellationToken ct){try{return Ok(await divergencias.ListarAsync(Contexto(),filtro,ct));}catch(Exception ex){return Falha(ex);}}
 [HttpGet("divergencias/{id:long}"),Authorize(Policy="compras_empresariais.divergencias.visualizar")]public async Task<IActionResult> Divergencia(long id,CancellationToken ct){try{var item=await divergencias.ObterAsync(Contexto(),id,ct);return item is null?NotFound():Ok(item);}catch(Exception ex){return Falha(ex);}}
 [HttpGet("divergencias/responsaveis"),Authorize(Policy="compras_empresariais.divergencias.atribuir")]public async Task<IActionResult> Responsaveis(string? busca,int pagina=1,int tamanho=20,CancellationToken ct=default){try{return Ok(await divergencias.PesquisarResponsaveisAsync(Contexto(),busca,pagina,tamanho,ct));}catch(Exception ex){return Falha(ex);}}
 [HttpPost("divergencias/{id:long}/responsavel"),Authorize(Policy="compras_empresariais.divergencias.atribuir")]public async Task<IActionResult> Atribuir(long id,AtribuirDivergenciaRequest request,CancellationToken ct){try{return Ok(await divergencias.AtribuirAsync(Contexto(),id,request with{IdempotencyKey=Key()},ct));}catch(Exception ex){return Falha(ex);}}
 [HttpPost("divergencias/{id:long}/andamentos"),Authorize(Policy="compras_empresariais.divergencias.tratar")]public async Task<IActionResult> Andamento(long id,RegistrarAndamentoDivergenciaRequest request,CancellationToken ct){try{return Ok(await divergencias.RegistrarAndamentoAsync(Contexto(),id,request with{IdempotencyKey=Key()},ct));}catch(Exception ex){return Falha(ex);}}
 [HttpPost("divergencias/{id:long}/encerramento"),Authorize(Policy="compras_empresariais.divergencias.encerrar")]public async Task<IActionResult> Encerrar(long id,EncerrarDivergenciaRequest request,CancellationToken ct){try{return Ok(await divergencias.EncerrarAsync(Contexto(),id,request with{IdempotencyKey=Key()},ct));}catch(Exception ex){return Falha(ex);}}
 [HttpGet("devolucoes"),Authorize(Policy="compras_empresariais.devolucoes.visualizar")]public async Task<IActionResult> Devolucoes([FromQuery]DevolucaoFiltro filtro,CancellationToken ct){try{return Ok(await devolucoes.ListarAsync(Contexto().TenantId,filtro,ct));}catch(Exception ex){return Falha(ex);}}
 [HttpGet("devolucoes/{id:long}"),Authorize(Policy="compras_empresariais.devolucoes.visualizar")]public async Task<IActionResult> Devolucao(long id,CancellationToken ct){try{var x=await devolucoes.ObterAsync(Contexto().TenantId,id,ct);return x is null?NotFound():Ok(x);}catch(Exception ex){return Falha(ex);}}
 [HttpGet("devolucoes/origens/{recebimentoId:guid}"),Authorize(Policy="compras_empresariais.devolucoes.criar")]public async Task<IActionResult> OrigemDevolucao(Guid recebimentoId,CancellationToken ct){try{var x=await devolucoes.ObterOrigemAsync(Contexto().TenantId,recebimentoId,ct);return x is null?NotFound():Ok(x);}catch(Exception ex){return Falha(ex);}}
 [HttpPost("devolucoes"),Authorize(Policy="compras_empresariais.devolucoes.criar")]public async Task<IActionResult> CriarDevolucao(CriarDevolucaoRequest request,CancellationToken ct){try{var x=await devolucoes.CriarAsync(Contexto(),request with{IdempotencyKey=Key()},ct);return Created($"/api/compras-empresariais/devolucoes/{x.Id}",x);}catch(Exception ex){return Falha(ex);}}
 [HttpPut("devolucoes/{id:long}"),Authorize(Policy="compras_empresariais.devolucoes.editar")]public async Task<IActionResult> EditarDevolucao(long id,EditarDevolucaoRequest request,CancellationToken ct){try{return Ok(await devolucoes.EditarAsync(Contexto(),id,request with{IdempotencyKey=Key()},ct));}catch(Exception ex){return Falha(ex);}}
 [HttpPost("devolucoes/{id:long}/expedicao"),Authorize(Policy="compras_empresariais.devolucoes.expedir")]public async Task<IActionResult> ExpedirDevolucao(long id,ExpedirDevolucaoRequest request,CancellationToken ct){try{return Ok(await devolucoes.ExpedirAsync(Contexto(),id,request with{IdempotencyKey=Key()},ct));}catch(Exception ex){return Falha(ex);}}
 [HttpPost("devolucoes/{id:long}/entrega"),Authorize(Policy="compras_empresariais.devolucoes.entregar")]public async Task<IActionResult> EntregarDevolucao(long id,EntregarDevolucaoRequest request,CancellationToken ct){try{return Ok(await devolucoes.EntregarAsync(Contexto(),id,request with{IdempotencyKey=Key()},ct));}catch(Exception ex){return Falha(ex);}}
 [HttpPost("devolucoes/{id:long}/cancelamento"),Authorize(Policy="compras_empresariais.devolucoes.editar")]public async Task<IActionResult> CancelarDevolucao(long id,CancelarDevolucaoRequest request,CancellationToken ct){try{return Ok(await devolucoes.CancelarAsync(Contexto(),id,request with{IdempotencyKey=Key()},ct));}catch(Exception ex){return Falha(ex);}}
  [HttpGet("cotacoes"),Authorize(Policy="compras_empresariais.cotacoes.visualizar")]public async Task<IActionResult> Cotacoes([FromQuery]CotacaoFiltro filtro,CancellationToken ct=default){try{return Ok(await cotacoes.ListarAsync(Contexto(),filtro,ct));}catch(Exception ex){return Falha(ex);}}
  [HttpGet("cotacoes/elegiveis"),Authorize(Policy="compras_empresariais.cotacoes.visualizar")]public async Task<IActionResult> CotacoesElegiveis([FromQuery]string? busca,[FromQuery]int pagina=1,[FromQuery]int tamanho=20,CancellationToken ct=default){try{return Ok(await cotacoes.ListarElegiveisAsync(Contexto(),busca,pagina,tamanho,ct));}catch(Exception ex){return Falha(ex);}}
  [HttpGet("cotacoes/elaboracao/{requisicaoId:guid}"),Authorize(Policy="compras_empresariais.cotacoes.visualizar")]public async Task<IActionResult> CotacaoElaboracao(Guid requisicaoId,CancellationToken ct){try{var item=await cotacoes.ObterElaboracaoAsync(Contexto(),requisicaoId,ct);return item is null?NotFound():Ok(item);}catch(Exception ex){return Falha(ex);}}
  [HttpGet("cotacoes/produtos"),Authorize(Policy="compras_empresariais.cotacoes.visualizar")]public async Task<IActionResult> CotacaoProdutos([FromQuery]string? busca,[FromQuery]int limite=50,CancellationToken ct=default){try{return Ok(await cotacoes.PesquisarProdutosAsync(Contexto(),busca,limite,ct));}catch(Exception ex){return Falha(ex);}}
  [HttpPost("cotacoes"),Authorize(Policy="compras_empresariais.cotacoes.criar")]public async Task<IActionResult> CriarCotacao(CriarCotacaoRequest request,CancellationToken ct){try{var x=await cotacoes.CriarAsync(Contexto(),request,Key(),ct);return Created($"/api/compras-empresariais/cotacoes/{x.Id}",x);}catch(Exception ex){return Falha(ex);}}
  [HttpGet("cotacoes/{id:guid}"),Authorize(Policy="compras_empresariais.cotacoes.visualizar")]public async Task<IActionResult> CotacaoDetalhe(Guid id,CancellationToken ct){try{var item=await cotacoes.ObterAsync(Contexto(),id,ct);return item is null?NotFound():Ok(item);}catch(Exception ex){return Falha(ex);}}
  [HttpGet("cotacoes/{id:guid}/comparativo"),Authorize(Policy="compras_empresariais.cotacoes.visualizar")]public async Task<IActionResult> CotacaoComparativo(Guid id,CancellationToken ct){try{var item=await cotacoes.ObterComparativoAsync(Contexto(),id,ct);return item is null?NotFound():Ok(item);}catch(Exception ex){return Falha(ex);}}
  [HttpPost("cotacoes/{id:guid}/respostas"),Authorize(Policy="compras_empresariais.cotacoes.enviar")]public async Task<IActionResult> RegistrarResposta(Guid id,RegistrarRespostaRequest request,CancellationToken ct){try{return Ok(await cotacoes.RegistrarRespostaAsync(Contexto(),id,request,Key(),ct));}catch(Exception ex){return Falha(ex);}}
  [HttpPost("cotacoes/{id:guid}/selecionar"),Authorize(Policy="compras_empresariais.cotacoes.julgar")]public async Task<IActionResult> SelecionarCotacao(Guid id,SelecionarItensRequest request,CancellationToken ct){try{return Ok(await cotacoes.SelecionarAsync(Contexto(),id,request,Key(),ct));}catch(Exception ex){return Falha(ex);}}
  [HttpPost("cotacoes/{id:guid}/encerrar"),Authorize(Policy="compras_empresariais.cotacoes.julgar")]public async Task<IActionResult> EncerrarCotacao(Guid id,EncerrarCotacaoRequest request,CancellationToken ct){try{return Ok(await cotacoes.EncerrarAsync(Contexto(),id,request,Key(),ct));}catch(Exception ex){return Falha(ex);}}
  [HttpGet("pedidos"),Authorize(Policy="compras_empresariais.pedidos.visualizar")]public async Task<IActionResult> Pedidos([FromQuery]PedidoFiltro filtro,CancellationToken ct=default){try{return Ok(await cotacoes.ListarPedidosAsync(Contexto(),filtro,ct));}catch(Exception ex){return Falha(ex);}}
  [HttpGet("pedidos/{id:guid}"),Authorize(Policy="compras_empresariais.pedidos.visualizar")]public async Task<IActionResult> PedidoDetalhe(Guid id,CancellationToken ct){try{var item=await cotacoes.ObterPedidoAsync(Contexto(),id,ct);return item is null?NotFound():Ok(item);}catch(Exception ex){return Falha(ex);}}
  [HttpPost("pedidos/{id:guid}/encerrar"),Authorize(Policy="compras_empresariais.pedidos.emitir")]public async Task<IActionResult> EncerrarPedido(Guid id,EncerrarPedidoRequest request,CancellationToken ct){try{return Ok(await cotacoes.EncerrarPedidoAsync(Contexto(),id,request,Key(),ct));}catch(Exception ex){return Falha(ex);}}
  [HttpPost("pedidos/{id:guid}/cancelar"),Authorize(Policy="compras_empresariais.pedidos.cancelar")]public async Task<IActionResult> CancelarPedido(Guid id,CancelarPedidoRequest request,CancellationToken ct){try{return Ok(await cotacoes.CancelarPedidoAsync(Contexto(),id,request,Key(),ct));}catch(Exception ex){return Falha(ex);}}
  [HttpGet("recebimentos/pedidos/{pedidoId:guid}"),Authorize(Policy="compras_empresariais.recebimentos.registrar")]public async Task<IActionResult> RecebimentoParaPedido(Guid pedidoId,CancellationToken ct){try{var item=await recebimentos.ObterPedidoAsync(Contexto(),pedidoId,ct);return item is null?NotFound():Ok(item);}catch(Exception ex){return Falha(ex);}}

}
