using System.Text;
using Sigov.Application.Common;
using Sigov.Application.Social;

namespace Sigov.Infrastructure.Social;

public sealed class SocialRepository : ISocialUnidadeRepository, ISocialFamiliaRepository, ISocialPessoaRepository, ISocialCadastroRepository, ISocialProgramaRepository, ISocialBeneficioRepository, ISocialAtendimentoRepository, ISocialVisitaRepository, ISocialParecerRepository, ISocialAcompanhamentoRepository, ISocialVigilanciaRepository, ISocialDashboardRepository, ISocialExportacaoRepository, ISocialSequencialService
{
    private static long _id=1; private static long Next()=>Interlocked.Increment(ref _id);
    public Task<PagedResult<SocialUnidadeResponse>> ListarAsync(long t,long e,SocialUnidadeFiltro f,CancellationToken ct)=>Task.FromResult(PagedResult<SocialUnidadeResponse>.Empty(f.Page,f.PageSize));
    public Task<SocialUnidadeResponse?> ObterAsync(long t,long e,long id,CancellationToken ct)=>Task.FromResult<SocialUnidadeResponse?>(new(id,"***","Unidade Social","CRAS","ATIVA",true));
    public Task<long> CriarAsync(SocialContexto c,SocialUnidadeCreateRequest r,CancellationToken ct)=>Task.FromResult(Next()); public Task AtualizarAsync(SocialContexto c,long id,SocialUnidadeUpdateRequest r,CancellationToken ct)=>Task.CompletedTask; public Task ExcluirAsync(SocialContexto c,long id,CancellationToken ct)=>Task.CompletedTask;
    public Task<PagedResult<SocialFamiliaResponse>> ListarAsync(long t,long e,SocialFamiliaFiltro f,CancellationToken ct)=>Task.FromResult(PagedResult<SocialFamiliaResponse>.Empty(f.Page,f.PageSize));
    public Task<SocialFamiliaResponse?> ObterAsync(long t,long e,long id,CancellationToken ct)=>Task.FromResult<SocialFamiliaResponse?>(new(id,"FAM-****",null,null,null,0,"ATIVA","***"));
    public Task<long> CriarAsync(SocialContexto c,SocialFamiliaCreateRequest r,string codigo,CancellationToken ct)=>Task.FromResult(Next()); public Task AtualizarAsync(SocialContexto c,long id,SocialFamiliaUpdateRequest r,CancellationToken ct)=>Task.CompletedTask; Task ISocialFamiliaRepository.ExcluirAsync(SocialContexto c,long id,CancellationToken ct)=>Task.CompletedTask; public Task<long> AdicionarComposicaoAsync(SocialContexto c,long familiaId,SocialComposicaoFamiliarRequest r,CancellationToken ct)=>Task.FromResult(Next()); public Task<long> RegistrarVulnerabilidadeAsync(SocialContexto c,long familiaId,SocialVulnerabilidadeCreateRequest r,CancellationToken ct)=>Task.FromResult(Next());
    public Task<PagedResult<SocialPessoaResponse>> ListarAsync(long t,long e,SocialPessoaFiltro f,CancellationToken ct)=>Task.FromResult(PagedResult<SocialPessoaResponse>.Empty(f.Page,f.PageSize));
    public Task<SocialPessoaResponse?> ObterAsync(long t,long e,long id,CancellationToken ct)=>Task.FromResult<SocialPessoaResponse?>(new(id,1,null,"***",null,"ATIVA"));
    public Task<long> CriarAsync(SocialContexto c,SocialPessoaCreateRequest r,CancellationToken ct)=>Task.FromResult(Next()); public Task AtualizarAsync(SocialContexto c,long id,SocialPessoaUpdateRequest r,CancellationToken ct)=>Task.CompletedTask; Task ISocialPessoaRepository.ExcluirAsync(SocialContexto c,long id,CancellationToken ct)=>Task.CompletedTask;
    public Task<long> CriarAsync(SocialContexto c,SocialCadastroCreateRequest r,string numero,CancellationToken ct)=>Task.FromResult(Next());
    public Task<PagedResult<SocialProgramaResponse>> ListarAsync(long t,long e,SocialFiltro f,CancellationToken ct)=>Task.FromResult(PagedResult<SocialProgramaResponse>.Empty(f.Page,f.PageSize)); public Task<long> CriarAsync(SocialContexto c,SocialProgramaCreateRequest r,CancellationToken ct)=>Task.FromResult(Next()); public Task AtualizarAsync(SocialContexto c,long id,SocialProgramaCreateRequest r,CancellationToken ct)=>Task.CompletedTask; Task ISocialProgramaRepository.ExcluirAsync(SocialContexto c,long id,CancellationToken ct)=>Task.CompletedTask;
    public Task<PagedResult<SocialBeneficioResponse>> ListarAsync(long t,long e,SocialFiltro f,CancellationToken ct)=>Task.FromResult(PagedResult<SocialBeneficioResponse>.Empty(f.Page,f.PageSize)); public Task<long> CriarAsync(SocialContexto c,SocialBeneficioCreateRequest r,CancellationToken ct)=>Task.FromResult(Next()); public Task AtualizarAsync(SocialContexto c,long id,SocialBeneficioCreateRequest r,CancellationToken ct)=>Task.CompletedTask; Task ISocialBeneficioRepository.ExcluirAsync(SocialContexto c,long id,CancellationToken ct)=>Task.CompletedTask; public Task<PagedResult<SocialBeneficioConcessaoResponse>> ListarConcessoesAsync(long t,long e,SocialFiltro f,CancellationToken ct)=>Task.FromResult(PagedResult<SocialBeneficioConcessaoResponse>.Empty(f.Page,f.PageSize)); public Task<long> ConcederAsync(SocialContexto c,SocialBeneficioConcessaoCreateRequest r,string numero,CancellationToken ct)=>Task.FromResult(Next()); public Task AlterarStatusConcessaoAsync(SocialContexto c,long id,string status,CancellationToken ct)=>Task.CompletedTask;
    public Task<PagedResult<SocialAtendimentoResponse>> ListarAsync(long t,long e,SocialAtendimentoFiltro f,CancellationToken ct)=>Task.FromResult(PagedResult<SocialAtendimentoResponse>.Empty(f.Page,f.PageSize)); public Task<SocialAtendimentoResponse?> ObterAsync(long t,long e,long id,CancellationToken ct)=>Task.FromResult<SocialAtendimentoResponse?>(new(id,"ATSOC-****",null,null,null,DateTimeOffset.UtcNow,"ACOLHIDA","ABERTO")); public Task<long> CriarAsync(SocialContexto c,SocialAtendimentoCreateRequest r,string numero,CancellationToken ct)=>Task.FromResult(Next()); public Task<long> EncaminharAsync(SocialContexto c,long atendimentoId,SocialEncaminhamentoCreateRequest r,CancellationToken ct)=>Task.FromResult(Next());
    public Task<PagedResult<SocialVisitaResponse>> ListarAsync(long t,long e,SocialVisitaFiltro f,CancellationToken ct)=>Task.FromResult(PagedResult<SocialVisitaResponse>.Empty(f.Page,f.PageSize)); public Task<SocialVisitaResponse?> ObterAsync(long t,long e,long id,CancellationToken ct)=>Task.FromResult<SocialVisitaResponse?>(new(id,null,null,DateTimeOffset.UtcNow,"ACOMPANHAMENTO","REALIZADA")); public Task<long> CriarAsync(SocialContexto c,SocialVisitaCreateRequest r,CancellationToken ct)=>Task.FromResult(Next());
    public Task<PagedResult<SocialParecerResponse>> ListarAsync(long t,long e,SocialFiltro f,CancellationToken ct)=>Task.FromResult(PagedResult<SocialParecerResponse>.Empty(f.Page,f.PageSize)); public Task<long> CriarAsync(SocialContexto c,SocialParecerCreateRequest r,CancellationToken ct)=>Task.FromResult(Next());
    public Task<PagedResult<SocialAcompanhamentoResponse>> ListarAsync(long t,long e,SocialFiltro f,CancellationToken ct)=>Task.FromResult(PagedResult<SocialAcompanhamentoResponse>.Empty(f.Page,f.PageSize)); public Task<long> CriarAsync(SocialContexto c,SocialAcompanhamentoCreateRequest r,CancellationToken ct)=>Task.FromResult(Next()); public Task EncerrarAsync(SocialContexto c,long id,CancellationToken ct)=>Task.CompletedTask;
    public Task<PagedResult<object>> ListarIndicadoresAsync(long t,long e,SocialFiltro f,CancellationToken ct)=>Task.FromResult(PagedResult<object>.Empty(f.Page,f.PageSize)); public Task<long> CriarIndicadorAsync(SocialContexto c,SocialVigilanciaIndicadorCreateRequest r,CancellationToken ct)=>Task.FromResult(Next()); public Task<PagedResult<object>> ListarOcorrenciasAsync(long t,long e,SocialFiltro f,CancellationToken ct)=>Task.FromResult(PagedResult<object>.Empty(f.Page,f.PageSize)); public Task<long> CriarOcorrenciaAsync(SocialContexto c,SocialVigilanciaOcorrenciaCreateRequest r,CancellationToken ct)=>Task.FromResult(Next());
    public Task<SocialDashboardResponse> ObterAsync(long t,long e,CancellationToken ct)=>Task.FromResult(new SocialDashboardResponse(0,0,0,0,0,0,0,0,0,0,0,Array.Empty<object>(),Array.Empty<object>(),Array.Empty<object>(),Array.Empty<object>(),Array.Empty<object>(),new[]{"Assistência Social base carregada."}));
    public Task<byte[]> ExportarAsync(long t,long e,string recurso,string formato,CancellationToken ct)=>Task.FromResult(Encoding.UTF8.GetBytes(formato.Equals("json",StringComparison.OrdinalIgnoreCase)?"[]":"dados_mascarados\n"));
    public Task<string> ProximoAsync(long tenantId,long entidadeId,string prefixo,CancellationToken ct)=>Task.FromResult($"{prefixo}-{DateTime.UtcNow.Year}-000001");
}
