using Sigov.Application.Common;
using Sigov.Domain.Common;
namespace Sigov.Application.Social;
public static class SocialPermissoes{public const string Modulo="social";public const string ModuloAlternativo="assistencia_social";}
public sealed record SocialContexto(long TenantId,long EntidadeId,long? ExercicioId,long? UsuarioId);
public sealed record SocialFiltro(int Page=1,int PageSize=20,string? Termo=null,string? Status=null,long? FamiliaId=null);
public sealed record SocialUnidadeCreateRequest(string Codigo,string Nome,string TipoUnidade="CRAS",string Situacao="ATIVA",string? Observacao=null,decimal? Latitude=null,decimal? Longitude=null);
public sealed record SocialUnidadeUpdateRequest(string Codigo,string Nome,string TipoUnidade="CRAS",string Situacao="ATIVA",string? Observacao=null,decimal? Latitude=null,decimal? Longitude=null);
public sealed record SocialUnidadeFiltro(int Page=1,int PageSize=20,string? Termo=null,string? Situacao=null);
public sealed record SocialUnidadeResponse(long Id,string Codigo,string Nome,string TipoUnidade,string Situacao,bool Ativo);
public sealed record SocialFamiliaCreateRequest(string? CodigoFamilia=null,string? NisFamiliar=null,long? ResponsavelPessoaId=null,decimal? RendaFamiliar=null,string Situacao="ATIVA",string? ClassificacaoRisco=null,decimal? Latitude=null,decimal? Longitude=null,string? Observacao=null);
public sealed record SocialFamiliaUpdateRequest(string CodigoFamilia,string? NisFamiliar=null,long? ResponsavelPessoaId=null,decimal? RendaFamiliar=null,string Situacao="ATIVA",string? ClassificacaoRisco=null,decimal? Latitude=null,decimal? Longitude=null,string? Observacao=null);
public sealed record SocialFamiliaFiltro(int Page=1,int PageSize=20,string? Termo=null,string? Risco=null);
public sealed record SocialFamiliaResponse(long Id,string CodigoFamilia,string? NisFamiliar,long? ResponsavelPessoaId,decimal? RendaFamiliar,int QuantidadeMembros,string Situacao,string? ClassificacaoRisco);
public sealed record SocialFamiliaDetalheResponse(SocialFamiliaResponse Familia,IReadOnlyCollection<SocialComposicaoFamiliarResponse> Composicao,IReadOnlyCollection<SocialVulnerabilidadeResponse> Vulnerabilidades);
public sealed record SocialPessoaCreateRequest(long PessoaId,long? FamiliaId=null,string? Nis=null,string? NumeroProntuario=null,string? Escolaridade=null,string? Ocupacao=null,decimal? RendaIndividual=null,string Situacao="ATIVA");
public sealed record SocialPessoaUpdateRequest(long? FamiliaId=null,string? Nis=null,string? NumeroProntuario=null,string? Escolaridade=null,string? Ocupacao=null,decimal? RendaIndividual=null,string Situacao="ATIVA");
public sealed record SocialPessoaFiltro(int Page=1,int PageSize=20,string? Termo=null,long? FamiliaId=null);
public sealed record SocialPessoaResponse(long Id,long PessoaId,long? FamiliaId,string? Nis,string? NumeroProntuario,string Situacao);
public sealed record SocialComposicaoFamiliarRequest(long SocialPessoaId,string Parentesco,bool ResponsavelFamiliar=false);
public sealed record SocialComposicaoFamiliarResponse(long Id,long FamiliaId,long SocialPessoaId,string Parentesco,bool ResponsavelFamiliar,bool Ativo);
public sealed record SocialCadastroCreateRequest(long FamiliaId,long? UnidadeId=null,string? NumeroCadastro=null,string Status="ABERTO",string? Origem=null,string? Observacao=null);
public sealed record SocialCadastroResponse(long Id,long FamiliaId,string NumeroCadastro,DateOnly DataCadastro,string Status);
public sealed record SocialVulnerabilidadeCreateRequest(long? FamiliaId,long? SocialPessoaId,string TipoVulnerabilidade,string Grau="MEDIO",string? Descricao=null,string Status="ABERTA");
public sealed record SocialVulnerabilidadeResponse(long Id,long? FamiliaId,long? SocialPessoaId,string TipoVulnerabilidade,string Grau,string Status);
public sealed record SocialProgramaCreateRequest(string Codigo,string Nome,string TipoPrograma="MUNICIPAL",string? Descricao=null);
public sealed record SocialProgramaResponse(long Id,string Codigo,string Nome,string TipoPrograma,bool Ativo);
public sealed record SocialBeneficioCreateRequest(string Codigo,string Nome,string TipoBeneficio="EVENTUAL",long? ProgramaId=null,decimal? ValorReferencia=null,string? Periodicidade=null);
public sealed record SocialBeneficioResponse(long Id,string Codigo,string Nome,string TipoBeneficio,decimal? ValorReferencia,bool Ativo);
public sealed record SocialBeneficioConcessaoCreateRequest(long BeneficioId,long? FamiliaId=null,long? SocialPessoaId=null,string? NumeroConcessao=null,decimal? Valor=null,decimal? Quantidade=null,string Status="SOLICITADO",string? Observacao=null);
public sealed record SocialBeneficioConcessaoResponse(long Id,long BeneficioId,long? FamiliaId,long? SocialPessoaId,string NumeroConcessao,decimal? Valor,string Status);
public sealed record AutorizarBeneficioRequest(string? Observacao=null); public sealed record IndeferirBeneficioRequest(string Motivo);
public sealed record SocialAtendimentoCreateRequest(long? UnidadeId=null,long? FamiliaId=null,long? SocialPessoaId=null,string? NumeroAtendimento=null,string TipoAtendimento="ACOLHIDA",string Demanda="",string? EncaminhamentoResumo=null,string Status="ABERTO");
public sealed record SocialAtendimentoFiltro(int Page=1,int PageSize=20,long? FamiliaId=null,string? Status=null);
public sealed record SocialAtendimentoResponse(long Id,string NumeroAtendimento,long? UnidadeId,long? FamiliaId,long? SocialPessoaId,DateTimeOffset DataAtendimento,string TipoAtendimento,string Status);
public sealed record SocialEncaminhamentoCreateRequest(long? AtendimentoId,long? FamiliaId,long? SocialPessoaId,string Destino,string TipoEncaminhamento="REDE",string Descricao="",DateOnly? PrazoRetorno=null,string Status="PENDENTE");
public sealed record SocialEncaminhamentoResponse(long Id,long? AtendimentoId,string Destino,string TipoEncaminhamento,string Status);
public sealed record SocialVisitaCreateRequest(long? FamiliaId=null,long? SocialPessoaId=null,string Motivo="ACOMPANHAMENTO",string Relato="",string? Encaminhamentos=null,decimal? Latitude=null,decimal? Longitude=null,decimal? PrecisaoMetros=null,string Status="REALIZADA");
public sealed record SocialVisitaFiltro(int Page=1,int PageSize=20,long? FamiliaId=null,string? Status=null);
public sealed record SocialVisitaResponse(long Id,long? FamiliaId,long? SocialPessoaId,DateTimeOffset DataVisita,string Motivo,string Status);
public sealed record SocialParecerCreateRequest(long? AtendimentoId=null,long? FamiliaId=null,long? SocialPessoaId=null,string Titulo="",string Texto="",string TipoParecer="SOCIAL",bool Sigiloso=true);
public sealed record SocialParecerResponse(long Id,long? AtendimentoId,long? FamiliaId,string Titulo,string TipoParecer,bool Sigiloso,DateTimeOffset EmitidoAt);
public sealed record SocialAcompanhamentoCreateRequest(long FamiliaId,long? UnidadeId=null,string Objetivo="",string Status="ATIVO");
public sealed record SocialAcompanhamentoResponse(long Id,long FamiliaId,long? UnidadeId,DateOnly DataInicio,string Status);
public sealed record SocialVigilanciaIndicadorCreateRequest(string Codigo,string Nome,string? Descricao=null,decimal Valor=0,string? Competencia=null);
public sealed record SocialVigilanciaOcorrenciaCreateRequest(string TipoOcorrencia,string Descricao,long? FamiliaId=null,long? SocialPessoaId=null,decimal? Latitude=null,decimal? Longitude=null,string Status="ABERTA");
public sealed record SocialDashboardResponse(long TotalFamilias,long FamiliasEmRisco,long PessoasAcompanhadas,long AtendimentosMes,long VisitasMes,long BeneficiosConcedidosMes,long BeneficiosPendentes,long VulnerabilidadesAbertas,long AcompanhamentosAtivos,long EncaminhamentosPendentes,long OcorrenciasVigilanciaMes,IReadOnlyCollection<object> FamiliasPorRisco,IReadOnlyCollection<object> AtendimentosPorUnidade,IReadOnlyCollection<object> BeneficiosPorTipo,IReadOnlyCollection<object> UltimosAtendimentos,IReadOnlyCollection<object> UltimasVisitas,IReadOnlyCollection<string> Alertas);
public interface ISocialUnidadeRepository{Task<PagedResult<SocialUnidadeResponse>> ListarAsync(long t,long e,SocialUnidadeFiltro f,CancellationToken ct);Task<SocialUnidadeResponse?> ObterAsync(long t,long e,long id,CancellationToken ct);Task<long>CriarAsync(SocialContexto c,SocialUnidadeCreateRequest r,CancellationToken ct);Task AtualizarAsync(SocialContexto c,long id,SocialUnidadeUpdateRequest r,CancellationToken ct);Task ExcluirAsync(SocialContexto c,long id,CancellationToken ct);}
public interface ISocialFamiliaRepository{Task<PagedResult<SocialFamiliaResponse>> ListarAsync(long t,long e,SocialFamiliaFiltro f,CancellationToken ct);Task<SocialFamiliaResponse?> ObterAsync(long t,long e,long id,CancellationToken ct);Task<long>CriarAsync(SocialContexto c,SocialFamiliaCreateRequest r,string codigo,CancellationToken ct);Task AtualizarAsync(SocialContexto c,long id,SocialFamiliaUpdateRequest r,CancellationToken ct);Task ExcluirAsync(SocialContexto c,long id,CancellationToken ct);Task<long>AdicionarComposicaoAsync(SocialContexto c,long familiaId,SocialComposicaoFamiliarRequest r,CancellationToken ct);Task<long>RegistrarVulnerabilidadeAsync(SocialContexto c,long familiaId,SocialVulnerabilidadeCreateRequest r,CancellationToken ct);}
public interface ISocialPessoaRepository{Task<PagedResult<SocialPessoaResponse>> ListarAsync(long t,long e,SocialPessoaFiltro f,CancellationToken ct);Task<SocialPessoaResponse?> ObterAsync(long t,long e,long id,CancellationToken ct);Task<long>CriarAsync(SocialContexto c,SocialPessoaCreateRequest r,CancellationToken ct);Task AtualizarAsync(SocialContexto c,long id,SocialPessoaUpdateRequest r,CancellationToken ct);Task ExcluirAsync(SocialContexto c,long id,CancellationToken ct);}
public interface ISocialCadastroRepository{Task<long>CriarAsync(SocialContexto c,SocialCadastroCreateRequest r,string numero,CancellationToken ct);}
public interface ISocialProgramaRepository{Task<PagedResult<SocialProgramaResponse>> ListarAsync(long t,long e,SocialFiltro f,CancellationToken ct);Task<long>CriarAsync(SocialContexto c,SocialProgramaCreateRequest r,CancellationToken ct);Task AtualizarAsync(SocialContexto c,long id,SocialProgramaCreateRequest r,CancellationToken ct);Task ExcluirAsync(SocialContexto c,long id,CancellationToken ct);}
public interface ISocialBeneficioRepository{Task<PagedResult<SocialBeneficioResponse>> ListarAsync(long t,long e,SocialFiltro f,CancellationToken ct);Task<long>CriarAsync(SocialContexto c,SocialBeneficioCreateRequest r,CancellationToken ct);Task AtualizarAsync(SocialContexto c,long id,SocialBeneficioCreateRequest r,CancellationToken ct);Task ExcluirAsync(SocialContexto c,long id,CancellationToken ct);Task<PagedResult<SocialBeneficioConcessaoResponse>> ListarConcessoesAsync(long t,long e,SocialFiltro f,CancellationToken ct);Task<long>ConcederAsync(SocialContexto c,SocialBeneficioConcessaoCreateRequest r,string numero,CancellationToken ct);Task AlterarStatusConcessaoAsync(SocialContexto c,long id,string status,CancellationToken ct);}
public interface ISocialAtendimentoRepository{Task<PagedResult<SocialAtendimentoResponse>> ListarAsync(long t,long e,SocialAtendimentoFiltro f,CancellationToken ct);Task<SocialAtendimentoResponse?> ObterAsync(long t,long e,long id,CancellationToken ct);Task<long>CriarAsync(SocialContexto c,SocialAtendimentoCreateRequest r,string numero,CancellationToken ct);Task<long>EncaminharAsync(SocialContexto c,long atendimentoId,SocialEncaminhamentoCreateRequest r,CancellationToken ct);}
public interface ISocialVisitaRepository{Task<PagedResult<SocialVisitaResponse>> ListarAsync(long t,long e,SocialVisitaFiltro f,CancellationToken ct);Task<SocialVisitaResponse?> ObterAsync(long t,long e,long id,CancellationToken ct);Task<long>CriarAsync(SocialContexto c,SocialVisitaCreateRequest r,CancellationToken ct);}
public interface ISocialParecerRepository{Task<PagedResult<SocialParecerResponse>> ListarAsync(long t,long e,SocialFiltro f,CancellationToken ct);Task<long>CriarAsync(SocialContexto c,SocialParecerCreateRequest r,CancellationToken ct);}
public interface ISocialAcompanhamentoRepository{Task<PagedResult<SocialAcompanhamentoResponse>> ListarAsync(long t,long e,SocialFiltro f,CancellationToken ct);Task<long>CriarAsync(SocialContexto c,SocialAcompanhamentoCreateRequest r,CancellationToken ct);Task EncerrarAsync(SocialContexto c,long id,CancellationToken ct);}
public interface ISocialVigilanciaRepository{Task<PagedResult<object>> ListarIndicadoresAsync(long t,long e,SocialFiltro f,CancellationToken ct);Task<long>CriarIndicadorAsync(SocialContexto c,SocialVigilanciaIndicadorCreateRequest r,CancellationToken ct);Task<PagedResult<object>> ListarOcorrenciasAsync(long t,long e,SocialFiltro f,CancellationToken ct);Task<long>CriarOcorrenciaAsync(SocialContexto c,SocialVigilanciaOcorrenciaCreateRequest r,CancellationToken ct);}
public interface ISocialDashboardRepository{Task<SocialDashboardResponse> ObterAsync(long t,long e,CancellationToken ct);}
public interface ISocialExportacaoRepository{Task<byte[]> ExportarAsync(long t,long e,string recurso,string formato,CancellationToken ct);}
public interface ISocialSequencialService{Task<string> ProximoAsync(long tenantId,long entidadeId,string prefixo,CancellationToken ct);}

public interface ISocialUnidadeService{Task<Result<PagedResult<SocialUnidadeResponse>>> ListarAsync(SocialUnidadeFiltro f,CancellationToken ct);Task<Result<SocialUnidadeResponse>> ObterAsync(long id,CancellationToken ct);Task<Result<long>> CriarAsync(SocialUnidadeCreateRequest r,CancellationToken ct);Task<Result> AtualizarAsync(long id,SocialUnidadeUpdateRequest r,CancellationToken ct);Task<Result> ExcluirAsync(long id,CancellationToken ct);}
public interface ISocialFamiliaService{Task<Result<PagedResult<SocialFamiliaResponse>>> ListarAsync(SocialFamiliaFiltro f,CancellationToken ct);Task<Result<SocialFamiliaResponse>> ObterAsync(long id,CancellationToken ct);Task<Result<long>> CriarAsync(SocialFamiliaCreateRequest r,CancellationToken ct);Task<Result> AtualizarAsync(long id,SocialFamiliaUpdateRequest r,CancellationToken ct);Task<Result> ExcluirAsync(long id,CancellationToken ct);Task<Result<long>> AdicionarComposicaoAsync(long id,SocialComposicaoFamiliarRequest r,CancellationToken ct);Task<Result<long>> RegistrarVulnerabilidadeAsync(long id,SocialVulnerabilidadeCreateRequest r,CancellationToken ct);Task<Result<long>> CriarCadastroAsync(long id,SocialCadastroCreateRequest r,CancellationToken ct);}
public interface ISocialPessoaService{Task<Result<PagedResult<SocialPessoaResponse>>> ListarAsync(SocialPessoaFiltro f,CancellationToken ct);Task<Result<SocialPessoaResponse>> ObterAsync(long id,CancellationToken ct);Task<Result<long>> CriarAsync(SocialPessoaCreateRequest r,CancellationToken ct);Task<Result> AtualizarAsync(long id,SocialPessoaUpdateRequest r,CancellationToken ct);Task<Result> ExcluirAsync(long id,CancellationToken ct);}
public interface ISocialCadastroService{Task<Result<long>> CriarAsync(SocialCadastroCreateRequest r,CancellationToken ct);}
public interface ISocialProgramaService{Task<Result<PagedResult<SocialProgramaResponse>>> ListarAsync(SocialFiltro f,CancellationToken ct);Task<Result<long>> CriarAsync(SocialProgramaCreateRequest r,CancellationToken ct);Task<Result> AtualizarAsync(long id,SocialProgramaCreateRequest r,CancellationToken ct);Task<Result> ExcluirAsync(long id,CancellationToken ct);}
public interface ISocialBeneficioService{Task<Result<PagedResult<SocialBeneficioResponse>>> ListarAsync(SocialFiltro f,CancellationToken ct);Task<Result<long>> CriarAsync(SocialBeneficioCreateRequest r,CancellationToken ct);Task<Result> AtualizarAsync(long id,SocialBeneficioCreateRequest r,CancellationToken ct);Task<Result> ExcluirAsync(long id,CancellationToken ct);Task<Result<PagedResult<SocialBeneficioConcessaoResponse>>> ListarConcessoesAsync(SocialFiltro f,CancellationToken ct);Task<Result<long>> ConcederAsync(SocialBeneficioConcessaoCreateRequest r,CancellationToken ct);Task<Result> AutorizarAsync(long id,AutorizarBeneficioRequest r,CancellationToken ct);Task<Result> IndeferirAsync(long id,IndeferirBeneficioRequest r,CancellationToken ct);Task<Result> EntregarAsync(long id,CancellationToken ct);}
public interface ISocialAtendimentoService{Task<Result<PagedResult<SocialAtendimentoResponse>>> ListarAsync(SocialAtendimentoFiltro f,CancellationToken ct);Task<Result<SocialAtendimentoResponse>> ObterAsync(long id,CancellationToken ct);Task<Result<long>> CriarAsync(SocialAtendimentoCreateRequest r,CancellationToken ct);Task<Result<long>> EncaminharAsync(long id,SocialEncaminhamentoCreateRequest r,CancellationToken ct);}
public interface ISocialVisitaService{Task<Result<PagedResult<SocialVisitaResponse>>> ListarAsync(SocialVisitaFiltro f,CancellationToken ct);Task<Result<SocialVisitaResponse>> ObterAsync(long id,CancellationToken ct);Task<Result<long>> CriarAsync(SocialVisitaCreateRequest r,CancellationToken ct);}
public interface ISocialParecerService{Task<Result<PagedResult<SocialParecerResponse>>> ListarAsync(SocialFiltro f,CancellationToken ct);Task<Result<long>> CriarAsync(SocialParecerCreateRequest r,CancellationToken ct);}
public interface ISocialAcompanhamentoService{Task<Result<PagedResult<SocialAcompanhamentoResponse>>> ListarAsync(SocialFiltro f,CancellationToken ct);Task<Result<long>> CriarAsync(SocialAcompanhamentoCreateRequest r,CancellationToken ct);Task<Result> EncerrarAsync(long id,CancellationToken ct);}
public interface ISocialVigilanciaService{Task<Result<PagedResult<object>>> ListarIndicadoresAsync(SocialFiltro f,CancellationToken ct);Task<Result<long>> CriarIndicadorAsync(SocialVigilanciaIndicadorCreateRequest r,CancellationToken ct);Task<Result<PagedResult<object>>> ListarOcorrenciasAsync(SocialFiltro f,CancellationToken ct);Task<Result<long>> CriarOcorrenciaAsync(SocialVigilanciaOcorrenciaCreateRequest r,CancellationToken ct);}
public interface ISocialDashboardService{Task<Result<SocialDashboardResponse>> ObterAsync(CancellationToken ct);}
public interface ISocialExportacaoService{Task<Result<byte[]>> ExportarAsync(string recurso,string formato,CancellationToken ct);}
