using Microsoft.Extensions.Logging;
using Sigov.Application.Abstractions;
using Sigov.Application.Common;
using Sigov.Application.Saas;
using Sigov.Domain.Common;
using Sigov.Domain.Social;

namespace Sigov.Application.Social;

public sealed class SocialService : ISocialUnidadeService, ISocialFamiliaService, ISocialPessoaService, ISocialCadastroService, ISocialProgramaService, ISocialBeneficioService, ISocialAtendimentoService, ISocialVisitaService, ISocialParecerService, ISocialAcompanhamentoService, ISocialVigilanciaService, ISocialDashboardService, ISocialExportacaoService
{
    private readonly ICurrentTenant _tenant; private readonly ICurrentUser _user; private readonly IPermissionService _perm; private readonly IModuloLicenciamentoService _modulos; private readonly IAuditService _audit; private readonly ILogger<SocialService> _log;
    private readonly ISocialUnidadeRepository _unidades; private readonly ISocialFamiliaRepository _familias; private readonly ISocialPessoaRepository _pessoas; private readonly ISocialCadastroRepository _cadastros; private readonly ISocialProgramaRepository _programas; private readonly ISocialBeneficioRepository _beneficios; private readonly ISocialAtendimentoRepository _atendimentos; private readonly ISocialVisitaRepository _visitas; private readonly ISocialParecerRepository _pareceres; private readonly ISocialAcompanhamentoRepository _acompanhamentos; private readonly ISocialVigilanciaRepository _vigilancia; private readonly ISocialDashboardRepository _dashboard; private readonly ISocialExportacaoRepository _exportacao; private readonly ISocialSequencialService _seq;
    public SocialService(ICurrentTenant tenant, ICurrentUser user, IPermissionService perm, IModuloLicenciamentoService modulos, IAuditService audit, ILogger<SocialService> log, ISocialUnidadeRepository unidades, ISocialFamiliaRepository familias, ISocialPessoaRepository pessoas, ISocialCadastroRepository cadastros, ISocialProgramaRepository programas, ISocialBeneficioRepository beneficios, ISocialAtendimentoRepository atendimentos, ISocialVisitaRepository visitas, ISocialParecerRepository pareceres, ISocialAcompanhamentoRepository acompanhamentos, ISocialVigilanciaRepository vigilancia, ISocialDashboardRepository dashboard, ISocialExportacaoRepository exportacao, ISocialSequencialService seq)
    { _tenant=tenant; _user=user; _perm=perm; _modulos=modulos; _audit=audit; _log=log; _unidades=unidades; _familias=familias; _pessoas=pessoas; _cadastros=cadastros; _programas=programas; _beneficios=beneficios; _atendimentos=atendimentos; _visitas=visitas; _pareceres=pareceres; _acompanhamentos=acompanhamentos; _vigilancia=vigilancia; _dashboard=dashboard; _exportacao=exportacao; _seq=seq; }
    private static int Page(int p)=>p<1?1:p; private static int Size(int s)=>s<1?20:s>100?100:s;
    private async Task<Result<SocialContexto>> Ctx(string recurso,string acao,CancellationToken ct){ if(!_tenant.TenantId.HasValue) return Result<SocialContexto>.Failure("Tenant obrigatório."); if(!_tenant.EntidadeId.HasValue) return Result<SocialContexto>.Failure("Entidade obrigatória."); var enabled=await _modulos.IsModuleEnabledAsync(_tenant.TenantId.Value,SocialPermissoes.Modulo,ct)||await _modulos.IsModuleEnabledAsync(_tenant.TenantId.Value,SocialPermissoes.ModuloAlternativo,ct); if(!enabled) return Result<SocialContexto>.Failure("Módulo Assistência Social não contratado."); if(_user.UsuarioId.HasValue && !await _perm.HasPermissionAsync(_user.UsuarioId.Value,"social",recurso,acao,ct)) return Result<SocialContexto>.Failure("Permissão negada."); return Result<SocialContexto>.Success(new(_tenant.TenantId.Value,_tenant.EntidadeId.Value,_tenant.ExercicioId,_user.UsuarioId)); }
    private async Task Audit(string acao,string tabela,string chave,object? novo,CancellationToken ct){ try{ await _audit.RegistrarAsync("social",acao,tabela,chave,null,novo,ct);}catch(Exception ex){_log.LogWarning(ex,"Falha ao auditar Assistência Social");} }
    async Task<Result<PagedResult<SocialUnidadeResponse>>> ISocialUnidadeService.ListarAsync(SocialUnidadeFiltro f,CancellationToken ct){var c=await Ctx("unidade","visualizar",ct); if(c.IsFailure)return Result<PagedResult<SocialUnidadeResponse>>.Failure(c.Error!); var v=c.Value!; return Result<PagedResult<SocialUnidadeResponse>>.Success(await _unidades.ListarAsync(v.TenantId,v.EntidadeId,f with{Page=Page(f.Page),PageSize=Size(f.PageSize)},ct));}
    async Task<Result<SocialUnidadeResponse>> ISocialUnidadeService.ObterAsync(long id,CancellationToken ct){var c=await Ctx("unidade","visualizar",ct); if(c.IsFailure)return Result<SocialUnidadeResponse>.Failure(c.Error!); var v=c.Value!; var x=await _unidades.ObterAsync(v.TenantId,v.EntidadeId,id,ct); return x is null?Result<SocialUnidadeResponse>.Failure("Unidade não encontrada."):Result<SocialUnidadeResponse>.Success(x);}
    async Task<Result<long>> ISocialUnidadeService.CriarAsync(SocialUnidadeCreateRequest r,CancellationToken ct){var c=await Ctx("unidade","criar",ct); if(c.IsFailure)return Result<long>.Failure(c.Error!); var v=c.Value!; _=new SocialUnidade(v.TenantId,v.EntidadeId,r.Codigo,r.Nome,Enum.Parse<SocialUnidadeTipo>(r.TipoUnidade,true),r.Latitude,r.Longitude); var id=await _unidades.CriarAsync(v,r,ct); await Audit("CRIAR","sigov.social_unidade",id.ToString(),r,ct); return Result<long>.Success(id);}
    async Task<Result> ISocialUnidadeService.AtualizarAsync(long id,SocialUnidadeUpdateRequest r,CancellationToken ct){var c=await Ctx("unidade","editar",ct); if(c.IsFailure)return Result.Failure(c.Error!); await _unidades.AtualizarAsync(c.Value!,id,r,ct); await Audit("EDITAR","sigov.social_unidade",id.ToString(),r,ct); return Result.Success();}
    async Task<Result> ISocialUnidadeService.ExcluirAsync(long id,CancellationToken ct){var c=await Ctx("unidade","excluir",ct); if(c.IsFailure)return Result.Failure(c.Error!); await _unidades.ExcluirAsync(c.Value!,id,ct); await Audit("EXCLUIR","sigov.social_unidade",id.ToString(),null,ct); return Result.Success();}
    async Task<Result<PagedResult<SocialFamiliaResponse>>> ISocialFamiliaService.ListarAsync(SocialFamiliaFiltro f,CancellationToken ct){var c=await Ctx("familia","visualizar",ct); if(c.IsFailure)return Result<PagedResult<SocialFamiliaResponse>>.Failure(c.Error!); var v=c.Value!; return Result<PagedResult<SocialFamiliaResponse>>.Success(await _familias.ListarAsync(v.TenantId,v.EntidadeId,f with{Page=Page(f.Page),PageSize=Size(f.PageSize)},ct));}
    async Task<Result<SocialFamiliaResponse>> ISocialFamiliaService.ObterAsync(long id,CancellationToken ct){var c=await Ctx("familia","visualizar",ct); if(c.IsFailure)return Result<SocialFamiliaResponse>.Failure(c.Error!); var v=c.Value!; var x=await _familias.ObterAsync(v.TenantId,v.EntidadeId,id,ct); await Audit("ACESSO_DADO_PESSOAL","sigov.social_familia",id.ToString(),null,ct); return x is null?Result<SocialFamiliaResponse>.Failure("Família não encontrada."):Result<SocialFamiliaResponse>.Success(x);}
    async Task<Result<long>> ISocialFamiliaService.CriarAsync(SocialFamiliaCreateRequest r,CancellationToken ct){var c=await Ctx("familia","criar",ct); if(c.IsFailure)return Result<long>.Failure(c.Error!); var v=c.Value!; var codigo=r.CodigoFamilia??await _seq.ProximoAsync(v.TenantId,v.EntidadeId,"FAM",ct); _=new SocialFamilia(v.TenantId,v.EntidadeId,codigo); var id=await _familias.CriarAsync(v,r,codigo,ct); await Audit("CRIAR","sigov.social_familia",id.ToString(),r,ct); return Result<long>.Success(id);}
    async Task<Result> ISocialFamiliaService.AtualizarAsync(long id,SocialFamiliaUpdateRequest r,CancellationToken ct){var c=await Ctx("familia","editar",ct); if(c.IsFailure)return Result.Failure(c.Error!); await _familias.AtualizarAsync(c.Value!,id,r,ct); await Audit("EDITAR","sigov.social_familia",id.ToString(),r,ct); return Result.Success();}
    async Task<Result> ISocialFamiliaService.ExcluirAsync(long id,CancellationToken ct){var c=await Ctx("familia","excluir",ct); if(c.IsFailure)return Result.Failure(c.Error!); await _familias.ExcluirAsync(c.Value!,id,ct); await Audit("EXCLUIR","sigov.social_familia",id.ToString(),null,ct); return Result.Success();}
    async Task<Result<long>> ISocialFamiliaService.AdicionarComposicaoAsync(long id,SocialComposicaoFamiliarRequest r,CancellationToken ct){var c=await Ctx("familia","editar",ct); if(c.IsFailure)return Result<long>.Failure(c.Error!); _=new SocialComposicaoFamiliar(c.Value!.TenantId,c.Value.EntidadeId,id,r.SocialPessoaId,r.Parentesco,r.ResponsavelFamiliar); return Result<long>.Success(await _familias.AdicionarComposicaoAsync(c.Value,id,r,ct));}
    async Task<Result<long>> ISocialFamiliaService.RegistrarVulnerabilidadeAsync(long id,SocialVulnerabilidadeCreateRequest r,CancellationToken ct){var c=await Ctx("vulnerabilidade","criar",ct); if(c.IsFailure)return Result<long>.Failure(c.Error!); var req=r with{FamiliaId=id}; return Result<long>.Success(await _familias.RegistrarVulnerabilidadeAsync(c.Value!,id,req,ct));}
    async Task<Result<long>> ISocialFamiliaService.CriarCadastroAsync(long id,SocialCadastroCreateRequest r,CancellationToken ct)=> await ((ISocialCadastroService)this).CriarAsync(r with{FamiliaId=id},ct);
    async Task<Result<PagedResult<SocialPessoaResponse>>> ISocialPessoaService.ListarAsync(SocialPessoaFiltro f,CancellationToken ct){var c=await Ctx("pessoa","visualizar",ct); if(c.IsFailure)return Result<PagedResult<SocialPessoaResponse>>.Failure(c.Error!); var v=c.Value!; return Result<PagedResult<SocialPessoaResponse>>.Success(await _pessoas.ListarAsync(v.TenantId,v.EntidadeId,f with{Page=Page(f.Page),PageSize=Size(f.PageSize)},ct));}
    async Task<Result<SocialPessoaResponse>> ISocialPessoaService.ObterAsync(long id,CancellationToken ct){var c=await Ctx("pessoa","visualizar",ct); if(c.IsFailure)return Result<SocialPessoaResponse>.Failure(c.Error!); var v=c.Value!; var x=await _pessoas.ObterAsync(v.TenantId,v.EntidadeId,id,ct); await Audit("ACESSO_DADO_PESSOAL","sigov.social_pessoa",id.ToString(),null,ct); return x is null?Result<SocialPessoaResponse>.Failure("Pessoa social não encontrada."):Result<SocialPessoaResponse>.Success(x);}
    async Task<Result<long>> ISocialPessoaService.CriarAsync(SocialPessoaCreateRequest r,CancellationToken ct){var c=await Ctx("pessoa","criar",ct); if(c.IsFailure)return Result<long>.Failure(c.Error!); _=new SocialPessoa(c.Value!.TenantId,c.Value.EntidadeId,r.PessoaId,r.FamiliaId); return Result<long>.Success(await _pessoas.CriarAsync(c.Value,r,ct));}
    async Task<Result> ISocialPessoaService.AtualizarAsync(long id,SocialPessoaUpdateRequest r,CancellationToken ct){var c=await Ctx("pessoa","editar",ct); if(c.IsFailure)return Result.Failure(c.Error!); await _pessoas.AtualizarAsync(c.Value!,id,r,ct); return Result.Success();}
    async Task<Result> ISocialPessoaService.ExcluirAsync(long id,CancellationToken ct){var c=await Ctx("pessoa","excluir",ct); if(c.IsFailure)return Result.Failure(c.Error!); await _pessoas.ExcluirAsync(c.Value!,id,ct); return Result.Success();}
    async Task<Result<long>> ISocialCadastroService.CriarAsync(SocialCadastroCreateRequest r,CancellationToken ct){var c=await Ctx("cadastro","criar",ct); if(c.IsFailure)return Result<long>.Failure(c.Error!); var v=c.Value!; var numero=r.NumeroCadastro??await _seq.ProximoAsync(v.TenantId,v.EntidadeId,"CADSOC",ct); _=new SocialCadastro(v.TenantId,v.EntidadeId,r.FamiliaId,numero); return Result<long>.Success(await _cadastros.CriarAsync(v,r,numero,ct));}
    async Task<Result<PagedResult<SocialProgramaResponse>>> ISocialProgramaService.ListarAsync(SocialFiltro f,CancellationToken ct){var c=await Ctx("programa","visualizar",ct); if(c.IsFailure)return Result<PagedResult<SocialProgramaResponse>>.Failure(c.Error!); var v=c.Value!; return Result<PagedResult<SocialProgramaResponse>>.Success(await _programas.ListarAsync(v.TenantId,v.EntidadeId,f with{Page=Page(f.Page),PageSize=Size(f.PageSize)},ct));}
    async Task<Result<long>> ISocialProgramaService.CriarAsync(SocialProgramaCreateRequest r,CancellationToken ct){var c=await Ctx("programa","criar",ct); if(c.IsFailure)return Result<long>.Failure(c.Error!); return Result<long>.Success(await _programas.CriarAsync(c.Value!,r,ct));}
    async Task<Result> ISocialProgramaService.AtualizarAsync(long id,SocialProgramaCreateRequest r,CancellationToken ct){var c=await Ctx("programa","editar",ct); if(c.IsFailure)return Result.Failure(c.Error!); await _programas.AtualizarAsync(c.Value!,id,r,ct); return Result.Success();} async Task<Result> ISocialProgramaService.ExcluirAsync(long id,CancellationToken ct){var c=await Ctx("programa","excluir",ct); if(c.IsFailure)return Result.Failure(c.Error!); await _programas.ExcluirAsync(c.Value!,id,ct); return Result.Success();}
    async Task<Result<PagedResult<SocialBeneficioResponse>>> ISocialBeneficioService.ListarAsync(SocialFiltro f,CancellationToken ct){var c=await Ctx("beneficio","visualizar",ct); if(c.IsFailure)return Result<PagedResult<SocialBeneficioResponse>>.Failure(c.Error!); var v=c.Value!; return Result<PagedResult<SocialBeneficioResponse>>.Success(await _beneficios.ListarAsync(v.TenantId,v.EntidadeId,f with{Page=Page(f.Page),PageSize=Size(f.PageSize)},ct));}
    async Task<Result<long>> ISocialBeneficioService.CriarAsync(SocialBeneficioCreateRequest r,CancellationToken ct){var c=await Ctx("beneficio","criar",ct); if(c.IsFailure)return Result<long>.Failure(c.Error!); return Result<long>.Success(await _beneficios.CriarAsync(c.Value!,r,ct));}
    async Task<Result> ISocialBeneficioService.AtualizarAsync(long id,SocialBeneficioCreateRequest r,CancellationToken ct){var c=await Ctx("beneficio","editar",ct); if(c.IsFailure)return Result.Failure(c.Error!); await _beneficios.AtualizarAsync(c.Value!,id,r,ct); return Result.Success();} async Task<Result> ISocialBeneficioService.ExcluirAsync(long id,CancellationToken ct){var c=await Ctx("beneficio","editar",ct); if(c.IsFailure)return Result.Failure(c.Error!); await _beneficios.ExcluirAsync(c.Value!,id,ct); return Result.Success();}
    async Task<Result<PagedResult<SocialBeneficioConcessaoResponse>>> ISocialBeneficioService.ListarConcessoesAsync(SocialFiltro f,CancellationToken ct){var c=await Ctx("beneficio","visualizar",ct); if(c.IsFailure)return Result<PagedResult<SocialBeneficioConcessaoResponse>>.Failure(c.Error!); var v=c.Value!; return Result<PagedResult<SocialBeneficioConcessaoResponse>>.Success(await _beneficios.ListarConcessoesAsync(v.TenantId,v.EntidadeId,f,ct));}
    async Task<Result<long>> ISocialBeneficioService.ConcederAsync(SocialBeneficioConcessaoCreateRequest r,CancellationToken ct){var c=await Ctx("beneficio","conceder",ct); if(c.IsFailure)return Result<long>.Failure(c.Error!); var v=c.Value!; var numero=r.NumeroConcessao??await _seq.ProximoAsync(v.TenantId,v.EntidadeId,"BENSOC",ct); return Result<long>.Success(await _beneficios.ConcederAsync(v,r,numero,ct));}
    async Task<Result> ISocialBeneficioService.AutorizarAsync(long id,AutorizarBeneficioRequest r,CancellationToken ct){var c=await Ctx("beneficio","autorizar",ct); if(c.IsFailure)return Result.Failure(c.Error!); await _beneficios.AlterarStatusConcessaoAsync(c.Value!,id,"CONCEDIDO",ct); return Result.Success();} async Task<Result> ISocialBeneficioService.IndeferirAsync(long id,IndeferirBeneficioRequest r,CancellationToken ct){var c=await Ctx("beneficio","autorizar",ct); if(c.IsFailure)return Result.Failure(c.Error!); await _beneficios.AlterarStatusConcessaoAsync(c.Value!,id,"INDEFERIDO",ct); return Result.Success();} async Task<Result> ISocialBeneficioService.EntregarAsync(long id,CancellationToken ct){var c=await Ctx("beneficio","entregar",ct); if(c.IsFailure)return Result.Failure(c.Error!); await _beneficios.AlterarStatusConcessaoAsync(c.Value!,id,"ENTREGUE",ct); return Result.Success();}
    async Task<Result<PagedResult<SocialAtendimentoResponse>>> ISocialAtendimentoService.ListarAsync(SocialAtendimentoFiltro f,CancellationToken ct){var c=await Ctx("atendimento","visualizar",ct); if(c.IsFailure)return Result<PagedResult<SocialAtendimentoResponse>>.Failure(c.Error!); var v=c.Value!; return Result<PagedResult<SocialAtendimentoResponse>>.Success(await _atendimentos.ListarAsync(v.TenantId,v.EntidadeId,f,ct));}
    async Task<Result<SocialAtendimentoResponse>> ISocialAtendimentoService.ObterAsync(long id,CancellationToken ct){var c=await Ctx("atendimento","visualizar",ct); if(c.IsFailure)return Result<SocialAtendimentoResponse>.Failure(c.Error!); var v=c.Value!; var x=await _atendimentos.ObterAsync(v.TenantId,v.EntidadeId,id,ct); return x is null?Result<SocialAtendimentoResponse>.Failure("Atendimento não encontrado."):Result<SocialAtendimentoResponse>.Success(x);}
    async Task<Result<long>> ISocialAtendimentoService.CriarAsync(SocialAtendimentoCreateRequest r,CancellationToken ct){var c=await Ctx("atendimento","criar",ct); if(c.IsFailure)return Result<long>.Failure(c.Error!); var v=c.Value!; var numero=r.NumeroAtendimento??await _seq.ProximoAsync(v.TenantId,v.EntidadeId,"ATSOC",ct); _=new SocialAtendimento(v.TenantId,v.EntidadeId,numero,r.Demanda); return Result<long>.Success(await _atendimentos.CriarAsync(v,r,numero,ct));}
    async Task<Result<long>> ISocialAtendimentoService.EncaminharAsync(long id,SocialEncaminhamentoCreateRequest r,CancellationToken ct){var c=await Ctx("atendimento","encaminhar",ct); if(c.IsFailure)return Result<long>.Failure(c.Error!); _=new SocialEncaminhamento(c.Value!.TenantId,c.Value.EntidadeId,r.Destino,r.Descricao); return Result<long>.Success(await _atendimentos.EncaminharAsync(c.Value,id,r,ct));}
    async Task<Result<PagedResult<SocialVisitaResponse>>> ISocialVisitaService.ListarAsync(SocialVisitaFiltro f,CancellationToken ct){var c=await Ctx("visita","visualizar",ct); if(c.IsFailure)return Result<PagedResult<SocialVisitaResponse>>.Failure(c.Error!); var v=c.Value!; return Result<PagedResult<SocialVisitaResponse>>.Success(await _visitas.ListarAsync(v.TenantId,v.EntidadeId,f,ct));}
    async Task<Result<SocialVisitaResponse>> ISocialVisitaService.ObterAsync(long id,CancellationToken ct){var c=await Ctx("visita","visualizar",ct); if(c.IsFailure)return Result<SocialVisitaResponse>.Failure(c.Error!); var v=c.Value!; var x=await _visitas.ObterAsync(v.TenantId,v.EntidadeId,id,ct); return x is null?Result<SocialVisitaResponse>.Failure("Visita não encontrada."):Result<SocialVisitaResponse>.Success(x);} async Task<Result<long>> ISocialVisitaService.CriarAsync(SocialVisitaCreateRequest r,CancellationToken ct){var c=await Ctx("visita","criar",ct); if(c.IsFailure)return Result<long>.Failure(c.Error!); _=new SocialVisita(c.Value!.TenantId,c.Value.EntidadeId,r.Relato,r.Latitude,r.Longitude); return Result<long>.Success(await _visitas.CriarAsync(c.Value,r,ct));}
    async Task<Result<PagedResult<SocialParecerResponse>>> ISocialParecerService.ListarAsync(SocialFiltro f,CancellationToken ct){var c=await Ctx("parecer","visualizar",ct); if(c.IsFailure)return Result<PagedResult<SocialParecerResponse>>.Failure(c.Error!); var v=c.Value!; return Result<PagedResult<SocialParecerResponse>>.Success(await _pareceres.ListarAsync(v.TenantId,v.EntidadeId,f,ct));} async Task<Result<long>> ISocialParecerService.CriarAsync(SocialParecerCreateRequest r,CancellationToken ct){var c=await Ctx("parecer","criar",ct); if(c.IsFailure)return Result<long>.Failure(c.Error!); _=new SocialParecer(c.Value!.TenantId,c.Value.EntidadeId,r.Titulo,r.Texto,r.Sigiloso); return Result<long>.Success(await _pareceres.CriarAsync(c.Value,r,ct));}
    async Task<Result<PagedResult<SocialAcompanhamentoResponse>>> ISocialAcompanhamentoService.ListarAsync(SocialFiltro f,CancellationToken ct){var c=await Ctx("acompanhamento","visualizar",ct); if(c.IsFailure)return Result<PagedResult<SocialAcompanhamentoResponse>>.Failure(c.Error!); var v=c.Value!; return Result<PagedResult<SocialAcompanhamentoResponse>>.Success(await _acompanhamentos.ListarAsync(v.TenantId,v.EntidadeId,f,ct));} async Task<Result<long>> ISocialAcompanhamentoService.CriarAsync(SocialAcompanhamentoCreateRequest r,CancellationToken ct){var c=await Ctx("acompanhamento","criar",ct); if(c.IsFailure)return Result<long>.Failure(c.Error!); _=new SocialAcompanhamentoFamiliar(c.Value!.TenantId,c.Value.EntidadeId,r.FamiliaId,r.Objetivo); return Result<long>.Success(await _acompanhamentos.CriarAsync(c.Value,r,ct));} async Task<Result> ISocialAcompanhamentoService.EncerrarAsync(long id,CancellationToken ct){var c=await Ctx("acompanhamento","encerrar",ct); if(c.IsFailure)return Result.Failure(c.Error!); await _acompanhamentos.EncerrarAsync(c.Value!,id,ct); return Result.Success();}
    async Task<Result<PagedResult<object>>> ISocialVigilanciaService.ListarIndicadoresAsync(SocialFiltro f,CancellationToken ct){var c=await Ctx("vigilancia","visualizar",ct); if(c.IsFailure)return Result<PagedResult<object>>.Failure(c.Error!); var v=c.Value!; return Result<PagedResult<object>>.Success(await _vigilancia.ListarIndicadoresAsync(v.TenantId,v.EntidadeId,f,ct));} async Task<Result<long>> ISocialVigilanciaService.CriarIndicadorAsync(SocialVigilanciaIndicadorCreateRequest r,CancellationToken ct){var c=await Ctx("vigilancia","criar",ct); if(c.IsFailure)return Result<long>.Failure(c.Error!); _=new SocialVigilanciaIndicador(c.Value!.TenantId,c.Value.EntidadeId,r.Codigo,r.Nome,r.Valor); return Result<long>.Success(await _vigilancia.CriarIndicadorAsync(c.Value,r,ct));} async Task<Result<PagedResult<object>>> ISocialVigilanciaService.ListarOcorrenciasAsync(SocialFiltro f,CancellationToken ct){var c=await Ctx("vigilancia","visualizar",ct); if(c.IsFailure)return Result<PagedResult<object>>.Failure(c.Error!); var v=c.Value!; return Result<PagedResult<object>>.Success(await _vigilancia.ListarOcorrenciasAsync(v.TenantId,v.EntidadeId,f,ct));} async Task<Result<long>> ISocialVigilanciaService.CriarOcorrenciaAsync(SocialVigilanciaOcorrenciaCreateRequest r,CancellationToken ct){var c=await Ctx("vigilancia","criar",ct); if(c.IsFailure)return Result<long>.Failure(c.Error!); return Result<long>.Success(await _vigilancia.CriarOcorrenciaAsync(c.Value!,r,ct));}
    async Task<Result<SocialDashboardResponse>> ISocialDashboardService.ObterAsync(CancellationToken ct){var c=await Ctx("dashboard","visualizar",ct); if(c.IsFailure)return Result<SocialDashboardResponse>.Failure(c.Error!); var v=c.Value!; return Result<SocialDashboardResponse>.Success(await _dashboard.ObterAsync(v.TenantId,v.EntidadeId,ct));}
    async Task<Result<byte[]>> ISocialExportacaoService.ExportarAsync(string recurso,string formato,CancellationToken ct){var c=await Ctx("exportar","executar",ct); if(c.IsFailure)return Result<byte[]>.Failure(c.Error!); var v=c.Value!; await Audit("EXPORTAR","sigov.social_exportacao",recurso,new{recurso,formato},ct); return Result<byte[]>.Success(await _exportacao.ExportarAsync(v.TenantId,v.EntidadeId,recurso,formato,ct));}
}
