using System.Globalization;
using System.Text;
using System.Text.Json;
using Dapper;
using Sigov.Application.Ambiental;
using Sigov.Infrastructure.Persistence.Dapper;
namespace Sigov.Infrastructure.Ambiental;
public sealed class AmbientalRepository(DapperContext db):IAmbientalRepository
{
 private static readonly IReadOnlyDictionary<string,string> Tables=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase){["empreendedores"]="ambiental_empreendedor",["empreendimentos"]="ambiental_empreendimento",["parametros"]="ambiental_tipo_licenca",["requerimentos"]="ambiental_requerimento",["documentos"]="ambiental_documento",["analises"]="ambiental_analise_tecnica",["licencas"]="ambiental_licenca",["condicionantes"]="ambiental_condicionante",["vistorias"]="ambiental_vistoria",["denuncias"]="ambiental_denuncia",["autos"]="ambiental_auto",["taxas"]="ambiental_taxa",["auditoria"]="ambiental_auditoria",["pareceres"]="ambiental_parecer",["fiscalizacao"]="ambiental_vistoria",["autosinfracao"]="ambiental_auto",["notificacoes"]="ambiental_auto",["embargos"]="ambiental_auto",["recursos"]="ambiental_auto"};
 public async Task<AmbientalDashboard> DashboardAsync(AmbientalContexto c,AmbientalFiltro f,CancellationToken ct){using var cn=db.CreateConnection();const string sql="""select
 (select count(*) from sigov.ambiental_requerimento where tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted and status='ABERTO') RequerimentosAbertos,
 (select count(*) from sigov.ambiental_requerimento where tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted and status='EM_ANALISE') EmAnalise,
 (select count(*) from sigov.ambiental_documento where tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted and obrigatorio and not entregue) PendenciasDocumentais,
 (select count(*) from sigov.ambiental_vistoria where tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted and status='AGENDADA') VistoriasAgendadas,
 (select count(*) from sigov.ambiental_licenca where tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted and status='VIGENTE' and validade_fim>=current_date) LicencasVigentes,
 (select count(*) from sigov.ambiental_licenca where tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted and validade_fim<current_date) LicencasVencidas,
 (select count(*) from sigov.ambiental_licenca where tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted and validade_fim between current_date and current_date+30) LicencasAVencer,
 (select count(*) from sigov.ambiental_condicionante where tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted and status='PENDENTE' and prazo>=current_date) CondicionantesPendentes,
 (select count(*) from sigov.ambiental_condicionante where tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted and status in('PENDENTE','VENCIDA') and prazo<current_date) CondicionantesVencidas,
 (select count(*) from sigov.ambiental_denuncia where tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted and status in('RECEBIDA','EM_APURACAO')) DenunciasAbertas,
 (select count(*) from sigov.ambiental_auto where tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted and tipo='AUTO_INFRACAO' and status in('EMITIDO','DEFESA_PENDENTE','EM_ANALISE','MANTIDO')) AutosEmitidos,
 (select count(*) from sigov.ambiental_taxa where tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted and status='PENDENTE') TaxasPendentes""";return await cn.QuerySingleAsync<AmbientalDashboard>(new CommandDefinition(sql,c,cancellationToken:ct));}
 public async Task<AmbientalPagina> ListarAsync(AmbientalContexto c,string recurso,AmbientalFiltro f,CancellationToken ct){var t=Table(recurso);var page=Math.Max(1,f.Pagina);var size=Math.Clamp(f.Tamanho,1,100);using var cn=db.CreateConnection();var privacy=recurso=="denuncias"?",case when sigilo then '[DADO SIGILOSO]' else coalesce(denunciante,'') end as denunciante_lista":"";var where="tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted and (@Busca is null or coalesce(codigo,'') ilike '%'||@Busca||'%' or descricao ilike '%'||@Busca||'%') and (@Status is null or status=@Status)";var a=new{c.TenantId,c.EntidadeId,f.Busca,f.Status,Limit=size,Offset=(page-1)*size};var total=await cn.ExecuteScalarAsync<long>(new CommandDefinition($"select count(*) from sigov.{t} where {where}",a,cancellationToken:ct));var rows=(await cn.QueryAsync<AmbientalRegistro>(new CommandDefinition($"select id,coalesce(codigo,'') Codigo,descricao,status,valor,data,dados::text DadosJson,created_at CriadoEm {privacy} from sigov.{t} where {where} order by updated_at desc limit @Limit offset @Offset",a,cancellationToken:ct))).AsList();return new(rows,page,size,total);}
 public async Task<long> SalvarAsync(AmbientalContexto c,string recurso,AmbientalRegistroRequest r,long? id,CancellationToken ct){Validate(recurso,r);var t=Table(recurso);using var cn=db.CreateConnection();cn.Open();using var tx=cn.BeginTransaction();if(recurso=="licencas"){var req=JsonDocument.Parse(r.DadosJson).RootElement.GetProperty("requerimento_id").GetInt64();if(!await cn.ExecuteScalarAsync<bool>(new CommandDefinition("select exists(select 1 from sigov.ambiental_requerimento where id=@req and tenant_id=@TenantId and entidade_id=@EntidadeId and status='DEFERIDO' and not is_deleted)",new{req,c.TenantId,c.EntidadeId},tx,cancellationToken:ct)))throw new InvalidOperationException("A licença somente pode ser emitida para requerimento deferido.");}
 if(recurso=="requerimentos"&&r.Status=="DEFERIDO"){var pend=await cn.ExecuteScalarAsync<long>(new CommandDefinition("select count(*) from sigov.ambiental_documento where requerimento_id=@id and tenant_id=@TenantId and entidade_id=@EntidadeId and obrigatorio and not entregue and not is_deleted",new{id,c.TenantId,c.EntidadeId},tx,cancellationToken:ct));if(pend>0&&string.IsNullOrWhiteSpace(r.Justificativa))throw new InvalidOperationException("Há documentos obrigatórios pendentes; informe exceção justificada e auditável.");}
 var args=new DynamicParameters(r);args.Add("TenantId",c.TenantId);args.Add("EntidadeId",c.EntidadeId);args.Add("UsuarioId",c.UsuarioId);args.Add("Id",id);var sql=id is null?$"insert into sigov.{t}(codigo,descricao,status,valor,data,justificativa,dados,tenant_id,entidade_id,created_by) values(@Codigo,@Descricao,@Status,@Valor,@Data,@Justificativa,cast(@DadosJson as jsonb),@TenantId,@EntidadeId,@UsuarioId) returning id":$"update sigov.{t} set codigo=@Codigo,descricao=@Descricao,status=@Status,valor=@Valor,data=@Data,justificativa=@Justificativa,dados=cast(@DadosJson as jsonb),updated_at=now(),updated_by=@UsuarioId where id=@Id and tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted returning id";var saved=await cn.ExecuteScalarAsync<long?>(new CommandDefinition(sql,args,tx,cancellationToken:ct))??throw new KeyNotFoundException("Registro não encontrado no contexto atual.");await Audit(c,cn,id is null?"CRIAR":"ALTERAR",recurso,saved,null,JsonSerializer.Serialize(r),ct,tx);tx.Commit();return saved;}
 public async Task ExcluirAsync(AmbientalContexto c,string recurso,long id,string justificativa,CancellationToken ct){if(string.IsNullOrWhiteSpace(justificativa))throw new ArgumentException("Justificativa obrigatória.");using var cn=db.CreateConnection();var n=await cn.ExecuteAsync(new CommandDefinition($"update sigov.{Table(recurso)} set ativo=false,is_deleted=true,deleted_at=now(),deleted_by=@UsuarioId,justificativa=@justificativa where id=@id and tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted",new{id,justificativa,c.UsuarioId,c.TenantId,c.EntidadeId},cancellationToken:ct));if(n==0)throw new KeyNotFoundException();await Audit(c,cn,"EXCLUIR",recurso,id,null,null,ct);}
 public async Task<byte[]> ExportarCsvAsync(AmbientalContexto c,string relatorio,AmbientalFiltro f,CancellationToken ct){var t=Table(relatorio);using var cn=db.CreateConnection();var rows=await cn.QueryAsync<dynamic>(new CommandDefinition($"select id,coalesce(codigo,'') codigo,descricao,status,coalesce(valor,0) valor,data from sigov.{t} where tenant_id=@TenantId and entidade_id=@EntidadeId and not is_deleted order by id",c,cancellationToken:ct));var b=new StringBuilder("id;codigo;descricao;status;valor;data\r\n");foreach(var x in rows)b.AppendLine($"{x.id};{Csv(x.codigo)};{Csv(x.descricao)};{Csv(x.status)};{x.valor.ToString(CultureInfo.InvariantCulture)};{x.data:yyyy-MM-dd}");await Audit(c,cn,"EXPORTAR",relatorio,null,null,null,ct);return new UTF8Encoding(true).GetBytes(b.ToString());}
 private static string Table(string r)=>Tables.TryGetValue(r,out var t)?t:throw new ArgumentException("Recurso/relatório ambiental inválido.");
 private static void Validate(string recurso,AmbientalRegistroRequest r){if(string.IsNullOrWhiteSpace(r.Descricao))throw new ArgumentException("Descrição é obrigatória.");if(r.Valor<0)throw new ArgumentException("Valor não pode ser negativo.");if((r.Status is "CANCELADO" or "CANCELADA" or "ARQUIVADO" or "INDEFERIDO" or "SUSPENSA")&&string.IsNullOrWhiteSpace(r.Justificativa))throw new ArgumentException("O status exige justificativa.");try{JsonDocument.Parse(r.DadosJson);}catch(JsonException){throw new ArgumentException("Detalhes técnicos devem ser JSON válido.");}}
 private static string Csv(object? value){var s=Convert.ToString(value,CultureInfo.InvariantCulture)??"";if(s.Length>0&&"=+-@\t\r".Contains(s[0]))s="'"+s;return '"'+s.Replace("\"","\"\"")+'"';}
 private static async Task Audit(AmbientalContexto c,System.Data.IDbConnection cn,string acao,string recurso,long? id,string? antes,string? depois,CancellationToken ct,System.Data.IDbTransaction? tx=null)=>await cn.ExecuteAsync(new CommandDefinition("insert into sigov.ambiental_auditoria(acao,recurso,registro_id,usuario_id,antes,depois,correlation_id,ip,tenant_id,entidade_id,created_by,descricao,status,dados) values(@acao,@recurso,@id,@UsuarioId,cast(@antes as jsonb),cast(@depois as jsonb),@CorrelationId,cast(@Ip as inet),@TenantId,@EntidadeId,@UsuarioId,@recurso,'REGISTRADA','{}')",new{acao,recurso,id,c.UsuarioId,antes,depois,c.CorrelationId,c.Ip,c.TenantId,c.EntidadeId},tx,cancellationToken:ct));
}
