using Sigov.Application.Abstractions;
using Sigov.Application.Common;
using Sigov.Domain.Common;

namespace Sigov.Application.Bloco8;

public sealed class Bloco8Service : IProcessosDigitaisService,IProtocoloDigitalService,IProcessoNumeroService,IProcessoMovimentacaoService,IProcessoRelatorioService,IGedService,IGedDocumentoService,IGedArquivoFisicoService,IGedValidacaoPublicaService,IAssinaturaService,ILegislativoService,ILegislativoProposicaoService,ILegislativoSessaoService,ILegislativoVotacaoService,ILegislativoNormaService,ILegislativoRelatorioService,ITransparenciaService,IDiarioOficialService,IEsicService,IOuvidoriaService,IAtendimentoDigitalService
{
 private readonly ICurrentTenant _tenant; private readonly ICurrentUser _user; private readonly IBloco8Repository _repository; private readonly IAuditService _audit;
 public Bloco8Service(ICurrentTenant tenant,ICurrentUser user,IBloco8Repository repository,IAuditService audit){_tenant=tenant;_user=user;_repository=repository;_audit=audit;}
 public async Task<Result<PagedResult<Bloco8RegistroDto>>> ListarAsync(string recurso,int pagina,int tamanho,CancellationToken ct){if(!_tenant.TenantId.HasValue)return Result<PagedResult<Bloco8RegistroDto>>.Failure("Tenant obrigatório.");return Result<PagedResult<Bloco8RegistroDto>>.Success(await _repository.ListarAsync(_tenant.TenantId.Value,recurso,Math.Max(1,pagina),Math.Clamp(tamanho,1,100),ct));}
 public async Task<Result<Bloco8RegistroDto>> ObterAsync(string recurso,long id,CancellationToken ct){if(!_tenant.TenantId.HasValue)return Result<Bloco8RegistroDto>.Failure("Tenant obrigatório.");var item=await _repository.ObterAsync(_tenant.TenantId.Value,recurso,id,ct);return item is null?Result<Bloco8RegistroDto>.Failure("Registro não encontrado."):Result<Bloco8RegistroDto>.Success(item);}
 public async Task<Result<long>> CriarAsync(string recurso,Bloco8RegistroRequest request,string correlationId,CancellationToken ct){if(!_tenant.TenantId.HasValue)return Result<long>.Failure("Tenant obrigatório.");if(string.IsNullOrWhiteSpace(request.Titulo)&&string.IsNullOrWhiteSpace(request.Descricao))return Result<long>.Failure("Título ou descrição é obrigatório.");var id=await _repository.CriarAsync(_tenant.TenantId.Value,_tenant.EntidadeId,_tenant.ExercicioId,_user.UsuarioId,recurso,request,correlationId,ct);await _audit.RegistrarAsync("bloco8","CRIAR",recurso,id.ToString(),null,new{id},ct);return Result<long>.Success(id);}
 public async Task<Result> AlterarStatusAsync(string recurso,long id,string status,string? justificativa,string correlationId,CancellationToken ct){if(!_tenant.TenantId.HasValue)return Result.Failure("Tenant obrigatório.");if((status=="ENCERRADO"||status=="REABERTO"||status=="CANCELADO")&&string.IsNullOrWhiteSpace(justificativa))return Result.Failure("Justificativa obrigatória.");var ok=await _repository.AlterarStatusAsync(_tenant.TenantId.Value,recurso,id,status,justificativa,_user.UsuarioId,correlationId,ct);if(!ok)return Result.Failure("Registro não encontrado ou transição não permitida.");await _audit.RegistrarAsync("bloco8","STATUS",recurso,id.ToString(),null,new{status},ct);return Result.Success();}
 public async Task<Result<Bloco8DashboardDto>> DashboardAsync(string recurso,CancellationToken ct){if(!_tenant.TenantId.HasValue)return Result<Bloco8DashboardDto>.Failure("Tenant obrigatório.");return Result<Bloco8DashboardDto>.Success(await _repository.DashboardAsync(_tenant.TenantId.Value,recurso,ct));}
}
