using System.Text.Json; using Dapper; using Sigov.Application.Common; using Sigov.Application.Empresarial; using Sigov.Infrastructure.Persistence.Dapper; using Sigov.Infrastructure.Persistence.Repositories;
namespace Sigov.Infrastructure.Empresarial;
public sealed class EmpresarialRepository:BaseRepository,IEmpresarialRepository,IEmpresarialComercialRepository,IEmpresarialOrdemServicoRepository,IEmpresarialEstoqueRepository,IEmpresarialIndustrialRepository {
 private static readonly HashSet<string> Tabelas=new(StringComparer.Ordinal){"emp_comercial_cliente","emp_comercial_lead","emp_comercial_oportunidade","emp_comercial_proposta","emp_comercial_pedido","emp_comercial_tabela_preco","emp_comercial_atividade","emp_os_ordem","emp_os_apontamento","emp_os_checklist","emp_os_agendamento","emp_os_sla","emp_estoque_produto","emp_estoque_almoxarifado","emp_estoque_saldo","emp_estoque_movimento","emp_estoque_requisicao","emp_estoque_inventario","emp_compras_fornecedor","emp_compras_pedido","emp_industrial_ativo","emp_industrial_plano_manutencao","emp_industrial_manutencao_programada","emp_industrial_medidor","emp_industrial_leitura_medidor","emp_industrial_parada","emp_industrial_ordem_producao","emp_industrial_apontamento_producao","emp_industrial_qualidade_ocorrencia"}; private readonly DapperContext _context; public EmpresarialRepository(DapperContext context)=>_context=context;
 public async Task<PagedResult<EmpresarialRegistroDto>> ListarAsync(long tenantId,string tabela,int pagina,int tamanho,CancellationToken ct){tabela=Tabela(tabela);var sql=$"select id as Id,codigo as Codigo,status as Status,titulo as Titulo,descricao as Descricao,created_at as CreatedAt,dados as Dados from sigov.{tabela} where tenant_id=@TenantId and is_deleted=false order by id desc limit @Tamanho offset @Offset; select count(1) from sigov.{tabela} where tenant_id=@TenantId and is_deleted=false";using var c=_context.CreateConnection();using var m=await c.QueryMultipleAsync(new CommandDefinition(sql,new{TenantId=tenantId,Tamanho=tamanho,Offset=(pagina-1)*tamanho},cancellationToken:ct));var raw=(await m.ReadAsync<Row>()).AsList();var items=raw.Select(x=>new EmpresarialRegistroDto(x.Id,x.Codigo,x.Status,x.Titulo,x.Descricao,x.CreatedAt,JsonSerializer.Deserialize<Dictionary<string,object?>>(x.Dados)??new())).ToList();return new(items,pagina,tamanho,await m.ReadSingleAsync<long>());}
 public async Task<long> CriarAsync(long tenantId,long? entidadeId,long? usuarioId,string tabela,EmpresarialOperacaoRequest r,string cid,CancellationToken ct){tabela=Tabela(tabela);var sql=$"insert into sigov.{tabela}(tenant_id,entidade_id,codigo,tipo,status,titulo,descricao,referencia_id,quantidade,valor,justificativa,dados,auditoria,correlation_id,created_by) values(@TenantId,@EntidadeId,@Codigo,@Tipo,@Status,@Titulo,@Descricao,@ReferenciaId,@Quantidade,@Valor,@Justificativa,@Dados::jsonb,jsonb_build_object('acao','CRIAR','em',now()),@CorrelationId,@UsuarioId) returning id";using var c=_context.CreateConnection();return await c.ExecuteScalarAsync<long>(new CommandDefinition(sql,new{TenantId=tenantId,EntidadeId=entidadeId??0,r.Codigo,r.Tipo,r.Status,r.Titulo,r.Descricao,r.ReferenciaId,r.Quantidade,r.Valor,r.Justificativa,Dados=JsonSerializer.Serialize(r.Dados??new()),CorrelationId=Guid.TryParse(cid,out var g)?g:Guid.NewGuid(),UsuarioId=usuarioId},cancellationToken:ct));}
 public async Task<bool> StatusAsync(long tenantId,string tabela,long id,string status,string? justificativa,long? usuarioId,string cid,CancellationToken ct){tabela=Tabela(tabela);var sql=$"update sigov.{tabela} set status=@Status,justificativa=coalesce(@Justificativa,justificativa),updated_at=now(),updated_by=@UsuarioId,correlation_id=@CorrelationId,auditoria=auditoria||jsonb_build_object('status',@Status,'em',now()) where tenant_id=@TenantId and id=@Id and is_deleted=false";using var c=_context.CreateConnection();return await c.ExecuteAsync(new CommandDefinition(sql,new{TenantId=tenantId,Id=id,Status=status,Justificativa=justificativa,UsuarioId=usuarioId,CorrelationId=Guid.TryParse(cid,out var g)?g:Guid.NewGuid()},cancellationToken:ct))>0;}
 public async Task<EmpresarialDashboardDto> DashboardAsync(long tenantId,string tabela,CancellationToken ct){tabela=Tabela(tabela);var sql=$"select count(1) as Total,count(1) filter(where status in ('ABERTA','ABERTO','ATIVO','EM_EXECUCAO','PENDENTE')) as Abertos,count(1) filter(where status in ('VENCIDA','ATRASADA','CRITICA') or prazo_at<now()) as Alertas,count(1) filter(where status in ('CONCLUIDA','CONCLUIDO','APROVADA','RECEBIDO')) as Concluidos from sigov.{tabela} where tenant_id=@TenantId and is_deleted=false";using var c=_context.CreateConnection();var k=await c.QuerySingleAsync<Kpi>(new CommandDefinition(sql,new{TenantId=tenantId},cancellationToken:ct));var recent=await ListarAsync(tenantId,tabela,1,6,ct);return new(k.Total,k.Abertos,k.Alertas,k.Concluidos,recent.Items);}
 private static string Tabela(string t)=>Tabelas.Contains(t)?t:throw new ArgumentException("Recurso empresarial inválido."); private sealed record Row(long Id,string? Codigo,string Status,string? Titulo,string? Descricao,DateTimeOffset CreatedAt,string Dados); private sealed record Kpi(long Total,long Abertos,long Alertas,long Concluidos);
}
