namespace Sigov.Domain.Processos;

public enum ProcessoStatus { ABERTO, EM_TRAMITACAO, AGUARDANDO_DOCUMENTO, AGUARDANDO_ASSINATURA, SUSPENSO, ENCERRADO, CANCELADO }
public enum ProcessoPrioridade { BAIXA, NORMAL, ALTA, URGENTE }
public enum ProtocoloStatus { ABERTO, EM_ATENDIMENTO, CONVERTIDO_PROCESSO, ENCERRADO, CANCELADO }
public enum ProtocoloCanal { PRESENCIAL, TELEFONE, EMAIL, PORTAL, WHATSAPP, OUTROS }
public enum OuvidoriaTipoManifestacao { RECLAMACAO, DENUNCIA, ELOGIO, SUGESTAO, SOLICITACAO, INFORMACAO }
public enum OuvidoriaStatus { RECEBIDA, EM_ANALISE, ENCAMINHADA, RESPONDIDA, ARQUIVADA, CANCELADA }
public enum DiarioOficialStatus { RASCUNHO, AGENDADO, PUBLICADO, CANCELADO }
public enum AssinaturaDigitalStatus { PENDENTE, EM_FILA, ASSINADO, RECUSADO, CANCELADO }
