namespace Sigov.Domain.Agro.Relatorios;

public enum AgroIndicadorCategoria { PRODUTORES, PROPRIEDADES, PRODUCAO, PECUARIA, ASSISTENCIA_TECNICA, PROGRAMAS, PATRULHA_MECANIZADA, ESTRADAS, FEIRAS, AGROINDUSTRIA, COMPRAS_AF }
public enum AgroRelatorioTipo { PRODUTORES, PROPRIEDADES, PRODUCAO_AGRICOLA, PECUARIA, ASSISTENCIA_TECNICA, PROGRAMAS_BENEFICIOS, PATRULHA_MECANIZADA, ESTRADAS_VICINAIS, FEIRAS, AGROINDUSTRIAS, COMPRAS_AGRICULTURA_FAMILIAR, GEO }
public enum AgroRelatorioFormato { HTML, CSV, JSON, GEOJSON, XML }
public enum AgroRelatorioStatus { SOLICITADO, PROCESSANDO, CONCLUIDO, ERRO }
