create table if not exists sigov.log_aplicacao (
    id bigint generated always as identity primary key,
    entidade_id bigint null,
    exercicio_id bigint null,
    nivel varchar(30) not null,
    origem varchar(150) not null,
    mensagem text not null,
    propriedades jsonb null,
    codigo_externo varchar(100) null,
    observacao text null,
    ativo boolean not null default true,
    is_deleted boolean not null default false,
    created_at timestamptz not null default now(),
    created_by bigint null,
    updated_at timestamptz null,
    updated_by bigint null,
    deleted_at timestamptz null,
    deleted_by bigint null,
    correlation_id uuid null
);

create table if not exists sigov.log_erro (
    id bigint generated always as identity primary key,
    entidade_id bigint null,
    exercicio_id bigint null,
    origem varchar(150) not null,
    mensagem text not null,
    tipo_excecao varchar(250) null,
    stack_trace text null,
    propriedades jsonb null,
    codigo_externo varchar(100) null,
    observacao text null,
    ativo boolean not null default true,
    is_deleted boolean not null default false,
    created_at timestamptz not null default now(),
    created_by bigint null,
    updated_at timestamptz null,
    updated_by bigint null,
    deleted_at timestamptz null,
    deleted_by bigint null,
    correlation_id uuid null
);

create table if not exists sigov.fila_evento (
    id bigint generated always as identity primary key,
    entidade_id bigint null,
    exercicio_id bigint null,
    tipo_evento varchar(150) not null,
    payload jsonb not null,
    status varchar(30) not null default 'PENDENTE',
    tentativas integer not null default 0,
    processado_at timestamptz null,
    codigo_externo varchar(100) null,
    observacao text null,
    ativo boolean not null default true,
    is_deleted boolean not null default false,
    created_at timestamptz not null default now(),
    created_by bigint null,
    updated_at timestamptz null,
    updated_by bigint null,
    deleted_at timestamptz null,
    deleted_by bigint null,
    correlation_id uuid null
);
