create unique index if not exists ux_entidade_cnpj on sigov.entidade(cnpj) where is_deleted = false;
create index if not exists idx_pessoa_entidade_id on sigov.pessoa(entidade_id);
create index if not exists idx_pessoa_exercicio_id on sigov.pessoa(exercicio_id);
create index if not exists idx_pessoa_documento on sigov.pessoa(documento);
create index if not exists idx_pessoa_is_deleted on sigov.pessoa(is_deleted);
create index if not exists idx_pessoa_created_at on sigov.pessoa(created_at);
create unique index if not exists idx_usuario_login on sigov.usuario(login) where is_deleted = false;
create index if not exists idx_usuario_entidade_id on sigov.usuario(entidade_id);
create index if not exists idx_usuario_exercicio_id on sigov.usuario(exercicio_id);
create index if not exists idx_usuario_is_deleted on sigov.usuario(is_deleted);
create index if not exists idx_usuario_created_at on sigov.usuario(created_at);
create index if not exists idx_trilha_auditoria_periodo on sigov.trilha_auditoria(created_at);
create index if not exists idx_trilha_auditoria_tabela on sigov.trilha_auditoria(tabela);
create index if not exists idx_trilha_auditoria_usuario_id on sigov.trilha_auditoria(usuario_id);
create index if not exists idx_trilha_auditoria_valores_novos_gin on sigov.trilha_auditoria using gin(valores_novos);
create index if not exists idx_log_aplicacao_propriedades_gin on sigov.log_aplicacao using gin(propriedades);
create index if not exists idx_fila_evento_payload_gin on sigov.fila_evento using gin(payload);
create index if not exists idx_acesso_dado_pessoal_pessoa on sigov.acesso_dado_pessoal(pessoa_id);
create index if not exists idx_chamado_usuario_solicitante_id on sigov.chamado(usuario_solicitante_id);
create index if not exists idx_chamado_entidade_id on sigov.chamado(entidade_id);
create index if not exists idx_chamado_exercicio_id on sigov.chamado(exercicio_id);
create index if not exists idx_chamado_is_deleted on sigov.chamado(is_deleted);
create index if not exists idx_chamado_created_at on sigov.chamado(created_at);
create index if not exists idx_endereco_pessoa_id on sigov.endereco(pessoa_id);
create index if not exists idx_contato_pessoa_id on sigov.contato(pessoa_id);
