begin;

-- CORR20: regras publicadas em migration corretiva; a migration FUNC20 permanece imutável.
alter table sigov.convenio_orgao_concedente drop constraint if exists ck_convenio_orgao_status;
alter table sigov.convenio_orgao_concedente add constraint ck_convenio_orgao_status check (status in ('ATIVO','INATIVO'));
alter table sigov.convenio_programa drop constraint if exists ck_convenio_programa_status;
alter table sigov.convenio_programa add constraint ck_convenio_programa_status check (status in ('ATIVO','INATIVO','ENCERRADO','CANCELADO'));
alter table sigov.convenio_emenda drop constraint if exists ck_convenio_emenda_status;
alter table sigov.convenio_emenda add constraint ck_convenio_emenda_status check (status in ('CADASTRADA','APROVADA','EMPENHADA','PAGA','CANCELADA'));
alter table sigov.convenio_instrumento drop constraint if exists ck_convenio_instrumento_status;
alter table sigov.convenio_instrumento add constraint ck_convenio_instrumento_status check (status in ('RASCUNHO','ATIVO','SUSPENSO','ENCERRADO','CANCELADO'));
alter table sigov.convenio_projeto drop constraint if exists ck_convenio_projeto_status;
alter table sigov.convenio_projeto add constraint ck_convenio_projeto_status check (status in ('PLANEJADO','EM_EXECUCAO','CONCLUIDO','SUSPENSO','CANCELADO'));
alter table sigov.convenio_meta drop constraint if exists ck_convenio_meta_status;
alter table sigov.convenio_meta add constraint ck_convenio_meta_status check (status in ('PENDENTE','EM_EXECUCAO','CONCLUIDA','CANCELADA'));
alter table sigov.convenio_etapa drop constraint if exists ck_convenio_etapa_status;
alter table sigov.convenio_etapa add constraint ck_convenio_etapa_status check (status in ('PENDENTE','EM_EXECUCAO','CONCLUIDA','CANCELADA'));
alter table sigov.convenio_conta_bancaria drop constraint if exists ck_convenio_conta_status;
alter table sigov.convenio_conta_bancaria add constraint ck_convenio_conta_status check (status in ('ATIVA','INATIVA','ENCERRADA','AJUSTE'));
alter table sigov.convenio_repasse drop constraint if exists ck_convenio_repasse_status;
alter table sigov.convenio_repasse add constraint ck_convenio_repasse_status check (status in ('PREVISTO','RECEBIDO','ESTORNADO','CANCELADO'));
alter table sigov.convenio_despesa drop constraint if exists ck_convenio_despesa_status;
alter table sigov.convenio_despesa add constraint ck_convenio_despesa_status check (status in ('PENDENTE','LIQUIDADA','PAGA','ESTORNADA','CANCELADA'));
alter table sigov.convenio_contrapartida drop constraint if exists ck_convenio_contrapartida_status;
alter table sigov.convenio_contrapartida add constraint ck_convenio_contrapartida_status check (status in ('PREVISTA','REALIZADA','PARCIAL','CANCELADA'));
alter table sigov.convenio_acompanhamento drop constraint if exists ck_convenio_acompanhamento_status;
alter table sigov.convenio_acompanhamento add constraint ck_convenio_acompanhamento_status check (status in ('REGULAR','ATENCAO','CRITICO','ENCERRADO'));
alter table sigov.convenio_prestacao_contas drop constraint if exists ck_convenio_prestacao_status;
alter table sigov.convenio_prestacao_contas add constraint ck_convenio_prestacao_status check (status in ('RASCUNHO','ENVIADA','EM_ANALISE','DILIGENCIA','APROVADA','REJEITADA','CANCELADA'));
alter table sigov.convenio_diligencia drop constraint if exists ck_convenio_diligencia_status;
alter table sigov.convenio_diligencia add constraint ck_convenio_diligencia_status check (status in ('ABERTA','EM_RESPOSTA','RESPONDIDA','ENCERRADA','CANCELADA'));
alter table sigov.convenio_documento_referencia drop constraint if exists ck_convenio_documento_status;
alter table sigov.convenio_documento_referencia add constraint ck_convenio_documento_status check (status in ('ATIVO','INATIVO','CANCELADO'));
alter table sigov.convenio_documento_referencia drop constraint if exists ck_convenio_documento_vinculo;
alter table sigov.convenio_documento_referencia add constraint ck_convenio_documento_vinculo check (num_nonnulls(instrumento_id,projeto_id,prestacao_contas_id) = 1);
alter table sigov.convenio_meta drop constraint if exists ck_convenio_meta_conclusao;
alter table sigov.convenio_meta add constraint ck_convenio_meta_conclusao check (status <> 'CONCLUIDA' or quantidade_executada >= quantidade_prevista);
alter table sigov.convenio_contrapartida drop constraint if exists ck_convenio_contrapartida_realizacao;
alter table sigov.convenio_contrapartida add constraint ck_convenio_contrapartida_realizacao check (status not in ('REALIZADA','PARCIAL') or data_realizacao is not null);
alter table sigov.convenio_despesa drop constraint if exists ck_convenio_despesa_pagamento;
alter table sigov.convenio_despesa add constraint ck_convenio_despesa_pagamento check (data_pagamento is null or data_pagamento >= data_despesa);
alter table sigov.convenio_prestacao_contas drop constraint if exists ck_convenio_prestacao_valor_aprovado;
alter table sigov.convenio_prestacao_contas add constraint ck_convenio_prestacao_valor_aprovado check (valor_aprovado is null or valor_aprovado <= valor_prestado);

create index if not exists ix_convenio_orgao_contexto_status on sigov.convenio_orgao_concedente(tenant_id,entity_id,status) where deleted_at is null;
create index if not exists ix_convenio_programa_contexto_orgao_status on sigov.convenio_programa(tenant_id,entity_id,orgao_concedente_id,status) where deleted_at is null;
create index if not exists ix_convenio_emenda_contexto_status_ano on sigov.convenio_emenda(tenant_id,entity_id,status,ano desc) where deleted_at is null;
create index if not exists ix_convenio_instrumento_orgao_programa on sigov.convenio_instrumento(tenant_id,entity_id,orgao_concedente_id,programa_id) where deleted_at is null;
create index if not exists ix_convenio_projeto_instrumento_status on sigov.convenio_projeto(tenant_id,entity_id,instrumento_id,status) where deleted_at is null;
create index if not exists ix_convenio_meta_projeto_status on sigov.convenio_meta(tenant_id,entity_id,projeto_id,status) where deleted_at is null;
create index if not exists ix_convenio_etapa_meta_status on sigov.convenio_etapa(tenant_id,entity_id,meta_id,status) where deleted_at is null;
create index if not exists ix_convenio_conta_instrumento_status on sigov.convenio_conta_bancaria(tenant_id,entity_id,instrumento_id,status) where deleted_at is null;
create index if not exists ix_convenio_repasse_instrumento_data on sigov.convenio_repasse(tenant_id,entity_id,instrumento_id,data_repasse desc) where deleted_at is null;
create index if not exists ix_convenio_despesa_instrumento_status on sigov.convenio_despesa(tenant_id,entity_id,instrumento_id,status,data_despesa desc) where deleted_at is null;
create index if not exists ix_convenio_contrapartida_instrumento_status on sigov.convenio_contrapartida(tenant_id,entity_id,instrumento_id,status) where deleted_at is null;
create index if not exists ix_convenio_acompanhamento_projeto_data on sigov.convenio_acompanhamento(tenant_id,entity_id,projeto_id,data_acompanhamento desc) where deleted_at is null;
create index if not exists ix_convenio_prestacao_instrumento_status on sigov.convenio_prestacao_contas(tenant_id,entity_id,instrumento_id,status,periodo_fim desc) where deleted_at is null;
create index if not exists ix_convenio_diligencia_prestacao_status on sigov.convenio_diligencia(tenant_id,entity_id,prestacao_contas_id,status,prazo_resposta) where deleted_at is null;
create index if not exists ix_convenio_documento_vinculos on sigov.convenio_documento_referencia(tenant_id,entity_id,instrumento_id,projeto_id,prestacao_contas_id) where deleted_at is null;
create index if not exists ix_convenio_auditoria_registro on sigov.convenio_auditoria(tenant_id,entity_id,tabela,registro_id,created_at desc);

commit;
