-- RC50.85: núcleo multi-esfera de planejamento, licitação, atas e fiscalização contratual.
-- Corretiva aditiva e reexecutável: preserva as estruturas legadas do FUNC03.
CREATE SCHEMA IF NOT EXISTS sigov;

CREATE TABLE IF NOT EXISTS sigov.compras_plano_contratacao_anual (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id bigint NOT NULL, entidade_id bigint NOT NULL,
 esfera_governo varchar(10) NOT NULL, tipo_entidade varchar(80) NOT NULL, orgao_superior_id bigint,
 unidade_gestora_id bigint NOT NULL, unidade_executora_id bigint, exercicio_id bigint NOT NULL,
 abrangencia_territorial varchar(120) NOT NULL, jurisdicao varchar(160), uf char(2), municipio varchar(160), regiao varchar(120),
 titulo varchar(240) NOT NULL, status varchar(20) NOT NULL DEFAULT 'rascunho', justificativa_decisao text,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by bigint NOT NULL, updated_by bigint NOT NULL,
 CONSTRAINT ck_compras_pca_esfera CHECK (esfera_governo IN ('municipal','estadual','federal')),
 CONSTRAINT ck_compras_pca_status CHECK (status IN ('rascunho','em_aprovacao','aprovado','reprovado','cancelado')),
 CONSTRAINT ck_compras_pca_justificativa CHECK (status NOT IN ('reprovado','cancelado') OR nullif(btrim(justificativa_decisao),'') IS NOT NULL),
 CONSTRAINT ux_compras_pca_contexto UNIQUE (tenant_id,entidade_id,unidade_gestora_id,exercicio_id)
);

CREATE TABLE IF NOT EXISTS sigov.compras_demanda (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, esfera_governo varchar(10) NOT NULL,
 plano_id bigint REFERENCES sigov.compras_plano_contratacao_anual(id), orgao_id bigint, unidade_gestora_id bigint NOT NULL, unidade_executora_id bigint,
 exercicio_id bigint NOT NULL, objeto text NOT NULL, justificativa text NOT NULL, valor_estimado numeric(18,4) NOT NULL DEFAULT 0,
 prioridade varchar(12) NOT NULL DEFAULT 'normal', status varchar(20) NOT NULL DEFAULT 'rascunho', justificativa_decisao text,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by bigint NOT NULL, updated_by bigint NOT NULL,
 CHECK (esfera_governo IN ('municipal','estadual','federal')), CHECK (valor_estimado >= 0), CHECK (prioridade IN ('baixa','normal','alta','urgente')),
 CHECK (status IN ('rascunho','submetida','aprovada','reprovada','cancelada')), CHECK (status NOT IN ('reprovada','cancelada') OR nullif(btrim(justificativa_decisao),'') IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS sigov.compras_dfd (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, esfera_governo varchar(10) NOT NULL,
 demanda_id bigint NOT NULL REFERENCES sigov.compras_demanda(id), orgao_id bigint, unidade_gestora_id bigint NOT NULL, unidade_executora_id bigint,
 necessidade text NOT NULL, resultados_esperados text NOT NULL, status varchar(20) NOT NULL DEFAULT 'rascunho', justificativa_decisao text,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by bigint NOT NULL, updated_by bigint NOT NULL,
 CHECK (esfera_governo IN ('municipal','estadual','federal')), CHECK (status IN ('rascunho','em_aprovacao','aprovado','reprovado','cancelado')),
 CHECK (status NOT IN ('reprovado','cancelado') OR nullif(btrim(justificativa_decisao),'') IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS sigov.compras_estudo_tecnico_preliminar (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, esfera_governo varchar(10) NOT NULL,
 demanda_id bigint NOT NULL REFERENCES sigov.compras_demanda(id), descricao_solucao text NOT NULL, requisitos text NOT NULL,
 estimativa_quantidades text NOT NULL, justificativa_viabilidade text NOT NULL, status varchar(20) NOT NULL DEFAULT 'rascunho',
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by bigint NOT NULL, updated_by bigint NOT NULL,
 CHECK (esfera_governo IN ('municipal','estadual','federal')), CHECK (status IN ('rascunho','em_aprovacao','aprovado','reprovado','cancelado'))
);
CREATE TABLE IF NOT EXISTS sigov.compras_mapa_riscos (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, esfera_governo varchar(10) NOT NULL,
 demanda_id bigint NOT NULL REFERENCES sigov.compras_demanda(id), risco text NOT NULL, probabilidade smallint NOT NULL, impacto smallint NOT NULL,
 tratamento text NOT NULL, responsavel_id bigint NOT NULL, status varchar(20) NOT NULL DEFAULT 'aberto',
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by bigint NOT NULL, updated_by bigint NOT NULL,
 CHECK (esfera_governo IN ('municipal','estadual','federal')), CHECK (probabilidade BETWEEN 1 AND 5), CHECK (impacto BETWEEN 1 AND 5), CHECK (status IN ('aberto','mitigado','aceito','encerrado'))
);
CREATE TABLE IF NOT EXISTS sigov.compras_termo_referencia (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, esfera_governo varchar(10) NOT NULL,
 demanda_id bigint NOT NULL REFERENCES sigov.compras_demanda(id), objeto text NOT NULL, especificacao text NOT NULL, criterios_aceite text NOT NULL,
 obrigacoes text NOT NULL, prazo_execucao_dias integer NOT NULL, status varchar(20) NOT NULL DEFAULT 'rascunho',
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by bigint NOT NULL, updated_by bigint NOT NULL,
 CHECK (esfera_governo IN ('municipal','estadual','federal')), CHECK (prazo_execucao_dias > 0), CHECK (status IN ('rascunho','em_aprovacao','aprovado','reprovado','cancelado'))
);

CREATE TABLE IF NOT EXISTS sigov.compras_pesquisa_preco (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, esfera_governo varchar(10) NOT NULL,
 demanda_id bigint NOT NULL REFERENCES sigov.compras_demanda(id), metodo varchar(12) NOT NULL, valor_referencia numeric(18,4) NOT NULL DEFAULT 0,
 status varchar(20) NOT NULL DEFAULT 'rascunho', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by bigint NOT NULL, updated_by bigint NOT NULL,
 CHECK (esfera_governo IN ('municipal','estadual','federal')), CHECK (metodo IN ('media','mediana','menor')), CHECK (valor_referencia >= 0), CHECK (status IN ('rascunho','em_coleta','concluida','cancelada'))
);
CREATE TABLE IF NOT EXISTS sigov.compras_pesquisa_preco_item (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, pesquisa_preco_id bigint NOT NULL REFERENCES sigov.compras_pesquisa_preco(id) ON DELETE CASCADE,
 descricao text NOT NULL, quantidade numeric(18,4) NOT NULL, unidade varchar(30) NOT NULL, media numeric(18,4), mediana numeric(18,4), menor_preco numeric(18,4),
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by bigint NOT NULL, updated_by bigint NOT NULL,
 CHECK (quantidade > 0), CHECK (media IS NULL OR media >= 0), CHECK (mediana IS NULL OR mediana >= 0), CHECK (menor_preco IS NULL OR menor_preco >= 0)
);
CREATE TABLE IF NOT EXISTS sigov.compras_fornecedor_cotacao (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id bigint NOT NULL, entidade_id bigint NOT NULL,
 pesquisa_item_id bigint NOT NULL REFERENCES sigov.compras_pesquisa_preco_item(id) ON DELETE CASCADE, fornecedor_id bigint NOT NULL REFERENCES sigov.compras_fornecedor(id),
 fonte varchar(40) NOT NULL, valor_unitario numeric(18,4) NOT NULL, coletado_em date NOT NULL, discrepante boolean NOT NULL DEFAULT false, justificativa_discrepancia text,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by bigint NOT NULL, updated_by bigint NOT NULL,
 CHECK (valor_unitario >= 0), CHECK (NOT discrepante OR nullif(btrim(justificativa_discrepancia),'') IS NOT NULL), UNIQUE (pesquisa_item_id,fornecedor_id,fonte)
);

CREATE TABLE IF NOT EXISTS sigov.compras_modalidade_config (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, esfera_governo varchar(10) NOT NULL,
 modalidade varchar(30) NOT NULL, criterio_julgamento varchar(30) NOT NULL, exige_dfd boolean NOT NULL DEFAULT true, exige_etp boolean NOT NULL DEFAULT true,
 exige_mapa_riscos boolean NOT NULL DEFAULT true, exige_termo_referencia boolean NOT NULL DEFAULT true, ativo boolean NOT NULL DEFAULT true,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by bigint NOT NULL, updated_by bigint NOT NULL,
 CHECK (esfera_governo IN ('municipal','estadual','federal')), CHECK (modalidade IN ('pregao','concorrencia','concurso','leilao','dialogo_competitivo','dispensa','inexigibilidade')),
 CHECK (criterio_julgamento IN ('menor_preco','maior_desconto','melhor_tecnica','tecnica_preco','maior_lance','maior_retorno')), UNIQUE (tenant_id,entidade_id,esfera_governo,modalidade)
);
CREATE TABLE IF NOT EXISTS sigov.compras_processo_fase (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, processo_id bigint NOT NULL,
 fase varchar(30) NOT NULL, status_anterior varchar(30), status_novo varchar(30) NOT NULL, justificativa text, responsavel_id bigint NOT NULL,
 created_at timestamptz NOT NULL DEFAULT now(), created_by bigint NOT NULL,
 CHECK (fase IN ('planejamento','publicacao','disputa','julgamento','habilitacao','recurso','adjudicacao','homologacao','contratacao'))
);
CREATE TABLE IF NOT EXISTS sigov.compras_licitacao (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, esfera_governo varchar(10) NOT NULL,
 processo_id bigint NOT NULL, orgao_id bigint, unidade_gestora_id bigint NOT NULL, unidade_executora_id bigint, modalidade_config_id bigint NOT NULL REFERENCES sigov.compras_modalidade_config(id),
 numero varchar(80) NOT NULL, objeto text NOT NULL, status varchar(30) NOT NULL DEFAULT 'rascunho', data_publicacao date, data_disputa timestamptz,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by bigint NOT NULL, updated_by bigint NOT NULL,
 CHECK (esfera_governo IN ('municipal','estadual','federal')), CHECK (status IN ('rascunho','em_planejamento','publicado','em_disputa','julgamento','habilitacao','recurso','adjudicado','homologado','fracassado','deserto','revogado','anulado','cancelado')),
 UNIQUE (tenant_id,entidade_id,numero)
);
CREATE TABLE IF NOT EXISTS sigov.compras_licitacao_lote (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, licitacao_id bigint NOT NULL REFERENCES sigov.compras_licitacao(id) ON DELETE CASCADE,
 numero integer NOT NULL, descricao text NOT NULL, valor_estimado numeric(18,4) NOT NULL DEFAULT 0, status varchar(20) NOT NULL DEFAULT 'aberto',
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by bigint NOT NULL, updated_by bigint NOT NULL,
 CHECK (numero > 0), CHECK (valor_estimado >= 0), CHECK (status IN ('aberto','julgado','fracassado','cancelado')), UNIQUE (licitacao_id,numero)
);
CREATE TABLE IF NOT EXISTS sigov.compras_licitacao_item (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, licitacao_id bigint NOT NULL REFERENCES sigov.compras_licitacao(id) ON DELETE CASCADE,
 lote_id bigint REFERENCES sigov.compras_licitacao_lote(id), numero integer NOT NULL, descricao text NOT NULL, quantidade numeric(18,4) NOT NULL, unidade varchar(30) NOT NULL, valor_estimado numeric(18,4) NOT NULL,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by bigint NOT NULL, updated_by bigint NOT NULL,
 CHECK (numero > 0), CHECK (quantidade > 0), CHECK (valor_estimado >= 0), UNIQUE (licitacao_id,numero)
);
CREATE TABLE IF NOT EXISTS sigov.compras_sessao (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, licitacao_id bigint NOT NULL REFERENCES sigov.compras_licitacao(id),
 inicio_em timestamptz NOT NULL, fim_em timestamptz, responsavel_id bigint NOT NULL, status varchar(20) NOT NULL DEFAULT 'agendada',
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by bigint NOT NULL, updated_by bigint NOT NULL,
 CHECK (fim_em IS NULL OR fim_em >= inicio_em), CHECK (status IN ('agendada','aberta','suspensa','encerrada','cancelada'))
);
CREATE TABLE IF NOT EXISTS sigov.compras_proposta (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, licitacao_id bigint NOT NULL REFERENCES sigov.compras_licitacao(id),
 lote_id bigint REFERENCES sigov.compras_licitacao_lote(id), item_id bigint REFERENCES sigov.compras_licitacao_item(id), fornecedor_id bigint NOT NULL REFERENCES sigov.compras_fornecedor(id),
 valor numeric(18,4) NOT NULL, status varchar(20) NOT NULL DEFAULT 'recebida', ordem_classificacao integer, justificativa_desclassificacao text,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by bigint NOT NULL, updated_by bigint NOT NULL,
 CHECK (valor >= 0), CHECK ((lote_id IS NOT NULL) <> (item_id IS NOT NULL)), CHECK (status IN ('recebida','classificada','desclassificada','vencedora')), CHECK (status <> 'desclassificada' OR nullif(btrim(justificativa_desclassificacao),'') IS NOT NULL)
);
CREATE TABLE IF NOT EXISTS sigov.compras_julgamento_rc50_85 (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, licitacao_id bigint NOT NULL REFERENCES sigov.compras_licitacao(id),
 proposta_id bigint NOT NULL REFERENCES sigov.compras_proposta(id), criterio varchar(30) NOT NULL, resultado varchar(20) NOT NULL, justificativa text NOT NULL, responsavel_id bigint NOT NULL,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by bigint NOT NULL, updated_by bigint NOT NULL,
 CHECK (resultado IN ('classificada','desclassificada','vencedora'))
);

-- Registros de decisão licitatória compartilham o mesmo contrato de contexto e auditoria.
CREATE TABLE IF NOT EXISTS sigov.compras_habilitacao (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,tenant_id bigint NOT NULL,entidade_id bigint NOT NULL,licitacao_id bigint NOT NULL REFERENCES sigov.compras_licitacao(id),fornecedor_id bigint NOT NULL REFERENCES sigov.compras_fornecedor(id),status varchar(20) NOT NULL,justificativa text,responsavel_id bigint NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),created_by bigint NOT NULL,updated_by bigint NOT NULL,CHECK(status IN ('pendente','habilitado','inabilitado')),CHECK(status<>'inabilitado' OR nullif(btrim(justificativa),'') IS NOT NULL));
CREATE TABLE IF NOT EXISTS sigov.compras_recurso (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,tenant_id bigint NOT NULL,entidade_id bigint NOT NULL,licitacao_id bigint NOT NULL REFERENCES sigov.compras_licitacao(id),fornecedor_id bigint NOT NULL REFERENCES sigov.compras_fornecedor(id),motivo text NOT NULL,prazo_final timestamptz NOT NULL,decisao varchar(20),fundamentacao text,responsavel_id bigint,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),created_by bigint NOT NULL,updated_by bigint NOT NULL,CHECK(decisao IS NULL OR decisao IN ('deferido','indeferido')),CHECK(decisao IS NULL OR (nullif(btrim(fundamentacao),'') IS NOT NULL AND responsavel_id IS NOT NULL)));
CREATE TABLE IF NOT EXISTS sigov.compras_adjudicacao (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,tenant_id bigint NOT NULL,entidade_id bigint NOT NULL,licitacao_id bigint NOT NULL REFERENCES sigov.compras_licitacao(id),proposta_vencedora_id bigint NOT NULL REFERENCES sigov.compras_proposta(id),responsavel_id bigint NOT NULL,adjudicado_em timestamptz NOT NULL DEFAULT now(),created_at timestamptz NOT NULL DEFAULT now(),created_by bigint NOT NULL,UNIQUE(licitacao_id,proposta_vencedora_id));
CREATE TABLE IF NOT EXISTS sigov.compras_homologacao (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,tenant_id bigint NOT NULL,entidade_id bigint NOT NULL,licitacao_id bigint NOT NULL REFERENCES sigov.compras_licitacao(id),adjudicacao_id bigint NOT NULL REFERENCES sigov.compras_adjudicacao(id),responsavel_id bigint NOT NULL,homologado_em timestamptz NOT NULL DEFAULT now(),created_at timestamptz NOT NULL DEFAULT now(),created_by bigint NOT NULL,UNIQUE(licitacao_id));

CREATE TABLE IF NOT EXISTS sigov.contrato_administrativo (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id bigint NOT NULL, entidade_id bigint NOT NULL, esfera_governo varchar(10) NOT NULL,
 licitacao_id bigint REFERENCES sigov.compras_licitacao(id), ata_id bigint, fornecedor_id bigint NOT NULL REFERENCES sigov.compras_fornecedor(id), orgao_id bigint,
 unidade_gestora_id bigint NOT NULL, unidade_executora_id bigint, numero varchar(80) NOT NULL, objeto text NOT NULL, valor_inicial numeric(18,4) NOT NULL,
 saldo numeric(18,4) NOT NULL, inicio_vigencia date NOT NULL, fim_vigencia date NOT NULL, status varchar(20) NOT NULL DEFAULT 'vigente',
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by bigint NOT NULL, updated_by bigint NOT NULL,
 CHECK (esfera_governo IN ('municipal','estadual','federal')), CHECK (valor_inicial >= 0 AND saldo >= 0 AND saldo <= valor_inicial), CHECK (fim_vigencia >= inicio_vigencia),
 CHECK (status IN ('rascunho','vigente','suspenso','encerrado','rescindido','cancelado')), UNIQUE (tenant_id,entidade_id,numero)
);
CREATE TABLE IF NOT EXISTS sigov.contrato_item (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,tenant_id bigint NOT NULL,entidade_id bigint NOT NULL,contrato_id bigint NOT NULL REFERENCES sigov.contrato_administrativo(id) ON DELETE CASCADE,descricao text NOT NULL,quantidade numeric(18,4) NOT NULL,valor_unitario numeric(18,4) NOT NULL,saldo_quantidade numeric(18,4) NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),created_by bigint NOT NULL,updated_by bigint NOT NULL,CHECK(quantidade>0 AND valor_unitario>=0 AND saldo_quantidade BETWEEN 0 AND quantidade));
CREATE TABLE IF NOT EXISTS sigov.contrato_fiscal (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,tenant_id bigint NOT NULL,entidade_id bigint NOT NULL,contrato_id bigint NOT NULL REFERENCES sigov.contrato_administrativo(id),pessoa_id bigint NOT NULL,tipo varchar(12) NOT NULL,inicio_em date NOT NULL,fim_em date,ativo boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),created_by bigint NOT NULL,updated_by bigint NOT NULL,CHECK(tipo IN ('titular','substituto')),CHECK(fim_em IS NULL OR fim_em>=inicio_em));
CREATE TABLE IF NOT EXISTS sigov.contrato_gestor (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,tenant_id bigint NOT NULL,entidade_id bigint NOT NULL,contrato_id bigint NOT NULL REFERENCES sigov.contrato_administrativo(id),pessoa_id bigint NOT NULL,inicio_em date NOT NULL,fim_em date,ativo boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),created_by bigint NOT NULL,updated_by bigint NOT NULL,CHECK(fim_em IS NULL OR fim_em>=inicio_em));
CREATE TABLE IF NOT EXISTS sigov.contrato_garantia (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,tenant_id bigint NOT NULL,entidade_id bigint NOT NULL,contrato_id bigint NOT NULL REFERENCES sigov.contrato_administrativo(id),tipo varchar(30) NOT NULL,percentual numeric(5,2) NOT NULL,valor numeric(18,4) NOT NULL,inicio_em date NOT NULL,fim_em date NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),created_by bigint NOT NULL,updated_by bigint NOT NULL,CHECK(percentual BETWEEN 0 AND 100),CHECK(valor>=0),CHECK(fim_em>=inicio_em));
CREATE TABLE IF NOT EXISTS sigov.contrato_execucao_evento (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,tenant_id bigint NOT NULL,entidade_id bigint NOT NULL,contrato_id bigint NOT NULL REFERENCES sigov.contrato_administrativo(id),tipo varchar(30) NOT NULL,descricao text NOT NULL,ocorrido_em timestamptz NOT NULL,responsavel_id bigint NOT NULL,valor numeric(18,4),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),created_by bigint NOT NULL,updated_by bigint NOT NULL,CHECK(tipo IN ('ocorrencia','aceite','recebimento_provisorio','recebimento_definitivo','medicao')),CHECK(valor IS NULL OR valor>=0));
CREATE TABLE IF NOT EXISTS sigov.contrato_aditivo (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,tenant_id bigint NOT NULL,entidade_id bigint NOT NULL,contrato_id bigint NOT NULL REFERENCES sigov.contrato_administrativo(id),tipo varchar(30) NOT NULL,justificativa text NOT NULL,valor numeric(18,4) NOT NULL DEFAULT 0,percentual numeric(5,2) NOT NULL DEFAULT 0,nova_data_fim date,status varchar(20) NOT NULL DEFAULT 'pendente',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),created_by bigint NOT NULL,updated_by bigint NOT NULL,CHECK(valor>=0),CHECK(percentual BETWEEN 0 AND 100),CHECK(status IN ('pendente','aprovado','rejeitado','cancelado')));
CREATE TABLE IF NOT EXISTS sigov.contrato_apostilamento (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,tenant_id bigint NOT NULL,entidade_id bigint NOT NULL,contrato_id bigint NOT NULL REFERENCES sigov.contrato_administrativo(id),motivo text NOT NULL,valor numeric(18,4) NOT NULL DEFAULT 0,responsavel_id bigint NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),created_by bigint NOT NULL,updated_by bigint NOT NULL,CHECK(valor>=0));
CREATE TABLE IF NOT EXISTS sigov.contrato_sancao (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,tenant_id bigint NOT NULL,entidade_id bigint NOT NULL,contrato_id bigint NOT NULL REFERENCES sigov.contrato_administrativo(id),fornecedor_id bigint NOT NULL REFERENCES sigov.compras_fornecedor(id),motivo text NOT NULL,fundamento text NOT NULL,inicio_em date NOT NULL,fim_em date NOT NULL,responsavel_id bigint NOT NULL,status varchar(20) NOT NULL DEFAULT 'aberta',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),created_by bigint NOT NULL,updated_by bigint NOT NULL,CHECK(fim_em>=inicio_em),CHECK(status IN ('aberta','em_recurso','aplicada','revogada','encerrada')));
CREATE TABLE IF NOT EXISTS sigov.contrato_vinculo_financeiro (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,tenant_id bigint NOT NULL,entidade_id bigint NOT NULL,contrato_id bigint NOT NULL REFERENCES sigov.contrato_administrativo(id),tipo varchar(20) NOT NULL,referencia_id bigint NOT NULL,valor numeric(18,4) NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),created_by bigint NOT NULL,CHECK(tipo IN ('empenho','liquidacao','pagamento')),CHECK(valor>=0),UNIQUE(contrato_id,tipo,referencia_id));
CREATE TABLE IF NOT EXISTS sigov.contrato_vinculo_ged (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,tenant_id bigint NOT NULL,entidade_id bigint NOT NULL,contrato_id bigint NOT NULL REFERENCES sigov.contrato_administrativo(id),documento_id bigint NOT NULL,tipo_documento varchar(40) NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),created_by bigint NOT NULL,UNIQUE(contrato_id,documento_id));

-- A tabela de atas legada já existe; estes campos tornam seu contexto multi-esfera explícito sem conversão destrutiva.
ALTER TABLE IF EXISTS sigov.compras_ata_registro_preco ADD COLUMN IF NOT EXISTS esfera_governo varchar(10);
ALTER TABLE IF EXISTS sigov.compras_ata_registro_preco ADD COLUMN IF NOT EXISTS orgao_id bigint;
ALTER TABLE IF EXISTS sigov.compras_ata_registro_preco ADD COLUMN IF NOT EXISTS unidade_gestora_id bigint;
ALTER TABLE IF EXISTS sigov.compras_ata_registro_preco ADD COLUMN IF NOT EXISTS unidade_executora_id bigint;

CREATE INDEX IF NOT EXISTS ix_compras_pca_contexto ON sigov.compras_plano_contratacao_anual(tenant_id,entidade_id,esfera_governo,exercicio_id,status);
CREATE INDEX IF NOT EXISTS ix_compras_demanda_contexto ON sigov.compras_demanda(tenant_id,entidade_id,esfera_governo,orgao_id,unidade_gestora_id,unidade_executora_id,exercicio_id,status);
CREATE INDEX IF NOT EXISTS ix_compras_pesquisa_demanda ON sigov.compras_pesquisa_preco(tenant_id,entidade_id,demanda_id,status);
CREATE INDEX IF NOT EXISTS ix_compras_licitacao_contexto ON sigov.compras_licitacao(tenant_id,entidade_id,esfera_governo,orgao_id,unidade_gestora_id,unidade_executora_id,status,data_disputa);
CREATE INDEX IF NOT EXISTS ix_compras_proposta_fornecedor ON sigov.compras_proposta(tenant_id,entidade_id,licitacao_id,fornecedor_id,status);
CREATE INDEX IF NOT EXISTS ix_contrato_contexto ON sigov.contrato_administrativo(tenant_id,entidade_id,esfera_governo,orgao_id,unidade_gestora_id,unidade_executora_id,fornecedor_id,status,fim_vigencia);
CREATE INDEX IF NOT EXISTS ix_contrato_fiscal_ativo ON sigov.contrato_fiscal(tenant_id,entidade_id,contrato_id,ativo);
CREATE INDEX IF NOT EXISTS ix_contrato_sancao_status ON sigov.contrato_sancao(tenant_id,entidade_id,fornecedor_id,status,inicio_em);

INSERT INTO sigov.permissao(modulo,chave,recurso,acao,descricao,ativo,is_deleted)
SELECT 'compras',v.chave,'compras',CASE WHEN v.chave LIKE '%VIEW' THEN 'visualizar' WHEN v.chave LIKE '%EXPORT' THEN 'exportar' WHEN v.chave LIKE '%APPROVE' THEN 'aprovar' ELSE 'gerenciar' END,v.descricao,true,false
FROM (VALUES
 ('COMPRAS_DASHBOARD_VIEW','Visualizar dashboard de compras e contratos'),('COMPRAS_PCA_VIEW','Visualizar plano anual de contratações'),('COMPRAS_PCA_MANAGE','Gerenciar plano anual de contratações'),
 ('COMPRAS_DEMANDA_VIEW','Visualizar demandas'),('COMPRAS_DEMANDA_MANAGE','Gerenciar demandas'),('COMPRAS_PLANEJAMENTO_MANAGE','Gerenciar planejamento da contratação'),
 ('COMPRAS_PESQUISA_PRECO_VIEW','Visualizar pesquisas de preço'),('COMPRAS_PESQUISA_PRECO_MANAGE','Gerenciar pesquisas de preço'),('COMPRAS_PROCESSO_VIEW','Visualizar processos de contratação'),
 ('COMPRAS_PROCESSO_MANAGE','Gerenciar processos de contratação'),('LICITACAO_VIEW','Visualizar licitações'),('LICITACAO_MANAGE','Gerenciar licitações'),
 ('LICITACAO_SESSAO_MANAGE','Gerenciar sessões'),('LICITACAO_JULGAMENTO_MANAGE','Gerenciar julgamentos'),('LICITACAO_HOMOLOGACAO_APPROVE','Aprovar homologações'),
 ('CONTRATO_VIEW','Visualizar contratos'),('CONTRATO_MANAGE','Gerenciar contratos'),('CONTRATO_FISCAL_MANAGE','Gerenciar fiscalização contratual'),
 ('CONTRATO_ADITIVO_MANAGE','Gerenciar aditivos'),('CONTRATO_SANCAO_MANAGE','Gerenciar sanções'),('ATA_REGISTRO_PRECO_VIEW','Visualizar atas de registro de preço'),
 ('ATA_REGISTRO_PRECO_MANAGE','Gerenciar atas de registro de preço'),('COMPRAS_RELATORIO_EXPORT','Exportar relatórios de compras e contratos')) v(chave,descricao)
WHERE NOT EXISTS (SELECT 1 FROM sigov.permissao p WHERE p.chave=v.chave);
