-- EXP24 Royalties360 - PostgreSQL 16+, idempotente, não destrutivo
create schema if not exists sigov;

create table if not exists sigov.royalties_parametro_normativo(
 id bigint generated by default as identity primary key, tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint, unidade_id bigint,
 codigo text not null, nome text not null, descricao text, status text not null default 'RASCUNHO', tipo_receita text, competencia date, data_referencia date,
 fonte_recurso_id bigint, parametro_id bigint, projeto_id bigint, pessoa_juridica_id bigint, programa_id bigint, acao_id bigint, contrato_id bigint, receita_arrecadacao_id bigint, empenho_id bigint, liquidacao_id bigint, pagamento_id bigint,
 saldo_reservado numeric(18,2) not null default 0 check(saldo_reservado>=0), saldo_empenhado numeric(18,2) not null default 0 check(saldo_empenhado>=0), saldo_liquidado numeric(18,2) not null default 0 check(saldo_liquidado>=0), saldo_pago numeric(18,2) not null default 0 check(saldo_pago>=0), saldo_disponivel numeric(18,2) not null default 0 check(saldo_disponivel>=0),
 valor numeric(18,2) not null default 0 check(valor>=0), valor_bruto numeric(18,2) not null default 0 check(valor_bruto>=0), deducoes numeric(18,2) not null default 0 check(deducoes>=0), valor_liquido numeric(18,2) not null default 0 check(valor_liquido>=0),
 percentual numeric(7,4) check(percentual is null or percentual between 0 and 100), cenario text, fonte_normativa text, vigencia_inicio date, vigencia_fim date, formula_textual text, origem_dado text,
 justificativa text, premissas text, visibilidade text not null default 'INTERNA', publicavel boolean not null default false, data_fim_prevista date,
 created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz, updated_by bigint,
 check(tipo_receita is null or tipo_receita in('ROYALTIES','PARTICIPACAO_ESPECIAL','COMPENSACAO','BONUS','FUNDO_ESPECIAL','OUTRA')),
 check(cenario is null or cenario in('CONSERVADOR','BASE','OTIMISTA')), check(vigencia_fim is null or vigencia_inicio is null or vigencia_fim>=vigencia_inicio),
 check(visibilidade in('INTERNA','PUBLICA','SIGILOSA'))
);
create index if not exists ix_royalties_parametro_normativo_contexto on sigov.royalties_parametro_normativo(tenant_id,entidade_id,status,data_referencia);
create index if not exists ix_royalties_parametro_normativo_filtros on sigov.royalties_parametro_normativo(entidade_id,exercicio_id,competencia,fonte_recurso_id,tipo_receita,projeto_id);

create table if not exists sigov.royalties_fonte_dado(
 id bigint generated by default as identity primary key, tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint, unidade_id bigint,
 codigo text not null, nome text not null, descricao text, status text not null default 'RASCUNHO', tipo_receita text, competencia date, data_referencia date,
 fonte_recurso_id bigint, parametro_id bigint, projeto_id bigint, pessoa_juridica_id bigint, programa_id bigint, acao_id bigint, contrato_id bigint, receita_arrecadacao_id bigint, empenho_id bigint, liquidacao_id bigint, pagamento_id bigint,
 saldo_reservado numeric(18,2) not null default 0 check(saldo_reservado>=0), saldo_empenhado numeric(18,2) not null default 0 check(saldo_empenhado>=0), saldo_liquidado numeric(18,2) not null default 0 check(saldo_liquidado>=0), saldo_pago numeric(18,2) not null default 0 check(saldo_pago>=0), saldo_disponivel numeric(18,2) not null default 0 check(saldo_disponivel>=0),
 valor numeric(18,2) not null default 0 check(valor>=0), valor_bruto numeric(18,2) not null default 0 check(valor_bruto>=0), deducoes numeric(18,2) not null default 0 check(deducoes>=0), valor_liquido numeric(18,2) not null default 0 check(valor_liquido>=0),
 percentual numeric(7,4) check(percentual is null or percentual between 0 and 100), cenario text, fonte_normativa text, vigencia_inicio date, vigencia_fim date, formula_textual text, origem_dado text,
 justificativa text, premissas text, visibilidade text not null default 'INTERNA', publicavel boolean not null default false, data_fim_prevista date,
 created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz, updated_by bigint,
 check(tipo_receita is null or tipo_receita in('ROYALTIES','PARTICIPACAO_ESPECIAL','COMPENSACAO','BONUS','FUNDO_ESPECIAL','OUTRA')),
 check(cenario is null or cenario in('CONSERVADOR','BASE','OTIMISTA')), check(vigencia_fim is null or vigencia_inicio is null or vigencia_fim>=vigencia_inicio),
 check(visibilidade in('INTERNA','PUBLICA','SIGILOSA'))
);
create index if not exists ix_royalties_fonte_dado_contexto on sigov.royalties_fonte_dado(tenant_id,entidade_id,status,data_referencia);
create index if not exists ix_royalties_fonte_dado_filtros on sigov.royalties_fonte_dado(entidade_id,exercicio_id,competencia,fonte_recurso_id,tipo_receita,projeto_id);

create table if not exists sigov.royalties_area_exploracao(
 id bigint generated by default as identity primary key, tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint, unidade_id bigint,
 codigo text not null, nome text not null, descricao text, status text not null default 'RASCUNHO', tipo_receita text, competencia date, data_referencia date,
 fonte_recurso_id bigint, parametro_id bigint, projeto_id bigint, pessoa_juridica_id bigint, programa_id bigint, acao_id bigint, contrato_id bigint, receita_arrecadacao_id bigint, empenho_id bigint, liquidacao_id bigint, pagamento_id bigint,
 saldo_reservado numeric(18,2) not null default 0 check(saldo_reservado>=0), saldo_empenhado numeric(18,2) not null default 0 check(saldo_empenhado>=0), saldo_liquidado numeric(18,2) not null default 0 check(saldo_liquidado>=0), saldo_pago numeric(18,2) not null default 0 check(saldo_pago>=0), saldo_disponivel numeric(18,2) not null default 0 check(saldo_disponivel>=0),
 valor numeric(18,2) not null default 0 check(valor>=0), valor_bruto numeric(18,2) not null default 0 check(valor_bruto>=0), deducoes numeric(18,2) not null default 0 check(deducoes>=0), valor_liquido numeric(18,2) not null default 0 check(valor_liquido>=0),
 percentual numeric(7,4) check(percentual is null or percentual between 0 and 100), cenario text, fonte_normativa text, vigencia_inicio date, vigencia_fim date, formula_textual text, origem_dado text,
 justificativa text, premissas text, visibilidade text not null default 'INTERNA', publicavel boolean not null default false, data_fim_prevista date,
 created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz, updated_by bigint,
 check(tipo_receita is null or tipo_receita in('ROYALTIES','PARTICIPACAO_ESPECIAL','COMPENSACAO','BONUS','FUNDO_ESPECIAL','OUTRA')),
 check(cenario is null or cenario in('CONSERVADOR','BASE','OTIMISTA')), check(vigencia_fim is null or vigencia_inicio is null or vigencia_fim>=vigencia_inicio),
 check(visibilidade in('INTERNA','PUBLICA','SIGILOSA'))
);
create index if not exists ix_royalties_area_exploracao_contexto on sigov.royalties_area_exploracao(tenant_id,entidade_id,status,data_referencia);
create index if not exists ix_royalties_area_exploracao_filtros on sigov.royalties_area_exploracao(entidade_id,exercicio_id,competencia,fonte_recurso_id,tipo_receita,projeto_id);

create table if not exists sigov.royalties_campo_origem(
 id bigint generated by default as identity primary key, tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint, unidade_id bigint,
 codigo text not null, nome text not null, descricao text, status text not null default 'RASCUNHO', tipo_receita text, competencia date, data_referencia date,
 fonte_recurso_id bigint, parametro_id bigint, projeto_id bigint, pessoa_juridica_id bigint, programa_id bigint, acao_id bigint, contrato_id bigint, receita_arrecadacao_id bigint, empenho_id bigint, liquidacao_id bigint, pagamento_id bigint,
 saldo_reservado numeric(18,2) not null default 0 check(saldo_reservado>=0), saldo_empenhado numeric(18,2) not null default 0 check(saldo_empenhado>=0), saldo_liquidado numeric(18,2) not null default 0 check(saldo_liquidado>=0), saldo_pago numeric(18,2) not null default 0 check(saldo_pago>=0), saldo_disponivel numeric(18,2) not null default 0 check(saldo_disponivel>=0),
 valor numeric(18,2) not null default 0 check(valor>=0), valor_bruto numeric(18,2) not null default 0 check(valor_bruto>=0), deducoes numeric(18,2) not null default 0 check(deducoes>=0), valor_liquido numeric(18,2) not null default 0 check(valor_liquido>=0),
 percentual numeric(7,4) check(percentual is null or percentual between 0 and 100), cenario text, fonte_normativa text, vigencia_inicio date, vigencia_fim date, formula_textual text, origem_dado text,
 justificativa text, premissas text, visibilidade text not null default 'INTERNA', publicavel boolean not null default false, data_fim_prevista date,
 created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz, updated_by bigint,
 check(tipo_receita is null or tipo_receita in('ROYALTIES','PARTICIPACAO_ESPECIAL','COMPENSACAO','BONUS','FUNDO_ESPECIAL','OUTRA')),
 check(cenario is null or cenario in('CONSERVADOR','BASE','OTIMISTA')), check(vigencia_fim is null or vigencia_inicio is null or vigencia_fim>=vigencia_inicio),
 check(visibilidade in('INTERNA','PUBLICA','SIGILOSA'))
);
create index if not exists ix_royalties_campo_origem_contexto on sigov.royalties_campo_origem(tenant_id,entidade_id,status,data_referencia);
create index if not exists ix_royalties_campo_origem_filtros on sigov.royalties_campo_origem(entidade_id,exercicio_id,competencia,fonte_recurso_id,tipo_receita,projeto_id);

create table if not exists sigov.royalties_receita_previsao(
 id bigint generated by default as identity primary key, tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint, unidade_id bigint,
 codigo text not null, nome text not null, descricao text, status text not null default 'RASCUNHO', tipo_receita text, competencia date, data_referencia date,
 fonte_recurso_id bigint, parametro_id bigint, projeto_id bigint, pessoa_juridica_id bigint, programa_id bigint, acao_id bigint, contrato_id bigint, receita_arrecadacao_id bigint, empenho_id bigint, liquidacao_id bigint, pagamento_id bigint,
 saldo_reservado numeric(18,2) not null default 0 check(saldo_reservado>=0), saldo_empenhado numeric(18,2) not null default 0 check(saldo_empenhado>=0), saldo_liquidado numeric(18,2) not null default 0 check(saldo_liquidado>=0), saldo_pago numeric(18,2) not null default 0 check(saldo_pago>=0), saldo_disponivel numeric(18,2) not null default 0 check(saldo_disponivel>=0),
 valor numeric(18,2) not null default 0 check(valor>=0), valor_bruto numeric(18,2) not null default 0 check(valor_bruto>=0), deducoes numeric(18,2) not null default 0 check(deducoes>=0), valor_liquido numeric(18,2) not null default 0 check(valor_liquido>=0),
 percentual numeric(7,4) check(percentual is null or percentual between 0 and 100), cenario text, fonte_normativa text, vigencia_inicio date, vigencia_fim date, formula_textual text, origem_dado text,
 justificativa text, premissas text, visibilidade text not null default 'INTERNA', publicavel boolean not null default false, data_fim_prevista date,
 created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz, updated_by bigint,
 check(tipo_receita is null or tipo_receita in('ROYALTIES','PARTICIPACAO_ESPECIAL','COMPENSACAO','BONUS','FUNDO_ESPECIAL','OUTRA')),
 check(cenario is null or cenario in('CONSERVADOR','BASE','OTIMISTA')), check(vigencia_fim is null or vigencia_inicio is null or vigencia_fim>=vigencia_inicio),
 check(visibilidade in('INTERNA','PUBLICA','SIGILOSA'))
);
create index if not exists ix_royalties_receita_previsao_contexto on sigov.royalties_receita_previsao(tenant_id,entidade_id,status,data_referencia);
create index if not exists ix_royalties_receita_previsao_filtros on sigov.royalties_receita_previsao(entidade_id,exercicio_id,competencia,fonte_recurso_id,tipo_receita,projeto_id);

create table if not exists sigov.royalties_receita_realizada(
 id bigint generated by default as identity primary key, tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint, unidade_id bigint,
 codigo text not null, nome text not null, descricao text, status text not null default 'RASCUNHO', tipo_receita text, competencia date, data_referencia date,
 fonte_recurso_id bigint, parametro_id bigint, projeto_id bigint, pessoa_juridica_id bigint, programa_id bigint, acao_id bigint, contrato_id bigint, receita_arrecadacao_id bigint, empenho_id bigint, liquidacao_id bigint, pagamento_id bigint,
 saldo_reservado numeric(18,2) not null default 0 check(saldo_reservado>=0), saldo_empenhado numeric(18,2) not null default 0 check(saldo_empenhado>=0), saldo_liquidado numeric(18,2) not null default 0 check(saldo_liquidado>=0), saldo_pago numeric(18,2) not null default 0 check(saldo_pago>=0), saldo_disponivel numeric(18,2) not null default 0 check(saldo_disponivel>=0),
 valor numeric(18,2) not null default 0 check(valor>=0), valor_bruto numeric(18,2) not null default 0 check(valor_bruto>=0), deducoes numeric(18,2) not null default 0 check(deducoes>=0), valor_liquido numeric(18,2) not null default 0 check(valor_liquido>=0),
 percentual numeric(7,4) check(percentual is null or percentual between 0 and 100), cenario text, fonte_normativa text, vigencia_inicio date, vigencia_fim date, formula_textual text, origem_dado text,
 justificativa text, premissas text, visibilidade text not null default 'INTERNA', publicavel boolean not null default false, data_fim_prevista date,
 created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz, updated_by bigint,
 check(tipo_receita is null or tipo_receita in('ROYALTIES','PARTICIPACAO_ESPECIAL','COMPENSACAO','BONUS','FUNDO_ESPECIAL','OUTRA')),
 check(cenario is null or cenario in('CONSERVADOR','BASE','OTIMISTA')), check(vigencia_fim is null or vigencia_inicio is null or vigencia_fim>=vigencia_inicio),
 check(visibilidade in('INTERNA','PUBLICA','SIGILOSA'))
);
create index if not exists ix_royalties_receita_realizada_contexto on sigov.royalties_receita_realizada(tenant_id,entidade_id,status,data_referencia);
create index if not exists ix_royalties_receita_realizada_filtros on sigov.royalties_receita_realizada(entidade_id,exercicio_id,competencia,fonte_recurso_id,tipo_receita,projeto_id);

create table if not exists sigov.royalties_repasse(
 id bigint generated by default as identity primary key, tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint, unidade_id bigint,
 codigo text not null, nome text not null, descricao text, status text not null default 'RASCUNHO', tipo_receita text, competencia date, data_referencia date,
 fonte_recurso_id bigint, parametro_id bigint, projeto_id bigint, pessoa_juridica_id bigint, programa_id bigint, acao_id bigint, contrato_id bigint, receita_arrecadacao_id bigint, empenho_id bigint, liquidacao_id bigint, pagamento_id bigint,
 saldo_reservado numeric(18,2) not null default 0 check(saldo_reservado>=0), saldo_empenhado numeric(18,2) not null default 0 check(saldo_empenhado>=0), saldo_liquidado numeric(18,2) not null default 0 check(saldo_liquidado>=0), saldo_pago numeric(18,2) not null default 0 check(saldo_pago>=0), saldo_disponivel numeric(18,2) not null default 0 check(saldo_disponivel>=0),
 valor numeric(18,2) not null default 0 check(valor>=0), valor_bruto numeric(18,2) not null default 0 check(valor_bruto>=0), deducoes numeric(18,2) not null default 0 check(deducoes>=0), valor_liquido numeric(18,2) not null default 0 check(valor_liquido>=0),
 percentual numeric(7,4) check(percentual is null or percentual between 0 and 100), cenario text, fonte_normativa text, vigencia_inicio date, vigencia_fim date, formula_textual text, origem_dado text,
 justificativa text, premissas text, visibilidade text not null default 'INTERNA', publicavel boolean not null default false, data_fim_prevista date,
 created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz, updated_by bigint,
 check(tipo_receita is null or tipo_receita in('ROYALTIES','PARTICIPACAO_ESPECIAL','COMPENSACAO','BONUS','FUNDO_ESPECIAL','OUTRA')),
 check(cenario is null or cenario in('CONSERVADOR','BASE','OTIMISTA')), check(vigencia_fim is null or vigencia_inicio is null or vigencia_fim>=vigencia_inicio),
 check(visibilidade in('INTERNA','PUBLICA','SIGILOSA'))
);
create index if not exists ix_royalties_repasse_contexto on sigov.royalties_repasse(tenant_id,entidade_id,status,data_referencia);
create index if not exists ix_royalties_repasse_filtros on sigov.royalties_repasse(entidade_id,exercicio_id,competencia,fonte_recurso_id,tipo_receita,projeto_id);

create table if not exists sigov.royalties_conciliacao(
 id bigint generated by default as identity primary key, tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint, unidade_id bigint,
 codigo text not null, nome text not null, descricao text, status text not null default 'RASCUNHO', tipo_receita text, competencia date, data_referencia date,
 fonte_recurso_id bigint, parametro_id bigint, projeto_id bigint, pessoa_juridica_id bigint, programa_id bigint, acao_id bigint, contrato_id bigint, receita_arrecadacao_id bigint, empenho_id bigint, liquidacao_id bigint, pagamento_id bigint,
 saldo_reservado numeric(18,2) not null default 0 check(saldo_reservado>=0), saldo_empenhado numeric(18,2) not null default 0 check(saldo_empenhado>=0), saldo_liquidado numeric(18,2) not null default 0 check(saldo_liquidado>=0), saldo_pago numeric(18,2) not null default 0 check(saldo_pago>=0), saldo_disponivel numeric(18,2) not null default 0 check(saldo_disponivel>=0),
 valor numeric(18,2) not null default 0 check(valor>=0), valor_bruto numeric(18,2) not null default 0 check(valor_bruto>=0), deducoes numeric(18,2) not null default 0 check(deducoes>=0), valor_liquido numeric(18,2) not null default 0 check(valor_liquido>=0),
 percentual numeric(7,4) check(percentual is null or percentual between 0 and 100), cenario text, fonte_normativa text, vigencia_inicio date, vigencia_fim date, formula_textual text, origem_dado text,
 justificativa text, premissas text, visibilidade text not null default 'INTERNA', publicavel boolean not null default false, data_fim_prevista date,
 created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz, updated_by bigint,
 check(tipo_receita is null or tipo_receita in('ROYALTIES','PARTICIPACAO_ESPECIAL','COMPENSACAO','BONUS','FUNDO_ESPECIAL','OUTRA')),
 check(cenario is null or cenario in('CONSERVADOR','BASE','OTIMISTA')), check(vigencia_fim is null or vigencia_inicio is null or vigencia_fim>=vigencia_inicio),
 check(visibilidade in('INTERNA','PUBLICA','SIGILOSA'))
);
create index if not exists ix_royalties_conciliacao_contexto on sigov.royalties_conciliacao(tenant_id,entidade_id,status,data_referencia);
create index if not exists ix_royalties_conciliacao_filtros on sigov.royalties_conciliacao(entidade_id,exercicio_id,competencia,fonte_recurso_id,tipo_receita,projeto_id);

create table if not exists sigov.royalties_plano_aplicacao(
 id bigint generated by default as identity primary key, tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint, unidade_id bigint,
 codigo text not null, nome text not null, descricao text, status text not null default 'RASCUNHO', tipo_receita text, competencia date, data_referencia date,
 fonte_recurso_id bigint, parametro_id bigint, projeto_id bigint, pessoa_juridica_id bigint, programa_id bigint, acao_id bigint, contrato_id bigint, receita_arrecadacao_id bigint, empenho_id bigint, liquidacao_id bigint, pagamento_id bigint,
 saldo_reservado numeric(18,2) not null default 0 check(saldo_reservado>=0), saldo_empenhado numeric(18,2) not null default 0 check(saldo_empenhado>=0), saldo_liquidado numeric(18,2) not null default 0 check(saldo_liquidado>=0), saldo_pago numeric(18,2) not null default 0 check(saldo_pago>=0), saldo_disponivel numeric(18,2) not null default 0 check(saldo_disponivel>=0),
 valor numeric(18,2) not null default 0 check(valor>=0), valor_bruto numeric(18,2) not null default 0 check(valor_bruto>=0), deducoes numeric(18,2) not null default 0 check(deducoes>=0), valor_liquido numeric(18,2) not null default 0 check(valor_liquido>=0),
 percentual numeric(7,4) check(percentual is null or percentual between 0 and 100), cenario text, fonte_normativa text, vigencia_inicio date, vigencia_fim date, formula_textual text, origem_dado text,
 justificativa text, premissas text, visibilidade text not null default 'INTERNA', publicavel boolean not null default false, data_fim_prevista date,
 created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz, updated_by bigint,
 check(tipo_receita is null or tipo_receita in('ROYALTIES','PARTICIPACAO_ESPECIAL','COMPENSACAO','BONUS','FUNDO_ESPECIAL','OUTRA')),
 check(cenario is null or cenario in('CONSERVADOR','BASE','OTIMISTA')), check(vigencia_fim is null or vigencia_inicio is null or vigencia_fim>=vigencia_inicio),
 check(visibilidade in('INTERNA','PUBLICA','SIGILOSA'))
);
create index if not exists ix_royalties_plano_aplicacao_contexto on sigov.royalties_plano_aplicacao(tenant_id,entidade_id,status,data_referencia);
create index if not exists ix_royalties_plano_aplicacao_filtros on sigov.royalties_plano_aplicacao(entidade_id,exercicio_id,competencia,fonte_recurso_id,tipo_receita,projeto_id);

create table if not exists sigov.royalties_projeto(
 id bigint generated by default as identity primary key, tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint, unidade_id bigint,
 codigo text not null, nome text not null, descricao text, status text not null default 'RASCUNHO', tipo_receita text, competencia date, data_referencia date,
 fonte_recurso_id bigint, parametro_id bigint, projeto_id bigint, pessoa_juridica_id bigint, programa_id bigint, acao_id bigint, contrato_id bigint, receita_arrecadacao_id bigint, empenho_id bigint, liquidacao_id bigint, pagamento_id bigint,
 saldo_reservado numeric(18,2) not null default 0 check(saldo_reservado>=0), saldo_empenhado numeric(18,2) not null default 0 check(saldo_empenhado>=0), saldo_liquidado numeric(18,2) not null default 0 check(saldo_liquidado>=0), saldo_pago numeric(18,2) not null default 0 check(saldo_pago>=0), saldo_disponivel numeric(18,2) not null default 0 check(saldo_disponivel>=0),
 valor numeric(18,2) not null default 0 check(valor>=0), valor_bruto numeric(18,2) not null default 0 check(valor_bruto>=0), deducoes numeric(18,2) not null default 0 check(deducoes>=0), valor_liquido numeric(18,2) not null default 0 check(valor_liquido>=0),
 percentual numeric(7,4) check(percentual is null or percentual between 0 and 100), cenario text, fonte_normativa text, vigencia_inicio date, vigencia_fim date, formula_textual text, origem_dado text,
 justificativa text, premissas text, visibilidade text not null default 'INTERNA', publicavel boolean not null default false, data_fim_prevista date,
 created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz, updated_by bigint,
 check(tipo_receita is null or tipo_receita in('ROYALTIES','PARTICIPACAO_ESPECIAL','COMPENSACAO','BONUS','FUNDO_ESPECIAL','OUTRA')),
 check(cenario is null or cenario in('CONSERVADOR','BASE','OTIMISTA')), check(vigencia_fim is null or vigencia_inicio is null or vigencia_fim>=vigencia_inicio),
 check(visibilidade in('INTERNA','PUBLICA','SIGILOSA'))
);
create index if not exists ix_royalties_projeto_contexto on sigov.royalties_projeto(tenant_id,entidade_id,status,data_referencia);
create index if not exists ix_royalties_projeto_filtros on sigov.royalties_projeto(entidade_id,exercicio_id,competencia,fonte_recurso_id,tipo_receita,projeto_id);

create table if not exists sigov.royalties_projeto_meta(
 id bigint generated by default as identity primary key, tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint, unidade_id bigint,
 codigo text not null, nome text not null, descricao text, status text not null default 'RASCUNHO', tipo_receita text, competencia date, data_referencia date,
 fonte_recurso_id bigint, parametro_id bigint, projeto_id bigint, pessoa_juridica_id bigint, programa_id bigint, acao_id bigint, contrato_id bigint, receita_arrecadacao_id bigint, empenho_id bigint, liquidacao_id bigint, pagamento_id bigint,
 saldo_reservado numeric(18,2) not null default 0 check(saldo_reservado>=0), saldo_empenhado numeric(18,2) not null default 0 check(saldo_empenhado>=0), saldo_liquidado numeric(18,2) not null default 0 check(saldo_liquidado>=0), saldo_pago numeric(18,2) not null default 0 check(saldo_pago>=0), saldo_disponivel numeric(18,2) not null default 0 check(saldo_disponivel>=0),
 valor numeric(18,2) not null default 0 check(valor>=0), valor_bruto numeric(18,2) not null default 0 check(valor_bruto>=0), deducoes numeric(18,2) not null default 0 check(deducoes>=0), valor_liquido numeric(18,2) not null default 0 check(valor_liquido>=0),
 percentual numeric(7,4) check(percentual is null or percentual between 0 and 100), cenario text, fonte_normativa text, vigencia_inicio date, vigencia_fim date, formula_textual text, origem_dado text,
 justificativa text, premissas text, visibilidade text not null default 'INTERNA', publicavel boolean not null default false, data_fim_prevista date,
 created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz, updated_by bigint,
 check(tipo_receita is null or tipo_receita in('ROYALTIES','PARTICIPACAO_ESPECIAL','COMPENSACAO','BONUS','FUNDO_ESPECIAL','OUTRA')),
 check(cenario is null or cenario in('CONSERVADOR','BASE','OTIMISTA')), check(vigencia_fim is null or vigencia_inicio is null or vigencia_fim>=vigencia_inicio),
 check(visibilidade in('INTERNA','PUBLICA','SIGILOSA'))
);
create index if not exists ix_royalties_projeto_meta_contexto on sigov.royalties_projeto_meta(tenant_id,entidade_id,status,data_referencia);
create index if not exists ix_royalties_projeto_meta_filtros on sigov.royalties_projeto_meta(entidade_id,exercicio_id,competencia,fonte_recurso_id,tipo_receita,projeto_id);

create table if not exists sigov.royalties_projeto_acompanhamento(
 id bigint generated by default as identity primary key, tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint, unidade_id bigint,
 codigo text not null, nome text not null, descricao text, status text not null default 'RASCUNHO', tipo_receita text, competencia date, data_referencia date,
 fonte_recurso_id bigint, parametro_id bigint, projeto_id bigint, pessoa_juridica_id bigint, programa_id bigint, acao_id bigint, contrato_id bigint, receita_arrecadacao_id bigint, empenho_id bigint, liquidacao_id bigint, pagamento_id bigint,
 saldo_reservado numeric(18,2) not null default 0 check(saldo_reservado>=0), saldo_empenhado numeric(18,2) not null default 0 check(saldo_empenhado>=0), saldo_liquidado numeric(18,2) not null default 0 check(saldo_liquidado>=0), saldo_pago numeric(18,2) not null default 0 check(saldo_pago>=0), saldo_disponivel numeric(18,2) not null default 0 check(saldo_disponivel>=0),
 valor numeric(18,2) not null default 0 check(valor>=0), valor_bruto numeric(18,2) not null default 0 check(valor_bruto>=0), deducoes numeric(18,2) not null default 0 check(deducoes>=0), valor_liquido numeric(18,2) not null default 0 check(valor_liquido>=0),
 percentual numeric(7,4) check(percentual is null or percentual between 0 and 100), cenario text, fonte_normativa text, vigencia_inicio date, vigencia_fim date, formula_textual text, origem_dado text,
 justificativa text, premissas text, visibilidade text not null default 'INTERNA', publicavel boolean not null default false, data_fim_prevista date,
 created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz, updated_by bigint,
 check(tipo_receita is null or tipo_receita in('ROYALTIES','PARTICIPACAO_ESPECIAL','COMPENSACAO','BONUS','FUNDO_ESPECIAL','OUTRA')),
 check(cenario is null or cenario in('CONSERVADOR','BASE','OTIMISTA')), check(vigencia_fim is null or vigencia_inicio is null or vigencia_fim>=vigencia_inicio),
 check(visibilidade in('INTERNA','PUBLICA','SIGILOSA'))
);
create index if not exists ix_royalties_projeto_acompanhamento_contexto on sigov.royalties_projeto_acompanhamento(tenant_id,entidade_id,status,data_referencia);
create index if not exists ix_royalties_projeto_acompanhamento_filtros on sigov.royalties_projeto_acompanhamento(entidade_id,exercicio_id,competencia,fonte_recurso_id,tipo_receita,projeto_id);

create table if not exists sigov.royalties_execucao_financeira_vinculo(
 id bigint generated by default as identity primary key, tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint, unidade_id bigint,
 codigo text not null, nome text not null, descricao text, status text not null default 'RASCUNHO', tipo_receita text, competencia date, data_referencia date,
 fonte_recurso_id bigint, parametro_id bigint, projeto_id bigint, pessoa_juridica_id bigint, programa_id bigint, acao_id bigint, contrato_id bigint, receita_arrecadacao_id bigint, empenho_id bigint, liquidacao_id bigint, pagamento_id bigint,
 saldo_reservado numeric(18,2) not null default 0 check(saldo_reservado>=0), saldo_empenhado numeric(18,2) not null default 0 check(saldo_empenhado>=0), saldo_liquidado numeric(18,2) not null default 0 check(saldo_liquidado>=0), saldo_pago numeric(18,2) not null default 0 check(saldo_pago>=0), saldo_disponivel numeric(18,2) not null default 0 check(saldo_disponivel>=0),
 valor numeric(18,2) not null default 0 check(valor>=0), valor_bruto numeric(18,2) not null default 0 check(valor_bruto>=0), deducoes numeric(18,2) not null default 0 check(deducoes>=0), valor_liquido numeric(18,2) not null default 0 check(valor_liquido>=0),
 percentual numeric(7,4) check(percentual is null or percentual between 0 and 100), cenario text, fonte_normativa text, vigencia_inicio date, vigencia_fim date, formula_textual text, origem_dado text,
 justificativa text, premissas text, visibilidade text not null default 'INTERNA', publicavel boolean not null default false, data_fim_prevista date,
 created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz, updated_by bigint,
 check(tipo_receita is null or tipo_receita in('ROYALTIES','PARTICIPACAO_ESPECIAL','COMPENSACAO','BONUS','FUNDO_ESPECIAL','OUTRA')),
 check(cenario is null or cenario in('CONSERVADOR','BASE','OTIMISTA')), check(vigencia_fim is null or vigencia_inicio is null or vigencia_fim>=vigencia_inicio),
 check(visibilidade in('INTERNA','PUBLICA','SIGILOSA'))
);
create index if not exists ix_royalties_execucao_financeira_vinculo_contexto on sigov.royalties_execucao_financeira_vinculo(tenant_id,entidade_id,status,data_referencia);
create index if not exists ix_royalties_execucao_financeira_vinculo_filtros on sigov.royalties_execucao_financeira_vinculo(entidade_id,exercicio_id,competencia,fonte_recurso_id,tipo_receita,projeto_id);

create table if not exists sigov.royalties_transparencia_publicacao(
 id bigint generated by default as identity primary key, tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint, unidade_id bigint,
 codigo text not null, nome text not null, descricao text, status text not null default 'RASCUNHO', tipo_receita text, competencia date, data_referencia date,
 fonte_recurso_id bigint, parametro_id bigint, projeto_id bigint, pessoa_juridica_id bigint, programa_id bigint, acao_id bigint, contrato_id bigint, receita_arrecadacao_id bigint, empenho_id bigint, liquidacao_id bigint, pagamento_id bigint,
 saldo_reservado numeric(18,2) not null default 0 check(saldo_reservado>=0), saldo_empenhado numeric(18,2) not null default 0 check(saldo_empenhado>=0), saldo_liquidado numeric(18,2) not null default 0 check(saldo_liquidado>=0), saldo_pago numeric(18,2) not null default 0 check(saldo_pago>=0), saldo_disponivel numeric(18,2) not null default 0 check(saldo_disponivel>=0),
 valor numeric(18,2) not null default 0 check(valor>=0), valor_bruto numeric(18,2) not null default 0 check(valor_bruto>=0), deducoes numeric(18,2) not null default 0 check(deducoes>=0), valor_liquido numeric(18,2) not null default 0 check(valor_liquido>=0),
 percentual numeric(7,4) check(percentual is null or percentual between 0 and 100), cenario text, fonte_normativa text, vigencia_inicio date, vigencia_fim date, formula_textual text, origem_dado text,
 justificativa text, premissas text, visibilidade text not null default 'INTERNA', publicavel boolean not null default false, data_fim_prevista date,
 created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz, updated_by bigint,
 check(tipo_receita is null or tipo_receita in('ROYALTIES','PARTICIPACAO_ESPECIAL','COMPENSACAO','BONUS','FUNDO_ESPECIAL','OUTRA')),
 check(cenario is null or cenario in('CONSERVADOR','BASE','OTIMISTA')), check(vigencia_fim is null or vigencia_inicio is null or vigencia_fim>=vigencia_inicio),
 check(visibilidade in('INTERNA','PUBLICA','SIGILOSA'))
);
create index if not exists ix_royalties_transparencia_publicacao_contexto on sigov.royalties_transparencia_publicacao(tenant_id,entidade_id,status,data_referencia);
create index if not exists ix_royalties_transparencia_publicacao_filtros on sigov.royalties_transparencia_publicacao(entidade_id,exercicio_id,competencia,fonte_recurso_id,tipo_receita,projeto_id);

create table if not exists sigov.royalties_alerta(
 id bigint generated by default as identity primary key, tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint, unidade_id bigint,
 codigo text not null, nome text not null, descricao text, status text not null default 'RASCUNHO', tipo_receita text, competencia date, data_referencia date,
 fonte_recurso_id bigint, parametro_id bigint, projeto_id bigint, pessoa_juridica_id bigint, programa_id bigint, acao_id bigint, contrato_id bigint, receita_arrecadacao_id bigint, empenho_id bigint, liquidacao_id bigint, pagamento_id bigint,
 saldo_reservado numeric(18,2) not null default 0 check(saldo_reservado>=0), saldo_empenhado numeric(18,2) not null default 0 check(saldo_empenhado>=0), saldo_liquidado numeric(18,2) not null default 0 check(saldo_liquidado>=0), saldo_pago numeric(18,2) not null default 0 check(saldo_pago>=0), saldo_disponivel numeric(18,2) not null default 0 check(saldo_disponivel>=0),
 valor numeric(18,2) not null default 0 check(valor>=0), valor_bruto numeric(18,2) not null default 0 check(valor_bruto>=0), deducoes numeric(18,2) not null default 0 check(deducoes>=0), valor_liquido numeric(18,2) not null default 0 check(valor_liquido>=0),
 percentual numeric(7,4) check(percentual is null or percentual between 0 and 100), cenario text, fonte_normativa text, vigencia_inicio date, vigencia_fim date, formula_textual text, origem_dado text,
 justificativa text, premissas text, visibilidade text not null default 'INTERNA', publicavel boolean not null default false, data_fim_prevista date,
 created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz, updated_by bigint,
 check(tipo_receita is null or tipo_receita in('ROYALTIES','PARTICIPACAO_ESPECIAL','COMPENSACAO','BONUS','FUNDO_ESPECIAL','OUTRA')),
 check(cenario is null or cenario in('CONSERVADOR','BASE','OTIMISTA')), check(vigencia_fim is null or vigencia_inicio is null or vigencia_fim>=vigencia_inicio),
 check(visibilidade in('INTERNA','PUBLICA','SIGILOSA'))
);
create index if not exists ix_royalties_alerta_contexto on sigov.royalties_alerta(tenant_id,entidade_id,status,data_referencia);
create index if not exists ix_royalties_alerta_filtros on sigov.royalties_alerta(entidade_id,exercicio_id,competencia,fonte_recurso_id,tipo_receita,projeto_id);

create table if not exists sigov.royalties_auditoria_operacional(
 id bigint generated by default as identity primary key, tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint, unidade_id bigint,
 codigo text not null, nome text not null, descricao text, status text not null default 'RASCUNHO', tipo_receita text, competencia date, data_referencia date,
 fonte_recurso_id bigint, parametro_id bigint, projeto_id bigint, pessoa_juridica_id bigint, programa_id bigint, acao_id bigint, contrato_id bigint, receita_arrecadacao_id bigint, empenho_id bigint, liquidacao_id bigint, pagamento_id bigint,
 saldo_reservado numeric(18,2) not null default 0 check(saldo_reservado>=0), saldo_empenhado numeric(18,2) not null default 0 check(saldo_empenhado>=0), saldo_liquidado numeric(18,2) not null default 0 check(saldo_liquidado>=0), saldo_pago numeric(18,2) not null default 0 check(saldo_pago>=0), saldo_disponivel numeric(18,2) not null default 0 check(saldo_disponivel>=0),
 valor numeric(18,2) not null default 0 check(valor>=0), valor_bruto numeric(18,2) not null default 0 check(valor_bruto>=0), deducoes numeric(18,2) not null default 0 check(deducoes>=0), valor_liquido numeric(18,2) not null default 0 check(valor_liquido>=0),
 percentual numeric(7,4) check(percentual is null or percentual between 0 and 100), cenario text, fonte_normativa text, vigencia_inicio date, vigencia_fim date, formula_textual text, origem_dado text,
 justificativa text, premissas text, visibilidade text not null default 'INTERNA', publicavel boolean not null default false, data_fim_prevista date,
 created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz, updated_by bigint,
 check(tipo_receita is null or tipo_receita in('ROYALTIES','PARTICIPACAO_ESPECIAL','COMPENSACAO','BONUS','FUNDO_ESPECIAL','OUTRA')),
 check(cenario is null or cenario in('CONSERVADOR','BASE','OTIMISTA')), check(vigencia_fim is null or vigencia_inicio is null or vigencia_fim>=vigencia_inicio),
 check(visibilidade in('INTERNA','PUBLICA','SIGILOSA'))
);
create index if not exists ix_royalties_auditoria_operacional_contexto on sigov.royalties_auditoria_operacional(tenant_id,entidade_id,status,data_referencia);
create index if not exists ix_royalties_auditoria_operacional_filtros on sigov.royalties_auditoria_operacional(entidade_id,exercicio_id,competencia,fonte_recurso_id,tipo_receita,projeto_id);

-- Integridade especializada e vínculos sem duplicar os domínios financeiro, orçamentário e contratual.
create unique index if not exists ux_royalties_fonte_codigo on sigov.royalties_fonte_dado(tenant_id,entidade_id,codigo);
create unique index if not exists ux_royalties_origem_codigo_fonte on sigov.royalties_campo_origem(tenant_id,entidade_id,codigo,coalesce(origem_dado,''));
create unique index if not exists ux_royalties_repasse_natural on sigov.royalties_repasse(tenant_id,entidade_id,competencia,tipo_receita,fonte_recurso_id,data_referencia,valor_liquido) where status<>'CANCELADO';
create index if not exists ix_royalties_parametro_vigencia on sigov.royalties_parametro_normativo(tenant_id,entidade_id,tipo_receita,vigencia_inicio,vigencia_fim,status);

insert into sigov.permissao(modulo,chave,descricao,ativo,is_deleted)
select 'royalties',p,'Royalties360: '||replace(p,'_',' '),true,false from unnest(array[
'ROYALTIES_DASHBOARD_VIEW','ROYALTIES_PARAMETRO_MANAGE','ROYALTIES_FONTE_DADO_MANAGE','ROYALTIES_ORIGEM_RECEITA_MANAGE','ROYALTIES_PREVISAO_VIEW','ROYALTIES_PREVISAO_MANAGE','ROYALTIES_REPASSE_VIEW','ROYALTIES_REPASSE_MANAGE','ROYALTIES_CONCILIACAO_MANAGE','ROYALTIES_PLANO_VIEW','ROYALTIES_PLANO_MANAGE','ROYALTIES_PLANO_APPROVE','ROYALTIES_PROJETO_VIEW','ROYALTIES_PROJETO_MANAGE','ROYALTIES_EXECUCAO_VIEW','ROYALTIES_TRANSPARENCIA_VIEW','ROYALTIES_TRANSPARENCIA_PUBLISH','ROYALTIES_ALERTA_MANAGE','ROYALTIES_RELATORIO_EXPORT']) p
on conflict(modulo,chave) do update set descricao=excluded.descricao,ativo=true,is_deleted=false;
