-- RC50.92 Saneamento360 e Meio Ambiente360 multi-esfera
-- PostgreSQL 16+, aditiva, idempotente e sem dados artificiais.
create schema if not exists sigov;

create table if not exists sigov.saneamento_ligacao_agua (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint,
    esfera_governo varchar(12) not null check (esfera_governo in ('municipal','estadual','federal')),
    tipo_entidade varchar(80) not null, orgao_id bigint, orgao_superior_id bigint,
    unidade_gestora_id bigint, unidade_executora_id bigint,
    hierarquia_administrativa text, abrangencia_territorial text, uf char(2), municipio text, regiao_jurisdicao text, territorio_id bigint,
    codigo varchar(80) not null, pessoa_id bigint, imovel_id bigint, contribuinte_id bigint, status varchar(24) not null default 'ativa' check(status in ('ativa','suspensa','inativa','cancelada')), data_ligacao date, latitude numeric(9,6), longitude numeric(9,6),
    created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz, updated_by bigint,
    check(latitude is null or latitude between -90 and 90),
    check(longitude is null or longitude between -180 and 180)
);
create index if not exists ix_saneamento_ligacao_agua_contexto on sigov.saneamento_ligacao_agua(tenant_id, entidade_id, exercicio_id, orgao_id, unidade_gestora_id, unidade_executora_id);
create index if not exists ix_saneamento_ligacao_agua_territorio on sigov.saneamento_ligacao_agua(tenant_id, entidade_id, territorio_id);

create table if not exists sigov.saneamento_ligacao_esgoto (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint,
    esfera_governo varchar(12) not null check (esfera_governo in ('municipal','estadual','federal')),
    tipo_entidade varchar(80) not null, orgao_id bigint, orgao_superior_id bigint,
    unidade_gestora_id bigint, unidade_executora_id bigint,
    hierarquia_administrativa text, abrangencia_territorial text, uf char(2), municipio text, regiao_jurisdicao text, territorio_id bigint,
    codigo varchar(80) not null, pessoa_id bigint, imovel_id bigint, contribuinte_id bigint, status varchar(24) not null default 'ativa' check(status in ('ativa','suspensa','inativa','cancelada')), data_ligacao date, latitude numeric(9,6), longitude numeric(9,6),
    created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz, updated_by bigint,
    check(latitude is null or latitude between -90 and 90),
    check(longitude is null or longitude between -180 and 180)
);
create index if not exists ix_saneamento_ligacao_esgoto_contexto on sigov.saneamento_ligacao_esgoto(tenant_id, entidade_id, exercicio_id, orgao_id, unidade_gestora_id, unidade_executora_id);
create index if not exists ix_saneamento_ligacao_esgoto_territorio on sigov.saneamento_ligacao_esgoto(tenant_id, entidade_id, territorio_id);

create table if not exists sigov.saneamento_ocorrencia (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint,
    esfera_governo varchar(12) not null check (esfera_governo in ('municipal','estadual','federal')),
    tipo_entidade varchar(80) not null, orgao_id bigint, orgao_superior_id bigint,
    unidade_gestora_id bigint, unidade_executora_id bigint,
    hierarquia_administrativa text, abrangencia_territorial text, uf char(2), municipio text, regiao_jurisdicao text, territorio_id bigint,
    protocolo varchar(80) not null, cidadao_id bigint, tipo text not null, local_descricao text not null, data_ocorrencia timestamptz not null, prioridade varchar(12) not null check(prioridade in ('baixa','media','alta','urgente')), responsavel_id bigint not null, status varchar(24) not null check(status in ('aberta','triada','em_atendimento','resolvida','recusada','cancelada')), justificativa text, latitude numeric(9,6), longitude numeric(9,6), check(status not in ('recusada','cancelada') or nullif(trim(justificativa),'') is not null),
    created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz, updated_by bigint,
    check(latitude is null or latitude between -90 and 90),
    check(longitude is null or longitude between -180 and 180)
);
create index if not exists ix_saneamento_ocorrencia_contexto on sigov.saneamento_ocorrencia(tenant_id, entidade_id, exercicio_id, orgao_id, unidade_gestora_id, unidade_executora_id);
create index if not exists ix_saneamento_ocorrencia_territorio on sigov.saneamento_ocorrencia(tenant_id, entidade_id, territorio_id);

create table if not exists sigov.saneamento_ordem_servico (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint,
    esfera_governo varchar(12) not null check (esfera_governo in ('municipal','estadual','federal')),
    tipo_entidade varchar(80) not null, orgao_id bigint, orgao_superior_id bigint,
    unidade_gestora_id bigint, unidade_executora_id bigint,
    hierarquia_administrativa text, abrangencia_territorial text, uf char(2), municipio text, regiao_jurisdicao text, territorio_id bigint,
    ocorrencia_id bigint references sigov.saneamento_ocorrencia(id), equipe_id bigint not null, previsao timestamptz not null, prioridade varchar(12) not null check(prioridade in ('baixa','media','alta','urgente')), descricao text not null, status varchar(24) not null default 'aberta', solucao text, encerrada_em timestamptz, responsavel_encerramento_id bigint, check(encerrada_em is null or (nullif(trim(solucao),'') is not null and responsavel_encerramento_id is not null)),
    created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz, updated_by bigint
);
create index if not exists ix_saneamento_ordem_servico_contexto on sigov.saneamento_ordem_servico(tenant_id, entidade_id, exercicio_id, orgao_id, unidade_gestora_id, unidade_executora_id);
create index if not exists ix_saneamento_ordem_servico_territorio on sigov.saneamento_ordem_servico(tenant_id, entidade_id, territorio_id);

create table if not exists sigov.saneamento_drenagem_ponto (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint,
    esfera_governo varchar(12) not null check (esfera_governo in ('municipal','estadual','federal')),
    tipo_entidade varchar(80) not null, orgao_id bigint, orgao_superior_id bigint,
    unidade_gestora_id bigint, unidade_executora_id bigint,
    hierarquia_administrativa text, abrangencia_territorial text, uf char(2), municipio text, regiao_jurisdicao text, territorio_id bigint,
    codigo varchar(80) not null, tipo text not null, descricao text not null, status varchar(24) not null, criticidade varchar(12) not null, latitude numeric(9,6), longitude numeric(9,6), ultima_inspecao date,
    created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz, updated_by bigint,
    check(latitude is null or latitude between -90 and 90),
    check(longitude is null or longitude between -180 and 180)
);
create index if not exists ix_saneamento_drenagem_ponto_contexto on sigov.saneamento_drenagem_ponto(tenant_id, entidade_id, exercicio_id, orgao_id, unidade_gestora_id, unidade_executora_id);
create index if not exists ix_saneamento_drenagem_ponto_territorio on sigov.saneamento_drenagem_ponto(tenant_id, entidade_id, territorio_id);

create table if not exists sigov.saneamento_residuo_tipo (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint,
    esfera_governo varchar(12) not null check (esfera_governo in ('municipal','estadual','federal')),
    tipo_entidade varchar(80) not null, orgao_id bigint, orgao_superior_id bigint,
    unidade_gestora_id bigint, unidade_executora_id bigint,
    hierarquia_administrativa text, abrangencia_territorial text, uf char(2), municipio text, regiao_jurisdicao text, territorio_id bigint,
    codigo varchar(80) not null, nome text not null, classificacao text not null, unidade_medida varchar(20) not null, status varchar(24) not null default 'ativo',
    created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz, updated_by bigint
);
create index if not exists ix_saneamento_residuo_tipo_contexto on sigov.saneamento_residuo_tipo(tenant_id, entidade_id, exercicio_id, orgao_id, unidade_gestora_id, unidade_executora_id);
create index if not exists ix_saneamento_residuo_tipo_territorio on sigov.saneamento_residuo_tipo(tenant_id, entidade_id, territorio_id);

create table if not exists sigov.saneamento_rota_coleta (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint,
    esfera_governo varchar(12) not null check (esfera_governo in ('municipal','estadual','federal')),
    tipo_entidade varchar(80) not null, orgao_id bigint, orgao_superior_id bigint,
    unidade_gestora_id bigint, unidade_executora_id bigint,
    hierarquia_administrativa text, abrangencia_territorial text, uf char(2), municipio text, regiao_jurisdicao text, territorio_id bigint,
    codigo varchar(80) not null, frequencia text not null, veiculo_id bigint, equipe_id bigint, residuo_tipo_id bigint not null references sigov.saneamento_residuo_tipo(id), status varchar(24) not null, responsavel_id bigint not null,
    created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz, updated_by bigint
);
create index if not exists ix_saneamento_rota_coleta_contexto on sigov.saneamento_rota_coleta(tenant_id, entidade_id, exercicio_id, orgao_id, unidade_gestora_id, unidade_executora_id);
create index if not exists ix_saneamento_rota_coleta_territorio on sigov.saneamento_rota_coleta(tenant_id, entidade_id, territorio_id);

create table if not exists sigov.saneamento_destinacao_residuo (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint,
    esfera_governo varchar(12) not null check (esfera_governo in ('municipal','estadual','federal')),
    tipo_entidade varchar(80) not null, orgao_id bigint, orgao_superior_id bigint,
    unidade_gestora_id bigint, unidade_executora_id bigint,
    hierarquia_administrativa text, abrangencia_territorial text, uf char(2), municipio text, regiao_jurisdicao text, territorio_id bigint,
    residuo_tipo_id bigint not null references sigov.saneamento_residuo_tipo(id), local_destino text not null, tipo_destinacao text not null, documento_referencia text not null, status varchar(24) not null, responsavel_id bigint not null,
    created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz, updated_by bigint
);
create index if not exists ix_saneamento_destinacao_residuo_contexto on sigov.saneamento_destinacao_residuo(tenant_id, entidade_id, exercicio_id, orgao_id, unidade_gestora_id, unidade_executora_id);
create index if not exists ix_saneamento_destinacao_residuo_territorio on sigov.saneamento_destinacao_residuo(tenant_id, entidade_id, territorio_id);

create table if not exists sigov.saneamento_coleta (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint,
    esfera_governo varchar(12) not null check (esfera_governo in ('municipal','estadual','federal')),
    tipo_entidade varchar(80) not null, orgao_id bigint, orgao_superior_id bigint,
    unidade_gestora_id bigint, unidade_executora_id bigint,
    hierarquia_administrativa text, abrangencia_territorial text, uf char(2), municipio text, regiao_jurisdicao text, territorio_id bigint,
    rota_id bigint not null references sigov.saneamento_rota_coleta(id), data_coleta timestamptz not null, quantidade numeric(18,3) not null check(quantidade>=0), unidade_medida varchar(20) not null, destinacao_id bigint not null references sigov.saneamento_destinacao_residuo(id), responsavel_id bigint not null, status varchar(24) not null,
    created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz, updated_by bigint
);
create index if not exists ix_saneamento_coleta_contexto on sigov.saneamento_coleta(tenant_id, entidade_id, exercicio_id, orgao_id, unidade_gestora_id, unidade_executora_id);
create index if not exists ix_saneamento_coleta_territorio on sigov.saneamento_coleta(tenant_id, entidade_id, territorio_id);

create table if not exists sigov.saneamento_ecoponto (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint,
    esfera_governo varchar(12) not null check (esfera_governo in ('municipal','estadual','federal')),
    tipo_entidade varchar(80) not null, orgao_id bigint, orgao_superior_id bigint,
    unidade_gestora_id bigint, unidade_executora_id bigint,
    hierarquia_administrativa text, abrangencia_territorial text, uf char(2), municipio text, regiao_jurisdicao text, territorio_id bigint,
    codigo varchar(80) not null, endereco text not null, responsavel_id bigint not null, tipos_aceitos text not null, horario_funcionamento text not null, status varchar(24) not null, latitude numeric(9,6), longitude numeric(9,6),
    created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz, updated_by bigint,
    check(latitude is null or latitude between -90 and 90),
    check(longitude is null or longitude between -180 and 180)
);
create index if not exists ix_saneamento_ecoponto_contexto on sigov.saneamento_ecoponto(tenant_id, entidade_id, exercicio_id, orgao_id, unidade_gestora_id, unidade_executora_id);
create index if not exists ix_saneamento_ecoponto_territorio on sigov.saneamento_ecoponto(tenant_id, entidade_id, territorio_id);

create table if not exists sigov.meio_ambiente_empreendimento (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint,
    esfera_governo varchar(12) not null check (esfera_governo in ('municipal','estadual','federal')),
    tipo_entidade varchar(80) not null, orgao_id bigint, orgao_superior_id bigint,
    unidade_gestora_id bigint, unidade_executora_id bigint,
    hierarquia_administrativa text, abrangencia_territorial text, uf char(2), municipio text, regiao_jurisdicao text, territorio_id bigint,
    responsavel_id bigint not null, cpf_cnpj_cifrado text not null, atividade text not null, endereco text not null, porte varchar(30) not null, potencial_poluidor varchar(30) not null, status varchar(24) not null,
    created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz, updated_by bigint
);
create index if not exists ix_meio_ambiente_empreendimento_contexto on sigov.meio_ambiente_empreendimento(tenant_id, entidade_id, exercicio_id, orgao_id, unidade_gestora_id, unidade_executora_id);
create index if not exists ix_meio_ambiente_empreendimento_territorio on sigov.meio_ambiente_empreendimento(tenant_id, entidade_id, territorio_id);

create table if not exists sigov.meio_ambiente_licenca (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint,
    esfera_governo varchar(12) not null check (esfera_governo in ('municipal','estadual','federal')),
    tipo_entidade varchar(80) not null, orgao_id bigint, orgao_superior_id bigint,
    unidade_gestora_id bigint, unidade_executora_id bigint,
    hierarquia_administrativa text, abrangencia_territorial text, uf char(2), municipio text, regiao_jurisdicao text, territorio_id bigint,
    empreendimento_id bigint not null references sigov.meio_ambiente_empreendimento(id), tipo varchar(30) not null check(tipo in ('licenca_previa','licenca_instalacao','licenca_operacao','autorizacao','dispensa','renovacao')), protocolo_processo text, validade_inicio date not null, validade_fim date not null, responsavel_tecnico_id bigint not null, parecer_id bigint, licenca_origem_id bigint references sigov.meio_ambiente_licenca(id), status varchar(24) not null, justificativa text, check(validade_fim>=validade_inicio), check(status<>'indeferida' or nullif(trim(justificativa),'') is not null),
    created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz, updated_by bigint
);
create index if not exists ix_meio_ambiente_licenca_contexto on sigov.meio_ambiente_licenca(tenant_id, entidade_id, exercicio_id, orgao_id, unidade_gestora_id, unidade_executora_id);
create index if not exists ix_meio_ambiente_licenca_territorio on sigov.meio_ambiente_licenca(tenant_id, entidade_id, territorio_id);

create table if not exists sigov.meio_ambiente_condicionante (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint,
    esfera_governo varchar(12) not null check (esfera_governo in ('municipal','estadual','federal')),
    tipo_entidade varchar(80) not null, orgao_id bigint, orgao_superior_id bigint,
    unidade_gestora_id bigint, unidade_executora_id bigint,
    hierarquia_administrativa text, abrangencia_territorial text, uf char(2), municipio text, regiao_jurisdicao text, territorio_id bigint,
    licenca_id bigint not null references sigov.meio_ambiente_licenca(id), descricao text not null, prazo date not null, responsavel_id bigint not null, status varchar(24) not null, evidencia_documento_id bigint,
    created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz, updated_by bigint
);
create index if not exists ix_meio_ambiente_condicionante_contexto on sigov.meio_ambiente_condicionante(tenant_id, entidade_id, exercicio_id, orgao_id, unidade_gestora_id, unidade_executora_id);
create index if not exists ix_meio_ambiente_condicionante_territorio on sigov.meio_ambiente_condicionante(tenant_id, entidade_id, territorio_id);

create table if not exists sigov.meio_ambiente_parecer (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint,
    esfera_governo varchar(12) not null check (esfera_governo in ('municipal','estadual','federal')),
    tipo_entidade varchar(80) not null, orgao_id bigint, orgao_superior_id bigint,
    unidade_gestora_id bigint, unidade_executora_id bigint,
    hierarquia_administrativa text, abrangencia_territorial text, uf char(2), municipio text, regiao_jurisdicao text, territorio_id bigint,
    empreendimento_id bigint not null references sigov.meio_ambiente_empreendimento(id), licenca_id bigint references sigov.meio_ambiente_licenca(id), tipo text not null, conclusao text not null, responsavel_id bigint not null, data_parecer date not null, documento_id bigint, status varchar(24) not null,
    created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz, updated_by bigint
);
create index if not exists ix_meio_ambiente_parecer_contexto on sigov.meio_ambiente_parecer(tenant_id, entidade_id, exercicio_id, orgao_id, unidade_gestora_id, unidade_executora_id);
create index if not exists ix_meio_ambiente_parecer_territorio on sigov.meio_ambiente_parecer(tenant_id, entidade_id, territorio_id);

create table if not exists sigov.meio_ambiente_fiscalizacao (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint,
    esfera_governo varchar(12) not null check (esfera_governo in ('municipal','estadual','federal')),
    tipo_entidade varchar(80) not null, orgao_id bigint, orgao_superior_id bigint,
    unidade_gestora_id bigint, unidade_executora_id bigint,
    hierarquia_administrativa text, abrangencia_territorial text, uf char(2), municipio text, regiao_jurisdicao text, territorio_id bigint,
    origem text not null, local_descricao text not null, responsavel_id bigint not null, tipo text not null, prioridade varchar(12) not null check(prioridade in ('baixa','media','alta','urgente')), status varchar(24) not null, latitude numeric(9,6), longitude numeric(9,6),
    created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz, updated_by bigint,
    check(latitude is null or latitude between -90 and 90),
    check(longitude is null or longitude between -180 and 180)
);
create index if not exists ix_meio_ambiente_fiscalizacao_contexto on sigov.meio_ambiente_fiscalizacao(tenant_id, entidade_id, exercicio_id, orgao_id, unidade_gestora_id, unidade_executora_id);
create index if not exists ix_meio_ambiente_fiscalizacao_territorio on sigov.meio_ambiente_fiscalizacao(tenant_id, entidade_id, territorio_id);

create table if not exists sigov.meio_ambiente_vistoria (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint,
    esfera_governo varchar(12) not null check (esfera_governo in ('municipal','estadual','federal')),
    tipo_entidade varchar(80) not null, orgao_id bigint, orgao_superior_id bigint,
    unidade_gestora_id bigint, unidade_executora_id bigint,
    hierarquia_administrativa text, abrangencia_territorial text, uf char(2), municipio text, regiao_jurisdicao text, territorio_id bigint,
    fiscalizacao_id bigint not null references sigov.meio_ambiente_fiscalizacao(id), data_prevista timestamptz not null, data_conclusao timestamptz, resultado text, evidencia_documento_id bigint, responsavel_id bigint not null, status varchar(24) not null, check(data_conclusao is null or (resultado is not null and data_conclusao>=data_prevista)),
    created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz, updated_by bigint
);
create index if not exists ix_meio_ambiente_vistoria_contexto on sigov.meio_ambiente_vistoria(tenant_id, entidade_id, exercicio_id, orgao_id, unidade_gestora_id, unidade_executora_id);
create index if not exists ix_meio_ambiente_vistoria_territorio on sigov.meio_ambiente_vistoria(tenant_id, entidade_id, territorio_id);

create table if not exists sigov.meio_ambiente_auto_infracao (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint,
    esfera_governo varchar(12) not null check (esfera_governo in ('municipal','estadual','federal')),
    tipo_entidade varchar(80) not null, orgao_id bigint, orgao_superior_id bigint,
    unidade_gestora_id bigint, unidade_executora_id bigint,
    hierarquia_administrativa text, abrangencia_territorial text, uf char(2), municipio text, regiao_jurisdicao text, territorio_id bigint,
    fiscalizacao_id bigint not null references sigov.meio_ambiente_fiscalizacao(id), fundamento text not null, descricao text not null, autuado_pessoa_id bigint not null, valor_multa numeric(18,2) check(valor_multa>=0), status varchar(24) not null, juridico_vinculo_id bigint,
    created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz, updated_by bigint
);
create index if not exists ix_meio_ambiente_auto_infracao_contexto on sigov.meio_ambiente_auto_infracao(tenant_id, entidade_id, exercicio_id, orgao_id, unidade_gestora_id, unidade_executora_id);
create index if not exists ix_meio_ambiente_auto_infracao_territorio on sigov.meio_ambiente_auto_infracao(tenant_id, entidade_id, territorio_id);

create table if not exists sigov.meio_ambiente_notificacao (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint,
    esfera_governo varchar(12) not null check (esfera_governo in ('municipal','estadual','federal')),
    tipo_entidade varchar(80) not null, orgao_id bigint, orgao_superior_id bigint,
    unidade_gestora_id bigint, unidade_executora_id bigint,
    hierarquia_administrativa text, abrangencia_territorial text, uf char(2), municipio text, regiao_jurisdicao text, territorio_id bigint,
    fiscalizacao_id bigint not null references sigov.meio_ambiente_fiscalizacao(id), fundamento text not null, descricao text not null, data_notificacao date not null, prazo date, responsavel_id bigint not null, status varchar(24) not null, check(prazo is null or prazo>=data_notificacao),
    created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz, updated_by bigint
);
create index if not exists ix_meio_ambiente_notificacao_contexto on sigov.meio_ambiente_notificacao(tenant_id, entidade_id, exercicio_id, orgao_id, unidade_gestora_id, unidade_executora_id);
create index if not exists ix_meio_ambiente_notificacao_territorio on sigov.meio_ambiente_notificacao(tenant_id, entidade_id, territorio_id);

create table if not exists sigov.meio_ambiente_embargo (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint,
    esfera_governo varchar(12) not null check (esfera_governo in ('municipal','estadual','federal')),
    tipo_entidade varchar(80) not null, orgao_id bigint, orgao_superior_id bigint,
    unidade_gestora_id bigint, unidade_executora_id bigint,
    hierarquia_administrativa text, abrangencia_territorial text, uf char(2), municipio text, regiao_jurisdicao text, territorio_id bigint,
    fiscalizacao_id bigint not null references sigov.meio_ambiente_fiscalizacao(id), fundamento text not null, data_embargo date not null, responsavel_id bigint not null, status varchar(24) not null,
    created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz, updated_by bigint
);
create index if not exists ix_meio_ambiente_embargo_contexto on sigov.meio_ambiente_embargo(tenant_id, entidade_id, exercicio_id, orgao_id, unidade_gestora_id, unidade_executora_id);
create index if not exists ix_meio_ambiente_embargo_territorio on sigov.meio_ambiente_embargo(tenant_id, entidade_id, territorio_id);

create table if not exists sigov.meio_ambiente_recurso (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint,
    esfera_governo varchar(12) not null check (esfera_governo in ('municipal','estadual','federal')),
    tipo_entidade varchar(80) not null, orgao_id bigint, orgao_superior_id bigint,
    unidade_gestora_id bigint, unidade_executora_id bigint,
    hierarquia_administrativa text, abrangencia_territorial text, uf char(2), municipio text, regiao_jurisdicao text, territorio_id bigint,
    auto_infracao_id bigint references sigov.meio_ambiente_auto_infracao(id), embargo_id bigint references sigov.meio_ambiente_embargo(id), data_protocolo date not null, prazo_limite date not null, fundamento text not null, responsavel_id bigint not null, status varchar(24) not null, check(prazo_limite>=data_protocolo), check(auto_infracao_id is not null or embargo_id is not null),
    created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz, updated_by bigint
);
create index if not exists ix_meio_ambiente_recurso_contexto on sigov.meio_ambiente_recurso(tenant_id, entidade_id, exercicio_id, orgao_id, unidade_gestora_id, unidade_executora_id);
create index if not exists ix_meio_ambiente_recurso_territorio on sigov.meio_ambiente_recurso(tenant_id, entidade_id, territorio_id);

create table if not exists sigov.meio_ambiente_denuncia (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint,
    esfera_governo varchar(12) not null check (esfera_governo in ('municipal','estadual','federal')),
    tipo_entidade varchar(80) not null, orgao_id bigint, orgao_superior_id bigint,
    unidade_gestora_id bigint, unidade_executora_id bigint,
    hierarquia_administrativa text, abrangencia_territorial text, uf char(2), municipio text, regiao_jurisdicao text, territorio_id bigint,
    protocolo varchar(80) not null, cidadao_id bigint, anonima boolean not null default false, denunciante_cifrado text, tipo text not null, descricao text not null, local_descricao text not null, data_denuncia timestamptz not null default now(), responsavel_id bigint, status varchar(24) not null, fiscalizacao_id bigint references sigov.meio_ambiente_fiscalizacao(id), acompanhamento_chave_hash text not null, check(anonima or cidadao_id is not null),
    created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz, updated_by bigint
);
create index if not exists ix_meio_ambiente_denuncia_contexto on sigov.meio_ambiente_denuncia(tenant_id, entidade_id, exercicio_id, orgao_id, unidade_gestora_id, unidade_executora_id);
create index if not exists ix_meio_ambiente_denuncia_territorio on sigov.meio_ambiente_denuncia(tenant_id, entidade_id, territorio_id);

create table if not exists sigov.meio_ambiente_area_degradada (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint,
    esfera_governo varchar(12) not null check (esfera_governo in ('municipal','estadual','federal')),
    tipo_entidade varchar(80) not null, orgao_id bigint, orgao_superior_id bigint,
    unidade_gestora_id bigint, unidade_executora_id bigint,
    hierarquia_administrativa text, abrangencia_territorial text, uf char(2), municipio text, regiao_jurisdicao text, territorio_id bigint,
    codigo varchar(80) not null, descricao text not null, risco varchar(20) not null, area_hectares numeric(18,4) check(area_hectares>=0), percentual_recuperado numeric(5,2) check(percentual_recuperado between 0 and 100), responsavel_id bigint not null, status varchar(24) not null, latitude numeric(9,6), longitude numeric(9,6),
    created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz, updated_by bigint,
    check(latitude is null or latitude between -90 and 90),
    check(longitude is null or longitude between -180 and 180)
);
create index if not exists ix_meio_ambiente_area_degradada_contexto on sigov.meio_ambiente_area_degradada(tenant_id, entidade_id, exercicio_id, orgao_id, unidade_gestora_id, unidade_executora_id);
create index if not exists ix_meio_ambiente_area_degradada_territorio on sigov.meio_ambiente_area_degradada(tenant_id, entidade_id, territorio_id);

create table if not exists sigov.meio_ambiente_indicador (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint,
    esfera_governo varchar(12) not null check (esfera_governo in ('municipal','estadual','federal')),
    tipo_entidade varchar(80) not null, orgao_id bigint, orgao_superior_id bigint,
    unidade_gestora_id bigint, unidade_executora_id bigint,
    hierarquia_administrativa text, abrangencia_territorial text, uf char(2), municipio text, regiao_jurisdicao text, territorio_id bigint,
    codigo varchar(80) not null, nome text not null, competencia date not null, valor numeric(20,6) not null, unidade_medida text not null, fonte text not null, status varchar(24) not null, publicado_transparencia boolean not null default false,
    created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz, updated_by bigint
);
create index if not exists ix_meio_ambiente_indicador_contexto on sigov.meio_ambiente_indicador(tenant_id, entidade_id, exercicio_id, orgao_id, unidade_gestora_id, unidade_executora_id);
create index if not exists ix_meio_ambiente_indicador_territorio on sigov.meio_ambiente_indicador(tenant_id, entidade_id, territorio_id);

create table if not exists sigov.saneamento_auditoria_operacional (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint,
    esfera_governo varchar(12) not null check (esfera_governo in ('municipal','estadual','federal')),
    tipo_entidade varchar(80) not null, orgao_id bigint, orgao_superior_id bigint,
    unidade_gestora_id bigint, unidade_executora_id bigint,
    hierarquia_administrativa text, abrangencia_territorial text, uf char(2), municipio text, regiao_jurisdicao text, territorio_id bigint,
    recurso text not null, registro_id bigint, acao text not null, responsavel_id bigint, correlation_id text not null, dados jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz, updated_by bigint
);
create index if not exists ix_saneamento_auditoria_operacional_contexto on sigov.saneamento_auditoria_operacional(tenant_id, entidade_id, exercicio_id, orgao_id, unidade_gestora_id, unidade_executora_id);
create index if not exists ix_saneamento_auditoria_operacional_territorio on sigov.saneamento_auditoria_operacional(tenant_id, entidade_id, territorio_id);

create table if not exists sigov.meio_ambiente_auditoria_sensivel (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint,
    esfera_governo varchar(12) not null check (esfera_governo in ('municipal','estadual','federal')),
    tipo_entidade varchar(80) not null, orgao_id bigint, orgao_superior_id bigint,
    unidade_gestora_id bigint, unidade_executora_id bigint,
    hierarquia_administrativa text, abrangencia_territorial text, uf char(2), municipio text, regiao_jurisdicao text, territorio_id bigint,
    recurso text not null, registro_id bigint, acao text not null, responsavel_id bigint, correlation_id text not null, justificativa_acesso text, dados_protegidos boolean not null default true,
    created_at timestamptz not null default now(), created_by bigint, updated_at timestamptz, updated_by bigint
);
create index if not exists ix_meio_ambiente_auditoria_sensivel_contexto on sigov.meio_ambiente_auditoria_sensivel(tenant_id, entidade_id, exercicio_id, orgao_id, unidade_gestora_id, unidade_executora_id);
create index if not exists ix_meio_ambiente_auditoria_sensivel_territorio on sigov.meio_ambiente_auditoria_sensivel(tenant_id, entidade_id, territorio_id);

create unique index if not exists ux_saneamento_ligacao_agua_codigo on sigov.saneamento_ligacao_agua(tenant_id,entidade_id,codigo);
create unique index if not exists ux_saneamento_ligacao_esgoto_codigo on sigov.saneamento_ligacao_esgoto(tenant_id,entidade_id,codigo);
create unique index if not exists ux_saneamento_ocorrencia_protocolo on sigov.saneamento_ocorrencia(tenant_id,entidade_id,protocolo);
create unique index if not exists ux_meio_ambiente_denuncia_protocolo on sigov.meio_ambiente_denuncia(tenant_id,entidade_id,protocolo);

insert into sigov.permissao(modulo,recurso,acao,chave,descricao,ativo)
select v.* from (values
('rc50.92','operacao','executar','SANEAMENTO_DASHBOARD_VIEW','Permissão RC50.92',true),
('rc50.92','operacao','executar','SANEAMENTO_LIGACAO_VIEW','Permissão RC50.92',true),
('rc50.92','operacao','executar','SANEAMENTO_LIGACAO_MANAGE','Permissão RC50.92',true),
('rc50.92','operacao','executar','SANEAMENTO_OCORRENCIA_VIEW','Permissão RC50.92',true),
('rc50.92','operacao','executar','SANEAMENTO_OCORRENCIA_MANAGE','Permissão RC50.92',true),
('rc50.92','operacao','executar','SANEAMENTO_OS_MANAGE','Permissão RC50.92',true),
('rc50.92','operacao','executar','SANEAMENTO_RESIDUOS_VIEW','Permissão RC50.92',true),
('rc50.92','operacao','executar','SANEAMENTO_RESIDUOS_MANAGE','Permissão RC50.92',true),
('rc50.92','operacao','executar','SANEAMENTO_RELATORIO_EXPORT','Permissão RC50.92',true),
('rc50.92','operacao','executar','MEIO_AMBIENTE_DASHBOARD_VIEW','Permissão RC50.92',true),
('rc50.92','operacao','executar','MEIO_AMBIENTE_LICENCA_VIEW','Permissão RC50.92',true),
('rc50.92','operacao','executar','MEIO_AMBIENTE_LICENCA_MANAGE','Permissão RC50.92',true),
('rc50.92','operacao','executar','MEIO_AMBIENTE_LICENCA_APPROVE','Permissão RC50.92',true),
('rc50.92','operacao','executar','MEIO_AMBIENTE_FISCALIZACAO_VIEW','Permissão RC50.92',true),
('rc50.92','operacao','executar','MEIO_AMBIENTE_FISCALIZACAO_MANAGE','Permissão RC50.92',true),
('rc50.92','operacao','executar','MEIO_AMBIENTE_AUTO_INFRACAO_MANAGE','Permissão RC50.92',true),
('rc50.92','operacao','executar','MEIO_AMBIENTE_DENUNCIA_VIEW','Permissão RC50.92',true),
('rc50.92','operacao','executar','MEIO_AMBIENTE_DENUNCIA_MANAGE','Permissão RC50.92',true),
('rc50.92','operacao','executar','MEIO_AMBIENTE_DADO_SENSIVEL_VIEW','Permissão RC50.92',true),
('rc50.92','operacao','executar','MEIO_AMBIENTE_RELATORIO_EXPORT','Permissão RC50.92',true),
('rc50.92','operacao','executar','PORTAL_CIDADAO_SANEAMENTO_ACCESS','Permissão RC50.92',true),
('rc50.92','operacao','executar','PORTAL_CIDADAO_MEIO_AMBIENTE_ACCESS','Permissão RC50.92',true)
) v(modulo,recurso,acao,chave,descricao,ativo)
where not exists(select 1 from sigov.permissao p where p.chave=v.chave);

create index if not exists ix_saneamento_ocorrencia_gestao on sigov.saneamento_ocorrencia(tenant_id,entidade_id,status,prioridade,responsavel_id,data_ocorrencia);
create index if not exists ix_saneamento_ordem_servico_gestao on sigov.saneamento_ordem_servico(tenant_id,entidade_id,status,prioridade,equipe_id,previsao);
create index if not exists ix_saneamento_coleta_gestao on sigov.saneamento_coleta(tenant_id,entidade_id,status,responsavel_id,data_coleta);
create index if not exists ix_meio_ambiente_licenca_gestao on sigov.meio_ambiente_licenca(tenant_id,entidade_id,status,responsavel_tecnico_id,validade_fim);
create index if not exists ix_meio_ambiente_fiscalizacao_gestao on sigov.meio_ambiente_fiscalizacao(tenant_id,entidade_id,status,prioridade,responsavel_id,created_at);
create index if not exists ix_meio_ambiente_denuncia_gestao on sigov.meio_ambiente_denuncia(tenant_id,entidade_id,status,responsavel_id,data_denuncia);
create index if not exists ix_meio_ambiente_indicador_competencia on sigov.meio_ambiente_indicador(tenant_id,entidade_id,territorio_id,competencia,status);
