-- FUNC05 - Educação e Gestão Escolar. PostgreSQL 16+, idempotente e não destrutiva.
create schema if not exists sigov;
create table if not exists sigov.educacao_escola (id bigint generated always as identity primary key, tenant_id bigint not null, entidade_id bigint not null, created_at timestamptz not null default now(), updated_at timestamptz, created_by bigint, updated_by bigint, is_deleted boolean not null default false, nome varchar(200) not null, codigo_inep varchar(20), endereco text, telefone varchar(30), email varchar(180), tipo varchar(20) not null default 'OUTRO', status varchar(10) not null default 'ATIVA', capacidade_geral integer not null default 0 check(capacidade_geral>=0));
create table if not exists sigov.educacao_aluno (id bigint generated always as identity primary key, tenant_id bigint not null, entidade_id bigint not null, created_at timestamptz not null default now(), updated_at timestamptz, created_by bigint, updated_by bigint, is_deleted boolean not null default false, nome varchar(200) not null, data_nascimento date not null, documento varchar(30), sexo varchar(20), endereco text, metadados_protegidos jsonb not null default '{}'::jsonb, status varchar(20) not null default 'ATIVO');
create table if not exists sigov.educacao_responsavel (id bigint generated always as identity primary key, tenant_id bigint not null, entidade_id bigint not null, created_at timestamptz not null default now(), updated_at timestamptz, created_by bigint, updated_by bigint, is_deleted boolean not null default false, nome varchar(200) not null, documento varchar(30), telefone varchar(30), email varchar(180), parentesco varchar(50), status varchar(10) not null default 'ATIVO');
create table if not exists sigov.educacao_professor (id bigint generated always as identity primary key, tenant_id bigint not null, entidade_id bigint not null, created_at timestamptz not null default now(), updated_at timestamptz, created_by bigint, updated_by bigint, is_deleted boolean not null default false, nome varchar(200) not null, documento varchar(30), matricula_funcional varchar(50), email varchar(180), telefone varchar(30), escolaridade varchar(100), vinculo varchar(80), carga_horaria numeric(7,2) not null default 0 check(carga_horaria>=0), status varchar(10) not null default 'ATIVO');
create table if not exists sigov.educacao_serie_etapa (id bigint generated always as identity primary key, tenant_id bigint not null, entidade_id bigint not null, created_at timestamptz not null default now(), updated_at timestamptz, created_by bigint, updated_by bigint, is_deleted boolean not null default false, codigo varchar(30) not null, nome varchar(150) not null, metodologia varchar(10) not null default 'NOTA', ativo boolean not null default true);
create table if not exists sigov.educacao_componente_curricular (id bigint generated always as identity primary key, tenant_id bigint not null, entidade_id bigint not null, created_at timestamptz not null default now(), updated_at timestamptz, created_by bigint, updated_by bigint, is_deleted boolean not null default false, codigo varchar(30) not null, nome varchar(150) not null, ativo boolean not null default true);
create table if not exists sigov.educacao_aluno_responsavel (id bigint generated always as identity primary key, tenant_id bigint not null, entidade_id bigint not null, created_at timestamptz not null default now(), updated_at timestamptz, created_by bigint, updated_by bigint, is_deleted boolean not null default false, aluno_id bigint not null references sigov.educacao_aluno(id), responsavel_id bigint not null references sigov.educacao_responsavel(id), responsavel_legal boolean not null default false, autorizado_buscar boolean not null default false);
create table if not exists sigov.educacao_ano_letivo (id bigint generated always as identity primary key, tenant_id bigint not null, entidade_id bigint not null, created_at timestamptz not null default now(), updated_at timestamptz, created_by bigint, updated_by bigint, is_deleted boolean not null default false, escola_id bigint not null references sigov.educacao_escola(id), ano integer not null check(ano between 2000 and 2200), data_inicio date not null, data_fim date not null, status varchar(12) not null default 'ABERTO', check(data_fim>=data_inicio));
create table if not exists sigov.educacao_periodo_avaliativo (id bigint generated always as identity primary key, tenant_id bigint not null, entidade_id bigint not null, created_at timestamptz not null default now(), updated_at timestamptz, created_by bigint, updated_by bigint, is_deleted boolean not null default false, ano_letivo_id bigint not null references sigov.educacao_ano_letivo(id), nome varchar(100) not null, data_inicio date not null, data_fim date not null, status varchar(12) not null default 'ABERTO', check(data_fim>=data_inicio));
create table if not exists sigov.educacao_turma (id bigint generated always as identity primary key, tenant_id bigint not null, entidade_id bigint not null, created_at timestamptz not null default now(), updated_at timestamptz, created_by bigint, updated_by bigint, is_deleted boolean not null default false, escola_id bigint not null references sigov.educacao_escola(id), ano_letivo_id bigint not null references sigov.educacao_ano_letivo(id), serie_etapa_id bigint not null references sigov.educacao_serie_etapa(id), professor_regente_id bigint references sigov.educacao_professor(id), codigo varchar(30) not null, nome varchar(150) not null, turno varchar(10) not null, capacidade integer not null check(capacidade>0), status varchar(12) not null default 'ABERTA');
create table if not exists sigov.educacao_turma_professor (id bigint generated always as identity primary key, tenant_id bigint not null, entidade_id bigint not null, created_at timestamptz not null default now(), updated_at timestamptz, created_by bigint, updated_by bigint, is_deleted boolean not null default false, turma_id bigint not null references sigov.educacao_turma(id), professor_id bigint not null references sigov.educacao_professor(id), componente_curricular_id bigint not null references sigov.educacao_componente_curricular(id), carga_horaria numeric(7,2) not null check(carga_horaria>0), dia_semana smallint, horario time);
create table if not exists sigov.educacao_matricula (id bigint generated always as identity primary key, tenant_id bigint not null, entidade_id bigint not null, created_at timestamptz not null default now(), updated_at timestamptz, created_by bigint, updated_by bigint, is_deleted boolean not null default false, aluno_id bigint not null references sigov.educacao_aluno(id), escola_id bigint not null references sigov.educacao_escola(id), ano_letivo_id bigint not null references sigov.educacao_ano_letivo(id), serie_etapa_id bigint not null references sigov.educacao_serie_etapa(id), turma_id bigint references sigov.educacao_turma(id), numero varchar(50) not null, data_matricula date not null default current_date, situacao varchar(15) not null default 'ATIVA', justificativa text);
create table if not exists sigov.educacao_matricula_historico (id bigint generated always as identity primary key, tenant_id bigint not null, entidade_id bigint not null, created_at timestamptz not null default now(), updated_at timestamptz, created_by bigint, updated_by bigint, is_deleted boolean not null default false, matricula_id bigint not null references sigov.educacao_matricula(id), situacao_anterior varchar(15), situacao_nova varchar(15) not null, turma_anterior_id bigint, turma_nova_id bigint, justificativa text, ocorrido_em timestamptz not null default now());
create table if not exists sigov.educacao_frequencia_aula (id bigint generated always as identity primary key, tenant_id bigint not null, entidade_id bigint not null, created_at timestamptz not null default now(), updated_at timestamptz, created_by bigint, updated_by bigint, is_deleted boolean not null default false, turma_id bigint not null references sigov.educacao_turma(id), componente_curricular_id bigint not null references sigov.educacao_componente_curricular(id), professor_id bigint not null references sigov.educacao_professor(id), data_aula date not null, conteudo text not null, observacao text);
create table if not exists sigov.educacao_frequencia_aluno (id bigint generated always as identity primary key, tenant_id bigint not null, entidade_id bigint not null, created_at timestamptz not null default now(), updated_at timestamptz, created_by bigint, updated_by bigint, is_deleted boolean not null default false, frequencia_aula_id bigint not null references sigov.educacao_frequencia_aula(id), aluno_id bigint not null references sigov.educacao_aluno(id), status varchar(12) not null, justificativa text);
create table if not exists sigov.educacao_avaliacao (id bigint generated always as identity primary key, tenant_id bigint not null, entidade_id bigint not null, created_at timestamptz not null default now(), updated_at timestamptz, created_by bigint, updated_by bigint, is_deleted boolean not null default false, turma_id bigint not null references sigov.educacao_turma(id), componente_curricular_id bigint not null references sigov.educacao_componente_curricular(id), periodo_avaliativo_id bigint not null references sigov.educacao_periodo_avaliativo(id), instrumento varchar(100) not null, data_avaliacao date not null, peso numeric(6,2), nota_maxima numeric(6,2), status varchar(12) not null default 'ABERTA');
create table if not exists sigov.educacao_nota_aluno (id bigint generated always as identity primary key, tenant_id bigint not null, entidade_id bigint not null, created_at timestamptz not null default now(), updated_at timestamptz, created_by bigint, updated_by bigint, is_deleted boolean not null default false, avaliacao_id bigint not null references sigov.educacao_avaliacao(id), aluno_id bigint not null references sigov.educacao_aluno(id), nota numeric(6,2), conceito varchar(30), parecer text, recuperacao boolean not null default false);
create table if not exists sigov.educacao_ocorrencia (id bigint generated always as identity primary key, tenant_id bigint not null, entidade_id bigint not null, created_at timestamptz not null default now(), updated_at timestamptz, created_by bigint, updated_by bigint, is_deleted boolean not null default false, aluno_id bigint not null references sigov.educacao_aluno(id), escola_id bigint not null references sigov.educacao_escola(id), turma_id bigint references sigov.educacao_turma(id), tipo varchar(12) not null, ocorrido_em timestamptz not null, descricao_protegida text not null, providencia_protegida text, registrado_por bigint not null);
create table if not exists sigov.educacao_prematricula (id bigint generated always as identity primary key, tenant_id bigint not null, entidade_id bigint not null, created_at timestamptz not null default now(), updated_at timestamptz, created_by bigint, updated_by bigint, is_deleted boolean not null default false, protocolo varchar(50) not null, aluno_id bigint references sigov.educacao_aluno(id), nome_interessado varchar(200) not null, responsavel_id bigint references sigov.educacao_responsavel(id), escola_id bigint not null references sigov.educacao_escola(id), serie_etapa_id bigint not null references sigov.educacao_serie_etapa(id), turno varchar(10), endereco text, status varchar(15) not null default 'RECEBIDA', justificativa text);
create table if not exists sigov.educacao_comunicado (id bigint generated always as identity primary key, tenant_id bigint not null, entidade_id bigint not null, created_at timestamptz not null default now(), updated_at timestamptz, created_by bigint, updated_by bigint, is_deleted boolean not null default false, escola_id bigint not null references sigov.educacao_escola(id), turma_id bigint references sigov.educacao_turma(id), titulo varchar(180) not null, mensagem text not null, publicado_em timestamptz not null default now(), ativo boolean not null default true);
create table if not exists sigov.educacao_portal_vinculo (id bigint generated always as identity primary key, tenant_id bigint not null, entidade_id bigint not null, created_at timestamptz not null default now(), updated_at timestamptz, created_by bigint, updated_by bigint, is_deleted boolean not null default false, usuario_id bigint not null, aluno_id bigint not null references sigov.educacao_aluno(id), responsavel_id bigint references sigov.educacao_responsavel(id), status varchar(10) not null default 'ATIVO');
create table if not exists sigov.educacao_auditoria (id bigint generated always as identity primary key, tenant_id bigint not null, entidade_id bigint not null, created_at timestamptz not null default now(), updated_at timestamptz, created_by bigint, updated_by bigint, is_deleted boolean not null default false, tabela varchar(100) not null, registro_id bigint not null, operacao varchar(30) not null, antes jsonb, depois jsonb, usuario_id bigint, ocorrido_em timestamptz not null default now(), correlation_id varchar(100));
do $$ begin if not exists(select 1 from pg_constraint where conname='educacao_escola_tipo') then alter table sigov.educacao_escola add constraint educacao_escola_tipo check (tipo in ('INFANTIL','FUNDAMENTAL','EJA','OUTRO')); end if; end $$;
do $$ begin if not exists(select 1 from pg_constraint where conname='educacao_escola_status') then alter table sigov.educacao_escola add constraint educacao_escola_status check (status in ('ATIVA','INATIVA')); end if; end $$;
do $$ begin if not exists(select 1 from pg_constraint where conname='educacao_aluno_status') then alter table sigov.educacao_aluno add constraint educacao_aluno_status check (status in ('ATIVO','TRANSFERIDO','EVADIDO','CONCLUINTE','INATIVO')); end if; end $$;
do $$ begin if not exists(select 1 from pg_constraint where conname='educacao_professor_status') then alter table sigov.educacao_professor add constraint educacao_professor_status check (status in ('ATIVO','AFASTADO','INATIVO')); end if; end $$;
do $$ begin if not exists(select 1 from pg_constraint where conname='educacao_metodologia') then alter table sigov.educacao_serie_etapa add constraint educacao_metodologia check (metodologia in ('NOTA','CONCEITO','PARECER')); end if; end $$;
do $$ begin if not exists(select 1 from pg_constraint where conname='educacao_ano_status') then alter table sigov.educacao_ano_letivo add constraint educacao_ano_status check (status in ('PLANEJADO','ABERTO','ENCERRADO')); end if; end $$;
do $$ begin if not exists(select 1 from pg_constraint where conname='educacao_periodo_status') then alter table sigov.educacao_periodo_avaliativo add constraint educacao_periodo_status check (status in ('ABERTO','ENCERRADO')); end if; end $$;
do $$ begin if not exists(select 1 from pg_constraint where conname='educacao_turma_turno') then alter table sigov.educacao_turma add constraint educacao_turma_turno check (turno in ('MANHA','TARDE','NOITE','INTEGRAL')); end if; end $$;
do $$ begin if not exists(select 1 from pg_constraint where conname='educacao_turma_status') then alter table sigov.educacao_turma add constraint educacao_turma_status check (status in ('ABERTA','FECHADA','ENCERRADA')); end if; end $$;
do $$ begin if not exists(select 1 from pg_constraint where conname='educacao_matricula_situacao') then alter table sigov.educacao_matricula add constraint educacao_matricula_situacao check (situacao in ('ATIVA','PRE_MATRICULA','TRANSFERIDA','CANCELADA','ABANDONO','CONCLUIDA')); end if; end $$;
do $$ begin if not exists(select 1 from pg_constraint where conname='educacao_frequencia_status') then alter table sigov.educacao_frequencia_aluno add constraint educacao_frequencia_status check (status in ('PRESENTE','FALTA','JUSTIFICADA')); end if; end $$;
do $$ begin if not exists(select 1 from pg_constraint where conname='educacao_ocorrencia_tipo') then alter table sigov.educacao_ocorrencia add constraint educacao_ocorrencia_tipo check (tipo in ('DISCIPLINAR','PEDAGOGICA','SAUDE','OUTRA')); end if; end $$;
do $$ begin if not exists(select 1 from pg_constraint where conname='educacao_prematricula_status') then alter table sigov.educacao_prematricula add constraint educacao_prematricula_status check (status in ('RECEBIDA','EM_ANALISE','DEFERIDA','INDEFERIDA','LISTA_ESPERA','CANCELADA')); end if; end $$;
create unique index if not exists ux_educacao_escola_inep on sigov.educacao_escola(tenant_id,entidade_id,codigo_inep) where codigo_inep is not null and not is_deleted;
create unique index if not exists ux_educacao_aluno_documento on sigov.educacao_aluno(tenant_id,entidade_id,documento) where documento is not null and not is_deleted;
create unique index if not exists ux_educacao_responsavel_documento on sigov.educacao_responsavel(tenant_id,entidade_id,documento) where documento is not null and not is_deleted;
create unique index if not exists ux_educacao_professor_documento on sigov.educacao_professor(tenant_id,entidade_id,documento) where documento is not null and not is_deleted;
create unique index if not exists ux_educacao_professor_matricula on sigov.educacao_professor(tenant_id,entidade_id,matricula_funcional) where matricula_funcional is not null and not is_deleted;
create unique index if not exists ux_educacao_matricula_ativa on sigov.educacao_matricula(tenant_id,entidade_id,aluno_id,escola_id,ano_letivo_id,serie_etapa_id) where situacao='ATIVA' and not is_deleted;
create unique index if not exists ux_educacao_prematricula_protocolo on sigov.educacao_prematricula(tenant_id,protocolo) where not is_deleted;
create unique index if not exists ux_educacao_frequencia_aluno on sigov.educacao_frequencia_aluno(frequencia_aula_id,aluno_id) where not is_deleted;
create unique index if not exists ux_educacao_nota_aluno on sigov.educacao_nota_aluno(avaliacao_id,aluno_id,recuperacao) where not is_deleted;
create index if not exists ix_educacao_escola_escopo on sigov.educacao_escola(tenant_id,entidade_id,status);
create index if not exists ix_educacao_aluno_escopo on sigov.educacao_aluno(tenant_id,entidade_id,status);
create index if not exists ix_educacao_responsavel_escopo on sigov.educacao_responsavel(tenant_id,entidade_id,status);
create index if not exists ix_educacao_professor_escopo on sigov.educacao_professor(tenant_id,entidade_id,status);
create index if not exists ix_educacao_serie_etapa_escopo on sigov.educacao_serie_etapa(tenant_id,entidade_id);
create index if not exists ix_educacao_componente_curricular_escopo on sigov.educacao_componente_curricular(tenant_id,entidade_id);
create index if not exists ix_educacao_aluno_responsavel_escopo on sigov.educacao_aluno_responsavel(tenant_id,entidade_id,aluno_id);
create index if not exists ix_educacao_ano_letivo_escopo on sigov.educacao_ano_letivo(tenant_id,entidade_id,escola_id,status);
create index if not exists ix_educacao_periodo_avaliativo_escopo on sigov.educacao_periodo_avaliativo(tenant_id,entidade_id,ano_letivo_id,status);
create index if not exists ix_educacao_turma_escopo on sigov.educacao_turma(tenant_id,entidade_id,escola_id,ano_letivo_id,status);
create index if not exists ix_educacao_turma_professor_escopo on sigov.educacao_turma_professor(tenant_id,entidade_id,turma_id,professor_id);
create index if not exists ix_educacao_matricula_escopo on sigov.educacao_matricula(tenant_id,entidade_id,escola_id,ano_letivo_id,turma_id,aluno_id);
create index if not exists ix_educacao_matricula_historico_escopo on sigov.educacao_matricula_historico(tenant_id,entidade_id);
create index if not exists ix_educacao_frequencia_aula_escopo on sigov.educacao_frequencia_aula(tenant_id,entidade_id,turma_id,professor_id);
create index if not exists ix_educacao_frequencia_aluno_escopo on sigov.educacao_frequencia_aluno(tenant_id,entidade_id,aluno_id,status);
create index if not exists ix_educacao_avaliacao_escopo on sigov.educacao_avaliacao(tenant_id,entidade_id,turma_id,status);
create index if not exists ix_educacao_nota_aluno_escopo on sigov.educacao_nota_aluno(tenant_id,entidade_id,aluno_id);
create index if not exists ix_educacao_ocorrencia_escopo on sigov.educacao_ocorrencia(tenant_id,entidade_id,escola_id,turma_id,aluno_id);
create index if not exists ix_educacao_prematricula_escopo on sigov.educacao_prematricula(tenant_id,entidade_id,escola_id,aluno_id,status);
create index if not exists ix_educacao_comunicado_escopo on sigov.educacao_comunicado(tenant_id,entidade_id,escola_id,turma_id);
create index if not exists ix_educacao_portal_vinculo_escopo on sigov.educacao_portal_vinculo(tenant_id,entidade_id,aluno_id,status);
create index if not exists ix_educacao_auditoria_escopo on sigov.educacao_auditoria(tenant_id,entidade_id);
create or replace function sigov.fn_educacao_validar_operacao() returns trigger language plpgsql as $$
declare v_status text; v_cap integer; v_ocupadas bigint; v_metodo text; v_ano_status text; v_max numeric;
begin
 if tg_table_name='educacao_turma' then select status into v_status from sigov.educacao_escola where id=new.escola_id and not is_deleted; if v_status<>'ATIVA' then raise exception 'Escola inativa não recebe turma'; end if; end if;
 if tg_table_name='educacao_matricula' and new.situacao='ATIVA' then
  select e.status,t.status,t.capacidade into v_status,v_metodo,v_cap from sigov.educacao_escola e left join sigov.educacao_turma t on t.id=new.turma_id where e.id=new.escola_id;
  if v_status<>'ATIVA' then raise exception 'Escola inativa não recebe matrícula'; end if;
  if new.turma_id is not null then select count(*) into v_ocupadas from sigov.educacao_matricula where turma_id=new.turma_id and situacao='ATIVA' and not is_deleted and id<>coalesce(new.id,0); if v_metodo<>'ABERTA' or v_ocupadas>=v_cap then raise exception 'Turma encerrada ou sem vaga'; end if; end if;
 end if;
 if tg_table_name='educacao_nota_aluno' then select a.nota_maxima,p.status,al.status,se.metodologia into v_max,v_status,v_ano_status,v_metodo from sigov.educacao_avaliacao a join sigov.educacao_periodo_avaliativo p on p.id=a.periodo_avaliativo_id join sigov.educacao_turma t on t.id=a.turma_id join sigov.educacao_ano_letivo al on al.id=t.ano_letivo_id join sigov.educacao_serie_etapa se on se.id=t.serie_etapa_id where a.id=new.avaliacao_id; if v_status='ENCERRADO' or v_ano_status='ENCERRADO' then raise exception 'Período ou ano encerrado'; end if; if new.nota is not null and (new.nota<0 or new.nota>v_max) then raise exception 'Nota fora do intervalo'; end if; end if;
 return new;
end $$;
drop trigger if exists trg_educacao_validar_turma on sigov.educacao_turma; create trigger trg_educacao_validar_turma before insert or update on sigov.educacao_turma for each row execute function sigov.fn_educacao_validar_operacao();
drop trigger if exists trg_educacao_validar_matricula on sigov.educacao_matricula; create trigger trg_educacao_validar_matricula before insert or update on sigov.educacao_matricula for each row execute function sigov.fn_educacao_validar_operacao();
drop trigger if exists trg_educacao_validar_nota on sigov.educacao_nota_aluno; create trigger trg_educacao_validar_nota before insert or update on sigov.educacao_nota_aluno for each row execute function sigov.fn_educacao_validar_operacao();
insert into sigov.permissao(modulo,chave,recurso,acao,descricao,ativo,is_deleted) select 'educacao',v.chave,v.recurso,v.acao,v.descricao,true,false from(values
('educacao.dashboard.visualizar','educacao.dashboard','visualizar','Permissão FUNC05'),
('educacao.escola.visualizar','educacao.escola','visualizar','Permissão FUNC05'),
('educacao.escola.criar','educacao.escola','criar','Permissão FUNC05'),
('educacao.escola.editar','educacao.escola','editar','Permissão FUNC05'),
('educacao.aluno.visualizar','educacao.aluno','visualizar','Permissão FUNC05'),
('educacao.aluno.criar','educacao.aluno','criar','Permissão FUNC05'),
('educacao.aluno.editar','educacao.aluno','editar','Permissão FUNC05'),
('educacao.professor.visualizar','educacao.professor','visualizar','Permissão FUNC05'),
('educacao.professor.criar','educacao.professor','criar','Permissão FUNC05'),
('educacao.professor.editar','educacao.professor','editar','Permissão FUNC05'),
('educacao.anoletivo.gerenciar','educacao.anoletivo','gerenciar','Permissão FUNC05'),
('educacao.turma.visualizar','educacao.turma','visualizar','Permissão FUNC05'),
('educacao.turma.criar','educacao.turma','criar','Permissão FUNC05'),
('educacao.turma.editar','educacao.turma','editar','Permissão FUNC05'),
('educacao.matricula.visualizar','educacao.matricula','visualizar','Permissão FUNC05'),
('educacao.matricula.criar','educacao.matricula','criar','Permissão FUNC05'),
('educacao.matricula.transferir','educacao.matricula','transferir','Permissão FUNC05'),
('educacao.frequencia.visualizar','educacao.frequencia','visualizar','Permissão FUNC05'),
('educacao.frequencia.lancar','educacao.frequencia','lancar','Permissão FUNC05'),
('educacao.avaliacao.visualizar','educacao.avaliacao','visualizar','Permissão FUNC05'),
('educacao.avaliacao.lancar','educacao.avaliacao','lancar','Permissão FUNC05'),
('educacao.ocorrencia.visualizar','educacao.ocorrencia','visualizar','Permissão FUNC05'),
('educacao.ocorrencia.criar','educacao.ocorrencia','criar','Permissão FUNC05'),
('educacao.prematricula.visualizar','educacao.prematricula','visualizar','Permissão FUNC05'),
('educacao.prematricula.criar','educacao.prematricula','criar','Permissão FUNC05'),
('educacao.prematricula.deferir','educacao.prematricula','deferir','Permissão FUNC05'),
('educacao.portal.visualizar','educacao.portal','visualizar','Permissão FUNC05'),
('educacao.exportar','educacao','exportar','Permissão FUNC05'))v(chave,recurso,acao,descricao) where not exists(select 1 from sigov.permissao p where p.chave=v.chave);
insert into sigov.perfil_permissao(perfil_acesso_id,permissao_id,efeito,ativo,is_deleted) select pa.id,p.id,'PERMITIR',true,false from sigov.perfil_acesso pa cross join sigov.permissao p where pa.codigo_externo='SUPERADMIN' and pa.sistemico and pa.ativo and not pa.is_deleted and p.modulo='educacao' and p.ativo and not p.is_deleted on conflict(perfil_acesso_id,permissao_id) do update set efeito='PERMITIR',ativo=true,is_deleted=false;
