create schema if not exists sigov;
create table if not exists sigov.workflow_definicao (
 id bigint generated by default as identity primary key, tenant_id bigint not null, nome varchar(120) not null, descricao varchar(500), modulo varchar(40) not null,
 status varchar(20) not null default 'RASCUNHO' check(status in('RASCUNHO','PUBLICADO','INATIVO')), versao_atual integer not null default 0,
 created_by bigint, updated_by bigint, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), is_deleted boolean not null default false,
 constraint uq_workflow_definicao_tenant_nome unique(tenant_id,nome)
);
create index if not exists ix_workflow_definicao_tenant_status on sigov.workflow_definicao(tenant_id,status) where not is_deleted;
create table if not exists sigov.workflow_versao (
 id bigint generated by default as identity primary key, tenant_id bigint not null, workflow_definicao_id bigint not null references sigov.workflow_definicao(id), numero integer not null,
 status varchar(20) not null, conteudo_json jsonb not null default '{}'::jsonb, publicado_por bigint, publicado_em timestamptz, created_at timestamptz not null default now(),
 constraint uq_workflow_versao unique(tenant_id,workflow_definicao_id,numero)
);
create table if not exists sigov.workflow_etapa (
 id bigint generated by default as identity primary key, tenant_id bigint not null, workflow_definicao_id bigint not null references sigov.workflow_definicao(id) on delete cascade,
 nome varchar(100) not null, descricao varchar(400), tipo varchar(40) not null, responsavel_id bigint, grupo_responsavel_id bigint, ordem integer not null, prazo_horas integer,
 inicial boolean not null default false, final boolean not null default false, exige_justificativa boolean not null default false, exige_anexo boolean not null default false,
 exige_aprovacao boolean not null default false, permite_retorno boolean not null default false, formulario_definicao_id bigint, created_at timestamptz not null default now()
);
create index if not exists ix_workflow_etapa_tenant_workflow on sigov.workflow_etapa(tenant_id,workflow_definicao_id,ordem);
create table if not exists sigov.workflow_transicao (
 id bigint generated by default as identity primary key, tenant_id bigint not null, workflow_definicao_id bigint not null references sigov.workflow_definicao(id) on delete cascade,
 de_etapa_id bigint not null references sigov.workflow_etapa(id), para_etapa_id bigint not null references sigov.workflow_etapa(id), condicao varchar(300), acao varchar(80) not null,
 permissao_necessaria varchar(100), mensagem_usuario varchar(240), created_at timestamptz not null default now(), check(de_etapa_id<>para_etapa_id)
);
create table if not exists sigov.workflow_evento (
 id bigint generated by default as identity primary key, tenant_id bigint not null, workflow_instancia_id bigint not null, tipo varchar(40) not null,
 de_etapa_id bigint, para_etapa_id bigint, justificativa varchar(1000), usuario_id bigint, dados_json jsonb not null default '{}'::jsonb, correlation_id uuid not null, created_at timestamptz not null default now()
);
create index if not exists ix_workflow_evento_tenant_instancia on sigov.workflow_evento(tenant_id,workflow_instancia_id,created_at desc);

-- Catálogo canônico; o ON CONFLICT torna reaplicação segura em instalações existentes.
do $$ begin
 if to_regclass('sigov.permissao') is not null then
  insert into sigov.permissao(chave,descricao,modulo,recurso,acao,ativo)
  select p.codigo,p.nome,p.modulo,p.recurso,p.acao,true from (values
   ('WORKFLOW_CONSULTA','Consultar workflows','workflow','configuracao','consultar'),('WORKFLOW_GERENCIAR','Gerenciar workflows','workflow','configuracao','gerenciar'),
   ('FORMULARIO_CONSULTA','Consultar formulários','formularios','configuracao','consultar'),('FORMULARIO_GERENCIAR','Gerenciar formulários','formularios','configuracao','gerenciar'),
   ('PORTAL_CONFIGURAR','Configurar portal','portal','configuracao','gerenciar'),('PORTAL_CONSULTAR_SOLICITACOES','Consultar solicitações externas','portal','configuracao','consultar'),
   ('SLA_CONSULTA','Consultar SLA','sla','configuracao','consultar'),('SLA_GERENCIAR','Gerenciar SLA','sla','configuracao','gerenciar'),('APROVACAO_CONSULTA','Consultar aprovações','aprovacoes','configuracao','consultar'),
   ('APROVACAO_DECIDIR','Decidir aprovações','aprovacoes','configuracao','decidir'),('TEMPLATE_CONSULTA','Consultar templates','templates','configuracao','consultar'),('TEMPLATE_GERENCIAR','Gerenciar templates','templates','configuracao','gerenciar'),
   ('ONBOARDING_CONSULTA','Consultar onboarding','onboarding','configuracao','consultar'),('SHOWCASE_ACESSAR','Acessar showcase','showcase','configuracao','consultar'),('RELATORIO_EXECUTIVO','Consultar relatório executivo','relatorios','configuracao','consultar')
  ) p(codigo,nome,modulo,recurso,acao) on conflict(chave) do nothing;
 end if;
end $$;
