-- SIGOV+ RC50.45 - numeração, votação e publicação legislativa.

create table if not exists sigov.legislativo_votacao (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    status varchar(40) not null default 'PENDENTE',
    ativo boolean not null default true,
    is_deleted boolean not null default false
);
alter table sigov.legislativo_proposicao add column if not exists ativo boolean not null default true;
alter table sigov.legislativo_proposicao add column if not exists is_deleted boolean not null default false;
alter table sigov.legislativo_proposicao add column if not exists status varchar(40) not null default 'EM_TRAMITACAO';
alter table sigov.legislativo_votacao add column if not exists ativo boolean not null default true;
alter table sigov.legislativo_votacao add column if not exists is_deleted boolean not null default false;
alter table sigov.legislativo_votacao add column if not exists status varchar(40) not null default 'PENDENTE';

create unique index if not exists ux_legislativo_proposicao_numero
    on sigov.legislativo_proposicao (tenant_id, tipo, ano, numero)
    where numero is not null and is_deleted = false;
create unique index if not exists ux_legislativo_voto_parlamentar
    on sigov.legislativo_voto (tenant_id, referencia_id, responsavel_id)
    where referencia_id is not null and responsavel_id is not null and is_deleted = false;
create index if not exists ix_legislativo_votacao_aberta
    on sigov.legislativo_votacao (tenant_id, referencia_id, status)
    where is_deleted = false and ativo = true;
