-- RC50.36: arrecadação e dívida ativa preparatória, sem integração externa automática.
create schema if not exists sigov;
create table if not exists sigov.tributario_contribuinte (
 id bigserial primary key, tenant_id bigint not null, entidade_id bigint not null, nome varchar(180) not null,
 documento varchar(20), inscricao varchar(60), tipo varchar(20) not null default 'PESSOA', status varchar(24) not null default 'ABERTO',
 dados jsonb not null default '{}'::jsonb, auditoria jsonb not null default '{}'::jsonb, correlation_id varchar(100), ativo boolean not null default true,
 is_deleted boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz, deleted_at timestamptz, created_by bigint, updated_by bigint, deleted_by bigint
);
create unique index if not exists ux_tri_contribuinte_documento on sigov.tributario_contribuinte(tenant_id,documento) where documento is not null and is_deleted=false;

do $$ declare t text; begin foreach t in array array['tributario_cadastro_imobiliario','tributario_cadastro_economico','tributario_tributo'] loop execute format('create table if not exists sigov.%I (id bigserial primary key, tenant_id bigint not null, entidade_id bigint not null, contribuinte_id bigint references sigov.tributario_contribuinte(id), inscricao varchar(60), codigo varchar(60), descricao text, status varchar(24) not null default ''ABERTO'', dados jsonb not null default ''{}''::jsonb, auditoria jsonb not null default ''{}''::jsonb, correlation_id varchar(100), ativo boolean not null default true, is_deleted boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz, deleted_at timestamptz, created_by bigint, updated_by bigint, deleted_by bigint)',t); end loop; end $$;

create table if not exists sigov.tributario_lancamento (
 id bigserial primary key, tenant_id bigint not null, entidade_id bigint not null, exercicio_id bigint, contribuinte_id bigint not null references sigov.tributario_contribuinte(id), tributo_id bigint not null references sigov.tributario_tributo(id),
 codigo varchar(60) not null, descricao text, competencia date not null, data_vencimento date not null, valor_original numeric(18,2) not null check(valor_original>0), valor_multa numeric(18,2) not null default 0,
 valor_juros numeric(18,2) not null default 0, valor_correcao numeric(18,2) not null default 0, valor_total numeric(18,2) not null check(valor_total>0), saldo numeric(18,2) not null check(saldo>=0),
 status varchar(24) not null default 'RASCUNHO', dados jsonb not null default '{}'::jsonb, auditoria jsonb not null default '{}'::jsonb, correlation_id varchar(100), ativo boolean not null default true,
 is_deleted boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz, deleted_at timestamptz, created_by bigint, updated_by bigint, deleted_by bigint,
 unique(tenant_id,entidade_id,codigo)
);
create table if not exists sigov.tributario_lancamento_item (id bigserial primary key, tenant_id bigint not null, lancamento_id bigint not null references sigov.tributario_lancamento(id), descricao text not null, valor numeric(18,2) not null check(valor>0), dados jsonb not null default '{}'::jsonb, is_deleted boolean not null default false, created_at timestamptz not null default now());
create table if not exists sigov.tributario_guia (id bigserial primary key, tenant_id bigint not null, entidade_id bigint not null, lancamento_id bigint not null references sigov.tributario_lancamento(id), contribuinte_id bigint not null references sigov.tributario_contribuinte(id), codigo varchar(80) not null, data_vencimento date not null, valor_total numeric(18,2) not null check(valor_total>0), saldo numeric(18,2) not null check(saldo>=0), status varchar(24) not null default 'EM_ABERTO', dados jsonb not null default '{}'::jsonb, auditoria jsonb not null default '{}'::jsonb, correlation_id varchar(100), ativo boolean not null default true, is_deleted boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz, deleted_at timestamptz, created_by bigint, updated_by bigint, deleted_by bigint, unique(tenant_id,codigo));
create table if not exists sigov.tributario_pagamento (id bigserial primary key, tenant_id bigint not null, entidade_id bigint not null, guia_id bigint not null references sigov.tributario_guia(id), valor numeric(18,2) not null check(valor>0), data_pagamento date not null, status varchar(24) not null default 'PAGO', dados jsonb not null default '{}'::jsonb, auditoria jsonb not null default '{}'::jsonb, correlation_id varchar(100), is_deleted boolean not null default false, created_at timestamptz not null default now(), created_by bigint);
create table if not exists sigov.tributario_divida_ativa (id bigserial primary key, tenant_id bigint not null, entidade_id bigint not null, contribuinte_id bigint not null references sigov.tributario_contribuinte(id), lancamento_id bigint not null references sigov.tributario_lancamento(id), inscricao varchar(80) not null, data_inscricao date not null, data_prescricao_alerta date, valor_total numeric(18,2) not null, saldo numeric(18,2) not null, status varchar(24) not null default 'INSCRITO_DIVIDA', dados jsonb not null default '{}'::jsonb, auditoria jsonb not null default '{}'::jsonb, correlation_id varchar(100), ativo boolean not null default true, is_deleted boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz, deleted_at timestamptz, created_by bigint, updated_by bigint, deleted_by bigint, unique(tenant_id,lancamento_id), unique(tenant_id,inscricao));
do $$ declare t text; begin foreach t in array array['tributario_parcelamento','tributario_parcelamento_parcela','tributario_divida_movimento','tributario_cobranca','tributario_baixa','tributario_suspensao','tributario_evento'] loop execute format('create table if not exists sigov.%I (id bigserial primary key, tenant_id bigint not null, entidade_id bigint not null, contribuinte_id bigint, divida_ativa_id bigint, codigo varchar(80), descricao text, competencia date, data_vencimento date, valor_original numeric(18,2) not null default 0, valor_total numeric(18,2) not null default 0, saldo numeric(18,2) not null default 0, status varchar(24) not null default ''EM_ABERTO'', dados jsonb not null default ''{}''::jsonb, auditoria jsonb not null default ''{}''::jsonb, correlation_id varchar(100), ativo boolean not null default true, is_deleted boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz, deleted_at timestamptz, created_by bigint, updated_by bigint, deleted_by bigint)',t); end loop; end $$;
create index if not exists ix_tri_lancamento_tenant_status on sigov.tributario_lancamento(tenant_id,status,data_vencimento) where is_deleted=false;
create index if not exists ix_tri_guia_contribuinte on sigov.tributario_guia(tenant_id,contribuinte_id,status) where is_deleted=false;
create index if not exists ix_tri_divida_prescricao on sigov.tributario_divida_ativa(tenant_id,data_prescricao_alerta,status) where is_deleted=false;
