create schema if not exists sigov;

create table if not exists sigov.convenio_orgao_concedente(id bigint generated always as identity primary key,tenant_id bigint not null,entity_id bigint not null,nome text not null,cnpj text,esfera text not null check(esfera in('FEDERAL','ESTADUAL','MUNICIPAL','OUTRA')),sigla text,contato_nome text,contato_email text,contato_telefone text,status text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz);
create table if not exists sigov.convenio_programa(id bigint generated always as identity primary key,tenant_id bigint not null,entity_id bigint not null,orgao_concedente_id bigint not null references sigov.convenio_orgao_concedente(id),nome text not null,codigo text not null,finalidade text not null,area text not null check(area in('SAUDE','EDUCACAO','INFRAESTRUTURA','ASSISTENCIA','MEIO_AMBIENTE','CULTURA','ESPORTE','OUTRA')),data_inicio date not null,data_fim date,status text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz,check(data_fim is null or data_fim>=data_inicio));
create table if not exists sigov.convenio_emenda(id bigint generated always as identity primary key,tenant_id bigint not null,entity_id bigint not null,numero_emenda text not null,parlamentar_nome text not null,parlamentar_partido text,esfera text not null,ano integer not null check(ano>=1900),area text not null,valor_previsto numeric(18,2) not null default 0 check(valor_previsto>=0),valor_aprovado numeric(18,2) not null default 0 check(valor_aprovado>=0),status text not null,observacao text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz,constraint uq_convenio_emenda unique(tenant_id,entity_id,ano,numero_emenda));
create table if not exists sigov.convenio_instrumento(id bigint generated always as identity primary key,tenant_id bigint not null,entity_id bigint not null,numero_instrumento text not null,tipo text not null check(tipo in('CONVENIO','CONTRATO_REPASSE','TERMO_FOMENTO','TERMO_COLABORACAO','TRANSFERENCIA_ESPECIAL','OUTRO')),orgao_concedente_id bigint not null references sigov.convenio_orgao_concedente(id),programa_id bigint references sigov.convenio_programa(id),emenda_id bigint references sigov.convenio_emenda(id),objeto text not null,valor_global numeric(18,2) not null check(valor_global>=0),valor_repasse numeric(18,2) not null check(valor_repasse>=0),valor_contrapartida numeric(18,2) not null check(valor_contrapartida>=0),data_assinatura date not null,vigencia_inicio date not null,vigencia_fim date not null,status text not null,responsavel_nome text not null,responsavel_cpf text,observacao text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz,constraint uq_convenio_instrumento unique(tenant_id,entity_id,numero_instrumento),check(abs(valor_global-(valor_repasse+valor_contrapartida))<=0.01),check(vigencia_fim>=vigencia_inicio));
create table if not exists sigov.convenio_projeto(id bigint generated always as identity primary key,tenant_id bigint not null,entity_id bigint not null,instrumento_id bigint not null references sigov.convenio_instrumento(id),nome text not null,objetivo text not null,justificativa text not null,publico_alvo text not null,local_execucao text not null,unidade_responsavel text not null,data_inicio date not null,data_fim_prevista date not null,data_fim_real date,percentual_execucao numeric(5,2) not null default 0 check(percentual_execucao between 0 and 100),status text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz,check(data_fim_prevista>=data_inicio),check(data_fim_real is null or data_fim_real>=data_inicio),check(status<>'CONCLUIDO' or data_fim_real is not null));
create table if not exists sigov.convenio_meta(id bigint generated always as identity primary key,tenant_id bigint not null,entity_id bigint not null,projeto_id bigint not null references sigov.convenio_projeto(id),numero text not null,descricao text not null,indicador text not null,unidade_medida text not null,quantidade_prevista numeric(18,4) not null check(quantidade_prevista>0),quantidade_executada numeric(18,4) not null default 0 check(quantidade_executada>=0),status text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz);
create table if not exists sigov.convenio_etapa(id bigint generated always as identity primary key,tenant_id bigint not null,entity_id bigint not null,meta_id bigint not null references sigov.convenio_meta(id),numero text not null,descricao text not null,data_inicio date not null,data_fim_prevista date not null,data_fim_real date,valor_previsto numeric(18,2) not null check(valor_previsto>=0),valor_executado numeric(18,2) not null default 0 check(valor_executado>=0),observacao text,status text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz,check(data_fim_prevista>=data_inicio),check(data_fim_real is null or data_fim_real>=data_inicio),check(status<>'CONCLUIDA' or data_fim_real is not null),check(valor_executado<=valor_previsto or nullif(trim(observacao),'') is not null));
create table if not exists sigov.convenio_conta_bancaria(id bigint generated always as identity primary key,tenant_id bigint not null,entity_id bigint not null,instrumento_id bigint not null references sigov.convenio_instrumento(id),banco text not null,agencia text not null,conta text not null,tipo_conta text not null,saldo_inicial numeric(18,2) not null default 0,saldo_atual numeric(18,2) not null default 0,status text not null,observacao text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz,constraint uq_convenio_conta unique(instrumento_id,banco,agencia,conta),check(saldo_atual>=0 or(status='AJUSTE' and nullif(trim(observacao),'') is not null)));
create table if not exists sigov.convenio_repasse(id bigint generated always as identity primary key,tenant_id bigint not null,entity_id bigint not null,instrumento_id bigint not null references sigov.convenio_instrumento(id),conta_bancaria_id bigint references sigov.convenio_conta_bancaria(id),numero_repasse text not null,data_repasse date not null,valor numeric(18,2) not null check(valor>0),fonte_recurso text not null,status text not null,observacao text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz);
create table if not exists sigov.convenio_despesa(id bigint generated always as identity primary key,tenant_id bigint not null,entity_id bigint not null,instrumento_id bigint not null references sigov.convenio_instrumento(id),projeto_id bigint references sigov.convenio_projeto(id),etapa_id bigint references sigov.convenio_etapa(id),conta_bancaria_id bigint references sigov.convenio_conta_bancaria(id),numero_documento text not null,fornecedor_nome text not null,fornecedor_documento text not null,data_despesa date not null,data_pagamento date,descricao text not null,valor numeric(18,2) not null check(valor>0),natureza_despesa text not null,status text not null,observacao text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz,check(status<>'PAGA' or data_pagamento is not null));
create table if not exists sigov.convenio_contrapartida(id bigint generated always as identity primary key,tenant_id bigint not null,entity_id bigint not null,instrumento_id bigint not null references sigov.convenio_instrumento(id),tipo text not null check(tipo in('FINANCEIRA','BENS','SERVICOS','PESSOAL','OUTRA')),descricao text not null,valor_previsto numeric(18,2) not null check(valor_previsto>=0),valor_realizado numeric(18,2) not null default 0 check(valor_realizado>=0),data_realizacao date,status text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz);
create table if not exists sigov.convenio_acompanhamento(id bigint generated always as identity primary key,tenant_id bigint not null,entity_id bigint not null,projeto_id bigint not null references sigov.convenio_projeto(id),data_acompanhamento date not null,responsavel_nome text not null,percentual_fisico numeric(5,2) not null check(percentual_fisico between 0 and 100),percentual_financeiro numeric(5,2) not null check(percentual_financeiro between 0 and 100),resumo text not null,risco text,providencias text,status text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz);
create table if not exists sigov.convenio_prestacao_contas(id bigint generated always as identity primary key,tenant_id bigint not null,entity_id bigint not null,instrumento_id bigint not null references sigov.convenio_instrumento(id),numero_prestacao text not null,tipo text not null check(tipo in('PARCIAL','FINAL','COMPLEMENTAR')),periodo_inicio date not null,periodo_fim date not null,data_envio date,valor_prestado numeric(18,2) not null check(valor_prestado>=0),valor_aprovado numeric(18,2) check(valor_aprovado>=0),status text not null,parecer_resumo text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz,constraint uq_convenio_prestacao unique(instrumento_id,numero_prestacao),check(periodo_fim>=periodo_inicio),check(tipo<>'FINAL' or data_envio is not null),check(status not in('ENVIADA','APROVADA') or data_envio is not null),check(status<>'APROVADA' or(valor_aprovado is not null and nullif(trim(parecer_resumo),'') is not null)));
create table if not exists sigov.convenio_diligencia(id bigint generated always as identity primary key,tenant_id bigint not null,entity_id bigint not null,prestacao_contas_id bigint not null references sigov.convenio_prestacao_contas(id),numero_diligencia text not null,data_recebimento date not null,prazo_resposta date not null,data_resposta date,descricao text not null,resposta text,status text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz,check(prazo_resposta>=data_recebimento),check(data_resposta is null or data_resposta>=data_recebimento),check(status<>'RESPONDIDA' or(data_resposta is not null and nullif(trim(resposta),'') is not null)));
create table if not exists sigov.convenio_documento_referencia(id bigint generated always as identity primary key,tenant_id bigint not null,entity_id bigint not null,instrumento_id bigint references sigov.convenio_instrumento(id),projeto_id bigint references sigov.convenio_projeto(id),prestacao_contas_id bigint references sigov.convenio_prestacao_contas(id),tipo_documento text not null,titulo text not null,numero_documento text,data_documento date not null,observacao text,status text not null default 'ATIVO',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz);
create table if not exists sigov.convenio_auditoria(id bigint generated always as identity primary key,tenant_id bigint not null,entity_id bigint not null,tabela text not null,registro_id bigint not null,acao text not null,usuario text not null,dados_anteriores jsonb,dados_novos jsonb,created_at timestamptz not null default now());

create index if not exists ix_convenio_instrumento_contexto on sigov.convenio_instrumento(tenant_id,entity_id,status,vigencia_fim) where deleted_at is null;
create index if not exists ix_convenio_projeto_contexto on sigov.convenio_projeto(tenant_id,entity_id,status,data_fim_prevista) where deleted_at is null;
create index if not exists ix_convenio_despesa_contexto on sigov.convenio_despesa(tenant_id,entity_id,data_despesa,status) where deleted_at is null;
create index if not exists ix_convenio_diligencia_contexto on sigov.convenio_diligencia(tenant_id,entity_id,prazo_resposta,status) where deleted_at is null;
create index if not exists ix_convenio_auditoria_contexto on sigov.convenio_auditoria(tenant_id,entity_id,created_at desc);

insert into sigov.permissao(chave,nome,modulo,ativo,created_at)
select p.chave,p.nome,'convenios',true,now() from(values
('CONVENIO_DASHBOARD_VIEW','Visualizar dashboard de convênios'),('CONVENIO_ORGAO_VIEW','Visualizar órgãos concedentes'),('CONVENIO_ORGAO_MANAGE','Gerenciar órgãos concedentes'),('CONVENIO_PROGRAMA_VIEW','Visualizar programas'),('CONVENIO_PROGRAMA_MANAGE','Gerenciar programas'),('CONVENIO_EMENDA_VIEW','Visualizar emendas'),('CONVENIO_EMENDA_MANAGE','Gerenciar emendas'),('CONVENIO_INSTRUMENTO_VIEW','Visualizar instrumentos'),('CONVENIO_INSTRUMENTO_MANAGE','Gerenciar instrumentos'),('CONVENIO_PROJETO_VIEW','Visualizar projetos'),('CONVENIO_PROJETO_MANAGE','Gerenciar projetos'),('CONVENIO_META_VIEW','Visualizar metas'),('CONVENIO_META_MANAGE','Gerenciar metas'),('CONVENIO_ETAPA_VIEW','Visualizar etapas'),('CONVENIO_ETAPA_MANAGE','Gerenciar etapas'),('CONVENIO_FINANCEIRO_VIEW','Visualizar financeiro de convênios'),('CONVENIO_FINANCEIRO_MANAGE','Gerenciar financeiro de convênios'),('CONVENIO_PRESTACAO_VIEW','Visualizar prestações de contas'),('CONVENIO_PRESTACAO_MANAGE','Gerenciar prestações de contas'),('CONVENIO_DILIGENCIA_VIEW','Visualizar diligências'),('CONVENIO_DILIGENCIA_MANAGE','Gerenciar diligências'),('CONVENIO_RELATORIO_EXPORT','Exportar relatórios de convênios'),('CONVENIO_AUDITORIA_VIEW','Visualizar auditoria de convênios'))p(chave,nome)
where not exists(select 1 from sigov.permissao x where x.chave=p.chave);
