-- FUNC19 - Defesa Civil, Guarda Municipal e Seguranca Publica Municipal
create schema if not exists sigov;

create table if not exists sigov.defesa_agente(id bigint generated always as identity primary key,tenant_id bigint not null,entity_id bigint not null,nome text not null,matricula text not null,cpf text not null,telefone text,email text,tipo_agente text not null check(tipo_agente in('DEFESA_CIVIL','GUARDA_MUNICIPAL','APOIO')),cargo_funcao text,status text not null default 'ATIVO',data_inicio date not null,data_fim date,observacao text,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz,constraint uq_defesa_agente_matricula unique(tenant_id,entity_id,matricula),constraint ck_defesa_agente_datas check(data_fim is null or data_fim>=data_inicio));
create table if not exists sigov.defesa_equipe(id bigint generated always as identity primary key,tenant_id bigint not null,entity_id bigint not null,nome text not null,tipo_equipe text not null,turno text,responsavel_agente_id bigint not null references sigov.defesa_agente(id),status text not null default 'ATIVA',observacao text,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz);
create table if not exists sigov.defesa_equipe_agente(id bigint generated always as identity primary key,tenant_id bigint not null,entity_id bigint not null,equipe_id bigint not null references sigov.defesa_equipe(id),agente_id bigint not null references sigov.defesa_agente(id),funcao_na_equipe text,data_entrada date not null,data_saida date,created_at timestamptz not null default now(),constraint ck_defesa_equipe_agente_datas check(data_saida is null or data_saida>=data_entrada),unique(tenant_id,entity_id,equipe_id,agente_id,data_entrada));
create table if not exists sigov.defesa_recurso_operacional(id bigint generated always as identity primary key,tenant_id bigint not null,entity_id bigint not null,tipo text not null,descricao text not null,patrimonio_codigo text,placa_viatura text,situacao text not null,localizacao text,observacao text,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz);
create table if not exists sigov.defesa_area_risco(id bigint generated always as identity primary key,tenant_id bigint not null,entity_id bigint not null,nome text not null,tipo_risco text not null check(tipo_risco in('ALAGAMENTO','DESLIZAMENTO','INCENDIO','ESTRUTURAL','AMBIENTAL','OUTRO')),nivel_risco text not null check(nivel_risco in('BAIXO','MEDIO','ALTO','CRITICO')),endereco text not null,bairro text not null,latitude numeric(9,6),longitude numeric(9,6),descricao text not null,populacao_estimada integer,status text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz,constraint ck_defesa_area_coords check((latitude is null or latitude between -90 and 90) and (longitude is null or longitude between -180 and 180)),constraint ck_defesa_area_critica check(nivel_risco<>'CRITICO' or length(trim(descricao))>=30));
create table if not exists sigov.defesa_ocorrencia(id bigint generated always as identity primary key,tenant_id bigint not null,entity_id bigint not null,numero_ocorrencia text not null,tipo_ocorrencia text not null,origem_chamado text not null,data_hora_abertura timestamptz not null,data_hora_fechamento timestamptz,endereco text not null,bairro text not null,latitude numeric(9,6),longitude numeric(9,6),area_risco_id bigint references sigov.defesa_area_risco(id),equipe_responsavel_id bigint references sigov.defesa_equipe(id),prioridade text not null,status text not null,descricao text not null,providencias text,resultado text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz,constraint uq_defesa_ocorrencia_num unique(tenant_id,entity_id,numero_ocorrencia),constraint ck_defesa_ocorrencia_coords check((latitude is null or latitude between -90 and 90) and (longitude is null or longitude between -180 and 180)),constraint ck_defesa_ocorrencia_datas check(data_hora_fechamento is null or data_hora_fechamento>=data_hora_abertura),constraint ck_defesa_ocorrencia_fechada check(status<>'FECHADA' or(data_hora_fechamento is not null and nullif(trim(providencias),'') is not null and nullif(trim(resultado),'') is not null)));
create table if not exists sigov.defesa_acionamento(id bigint generated always as identity primary key,tenant_id bigint not null,entity_id bigint not null,ocorrencia_id bigint not null references sigov.defesa_ocorrencia(id),equipe_id bigint not null references sigov.defesa_equipe(id),agente_responsavel_id bigint references sigov.defesa_agente(id),data_hora_acionamento timestamptz not null,data_hora_chegada timestamptz,data_hora_encerramento timestamptz,status text not null,observacao text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz,constraint ck_defesa_acionamento_datas check((data_hora_chegada is null or data_hora_chegada>=data_hora_acionamento)and(data_hora_encerramento is null or data_hora_encerramento>=coalesce(data_hora_chegada,data_hora_acionamento))));
create table if not exists sigov.defesa_vistoria(id bigint generated always as identity primary key,tenant_id bigint not null,entity_id bigint not null,numero_vistoria text not null,tipo_vistoria text not null,area_risco_id bigint references sigov.defesa_area_risco(id),ocorrencia_id bigint references sigov.defesa_ocorrencia(id),agente_responsavel_id bigint not null references sigov.defesa_agente(id),data_vistoria date not null,endereco text not null,bairro text not null,situacao_encontrada text not null,recomendacoes text not null,prazo_regularizacao date,status text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz,constraint uq_defesa_vistoria_num unique(tenant_id,entity_id,numero_vistoria),constraint ck_defesa_vistoria_datas check(prazo_regularizacao is null or prazo_regularizacao>=data_vistoria));
create table if not exists sigov.defesa_abrigo(id bigint generated always as identity primary key,tenant_id bigint not null,entity_id bigint not null,nome text not null,tipo text not null,endereco text not null,bairro text not null,capacidade_total integer not null,capacidade_ocupada integer not null default 0,responsavel_nome text not null,responsavel_telefone text,status text not null,observacao text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz,constraint ck_defesa_abrigo_capacidade check(capacidade_total>=0 and capacidade_ocupada>=0 and capacidade_ocupada<=capacidade_total));
create table if not exists sigov.defesa_atendimento_emergencial(id bigint generated always as identity primary key,tenant_id bigint not null,entity_id bigint not null,ocorrencia_id bigint references sigov.defesa_ocorrencia(id),abrigo_id bigint references sigov.defesa_abrigo(id),nome_responsavel_familiar text not null,documento_responsavel text,telefone text,quantidade_pessoas integer not null,quantidade_criancas integer not null default 0,quantidade_idosos integer not null default 0,necessidade_especial text,tipo_apoio text not null,descricao_apoio text,data_atendimento timestamptz not null,status text not null,observacao text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz,constraint ck_defesa_atendimento_quantidades check(quantidade_pessoas>=1 and quantidade_criancas>=0 and quantidade_idosos>=0 and quantidade_criancas<=quantidade_pessoas and quantidade_idosos<=quantidade_pessoas));
create table if not exists sigov.defesa_ronda(id bigint generated always as identity primary key,tenant_id bigint not null,entity_id bigint not null,numero_ronda text not null,equipe_id bigint not null references sigov.defesa_equipe(id),agente_responsavel_id bigint not null references sigov.defesa_agente(id),data_hora_inicio timestamptz not null,data_hora_fim timestamptz,area_atuacao text not null,tipo_ronda text not null,status text not null,resumo text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz,constraint uq_defesa_ronda_num unique(tenant_id,entity_id,numero_ronda),constraint ck_defesa_ronda_datas check(data_hora_fim is null or data_hora_fim>=data_hora_inicio),constraint ck_defesa_ronda_concluida check(status<>'CONCLUIDA' or nullif(trim(resumo),'') is not null));
create table if not exists sigov.defesa_ordem_servico(id bigint generated always as identity primary key,tenant_id bigint not null,entity_id bigint not null,numero_os text not null,tipo_servico text not null,solicitante text not null,equipe_id bigint references sigov.defesa_equipe(id),agente_responsavel_id bigint references sigov.defesa_agente(id),data_abertura timestamptz not null,data_previsao timestamptz,data_conclusao timestamptz,prioridade text not null,status text not null,descricao text not null,resultado text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz,constraint uq_defesa_os_num unique(tenant_id,entity_id,numero_os),constraint ck_defesa_os_datas check((data_previsao is null or data_previsao>=data_abertura)and(data_conclusao is null or data_conclusao>=data_abertura)),constraint ck_defesa_os_concluida check(status<>'CONCLUIDA' or nullif(trim(resultado),'') is not null));
create table if not exists sigov.defesa_notificacao_preventiva(id bigint generated always as identity primary key,tenant_id bigint not null,entity_id bigint not null,numero_notificacao text not null,vistoria_id bigint references sigov.defesa_vistoria(id),area_risco_id bigint references sigov.defesa_area_risco(id),destinatario_nome text not null,destinatario_documento text,endereco text not null,data_emissao date not null,prazo_atendimento date,motivo text not null,recomendacao text not null,status text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz,constraint uq_defesa_notificacao_num unique(tenant_id,entity_id,numero_notificacao),constraint ck_defesa_notificacao_datas check(prazo_atendimento is null or prazo_atendimento>=data_emissao));
create table if not exists sigov.defesa_plano_contingencia(id bigint generated always as identity primary key,tenant_id bigint not null,entity_id bigint not null,titulo text not null,tipo_evento text not null,area_risco_id bigint references sigov.defesa_area_risco(id),responsavel_agente_id bigint not null references sigov.defesa_agente(id),vigencia_inicio date not null,vigencia_fim date,resumo text not null,medidas_preventivas text,fluxos_acionamento text,status text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz,constraint ck_defesa_plano_datas check(vigencia_fim is null or vigencia_fim>=vigencia_inicio),constraint ck_defesa_plano_ativo check(status<>'ATIVO' or(nullif(trim(medidas_preventivas),'') is not null and nullif(trim(fluxos_acionamento),'') is not null)));
create table if not exists sigov.defesa_auditoria(id bigint generated always as identity primary key,tenant_id bigint not null,entity_id bigint not null,tabela text not null,registro_id bigint not null,acao text not null,usuario text not null,dados_anteriores jsonb,dados_novos jsonb,created_at timestamptz not null default now());

create index if not exists ix_defesa_ocorrencia_contexto on sigov.defesa_ocorrencia(tenant_id,entity_id,status,prioridade) where deleted_at is null;
create index if not exists ix_defesa_acionamento_contexto on sigov.defesa_acionamento(tenant_id,entity_id,status) where deleted_at is null;
create index if not exists ix_defesa_auditoria_contexto on sigov.defesa_auditoria(tenant_id,entity_id,created_at desc);

insert into sigov.permissao(chave,descricao,modulo,ativo,created_at)
select p.chave,p.nome,'defesa',true,now() from(values
('DEFESA_DASHBOARD_VIEW','Visualizar dashboard de Defesa'),('DEFESA_AGENTE_VIEW','Visualizar agentes'),('DEFESA_AGENTE_MANAGE','Gerenciar agentes'),('DEFESA_EQUIPE_VIEW','Visualizar equipes'),('DEFESA_EQUIPE_MANAGE','Gerenciar equipes'),('DEFESA_RECURSO_VIEW','Visualizar recursos'),('DEFESA_RECURSO_MANAGE','Gerenciar recursos'),('DEFESA_AREA_RISCO_VIEW','Visualizar areas de risco'),('DEFESA_AREA_RISCO_MANAGE','Gerenciar areas de risco'),('DEFESA_OCORRENCIA_VIEW','Visualizar ocorrencias'),('DEFESA_OCORRENCIA_MANAGE','Gerenciar ocorrencias'),('DEFESA_ACIONAMENTO_VIEW','Visualizar acionamentos'),('DEFESA_ACIONAMENTO_MANAGE','Gerenciar acionamentos'),('DEFESA_VISTORIA_VIEW','Visualizar vistorias'),('DEFESA_VISTORIA_MANAGE','Gerenciar vistorias'),('DEFESA_ABRIGO_VIEW','Visualizar abrigos'),('DEFESA_ABRIGO_MANAGE','Gerenciar abrigos'),('DEFESA_ATENDIMENTO_VIEW','Visualizar atendimentos'),('DEFESA_ATENDIMENTO_MANAGE','Gerenciar atendimentos'),('DEFESA_RONDA_VIEW','Visualizar rondas'),('DEFESA_RONDA_MANAGE','Gerenciar rondas'),('DEFESA_OS_VIEW','Visualizar ordens de servico'),('DEFESA_OS_MANAGE','Gerenciar ordens de servico'),('DEFESA_NOTIFICACAO_VIEW','Visualizar notificacoes'),('DEFESA_NOTIFICACAO_MANAGE','Gerenciar notificacoes'),('DEFESA_PLANO_VIEW','Visualizar planos'),('DEFESA_PLANO_MANAGE','Gerenciar planos'),('DEFESA_RELATORIO_EXPORT','Exportar relatorios de Defesa'),('DEFESA_AUDITORIA_VIEW','Visualizar auditoria de Defesa'))p(chave,nome)
on conflict(chave) do update set descricao=excluded.descricao,modulo=excluded.modulo,ativo=true;
