-- RC50.68F: administração auditável da matriz persistente.
create table if not exists sigov.autorizacao_admin_auditoria (
    id bigint generated by default as identity primary key,
    operacao varchar(80) not null,
    entidade varchar(80) not null,
    registro_chave varchar(160),
    usuario_id bigint,
    correlation_id varchar(100),
    antes jsonb,
    depois jsonb,
    ocorrido_em_utc timestamptz not null default now()
);

create index if not exists ix_autorizacao_admin_auditoria_ocorrido
    on sigov.autorizacao_admin_auditoria(ocorrido_em_utc desc, entidade, operacao);

insert into sigov.permissao(modulo,chave,recurso,acao,descricao,ativo,is_deleted)
values ('saas','saas.superadmin.autorizacao.administrar','saas.superadmin.autorizacao','administrar',
        'Administrar a matriz contextual persistida',true,false)
on conflict(modulo,chave) do update
 set recurso=excluded.recurso,acao=excluded.acao,descricao=excluded.descricao,ativo=true,is_deleted=false,updated_at=now();

insert into sigov.perfil_permissao(perfil_acesso_id,permissao_id,efeito,ativo,is_deleted,justificativa)
select pa.id,p.id,'PERMITIR',true,false,'RC50.68F: administração SuperAdmin persistida'
from sigov.perfil_acesso pa
join sigov.permissao p on p.chave='saas.superadmin.autorizacao.administrar'
where pa.codigo_externo='SUPERADMIN' and pa.sistemico and pa.ativo and not pa.is_deleted
on conflict(perfil_acesso_id,permissao_id) do update
 set efeito='PERMITIR',ativo=true,is_deleted=false,justificativa=excluded.justificativa,updated_at=now();
