-- Pós-RC 32: estrutura aditiva da operação de campo.
create table if not exists sigov.os_numeracao(tenant_id uuid not null,ano int not null,ultimo_numero bigint not null,updated_at timestamptz not null default now(),primary key(tenant_id,ano));
create table if not exists sigov.os_ordem_servico(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,numero varchar(40) not null,cliente_id uuid not null,cliente_nome varchar(250) not null,pedido_id uuid,proposta_id uuid,tecnico_id uuid,equipe_id uuid,status varchar(30) not null,prioridade varchar(20) not null,origem varchar(30) not null,descricao text not null,endereco text,prazo_sla timestamptz,agendada_inicio timestamptz,agendada_fim timestamptz,inicio_real timestamptz,conclusao_em timestamptz,custo_real numeric(18,2) not null default 0,version bigint not null default 1,is_deleted boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by varchar(80) not null,updated_by varchar(80) not null,correlation_id varchar(120),unique(tenant_id,numero),unique(tenant_id,pedido_id));
create index if not exists ix_os_operacao on sigov.os_ordem_servico(tenant_id,status,prioridade,agendada_inicio) where not is_deleted;
create table if not exists sigov.os_item(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,ordem_servico_id uuid not null references sigov.os_ordem_servico(id),descricao text not null,quantidade numeric(18,4) not null check(quantidade>0),unidade varchar(20) not null,ordem int not null,executado boolean not null default false,justificativa text,version bigint not null default 1,is_deleted boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by varchar(80) not null,updated_by varchar(80) not null,correlation_id varchar(120));
create table if not exists sigov.os_agendamento(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,ordem_servico_id uuid not null references sigov.os_ordem_servico(id),tecnico_id uuid,equipe_id uuid,inicio timestamptz not null,fim timestamptz not null,janela varchar(100),observacao text,conflito_autorizado boolean not null default false,justificativa_conflito text,version bigint not null default 1,is_deleted boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by varchar(80) not null,updated_by varchar(80) not null,correlation_id varchar(120),check(fim>inicio));
create index if not exists ix_os_agenda_tecnico on sigov.os_agendamento(tenant_id,tecnico_id,inicio,fim) where not is_deleted;
create table if not exists sigov.os_checklist_instancia(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,ordem_servico_id uuid not null references sigov.os_ordem_servico(id),titulo text not null,tipo varchar(30) not null,ordem int not null,obrigatorio boolean not null default false,bloqueia_conclusao boolean not null default false,respondido boolean not null default false,resposta text,observacao_resposta text,evidencia_id uuid,respondido_em timestamptz,version bigint not null default 1,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by varchar(80) not null,updated_by varchar(80) not null,correlation_id varchar(120));
create table if not exists sigov.os_apontamento(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,ordem_servico_id uuid not null references sigov.os_ordem_servico(id),tecnico_id uuid not null,atividade text not null,inicio timestamptz not null,fim timestamptz,intervalo_minutos int not null default 0,observacao text,idempotency_key varchar(200) not null,version bigint not null default 1,is_deleted boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by varchar(80) not null,updated_by varchar(80) not null,correlation_id varchar(120),unique(tenant_id,idempotency_key),check(fim is null or fim>=inicio),check(intervalo_minutos>=0));
create unique index if not exists ux_os_cronometro_aberto on sigov.os_apontamento(tenant_id,tecnico_id) where fim is null and not is_deleted;
create table if not exists sigov.os_consumo_peca(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,ordem_servico_id uuid not null references sigov.os_ordem_servico(id),produto_id uuid not null,almoxarifado_id uuid not null,quantidade numeric(18,4) not null,custo_unitario numeric(18,4) not null,quantidade_devolvida numeric(18,4) not null default 0,idempotency_key varchar(200) not null,version bigint not null default 1,is_deleted boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by varchar(80) not null,updated_by varchar(80) not null,correlation_id varchar(120),unique(tenant_id,idempotency_key),check(quantidade>0));
create table if not exists sigov.os_devolucao_peca(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,ordem_servico_id uuid not null,consumo_id uuid not null references sigov.os_consumo_peca(id),produto_id uuid not null,almoxarifado_id uuid not null,quantidade numeric(18,4) not null,motivo text not null,idempotency_key varchar(200) not null,version bigint not null default 1,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by varchar(80) not null,updated_by varchar(80) not null,correlation_id varchar(120),unique(tenant_id,idempotency_key),check(quantidade>0));
create table if not exists sigov.os_status_historico(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,ordem_servico_id uuid not null,status_anterior varchar(30),status_novo varchar(30) not null,observacao text,version bigint not null default 1,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by varchar(80) not null,updated_by varchar(80) not null,correlation_id varchar(120));
create table if not exists sigov.os_idempotencia(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,operacao varchar(50) not null,chave varchar(200) not null,recurso_id uuid not null,version bigint not null default 1,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by varchar(80) not null,updated_by varchar(80) not null,correlation_id varchar(120),unique(tenant_id,operacao,chave));
alter table if exists sigov.enterprise_integracao_financeira add column if not exists conta_receber_core_id bigint,add column if not exists tenant_core_id bigint;
create index if not exists ix_enterprise_financeiro_core on sigov.enterprise_integracao_financeira(tenant_core_id,conta_receber_core_id);