-- FUNC15: Ouvidoria, Atendimento ao Cidadão, e-SIC e Carta de Serviços
-- Idempotente; executar com psql -v ON_ERROR_STOP=1.
CREATE SCHEMA IF NOT EXISTS sigov;
CREATE TABLE IF NOT EXISTS sigov.atendimento_cidadao (
 id bigint generated by default as identity primary key,
 tenant_id bigint not null, entidade_id bigint not null, codigo varchar(80), descricao text not null, status varchar(40) not null default 'ATIVO', dados jsonb not null default '{}'::jsonb,
 ativo boolean not null default true, is_deleted boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz, created_by bigint, updated_by bigint, deleted_by bigint,
 constraint ck_atendimento_cidadao_exclusao check ((not is_deleted and deleted_at is null and deleted_by is null) or (is_deleted and deleted_at is not null)),
 constraint ck_atendimento_cidadao_dados check (jsonb_typeof(dados)='object'), nome varchar(200) not null, cpf_cnpj varchar(14), data_nascimento date, email varchar(254), telefone varchar(30), endereco text, bairro varchar(120), municipio varchar(120), uf char(2), consentimento_lgpd boolean not null default false, consentimento_em timestamptz, observacoes_internas text, constraint ck_atendimento_cidadao_consentimento check (not consentimento_lgpd or consentimento_em is not null)
);
CREATE INDEX IF NOT EXISTS ix_atendimento_cidadao_contexto_status ON sigov.atendimento_cidadao(tenant_id, entidade_id, status) WHERE NOT is_deleted;
CREATE INDEX IF NOT EXISTS ix_atendimento_cidadao_datas ON sigov.atendimento_cidadao(created_at, updated_at);
CREATE TABLE IF NOT EXISTS sigov.atendimento_contato (
 id bigint generated by default as identity primary key,
 tenant_id bigint not null, entidade_id bigint not null, codigo varchar(80), descricao text not null, status varchar(40) not null default 'ATIVO', dados jsonb not null default '{}'::jsonb,
 ativo boolean not null default true, is_deleted boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz, created_by bigint, updated_by bigint, deleted_by bigint,
 constraint ck_atendimento_contato_exclusao check ((not is_deleted and deleted_at is null and deleted_by is null) or (is_deleted and deleted_at is not null)),
 constraint ck_atendimento_contato_dados check (jsonb_typeof(dados)='object'), cidadao_id bigint references sigov.atendimento_cidadao(id), tipo varchar(30), valor varchar(254)
);
CREATE INDEX IF NOT EXISTS ix_atendimento_contato_contexto_status ON sigov.atendimento_contato(tenant_id, entidade_id, status) WHERE NOT is_deleted;
CREATE INDEX IF NOT EXISTS ix_atendimento_contato_datas ON sigov.atendimento_contato(created_at, updated_at);
CREATE TABLE IF NOT EXISTS sigov.atendimento_servico (
 id bigint generated by default as identity primary key,
 tenant_id bigint not null, entidade_id bigint not null, codigo varchar(80), descricao text not null, status varchar(40) not null default 'ATIVO', dados jsonb not null default '{}'::jsonb,
 ativo boolean not null default true, is_deleted boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz, created_by bigint, updated_by bigint, deleted_by bigint,
 constraint ck_atendimento_servico_exclusao check ((not is_deleted and deleted_at is null and deleted_by is null) or (is_deleted and deleted_at is not null)),
 constraint ck_atendimento_servico_dados check (jsonb_typeof(dados)='object'), nome varchar(200) not null, setor_responsavel varchar(200) not null, requisitos text, prazo_dias integer, canais text, custo numeric(14,2), constraint ck_atendimento_servico_prazo check (prazo_dias is null or prazo_dias>=0), constraint ck_atendimento_servico_custo check(custo is null or custo>=0)
);
CREATE INDEX IF NOT EXISTS ix_atendimento_servico_contexto_status ON sigov.atendimento_servico(tenant_id, entidade_id, status) WHERE NOT is_deleted;
CREATE INDEX IF NOT EXISTS ix_atendimento_servico_datas ON sigov.atendimento_servico(created_at, updated_at);
CREATE TABLE IF NOT EXISTS sigov.atendimento_canal (
 id bigint generated by default as identity primary key,
 tenant_id bigint not null, entidade_id bigint not null, codigo varchar(80), descricao text not null, status varchar(40) not null default 'ATIVO', dados jsonb not null default '{}'::jsonb,
 ativo boolean not null default true, is_deleted boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz, created_by bigint, updated_by bigint, deleted_by bigint,
 constraint ck_atendimento_canal_exclusao check ((not is_deleted and deleted_at is null and deleted_by is null) or (is_deleted and deleted_at is not null)),
 constraint ck_atendimento_canal_dados check (jsonb_typeof(dados)='object'), nome varchar(120) not null
);
CREATE INDEX IF NOT EXISTS ix_atendimento_canal_contexto_status ON sigov.atendimento_canal(tenant_id, entidade_id, status) WHERE NOT is_deleted;
CREATE INDEX IF NOT EXISTS ix_atendimento_canal_datas ON sigov.atendimento_canal(created_at, updated_at);
CREATE TABLE IF NOT EXISTS sigov.atendimento_demanda (
 id bigint generated by default as identity primary key,
 tenant_id bigint not null, entidade_id bigint not null, codigo varchar(80), descricao text not null, status varchar(40) not null default 'ATIVO', dados jsonb not null default '{}'::jsonb,
 ativo boolean not null default true, is_deleted boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz, created_by bigint, updated_by bigint, deleted_by bigint,
 constraint ck_atendimento_demanda_exclusao check ((not is_deleted and deleted_at is null and deleted_by is null) or (is_deleted and deleted_at is not null)),
 constraint ck_atendimento_demanda_dados check (jsonb_typeof(dados)='object'), cidadao_id bigint references sigov.atendimento_cidadao(id), servico_id bigint references sigov.atendimento_servico(id), canal_id bigint references sigov.atendimento_canal(id), assunto varchar(250) not null, prioridade varchar(20) not null default 'NORMAL', prazo timestamptz, responsavel_id bigint, justificativa text, constraint ck_atendimento_demanda_status check(status in('ABERTO','EM_TRIAGEM','ENCAMINHADO','EM_ATENDIMENTO','AGUARDANDO_CIDADAO','CONCLUIDO','CANCELADO','ARQUIVADO')), constraint ck_atendimento_demanda_just check(status not in('CONCLUIDO','CANCELADO','ARQUIVADO') or nullif(trim(justificativa),'') is not null)
);
CREATE INDEX IF NOT EXISTS ix_atendimento_demanda_contexto_status ON sigov.atendimento_demanda(tenant_id, entidade_id, status) WHERE NOT is_deleted;
CREATE INDEX IF NOT EXISTS ix_atendimento_demanda_datas ON sigov.atendimento_demanda(created_at, updated_at);
CREATE TABLE IF NOT EXISTS sigov.atendimento_ouvidoria_manifestacao (
 id bigint generated by default as identity primary key,
 tenant_id bigint not null, entidade_id bigint not null, codigo varchar(80), descricao text not null, status varchar(40) not null default 'ATIVO', dados jsonb not null default '{}'::jsonb,
 ativo boolean not null default true, is_deleted boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz, created_by bigint, updated_by bigint, deleted_by bigint,
 constraint ck_atendimento_ouvidoria_manifestacao_exclusao check ((not is_deleted and deleted_at is null and deleted_by is null) or (is_deleted and deleted_at is not null)),
 constraint ck_atendimento_ouvidoria_manifestacao_dados check (jsonb_typeof(dados)='object'), demanda_id bigint references sigov.atendimento_demanda(id), cidadao_id bigint references sigov.atendimento_cidadao(id), tipo varchar(30) not null, anonima boolean not null default false, sigilosa boolean not null default false, denunciante_dados jsonb, resposta text, justificativa text, constraint ck_ouvidoria_tipo check(tipo in('RECLAMACAO','DENUNCIA','SUGESTAO','ELOGIO','SOLICITACAO','COMUNICACAO')), constraint ck_ouvidoria_anonima check(not anonima or cidadao_id is null)
);
CREATE INDEX IF NOT EXISTS ix_atendimento_ouvidoria_manifestacao_contexto_status ON sigov.atendimento_ouvidoria_manifestacao(tenant_id, entidade_id, status) WHERE NOT is_deleted;
CREATE INDEX IF NOT EXISTS ix_atendimento_ouvidoria_manifestacao_datas ON sigov.atendimento_ouvidoria_manifestacao(created_at, updated_at);
CREATE TABLE IF NOT EXISTS sigov.atendimento_esic_pedido (
 id bigint generated by default as identity primary key,
 tenant_id bigint not null, entidade_id bigint not null, codigo varchar(80), descricao text not null, status varchar(40) not null default 'ATIVO', dados jsonb not null default '{}'::jsonb,
 ativo boolean not null default true, is_deleted boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz, created_by bigint, updated_by bigint, deleted_by bigint,
 constraint ck_atendimento_esic_pedido_exclusao check ((not is_deleted and deleted_at is null and deleted_by is null) or (is_deleted and deleted_at is not null)),
 constraint ck_atendimento_esic_pedido_dados check (jsonb_typeof(dados)='object'), solicitante_id bigint references sigov.atendimento_cidadao(id), setor_destino varchar(200) not null, prazo timestamptz not null, resposta text, justificativa text, constraint ck_esic_status check(status in('RECEBIDO','EM_ANALISE','PRORROGADO','RESPONDIDO','NEGADO','RECURSO','CANCELADO')), constraint ck_esic_just check(status not in('PRORROGADO','NEGADO','CANCELADO') or nullif(trim(justificativa),'') is not null)
);
CREATE INDEX IF NOT EXISTS ix_atendimento_esic_pedido_contexto_status ON sigov.atendimento_esic_pedido(tenant_id, entidade_id, status) WHERE NOT is_deleted;
CREATE INDEX IF NOT EXISTS ix_atendimento_esic_pedido_datas ON sigov.atendimento_esic_pedido(created_at, updated_at);
CREATE TABLE IF NOT EXISTS sigov.atendimento_encaminhamento (
 id bigint generated by default as identity primary key,
 tenant_id bigint not null, entidade_id bigint not null, codigo varchar(80), descricao text not null, status varchar(40) not null default 'ATIVO', dados jsonb not null default '{}'::jsonb,
 ativo boolean not null default true, is_deleted boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz, created_by bigint, updated_by bigint, deleted_by bigint,
 constraint ck_atendimento_encaminhamento_exclusao check ((not is_deleted and deleted_at is null and deleted_by is null) or (is_deleted and deleted_at is not null)),
 constraint ck_atendimento_encaminhamento_dados check (jsonb_typeof(dados)='object'), demanda_id bigint references sigov.atendimento_demanda(id), origem varchar(200) not null, destino varchar(200) not null, responsavel_id bigint, encaminhado_em timestamptz not null default now(), prazo timestamptz, resposta text, justificativa text, constraint ck_enc_status check(status in('PENDENTE','RECEBIDO','DEVOLVIDO','CONCLUIDO','REENCAMINHADO')), constraint ck_enc_just check(status not in('DEVOLVIDO','CONCLUIDO','REENCAMINHADO') or nullif(trim(justificativa),'') is not null)
);
CREATE INDEX IF NOT EXISTS ix_atendimento_encaminhamento_contexto_status ON sigov.atendimento_encaminhamento(tenant_id, entidade_id, status) WHERE NOT is_deleted;
CREATE INDEX IF NOT EXISTS ix_atendimento_encaminhamento_datas ON sigov.atendimento_encaminhamento(created_at, updated_at);
CREATE TABLE IF NOT EXISTS sigov.atendimento_historico (
 id bigint generated by default as identity primary key,
 tenant_id bigint not null, entidade_id bigint not null, codigo varchar(80), descricao text not null, status varchar(40) not null default 'ATIVO', dados jsonb not null default '{}'::jsonb,
 ativo boolean not null default true, is_deleted boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz, created_by bigint, updated_by bigint, deleted_by bigint,
 constraint ck_atendimento_historico_exclusao check ((not is_deleted and deleted_at is null and deleted_by is null) or (is_deleted and deleted_at is not null)),
 constraint ck_atendimento_historico_dados check (jsonb_typeof(dados)='object'), recurso varchar(60) not null, registro_id bigint not null, status_anterior varchar(40), status_novo varchar(40), justificativa text
);
CREATE INDEX IF NOT EXISTS ix_atendimento_historico_contexto_status ON sigov.atendimento_historico(tenant_id, entidade_id, status) WHERE NOT is_deleted;
CREATE INDEX IF NOT EXISTS ix_atendimento_historico_datas ON sigov.atendimento_historico(created_at, updated_at);
CREATE TABLE IF NOT EXISTS sigov.atendimento_agenda (
 id bigint generated by default as identity primary key,
 tenant_id bigint not null, entidade_id bigint not null, codigo varchar(80), descricao text not null, status varchar(40) not null default 'ATIVO', dados jsonb not null default '{}'::jsonb,
 ativo boolean not null default true, is_deleted boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz, created_by bigint, updated_by bigint, deleted_by bigint,
 constraint ck_atendimento_agenda_exclusao check ((not is_deleted and deleted_at is null and deleted_by is null) or (is_deleted and deleted_at is not null)),
 constraint ck_atendimento_agenda_dados check (jsonb_typeof(dados)='object'), servico_id bigint references sigov.atendimento_servico(id), setor varchar(200) not null, inicio_vigencia date not null, fim_vigencia date, slot_minutos integer not null, constraint ck_agenda_slot check(slot_minutos between 5 and 1440)
);
CREATE INDEX IF NOT EXISTS ix_atendimento_agenda_contexto_status ON sigov.atendimento_agenda(tenant_id, entidade_id, status) WHERE NOT is_deleted;
CREATE INDEX IF NOT EXISTS ix_atendimento_agenda_datas ON sigov.atendimento_agenda(created_at, updated_at);
CREATE TABLE IF NOT EXISTS sigov.atendimento_agendamento (
 id bigint generated by default as identity primary key,
 tenant_id bigint not null, entidade_id bigint not null, codigo varchar(80), descricao text not null, status varchar(40) not null default 'ATIVO', dados jsonb not null default '{}'::jsonb,
 ativo boolean not null default true, is_deleted boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz, created_by bigint, updated_by bigint, deleted_by bigint,
 constraint ck_atendimento_agendamento_exclusao check ((not is_deleted and deleted_at is null and deleted_by is null) or (is_deleted and deleted_at is not null)),
 constraint ck_atendimento_agendamento_dados check (jsonb_typeof(dados)='object'), agenda_id bigint not null references sigov.atendimento_agenda(id), cidadao_id bigint not null references sigov.atendimento_cidadao(id), inicio timestamptz not null, fim timestamptz not null, justificativa text, constraint ck_agendamento_status check(status in('AGENDADO','CONFIRMADO','ATENDIDO','FALTOU','CANCELADO')), constraint ck_agendamento_periodo check(fim>inicio), constraint ck_agendamento_just check(status<>'CANCELADO' or nullif(trim(justificativa),'') is not null)
);
CREATE INDEX IF NOT EXISTS ix_atendimento_agendamento_contexto_status ON sigov.atendimento_agendamento(tenant_id, entidade_id, status) WHERE NOT is_deleted;
CREATE INDEX IF NOT EXISTS ix_atendimento_agendamento_datas ON sigov.atendimento_agendamento(created_at, updated_at);
CREATE TABLE IF NOT EXISTS sigov.atendimento_sla_parametro (
 id bigint generated by default as identity primary key,
 tenant_id bigint not null, entidade_id bigint not null, codigo varchar(80), descricao text not null, status varchar(40) not null default 'ATIVO', dados jsonb not null default '{}'::jsonb,
 ativo boolean not null default true, is_deleted boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz, created_by bigint, updated_by bigint, deleted_by bigint,
 constraint ck_atendimento_sla_parametro_exclusao check ((not is_deleted and deleted_at is null and deleted_by is null) or (is_deleted and deleted_at is not null)),
 constraint ck_atendimento_sla_parametro_dados check (jsonb_typeof(dados)='object'), tipo varchar(40) not null, servico_id bigint references sigov.atendimento_servico(id), prazo_dias integer not null, permite_prorrogacao boolean not null default false, constraint ck_sla_prazo check(prazo_dias>0)
);
CREATE INDEX IF NOT EXISTS ix_atendimento_sla_parametro_contexto_status ON sigov.atendimento_sla_parametro(tenant_id, entidade_id, status) WHERE NOT is_deleted;
CREATE INDEX IF NOT EXISTS ix_atendimento_sla_parametro_datas ON sigov.atendimento_sla_parametro(created_at, updated_at);
CREATE TABLE IF NOT EXISTS sigov.atendimento_prazo_alerta (
 id bigint generated by default as identity primary key,
 tenant_id bigint not null, entidade_id bigint not null, codigo varchar(80), descricao text not null, status varchar(40) not null default 'ATIVO', dados jsonb not null default '{}'::jsonb,
 ativo boolean not null default true, is_deleted boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz, created_by bigint, updated_by bigint, deleted_by bigint,
 constraint ck_atendimento_prazo_alerta_exclusao check ((not is_deleted and deleted_at is null and deleted_by is null) or (is_deleted and deleted_at is not null)),
 constraint ck_atendimento_prazo_alerta_dados check (jsonb_typeof(dados)='object'), recurso varchar(60) not null, registro_id bigint not null, prazo timestamptz not null, nivel varchar(20) not null, lido_em timestamptz
);
CREATE INDEX IF NOT EXISTS ix_atendimento_prazo_alerta_contexto_status ON sigov.atendimento_prazo_alerta(tenant_id, entidade_id, status) WHERE NOT is_deleted;
CREATE INDEX IF NOT EXISTS ix_atendimento_prazo_alerta_datas ON sigov.atendimento_prazo_alerta(created_at, updated_at);
CREATE TABLE IF NOT EXISTS sigov.atendimento_satisfacao (
 id bigint generated by default as identity primary key,
 tenant_id bigint not null, entidade_id bigint not null, codigo varchar(80), descricao text not null, status varchar(40) not null default 'ATIVO', dados jsonb not null default '{}'::jsonb,
 ativo boolean not null default true, is_deleted boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz, created_by bigint, updated_by bigint, deleted_by bigint,
 constraint ck_atendimento_satisfacao_exclusao check ((not is_deleted and deleted_at is null and deleted_by is null) or (is_deleted and deleted_at is not null)),
 constraint ck_atendimento_satisfacao_dados check (jsonb_typeof(dados)='object'), demanda_id bigint references sigov.atendimento_demanda(id), agendamento_id bigint references sigov.atendimento_agendamento(id), nota smallint not null, comentario text, constraint ck_satisfacao_nota check(nota between 1 and 5), constraint ck_satisfacao_vinculo check((demanda_id is not null)::int+(agendamento_id is not null)::int=1)
);
CREATE INDEX IF NOT EXISTS ix_atendimento_satisfacao_contexto_status ON sigov.atendimento_satisfacao(tenant_id, entidade_id, status) WHERE NOT is_deleted;
CREATE INDEX IF NOT EXISTS ix_atendimento_satisfacao_datas ON sigov.atendimento_satisfacao(created_at, updated_at);
CREATE TABLE IF NOT EXISTS sigov.atendimento_base_conhecimento (
 id bigint generated by default as identity primary key,
 tenant_id bigint not null, entidade_id bigint not null, codigo varchar(80), descricao text not null, status varchar(40) not null default 'ATIVO', dados jsonb not null default '{}'::jsonb,
 ativo boolean not null default true, is_deleted boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz, created_by bigint, updated_by bigint, deleted_by bigint,
 constraint ck_atendimento_base_conhecimento_exclusao check ((not is_deleted and deleted_at is null and deleted_by is null) or (is_deleted and deleted_at is not null)),
 constraint ck_atendimento_base_conhecimento_dados check (jsonb_typeof(dados)='object'), pergunta text not null, resposta text not null, servico_id bigint references sigov.atendimento_servico(id), tags text[] not null default '{}'
);
CREATE INDEX IF NOT EXISTS ix_atendimento_base_conhecimento_contexto_status ON sigov.atendimento_base_conhecimento(tenant_id, entidade_id, status) WHERE NOT is_deleted;
CREATE INDEX IF NOT EXISTS ix_atendimento_base_conhecimento_datas ON sigov.atendimento_base_conhecimento(created_at, updated_at);
CREATE TABLE IF NOT EXISTS sigov.atendimento_integracao_referencia (
 id bigint generated by default as identity primary key,
 tenant_id bigint not null, entidade_id bigint not null, codigo varchar(80), descricao text not null, status varchar(40) not null default 'ATIVO', dados jsonb not null default '{}'::jsonb,
 ativo boolean not null default true, is_deleted boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz, created_by bigint, updated_by bigint, deleted_by bigint,
 constraint ck_atendimento_integracao_referencia_exclusao check ((not is_deleted and deleted_at is null and deleted_by is null) or (is_deleted and deleted_at is not null)),
 constraint ck_atendimento_integracao_referencia_dados check (jsonb_typeof(dados)='object'), recurso varchar(60) not null, registro_id bigint not null, sistema_externo varchar(100) not null, referencia_textual varchar(500) not null, metadados jsonb not null default '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS ix_atendimento_integracao_referencia_contexto_status ON sigov.atendimento_integracao_referencia(tenant_id, entidade_id, status) WHERE NOT is_deleted;
CREATE INDEX IF NOT EXISTS ix_atendimento_integracao_referencia_datas ON sigov.atendimento_integracao_referencia(created_at, updated_at);
CREATE TABLE IF NOT EXISTS sigov.atendimento_auditoria (
 id bigint generated by default as identity primary key,
 tenant_id bigint not null, entidade_id bigint not null, codigo varchar(80), descricao text not null, status varchar(40) not null default 'ATIVO', dados jsonb not null default '{}'::jsonb,
 ativo boolean not null default true, is_deleted boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz, created_by bigint, updated_by bigint, deleted_by bigint,
 constraint ck_atendimento_auditoria_exclusao check ((not is_deleted and deleted_at is null and deleted_by is null) or (is_deleted and deleted_at is not null)),
 constraint ck_atendimento_auditoria_dados check (jsonb_typeof(dados)='object'), acao varchar(60) not null, recurso varchar(60) not null, registro_id bigint, usuario_id bigint, antes jsonb, depois jsonb, correlation_id varchar(100), ip inet
);
CREATE INDEX IF NOT EXISTS ix_atendimento_auditoria_contexto_status ON sigov.atendimento_auditoria(tenant_id, entidade_id, status) WHERE NOT is_deleted;
CREATE INDEX IF NOT EXISTS ix_atendimento_auditoria_datas ON sigov.atendimento_auditoria(created_at, updated_at);
CREATE UNIQUE INDEX IF NOT EXISTS ux_atendimento_cidadao_documento ON sigov.atendimento_cidadao(tenant_id,entidade_id,cpf_cnpj) WHERE cpf_cnpj IS NOT NULL AND NOT is_deleted;
CREATE INDEX IF NOT EXISTS ix_atendimento_demanda_prazo ON sigov.atendimento_demanda(tenant_id,entidade_id,prazo) WHERE NOT is_deleted;
CREATE INDEX IF NOT EXISTS ix_atendimento_agendamento_inicio ON sigov.atendimento_agendamento(tenant_id,entidade_id,inicio) WHERE NOT is_deleted;
DO $func15$ DECLARE p text; BEGIN FOREACH p IN ARRAY ARRAY['ATENDIMENTO_DASHBOARD_VIEW','ATENDIMENTO_CIDADAO_VIEW','ATENDIMENTO_CIDADAO_MANAGE','ATENDIMENTO_SERVICO_VIEW','ATENDIMENTO_SERVICO_MANAGE','ATENDIMENTO_DEMANDA_VIEW','ATENDIMENTO_DEMANDA_MANAGE','OUVIDORIA_MANIFESTACAO_VIEW','OUVIDORIA_MANIFESTACAO_MANAGE','OUVIDORIA_SIGILO_VIEW','ESIC_PEDIDO_VIEW','ESIC_PEDIDO_MANAGE','ATENDIMENTO_ENCAMINHAMENTO_VIEW','ATENDIMENTO_ENCAMINHAMENTO_MANAGE','ATENDIMENTO_AGENDA_VIEW','ATENDIMENTO_AGENDA_MANAGE','ATENDIMENTO_AGENDAMENTO_VIEW','ATENDIMENTO_AGENDAMENTO_MANAGE','ATENDIMENTO_SLA_VIEW','ATENDIMENTO_SLA_MANAGE','ATENDIMENTO_SATISFACAO_VIEW','ATENDIMENTO_BASE_CONHECIMENTO_VIEW','ATENDIMENTO_BASE_CONHECIMENTO_MANAGE','ATENDIMENTO_RELATORIO_EXPORT','ATENDIMENTO_AUDITORIA_VIEW'] LOOP
 INSERT INTO sigov.permissao(chave,nome,descricao,modulo,ativo) VALUES(p,replace(initcap(replace(lower(p),'_',' ')),'Esic','e-SIC'),'Permissão persistida do FUNC15','ATENDIMENTO',true) ON CONFLICT(chave) DO UPDATE SET ativo=true,modulo='ATENDIMENTO';
 END LOOP; END $func15$;
