begin;
create schema if not exists sigov;
create extension if not exists pgcrypto;

create table if not exists sigov.tarefa (
  id bigserial primary key, tenant_id bigint not null, titulo text not null, descricao text null, status text not null default 'ABERTA', prioridade text not null default 'NORMAL', responsavel_id bigint null, prazo_em timestamptz null, origem text null, entidade text null, entidade_id text null, created_at timestamptz not null default now(), created_by bigint null, updated_at timestamptz not null default now(), updated_by bigint null, is_deleted boolean not null default false, deleted_at timestamptz null, deleted_by bigint null, correlation_id text null
);
create table if not exists sigov.tarefa_historico (id bigserial primary key, tenant_id bigint not null, tarefa_id bigint not null references sigov.tarefa(id), acao text not null, antes_json jsonb null, depois_json jsonb null, created_at timestamptz not null default now(), created_by bigint null, ip_address text null, user_agent text null, correlation_id text null);
create table if not exists sigov.tarefa_comentario (id bigserial primary key, tenant_id bigint not null, tarefa_id bigint not null references sigov.tarefa(id), comentario text not null, classificacao_acesso text not null default 'INTERNO', created_at timestamptz not null default now(), created_by bigint null, updated_at timestamptz not null default now(), updated_by bigint null, is_deleted boolean not null default false, deleted_at timestamptz null, deleted_by bigint null, correlation_id text null);
create table if not exists sigov.tarefa_anexo (id bigserial primary key, tenant_id bigint not null, tarefa_id bigint not null references sigov.tarefa(id), storage_key text not null, nome_arquivo text not null, content_type text null, classificacao_acesso text not null default 'INTERNO', created_at timestamptz not null default now(), created_by bigint null, updated_at timestamptz not null default now(), updated_by bigint null, is_deleted boolean not null default false, deleted_at timestamptz null, deleted_by bigint null, correlation_id text null);
create table if not exists sigov.tarefa_vinculo (id bigserial primary key, tenant_id bigint not null, tarefa_id bigint not null references sigov.tarefa(id), entidade text not null, entidade_id text not null, created_at timestamptz not null default now(), created_by bigint null, updated_at timestamptz not null default now(), updated_by bigint null, is_deleted boolean not null default false, deleted_at timestamptz null, deleted_by bigint null, correlation_id text null);

create table if not exists sigov.agenda_compromisso (id bigserial primary key, tenant_id bigint not null, titulo text not null, descricao text null, inicio_em timestamptz not null, fim_em timestamptz not null, status text not null default 'AGENDADO', recorrencia text null, origem text null, entidade text null, entidade_id text null, created_at timestamptz not null default now(), created_by bigint null, updated_at timestamptz not null default now(), updated_by bigint null, is_deleted boolean not null default false, deleted_at timestamptz null, deleted_by bigint null, correlation_id text null);
create table if not exists sigov.agenda_participante (id bigserial primary key, tenant_id bigint not null, compromisso_id bigint not null references sigov.agenda_compromisso(id), usuario_id bigint not null, status text not null default 'PENDENTE', created_at timestamptz not null default now(), created_by bigint null, updated_at timestamptz not null default now(), updated_by bigint null, is_deleted boolean not null default false, deleted_at timestamptz null, deleted_by bigint null, correlation_id text null);
create table if not exists sigov.agenda_lembrete (id bigserial primary key, tenant_id bigint not null, compromisso_id bigint not null references sigov.agenda_compromisso(id), lembrar_em timestamptz not null, status text not null default 'PENDENTE', created_at timestamptz not null default now(), created_by bigint null, updated_at timestamptz not null default now(), updated_by bigint null, is_deleted boolean not null default false, deleted_at timestamptz null, deleted_by bigint null, correlation_id text null);
create table if not exists sigov.prazo_operacional (id bigserial primary key, tenant_id bigint not null, titulo text not null, tipo text not null default 'INTERNO', vence_em timestamptz not null, status text not null default 'ABERTO', tarefa_id bigint null references sigov.tarefa(id), origem text null, entidade text null, entidade_id text null, created_at timestamptz not null default now(), created_by bigint null, updated_at timestamptz not null default now(), updated_by bigint null, is_deleted boolean not null default false, deleted_at timestamptz null, deleted_by bigint null, correlation_id text null);
create table if not exists sigov.prazo_historico (id bigserial primary key, tenant_id bigint not null, prazo_id bigint not null references sigov.prazo_operacional(id), acao text not null, antes_json jsonb null, depois_json jsonb null, created_at timestamptz not null default now(), created_by bigint null, correlation_id text null);

create table if not exists sigov.notificacao (id bigserial primary key, tenant_id bigint not null, tipo text not null, titulo text not null, mensagem text null, modulo text null, prioridade text not null default 'NORMAL', origem text null, entidade text null, entidade_id text null, created_at timestamptz not null default now(), created_by bigint null, updated_at timestamptz not null default now(), updated_by bigint null, is_deleted boolean not null default false, deleted_at timestamptz null, deleted_by bigint null, correlation_id text null);
create table if not exists sigov.notificacao_usuario (id bigserial primary key, tenant_id bigint not null, notificacao_id bigint null references sigov.notificacao(id), usuario_id bigint not null, tipo text not null default 'operacional', titulo text not null, lida boolean not null default false, lida_em timestamptz null, arquivada boolean not null default false, created_at timestamptz not null default now(), created_by bigint null, updated_at timestamptz not null default now(), updated_by bigint null, is_deleted boolean not null default false, deleted_at timestamptz null, deleted_by bigint null, correlation_id text null);
create table if not exists sigov.notificacao_preferencia (id bigserial primary key, tenant_id bigint not null, usuario_id bigint not null, tipo text not null, habilitada boolean not null default true, created_at timestamptz not null default now(), created_by bigint null, updated_at timestamptz not null default now(), updated_by bigint null, is_deleted boolean not null default false, deleted_at timestamptz null, deleted_by bigint null, correlation_id text null, unique (tenant_id, usuario_id, tipo));

create table if not exists sigov.kanban_quadro (id bigserial primary key, tenant_id bigint not null, nome text not null, origem text not null, created_at timestamptz not null default now(), created_by bigint null, updated_at timestamptz not null default now(), updated_by bigint null, is_deleted boolean not null default false, deleted_at timestamptz null, deleted_by bigint null, correlation_id text null);
create table if not exists sigov.kanban_coluna (id bigserial primary key, tenant_id bigint not null, quadro_id bigint not null references sigov.kanban_quadro(id), nome text not null, status text not null, ordem int not null default 0, created_at timestamptz not null default now(), created_by bigint null, updated_at timestamptz not null default now(), updated_by bigint null, is_deleted boolean not null default false, deleted_at timestamptz null, deleted_by bigint null, correlation_id text null);
create table if not exists sigov.kanban_card (id bigserial primary key, tenant_id bigint not null, quadro_id bigint null references sigov.kanban_quadro(id), origem text not null, entidade_id bigint not null, titulo text not null, coluna text not null, ordem int not null default 0, responsavel_id bigint null, prioridade text null, prazo_em timestamptz null, sla text null, version int not null default 1, created_at timestamptz not null default now(), created_by bigint null, updated_at timestamptz not null default now(), updated_by bigint null, is_deleted boolean not null default false, deleted_at timestamptz null, deleted_by bigint null, correlation_id text null);
create table if not exists sigov.kanban_historico (id bigserial primary key, tenant_id bigint not null, card_id bigint not null references sigov.kanban_card(id), acao text not null, antes_json jsonb null, depois_json jsonb null, created_at timestamptz not null default now(), created_by bigint null, correlation_id text null);

create table if not exists sigov.outbox_evento (id bigserial primary key, tenant_id bigint not null, event_id uuid not null, event_type text not null, event_version int not null default 1, aggregate_type text not null, aggregate_id text not null, user_id bigint null, correlation_id text null, occurred_at timestamptz not null default now(), payload jsonb not null default '{}'::jsonb, status text not null default 'PENDING', attempts int not null default 0, next_attempt_at timestamptz null, idempotency_key text null unique);

create index if not exists ix_tarefa_tenant_status on sigov.tarefa (tenant_id, status);
create index if not exists ix_tarefa_responsavel_prazo on sigov.tarefa (tenant_id, responsavel_id, prazo_em);
create index if not exists ix_agenda_periodo on sigov.agenda_compromisso (tenant_id, inicio_em, fim_em);
create index if not exists ix_prazo_vencimento on sigov.prazo_operacional (tenant_id, status, vence_em);
create index if not exists ix_notificacao_usuario_lida on sigov.notificacao_usuario (tenant_id, usuario_id, lida);
create index if not exists ix_kanban_filtros on sigov.kanban_card (tenant_id, origem, responsavel_id, sla, coluna);
create index if not exists ix_outbox_evento_status on sigov.outbox_evento (status, next_attempt_at);
commit;
