-- RC50.68C-R1: sessão de contexto operacional por navegador e auditoria atômica.
create table if not exists sigov.tenant_entidade (
 id bigint generated by default as identity primary key,
 tenant_id bigint not null references sigov.tenant(id), entidade_id bigint not null references sigov.entidade(id),
 ativo boolean not null default true, created_at timestamptz not null default now(), unique(tenant_id,entidade_id)
);

alter table sigov.usuario_escopo_acesso add column if not exists unidade_id bigint references sigov.unidade_organizacional(id), add column if not exists vigencia_inicio timestamptz, add column if not exists vigencia_fim timestamptz, add column if not exists modo_acesso varchar(20) not null default 'OPERACIONAL';
alter table sigov.tenant_modulo add column if not exists motivo_bloqueio varchar(500), add column if not exists desativado_at timestamptz;
drop index if exists sigov.ux_usuario_escopo_acesso_resolucao;
create unique index if not exists ux_usuario_escopo_acesso_resolucao on sigov.usuario_escopo_acesso(tenant_id,usuario_id,coalesce(entidade_id,0),coalesce(exercicio_id,0),coalesce(unidade_id,0),coalesce(modulo_codigo,''),escopo) where ativo;

do $$ begin
 if not exists(select 1 from pg_constraint where conname='ck_usuario_escopo_modo') then alter table sigov.usuario_escopo_acesso add constraint ck_usuario_escopo_modo check(modo_acesso in ('LEITURA','OPERACIONAL')); end if;
 if not exists(select 1 from pg_constraint where conname='ck_usuario_escopo_vigencia') then alter table sigov.usuario_escopo_acesso add constraint ck_usuario_escopo_vigencia check(vigencia_fim is null or vigencia_inicio is null or vigencia_fim>=vigencia_inicio); end if;
end $$;

create table if not exists sigov.sessao_contexto_usuario (
 id bigint generated by default as identity primary key, usuario_id bigint not null references sigov.usuario(id),
 chave_sessao_hash varchar(64) not null unique, tenant_id bigint references sigov.tenant(id), entidade_id bigint references sigov.entidade(id),
 unidade_id bigint references sigov.unidade_organizacional(id), exercicio_id bigint references sigov.exercicio(id), sistema_id bigint references sigov.modulo_saas(id), perfil_id bigint references sigov.perfil_acesso(id),
 modo_acesso varchar(20) not null default 'GLOBAL', contexto_global boolean not null default true, situacao varchar(20) not null default 'ATIVA',
 criado_at timestamptz not null default now(), alterado_at timestamptz not null default now(), expira_at timestamptz not null, encerrado_at timestamptz, versao bigint not null default 1,
 constraint ck_sessao_contexto_modo check(modo_acesso in ('GLOBAL','LEITURA','OPERACIONAL')),
 constraint ck_sessao_contexto_situacao check(situacao in ('ATIVA','EXPIRADA','ENCERRADA','REVOGADA')),
 constraint ck_sessao_contexto_coerente check((contexto_global and tenant_id is null and entidade_id is null and unidade_id is null and exercicio_id is null and sistema_id is null) or (not contexto_global and tenant_id is not null and entidade_id is not null and unidade_id is not null and exercicio_id is not null and sistema_id is not null and perfil_id is not null))
);
create index if not exists ix_sessao_contexto_usuario_ativa on sigov.sessao_contexto_usuario(usuario_id,situacao,expira_at);
create index if not exists ix_sessao_contexto_tenant_sistema on sigov.sessao_contexto_usuario(tenant_id,sistema_id) where situacao='ATIVA';

create table if not exists sigov.contexto_operacional_auditoria (
 id bigint generated by default as identity primary key, usuario_executor_id bigint not null references sigov.usuario(id), perfil_efetivo_id bigint references sigov.perfil_acesso(id), sessao_contexto_id bigint references sigov.sessao_contexto_usuario(id),
 tenant_anterior_id bigint references sigov.tenant(id), tenant_novo_id bigint references sigov.tenant(id), entidade_anterior_id bigint references sigov.entidade(id), entidade_nova_id bigint references sigov.entidade(id),
 unidade_anterior_id bigint references sigov.unidade_organizacional(id), unidade_nova_id bigint references sigov.unidade_organizacional(id), exercicio_anterior_id bigint references sigov.exercicio(id), exercicio_novo_id bigint references sigov.exercicio(id), sistema_anterior_id bigint references sigov.modulo_saas(id), sistema_novo_id bigint references sigov.modulo_saas(id),
 modo_acesso varchar(20), justificativa varchar(1000), resultado varchar(20) not null, codigo_motivo varchar(80), ocorrido_at timestamptz not null default now(), correlation_id varchar(100) not null, ip varchar(80), user_agent varchar(500), origem varchar(50) not null, metadados jsonb not null default '{}'::jsonb,
 constraint ck_contexto_auditoria_resultado check(resultado in ('SUCESSO','NEGADO','ERRO'))
);
create index if not exists ix_contexto_auditoria_usuario_data on sigov.contexto_operacional_auditoria(usuario_executor_id,ocorrido_at desc);
create index if not exists ix_contexto_auditoria_tenant_data on sigov.contexto_operacional_auditoria(tenant_novo_id,ocorrido_at desc);

insert into sigov.permissao(modulo,chave,recurso,acao,descricao,ativo,is_deleted)
select 'contexto',v.chave,'contexto',v.acao,v.descricao,true,false from (values
 ('contexto.seletor.visualizar','visualizar','Visualizar seletor de contexto'),('contexto.proprio.alterar','alterar','Alterar o próprio contexto'),('contexto.empresa.assumir','assumir','Assumir contexto empresarial'),('contexto.global.retornar','retornar','Retornar ao contexto global'),('contexto.empresa.visualizar','visualizar','Pesquisar empresas globais'),('contexto.unidade.visualizar','visualizar','Visualizar unidades'),('contexto.exercicio.visualizar','visualizar','Visualizar exercícios'),('contexto.sistema.visualizar','visualizar','Visualizar sistemas disponíveis'),('contexto.leitura.acessar','acessar','Acessar em modo leitura'),('contexto.operacional.acessar','acessar','Acessar em modo operacional')) v(chave,acao,descricao)
where not exists(select 1 from sigov.permissao p where p.modulo='contexto' and p.chave=v.chave);

-- Associação bootstrap por chave natural; depois desta migration a decisão é sempre lida dos vínculos.
insert into sigov.perfil_permissao(perfil_acesso_id,permissao_id,efeito,ativo,is_deleted)
select pa.id,p.id,'PERMITIR',true,false from sigov.perfil_acesso pa cross join sigov.permissao p
where pa.codigo_externo='SUPERADMIN' and pa.sistemico and pa.ativo and not pa.is_deleted and p.modulo='contexto' and p.ativo and not p.is_deleted
on conflict(perfil_acesso_id,permissao_id) do update set efeito='PERMITIR',ativo=true,is_deleted=false;
