-- EXP08 Ativos360: extensões integradas a almoxarifado, patrimônio e frotas existentes.
-- Idempotente, aditiva e sem conversões destrutivas de identificadores legados.
create table if not exists sigov.ativo_transferencia_estoque(
 id bigint generated by default as identity primary key, tenant_id bigint not null, entidade_id bigint not null,
 almoxarifado_origem_id bigint not null, almoxarifado_destino_id bigint not null, material_id bigint not null,
 quantidade numeric(18,4) not null, status varchar(20) not null default 'PENDENTE', justificativa text not null,
 ocorrido_em timestamptz not null default now(), created_by bigint, correlation_id varchar(100) not null,
 constraint ck_ativo_transf_destino check(almoxarifado_origem_id<>almoxarifado_destino_id),
 constraint ck_ativo_transf_qtd check(quantidade>0), constraint ck_ativo_transf_status check(status in('PENDENTE','CONCLUIDA','CANCELADA')));
create table if not exists sigov.ativo_movimentacao_patrimonial(
 id bigint generated by default as identity primary key,tenant_id bigint not null,entidade_id bigint not null,bem_id bigint not null,
 tipo varchar(24) not null,unidade_origem_id bigint,unidade_destino_id bigint,responsavel_origem_id bigint,responsavel_destino_id bigint,
 justificativa text not null,ocorrido_em timestamptz not null default now(),created_by bigint,correlation_id varchar(100) not null,
 constraint ck_ativo_mov_pat_tipo check(tipo in('TOMBAMENTO','TRANSFERENCIA','CESSAO','RETORNO','MANUTENCAO','BAIXA')),
 constraint ck_ativo_mov_pat_transferencia check(tipo<>'TRANSFERENCIA' or unidade_origem_id is distinct from unidade_destino_id));
create table if not exists sigov.ativo_baixa_patrimonial(
 id bigint generated by default as identity primary key,tenant_id bigint not null,entidade_id bigint not null,bem_id bigint not null,
 motivo text not null,autorizado_por bigint not null,data_baixa date not null,valor numeric(18,2),created_at timestamptz not null default now(),created_by bigint,
 constraint ck_ativo_baixa_motivo check(length(trim(motivo))>=5),constraint ck_ativo_baixa_valor check(valor is null or valor>=0));
create table if not exists sigov.ativo_depreciacao_patrimonial(
 id bigint generated by default as identity primary key,tenant_id bigint not null,entidade_id bigint not null,bem_id bigint not null,
 competencia date not null,valor_base numeric(18,2) not null,valor_depreciado numeric(18,2) not null,valor_residual numeric(18,2) not null,
 vida_util_meses integer not null,percentual numeric(9,6) not null,created_at timestamptz not null default now(),created_by bigint,
 constraint ck_ativo_deprec_valores check(valor_base>=0 and valor_depreciado>=0 and valor_residual>=0),
 constraint ck_ativo_deprec_vida check(vida_util_meses>0),constraint ck_ativo_deprec_percentual check(percentual between 0 and 100),unique(tenant_id,bem_id,competencia));
create table if not exists sigov.ativo_veiculo_documento(
 id bigint generated by default as identity primary key,tenant_id bigint not null,entidade_id bigint not null,veiculo_id bigint not null,
 tipo varchar(30) not null,numero varchar(100),emitido_em date,vencimento date not null,status varchar(16) not null default 'VALIDO',evidencia_id bigint,
 created_at timestamptz not null default now(),created_by bigint,constraint ck_ativo_doc_datas check(emitido_em is null or vencimento>=emitido_em),constraint ck_ativo_doc_status check(status in('VALIDO','VENCIDO','CANCELADO')));
create table if not exists sigov.ativo_veiculo_motorista(
 id bigint generated by default as identity primary key,tenant_id bigint not null,entidade_id bigint not null,veiculo_id bigint not null,pessoa_id bigint not null,
 inicio_em date not null,fim_em date,principal boolean not null default false,created_at timestamptz not null default now(),created_by bigint,
 constraint ck_ativo_motorista_datas check(fim_em is null or fim_em>=inicio_em));
create table if not exists sigov.ativo_veiculo_rota(
 id bigint generated by default as identity primary key,tenant_id bigint not null,entidade_id bigint not null,veiculo_id bigint not null,motorista_pessoa_id bigint,
 origem varchar(300) not null,destino varchar(300) not null,finalidade text not null,saida_em timestamptz not null,retorno_em timestamptz,
 km_saida numeric(18,2) not null,km_retorno numeric(18,2),status varchar(20) not null default 'PLANEJADA',created_at timestamptz not null default now(),created_by bigint,
 constraint ck_ativo_rota_km check(km_saida>=0 and (km_retorno is null or km_retorno>=km_saida)),constraint ck_ativo_rota_datas check(retorno_em is null or retorno_em>=saida_em),constraint ck_ativo_rota_status check(status in('PLANEJADA','EM_ANDAMENTO','CONCLUIDA','CANCELADA')));
create table if not exists sigov.ativo_alerta_operacional(
 id bigint generated by default as identity primary key,tenant_id bigint not null,entidade_id bigint not null,tipo varchar(40) not null,
 contexto_tipo varchar(30) not null,contexto_id bigint not null,severidade varchar(12) not null,mensagem varchar(500) not null,vencimento date,
 status varchar(16) not null default 'ABERTO',resolvido_em timestamptz,created_at timestamptz not null default now(),created_by bigint,
 constraint ck_ativo_alerta_severidade check(severidade in('INFO','ATENCAO','CRITICO')),constraint ck_ativo_alerta_status check(status in('ABERTO','RESOLVIDO','DESCARTADO')));

-- Requisições e inventários usam as tabelas oficiais já publicadas; aliases de integração preservam uma única autoridade.
create or replace view sigov.ativo_requisicao_material as select * from sigov.almoxarifado_requisicao;
create or replace view sigov.ativo_requisicao_material_item as select * from sigov.almoxarifado_requisicao_item;
create or replace view sigov.ativo_inventario_patrimonial as select * from sigov.patrimonio_inventario;
create or replace view sigov.ativo_inventario_patrimonial_item as select * from sigov.patrimonio_inventario_item;

create index if not exists ix_ativo_transf_contexto on sigov.ativo_transferencia_estoque(tenant_id,entidade_id,status,ocorrido_em desc);
create index if not exists ix_ativo_transf_produto on sigov.ativo_transferencia_estoque(tenant_id,material_id,almoxarifado_origem_id,almoxarifado_destino_id);
create index if not exists ix_ativo_mov_bem on sigov.ativo_movimentacao_patrimonial(tenant_id,entidade_id,bem_id,ocorrido_em desc);
create index if not exists ix_ativo_baixa_bem on sigov.ativo_baixa_patrimonial(tenant_id,entidade_id,bem_id,data_baixa desc);
create index if not exists ix_ativo_deprec_bem on sigov.ativo_depreciacao_patrimonial(tenant_id,entidade_id,bem_id,competencia desc);
create index if not exists ix_ativo_doc_vencimento on sigov.ativo_veiculo_documento(tenant_id,entidade_id,status,vencimento);
create index if not exists ix_ativo_doc_veiculo on sigov.ativo_veiculo_documento(tenant_id,veiculo_id,tipo);
create index if not exists ix_ativo_motorista_pessoa on sigov.ativo_veiculo_motorista(tenant_id,entidade_id,pessoa_id,inicio_em desc);
create index if not exists ix_ativo_motorista_veiculo on sigov.ativo_veiculo_motorista(tenant_id,veiculo_id,principal);
create index if not exists ix_ativo_rota_veiculo on sigov.ativo_veiculo_rota(tenant_id,entidade_id,veiculo_id,saida_em desc);
create index if not exists ix_ativo_alerta_status on sigov.ativo_alerta_operacional(tenant_id,entidade_id,status,severidade,vencimento);

-- FKs são acrescentadas somente quando os objetos oficiais estão disponíveis na instalação.
do $$ begin
 if to_regclass('sigov.almoxarifado_local') is not null then
  if not exists(select 1 from pg_constraint where conname='fk_ativo_transf_origem') then alter table sigov.ativo_transferencia_estoque add constraint fk_ativo_transf_origem foreign key(almoxarifado_origem_id) references sigov.almoxarifado_local(id); end if;
  if not exists(select 1 from pg_constraint where conname='fk_ativo_transf_destino') then alter table sigov.ativo_transferencia_estoque add constraint fk_ativo_transf_destino foreign key(almoxarifado_destino_id) references sigov.almoxarifado_local(id); end if;
 end if;
 if to_regclass('sigov.almoxarifado_material') is not null and not exists(select 1 from pg_constraint where conname='fk_ativo_transf_material') then alter table sigov.ativo_transferencia_estoque add constraint fk_ativo_transf_material foreign key(material_id) references sigov.almoxarifado_material(id); end if;
 if to_regclass('sigov.patrimonio_bem') is not null then
  if not exists(select 1 from pg_constraint where conname='fk_ativo_mov_bem') then alter table sigov.ativo_movimentacao_patrimonial add constraint fk_ativo_mov_bem foreign key(bem_id) references sigov.patrimonio_bem(id); end if;
  if not exists(select 1 from pg_constraint where conname='fk_ativo_baixa_bem') then alter table sigov.ativo_baixa_patrimonial add constraint fk_ativo_baixa_bem foreign key(bem_id) references sigov.patrimonio_bem(id); end if;
  if not exists(select 1 from pg_constraint where conname='fk_ativo_deprec_bem') then alter table sigov.ativo_depreciacao_patrimonial add constraint fk_ativo_deprec_bem foreign key(bem_id) references sigov.patrimonio_bem(id); end if;
 end if;
 if to_regclass('sigov.frota_veiculo') is not null then
  if not exists(select 1 from pg_constraint where conname='fk_ativo_doc_veiculo') then alter table sigov.ativo_veiculo_documento add constraint fk_ativo_doc_veiculo foreign key(veiculo_id) references sigov.frota_veiculo(id); end if;
  if not exists(select 1 from pg_constraint where conname='fk_ativo_motorista_veiculo') then alter table sigov.ativo_veiculo_motorista add constraint fk_ativo_motorista_veiculo foreign key(veiculo_id) references sigov.frota_veiculo(id); end if;
  if not exists(select 1 from pg_constraint where conname='fk_ativo_rota_veiculo') then alter table sigov.ativo_veiculo_rota add constraint fk_ativo_rota_veiculo foreign key(veiculo_id) references sigov.frota_veiculo(id); end if;
 end if;
end $$;

insert into sigov.permissao(modulo,chave,recurso,acao,descricao,ativo,is_deleted)
select 'ativos',v.chave,v.recurso,v.acao,v.descricao,true,false from(values
('ATIVOS_DASHBOARD_VIEW','ativos.dashboard','view','Visualizar dashboard Ativos360'),('ATIVOS_ALMOXARIFADO_VIEW','ativos.almoxarifado','view','Visualizar almoxarifado'),('ATIVOS_ALMOXARIFADO_MANAGE','ativos.almoxarifado','manage','Gerenciar almoxarifado'),('ATIVOS_ESTOQUE_MOVIMENTAR','ativos.estoque','movimentar','Movimentar estoque'),('ATIVOS_REQUISICAO_VIEW','ativos.requisicao','view','Visualizar requisições'),('ATIVOS_REQUISICAO_APPROVE','ativos.requisicao','approve','Aprovar requisições'),('ATIVOS_PATRIMONIO_VIEW','ativos.patrimonio','view','Visualizar patrimônio'),('ATIVOS_PATRIMONIO_MANAGE','ativos.patrimonio','manage','Gerenciar patrimônio'),('ATIVOS_PATRIMONIO_TRANSFER','ativos.patrimonio','transfer','Transferir patrimônio'),('ATIVOS_PATRIMONIO_BAIXA','ativos.patrimonio','baixa','Baixar patrimônio'),('ATIVOS_INVENTARIO_MANAGE','ativos.inventario','manage','Gerenciar inventário'),('ATIVOS_FROTA_VIEW','ativos.frota','view','Visualizar frota'),('ATIVOS_FROTA_MANAGE','ativos.frota','manage','Gerenciar frota'),('ATIVOS_FROTA_ABASTECIMENTO','ativos.frota','abastecimento','Registrar abastecimento'),('ATIVOS_FROTA_MANUTENCAO','ativos.frota','manutencao','Gerenciar manutenção'),('ATIVOS_RELATORIO_EXPORT','ativos.relatorio','export','Exportar relatórios'))v(chave,recurso,acao,descricao)
where not exists(select 1 from sigov.permissao p where p.chave=v.chave);
insert into sigov.perfil_permissao(perfil_acesso_id,permissao_id,efeito,ativo,is_deleted)
select pa.id,p.id,'PERMITIR',true,false from sigov.perfil_acesso pa cross join sigov.permissao p where pa.codigo_externo='SUPERADMIN' and pa.sistemico and pa.ativo and not pa.is_deleted and p.modulo='ativos' and p.ativo and not p.is_deleted on conflict(perfil_acesso_id,permissao_id) do update set efeito='PERMITIR',ativo=true,is_deleted=false;
