-- RC50.98: corrige o schema obrigatório do GED Smart Workflow e os metadados da logo.
-- Idempotente e não destrutiva.
CREATE SCHEMA IF NOT EXISTS ged;

CREATE TABLE IF NOT EXISTS ged.smart_workflow_rule (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint NOT NULL,
    entidade_id bigint NOT NULL,
    nome varchar(180) NOT NULL,
    tipo varchar(40) NOT NULL,
    status varchar(24) NOT NULL DEFAULT 'ATIVA',
    prioridade varchar(16) NOT NULL DEFAULT 'NORMAL',
    referencia varchar(180),
    condicao_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    acao_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    esfera_governo varchar(12) NOT NULL,
    tipo_entidade varchar(80) NOT NULL,
    orgao_superior_id bigint, unidade_gestora_id bigint, unidade_executora_id bigint,
    hierarquia_administrativa varchar(300), abrangencia_territorial varchar(80),
    uf char(2), municipio varchar(150), regiao varchar(150), jurisdicao varchar(200),
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz,
    created_by bigint, updated_by bigint,
    CONSTRAINT ck_smart_workflow_rule_status CHECK (status IN ('ATIVA','INATIVA','RASCUNHO')),
    CONSTRAINT ck_smart_workflow_rule_tipo CHECK (tipo IN ('DOCUMENTO','PROCESSO','PRAZO','APROVACAO','DISTRIBUICAO','NOTIFICACAO')),
    CONSTRAINT ck_smart_workflow_rule_prioridade CHECK (prioridade IN ('BAIXA','NORMAL','ALTA','URGENTE')),
    CONSTRAINT ck_smart_workflow_rule_esfera CHECK (esfera_governo IN ('municipal','estadual','federal'))
);

CREATE TABLE IF NOT EXISTS ged.smart_workflow_task (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint NOT NULL, entidade_id bigint NOT NULL,
    rule_id bigint, documento_id bigint, referencia varchar(180),
    titulo varchar(220) NOT NULL, descricao text,
    tipo varchar(40) NOT NULL DEFAULT 'ANALISE', status varchar(24) NOT NULL DEFAULT 'PENDENTE',
    prioridade varchar(16) NOT NULL DEFAULT 'NORMAL', responsavel_id bigint,
    due_at timestamptz, completed_at timestamptz,
    esfera_governo varchar(12) NOT NULL, tipo_entidade varchar(80) NOT NULL,
    orgao_superior_id bigint, unidade_gestora_id bigint, unidade_executora_id bigint,
    hierarquia_administrativa varchar(300), abrangencia_territorial varchar(80),
    uf char(2), municipio varchar(150), regiao varchar(150), jurisdicao varchar(200),
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz,
    created_by bigint, updated_by bigint,
    CONSTRAINT ck_smart_workflow_task_status CHECK (status IN ('PENDENTE','EM_ANDAMENTO','CONCLUIDA','CANCELADA','ATRASADA')),
    CONSTRAINT ck_smart_workflow_task_tipo CHECK (tipo IN ('ANALISE','APROVACAO','ASSINATURA','DISTRIBUICAO','CIENCIA','ARQUIVAMENTO')),
    CONSTRAINT ck_smart_workflow_task_prioridade CHECK (prioridade IN ('BAIXA','NORMAL','ALTA','URGENTE')),
    CONSTRAINT ck_smart_workflow_task_esfera CHECK (esfera_governo IN ('municipal','estadual','federal'))
);

CREATE TABLE IF NOT EXISTS ged.smart_workflow_event (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint NOT NULL, entidade_id bigint NOT NULL,
    task_id bigint, rule_id bigint, referencia varchar(180),
    tipo varchar(40) NOT NULL, status varchar(24) NOT NULL DEFAULT 'REGISTRADO',
    payload jsonb NOT NULL DEFAULT '{}'::jsonb, occurred_at timestamptz NOT NULL DEFAULT now(),
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz,
    created_by bigint, updated_by bigint,
    CONSTRAINT ck_smart_workflow_event_tipo CHECK (tipo IN ('CRIACAO','ATRIBUICAO','TRANSICAO','COMENTARIO','ANEXO','NOTIFICACAO','ERRO')),
    CONSTRAINT ck_smart_workflow_event_status CHECK (status IN ('REGISTRADO','PROCESSADO','IGNORADO','ERRO'))
);

CREATE TABLE IF NOT EXISTS ged.smart_workflow_dashboard_snapshot (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint NOT NULL, entidade_id bigint NOT NULL,
    tipo varchar(40) NOT NULL DEFAULT 'GERAL', status varchar(24) NOT NULL DEFAULT 'ATUAL',
    referencia varchar(180), snapshot_date date NOT NULL DEFAULT CURRENT_DATE,
    metrics jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz,
    created_by bigint, updated_by bigint,
    CONSTRAINT ck_smart_workflow_snapshot_tipo CHECK (tipo IN ('GERAL','UNIDADE','RESPONSAVEL','DOCUMENTO')),
    CONSTRAINT ck_smart_workflow_snapshot_status CHECK (status IN ('ATUAL','HISTORICO','INVALIDADO'))
);

CREATE INDEX IF NOT EXISTS ix_swf_rule_context_status ON ged.smart_workflow_rule(tenant_id, entidade_id, status, tipo);
CREATE INDEX IF NOT EXISTS ix_swf_rule_reference ON ged.smart_workflow_rule(tenant_id, referencia) WHERE referencia IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_swf_task_context_status ON ged.smart_workflow_task(tenant_id, entidade_id, status, prioridade);
CREATE INDEX IF NOT EXISTS ix_swf_task_type_date ON ged.smart_workflow_task(tenant_id, tipo, due_at);
CREATE INDEX IF NOT EXISTS ix_swf_task_reference ON ged.smart_workflow_task(tenant_id, referencia) WHERE referencia IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_swf_event_context_type_date ON ged.smart_workflow_event(tenant_id, entidade_id, tipo, occurred_at DESC);
CREATE INDEX IF NOT EXISTS ix_swf_event_reference ON ged.smart_workflow_event(tenant_id, referencia) WHERE referencia IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_swf_snapshot_context_date ON ged.smart_workflow_dashboard_snapshot(tenant_id, entidade_id, snapshot_date DESC, tipo);

-- FKs são adicionadas somente quando a origem existe, permitindo aplicar a correção em bases parciais.
DO $$ BEGIN
 IF to_regclass('sigov.tenant') IS NOT NULL THEN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_swf_rule_tenant') THEN ALTER TABLE ged.smart_workflow_rule ADD CONSTRAINT fk_swf_rule_tenant FOREIGN KEY(tenant_id) REFERENCES sigov.tenant(id); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_swf_task_tenant') THEN ALTER TABLE ged.smart_workflow_task ADD CONSTRAINT fk_swf_task_tenant FOREIGN KEY(tenant_id) REFERENCES sigov.tenant(id); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_swf_event_tenant') THEN ALTER TABLE ged.smart_workflow_event ADD CONSTRAINT fk_swf_event_tenant FOREIGN KEY(tenant_id) REFERENCES sigov.tenant(id); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_swf_snapshot_tenant') THEN ALTER TABLE ged.smart_workflow_dashboard_snapshot ADD CONSTRAINT fk_swf_snapshot_tenant FOREIGN KEY(tenant_id) REFERENCES sigov.tenant(id); END IF;
 END IF;
 IF to_regclass('sigov.entidade') IS NOT NULL THEN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_swf_rule_entidade') THEN ALTER TABLE ged.smart_workflow_rule ADD CONSTRAINT fk_swf_rule_entidade FOREIGN KEY(entidade_id) REFERENCES sigov.entidade(id); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_swf_task_entidade') THEN ALTER TABLE ged.smart_workflow_task ADD CONSTRAINT fk_swf_task_entidade FOREIGN KEY(entidade_id) REFERENCES sigov.entidade(id); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_swf_event_entidade') THEN ALTER TABLE ged.smart_workflow_event ADD CONSTRAINT fk_swf_event_entidade FOREIGN KEY(entidade_id) REFERENCES sigov.entidade(id); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_swf_snapshot_entidade') THEN ALTER TABLE ged.smart_workflow_dashboard_snapshot ADD CONSTRAINT fk_swf_snapshot_entidade FOREIGN KEY(entidade_id) REFERENCES sigov.entidade(id); END IF;
 END IF;
 IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_swf_task_rule') THEN ALTER TABLE ged.smart_workflow_task ADD CONSTRAINT fk_swf_task_rule FOREIGN KEY(rule_id) REFERENCES ged.smart_workflow_rule(id); END IF;
 IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_swf_event_task') THEN ALTER TABLE ged.smart_workflow_event ADD CONSTRAINT fk_swf_event_task FOREIGN KEY(task_id) REFERENCES ged.smart_workflow_task(id); END IF;
 IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_swf_event_rule') THEN ALTER TABLE ged.smart_workflow_event ADD CONSTRAINT fk_swf_event_rule FOREIGN KEY(rule_id) REFERENCES ged.smart_workflow_rule(id); END IF;
END $$;

ALTER TABLE IF EXISTS sigov.saas_tenant_branding ADD COLUMN IF NOT EXISTS logo_width_px integer NOT NULL DEFAULT 240;
ALTER TABLE IF EXISTS sigov.saas_tenant_branding ADD COLUMN IF NOT EXISTS logo_height_px integer NOT NULL DEFAULT 80;
ALTER TABLE IF EXISTS sigov.saas_tenant_branding ADD COLUMN IF NOT EXISTS logo_fit varchar(12) NOT NULL DEFAULT 'contain';
ALTER TABLE IF EXISTS sigov.saas_tenant_branding ADD COLUMN IF NOT EXISTS logo_original_filename varchar(255);
ALTER TABLE IF EXISTS sigov.saas_tenant_branding ADD COLUMN IF NOT EXISTS logo_content_type varchar(50);
ALTER TABLE IF EXISTS sigov.saas_tenant_branding ADD COLUMN IF NOT EXISTS logo_size_bytes bigint;
ALTER TABLE IF EXISTS sigov.saas_tenant_branding ADD COLUMN IF NOT EXISTS logo_uploaded_at timestamptz;
ALTER TABLE IF EXISTS sigov.saas_tenant_branding ADD COLUMN IF NOT EXISTS created_by bigint;
ALTER TABLE IF EXISTS sigov.saas_tenant_branding ADD COLUMN IF NOT EXISTS updated_by bigint;
DO $$ BEGIN
 IF to_regclass('sigov.saas_tenant_branding') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='ck_saas_branding_logo_dimensions') THEN
  ALTER TABLE sigov.saas_tenant_branding ADD CONSTRAINT ck_saas_branding_logo_dimensions CHECK (logo_width_px BETWEEN 32 AND 1200 AND logo_height_px BETWEEN 16 AND 600);
 END IF;
 IF to_regclass('sigov.saas_tenant_branding') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='ck_saas_branding_logo_fit') THEN
  ALTER TABLE sigov.saas_tenant_branding ADD CONSTRAINT ck_saas_branding_logo_fit CHECK (logo_fit IN ('contain','cover','fill'));
 END IF;
END $$;
