-- FUNC02: Almoxarifado, estoque, requisições e integração segura com Patrimônio.
create table if not exists sigov.almoxarifado_material(
 id bigint generated always as identity primary key,tenant_id bigint not null,entidade_id bigint not null,codigo varchar(60) not null,descricao varchar(300) not null,tipo_material varchar(20) not null,unidade_medida varchar(30) not null,categoria varchar(120),estoque_minimo numeric(18,4) not null default 0,estoque_maximo numeric(18,4),controla_lote boolean not null default false,controla_validade boolean not null default false,ativo boolean not null default true,created_at timestamptz not null default now(),created_by bigint,updated_at timestamptz not null default now(),updated_by bigint,
 constraint ck_almox_material_tipo check(tipo_material in('CONSUMO','PERMANENTE')),constraint ck_almox_material_min check(estoque_minimo>=0),constraint ck_almox_material_max check(estoque_maximo is null or estoque_maximo>=estoque_minimo),constraint ux_almox_material_codigo unique(tenant_id,entidade_id,codigo));
create table if not exists sigov.almoxarifado_local(
 id bigint generated always as identity primary key,tenant_id bigint not null,entidade_id bigint not null,unidade_id bigint,codigo varchar(60) not null,nome varchar(200) not null,responsavel_nome varchar(200),ativo boolean not null default true,created_at timestamptz not null default now(),created_by bigint,updated_at timestamptz not null default now(),updated_by bigint,constraint ux_almox_local_codigo unique(tenant_id,entidade_id,codigo));
create table if not exists sigov.almoxarifado_estoque(
 id bigint generated always as identity primary key,tenant_id bigint not null,entidade_id bigint not null,almoxarifado_id bigint not null,material_id bigint not null,quantidade numeric(18,4) not null default 0,updated_at timestamptz not null default now(),constraint fk_almox_estoque_local foreign key(almoxarifado_id) references sigov.almoxarifado_local(id),constraint fk_almox_estoque_material foreign key(material_id) references sigov.almoxarifado_material(id),constraint ck_almox_estoque_nao_negativo check(quantidade>=0),constraint ux_almox_estoque unique(tenant_id,entidade_id,almoxarifado_id,material_id));
create table if not exists sigov.almoxarifado_requisicao(
 id bigint generated always as identity primary key,tenant_id bigint not null,entidade_id bigint not null,almoxarifado_id bigint not null,unidade_solicitante_id bigint,status varchar(20) not null default 'RASCUNHO',observacao text,justificativa text,created_at timestamptz not null default now(),created_by bigint,updated_at timestamptz not null default now(),updated_by bigint,constraint fk_almox_req_local foreign key(almoxarifado_id) references sigov.almoxarifado_local(id),constraint ck_almox_req_status check(status in('RASCUNHO','ENVIADA','APROVADA','ATENDIDA','CANCELADA','REJEITADA')));
create table if not exists sigov.almoxarifado_requisicao_item(
 id bigint generated always as identity primary key,tenant_id bigint not null,entidade_id bigint not null,requisicao_id bigint not null,material_id bigint not null,quantidade_solicitada numeric(18,4) not null,quantidade_atendida numeric(18,4) not null default 0,constraint fk_almox_req_item_req foreign key(requisicao_id) references sigov.almoxarifado_requisicao(id) on delete cascade,constraint fk_almox_req_item_material foreign key(material_id) references sigov.almoxarifado_material(id),constraint ck_almox_req_item_qtd check(quantidade_solicitada>0 and quantidade_atendida>=0 and quantidade_atendida<=quantidade_solicitada),constraint ux_almox_req_item unique(requisicao_id,material_id));
create table if not exists sigov.almoxarifado_movimentacao(
 id bigint generated always as identity primary key,tenant_id bigint not null,entidade_id bigint not null,almoxarifado_id bigint not null,material_id bigint not null,requisicao_id bigint,tipo varchar(10) not null,motivo varchar(40) not null,quantidade numeric(18,4) not null,valor_unitario numeric(18,4),lote varchar(100),validade date,documento_origem varchar(200),observacao text,saldo_antes numeric(18,4) not null,saldo_depois numeric(18,4) not null,usuario_id bigint,correlation_id varchar(100) not null,ocorrido_em timestamptz not null default now(),constraint fk_almox_mov_local foreign key(almoxarifado_id) references sigov.almoxarifado_local(id),constraint fk_almox_mov_material foreign key(material_id) references sigov.almoxarifado_material(id),constraint fk_almox_mov_req foreign key(requisicao_id) references sigov.almoxarifado_requisicao(id),constraint ck_almox_mov_tipo check(tipo in('ENTRADA','SAIDA')),constraint ck_almox_mov_qtd check(quantidade>0),constraint ck_almox_mov_saldos check(saldo_antes>=0 and saldo_depois>=0),constraint ck_almox_mov_valor check(valor_unitario is null or valor_unitario>=0));
create table if not exists sigov.almoxarifado_requisicao_historico(
 id bigint generated always as identity primary key,tenant_id bigint not null,entidade_id bigint not null,requisicao_id bigint not null,status_anterior varchar(20) not null,status_novo varchar(20) not null,justificativa text,usuario_id bigint,correlation_id varchar(100) not null,ocorrido_em timestamptz not null default now(),constraint fk_almox_req_hist_req foreign key(requisicao_id) references sigov.almoxarifado_requisicao(id),constraint ck_almox_req_hist_novo check(status_novo in('RASCUNHO','ENVIADA','APROVADA','ATENDIDA','CANCELADA','REJEITADA')));
create table if not exists sigov.almoxarifado_pendencia_patrimonial(
 id bigint generated always as identity primary key,tenant_id bigint not null,entidade_id bigint not null,movimentacao_id bigint not null,material_id bigint not null,quantidade numeric(18,4) not null,status varchar(20) not null default 'PENDENTE',patrimonio_bem_id bigint,observacao text,created_at timestamptz not null default now(),resolved_at timestamptz,constraint fk_almox_pend_mov foreign key(movimentacao_id) references sigov.almoxarifado_movimentacao(id),constraint fk_almox_pend_material foreign key(material_id) references sigov.almoxarifado_material(id),constraint ck_almox_pend_qtd check(quantidade>0),constraint ck_almox_pend_status check(status in('PENDENTE','CONCLUIDA','CANCELADA')),constraint ux_almox_pend_mov unique(movimentacao_id));
create table if not exists sigov.almoxarifado_auditoria(
 id bigint generated always as identity primary key,tenant_id bigint not null,entidade_id bigint not null,entidade varchar(80) not null,registro_id bigint not null,operacao varchar(40) not null,antes jsonb,depois jsonb,usuario_id bigint,correlation_id varchar(100) not null,ocorrido_em timestamptz not null default now());
create index if not exists ix_almox_material_tenant_entidade on sigov.almoxarifado_material(tenant_id,entidade_id,ativo);
create index if not exists ix_almox_local_tenant_entidade on sigov.almoxarifado_local(tenant_id,entidade_id,unidade_id,ativo);
create index if not exists ix_almox_estoque_material_local on sigov.almoxarifado_estoque(tenant_id,entidade_id,material_id,almoxarifado_id);
create index if not exists ix_almox_mov_data on sigov.almoxarifado_movimentacao(tenant_id,entidade_id,ocorrido_em desc);
create index if not exists ix_almox_mov_material on sigov.almoxarifado_movimentacao(tenant_id,entidade_id,material_id,ocorrido_em desc);
create index if not exists ix_almox_req_status on sigov.almoxarifado_requisicao(tenant_id,entidade_id,status,created_at desc);
create index if not exists ix_almox_req_item_material on sigov.almoxarifado_requisicao_item(tenant_id,entidade_id,material_id);
create index if not exists ix_almox_req_hist_data on sigov.almoxarifado_requisicao_historico(tenant_id,entidade_id,requisicao_id,ocorrido_em);
create index if not exists ix_almox_pend_status on sigov.almoxarifado_pendencia_patrimonial(tenant_id,entidade_id,status,created_at);
create index if not exists ix_almox_audit_data on sigov.almoxarifado_auditoria(tenant_id,entidade_id,ocorrido_em desc);
insert into sigov.permissao(modulo,chave,recurso,acao,descricao,ativo,is_deleted)
select 'almoxarifado',v.chave,v.recurso,v.acao,v.descricao,true,false from(values
('almoxarifado.dashboard.visualizar','almoxarifado.dashboard','visualizar','Visualizar dashboard do almoxarifado'),('almoxarifado.material.visualizar','almoxarifado.material','visualizar','Visualizar materiais'),('almoxarifado.material.criar','almoxarifado.material','criar','Cadastrar materiais'),('almoxarifado.material.editar','almoxarifado.material','editar','Editar e ativar materiais'),('almoxarifado.estoque.visualizar','almoxarifado.estoque','visualizar','Visualizar saldos'),('almoxarifado.movimentacao.entrada','almoxarifado.movimentacao','entrada','Registrar entradas'),('almoxarifado.movimentacao.saida','almoxarifado.movimentacao','saida','Registrar saídas'),('almoxarifado.requisicao.visualizar','almoxarifado.requisicao','visualizar','Visualizar requisições'),('almoxarifado.requisicao.criar','almoxarifado.requisicao','criar','Criar e enviar requisições'),('almoxarifado.requisicao.aprovar','almoxarifado.requisicao','aprovar','Aprovar e rejeitar requisições'),('almoxarifado.requisicao.atender','almoxarifado.requisicao','atender','Atender requisições'),('almoxarifado.exportar','almoxarifado','exportar','Exportar catálogo, saldos e movimentos'))v(chave,recurso,acao,descricao)
where not exists(select 1 from sigov.permissao p where p.modulo='almoxarifado' and p.chave=v.chave);
insert into sigov.perfil_permissao(perfil_acesso_id,permissao_id,efeito,ativo,is_deleted)
select pa.id,p.id,'PERMITIR',true,false from sigov.perfil_acesso pa cross join sigov.permissao p where pa.codigo_externo='SUPERADMIN' and pa.sistemico and pa.ativo and not pa.is_deleted and p.modulo='almoxarifado' and p.ativo and not p.is_deleted on conflict(perfil_acesso_id,permissao_id) do update set efeito='PERMITIR',ativo=true,is_deleted=false;
