using System.Globalization;
using System.Text;
using Dapper;
using Sigov.Application.Common;
using Sigov.Application.Saneamento;
using Sigov.Infrastructure.Persistence.Dapper;

namespace Sigov.Infrastructure.Saneamento;

public sealed class SaneamentoRepository : ISaneamentoConsumidorRepository, ILigacaoSaneamentoRepository, IUnidadeConsumidoraRepository, IHidrometroRepository, ILeituraConsumoRepository, IFaturaSaneamentoRepository, IArrecadacaoSaneamentoRepository, IParcelamentoSaneamentoRepository, IOrdemServicoSaneamentoRepository, IEquipeCampoSaneamentoRepository, ILaboratorioSaneamentoRepository, IRedeSaneamentoRepository, ISaneamentoDashboardRepository, ISaneamentoExportacaoRepository, ISaneamentoSequencialService
{
    private readonly DapperContext _context;
    public SaneamentoRepository(DapperContext context) => _context = context;
    private static int Offset(int page,int size)=>(Math.Max(1,page)-1)*Math.Clamp(size,1,100);
    private static int Limit(int size)=>Math.Clamp(size,1,100);
    private static string Like(string? termo)=>$"%{(termo??string.Empty).Trim()}%";

    public async Task<string> ProximoAsync(long tenantId,long entidadeId,string prefixo,CancellationToken ct)
    {
        var ano=DateTimeOffset.UtcNow.Year.ToString(CultureInfo.InvariantCulture);
        var table=prefixo switch { "CON"=>"saneamento_consumidor", "LIG"=>"saneamento_ligacao", "UC"=>"saneamento_unidade_consumidora", "FAT"=>"saneamento_fatura", "ARR-SAN"=>"saneamento_arrecadacao", "PARC-SAN"=>"saneamento_parcelamento", "OS-SAN"=>"saneamento_ordem_servico", "AMO"=>"saneamento_laboratorio_amostra", "RED"=>"saneamento_rede_trecho", "EQ-SAN"=>"saneamento_equipe_campo", _=>"saneamento_evento" };
        var column=prefixo switch { "CON"=>"codigo_consumidor", "LIG"=>"numero_ligacao", "UC"=>"codigo_unidade", "FAT" or "ARR-SAN" or "PARC-SAN" or "OS-SAN" or "AMO"=>"numero", "RED" or "EQ-SAN"=>"codigo", _=>"tipo_evento" };
        var sql=$"select count(*) + 1 from sigov.{table} where tenant_id=@TenantId and entidade_id=@EntidadeId and {column} like @Pattern;";
        using var cn=_context.CreateConnection();
        var n=await cn.ExecuteScalarAsync<long>(new CommandDefinition(sql,new{TenantId=tenantId,EntidadeId=entidadeId,Pattern=$"{prefixo}-{ano}-%"},cancellationToken:ct)).ConfigureAwait(false);
        return $"{prefixo}-{ano}-{n:000000}";
    }

    async Task<PagedResult<SaneamentoConsumidorResponse>> ISaneamentoConsumidorRepository.ListarAsync(long tenantId,long entidadeId,SaneamentoConsumidorFiltro f,CancellationToken ct){const string where="tenant_id=@TenantId and entidade_id=@EntidadeId and is_deleted=false and (@Situacao is null or situacao=@Situacao) and (@Termo='' or codigo_consumidor ilike @Like)"; using var cn=_context.CreateConnection(); var total=await cn.ExecuteScalarAsync<long>(new CommandDefinition($"select count(*) from sigov.saneamento_consumidor where {where}",new{TenantId=tenantId,EntidadeId=entidadeId,f.Situacao,Termo=f.Termo??"",Like=Like(f.Termo)},cancellationToken:ct)); var rows=await cn.QueryAsync<SaneamentoConsumidorResponse>(new CommandDefinition($"select c.id as Id,c.pessoa_id as PessoaId,c.codigo_consumidor as CodigoConsumidor,c.tipo_consumidor as TipoConsumidor,c.situacao as Situacao, left(coalesce(p.nome_social,p.nome,''),3)||'***' as NomePessoa from sigov.saneamento_consumidor c left join sigov.pessoa p on p.id=c.pessoa_id and p.tenant_id=c.tenant_id where c.tenant_id=@TenantId and c.entidade_id=@EntidadeId and c.is_deleted=false and (@Situacao is null or c.situacao=@Situacao) and (@Termo='' or c.codigo_consumidor ilike @Like) order by c.id desc limit @Limit offset @Offset",new{TenantId=tenantId,EntidadeId=entidadeId,f.Situacao,Termo=f.Termo??"",Like=Like(f.Termo),Limit=Limit(f.PageSize),Offset=Offset(f.Page,f.PageSize)},cancellationToken:ct)); return new(rows.AsList(),f.Page,f.PageSize,total);}
    async Task<SaneamentoConsumidorResponse?> ISaneamentoConsumidorRepository.ObterAsync(long tenantId,long entidadeId,long id,bool completo,CancellationToken ct){using var cn=_context.CreateConnection(); var nome=completo?"coalesce(p.nome_social,p.nome,'')":"left(coalesce(p.nome_social,p.nome,''),3)||'***'"; return await cn.QuerySingleOrDefaultAsync<SaneamentoConsumidorResponse>(new CommandDefinition($"select c.id as Id,c.pessoa_id as PessoaId,c.codigo_consumidor as CodigoConsumidor,c.tipo_consumidor as TipoConsumidor,c.situacao as Situacao,{nome} as NomePessoa from sigov.saneamento_consumidor c left join sigov.pessoa p on p.id=c.pessoa_id and p.tenant_id=c.tenant_id where c.tenant_id=@TenantId and c.entidade_id=@EntidadeId and c.id=@Id and c.is_deleted=false",new{TenantId=tenantId,EntidadeId=entidadeId,Id=id},cancellationToken:ct));}
    async Task<long> ISaneamentoConsumidorRepository.CriarAsync(long tenantId,long entidadeId,long? usuarioId,SaneamentoConsumidorCreateRequest r,string codigo,CancellationToken ct){const string sql="insert into sigov.saneamento_consumidor(tenant_id,entidade_id,pessoa_id,codigo_consumidor,tipo_consumidor,situacao,observacao,created_by) values(@TenantId,@EntidadeId,@PessoaId,@Codigo,@Tipo,@Situacao,@Observacao,@UsuarioId) returning id"; using var cn=_context.CreateConnection(); return await cn.ExecuteScalarAsync<long>(new CommandDefinition(sql,new{TenantId=tenantId,EntidadeId=entidadeId,r.PessoaId,Codigo=codigo,Tipo=r.TipoConsumidor,Situacao=r.Situacao,r.Observacao,UsuarioId=usuarioId},cancellationToken:ct));}
    async Task ISaneamentoConsumidorRepository.AtualizarAsync(long tenantId,long entidadeId,long id,long? usuarioId,SaneamentoConsumidorUpdateRequest r,CancellationToken ct){const string sql="update sigov.saneamento_consumidor set codigo_consumidor=@CodigoConsumidor,tipo_consumidor=@TipoConsumidor,situacao=@Situacao,observacao=@Observacao,updated_by=@UsuarioId,updated_at=now() where tenant_id=@TenantId and entidade_id=@EntidadeId and id=@Id and is_deleted=false"; using var cn=_context.CreateConnection(); await cn.ExecuteAsync(new CommandDefinition(sql,new{TenantId=tenantId,EntidadeId=entidadeId,Id=id,UsuarioId=usuarioId,r.CodigoConsumidor,r.TipoConsumidor,r.Situacao,r.Observacao},cancellationToken:ct));}
    async Task ISaneamentoConsumidorRepository.ExcluirAsync(long tenantId,long entidadeId,long id,long? usuarioId,CancellationToken ct)=>await Soft("saneamento_consumidor",tenantId,entidadeId,id,usuarioId,ct);
    private async Task Soft(string table,long tenantId,long entidadeId,long id,long? usuarioId,CancellationToken ct){using var cn=_context.CreateConnection(); await cn.ExecuteAsync(new CommandDefinition($"update sigov.{table} set is_deleted=true,ativo=false,deleted_at=now(),deleted_by=@UsuarioId where tenant_id=@TenantId and entidade_id=@EntidadeId and id=@Id and is_deleted=false",new{TenantId=tenantId,EntidadeId=entidadeId,Id=id,UsuarioId=usuarioId},cancellationToken:ct));}

    async Task<PagedResult<LigacaoSaneamentoResponse>> ILigacaoSaneamentoRepository.ListarAsync(long t,long e,SaneamentoFiltro f,CancellationToken ct){using var cn=_context.CreateConnection(); const string w="tenant_id=@TenantId and entidade_id=@EntidadeId and is_deleted=false and (@Status is null or situacao=@Status)"; var p=new{TenantId=t,EntidadeId=e,f.Status,Limit=Limit(f.PageSize),Offset=Offset(f.Page,f.PageSize)}; var total=await cn.ExecuteScalarAsync<long>(new CommandDefinition($"select count(*) from sigov.saneamento_ligacao where {w}",p,cancellationToken:ct)); var rows=await cn.QueryAsync<LigacaoSaneamentoResponse>(new CommandDefinition($"select id as Id,consumidor_id as ConsumidorId,numero_ligacao as NumeroLigacao,tipo_ligacao as TipoLigacao,situacao as Situacao,categoria as Categoria,economia as Economia from sigov.saneamento_ligacao where {w} order by id desc limit @Limit offset @Offset",p,cancellationToken:ct)); return new(rows.AsList(),f.Page,f.PageSize,total);}
    async Task<LigacaoSaneamentoResponse?> ILigacaoSaneamentoRepository.ObterAsync(long t,long e,long id,CancellationToken ct){using var cn=_context.CreateConnection(); return await cn.QuerySingleOrDefaultAsync<LigacaoSaneamentoResponse>(new CommandDefinition("select id as Id,consumidor_id as ConsumidorId,numero_ligacao as NumeroLigacao,tipo_ligacao as TipoLigacao,situacao as Situacao,categoria as Categoria,economia as Economia from sigov.saneamento_ligacao where tenant_id=@TenantId and entidade_id=@EntidadeId and id=@Id and is_deleted=false",new{TenantId=t,EntidadeId=e,Id=id},cancellationToken:ct));}
    async Task<long> ILigacaoSaneamentoRepository.CriarAsync(long t,long e,long? u,LigacaoSaneamentoCreateRequest r,string numero,CancellationToken ct){using var cn=_context.CreateConnection(); var situacaoConsumidor = await cn.ExecuteScalarAsync<string>(new CommandDefinition("select situacao from sigov.saneamento_consumidor where tenant_id=@TenantId and entidade_id=@EntidadeId and id=@ConsumidorId and is_deleted=false",new{TenantId=t,EntidadeId=e,r.ConsumidorId},cancellationToken:ct)).ConfigureAwait(false); if(string.IsNullOrWhiteSpace(situacaoConsumidor) || !situacaoConsumidor.Equals("ATIVO", StringComparison.OrdinalIgnoreCase)) throw new InvalidOperationException("Cliente inativo não pode receber nova ligação."); return await cn.ExecuteScalarAsync<long>(new CommandDefinition("insert into sigov.saneamento_ligacao(tenant_id,entidade_id,consumidor_id,numero_ligacao,tipo_ligacao,situacao,data_ligacao,categoria,economia,observacao,created_by) values(@TenantId,@EntidadeId,@ConsumidorId,@Numero,@Tipo,@Situacao,@DataLigacao,@Categoria,@Economia,@Observacao,@UsuarioId) returning id",new{TenantId=t,EntidadeId=e,r.ConsumidorId,Numero=numero,Tipo=r.TipoLigacao,r.Situacao,r.DataLigacao,r.Categoria,r.Economia,r.Observacao,UsuarioId=u},cancellationToken:ct));}
    async Task ILigacaoSaneamentoRepository.AtualizarAsync(long t,long e,long id,long? u,LigacaoSaneamentoUpdateRequest r,CancellationToken ct){using var cn=_context.CreateConnection(); await cn.ExecuteAsync(new CommandDefinition("update sigov.saneamento_ligacao set numero_ligacao=@NumeroLigacao,tipo_ligacao=@TipoLigacao,situacao=@Situacao,categoria=@Categoria,economia=@Economia,data_ligacao=@DataLigacao,data_corte=@DataCorte,observacao=@Observacao,updated_by=@UsuarioId,updated_at=now() where tenant_id=@TenantId and entidade_id=@EntidadeId and id=@Id and is_deleted=false",new{TenantId=t,EntidadeId=e,Id=id,UsuarioId=u,r.NumeroLigacao,r.TipoLigacao,r.Situacao,r.Categoria,r.Economia,r.DataLigacao,r.DataCorte,r.Observacao},cancellationToken:ct));}
    async Task ILigacaoSaneamentoRepository.ExcluirAsync(long t,long e,long id,long? u,CancellationToken ct)=>await Soft("saneamento_ligacao",t,e,id,u,ct);

    async Task<PagedResult<UnidadeConsumidoraResponse>> IUnidadeConsumidoraRepository.ListarAsync(long t,long e,UnidadeConsumidoraFiltro f,CancellationToken ct){using var cn=_context.CreateConnection(); const string w="tenant_id=@TenantId and entidade_id=@EntidadeId and is_deleted=false and (@Situacao is null or situacao=@Situacao) and (@Rota is null or rota=@Rota)"; var p=new{TenantId=t,EntidadeId=e,f.Situacao,f.Rota,Limit=Limit(f.PageSize),Offset=Offset(f.Page,f.PageSize)}; var total=await cn.ExecuteScalarAsync<long>(new CommandDefinition($"select count(*) from sigov.saneamento_unidade_consumidora where {w}",p,cancellationToken:ct)); var rows=await cn.QueryAsync<UnidadeConsumidoraResponse>(new CommandDefinition($"select id as Id,consumidor_id as ConsumidorId,ligacao_id as LigacaoId,codigo_unidade as CodigoUnidade,bairro as Bairro,rota as Rota,sequencia_rota as SequenciaRota,latitude as Latitude,longitude as Longitude,situacao as Situacao from sigov.saneamento_unidade_consumidora where {w} order by id desc limit @Limit offset @Offset",p,cancellationToken:ct)); return new(rows.AsList(),f.Page,f.PageSize,total);}
    async Task<UnidadeConsumidoraResponse?> IUnidadeConsumidoraRepository.ObterAsync(long t,long e,long id,CancellationToken ct){using var cn=_context.CreateConnection(); return await cn.QuerySingleOrDefaultAsync<UnidadeConsumidoraResponse>(new CommandDefinition("select id as Id,consumidor_id as ConsumidorId,ligacao_id as LigacaoId,codigo_unidade as CodigoUnidade,bairro as Bairro,rota as Rota,sequencia_rota as SequenciaRota,latitude as Latitude,longitude as Longitude,situacao as Situacao from sigov.saneamento_unidade_consumidora where tenant_id=@TenantId and entidade_id=@EntidadeId and id=@Id and is_deleted=false",new{TenantId=t,EntidadeId=e,Id=id},cancellationToken:ct));}
    async Task<long> IUnidadeConsumidoraRepository.CriarAsync(long t,long e,long? u,UnidadeConsumidoraCreateRequest r,string codigo,CancellationToken ct){using var cn=_context.CreateConnection(); return await cn.ExecuteScalarAsync<long>(new CommandDefinition("insert into sigov.saneamento_unidade_consumidora(tenant_id,entidade_id,consumidor_id,ligacao_id,codigo_unidade,endereco_json,bairro,setor,rota,sequencia_rota,latitude,longitude,situacao,created_by) values(@TenantId,@EntidadeId,@ConsumidorId,@LigacaoId,@Codigo,cast(@EnderecoJson as jsonb),@Bairro,@Setor,@Rota,@SequenciaRota,@Latitude,@Longitude,@Situacao,@UsuarioId) returning id",new{TenantId=t,EntidadeId=e,r.ConsumidorId,r.LigacaoId,Codigo=codigo,r.EnderecoJson,r.Bairro,r.Setor,r.Rota,r.SequenciaRota,r.Latitude,r.Longitude,r.Situacao,UsuarioId=u},cancellationToken:ct));}
    async Task IUnidadeConsumidoraRepository.AtualizarAsync(long t,long e,long id,long? u,UnidadeConsumidoraUpdateRequest r,CancellationToken ct){using var cn=_context.CreateConnection(); await cn.ExecuteAsync(new CommandDefinition("update sigov.saneamento_unidade_consumidora set ligacao_id=@LigacaoId,codigo_unidade=@CodigoUnidade,endereco_json=cast(@EnderecoJson as jsonb),bairro=@Bairro,setor=@Setor,rota=@Rota,sequencia_rota=@SequenciaRota,latitude=@Latitude,longitude=@Longitude,situacao=@Situacao,updated_by=@UsuarioId,updated_at=now() where tenant_id=@TenantId and entidade_id=@EntidadeId and id=@Id and is_deleted=false",new{TenantId=t,EntidadeId=e,Id=id,UsuarioId=u,r.LigacaoId,r.CodigoUnidade,r.EnderecoJson,r.Bairro,r.Setor,r.Rota,r.SequenciaRota,r.Latitude,r.Longitude,r.Situacao},cancellationToken:ct));}
    async Task IUnidadeConsumidoraRepository.ExcluirAsync(long t,long e,long id,long? u,CancellationToken ct)=>await Soft("saneamento_unidade_consumidora",t,e,id,u,ct);

    async Task<PagedResult<HidrometroResponse>> IHidrometroRepository.ListarAsync(long t,long e,SaneamentoFiltro f,CancellationToken ct){using var cn=_context.CreateConnection(); const string w="tenant_id=@TenantId and entidade_id=@EntidadeId and is_deleted=false and (@UnidadeConsumidoraId is null or unidade_consumidora_id=@UnidadeConsumidoraId)"; var p=new{TenantId=t,EntidadeId=e,f.UnidadeConsumidoraId,Limit=Limit(f.PageSize),Offset=Offset(f.Page,f.PageSize)}; var total=await cn.ExecuteScalarAsync<long>(new CommandDefinition($"select count(*) from sigov.saneamento_hidrometro where {w}",p,cancellationToken:ct)); var rows=await cn.QueryAsync<HidrometroResponse>(new CommandDefinition($"select id as Id,unidade_consumidora_id as UnidadeConsumidoraId,numero_serie as NumeroSerie,marca as Marca,modelo as Modelo,situacao as Situacao from sigov.saneamento_hidrometro where {w} order by id desc limit @Limit offset @Offset",p,cancellationToken:ct)); return new(rows.AsList(),f.Page,f.PageSize,total);}
    async Task<long> IHidrometroRepository.CriarAsync(long t,long e,long? u,HidrometroCreateRequest r,CancellationToken ct){using var cn=_context.CreateConnection(); if(string.Equals(r.Situacao, "INSTALADO", StringComparison.OrdinalIgnoreCase)){ var jaInstalado = await cn.ExecuteScalarAsync<int>(new CommandDefinition("select count(*) from sigov.saneamento_hidrometro where tenant_id=@TenantId and entidade_id=@EntidadeId and unidade_consumidora_id=@UnidadeConsumidoraId and situacao='INSTALADO' and is_deleted=false", new { TenantId = t, EntidadeId = e, r.UnidadeConsumidoraId }, cancellationToken: ct)).ConfigureAwait(false); if(jaInstalado > 0) throw new InvalidOperationException("Já existe hidrômetro INSTALADO nesta ligação."); } return await cn.ExecuteScalarAsync<long>(new CommandDefinition("insert into sigov.saneamento_hidrometro(tenant_id,entidade_id,unidade_consumidora_id,numero_serie,marca,modelo,diametro,data_instalacao,leitura_instalacao,situacao,created_by) values(@TenantId,@EntidadeId,@UnidadeConsumidoraId,@NumeroSerie,@Marca,@Modelo,@Diametro,@DataInstalacao,@LeituraInstalacao,@Situacao,@UsuarioId) returning id",new{TenantId=t,EntidadeId=e,r.UnidadeConsumidoraId,r.NumeroSerie,r.Marca,r.Modelo,r.Diametro,r.DataInstalacao,r.LeituraInstalacao,r.Situacao,UsuarioId=u},cancellationToken:ct));}
    async Task<long> IHidrometroRepository.SubstituirAsync(long t,long e,long? u,long hidrometroAtualId,HidrometroCreateRequest r,CancellationToken ct){using var cn=_context.CreateConnection(); cn.Open(); using var tx=cn.BeginTransaction(); await cn.ExecuteAsync(new CommandDefinition("update sigov.saneamento_hidrometro set situacao='SUBSTITUIDO',data_retirada=current_date,updated_at=now(),updated_by=@UsuarioId where tenant_id=@TenantId and entidade_id=@EntidadeId and id=@Id and is_deleted=false",new{TenantId=t,EntidadeId=e,Id=hidrometroAtualId,UsuarioId=u},transaction:tx,cancellationToken:ct)).ConfigureAwait(false); var novoId = await cn.ExecuteScalarAsync<long>(new CommandDefinition("insert into sigov.saneamento_hidrometro(tenant_id,entidade_id,unidade_consumidora_id,numero_serie,marca,modelo,diametro,data_instalacao,leitura_instalacao,situacao,created_by) values(@TenantId,@EntidadeId,@UnidadeConsumidoraId,@NumeroSerie,@Marca,@Modelo,@Diametro,@DataInstalacao,@LeituraInstalacao,'INSTALADO',@UsuarioId) returning id",new{TenantId=t,EntidadeId=e,r.UnidadeConsumidoraId,r.NumeroSerie,r.Marca,r.Modelo,r.Diametro,r.DataInstalacao,r.LeituraInstalacao,UsuarioId=u},transaction:tx,cancellationToken:ct)).ConfigureAwait(false); tx.Commit(); return novoId;}
    async Task IHidrometroRepository.AtualizarAsync(long t,long e,long id,long? u,HidrometroUpdateRequest r,CancellationToken ct){using var cn=_context.CreateConnection(); if(string.Equals(r.Situacao, "INSTALADO", StringComparison.OrdinalIgnoreCase)){ var jaInstalado = await cn.ExecuteScalarAsync<int>(new CommandDefinition("select count(*) from sigov.saneamento_hidrometro where tenant_id=@TenantId and entidade_id=@EntidadeId and id <> @Id and unidade_consumidora_id=(select unidade_consumidora_id from sigov.saneamento_hidrometro where id=@Id and tenant_id=@TenantId and entidade_id=@EntidadeId) and situacao='INSTALADO' and is_deleted=false", new { TenantId = t, EntidadeId = e, Id = id }, cancellationToken: ct)).ConfigureAwait(false); if(jaInstalado > 0) throw new InvalidOperationException("Já existe hidrômetro INSTALADO nesta ligação."); } await cn.ExecuteAsync(new CommandDefinition("update sigov.saneamento_hidrometro set numero_serie=@NumeroSerie,marca=@Marca,modelo=@Modelo,diametro=@Diametro,data_instalacao=@DataInstalacao,data_retirada=@DataRetirada,leitura_instalacao=@LeituraInstalacao,situacao=@Situacao,updated_by=@UsuarioId,updated_at=now() where tenant_id=@TenantId and entidade_id=@EntidadeId and id=@Id and is_deleted=false",new{TenantId=t,EntidadeId=e,Id=id,UsuarioId=u,r.NumeroSerie,r.Marca,r.Modelo,r.Diametro,r.DataInstalacao,r.DataRetirada,r.LeituraInstalacao,r.Situacao},cancellationToken:ct));}
    async Task IHidrometroRepository.ExcluirAsync(long t,long e,long id,long? u,CancellationToken ct)=>await Soft("saneamento_hidrometro",t,e,id,u,ct);

    async Task<PagedResult<LeituraConsumoResponse>> ILeituraConsumoRepository.ListarAsync(long t,long e,LeituraConsumoFiltro f,CancellationToken ct){using var cn=_context.CreateConnection(); const string w="tenant_id=@TenantId and entidade_id=@EntidadeId and is_deleted=false and (@UnidadeConsumidoraId is null or unidade_consumidora_id=@UnidadeConsumidoraId) and (@Competencia is null or competencia=@Competencia)"; var p=new{TenantId=t,EntidadeId=e,f.UnidadeConsumidoraId,f.Competencia,Limit=Limit(f.PageSize),Offset=Offset(f.Page,f.PageSize)}; var total=await cn.ExecuteScalarAsync<long>(new CommandDefinition($"select count(*) from sigov.saneamento_leitura where {w}",p,cancellationToken:ct)); var rows=await cn.QueryAsync<LeituraConsumoResponse>(new CommandDefinition($"select id as Id,unidade_consumidora_id as UnidadeConsumidoraId,hidrometro_id as HidrometroId,competencia as Competencia,data_leitura as DataLeitura,leitura_anterior as LeituraAnterior,leitura_atual as LeituraAtual,consumo_medido as ConsumoMedido,consumo_faturado as ConsumoFaturado,tipo_leitura as TipoLeitura from sigov.saneamento_leitura where {w} order by data_leitura desc,id desc limit @Limit offset @Offset",p,cancellationToken:ct)); return new(rows.AsList(),f.Page,f.PageSize,total);}
    async Task<LeituraConsumoResponse?> ILeituraConsumoRepository.ObterAsync(long t,long e,long id,CancellationToken ct){using var cn=_context.CreateConnection(); return await cn.QuerySingleOrDefaultAsync<LeituraConsumoResponse>(new CommandDefinition("select id as Id,unidade_consumidora_id as UnidadeConsumidoraId,hidrometro_id as HidrometroId,competencia as Competencia,data_leitura as DataLeitura,leitura_anterior as LeituraAnterior,leitura_atual as LeituraAtual,consumo_medido as ConsumoMedido,consumo_faturado as ConsumoFaturado,tipo_leitura as TipoLeitura from sigov.saneamento_leitura where tenant_id=@TenantId and entidade_id=@EntidadeId and id=@Id and is_deleted=false",new{TenantId=t,EntidadeId=e,Id=id},cancellationToken:ct));}
    async Task<long> ILeituraConsumoRepository.CriarAsync(long t,long e,long? ex,long? u,LeituraConsumoCreateRequest r,decimal medido,decimal faturado,CancellationToken ct){using var cn=_context.CreateConnection(); var hidrometroInstalado = await cn.ExecuteScalarAsync<long?>(new CommandDefinition("select id from sigov.saneamento_hidrometro where tenant_id=@TenantId and entidade_id=@EntidadeId and unidade_consumidora_id=@UnidadeConsumidoraId and situacao='INSTALADO' and is_deleted=false limit 1", new { TenantId = t, EntidadeId = e, r.UnidadeConsumidoraId }, cancellationToken: ct)).ConfigureAwait(false); if(!hidrometroInstalado.HasValue) throw new InvalidOperationException("A unidade consumidora não possui hidrômetro INSTALADO para leitura."); if(r.LeituraAtual < r.LeituraAnterior && string.IsNullOrWhiteSpace(r.Ocorrencia)) throw new InvalidOperationException("Leitura menor que a anterior. Confira a troca do hidrômetro."); var jaLeu = await cn.ExecuteScalarAsync<int>(new CommandDefinition("select count(*) from sigov.saneamento_leitura where tenant_id=@TenantId and entidade_id=@EntidadeId and unidade_consumidora_id=@UnidadeConsumidoraId and competencia=@Competencia and is_deleted=false", new { TenantId = t, EntidadeId = e, r.UnidadeConsumidoraId, r.Competencia }, cancellationToken: ct)).ConfigureAwait(false); if(jaLeu > 0) throw new InvalidOperationException("Já existe leitura registrada para esta competência."); var hidrometroId = r.HidrometroId ?? hidrometroInstalado; return await cn.ExecuteScalarAsync<long>(new CommandDefinition("insert into sigov.saneamento_leitura(tenant_id,entidade_id,exercicio_id,unidade_consumidora_id,hidrometro_id,competencia,data_leitura,leitura_anterior,leitura_atual,consumo_medido,consumo_faturado,tipo_leitura,ocorrencia,latitude,longitude,observacao,created_by) values(@TenantId,@EntidadeId,@ExercicioId,@UnidadeConsumidoraId,@HidrometroId,@Competencia,@DataLeitura,@LeituraAnterior,@LeituraAtual,@Medido,@Faturado,@TipoLeitura,@Ocorrencia,@Latitude,@Longitude,@Observacao,@UsuarioId) returning id",new{TenantId=t,EntidadeId=e,ExercicioId=ex,r.UnidadeConsumidoraId,HidrometroId=hidrometroId,r.Competencia,r.DataLeitura,r.LeituraAnterior,r.LeituraAtual,Medido=medido,Faturado=faturado,r.TipoLeitura,r.Ocorrencia,r.Latitude,r.Longitude,r.Observacao,UsuarioId=u},cancellationToken:ct));}

    async Task<PagedResult<FaturaSaneamentoResponse>> IFaturaSaneamentoRepository.ListarAsync(long t,long e,FaturaSaneamentoFiltro f,CancellationToken ct){using var cn=_context.CreateConnection(); const string w="tenant_id=@TenantId and entidade_id=@EntidadeId and is_deleted=false and (@Status is null or status=@Status) and (@UnidadeConsumidoraId is null or unidade_consumidora_id=@UnidadeConsumidoraId) and (@Competencia is null or competencia=@Competencia)"; var p=new{TenantId=t,EntidadeId=e,f.Status,f.UnidadeConsumidoraId,f.Competencia,Limit=Limit(f.PageSize),Offset=Offset(f.Page,f.PageSize)}; var total=await cn.ExecuteScalarAsync<long>(new CommandDefinition($"select count(*) from sigov.saneamento_fatura where {w}",p,cancellationToken:ct)); var rows=await cn.QueryAsync<FaturaSaneamentoResponse>(new CommandDefinition($"select id as Id,unidade_consumidora_id as UnidadeConsumidoraId,leitura_id as LeituraId,numero as Numero,competencia as Competencia,data_vencimento as DataVencimento,valor_total as ValorTotal,valor_pago as ValorPago,status as Status from sigov.saneamento_fatura where {w} order by id desc limit @Limit offset @Offset",p,cancellationToken:ct)); return new(rows.AsList(),f.Page,f.PageSize,total);}
    async Task<FaturaSaneamentoResponse?> IFaturaSaneamentoRepository.ObterAsync(long t,long e,long id,CancellationToken ct){using var cn=_context.CreateConnection(); return await cn.QuerySingleOrDefaultAsync<FaturaSaneamentoResponse>(new CommandDefinition("select id as Id,unidade_consumidora_id as UnidadeConsumidoraId,leitura_id as LeituraId,numero as Numero,competencia as Competencia,data_vencimento as DataVencimento,valor_total as ValorTotal,valor_pago as ValorPago,status as Status from sigov.saneamento_fatura where tenant_id=@TenantId and entidade_id=@EntidadeId and id=@Id and is_deleted=false",new{TenantId=t,EntidadeId=e,Id=id},cancellationToken:ct));}
    async Task<long> IFaturaSaneamentoRepository.CriarAsync(long t,long e,long? ex,long? u,FaturaSaneamentoCreateRequest r,string numero,decimal total,string ambiente,CancellationToken ct){using var cn=_context.CreateConnection(); var tarifasAtivas = await cn.ExecuteScalarAsync<int>(new CommandDefinition("select count(*) from sigov.saneamento_tarifa where tenant_id=@TenantId and (entidade_id=@EntidadeId or entidade_id is null) and status='ATIVO' and is_deleted=false", new { TenantId = t, EntidadeId = e }, cancellationToken: ct)).ConfigureAwait(false); if(tarifasAtivas == 0) throw new InvalidOperationException("Não há parâmetro tarifário para esta competência."); var clienteAtivo = await cn.ExecuteScalarAsync<int>(new CommandDefinition("select count(*) from sigov.saneamento_unidade_consumidora uc inner join sigov.saneamento_consumidor c on c.id=uc.consumidor_id and c.tenant_id=uc.tenant_id and c.entidade_id=uc.entidade_id where uc.tenant_id=@TenantId and uc.entidade_id=@EntidadeId and uc.id=@UnidadeConsumidoraId and c.situacao='ATIVO' and c.is_deleted=false and uc.is_deleted=false", new { TenantId = t, EntidadeId = e, r.UnidadeConsumidoraId }, cancellationToken: ct)).ConfigureAwait(false); if(clienteAtivo == 0) throw new InvalidOperationException("Cliente inativo não pode receber nova fatura."); return await cn.ExecuteScalarAsync<long>(new CommandDefinition("insert into sigov.saneamento_fatura(tenant_id,entidade_id,exercicio_id,unidade_consumidora_id,leitura_id,numero,competencia,data_vencimento,valor_agua,valor_esgoto,valor_servicos,valor_multa,valor_juros,valor_desconto,valor_total,status,codigo_barras,linha_digitavel,ambiente,created_by) values(@TenantId,@EntidadeId,@ExercicioId,@UnidadeConsumidoraId,@LeituraId,@Numero,@Competencia,@DataVencimento,@ValorAgua,@ValorEsgoto,@ValorServicos,@ValorMulta,@ValorJuros,@ValorDesconto,@Total,'ABERTA',null,null,@Ambiente,@UsuarioId) returning id",new{TenantId=t,EntidadeId=e,ExercicioId=ex,r.UnidadeConsumidoraId,r.LeituraId,Numero=numero,r.Competencia,r.DataVencimento,r.ValorAgua,r.ValorEsgoto,r.ValorServicos,r.ValorMulta,r.ValorJuros,r.ValorDesconto,Total=total,Ambiente=ambiente,UsuarioId=u},cancellationToken:ct));}
    async Task<long> IFaturaSaneamentoRepository.GerarPorLeituraAsync(long t,long e,long? ex,long leituraId,long? u,GerarFaturaPorLeituraRequest r,string numero,string ambiente,CancellationToken ct){using var cn=_context.CreateConnection(); var tarifasAtivas = await cn.ExecuteScalarAsync<int>(new CommandDefinition("select count(*) from sigov.saneamento_tarifa where tenant_id=@TenantId and (entidade_id=@EntidadeId or entidade_id is null) and status='ATIVO' and is_deleted=false", new { TenantId = t, EntidadeId = e }, cancellationToken: ct)).ConfigureAwait(false); if(tarifasAtivas == 0) throw new InvalidOperationException("Não há parâmetro tarifário para esta competência."); var ucId = await cn.ExecuteScalarAsync<long?>(new CommandDefinition("select unidade_consumidora_id from sigov.saneamento_leitura where tenant_id=@TenantId and entidade_id=@EntidadeId and id=@LeituraId and is_deleted=false", new { TenantId = t, EntidadeId = e, LeituraId = leituraId }, cancellationToken: ct)).ConfigureAwait(false); if(!ucId.HasValue) throw new InvalidOperationException("Leitura não encontrada para faturamento."); var clienteAtivoLeitura = await cn.ExecuteScalarAsync<int>(new CommandDefinition("select count(*) from sigov.saneamento_unidade_consumidora uc inner join sigov.saneamento_consumidor c on c.id=uc.consumidor_id and c.tenant_id=uc.tenant_id and c.entidade_id=uc.entidade_id where uc.tenant_id=@TenantId and uc.entidade_id=@EntidadeId and uc.id=@UcId and c.situacao='ATIVO' and c.is_deleted=false and uc.is_deleted=false", new { TenantId = t, EntidadeId = e, UcId = ucId.Value }, cancellationToken: ct)).ConfigureAwait(false); if(clienteAtivoLeitura == 0) throw new InvalidOperationException("Cliente inativo não pode receber nova fatura."); const string sql="insert into sigov.saneamento_fatura(tenant_id,entidade_id,exercicio_id,unidade_consumidora_id,leitura_id,numero,competencia,data_vencimento,valor_agua,valor_esgoto,valor_servicos,valor_total,status,codigo_barras,linha_digitavel,ambiente,created_by) select tenant_id,entidade_id,@ExercicioId,unidade_consumidora_id,id,@Numero,competencia,@DataVencimento,consumo_faturado*@TarifaAgua,consumo_faturado*@TarifaEsgoto,@ValorServicos,(consumo_faturado*@TarifaAgua)+(consumo_faturado*@TarifaEsgoto)+@ValorServicos,'ABERTA',null,null,@Ambiente,@UsuarioId from sigov.saneamento_leitura where tenant_id=@TenantId and entidade_id=@EntidadeId and id=@LeituraId and is_deleted=false returning id"; return await cn.ExecuteScalarAsync<long>(new CommandDefinition(sql,new{TenantId=t,EntidadeId=e,ExercicioId=ex,LeituraId=leituraId,Numero=numero,r.DataVencimento,r.TarifaAgua,r.TarifaEsgoto,r.ValorServicos,Ambiente=ambiente,UsuarioId=u},cancellationToken:ct));}
    async Task IFaturaSaneamentoRepository.CancelarAsync(long t,long e,long id,long? u,string motivo,CancellationToken ct){using var cn=_context.CreateConnection(); await cn.ExecuteAsync(new CommandDefinition("update sigov.saneamento_fatura set status='CANCELADA',updated_by=@UsuarioId,updated_at=now() where tenant_id=@TenantId and entidade_id=@EntidadeId and id=@Id and status <> 'PAGA'",new{TenantId=t,EntidadeId=e,Id=id,UsuarioId=u,Motivo=motivo},cancellationToken:ct));}
    async Task<ArrecadacaoSaneamentoResponse> IFaturaSaneamentoRepository.RegistrarPagamentoDevAsync(long t,long e,long? ex,long id,long? u,RegistrarPagamentoDevRequest r,string numero,CancellationToken ct){using var cn=_context.CreateConnection(); cn.Open(); using var tx=cn.BeginTransaction(); var f=await cn.QuerySingleAsync<(decimal ValorTotal,decimal ValorPago,string Status)>(new CommandDefinition("select valor_total as ValorTotal,valor_pago as ValorPago,status as Status from sigov.saneamento_fatura where tenant_id=@TenantId and entidade_id=@EntidadeId and id=@Id and is_deleted=false for update",new{TenantId=t,EntidadeId=e,Id=id},transaction:tx,cancellationToken:ct)); if(f.Status is "PAGA" or "CANCELADA") throw new InvalidOperationException("Fatura não pode receber pagamento."); if(r.ValorPago<=0 || r.ValorPago>f.ValorTotal-f.ValorPago) throw new InvalidOperationException("Valor maior que o saldo da fatura."); var aid=await cn.ExecuteScalarAsync<long>(new CommandDefinition("insert into sigov.saneamento_arrecadacao(tenant_id,entidade_id,exercicio_id,fatura_id,numero,data_pagamento,forma_pagamento,valor_pago,origem,metadados,created_by) values(@TenantId,@EntidadeId,@ExercicioId,@FaturaId,@Numero,@DataPagamento,'MANUAL_DEV',@ValorPago,@Origem,'{}'::jsonb,@UsuarioId) returning id",new{TenantId=t,EntidadeId=e,ExercicioId=ex,FaturaId=id,Numero=numero,DataPagamento=r.DataPagamento??DateOnly.FromDateTime(DateTime.UtcNow),r.ValorPago,r.Origem,UsuarioId=u},transaction:tx,cancellationToken:ct)); var novo=f.ValorPago+r.ValorPago; await cn.ExecuteAsync(new CommandDefinition("update sigov.saneamento_fatura set valor_pago=@ValorPago,status=case when @ValorPago>=valor_total then 'PAGA' else status end,updated_at=now(),updated_by=@UsuarioId where tenant_id=@TenantId and entidade_id=@EntidadeId and id=@Id",new{TenantId=t,EntidadeId=e,Id=id,ValorPago=novo,UsuarioId=u},transaction:tx,cancellationToken:ct)); tx.Commit(); return new(aid,id,numero,r.DataPagamento??DateOnly.FromDateTime(DateTime.UtcNow),"MANUAL_DEV",r.ValorPago);}

    async Task<PagedResult<ArrecadacaoSaneamentoResponse>> IArrecadacaoSaneamentoRepository.ListarAsync(long t,long e,SaneamentoFiltro f,CancellationToken ct){using var cn=_context.CreateConnection(); var p=new{TenantId=t,EntidadeId=e,Limit=Limit(f.PageSize),Offset=Offset(f.Page,f.PageSize)}; var total=await cn.ExecuteScalarAsync<long>(new CommandDefinition("select count(*) from sigov.saneamento_arrecadacao where tenant_id=@TenantId and entidade_id=@EntidadeId and is_deleted=false",p,cancellationToken:ct)); var rows=await cn.QueryAsync<ArrecadacaoSaneamentoResponse>(new CommandDefinition("select id as Id,fatura_id as FaturaId,numero as Numero,data_pagamento as DataPagamento,forma_pagamento as FormaPagamento,valor_pago as ValorPago from sigov.saneamento_arrecadacao where tenant_id=@TenantId and entidade_id=@EntidadeId and is_deleted=false order by id desc limit @Limit offset @Offset",p,cancellationToken:ct)); return new(rows.AsList(),f.Page,f.PageSize,total);}
    async Task<long> IArrecadacaoSaneamentoRepository.CriarAsync(long t,long e,long? ex,long? u,ArrecadacaoSaneamentoCreateRequest r,string numero,CancellationToken ct){using var cn=_context.CreateConnection(); return await cn.ExecuteScalarAsync<long>(new CommandDefinition("insert into sigov.saneamento_arrecadacao(tenant_id,entidade_id,exercicio_id,fatura_id,numero,data_pagamento,forma_pagamento,valor_pago,origem,metadados,created_by) values(@TenantId,@EntidadeId,@ExercicioId,@FaturaId,@Numero,@DataPagamento,@FormaPagamento,@ValorPago,@Origem,cast(@MetadadosJson as jsonb),@UsuarioId) returning id",new{TenantId=t,EntidadeId=e,ExercicioId=ex,r.FaturaId,Numero=numero,DataPagamento=r.DataPagamento??DateOnly.FromDateTime(DateTime.UtcNow),r.FormaPagamento,r.ValorPago,r.Origem,r.MetadadosJson,UsuarioId=u},cancellationToken:ct));}
    async Task<PagedResult<ParcelamentoSaneamentoResponse>> IParcelamentoSaneamentoRepository.ListarAsync(long t,long e,SaneamentoFiltro f,CancellationToken ct){using var cn=_context.CreateConnection(); var p=new{TenantId=t,EntidadeId=e,Limit=Limit(f.PageSize),Offset=Offset(f.Page,f.PageSize)}; var total=await cn.ExecuteScalarAsync<long>(new CommandDefinition("select count(*) from sigov.saneamento_parcelamento where tenant_id=@TenantId and entidade_id=@EntidadeId and is_deleted=false",p,cancellationToken:ct)); var rows=await cn.QueryAsync<ParcelamentoSaneamentoResponse>(new CommandDefinition("select id as Id,consumidor_id as ConsumidorId,numero as Numero,quantidade_parcelas as QuantidadeParcelas,valor_total as ValorTotal,status as Status from sigov.saneamento_parcelamento where tenant_id=@TenantId and entidade_id=@EntidadeId and is_deleted=false order by id desc limit @Limit offset @Offset",p,cancellationToken:ct)); return new(rows.AsList(),f.Page,f.PageSize,total);}
    async Task<long> IParcelamentoSaneamentoRepository.CriarAsync(long t,long e,long? ex,long? u,ParcelamentoSaneamentoCreateRequest r,string numero,CancellationToken ct){if(r.QuantidadeParcelas <= 1) throw new ArgumentException("Quantidade de parcelas deve ser maior que 1."); if(r.ValorTotal <= 0) throw new ArgumentException("Valor total do parcelamento deve ser maior que zero."); using var cn=_context.CreateConnection(); return await cn.ExecuteScalarAsync<long>(new CommandDefinition("insert into sigov.saneamento_parcelamento(tenant_id,entidade_id,exercicio_id,consumidor_id,numero,quantidade_parcelas,valor_total,status,observacao,created_by) values(@TenantId,@EntidadeId,@ExercicioId,@ConsumidorId,@Numero,@QuantidadeParcelas,@ValorTotal,'ATIVO',@Observacao,@UsuarioId) returning id",new{TenantId=t,EntidadeId=e,ExercicioId=ex,r.ConsumidorId,Numero=numero,r.QuantidadeParcelas,r.ValorTotal,r.Observacao,UsuarioId=u},cancellationToken:ct));}

    async Task<PagedResult<OrdemServicoSaneamentoResponse>> IOrdemServicoSaneamentoRepository.ListarAsync(long t,long e,OrdemServicoSaneamentoFiltro f,CancellationToken ct){using var cn=_context.CreateConnection(); const string w="tenant_id=@TenantId and entidade_id=@EntidadeId and is_deleted=false and (@Status is null or status=@Status) and (@UnidadeConsumidoraId is null or unidade_consumidora_id=@UnidadeConsumidoraId)"; var p=new{TenantId=t,EntidadeId=e,f.Status,f.UnidadeConsumidoraId,Limit=Limit(f.PageSize),Offset=Offset(f.Page,f.PageSize)}; var total=await cn.ExecuteScalarAsync<long>(new CommandDefinition($"select count(*) from sigov.saneamento_ordem_servico where {w}",p,cancellationToken:ct)); var rows=await cn.QueryAsync<OrdemServicoSaneamentoResponse>(new CommandDefinition($"select id as Id,numero as Numero,unidade_consumidora_id as UnidadeConsumidoraId,consumidor_id as ConsumidorId,tipo_servico as TipoServico,prioridade as Prioridade,status as Status,data_abertura as DataAbertura from sigov.saneamento_ordem_servico where {w} order by id desc limit @Limit offset @Offset",p,cancellationToken:ct)); return new(rows.AsList(),f.Page,f.PageSize,total);}
    async Task<OrdemServicoSaneamentoResponse?> IOrdemServicoSaneamentoRepository.ObterAsync(long t,long e,long id,CancellationToken ct){using var cn=_context.CreateConnection(); return await cn.QuerySingleOrDefaultAsync<OrdemServicoSaneamentoResponse>(new CommandDefinition("select id as Id,numero as Numero,unidade_consumidora_id as UnidadeConsumidoraId,consumidor_id as ConsumidorId,tipo_servico as TipoServico,prioridade as Prioridade,status as Status,data_abertura as DataAbertura from sigov.saneamento_ordem_servico where tenant_id=@TenantId and entidade_id=@EntidadeId and id=@Id and is_deleted=false",new{TenantId=t,EntidadeId=e,Id=id},cancellationToken:ct));}
    async Task<long> IOrdemServicoSaneamentoRepository.CriarAsync(long t,long e,long? ex,long? u,OrdemServicoSaneamentoCreateRequest r,string numero,CancellationToken ct){using var cn=_context.CreateConnection(); return await cn.ExecuteScalarAsync<long>(new CommandDefinition("insert into sigov.saneamento_ordem_servico(tenant_id,entidade_id,exercicio_id,unidade_consumidora_id,consumidor_id,numero,tipo_servico,prioridade,status,data_agendamento,equipe_campo_id,descricao,latitude,longitude,created_by) values(@TenantId,@EntidadeId,@ExercicioId,@UnidadeConsumidoraId,@ConsumidorId,@Numero,@TipoServico,@Prioridade,'ABERTA',@DataAgendamento,@EquipeCampoId,@Descricao,@Latitude,@Longitude,@UsuarioId) returning id",new{TenantId=t,EntidadeId=e,ExercicioId=ex,r.UnidadeConsumidoraId,r.ConsumidorId,Numero=numero,r.TipoServico,r.Prioridade,r.DataAgendamento,r.EquipeCampoId,r.Descricao,r.Latitude,r.Longitude,UsuarioId=u},cancellationToken:ct));}
    async Task IOrdemServicoSaneamentoRepository.AtualizarAsync(long t,long e,long id,long? u,OrdemServicoSaneamentoUpdateRequest r,CancellationToken ct){using var cn=_context.CreateConnection(); await cn.ExecuteAsync(new CommandDefinition("update sigov.saneamento_ordem_servico set tipo_servico=@TipoServico,prioridade=@Prioridade,status=@Status,descricao=@Descricao,equipe_campo_id=@EquipeCampoId,data_agendamento=@DataAgendamento,latitude=@Latitude,longitude=@Longitude,updated_by=@UsuarioId,updated_at=now() where tenant_id=@TenantId and entidade_id=@EntidadeId and id=@Id and is_deleted=false and status <> 'EXECUTADA'",new{TenantId=t,EntidadeId=e,Id=id,UsuarioId=u,r.TipoServico,r.Prioridade,r.Status,r.Descricao,r.EquipeCampoId,r.DataAgendamento,r.Latitude,r.Longitude},cancellationToken:ct));}
    async Task IOrdemServicoSaneamentoRepository.ExecutarAsync(long t,long e,long? ex,long id,long? u,ExecutarOrdemServicoRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Solucao)) throw new ArgumentException("O encerramento da ordem de serviço exige relatório da solução."); using var cn=_context.CreateConnection(); cn.Open(); using var tx=cn.BeginTransaction(); await cn.ExecuteAsync(new CommandDefinition("update sigov.saneamento_ordem_servico set status='EXECUTADA',solucao=@Solucao,data_execucao=now(),equipe_campo_id=coalesce(@EquipeCampoId,equipe_campo_id),updated_by=@UsuarioId,updated_at=now() where tenant_id=@TenantId and entidade_id=@EntidadeId and id=@Id and status <> 'CANCELADA'",new{TenantId=t,EntidadeId=e,Id=id,r.Solucao,r.EquipeCampoId,UsuarioId=u},transaction:tx,cancellationToken:ct)); await cn.ExecuteAsync(new CommandDefinition("insert into sigov.saneamento_servico_executado(tenant_id,entidade_id,exercicio_id,ordem_servico_id,tipo_servico,descricao,equipe_campo_id,materiais_json,evidencias_json,created_by) select tenant_id,entidade_id,@ExercicioId,id,tipo_servico,@Solucao,@EquipeCampoId,cast(@Materiais as jsonb),cast(@Evidencias as jsonb),@UsuarioId from sigov.saneamento_ordem_servico where tenant_id=@TenantId and entidade_id=@EntidadeId and id=@Id",new{TenantId=t,EntidadeId=e,ExercicioId=ex,Id=id,r.Solucao,r.EquipeCampoId,Materiais=r.MateriaisJson??"[]",Evidencias=r.EvidenciasJson??"[]",UsuarioId=u},transaction:tx,cancellationToken:ct)); tx.Commit();}
    async Task IOrdemServicoSaneamentoRepository.CancelarAsync(long t,long e,long id,long? u,string motivo,CancellationToken ct){using var cn=_context.CreateConnection(); await cn.ExecuteAsync(new CommandDefinition("update sigov.saneamento_ordem_servico set status='CANCELADA',solucao=@Motivo,updated_by=@UsuarioId,updated_at=now() where tenant_id=@TenantId and entidade_id=@EntidadeId and id=@Id and status <> 'EXECUTADA'",new{TenantId=t,EntidadeId=e,Id=id,Motivo=motivo,UsuarioId=u},cancellationToken:ct));}
    async Task<PagedResult<EquipeCampoSaneamentoResponse>> IEquipeCampoSaneamentoRepository.ListarAsync(long t,long e,SaneamentoFiltro f,CancellationToken ct){using var cn=_context.CreateConnection(); var p=new{TenantId=t,EntidadeId=e,Limit=Limit(f.PageSize),Offset=Offset(f.Page,f.PageSize)}; var total=await cn.ExecuteScalarAsync<long>(new CommandDefinition("select count(*) from sigov.saneamento_equipe_campo where tenant_id=@TenantId and entidade_id=@EntidadeId and is_deleted=false",p,cancellationToken:ct)); var rows=await cn.QueryAsync<EquipeCampoSaneamentoResponse>(new CommandDefinition("select id as Id,codigo as Codigo,nome as Nome,responsavel_usuario_id as ResponsavelUsuarioId,ativo as Ativo from sigov.saneamento_equipe_campo where tenant_id=@TenantId and entidade_id=@EntidadeId and is_deleted=false order by id desc limit @Limit offset @Offset",p,cancellationToken:ct)); return new(rows.AsList(),f.Page,f.PageSize,total);}
    async Task<long> IEquipeCampoSaneamentoRepository.CriarAsync(long t,long e,long? u,EquipeCampoSaneamentoCreateRequest r,string codigo,CancellationToken ct){using var cn=_context.CreateConnection(); return await cn.ExecuteScalarAsync<long>(new CommandDefinition("insert into sigov.saneamento_equipe_campo(tenant_id,entidade_id,codigo,nome,responsavel_usuario_id,membros_json,created_by) values(@TenantId,@EntidadeId,@Codigo,@Nome,@ResponsavelUsuarioId,cast(@MembrosJson as jsonb),@UsuarioId) returning id",new{TenantId=t,EntidadeId=e,Codigo=codigo,r.Nome,r.ResponsavelUsuarioId,r.MembrosJson,UsuarioId=u},cancellationToken:ct));}

    async Task<PagedResult<LaboratorioAmostraResponse>> ILaboratorioSaneamentoRepository.ListarAsync(long t,long e,SaneamentoFiltro f,CancellationToken ct){using var cn=_context.CreateConnection(); var p=new{TenantId=t,EntidadeId=e,Limit=Limit(f.PageSize),Offset=Offset(f.Page,f.PageSize)}; var total=await cn.ExecuteScalarAsync<long>(new CommandDefinition("select count(*) from sigov.saneamento_laboratorio_amostra where tenant_id=@TenantId and entidade_id=@EntidadeId and is_deleted=false",p,cancellationToken:ct)); var rows=await cn.QueryAsync<LaboratorioAmostraResponse>(new CommandDefinition("select id as Id,numero as Numero,ponto_coleta as PontoColeta,data_coleta as DataColeta,status as Status from sigov.saneamento_laboratorio_amostra where tenant_id=@TenantId and entidade_id=@EntidadeId and is_deleted=false order by id desc limit @Limit offset @Offset",p,cancellationToken:ct)); return new(rows.AsList(),f.Page,f.PageSize,total);}
    async Task<long> ILaboratorioSaneamentoRepository.CriarAmostraAsync(long t,long e,long? ex,long? u,LaboratorioAmostraCreateRequest r,string numero,CancellationToken ct){using var cn=_context.CreateConnection(); return await cn.ExecuteScalarAsync<long>(new CommandDefinition("insert into sigov.saneamento_laboratorio_amostra(tenant_id,entidade_id,exercicio_id,numero,ponto_coleta,data_coleta,coletado_por_usuario_id,latitude,longitude,status,observacao,created_by) values(@TenantId,@EntidadeId,@ExercicioId,@Numero,@PontoColeta,@DataColeta,@ColetadoPorUsuarioId,@Latitude,@Longitude,@Status,@Observacao,@UsuarioId) returning id",new{TenantId=t,EntidadeId=e,ExercicioId=ex,Numero=numero,r.PontoColeta,r.DataColeta,r.ColetadoPorUsuarioId,r.Latitude,r.Longitude,r.Status,r.Observacao,UsuarioId=u},cancellationToken:ct));}
    async Task<long> ILaboratorioSaneamentoRepository.CriarResultadoAsync(long t,long e,long amostraId,long? u,LaboratorioResultadoCreateRequest r,CancellationToken ct){using var cn=_context.CreateConnection(); return await cn.ExecuteScalarAsync<long>(new CommandDefinition("insert into sigov.saneamento_laboratorio_resultado(tenant_id,entidade_id,amostra_id,parametro,valor,unidade,limite_referencia,conforme,data_resultado,observacao,created_by) values(@TenantId,@EntidadeId,@AmostraId,@Parametro,@Valor,@Unidade,@LimiteReferencia,@Conforme,@DataResultado,@Observacao,@UsuarioId) returning id",new{TenantId=t,EntidadeId=e,AmostraId=amostraId,r.Parametro,r.Valor,r.Unidade,r.LimiteReferencia,r.Conforme,DataResultado=r.DataResultado??DateOnly.FromDateTime(DateTime.UtcNow),r.Observacao,UsuarioId=u},cancellationToken:ct));}
    async Task<PagedResult<RedeSaneamentoTrechoResponse>> IRedeSaneamentoRepository.ListarAsync(long t,long e,SaneamentoFiltro f,CancellationToken ct){using var cn=_context.CreateConnection(); var p=new{TenantId=t,EntidadeId=e,Limit=Limit(f.PageSize),Offset=Offset(f.Page,f.PageSize)}; var total=await cn.ExecuteScalarAsync<long>(new CommandDefinition("select count(*) from sigov.saneamento_rede_trecho where tenant_id=@TenantId and entidade_id=@EntidadeId and is_deleted=false",p,cancellationToken:ct)); var rows=await cn.QueryAsync<RedeSaneamentoTrechoResponse>(new CommandDefinition("select id as Id,codigo as Codigo,tipo_rede as TipoRede,material as Material,diametro as Diametro,extensao_metros as ExtensaoMetros,situacao as Situacao from sigov.saneamento_rede_trecho where tenant_id=@TenantId and entidade_id=@EntidadeId and is_deleted=false order by id desc limit @Limit offset @Offset",p,cancellationToken:ct)); return new(rows.AsList(),f.Page,f.PageSize,total);}
    async Task<long> IRedeSaneamentoRepository.CriarAsync(long t,long e,long? u,RedeSaneamentoTrechoCreateRequest r,string codigo,CancellationToken ct){using var cn=_context.CreateConnection(); return await cn.ExecuteScalarAsync<long>(new CommandDefinition("insert into sigov.saneamento_rede_trecho(tenant_id,entidade_id,codigo,tipo_rede,material,diametro,extensao_metros,geometria_geojson,situacao,created_by) values(@TenantId,@EntidadeId,@Codigo,@TipoRede,@Material,@Diametro,@ExtensaoMetros,cast(@GeometriaGeoJson as jsonb),@Situacao,@UsuarioId) returning id",new{TenantId=t,EntidadeId=e,Codigo=codigo,r.TipoRede,r.Material,r.Diametro,r.ExtensaoMetros,GeometriaGeoJson=r.GeometriaGeoJson??"{}",r.Situacao,UsuarioId=u},cancellationToken:ct));}
    async Task<SaneamentoDashboardResponse> ISaneamentoDashboardRepository.ObterAsync(long t,long e,CancellationToken ct){using var cn=_context.CreateConnection(); const string sql = """
        select
            (select count(*) from sigov.saneamento_consumidor where tenant_id=@TenantId and entidade_id=@EntidadeId and is_deleted=false) as total_consumidores,
            (select count(*) from sigov.saneamento_unidade_consumidora where tenant_id=@TenantId and entidade_id=@EntidadeId and situacao='ATIVA' and is_deleted=false) as total_unidades_consumidoras,
            (select count(*) from sigov.saneamento_ligacao where tenant_id=@TenantId and entidade_id=@EntidadeId and situacao='ATIVA' and is_deleted=false) as ligacoes_ativas,
            (select count(*) from sigov.saneamento_hidrometro where tenant_id=@TenantId and entidade_id=@EntidadeId and situacao='INSTALADO' and is_deleted=false) as hidrometros_ativos,
            (select count(*) from sigov.saneamento_leitura where tenant_id=@TenantId and entidade_id=@EntidadeId and competencia=to_char(current_date, 'YYYY-MM') and is_deleted=false) as leituras_competencia,
            (select count(*) from sigov.saneamento_fatura where tenant_id=@TenantId and entidade_id=@EntidadeId and status='ABERTA' and is_deleted=false) as faturas_abertas,
            (select count(*) from sigov.saneamento_fatura where tenant_id=@TenantId and entidade_id=@EntidadeId and status='ABERTA' and data_vencimento < current_date and is_deleted=false) as faturas_vencidas,
            (select coalesce(sum(valor_total), 0) from sigov.saneamento_fatura where tenant_id=@TenantId and entidade_id=@EntidadeId and competencia=to_char(current_date, 'YYYY-MM') and is_deleted=false) as valor_faturado_mes,
            (select coalesce(sum(valor_pago), 0) from sigov.saneamento_arrecadacao where tenant_id=@TenantId and entidade_id=@EntidadeId and to_char(data_pagamento, 'YYYY-MM')=to_char(current_date, 'YYYY-MM') and is_deleted=false) as valor_arrecadado_mes,
            (select count(*) from sigov.saneamento_ordem_servico where tenant_id=@TenantId and entidade_id=@EntidadeId and status='ABERTA' and is_deleted=false) as ordens_abertas,
            (select count(*) from sigov.saneamento_ordem_servico where tenant_id=@TenantId and entidade_id=@EntidadeId and status in ('EM_ANDAMENTO','EM_EXECUCAO') and is_deleted=false) as ordens_em_campo,
            (select count(*) from sigov.saneamento_fatura where tenant_id=@TenantId and entidade_id=@EntidadeId and status='ABERTA' and (linha_digitavel is null or linha_digitavel='') and is_deleted=false) as faturas_sem_convenio;
        """;
        var d = await cn.QuerySingleOrDefaultAsync<dynamic>(new CommandDefinition(sql, new { TenantId = t, EntidadeId = e }, cancellationToken: ct)).ConfigureAwait(false);
        if (d is null) return new(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Array.Empty<object>(),Array.Empty<object>(),Array.Empty<object>(),Array.Empty<string>());
        long cons = (long)(d.total_consumidores ?? 0L);
        long ucs = (long)(d.total_unidades_consumidoras ?? 0L);
        long lig = (long)(d.ligacoes_ativas ?? 0L);
        long hid = (long)(d.hidrometros_ativos ?? 0L);
        long leit = (long)(d.leituras_competencia ?? 0L);
        long fatAb = (long)(d.faturas_abertas ?? 0L);
        long fatVenc = (long)(d.faturas_vencidas ?? 0L);
        decimal vFat = (decimal)(d.valor_faturado_mes ?? 0m);
        decimal vArr = (decimal)(d.valor_arrecadado_mes ?? 0m);
        long osAb = (long)(d.ordens_abertas ?? 0L);
        long osCampo = (long)(d.ordens_em_campo ?? 0L);
        long fatSemConv = (long)(d.faturas_sem_convenio ?? 0L);
        var alertas = new List<string>();
        if (fatSemConv > 0) alertas.Add($"{fatSemConv} fatura(s) sem linha digitável gerada por ausência de convênio bancário.");
        if (fatVenc > 0) alertas.Add($"{fatVenc} fatura(s) vencida(s) em cobrança.");
        return new(cons, ucs, lig, hid, leit, fatAb, fatVenc, vFat, vArr, Math.Max(0m, vFat - vArr), osAb, osCampo, 0, 0, 0, 0, Array.Empty<object>(), Array.Empty<object>(), Array.Empty<object>(), alertas);
    }

    async Task<byte[]> ISaneamentoExportacaoRepository.ExportarAsync(long t,long e,string recurso,string formato,CancellationToken ct){
        var recursoNormalizado=(recurso??string.Empty).ToLowerInvariant();
        var table=recursoNormalizado switch { "consumidores"=>"saneamento_consumidor", "unidades-consumidoras"=>"saneamento_unidade_consumidora", "leituras"=>"saneamento_leitura", "faturas"=>"saneamento_fatura", "ordens-servico"=>"saneamento_ordem_servico", "laboratorio"=>"saneamento_laboratorio_amostra", _=>"saneamento_consumidor" };
        using var cn=_context.CreateConnection();
        var rows=(await cn.QueryAsync(new CommandDefinition($"select * from sigov.{table} where tenant_id=@TenantId and entidade_id=@EntidadeId and is_deleted=false order by id desc limit 5000",new{TenantId=t,EntidadeId=e},cancellationToken:ct))).Select(r=>(IDictionary<string,object>)r).ToList();
        if(formato.Equals("json",StringComparison.OrdinalIgnoreCase)) return Encoding.UTF8.GetBytes(System.Text.Json.JsonSerializer.Serialize(rows));
        var sb=new StringBuilder();
        if(rows.Count>0){
            var keys = rows[0].Keys.Where(k => !k.Contains("senha", StringComparison.OrdinalIgnoreCase) && !k.Contains("token", StringComparison.OrdinalIgnoreCase)).ToList();
            sb.AppendLine(string.Join(';', keys));
            foreach(var r in rows){
                var vals = keys.Select(k => {
                    r.TryGetValue(k, out var val);
                    var str = Convert.ToString(val, CultureInfo.InvariantCulture) ?? string.Empty;
                    if (k.Contains("cpf", StringComparison.OrdinalIgnoreCase) || k.Contains("documento", StringComparison.OrdinalIgnoreCase)) {
                        if (str.Length >= 6) str = string.Concat(str.AsSpan(0, 3), "***", str.AsSpan(str.Length - 2));
                    }
                    if (str.StartsWith('=') || str.StartsWith('+') || str.StartsWith('-') || str.StartsWith('@') || str.StartsWith('\t') || str.StartsWith('\r')) str = "'" + str;
                    return str.Replace(";", ",", StringComparison.Ordinal);
                });
                sb.AppendLine(string.Join(';', vals));
            }
        }
        var bom = Encoding.UTF8.GetPreamble();
        var data = Encoding.UTF8.GetBytes(sb.ToString());
        var res = new byte[bom.Length + data.Length];
        Buffer.BlockCopy(bom, 0, res, 0, bom.Length);
        Buffer.BlockCopy(data, 0, res, bom.Length, data.Length);
        return res;
    }
}
