using Dapper;
using Npgsql;
using Sigov.Application.Common;
using Sigov.Application.ComprasEmpresariais;
using Sigov.Infrastructure.Persistence.Dapper;

namespace Sigov.Infrastructure.ComprasEmpresariais;

public sealed class FornecedorRepository(NpgsqlConnectionFactory factory):IFornecedorRepository
{
 public async Task<PagedResult<FornecedorResumo>> ListarAsync(Guid t,FornecedorFiltro f,CancellationToken ct){var p=Math.Max(1,f.Pagina);var s=Math.Clamp(f.Tamanho,1,100);const string q="select count(*) from sigov.compras_empresarial_fornecedor where tenant_id=@t and not is_deleted and (@status is null or status=@status) and (@busca is null or razao_social ilike @term or nome_fantasia ilike @term or codigo ilike @term);select id,codigo,razao_social RazaoSocial,nome_fantasia NomeFantasia,documento_mascarado DocumentoMascarado,status,score,version from sigov.compras_empresarial_fornecedor where tenant_id=@t and not is_deleted and (@status is null or status=@status) and (@busca is null or razao_social ilike @term or nome_fantasia ilike @term or codigo ilike @term) order by razao_social offset @off limit @s";await using var c=factory.CreateConnection();using var m=await c.QueryMultipleAsync(new CommandDefinition(q,new{t,status=string.IsNullOrWhiteSpace(f.Status)?null:f.Status.ToUpperInvariant(),busca=string.IsNullOrWhiteSpace(f.Busca)?null:f.Busca,term=$"%{f.Busca}%",off=(p-1)*s,s},cancellationToken:ct));var n=await m.ReadSingleAsync<long>();return new((await m.ReadAsync<FornecedorResumo>()).AsList(),p,s,n);}
 public async Task<FornecedorResumo?> ObterAsync(Guid t,Guid id,CancellationToken ct){const string q="select id,codigo,razao_social RazaoSocial,nome_fantasia NomeFantasia,documento_mascarado DocumentoMascarado,status,score,version from sigov.compras_empresarial_fornecedor where tenant_id=@t and id=@id and not is_deleted";await using var c=factory.CreateConnection();return await c.QuerySingleOrDefaultAsync<FornecedorResumo>(new CommandDefinition(q,new{t,id},cancellationToken:ct));}
 public async Task<Guid> CriarAsync(ComprasContext x,CriarFornecedorRequest r,string key,CancellationToken ct){await using var c=factory.CreateConnection();await c.OpenAsync(ct);await using var tx=await c.BeginTransactionAsync(ct);var old=await c.ExecuteScalarAsync<Guid?>(new CommandDefinition("select recurso_id from sigov.compras_empresarial_idempotencia where tenant_id=@t and operacao='FORNECEDOR_CRIAR' and chave=@key",new{t=x.TenantId,key},tx,cancellationToken:ct));if(old.HasValue){await tx.CommitAsync(ct);return old.Value;}var id=Guid.NewGuid();var codigo=await Next(c,tx,x.TenantId,"FORNECEDOR","FOR",ct);const string sql="insert into sigov.compras_empresarial_fornecedor(id,tenant_id,codigo,tipo_pessoa,documento_hash,documento_mascarado,razao_social,nome_fantasia,categoria,porte,condicao_pagamento,prazo_medio,observacoes,created_by,updated_by,correlation_id) values(@id,@t,@codigo,upper(@TipoPessoa),encode(digest(regexp_replace(@Documento,'[^0-9]','','g'),'sha256'),'hex'),case when length(regexp_replace(@Documento,'[^0-9]','','g'))=14 then '***.***.***/' || substring(regexp_replace(@Documento,'[^0-9]','','g') from 9 for 4) || '-**' else '***.***.' || substring(regexp_replace(@Documento,'[^0-9]','','g') from 7 for 3) || '-**' end,@RazaoSocial,@NomeFantasia,@Categoria,@Porte,@CondicaoPagamento,@PrazoMedio,@Observacoes,@us,@us,@corr);insert into sigov.compras_empresarial_historico(tenant_id,aggregate_type,aggregate_id,acao,created_by,correlation_id) values(@t,'FORNECEDOR',@id,'CRIADO',@us,@corr);insert into sigov.compras_empresarial_idempotencia(tenant_id,operacao,chave,recurso_id) values(@t,'FORNECEDOR_CRIAR',@key,@id);insert into sigov.integracao_outbox(id,tenant_id,tipo_evento,aggregate_id,payload,created_at) values(gen_random_uuid(),@t,'compras.fornecedor.criado',@id,jsonb_build_object('fornecedorId',@id),now())";await c.ExecuteAsync(new CommandDefinition(sql,new{id,t=x.TenantId,codigo,r.TipoPessoa,r.Documento,r.RazaoSocial,r.NomeFantasia,r.Categoria,r.Porte,r.CondicaoPagamento,r.PrazoMedio,r.Observacoes,us=x.UsuarioId.ToString(),corr=x.CorrelationId,key},tx,cancellationToken:ct));await tx.CommitAsync(ct);return id;}
 public async Task AlterarStatusAsync(ComprasContext x,Guid id,AlterarStatusRequest r,CancellationToken ct){var status=r.Status.ToUpperInvariant();if((status is "BLOQUEADO" or "SUSPENSO") && string.IsNullOrWhiteSpace(r.Motivo))throw new ArgumentException("Motivo obrigatório.");await using var c=factory.CreateConnection();await c.OpenAsync(ct);await using var tx=await c.BeginTransactionAsync(ct);var n=await c.ExecuteAsync(new CommandDefinition("update sigov.compras_empresarial_fornecedor set status=@status,version=version+1,updated_at=now(),updated_by=@us,correlation_id=@corr where tenant_id=@t and id=@id and version=@Version and not is_deleted",new{t=x.TenantId,id,status,r.Version,r.Motivo,us=x.UsuarioId.ToString(),corr=x.CorrelationId},tx,cancellationToken:ct));if(n!=1)throw new InvalidOperationException("Fornecedor não encontrado ou versão desatualizada.");await c.ExecuteAsync(new CommandDefinition("insert into sigov.compras_empresarial_historico(tenant_id,aggregate_type,aggregate_id,acao,detalhes,created_by,correlation_id) values(@t,'FORNECEDOR',@id,@status,jsonb_build_object('motivo',@motivo),@us,@corr)",new{t=x.TenantId,id,status,motivo=r.Motivo,us=x.UsuarioId.ToString(),corr=x.CorrelationId},tx,cancellationToken:ct));await tx.CommitAsync(ct);}
 public Task AdicionarContatoAsync(ComprasContext x,Guid id,AdicionarContatoRequest r,string key,CancellationToken ct)=>Child(x,id,key,"CONTATO","insert into sigov.compras_empresarial_fornecedor_contato(id,tenant_id,fornecedor_id,nome,email,telefone,principal,created_by,updated_by,correlation_id) values(@child,@t,@id,@Nome,@Email,@Telefone,@Principal,@us,@us,@corr)",r,ct);
 public Task AdicionarEnderecoAsync(ComprasContext x,Guid id,AdicionarEnderecoRequest r,string key,CancellationToken ct)=>Child(x,id,key,"ENDERECO","insert into sigov.compras_empresarial_fornecedor_endereco(id,tenant_id,fornecedor_id,tipo,logradouro,numero,complemento,bairro,cidade,uf,cep,created_by,updated_by,correlation_id) values(@child,@t,@id,@Tipo,@Logradouro,@Numero,@Complemento,@Bairro,@Cidade,upper(@Uf),@Cep,@us,@us,@corr)",r,ct);
 public Task AdicionarDocumentoAsync(ComprasContext x,Guid id,AdicionarDocumentoRequest r,string key,CancellationToken ct)=>Child(x,id,key,"DOCUMENTO","insert into sigov.compras_empresarial_fornecedor_documento(id,tenant_id,fornecedor_id,documento_ged_id,tipo,obrigatorio,validade,created_by,updated_by,correlation_id) values(@child,@t,@id,@DocumentoGedId,@Tipo,@Obrigatorio,@Validade,@us,@us,@corr)",r,ct);
 private async Task Child(ComprasContext x,Guid id,string key,string op,string sql,object values,CancellationToken ct){await using var c=factory.CreateConnection();await c.OpenAsync(ct);await using var tx=await c.BeginTransactionAsync(ct);var args=new DynamicParameters(values);args.Add("child",Guid.NewGuid());args.Add("t",x.TenantId);args.Add("id",id);args.Add("us",x.UsuarioId.ToString());args.Add("corr",x.CorrelationId);args.Add("key",key);args.Add("op",op);var n=await c.ExecuteAsync(new CommandDefinition(sql+";insert into sigov.compras_empresarial_idempotencia(tenant_id,operacao,chave,recurso_id) values(@t,@op,@key,@child) on conflict do nothing;insert into sigov.compras_empresarial_historico(tenant_id,aggregate_type,aggregate_id,acao,created_by,correlation_id) values(@t,'FORNECEDOR',@id,@op,@us,@corr)",args,tx,cancellationToken:ct));if(n!=3)throw new InvalidOperationException("Operação duplicada ou fornecedor inválido.");await tx.CommitAsync(ct);}
 internal static async Task<string> Next(NpgsqlConnection c,NpgsqlTransaction tx,Guid t,string tipo,string prefix,CancellationToken ct){var n=await c.ExecuteScalarAsync<long>(new CommandDefinition("insert into sigov.compras_empresarial_numeracao(tenant_id,tipo,ano,ultimo_numero) values(@t,@tipo,extract(year from current_date)::int,1) on conflict(tenant_id,tipo,ano) do update set ultimo_numero=sigov.compras_empresarial_numeracao.ultimo_numero+1,updated_at=now() returning ultimo_numero",new{t,tipo},tx,cancellationToken:ct));return $"{prefix}-{DateTime.UtcNow:yyyy}-{n:000000}";}
}

public sealed class RequisicaoCompraRepository(NpgsqlConnectionFactory factory):IRequisicaoCompraRepository
{
 public async Task<PagedResult<RequisicaoResumo>> ListarAsync(Guid t,int pagina,int tamanho,CancellationToken ct){var p=Math.Max(1,pagina);var s=Math.Clamp(tamanho,1,100);const string q="select count(*) from sigov.compras_empresarial_requisicao where tenant_id=@t and not is_deleted;select r.id,r.numero,r.status,r.valor_estimado ValorEstimado,r.data_necessaria DataNecessaria,count(i.id)::int Itens,r.version from sigov.compras_empresarial_requisicao r left join sigov.compras_empresarial_requisicao_item i on i.tenant_id=r.tenant_id and i.requisicao_id=r.id and not i.is_deleted where r.tenant_id=@t and not r.is_deleted group by r.id order by r.created_at desc offset @off limit @s";await using var c=factory.CreateConnection();using var m=await c.QueryMultipleAsync(new CommandDefinition(q,new{t,off=(p-1)*s,s},cancellationToken:ct));var n=await m.ReadSingleAsync<long>();return new((await m.ReadAsync<RequisicaoResumo>()).AsList(),p,s,n);}
 public async Task<Guid> CriarAsync(ComprasContext x,CriarRequisicaoRequest r,string key,CancellationToken ct){await using var c=factory.CreateConnection();await c.OpenAsync(ct);await using var tx=await c.BeginTransactionAsync(ct);var old=await c.ExecuteScalarAsync<Guid?>(new CommandDefinition("select recurso_id from sigov.compras_empresarial_idempotencia where tenant_id=@t and operacao='REQUISICAO_CRIAR' and chave=@key",new{t=x.TenantId,key},tx,cancellationToken:ct));if(old.HasValue){await tx.CommitAsync(ct);return old.Value;}var id=Guid.NewGuid();var numero=await FornecedorRepository.Next(c,tx,x.TenantId,"REQUISICAO","RC",ct);var total=r.Itens.Sum(i=>i.Quantidade*i.ValorEstimado);const string head="insert into sigov.compras_empresarial_requisicao(id,tenant_id,numero,solicitante_id,setor,centro_custo_id,projeto_id,contrato_id,ordem_servico_id,almoxarifado_id,urgencia,data_necessaria,justificativa,observacoes,valor_estimado,created_by,updated_by,correlation_id) values(@id,@t,@numero,@usId,@Setor,@CentroCustoId,@ProjetoId,@ContratoId,@OrdemServicoId,@AlmoxarifadoId,upper(@Urgencia),@DataNecessaria,@Justificativa,@Observacoes,@total,@us,@us,@corr)";await c.ExecuteAsync(new CommandDefinition(head,new{id,t=x.TenantId,numero,usId=x.UsuarioId,r.Setor,r.CentroCustoId,r.ProjetoId,r.ContratoId,r.OrdemServicoId,r.AlmoxarifadoId,r.Urgencia,r.DataNecessaria,r.Justificativa,r.Observacoes,total,us=x.UsuarioId.ToString(),corr=x.CorrelationId},tx,cancellationToken:ct));var ordem=0;foreach(var item in r.Itens){ordem++;await c.ExecuteAsync(new CommandDefinition("insert into sigov.compras_empresarial_requisicao_item(tenant_id,requisicao_id,ordem,tipo,descricao,especificacao,unidade,quantidade,valor_estimado,permite_parcial,exige_inspecao,created_by,updated_by,correlation_id) values(@t,@id,@ordem,upper(@Tipo),@Descricao,@Especificacao,@Unidade,@Quantidade,@ValorEstimado,@PermiteParcial,@ExigeInspecao,@us,@us,@corr)",new{t=x.TenantId,id,ordem,item.Tipo,item.Descricao,item.Especificacao,item.Unidade,item.Quantidade,item.ValorEstimado,item.PermiteParcial,item.ExigeInspecao,us=x.UsuarioId.ToString(),corr=x.CorrelationId},tx,cancellationToken:ct));}await c.ExecuteAsync(new CommandDefinition("insert into sigov.compras_empresarial_historico(tenant_id,aggregate_type,aggregate_id,acao,created_by,correlation_id) values(@t,'REQUISICAO',@id,'RASCUNHO_CRIADO',@us,@corr);insert into sigov.compras_empresarial_idempotencia(tenant_id,operacao,chave,recurso_id) values(@t,'REQUISICAO_CRIAR',@key,@id)",new{t=x.TenantId,id,key,us=x.UsuarioId.ToString(),corr=x.CorrelationId},tx,cancellationToken:ct));await tx.CommitAsync(ct);return id;}
 public async Task EnviarAsync(ComprasContext x,Guid id,long version,CancellationToken ct){await using var c=factory.CreateConnection();const string q="update sigov.compras_empresarial_requisicao r set status='PENDENTE_APROVACAO',version=version+1,updated_at=now(),updated_by=@us,correlation_id=@corr where tenant_id=@t and id=@id and version=@version and status='RASCUNHO' and exists(select 1 from sigov.compras_empresarial_requisicao_item i where i.tenant_id=r.tenant_id and i.requisicao_id=r.id and not i.is_deleted)";var n=await c.ExecuteAsync(new CommandDefinition(q,new{t=x.TenantId,id,version,us=x.UsuarioId.ToString(),corr=x.CorrelationId},cancellationToken:ct));if(n!=1)throw new InvalidOperationException("Requisição sem itens, fora de rascunho ou versão desatualizada.");}
}
public sealed class ComprasDashboardRepository(NpgsqlConnectionFactory factory):IComprasDashboardRepository
{public async Task<ComprasDashboard> ObterAsync(Guid t,CancellationToken ct){const string q="select coalesce(sum(valor_estimado),0) TotalSolicitado,coalesce(sum(valor_estimado) filter(where status in('APROVADA','EM_COTACAO','PEDIDA','RECEBIDA','ENCERRADA')),0) ValorAprovado,(select count(*) from sigov.compras_empresarial_aprovacao where tenant_id=@t and status='PENDENTE')::int AprovacoesPendentes,(select count(*) from sigov.compras_empresarial_cotacao where tenant_id=@t and status in('ABERTA','EM_RESPOSTA'))::int CotacoesAbertas,(select count(*) from sigov.compras_empresarial_pedido where tenant_id=@t and previsao<current_date and status not in('RECEBIDO','ENCERRADO','CANCELADO'))::int PedidosAtrasados,(select count(*) from sigov.compras_empresarial_pedido where tenant_id=@t and status in('CONFIRMADO','PARCIALMENTE_RECEBIDO'))::int RecebimentosPendentes,(select count(*) from sigov.compras_empresarial_fatura where tenant_id=@t and status='BLOQUEADA')::int FaturasBloqueadas,(select count(*) from sigov.compras_empresarial_fornecedor_documento where tenant_id=@t and validade between current_date and current_date+30 and not is_deleted)::int DocumentosVencendo from sigov.compras_empresarial_requisicao where tenant_id=@t and not is_deleted";await using var c=factory.CreateConnection();return await c.QuerySingleAsync<ComprasDashboard>(new CommandDefinition(q,new{t},cancellationToken:ct));}}
