using System.Security.Cryptography;
using System.Text;
using Dapper;
using Npgsql;
using Sigov.Application.Common;
using Sigov.Application.ComprasEmpresariais;
using Sigov.Infrastructure.Persistence.Dapper;

namespace Sigov.Infrastructure.ComprasEmpresariais;

public sealed class DivergenciaRecebimentoRepository(NpgsqlConnectionFactory factory):IDivergenciaRecebimentoRepository
{
 public async Task<CentralDivergencias> ListarAsync(Guid tenant,DivergenciaFiltro f,CancellationToken ct)
 {
  const string where=@"d.tenant_id=@tenant and (@recebimento is null or d.recebimento_id=@recebimento) and (@fornecedor is null or coalesce(fo.nome_fantasia,fo.razao_social) ilike @fornecedor) and (@produto is null or pr.nome ilike @produto) and (@situacao is null or d.situacao=@situacao) and (@responsavel is null or d.responsavel_id=@responsavel) and (not @naoAtribuidas or d.responsavel_id is null) and (@ai is null or d.created_at>=@ai) and (@af is null or d.created_at<(@af::date+1)) and (@ei is null or d.encerrada_em>=@ei) and (@ef is null or d.encerrada_em<(@ef::date+1))";
  var sql=$@"select count(*) from sigov.compras_empresarial_recebimento_divergencia d join sigov.compras_empresarial_recebimento r on (r.tenant_id,r.id)=(d.tenant_id,d.recebimento_id) join sigov.compras_empresarial_recebimento_item ri on (ri.tenant_id,ri.id)=(d.tenant_id,d.recebimento_item_id) join sigov.compras_empresarial_pedido p on (p.tenant_id,p.id)=(r.tenant_id,r.pedido_id) join sigov.compras_empresarial_fornecedor fo on (fo.tenant_id,fo.id)=(p.tenant_id,p.fornecedor_id) join sigov.estoque_produto pr on (pr.tenant_id,pr.id)=(ri.tenant_id,ri.produto_id) where {where};
select d.id,d.recebimento_id RecebimentoId,r.documento,p.numero PedidoNumero,coalesce(fo.nome_fantasia,fo.razao_social) Fornecedor,pr.nome Produto,pr.unidade,d.quantidade_rejeitada QuantidadeRejeitada,d.motivo,d.situacao,d.responsavel_id ResponsavelId,t.nome ResponsavelNome,d.created_at AbertaEm,d.encerrada_em EncerradaEm,d.providencia,d.resultado,d.version from sigov.compras_empresarial_recebimento_divergencia d join sigov.compras_empresarial_recebimento r on (r.tenant_id,r.id)=(d.tenant_id,d.recebimento_id) join sigov.compras_empresarial_recebimento_item ri on (ri.tenant_id,ri.id)=(d.tenant_id,d.recebimento_item_id) join sigov.compras_empresarial_pedido p on (p.tenant_id,p.id)=(r.tenant_id,r.pedido_id) join sigov.compras_empresarial_fornecedor fo on (fo.tenant_id,fo.id)=(p.tenant_id,p.fornecedor_id) join sigov.estoque_produto pr on (pr.tenant_id,pr.id)=(ri.tenant_id,ri.produto_id) left join sigov.os_tecnico t on (t.tenant_id,t.usuario_id)=(d.tenant_id,d.responsavel_id) and not t.is_deleted where {where} order by d.created_at desc,d.id desc offset @offset limit @size;
select count(*) Total,count(*) filter(where d.situacao='ABERTA') Abertas,count(*) filter(where d.situacao='EM_TRATAMENTO') EmTratamento,count(*) filter(where d.situacao='ENCERRADA') Encerradas,count(*) filter(where d.responsavel_id is null) NaoAtribuidas from sigov.compras_empresarial_recebimento_divergencia d join sigov.compras_empresarial_recebimento r on (r.tenant_id,r.id)=(d.tenant_id,d.recebimento_id) join sigov.compras_empresarial_recebimento_item ri on (ri.tenant_id,ri.id)=(d.tenant_id,d.recebimento_item_id) join sigov.compras_empresarial_pedido p on (p.tenant_id,p.id)=(r.tenant_id,r.pedido_id) join sigov.compras_empresarial_fornecedor fo on (fo.tenant_id,fo.id)=(p.tenant_id,p.fornecedor_id) join sigov.estoque_produto pr on (pr.tenant_id,pr.id)=(ri.tenant_id,ri.produto_id) where {where}";
  var size=Math.Clamp(f.Tamanho,1,100);var page=Math.Max(f.Pagina,1);var a=new{tenant,recebimento=f.RecebimentoId,fornecedor=Like(f.Fornecedor),produto=Like(f.Produto),situacao=Clean(f.Situacao),responsavel=f.ResponsavelId,naoAtribuidas=f.NaoAtribuidas,ai=f.AberturaInicial,af=f.AberturaFinal,ei=f.EncerramentoInicial,ef=f.EncerramentoFinal,offset=(page-1)*size,size};
  await using var c=factory.CreateConnection();using var m=await c.QueryMultipleAsync(new CommandDefinition(sql,a,cancellationToken:ct));var total=await m.ReadSingleAsync<long>();var rows=(await m.ReadAsync<DivergenciaResumo>()).AsList();var totals=await m.ReadSingleAsync<DivergenciaTotais>();return new(new PagedResult<DivergenciaResumo>(rows,page,size,total),totals);
 }
 public async Task<DivergenciaDetalhe?> ObterAsync(Guid tenant,long id,CancellationToken ct)
 {
  const string sql=@"select d.id,d.recebimento_id RecebimentoId,d.recebimento_item_id RecebimentoItemId,r.documento,p.numero PedidoNumero,coalesce(fo.nome_fantasia,fo.razao_social) Fornecedor,pr.nome Produto,pr.unidade,d.quantidade_rejeitada QuantidadeRejeitada,d.motivo,d.situacao,d.responsavel_id ResponsavelId,t.nome ResponsavelNome,d.providencia,d.resultado,d.justificativa_encerramento JustificativaEncerramento,d.created_at AbertaEm,d.encerrada_em EncerradaEm,d.version from sigov.compras_empresarial_recebimento_divergencia d join sigov.compras_empresarial_recebimento r on (r.tenant_id,r.id)=(d.tenant_id,d.recebimento_id) join sigov.compras_empresarial_recebimento_item ri on (ri.tenant_id,ri.id)=(d.tenant_id,d.recebimento_item_id) join sigov.compras_empresarial_pedido p on (p.tenant_id,p.id)=(r.tenant_id,r.pedido_id) join sigov.compras_empresarial_fornecedor fo on (fo.tenant_id,fo.id)=(p.tenant_id,p.fornecedor_id) join sigov.estoque_produto pr on (pr.tenant_id,pr.id)=(ri.tenant_id,ri.produto_id) left join sigov.os_tecnico t on (t.tenant_id,t.usuario_id)=(d.tenant_id,d.responsavel_id) and not t.is_deleted where d.tenant_id=@tenant and d.id=@id;
select e.id,e.tipo,e.detalhes->>'descricao' Descricao,e.detalhes->>'providencia' Providencia,e.detalhes->>'resultado' Resultado,e.detalhes->>'justificativa' Justificativa,e.detalhes->>'responsavel_anterior' ResponsavelAnterior,e.detalhes->>'responsavel_novo' ResponsavelNovo,e.usuario_id UsuarioId,coalesce(t.nome,e.usuario_id::text) Autor,e.ocorrido_em OcorridoEm,e.correlation_id CorrelationId from sigov.compras_empresarial_recebimento_divergencia_evento e left join sigov.os_tecnico t on (t.tenant_id,t.usuario_id)=(e.tenant_id,e.usuario_id) and not t.is_deleted where e.tenant_id=@tenant and e.divergencia_id=@id order by e.ocorrido_em,e.id";
  await using var c=factory.CreateConnection();using var m=await c.QueryMultipleAsync(new CommandDefinition(sql,new{tenant,id},cancellationToken:ct));var h=await m.ReadSingleOrDefaultAsync<DetailRow>();if(h is null)return null;return new(h.Id,h.RecebimentoId,h.RecebimentoItemId,h.Documento,h.PedidoNumero,h.Fornecedor,h.Produto,h.Unidade,h.QuantidadeRejeitada,h.Motivo,h.Situacao,h.ResponsavelId,h.ResponsavelNome,h.Providencia,h.Resultado,h.JustificativaEncerramento,h.AbertaEm,h.EncerradaEm,h.Version,(await m.ReadAsync<DivergenciaEvento>()).AsList());
 }
 public async Task<IReadOnlyList<ResponsavelDivergencia>> PesquisarResponsaveisAsync(Guid tenant,string? busca,int pagina,int tamanho,CancellationToken ct)
 {const string sql="select usuario_id UsuarioId,nome,especialidade Vinculo,coalesce(regiao,e.nome) Unidade from sigov.os_tecnico t left join sigov.os_equipe e on e.tenant_id=t.tenant_id and e.id=t.equipe_id where t.tenant_id=@tenant and not t.is_deleted and t.status in('DISPONIVEL','EM_ATENDIMENTO') and (@term is null or t.nome ilike @term) order by t.nome,t.usuario_id offset @offset limit @tamanho";await using var c=factory.CreateConnection();return (await c.QueryAsync<ResponsavelDivergencia>(new CommandDefinition(sql,new{tenant,term=Like(busca),offset=(pagina-1)*tamanho,tamanho},cancellationToken:ct))).AsList();}
 public Task<DivergenciaComandoResultado> AtribuirAsync(ComprasContext c,long id,AtribuirDivergenciaRequest r,CancellationToken ct)=>Execute(c,id,"ATRIBUIR",r.IdempotencyKey,r.Version,new{r.ResponsavelId},async(cn,tx,row)=>{if(row.Situacao=="ENCERRADA")throw new InvalidOperationException("Divergência encerrada é somente consulta.");if(!await cn.ExecuteScalarAsync<bool>(new CommandDefinition("select exists(select 1 from sigov.os_tecnico where tenant_id=@tenant and usuario_id=@responsavel and not is_deleted and status in('DISPONIVEL','EM_ATENDIMENTO'))",new{tenant=c.TenantId,responsavel=r.ResponsavelId},tx,cancellationToken:ct)))throw new InvalidOperationException("O responsável não está ativo e elegível no contexto autorizado.");await Update(cn,tx,c,id,r.Version,"situacao='EM_TRATAMENTO',responsavel_id=@responsavel",new{responsavel=r.ResponsavelId},ct);await Event(cn,tx,c,id,"RESPONSAVEL_ATRIBUIDO",new{responsavel_anterior=row.ResponsavelId,responsavel_novo=r.ResponsavelId},ct);return false;},ct);
 public Task<DivergenciaComandoResultado> RegistrarAndamentoAsync(ComprasContext c,long id,RegistrarAndamentoDivergenciaRequest r,CancellationToken ct)=>Execute(c,id,"ANDAMENTO",r.IdempotencyKey,r.Version,new{r.Descricao,r.Providencia},async(cn,tx,row)=>{if(row.Situacao!="EM_TRATAMENTO")throw new InvalidOperationException("Somente divergência em tratamento aceita andamento.");await Update(cn,tx,c,id,r.Version,"providencia=coalesce(@providencia,providencia),andamento=@descricao",new{descricao=r.Descricao,providencia=r.Providencia},ct);await Event(cn,tx,c,id,"ANDAMENTO_REGISTRADO",new{descricao=r.Descricao,providencia=r.Providencia},ct);return false;},ct);
 public Task<DivergenciaComandoResultado> EncerrarAsync(ComprasContext c,long id,EncerrarDivergenciaRequest r,CancellationToken ct)=>Execute(c,id,"ENCERRAR",r.IdempotencyKey,r.Version,new{r.Resultado,r.Justificativa},async(cn,tx,row)=>{if(row.Situacao!="EM_TRATAMENTO")throw new InvalidOperationException("Somente divergência em tratamento pode ser encerrada.");await Update(cn,tx,c,id,r.Version,"situacao='ENCERRADA',resultado=@resultado,justificativa_encerramento=@justificativa,encerrada_em=now()",new{resultado=r.Resultado,justificativa=r.Justificativa},ct);await Event(cn,tx,c,id,"ENCERRADA",new{resultado=r.Resultado,justificativa=r.Justificativa},ct);var remaining=await cn.ExecuteScalarAsync<bool>(new CommandDefinition("select exists(select 1 from sigov.compras_empresarial_recebimento_divergencia where tenant_id=@tenant and recebimento_id=@recebimento and situacao<>'ENCERRADA')",new{tenant=c.TenantId,recebimento=row.RecebimentoId},tx,cancellationToken:ct));if(remaining)return false;const string close=@"with atualizada as (update sigov.pendencia_operacional p set status='RESOLVIDA',resolved_at=now(),updated_at=now(),versao=versao+1 from sigov.enterprise_tenant_mapping m where m.enterprise_tenant_id=@tenant and m.ativo and p.tenant_id=m.core_tenant_id and p.modulo='COMPRAS_EMPRESARIAIS' and p.tipo='TRATAMENTO_DIVERGENCIA' and p.entidade_id=@recebimento::text and p.status in('ABERTA','EM_TRATAMENTO') returning p.id,p.tenant_id,p.versao) insert into sigov.governanca_ocorrencia_historico(tenant_id,ocorrencia_tipo,ocorrencia_id,evento,usuario_id,justificativa,dados_depois) select tenant_id,'PENDENCIA',id,'RESOLVIDA_NA_ORIGEM',@usuario,@justificativa,jsonb_build_object('recebimento_id',@recebimento,'versao',versao) from atualizada";var closed=await cn.ExecuteAsync(new CommandDefinition(close,new{tenant=c.TenantId,recebimento=row.RecebimentoId,usuario=c.UsuarioId,justificativa=r.Justificativa},tx,cancellationToken:ct));if(closed>1)throw new InvalidOperationException("Mais de uma pendência agregada ativa foi encontrada.");return closed==1;},ct);

 private async Task<DivergenciaComandoResultado> Execute(ComprasContext context,long id,string operation,string key,long version,object payload,Func<NpgsqlConnection,NpgsqlTransaction,LockRow,Task<bool>> body,CancellationToken ct)
 {await using var cn=factory.CreateConnection();await cn.OpenAsync(ct);await using var tx=await cn.BeginTransactionAsync(ct);var hash=HashV2(new{id,version,payload});var legacyPayload=string.Join("|",payload.GetType().GetProperties().Select(p=>p.GetValue(payload)?.ToString()??string.Empty));var legacyHash=Hash($"{id}|{version}|{legacyPayload}");
  await cn.ExecuteAsync(new CommandDefinition("select pg_advisory_xact_lock(hashtextextended(@lock,0))",new{lock=$"{context.TenantId:D}|DIVERGENCIA|{operation}|{key}"},tx,cancellationToken:ct));
  var previous=await cn.QuerySingleOrDefaultAsync<IdemRow>(new CommandDefinition("select request_hash RequestHash,situacao,version,pendencia_concluida PendenciaConcluida from sigov.compras_empresarial_divergencia_idempotencia where tenant_id=@tenant and operacao=@operation and chave=@key",new{tenant=context.TenantId,operation,key},tx,cancellationToken:ct));if(previous is not null){if(previous.RequestHash!=hash&&previous.RequestHash!=legacyHash)throw new ComprasConcurrencyException("A chave de idempotência já foi usada com dados diferentes.");await tx.CommitAsync(ct);return new(id,previous.Situacao,previous.Version,true,previous.PendenciaConcluida);}
  var recebimento=await cn.ExecuteScalarAsync<Guid?>(new CommandDefinition("select recebimento_id from sigov.compras_empresarial_recebimento_divergencia where tenant_id=@tenant and id=@id",new{tenant=context.TenantId,id},tx,cancellationToken:ct));if(!recebimento.HasValue)throw new InvalidOperationException("Divergência não encontrada no contexto autorizado.");
  await cn.QuerySingleAsync<Guid>(new CommandDefinition("select id from sigov.compras_empresarial_recebimento where tenant_id=@tenant and id=@recebimento for update",new{tenant=context.TenantId,recebimento},tx,cancellationToken:ct));
  var row=await cn.QuerySingleOrDefaultAsync<LockRow>(new CommandDefinition("select id,recebimento_id RecebimentoId,situacao,version,responsavel_id ResponsavelId from sigov.compras_empresarial_recebimento_divergencia where tenant_id=@tenant and id=@id for update",new{tenant=context.TenantId,id},tx,cancellationToken:ct));if(row is null)throw new InvalidOperationException("Divergência não encontrada no contexto autorizado.");
  await cn.ExecuteAsync(new CommandDefinition("select id from sigov.compras_empresarial_recebimento_divergencia where tenant_id=@tenant and recebimento_id=@recebimento order by id for update",new{tenant=context.TenantId,recebimento},tx,cancellationToken:ct));
  if(row.Version!=version)throw new ComprasConcurrencyException("A divergência foi alterada. Revise o estado atual antes de uma nova tentativa.");var closed=await body(cn,tx,row);var persisted=await cn.QuerySingleAsync<LockRow>(new CommandDefinition("select id,recebimento_id RecebimentoId,situacao,version,responsavel_id ResponsavelId from sigov.compras_empresarial_recebimento_divergencia where tenant_id=@tenant and id=@id",new{tenant=context.TenantId,id},tx,cancellationToken:ct));await cn.ExecuteAsync(new CommandDefinition("insert into sigov.compras_empresarial_divergencia_idempotencia(tenant_id,operacao,chave,request_hash,divergencia_id,situacao,version,pendencia_concluida) values(@tenant,@operation,@key,@hash,@id,@situacao,@version,@closed)",new{tenant=context.TenantId,operation,key,hash,id,situacao=persisted.Situacao,version=persisted.Version,closed},tx,cancellationToken:ct));await tx.CommitAsync(ct);return new(id,persisted.Situacao,persisted.Version,false,closed);}
 private static async Task Update(NpgsqlConnection cn,NpgsqlTransaction tx,ComprasContext c,long id,long version,string set,object values,CancellationToken ct){var p=new DynamicParameters(values);p.Add("tenant",c.TenantId);p.Add("id",id);p.Add("version",version);p.Add("user",c.UsuarioId.ToString());p.Add("corr",c.CorrelationId);if(await cn.ExecuteAsync(new CommandDefinition($"update sigov.compras_empresarial_recebimento_divergencia set {set},version=version+1,updated_at=now(),updated_by=@user,correlation_id=@corr where tenant_id=@tenant and id=@id and version=@version",p,tx,cancellationToken:ct))!=1)throw new ComprasConcurrencyException("A divergência foi alterada. Revise o estado atual antes de uma nova tentativa.");}
 private static Task<int> Event(NpgsqlConnection cn,NpgsqlTransaction tx,ComprasContext c,long id,string type,object details,CancellationToken ct)=>cn.ExecuteAsync(new CommandDefinition("insert into sigov.compras_empresarial_recebimento_divergencia_evento(tenant_id,divergencia_id,tipo,detalhes,usuario_id,correlation_id) values(@tenant,@id,@type,@details::jsonb,@user,@corr)",new{tenant=c.TenantId,id,type,details=System.Text.Json.JsonSerializer.Serialize(details),user=c.UsuarioId,corr=c.CorrelationId},tx,cancellationToken:ct));
 private static string HashV2(object value)=>"v2:"+Convert.ToHexString(SHA256.HashData(System.Text.Json.JsonSerializer.SerializeToUtf8Bytes(value))).ToLowerInvariant();private static string Hash(string value)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(value))).ToLowerInvariant();private static string? Clean(string? x)=>string.IsNullOrWhiteSpace(x)?null:x.Trim();private static string? Like(string? x)=>string.IsNullOrWhiteSpace(x)?null:$"%{x.Trim()}%";
 private sealed record DetailRow(long Id,Guid RecebimentoId,long RecebimentoItemId,string Documento,string PedidoNumero,string Fornecedor,string Produto,string Unidade,decimal QuantidadeRejeitada,string Motivo,string Situacao,Guid? ResponsavelId,string? ResponsavelNome,string? Providencia,string? Resultado,string? JustificativaEncerramento,DateTimeOffset AbertaEm,DateTimeOffset? EncerradaEm,long Version);
 private sealed record LockRow(long Id,Guid RecebimentoId,string Situacao,long Version,Guid? ResponsavelId);private sealed record IdemRow(string RequestHash,string Situacao,long Version,bool PendenciaConcluida);
}
